### ISSUE TITLE
dynamo打开只有连线不显示节点！

### ISSUE THREAD

**Issue by mm239231213** [DynamoDS/Dynamo#10010]
打开dynamo后项目不显示节点只显示连线，重装软件后还是无效。
![QQ截图20190926112341](https://user-images.githubusercontent.com/55822285/65656202-8f243b80-e051-11e9-9045-3e5cdac686af.png)

**Comment by mm239231213** [comment]
使用的是revit2017版本

**Comment by beichengyuxia** [comment]
哈哈，我也遇到过，后来发现删掉springnet插件就好了，很奇怪，突然有一天就出现了，和revit别的有冲突了。

**Comment by QilongTang** [comment]
@mm239231213 如果先删除所有的Dynamo package 问题还有吗

**Comment by Amoursol** [comment]
Hello @mm239231213,

Please let us know if this problem persists. We will be closing this issue in lieu of getting more information.
