### ISSUE TITLE
Crash report from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by caddguru** [DynamoDS/Dynamo#10023]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)
was experimenting with adding wall families
### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by mjkkirschner** [comment]
Hi @caddguru this is not enough info to be actionable, is it possible to add your files or detailed repro steps?

**Comment by Amoursol** [comment]
Closing this issue as there has been a request for more information made and no traction for longer than 2 weeks. Please re-open if you are still seeing this issue and provide detailed reproduction steps.
