### ISSUE TITLE
Sandbox: Search return no results

### ISSUE THREAD

**Issue by MatiasArguello94** [DynamoDS/Dynamo#10030]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.3.8810

## Operating system
windows 10

## What did you do? 

search packages

## What did you expect to see?

results

## What did you see instead?

" Search return no results"

**Comment by MatiasArguello94** [comment]
Hi, i open a new issue abot this because other where refered to dynamo for revit.
In my case, Dynamo for revit(both 1.3.4 and 2.0.3) throws results and even Sandbox 1.3.4 works.
Only Sandbox 2.0.3 return no results. i already check the firewall, and just in case, updated my revit versions.

**Comment by mjkkirschner** [comment]
Hi @MatiasArguello94 - this is very very likely a TLS issue - please update revit to the version specified here:
https://knowledge.autodesk.com/support/revit-products/downloads/caas/downloads/content/autodesk-transport-layer-security-updates-require-revit-security-fix.html

**Comment by mjkkirschner** [comment]
ah, for sandbox 2.0.3. you can make this change to the `DynamoSandbox.exe.config`
```
<runtime>
    <AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>
  </runtime>
```

but I would advise just using a newer Dynamo Sandbox.

**Comment by MatiasArguello94** [comment]
i already updated my revit 2019 from de autodek desktop manager.
i used 2.0 so i could investigate Refinery, wich i thinks it is no avaible for newer versions.
the "DynamoSandbox.exe.config", should i open it with visual studio? is there other way to do that?

**Comment by mjkkirschner** [comment]
it's just a text file so notepad will do.

**Comment by MatiasArguello94** [comment]
thanks. but i dont undestand what should i do. Add those lines? i cant find them in the text as it is now

**Comment by mjkkirschner** [comment]
there will be an existing 
```<runtime> 
</runtime>```

section - you can add
`    <AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>`

between the two `runtime` tags.

**Comment by MatiasArguello94** [comment]
THANK YOU! very much, u made my day.
Goodbye!
