### ISSUE TITLE
Major Crash - No Save Options - Placed a node inside itself on Accident

### ISSUE THREAD

**Issue by EmCru** [DynamoDS/Dynamo#10049]
Poof - its gone!
Dynamo version 2.0.2
windows 10 OS

I accidentally placed a node inside itself and both dynamo and Revit terminated without a chance to save my work in either program.  I knew that this is not a good idea but I did not mean to do it.

**Comment by Amoursol** [comment]
Hello Emmett,

To confirm - you created a **custom node** and then attempted to put that same custom node inside itself?

**Comment by EmCru** [comment]
yes exactly.  I was just moving too fast, I know that I should do that.
Regards,
Emmett Cruey
*ConnectedBIM.io* <http://connectedbim.io>
AEC Technology Consultant
*mobile: 925.695.6000*

**Comment by mjkkirschner** [comment]
Hi @EmCru thanks for reporting this, unfortunately knowing if a recursive workflow is going to result in an infinite loop is a very complex problem.

We'll monitor the occurrence of this in the future and determine if it makes sense to put in some kind of warning when a user adds a node to its own definition.
