### ISSUE TITLE
Dynamo has stopped working. while executing python loop.

### ISSUE THREAD

**Issue by MarcinTata** [DynamoDS/Dynamo#10043]
## Dynamo version

1.3.3.4651

## Operating system

Windows 7

## What did you do? 

Executed python script 

## What did you expect to see?

output list

## What did you see instead?

Windows's pop-up crash window.

DESCRIPTION
I have a point cloud. I try to find points on the edge of the cloud.
The algorithm written in Python creates a sphere, move the sphere and check for intersection.

Problem is with assigning **0** to '**stoper**' value in **for loop**. The strange thing is it works **sometimes**.  When I  exclude stoper operation, the script does not crash Dynamo.
![stoppedWorkind](https://user-images.githubusercontent.com/38285902/66458083-1f12ae00-ea72-11e9-86b0-8d28f1dfc989.JPG)
![stoppedWorkingScript](https://user-images.githubusercontent.com/38285902/66458090-246ff880-ea72-11e9-89e0-423a0a5b7b24.JPG)

**Comment by mjkkirschner** [comment]
you need to follow the advise here:
https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#dispose--using-statement

in master (2.5) this should no longer be required - but if you are in 1.3.3 it will be.

**Comment by mjkkirschner** [comment]
please reopen if following this disposal pattern does not help.
