### ISSUE TITLE
Background 3d preview not available

### ISSUE THREAD

**Issue by jli113** [DynamoDS/Dynamo#10063]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo core 2.4.0.6186

## Operating system

Win 10 18362, 64

## What did you do? 

To use Dynamo

## What did you expect to see?

Default background 3d preview 

## What did you see instead?

Background 3d preview is gray in Dynamo from Revit 2020, has the same problem when opening DynamoSandbox from Dynamo Core 2.4.0.6186.
I only have an RX5700XT GPU card using Win 10 18362, tried many methods, no use.

**Comment by jli113** [comment]
Solved by reinstalling DirectX

**Comment by mjkkirschner** [comment]
@jli113 could add a bit more info here on what you did to resolve this? Where did you install directX from? What version?

**Comment by jli113** [comment]
reinstalled directX from this wiki https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by cuiningdan** [comment]
My computer version is win10 1709, it does not have graphics settings, how to solve the problem of dynamo default background preview
