### ISSUE TITLE
Crash report from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by maxxliamblake** [DynamoDS/Dynamo#10060]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Checked NVIDIA and DirectX Graphic Card Drivers were up to date because Default Background Preview is greyed out

### What did you expect to see?
Default Background Preview

### What did you see instead?
Nothing - option to activate Default Background Preview is still greyed out

### What packages or external references (if any) were used?
Dynamo. Revit

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.17763.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by mjkkirschner** [comment]
try installing this set of dx installers:
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by maxxliamblake** [comment]
Thanks,

and then what?

I know have a large number of .cab files?

Thanks,


Mit freundlichen Grüßen

With kind regards

Max Blake

+49 (0) 176 7715 0749



Am Sa., 19. Okt. 2019 um 19:27 Uhr schrieb Michael Kirschner <
notifications@github.com>:

**Comment by mjkkirschner** [comment]
Hi @maxxliamblake - theres a setup.exe that will be extracted as well - run that.

**Comment by maxxliamblake** [comment]
Done! Works!

Thanks a million


Mit freundlichen Grüßen

With kind regards

Max Blake

+49 (0) 176 7715 0749



Am Mi., 23. Okt. 2019 um 16:54 Uhr schrieb Michael Kirschner <
notifications@github.com>:
