### ISSUE TITLE
Dynamo 2.0.3 - Save

### ISSUE THREAD

**Issue by Bobidou** [DynamoDS/Dynamo#10084]
Dynamo doesn't save Number or Number Slider. When I open un file .dyn they disappear.
Can you help me ?

Thanks

**Comment by Amoursol** [comment]
Hello @Bobidou,

Can you please provide the following information?
1. The version of Dynamo you are using (i.e 2.0.3)
2. The location of Dynamo (i.e Revit, Civil 3d, Sandbox)
3. Any error message that pops-up when this happens

If you can also provide the .dyn file that would also be helpful!

**Comment by mjkkirschner** [comment]
Hi @Bobidou - usually caused by an addin conflict in Revit - if you are using pyRevit please try updating to their latest version.

**Comment by mjkkirschner** [comment]
Some addin or package is causing a conflict when loading dlls - this has been hardened in newer versions of Dynamo, but for 2.0.3 you'll need to track down which .addin it is on your system by removing them in batches etc.

Please reopen if that does not turn out to be the cause.
