### ISSUE TITLE
Dynamo Cloud rendering (2.0.3 with revit 2019)

### ISSUE THREAD

**Issue by Saifou** [DynamoDS/Dynamo#10093]
Hi i have an issue trying to cloud rende my dynamo model

Can you help me? thank you here is my script 

![test panorama](https://user-images.githubusercontent.com/34438713/67785983-676c2d00-fa6e-11e9-885f-1c4179c65e2b.PNG)

i try to make a panorama render with dynamo and exporting it. but there's an error at the end and i don't know how to fix it.

**Comment by Amoursol** [comment]
Hello @Saifou - Can you please provide a screenshot with the error message shown?

**Comment by Saifou** [comment]
Hi @Amoursol here's the screenshot
![Sans titr123e](https://user-images.githubusercontent.com/34438713/67848534-28d58180-fb05-11e9-9897-cc56f174c539.png)

**Comment by mjkkirschner** [comment]
the error makes it clear - the node is being passed a directoryObject but should be given a string( the directory path as a string of characters)

just get rid of the `Directory From Path` node.

**Comment by Saifou** [comment]
it fails ! :(

![Sans titre](https://user-images.githubusercontent.com/34438713/67959389-f2792e80-fbf8-11e9-9530-d173a2eb0df3.png)

**Comment by Amoursol** [comment]
Hello @Saifou -

Can you please tell me what **Custom Package** all of the Cloud Rendering workflows come from? This is not an out-of-the-box Revit package that we supply, and as such it has been created by a **community author**. 

The _Error Message_ here shows that the node is not accurately linking your Dynamo session to the Cloud Rendering Service: It's failing to check the price of the render as Cloud Rendering costs Cloud Credits.

**Comment by mjkkirschner** [comment]
I don't believe this functionality is supported any longer.
