### ISSUE TITLE
Dynamo 2.0.3 Library Freezes Constantly

### ISSUE THREAD

**Issue by OliverEGreen** [DynamoDS/Dynamo#10099]
## Dynamo version

v2.0.3

## Operating system
Windows 10

## What did you do? 
Generally using Dynamo, simple definitions with a range of popular packages e.g. Data-Shapes, Archi-Lab, etc.

## What did you expect to see?
The node library working as per normal

## What did you see instead?
The node library operates as normal when I first open Dynamo. After about 1-2 minutes of usage it will randomly freeze. I remain able to resize the library but not expand/contract the node package trees and I cannot use the search bar any longer. 

This bug is quite reliable and has happened a lot since I began testing Dynamo 2.X.

**Comment by mjkkirschner** [comment]
Hi @OliverEGreen - try disabling antivirus temporarily - do you have access to 2020 where you can try newer versions of Dynamo?

do you see the same issue with sandbox daily builds?

**Comment by waracana** [comment]
Same here, it keeps freezing. It starts behaving like this early in the session but although annoying you can get going OK, but after a while it just won't respond any more. thanks

**Comment by mjkkirschner** [comment]
Have not seen this reported for a while - closing for now, will reopen if  new reports arise.
