### ISSUE TITLE
Crash report from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by JoelvanHerwaarden** [DynamoDS/Dynamo#10103]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by Amoursol** [comment]
Hello @JoelvanHerwaarden,

Could you please provide a little more insight into what your problem is and any reproducible steps?

**Comment by mjkkirschner** [comment]
Hi @JoelvanHerwaarden - To address this issue we will need more information. Please re-open this issue when the required you have answered the questions in the issue template.
