### ISSUE TITLE
Dynamo 2.3.0.5885 + loads of packages crash - featuring Simplex

### ISSUE THREAD

**Issue by jmcouffin** [DynamoDS/Dynamo#10117]
# Issue Description
Crash right after startup

### What packages or external references (if any) were used?
Latest version of Monocle seems to have trouble @johnpierson unless it is another package interaction

### Stack Trace
```
Méthode introuvable : 'Dynamo.Graph.Nodes.NodeModel Dynamo.ViewModels.NodeViewModel.get_NodeLogic()'.

   à MonocleViewExtension.MonocleViewExtension.AddNodeLookup(Object sender, EventArgs e)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   à System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   à System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   à System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by jmcouffin** [comment]
uninstalling does the trick

**Comment by jmcouffin** [comment]
after uninstalling the package I got it to last a bit longer, it let me put a python node then crashed again

`La définition de connectionId a levé une exception.

   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel, PythonNode nodeModel, NodeView nodeView, WindowRect& windowRect)
   à PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   à PythonNodeModelsWpf.PythonNodeViewCustomization.view_MouseDown(Object sender, MouseButtonEventArgs e)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   à System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   à System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   à System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)`

**Comment by jmcouffin** [comment]
removing all the packages does the trick. but it is quite unpractical

**Comment by johnpierson** [comment]
Did you restart dynamo after installing the package?

**Comment by johnpierson** [comment]
You are using Dynamo runtime 2.3.0?

**Comment by johnpierson** [comment]
The fact that you are having crashes outside of monocle, tells me it might not be monocle.
 

Did you unzip the runtime with 7Zip?

**Comment by jmcouffin** [comment]
> Did you restart dynamo after installing the package?

yes

> You are using Dynamo Core runtime 2.3.0?

yes

> Also, need to know what other packages you have installed...

![image](https://user-images.githubusercontent.com/7872003/68325142-23f66c00-00c9-11ea-8532-8e87d71283af.png)

> With Dynamo core runtime monocle is running as expected for me. @jmcouffin
> The fact that you are having crashes outside of monocle, tells me it might not be monocle.
> Did you unzip the runtime with 7Zip?

yes, always do

**Comment by jmcouffin** [comment]
having just monocle works. changed the title.
Is there a way to have a better diagnosis from the stack while crashing
kind of hard to figure out which one is causing problems

**Comment by johnpierson** [comment]
What environment are you testing in? Just sandbox?

**Comment by jmcouffin** [comment]
yep, just sandbox is crashing

**Comment by jmcouffin** [comment]
painful but I got the one messing my dynamo: 
![image](https://user-images.githubusercontent.com/7872003/68326630-18f10b00-00cc-11ea-9c5a-70307fd8a18c.png)
just don't tell Marcello :), you know, his heart condition , also that might be the interaction of Simplex with another package
