### ISSUE TITLE
Dynamo 2.1 EnergyAnalysis Error  

### ISSUE THREAD

**Issue by jaaaaaaaamie** [DynamoDS/Dynamo#10112]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
2.107733
## Operating system
Windows
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
(Fill in here)
Implement EnergyAnalysisForDynamo nodes (LoadAnalysisResults)
## What did you expect to see?
Watch nodes to monitor the results 
(Fill in here)

## What did you see instead?
The remote server returned an error: (500) Internal Server Error.
Internal error, please report: Dereferencing a non-pointer.
(Fill in here)

**Comment by Amoursol** [comment]
Hello @jaaaaaaaamie,

Is this the package you are referring to?
![image](https://user-images.githubusercontent.com/12857357/68225271-2c15b500-ffbe-11e9-9af7-d15d01bb47c1.png)

If so this is a _custom package_ not owned nor maintained by the Dynamo Team and appears to have been last updated 37 months ago 😢 Chances are likely the package no longer conforms with Dynamo's APIs. 

Please reach out to the package author to see if they can help you resolve this problem.
