### ISSUE TITLE
Major BUG! Dynamo not saving backup of main file just the open custon node that has crashed the code

### ISSUE THREAD

**Issue by MattGaydon** [DynamoDS/Dynamo#10114]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo Core 2.1.0.7500
Dynamo Revit 21.0.7733

## Revit version

2020

## Operating system
Window 10

## What did you do? 

Crashed Dynamo

## What did you expect to see?

A back-up of the main file when i reopened it 

## What did you see instead?

The custom node with the name of the main file i had open when dynamo crashed even when i said not to save as i knew this would overwrite the main file as the custom node. And as such lose my original code.

See Longer comment here on the matter on the Dynamo forum.
https://forum.dynamobim.com/t/major-bug-dynamo-not-saving-backup-of-main-file-just-the-open-custon-node-that-has-crashed-the-code/42746

**Comment by QilongTang** [comment]
@MattGaydon Hello from Dynamo Team, we are addressing this issue in current sprint. Stay tuned.

**Comment by QilongTang** [comment]
@mjkkirschner Thank you for reminding me, this should be fixed by https://github.com/DynamoDS/Dynamo/pull/10119 in Dynamo 2.5.x. Closing.
