### ISSUE TITLE
Some nodes disappears in the Graph when I use Civil3D 2020 and Dynamo 2.1.1.7865 and Civil3D 2.1.1.896

### ISSUE THREAD

**Issue by peterhuau** [DynamoDS/Dynamo#10120]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.1.1.7865 and Civil3D 2.1.1.896

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

I made some nodes in Civil3D 2020 Dynamo, I saved it and next time when I open some nodes in this graph just disappears

## What did you expect to see?
I should see the whole graph which already finished and tested, run smoothly.

## What did you see instead?
 some nodes in this graph just disappears. waste me a few hours works. I did again and it happened again.

**Comment by QilongTang** [comment]
@Amoursol @DynamoDS/dynamo This issue happened for Civil3D users worth noticing.

**Comment by angelowang** [comment]
It's known issue and probably have been fixed in 2.4.1 (2020 update 1). @QilongTang

**Comment by QilongTang** [comment]
@angelowang Thanks, now I recall

**Comment by QilongTang** [comment]
@peterhuau Do you mind updating to Civil3D 2020 update 1? This bug should be addressed already. Closing.
