### ISSUE TITLE
Packages not available

### ISSUE THREAD

**Issue by Sami1984** [DynamoDS/Dynamo#10136]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1

## Operating system

 Windows10

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by Sami1984** [comment]
![image](https://user-images.githubusercontent.com/57906006/69061588-baa42080-0a19-11ea-91d5-a2e636f45784.png)

**Comment by mjkkirschner** [comment]
see the related issues here:
https://github.com/DynamoDS/Dynamo/issues/9896
