### ISSUE TITLE
## Dynamo 2.0 Revit 2018.3 Crashed in all Pcs

### ISSUE THREAD

**Issue by Vepc** [DynamoDS/Dynamo#10140]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Operating system

Windows 10 Pro

## What did you do? 

Trying to open any dynamo script, in both player and scripting ui

## What did you expect to see?

Dynamo to run in player or script ui

## What did you see instead?

Dynamo has crashed window, submit to github

**Comment by QilongTang** [comment]
@Vepc Do you mind providing more details to help our team digest this:
1. Are there any steps to reproduce or it is the case that DynamoRevit crashes right away after opening in any Revit project. 
2. Did Revit crash as well? 
3. Are there any packages or nodes you or your company deployed aside of vanila Dynamo? 
Our team would also be happy to receive gif or video about the crash. This will help us determine if this is a Dynamo issue or DynamoRevit issue.

**Comment by Vepc** [comment]
> @Vepc Do you mind providing more details to help our team digest this:
> 
> 1. Are there any steps to reproduce or it is the case that DynamoRevit crashes right away after opening in any Revit project.
> 2. Did Revit crash as well?
> 3. Are there any packages or nodes you or your company deployed aside of vanila Dynamo?
>    Our team would also be happy to receive gif or video about the crash. This will help us determine if this is a Dynamo issue or DynamoRevit issue.

Sorry for this late response:
1. Yes, there was no way to reproduce
2. Yes, Revit's ribbon was greyed out, there was nothing else editable once Revit Dynamo crashed
3. i) No. ii) Was attempting to create a video/gif however it worked normally after a system restart. 

(suspecting it was due to OS update the night before, however no knowledge how it could affect that)

**Comment by QilongTang** [comment]
@Vepc Thanks for coming back! I will close it for now until you find the crash coming back. Feel free to re-open this issue with it happens again. Thanks for reporting this to us, your pleasure of using Dynamo is most important to us

**Comment by Vepc** [comment]
Thanks!
