### ISSUE TITLE
Error not written to logs

### ISSUE THREAD

**Issue by erenturkm** [DynamoDS/Dynamo#10156]
## Dynamo version
Dynamo 2.4.1
## Operating system
Windows 10, 1903
## What did you do? 
I ran DynamoSandbox.exe, saw the UI.
I went to View/Show Console to bring up the console.
I was the following message
There was an error creating a background preview in Dynamo. This could be due to a lack of graphics resources on your machine. See the log for more information.
I went to the file system, opened debug.log, 
## What did you expect to see?
I expected to see further info on what API calls were made and see more detailed error information and return codes. 
## What did you see instead?
Nothing related to the mentioned error was provided.

**Comment by mjkkirschner** [comment]
you're looking at the wrong log - dynamo logs are in `%appData%/Dynamo` - debug.log is the CEF log.

**Comment by erenturkm** [comment]
I checked under %appdata%\Roaming\Dynamo\Dynamo Core\2.4\Logs and same result. There isnt any warnings or errors written to the log. 
1)  "See the logs" is misleading.
2) We need lot more info (probably with switches for increasing/decreasing log amount) to troubleshoot issues.

**Comment by mjkkirschner** [comment]
please attach your log if you wish, the error if it as I believe is only a single additional line, so it may be easy to miss.

**Comment by erenturkm** [comment]
mjkkirschner you are misreading. There is nothing to attach. Same information provided in console is written to the log whereas message states MORE INFORMATION. 
1) Any warning/Error messages should be tagged as such
2) The message is a catch all Exception, it has to dig deeper (stack trace, return codes etc) to provide much more detailed information so that we can collect what's going wrong.
