### ISSUE TITLE
Wrong DLL referenced

### ISSUE THREAD

**Issue by erenturkm** [DynamoDS/Dynamo#10157]
## Dynamo version
Dynamo 2.4.1
## Operating system
Windows 10, 1909
## What did you do? 
I ran DynamoSanbox.exe and saw the UI with 3D.
I went to View/Show Console, no error displayed.
I select "Circle.ByCenterPointRadius" and was placed on canvas.
## What did you expect to see?
I expected to see the box without errors.
## What did you see instead?
I saw the warning message on the box.
"Warning: Point.ByCoordinates operation failed. Could not load file or assembly 'file://<Omitted>\LibG.ProtoInterface.dll' or one of its dependencies. The system cannot find the file specified'
There was no extra information reported in debug.log.
Refrenced file was not in the reported directory.

**Comment by mjkkirschner** [comment]
please this thread for a bit more info:
https://github.com/DynamoDS/Dynamo/issues/10047

and this blurb:
https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#optional-components

the geometry library will only work if specific adsk products are installed, as it is not open source.

**Comment by erenturkm** [comment]
1 )We need a proper error messaging in the console AND logs stating this, having a file not found error is a horrible user experience. 
2) The need for ADSK products should be mentioned in Download page for Dynamo Sanbox since it states "Runs standalone from other Autodesk applications"

**Comment by mjkkirschner** [comment]
thanks @erenturkm - we have filed a task as a result of the referenced thread to improve the communication regarding the geometry library requirements.
