### ISSUE TITLE
Crash Dynamo 2.0.3 after "Node to code"

### ISSUE THREAD

**Issue by Prynka1995** [DynamoDS/Dynamo#10195]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.3

## Operating system

Windows 8.1,

## What did you do? 

https://aws1.discourse-cdn.com/business6/uploads/dynamobim/original/3X/d/3/d330e6c17187c27d7fb6c13963046d1177bda68e.gif

## What did you expect to see?

node to code

## What did you see instead?

object reference does not indicate an instance of an object

   â ProtoCore.Utils.CoreUtils.CreateNodeFromString(String name)
   â Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.CreateNodeFromShortName(String className, String qualifiedName)
   â Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.RewriteNodeWithShortName(IdentifierListNode node)
   â Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.VisitIdentifierListNode(IdentifierListNode node)
   â ProtoCore.SyntaxAnalysis.AstReplacer.VisitBinaryExpressionNode(BinaryExpressionNode node)
   â Dynamo.Engine.NodeToCode.NodeToCodeCompiler.ReplaceWithShortestQualifiedName(ClassTable classTable, IEnumerable`1 asts, ElementResolver resolver)
   â Dynamo.Graph.Workspaces.NodesToCodeExtensions.ConvertNodesToCodeInternal(WorkspaceModel workspace, EngineController engineController, INamingProvider namingProvider)
   â Dynamo.Models.DynamoModel.ConvertNodesToCodeImpl(ConvertNodesToCodeCommand command)
   â Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   â MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   â System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   â System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   â System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
I'm confused, the attached gif shows node 2 code working - do you have a reproducible input case that causes node2code to crash that you can share?

**Comment by Amoursol** [comment]
Hello @Prynka1995,

As we have not received any further information, or a reproducible case for us to look at, we are closing this issue. Please free free to re-open if you want to attach additional information for us to look at, but as it stands we cannot take any further action on this.

Thanks,
Sol
