### ISSUE TITLE
What do i do my dynamo graph is not showing on the interface and anything  i code doesnt appear

### ISSUE THREAD

**Issue by AjuwonAyodeji** [DynamoDS/Dynamo#10207]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by Amoursol** [comment]
Hello @AjuwonAyodeji,

Would you be able to please fill in the blank slots here so we can better help you? Screenshots are very beneficial to us.

**Comment by Amoursol** [comment]
Hello @AjuwonAyodeji - As we have not received any additional information to this issue and cannot progress, we are going to close it for now. Please reopen with a filled in template if you run into this issue again.
