### ISSUE TITLE
*.dyn file opens as a *.dyf file

### ISSUE THREAD

**Issue by guillaumethon123** [DynamoDS/Dynamo#10210]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

Dynamo 2.1.0

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

Windows 8

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

I saved my work

## What did you expect to see?

my dyn file

## What did you see instead?

a dyf file

Copy of my message on the Dynamo Forum with more informations 

:

Hello everyone!

I recently had an issue with my Dynamo environment and I’m seeking for help here, because I think I’ve tried all the logical solutions that came to my mind (haven’t tried the mystical ones yet).

My problem is that when I open my Dynamo workspace (The .dyn file), Dynamo opens the custom node window (with the yellow background) named with the name of my .dyn file, with the .dyn extension. The workflow inside this custom node is one of my other custom node. Where the main window should be (with the white background), there is an empty Home.dyn.
I don’t know from what action this issue came from, I was working and when I saved my file, this happened.
The strange thing is that the .dyn file I wan’t to open has still the same size (42ko).

I’m working with Dynamo 2.1.0 and Revit 2017

Here are some screenshots :

what I had :
Workflow
Workflow
1245×622 511 KB
what I have now :
issue
issue
1615×813 263 KB
log :
Active view is now Title Sheet

Thank you by advance for the time some of you will take for me!

**Comment by Amoursol** [comment]
Hello @guillaumethon123 ,

Could you please upload the screenshots to here and provide a link to your forum post 😊 ?

**Comment by mjkkirschner** [comment]
This should be fixed in newer versions of dynamo after this change: 
https://github.com/DynamoDS/Dynamo/pull/10119

I think.

**Comment by sahawnehmajdi** [comment]
hello,

did anyone solve this problem, i have the same thing happened to me, my entire workflow is now a  #custom node.

**Comment by DaltonGOO** [comment]
![image](https://user-images.githubusercontent.com/30426235/94952945-6167a300-04ac-11eb-97be-c39da4224d8f.png)

**Comment by QilongTang** [comment]
@DaltonGOO Do you mind sharing with us your Dynamo version, steps to reproduce and sample workflow for our team to look at a fix?
