### ISSUE TITLE
Отчет о сбое в Dynamo 2.4.1.6394

### ISSUE THREAD

**Issue by dmlunov** [DynamoDS/Dynamo#10225]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.1.6394`

**Comment by Amoursol** [comment]
Hello @dmlunov ,

Would you be able to please fill in the template so that we can better understand the problem you are facing?

большое спасибо
