### ISSUE TITLE
Recently i have installed dynamo to use in fusion 360. when i open dynamo after installation the work space looks blank. Have checked all option in setting. Could someone help in this regards

### ISSUE THREAD

**Issue by Danesebastian** [DynamoDS/Dynamo#10253]
Recently i have installed dynamo to use in fusion 360. when i open dynamo after installation the work space looks blank. Have checked all option in setting. Could someone help in this regards

**Comment by QilongTang** [comment]
@Danesebastian Can you share screenshots? Wonder when you mentioned workspace looks blank, do you mean opening an existing workspace or starting from fresh and expecting geometry preview to show up.

**Comment by Danesebastian** [comment]
![image](https://user-images.githubusercontent.com/59351853/71606013-9f543580-2bc1-11ea-8756-fe703772bc30.png)

**Comment by Danesebastian** [comment]
@QilongTang  here is the screenshot. u will see its blank without grid or origin(Work space)

**Comment by QilongTang** [comment]
@Danesebastian Hi, once you have launched Dynamo Studio, under view->show console, can you give our team a screenshot of the console messages to help us digest what's happening?

**Comment by Danesebastian** [comment]
@QilongTang  Hi, Here is the screenshot as said

![image](https://user-images.githubusercontent.com/59351853/71619487-ba9e5f80-2c18-11ea-84ea-4615d61618bf.png)

**Comment by mjkkirschner** [comment]
try following the suggestions in the faq about graphics here:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by Danesebastian** [comment]
@mjkkirschner 

In my system there is AMD Radeon R7 A360 and Intel(R) HD Graphics 530.
As mentioned in (AutoCAD uses the wrong graphics card troubleshooting)
(In Control Panel > Device Manager, expand Display adapters, right-click on Intel HD Graphics and choose Disable.)
I tried disabling my AMD Radeon R7 A360 and now workspace shows up
Thank you. 
But I'm not sure this affects other software in my system

**Comment by Danesebastian** [comment]
![image](https://user-images.githubusercontent.com/59351853/71700744-d2910180-2e19-11ea-9f41-fa644e09f543.png)

**Comment by Danesebastian** [comment]
Thank you!!! @QilongTang @mjkkirschner
