### ISSUE TITLE
Running Python Editor within custom node causes crash

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#10276]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.3.0

## Operating system
Win 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
1. Open new Dynamo file
2. Place Python node and open
3. Place any custom node(tested with springs.WatchDialog last)
4. Open custom node while python editor is still open
5. Able to press Run while in .dyf of custom node
6. Crash
(Fill in here)

## What did you expect to see?
I don't know if this has been reported before, couldn't find it. Would have been great if the Run button was greyed out maybe while in the dyf.

## What did you see instead?
Crash

**Comment by mjkkirschner** [comment]
Hi @josols  I think this was fixed here:
https://github.com/DynamoDS/Dynamo/pull/9988
and should be in 2.5 - it might be a slightly different issue though...

**Comment by mjkkirschner** [comment]
tracked with https://jira.autodesk.com/browse/DYN-2431
