### ISSUE TITLE
Problem witth Empty List

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/Dynamo#10319]
I see problem with node this, please fix it or any explain for thit

[https://drive.google.com/file/d/1EzTICXGwCXemOPLrt9OQrEAwMFC6aVFw/view?usp=sharing](url)

**Comment by Amoursol** [comment]
Hello @chuong9x, this is being tracked now to fix 😄 Thanks for bringing it to our attention!

**Comment by mjkkirschner** [comment]
tracked with: https://jira.autodesk.com/browse/DYN-2399

**Comment by avidit** [comment]
Fixed in 2.9
