### ISSUE TITLE
Crash report from Dynamo 2.4.0.6186

### ISSUE THREAD

**Issue by Richard-Volker** [DynamoDS/Dynamo#10317]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.0.6186`

**Comment by Amoursol** [comment]
Hello @Richard-Volker, could you please fill in more information in the template? There is nothing we can action based on this submission.

**Comment by mjkkirschner** [comment]
please reopen with additional information. Thanks.
