### ISSUE TITLE
Fatal error pasting polylines

### ISSUE THREAD

**Issue by nikkiver98** [DynamoDS/Dynamo#10338]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.4.1.1417

## Operating system

windows 10

## What did you do? 

1 Opend a dynamo script
2 opend a dwg file
3 select polylines
4 paste ploly lines in empty file
(this happends only when i have Dynamo open)

## What did you expect to see?

pasting poly lines in empty file

## What did you see instead?

tatal error

**Comment by Amoursol** [comment]
@CoolStarLee would you be able to please take a look at @nikkiver98 's issue in Dynamo4Civil3D?

**Comment by mjkkirschner** [comment]
tracked internally with: https://jira.autodesk.com/browse/CIVIL-31303

**Comment by NoraLi** [comment]
@nikkiver98 are you pasting the polyline to a new dwg? would you add more info of how to crash happened? I tried the steps below in C3D and failed to reproduce the problem:
1. Launch C3D and new a dwg, new a polyline, copy to the polyline to clipboard
2. New an empty dwg and launch Dynamo
3. paste the polyline to dwg created in step2
