### ISSUE TITLE
Missing Nodes an connectors

### ISSUE THREAD

**Issue by nikkiver98** [DynamoDS/Dynamo#10336]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.4.1.1417

## Operating system

windows 10

## What did you do? 

After AutoCAD crashing i tried to open autocad and dynamo again.

## What did you expect to see?

i expected to see my nodes and connecters the whay i left them on the last save attempt

## What did you see instead?

random missing nodes and connectors which were in the script in de last save file

**Comment by QilongTang** [comment]
@CoolStarLee FYI
