### ISSUE TITLE
fatal error after selecting polylines

### ISSUE THREAD

**Issue by nikkiver98** [DynamoDS/Dynamo#10337]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.4.1.1417

## Operating system

Windows 10

## What did you do? 

1 Opend a dynamo script
2 opend a dwg file
3 select polylines

## What did you expect to see?

i expected to see me selecting polylines
(this only happends while i have an dynamo script open)

## What did you see instead?

fatal error

**Comment by Amoursol** [comment]
@CoolStarLee would you be able to please take a look at @nikkiver98 's issue in Dynamo4Civil3D?

**Comment by mjkkirschner** [comment]
tracked internally with : https://jira.autodesk.com/browse/CIVIL-31303
together with https://github.com/DynamoDS/Dynamo/issues/10338
