### ISSUE TITLE
Crash report from Dynamo 2.4.0.6186

### ISSUE THREAD

**Issue by charan1644** [DynamoDS/Dynamo#10393]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.0.6186`

**Comment by QilongTang** [comment]
@charan1644 Would you fill in the crash details here to help our team digest?

**Comment by Amoursol** [comment]
Hello @charan1644 - As we have not received any additional information to this issue and cannot progress any further, we are going to close it for now. Please reopen with additional information if you run into this issue again.
