### ISSUE TITLE
is/will it be possible to create and modify rebar?

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#1039]
is/will it be possible to model rebar similar to the "structural framing" node?
it seems that since its a system family ... sort of .... it could not be created? or its parameters could not be read/get on existing rebar? 
am i missing something or its not there yet? if not when? if ever? 
THX!

**Comment by ksobon** [comment]
@marcellosgamb there is an external package called DynamoRebar that has been out for a while. I think that would address the issue here. cc: @kronz can we close this?

**Comment by kronz** [comment]
Agreed, the package functionality exists.  We are trying to keep the out-of-the-box Dynamo for Revit functionality to be as general as possible, which often means staying out of discipline specific tools.
