### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by wiook** [DynamoDS/Dynamo#10412]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I was running a Dynamo script

### What did you expect to see?
"Run completed" without errors

### What did you see instead?
an error "Unhandled Exception"

### What packages or external references (if any) were used?
none

### Stack Trace
```

```
![Unhandled Exception](https://user-images.githubusercontent.com/61423592/75166906-e58ec680-5724-11ea-908f-d0d793ca6a19.JPG)

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by johnpierson** [comment]
Hi @wiook - do you have a revit file and graph that reproduce this consistently?

**Comment by Amoursol** [comment]
Hello @wiook,


As we have not received any further information, or a reproducible case for us to look at, we are **closing this issue**. 

Please free free to re-open if you want to attach additional information for us to look at, but as it stands we cannot take any further action on this.

Thanks,
Sol
