### ISSUE TITLE
Bugs Boolean Difference: Returns 0 volume solids not nulls. Also returns disjointed solid

### ISSUE THREAD

**Issue by MattGaydon** [DynamoDS/Dynamo#10417]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dyn Core: 2.1.0.7500
Dyn Revit: 2.1.07733

Dyn Core: 2.4.1.6326
Dyn Civil 3D: 2.4.1.1417

## Operating system

Windows 10

## What did you do? 

2 Issues that maybe linked/ fixed at the same time.

1. Boolean difference on a couple of solids , one that is inside solid and the other intersecting the solid inside is returned but does not exist and has a volume of 0.

![image](https://user-images.githubusercontent.com/57402212/75327986-8db7a300-587d-11ea-995f-af05eafabcc3.png)

2. Boolean difference returns a single disjoined solid if the part being boolean is inside and outside the subtracting object

![image](https://user-images.githubusercontent.com/57402212/75328097-b6d83380-587d-11ea-9aaa-6631ee6621f9.png)

## What did you expect to see?

Issue 1 . A null value and not no solid and a 0 volume
Issue 2.  A list of solids

## What did you see instead?

See Images above.

**Comment by aparajit-pratap** [comment]
We have added a new node called `Solid.Separate` that can be used to separate the composite solid containing disjoint one or more disjoint lumps in it. This node will be available in Dynamo 2.9. Also fixed the issue where we are not returning `null` for a zero-volume solid and at the same time issuing a warning on the node when that happens.
