### ISSUE TITLE
Problem With Formula Node

### ISSUE THREAD

**Issue by chuong9x** [DynamoDS/Dynamo#10453]
## Dynamo version

2.1(master branch)

## Operating system

Windows 10.

## What did you do? 

I found a humorous error that was described as a video. The line was not removed when I deleted the node, and when I pressed the command back, they exited dynamo and showed an error.
video description of me  : https://www.youtube.com/watch?v=ZMMBZC_s-7A&feature=youtu.be
## What did you expect to see?

I Hope team can fix soom :D

**Comment by mjkkirschner** [comment]
Hi @chuong9x - looks like this same issue https://github.com/DynamoDS/Dynamo/issues/9908 which we have tracked, I will close this one and progress will be updated there. Thanks for the report.
