### ISSUE TITLE
Wish: BuiltInParameter Selector

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1046]
Built-in parameters have the (somewhat annoying) property of being localized, so when we share graphs that read or write parameters between collaborators that use different localizations of Revit, we end up having to rename parameters in our graphs every time.
Now that there's an infrastructure for dropdowns in place, it would be great to have a node that lets us select built-in parameters (perhaps ordered or filtered by category) in order to pass the selected parameter to the get/set parameter node. Ideally, the dropdown would display both the localized parameter name as well as the internal built-in name.

**Comment by ksobon** [comment]
@andydandy74 archi-lab has that functionality now:

![capture](https://cloud.githubusercontent.com/assets/529781/10382671/5a1e28ac-6df4-11e5-8cc9-e0f9c459500a.PNG)

The dropdown doesn't exactly list all of the BuiltInParameters, but you can input an element instance or type to get a list of BuiltInParameters that given element supports. 

Can we close this issue? Thank you,

**Comment by andydandy74** [comment]
Cool!
