### ISSUE TITLE
Dereferencing a non-pointer and Interop.Excel

### ISSUE THREAD

**Issue by dimvoly** [DynamoDS/Dynamo#10475]
## Dynamo version
2.0.3.8810
2.0.3.8811
(side note: can you make the about page copy pastable?)

## Revit version
Revit 2019.2

## Operating system
Windows 10

## What did you do? 
I'm making an "Explicit Custom Node" (ECN), and was following this tutorial:
[http://teocomi.com/dynamo-unchained-2-learn-how-to-develop-explicit-nodes-in-csharp/](http://teocomi.com/dynamo-unchained-2-learn-how-to-develop-explicit-nodes-in-csharp/)

The tutorial worked fine.
I then made a separate project that uses `Microsoft.Office.Interop.Excel` to take in 3 `double` values, open an Excel file, use those 3 `double` values to calculate a single `double` value. While this can be re-coded in python/design script/dynamo - the calculations need to be in Excel files as a significant amount of business logic already exists as Excel files. They're also used for review when they're later saved as PDFs. This part worked fine.

I have then inserted the code from the second project into the ECN and have been getting the non-pointer error.

## What did you expect to see?
I expected my custom node to take some time to open and close Excel while calculating and then output the correct answer in the watch node.

## What did you see instead?
`null` output with the following error:
`Warning: Internal error, please report: Dereferencing a non-pointer.`

## Additional Information
The issue appears to be with the `Microsoft.Office.Interop.Excel` parts, I have reduced the `Functions` part of the code to only include this:
```
public static double RodTension(double height, double width, double force)
{
	string filePath = @"C:\Projects\SharpExcel\Functions\ExcelFile\Braced Frame Member Forces_Original.xlsx";
	double tensionValue;

	var excelApp = new Excel.Application();
	excelApp.Visible = false;

	var xlWorkBooks = excelApp.Workbooks;
	var xlWorkBook = xlWorkBooks.Open(filePath);
	var xlSheets = xlWorkBook.Worksheets;
	var xlWorkSheet = (Excel.Worksheet)xlSheets[1];

	tensionValue = width;
	return tensionValue;
}
```

The above code produces the dereferencing error.

For context, the Excel sheet takes in a braced frame's width, height and lateral force at top, to calculate the tension in the rod bracing.

## Full Code
In reality, the full code would include the actual Excel manipulation and disposal of each COM object:
```
public static double RodTension(double height, double width, double force)
{
	string filePath = @"C:\Projects\SharpExcel\Functions\ExcelFile\Braced Frame Member Forces_Original.xlsx";
	double tensionValue;

	using (var com = new ComObjectManager())
	// https://stackoverflow.com/q/2926205/1758759
	{
		var excelApp = com.Get<Excel.Application>(() => new Excel.Application());
		excelApp.Visible = true;
		excelApp.Visible = false;
		var xlWorkBooks = com.Get<Excel.Workbooks>(() => excelApp.Workbooks);
		var xlWorkBook = com.Get<Excel.Workbook>(() => xlWorkBooks.Open(filePath));
		var xlSheets = com.Get<Excel.Sheets>(() => xlWorkBook.Worksheets);
		var xlWorkSheet = com.Get<Excel.Worksheet>(() => (Excel.Worksheet)xlSheets[1]);

		xlWorkSheet.Cells[6, "B"] = height;
		xlWorkSheet.Cells[7, "B"] = width;
		xlWorkSheet.Cells[8, "B"] = force;

		tensionValue = Convert.ToDouble(xlWorkSheet.Cells[20, "B"].Text);

		xlWorkBook.Save();
		xlWorkBook.Close();
		xlWorkBooks.Close();
		excelApp.Quit();
		
		return tensionValue;
	}
}
```

**Comment by mjkkirschner** [comment]
Hi @dimvoly - I found the issue
![Screen Shot 2020-03-18 at 6 01 48 PM](https://user-images.githubusercontent.com/508936/77011600-96623d00-6942-11ea-98e9-9badb5dfb8e8.png)

We really need to provide better errors in the console regarding ZT import, but I was able to track this down debugging dynamo and catching all exceptions - I found that 16 types were being imported from your dll - 15 from excel interop - these are too complex to get imported into the VM. 

To fix the issue, don't embed interop types into your zt dlls or Dynamo will try to import them and usually fail.

**Comment by dimvoly** [comment]
Not sure I can accept that. Excel is pretty critical to this work flow. I may try DynamoDS/Dynamo and see if they can point me in the right direction.

If you look at the [ExportExcel or ImportExcel Node](https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/DynamoExcel/dynExcel.cs), it uses Excel.Interop:
```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Dynamo.Connectors;
using Dynamo.FSchemeInterop;
using Dynamo.Models;
using Dynamo.Utilities;
using Microsoft.FSharp.Collections;
using Microsoft.Office.Interop.Excel;
```

Thanks for tracing through it Michael, gave me some pointers. I'll try the [DynamoDS/Dynamo](https://github.com/DynamoDS/Dynamo) page.

**Comment by mjkkirschner** [comment]
I’ve already transferred this issue there - I’m not saying don’t use excel - I’m saying don’t use embedded types - see the screenshot where it says embed interop types - change thstbto none.

**Comment by dimvoly** [comment]
Thank you so much for your help, I got it working!

For the benefit of anyone else coming across this issue - once I've set the embed types to False, I did have to explicitly cast each type so that Visual Studio can pick up the methods/properties available.

So instead of something like this to get my output value out of Excel:
```
tensionValue = ToDouble(xlWorkSheet.Cells[20, "B"].Value2;
```
I'll be doing this):
```
tensionValue = ((Excel.Range)xlWorkSheet.Cells[20, "B"]).Value2;
```
