### ISSUE TITLE
Project environment, Exception thrown on target of invocation when attempting to bake a primitive box

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1048]
![screen shot 2014-01-27 at 10 18 23 am](https://f.cloud.github.com/assets/508936/2009926/91e0d53a-8766-11e3-9ed6-73f88554fcc2.png)

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
