### ISSUE TITLE
Cannot resolve reference to face of family instance

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1049]
![screen shot 2014-01-27 at 12 07 48 pm](https://f.cloud.github.com/assets/508936/2011061/9ec18b5a-8775-11e3-9970-ca82fea661b9.png)
![screen shot 2014-01-27 at 12 07 02 pm](https://f.cloud.github.com/assets/508936/2011064/a10f791c-8775-11e3-857f-86969f1a22dc.png)

I tried parsing the face, after using a transaction to place the adaptive component and I also tried selecting the face directly from the document after creating the family instance.

**Comment by ikeough** [comment]
@mjkkirschner Still a bug? :)
