### ISSUE TITLE
Curves from Family Instance moved from original position

### ISSUE THREAD

**Issue by johannariad** [DynamoDS/Dynamo#1051]
Hi!
I'm having a problem which confuses me a little. When I use the curves from family instance node I get the curves from the family instance (which in my case is a set of model lines) but they are moved from their original position in a direction which to me seems arbitrary. Is anyone else having this issue? Anyone who knows how to resolve it?
Thanks,
Johanna

![revitprojectview](https://f.cloud.github.com/assets/6522600/2017249/3fe90b2c-87f6-11e3-99eb-b9b06a5420cd.png)

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
