### ISSUE TITLE
Search returned no results!

### ISSUE THREAD

**Issue by timry** [DynamoDS/Dynamo#10529]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo 2.0.3

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

I am trying to work in Sandbox mode, and wish to install custom packages. When I select "Search for Packages" the menu window immediately displays "Search returned no results!"

## What did you expect to see?

Packages available to download.

## Search returned no results!

It appears that server is down, but when searching for packages in Revit / Dynamo sessions, search works as expected.
<img width="779" alt="Screenshot_1" src="https://user-images.githubusercontent.com/50882655/78076625-c8c55e80-7374-11ea-8e24-d1b2c944756e.png">

**Comment by mjkkirschner** [comment]
This is a tls issue with sandbox - grab one of the newer sandbox builds from www.dynamobuilds.com 

alternatively you can try this change in sandbox app config: 
https://github.com/DynamoDS/Dynamo/issues/10030

**Comment by timry** [comment]
Still cannnot see custom packages in the main window

**Comment by mjkkirschner** [comment]
Hi @timry - which route did you go to try to solve the issue? Can you make sure .net 4.7 is installed on this machine?

**Comment by timry** [comment]
All current just checked latest .net
