### ISSUE TITLE
If node has strange behaviour

### ISSUE THREAD

**Issue by m-danm** [DynamoDS/Dynamo#10523]
I'm trying the following
1.create a matrix of points
2.(count) get the no of elements on rows no1
3.(count) get the no of elements on column no1
4.create two lists
  a. matrix of points & number of elements on row1
  b. trasposed matrix & number of elemtne on row2

IF statement
check if one element si bigged that other element. and based on this feed list 4a or 4b.

IF - chunks the last row of the initial matix - for example if the matrix has 80 elements 8x10 i get only 70 items...
Revit dynamo core 2,3

**Comment by Amoursol** [comment]
Hello @m-danm ,

The **If node** has some interesting behavior that is on our radar to fix. Please refer to this thread: https://forum.dynamobim.com/t/request-for-feedback-if-node/45257 and see the work-arounds in it.

Alternatively, feel free to post your script here and we can take a look 😄

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/Dynamo/pull/11728
