### ISSUE TITLE
Crash report from Dynamo 2.5.2.7915

### ISSUE THREAD

**Issue by alvaroluna** [DynamoDS/Dynamo#10539]
# Issue Description
Hello - I clicked on the individual indices (in the printout that you can pin on the bottom of a node) of the elements created by the Surface from Polysurface node in order to display their list number on screen and Dynamo crashed. I have to use Dynamo 2.5 bc earlier versions do not have a geometry preview in Dynamo on 16" macbook pros with the AMD Radeon Pro card.

### What did you do?
[...]

### What did you expect to see?
I want to see the index numbers of each respective element within a node on screen in the Dynamo preview window.

### What did you see instead?
Dynamo crashes

### What packages or external references (if any) were used?
N/A

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.2.7915`

**Comment by mjkkirschner** [comment]
@alvaroluna please paste the stack trace here and also your files.

**Comment by Amoursol** [comment]
Hello @alvaroluna - As this has gone beyond two weeks without further information we cannot progress any further. Please re-open with additional information if you wish, but for now we are going to close this issue.
