### ISSUE TITLE
new data shapes nodes crashing dynamo?

### ISSUE THREAD

**Issue by revithero** [DynamoDS/Dynamo#10559]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.4

## Operating system

Windows 10

## What did you do? 

ran a script

## What did you expect to see?

to run my script to the end

## What did you see instead?

it gave me an ARRG crash message.

**Comment by Amoursol** [comment]
Hello @revithero ,

Would you be able to tell us the version of Revit you are inside and upload a script that exhibits this failure?

**Comment by mjkkirschner** [comment]
I think you should file an issue here:
https://github.com/MostafaElAyoubi/Data-shapes

**Comment by Amoursol** [comment]
Hello @revithero, as Mike mentioned this appears to be an issue with a 3rd party package, called 'Data-Shapes'. Please submit to Mostafa's repo (https://github.com/MostafaElAyoubi/Data-shapes). Best of luck with the submission - Mostafa is typically very swift upon his responses.
