### ISSUE TITLE
Relatório de erros do Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by Luckianoh** [DynamoDS/Dynamo#10595]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment]
Hello @Luckianoh ,

We need more information in order to proceed with investigation of this crash - please fill in the templated fields.

**Comment by Amoursol** [comment]
Hello @Luckianoh,

As we have not received any further information, or a reproducible case for us to look at, we are **closing this issue**. 

Please free free to re-open if you want to attach additional information for us to look at, but as it stands we cannot take any further action on this.

Thanks,
Sol
