### ISSUE TITLE
Informe de conflictos de Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by Peresino** [DynamoDS/Dynamo#10613]
# Issue Description
Please fill in the following information to help us reproduce the issue:
_Problems with 3D view in Dynamo. I can't see anything in Dynamo's 3D workspace._

### What did you do?
_I've recently instaled Revit 2020 with Dynamo 2.3.0 and something wrong has happen. There is no problema with my new graphic card_

### What did you expect to see?
_I'd like to see 3D space, like used to see before with my previous Dynamo version._

### What did you see instead?
_I just can see a 2D grid, nothing more._

### What packages or external references (if any) were used?
_[I've installed most typicall packages, there no problems with them. I just have problems with graphics...]_

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
try installing this:
https://www.microsoft.com/en-us/download/details.aspx?id=8109

see similar issues:
https://github.com/DynamoDS/Dynamo/search?q=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fdownload%2Fdetails.aspx%3Fid%3D8109&type=Issues

**Comment by Peresino** [comment]
Thanks very much Michael.
I’ll try to see how it goes…
Cheers!

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Michael Kirschner<mailto:notifications@github.com>
Enviado: miércoles, 29 de abril de 2020 2:28
Para: DynamoDS/Dynamo<mailto:Dynamo@noreply.github.com>
CC: Peresino<mailto:rosaperezresino@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [DynamoDS/Dynamo] Informe de conflictos de Dynamo 2.3.0.5885 (#10613)


try installing this:
https://www.microsoft.com/en-us/download/details.aspx?id=8109<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fdownload%2Fdetails.aspx%3Fid%3D8109&data=02%7C01%7C%7Cdb9d4a0a087f43bcb07108d7ebd447e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637237169275086080&sdata=oidBOS%2FZukgSYWUIPWWgAioMN6sVZsRTyiDukULRuP0%3D&reserved=0>

see similar issues:
https://github.com/DynamoDS/Dynamo/search?q=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fdownload%2Fdetails.aspx%3Fid%3D8109&type=Issues<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDynamoDS%2FDynamo%2Fsearch%3Fq%3Dhttps%253A%252F%252Fwww.microsoft.com%252Fen-us%252Fdownload%252Fdetails.aspx%253Fid%253D8109%26type%3DIssues&data=02%7C01%7C%7Cdb9d4a0a087f43bcb07108d7ebd447e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637237169275096074&sdata=CmnyuTv%2FPjBCal28cnc9pD8wA41naZBiasEW9U2hOjQ%3D&reserved=0>

**Comment by Amoursol** [comment]
Hello @Peresino - did these steps help you?

**Comment by mjkkirschner** [comment]
please reopen if required.
