### ISSUE TITLE
Issue report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by amelvin90** [DynamoDS/Dynamo#10617]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
created a dynamo file with List Create and Boolean Toggle, saved it. When I reopen, the nodes are gone. This happens with all my definitions

### What did you expect to see?
the nodes I created before saving 

### What did you see instead?
blank

### What packages or external references (if any) were used?
-

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment]
Hello @amelvin90 - Would you please be able to upload they DYN file that crashed here for us to look at?

**Comment by amelvin90** [comment]
Hey,

It wasn’t a crash, what’s happening is that I am working in dynamo, completing a definition, or wanting to stop, so I save the file, then when I try to reopen, most of the nodes disappear.  This happens every time I work in dynamo.

I have attached a saved dynamo file with a screenshot of what it looked like after saving, before closing. And another screenshot of what the file looks like when I re-open.

I just don’t know why basic nodes keep disappearing… even the Boolean toggle node disappears.

**Comment by Amoursol** [comment]
Hello @amelvin90 - I'm not receiving the attached screenshots I'm afraid. Could you please log into Github itself and attach here? 😊 

As it stands, I do not experience the same issue on my side. If we can't reproduce the issue then it's very hard for us to debug the process to see what is going wrong.

**Comment by amelvin90** [comment]
![dynamo door swing script after](https://user-images.githubusercontent.com/64550427/81114091-53a6f500-8eef-11ea-9b8d-5091360b7a83.JPG)
![dynamo door swing script before](https://user-images.githubusercontent.com/64550427/81114092-53a6f500-8eef-11ea-85d6-c8890e12293a.JPG)

and I cant upload .dyn files...

**Comment by mjkkirschner** [comment]
there are other threads with the same issue, usually it occurs because the nodes could not be deserialized correctly because of some conflicting addin.

Do you have any revit addins installed?

**Comment by amelvin90** [comment]
I came across that too, deleted all add-ins and it still happened…

all I can think of now is uninstall revit 2020 completely and reinstall it…

**Comment by mjkkirschner** [comment]
what packages do you have installed for Dynamo? Do you have any green notifications in the menu bar of dynamo?

**Comment by amelvin90** [comment]
Archi-lab and Lunchbox was all I had.  I uninstalled all packages after you emailed last.

Currently I have none installed and the same problem is happening.  Tested it with list create and a Boolean toggle. Both disappear.

No green notifications.

**Comment by QilongTang** [comment]
@amelvin90 I still could not reproduce the issue you are seeing. Do you mind connect with me offline and we can do a screen share, I would love to dig this a bit with you

**Comment by QilongTang** [comment]
Closing the issue due to inactive state. Team could not reproduce this issue and need more user input.
