### ISSUE TITLE
ConvexHull.ByPoints Node shows warning

### ISSUE THREAD

**Issue by thiruvarasan** [DynamoDS/Dynamo#10614]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo core 2.03

## Operating system

windows 10

## What did you do? 

Run Convexhull.ByPoint node by random points 

## What did you expect to see?

Convexhull Curve

## What did you see instead?

Below warning

Warning: ConvexHull.ByPoints operation failed. 
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

![image](https://user-images.githubusercontent.com/37893994/80568443-a165be00-8a14-11ea-8808-d627f6911d8f.png)

**Comment by Amoursol** [comment]
This is now being tracked internally at: https://jira.autodesk.com/browse/DYN-2668

**Comment by Amoursol** [comment]
Hello @thiruvarasan  - Looking into this further, the library we use for ConvexHull was never intended to be used in a 2D setting. As such, we are not going to support this at this time and will be amending the description on the node to state that it only works on 3D points.

**Comment by andydandy74** [comment]
@thiruvarasan - If you need a 2D convex hull, there are nodes for that in the Springnodes and Clockwork packages.
