### ISSUE TITLE
Workspace References View Extension UI issue

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#10627]
I don't think the hover over on these buttons is the right color: 

![image](https://user-images.githubusercontent.com/529781/80979080-83210900-8dec-11ea-94ee-e05eac8ccd62.png)

When hovered over the button it obscures the actual button content. White font on baby blue background is impossible to read.

**Comment by QilongTang** [comment]
@ksobon Thanks for reporting! Indeed, this is inconsistent with default Dynamo button style. I will move this issue as tech debt on our internal tracking.

**Comment by ksobon** [comment]
@is this extension open source? is there a different repo to report these issues to?

**Comment by QilongTang** [comment]
@ksobon This extension is part of Dynamo code base open sourced here https://github.com/DynamoDS/Dynamo/tree/master/src/WorkspaceDependencyViewExtension. If you would like to propose code changes, you are more than welcome to do so.

**Comment by mjkkirschner** [comment]
should be fixed in ui refresh.
