### ISSUE TITLE
Build of Dynamo.Mono.sln fails on Linux 

### ISSUE THREAD

**Issue by andredaa** [DynamoDS/Dynamo#10634]
When trying to build `xbuild /p:Configuration=Release src/Dynamo.Mono.sln `
I get the following error : 

> /home/andre/software/Dynamo/src/Libraries/DSIronPython/DSIronPython.csproj (default targets) 
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetFrameworkPaths target)
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.7' not supported by this toolset (ToolsVersion: 14.0).
Errors:
/home/andre/software/Dynamo/src/Dynamo.Mono.sln (default targets) 
(Build target) 
/home/andre/software/Dynamo/src/Libraries/DSIronPython/DSIronPython.csproj (default targets) 
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) 
	IronPythonEvaluator.cs(8,14): error CS0234: The type or namespace name 'Utilities' does not exist in the namespace 'Dynamo' (are you missing an assembly reference?)
	IronPythonEvaluator.cs(143,23): error CS0246: The type or namespace name 'DataMarshaler' could not be found (are you missing a using directive or an assembly reference?)
	IronPythonEvaluator.cs(179,23): error CS0246: The type or namespace name 'DataMarshaler' could not be found (are you missing a using directive or an assembly reference?)
	IronPythonEvaluator.cs(184,24): error CS0246: The type or namespace name 'DataMarshaler' could not be found (are you missing a using directive or an assembly reference?)
	IronPythonEvaluator.cs(185,24): error CS0246: The type or namespace

I use the following Mono Version
                                                                    
Mono JIT compiler version 6.4.0 (makepkg/fe64a4765e6 Sat 16 Nov 2019 04:59:42 PM UTC)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notificati
/home/andre/software/Dynamo/src/Dynamo.Mono.sln (default targets) ->
(Build target) ->
/home/andre/software/Dynamo/src/Libraries/DSIronPython/DSIronPython.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) -ons: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

nuget version: 
$ nuget install                                                                  
Feeds used:
  /home/andre/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /home/andre/software/Dynamo/src/packages.config are already installed.

Never used Mono or nuget before - so I might be missing something obvious.

**Comment by andredaa** [comment]
Forget about it. Now it worked.

**Comment by QilongTang** [comment]
Closing
