### ISSUE TITLE
MeshToolKit Import Error

### ISSUE THREAD

**Issue by LittleHobbyShop** [DynamoDS/Dynamo#10645]
## Dynamo version

Dynamo Sandbox

## Operating system

Windows 10 Pro

## What did you do? 

Tried to import simple mesh from stl file. Tried with several different stl files.

## What did you expect to see?

Mesh object imported

## What did you see instead?

Warning: Mesh.ImportFile operation failed. 
The type initializer for 'Autodesk.Dynamo.DynAMT.DynAMTPINVOKE' threw an exception.

![image](https://user-images.githubusercontent.com/16748684/81761068-dc5dfc00-94c0-11ea-86ca-d3bfe538294c.png)

**Comment by mjkkirschner** [comment]
Do other geometry functions work in sandbox? (like point creation?)

**Comment by LittleHobbyShop** [comment]
Realised I'm trying to use geometry without a companion Autodesk product installed. Not clear at all when installing sandbox.
