### ISSUE TITLE
Crash report from Dynamo 2.5.2.7915

### ISSUE THREAD

**Issue by 61Revenge** [DynamoDS/Dynamo#10658]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.2.7915`

**Comment by Amoursol** [comment]
Hello @61Revenge - Could you please fill in the template with more information, stack trace and/or attach a DYN file?

**Comment by Amoursol** [comment]
We are closing this issue as there has been no further additional information provided - please re-open and fill in the template if this issue still persists.
