### ISSUE TITLE
Rapport d'erreur de Dynamo 2.4.1.6394

### ISSUE THREAD

**Issue by Ge0rgeO** [DynamoDS/Dynamo#10662]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
The scrolling on the library stops after using the pressed middle button (in the library space). To access the contents of the library I am obliged to use only the scroll bar. It's tiring and frustrating at the same time ...

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
Archi-lab_Mandrill
Autodesk (Civil 3D Toolkit)
Clockwork
IterisCivilDynamo
LinkDWG

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.1.6394`

**Comment by mjkkirschner** [comment]
Hi @Ge0rgeO thanks for reporting this - we've fixed it here:
https://github.com/DynamoDS/Dynamo/pull/10509
which will be included in Dynamo 2.6
