### ISSUE TITLE
Dynamo 2.5 (for Revit 2021) not importing GenerativeDesign

### ISSUE THREAD

**Issue by jeczmien94** [DynamoDS/Dynamo#10684]
## Dynamo version

Dynamo Revit 2.5.0.7586

## Operating system

Windows 10

## What did you do? 

The Generative Design Tab in the top-bar menu is not showing after Dynamo is launched. This problem is new - I could work with the Refinery for about a month after installation, but suddenly this add-in is not working.

Dynamo shows such notifications:

Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit
   at Dynamo.PackageManager.PackageLoader.CheckPackageNodeLibraryCertificates(String packageDirectoryPath, Package discoveredPkg)
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit

DETAILS:
"A package called GenerativeDesign found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit could not be verified to have signed dll files.  A dll file found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit\bin\GenerativeDesignNodes.dll did not have a signed certificate.  Ignoring it."

![2020-05-20_10h16_04](https://user-images.githubusercontent.com/48924657/82422598-efee0180-9a82-11ea-8638-471bf40ef5a9.png)

I've tried to reinstall Revit 2021, but it didn't help. However, I don't see a possibility to reinstall just Dynamo, like it was with the versions attached to the previous Revits (2020, 2019).

I will be grateful for your help with this issue.

**Comment by saintentropy** [comment]
@jeczmien94 Unfortunately you are hitting an issue that affected the availability of the Generative Design menu and Generative Design nodes in Dynamo For Revit after 5/13.  There is a patch available for GD in Revit and it can be found in the Autodesk Desktop Application or in the Manage portal https://manage.autodesk.com/cep/#products-services/updates.  If you install the Generative Design v21.5.10 for Revit 2021 update, the menu and node functionally will return.
