### ISSUE TITLE
Facets cannot be intersected

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#1068]
HI, 
i have problems to create intersection between my facets and lines created by endpoints, i was also trying to use project xyz to face node but it was without success (it didnt accept facets as face input). ideally i would like to project curve (circle) from bottom points to faces. Thanks

![capture](https://f.cloud.github.com/assets/4834544/2049316/4a00f18c-8a5e-11e3-887a-e1f49b8eb0a4.PNG)

**Comment by johnpierson** [comment]
Going ahead and closing this as it is for a very old version of Dynamo. If this kind of problem still persists for you in 2.0.x releases, please feel free to open a new issue with updated information.
