### ISSUE TITLE
How to solve the default background preview is not available in dynamo view

### ISSUE THREAD

**Issue by cuiningdan** [DynamoDS/Dynamo#10706]
## Operating system 
windows 10

## What did you do? 

(Fill in here)

## What did you expect to see?
I want to preview the 3D view in the default background of dynamo, but I cannot

## What did you see instead?
The default background preview is not available, I cannot set

**Comment by mjkkirschner** [comment]
please see related issues and reopen if that does not solve your issue.
https://github.com/DynamoDS/Dynamo/issues/10063

**Comment by cuiningdan** [comment]
> 请查看相关问题，如果仍不能解决您的问题，请重新打开。
> [＃10063](https://github.com/DynamoDS/Dynamo/issues/10063)

My computer version is win10 1709, it does not have graphics settings, how to solve the problem of dynamo default background preview

**Comment by Amoursol** [comment]
As per the other thread which @mjkkirschner  linked, @cuiningdan - have you downloaded https://www.microsoft.com/en-us/download/details.aspx?id=8109 and installed yet?
