### ISSUE TITLE
Strange drag+ctrl copy node behavior 

### ISSUE THREAD

**Issue by atis-s** [DynamoDS/Dynamo#10720]
## Dynamo version
core 2.5.0.7460
revit 2.5.7586
## Revit version
21.0.0.383
## Operating system
win10 x64
## What did you do? 
Copied node with mouse drag + ctrl
## What did you expect to see?
Copied node
## What did you see instead?
Copied node but after that if I click back no copied node- original node flies and snaps to copied node. Same happens if I click on canvas and then on copied node. OR if I click on different node. Issue is resolved only when I click back on original node after drag+ctrl copy.

**Comment by mjkkirschner** [comment]
Hi @atis-s we cannot reproduce this, can you share a video or gif of the behavior?

We'll also need more info about your system, display scaling setting might be useful information as well as resolution, etc and Revit version.

**Comment by QilongTang** [comment]
@mjkkirschner I can't reproduce this either using Dynamo 2.8.0 inside Revit. So curious about the steps and env as well.

**Comment by atis-s** [comment]
Hi, @mjkkirschner @QilongTang 
using multiple screens, scale 100%
 video: 
https://drive.google.com/file/d/1TQf9C1Vd7TmTgYUnWxRJVggSdcJpvlxx/view?usp=sharing

**Comment by mjkkirschner** [comment]
Hi @atis-s thanks for the video! I cannot reproduce yet - would you mind trying in latest daily build to see if it reproduces there on your system?
https://dynamobuilds.com/

**Comment by mjkkirschner** [comment]
It will also be good to have a list of your packages, you can also try disabling them to see if that makes a difference.

**Comment by atis-s** [comment]
Hi, just testing 
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`
And the bug is still there - https://drive.google.com/file/d/1zKrgEpf9Ip2P3McWMDTnU5KQvNuQOypy/view?usp=sharing

**Comment by mjkkirschner** [comment]
@atis-s the fix was only merged to dynamo 2.9.0 - it would not be fixed in 2.6.1
