### ISSUE TITLE
Absturzbericht von Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by konradsten** [DynamoDS/Dynamo#10730]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
just try to save graph

### What did you expect to see?
noting

### What did you see instead?
Dynamo failed

### What packages or external references (if any) were used?
Genius Lochi, spring nodes, archi-lab net, Data Shapes

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

   bei Dynamo.Models.DynamoModel.Dispose()
   bei Dynamo.Models.DynamoModel.ShutDownCore(Boolean shutdownHost)
   bei Dynamo.Applications.Models.RevitDynamoModel.ShutDownCore(Boolean shutDownHost)
   bei Dynamo.Models.DynamoModel.ShutDown(Boolean shutdownHost)
   bei Dynamo.ViewModels.DynamoViewModel.PerformShutdownSequence(ShutdownParams shutdownParams)
   bei Dynamo.Controls.DynamoView.PerformShutdownSequenceOnViewModel()
   bei Dynamo.Controls.DynamoView.WindowClosing(Object sender, CancelEventArgs e)
   bei System.Windows.Window.OnClosing(CancelEventArgs e)
   bei System.Windows.Window.WmClose()
   bei System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
@konradsten can you reproduce this crash on your system? Where you using Revit as well? What version?

Can you reproduce this crash if you remove the packages listed?

**Comment by konradsten** [comment]
Hi,
I work on Revit 20 for Windows, I have already tried to reinstall Revit and
to remove all packages. I became this error even on Revit 21. This only
happened when I work on of my PC in second office. On another PC and
Notebook all runs perfect.
Thank for your response.

Konrad Sten

Michael Kirschner <notifications@github.com> schrieb am Fr., 5. Juni 2020,
21:19:

**Comment by mjkkirschner** [comment]
Hi @konradsten, I am still not 100% clear.

So on your other pcs (where this does not occur) do you also have Revit 2020 and 2021 installed?

Can you take a video of this behavior?

Can you also uninstall or disable all addins (in addition to Dynamo packages) ?

**Comment by mjkkirschner** [comment]
Please provide repro steps for us and reopen when those are available.
