### ISSUE TITLE
list.intersection

### ISSUE THREAD

**Issue by 123ll-szu** [DynamoDS/Dynamo#10749]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo 2020
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

i use list.intersect to find the same points between the list of endpoints and startpoints

## What did you expect to see?

find the same points 

## What did you see instead?

some repeat points do not display in list.intersect

**Comment by mjkkirschner** [comment]
Can you share the graph to reproduce this?

**Comment by Amoursol** [comment]
Hello @123ll-szu - As we have not had any response on this issue we are closing for now. Please re-open with more information if you are still experiencing the issue.
