### ISSUE TITLE
Wish/ Bug: Get Family Istance Parameter Value for "Base Level" Returns only Element ID

### ISSUE THREAD

**Issue by gschleusner** [DynamoDS/Dynamo#1075]
I know why this is happening, but it seems that we should either get both the ID and the text value or get to choose for host type values. 

![image](https://f.cloud.github.com/assets/6507154/2060399/ac13885e-8c15-11e3-98ae-e1878af6feb9.png)

**Comment by ksobon** [comment]
@kronz I think it's safe to close this particular issue. There were major improvements made to this functionality since as well as ability to select BuiltInParameters which would be the recommended route here.
