### ISSUE TITLE
BUG: Any update on fixing the name space clashes in code blocks between OOTB nodes and Orchid package etc

### ISSUE THREAD

**Issue by MattGaydon** [DynamoDS/Dynamo#10755]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Version 2.1.0.7500
Revit Version 2.1.0.7733

## Revit version

Revit 2020
20.0.0.377 

## Operating system

Windows 10

## What did you do? 

Node to code/ write a code block

## What did you expect to see?

Working  code block without requiring adding DsCore etc in front list say.

## What did you see instead?

Broken Node

![image](https://user-images.githubusercontent.com/57402212/83507046-48cc8980-a4c8-11ea-808a-43f3adffda26.png)

**Comment by aparajit-pratap** [comment]
We have made a number of improvements to this issue recently: https://github.com/DynamoDS/Dynamo/pull/10558. These will be available in Dynamo 2.7.
