### ISSUE TITLE
Ladybug sun path doesn't show up

### ISSUE THREAD

**Issue by ib990** [DynamoDS/Dynamo#10752]
**Ladybug sun path doesn't show up**

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)  
2.1.0.755
## Operating system
Windows 10

## What did you do? 

(Fill in here)

## What did you expect to see?

Sunpath

## What did you see instead?

nothing/ null

**Comment by ib990** [comment]
![image](https://user-images.githubusercontent.com/66656783/84169241-66f53500-aa46-11ea-87f7-8491f8ca6d6f.png)

**Comment by ib990** [comment]
![image](https://user-images.githubusercontent.com/66656783/84169416-99069700-aa46-11ea-9d91-591cb99ec212.png)

**Comment by mjkkirschner** [comment]
This issue should be opened with the author of ladybug - please file it there. https://github.com/ladybug-tools/ladybug-dynamo
