### ISSUE TITLE
Surface.TrimWithEdgeLoops

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#10772]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.4 and 2.5 but likely other versions as well.

## Operating system

Win 

10

## What did you do? 

Used a Surface.TrimWithEdgeLoops node which would seem to indicate a series of edge loops would be removed from the interior of a surface. 

## What did you expect to see?

A surface with holes in it.

## What did you see instead?

The perimeter curves of the holes as if they were filled in.

@mjkkirschner pointed out that the behavior changes by adding the edge loop as well. 

[Doesn't work.dyn.txt](https://github.com/DynamoDS/Dynamo/files/4787526/Doesn.t.work.dyn.txt)
[Works.dyn.txt](https://github.com/DynamoDS/Dynamo/files/4787527/Works.dyn.txt)

**Comment by aparajit-pratap** [comment]
@JacobSmall  by definition of the `TrimWithEdgeLoops` node, this is not a bug. One is expected to provide all the edges of the surface, both outer and interior ones for the node to work as expected. We could make the description of the node clearer so that users use it the correct way.

**Comment by aparajit-pratap** [comment]
The description for the node has been updated and will be available in Dynamo version 2.15+
