### ISSUE TITLE
来自 Dynamo 2.3.0.5885 的崩溃报告

### ISSUE THREAD

**Issue by shenlant314** [DynamoDS/Dynamo#10800]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.1.7601 Service Pack 1`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by QilongTang** [comment]
@shenlant314 Can you post more info and fill the template here in order to help our team digest your problem?

**Comment by Amoursol** [comment]
Hello @shenlant314 - We are closing this issue right now as there has been no additional information supplied. If you still experience this issue, please reopen this issue and provide more information.
