### ISSUE TITLE
Отчет о сбое в Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by maravillosome** [DynamoDS/Dynamo#10805]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by Amoursol** [comment]
Hello @maravillosome - Could you please fill in more information into the original post? Without any more information it's difficult for us to follow up on this.

**Comment by Amoursol** [comment]
Hello @maravillosome - We are closing this issue right now as there has been no additional information supplied. If you still experience this issue, please reopen this issue and provide more information.
