### ISSUE TITLE
Crash report from Dynamo 2.6.0.8481

### ISSUE THREAD

**Issue by chrisjarvis13** [DynamoDS/Dynamo#10838]
# Issue Description
Warning Circle.ByCentrePointRadius operation failed. Could not load file or assembly [user file path] LibG.ProtoInterface.dll' or one of its dependencies. The system cannot find the file specified. 
This is within the Sandbox. 

### What did you do?
Simply clicked on the ByCentrePointRadius in the library

### What did you expect to see?
No error

### What did you see instead?
![2020-07-02 15_56_46-Dynamo](https://user-images.githubusercontent.com/64306238/86374604-aba67180-bc7c-11ea-9ad0-3a598f369109.png)

### What packages or external references (if any) were used?
None

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.0.8481`

**Comment by QilongTang** [comment]
@chrisjarvis13 Hi, thank you for reporting. Dynamo geometry nodes are depending on one of other Autodesk software, e.g. Revit, Civil3D, FormIt, Alias, Advance Steel. Are you running Dynamo without any of them installed?

**Comment by chrisjarvis13** [comment]
Hi @QilongTang , I do not have Revit installed, but I have Civil3D 2018 installed, but do not have the Dynamo Civil3D add in yet. I presume once I get that my problem will be solved? 
is there a way of distinguishing what nodes work only for Revit and which are for Civil 3D?
Thanks.

**Comment by QilongTang** [comment]
@chrisjarvis13 Dynamo Sandbox support geometry operations which depending the list of softwares installed and up to 3 versions back. So for Dynamo 2.6 you are using, it depends on any product from the list but with 2019, 2020 or the newly released 2021. That is why Civil3D 2018 would not work this case. To just use Dynamo Sandbox , you will not need DynamoForCivil3D addin, What you will need in this case is a local install of any product in that list I mentioned earlier even in trial version.

To your second question, nodes in DynamoSandbox are all generic. Product flavored Dynamo will come with additional nodes under particular category in left side library.
![image](https://user-images.githubusercontent.com/3942418/86393053-7133d900-bc6a-11ea-9837-52b77978e9b3.png)

But on node level, Dynamo do not provide such indication yet. Our team is actively thing about the strategy there in this topic. Please let me know if you have more questions.

**Comment by chrisjarvis13** [comment]
great, that all makes sense, thanks @QilongTang !
