### ISSUE TITLE
Comment Error in Code Block

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#10847]
## Dynamo version

2.8.0.1737

## Operating system

Windows 10

## What did you do? 

Replaced variable with comment in Code Block

## What did you expect to see?

Disappearance of input port

## What did you see instead?

![errorComment](https://user-images.githubusercontent.com/5621624/86525451-d410b480-bea4-11ea-9793-811d768a2a2a.gif)
###

**Comment by iAliJ** [comment]
I think this behavior occurs because InPorts and OutPorts are not updated when there is no actual statement in the code block "only comments", I found a way to solve this but before creating PR I wanna know if there are any tests to run?

**Comment by Amoursol** [comment]
@aparajit-pratap are you able to help shed some light on the test situation for @iAliJ here please?

**Comment by iAliJ** [comment]
@Amoursol @aparajit-pratap I assume I need to run CodeBlockNodeTests?

![image](https://user-images.githubusercontent.com/47180374/129802552-91117f0f-938e-4bc7-9347-f19009dafc16.png)

**Comment by QilongTang** [comment]
Closing. This will be fixed as Dynamo 2.13.0 release. Thanks to @iAliJ
