### ISSUE TITLE
Trouble of Material.StructuralParameters  with Parameter.Nmae and Parameter.Value

### ISSUE THREAD

**Issue by hikozan** [DynamoDS/Dynamo#10855]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Revit2020/Dynamo 2.1.0 and Revit2021/Dynamo 2.5.?
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
![MaterialStructureParameters_sample_2020-07-06_12-34-16](https://user-images.githubusercontent.com/33724546/86731542-9b223c80-c06a-11ea-82a9-9013369fd2e7.png)
As you can see on the png file, I want get the properties of material and used Material.StructuralParameters and Parameter.Name and Parameter.Value.  The function of these nodes seems working, but there are error messages on the Parameter.Name and Prameter.Valu nodes.

## What did you expect to see?
It should be no error message!

## What did you see instead?

(Fill in here)

**Comment by Amoursol** [comment]
Hello @hikozan - Can you please provide a screenshot with the error message shown?

**Comment by hikozan** [comment]
I am sorry This was not "error". It just warning because the content of some properties were "null". 
I was O.K. I can handle the output from the node "Material.StructuralParameters" by Python script convert it to string
in case of Version 2.0.3.

**Comment by Amoursol** [comment]
@hikozan This issue should now be resolved by the Revit team in the DynamoRevit repo. If you are still experiencing this issue in a future release please do re-open this!
