### ISSUE TITLE
Dynamo Viewport Jumps/Pans when I press Run

### ISSUE THREAD

**Issue by wassimj** [DynamoDS/Dynamo#10908]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.7.0.8167

## Operating system

Windows 10

## What did you do? 

Pressed Run

## What did you expect to see?

The Viewport to stay the same as before I pressed Run

## What did you see instead?

The Viewport 'Jumped'/'Panned' to a different area of the graph
[bandicam 2020-07-19 13-20-06-370.zip](https://github.com/DynamoDS/Dynamo/files/4943689/bandicam.2020-07-19.13-20-06-370.zip)

**Comment by Amoursol** [comment]
Hello @wassimj - I cannot reproduce this on the released Sandbox version of Dynamo: 2.7.9206

Can you please try with the stable version and let me know if you are still experiencing this issue? 

![image](https://user-images.githubusercontent.com/12857357/87947941-0cea8500-ca72-11ea-8c82-161e3de7c47e.png)

**Comment by wassimj** [comment]
Hi Sol,
I just installed Dynamo 2.7.0.9206 fresh and ran a definition and it jumped on first run.

**Comment by mjkkirschner** [comment]
Hi @wassimj please share details of your display, like display scaling settings etc.

**Comment by wassimj** [comment]
Hi @mjkkirschner It is 1920x1080 @ 100%

**Comment by mjkkirschner** [comment]
Thanks @wassimj would you be able to record a gif or video of the behavior? I cannot reproduce it locally at this point.

**Comment by wassimj** [comment]
Hi @mjkkirschner You can see it in action at: https://cf-my.sharepoint.com/:v:/g/personal/jabiw_cardiff_ac_uk/ETPeW3-ITHNHqkNeusEiH6EBGAFQ4w0IbCbXZDnI_Pvviw?e=Qdcvf1

**Comment by mjkkirschner** [comment]
@wassimj apologies - I just got back to this and link has expired 😢  - can you share another?

**Comment by wassimj** [comment]
Hi @mjkkirschner I reset the expiration date to end of August. Here is the new link:
https://cf-my.sharepoint.com/:v:/g/personal/jabiw_cardiff_ac_uk/ETPeW3-ITHNHqkNeusEiH6EBGAFQ4w0IbCbXZDnI_Pvviw?e=VEdkfn

**Comment by mjkkirschner** [comment]
Thanks, I notice there are a bunch of viewExtensions installed.
I cannot reproduce this locally, please remove your extensions and see if it reproduces. We may then be able to track down if a particular extension is causing it.
