### ISSUE TITLE
Fehlerberciht von Dynamo 2.4.1.6326

### ISSUE THREAD

**Issue by Darkumbrat** [DynamoDS/Dynamo#10914]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Open my projekt

### What did you expect to see?
All my (visual) Code (with functional, string, filpath and number-blocks)

### What did you see instead?
Functional Codeblocks, no "string" or "number" or "filepath" block

### What packages or external references (if any) were used?
no

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.1.6326`

**Comment by Darkumbrat** [comment]
I saved my project the last time with string-blocks, number-blocks e.g.
If I didn't save ist, there has to be some "number" or"string" blocks, but there are none!

Please help me, because it's anoying and a waste of time, every time I open the project to fill up the missig blocks

**Comment by Amoursol** [comment]
Hello @Darkumbrat - is it possible for you to upload your .DYN file here for us to take a look?

**Comment by mjkkirschner** [comment]
There are many posts on the forum about this - in my experience, it's almost always an addin conflict. I am going to close this as theres not enough info, please review threads on the forum first, like this one:
https://forum.dynamobim.com/t/nodes-disappear/54183

and re open if the advice there does help with more information.
