### ISSUE TITLE
Wish: Make Manage Packages and Search For Packages scrolling more comfy

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1092]
Both of these dialogs can not be scrolled through using the mouse wheel, only by dragging the scrollbar on the right.

**Comment by andydandy74** [comment]
Online Package Search is now scrollable by mouse wheel - Installed Packages still isn't.

**Comment by Benglin** [comment]
This should now be fixed by [the pull request mentioned above](https://github.com/DynamoDS/Dynamo/pull/4298) and will soon be available on the daily master. Thanks for reporting anyway, @andydandy74! Enjoy the comfort.

**Comment by andydandy74** [comment]
Great, thanks!
