### ISSUE TITLE
Dynamo on iPad?

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#1093]
I'm sort of afraid of proposing this, but I'd love to be able to play with Dynamo on my iPad while the wife watches sit coms. A laptop without mouse access (I lie on my couch) does not really feel good, mostly because lack of panning.

Is this at all remotely possible?

Håvard

**Comment by Racel** [comment]
The next generation of Dynamo leverages web technologies and can be used on mobile devices. Closing.
