### ISSUE TITLE
Relatório de erros do Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by hrap94** [DynamoDS/Dynamo#10969]
when I write or create a code inside Dynamo, usually the geometry appears right on the other screen but in my case the geometry is not showing up, I don't know what to do, could you help me?

**Comment by Amoursol** [comment]
Hello @hrap94 - I have a few questions:

1. Are you using `Dynamo Sandbox` and do you have any other Autodesk software installed? Our Geometry kernel is only available in Sandbox if you have other Autodesk products.
2. Are you using Dynamo in Revit 2020 / 2021 on a clean machine? 
2. As per this image, do you have: **View** --> **Background 3D Preview** --> **Available Previews** --> **Background Preview** turned on? 
![image](https://user-images.githubusercontent.com/12857357/89540954-ba2bff80-d7cb-11ea-9b99-db4082f654f4.png)

**Comment by Amoursol** [comment]
Hello @hrap94 - As we have no received any additional information here we are going to close this issue for now. Please feel free to reopen if you are still experiencing any issues!
