### ISSUE TITLE
Tooltips disabled when geometry preview is turned off.

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#10984]
## Dynamo version

2.5 and up

## Operating system

Any

## What did you do? 

Hover over a node with a disabled preview state

## What did you expect to see?

The tooltip help, like this: 
![image](https://user-images.githubusercontent.com/29869395/89810318-e10b6e00-db0a-11ea-8931-9105dcc8cc37.png)

## What did you see instead?

No tooltip help, like this: 
![image](https://user-images.githubusercontent.com/29869395/89810355-ee285d00-db0a-11ea-819b-3f8d78e0b3e8.png)

**Comment by Amoursol** [comment]
@zeusongit - Was this fixed when you enabled the ability to rename nodes when preview was turned off?

**Comment by mjkkirschner** [comment]
no it's still a problem we should bring it in.

**Comment by Amoursol** [comment]
Fixed and in-product.
