### ISSUE TITLE
Export Image node returns null on failure

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#10980]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

All

## Operating system

Any

## What did you do? 

Used the export image node, which when successful returns a null value. 

## What did you expect to see?

Useful data (such as the file object which was exported)

## What did you see instead?

A list of null values

![](https://aws1.discourse-cdn.com/business6/uploads/dynamobim/original/3X/4/8/48d249333b28e8e30bb0862246798db5115cd5ef.png)

**Comment by iAliJ** [comment]
Hello @JacobSmall  

I would like to work on this issue.

**Comment by Amoursol** [comment]
@iAliJ - are you looking to contribute code to Dynamo? If so great! 😀  we would very much welcome that.

You can refer to https://github.com/DynamoDS/Dynamo/pull/11798 as predecent.

CC @QilongTang

**Comment by iAliJ** [comment]
> 
> 
> @iAliJ - are you looking to contribute code to Dynamo? If so great! 😀 we would very much welcome that.
> 
> You can refer to #11798 as predecent.
> 
> CC @QilongTang

Alright will refer to that thank you! And yes been using dynamo for over a year and always wanted to contributed to the open source as much as I could :smile:

**Comment by QilongTang** [comment]
This issue has been fixed by https://github.com/DynamoDS/Dynamo/pull/11858 and will be part of Dynamo 2.13.0
