### ISSUE TITLE
Dynamo background grid not showing

### ISSUE THREAD

**Issue by Salma-elahmar** [DynamoDS/Dynamo#10999]
# Issue Description
The Dynamo background grid does not appear, despite following suggested solutions in the dynamo forum. 
I am using revit 2020.1, dynamo version: 2.1.0.7733, on an HP laptop with windows 10 64-bit operating system, AMD A10 -9600P radeon R5, 2.4 GHz, 16 GB RAM.
![disabled amd radeon crossfire](https://user-images.githubusercontent.com/69671405/90230484-e3770c00-de19-11ea-8049-7dbfb8002476.jpg)
![dynamo version](https://user-images.githubusercontent.com/69671405/90230487-e40fa280-de19-11ea-996e-02fd72b8d4dd.jpg)
![revit graphic card settings](https://user-images.githubusercontent.com/69671405/90230490-e40fa280-de19-11ea-9c6e-e9c2a713f90a.jpg)
![system specs](https://user-images.githubusercontent.com/69671405/90230491-e4a83900-de19-11ea-981e-0ee7622ebc8d.JPG)
![windows graphic settings](https://user-images.githubusercontent.com/69671405/90230493-e4a83900-de19-11ea-9783-7d8ca05d42f3.JPG)

### What did you do?

- checked that the background preview option is enabled
- changed windows graphics settings: choosing Revit and assigning it to high performance
- AMD radeon catalyst control centre: from the switchable graphics applications settings: chose Revit and assigning it to high performance
- AMD graphics settings: advanced: disabled the AMD crossfire which allowed multi GPU operation
- updated the graphics card to the latest available version.

### What did you expect to see?
the dynamo grid

### What did you see instead?
nothing

### What packages or external references (if any) were used?
none

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by mjkkirschner** [comment]
can you share your dynamo log file from %appData%Dynamo etc etc logs/

**Comment by Salma-elahmar** [comment]
[dynamoLog_fd0b5f7f-4f63-45af-b67e-41770c861be6.txt](https://github.com/DynamoDS/Dynamo/files/5077283/dynamoLog_fd0b5f7f-4f63-45af-b67e-41770c861be6.txt)

Thank you for replying...here is the file.
although i didn't even start using dynamo yet to do anything..so i am not sure if the log file is useful.

**Comment by Amoursol** [comment]
@QilongTang @aparajit-pratap - Now that Mike's on sabbatical, can we get another team member to look at this?

**Comment by aparajit-pratap** [comment]
@Salma-elahmar could you make sure you have the necessary end-user DirectX runtimes installed. They can be found here: https://github.com/DynamoDS/Dynamo/tree/master/tools/install/Extra/DirectX. If that doesn't work, try the [FAQ](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ).

**Comment by Salma-elahmar** [comment]
I think the DirectX runtimes are already installed.

i disabled one of the graphic cards from the windows device manager and it did the trick.
previously i disabled it from the Radeon application settings but it seems that it didn't change anythings...both cards were still running.
But now although the dynamo grid problem is solved, i get an error message from revit every time i open it (see screenshot attached). i simply ignore it and move on but i am not sure if it must be addressed. Can anyone advise please??

Additionally, switching off one graphic card caused a serious of other visualization problems in general on my laptop. 

![revit error after diabling one graphic card R7](https://user-images.githubusercontent.com/69671405/91287075-8ec77f80-e78f-11ea-8e36-95a349e258e6.JPG)
![error on startup](https://user-images.githubusercontent.com/69671405/91287080-8ff8ac80-e78f-11ea-84bc-ca88953c3a16.JPG)

**Comment by QilongTang** [comment]
@Salma-elahmar Thanks, let us forward your screen shot to Revit group and see what they say.

**Comment by Salma-elahmar** [comment]
That would be great. Thank you!

**Comment by QilongTang** [comment]
@Salma-elahmar Here is what I got from Revit group

> There are a select few graphics cards which have been intentionally disabled and which would trigger this message. If they are receiving this message and don't have one of those cards, we should investigate why. It would be helpful to know: what version/year of Revit are they running? What model is the graphics card they had to disable?

**Comment by Salma-elahmar** [comment]
I am using Revit 2020.1, i have 2 switchable graphic cards; 
1. AMD Radeon (TM) R7 M340 which is the one i disabled
2. AMD Radeon R5 
windows 10 64-bit operating system

**Comment by QilongTang** [comment]
@Salma-elahmar Here is what I got from Revit team:

> It is safe to ignore. Both these cards are super low end gaming cards that can't handle most modern games. So they can work but performance will not be great...but no program will be with these cards. We are curious what Revit is using to detect this so we will look into that, but the customer does not need to wait for that.

**Comment by Salma-elahmar** [comment]
ok thank you. I hope they could resolve this dynamo visualisation issue, as now with only one graphic card enabled,  Autocad has serious visualisation issues so i cannot be working on both programs simultaneously.

**Comment by QilongTang** [comment]
@Salma-elahmar I hope that's the case as well. Given you have a workaround, I will close this for now. Thank you for all the commnucation helping us to identify another edge case. This issue will be searchable from internet so hope other users benefit from this in the future. Closing.
