### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by cheoleejj** [DynamoDS/Dynamo#11027]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by Amoursol** [comment]
Hello @cheoleejj  - are you able to add more information to the template, upload a .DYN file or log file? We need a bit more to be able to take any action as currently all we know is that you experienced a crash in Dynamo 2.6.

**Comment by Amoursol** [comment]
Hello @cheoleejj - As we have not received any additional information now for over two weeks we are closing this issue. If you want to reopen please feel free to do so with any more context you have!
