### ISSUE TITLE
Crash report from Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by meatngreenz** [DynamoDS/Dynamo#11030]
# Issue Description
I tried to add a path to dynamo for my packages it crshed dynamo and took revit down with it.
### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by Amoursol** [comment]
Hello @meatngreenz - are you able to add more information to the template, upload a .DYN file or log file? We need a bit more to be able to take any action as currently all we know is that you experienced a crash in Dynamo 2.5.

**Comment by Amoursol** [comment]
Hello @meatngreenz  - As we have not received any additional information now for over two weeks we are closing this issue. If you want to reopen please feel free to do so with any more context you may have!
