### ISSUE TITLE
Dynamo からのクラッシュ レポート 2.7.0.9206

### ISSUE THREAD

**Issue by sakamoto-fit** [DynamoDS/Dynamo#11034]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.7.0.9206`

**Comment by Amoursol** [comment]
Hello @sakamoto-fit  - Could you please fill in the template with more information here? Right now we don't have enough information to explore what caused your crash.

**Comment by Amoursol** [comment]
Hello @sakamoto-fit   - As we have not received any additional information now for over two weeks we are closing this issue. If you want to reopen please feel free to do so with any more context you may have!
