### ISSUE TITLE
Crash report from Dynamo 2.7.0.9206

### ISSUE THREAD

**Issue by guptha1** [DynamoDS/Dynamo#11083]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.7.0.9206`

**Comment by Amoursol** [comment]
Hello @guptha1 - Could you please let us know what you were doing when you experienced this crash? If you can upload the Stack Trace, images or a Dynamo file that would help us get to the bottom of this issue :)

**Comment by Amoursol** [comment]
Hello @guptha1   - As we have not received any additional information now for over two weeks we are closing this issue. If you want to reopen please feel free to do so and let us know what you were doing when you experienced this crash.
