### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hikozan** [DynamoDS/Dynamo#11100]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0.3
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

run dynamo

## What did you see instead?
crash
Runtime exception occured. The Type of StackValue is not Integer

   場所 ProtoCore.DSASM.StackValue.get_IntegerValue()
   場所 ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   場所 ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   場所 ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   場所 ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   場所 ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   場所 ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   場所 ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   場所 ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   場所 ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   場所 ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   場所 ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   場所 Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   場所 Dynamo.Scheduler.AsyncTask.Execute()

**Comment by Amoursol** [comment]
Hello @hikozan - Could you please tell us what you were trying to do when this happened?
