### ISSUE TITLE
My Dynamo is Getting Closed frequently

### ISSUE THREAD

**Issue by askgrkumar** [DynamoDS/Dynamo#11113]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

I am Using 2.3.0

## Operating system

Windows 10

## What did you do? 

Modeller, I am planning to Place the Lighting Fixtures with the CAD Points

## What did you expect to see?

Lighting Fixtures to be placed in the points

## What did you see instead?

Getting Closed.

**Comment by Amoursol** [comment]
Hello @askgrkumar - Is Dynamo crashing? And, are you able to provide us with a .DYN file for this?

**Comment by Amoursol** [comment]
Hello @askgrkumar  - As we have not had any response on this issue we are closing for now. Please re-open with more information if you are still experiencing the issue.

**Comment by askgrkumar** [comment]
Sincere Apologies dear,

As it is a Concept we do teach to our Students, how to use github & how to raise a Application Issues if any. Sorry if I've wasted your time.

Maybe accidentally, I have posted itseems. Generally I don't do publish. 

Hope you understand, Thanks
