### ISSUE TITLE
Cannot set class ShortName for Zero Touch Nodes

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/Dynamo#11117]
## Dynamo version

2.9.0.2585

## Operating system

Win 10

## What did you do? 

I want to set a class ShortName for Zero Touch Nodes classes so that in the library they are not displayed with their C# class name but with a custom one. I've tried either via a `DynamoCustomization.xml` and by adding a `[PreferredShortName("")]` attribute on my classes.

I've debugged Dynamo and it seems the `GetShortName` method in charge of picking these customisations is not being called at all:

https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Engine/NodeToCode/NodeToCode.cs#L69

Mapping namespaces to custom Categories is working as expected via the `DynamoCustomization.xml`.

Sample code:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<doc>
  <assembly>
    <name>SpeckleConnectorDynamoFunctions</name>
  </assembly>
  <namespaces>
    <namespace name="Speckle.ConnectorDynamo.Functions">
      <category>Speckle</category>
    </namespace>
  </namespaces>
  <classes>
    <class name="Speckle.ConnectorDynamo.Functions.SpeckleAccounts" shortname="Accounts">
    </class>
  </classes>
</doc>
```

or 

```csharp

namespace Speckle.ConnectorDynamo.Functions
{
  [PreferredShortName("Accounts")]
  public static class SpeckleAccounts
  {
    ...
```

**Comment by aparajit-pratap** [comment]
@teocomi the `PreferredShortName` attribute can only be used to create a custom variable name for the object when you invoke a "node to code" command using the nodes for that class as shown. Unfortunately, there is currently no mechanism to display a custom name for a class in the Dynamo library.
![n2c_preferred_shortname](https://user-images.githubusercontent.com/5710686/93498986-6e976600-f8e0-11ea-9576-585b6b8d91be.gif)
