### ISSUE TITLE
Public setter on PortModel.DefaultValue 

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/Dynamo#11118]
I'd like to set default inputs for a custom NodeModel node such as in: 

https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodeModels/Range.cs#L33

Currently this can be done in the main constructor via `InPorts.Add(new PortModel(PortType.Input, this, new PortData("","", defaultValue)));` but not in the `JsonConstructor` because `PortModel.DefaultValue` has an internal setter. 

I believe this is a bug and the setter should be made public so that default values can be set correctly also when opening saved definitions.

**Comment by QilongTang** [comment]
Look reasonable to me. @DynamoDS/dynamo What do you think?

**Comment by mjkkirschner** [comment]
@QilongTang let's do this.
