### ISSUE TITLE
Output Dictionary, from Python node, if keys is int fails.

### ISSUE THREAD

**Issue by Babinoff** [DynamoDS/Dynamo#11124]
## Dynamo version

2.8.0.2471

## Operating system

Windows 10

## What did you do? 

In Python node, send dictionary, what keys contain int,  to OUT.

## What did you expect to see?

Fine Dictionary in OUT
![if items](https://db3pap007files.storage.live.com/y4m0LcQnhrL9vf9_rukA8VlEKFfGcWsluZrf6QiC_5Ajj8gluWfX7ZruHyIOEeU02q-qSbC0MfYlI_wiKw-oohkHtGw8YrWnJHNtfedh7WszW7R_3c4yCgyjgYz6X74csYdVEViIUWGm7cOcfuTiG9K6J3QCdIT6p6jxUyGKxYMdatVzQf-J7BJNwuhVLMZzNtlVsPr2xJGStn7egN72gLXOw/if%20items%28%29.png?psid=1&width=795&height=520)

## What did you see instead?

"Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed.
Could not cast object 'System.Int32' to type 'System.String'."
![if keys is int fails](https://db3pap007files.storage.live.com/y4mRudDiBWhGJk9qWVtNUzGMR65xVtjgrxGnZaeH_6oAoZTMiMXNbdcoCYDvBNOaf5nAUruXI2nwHME6QcSAKkFDL91sbwf1CQvAgg8lrysGKwAXX908ZmgzR0oFtCO_ZcUPMefq13vMRixx5mu8eQhm63PnfGZwDlQZjbqMVITzdQEZ6ucy8hz5Hgm5UDuSWfsv_CDZUVaYzREFw6SITKuIQ/if%20keys%20is%20int%20fails.jpg?psid=1&width=1003&height=359)

![if keys is int but not in OUT](https://db3pap007files.storage.live.com/y4mtCOt5e6fUtmrX8xsEYKnp_Q672IEuY2f_dEhCcEDouiDt_d3wkbhn6px5OrCfaUN1qy8MUszJj8eww-FiM9jsNB9m2Dhif2Sgajkr54zMP2-8lfQyaeQSTk0dyN0mqezyGUXdbPkh1Jk3EZfwnlr7KeUPp8WLeAt0jYESQsUbcdjuBwZRHinjD7w2Es7y5d8jrC2PSyO-xsGwbEO2mg1JQ/if%20keys%20is%20int.jpg?psid=1&width=872&height=539)

**Comment by Amoursol** [comment]
Hello @Babinoff, 

Thank you for reporting this issue! However, the lack of integer support for dictionary keys is working as intended as Dynamo only supports `strings` for a few reasons, that are best explained in the following two links:

- Peter Boyer's reply to my query (Before joining Autodesk!) here: https://github.com/DynamoDS/Dynamo/issues/8497
- Aparajit Pratap's reply near the end of this thread for the DesignScript context: https://github.com/DynamoDS/Dynamo/issues/8759#issuecomment-382467614
