### ISSUE TITLE
Extension method from C# not picking up in Cpython but it does work with ironpython

### ISSUE THREAD

**Issue by JK-Lau** [DynamoDS/Dynamo#11159]
## Dynamo version
2.8

## Operating system
10

## What did you do? 
Created a C# extension method for a string type object and call that extension method in python using CPython engine

## What did you expect to see?
The extension to complete its intended function

## What did you see instead?
An error message of  
"Warning: AttributeError : 'str' object has no attribute '**{Extension method name}**' ['  File "<string>", line 74, in <module>\n', '  File "<string>", line 74, in <lambda>\n']"

## Notes
The extension work as intended on ironpython engine, but doesnt work with Cpython engine

**Comment by aparajit-pratap** [comment]
@mmisol?

**Comment by mmisol** [comment]
Hi @JK-Lau . Strings in the `CPython3` engine are different than in the `IronPython2` engine. They don't correspond to the `System.String` .NET class and you cannot really extend them. This is explained here: https://github.com/DynamoDS/Dynamo/wiki/Work-in-progress-to-improve-Python-3-support#python-primitives-are-not-net-objects-not-planned

Please re-open if I misunderstood.
