### ISSUE TITLE
CRASED WHEN ENABLING DYNAMAPS PACKAGE

### ISSUE THREAD

**Issue by andrzejSlomiany** [DynamoDS/Dynamo#11171]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
 Dynamo 2.0.4 Revit 2017.2.4

## Operating system

Windows 7

## What did you do? 

Tur on DynaMaps

**Comment by Amoursol** [comment]
Hello @andrzejSlomiany - this issue is with the Dynamaps Package, so best to talk directly to it's author, Mostafa El Ayoubi. You can reach him here: https://data-shapes.io/contact/
