### ISSUE TITLE
Crash report from Dynamo 2.8.0.2471

### ISSUE THREAD

**Issue by electric1625** [DynamoDS/Dynamo#11175]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.8.0.2471`

**Comment by Amoursol** [comment]
Hello @electric1625 - Can you please provide more information (i.e in the template provided, or upload the .dyn graph that crashed) so that we have reproducible steps to investigate? Unfortunately this post doesn't currently contain enough information for us to do anything with it.
