### ISSUE TITLE
Crash report from Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by mustafateksoy** [DynamoDS/Dynamo#11174]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`

**Comment by Amoursol** [comment]
Hello @mustafateksoy  - Can you please fill in the template here? As it stands we don't have enough information to action this any further as we need a reproducible case 😊

**Comment by mustafateksoy** [comment]
> Hello @mustafateksoy - Can you please fill in the template here? As it stands we don't have enough information to action this any further as we need a reproducible case 😊

Sorry, I am very new to how Github works. The next time when I have the same problem I will fill in the template.

**Comment by Amoursol** [comment]
No problem at all! For us to be able to take action on the report we simply need context:

- Uploaded .dyn file and steps you can take to reproduce the crash
- Stack Trace (Lots of text that shows up in the error message when Dynamo crashes)
- Sometimes also machine context (i.e. what GPU, Windows vs. Mac vs. Linux etc.)
