### ISSUE TITLE
Dynamo is not working when i press "Run"

### ISSUE THREAD

**Issue by Jovika199** [DynamoDS/Dynamo#11181]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.3
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

I tried a code and clicked "run"

## What did you expect to see?

I expected to see the result of my coding

## What did you see instead?

But whenever I click run, it shows not responding and freezes, and the program closes.

**Comment by QilongTang** [comment]
@Jovika199 This might be an instance of bug or issue we want to fix in Dynamo, or workflow we did not support in previous version of 2.3.0, do you mind sharing this workflow with our team somehow? If it contains sensitive info which you cant share on github, we can contact by email.

**Comment by Jovika199** [comment]
@QilongTang Thank you so much for replying, 
![11](https://user-images.githubusercontent.com/72816639/95914480-d4c7b980-0db6-11eb-9c92-381a36946000.PNG)
![22](https://user-images.githubusercontent.com/72816639/95914485-d5f8e680-0db6-11eb-87eb-68e51282e6e5.PNG)

This is the file that I was working on, but this problem is not just with this file, any previous file that I open now and click "Run" it just shows not responding. I tried to do Revit updates, but nothing worked. 

![InkedCapture_LI](https://user-images.githubusercontent.com/72816639/95915102-bb733d00-0db7-11eb-8682-446ddabd600c.jpg)
this is what happens... :(

**Comment by mjkkirschner** [comment]
@Jovika199 do you still happen to have the .dyn for this graph - can you upload it here?

**Comment by Jovika199** [comment]
@mjkkirschner, this issue was solved by itself some weeks back but thank you so much for asking. <3
