### ISSUE TITLE
Problems with placing family instance of Windows or Doors

### ISSUE THREAD

**Issue by michaelbergin** [DynamoDS/Dynamo#1120]
Creating a curve-based model, using Wall by Curve to create some walls.
Evaluating those curves to produce an XYZ where I would like to place windows or doors.

Receiving an error with various attempts to make it so :
        Family symbol is not valid for this instance. Parameter name: value

Tried moving the point in the Z axis, using Create Family and Create Family by Level, Changing the levels and elevations of levels, rebuilding the entire script...

![image](https://f.cloud.github.com/assets/1483331/2175987/c15cde00-95c9-11e3-96cc-56b01f22e5fe.png)

Version - 0.6.3.22045
https://www.dropbox.com/s/rpojkyrpgkixm5l/dynamo-Outline.dyn

**Comment by jhubers** [comment]
Why is there not a solution without scripting to place doors and windows in a wall? Seems to me that this is one of the first things a novice with Dynamo would like to do... In fact one of my students wanted to make a terrace wall with many holes. Dynamo seemed the right tool. But finally had to use the array tool of Revit and do the arithmetic by hand. A missed chance to introduce some students to Dynamo.
![image](https://cloud.githubusercontent.com/assets/1529297/13488652/e0c48698-e122-11e5-9de7-bd0c4942e02e.png)
