### ISSUE TITLE
Error: No Module Named shapley.geometry 

### ISSUE THREAD

**Issue by serendipity532** [DynamoDS/Dynamo#11206]
![image](https://user-images.githubusercontent.com/28829619/97236027-6cf37480-17a1-11eb-82f6-b37c572ae422.png)
I am trying to write a python node in dynamo which tests if a point is within a polygon. To do this I need to import Polygon via 
**from shapely.geometry import Point, Polygon**
adding this line to the python node returns the error in the image above. Does anyone have any idea how I might be able to resolve this? I am using Dynamo 2.3  and Windows 10. Thank you! 

If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

**Comment by Amoursol** [comment]
Hello @serendipity532,

Shapely is a Python module that doesn't ship out-of-the-box with Dynamo. It's also built upon Python 3, so will only be available inside Dynamo from versions 2.8 onwards (Which you can get in Sandbox now, and all the hosts in future releases). You'll need to install the module and import it into your Python node. 

Please go to this wiki page and follow the instructions on how to do so 😊  https://github.com/DynamoDS/Dynamo/wiki/Customizing-Dynamo's-Python-3-installation
