### ISSUE TITLE
Package keywords ignored in search on dynamopackages.com

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1121]
Looks like the package keywords are no longer relevant for search operations on the package manager website. Try searching for "checkerboard". It'll only return a result in the package search that is built into Dynamo itself.

**Comment by Racel** [comment]
You are correct. We are trying to figure out the next generation of package manager UI that will work on both desktop and web. Closing this for now as this will be addressed when this work is complete.
