### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by DonniaT-H** [DynamoDS/Dynamo#11229]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Tried to add another drive for path to packages - it is a cloud drive location

### What did you expect to see?
the path to be acceptable

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
nothing new here

### Stack Trace
```
can't get to anything - appears to have locked up entire Revit 2020
```

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by QilongTang** [comment]
@DonniaT-H Hi, this is a known issue and here is our team's recommendation https://github.com/DynamoDS/Dynamo/wiki/Loading-Packages-with-Binaries-from-a-Network-Location

**Comment by DonniaT-H** [comment]
I do have these on a mapped network drive. Now my packages do not show up in my library - more searching online.

**Comment by DonniaT-H** [comment]
The crashing was due to duplication locations of packages - they are now only on the mapped network drive.
This can be closed.
