### ISSUE TITLE
Informe de conflictos de Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by delcampodavid** [DynamoDS/Dynamo#11239]
![1](https://user-images.githubusercontent.com/65350306/98833666-99b0b880-243e-11eb-8e67-395863e08f1d.PNG)
![2](https://user-images.githubusercontent.com/65350306/98833670-9a494f00-243e-11eb-985c-1096abc6fec7.png)

# Issue Description
Please fill in the following information to help us reproduce the issue:
There is no 3D visualization of elements in Dynamo, nor preview 3D elements visualization.
### What did you do?
I configured Nvidia to use Revit as Advanced mode using GPU by default with this program, as well as set the Windows graphic configuration to use Revit with GPU instead of integrated graphics.

### What did you expect to see?
I expected to have the problem solved.

### What did you see instead?
Dynamo it's not showing the 3D geometry preview.

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
Hi @delcampodavid - have you installed https://www.microsoft.com/en-us/download/details.aspx?id=8109 dx 10 end user runtimes?

**Comment by delcampodavid** [comment]
I have currently installed DirectX 12.

What are the "end user runtimes"? I can try.

**Comment by mjkkirschner** [comment]
that link is for dx 10 - it is required for the version of Dynamo you are using (at least the one noted in the crash above)

**Comment by delcampodavid** [comment]
It worked!!!

So accurate! Thank you very much for your tip, I spent a lot of time thinking about how to solve this problem I finally it's done.

Thanks!
