### ISSUE TITLE
Import and Remove Imported Library in dynamo Revit

### ISSUE THREAD

**Issue by HossamMoussa** [DynamoDS/Dynamo#11247]
I try to import a .dll (zero touch node library) in dynamo Revit but if i remove it again form list of imported nodes and packages and restart dynamo (not Revit). i Try to load another .dll with the same name, dynamo load it but the old one.

it works fine if you use dynamo sandbox but if you use dynamo in Revit you have to close dynamo and close Revit to get this result. That means that it works just for dynamo Sandbox and not for Dynmao in Revit

**Comment by mjkkirschner** [comment]
Yes, your observations are correct. Currently there is no way to unload an assembly from Revit's process without assembly domains -  so Revit must be restarted to unload the zt binary.

in newer versions of .net assembly unloading is possible, but we won't be able to take advantage of it until Revit and other host products - and Dynamo itself move up to dotnetcore / .net 5.

https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability

**Comment by aparajit-pratap** [comment]
@HossamMoussa sorry for misleading you here. I got confused with a different scenario.
