### ISSUE TITLE
Solid.ByLoft fails 

### ISSUE THREAD

**Issue by egmodelab** [DynamoDS/Dynamo#11264]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.7.0.9206

## Operating system

Windows 10

## What did you do? 

Attempted to loft pairs of Curves as solids

## What did you expect to see?

Solid geometry

## What did you see instead?

Some curves lofted as solids, while others failed: "Warning: Solid.ByLoft operation failed. Unable to loft! : SOLID_NOT_MADE -- A solid body could not be made"

**Comment by aparajit-pratap** [comment]
@egmodelab a similar was brought to our attention by Michael GG. We are tracking this.

**Comment by avidit** [comment]
Fixed in 2.11
