### ISSUE TITLE
Broken Link from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by AndrellLaniewicz** [DynamoDS/Dynamo#11277]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Clicking on Dynamo Dictionary links takes you to 404 page

### What did you do?
Clicked on link

### What did you expect to see?
Dynamo Dictionary

### What did you see instead?
Error 404

### What packages or external references (if any) were used?
nothing

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by QilongTang** [comment]
hi @AndrellLaniewicz , can you tell us which node it is? The dictionary link should have been disabled for all of the nodes since Dynamo 2.1.0 so I am quite surprised if this happened to you on Dynamo 2.6.1.

**Comment by AndrellLaniewicz** [comment]
It isn't in a node - it is in the main interface. The Help Dropdown click on Dynamo Dictionary. I'm on the most current according to Dynamo's "About"

**Comment by QilongTang** [comment]
@AndrellLaniewicz I see. Confirmed yes this is an issue, we will work on the fix

**Comment by QilongTang** [comment]
@AndrellLaniewicz The link should work now, can you verify?

**Comment by AndrellLaniewicz** [comment]
It does! Thank you so much!
