### ISSUE TITLE
Surface.TrimWithEdgeLoops returns edge geometry with eccentricities

### ISSUE THREAD

**Issue by egmodelab** [DynamoDS/Dynamo#11279]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.7.0.9206

## Operating system

Windows 10

## What did you do? 

Attempted to return trim surfaces using TrimWithEdgeLoops.

## What did you expect to see?

A series of trim surfaces with edges that mirror the curve tool used for the trim.

## What did you see instead?

Some surfaces had eccentricities along their edges (ie. a curve, originally with a smooth curvature gradient, returned a surface with an edge that was 'bumpy').

**Comment by Amoursol** [comment]
@egmodelab - We have fixed a bug with the **Surface.TrimWithEdgeLoops** node in the `Dynamo 2.9` release. Are you able to test your workflow inside of this version of Sandbox? If so, would be good to know if it solves your problem, otherwise we can investigate further.

**Comment by egmodelab** [comment]
@Amoursol we work in Dynamo for Alias and do not have access to Revit. Is Revit still required to use Sandbox? Thanks.

**Comment by Amoursol** [comment]
Hello @egmodelab - You don't need Revit anymore, no! You can now access Sandbox by itself, please have a read here: https://dynamobim.org/a-new-way-to-get-dynamo-sandbox/ 😁 

Please let me know if there is anything you come across that doesn't make sense, but the blog post should pretty much spell out the steps.

**Comment by mjkkirschner** [comment]
please reopen with more info.
