### ISSUE TITLE
I can no see 3D background in Dynamo. Help Please!

### ISSUE THREAD

**Issue by Luismg888** [DynamoDS/Dynamo#11270]
I have installed Revit on a new computer and I cannot view the 3D background in Dynamo
![Dynamo 21_11_2020 02_21_37](https://user-images.githubusercontent.com/74807535/99868332-67baf700-2ba0-11eb-9eb5-c189060fca9c.png)

**Comment by QilongTang** [comment]
@Luismg888 Hi, can you compare your local env with our trouble shooting wiki: https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#troubleshooting

**Comment by Amoursol** [comment]
Hello @Luismg888 - Did you manage to try the steps that @QilongTang mentioned above?

**Comment by Luismg888** [comment]
Hello @QilongTang , @Amoursol 
 Thank you very much. I had to download the updates for my graphics card. Only then can you set the Dynamo background.
I have solved the problem.

**Comment by QilongTang** [comment]
@Luismg888 Glad it worked. In the future, please keep us updated if you see any other issue.

**Comment by Luismg888** [comment]
Got it
