### ISSUE TITLE
inicie Dynamo desde revit 2021

### ISSUE THREAD

**Issue by 231261** [DynamoDS/Dynamo#11281]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by Amoursol** [comment]
Hello @231261 - Please reopen this issue with the template filled in with additional information if you wish us to investigate further. Unfortunately as it stands there is not enough for us to further action your report. We would be looking for an uploaded .DYN file, screenshots and/or reproducible steps.
