### ISSUE TITLE
Cannot find excel that has been installed 

### ISSUE THREAD

**Issue by zhangzhang3399** [DynamoDS/Dynamo#11298]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

## Dynamo version

2.0.2

## Operating system

(e.g. Windows 7

## What did you do? 
I have successfully installed the Office 2010 version of Excel, but dynamo still prompts that excel is not installed on this machine when using the excel related nodes. 
Can you tell me about different versions of dynamo for Revit ?

revit 2018 version

Corresponding excel version  2010

**Comment by mjkkirschner** [comment]
can you try installing: https://www.microsoft.com/en-us/download/details.aspx?id=3508 ?

**Comment by zhangzhang3399** [comment]
Thank you very much for your patient and meticulous reply. I will try to install the software according to your method.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DynamoDS/Dynamo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 凌晨3:13
收件人:&nbsp;"DynamoDS/Dynamo"<Dynamo@noreply.github.com&gt;;
抄送:&nbsp;"1141262836"<1141262836@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DynamoDS/Dynamo] Cannot find excel that has been installed  (#11298)





 
can you try installing: https://www.microsoft.com/en-us/download/details.aspx?id=3508 ?
