### ISSUE TITLE
support transparency for surfaces in background preview and watch

### ISSUE THREAD

**Issue by tatlin** [DynamoDS/Dynamo#1130]
I'm tessellating a complex hermite surface and am finding the resulting geometry lines are quite hard to see because of the original surface's curvature. I can currently disable preview of the original surface but it would be better if i could set the surface to be 50% transparent.
![image](https://f.cloud.github.com/assets/1142008/2186871/deb8087e-97ec-11e3-850f-47a5f5204014.png)
![image](https://f.cloud.github.com/assets/1142008/2186875/eae6dac6-97ec-11e3-808c-c09e30c14894.png)

**Comment by ikeough** [comment]
@tatlin Color and transparency are now both available.
