### ISSUE TITLE
Rapport d'erreur de Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by NaderBoutros** [DynamoDS/Dynamo#11323]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Following tutirial on Excel to Revit on https://dynamobim.org/learn/#videoTut

### What did you expect to see?
just a warning to fill in id for codeblock content : Revit.ElementSelector.ByElementId(id);

### What did you see instead?
Bug error

### What packages or external references (if any) were used?
nothing

### Stack Trace
```
Runtime exception occured. The Type of StackValue is not Integer

   à ProtoCore.DSASM.StackValue.get_IntegerValue()
   à ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   à ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   à ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   à ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   à ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   à ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   à ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   à ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   à ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   à ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   à ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   à Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   à Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment]
Hello @NaderBoutros - It looks like there was a crash associated with using a non-integer (whole number) value, but I'm unable to reproduce inside of Revit. 

Are you able to upload a .DYN file, or a screenshot of your work for us to test? 😊 

What I did: 
![image](https://user-images.githubusercontent.com/12857357/101186135-ae890200-3620-11eb-9e02-6e396e90445a.png)
