### ISSUE TITLE
Dynamo sandbox 2.8 / 2.9 startup crash report

### ISSUE THREAD

**Issue by Michaelvantelgen** [DynamoDS/Dynamo#11357]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 

2.8, 2,9

## Operating system 

Windows 10 pro

## What did you do? 

Start up Dynamo sandbox by doubleclicking exe file

## What did you expect to see?

Dynamo starting regularly

## What did you see instead?

See attached images.

Only fix is to restart pc.

![message 1](https://user-images.githubusercontent.com/3114453/101886126-59f30300-3b9b-11eb-82fe-e35f7726b94a.png)
![message 2](https://user-images.githubusercontent.com/3114453/101886128-5a8b9980-3b9b-11eb-9e75-faeb58c40bb2.png)

**Comment by mjkkirschner** [comment]
please remove sandbox from one drive - it probably is considered a "remote source" by windows and blocks loading of dlls reliably there.

**Comment by Michaelvantelgen** [comment]
Thanks Michael, I will try that and report back if it doesn't solve the issue.

I didn't mention this yet, this happens mostly after a prior successful startup of Dynamo (from the OneDrive location).

Michael

**Comment by mjkkirschner** [comment]
please reopen is still reproducible
