### ISSUE TITLE
ConvexHull2D output not as expected

### ISSUE THREAD

**Issue by jamustoh** [DynamoDS/Dynamo#11364]
## Dynamo version

Dynamo 2.0.1

## Operating system

Win 10

## What did you do? 

Using ConvexHull2D to achieve a curve but it did not go as what I wanted. 
![image](https://user-images.githubusercontent.com/76026186/102169443-2f6fb580-3ecd-11eb-811e-db077b30607f.png)

## What did you expect to see?

![image](https://user-images.githubusercontent.com/76026186/102169306-de5fc180-3ecc-11eb-8833-917881c1dc4f.png)
I was hoping to achieve the convex hull with the blue lines included. Is there a way to achieve what I want without ConvexHull2D? I need a general nodes that involves all the outer points.

## What did you see instead?

![image](https://user-images.githubusercontent.com/76026186/102169356-f5061880-3ecc-11eb-8d06-66c3681e6ced.png)
The two points that I wanted are not included in the convex hull.

**Comment by mjkkirschner** [comment]
we can't tell what nodes you are using inside your custom node, but please see discussion at https://github.com/DynamoDS/Dynamo/issues/7229 - built in convex hull is for 3d sets - you can try the ampersand & package's convex hull for a 2d version.

**Comment by dimven** [comment]
The convex hull result is actually correct, you just forgot to connect the first to last point in your PolyCurve.ByPoints node. Tho it sounds like you're not actually interested in the convex hull but in the alpha shape of those points.
