### ISSUE TITLE
Empty background view

### ISSUE THREAD

**Issue by david939david** [DynamoDS/Dynamo#11376]
## Dynamo version
2.10.0.3445

## Operating system
Windows 10
AMD FX 8350
AMD Radeon HD 7800

## What did you do? 

I wrote a script for Robot, geometry appears in Robot but not in Dynamo Sandbox - in 3D view there is only empty coordinates system. To be honest it has never worked for me, when I was on Windows 8.1 and now it's the same, so I think that it is something concerning my graphic card.

EDIT: I've just tried to model 3D geometry not by Structural Analysis package, but through default geometry nodes and background view is working fine - so what could be the problem? Maybe it's working like it should, cause then I can change line to bars in Robot and everything is visible.

## What did you expect to see?

3D geometry in background view in Dynamo

## What did you see instead?

Empty 3D coordinates system.

**Comment by mjkkirschner** [comment]
It sounds to me like you are expecting robot geometry types to have 3d visualizations, I don't think thats the case.
@Amoursol - where should this issue be redirected?

**Comment by david939david** [comment]
Just the opposite - I see only the dynamo geometry types (points, lines), so then I can transform them to Robot analytical nodes or bars. The case is that if I use structural package nodes (like analytical nodes and bars) from the beginning, they doesn't appear in 3D dynamo cakground at all - maybe it's a normal behaviour, I'm not sure.

**Comment by Amoursol** [comment]
Will get the Robot team to have a look at this issue and provide feedback @david939david 😊

**Comment by maciekkubica** [comment]
Hi @david939david ,

What you are observing is a normal behavior of Robot Structural Analysis(RSA) plugin for Dynamo. The main function of RSA nodes is to generate structure in RSA based on its parametric definition in Dynamo. So as long as what you get in RSA corresponds to what you defined in Dynamo everything is OK.

As it currently stands we don't provide visual representation RSA nodes it Dynamo but we may consider doing it in the future.
The only workaround available at the moment is using native Dynamo geometry elements like points, lines and surfaces to create nodes, bars and panels in RSA. That way you can get a visual representation in Dynamo that corresponds to the structure definition in RSA with help of Dynamo nodes.

**Comment by david939david** [comment]
Thank you very much for the response. Sometimes it doesn't update or geometry is wrong, but restarting Dynamo always helps.
