### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786 - Nodes not Visible, no crash

### ISSUE THREAD

**Issue by rkoehlerHoffman** [DynamoDS/Dynamo#11375]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Opened Dynamo from Revit 2021 and then launched a script I have used previously, even in that version of revit.

### What did you expect to see?
My script

### What did you see instead?
All the lines connecting nodes were present, but the nodes were not visible, the script could not be run

### What packages or external references (if any) were used?
LunchBox
Clockwork

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by rkoehlerHoffman** [comment]
Dynamo Core 2.6.1.8786
Dynamo Revit 2.6.1.8850

Windows 10 Pro
Version 20H2
OS Build 19042.685

**Comment by rkoehlerHoffman** [comment]
![Screenshot 2020-12-21 103315](https://user-images.githubusercontent.com/76443803/102799300-f9707c80-4377-11eb-88f9-de3266859c67.jpg)

**Comment by timhevel** [comment]
same problem!

**Comment by rkoehlerHoffman** [comment]
That was the problem for me as well.

**Comment by mjkkirschner** [comment]
Is PyRevit updated to the latest version?

**Comment by timhevel** [comment]
jup 4.8.4

**Comment by rkoehlerHoffman** [comment]
It was at the time, now it crashes upon the launch of Revit after changing the selection for its IronPython Engine as noted here: 

[](https://github.com/eirannejad/pyRevit/issues/1101)

**Comment by rkoehlerHoffman** [comment]
It does not appear link posted, but title of post on GitHub is: pyRevit interferes with Dynamo #1101

https://github.com/eirannejad/pyRevit/issues/1101
