### ISSUE TITLE
Crash report from Dynamo 2.4.1.6394

### ISSUE THREAD

**Issue by roundbananas** [DynamoDS/Dynamo#11382]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Occasionally when I open a dyn file from Civil 3d 2020, the visual map is missing a whole bunch of nodes, links and groups that I'd previously created and saved. This has happened with several dyn files, on different occasions/sessions of using Civil3D/Dynamo visual editor.

### What did you expect to see?
The nodes and links and groups I'd created before I saved and closed the dyn file.

### What did you see instead?
Only a couple of the nodes/links/groups. Most of them just disappeared.
Standard nodes such as Code Block, Python Script and Watch were among those missing.

I closed and relaunched dynamo and civil3d and reopened my dyn file twice, before the nodes reappeared.

### What packages or external references (if any) were used?
I've got Bumblebee add-on (not using any of these nodes in this current dyn file), and Autodesk Civil3d toolkit add-on (I use several of those nodes. 

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
It's not a 'crash' issue. 
cheers

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.1.6394`

**Comment by roundbananas** [comment]
Dynamo core version 2.4.1.6394
Dynamo Civil 3d version 2.4.1.2161

Civil3d 2020 version 13.2.890.0

Windows 10 Enterprise
Intel Core i7-9750H 2.6GHz
64GB ram
64bit

I'm not able to reproduce the error. It just seems to happen sometimes, randomly.

**Comment by Amoursol** [comment]
Hello @roundbananas - When you say the visual map is missing a bunch of things, does it appear random or a consistent set?

For example:
1. Are you missing only wires? Or only Nodes? 
2. Are you missing all annotation features?
3. Are you missing only custom nodes? Or only out of the box nodes? Or a mixture?
4. Is it happening when you open a graph from a different version? Such as Dynamo 1.3 --> 2.0, or 2.0 --> 2.6

**Comment by roundbananas** [comment]
Hi @Amoursol
Thank you for following up. Sorry for the delay. It's finally happened again and I've captured some more details.

Scenario: Yesterday I worked on a dyn file in dynamo for several hours, no problem. I created a bunch of new nodes, wires and groups. This morning I turned on my computer, opened Civil 3d, opened the dwg I'm working on, opened dynamo and the dyn file. (like most other times). 
What I saw (screenshot 1): The dynamo graph was missing a lot of nodes, wires and groups. It appears that the missing nodes were all python nodes, as well as anything immediately downstream of a python node (eg watch nodes, as well as any other nodes that connect directly to the OUT of a python node, and their wires).

I tried closing the dyn file and reopening, closing dynamo and reopening. Nodes, wires were still missing.
Only closing dynamo and civil 3d, then reopening it all again seemed to fix it (Screenshot 2).

See attached screenshots.

I'm only using one version of Dynamo. All graphs created and opened in same version.
Hope that helps.
cheers
Carl
![Dynamo_Screenshot1_missing_content_210113](https://user-images.githubusercontent.com/42287840/104389023-4403a400-5586-11eb-92d9-3688a1e3113e.PNG)
![Dynamo_Screenshot2_correct_content_210113](https://user-images.githubusercontent.com/42287840/104389032-49f98500-5586-11eb-98a9-0b7e9df7e391.PNG)

**Comment by Amoursol** [comment]
@CoolStarLee @mjkkirschner - Any ideas here on whether or not this is Dynamo Core of Civil 3d specific?

**Comment by mjkkirschner** [comment]
This is usually caused by an addin - it can also be caused by Civil/Acad itself, - I would make sure Dynamo and Civil are fully upated. Then try removing all addins in Civil and see if you can reproduce it then.

**Comment by mjkkirschner** [comment]
hmm - on second look the behavior is a bit more specific than in previous cases - (types of nodes not loading) can you please share your log file? I'm not 100% sure where it should be in a Civil install - @CoolStarLee will know - 

But it will in a Logs folder likely near where packages are downloaded.

You can also open the console inside Dynamo and copy/paste that to get some of the info.

**Comment by roundbananas** [comment]
Thanks @mjkkirschner 
Two log files attached corresponding to the screenshot I posted above. I notice there's a bunch of lines in the logs that say: "connector d1494d99-5d52-469b-97bf-858465b90c11 could not be created, start or end port does not exist"
The dynamo program uses nodes from Civil3DToolkit package.
cheers

[dynamoLog_00e199eb-bff8-4349-8af2-bcf10a4c6d78.txt](https://github.com/DynamoDS/Dynamo/files/5840311/dynamoLog_00e199eb-bff8-4349-8af2-bcf10a4c6d78.txt)
[dynamoLog_1872738c-41c4-4689-95f1-f1b3bb098a7b.txt](https://github.com/DynamoDS/Dynamo/files/5840312/dynamoLog_1872738c-41c4-4689-95f1-f1b3bb098a7b.txt)

**Comment by mjkkirschner** [comment]
@roundbananas - AFAIK civil connection is a package that is supposed to function inside Revit, not inside Civil (it interoperates between them but depends on Revit apis) - I think theres a different package for that - CivilToolkit.

I would try removing that package.
