### ISSUE TITLE
3d View don't exist Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by amraboali** [DynamoDS/Dynamo#11392]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by mjkkirschner** [comment]
@amraboali please provide more info so we can help address this issue.

**Comment by amraboali** [comment]
When using Revit 2021 ‘s Dynamo 3D View does not view 



but when using Dyamo Sandbox 3D View Exist 







how to fix revit 2021



Sent from Mail for Windows 10

**Comment by amraboali** [comment]
![1](https://user-images.githubusercontent.com/77152297/104699817-f620a480-571b-11eb-9522-3af15d7ad1e8.PNG)
![2](https://user-images.githubusercontent.com/77152297/104699822-f751d180-571b-11eb-88fd-4882efe8b033.PNG)



How to fix Dynamo in revit 2021
