### ISSUE TITLE
Unsupported Input Type for Integer Slider

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#11401]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.10.0

## Operating system
Windows 10

## What did you do? 
use Integer sliders as inputs

## What did you expect to see?
them working as inputs

## What did you see instead?
![image](https://user-images.githubusercontent.com/15744724/104356861-b1053400-54c9-11eb-9346-cf4994159d2e.png)

FWIW, I made them double sliders and it worked. Does this mean integer slider supports for Dynamo player is getting deprecated?

**Comment by mjkkirschner** [comment]
Hi @johnpierson - we updated sliders in Dynamo to support int64 - long and some code in player was only supporting int32 - it's fixed in latest versions of player.

**Comment by QilongTang** [comment]
@johnpierson Not really, please check our release notes. I think you are trying to use a legacy version of GD and a newer version of Dynamo so the GD client is not up-to-date yet. 
1. You will need to make sure you are using Int64 slider(which is new). I would confirm by create a new DYN in your targeted Dynamo v2.10.0 than opening a legacy DYN.
2. @nate-peters Or @saintentropy can chime in if the newer version of GD client is released or not, if not, simply wait for it :)

**Comment by johnpierson** [comment]
Yeah, I am running 2020 on Dynamo Core 2.1.0. So it isn't a "typical" setup.

So no worries on that one. I will migrate to a double slider for now and ship it to the customer that way.
