### ISSUE TITLE
Package Load Failing

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#11403]
## Dynamo version

2.6.0

## Operating system

Windows 10

## What did you do? 

User mentioned they are loading Rhythm in Dynamo.

## What did you expect to see?

Loaded

## What did you see instead?

![image](https://user-images.githubusercontent.com/15744724/104518954-d7080280-55b5-11eb-83d8-5170c48c1306.png)

**Comment by QilongTang** [comment]
This is failing due to the certificate checking mechanism, but the package should not be installed to this location by default right？ @saintentropy

**Comment by johnpierson** [comment]
That was my assumption to regarding Package Location. (This is a report from a user and I suggested to move to appdata first and see if it helps)

**Comment by QilongTang** [comment]
@johnpierson Yeah, that should work

**Comment by johnpierson** [comment]
That did it. Thanks @QilongTang
