### ISSUE TITLE
Absturzbericht von Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by BuYv1** [DynamoDS/Dynamo#11422]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Tried to list by Bool Mask with a smaller as.

![image](https://user-images.githubusercontent.com/77834302/105478154-1cf25400-5ca3-11eb-9a68-e48f6f5b6f19.png)

Why does the bool mask work for equal objects but not for "smaller as"?
How can i fix that?

Thanks for your respond.

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by BuYv1** [comment]
Hello here is a screenshot of my issue:
![image](https://user-images.githubusercontent.com/77834302/105478394-693d9400-5ca3-11eb-9d36-d3898bbd6d34.png)

**Comment by Amoursol** [comment]
Hello @BuYv1 - This question is betters suited to the [Dynamo Forums](https://forum.dynamobim.com/) if you want a swift answer! 

I don't speak Deutsch, but using Google translate, this is the error it gives me:

`Warning: internal error, please report: dereferencing a non-pointer. Internal error, please report: dereferencing a non-pointer List.FilterByBoolMask failed.`

In this case, what is most likely happening is that one of the values coming out of your **Element.GetParameterValueByName** node is a `null` (Or nothing) and what this error means is that the node is trying to process a nothing, and failing. 

The input of **mask** simply needs a list of `true` and `false` values to come in that has the same list length, and rank (Depth) of the inptu into the **list** input.

**Comment by BuYv1** [comment]
Thank you for this solution. It was indeed the problem that not all Parameters had a value.

**Comment by Amoursol** [comment]
You are most welcome @BuYv1 ! Glad to be able to help 😊
