### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by hoangdt80s** [DynamoDS/Dynamo#11438]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Hit "Run" in Dynamo

### What did you expect to see?
Expected to see data returned

### What did you see instead?
warning 

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19041.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by hoangdt80s** [comment]
Dynamo Revit: 2.3.0.8352
Dynamo Core: 2.3.0.5885

Operating System: Window 10

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.

**Comment by RobertGlobant20** [comment]
I was testing a github action workflow then I'm closing this issue.
