### ISSUE TITLE
zero-touch node does not give GD any outputs

### ISSUE THREAD

**Issue by HadiMoosavi** [DynamoDS/Dynamo#11430]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I have made a few zero-touch custom nodes in Visual Studio using C# under the same project; so one single package.
I have some classes. and the code is not very complicated. no call on RevitAPI or anything like that.
I published locally in Revit Dynamo and tried it in a graph successfully and also in Sandbox.

It also exports successfully into generative design (GD).

However, it looks like all my zero-touch nodes output null GD environment.

### What did you expect to see?
I did a cross product study and output from my nodes is always null even if the node output is independent from the graph inputs.

### What did you see instead?
Null output from my zero-touch nodes
### What packages or external references (if any) were used?
No external references.
Here is my references in the Visual Studio
![image](https://user-images.githubusercontent.com/33848010/105917763-0ecc6c80-5ff0-11eb-8ed2-033901458d2e.png)

And here are my software versions:
![image](https://user-images.githubusercontent.com/33848010/105917811-273c8700-5ff0-11eb-8371-51a168d837d1.png)
![image](https://user-images.githubusercontent.com/33848010/105917828-2dcafe80-5ff0-11eb-9488-c455a6efe80c.png)
![image](https://user-images.githubusercontent.com/33848010/105917851-34597600-5ff0-11eb-8c17-af6378a0f5ea.png)

look at the "check" value that is *
![image](https://user-images.githubusercontent.com/33848010/105917941-5bb04300-5ff0-11eb-8d57-50f65b823bd1.png)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by HadiMoosavi** [comment]
Dynamo version
![image](https://user-images.githubusercontent.com/33848010/105918513-44be2080-5ff1-11eb-8277-ba99da40a3b5.png)

Operating system.
![image](https://user-images.githubusercontent.com/33848010/105918586-661f0c80-5ff1-11eb-848e-00bc98777f77.png)

[dynamo and package.zip](https://github.com/DynamoDS/Dynamo/files/5876714/dynamo.and.package.zip)

**Comment by QilongTang** [comment]
@nate-peters @saintentropy Bump

**Comment by saintentropy** [comment]
@HadiMoosavi A few questions.  Can you show a screenshot of the dependencies folder that is adjacent to your dynamo file.  Can you show us what is copied there and verify that it matches the packages you have listed with your graph.  Second question is to confirm GD works for you but not with your ZT nodes.  If so can you also take a screen shot of the bin folder for your package.  Thank you.

**Comment by HadiMoosavi** [comment]
Hello Craig,

I think I was able to find the problem. Please refer to the last comment I made in this forum page.
https://forum.dynamobim.com/t/zero-touch-node-gives-gd-no-output/


Let me know if you need more information from me.

Hadi
