### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by AlessandraAuteri** [DynamoDS/Dynamo#11458]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)
I'm using DynaMaps, but the node RoadsAsPolycurves doesen't appear correctly.
It is like incomplete
I can't see the complete name  in the list and select all or none

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

DynaMaps
### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by AlessandraAuteri** [comment]
- Dynamo version:

                                   Dynamo core 2.6.1.8786
                                   Dynamo 2.6.1.8850

   - Operating system: *Microsoft Windows*


[image: image.png] this what I expet to see
[image: image.png]

Il giorno ven 5 feb 2021 alle ore 17:55 github-actions[bot] <
notifications@github.com> ha scritto:

**Comment by mjkkirschner** [comment]
@AlessandraAuteri please check your links - no images are present, you likely need to upload them through the github ui.

it probably makes sense to reach out to the dynaMaps author - @MostafaElAyoubi
