### ISSUE TITLE
Curve.TrimByParameter fails with polycurves

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#11506]
## Dynamo version

2.10

## What did you do? 

![image](https://user-images.githubusercontent.com/29869395/108363894-6e6b0180-71c3-11eb-8ab5-be7727c0840c.png)

## What did you expect to see?

Trimmed polycurve

## What did you see instead?

`Warning: Curve.TrimSegmentsByParameter operation failed. 
Param Trim Segments Not Implemented`

**Comment by JacobSmall** [comment]
Likely worth reviewing the other curve modification on polycurves as we resolve this one

**Comment by aparajit-pratap** [comment]
The fix will be available in a future version of Dynamo (2.16+).
