### ISSUE TITLE
Crash report from Dynamo 2.9.0.3137

### ISSUE THREAD

**Issue by romangolev** [DynamoDS/Dynamo#11515]
# Issue Description
I tried to run a python script inside Dynamo using "Python from string" node.

### What did you do?
Pushed migration assistant button inside python script editor

### What packages or external references (if any) were used?
No packages

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.9.0.3137`

**Comment by QilongTang** [comment]
@Amoursol @mjkkirschner This one might be interesting to test.

**Comment by mjkkirschner** [comment]
what host was dynamo running in? ( or was this sandbox?)

**Comment by romangolev** [comment]
@mjkkirschner that was a sandbox version

**Comment by Amoursol** [comment]
@QilongTang we should safeguard against this for sure - it's a bit of an edge case, but still will be attempted by folk 😊

**Comment by QilongTang** [comment]
@romangolev May I know what kind of workflow you are doing? Because the default Python Script From String node should not involve Python editor in the workflow as below:
![image](https://user-images.githubusercontent.com/3942418/108951946-d5127400-7636-11eb-8124-85c469486ee9.png)

Are you using mixed Python nodes?

**Comment by romangolev** [comment]
@QilongTang Yes, my workflow is based on downloading up-to-date version of Python code and saving it locally before execution. 
![image](https://user-images.githubusercontent.com/67314258/109197533-2abd5c80-77ae-11eb-8ee4-de92c7f05868.png)

It might be not the most elegant solution, but gets the control of script version. 
Basically __.dyn__ file contains only a script that downloads, saves and then execucutes the Python script. from github [repository](https://github.com/romangolev/dynamo-scripts).

@Amoursol Maybe integrating a node that would dowload Github files :smirk:

**Comment by mjkkirschner** [comment]
Hi @romangolev I still don't think we understand your workflow clearly enough to help.

1. Can you provide the actual stack trace? This should be visible in the crash reporter if you can still reproduce this.
2. Where are you actually hitting migrate? The `pythonScriptFromString` node does not have a migrate button - so I'm assuming in the python node which downloads your second python code?

Another interesting note - I believe the python engine version should be shown on each node, but it's not there in your screenshot - so maybe that is an older version just for explanation?
