### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by dhurtado27** [DynamoDS/Dynamo#11511]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I tried to add the selectionitem.ByList node (highlighted in the image below) form Juggernaught and it crashed dynamo. 
![image](https://user-images.githubusercontent.com/79287242/108730836-87d8ba00-74f1-11eb-87e1-d9335933a2f9.png)

### What did you expect to see?
I expected to be able to work with the node but I can't open it without crashing dynamo

### What did you see instead?
I used other nodes

### What packages or external references (if any) were used?
I was using Juggernaught package

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
![image](https://user-images.githubusercontent.com/79287242/108730724-6ed00900-74f1-11eb-984b-de7f740dc5b7.png)

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by dhurtado27** [comment]
Hi;

Please see below my response in blue to the information requested

Dani Hurtado  |  I.D.T, B.I.A
Interior Designer
Grant Design Group Inc
T: 204 947 2843 / dhurtado@grantdeisgngroup.com

**Comment by mjkkirschner** [comment]
Hi @dhurtado27 - if you can reproduce this - please click "show details" and copy the stack trace to this issue.

**Comment by ToArn** [comment]
I tried to use the same node, with the same error. Any news on why this error shows or how to solve it?
