### ISSUE TITLE
Failed to load geometry binaries from Naviswork manage 2021

### ISSUE THREAD

**Issue by laujunkang** [DynamoDS/Dynamo#11522]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.5.2

## Operating system
Windows 10

## What did you do? 
Installed navisworks manage 2021 after extracting dynamo 2.5 to a folder

## What did you expect to see?
Expect dynamo 2.5 to open smoothly

## What did you see instead?
Upon lanching dynamo 2.5 sandbox, this messagebox appears
![image](https://user-images.githubusercontent.com/55877437/109517457-41ccb900-7ae4-11eb-8db3-0a9bad3590e8.png)
and protogeometry stops working
![image](https://user-images.githubusercontent.com/55877437/109517574-63c63b80-7ae4-11eb-8a36-8e04ae17e775.png)

**Comment by mjkkirschner** [comment]
this should be fixed in newer versions of sandbox from the daily builds site.

**Comment by laujunkang** [comment]
Hi there, the same happened for 2.6 as well

**Comment by mjkkirschner** [comment]
the first release that contained this fix was 2.7.
