### ISSUE TITLE
Opening a nested custom node after loading parent custom node causes crash

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1152]
The steps to replicate are:

1)Open a dyf file that has inside another custom node. (one that you have not loaded, and is not in your paths to load)
2)the workspace will display a red proxy node

3) open the real definition of the proxy node

4)crash will occur.

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
