### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by EricLrnt** [DynamoDS/Dynamo#11581]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by EricLrnt** [comment]
Error at the import of a large mesh with the Mesh Toolkit.

**Comment by QilongTang** [comment]
@EricLrnt can you fill the issue template to help us digest?

**Comment by EricLrnt** [comment]
Hi Qilong Tang,

As the bot marked it as closed I did not take the time to delve further into it thinking it was closed.
I think the error came from my code that was throwing back a humongous number of items in my list which wasn't what I was aiming for... I corrected the code and finally did things completely differently by using the Mesh Toolkit package combined with the Spring package.
I think we can close definitely this thread.
Thank you for coming back to me and for enquiring for more details I appreciate the concerns and interest.

**Comment by QilongTang** [comment]
> Hi Qilong Tang,
> 
> As the bot marked it as closed I did not take the time to delve further into it thinking it was closed.
> I think the error came from my code that was throwing back a humongous number of items in my list which wasn't what I was aiming for... I corrected the code and finally did things completely differently by using the Mesh Toolkit package combined with the Spring package.
> I think we can close definitely this thread.
> Thank you for coming back to me and for enquiring for more details I appreciate the concerns and interest.

I appreciate the effort of reporting and letting us know. Due to limitations, the issues template can't be full automatically filled in. If there is anything you think our bot can express more clearly, let us know for sure.
