### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by turboyerbo** [DynamoDS/Dynamo#11586]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Error Creating Background Preview

### What did you do?
Open Dynamo in Revit

### What did you expect to see?
3D Preview in background

### What did you see instead?
No option to view in 3D

### What packages or external references (if any) were used?
None

### Stack Trace
```

Dynamo log started 2021-04-02 13:09:51Z
Python template set to default.
Dynamo -- Build 2.6.1.8786

"There was an error creating a background preview in Dynamo. This could be due to a lack of graphics resources on your machine. See the log for more information."



---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`
![Dynamo 3D Background Preview not loading](https://user-images.githubusercontent.com/30615665/113419179-ef0d4800-9394-11eb-88ee-5774f4933374.png)
[Error Creating Background Preview.txt](https://github.com/DynamoDS/Dynamo/files/6249685/Error.Creating.Background.Preview.txt)

**Comment by QilongTang** [comment]
@turboyerbo Hey, thank you reporting. Although you used crash report as format but I do not see a crash so I will assume you need help enabling the 3D background preview? 
```
There was an error creating a background preview in Dynamo. This could be due to a lack of graphics resources on your machine. See the log for more information.
```
Since I saw this in the console log, I would suggest you follow our wiki at https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx to install directX and restart computer then give it a try.

**Comment by turboyerbo** [comment]
> @turboyerbo Hey, thank you reporting. Although you used crash report as format but I do not see a crash so I will assume you need help enabling the 3D background preview?
> 
> ```
> There was an error creating a background preview in Dynamo. This could be due to a lack of graphics resources on your machine. See the log for more information.
> ```
> 
> Since I saw this in the console log, I would suggest you follow our wiki at https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx to install directX and restart computer then give it a try.

Thank you that was an easy fix. I installed DirectX and it works fine. Thanks again.

**Comment by turboyerbo** [comment]
Installed DirectX and it works. Thank you.
