### ISSUE TITLE
Start page Error

### ISSUE THREAD

**Issue by CHOKYUNGMIN0113** [DynamoDS/Dynamo#11592]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.6.1.8786
Dynamo Revit 2.6.1.8850

## Operating system

Windows 10

## What did you do? 

just started Dynamo

## What did you expect to see?

3D view

## What did you see instead?

2D view and cannot change to 3D

![image](https://user-images.githubusercontent.com/82022752/113677987-1cd9f000-96f9-11eb-864b-da54698c6e15.png)

I downloaded Revit 2021 again and again to fix this problem, but I couldn't.
I even format my PC, and couldn't fix it still.

**Comment by mjkkirschner** [comment]
please try installing:
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by CHOKYUNGMIN0113** [comment]
@mjkkirschner  Thank you for your answer. I have downloaded and installed to the Autodesk folder(C:), but nothing has changed. It's still not working. Please help me

**Comment by QilongTang** [comment]
@CHOKYUNGMIN0113 Can you refer to this issue for details? More specifically, would you check your Dynamo console and see if you see the following error `There was an error creating a background preview in Dynamo. This could be due to a lack of graphics resources on your machine. See the log for more information.`?
