### ISSUE TITLE
Dictionary node to appear in Dynamo Player as an output

### ISSUE THREAD

**Issue by ElieTRAD** [DynamoDS/Dynamo#11607]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.6.1.8786/ 2.6.1.8850

## Operating system

Windows 10

## What did you do? 

I am trying to output the Dictionary.ByKeysValues node to show in the dynamo player

## What did you expect to see?

same output within Dynamo interface

## What did you see instead?

I see this output DesignScript.Builtin.Dictionary in Dynamo Player
![image](https://user-images.githubusercontent.com/55875794/114577734-f120b200-9c84-11eb-950e-c68fafae9d42.png)

**Comment by mjkkirschner** [comment]
this should be fixed in 2.10.1 I believe:
https://github.com/DynamoDS/Dynamo/wiki/Release-Notes#2101

**Comment by ElieTRAD** [comment]
Hopefully :)

**Comment by ElieTRAD** [comment]
The problem remains in release 2.10.1 :(
