### ISSUE TITLE
FileSystem.FileName Output Named Incorrectly

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#11614]
## Dynamo version

2.11.0

## Operating system

Windows 10

## What did you do? 
Using `FileSystem.FileName` 

## What did you expect to see?
The file name output named as string

## What did you see instead?
![image](https://user-images.githubusercontent.com/15744724/114888856-d5252980-9dc6-11eb-8484-29266f657cdc.png)

**Comment by QilongTang** [comment]
@johnpierson This is wrong indeed, will fix
