### ISSUE TITLE
Errors/warnings detection in workspacemodel

### ISSUE THREAD

**Issue by jamo162** [DynamoDS/Dynamo#11655]
## Dynamo version: 

2.10

## Operating system: 

Windows 10

## What did you do? 

My aim is to detect whether a script has been run with errors or warnings within my own app.

using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using Dynamo.Core;
using Dynamo.Graph.Workspaces;
using Dynamo.Models;
using Dynamo.Scheduler;
using Dynamo.Engine;
using Dynamo.Graph.Nodes.NodeLoaders;
using Dynamo.Graph.Nodes;
using Dynamo.Utilities;
using Dynamo.Migration;

namespace Dynamo
{
    public class DynamoApp
    {
        public static bool IsTestMode { get; set; }
        public static LibraryServices libraryServices { get; set; }
        private static MigrationManager migrationManager { get; set; }

        public static EngineController engineController { get; set; }
        public static DynamoScheduler scheduler { get; private set; }
        public static NodeFactory nodeFactory { get; set; }

        public static CustomNodeManager customNodeManager { get; set; }

        public class DynamoPreferencesData
        {
            public double ScaleFactor { get; internal set; }
            public bool HasRunWithoutCrash { get; internal set; }
            public bool IsVisibleInDynamoLibrary { get; internal set; }
            public string Version { get; internal set; }
            public string RunType { get; internal set; }
            public string RunPeriod { get; internal set; }
            

            public DynamoPreferencesData(
              double scaleFactor,
              bool hasRunWithoutCrash,
              bool isVisibleInDynamoLibrary,
              string version,
              string runType,
              string runPeriod)
            {
                ScaleFactor = scaleFactor;
                HasRunWithoutCrash = hasRunWithoutCrash;
                IsVisibleInDynamoLibrary = isVisibleInDynamoLibrary;
                Version = version;
                RunType = runType;
                RunPeriod = runPeriod;
            }

            public static DynamoPreferencesData Default()
            {
                return new DynamoPreferencesData(
                  1.0,
                  true,
                  true,
                  AssemblyHelper.GetDynamoVersion().ToString(),
                  "Automatic",
                  RunSettings.DefaultRunPeriod.ToString());
            }
        }
        public static bool isValidJson(string path, out string fileContents, out Exception ex)
        {
            fileContents = "";
            try
            {
                fileContents = File.ReadAllText(path);
                fileContents = fileContents.Trim();
                if ((fileContents.StartsWith("{") && fileContents.EndsWith("}")) || //For object
                    (fileContents.StartsWith("[") && fileContents.EndsWith("]"))) //For array
                {
                    var obj = Newtonsoft.Json.Linq.JToken.Parse(fileContents);
                    ex = null;
                    return true;
                }
                ex = new JsonReaderException();
                return false;
            }
            catch (Exception e) //some other exception
            {
                Console.WriteLine(e.ToString());
                ex = e;
                return false;
            }
        }
        
        public bool OpenJsonFile(
            string filePath,
            string fileContents,
            DynamoPreferencesData dynamoPreferences,
            bool forceManualExecutionMode,
            out WorkspaceModel workspace)
        {
            CustomNodeManager micustom = new CustomNodeManager(nodeFactory, migrationManager, libraryServices);

            micustom.AddUninitializedCustomNodesInPath(
                Path.GetDirectoryName(filePath),
                false);

            workspace = WorkspaceModel.FromJson(
                fileContents,
                libraryServices,
                engineController,
                scheduler,
                nodeFactory,
                IsTestMode,
                false,
                customNodeManager);

            workspace.FileName = filePath;

            HomeWorkspaceModel homeWorkspace = workspace as HomeWorkspaceModel;
            if (homeWorkspace != null)
            {
                homeWorkspace.HasRunWithoutCrash = dynamoPreferences.HasRunWithoutCrash;

                RunType runType;
                if (!homeWorkspace.HasRunWithoutCrash || !Enum.TryParse(dynamoPreferences.RunType, false, out runType) || forceManualExecutionMode)
                    runType = RunType.Manual;
                int runPeriod;
                if (!Int32.TryParse(dynamoPreferences.RunPeriod, out runPeriod))
                    runPeriod = RunSettings.DefaultRunPeriod;
                homeWorkspace.RunSettings = new RunSettings(runType, runPeriod);

            }

            CustomNodeWorkspaceModel customNodeWorkspace = workspace as CustomNodeWorkspaceModel;
            if (customNodeWorkspace != null)
                customNodeWorkspace.IsVisibleInDynamoLibrary = dynamoPreferences.IsVisibleInDynamoLibrary;

            return true;
        }

        public static string validjson;
        public void OpenAndGetWorkspace(string filepath, out WorkspaceModel myworkspace)
        {
            Exception ex;

            DynamoApp.isValidJson(filepath, out validjson, out ex);

            DynamoApp.DynamoPreferencesData nuevo = DynamoApp.DynamoPreferencesData.Default();

            OpenJsonFile(filepath, validjson, nuevo, true, out myworkspace);
        }
        

        public static void GetNodeErrors(WorkspaceModel workspacint, out List<string> listafinalconerrores)
        {
            List<string> listaerroreswarnings = new List<string>();
            WorkspaceInfo workspaceInfo = new WorkspaceInfo();
            

            foreach (Dynamo.Graph.Nodes.NodeModel node in workspacint.Nodes)
            {
                if (node.State != ElementState.Active)
                {
                    if (node.State == ElementState.Warning || node.State == ElementState.PersistentWarning)
                    {
                        listaerroreswarnings.Add("warning");
                    }

                    if (node.State == ElementState.Error || node.State == ElementState.AstBuildBroken && node.Name != "Watch")
                    {
                        listaerroreswarnings.Add("error");
                    }
                }

            }
            listafinalconerrores = listaerroreswarnings;
        }
    }
}

## What did you expect to see?

If the script has errors or warnings when running.

## What did you see instead?

Warnings are properly detected. However, I found the following issue;
-If there are a missing package that affect one node in the script they are not detected unless I add node.State == ElementState.Dead. However if I add the previous, errors are detected when there are none. I tried a work around with node.Tooltip.StartWith("Error") but it does not work either.

**Comment by jamo162** [comment]
The bot poped up a need more information label, I think because of missed line breakings. Could you recheck if you would need more information?

**Comment by jamo162** [comment]
# Dynamo version

2.10

## Operating system

Windows 10

## What did you do? .

Attached code above.

**Comment by QilongTang** [comment]
If there are missing packages, usually nodes will be dummy node so you can check if there is any node of the node type `DummyNode`. Node state and node tooltip seems greatly depending on if the graph has been ran so seem less stable to me in this case. Would you give this a try and we can discuss if there are other ways to detect Dynamo graph issue.

**Comment by jamo162** [comment]
Thank you for your reply! I have set up an instance of a DummyNode and 
been testing the following statements within the if statement;
DummyNode nododummy = new DummyNode();
Opt 1- node.GetType() == nododummy.GetType(). 
Result: No detection of missing packages as errors.
Opt 2- node == nododummy.
Result: No detection of missing packages as errors.
Opt 3- node.GetType().FullName == nododummy.GetType().FullName
Result: No detection of missing packages as errors.
Opt 4- node.GetType().Name == nododummy.GetType().Name
Result: No detection of missing packages as errors.

**Comment by jamo162** [comment]
@QilongTang @mjkkirschner  I think this issue may be related that I am getting the nodes directly from the WorkSpaceModel instead of ReadyParam. Would you know a way to get ReadyParam through the Workspacemodel or a work around to get the missing packages nodes?
