### ISSUE TITLE
Possible Geometry Kernel Problem

### ISSUE THREAD

**Issue by karambk** [DynamoDS/Dynamo#11661]
## Dynamo version

2.11.1

## Operating system

Windows 10

## What did you do? 

Imported a Surface in a SAT file (Geometry.ImportFromSAT)
Requested It's Perimeter Curves (Surface.PerimeterCurves)

## What did you expect to see?

Correct Perimeter Curves

## What did you see instead?

Faulty Perimeter Curves
![faultysurface](https://user-images.githubusercontent.com/74302224/116784218-c19ee180-aa9b-11eb-9f59-6b5554ba307e.png)

## More Info

-This is not a regression, it's a problem inside the geometry kernel as it seems.

-This problem affects multiple other workflows if similar surfaces came up (Which happens quite a lot when working with non-linear geometry).. either by different geometry operations with Revit, or other Autodesk products.

-This problem causes other later problems such as importing this geometry into Revit 2022.

-Legacy document.import method that was removed in Revit 2022 was able to heal this geometry to make it compatible with Revit.

-Other Autodesk products such as Fusion 360 understands the perimeter curves correctly. 
(UPDATE, AUTOCAD DOESN'T UNDERSTAND IT AFTER EXPLODING)

-Same behaver happens from Dynamo 1.3 up until 2.11.1

## Download Sample

[Surface.zip](https://github.com/DynamoDS/Dynamo/files/6409630/Surface.zip)

**Comment by karambk** [comment]
I have created a very direct example that can DEFINITALLY AND ALWAYS generate the problem from scratch, in fact it's a mess in this example..
 
 I also compared thickning in Fusion 360 with Dynamo, and Fusion gave a slightly better results.. but in any cases, Dynamo messed up with reading many surfaces perimeters (Which leads to other problems with Revit compatibility for sure)
 
 So, I think there's a room to improve thickining of multiple joined adjacent surfaces in Dynamo (Polysurfaces) 
 And a room to improve reading the geometry it self after thickining (Whether the source is from Dynamo itself or from another external software)
 
![ThickenProblem](https://user-images.githubusercontent.com/74302224/117526249-8c7b1d80-afcc-11eb-8406-ad76e35e4428.png)


Sample DYN and SAT files attached:
[MessedUp.zip](https://github.com/DynamoDS/Dynamo/files/6445192/MessedUp.zip)

**Comment by Amoursol** [comment]
@aparajit-pratap - are we able to look into this and see what's going on please? 😊

**Comment by karambk** [comment]
@aparajit-pratap pinging :)

**Comment by aparajit-pratap** [comment]
https://jira.autodesk.com/browse/DYN-5606

**Comment by aparajit-pratap** [comment]
@karambk I know it's been quite some time since this issue was logged but would you happen to remember how this surface was constructed in the first place, the one that's being imported from the SAT file:
![image](https://user-images.githubusercontent.com/5710686/218770368-a3442db6-4325-4d27-a3ae-ae52e73a0919.png)

This is a very unique issue that the kernel team is trying to solve for us. If you can provide any information as to the source of this surface (graph in Dynamo), that would be very useful. Thanks.

**Comment by aparajit-pratap** [comment]
@karambk from whatever info we could extract from the SAT and DYN files, it appears that one edge has a very large tolerance around it, with tolerant vertices at its ends. This could explain the strange mismatch of edges to surface. However, we cannot fix this issue or debug it further without looking further upstream. I'm closing this issue for the time being and will be happy to reopen it if we can get more information as to how the surfaces were created to begin with. Thank you.

**Comment by karambk** [comment]
@aparajit-pratap Thank you for the information.
It's quite hard to trace back the original generating graph.

But I do recall that this surface was a result of the thicken command in Dynamo.

In all cases, what brought my attention to this is that this issue happened multiple times in a short time span, but in recent versions, I'm not facing this particular issue again.

Whenever it surfaced again, I'll bring up more information.

Thanks :)

**Comment by aparajit-pratap** [comment]
Understood. Thanks, @karambk for your response. I'll try not to miss these notifications again.
