### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by carl-schwarz** [DynamoDS/Dynamo#11674]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Selected "ByList" From Juggernaught package in the Dynamo library.

### What did you expect to see?
A node to place into the script.

### What did you see instead?
The error message that Dynamo had crashed.

### What packages or external references (if any) were used?
Juggernaught

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Object reference not set to an instance of an object.

   at List.CustomNodeModelNodeViewCustomization.<updateInputList>b__8_1(AsyncTask _)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by mjkkirschner** [comment]
@QilongTang I think if you want this to stay open - comment on the issue.

**Comment by mjkkirschner** [comment]
some activity.

**Comment by QilongTang** [comment]
Still investigating

**Comment by QilongTang** [comment]
Still investigating
