### ISSUE TITLE
XYZ X, Y, and Z Output in meters?

### ISSUE THREAD

**Issue by wassimj** [DynamoDS/Dynamo#1169]
I am trying to get the X, Y, and Z components of an XYZ. Simple enough, but I am getting them in meters? Any hints on how to avoid this? Please see the simple workflow in the attached images.
![screen shot 2014-02-27 at 11 24 01](https://f.cloud.github.com/assets/6302909/2281749/56b271f4-9fa2-11e3-8a62-140aa138b55f.png)

**Comment by ikeough** [comment]
@wassimj I noticed that this has been open for a while. I'm closing it because the units behavior is completely changed in 0.8.0. Units in Dynamo now adhere to the unit setting you have set in Revit. If this does not solve the issue above, then let us know.

**Comment by wassimj** [comment]
Yes of course. This one is stale

Best Regards,

Dr. Wassim Jabi, Senior Lecturer
Welsh School of Architecture
