### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by h09aLuLV** [DynamoDS/Dynamo#11739]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Ran the code

### What did you expect to see?
Successful completion

### What did you see instead?
Operation Failed

### What packages or external references (if any) were used?
Data.ImportExcel

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by h09aLuLV** [comment]
Dynamo Core 2.6.1.8786
Dynamo Revit 2.6.1.8850

Windows 10 Pro 20H2

Warning: Data.ImportExcel operation failed.



Ryland Auburn, AIA, LEED AP BD+C
Manager of Design Technology

EskewDumezRipple+
AIA National Architecture Firm Award Recipient

365 Canal Street Suite 3150
New Orleans, LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by QilongTang** [comment]
Still investigating. Notice the latest Dynamo version will come with an alternative version of Excel node which no longer depend on a local install of office to launch, crashes related should be minimized when using the new node in the future.
