### ISSUE TITLE
Polysurface issue Dynamo 2.12.0.5311

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#11763]
# Issue Description
Polysurface Intersect with plane doesn't work

## Dynamo version
Dynamo: `2.12.0.5311`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
![polysurfaceError](https://user-images.githubusercontent.com/5621624/122156365-70e61b00-ce86-11eb-933c-9d3f7addcd14.png)

## What did you expect to see?
Rectangle

## What did you see instead?
Empty List

## What packages or external references (if any) were used?
None

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
thanks for reporting this, appears to be a regression from 2.11 - tracked internally.

**Comment by mjkkirschner** [comment]
this should be fixed in master now.
