### ISSUE TITLE
dynamo crashed when creating geometry using rhynamo

### ISSUE THREAD

**Issue by dine-12** [DynamoDS/Dynamo#11788]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by dine-12** [comment]
![asdf](https://user-images.githubusercontent.com/86413709/123298822-84544e80-d536-11eb-9b17-e7fa1002db9e.PNG)

**Comment by mjkkirschner** [comment]
Hi @dine-12 can you please attach your graph, required files and exact steps to reproduce? Unfortunately that stack trace does not contain enough information.

**Comment by dine-12** [comment]
﻿
