### ISSUE TITLE
IsVisibleInDynamoLibrary attribute not working for ZT public classes which implement an interface

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#11852]
## Dynamo version

2.10

## Operating system

Win 10

## What did you do? 

Declared a class publicly for zero touch import. Don't want the constructor to be available as a node so I used the IsVisibleInDynamoLibrary attribute to decorate the constructor. 

The constructor HAS to be public as its is instantiated via a processor class which uses dependency injection and the new() type constraint so I can instantiate the type constraint abstractly.  

## What did you expect to see?

The constructor hidden from the library. 

## What did you see instead?

It still shows.

**Comment by ThomasMahon** [comment]
I've temporarily fixed this by using the SupressImportIntoVM attribute. Would be good to get a proper fix though.

**Comment by QilongTang** [comment]
@ThomasMahon Indeed. FYI: @jasonstratton

**Comment by aparajit-pratap** [comment]
Fixed here: https://github.com/DynamoDS/Dynamo/pull/12032
