### ISSUE TITLE
Unable to use NurbsSurface in 2022

### ISSUE THREAD

**Issue by BasRongenSPIE** [DynamoDS/Dynamo#11888]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Tried to use the node NurbsSurface.ByPoints

### What did you expect to see?
For it to work, a sit does in 2021

### What did you see instead?
-

### What packages or external references (if any) were used?
None

![Printscreen 2021 - 2022](https://user-images.githubusercontent.com/70643737/127108942-f8e40c9a-b2d4-44cf-b75c-6831ea5811fb.png)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by mjkkirschner** [comment]
@BasRongenSPIE please attach a .dyn to reproduce the issue - or if required your .rvt and .dyn etc.

**Comment by BasRongenSPIE** [comment]
https://we.tl/t-q5Bxtz5ySF

**Comment by QilongTang** [comment]
still investigating

**Comment by BasRongenSPIE** [comment]
I don't understand what more you require of me? I've shown you my .dyn setup in the images. Are you not able to reproduce this? It's as simple as trying to use the node in the 2022 version and you'll run into the error.

**Comment by QilongTang** [comment]
FYI: @jasonstratton
