### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by marswillforgithub** [DynamoDS/Dynamo#11915]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here) I have installed Revit 2021.1.3, and Dynamo 2.6. I tried to do generative design in Dynamo. There is the "Generative Design" bar in the top menu bar, but this is no "Export for generative design" in the drop-down menu. Also there are always notifications saying "Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\GenerativeDesign"

### What did you expect to see?
(Fill in here)I expect to see "Export for generative design" in the drop-down menu of the "Generative Design" bar. 

### What did you see instead?
(Fill in here)I see "Open Denerative Design Tools" instead of "Export for generative design"

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
A duplicate of the package called GenerativeDesign was found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\GenerativeDesign.  Ignoring it.
A duplicate of the package called GenerativeDesign.Extension was found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\GenerativeDesign.Extension.  Ignoring it.
A duplicate of the package called GenerativeDesign.Revit was found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\GenerativeDesign.Revit.  Ignoring it.
---
OS: `Microsoft Windows NT 10.0.19043.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by marswillforgithub** [comment]
> Hello marswillforgithub, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.
> 
> Can you please fill in the following to the best of your ability:
> 
> * Dynamo version **Dynamo 2.6**
> * Operating system: **Microsoft Windows 10**
> 
> Additional information:
> 
> * Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
> * Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue)
> * Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
> * Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
> * Reproducible steps on how to create the error in question.

**Comment by QilongTang** [comment]
FYI: @nate-peters @saintentropy

**Comment by QilongTang** [comment]
@saintentropy @nate-peters @BogdanZavu are you able to speak to this?

**Comment by nate-peters** [comment]
Hi @marswillforgithub -can you look in your default package directory in Dynamo and check if there's an older version of the Generative Design extension installed there? The only place the Generative Design extension should be installed is in the `ProgramData` path that's listed in the error you submitted. It looks like Dynamo is finding another copy of the package somewhere else first, and skipping the one in `ProgramData`.
