### ISSUE TITLE
Clockwork Installations fails

### ISSUE THREAD

**Issue by mihail-architect** [DynamoDS/Dynamo#11913]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo

Dynamo Core 2.10.13.3976 / Revit .10.1.4002

## Windows

Windows 10

## What did you do? 

Trying to install Clockwork - it fails and the custom node which I was using previously to cleanup models doesn't work.

## What did you expect to see?

Cleaned up from views and sheets model

## What did you see instead?

N/A

**Comment by QilongTang** [comment]
Still investigating
