### ISSUE TITLE
could we add a node in dynamo that controls floor and roof subelement modification?

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#1195]
it would be very....very helpful to have a node in Dynamo that could ( "get and SET") the floor and roof subelements (points and split line and pick supports) ((MOST CRITICAL IS THE POINTS IF NOTHING ELSE)

I understand that creating a roof and floor from scratch is very difficult with Revit API so this node could just modify an existing floor or roof 
a sample of what I was thinking is below.

---GET--- FLOOR/ROOF SUBELEMENTS
INPUT - SELECTED FLOOR OR ROOF
OUTPUT1 - list subelement points (if any) in XYZ format
OUTPUT2 - list subelement split lines (if any) in curve format              

---SET--- FLOOR/ROOF SUBELEMENTS
INPUT1 - SELECTED FLOOR OR ROOF
INPUT2 - create subelement points in XYZ format
INPUT3 - create subelement split lines  in curve format            

yes yes I know I know 
"I could make a python node that has code to perform these tasks" 

![image](https://f.cloud.github.com/assets/6132497/2303604/834886cc-a1d2-11e3-978d-d708199a7cfd.png)

**Comment by karthickravi** [comment]
i am trying before three days onward  but its not working i given toposurface points as input points .using roof of foor node from clockworks its deleting all points on floor any ideas welcome.

**Comment by andydandy74** [comment]
@karthickravi - if you have an issue with a Clockwork node, please post it here: https://github.com/CAAD-RWTH/ClockworkForDynamo/issues
In this case, though, I think you'll find the information you need right here: http://landarchbim.com/2015/10/21/make-hardscape-follow-topo/
