### ISSUE TITLE
Could not load  LibG.ProtoInterface.dll

### ISSUE THREAD

**Issue by xRadne** [DynamoDS/Dynamo#11979]
## Dynamo version
Tested with both 2.12.5650 **and** 2.10.0.3455

## Operating system
Windows 10

## What did you do? 
Download build 2.10.0.3455, unblock, unzip, start, create point.ByCoordinates

## What did you see instead?
`Warning: Point.ByCoordinates operation failed. 
Could not load file or assembly 'file:///<a local directory>\DynamoCoreRuntime2.10.0\LibG.ProtoInterface.dll' or one of its dependencies. The system cannot find the file specified.`

**Comment by xRadne** [comment]
Installing some proprietary Autodesk software seems to have solved this temporary.

**Comment by QilongTang** [comment]
Thanks @xRadne , the geometry function in Dynamo currently is depending on installation of other ADSK tools, e.g. Revit, AutoCAD because Dynamo do not come with a dedicated geometry core yet.

**Comment by echosori** [comment]
![image](https://user-images.githubusercontent.com/19378581/178079187-d4a0eba4-5e20-451a-b282-9b37530baa57.png)
So I guess this is a half-lie.

**Comment by huntergregal** [comment]
Is this limitation still true? Dynamo geometry (the whole point) - is dependent on Revit or Autodesk software?

**Comment by chuongmep** [comment]
@huntergregal some people still have problem today.

**Comment by OnnoEbbens** [comment]
I still have this issue

**Comment by napooil** [comment]
I still have this issue (dynamo 2.19.3)

**Comment by walid03060306** [comment]
me too

**Comment by harilalmnzyeta** [comment]
me too

**Comment by zannas88** [comment]
same problem with version 3.3.0.5216

**Comment by MayoBIM** [comment]
I have same problem with Dyanmo Sandbox 3.1.0 only in my laptop but in PC dekstop work correctly...  
In both PC I have installed Revit.

**Comment by NuttyMonk** [comment]
Same here.  Version 3.3.0

:(

"Point.ByCoordinates operation failed.

Could not load file or assembly 'C:\Program Files\Autodesk\DynamoCoreRuntime3.3.0\LibG.ProtoInterface.dll'. The system cannot find the file specified."

**Comment by QilongTang** [comment]
hi @NuttyMonk Do you have Revit 2025 installed?

**Comment by NuttyMonk** [comment]
I have now installed Revit just to get Dynamo to work, which it does.
