### ISSUE TITLE
Evaluate Curve fails with some numbers but not others

### ISSUE THREAD

**Issue by wassimj** [DynamoDS/Dynamo#1197]
I am trying a simple "Evaluate Curve" with a sequence of numbers from 0 to 1. Most of the times, the curve gets evaluated fine and I get the reference points, but for a particular division (for example 20 divisions in this case) it fails with the error: Cannot evaluate the curve at the input parameter. Strangely, the same definition works for 10, 15, and 30 divisions. Just 20 divisions make it fail. Please see the attached screen shots for this very simple definition and let me know if this is a bug or if I am doing something wrong. Thank you!
![screen shot 2014-03-02 at 11 16 07](https://f.cloud.github.com/assets/6302909/2304018/a1bd5752-a1fc-11e3-9900-cc92cf13a6ff.png)
![screen shot 2014-03-02 at 11 16 26](https://f.cloud.github.com/assets/6302909/2304019/a1bdd786-a1fc-11e3-9559-d454d652187e.png)
![screen shot 2014-03-02 at 11 15 59](https://f.cloud.github.com/assets/6302909/2304020/a1c02fb8-a1fc-11e3-91fb-6c375b9ad93b.png)
![screen shot 2014-03-02 at 11 16 18](https://f.cloud.github.com/assets/6302909/2304017/a1bb2842-a1fc-11e3-82ac-5f5165d41119.png)

**Comment by ikeough** [comment]
@wassimj I apologize for the delayed response. Can you please retry this with a newer version of Dynamo and re-open if the issue persists?
