### ISSUE TITLE
nested Custom node in loaded dyn needs to be manually placed before updated definition of inputs/outputs register

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1202]
this is in .63

![screen shot 2014-03-03 at 10 51 29 am](https://f.cloud.github.com/assets/508936/2311043/d877f2da-a2eb-11e3-8a65-4f7f74460035.png)

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
