### ISSUE TITLE
Manage Packages disappeared from v2.13

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#12064]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.13

## Operating system
W10

## What did you do? 
Attempted to publish an update to BimorphNodes

## What did you expect to see?
No Manage Packages so I cant publish a new version. Where has it gone? 
![image](https://user-images.githubusercontent.com/18601851/134820628-9e37b4b9-1306-4f99-bb27-e56d1f451f9b.png)

## What did you see instead?
Manage Packages so I cant publish a new version.

**Comment by ThomasMahon** [comment]
I've found it!

**Comment by Amoursol** [comment]
Hurrah! Glad you found it @ThomasMahon 🙌

**Comment by QilongTang** [comment]
@ThomasMahon 😉

**Comment by ThomasMahon** [comment]
@Amoursol @QilongTang Warning...I'm going to whinge...
I want to give some feedback on this new menu organisation as its a bit disorganised:
1. Why is packages and the package manager split into two different menus? Its inconvenient and isn't very intuitive. Case in point - I didn't even think to look in Dynamo > Preferences > Package Manager > Installed Packages > Publish new version etc. So the user has Packages > Search for a Package or Packages > Publish a new Package, both 2 clicks in a clearly identifiable menu or 4 clicks masked behind an ambiguous Preferences menu taking 4 clicks. Whats the reasoning behind this? 
2. Why is there a 'Dynamo' menu? I know I'm in Dynamo why do I need a menu telling me this and what does it tell me anyway? Why cant Preferences go under the File menu...or just remove it? This menu is practically pointless; its sparse with only four items, two of which one would normally expect to be found under the Help menu (About and Agreement to collect Usability Data) - I guess they were shifted there to make it look less empty (and less pointless). The only other options in the Dynamo menu are Exit Dynamo and Preferences.
3. Why does preferences launch into its own dialog with a unique UI language. No other menu in Dynamo does this so I don't really get the UI concept; it just strikes me as confused, almost like beta software or something which is experimenting with different UI concepts. Also:
- Default run settings in General is redundant - there is already a dedicated button in the bottom-left of the Dynamo main window.
- Visual Settings are the type of controls the user normally wants immediate feedback from. Instead, this pop-up dialog blocks interactions with Dynamo forcing the user to change their visual settings blind, check then click on the convoluted menu structure just to get back to the setting again (4 clicks). 
4. Geometry Scaling - isn't this a really important setting for most Dynamo Revit users, especially those using mm. Their graphs wont execute if the scaling is too small. Its very strange that this essential setting has been demoted to the convoluted Dynamo > Preferences > Visual Settings > Display Settings. Imagine the UX for a new user. Isolate Selected Geometry is a useful setting, and it should be easier to access IMO. 

Whinge over. In summary:
- The Dynamo menu is pointless.
- Frequently used visual settings should be easily and immediately accessible.
- Packages and the package manager should be grouped into 1 menu. 
- Dynamo menu filler items (About and Agreement to collect Usability Data) should be moved to the Help menu.

**Comment by QilongTang** [comment]
> @Amoursol @QilongTang Warning...I'm going to whinge... I want to give some feedback on this new menu organisation as its a bit disorganised:
> ...
> 
> * The Dynamo menu is pointless.
> * Frequently used visual settings should be easily and immediately accessible.
> * Packages and the package manager should be grouped into 1 menu.
> * Dynamo menu filler items (Exit, About and Agreement to collect Usability Data) should be moved to the File and Help menus.
> * Too many mouse clicks - navigating the menus is too convoluted.
> * Redundant settings: e.g. Default Run Settings.

Thanks @ThomasMahon for these comments. It is good to know how Dynamo veterans would receive the Dynamo UI refresh. 

I understand the ease to access some options under Settings in previous versions before 2.11.0 has been reduced but I promise you:
- Dynamo is an open source project and just like any of them, when evolves, the development team will try all kinds of improvements. Any feedback is welcome.
- The current changes are reflecting designs by a lot of talented people, based on feedback by a lot of experienced users combined with less experienced ones.
- This is not and will not be the last version of Dynamo UI Refresh. Having settings in the preference panel is a first step to have a centralized and scalable solution to manage the rising number of settings in the coming versions. Also this is just our first step, and should not conflict with future improvements to have the most popular settings on toolbar. Appreciate your comments on the most useful settings, our UX @Jingyi-Wen will take these into consideration for sure.


Also I will share my comments here regarding to one of your comments:
> * Redundant settings: e.g. Default Run Settings.
Default Run Settings is a new feature which has been asked for a long time and is different than the Run Type Switch in Run status bar. The Run Type switch only manages the current workspace while user creating new workspace, it may be reverted back from current Manual or Periodic to Automatic (Default). The Default Run Settings will set the default run type for any newly created workspace while user can switch around for preferences anytime.

For other ones, hopefully our UX ppl and jump in and explain better. But even if not, by the time 2.13.0 is officially released, I'm sure they will share their philosophy in a public post.
