### ISSUE TITLE
Search Bar Shortcuts

### ISSUE THREAD

**Issue by michaelbergin** [DynamoDS/Dynamo#122]
Having some method of simply inputting a number in the search bar and generating a slider that is constrained to the value would be helpful.

For instance...

Entering 64 in the search bar would give a slider that is set to 64 (integer) and bound from 0 to 100.

Entering 52.33 would give a slider set to 52.33 (float) and bound from 0.00 to 100.00.

Entering 4.2 would give a slider, set to 4.2, bound from 0.0 to 10.0 ... and so on.

**Comment by sharadkjaiswal** [comment]
@michaelbergin, @dbaldacchino, I think we have addressed this issue by providing Code block node implementation, where users can quickly write design script code for any node. We also have default values on the nodes and in-canvas search allows you to create nodes at the specified location with default values. For now I am closing this issue, please feel free to provide your additional input and feedback.
