### ISSUE TITLE
Wishlist - Watch and Watch 3d in the right click shortcut menu

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#1225]
It would be great having the option of create both Watch and Watch 3d nodes directly in the shortcut menu when clicking the right button.

Even better, if right clicking an out connection we can directly create watch /  watch 3d nodes of that element.

**Comment by Racel** [comment]
We have improved preview bubbles to make it easier for customers to inspect the data that is coming out of their lists. We also intend on doing a context menu cleanup for the next generation Dynamo UI, so I don't think we will be working on this in the near term. Closing.
