### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by madsmartiny** [DynamoDS/Dynamo#12279]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.22000.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(The Script doesn't show nodes, only the strings. The ribbon is frozen and i cant do anything)

## What did you see instead?
(Fill in here)

## What packages or external references (if any) were used?
I think i tried to install Archi-lab.net, and then it happend.

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by madsmartiny** [comment]
![Error](https://user-images.githubusercontent.com/80713331/141360179-67fae71b-5a6d-427f-99a5-f7ecf7c7236f.jpg)

**Comment by madsmartiny** [comment]
Nodes doesn't show up. Dynamo is frozen, node blocks doesn't show text fields.

**Comment by mjkkirschner** [comment]
Hi @madsmartiny - please see https://github.com/DynamoDS/Dynamo/issues/10826 and many other threads about the issue. (search system.windows.interactivity)

* You can try removing addins to find if there is a conflicting one - CTC has been noted recently.
* update to latest packages (archilab in this case)
* check the conflicts noted in the notifications menu item.
