### ISSUE TITLE
Disproportionate Library Menu Text Dynamo 2.13.0.3292

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#12333]
## Dynamo version

2.13.0.3292

## Operating system

Windows 11

## What did you do? 

Installed the above build

## What did you expect to see?

Proportionate text in Library

## What did you see instead?
![Screenshot 2021-11-26 191847](https://user-images.githubusercontent.com/5621624/143591201-0508a549-295e-487f-8ff4-d19935a904f4.png)
![Screenshot 2021-11-26 192541](https://user-images.githubusercontent.com/5621624/143591619-6f28d088-fa50-4983-9bfd-6cc341386f47.png)

**Comment by Amoursol** [comment]
Hi Vikram - Thank you for reporting! This was a weird bug that snuck through, but should have now been addressed with this PR: https://github.com/DynamoDS/Dynamo/pull/12331

It's not yet merged, so won't show up in the daily builds until it is 😊
