### ISSUE TITLE
Error When Export Excel Open Xml To File Excel already exist

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/Dynamo#12344]
This issue is related to SheetStyle which I have looked through, it says null at that location, unfortunately I haven't had the detailed time to go through the source code and fix it.

## Dynamo version

2.14

## Operating system

Windows 10

## What did you do? 

Export To Excel With Node Data.OpenXMLExportExcel
## What did you expect to see?
![image](https://user-images.githubusercontent.com/31106432/144062855-ddd0e90c-2703-454c-86c3-5db109e48234.png)

## What did you see instead?

Problem may be error in line code : https://github.com/DynamoDS/Dynamo/blob/321793b96c2bfb882898f1896f6771bd6e149cff/src/Libraries/DSOffice/OpenXmlHelper.cs#L41-L41
Let use this file excels below to create error again:
[RST_Link.xlsx](https://github.com/DynamoDS/Dynamo/files/7626289/RST_Link.xlsx)
[OpenXmlError.zip](https://github.com/DynamoDS/Dynamo/files/7626319/OpenXmlError.zip)
FYIs
@mmisol

**Comment by iAliJ** [comment]
I tried to reproduce with local excel sheet, seems to work fine. I couldn't use the attached Excel file as the file seems to be corrupted?
