### ISSUE TITLE
Redundant right click options on input port labels

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#12398]
## Dynamo version

2.14.0.3401

## Operating system

Windows 11

## What did you do? 

Right clicked on an input node that has no option to change _levels_

## What did you expect to see?

Nothing, as there aren't arrows besides the input labels

## What did you see instead?
![Screenshot 2021-12-07 120212](https://user-images.githubusercontent.com/5621624/144978757-da5f4faf-45f3-4910-bbae-62c45992e1ad.png)

**Comment by QilongTang** [comment]
Thank you for reporting, this should be fixed with the latest changes already. See https://github.com/DynamoDS/Dynamo/pull/12384. If you see this again, feel free to reopen with screenshot!
