### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by haziq993** [DynamoDS/Dynamo#12488]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Trying to run generative design (Randomize study) on Dynamo for Revit. The nodes used are shown below. The idea is simple: From a floor I chose, select random point on the floor and create a cuboid at that said random point.
![image](https://user-images.githubusercontent.com/91877782/145759640-b3d8cf3c-707a-4eb3-80ca-527838f635b2.png)

### What did you expect to see?
I expected to see random results to appear for surface area, XYZ, Solid.Volume and By Pass Volume.

### What did you see instead?
![image](https://user-images.githubusercontent.com/91877782/145759077-0dc86382-2c0a-41a3-911c-7f6d48dee726.png)

Instead only results for By Pass Volume, which does not depend on the "Select Face" node was obtained. The rest did not. 

### What packages or external references (if any) were used?
The only external reference used was Revit.Selection.SelectFace. Is there a reason why Revit Selection nodes can't work on generative design?

### Other Information:
Generative Design version 21.16.10.0
Dynamo Core 2.6.1.8786
Dynamo Revit 2.6.1.8850
Revit version 21.1.50.27

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
No crash report since no crash
---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by QilongTang** [comment]
@saintentropy @nate-peters Anyone on your team could help to look at this case?
