### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by Alina-An** [DynamoDS/Dynamo#12512]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.18363.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- LunchBox for Dynamo 2018.8.8
- Rhythm 2021.7.3
- GenerativeDesign 1.9.3.0
- GenerativeDesign.Extension 1.9.3.0
- GenerativeDesign.Revit 1.9.3.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by Alina-An** [comment]
Hello GitHub Support team,

I currently work on Revit 2022.1 + Dynamo 2.12.0.5650 and I have a problem with installing packages. I tried several times install several different packages.
Any help would be very much appreciated.

***@***.***


Kind regards

Alina Antonik

***@***.***
T: 020 7553 6050
E: ***@***.******@***.***>

1 Bastwick Street, Clerkenwell, London, EC1V 3NU
www.rossandpartnersltd.co.uk<http://www.rossandpartnersltd.co.uk>

***@***.***<https://www.linkedin.com/in/matthew-nowman-9296bb62/>  ***@***.*** <https://www.instagram.com/rossandpartners/?igshid=1d8mkmj0rblpc>

**Comment by Amoursol** [comment]
Hello @Alina-An - Sorry to hear you are having troubles installing packages. Is Dynamo crashing when you try to install a package? Or is the process simply failing?

**Comment by Alina-An** [comment]
Hi @Sol ***@***.***>,

Thank you for contacting me, but I have already found the reason, and solved the problem.

Regards

Alina

**Comment by Amoursol** [comment]
Ah, perfect! Thanks for sharing that back with us @Alina-An
