### ISSUE TITLE
Default icons for package assemblies

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#12523]
Now it has been some time since we who code packages for Dynamo have been waiting for the option to have default icons (large/small) for our nodes.

I have tried to solve this problem many times and spent far too many hours looking at what is possible for overriding Dynamo. However, it always ends up that I have wasted my time :-S

I know that the “DefaultIcon” in the DynamoCore “customization” assembly is forced for all nodes unless we explicitly have a named icon according to the function + suffix (large/small). Why can't we all have the same option for our assembly/assemblies, meaning we could add a “DefaultIcon.Large” and “DefaultIcon.Small” in our own “customization” assembly!?

As you can see have I added all kinds of default icons to my resource file, hoping that it someday will be an option that this will work. It is time-wasting that we have to add a named icon for all nodes we don’t have an icon for yet. I have around 500 nodes where I have not had time to make an icon! That’s 1000 images added to the resource file which is a total waste of space!

![image](https://user-images.githubusercontent.com/2844374/147853706-325eaff9-7ff9-4f53-abbf-ed1f06ddd80e.png)

If default icon where supported pr. assembly like the node icons are, would it also be possible to split projects into several projects having each an option for a default icon. In my case would this imply a default node for FamilyDocument, Material, Core, and Project. That would be helpful!

My issue refers also to:
https://github.com/DynamoDS/Dynamo/issues/5752
https://github.com/DynamoDS/Dynamo/issues/5094

@Amoursol

**Comment by Amoursol** [comment]
@erfajo So sorry about the bot - this is indeed a bit mad. @jasonstratton can we look into why the bot is submitting the same message multiple times? Might just be easiest to check if the message exists, and not to repost if so.

**Comment by erfajo** [comment]
Thanks @Amoursol 
However, please delete this issue when you dont need it anymore :-)

Furthermore, the reason for my issue is much more important. I hope you have had the time to check it out
https://github.com/DynamoDS/DynamoWishlist/issues/204
