### ISSUE TITLE
IF code block from previous versions causes problems in Projekt Refinery 

### ISSUE THREAD

**Issue by Maier24091998** [DynamoDS/Dynamo#12541]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

version 2.12

## Operating system

Windows 10

## What did you do? 

I have written a dynamo script for a design study in project refinery. I noticed that as soon as I used nodes from old packages, this output [*] was displayed in the project refinery. In Dynamo the graph works fine. I was able to fix the problem as soon as I replaced the old IF block with the new version. 
However, I generally have the problem that the old versions of packages still work fine in Dynamo, but as soon as I start the design study in project refinery I don't get any output. 

This, unfortunately, leads to many good packages being useless for use with Project Refinery and limits the work with Project Refinery very much.

**Comment by Amoursol** [comment]
@saintentropy @nate-peters this one appears to be a GD issue. Are you able to investigate?
