### ISSUE TITLE
Rapport d'erreur de Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by DookDook92** [DynamoDS/Dynamo#12579]
#dynamaps doesnt want to charge the information of topography 

### What did you do?
if you have a solution ? :)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by Amoursol** [comment]
Hi @DookDook92 - This appears to be an issue with **DynaMaps** which is a custom package created by the team at https://data-shapes.io/

Unfortunately we cannot fix this as it would require Mostafa to do so. I'll let him know of the issue!
