### ISSUE TITLE
Point.ByCoordinates throwing error in 2.13.1

### ISSUE THREAD

**Issue by secretlyagoblin** [DynamoDS/Dynamo#12590]
## Dynamo version

2.13.1

## Operating system

Windows 10

## What did you do? 

Fresh install from dynamobuilds.com, unblocked dlls, opened a new document, created a code block and wrote Point.ByCoordinates(0,0,0).

## What did you expect to see?

A point be created

## What did you see instead?

![image](https://user-images.githubusercontent.com/13952064/151241900-967a0909-20d8-4207-8a8f-334bcee3d51f.png)

**Comment by mjkkirschner** [comment]
Hi @secretlyagoblin - do you have a 2022 ADSK product installed, like Revit, Acad etc?

**Comment by secretlyagoblin** [comment]
No, just purely dynamo core, pulled from https://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoCoreRuntime2.13.1.zip

**Comment by mjkkirschner** [comment]
ok - then this is expected, Dynamo's geometry library is not open source and requires an installed adsk product - theres a long thread about this here:
https://forum.dynamobim.com/t/dynamo-sandbox-without-revit-current-status/37589/42

and some more info on intended use cases for sandbox - 
https://dynamobim.org/a-new-way-to-get-dynamo-sandbox/

**Comment by secretlyagoblin** [comment]
Sweet as, thank you very much!
