### ISSUE TITLE
Color Palette UI

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#12610]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.13.1

## Operating system

Win 10

## What did you do? 

Opened color palette

## What did you expect to see?

colors

## What did you see instead?

somewhat botched color selection as per image with some kind of "sketchy line" going on around each color :
![image](https://user-images.githubusercontent.com/7080648/152793624-a93c6639-0b67-4c94-8f0d-a7214f43124a.png)
As the rest of the UI is neat now, maybe this can be tidied up as well? :)

**Comment by Amoursol** [comment]
@josols We looked into fixing this, but as it's a 3rd party component we have really limited ability to style it, which isn't ideal 😢 

We can look to these again in the future for sure, maybe there is a better way to surface it.
