### ISSUE TITLE
Context menu selection bug

### ISSUE THREAD

**Issue by Thomas84** [DynamoDS/Dynamo#12659]
This bug exists for a very long time (since ever?) and explaining Dynamo beginners these bugs all the time is frustrating for me. Even the new UI has the bug. 

![align_nodes_Dynamo2 12](https://user-images.githubusercontent.com/5624034/155842905-dc3b8852-93bd-4ea1-a06f-1f305bfe6cd6.gif)

![align_nodes_Dynamo2 13](https://user-images.githubusercontent.com/5624034/155842907-0b1df1aa-5f76-4623-82bf-e1e9eac1ef86.gif)

## Dynamo version

Revit 2022.1 (Dynamo 2.12)
Dynamo 2.13.0.3485 Sandbox
Dynamo Core 2.13.1.3887

## Operating system

win10

## What did you do? 

try to click the context menu

## What did you expect to see?

a working selection

## What did you see instead?

no selection

**Comment by Amoursol** [comment]
I have logged a JIRA task on this one @Thomas84

**Comment by Thomas84** [comment]
thanks for fixing in Revit 2023 :-)
