### ISSUE TITLE
WPF exception when integrate Dynamo with another host

### ISSUE THREAD

**Issue by weianweigan** [DynamoDS/Dynamo#12650]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.13.1

## Operating system

win10

## What did you do? 

I am trying to integrate Dynamo with another host and then i get a wpf XamlParseException. I think it may be caused by this line.

https://github.com/DynamoDS/Dynamo/blob/78d8eb04a72ea7fe1dc6efc42f9fafa0184d11d5/src/DynamoCoreWpf/UI/Prompts/dynEditWindow.xaml#L46

I modified the line with full uri and then it has no error.
```xaml
<ResourceDictionary Source="pack://application:,,,/DynamoCoreWpf;component/UI/Themes/Modern/DynamoModern.xaml" />
```

**Comment by QilongTang** [comment]
@weianweigan Would you propose the change or do you prefer us making that change for you?

**Comment by mjkkirschner** [comment]
interesting - does simply changing `DynamoCore` to `DynamoCoreWpf` also fix the issue?

**Comment by weianweigan** [comment]
> @weianweigan Would you propose the change or do you prefer us making that change for you? Do you mind me asking which host you were integrating?

I am trying to integrate dynamo with SolidWorks named [DynamoSolidWorks](https://github.com/weianweigan/DynamoSolidWorks). I don't know whether the change is right.If it is right, can i create a pr with other problem when i integrating dynamo with SolidWorks.

**Comment by QilongTang** [comment]
@weianweigan would you propose the change and also try the solution @mjkkirschner suggested?

**Comment by chuongmep** [comment]
yesterday, i have view DynamoModern.xaml to fix warning message and i see DynamoCore not use 
![image](https://user-images.githubusercontent.com/31106432/155826724-4dd60255-def4-4ba1-acc1-733466384194.png)
May be only need change like this: 
<ResourceDictionary Source="/DynamoCoreWpf;component/UI/Themes/DynamoModern.xaml" />

**Comment by weianweigan** [comment]
@QilongTang OK! Thanks for your help.
