### ISSUE TITLE
NurbsCurve closeCurve Bug [Dynamo 2.12.0.5650]

### ISSUE THREAD

**Issue by lgradisar** [DynamoDS/Dynamo#12651]
# Issue Description
NurbsCurve.ByControlPoints does not give warning if a string is connected to the closeCurve and it takes it as a true value, meaning that it returns double the length when using the Curve.Length node. 

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
Used NurbsCurve.ByControlPoints to construct curves with two points, degree 1, and "False" as a string for closeCurve input.

## What did you expect to see?
The node should return a warning that the input for closeCurve should be a bool and not a string and not accept it as a true bool.

## What did you see instead?
The code runs without issues, but the node understands any string as a true value and it returns a straight curve that has double the lenght, but visually you cannot see that it is closed.

## What packages or external references (if any) were used?
None

## Attaching the workspace image of a replicated bug
![CurveStringBug](https://user-images.githubusercontent.com/100343272/155490127-41bd8ada-70b2-4b51-abd3-bf8e46bcce46.png)

**Comment by mjkkirschner** [comment]
Hi @lgradisar - I'm not sure this is a bug. @pinzart90 @aparajit-pratap - don't string coalesce to bools in some cases?

**Comment by lgradisar** [comment]
> Hi @lgradisar - I'm not sure this is a bug. (it may be by design) @pinzart90 @aparajit-pratap - don't strings coalesce to bools in designscript in some cases?

Hi @mjkkirschner, I checked the designscript guide and it is yes, they convert to bools, based on the x != “” condition. It was just unfortunate in my case that I did not notice this before, as I had straight lines and could not see that they were closed and doubled in length.

**Comment by Amoursol** [comment]
@lgradisar going to close this for now, as it appears you have a solution and Dynamo is working as-designed. Please reopen if you wish to continue discussion.

**Comment by aparajit-pratap** [comment]
> Hi @lgradisar - I'm not sure this is a bug. (it may be by design) @pinzart90 @aparajit-pratap - don't strings coalesce to bools in designscript in some cases?

@mjkkirschner is correct, non-empty strings evaluate to `true `and empty to `false`.
