### ISSUE TITLE
Informe de conflictos de Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by sarahisaldana** [DynamoDS/Dynamo#12674]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Exporting map location to buildingfootprintsurfaces not working 
### What did you do?
(Fill in here)

### What did you expect to see?
(location map footprints) 

### What did you see instead?
(nothing)

### What packages or external references (if any) were used?
(DynaMaps)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.22000.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by Amoursol** [comment]
@sarahisaldana thank you for reporting this issue, but it lies with the DynaMaps package, not in Dynamo itself 😄  

Please contact Mostafa El Ayoubi at DataShapes.
