### ISSUE TITLE
bug report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by m-sexton** [DynamoDS/Dynamo#12678]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Tried to import sqlite3 in a python script node. I'm getting a ImportError: No module named _sqlite3 in Dynamo for Revit in 2020 & 2021.  I got the same error in 2019 but i added the full DLL path in the reference which resolved the issue.  2022 imports with no problem

### What did you expect to see?
access to sqlite3 module

### What did you see instead?
```
Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "C:\Program Files\Autodesk\Revit 2021\AddIns\DynamoForRevit\IronPython.StdLib.2.7.9\sqlite3\__init__.py", line 32, in <module>
  File "C:\Program Files\Autodesk\Revit 2021\AddIns\DynamoForRevit\IronPython.StdLib.2.7.9\sqlite3\dbapi2.py", line 28, in <module>
ImportError: No module named _sqlite3
```

### What packages or external references (if any) were used?
```
import clr
import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')
clr.AddReference('C:\Program Files (x86)\IronPython 2.7\DLLs\IronPython.SQLite')
import sqlite3
```

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by avidit** [comment]
Can you try with filename and extension `clr.AddReference('C:\Program Files (x86)\IronPython 2.7\DLLs\IronPython.SQLite.dll')`

**Comment by m-sexton** [comment]
Sorry for the delayed response. i was able to get it working with these lines

```
if doc.Application.VersionNumber == '2019':
	clr.AddReference(r"C:\Program Files (x86)\IronPython 2.7\DLLs\IronPython.SQLite.dll")
elif doc.Application.VersionNumber == '2020':
	sys.path.append(r'C:\Program Files\Autodesk\Revit 2020\AddIns\DynamoForRevit')
	clr.AddReferenceToFile('IronPython.SQLite.dll')
elif doc.Application.VersionNumber == '2021':
	clr.AddReference('C:\Program Files\Autodesk\Revit 2021\AddIns\DynamoForRevit\IronPython.SQLite.dll')
elif doc.Application.VersionNumber == '2022':
	clr.AddReference('C:\Program Files\Autodesk\Revit 2022\AddIns\DynamoForRevit\IronPython.SQLite.dll')
```
