### ISSUE TITLE
Rectangle node tooltip meaningless

### ISSUE THREAD

**Issue by TimWaldock** [DynamoDS/Dynamo#1270]
Apologies for such a basic question/issue - I'm relatively new with Dynamo, and cannot find any help for this anywhere:
In trying to use the "Rectangle" node, it is not obvious what the Transform input needs to be.  The tooltip is meaningless - I think it needs to be fixed?

![rectangle node tooltip](https://f.cloud.github.com/assets/6936176/2405563/e1d9bda8-aa53-11e3-8d84-7180c83045a7.JPG)

Eventually I figured out it needs a "Rotate transform" node as input.
For learning Dynamo it would really help if all tooltips were explicit about inputs.  Even the "axis" input for Rotate Transform was a bit cryptic [Axis(XYZ)] - I don't know what the XYZ relates to, but it appears to be relative to  0,0,0, not to the XYZ value for origin?

**Comment by ikeough** [comment]
Please try `Rectangle.ByWidthLength` with a `CoordinateSystem` for the first input.

Closing as out of date. If this is still an error in more recent builds, please re-open.
