### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by ilfabbra** [DynamoDS/Dynamo#12749]
I can't see the node RayBounce.ByOriginDirection. Why is not present as indicated from Dynamo Dictionary?

---
OS: `Microsoft Windows NT 10.0.19043.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by ilfabbra** [comment]
Hi, thanks for the help. I opened Dynamo through Revit, so I guess is Dynamo Revit. I am learning Dynamo and I have the student license.

![image](https://user-images.githubusercontent.com/102625454/160706585-a3754615-55da-403c-a27f-69d03104a487.png)

![image](https://user-images.githubusercontent.com/102625454/160706825-11d0d9fd-e19c-4d0f-a8ad-503bc80489af.png)

**Comment by Amoursol** [comment]
Hello @ilfabbra - We have found a bug (As seen in this Dynamo forum thread: https://forum.dynamobim.com/t/raybounce-byorigindirection-missing-node/74856/6) that means this node is unintentionally hidden from the Library 😢  

So sorry about this - I have filed a task for us to fix it. 

In the meantime, you can still access the node by doing the following:
1. In the Dynamo canvas (Where you place nodes)
2. Right-click to open up the right-click search and context menu
3. Type in "raybounce" and you should see an entry called "ByOriginDirection"
4. Click that and it will put the node into your canvas

**Comment by ilfabbra** [comment]
It works. Thanks a lot for the help!

**Comment by Amoursol** [comment]
@ilfabbra awesome! We're going to expose this again, but please do use the workaround in the short-term.
