### ISSUE TITLE
Point.ByCoordinates operation failed

### ISSUE THREAD

**Issue by EliaBarsoum** [DynamoDS/Dynamo#12750]
## Dynamo version

DynamoCoreRuntime_2.13.1.3887

## Operating system
windows 10 pro

## What did you do? 

From the library in Dynamo, I added a Code Block then Watch and then Point.ByCoordinates. Then I added 1..#6..10 in code block
(I already have Dynamo and Revit 2022 installed.

## What did you expect to see?

I expected to see some points on the grid

## What did you see instead?

I got Null values and a warning saying "Warning: Point.ByCoordinates operation failed. The type initializer for 'Autodesk.Libg.LibgPinvoke' threw an exception.

**Comment by Amoursol** [comment]
@EliaBarsoum can you please try restart Dynamo and try again? Do you get the same message? Dynamo could have got caught in a funny state 😊
