### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by YasmineBimplan** [DynamoDS/Dynamo#12767]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Element.GetParameterValueByName of an area which is not placed but still in the project. (I tried to read out the area and the perimeter of this element)

### What did you expect to see?
Value = 0,00

### What did you see instead?
Error message dynamo

### What packages or external references (if any) were used?
/

### Stack Trace
Unable to locate managed object for given dsObject.

   bij ProtoFFI.CLRObjectMarshaler.CreateCLRObject(StackValue dsObject, Context context, Interpreter dsi, Type type)
   bij ProtoFFI.CLRObjectMarshaler.UnMarshal(StackValue dsObject, Context context, Interpreter dsi, Type expectedCLRType)
   bij ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   bij ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   bij ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   bij ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   bij ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   bij ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   bij ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   bij ProtoCore.DSASM.Heap.Sweep()
   bij ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   bij ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   bij ProtoScript.Runners.LiveRunner.ApplyUpdate()
   bij ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   bij ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   bij ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   bij Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   bij Dynamo.Scheduler.AsyncTask.Execute()

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by Amoursol** [comment]
@YasmineBimplan thank you for submitting this report - this behavior indeed shouldn't cause a crash 😊 

@mjkkirschner do you think this is on the Core side, or DynamoRevit side? I can transfer if the latter.

**Comment by mjkkirschner** [comment]
@Amoursol the crash is on the core side.

**Comment by Amoursol** [comment]
@YasmineBimplan - I can't reproduce this my side on Dynamo 2.10.1 and in Revit 2022

![image](https://user-images.githubusercontent.com/12857357/162238286-50252f14-cbd5-4dfc-8afc-4a68f050e965.png)

Was there something else happening? Are you able to provide reproducible steps?
