### ISSUE TITLE
Library Text Size

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#12874]
### Discussed in https://github.com/DynamoDS/Dynamo/discussions/12873

<div type='discussions-op-text'>

<sup>Originally posted by **Jesscardi13** May 11, 2022</sup>
Hi all, 

I'm new to Dynamo so seeing the library task bar is kind of important to me and currently it is so small that I've got to get really close to my screen to see it. Is there a way to make that text larger? Currently it is half the size my mouse icon, which is the standard size. Anything helps, so thanks in advance. 
![Dynamo Library](https://user-images.githubusercontent.com/105389426/167932708-b9dd9fd6-9d26-4bc6-b81b-9b6173db5864.PNG)

</div>

**Comment by mjkkirschner** [comment]
@jesscardi13

two things for you to try - 
1. try adjusting your windows display scaling settings under display control panel
2. try changing your zoom level in internet explorer - as crazy as that sounds.

**Comment by Jesscardi13** [comment]
@mjkkirschner 

Thank you. I tried changing the scale of my Internet explorer but that didn't effect anything, and to make the task bar readable by scaling the desktop it had to be 175% which skews everything else on that monitor, so it doesn't seem feasible in the long run. I was hoping there was some setting in the program that I had been overlooking.

**Comment by QilongTang** [comment]
@Jesscardi13 Are you using a 4k monitor or a regular one?

**Comment by Jesscardi13** [comment]
@QilongTang the 2 monitors are regular
