### ISSUE TITLE
Dynamo Corrupted

### ISSUE THREAD

**Issue by deandaiuto** [DynamoDS/Dynamo#12879]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

1.3.4.6666

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

Windows 10 Enterprise

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Try to open Dynamo file

## What did you expect to see?

(Fill in here)

## What did you see instead?
![Capture](https://user-images.githubusercontent.com/26013315/168072556-6e0927d0-5aed-4cc5-b38a-9db9408a91f1.PNG)

**Comment by deandaiuto** [comment]
All the information that you need is in the post above

**Comment by QilongTang** [comment]
@deandaiuto Would you share the file with me? From the callstacks, it seems the file is corrupted XML file

**Comment by deandaiuto** [comment]
all of the files wont open. But they do open and work in later versions of revit and Dynamo

**Comment by deandaiuto** [comment]
> Are you trying to open a .dyn that is from dynamo 2.x - those are json based, not xml and will not open in dynamo 1.x

It was all working about a week ago with no changes since then.

**Comment by QilongTang** [comment]
> > @deandaiuto Would you share the file with me? From the callstacks, it seems the file is corrupted XML file. Are you able to open it on a different computer or a different Dynamo version?
> > all of the files wont open. But they do open and work in later versions of revit and Dynamo

If they only do not work in this particular v1.3.4, then this could be something our team can look at
