### ISSUE TITLE
Wish: Show current vs. former Used By info

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1291]
On the package manager website, it would be helpful if the "Used By" info were organized in two sections:
- Currently used by
- Formerly used by

Use case: I was culling a custom node from one of my packages (because there was now a built-in node with the same capabilities) and I was trying to track down all the packages that were using that custom node. It turned out that half of the packages in the list weren't using that node anymore...

**Comment by Racel** [comment]
We  do not have any plans to improve this in the short term. Closing.
