### ISSUE TITLE
Crash report from Dynamo 2.6.2.15705

### ISSUE THREAD

**Issue by bogens01** [DynamoDS/Dynamo#12957]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Opened Dynamo through Revit manage tab. 

### What did you expect to see?
Dynamo window

### What did you see instead?
Dynamo window and a crash error

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

**Comment by bogens01** [comment]
Hi,

I'm running the Dynamo plug in for Revit 2021. I just updated Revit and
downloaded the latest hotfix hoping to fix the issue but to now avail.

**Comment by Amoursol** [comment]
Hello @bogens01 - Would you be able to please explain the issue you are experiencing? Currently, we don't have any information to further investigate to try and help you out.
