### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by BaranRostami** [DynamoDS/Dynamo#13066]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(I was trying to import an excel sheet )

### What did you expect to see?
(excel sheet data)

### What did you see instead?
(failed operation )

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by BaranRostami** [comment]
I am not sure if this might be a bug for Revit 2022 that Dynamo can not read the Excel file (.xlsx) but is okay when I use (.csv)

**Comment by QilongTang** [comment]
@DynamoDS/dynamo Is there a known issue like this in 2.10.1?
