### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by pzyskowski42** [DynamoDS/Dynamo#13120]
# Issue Description
Dynamo freezing upon opening graph.  
no 3d view in graph or ability to switch between graph and node views.  
Nodes are incomplete and unusable.
No pull down menus are working.

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows 11 Pro v21H2

## What did you do?
just tried to open or make a new graph

## What did you expect to see?
a working graph and view

## What did you see instead?
Everything is broken

## Stack Trace
No error messages were seen.
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`
![image](https://user-images.githubusercontent.com/44787108/179572321-a7c2ffbf-9247-4d77-8f87-7add620edeb7.png)
![image](https://user-images.githubusercontent.com/44787108/179572436-66b9331b-193b-486f-9ecd-e42f766cb056.png)

**Comment by QilongTang** [comment]
@pzyskowski42 Would you share us the console message in Dynamo, you can find it by drag out the bottom area and that would give us more details?

**Comment by mjkkirschner** [comment]
sounds like an addin conflict, I would start there.
What version of Revit 2023 is this? Have you installed any updates recently, or manually installed dynamo core components?

**Comment by pzyskowski42** [comment]
Revit Version:  
23.0.11.19
20220503_1030(x64)

That is the first Hotfix that Autodesk released.

I did update a few add-ins.  I'll uninstall and let you know.  As for dynamo core... the last version I would have even tried to install would have been for 2019/2020 at the latest.  I don't mess around in there.  My gut feeling is telling me that it might be pyRevit.

**Comment by pzyskowski42** [comment]
Yup. uninstalled the newest version of pyRevit.  It's working now.  I'll let them know that there is a conflict as well.

**Comment by QilongTang** [comment]
@pzyskowski42 Appreciate it!
