### ISSUE TITLE
Dynamo not show result of multiple variable code block.

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/Dynamo#13143]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.6

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Define a code block to see result, result not show correct.

## What did you expect to see?

Result will be show two list for this

## What did you see instead?

![image](https://user-images.githubusercontent.com/31106432/181396509-06936a3a-3c1e-4833-8b7a-435d00548792.png)

**Comment by duttabhishek0** [comment]
Did you tried adding a watch node at the output ports? Does it shows the same behavior or anything different?

**Comment by chuongmep** [comment]
@duttabhishek0 problem I want report is it really not show correct what is using in code block
![image](https://user-images.githubusercontent.com/31106432/181656876-38195937-8c1c-4e34-a8b3-0fd443547660.png)

**Comment by iAliJ** [comment]
Can you show us what is feeding the input of the Code Block?

**Comment by chuongmep** [comment]
This issue too long to resolve, may be I will close this.
