### ISSUE TITLE
Using Levels in Revit 2023

### ISSUE THREAD

**Issue by glenstricottarboton** [DynamoDS/Dynamo#13167]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.13.1.3891

## Operating system

Windows 11

## What did you do? 

Using levels in List.ItemAtIndex to get specific items when dealing with Lists of Lists. This does not operate in the same way in Revit Dynamo 2023 as it has in Revit 2022

## What did you expect to see?

I expected to see the same result as returned with List.ItemAtIndex in Revit/Dynamo 2022 (Screenshot below)
![dynamo 2022](https://user-images.githubusercontent.com/50857665/182528814-6b376a53-9611-41d2-b62f-fe688120869e.png)

## What did you see instead?

Instead the 'use levels' returns the list with the index 0 on every level - Screenshot of Revit/Dynamo 2023

![Screenshot 2022-08-03 170558](https://user-images.githubusercontent.com/50857665/182528260-47624b2c-9855-403b-b08a-4646f433311d.jpg)

**Comment by QilongTang** [comment]
Interesting, I think I did check that the code for List.GetItemAtIndex did not change. Maybe something else has been updated related. @aparajit-pratap @mjkkirschner @sm6srw Do you know?

**Comment by glenstricottarboton** [comment]
This issue is not limited to List.GetItemAtIndex, it appears to also happen with other components when using the 'use levels' function. Below are examples of errors with Lunchbox Mass Addition with the same inputs, first screenshot is Dynamo in Revit 2021 and second is Dynamo in Revit 2023
![image](https://user-images.githubusercontent.com/50857665/182984988-e6dcac60-7daa-44de-a5e5-93f3b5d41cd7.png)
![image](https://user-images.githubusercontent.com/50857665/182985023-f77b50e1-1743-47d7-9203-f0fc6e8c7094.png)

**Comment by QilongTang** [comment]
@glenstricottarboton Thanks, let me share this report with my larger group to get more insights and will get back to you.

**Comment by avidit** [comment]
@glenstricottarboton In first screenshot(Revit/Dynamo 2022), you are applying `@L2` on the `list` while in the second one(Revit/Dynamo 2023) you are applying it on `index`.

![gh-13167](https://user-images.githubusercontent.com/1406153/183138488-d8fc20a9-fee7-487e-b675-b75b25e24ed7.png)

**Comment by glenstricottarboton** [comment]
Thanks @avidit for that simple fix! That resolves List.GetItemAtIndex. I am having trouble with other components with only one input Lunchbox Mass Addition

**Comment by avidit** [comment]
@glenstricottarboton I don't think the problem is with `List.GetItemAtIndex` but with the `Lunchbox Mass Addition` node. I used `Lunchbox for Dynamo 2018.7.7` and it seems there were some indentation issues due to mixed use of spaces and tabs in the python script of the node. 
Revit/Dynamo 2022 used `IronPython2` where it appears it did not cause any problems whereas Revit/Dynamo 2023 uses `CPython3`. 
You can either switch to IronPython2 (using `DynamoIronPython2.7` package from `DynamoTeam`) or try to fix the issue in the node.
![gh-12167_1](https://user-images.githubusercontent.com/1406153/183924259-395bdcef-d46f-4de8-9bd3-7095765b31d8.gif)

**Comment by glenstricottarboton** [comment]
@avidit This is exactly the issue, a few other lunchbox nodes needed the same change and it is now working as expected. Thanks for all your help everyone!
