### ISSUE TITLE
来自 Dynamo 2.13.1.3887 的崩溃报告

### ISSUE THREAD

**Issue by quejingchang** [DynamoDS/Dynamo#13191]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.22000.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2023.213.1523
- DynamoIronPython2.7 2.1.0
- LinkDWG 0.3.91
- LinkDWG2 0.4.18
- Rhynamo 2018.11.26
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by quejingchang** [comment]
谢谢你的回复，我应该找到崩溃的原因了，问题出现在我更改并保存自定义节点后，重新启动Dynamo，打开了存在旧自定义节点的dyn文件，忽略了旧节点的提示，将其他节点与之链接导致崩溃的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DynamoDS/Dynamo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DynamoDS/Dynamo] 来自 Dynamo 2.13.1.3887 的崩溃报告 (Issue #13191)





 
Hello quejingchang, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.
 
Can you please fill in the following to the best of your ability:
  
What did you do?
 
What did you expect to see?
 
What did you see instead?.
  
Additional information:
  
Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
 
Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue)
 
Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
 
Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
 
Reproducible steps on how to create the error in question.

**Comment by QilongTang** [comment]
> 谢谢你的回复，我应该找到崩溃的原因了，问题出现在我更改并保存自定义节点后，重新启动Dynamo，打开了存在旧自定义节点的dyn文件，忽略了旧节点的提示，将其他节点与之链接导致崩溃的。

感谢你的回复。虽然问题根源已经找到，但是我们团队还是希望可以修好导致崩溃的问题。您认为这个问题有比较容易复现的方式吗？如果有希望可以分享给我们团队
