### ISSUE TITLE
Add Icons for a Zero Touch Assembly or Node Model assembly, Not work with NET6 SDK Style

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/Dynamo#13199]
Hi, Im try work with NET6 SDK Style target Net Framework 4.8, and I have a problem with generate file `SampleLibraryZeroTouch.customization.dll` to map icon but it not working.
Origin Guide : https://github.com/DynamoDS/Dynamo/wiki/Add-Icons-for-a-Zero-Touch-Assembly-or-NodeModel-assembly
```
<Target Name="AfterBuild">
  <!-- Get System.Drawing.dll -->
  <GetReferenceAssemblyPaths TargetFrameworkMoniker=".NETFramework, Version=v4.7">
    <Output TaskParameter="FullFrameworkReferenceAssemblyPaths" PropertyName="FrameworkAssembliesPath" />
  </GetReferenceAssemblyPaths>
  <!-- Get assembly -->
  <GetAssemblyIdentity AssemblyFiles="$(OutDir)$(TargetName).dll">
    <Output TaskParameter="Assemblies" ItemName="AssemblyInfo" />
  </GetAssemblyIdentity>
  <!-- Generate customization dll -->
  <GenerateResource  SdkToolsPath="$(TargetFrameworkSDKToolsDirectory)" UseSourcePath="true" Sources="$(ProjectDir)\Resources\SampleLibraryZeroTouchImages.resx" OutputResources="$(ProjectDir)\Resources\SampleLibraryZeroTouchImages.resources" References="$(FrameworkAssembliesPath)System.Drawing.dll" />
  <AL SdkToolsPath="$(TargetFrameworkSDKToolsDirectory)"  TargetType="library" EmbedResources="$(ProjectDir)\Resources\SampleLibraryZeroTouchImages.resources" OutputAssembly="$(OutDir)SampleLibraryZeroTouch.customization.dll" Version="%(AssemblyInfo.Version)" />
</Target>
```
This is my project setting 2 year ago in Net Framework 4.5, and it's working : https://github.com/chuongmep/ZeroTouchIconTemplate/tree/master
OUTPUT : 
![image](https://user-images.githubusercontent.com/31106432/183831315-b657b9ab-afc0-4587-8cf7-df75726f7e69.png)

My Demo Project not working with NET6 SDK Style target Net Framework 4.8 branch net6_48 :  https://github.com/chuongmep/ZeroTouchIconTemplate/tree/net6_48
OIutput: 
![image](https://user-images.githubusercontent.com/31106432/183831626-1ba2564c-e515-4db4-9f02-adf35bdb7847.png)

Any have solution appreciate !

**Comment by QilongTang** [comment]
@jasonstratton I do not suppose you guys looked at this one yet?

**Comment by pinzart90** [comment]
@chuongmep I created a PR to fix this problem
https://github.com/chuongmep/ZeroTouchIconTemplate/pull/1
Please test it locally

**Comment by chuongmep** [comment]
> @chuongmep I created a PR to fix this problem [chuongmep/ZeroTouchIconTemplate#1](https://github.com/chuongmep/ZeroTouchIconTemplate/pull/1) Please test it locally

Rorry I'm reply late, tested and it working perfect. Thank you .
