### ISSUE TITLE
Raport o awarii z Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by Kamilex1109** [DynamoDS/Dynamo#13268]
# Issue Description
Please fill in the following information to help us reproduce the issue:
I wanted to open my file that I had previously worked on. Now it cannot be opened and an unknown error pops up.

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
I wanted to open my file that I had previously worked on. 

## What did you expect to see?
I expected the project to open.

## What did you see instead?
![obraz](https://user-images.githubusercontent.com/84992719/187440667-670327dd-c3ef-4f03-af1c-2fb5aad4ef94.png)

## What packages or external references (if any) were used?
Robot Structural Analysis Professional 

## Stack Trace
```
![obraz](https://user-images.githubusercontent.com/84992719/187441124-ee7fc80d-6af0-413c-b7a7-bdd4903c528e.png)
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
@saintentropy @deepakanand
