### ISSUE TITLE
DynamoIronPython2.7 won't load the libraries I need.

### ISSUE THREAD

**Issue by DavidJImm** [DynamoDS/Dynamo#13303]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 2.13
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Upgraded to Revit 2023

## What did you expect to see?

My dwg export program work

## What did you see instead?

My dwg export program did not work because you changed Python and the old version refuses to load.
![2022-09-07 10_06_10-](https://user-images.githubusercontent.com/113043272/188912970-929bad0c-6850-434d-bcba-12a6a076c7fc.png)

**Comment by mjkkirschner** [comment]
Hi @DavidJImm - 
1. what happens when you click the install button?
2. is there anything in the console or log?
3. can you try installing the latest DynamoIronPython package (2.5) manually using the package manager search.

**Comment by DavidJImm** [comment]
I have narrowed it down to this command in Python no longer working.

options = options.GetPredefinedOptions(doc,'1')

This command used to call up the Dwg export options saved as "1". Now it
gives me this error....
[image: image.png]

**Comment by mjkkirschner** [comment]
@DavidJImm I don't see the image you attached.
