### ISSUE TITLE
Python engine could not be fund report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by tatimh** [DynamoDS/Dynamo#13347]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.22000.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by tatimh** [comment]
Hi all, I am experiencing an issue with c3d22/dynamo in win11 involving a phyton node, the interesting thing is I have two computers set the same way and everything works fine in one of them, any help will be greatly appreciated  report from Dynamo 2.12.0.5650

**Comment by mjkkirschner** [comment]
Hi @tatimh - perhaps you are trying to use a node which references IronPython 2.x but have not installed the DSIronPython package.
