### ISSUE TITLE
Could not load LibG.ProtoInterface.dll

### ISSUE THREAD

**Issue by nodatasheet** [DynamoDS/Dynamo#13377]
# Issue Description
When I try to create any geometry, node rises this warning: 
"Could not load file or assembly `LibG.ProtoInterface.dll` or one of its dependencies. The system cannot find the file specified."

## Dynamo version
Dynamo: `2.16.1.2727`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
run nod `Point.Origin`

## What did you expect to see?
Point

## What did you see instead?
Could not load file or assembly warning

## What packages or external references (if any) were used?
no

## Stack Trace
```
no crash
```

---
CLR: `4.0.30319.42000`

**Comment by nodatasheet** [comment]
Ah, looks like this is a long-lasting issue.... can close

**Comment by QilongTang** [comment]
@nodatasheet for latest version of Dynamo and gemotry, you will need latest version of ASM on your computer, this is a known issue
