### ISSUE TITLE
why I couldn't write the result of dynamo to the h5ad file ? 

### ISSUE THREAD

**Issue by liuyang218622** [DynamoDS/Dynamo#13389]
## Dynamo version
Version 1.1.0
## Operating system
Linux
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
The scripts that I used are below: 
##
import dynamo as dyn 
dyn.get_all_dependencies_version()
dyn.configuration.set_figure_params('dynamo', background='white')
adata.obs['CellID']=adata.obs.index.tolist()
##
dyn.pp.recipe_monocle(adata)
dyn.tl.dynamics(adata, model='stochastic', cores=3)
dyn.tl.reduceDimension(adata)
dyn.pl.umap(adata, color='predicted_labels')## What did you expect to see?
dyn.pl.umap(adata, color='majority_voting')
dyn.tl.gene_wise_confidence(adata, group='majority_voting', lineage_dict={'Mid erythroid': ['Late erythroid']})
dyn.pl.phase_portraits(adata, genes=adata.var_names[adata.var.use_for_dynamics][:4], figsize=(6, 4), color='majority_voting')
dyn.tl.cell_velocities(adata, method='pearson', other_kernels_dict={'transform': 'sqrt'})
dyn.tl.cell_wise_confidence(adata)
dyn.tl.confident_cell_velocities(adata, group='majority_voting', lineage_dict={'Mid erythroid': ['Late erythroid']})
dyn.pl.streamline_plot(adata, color=['majority_voting'], color_key=color_key, basis='umap', show_legend='on data', show_arrowed_spines=True)
dyn.cleanup(adata)
#####
The above scripts all worked well. But when I written the result to h5ad, 
####
results_file="../test.h5ad"
adata.write(results_file)
######
I suffered from an error report. 
"TypeError: Can't implicitly convert non-string objects to strings". 
Then I searched out the answer mentioned in "https://github.com/aristoteleo/dynamo-release/issues/292". I tried to deal with the issue  follow the example.  I found  that many columns(for example: "beta", "gamma", "half_life", "alpha_b", "alpha_r2", "gamma_b", "gamma_r2", "gamma_logLL", "delta_b" , "delta_r2", "bs", "bf", "uu0", "ul0", "su0", "sl0", "U0", "S0", "total0") in adata.obs were non-string and they were all "none".  
Then I  deleted these columns as below:
##
for i in adata.var.columns[20:39]:
    print(i)
    del adata.var[i]
##
But, I still suffered from other error reports when I written the result of dynamo to h5ad, such as: 

![image](https://user-images.githubusercontent.com/13673840/194762713-fdd4b210-2baa-4bec-a1ea-0a9424059964.png)“” 
![image](https://user-images.githubusercontent.com/13673840/194762752-5fe4252d-d3e5-4645-a375-5f5f14c7c05a.png)
I continued to delete the data in adata.uns that reported in the error message as below: 
##
del adata.uns['cell_phase_genes']
del adata.uns['velocyto_SVR']
##
Finally, I written the result of dynamo to h5ad successfully !
But I don't think it's a good solution to the problem. Much information was deleted during the process. 
Are there any  other better solutions to the problem? 

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by mjkkirschner** [comment]
sorry @liuyang218622 this is not the repo you are looking for.
