### ISSUE TITLE
BUG report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by atis-s** [DynamoDS/Dynamo#13388]
# Issue Description
Bug that causes not to display GeometryColor.BySurfaceColors surface colors correctly.
If i translate points by 0 it displays correctly. 
https://user-images.githubusercontent.com/22381084/194756383-777960f5-1c11-4220-910f-54b5be79dbc7.mp4

## Dynamo version

Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
Made  GeometryColor.BySurfaceColors

## What did you expect to see?
 GeometryColor.BySurfaceColors surface with colors

## What did you see instead?
 GeometryColor.BySurfaceColors with no colors 

## What packages or external references (if any) were used?
![image](https://user-images.githubusercontent.com/22381084/194756421-0ebb2913-f9f2-4feb-93ac-9debf6b5621c.png)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
The previous uncolored surface is hiding the colored one - disable the preview of the input surface.
