### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by ongjiundar** [DynamoDS/Dynamo#13439]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
(Missing "Setting" in the Dynamo taskbar)

## What did you expect to see?
("Setting" to be shown in the Dynamo taskbar)

## What did you see instead?
("Setting" not seen 
![Capture](https://user-images.githubusercontent.com/116799543/198244134-14b46cd8-2007-4e42-b573-895bef8a7ded.PNG)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by ongjiundar** [comment]
I've got the following error message which I couldn't change any setting in "Preference". May I know how to change the setting?
_[Warning: Your inputs lie outside of the allowable modeling range, consider choosing the Large setting with a modeling range between 0.01 and 1,000,000 from the "Settings => Geometry Working Range" dialog]_

**Comment by QilongTang** [comment]
@aparajit-pratap Do you know the answer to this one?

**Comment by aparajit-pratap** [comment]
@ongjiundar you can change the geometry working range from the `Dynamo`->`Preferences` menu, which opens the `Preferences` dialog, then under the General tab, you'll find `Geometry Scaling` section as shown below:
![image](https://user-images.githubusercontent.com/5710686/198667951-2ba2bfaa-2fb9-4954-8980-378abba1fa64.png)
Hope this helps.

**Comment by aparajit-pratap** [comment]
@QilongTang I think we need to change the above warning message to point users to this new Preferences dialog. The current message is old and still directs users to the old menu. Will file a task to update this.

**Comment by mjkkirschner** [comment]
![Screen Shot 2022-10-28 at 11 08 25 AM](https://user-images.githubusercontent.com/508936/198669455-6e1422eb-8ec6-4268-8ace-447300088ff8.png)

the setting to change is here.

**Comment by ongjiundar** [comment]
That works! Thanks a lot for your help =)
