### ISSUE TITLE
Data.OpenXMLImportExcel importing formulas

### ISSUE THREAD

**Issue by Teun1** [DynamoDS/Dynamo#13475]
## Dynamo version

2.12.1 and upwards.
I checked 2.13.1 in Revit2023 and Sandbox 2.15.2

## Operating system

Windows 10

## What did you do? 

Using Data.OpenXMLImportExcel. 
Because Excel Import Node does not work in our VDI environment

## What did you expect to see?

The results of every cell in a specific sheet, just as it shows up in Excel.

## What did you see instead?

It works for most part but not for formula's with an indirect relation. In these cases you will get the complete excel formula.
E.g. INDIRECT or OFFSET. And there must be more cases like this.

In Excel if you check the formula in cell A5, it shows no result, but a message that it needs recalculation. And I think that might be the problem we are facing here. Simple formulas do not give any problems. 
Other Excel import nodes do not give a problem with this kind of formulas. Like the ones from BumbleBee or the native Excel Nodes (they do work on my local computer)

![image](https://user-images.githubusercontent.com/7262482/200119440-ee3a7322-d948-49e3-9a98-674bcfeda6fc.png)

[2_13_1 221005 OpenXMLimportExcel.zip](https://github.com/DynamoDS/Dynamo/files/9943766/2_13_1.221005.OpenXMLimportExcel.zip)

**Comment by avidit** [comment]
Fixed in 2.18 #13647
