### ISSUE TITLE
Crash report from Dynamo 2.6.2.15705

### ISSUE THREAD

**Issue by antonio-vachev** [DynamoDS/Dynamo#13525]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Upon "Force Re-execute", Dynamo crashes fatally. This has now happened multiple times, whenever I had run the script manually and then try to force re-execute it.

### What did you expect to see?
I was trying to rerun the script so that I can refresh the input data.

### What did you see instead?
The standard Dynamo error "Uh oh... something went wrong and Dynamo has crashed, sorry about that."

### What packages or external references (if any) were used?
Several of the widely used packages - clockwork, rhythm, RIE

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.19044.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.2.15705`

**Comment by QilongTang** [comment]
@antonio-vachev This bug has not been reported by other users a lot. I dont think our QA has been able to reproduce this. Do you think you can share a minimal graph to reproduce this?
