### ISSUE TITLE
Trusted locations error

### ISSUE THREAD

**Issue by NonicaTeam** [DynamoDS/Dynamo#13609]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.16.1.2727

## Revit version

2023.1.1

## Operating system

Windows 10

## What did you do? 

After adding a main folder as a trusted location, when I open a Dynamo script in a subdirectory within that trusted folder. If I click on Preferences in Dynamo and Security (no changes are made there) and then close the preferences window. The subfolder is detected as not trusted and the warning is displayed.

## What did you expect to see?

I expect the script to not be detected as untrustable at all times as it is within a subfolder of the trusted main directory.

## What did you see instead?

A warning that the scripts is not in a trustable location and blocking the execution button.

**Comment by avidit** [comment]
@NonicaTeam It should have been fixed in 3.0, what build version are you using?

**Comment by NonicaTeam** [comment]
Indeed @avidit , seems to be fixed in v.3.0.3. Many thanks
