### ISSUE TITLE
Crash report from Dynamo 2.16.0.2501

### ISSUE THREAD

**Issue by KarangaM** [DynamoDS/Dynamo#13605]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.0.2501`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
Tried to input a point node

## What did you expect to see?
Point node

## What did you see instead?
warning that the dll file was missing
![image](https://user-images.githubusercontent.com/119932280/205878394-71c50984-2ff1-4e44-9836-c9edd2a06942.png)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by mjkkirschner** [comment]
likely expected if you don't have some other adsk software installed, please see this thread https://forum.dynamobim.com/t/dynamo-sandbox-without-revit-current-status/37589/4 or others about sandbox and geometry.
