### ISSUE TITLE
FileSystem.CopyDirectory does not work when files lack an extension

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#13617]
## Dynamo version
2.12.x, 2.13.x, 2.16.x

## Operating system
Windows 11

## What did you do? 
![image](https://user-images.githubusercontent.com/15744724/206262844-7389e5c5-8870-4b81-8ced-c590c1b9dfa5.png)

## What did you expect to see?
The packages directory getting copied

## What did you see instead?
an error on the node with the copy stopping at that point.

## note, before anyone says, 

"why have a file with no extension"?!. This is because of files named `LICENSE` with no extension mirroring how GitHub works. The package this is happening with is @andydandy74 's clockwork.

**Comment by mjkkirschner** [comment]
what is the error?

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/206276966-2bdd5c00-df30-4ead-9d9d-21a8a7dde7ce.png)
