### ISSUE TITLE
Dynamo 2.16.0.2501 can't load build-in libraries

### ISSUE THREAD

**Issue by SparkDusk** [DynamoDS/Dynamo#13636]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.0.2501`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
Try to run simple script. Create 2 point and line.

## What did you expect to see?
Line.

## What did you see instead?
Nothing. Build in library can't be loaded.

## What packages or external references (if any) were used?

Dynamo log started 2022-12-13 22:17:21Z
Python template set to default.
launch darkly initalized
LD startup time: 797 
<<<<<InitDone>>>>>
feature flag exe starting
<<<<<Sod>>>>>
{"graphics-primitive-instancing":false,"testFlag":false,"EasterEggIcon1":false,"EasterEggMessage1":"NA","CER":false,"NodeAutocompleteMachineLearningIsBeta":false,"CER_v2":true}
<<<<<Eod>>>>>
EasterEggIcon1 is false FROM MODEL
EasterEggMessage1 is disabled FROM MODEL
Requesting version update info...
Dynamo -- Build 2.16.0.2501
System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for DSCoreNodesUI.Logic.If.

System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for If.

Duplicate migration type registered for SunPathDirection
The folder 'D:\Dynamo\DynamoCoreRuntime2.16.0\Built-In Packages\Packages' does not exist
Dynamo will use the package manager server at : https://www.dynamopackages.com
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\cs-CZ
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\cs-CZ
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\cs-CZ: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\cs-CZ\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\cs-CZ
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\de-DE
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\de-DE
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\de-DE: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\de-DE\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\de-DE
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\DynamoFeatureFlags
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\DynamoFeatureFlags
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\DynamoFeatureFlags: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\DynamoFeatureFlags\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\DynamoFeatureFlags
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\en-US
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\en-US
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\en-US: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\en-US\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\en-US
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\es-ES
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\es-ES
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\es-ES: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\es-ES\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\es-ES
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\extensions
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\extensions
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\extensions: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\extensions\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\extensions
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\fallback_docs
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\fallback_docs
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\fallback_docs: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\fallback_docs\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\fallback_docs
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\fr-FR
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\fr-FR
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\fr-FR: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\fr-FR\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\fr-FR
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\it-IT
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\it-IT
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\it-IT: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\it-IT\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\it-IT
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\ja-JP
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ja-JP
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ja-JP: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\ja-JP\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ja-JP
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\ko-KR
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ko-KR
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ko-KR: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\ko-KR\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ko-KR
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\libg_227_0_0
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_227_0_0
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_227_0_0: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\libg_227_0_0\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_227_0_0
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\libg_228_0_0
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_228_0_0
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_228_0_0: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\libg_228_0_0\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_228_0_0
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\libg_locale
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_locale
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_locale: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\libg_locale\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\libg_locale
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\Md2Html
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\Md2Html
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\Md2Html: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\Md2Html\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\Md2Html
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\nodes
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\nodes
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\nodes: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\nodes\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\nodes
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\Open Source Licenses
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\Open Source Licenses
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\Open Source Licenses: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\Open Source Licenses\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\Open Source Licenses
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\pl-PL
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\pl-PL
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\pl-PL: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\pl-PL\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\pl-PL
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\pt-BR
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\pt-BR
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\pt-BR: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\pt-BR\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\pt-BR
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\python_migration_fixers
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\python_migration_fixers
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\python_migration_fixers: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\python_migration_fixers\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\python_migration_fixers
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\ru-RU
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ru-RU
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ru-RU: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\ru-RU\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\ru-RU
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\runtimes
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\runtimes
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\runtimes: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\runtimes\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\runtimes
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\UI
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\UI
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\UI: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\UI\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\UI
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\unit
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\unit
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\unit: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\unit\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\unit
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\viewExtensions
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\viewExtensions
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\viewExtensions: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\viewExtensions\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\viewExtensions
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\zh-CN
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\zh-CN
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\zh-CN: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\zh-CN\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\zh-CN
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at D:\Dynamo\DynamoCoreRuntime2.16.0\zh-TW
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\zh-TW
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\zh-TW: 
 D:\Dynamo\DynamoCoreRuntime2.16.0\zh-TW\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: D:\Dynamo\DynamoCoreRuntime2.16.0\zh-TW
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
The folder 'D:\Dynamo\DynamoCoreRuntime2.16.0\Built-In Packages\Packages' does not exist
DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
Backup files timer is started with an interval of 60000 milliseconds
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384;16384
Documentation Browser (id: 68B45FC0-0BD1-435C-BF28-B97CB03C71C8) view extension is added
GeometryLibrary was not loaded, skipping DynamoManipulationExtension
DynamoManipulationExtension (id: 58B0496A-E3F8-43D9-86D2-94823D1D0F98) view extension is added
Properties (id: 28992e1d-abb9-417f-8b1b-05e053bee670) view extension is added
Graph Node Manager (id: F76F4274-537D-4782-B1E9-27E8FDE2186F) view extension is added
LibraryUI - MSWebBrowser (id: 63cd0755-4a36-4670-ae89-b68e772633c4) view extension is added
Graph Status (id: 3467481b-d20d-4918-a454-bf19fc5c25d7) view extension is added
Notifications (id: ef6cd025-514f-44cd-b6b1-69d9f5cce004) view extension is added
Package Details (id: C71CA1B9-BF9F-425A-A12C-53DF56770406) view extension is added
PackageManagerViewExtension (id: 100f5ec3-fde7-4205-80a7-c968b3a5a27b) view extension is added
Python Migration (id: 1f8146d0-58b1-4b3c-82b7-34a3fab5ac5d) view extension is added
Workspace References (id: A6706BF5-11C2-458F-B7C8-B745A77EF7FD) view extension is added
Dynamo is up to date.

Welcome to Dynamo!
00:00:01.0239050 elapsed for loading Dynamo main window.
GeometryLibrary was not loaded, skipping DynamoManipulationExtension
EasterEggIcon1 is false from view
EasterEggMessage1 is disabled from view
Browser Loaded

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by SparkDusk** [comment]
I try same script using dynamo build in revit and it works. But one of
dependencie is missing “LibG.ProtoInterface.dll”.

**Comment by avidit** [comment]
Is Revit installed in a location other than `C:\Program Files\Autodesk`? Can you try running Dynamo with [geometrypath](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Command-Line-Interface) flag, `DynamoSandbox.exe -gp C:\Program Files\Autodesk\Revit 2023`

**Comment by SparkDusk** [comment]
Hi, I find out the riot of the problem. The dynamo sandbox and revit
version should be same.

**Comment by SparkDusk** [comment]
Thanks for help.
