### ISSUE TITLE
Markdown helping files fail in dynamo 2.16

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#13648]
Markdown helping files fail in Dynamo 2.16/Revit 2023
...can the number of files be an issue? I have more than 1100 nodes/functions in my Orchid package!

it looks fine in Dynamo 2.12/Revit 2022
![image](https://user-images.githubusercontent.com/2844374/210214875-6a324ca9-11cf-4ee4-b73d-703560b27dd5.png)

however, not so good in Dynamo 2.16/Revit 2023
![image](https://user-images.githubusercontent.com/2844374/210214963-21498a7e-b76a-4cd1-be7c-5fb11982ebf4.png)

...and doc files does exist!
![image](https://user-images.githubusercontent.com/2844374/210215009-ef8c7964-1702-4dbe-8867-88dc662fd902.png)

**Comment by erfajo** [comment]
Besides, there is also a problem with several signatures for a method
![image](https://user-images.githubusercontent.com/2844374/210217969-69e3289e-0f90-4369-b020-736cdf03c3e3.png)

**Comment by erfajo** [comment]
Lastly... It would be better if there were an option for .net developers to maintain the markdown files as one pr. Class. That would lower my amount of files from +1100 to around 150 files.

Furthermore is the idea of the input port names not good, it would be much better if it was the type instead, like is the case with the naming convention for icons. In fact keep the icon naming convention instead of using parenthesis that gives other issues!

**Comment by erfajo** [comment]
I have not tried anything else than what is available to normal users, meaning what you release via Revit updated. Anything not common available is not something I take into account.

However, this should have been tested before releasing, so I will suggest that you extend your testing environment to include markdown files and their link from foreign packages. Try testing it on the sample zero touch project.

**Comment by erfajo** [comment]
I have now tried the latest 2.18 core build... and the same nodes fail, however, much more errors occur, but that must be due to the beta status this build has, and the reason why I don't use time on anything else than the released versions.

**Comment by mjkkirschner** [comment]
thanks @erfajo.

**Comment by erfajo** [comment]
Just for the record, i have testet if png files should be the problem, if "_img" should be added, and if the amount of files (more than 1100) should be the problem... None of that solved the problem.

I did also traverse the view extension file and must admit that it didn't gave anything... However, i could not figure how your split the filename around the parenthesis and where your find the linked image ressource files... But i did only see what was available in the master branch.

**Comment by avidit** [comment]
Tracked internally [DYN-5497](https://jira.autodesk.com/browse/DYN-5497)

**Comment by RobertGlobant20** [comment]
@erfajo could you provide an example of the files that you used? For example one .md and the .png file.
I've already downloaded the core version from here https://github.com/erfajo/OrchidForDynamo/tree/master/Zipped but the .png files are not present. Thanks

**Comment by erfajo** [comment]
Sure, here is a sample... this includes also the dyn graph files.
[Documentation.zip](https://github.com/DynamoDS/Dynamo/files/10380147/Documentation.zip)

**Comment by avidit** [comment]
Fixed by https://github.com/DynamoDS/Dynamo/pull/13703 in Dynamo 2.18

**Comment by erfajo** [comment]
Well yet another crappy bot message from my newly created issue... stop those crappy and useless bots :-(

reopen https://github.com/DynamoDS/Dynamo/issues/13814 and do something about that... and shot down those crappy bots...
