### ISSUE TITLE
Dynamo Nodes Library

### ISSUE THREAD

**Issue by shahnawaz3396** [DynamoDS/Dynamo#13646]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version- 2.0.4

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system- Windows 10 pro

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Dynamo node library used to show up before but it is not displaying now
![Uploading Capture.PNG…]()

**Comment by mjkkirschner** [comment]
Hi @shahnawaz3396 Are you using Dynamo in Revit or something else?

**Comment by shahnawaz3396** [comment]
> Hi @shahnawaz3396 Are you using Dynamo in Revit or something else?

Using it in Revit
