### ISSUE TITLE
Crash report from Dynamo 2.16.1.2727

### ISSUE THREAD

**Issue by wntrh0lm** [DynamoDS/Dynamo#13649]
# Issue Description
Please fill in the following information to help us reproduce the issue:

Attempting to export work space or backround 3d view. When I click on export as image in top right corner, nothing happens. No image is created and no prompt to save an image

## Dynamo version
Dynamo: `2.16.1.2727`

## Operating system
OS: `Microsoft Windows NT 10.0.22621.0`
Edition	Windows 11 Home
Version	22H2
Installed on	‎3/‎11/‎2022
OS build	22621.963
Experience	Windows Feature Experience Pack 1000.22638.1000.0

## What did you do?
Clicked on 'Export as image' top right of Dynamo Screen

## What did you expect to see?
An image to be created of the work space
## What did you see instead?
nothing happened

## What packages or external references (if any) were used?

None

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
This has been fixed in 2.17. As a workaround please use File > Export.
