### ISSUE TITLE
 Loading .NET library: CompilerInternalException if methods are present with optional parameter of type enum (2nd attempt)

### ISSUE THREAD

**Issue by MichaelBuehler** [DynamoDS/Dynamo#13671]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

ALL up to 2.17

## Operating system

Windows 10

## What did you do? 

Loading a dll into Dynamo Sandbox or Dynamo Revit.
The dynamo load library function will cause 'CompilerInternalException' error message if a method like this is present

myClass.AnyMethod(myCustomEnumType parameter = myCustomEnumType .None);
because "parameter" provides a default value of a custom type.
It looks like all dynamo versions are affected (I found in 2.12.0 but it appears also inside current 'main' code).

This is caused by the Dynamo code parsing the dll to generate nodes:

Engine\ProtoCore\FFI\CLRDLLModule
Method ParseArgumentSignature(MethodBase method)

This is caused by the Dynamo code parsing the dll to generate nodes:

Engine\ProtoCore\FFI\CLRDLLModule
Method ParseArgumentSignature(MethodBase method)
..
foreach (var parameter in parameter)
{
if (parameter.IsOptional
{
var defaultValue = = parameter.DefaultValue;
if (defaultValue != null)
{

**var rhs = AstFactory.BuildPrimitiveNodeFromObject(defaultValue); // EXCEPTION**

}
}
}

which calls

Engine/ProtoCore/Parser/AssociativeAST.cs
Method BuildPrimitiveNodeFromObject(object value)
where value must be of type short, int, long, float, double, string, boolan - otherwise it will throw exception.

## What did you expect to see?

No error on loading a dll.

Also: If error a more meaningful error message would be helpful.
Currently: 'Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown

Including dll name + class name + method name (or at least dll name) would be extreme helpful

quite often errors can be caused due a dependency.. (version conflict for example). Which dependency?

## What did you see instead?

A dialog 'Failed to load library'.

**Comment by mjkkirschner** [comment]
https://jira.autodesk.com/browse/DYN-5506

**Comment by erfajo** [comment]
Sorry to interrup, but this does look like something I have put on the whish list, and I think I have got an idea how this can be fixed
https://github.com/DynamoDS/DynamoWishlist/issues/237

**Comment by mjkkirschner** [comment]
Thanks @erfajo I will review the link - but this issue should now be fixed. 
You should be able to use enum default values just using optional argument syntax in c# without using the dynamo defaultvalue attribute after the linked pr.

**Comment by erfajo** [comment]
Will this be shipped with 2.18? Then I will start testing :-)

**Comment by mjkkirschner** [comment]
currently targeted for 2.19 (current master)
