### ISSUE TITLE
node views not displaying  

### ISSUE THREAD

**Issue by LianieH** [DynamoDS/Dynamo#13704]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

Dynamo Core 2.12.1.8246
Dynamo Revit 2.12.1.8411

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

Windows 10 Enterprise

## What did you do? 

Open Dynamo, add scripts (but the boxes are not displaying only, the nodes.

## What did you expect to see?

The code boxes are missing, I am only seeing lines/nodes.

## What did you see instead?

Code boxes.

![image](https://user-images.githubusercontent.com/123458933/214264515-b746180a-b728-4a44-b8b3-1fb0ad78d9c8.png)

**Comment by mjkkirschner** [comment]
reported many times.
Very likely a Revit addin / package conflict - 
1. search issues for similar closed issues.
2. disable addins and packages
3. add them back to id the conflict
4. also check your log.
