### ISSUE TITLE
Request for means to create dynamo deployments with packages

### ISSUE THREAD

**Issue by apsis0215** [DynamoDS/Dynamo#13736]
## Dynamo version
Dynamo Core 2.13.1.3887
Dynamo Revit 2.13.1.6202
(Up-to-date)

## Revit version
2023.1 & R22 & R21 ... Focus on 22 & 23
**& Civil 3D 2023**

## Operating system
Windows 10 / 11 in some cases

## What did you do? 

Tried to 'prep' Dynamo to point at library locations for custom (run/player) scripts for deployments.

## What did you expect to see?

1. REG or INI or something that after Revit is installed, Dynamo is pre-populated with locations of various packages & Updates
2.  Means to update these same locations remotely VIA some deployment method for updates.
(How does dynamo track this and how can we effectively manage it on install?)

## What did you see instead?

After installing Revit and trying to prepopulate Dynamo in Revit 20- Dynamo reset. Attempted to create a journal to run revit after 1st install which opened and closed dynamo - but limited success and very clunky/breakable process.

Is there a direct means to add/remove "Company approved" libraries in dynamo VIA REG, or INI or some other means? Preferably a way that won't affect end-user development attempts?

Seems like this would open possibilities for managing and scanning for old libraries to be replaced by new updated versions.

Thanks-
Ron

**Comment by Amoursol** [comment]
Hi @apsis0215 - We are collecting thoughts around where to take our Deployment of Settings work next (Refer to https://dynamobim.org/dynamo-core-2-17-release/) and this could form part of it. 

How would you envision access-listing approved packages best working for you?
