### ISSUE TITLE
Papercut report from Dynamo 2.18.0.3665

### ISSUE THREAD

**Issue by aliasguru** [DynamoDS/Dynamo#13730]
# Issue Description
I am missing the shortcut `Ctrl + I` to isolate the selected geometry in the background preview. This was super helpful before, when you had a lot of stuff overlapping each other, and you wanted to know exactly which node produces which geometry. The shortcut has been remapped to a function which opens a file browser, header is "Insert Title (Replace)", and does something unknown to me.

Is there an alternative shortcut somewhere for isolation of selected geometry? At the moment I always have to navigate into the preferences to toggle this, which is inconvenient, as I tend to toggle it a lot.

## Dynamo version
Dynamo: `2.18.0.3665`

## Operating system
OS: `Microsoft Windows NT 6.2.9200.0`

## What did you do?
See steps above, I hit `Ctrl + I` in a node graph

## What did you expect to see?
toggling the "Isolate Selected" property of Dynamo

## What did you see instead?
a file browser popping up

## What packages or external references (if any) were used?
just my own, but they should not have interfered

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by aliasguru** [comment]
please also note that the [docs](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Keyboard-Shortcuts) still list `Ctrl + I` as the shortcut to isolate geometry

**Comment by Amoursol** [comment]
@aliasguru Dynamo 2.18 is currently only daily builds, which means things are changing and could be broken. We have not actively removed this short-cut, but will double check to confirm it still works 👍 

FYI @avidit - can we please confirm that this hasn't been broken inadvertently?

**Comment by Amoursol** [comment]
Thanks @avidit

**Comment by aliasguru** [comment]
I don't have access to the linked fix, it always asks me to login to an Autodesk account, so I can't test if the problem is resolved by it. Can anyone confirm that it fixes the problem? Is there a plan to merge it to master soon?

**Comment by aliasguru** [comment]
Any updates on this? Will the fix be merged to master at some point?

**Comment by reddyashish** [comment]
@aliasguru Thank you for reporting it. We will fix this soon and update this thread when it is merged.

**Comment by avidit** [comment]
Fixed by https://github.com/DynamoDS/Dynamo/pull/13995
