### ISSUE TITLE
Reopening Issue because it was closed.  I could not access Jira to read or respond.

### ISSUE THREAD

**Issue by LoRue656Plus10** [DynamoDS/Dynamo#13741]
Please reference this issue:

https://github.com/DynamoDS/Dynamo/issues/13627

For some reason, Autodesk had an error with me getting into Jira.  I would appreciate a response about my submission.

Please do not respond using Jira.  I will not be able to access it.

.dyn and .dyf files are attached in the Crash Report Zip file.

What did you do?
Ran my large Dynamo script

What did you expect to see?
Creation of skeleton Revit model with levels, rooms, areas, properties, parking objects and generic model extrusion families

What did you see instead?
Got error/crash right at the end, but everything worked without any warnings!

What packages or external references (if any) were used?
Crumple 20214.9.24, spring nodes 210.1.1, archi-lab.net 2021.7.1, WombatDynamo 2.3.4

Stack Trace
Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.RecursiveMark(StackValue root)
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

OS: Microsoft Windows NT 10.0.19044.0
CLR: 4.0.30319.42000
Dynamo: 2.6.2.15705

If you need sample data, let me know. Also, if you are able to give me some insight, I can do troubleshooting as well. The script is pretty complicated (to me), but it works. It is part of a workflow that uses Excel files generated from an FME Workspace. I'm using Revit 2021.1.7. If this kind of crash has already been solved in 2022/23....I guess I'll do that. To be clear, I was able to replicate multiple times (same script, different data input).
Thanks, Loren
[Crash.report.zip](https://github.com/DynamoDS/Dynamo/files/10702856/Crash.report.zip)

**Comment by LoRue656Plus10** [comment]
Please note:  I have given you all information you require.  This was acknowledged by @mjkkirschner on 12/10/22 [here](https://github.com/DynamoDS/Dynamo/issues/13627#issuecomment-1345403296).

I am hoping to get either a resolution or some kind of info that I can use to further troubleshoot.  My previous request was closed without recourse, due to some kind of Autodesk/Jira error.  I would appreciate a response through GitHub.

Thanks,
@LoRue656Plus10

**Comment by LoRue656Plus10** [comment]
Welp, looks like your bot just closed my issue.  I will not be submitting anymore.  If @mjkkirschner would like to contact me, he is welcome to, but not through Jira, reason stated above.

**Comment by LoRue656Plus10** [comment]
Much appreciated!I’ve been getting crashes usually when my graph is processing a lot of data, ie: ~3,000 list items.  If you are unable to replicate, my assumption would be the likely culprit is either OS/image-based or possibly the Revit install package itself (which is configured by our IT dept).   Hopefully we can rule something out. Feel free to contact me if you have questions. Best,LorenOn Feb 13, 2023, at 6:12 AM, Aaron (Qilong) ***@***.***> wrote:﻿
@avidit Would you give it a try and file for Turbo team? FYI: @jasonstratton

**Comment by avidit** [comment]
@LoRue656Plus10 Is it possible for you to provide the .xlsx file as well?

**Comment by LoRue656Plus10** [comment]
Hi @avidit ,
Oh, are you still working on this issue?  I thought it was closed again.  I have subsequently updated the graph quite a bit, as well as moved to Revit 2023.  Haven't had issues lately.  I wish I could troubleshoot from my end if something pops up, but you may have special tests/tools.

**Comment by avidit** [comment]
Hi @LoRue656Plus10,
Thank you for confirming. It was still open on out internal issue management system. I will close it now.
