### ISSUE TITLE
Python Script Node  - Save and Close Button does not close Python window

### ISSUE THREAD

**Issue by LoRue656Plus10** [DynamoDS/Dynamo#13774]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Core 2.12.1.8246
Revit 2.12.1.8411

## Revit version

2022.1.3

## Operating system

Windows 10 Enterprise 21H2

The Python Script node "Save and Close" button does not close.  It does appear to save, but I need to hit the X to close it.

## What did you expect to see?

Hit button, saves and closes

## What did you see instead?

Saves only.  Did not close.

**Comment by avidit** [comment]
Fixed in Dynamo 2.18
![python_script_editor](https://github.com/DynamoDS/Dynamo/assets/1406153/ef4c0931-89c8-4af6-8e28-ff908e6e7b8f)

**Comment by LoRue656Plus10** [comment]
Awesome!  Thanks everybody!
