### ISSUE TITLE
Create building floor plane with only total floor area and without dimentions?

### ISSUE THREAD

**Issue by Santhan9999** [DynamoDS/Dynamo#13780]
### Discussed in https://github.com/DynamoDS/Dynamo/discussions/13779

<div type='discussions-op-text'>

<sup>Originally posted by **Santhan9999** February 27, 2023</sup>
For our building modelling in Generative design in Dynamo, we know the range of total floor area but we don't have the dimensions range. Is there a way to model the building with only the total floor area?</div>

**Comment by Amoursol** [comment]
Hello @Santhan9999 - This is a better question for the [Dynamo Forum](forum.dynamobim.com). Have you tried asking there yet?
