### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by MichelZaal85** [DynamoDS/Dynamo#13807]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
tried openening a file in dynamo

### What did you expect to see?
a 'open file' dialog

### What did you see instead?
Dynamo has crashed!

### What packages or external references (if any) were used?
none

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.22000.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by MichelZaal85** [comment]
> Hello MichelZaal85, thank you for submitting this issue! We are super excited that you want to help us make Dynamo all that it can be. However, we need some more information in order for the Dynamo team to investigate any further.
> 
> Can you please fill in the following to the best of your ability:
> 
> * Dynamo version
> * Operating system.
> 
> Additional information:
> 
> * Filling in of the provided Template (What did you do, What did you expect to see, What did you see instead, What packages or external references (if any) were used)
> * Attaching the Stack Trace (Error message that shows up when Dynamo crashes - You can copy and paste this into the Github Issue)
> * Upload a .DYN file that showcases the issue in action and any additional needed files, such as Revit (Note: If you cannot share a project, you can recreate this in a quick mock-up file)
> * Upload a Screenshot of the error messages you see (Hover over the offending node and showcase said errors message in the screenshot)
> * Reproducible steps on how to create the error in question.

Thanks you for the reply!

versions
Dynamo Core: 2.10.1.3976
Dynamo Revit: 2.10.1.4002

OS:
Windows 11 Enterprise, 21H2

**Comment by mjkkirschner** [comment]
Hi @MichelZaal85 can you share a screenshot or the text of the crash stack trace?
