### ISSUE TITLE
Couldn't open Dynamo, Pop up an analytics error message window.

### ISSUE THREAD

**Issue by arshidkuppanath** [DynamoDS/Dynamo#13806]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Don't know because it can't open, Using Revit 2021.1 version

## Operating system

Windows 10

## What did you do? 

Opened dynamo in Revit

## What did you expect to see?

A dynamo interface

## What did you see instead?

System.ArgumentException: An item with the same key has already been
added. at System.ThrowHelper.ThrowArgumentException (ExceptionResource
resource)
at System.Collections.Generic. Dictionary 2.Insert(TKey key, TValue
value, Boolean add) at Dynamo.Logging.DynamoAnalyticsClient.RegisterGATracker(Service service)
at Dynamo.Logging. Dynamo AnalyticsClient.Start()
at Dynamo.Logging.Analytics Service.Start(DynamoModel model) at Dynamo.Models. DynamoModel.InitializeInstrumentationLogger() at Dynamo.Models.DynamoModel..ctor(StartConfiguration config) at
Dynamo.Applications.Models.Revit DynamoModel..ctor(RevitStartConfig uration configuration)
at
Dynamo.Applications.Models.RevitDynamoModel.Start(RevitStartConfig uration configuration)
at Dynamo.Applications. Dynamo Revit.InitializeCoreModel(DynamoRevitCo mmandData commandData)
at Dynamo. Applications. Dynamo Revit.ExecuteCommand(Dynamo RevitCom mandData commandData)

![Dynamo Issue](https://user-images.githubusercontent.com/127305829/223718152-78214731-693e-4ff0-887f-f57e617f33b0.JPG)

**Comment by QilongTang** [comment]
Please check out the forum thread where other users discussing this: https://forum.dynamobim.com/t/cant-open-dynamo-in-revit-2021/87040/7. Looks like one user was unblocked after trying the fixes.

**Comment by Amoursol** [comment]
@arshidkuppanath closing for now. Please reopen if the fixes in Aaron's link didn't work.
