### ISSUE TITLE
Heatmap for transcriptional dynamics in Dynamo

### ISSUE THREAD

**Issue by jefferyUstc** [DynamoDS/Dynamo#13818]
The dynamical model (scvelo) recovers the latent time of the underlying cellular processes, then users can plot the top-likelihood genes in a heatmap form to represent the transcriptional dynamics (https://scvelo.readthedocs.io/en/stable/DynamicalModeling/#Latent-time). How can we make it in dynamo?

**Comment by QilongTang** [comment]
@Amoursol FYI
