### ISSUE TITLE
ElementWrapper does not convert 3DView as expected!

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#13832]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

any

## Operating system

any

## What did you do? 

fail tested your code

## What did you expect to see?

return of a 3DView as dynamo element

## What did you see instead?

null

Why do you sort out 3d template views? It should be possible to send template 3DView... seems like a silly restriction. Worst is, that this restriction is in any version of Dynamo, and if you fix it, then will all other versions be left not working :-S

Revit.Elements.ElementWrapper
```
public static View3D Wrap(Autodesk.Revit.DB.View3D view, bool isRevitOwned)
{
    if (!view.IsTemplate)
    {
        if (view.IsPerspective)
            return PerspectiveView.FromExisting(view, isRevitOwned);
        else
            return AxonometricView.FromExisting(view, isRevitOwned);
    }
    return null;
}
```

![image](https://user-images.githubusercontent.com/2844374/225916649-734b1790-814f-44c4-9162-2c6e1da9433d.png)

**Comment by Amoursol** [comment]
@erfajo this work has now been done in the DynamoRevit repo which you can see here: https://github.com/DynamoDS/DynamoRevit/pull/2916
