### ISSUE TITLE
Dynamo saving/opening files as Read-only on network drives.

### ISSUE THREAD

**Issue by calitoz** [DynamoDS/Dynamo#13845]
## Dynamo version

1.2.2

## Operating system

Windows 11

## What did you do? 

Opening/Saving Scripts

## What did you expect to see?

Full access to scripts

## What did you see instead?

Read-Only scripts.

I am trying to fix this issue for one of my clients. I installed Dynamo 1.2.2 for Revit 2023 on his machine and the files are saving and opening as "Read-Only" by default. The user has Full Permission to that network folder. Any ideas?

**Comment by Amoursol** [comment]
@calitoz Dynamo version 1.2.2 is not going to work with Revit 2023 and is unfortunately unsupported behavior. From Dynamo 2.1 onwards, Dynamo is bundled inside Revit: Single version of Revit (i.e. 2023) has a single version of Dynamo. 

Can you please try using the build-in version of Dynamo in Revit 2023?
