### ISSUE TITLE
How to use wombat Wall.ByProfile for Wall Finishes

### ISSUE THREAD

**Issue by yash23197** [DynamoDS/Dynamo#13856]
Hello,
I want to use the Wall.ByProfile node provided in the wombat package for Wall Finishes. I’m new to Dynamo so I’m not able to figure this out. Earlier i was using Wall.ByFace node for wall finishes using In-Place Mass. However, Massing Method has its limitations. We need to use this for plaster quantities (in area) and since we use composite models(AR+ST+MEP), we cannot add plaster as layer in the wall family.
The Model in the left is the type of output I need. I need the the plaster ‘wall’ to automatically profile themselves to the host brick wall. unfortunately the pick line command that works on walls, does not automatically profile the wall while the Pick face command that automatically profiles the wall, does not work on walls because it needs a generic or mass model. Thanks.

## Dynamo version
2.10

## Operating system

Windows 10

## What did you do? 

I tried going the way given in the post in 2019. 
https://forum.dynamobim.com/t/wombat-package-wall-by-profile-node-problem/44125

## What did you expect to see?
I expected to see a result similar to the given in the post mentioned above.

## What did you see instead?

Weird Graphical Glitch or Revit Crash and Shutdown.
![Expectation](https://user-images.githubusercontent.com/129148054/228150995-8a1bcf50-3aa5-4e75-aafc-54d6b34d7db1.jpg)

**Comment by Amoursol** [comment]
Hello @yash23197 - Welcome to the world of Dynamo! So sorry you've been running into issues. For this particular one, the "Wombat" package is an external 3rd party package made by a customer (Woods Bagot) and as such if it's causing a crash the fix would need to be made on their side. 

Could you please try reaching out to the package authors? Try reaching "Andrea Tassera" - unfortunately I do not have his contract details but you could try LinkedIn.
