### ISSUE TITLE
Code Block Not Correct Value

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/Dynamo#13861]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.18 Sanbox

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Create a number string include character `,` inside code block : "1,34"

![image](https://user-images.githubusercontent.com/31106432/229030277-a4db9bf7-b00c-49ae-b4fc-b16758dba3cc.png)

## What did you expect to see?

it will be help return correct : "1,34"

## What did you see instead?

![image](https://user-images.githubusercontent.com/31106432/229030606-1c62556f-c4bb-4b05-873b-95cfde0a4064.png)

**Comment by chuongmep** [comment]
@Amoursol @QilongTang  can give me quick look for this ?

**Comment by QilongTang** [comment]
And would you want to get the number based on number format under current language from preferences or you would like just more robust parsing overall?

**Comment by QilongTang** [comment]
Tracked as https://jira.autodesk.com/browse/DYN-5837

**Comment by chuongmep** [comment]
@QilongTang I mean is it is result wrong with my case. I just result return is correct with version 2.18

**Comment by mjkkirschner** [comment]
I believe any changes here will require or should be made in the parser - I am very curious what mainstream languages like c# do for numeric literal support.On Apr 28, 2023, at 11:34 PM, Chuong Ho ***@***.***> wrote:﻿
@QilongTang I mean is it is result wrong with my case. I just result return is correct with version 2.18

**Comment by chuongmep** [comment]
@mjkkirschner do we have any plan for this ? The version 2.17 is good for that.

**Comment by Amoursol** [comment]
@chuongmep Dynamo 2.17 is already out (And finished back in November) so it's not in this version, nor will it be in 2.18 which was just released. We have a task in our backlog to look at this 😊

**Comment by andydandy74** [comment]
Seeing something similar happening to strings that contain integers in v2.18:
![grafik](https://github.com/DynamoDS/Dynamo/assets/3014437/c3caf458-7558-49cb-a5b3-9148abe5b856)

**Comment by iAliJ** [comment]
I have a question that might be related to this issue, why do we need to convert the obj in GetStringFromObject method defined in Watch view model to the reflecting type when we just need to return the string of that object?

https://github.com/DynamoDS/Dynamo/blob/fb033b09ba33e3472439037c29d53ce6b07fc29b/src/DynamoCoreWpf/ViewModels/Preview/WatchViewModel.cs#L247-L276
