### ISSUE TITLE
3D preview not available 

### ISSUE THREAD

**Issue by aboali19** [DynamoDS/Dynamo#13874]
i can't use "Background 3D Preview" also there aren't any icon to select as appre in the screenshot

![Screenshot 2023-04-06 000547](https://user-images.githubusercontent.com/91283119/230222647-c0293248-e193-4216-b6f8-feaf1555add4.png)

i set Revit in high graphics and updated the drives but all were useless 0️⃣
![Screenshot 2023-04-05 201427](https://user-images.githubusercontent.com/91283119/230223465-6a7d9132-96f7-4bd4-9925-c042e7d7315d.png)
![Screenshot 2023-04-05 205127](https://user-images.githubusercontent.com/91283119/230223474-f8472c8b-8670-44af-bd36-ee784846a2b4.png)
![Screenshot 2023-04-05 205315](https://user-images.githubusercontent.com/91283119/230223478-ab752a90-3c54-429d-830c-43826258ac4e.png)

about Revit version and Dynamo version
![Screenshot 2023-04-05 235739](https://user-images.githubusercontent.com/91283119/230223562-3b7ae1c6-b723-4d92-ada4-effecf7f11b4.png)
![Screenshot 2023-04-05 235827](https://user-images.githubusercontent.com/91283119/230223564-163f2e73-a76b-4c3e-bf30-30e08474105f.png)

**Comment by mjkkirschner** [comment]
There are many threads on this topic, please try installing directx 10. 
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by aboali19** [comment]
solved, Thanks @mjkkirschner
