### ISSUE TITLE
Setting option missing in Cvil 3D Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by Kushagrajagtap** [DynamoDS/Dynamo#13891]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
TRYING to find setting options in dynamo

## What did you expect to see?
In all versions it is appearing in upper ribbon along with files, edit , view etc.

## What did you see instead?
Absent " setting " option.

## What packages or external references (if any) were used?
None

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by Amoursol** [comment]
@Kushagrajagtap - We have changed the "Settings" menu now into a "Preferences Panel". Please check under the new: _Dynamo --> Preferences..._

![image](https://github.com/DynamoDS/Dynamo/assets/12857357/89a0bca1-32d6-4e35-aa7a-d13d81b4722b)

![image](https://github.com/DynamoDS/Dynamo/assets/12857357/ef4a1427-652f-4f92-8c22-ed259bfe57e1)
