### ISSUE TITLE
Docs: Customizing Dynamo's Python-3 installation out of date

### ISSUE THREAD

**Issue by GrahamKnappAcernis** [DynamoDS/Dynamo#13951]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.17

## Operating system

Windows 11

## What did you do? 

Followed instructions here to install the pip package manager
https://github.com/DynamoDS/Dynamo/wiki/Customizing-Dynamo's-Python-3-installation

## What did you expect to see?

Up to date instructions

## What did you see instead?

Out of date instructions:
 - Cpython3 is now the default engine
 - Dynamo now uses Python version `3.9.12`
 - The zip is now called `python39.zip`
 - the path file is `python39._pth`
 - I have another python on my `PATH` so I had to specifically execute the local interpreter by typing `.\python.exe .\get-pip.py` 
 - I had to do the `sys.path.append` trick at the end to make imports work

**Comment by zeusongit** [comment]
https://jira.autodesk.com/browse/DYN-5860

**Comment by Amoursol** [comment]
@zeusongit I think this is the wrong link above? 😊

**Comment by GrahamKnappAcernis** [comment]
I don't have access to Autodesk Jira so can't comment on my side - thank you both for looking at this.

**Comment by avidit** [comment]
@GrahamKnappAcernis We have tracked it internally and are planning to fix with version 2.19.

**Comment by avidit** [comment]
https://github.com/DynamoDS/Dynamo/wiki/Customizing-Dynamo's-Python-3-installation
