### ISSUE TITLE
changing package name on website

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1397]
actually not an issue...
i uploaded a custom node.
didn t take to much care and finally it was uploaded with a wrong name.
there is no way to change the name of that node ore to delete that node.
secondly it automatically adds your autodesk login email adress into the authorship.... an alias might be helpful.

**Comment by Racel** [comment]
We have several issues we are trying to address in the next generation of Dynamo related to package manager. Will address this issue then, but as this is similar to others that have been filed, closing for now.
