### ISSUE TITLE
Bug report from Dynamo 2.3.2.15696

### ISSUE THREAD

**Issue by arcsparc** [DynamoDS/Dynamo#13977]
# Issue Description
Please fill in the following information to help us reproduce the issue:
Have two lists of values, using the "<" and "<=" nodes to compare them.  Gives me two lists of booleans.  However, when I try to take "List.FirstItem" from "<", I get a warning that the operation failed.  The "<=" node works fine.

---
OS: `Microsoft Windows NT 10.0.22621.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.2.15696`
![Screenshot 2023-05-10 145557](https://github.com/DynamoDS/Dynamo/assets/72473642/9d495601-cef1-4ee4-b4b1-14df7a4c0d7b)

**Comment by mjkkirschner** [comment]
![Screenshot 2023-05-10 at 3 41 56 PM](https://github.com/DynamoDS/Dynamo/assets/508936/c0354af6-136d-4a56-bdfe-4f69f95be20a)

this is quite an old version of Dynamo and this issue no longer reproduces. Please reopen if you find you can reproduce it in a daily build.
