### ISSUE TITLE
SharpDx Error on 2.18.0

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#14019]
## Dynamo version

DynamoCoreRuntime 2.18.0 from DynamoBuilds

## Operating system
Windows 11

## What did you do? 
Opened Dynamo

## What did you expect to see?
Dynamo Working

## What did you see instead?
![image](https://github.com/DynamoDS/Dynamo/assets/15744724/8185db2f-f129-4867-8f92-a075ff783d7d)

No packages installed, unzipped with 7zip,

**Comment by mjkkirschner** [comment]
hmm - info on your machine?
operating system, GPU etc?
Should no longer be required but can you try forcing hardware accel for this particular sandbox .exe
