### ISSUE TITLE
Delete not working in library search

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#14089]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.17; not sure other impacted versions but perhaps 2.13 as a start

## Operating system

Windows

## What did you do? 

Type "ASDF" in the search, hit the left arrow to put the cursor between the D and the F, and hit delete.

## What did you expect to see?

F to be deleted.

## What did you see instead?

Nothing happens. Backspace has to be used instead.

**Comment by Amoursol** [comment]
Logged internally on Jira here: https://jira.autodesk.com/browse/DYN-5976

**Comment by johnpierson** [comment]
The delete key actually used to delete nodes that were selected in canvas, so it might be worth verifying that too.

**Comment by avidit** [comment]
fixed by #14217 in 2.19
