### ISSUE TITLE
Unable to load LibG.ProtoInterface.dll on fresh install

### ISSUE THREAD

**Issue by holmes-mike** [DynamoDS/Dynamo#14097]
## Dynamo version
2.18.1

## Operating system
Windows10

## What did you do? 
Downloaded a new version of dynamo from the link https://dynamobim.org/download/
Unblocked zip file and unpacked to local directory
Open dynamo with no errors 
Add a geometry node to the graph.
(bug only arises for geometry nodes)

## What did you expect to see?
The Point.ByCartesianCoordinates to load with error.

## What did you see instead?
![image](https://github.com/DynamoDS/Dynamo/assets/36346832/99e49d96-0133-460a-a118-94f6bc917bd5)

**Comment by avidit** [comment]
To access Geometry in Dynamo, you need to install another piece of Autodesk software e.g  Revit, Civil 3d, FormIt or Robot Structural Analysis. 
[Dynamo Sandbox without Revit - current status?](https://forum.dynamobim.com/t/dynamo-sandbox-without-revit-current-status/37589)
