### ISSUE TITLE
nodo 

### ISSUE THREAD

**Issue by fnm776** [DynamoDS/Dynamo#14108]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.13.1.3891

## Operating system

Windows 11

## What did you do? 

I just set up a new nodo.

## What did you expect to see?

A full nodo with the options avaiable, its settings and option boxes to tag/check.

## What did you see instead?

I see a square with random subsquares which does not show the correct setting (none) and empty text-boxes, in other words. itis not operative.
![DYNAMO](https://github.com/DynamoDS/Dynamo/assets/137716137/56d7ab1a-06f3-4352-97f1-fd4c827cd460)

**Comment by QilongTang** [comment]
@fnm776 Can you list all Dynamo packages installed or Revit addins? This looks like a dependency conflict to me

**Comment by fnm776** [comment]
I don't have any additional Dynamo add-ons, I only have the pre-installed plugin that comes with Revit 2023. Where can I get the additional Dynamo addons? I just want it to work. I don't seem to find the issue. (The Revit version I have is 23.0.11.19)

**Comment by fnm776** [comment]
I just fixed it, I tried diRoot manager and disabled all the plugins and addons, it seems to be working now! Thank you.
