### ISSUE TITLE
Crash report from Dynamo 2.16.1.2727

### ISSUE THREAD

**Issue by GoldenSection** [DynamoDS/Dynamo#14130]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.1.2727`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
Dynamo doesn't read the excel file and transform it to the list. Only CSV option can be used for this purpose.

## What did you expect to see?
To take the data from excel file and transform it to the list without an issue.

## What did you see instead?
Error:)
![image](https://github.com/DynamoDS/Dynamo/assets/97038257/ffb68526-f927-4ae1-a1d0-4c0ce0c2c0a6)

## Stack Trace
![image](https://github.com/DynamoDS/Dynamo/assets/97038257/4abb2054-30e5-4747-bd37-1ec076334d0a)
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
![image](https://github.com/DynamoDS/Dynamo/assets/97038257/9680c39c-ee1d-4867-ba91-91b8721f3c3d)

---
CLR: `4.0.30319.42000`

**Comment by GoldenSection** [comment]
There 's no crash so that's why I have shared the same image.

**Comment by GoldenSection** [comment]
Thanks, it works.

**Comment by QilongTang** [comment]
Thank you for reaching out @GoldenSection Dont hesitate to ask about issues so we can help! Our forum https://forum.dynamobim.com/ is also a great place for the community. Closing.
