### ISSUE TITLE
Geometry Scaling Warning in D4C3D

### ISSUE THREAD

**Issue by mzjensen** [DynamoDS/Dynamo#14143]
## Dynamo version

![image](https://github.com/DynamoDS/Dynamo/assets/24361762/5653b71d-d968-4d34-9d13-a8681b0e3e8c)

This is the current version of Dynamo that ships with Civil 3D 2024, but the issue dates back to Dynamo's initial integration in Civil 3D 2020 (Dynamo Core 2.1).

## Operating system

Windows 10

## Summary
The geometry scaling warning is a point of confusion for many users of Dynamo for Civil 3D. The warning message suggests that Dynamo's geometry scaling settings should be changed, but this produces issues with geometry integrity.

What options exist for improving the user experience?

## Background
Most civil infrastructure projects are designed using mapping projections, which means that the data resides at coordinates that are very far from the origin. For example, it is common for X and Y coordinates to exceed 1,000,000 units. This means that when Dynamo geometry is created from Civil 3D geometry, users are presented with a warning about geometry scaling settings:

![image](https://github.com/DynamoDS/Dynamo/assets/24361762/fd0cb44c-11c9-4712-b1e1-4e1187771043)

However, changing the geometry scaling setting from the default of "Medium" will often introduce geometry integrity issues for downstream nodes.

## User Journey - Dynamo
1. Open Dynamo for Civil 3D
2. Create Dynamo geometry from AutoCAD/Civil 3D
3. Notice geometry scaling warning message
4. Follow the message's guidance and proceed to change geometry scaling setting to "Large" or "Extra Large".
5. Warning messages disappear -> assume problem is fixed
6. During further graph development, encounter more geometry-related warnings (e.g., "PolyCurves may be branching")

![image](https://github.com/DynamoDS/Dynamo/assets/24361762/7541d32d-1a16-4191-ac99-2974ea9f7eb7)

8. Struggle with trying to figure out what causes these issues
9. Go to the Dynamo forum and learn that the geometry scaling settings should never be changed from "Medium"
10. Start to wonder, _Why did the warning messages tell me to change to Large or Extra Large if it causes more problems?_

## User Journey - Dynamo Player
1. Open Dynamo Player in Civil 3D
2. Run graph
3. Execution completes, Player says "Run completed with warnings"

![image](https://github.com/DynamoDS/Dynamo/assets/24361762/fb7677b0-e009-4c0a-9926-61b2ddac9e87)

5. Wonders, _What warnings? Everything looks like it ran correctly..._
6. Opens Dynamo to troubleshoot and finds that the only warnings are geometry scaling warnings
7. Wonders, _I know I'm not supposed to change the geometry scaling settings from Medium, so can I somehow hide the warning?_
8. Clicks "Dismiss all" in the warning bubble, but learns that this does not persist in Dynamo Player

![image](https://github.com/DynamoDS/Dynamo/assets/24361762/d24be327-fd5a-40d2-a040-733e99ecf734)

11. Searches for a solution on the Dynamo forum, learns that a Function.Apply node can be used to "swallow" the warnings

![image](https://github.com/DynamoDS/Dynamo/assets/24361762/b7d08461-003a-4083-b60a-896b49840eaa)

12. Tries this solution, and it works! Feels a little hacky, but it works.
13. Later learns that the Function.Apply node causes object bindings to not be respected
14. Informs other users of the graph that they should ignore anything it might say about warnings

## Relevant Forum Posts
https://forum.dynamobim.com/t/polycurves-may-be-branching-caused-by-geometry-scaling-setting/40703
https://forum.dynamobim.com/t/geometry-scaling-with-large-coordinate-values/56568
https://forum.dynamobim.com/t/object-not-brought-into-dynamo/54922
https://forum.dynamobim.com/t/converting-tinsurface-to-dynamo-geometry-doesnt-work-for-certain-surface/60837
https://forum.dynamobim.com/t/intersection-polilyne-with-alignment/89291
https://forum.dynamobim.com/t/c3d-dynamo-multi-sweep-problem/77804
https://forum.dynamobim.com/t/civil3d-polycurve-bypoints-bug/41557
https://forum.dynamobim.com/t/civil3d-pipes-and-allowable-modeling-range/56640
https://forum.dynamobim.com/t/placing-objects-perpendicular-to-corridor-feature-line-using-corridorfeatureline-coordinatesystembystation/47192
https://forum.dynamobim.com/t/pipe-geometry-or-pipe-curve-failed-could-not-create-plane-some-of-the-vertices-may-be-collinear/61205
https://forum.dynamobim.com/t/solid-byjoinedsurfaces-error-at-civil3d/50361
https://forum.dynamobim.com/t/problem-extracting-pipe-solids/77893
https://forum.dynamobim.com/t/close-featureline-bypolycurve/78709
https://forum.dynamobim.com/t/create-solid-from-closed-polyline/71489
https://forum.dynamobim.com/t/extract-geometry-of-overlapping-polylines/69766
https://forum.dynamobim.com/t/featureline-polycurve/67281
https://forum.dynamobim.com/t/autocad-solids-from-pipe-works-in-civil-3d-2021-but-not-in-2022-whats-the-difference/68771
https://forum.dynamobim.com/t/missing-points-from-autocad-polyline/56715
https://forum.dynamobim.com/t/civil3d-into-dynamo-unable-to-create-line-points-are-likely-coincident/36908
https://forum.dynamobim.com/t/corridorfeatureline-parameter-at-point-warning/50655
https://forum.dynamobim.com/t/tinsurface-triangles-error/47018
https://forum.dynamobim.com/t/display-corridor-in-dynamo/45731

**Comment by mzjensen** [comment]
@QilongTang - pinging you per our discussion.

**Comment by mjkkirschner** [comment]
@aparajit-pratap another link for your epic.

**Comment by QilongTang** [comment]
@mjkkirschner @aparajit-pratap Which epic are you referring to? Morpheus team plan to take this and introduce a setting for geometry scaling warning in particular.

**Comment by mjkkirschner** [comment]
https://jira.autodesk.com/browse/DYN-2684

**Comment by mzjensen** [comment]
Another forum post:
[https://forum.dynamobim.com/t/get-points-inside-polyline/92738](https://forum.dynamobim.com/t/get-points-inside-polyline/92738)

**Comment by QilongTang** [comment]
@mzjensen This has been resolved in Dynamo 2.19 that geometry scaling message or suggestion by Dynamo is no longer treated as warning but node info. See https://github.com/DynamoDS/Dynamo/pull/14274

**Comment by mzjensen** [comment]
Looks great, @QilongTang. Thanks for the update. I'm certain this will reduce confusion for new users.
