### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by YuvarajNagarajan** [DynamoDS/Dynamo#14150]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.22621.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- Ampersand 2022.1.25
- Bakery 2019.5.8
- BIMOneGoogleAPI 1.2.0
- bimorphNodes 4.2.4
- BlackBox 2016.8.5
- BumbleBee 2021.25.3
- Butterfly 0.1.1
- Civil3DToolkit 1.1.32
- Crumple 2022.5.27
- Data-Shapes 2022.2.105
- Dynabridge 0.1.2
- DynaMEP 2.0.1
- Dynamo for Rebar 2.0.2
- Dynamo Future File 0.0.1
- DynamoAutomation 1.31.1
- DynamoIronPython2.7 2.5.0
- DynamoMEP 1.0.3
- DynaShape 0.8.1
- DynaWorks22 2.0.0
- ExcelReader 134.1.1
- Export To NWC 0.0.3
- Genius Loci 2023.2.21
- Honeybee 0.1.9
- KS-Node 1.0.0
- Ladybug 0.2.1
- LunchBox for Dynamo 2016.11.11
- MEPDesign 1.0.1
- MEPover 2020.6.2
- MeshToolkit 3.0.0
- Modelical 2022.6.15
- Monocle 2023.2.1
- PracticalBIM 2020.0.43
- Prorubim Common Kit 0.2.1
- Prorubim Revit Kit 2.x 2022.4.0
- Quads from Rectangular Grid 2.6.0
- QuasarII 2021.25.101
- Refinery Toolkit 1.1.1
- RevitLookupWpf 2022.0.3
- Rhynamo 2018.11.26
- RIE 2021.7.1
- Sastrugi 2.0.2
- SketchUpForDynamo 1.6.5
- Slingshot! for Dynamo 2014.11.30
- Smort 0.0.2
- spring nodes 110.0.2
- SteamNodes 1.2.3
- Structural Design 2022.12.15
- Synthesize toolkit 12.7.5
- Synthetic 2.0.200209
- TestFit Dynamo 1.35.0
- WombatDynamo 1.3.2
- Zhukoven.com 2021.2.27
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by YuvarajNagarajan** [comment]
Thank you for your response. I am delighted to inform you that the issue
has been resolved successfully. Should you have any further questions or
concerns related to Dynamo in the future, I will contact you for assistance.

**Comment by QilongTang** [comment]
@YuvarajNagarajan Thanks!
