### ISSUE TITLE
Python Script node: Save & run doesn't save Python version

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#14161]
## Dynamo version

2.18.1.5096

## Operating system

Windows 11

## What did you do? 

- Placed a new Python Script node
- Edited the code
- Changed the Python version to IronPython
- Clicked on "Save & Run" button in bottom right corner
- Exited editor

## What did you expect to see?

The node to be marked as an IronPython node

## What did you see instead?

The node was still marked as a CPython node.

Note that the save button in the editor's toolbar **will** save the Python version. But I would expect the **same** from the "Save & Run" button.

**Comment by reddyashish** [comment]
This was fixed recently https://github.com/DynamoDS/Dynamo/pull/13984 (4th point) and will be part of 2.19 release.

**Comment by andydandy74** [comment]
Nice
