### ISSUE TITLE
String to Integer conversion adds decimals to integer

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#14160]
## Dynamo version

2.18.1.5096

## Operating system

Windows 11

## What did you do? 

Converted an integer to a string using various methods

## What did you expect to see?
This is how it looked in previous versions (in this case 2.16.x):
![grafik](https://github.com/DynamoDS/Dynamo/assets/3014437/5174c04a-1956-48f7-a8e0-edbf963cbc9c)

## What did you see instead?
It looks like the integer is converted to a double before being converted to a string:
![grafik](https://github.com/DynamoDS/Dynamo/assets/3014437/fc8f5f11-4a24-4f01-8c5b-a42cb87632a8)

**Comment by QilongTang** [comment]
Internally linked with https://jira.autodesk.com/browse/DYN-5965

**Comment by andydandy74** [comment]
After stumbling across #13861 I see now that this is "only" an issue with what is shown in the preview bubble:

![grafik](https://github.com/DynamoDS/Dynamo/assets/3014437/be988667-ca65-41ff-b505-d2e74e3a045a)

**Comment by avidit** [comment]
fixed by https://github.com/DynamoDS/Dynamo/pull/14369
