### ISSUE TITLE
Wish - Watch 3D with multiple inputs

### ISSUE THREAD

**Issue by HansNewbie** [DynamoDS/Dynamo#1416]
It would be nice to have Watch 3D with multiple inputs so that we could watch many selected results at the same time without background preview and without turning on and off of `Preview` by nodes. The output could still be one which will be the inputs put as a list.

**Comment by Racel** [comment]
You can create multiple watch 3d nodes to watch multiple streams simultaneously. We also have been working on a project called fractal which would allow you to look at multiple results simultaneously. We, however, do not have plans to work on this in the current WPF UI, so closing this for now. We will address in our next generation UI in a different way.
