### ISSUE TITLE
Code block outports corrupt

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14240]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18.1 (Revit 2024)

## Operating system

Windows 11

## What did you do? 

Trying to modify the wires to the outport of a code block. The code block was previously in a group. Copy and paste creates the correct code block but I can copy the wires across from the corrupted one.

## What did you expect to see?

An outport that can be used to create a wire.

## What did you see instead?

No outport. 

![Code blocks](https://github.com/DynamoDS/Dynamo/assets/10913639/7ec98d4c-37f3-4c32-bbb8-0611e9b7ea37)

**Comment by Amoursol** [comment]
FYI @QilongTang

**Comment by avidit** [comment]
tracked internally [DYN-6165](https://jira.autodesk.com/browse/DYN-6165)

**Comment by avidit** [comment]
@ParametricMonkey I wasn't able to reproduce this one. Could you provide more details?

**Comment by ParametricMonkey** [comment]
Not really sure what else I can add.

**Comment by avidit** [comment]
Does it happen consistently? If so, could you please save a gif?
