### ISSUE TITLE
Adding dash to note crashes dynamo

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14256]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18

## Revit version

2024

## Operating system

Windows 11

## What did you do? 

Added a dash to an existing note with dashes

## What did you expect to see?

New dash/bullet added

## What did you see instead?

Dynamo crashed. Report ID 714240100. Dynamo file also attached.

I believe the issue is to do with bullets. Adding a dash creates a bullet but sometimes, not always, it will crash Dynamo on existing nodes with dashes.

[Notes bug.zip](https://github.com/DynamoDS/DynamoRevit/files/12307443/Notes.bug.zip)

**Comment by Amoursol** [comment]
FYI @avidit - Looks like we need guarding from existing formatting.

**Comment by avidit** [comment]
Tracked internally [DYN-6151](https://jira.autodesk.com/browse/DYN-6151)

@ParametricMonkey It didn't crash for me, however there were some formatting issues. What is your system language and region? and Do you have any packages installed?

**Comment by ParametricMonkey** [comment]
@avidit what were the formatting issues? The language is nothing exotic, just English (Australia).

I tried removing all existing dashes first, then adding a new dash (bullet) but it still crashes. 

I'm running it in Dynamo 2.18.1 for Revit 2024. Packages include Lunchbox, Rhythm, Clockwork, Archilab and Geniusloci but these should affect it. There are no view extensions installed.

**Comment by mjkkirschner** [comment]
@ParametricMonkey can you provide the package versions? Rhythm includes a view extension, some of the others may as well.

**Comment by ParametricMonkey** [comment]
<img width="502" alt="image" src="https://github.com/DynamoDS/Dynamo/assets/10913639/6624e2f9-a72c-48a4-bd41-971f0128d67c">

<img width="492" alt="image" src="https://github.com/DynamoDS/Dynamo/assets/10913639/7349df87-2214-4917-8dbd-56d19bf2e2cd">

**Comment by mjkkirschner** [comment]
@avidit please try to repro again with the above packages installed.

**Comment by QilongTang** [comment]
We are working on this https://github.com/DynamoDS/Dynamo/pull/14337

**Comment by QilongTang** [comment]
This should be fixed in 2.19 release and 3.0 release. Closing for now. Thank you for reporting these issues and feel free to re-open if that ever happens again in newer versions of Dynamo.

**Comment by avidit** [comment]
fixed by https://github.com/DynamoDS/Dynamo/pull/14996
