### ISSUE TITLE
Filter sample needed - Improvement

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#143]
Would be cool to have a sample for filters use, can't manage to get it work (language issue maybe :).

**Comment by ksobon** [comment]
damn this is old....anyways if anyone stumbles upon this, this example should do:

![image](https://cloud.githubusercontent.com/assets/529781/10414041/fb3a1cd2-6f8e-11e5-9a43-1f9c12f83446.png)

@kronz @Steell Can we close this?

**Comment by sharadkjaiswal** [comment]
We already have List.Filter node to accomplish the filter functionality, I think we can close this issue. Please feel free to leave your comments and feedback if any.
