### ISSUE TITLE
Nodes showing behind group background despite being grouped

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14328]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18.1

## Revit version

2024.1.0

## Operating system

Windows 11

## What did you do? 

Gouped node

## What did you expect to see?

Node visible on top of group

## What did you see instead?

Node occasionally appears behind the group background despite being grouped. Seems to occur when a node is selected and you pan the UI.

![image](https://github.com/DynamoDS/DynamoRevit/assets/10913639/f4f232fd-13a6-4536-80d5-c564840580bc)

**Comment by avidit** [comment]
tracked internally [DYN-6179](https://jira.autodesk.com/browse/DYN-6179)
