### ISSUE TITLE
Wire colours display orange despite no errors 

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14326]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18.1

## Revit version

2024.1.0

## Operating system

Windows 11

## What did you do? 

Ran the graph in Automatic node

## What did you expect to see?

No errors, and node wire colours black.

## What did you see instead?

Wires show as orange despite having no error and the graph is in automatic mode and so nodes are not being recomputed (i.e. dirty data). 

https://github.com/DynamoDS/DynamoRevit/assets/10913639/f319d13b-4403-46a4-bf56-5b14a768c8d9

**Comment by QilongTang** [comment]
@ParametricMonkey From my understanding, there should be no orange overlay for connectors displayed for graph at automatic run mode. Are you using a particular package to achieve that?
