### ISSUE TITLE
Alternate UI of nodes not updating when unfrozen

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14329]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18.1

## Revit version

2024.1.0

## Operating system

Windows 11

## What did you do? 

Unfreeze a node

## What did you expect to see?

Nodes downstream to show normally (in the zommed-out UI)

## What did you see instead?

Nodes continue to show frozen graphic, even though they are not frozen and data is flowing through.

**Comment by avidit** [comment]
duplicate #13765
