### ISSUE TITLE
Dynamo crashes switching from Auto to manual mode

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#14330]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18.1

## Revit version

2024

## Operating system

Windows 11

## What did you do? 

Switch run mode from automatic to manual

## What did you expect to see?

Script stops running

## What did you see instead?

Dynamo times out - white screen, nothing happening. I suspect the issue might be tied to Dynamo trying to undo/clear the element bindings of elemenets already created.

**Comment by avidit** [comment]
tracked internally [DYN-6180](https://jira.autodesk.com/browse/DYN-6180)
