### ISSUE TITLE
Duplicate item in Library

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#14333]
## Dynamo version
Dynamo 3.0.0.6017

## Operating system
Windows 11

## What did you do? 

Library > Script > Editor

## What did you expect to see?

One instance of Code Block

## What did you see instead?

Duplicate Code Block
![Screenshot 2023-08-27 150847](https://github.com/DynamoDS/Dynamo/assets/5621624/907a7ee4-6be3-4152-989e-0dcabc26a0fa)

**Comment by QilongTang** [comment]
I can reproduce this locally. Nice catch. We should track it internally. FYI: @avidit

**Comment by avidit** [comment]
tracked internally[DYN-6189](https://jira.autodesk.com/browse/DYN-6189)

**Comment by avidit** [comment]
fixed in dynamo 3.0
