### ISSUE TITLE
could not load file or assembly 

### ISSUE THREAD

**Issue by CooperLiumz** [DynamoDS/Dynamo#14362]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

v.2.18.1 

## Operating system

Windows 10 

## What did you do? 

Create Circle.ByCenterPointRadius

## What did you expect to see?

(Fill in here)

## What did you see instead?

![image](https://github.com/DynamoDS/Dynamo/assets/67528045/43afa492-c691-42b8-a0b1-54ef7f37a916)

**Comment by avidit** [comment]
Dynamo doesn't come with geometry. 

To access Geometry in Dynamo, you need to install another piece of Autodesk software e.g Revit, Civil 3d, FormIt or Robot Structural Analysis.

To utilize geometry, Dynamo can be started with *GeometryPath* flag. e.g. *DynamoSandbox.exe -GeometryPath C:\Program Files\Autodesk\Revit 2024*
