### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by a2d1s** [DynamoDS/Dynamo#14375]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
Tried to edit custom definition that containted arch-lab package.

## What did you expect to see?
(Fill in here)

## What did you see instead?
Warning messages about python version mismatch and crash

### Loaded Packages
- archi-lab.net 2023.213.1722
- Bang! 2021.4.3
- bimorphNodes 4.2.1
- Clockwork for Dynamo 2.x 2.4.0
- Data-Shapes 2022.2.105
- Dyn-BIMHEX 2020.2.6
- Monocle 2022.10.2
- Morpheus 2019.8.26
- ParametricMonkey 1.3.6
- Rhythm 2023.8.2
- SketchUpForDynamo 1.6.5
- spring nodes 210.1.1
- GenerativeDesign 1.10.10.0
- GenerativeDesign.Extension 1.10.10.0
- GenerativeDesign.Revit 1.10.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
tracked internally [DYN-6216]
(https://jira.autodesk.com/browse/DYN-6216)

**Comment by avidit** [comment]
@a2d1s I wasn't able to reproduce the crash. Do you have a screenshot or a gif?
