### ISSUE TITLE
Error when launching Dynamo Sandbox

### ISSUE THREAD

**Issue by borito788** [DynamoDS/Dynamo#14389]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Sandbox 2.18.1.5096

## Operating system

Windows 10 22H2

## What did you do? 

Launched Dynamo Sandbox

## What did you expect to see?

For it to launch and get to the Welcome screen

## What did you see instead?

Two error messages - the first message then clicked OK, then got the second message, then click OK, and then saw the Welcome screen

[image](https://github.com/DynamoDS/Dynamo/assets/144351420/5b60dc64-00ec-4585-a6b3-9a0218e75477)

These are the apps I have installed:

Dynamo Sandbox 2.18.1
Autodesk 2024 applications (Revit, 3ds Max, AutoCAD, CFD, Civil3D, FormIt Pro, Fusion 360, Inventor Pro, Maya, MotionBuilder, Mudbox, Netfabb Premium, ReCap Pro, PowerMill, PowerShape)
Many other applications (I can list these if necessary)

**Comment by avidit** [comment]
tracked internally [DYN-6227](https://jira.autodesk.com/browse/DYN-6227)

**Comment by mjkkirschner** [comment]
Hi @borito788 inside your 3dsmax folder, can you please check the version of mmsdk.dll and report it here?

**Comment by borito788** [comment]
C:\Program Files\Autodesk\3ds Max 2024\mmsdk.dll
Version 4.3.0.3540

**Comment by borito788** [comment]
Hi there, is there any update to this?

**Comment by mjkkirschner** [comment]
we found that an incorrect version of mmsdk.dll was shipped with 3dsmax, I believe that team should update to a compatible version, on our side we should not load incompatible versions, work is in the backlog but I believe it is currently scheduled pretty far out.

As a workaround please use the `-GeometryPath` command line flag when starting sandbox to point it towards a known good geometry library install path, like a compatible version of revit etc:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Command-Line-Interface

**Comment by borito788** [comment]
Thank you

**Comment by borito788** [comment]
.
