### ISSUE TITLE
help:I want to calculate the length of the sun visor

### ISSUE THREAD

**Issue by mingzhao240** [DynamoDS/Dynamo#1438]
I want to calculate the length of the sun visor 
I found a video from youtube, but could not find the content they seek help files
![8em_i 4lo492 0pj 28of 6](https://cloud.githubusercontent.com/assets/4797778/2599148/5b868e16-bad9-11e3-8730-f97cb48b9b6f.jpg)

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
