### ISSUE TITLE
Possible bug related with trim and surfaces (0.7.0)

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#1444]
It seems that the result of trimming a surface is always resulting a list, even when all the arguments are individual objects (one surface, one tool, one point). 

Maybe this is related to this: when trimming one surface against a list of tools, the result is always (independent of the lacing) a list of surfaces. It seems not possible to achieve the result of making all the trim operations on the same surface.

**Comment by johnpierson** [comment]
Going ahead and closing this as it is for a very old version of Dynamo. If this kind of problem still persists for you in 2.0.x releases, please feel free to open a new issue with updated information.
