### ISSUE TITLE
Crash report from Dynamo 2.16.1.2727

### ISSUE THREAD

**Issue by Robert7854** [DynamoDS/Dynamo#14463]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.1.2727`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I was trying to run designscript 
//
num_pts = 6;

pts = Point.ByCoordinates(1..30..#num_pts,
    Math.Sin(0..360..#num_pts) * 4, 0);

def create_curve(pts : Point[], degree : int) 
{
    return = NurbsCurve.ByControlPoints(pts,
        degree);
}

ctrl_crvs = create_curve(pts, 1..11);
//

## What did you see instead?
![image](https://github.com/DynamoDS/Dynamo/assets/146344042/92dfc1be-7212-4b0e-80d9-047ef83f9bf9)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@Robert7854 It it happening consistently? I was able to run your code without issue.
![Screenshot 2023-10-04 at 11 07 57 AM](https://github.com/DynamoDS/Dynamo/assets/1406153/29f4e049-f32e-408d-bff5-8fcdb0bce104)
