### ISSUE TITLE
why does speckle do not work on the recent version of Dynamo (Crash report from Dynamo 2.18.1.5096)

### ISSUE THREAD

**Issue by ShanmugaPriya4413** [DynamoDS/Dynamo#14467]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.18.1.5096`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@ShanmugaPriya4413 Which version of Speckle are you using? Could you provide more details?
