### ISSUE TITLE
Creating event handlers not working in Dynamo 2.19.3

### ISSUE THREAD

**Issue by nverhaegen-hfb** [DynamoDS/Dynamo#14612]
### Dynamo Version

Dynamo Core 2.19.3.6394
Dynamo for Revit 2.19.3.10292
(Revit 2024.2)

### Operating System

Windows 11

### What did you do?

Trying to create an event inside a Python node:

```python
from System import EventHandler, EventArgs

def my_handler(obj, e):
    pass

handler = EventHandler[EventArgs](my_handler)
```

### What did you expect to see?

No errors, this worked in Dynamo 2.16 in Revit 2023.1 but not in the 2.19 build shipped with Revit 2024.2.

### What did you see instead?

The following error:

PythonEvaluator.Evaluate operation failed. Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.

### Details

The same error occurs when trying to add the handler to events with the += operation.

**Comment by avidit** [comment]
tracked internally [DYN-6439](https://jira.autodesk.com/browse/DYN-6439)

**Comment by Cyril-Pop** [comment]
Hi,
for information, the same error occurs when constructing a predicate

![image](https://github.com/DynamoDS/Dynamo/assets/53660624/04d6730c-4658-4fb1-9861-375f5ace7692)

**Comment by Mudo32** [comment]
How come eventhandler works in 
Dynamo Core 2.18.1.5096
Dynamo for Revit 2.18.1.8943
(Revit 2024.1)

But not for the new version? 
Any news about this issue.?

**Comment by avidit** [comment]
fixed by https://github.com/DynamoDS/Dynamo/pull/15306
