### ISSUE TITLE
File From Path Node issue from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by joseph-kirkpatrick** [DynamoDS/Dynamo#14647]
# Issue Description
File from path node as a "input node" isn't showing up correctly

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I'm exporting items to a selected excel file. 

## What did you expect to see?
As a user input to select a file path for an excel file

## What did you see instead?
nothing

## What packages or external references (if any) were used?
"File From Path" is ootb

---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment]
hi @joseph-kirkpatrick Appreciate the report, do you happen to have a screenshot of what happened to you?

**Comment by joseph-kirkpatrick** [comment]
Unfortunately I don't, I can get one tomorrow. But essentially the location
in the dynamo player where there should be user input options, don't exist.
The nodes inside dynamo still show them as an input as well.

**Comment by QilongTang** [comment]
Thank you @joseph-kirkpatrick Please attach a screenshot when you can and also let us know if the node behaves correctly in Dynamo only so we can digest which part of the system is wrong. Really appreciate it.

**Comment by joseph-kirkpatrick** [comment]
1. How typical Dyn Player shows
![image](https://github.com/DynamoDS/Dynamo/assets/32959656/646c8c2a-2112-4dee-9993-12a84f2bf8d5)
2. Dyn Player showing there are no inputs for the user (the missing dependencies are b/c I have a different version of a package but the Data ExportToExcel is an Ootb node.
![image](https://github.com/DynamoDS/Dynamo/assets/32959656/865a3f5d-4dba-4365-acfd-c9f428454910)
3. Node showing that it's still as an input
![image](https://github.com/DynamoDS/Dynamo/assets/32959656/053ac5ef-aad6-4ee6-a668-4d90f7edfde7)
4. Running inside of dynamo the node does still work
![image](https://github.com/DynamoDS/Dynamo/assets/32959656/d82ad98b-ea1e-4a6c-a6f8-7b9cecf28646)

Thanks for the quick replies, let me know if there's anything else you need.
-KP

**Comment by twastvedt** [comment]
We think we have identified this bug. As a potential workaround, and to verify it's what I think it is, could you try adding a watch node to the graph and setting it as an output?

**Comment by joseph-kirkpatrick** [comment]
It looks like adding a watch node to the very end actually fixes it.
[image: image.png]
dyn player works correctly now as well.
[image: image.png]

**Comment by twastvedt** [comment]
Great, thanks for confirming!
tracked internally: [AGD-3153](https://jira.autodesk.com/browse/AGD-3153)

**Comment by twastvedt** [comment]
@joseph-kirkpatrick Absolutely, send away: trygve.wastvedt@autodesk.com. Thanks for your help in tracking down this issue!

**Comment by twastvedt** [comment]
Huh. I'm having some trouble getting that input node to load at all. Might be my local setup, I'll try in a cleaner environment. But I'm wondering if this is something to do with the Rhythm package or that node in particular.

**Comment by joseph-kirkpatrick** [comment]
That node is not in the newer versions of Rhythm, it could be a cross
between package support and the input error we're seeing.

**Comment by 17CrewRam** [comment]
Same issue here.  Setting the "file path" node as input, fails to show in player.  Adding the watch node inline after, seemed to fix it.

**Comment by joseph-kirkpatrick** [comment]
I thought it would fix it but ultimately it didn't.

**Comment by twastvedt** [comment]
@joseph-kirkpatrick Hooray! Can you clarify what you mean by "requires the user input"? Just want to understand the nuance for anyone else having this problem. Thanks!

**Comment by joseph-kirkpatrick** [comment]
I have a node that lists a drop down for scope boxes for the user to select, after adding the watch node immediately after that but not interrupting the node line, and setting it to output, it immediately shows up in the dynamo player. 
Same thing with the File From path node.
![image](https://github.com/DynamoDS/Dynamo/assets/32959656/9a9fd66c-34b1-419c-8d11-4ac138666964)
![image](https://github.com/DynamoDS/Dynamo/assets/32959656/ded92054-7e05-47d7-90f3-34b1ac8cbf5b)

**Comment by twastvedt** [comment]
Ah, I see. Sorry I didn't notice this sooner, but I _think_ just the Is Output toggle is necessary - the watch node can be anywhere.
