### ISSUE TITLE
EXPORT TO EXCEL ERROR 

### ISSUE THREAD

**Issue by chs14gh** [DynamoDS/Dynamo#14667]
THERE IS ALWAYS WARNING FOR EXCEL EXPORT I DONT KNOW WHY 
I CHANGED MY VERSION FROM 2016 TO 2023 LATEST THROUGHT MY UNI EMAIL BUT EVEN THOUGH IT DOESNT WORK '
PLEASE LET ME KNOW IF ANY LEAD

# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.2.5624`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by chs14gh** [comment]
I WANT TO EXPORT TO EXCEL SHEET MY PARAMETERS I USED ALL THE NODES THAT ARE
NEEDED
THE SAME NODE CODE WORKS FOR MY FRIEND BUT NOT ME
I EXPECTED TO SEE A EXCEL SHEET OUTPUT
I SEE WARNING IN EXPORTED WITH WARNING

I TRIED CHANGING MY EXCEL WERSION FROM 2016 TO THE LATEST VERSION

**Comment by avidit** [comment]
Hi @chs14gh Could you please provide the content of the error message and also the dyn file if possible?

**Comment by chs14gh** [comment]
I cleared it by troubleshooting excel software thanks

**Comment by QilongTang** [comment]
@chs14gh Thank you for letting us know!
