### ISSUE TITLE
Cpython string/decimals

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#14679]
### Dynamo Version

2.18.1

### Host

Revit

### Operating System

Win 10

### What did you do?

Strings gets decimal numbers:
![image](https://github.com/DynamoDS/Dynamo/assets/7080648/571c2b31-c0b3-4342-9b60-6bec070b188c)

### What did you expect to see?

not decimals being added.

### What did you see instead?

see above

### What packages or external references (if any) were used?

none

**Comment by mjkkirschner** [comment]
yes, preview issue, fixed here:
https://github.com/DynamoDS/Dynamo/pull/14377
