### ISSUE TITLE
Mesh.ImportFile from MeshToolkit doesn't work with Revit2024.

### ISSUE THREAD

**Issue by federicopana** [DynamoDS/Dynamo#14700]
### Dynamo Version

2.19.3.6394

### Host

Revit 2024.2

### Operating System

Windows 11

### What did you do?

I tried with different format (obj, stl) and with your example (bunny)

### What did you expect to see?

Everything works in Revit 2023 and Dynamo 2.16.

### What packages or external references (if any) were used?

MeshToolkit Version: 3.0.0

### Details

![Screenshot 2023-12-06 145019](https://github.com/DynamoDS/Dynamo/assets/124672108/f0e6e348-b55b-4e36-b53e-aee790ef8f9e)

**Comment by mjkkirschner** [comment]
FYI @aparajit-pratap

**Comment by avidit** [comment]
tracked internally [DYN-6532](https://jira.autodesk.com/browse/DYN-6532)

**Comment by aparajit-pratap** [comment]
I think this has got to do with the conflict between ASM and AMT. @federicopana can you tell us which version is being used in your Revit 2024 installation? If you go to C:\Program Files\Autodesk\Revit 2024, do you see ASMxxx229A.dll or 228?

I've tested the ImportFile node and don't see any issue.

**Comment by mjkkirschner** [comment]
@aparajit-pratap don't we just need to publish the 2024 version of mesh toolkit?

**Comment by federicopana** [comment]
hi @aparajit-pratap, I tried with Revit 2024 and than with the last update 2024.2. I see all 229A.dll file.

**Comment by aparajit-pratap** [comment]
> @aparajit-pratap don't we need to publish the 2024 version of mesh toolkit?

@mjkkirschner I had no idea. I can publish the version of MTK as it currently exists before the net8 upgrade.

**Comment by mjkkirschner** [comment]
@aparajit-pratap you may want to merge @saintentropy 's PR first though I think it unfortunately contains relevant and irrelevant (new API) changes.

**Comment by aparajit-pratap** [comment]
> @aparajit-pratap you may want to merge @saintentropy 's PR first though I think it unfortunately contains relevant and irrelevant (new API) changes.

Yes, the main part I borrowed from it is the loading of netfabbcore.

**Comment by aparajit-pratap** [comment]
> hi @aparajit-pratap, I tried with Revit 2024 and than with the last update 2024.2. I see all 229A.dll file.

@federicopana that explains it, we unfortunately don't have a version of MTK that supports this version of ASM and Revit 2024. Will be publishing one shortly.

**Comment by mjkkirschner** [comment]
should be resolved now.
