### ISSUE TITLE
Definition-Specific Custom Nodes

### ISSUE THREAD

**Issue by s-overall** [DynamoDS/Dynamo#148]
We just recently discovered the recursive abilities of custom nodes in dynamo at our office recently (example here: http://autodeskvasari.com/forum/topics/recursive-for-loop-using-dynamo-nodes?commentId=6375667%3AComment%3A53383&xg_source=msg_com_forum ), and we would like to see a way to create a custom node contained within the definition that won't show in the node library, similar to Clusters in grasshopper.  Creating a custom node to perform a specific operation within a definition currently clutters up the node library in all other definition files, which can be a problem over time.

It could also be used as an organizational tool to de-clutter and block off major definition elements.

**Comment by sharadkjaiswal** [comment]
If the workspace element of the custom node file has an attribute `IsVisibleInDynamoLibrary="false"` then the custom node is not visible in library UI. So you can edit your DYF file in text editor to add this attribute to hide your custom node from library UI.
`<Workspace Category="Migration" Name="XyzGrid" IsVisibleInDynamoLibrary="false" ID="9215492a-4cb9-4ec1-a111-c18d7f6fd5b3">`
