### ISSUE TITLE
Rapport d'erreur de Dynamo 2.19.4.6671

### ISSUE THREAD

**Issue by MaxCarrierIng** [DynamoDS/Dynamo#14824]
# Issue Description
Please fill in the following information to help us reproduce the issue:

Using the newest version of Dynamo (as part of the Civil 3D 2024.3 update), the nodes set as Input and Output won't appear anymore in the Dynamo Player, and were working fine in previous versions. 
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/8645d79a-8b41-4a26-85b8-3816d1ebaa23)

FYI, I'm using Civil 3D 2024.3 in French, and the recent update on Dynamo seems to overhaul the Language preference, using your Civil 3D's language. Prior to Civil 3D 2024.3 update (so 2024.2 and prior), my Dynamo was in English by default. Whatever I'm inputting as a language preference will now change the shown language.
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/d52b6a0f-a6d4-4823-9c0e-059bc8ed50e5)

What I'm implying is: maybe there's a language issue that this imposed translation causes.
What was once called "As Input" when you were right clicking a node is now called "Est une entrée"? Maybe that's the root of the problem, maybe not.
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/73200fe5-b86f-482c-91bd-324f7de7c142)

Maybe that's the root of the problem, maybe not.

Will need to reinstall the software in english to see if the bug persist, but something has definitely changed with the Civil 3D 2024.3 update rendering my scripts useless.

Thanks in advance!

## Dynamo version
Dynamo: `2.19.4.6671`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
Worked with a script functioning back with Civil 3D 2024.2. The update for 2024.3, using now Dynamo 2.19, doesn't show scripts Inputs and Outputs in the Dynamo Player interface.

## What did you expect to see?
Inputs and Outputs shown in the Dynamo Player interface set in the script (mainly selected objects and numbers).

## What did you see instead?
A mention of "Missing Inputs" and an empty page in the Dynamo Player.
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/fa5b0ed1-c83b-4ae1-9325-3ae9785e93d5)

## What packages or external references (if any) were used?
Civil3DToolkit
Camber
Clockwork for Dynamo

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
FYI @jnealb @twastvedt

**Comment by MaxCarrierIng** [comment]
In the meantime, rolling back to Civil 3D 2024.2 (in French) with the previous version of Dynamo as temporarily "solved" my situation, showing back the inputs in the Dynamo Player. I can still work for now, but would love to see this issue resolved to not be locked out of the current AND futur versions of Dynamo for Civil 3D.
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/11119ff8-0c5f-43d2-b554-90be4eed912c)

**Comment by mjkkirschner** [comment]
@twastvedt @BogdanZavu - I seem to remember another issue report for this, but can't recall what to search for - can you give more info?

**Comment by twastvedt** [comment]
@MaxCarrierIng Can you try adding a Watch node output to the graph? Doesn't need to hook up to anything, just needs to be there (if this is the bug I think it is).

**Comment by MaxCarrierIng** [comment]
> @MaxCarrierIng Can you try adding a Watch node output to the graph? Doesn't need to hook up to anything, just needs to be there (if this is the bug I think it is).

I think you got it, adding a Watch node as Output made everything reappeared in the Dynamo player!
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/a2cbb86a-247d-4927-b07d-a7c10c7a4ff2)

**Comment by MaxCarrierIng** [comment]
@twastvedt Looks like as long as you have an Output (Watch node or else), the Inputs will be shown. I'll force an output from now on!
![image](https://github.com/DynamoDS/Dynamo/assets/156234234/4321221f-335a-44dc-8d3b-f261cd9cd69f)

**Comment by twastvedt** [comment]
Yes! Note that this will only be necessary if the script doesn't have either a slider or boolean toggle input. Sorry you're running into this. We'll be looking at a fix for a future update!
