### ISSUE TITLE
Can't manage packages

### ISSUE THREAD

**Issue by isabellgustafsson** [DynamoDS/Dynamo#14823]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 2.12.0.5650

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Trying to uninstall a package by clicking on the Packages tab)

## What did you expect to see?

(An option that says Manage Packages)

## What did you see instead?

(No option, only the options to Search for a Package or Publish New Package)
![Manage Package missing](https://github.com/DynamoDS/Dynamo/assets/156207140/4564373f-ae0d-48b7-8ead-0656e1593a0b)
![Manage Package missing](https://github.com/DynamoDS/Dynamo/assets/156207140/9694cea2-2e4b-4311-a38c-dc9365b8ed22)
Package and Publish New Package)

**Comment by mjkkirschner** [comment]
Hi @isabellgustafsson the UI has changed in a previous Dynamo version, try the preferences menu, some package management has moved there.
