### ISSUE TITLE
Not able to see Nodes but can see wires in Dynamo for Revit 2021 and Revit 2022 version.

### ISSUE THREAD

**Issue by manojjadhav15** [DynamoDS/Dynamo#14863]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Revit 2021 and Revit 2022

## Operating system

Windows 10

## What did you do? 

I installed Revit 2021 and Revit 2022. I already have some other custom Revit plug-ins installed. 

## What did you expect to see?

I wanted to see nodes along with wires.

## What did you see instead?

When I opened Dynamo and opened already created script, I was not able to see nodes but I could see wires

**Comment by mjkkirschner** [comment]
sounds like an addin conflict,  reopen with more info.
