### ISSUE TITLE
Crash report from Dynamo 2.16.2.5624

### ISSUE THREAD

**Issue by McFlytelli** [DynamoDS/Dynamo#14886]
# Issue Description
"PerimeterCurves" doesn't work sometimes.
It doesn't work even if the surface is created directly in Dynamo

## Dynamo version
Dynamo: `2.16.2.5624`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I create a surface directly in Dynamo, a rectangular for example and when I ask to Dynamo to create a perimeter's curves it generate, sometimes, not all sides.

## What did you expect to see?
the complete perimeter. All curves. In this case, 4 sides.

## What did you see instead?
Only one or two or three sides. It's random

## What packages or external references (if any) were used?
No package. Only standard nodes

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@McFlytelli could you provide a sample graph or screen recording of the issue?
