### ISSUE TITLE
Dynamo wont start from Revit

### ISSUE THREAD

**Issue by Liquidmasl** [DynamoDS/Dynamo#14891]
### Dynamo Version

I cant open dynamo. but the one that currently ships with revit

### Revit Version

2024.1

### Operating System

Windows 11

### What did you do?

after I installed an addon (!) I tried opening dynamo from revit.
After deinstalling the addon, revit, and everything else mentioning autodesk and reinstalling (without the addon), its still broken

### What did you expect to see?

Dynamo

### What did you see instead?

![image](https://github.com/DynamoDS/DynamoRevit/assets/10048306/507cf04d-35e4-4aa7-8630-3e1d0b2facbf)

OCR: 
https://pastebin.com/GY3VJm2R

### Stacktrace/logs

error message OCR (cant copy from error window): https://pastebin.com/GY3VJm2R

Revit Journal: https://pastebin.com/Zfyc210y

**Comment by QilongTang** [comment]
> @pinzart90 this still seems like an issue we need to fix on the Dynamo side, a bad version of a python evaluator should not stop Dynamo from starting - so I'll leave this open and transfer to dynamo core repo for now.

Thank you @mjkkirschner

**Comment by Liquidmasl** [comment]
> @Liquidmasl - use the previous version which was built for net standard and should work in older builds of Revit. The most recent version 1.2 - will only work with .net 6+.

thank you all for the super quick reaction! always a joy to see!

and sorry for the possibly stupid question, do you mean the previous version of revit?
or can i just get .net +6?

I am a bit confused what exactly broke it for me, as it was working before. I guess the addon installed some other .net version?

Thanks again!

**Comment by KhaledHijazi** [comment]
Hello,
The issue is with some packages you installed, in my case it was (DynamoIronPython)

Go to: 
C:\Users\user\AppData\Roaming\Dynamo\Dynamo Revit\2.19\packages

Remove or move (DynamoIronPython) then try to run dynamo, if it doesn't open, remove the packages one by one until dynamo opens so you can know which package is creating the problem, then you can move back the other packages

Hope this helps

**Comment by avidit** [comment]
tracked internally [DYN-6672](https://jira.autodesk.com/browse/DYN-6672)

**Comment by Liquidmasl** [comment]
> @Liquidmasl Hello, The issue is with some packages you installed, in my case it was (DynamoIronPython)
> 
> Go to: C:\Users\user\AppData\Roaming\Dynamo\Dynamo Revit\2.19\packages
> 
> Remove or move (DynamoIronPython) then try to run dynamo, if it doesn't open, remove the packages one by one until dynamo opens so you can know which package is creating the problem, then you can move back the other packages
> 
> Hope this helps

wonderful thank you!
it works again.

Would be awesome if dynamo would just tell me that some package makes issues in a more newby human friendly version haha

Thanks for all your quick help!

**Comment by mjkkirschner** [comment]
reopening because the underlying issue still needs to be investigated to avoid the crash.
