### ISSUE TITLE
Excel Interop - Invalid Input type to make AST Node

### ISSUE THREAD

**Issue by miguelmaso** [DynamoDS/Dynamo#14919]
### Dynamo Version

2.17

### Operating System

Windows 10

### What did you do?

I'm trying to create an Excel Workbook with a Zero Touch Node.
```c#
            Microsoft.Office.Interop.Excel.Application excel_app = new Microsoft.Office.Interop.Excel.Application();
            Microsoft.Office.Interop.Excel.Workbook workbook = excel_app.Workbooks.Add(); // This line is creating the issue
            Marshal.ReleaseComObject(workbook);
            Marshal.ReleaseComObject(excel_app);
```

### What did you expect to see?

Load the library as usual.

### What did you see instead?

The library could not be loaded.

### What packages or external references (if any) were used?

```c#
Microsoft.Office.Interop.Excel
System.Runtime.InteropServices
```

### Stack Trace

![image](https://github.com/DynamoDS/Dynamo/assets/25640870/6eef0f50-d26c-449b-8700-544a58985bf3)

**Comment by avidit** [comment]
tracked internally [DYN-6675](https://jira.autodesk.com/browse/DYN-6675)

**Comment by mjkkirschner** [comment]
I'm guessing COM interop types are being embedded? Please first see these resources and then share a GitHub repo that reproduces the issue if the resources don't help.

https://github.com/DynamoDS/Dynamo/wiki/Using-COM-(interop)-types-in-dynamo-packages
https://forum.dynamobim.com/t/fail-to-load-two-packages-access-to-the-same-api/83556/6
