### ISSUE TITLE
String is threated as numbers 2.18.1.5096

### ISSUE THREAD

**Issue by terjetor** [DynamoDS/Dynamo#14924]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.18.1.5096`

## Operating system
OS: `Microsoft Windows NT 10.0.22621.0`

## What did you do?
I want list which looks like this:
![image](https://github.com/DynamoDS/Dynamo/assets/159159416/824ccf4d-cbec-406d-9e09-b083536070b1)

## What did you expect to see?
![image](https://github.com/DynamoDS/Dynamo/assets/159159416/a5d1ff18-0ca3-41fc-9b41-568fa88458ad)

## What did you see instead?
![image](https://github.com/DynamoDS/Dynamo/assets/159159416/2a26f5c9-0685-48b4-a337-b415a75b0297)

## What packages or external references (if any) were used?
None

## Stack Trace
```
Dynamo didnt crash

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
tracked internally [DYN-6688](https://jira.autodesk.com/browse/DYN-6688)

**Comment by mjkkirschner** [comment]
This should already be resolved 
https://github.com/DynamoDS/Dynamo/pull/14377

**Comment by terjetor** [comment]
Thanks
