### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by AzToastyTexan** [DynamoDS/Dynamo#14953]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
Upgrading Revit files from Revit 2021 to Revit 2022

## What did you expect to see?
I expected it to upgrade the files.  I have been doing this all morning and was able to upgrade about 200 files before the crash.

## What did you see instead?
I received an error that Dynomo had crashed.

### Loaded Packages
- Rhythm 2022.1.5
- GenerativeDesign 1.10.10.0
- GenerativeDesign.Extension 1.10.10.0
- GenerativeDesign.Revit 1.10.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
tracked internally [DYN-6724](https://jira.autodesk.com/browse/DYN-6724)

**Comment by avidit** [comment]
Please reopen the issue, if this occurs again. Thank you
