### ISSUE TITLE
Dynamo fails to launch

### ISSUE THREAD

**Issue by oliwerkulpa** [DynamoDS/Dynamo#14966]
### Dynamo Version

Dynamo Core 2.16.2.5624
Dynamo Revit 2.16.2.9354

### Revit Version

2023.1

### Operating System

Windows 10

### What did you do?

Click the Dynamo icon in Revit

### What did you expect to see?

Dynamo to launch

### What did you see instead?

[image](https://github.com/DynamoDS/DynamoRevit/assets/55832232/2293fe64-f087-416b-ae98-3546c8a32322)

### Details

Problem persists even though:
- Add-ins were removed
- Revit was reinstalled

**Comment by oliwerkulpa** [comment]
Any news on the topic? The project team is stuck with certain action using the workflow utilizing Dynamo. Is there any timeframe for solving these kind of issues?

**Comment by QilongTang** [comment]
Hi @oliwerkulpa Have you tried to reboot the computer and simply delete that folder under `Temp`?

**Comment by QilongTang** [comment]
> Hi @QilongTang, absolutely yes.

And you still see the error above? That's strange, files under `Temp` usually would not be blocked from accessing..

**Comment by QilongTang** [comment]
Thanks @oliwerkulpa Can you try one thing for me? Not sure if you are a Dynamo sandbox user but can you try download just the DynamoSandbox release from https://dynamobuilds.com/. You can pick 2.16.2 release and unzip with 7zip to launch DynamoSandbox.exe. Please let us know if you are running into the same issue. Then we can look at other options

**Comment by oliwerkulpa** [comment]
The test went through. Dynamo Sandbox v 2.16.2 runs successfully on user's machine. We cannot reproduce the same problem encountered when accessing Dynamo from Revit.

**Comment by oliwerkulpa** [comment]
Excuse me, but this thread is far from being closed. Dynamo for Revit 2023.1 is still not working.

**Comment by avidit** [comment]
@oliwerkulpa Sorry for the misunderstanding. Reopening the issue.

**Comment by QilongTang** [comment]
@Mikhinja Have you seen this kind of error on DynamoRevit side?

**Comment by QilongTang** [comment]
hi @oliwerkulpa I did some research but still could not figure out why DynamoRevit behave differently than DynamoSandbox in this case. Can you try another thing for me, when you launch Revit, could you launch it as admin to see if there is any difference?

**Comment by QilongTang** [comment]
Hi since the team need more info to fully address such issue and has been waiting for a month, we are closing this for now until more info available. Appreciate the reporting and conversation!
