### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by elboselyibraheim** [DynamoDS/Dynamo#14972]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
JUST OPENED DYNAMO APPLICATION AND IT WAS CLOSED IMMEDIATELY 
## What did you expect to see?
NORMALLY OPENING AND THE PROGRAN NORMALY RUN
## What did you see instead?
CLOSE THE PROGRAM EMMEDIATLEY
### Loaded Packages
- DynamoPlayerExtension 1.0.0.0
- GenerativeDesign 6.1.1.0
- GenerativeDesign.Extension 6.1.1.0
- GenerativeDesign.Revit 6.1.1.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment]
hi @elboselyibraheim Do see no crash dialog at all or nothing shows up I assume based on your description?

**Comment by elboselyibraheim** [comment]
> hi @elboselyibraheim Do see no crash dialog at all or nothing shows up I assume based on your description?

Yes, crach Dialog it's showing up after 3 seconds. then Dynamo force closed

**Comment by QilongTang** [comment]
Thanks @elboselyibraheim is the dialog the Dynamo one with callstacks or the Autodesk one? If the Dynamo default one shows up, it would be good that you `From the Dynamo crash window select 'Details' -> 'Copy' and paste here` to help our team to digest. Appreciate it!
