### ISSUE TITLE
Obsolete Method Typo / No Info

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/Dynamo#15015]
### Dynamo Version

Dynamo 3.0.0

### Host

N/A

### Operating System

Windows 11

### What did you do?

Migrating Monocle to Dynamo 3.0.0 and I received this error:
![image](https://github.com/DynamoDS/Dynamo/assets/15744724/a890cd7a-2c09-4543-bce9-717dc7847d02)

### What did you expect to see?

Guidance as to what to replace it with

### What did you see instead?

Only obsolete methods, not sure what I should use otherwise.
https://github.com/search?q=repo%3ADynamoDS%2FDynamo%20annotationTitelText&type=code

**Comment by Amoursol** [comment]
@QilongTang I think you worked on this - any advice for @johnpierson  here?

**Comment by johnpierson** [comment]
I actually ended up finding the changed method, and now allows for a description which is pretty cool. For now I am inputting, a blank string for dynamo three and up. https://github.com/johnpierson/MonocleForDynamo/blob/49b9a3cbaff478c77269a16b0b0b387545f69a9b/src/Monocle/PackageUsage/PackageUsageModel.cs#L319

**Comment by QilongTang** [comment]
hi @johnpierson Revisiting this, I think intellisense should provide you with options of other constructors which are not obsoleted. Is there anything I could improve your experience? Like updating comments or something, let me know. I looked at the code and it looks like standard constructor obsoletion.

**Comment by johnpierson** [comment]
Thanks for the reply @QilongTang , it was that I needed to update my budget package which helped. There is still a typo in the suggestion, but, I’m all set now. This issue can be closed now.
