### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by Erikl8** [DynamoDS/Dynamo#15014]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
Run a Civil Connection script

## What did you expect to see?
I was hoping to see the end result, This error was new to me. 

## What did you see instead?
(Fill in here)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@Erikl8 Can you provide the error message please?
