### ISSUE TITLE
Issue Tabs and Spacing in Python scripts

### ISSUE THREAD

**Issue by NonicaTeam** [DynamoDS/Dynamo#15033]
### Dynamo Version

3.0.3

### Host

Revit

### Operating System

Windows 10

### What did you do?

Open an existing graph done in a previous version of Dynamo that contains a Python Script node. As the script was indented using tabs, when trying to add a new line, apparently we cannot add tabs (if added, they are replaced for groups of spaces equivalent to a tab), so if we want to run the script we need to replace all existing tabs for spaces in the script.

### What did you expect to see?

Be able to add an actual tab in the Python IDE.

### What did you see instead?

When we press tab, there is a group of spaces added that simulates a Tab. Also it does not work when copy pasting a tab from anywhere else.

### What packages or external references (if any) were used?

IronPython 2.7.3 & IronPython 3.1.5

### Details

No crash, only difficulty to develop the scripts.

**Comment by ivaylo-matov** [comment]
Hi @NonicaTeam, would a button that converts all tab indentations to space indentations in the existing scripts fix the issue?

**Comment by NonicaTeam** [comment]
That would be great! We had to copy the code to other IDE as the one in Dynamo does not detect such issues.

**Comment by QilongTang** [comment]
> That would be great! We had to copy the code to other IDE as the one in Dynamo does not detect such issues.

Thanks for the feedback! I am closing this since the button mentioned should be available in Dynamo 3.2 release
