### ISSUE TITLE
Springs Nodes don´t work in Revit 2023

### ISSUE THREAD

**Issue by yliuanna** [DynamoDS/Dynamo#15074]
# Issue Description
Hi, i have just started working with Dynamo. I want to import geometry generated in Dynamo (version 2.16) as a family into Revit 2023.
 I used the FamilyInstanceByGeometry node form Spring Nodes(version 210.1.1), but the result I got was only a dictionary without any other information. Also, I couldn´t see the generated geometry in the Revit environment. 
As an experiment, I created a very simple sphere in Dynamo, but I can´t see it in Revit either.

However, I could use the same version of Spring Nodes successfully in Revit 2021(Dynamo version 2.6). 
Why is this happening ? Do I need to adjust any other settings?

By the way, is there any other way to load geometry generated in Dynamo as a family into Revit? The ImportInstance.ByGeometry node in Dynamo´s built-in Revit package isn´t suitable because it generates only a symbol.

Thank you very much in advance!

## Dynamo version
Dynamo: `2.16.1.2727`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment]
hi @yliuanna I saw you closed this issue yourself, is there anything we can help you?
