### ISSUE TITLE
Absturzbericht von Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by uelgit** [DynamoDS/Dynamo#15168]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
(Fill in here)
export partlis with dynamoscript
install bimorphNodes 4.0.13
### What did you expect to see?
(Fill in here)
install bimorphNodes 4.0.13

### What did you see instead?
(Fill in here)
Dynamo crashed

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

   bei Dynamo.PackageManager.PackageManagerSearchViewModel.<>c.<PackageOnExecuted>b__84_3(Tuple`2 x)
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Dynamo.PackageManager.PackageManagerSearchViewModel.PackageOnExecuted(PackageManagerSearchElement element, PackageVersion version, String downloadPath)
   bei Dynamo.PackageManager.ViewModels.PackageManagerSearchElementViewModel.OnRequestDownload(PackageVersion version, Boolean downloadToCustomPath)
   bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
OS: `Microsoft Windows NT 10.0.22631.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by uelgit** [comment]
Dynamo Core 2.3.0.5885
Dynamo Revit 2.3.0.7661

**Comment by uelgit** [comment]
![Screenshot 2024-04-22 153249](https://github.com/DynamoDS/Dynamo/assets/167778780/0c9b9842-6ba2-4841-b9d3-4a22e7e429e9)

**Comment by avidit** [comment]
Fixed

**Comment by QilongTang** [comment]
@avidit Would you provide which version of Dynamo has been fixed?

**Comment by avidit** [comment]
> @avidit Would you provide which version of Dynamo has been fixed?

It was fixed on Dynamo Package Manager backend.
