### ISSUE TITLE
Use OR node with list of boolean

### ISSUE THREAD

**Issue by Alexis0sixelA** [DynamoDS/Dynamo#15177]
### Dynamo Version

2.13.1.3887

### Operating System

W11

### What did you do?

Try to have an OR operation with two list of boolean in input to have on list of boolean in output
![image](https://github.com/DynamoDS/Dynamo/assets/168017214/e7ced20f-59a1-4344-85ac-cdf1fe128706)

### What did you expect to see?

List of boolean with True one index of the two list is True

### What did you see instead?

nul

**Comment by andydandy74** [comment]
Not in front of a computer right now but the other OR node (simply titled "||") should work the way you're expecting.
