### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by osamaemad22** [DynamoDS/Dynamo#15192]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.18363.0`

## What did you do?
(Fill in here)

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2024.217.1024
- bimorphNodes 5.1.3
- Civil3DToolkit 1.1.32
- Clockwork for Dynamo 2.x 2.6.0
- DynamoIronPython2.7 2.1.0
- Genius Loci 2024.2.26
- If Equal Return Index 0.1.0
- LunchBox for Dynamo 2018.8.8
- MEPover 2022.10.30
- Rhythm 2024.3.1
- spring nodes 210.1.1
- SteamNodes 1.2.4
- Zebra 2016.7.2

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by osamaemad22** [comment]
it crashes when i use parameter node

**Comment by avidit** [comment]
@osamaemad22 Could you provide the stack trace and also a sample dyn file if possible?
