### ISSUE TITLE
Rapport d'erreur de Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by 7SimoNo** [DynamoDS/Dynamo#15207]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
i'm trying to use nodes. 

## What did you expect to see?
nodes in the workspace 

## What did you see instead?
nothing

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by 7SimoNo** [comment]
i'm trying to use some simple nodes but it doesn't working

**Comment by avidit** [comment]
@7SimoNo Are you getting any error message? Is it possible share a screen recording?
