### ISSUE TITLE
Improvement: Python node code window 

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#1521]
Would be great that the Edit window of Python nodes remember his previous size/location on the screen.

**Comment by Racel** [comment]
While we do not have plans to address this in the near-term future, we have recently made Python improvements in the new 2.0 build (available at dynamobuilds.com). The Python window will remain open now which may reduce the importance of location persistence. Closing for now.

**Comment by Racel** [comment]
@jbenoit44- Turns out, @Dewb had a chance to work on this in  https://github.com/DynamoDS/Dynamo/pull/8295

We anticipate this will be in the 2.0 builds shortly. Will close this task once it is merged.
