### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by eweG5** [DynamoDS/Dynamo#15330]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
tried to make script for cutting openings (Generic models to walls)

## What did you expect to see?
hmm.. work done :D

## What did you see instead?
Dynamo crash, nodes not working

## What packages or external references (if any) were used?
clockwork

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@eweG5 Is it possible for you to copy the stack trace from the crash dialog? Also, could you please attach any screenshots/gifs and/or Dynamo graph?
