### ISSUE TITLE
Crash report from Dynamo 3.0.3.7597

### ISSUE THREAD

**Issue by phim1004** [DynamoDS/Dynamo#15331]
### Dynamo Version

3.0.3.7597

### Operating System

Microsoft Windows NT 10.0.22631.0

### What did you do?

[image](https://github.com/DynamoDS/Dynamo/assets/53715060/1b94d194-7b19-4f4d-bb74-5e5db12c2a87)

### What did you expect to see?

Make Fmily instance from Dynamo solid

### What did you see instead?

[image](https://github.com/DynamoDS/Dynamo/assets/53715060/005ef9b9-d4fd-4a7d-95be-bb758d554acf)

### Details

CLR: 8.0.0

**Comment by phim1004** [comment]
Message
FamilyType.ByGeometry 작업이 실패했습니다.

ElementId cannot be deleted.

Parameter name: elementId

**Comment by avidit** [comment]
@Mikhinja FYI

**Comment by Mikhinja** [comment]
Is this a crash or a warning? From the images and the warning message it looks like not a crash, but a problem with that node.

It would be good if we could have a Dynamo graph that reproduces the issue so that we can verify it will be fixed in the next update.

**Comment by phim1004** [comment]
![아치교 모델 다이나모_2024-06-27_06-34-40](https://github.com/DynamoDS/Dynamo/assets/53715060/8a026638-f62c-48e6-bd19-64e22171271f)

**Comment by Mikhinja** [comment]
Can we have the *.dyn file and what else is needed to reproduce the issue on our side, please? Recreating from a huge picture is very error prone, and simplifying the graph as much as possible is always helpful, ideally down to just a handful of nodes.

There will be a fix to a similar issue in the upcoming Revit update, but without a graph to reproduce on our side and confirm we can't say if it is the same issue or not.
