### ISSUE TITLE
CPython3 - 'System.Reflection.Emit.TypeBuilder' was not found - Dynamo 3.0.3

### ISSUE THREAD

**Issue by chrizzrott77** [DynamoDS/Dynamo#15347]
### Dynamo Version

3.0.3.7597
(Dynamo Revit 3.0.3.4605)

### Operating System

Microsoft Windows NT 10.0.22631.0

### What did you do?

try to use events subscription with CPython3

Code inside Python Code Block:

import clr
clr.AddReference('System.Windows.Forms')
from System.Windows.Forms import Form, TextBox, Button, DialogResult

def create_input_box():
    # Fenster erstellen
    form = Form()
    form.Text = "Input Box"
    form.Width = 300
    form.Height = 150
    
    # TextBox erstellen
    text_box = TextBox()
    text_box.Width = 200
    text_box.Top = 20
    text_box.Left = 50
    form.Controls.Add(text_box)
    
    # Button erstellen
    button = Button()
    button.Text = "OK"
    button.Width = 50
    button.Top = 60
    button.Left = 125
    
    # Event-Handler für den Button
    def on_button_click(sender, e):
        form.DialogResult = DialogResult.OK
        form.Close()
        
    button.Click += on_button_click
    form.Controls.Add(button)
    
    # Dialog anzeigen
    form.ShowDialog()
    
    return text_box.Text

# Text von der Eingabe-Box holen
input_text = create_input_box()

# Dynamo Output
OUT = input_text

### What did you expect to see?

not an error

### What did you see instead?

Python Error:
![image](https://github.com/DynamoDS/Dynamo/assets/65215267/eca36803-55b1-481a-895d-c9d3ee815185)

### Details

Related Issue: 
https://github.com/DynamoDS/DynamoRevit/issues/3008#issue-1994713029

CLR: 8.0.6

**Comment by avidit** [comment]
@chrizzrott77 Can you try this on https://github.com/DynamoDS/Dynamo/releases/tag/3.2.1

**Comment by Narimannp** [comment]
Has anyone found a solution for this?
this issue arises when updating from 2.18, 2.19 .

**Comment by Narimannp** [comment]
I apprecite your responce. I wish i could. I need the script to work on both 2022 and 2025. Fortunantly i found a solution how to fix the issue in earlier versions.
