### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by ececorlu** [DynamoDS/Dynamo#15342]
# Issue Description
Please fill in the following information to help us reproduce the issue:
parsing two different JSON file to run at the same time. 
I guess, I need to use thread pause. 

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
I am parsing two different JSON file and the file's large size made the crash

## What did you expect to see?
I was expecting to get two file model

## What did you see instead?
the error saying the size is large

## What packages or external references (if any) were used?
no

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@ececorlu Were you using Dynamo OOTB nodes or a node from a third-party extension?
