### ISSUE TITLE
Excel staying open in background after running Dynamo and closing Revit

### ISSUE THREAD

**Issue by DapperDangus** [DynamoDS/Dynamo#15353]
### Dynamo Version

3.0.3.7597

### Host

Autodesk Revit 2025

### Operating System

Microsoft Windows 11

### What did you do?

Ran dynamo script

### What did you expect to see?

Project updates

### What did you see instead?

I saw project updates but dynamo opens excel in background. Even after closing excel when dynamo opens it, excel still continues to run in background.

### What packages or external references (if any) were used?

Excel file

**Comment by avidit** [comment]
> Even after closing excel when dynamo opens it, excel still continues to run in background.

@pinzart any ideas?

**Comment by QilongTang** [comment]
hi @DapperDangus Feel free to switch from the Office Excel nodes to OpenXML nodes which are no longer depending on Excel to open (which could happen everytime legacy excel node executes). Namingly to use`OpenXMLImportExcel` and `OpenXMLExportExcel`, life gets a bit easier.

**Comment by DapperDangus** [comment]
Oh hey didn’t think anyone responded. Thank you for the response, I will give this a try.

**Comment by DapperDangus** [comment]
> hi @DapperDangus Feel free to switch from the Office Excel nodes to OpenXML nodes which are no longer depending on Excel to open (which could happen everytime legacy excel node executes). Namingly to use`OpenXMLImportExcel` and `OpenXMLExportExcel`, life gets a bit easier.

So, I finally was able to give this a shot today.  Using the same file it gives me a null value or it will gives me "Object reference not set to an instance of an object" error. Tried saving my file as XML but that did not help. Converted file path to string, did file from path, used path directly. I must be missing something. Our setup will require us to use excel files so I don't know if there is a way around this.

**Comment by avidit** [comment]
@DapperDangus You don't have to save your excel file as XML. `OpenXMLImportExcel` and `OpenXMLExportExcel` nodes are drop-in replacements for `ImportExcel` and `ExportExcel`. You can replace `ExportExcel` node with `OpenXMLExportExcel` and avoid opening Excel.
![gh-15353_export](https://github.com/user-attachments/assets/070a2e99-4393-4da8-891b-681105a6f39d)

**Comment by QilongTang** [comment]
@DapperDangus I would echo that, and sorry if my previous comment is not so clear. The node name starting with OpenXML might be a bit confusing but the nodes have nothing to do with XML file format requirement. The word `OpenXML` is a library maintained by Microsoft to provide API level support for Office suite related files. You should be able to switch from legacy excel files seamlessly to the OpenXML ones without touching the rest of graph or your target file format (still excel)

**Comment by DapperDangus** [comment]
Ok, I guess I should have specified but not sure if it matters. I only need to import data from excel not export. I'm still getting the same error.
![Screenshot 2024-07-18 092829](https://github.com/user-attachments/assets/03e25fbd-a613-4954-bf07-6dcab1229357)

**Comment by DapperDangus** [comment]
Ok, just tested with a new file. Something must be up with the file I am using then not sure what it is but I will try and diagnose and comment again with my results.

**Comment by QilongTang** [comment]
Thanks @DapperDangus Keep them coming

**Comment by andydandy74** [comment]
From looking at your screenshot, the path length may be an issue. Try a shorter file name, less subfolders and/or shorter folder names.

**Comment by DapperDangus** [comment]
@avidit @QilongTang @andydandy74 

I managed to diagnose the issue with the Data.OpenXMLImportExcel. Apparently that node does not like when the first row has nothing in it. It must seem to read that first row as empty or null and stops there? Not sure. Our excel files have an empty A column and 1 row just for appearance sake. Setting startRow and startColumn to a cell with a value in it did not work either. If that first row does not have at least one cell with a value in it, that node will throw the error or decide the entire file is null. 

This node should work now. I will just set A1 to 0 and turn the text white. Just wish we could keep the file open like we can with the regular import excel node but oh well, compromises I guess.

**Comment by avidit** [comment]
@DapperDangus Glad you found the solution. I will close the issue for now.
I had no issues empty column A and Row 1 either. I will see if there are any other issues related to this.
![gh-15353_import](https://github.com/user-attachments/assets/661d67a7-ec5f-4ab6-ba80-c4c85c4d8ffa)
