### ISSUE TITLE
problem with arduino package

### ISSUE THREAD

**Issue by moez66** [DynamoDS/Dynamo#15362]
### Dynamo Version

dynamo v3.1.0

### Operating System

w11 family

### What did you do?

i am trying to read and write using arduino card using firfly package. i obtain warnings in evry arduini node (get port available, read, xwrite..) warning are: could not load file or assembly

### What did you expect to see?

the number of the port available

### What did you see instead?

warning

### What packages or external references (if any) were used?

firefly

**Comment by avidit** [comment]
@moez66 Do have more detailed warning message? Also is it possible for you to contact the package author about it?

**Comment by moez66** [comment]
i would like to read some data from my arduino connected to port com8, after uploading firefly fermata to the card, i run dynamo  but these are the errors i found:

![Capture d'écran error in dynamo link to ard](https://github.com/DynamoDS/Dynamo/assets/174283012/6f2d6400-2e17-4649-bf99-989bb116e97f)
