### ISSUE TITLE
Crash report from Dynamo 2.12.0.5650

### ISSUE THREAD

**Issue by ShudhirGopinathan** [DynamoDS/Dynamo#15372]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I am trying to import the node for brand new creation of dynamo graph

## What did you expect to see?
plane graph

## What did you see instead?
I see the screen has freezed, it shows a program is running in the background to stop the script.
![Capture](https://github.com/DynamoDS/Dynamo/assets/174612408/cf3a19c1-f67d-4bcc-af66-d0f6c65ff7a3)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@ShudhirGopinathan Is it possible for you to use newer version of Dynamo?
https://dynamobuilds.com/

**Comment by ShudhirGopinathan** [comment]
Project requirements dictate to use the particular version of civil 3d & dynamo

**Comment by avidit** [comment]
@ShudhirGopinathan Can you make sure if your machine satisfies minimum requirements recommended by Civil 3D? Can you try the same operation in another machine?

**Comment by avidit** [comment]
@QilongTang Have you seen this error before?

**Comment by QilongTang** [comment]
> @QilongTang Have you seen this error before?

I have not, @RobertGlobant20 @Enzo707  have you seen it?

**Comment by RobertGlobant20** [comment]
> > @QilongTang Have you seen this error before?
> 
> I have not, @RobertGlobant20 @Enzo707 have you seen it?

No, I haven't see that message. 
I think Dynamo 2.12.0 is using MS WebBrowser (IExplorer - IE8) for Library, then probably there is a problem with IE8, we will need to reproduce it.

**Comment by Enzo707** [comment]
> > @QilongTang Have you seen this error before?
> 
> I have not, @RobertGlobant20 @Enzo707 have you seen it?

No, I haven't seen that message either.
