### ISSUE TITLE
Crash report from Dynamo 3.0.3.7597

### ISSUE THREAD

**Issue by Bentbrandt** [DynamoDS/Dynamo#15371]
### Dynamo Version

3.0.3.7597

### Host

Revit 2025.1

### Operating System

Microsoft Windows NT 10.0.19045.0

### What did you do?

Ran a script originally created in Revit 2019

### What did you expect to see?

Families updated to Revit 2025.1 and having a shared parameter added

### What did you see instead?

the something went wrong sign asking me to send errors to Github

### What packages or external references (if any) were used?

Clockwork
Crumple
Orchid

### Details

CLR: 8.0.6

**Comment by avidit** [comment]
@Bentbrandt is it possible for you to grab the stack trace form the crash report dialog?

**Comment by avidit** [comment]
@Bentbrandt Closing for now. Please feel free to reopen if you encounter this issue again.
