### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by prfwagbeart** [DynamoDS/Dynamo#15375]
# Issue Description
Please fill in the following information to help us reproduce the issue: Join 5 parameter  of element. The element around 20 k

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
Get parameter of element

## What did you expect to see?
element parameter

## What did you see instead?
cash

## What packages or external references (if any) were used?
no 

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@prfwagbeart could you please grab the stack trace from the crash dialog?
