### ISSUE TITLE
PolyCurve.ByPoints fails

### ISSUE THREAD

**Issue by ricardyn** [DynamoDS/Dynamo#15414]
### Dynamo Version

Dynamo Core 2.12.1.8246 and Dynamo Core 2.19.3.6394

### Host

Revit 2022.1 / 2024.2

### Operating System

Windows 11

### What did you do?

Trying to create a PolyCurve by four points.

### What did you expect to see?

The PolyCurve passing through the points

### What did you see instead?

The PolyCurve.ByPoints node creating a PolyCurve connecting just points [1] and [2]. See images below.

[image](https://github.com/user-attachments/assets/02b86113-3d01-4a24-ab48-f4d3a5278cb1)

[image](https://github.com/user-attachments/assets/43939a35-b1e6-416b-b49b-af9ac83732ae)

**Comment by ricardyn** [comment]
Below follows the graph (saved as json to load here) for you try to replicate the issue.

[PolycurveByPoints.json](https://github.com/user-attachments/files/16447771/PolycurveByPoints.json)

**Comment by aparajit-pratap** [comment]
@ricardyn the Dynamo graph you've attached has a geometry scale factor set to `10000.0`. This setting corresponds to the geometry scale setting of extra large, which is known to have issues in Dynamo as it introduces a precision issue with certain geometric operations returning unreliable results. We therefore recommend users to always adhere to the `Medium `setting, which corresponds to a scale factor of `1.0`. If you re-execute your graph with the `Medium` setting, it returns the rectangular polycurve as expected. 
You can find this setting as shown:
![image](https://github.com/user-attachments/assets/dc21947d-5732-4004-8a6c-a534ce72c2a2)

**Comment by ricardyn** [comment]
Thank you for the quick answer.
I see.

Just for registering. It's not always possible to use Medium.

Several structural engineers use centimeters as units in Revit. Causing large numbers in Dynamo.

What do you suggest in those cases that do not involve change project units to run the graph and after turn units back ?

**Comment by aparajit-pratap** [comment]
@ricardyn the geometry scaling feature was indeed introduced to solve the units issue you just highlighted above, however, it didn't turn out to be a one-size-fits-all solution. Although changing the scale setting to large/extra large for large numbers may work in some cases, it isn't guaranteed to work in all cases and therefore may have unintended consequences for some. Unfortunately, at the moment we don't have a good solution but we hope to resolve this in the future. FYI @Amoursol

**Comment by ricardyn** [comment]
@aparajit-pratap I understand. I am very grateful for the attention. Now I know what the problem is. That already has great value.
The solution here was to use another way to build PolyCurve.
