### ISSUE TITLE
Crash report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by Ilayiha** [DynamoDS/Dynamo#15448]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
I want to make create sheets script

## What did you expect to see?
When I want to make changes I couldn't.

## What did you see instead?
The Dynamo show error window and close itself

### Loaded Packages
- Crumple 2022.2.13
- DynamoIronPython2.7 2.1.0
- Modelical 2023.10.6
- GenerativeDesign 2.0.10.0
- GenerativeDesign.Extension 2.0.10.0
- GenerativeDesign.Revit 2.0.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
[Screenshot 2024-08-28 123129](https://github.com/user-attachments/assets/23eb0a77-8a69-4378-b166-e047f12ef732)

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
@Ilayiha Is it possible for you to share the dyn file?
