### ISSUE TITLE
Crash report from Dynamo 2.19.3.6394

### ISSUE THREAD

**Issue by mbrasa** [DynamoDS/Dynamo#15531]
# Issue Description
The problem occurs in any situation where the "Wall Location" node is used. Two errors happen: first, it does not generate the selected information; second, when trying to change the selection, it causes the program to freeze and close.

## Dynamo version
Dynamo: `2.19.3.6394`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you expect to see?
(Fill in here)

## What did you see instead?
Freeze and close Dynamo and Revit.

## What packages or external references (if any) were used?
No external packages.

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by mbrasa** [comment]
An quick mock-up file is here [https://1drv.ms/u/s!An0WocZk-VhWg4dhdITXDlYR_nImqg?e=ezklXF](url).
I added a detailed step-by-step guide directly on it.

**Comment by emru-y** [comment]
Hello @mbrasa,

I was able to reproduce the issue. Thank you very much for your feedback. After we investigate the cause, we will come back to you with an update!
