### ISSUE TITLE
Informe de conflictos de Dynamaps

### ISSUE THREAD

**Issue by Sormoran** [DynamoDS/Dynamo#15554]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`- Dynamaps

## What did you do?
urbanization

## What did you expect to see?
I saw a tutorial on how to use dynamaps, but when I tried it it didn't work and it didn't show me the map in dynamo

## What did you see instead?
Nothinf

## What packages or external references (if any) were used?
Dynamaps

---
CLR: `4.0.30319.42000`
![dynamaps](https://github.com/user-attachments/assets/7bf7345f-3e3e-4f10-9a03-1f51ea435ba9)

**Comment by JacobSmall** [comment]
Likely an issue with "could not load Autodesk.RevitDb.DisplayUnitType" or something similar. 

Dynamaps is not owned byt he Dynamo team, and the package has not been updated to work with the unit changes which were introduced in 2023. At this time I'm guessing it's not going to be supported any more, but you can reach out to the package author directly via the Dynamo forum or the Datashapes website: https://data-shapes.io/2019/08/17/dynamaps-to-revit/. 

Best to look into an alternative package such as Elk, Dynamo for Forma, or similar.

**Comment by Sormoran** [comment]
Thanks to the first person I comment, now the node does not appear in yellow: c but still the dynamaps does nothing, I have revit 2022 so I will try other alternatives as the second comment suggests, thank you very much for your contributions

**Comment by Sormoran** [comment]
![Uploading Dynamo.png…]()
