### ISSUE TITLE
Crash report from Dynamo 2.16.2.5624

### ISSUE THREAD

**Issue by Nazliy-ny** [DynamoDS/Dynamo#15598]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.16.2.5624`

## Operating system
OS: `Microsoft Windows NT 10.0.22631.0`

## What did you do?
tried to replace a certain string value

## What did you expect to see?
a new list with changed values

## What did you see instead?
error pop up

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by avidit** [comment]
tracked internally https://jira.autodesk.com/browse/DYN-7783

**Comment by avidit** [comment]
@Nazliy-ny Is it possible for you to share the dynamo graph?
