### ISSUE TITLE
Select Face

### ISSUE THREAD

**Issue by wruffenach** [DynamoDS/Dynamo#1592]
Could we add the ability to select multiple faces in Dynamo so we could add surface area together, currently there is a way to select model elements, and extract all the faces. Also the ability to select one face. Could the Select Face node be modified to allow for you to select multiple faces from different solids/elements and combine into list?

**Comment by ikeough** [comment]
Select Faces node now exists. Closing for now. Please re-open if you're still waiting for more :)
