### ISSUE TITLE
Possible bug when trimming a surface with a solid

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#1601]
It seems that when you use a solid as tool for trimming a surface, the result is the solid trimmed by the surface (the roles of geometry and tool are exchanged)
![01](https://cloud.githubusercontent.com/assets/6596042/2862421/bcd9abec-d1f1-11e3-8794-6b5fca549f3f.jpg)

**Comment by johnpierson** [comment]
Going ahead and closing this as it is for a very old version of Dynamo. If this kind of problem still persists for you in 2.0.x releases, please feel free to open a new issue with updated information.
