### ISSUE TITLE
Rename input on Custom Node when not saved in default location

### ISSUE THREAD

**Issue by TimWaldock** [DynamoDS/Dynamo#1605]
I have tried saving dynamo code and custom nodes in locations other than the default that it directs you to.  Not only is it annoying that it does not remember file locations, but if you try to rename the inputs on a custom node, it does not update the parent code that you created the custom node from.  If you save them to default location, it does update in the parent as soon as you save and close the custom node.

**Comment by Racel** [comment]
You can now use 'Manage Node and Pacakge Paths..' to track custom nodes and packages in various locations.
