### ISSUE TITLE
v.7 Get.Parameter node not working for floor and other floor issues

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#1643]
FLOOR ISSUES 
1 Get.Parameter Not displaying TYPE parameter value for Floors (Structural Material) for example 
(Comment is an instance and it works)
2 NOTE GET WORKS for type parameters IN v.6!!!!!!!!!!
also SET WORKS in v.6 and v.7
3 Element.Parameters not Listing "Mark"
4. Side note "material not listing parameters" works in v.6
See image
![room_issue](https://cloud.githubusercontent.com/assets/6132497/2940007/2022e5fa-d969-11e3-857c-7129db906968.png)

**Comment by riteshchandawar** [comment]
Hello @marcellosgamb 
This issue has been fixed in latst build. 
Please let me know if you are still seeing this issue.

Thanks,
Ritesh
