### ISSUE TITLE
WISH: Quick and easy input of values

### ISSUE THREAD

**Issue by tomekwi** [DynamoDS/Dynamo#1676]
I see some room for improvement as far inputting parameters (numbers, booleans etc.) is concerned.

The workflow I use is intuitive but quite inefficient – I just pick the appropriate thing under Core > Input or find it using search. You do these things often. Lots of unnecessary mouse klicks or keyboard labour. I don't know of other ways to do it.

Modifying number values when you have a simple number field (without the workspace-eating slider) requires select + input new value. Quite inefficient when you want to test different design variations by small increments of input parameters.
### Good examples in the wild:
- In Grasshopper you can double-click in empty workspace to pull up search. Instead of that you can also directly input the value in the dialog that comes up. You can see this well in [this tutorial around 2:40 - 3:15](http://youtu.be/Kyi_K85Gsm4?t=2m36s)
- In Chrome Developer Tools' Styles tab you can quickly modify number values when they are highlighted – `[UP/DOWN]` increases/decreases the value by 1, `[ALT + UP/DOWN]` by 0.1, `[SHIFT + UP/DOWN]` by 10 etc. For reference: https://developer.chrome.com/devtools/docs/shortcuts#styles-sidebar

**Comment by Racel** [comment]
You can easily do this by using a CBN. Double-click on the canvas to create a CBN. Then just type your number, string, boolean and feed it into a node.

To bring up search, right-click over the canvas.

We do not have plans of addressing this in the WPF UI, but will consider for the next generation Dynamo UI.
