### ISSUE TITLE
Code Block Node bug - Unhappy but executed.

### ISSUE THREAD

**Issue by gschleusner** [DynamoDS/Dynamo#1678]
<?xml version="1.0"?>
-<Commands CommandIntervalInMs="20" PauseAfterPlaybackInMs="10" ExitAfterPlayback="true"> <OpenFileCommand XmlFilePath="C:\+HOK\DynamoDemo\CurtainPanels_Patternand Select_v7_2.dyn"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <SelectModelCommand Modifiers="0" ModelGuid="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <SelectModelCommand Modifiers="0" ModelGuid="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <MakeConnectionCommand ConnectionMode="0" Type="0" PortIndex="0" NodeId="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <MakeConnectionCommand ConnectionMode="2" Type="0" PortIndex="-1" NodeId="00000000-0000-0000-0000-000000000000"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="49939ced-6986-4da0-8533-49ef7e9e956f"/> <MakeConnectionCommand ConnectionMode="1" Type="0" PortIndex="0" NodeId="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <SelectModelCommand Modifiers="0" ModelGuid="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <SelectModelCommand Modifiers="0" ModelGuid="2050fe0c-ee6a-4f54-bf3d-7e4b640b7402"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <CreateNodeCommand NodeId="e3550349-457d-4f26-a168-439da63fc2bf" TransformCoordinates="true" DefaultPosition="true" Y="0" X="0" NodeName="List.Map"/> <SelectModelCommand Modifiers="0" ModelGuid="e3550349-457d-4f26-a168-439da63fc2bf"/> <DragSelectionCommand Y="-831.283728591651" X="929.501006024472" DragOperation="0"/> <DragSelectionCommand Y="-832.475613181524" X="1139.27269384215" DragOperation="1"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="e3550349-457d-4f26-a168-439da63fc2bf"/> <MakeConnectionCommand ConnectionMode="1" Type="0" PortIndex="1" NodeId="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <SelectModelCommand Modifiers="0" ModelGuid="2050fe0c-ee6a-4f54-bf3d-7e4b640b7402"/> <DragSelectionCommand Y="-614.360733234733" X="1139.27269384215" DragOperation="0"/> <DragSelectionCommand Y="-864.6564971081" X="968.833197490287" DragOperation="1"/> <UndoRedoCommand CmdOperation="0"/> <UndoRedoCommand CmdOperation="0"/> <SelectModelCommand Modifiers="0" ModelGuid="e3550349-457d-4f26-a168-439da63fc2bf"/> <SelectModelCommand Modifiers="0" ModelGuid="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <CreateNodeCommand NodeId="fe5b48fb-5406-49c8-9a20-7647ef0dda8c" TransformCoordinates="true" DefaultPosition="true" Y="0" X="0" NodeName="Autodesk.DesignScript.Geometry.Curve.Normal"/> <SelectModelCommand Modifiers="0" ModelGuid="fe5b48fb-5406-49c8-9a20-7647ef0dda8c"/> <DragSelectionCommand Y="-806.254152204314" X="952.146813232063" DragOperation="0"/> <DragSelectionCommand Y="-695.408885346109" X="1473.00037900664" DragOperation="1"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <MakeConnectionCommand ConnectionMode="1" Type="0" PortIndex="0" NodeId="fe5b48fb-5406-49c8-9a20-7647ef0dda8c"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <SelectModelCommand Modifiers="0" ModelGuid="fe5b48fb-5406-49c8-9a20-7647ef0dda8c"/> <SelectModelCommand Modifiers="0" ModelGuid="fe5b48fb-5406-49c8-9a20-7647ef0dda8c"/> <SelectModelCommand Modifiers="0" ModelGuid="e3550349-457d-4f26-a168-439da63fc2bf"/> <SelectModelCommand Modifiers="0" ModelGuid="dbcaa652-338a-4918-85b5-957fdae06bd4"/> <CreateNodeCommand NodeId="8a12e2aa-a772-4adb-bd73-9d99a08a2162" TransformCoordinates="true" DefaultPosition="true" Y="0" X="0" NodeName="Autodesk.DesignScript.Geometry.Point.ByCartesianCoordinates@Autodesk.DesignScript.Geometry.CoordinateSystem,double,double,double"/> <SelectModelCommand Modifiers="0" ModelGuid="8a12e2aa-a772-4adb-bd73-9d99a08a2162"/> <DragSelectionCommand Y="-776.457037457485" X="993.862773877624" DragOperation="0"/> <DragSelectionCommand Y="-859.888958748607" X="695.891626409329" DragOperation="1"/> <SelectModelCommand Modifiers="0" ModelGuid="8a12e2aa-a772-4adb-bd73-9d99a08a2162"/> <DragSelectionCommand Y="-858.697074158734" X="712.578010667554" DragOperation="0"/> <DragSelectionCommand Y="-858.697074158734" X="712.578010667554" DragOperation="1"/> <DeleteModelCommand ModelGuid="00000000-0000-0000-0000-000000000000"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <CreateNodeCommand NodeId="86f40826-8bea-4be5-b8b2-854208809c75" TransformCoordinates="true" DefaultPosition="false" Y="-837.243151541017" X="350.245095346108" NodeName="Code Block"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <UpdateModelValueCommand ModelGuid="86f40826-8bea-4be5-b8b2-854208809c75" Value="5" Name="Code"/> <SelectModelCommand Modifiers="0" ModelGuid="86f40826-8bea-4be5-b8b2-854208809c75"/> <DragSelectionCommand Y="-846.778228260002" X="306.1453655208" DragOperation="0"/> <DragSelectionCommand Y="-790.759652535963" X="315.680442239786" DragOperation="1"/> <CreateNodeCommand NodeId="fd6bc8d8-d82e-41a6-a027-4c8cfcfcefb8" TransformCoordinates="true" DefaultPosition="true" Y="0" X="0" NodeName="Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double"/> <SelectModelCommand Modifiers="0" ModelGuid="fd6bc8d8-d82e-41a6-a027-4c8cfcfcefb8"/> <DragSelectionCommand Y="-720.438461733446" X="1078.48657975862" DragOperation="0"/> <DragSelectionCommand Y="-865.848381697973" X="626.762320196685" DragOperation="1"/> <CreateNodeCommand NodeId="cd420be4-bf37-4b47-91b6-ef5e256e75f0" TransformCoordinates="true" DefaultPosition="true" Y="0" X="0" NodeName="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double"/> <SelectModelCommand Modifiers="0" ModelGuid="cd420be4-bf37-4b47-91b6-ef5e256e75f0"/> <DragSelectionCommand Y="-827.708074822032" X="921.15781389536" DragOperation="0"/> <DragSelectionCommand Y="-900.413034804295" X="283.49955831321" DragOperation="1"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="cd420be4-bf37-4b47-91b6-ef5e256e75f0"/> <MakeConnectionCommand ConnectionMode="1" Type="0" PortIndex="0" NodeId="fd6bc8d8-d82e-41a6-a027-4c8cfcfcefb8"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="86f40826-8bea-4be5-b8b2-854208809c75"/> <MakeConnectionCommand ConnectionMode="1" Type="0" PortIndex="1" NodeId="fd6bc8d8-d82e-41a6-a027-4c8cfcfcefb8"/> <SelectModelCommand Modifiers="0" ModelGuid="86f40826-8bea-4be5-b8b2-854208809c75"/> <SelectModelCommand Modifiers="0" ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <DragSelectionCommand Y="-790.759652535963" X="200.067637022087" DragOperation="0"/> <DragSelectionCommand Y="-697.792654525855" X="432.485132047357" DragOperation="1"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <SelectInRegionCommand Y="-679.914385677758" X="515.917053338479" IsCrossSelection="false" Height="2.38376917974631" Width="0"/> <SelectModelCommand Modifiers="0" ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <DragSelectionCommand Y="-697.08158656099" X="437.094041343174" DragOperation="0"/> <DragSelectionCommand Y="-694.422830289145" X="365.307622003345" DragOperation="1"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <UpdateModelValueCommand ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d" Value="5;" Name="Code"/> <SelectInRegionCommand Y="-641.247704852234" X="465.010982197552" IsCrossSelection="false" Height="0" Width="0.664689067961433"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <CreateNodeCommand NodeId="9b2466d5-dcf9-46bd-831f-23568987081d" TransformCoordinates="true" DefaultPosition="false" Y="-630.612679764852" X="476.975385420857" NodeName="Code Block"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <UpdateModelValueCommand ModelGuid="9b2466d5-dcf9-46bd-831f-23568987081d" Value="" Name="Code"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <UpdateModelValueCommand ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d" Value="Circle.ByCenterPointRadius(pt,7)" Name="Code"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <MakeConnectionCommand ConnectionMode="2" Type="0" PortIndex="-1" NodeId="00000000-0000-0000-0000-000000000000"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="cd420be4-bf37-4b47-91b6-ef5e256e75f0"/> <MakeConnectionCommand ConnectionMode="1" Type="0" PortIndex="0" NodeId="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <SelectModelCommand Modifiers="0" ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <DragSelectionCommand Y="-694.422830289145" X="580.002190954871" DragOperation="0"/> <DragSelectionCommand Y="-645.235839260003" X="622.542291304399" DragOperation="1"/> <MakeConnectionCommand ConnectionMode="0" Type="0" PortIndex="0" NodeId="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <MakeConnectionCommand ConnectionMode="2" Type="0" PortIndex="-1" NodeId="00000000-0000-0000-0000-000000000000"/> <MakeConnectionCommand ConnectionMode="0" Type="0" PortIndex="0" NodeId="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <MakeConnectionCommand ConnectionMode="2" Type="0" PortIndex="-1" NodeId="00000000-0000-0000-0000-000000000000"/> <UpdateModelValueCommand ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d" Value="Point.ByCoordinates(0,10,0); Circle.ByCenterPointRadius(pt,7);" Name="Code"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <MakeConnectionCommand ConnectionMode="0" Type="1" PortIndex="0" NodeId="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <MakeConnectionCommand ConnectionMode="2" Type="0" PortIndex="-1" NodeId="00000000-0000-0000-0000-000000000000"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <UpdateModelValueCommand ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d" Value="pt=Point.ByCoordinates(0,10,0); Circle.ByCenterPointRadius(pt,7);" Name="Code"/> <RunCancelCommand CancelRun="false" ShowErrors="false"/> <SelectModelCommand Modifiers="0" ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <DragSelectionCommand Y="-639.918326716312" X="488.939788644162" DragOperation="0"/> <DragSelectionCommand Y="-635.930192308543" X="482.292897964548" DragOperation="1"/> <SelectModelCommand Modifiers="0" ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <SelectModelCommand Modifiers="0" ModelGuid="82465a95-0ee5-4f27-8616-b4683ee31e1d"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> <SelectModelCommand Modifiers="0" ModelGuid="00000000-0000-0000-0000-000000000000"/> </Commands>

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
