### ISSUE TITLE
"Evaluate Curve or Edge" and "XYZ Array on Curve" do not Return Even-Length Segments for Evenly Spaced Parameters on Splines.

### ISSUE THREAD

**Issue by s-overall** [DynamoDS/Dynamo#168]
As described in the title, "Evaluate Curve or Edge" and "XYZ Array on Curve" do not return even-length segments for evenly spaced parameters on splines

You can see in this example below that the points are placed much closer together on the spline as the curvature becomes tighter.
![segment length](https://f.cloud.github.com/assets/4680004/681675/751ac3aa-d9b7-11e2-9c96-c7287f95deb8.jpg)

At the moment, "Evaluate Curve or Edge" is a bit of a false lead for a lot of applications, because most of the time people are going to want evenly-spaced points.

**Comment by riteshchandawar** [comment]
With recent changes to Curve Divide and Points at Parameter, this problem may not exist.

I am closing this issue, please report back if the newly added node (in latest 1.0 release) doesn't solve your problem.

Ritesh
