### ISSUE TITLE
Python nodes with single input hard to edit by double click

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1701]
![pythonscriptwithoneinput](https://cloud.githubusercontent.com/assets/3014437/3144520/7e2c80d2-ea23-11e3-8603-65215f4259e2.PNG)
While I welcome the fact that there is only one Python node now, I find that Python nodes with a single input are extremely hard to edit by double click as there is basically no space to click into. I know I can use the context menu or I could add a (temporary) second input, but it would be helpful if the Python node were just a little bit larger to offer some clickable space...

**Comment by ikeough** [comment]
@riteshchandawar The internal issue is still open. What is the status?
