### ISSUE TITLE
Element.get.ParameterValueByName

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1706]
trying to acces parameter values from walls i get odd results.
querying a parameter of type string delivers expected result.
querying a parameter of type float results in empty list.

my error or a bug?
(daily build 20140601T1531)
![bug-in-parmaters](https://cloud.githubusercontent.com/assets/6928491/3149767/65bb4862-ea6e-11e3-8f08-62993924c53e.png)

**Comment by ke-yu** [comment]
Fixed in #3712 and #3666

**Comment by ikeough** [comment]
Guys, just a follow-on to @ke-yu's links above. Strings in Dynamo now support Unicode, so we should see better behavior with umlauts and the like. Please give some time for the linked PRs to be brought in before testing again.
