### ISSUE TITLE
Element.get.ParameterValueByName v2.0

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1715]
I found the problem: German special characters like ä,ö,ß,ü are not supported for parameter names.
if you run the same nodes in the English version there are no issues.

![bug-in-parmaters](https://cloud.githubusercontent.com/assets/6928491/3162269/8e1f9220-eb33-11e3-90a3-591e004edd21.png)

**Comment by ke-yu** [comment]
Fixed in #3712 and #3666
