### ISSUE TITLE
Wish - to allow optional inputs in custom nodes

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#1765]
Some default nodes have optional inputs. For example, in PolyCurve.ByPoints Dynamo assumes correctly that normally I am not using it for closed profiles. So I am not having to connect a true/false node to  "ConnectLasttoFirst" every time I am using it. "ConnectLasttoFirst" is an optional input with a default value of "false".

Sadly it seems not possible to make custom nodes with this smart behavior. All the inputs must be filled. Even if the internal logic of the  custom node is taking care of what to do if some are not.

Maybe a possibility would be the option of setting a default value in the "input" nodes when defining a custom node. If nothing connected to the default value, that input must be filled necessarily when using the custom node. If something is connected to the default value, the input becomes optional.

**Comment by ikeough** [comment]
Default values are now available in `Input` nodes in custom nodes. Closing.
