### ISSUE TITLE
python nodes from daily builds 20140612T0504

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1767]
trying andreas dieckmanns Element to IDs and IDs to Elements nodes:
working in daily build 20140611T0510 
refuse to work in 20140612T0504
result = empty list.
testing enviroment used following nodes:
categories -> all.Elements.of.Category -> Element to IDs -> IDs to Elements.

result: empty list in last node

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
