### ISSUE TITLE
Strange drop in performance when using conditionals

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#1774]
In developing custom nodes I am finding sometimes that the inclusion of conditionals results in a big drop in performance. 

For example, in a tool that makes sweep with automatic reposition of the profile, I am using Curve.IsClosed for checking if making a solid or a surface. The tool was initially far more complex, but I have reduced the logic to the very minimum trying to understand what is going on. Right now is just a simple DS function.

I have prepared this small sample for easily check the performance.
![01](https://cloud.githubusercontent.com/assets/6596042/3301701/d2b9d38c-f62d-11e3-88bd-2ae9ae5347b5.jpg)

There are two versions of the function. One is making directly SweepAsSolid and other one  ().IsClosed?().SweepAsSolid() : ().SweepAsSurface();

The one with the conditional is between 3 o 4 times slower.

If someone wants to take a look, the files related are here (change the extension to rar)

![20140617](https://cloud.githubusercontent.com/assets/6596042/3301740/4f5a9fca-f62e-11e3-9dd9-0ac5cb35298b.jpg)

**Comment by johnpierson** [comment]
Going ahead and closing this as it is for a very old version of Dynamo. If this kind of problem still persists for you in 2.0.x releases, please feel free to open a new issue with updated information.
