### ISSUE TITLE
Select Multiple Elements

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#1777]
Is there a way to select multiple elements when using the Revit>Selection Nodes. As an example I am trying to extract the XYZ of reference points within my model and wish to be able to select multiple points at once and use the outputs in a list. It seems I can only select one element at a time and therefore would have to create the node sequence several times over. Appreciate any help or guidance thanks.

**Comment by johnpierson** [comment]
Referenced in #355
