### ISSUE TITLE
Setting File Path to this CVS file crashes dynamo

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/Dynamo#1796]
In 0.7.0.27447:
Create a file path node
Browse to attached schoolprogram.csv file
--> Crash

**Comment by TimWW** [comment]
Still occurring in 0.9.0

**Comment by RodRecker** [comment]
@TimWW Can you post the file somewhere and tell us what the exact file path is? Also are you using a localized version of Dynamo?

**Comment by johnpierson** [comment]
Closing this issue as we are missing files needed to recreate. If this is still an issue, feel free to reopen with the additional files attached.
