### ISSUE TITLE
Python Node  - cannot return python dictionary objects

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#1805]
all key types return error - no definition for Key
![screen shot 2014-06-24 at 5 39 45 pm](https://cloud.githubusercontent.com/assets/508936/3378298/5bfa155c-fbe8-11e3-8e3e-32345a892d20.png)
![screen shot 2014-06-24 at 5 39 37 pm](https://cloud.githubusercontent.com/assets/508936/3378300/5c7bc80e-fbe8-11e3-82d5-5dd8d5d31e76.png)

**Comment by ikeough** [comment]
Closing as a duplicate.
