### ISSUE TITLE
Dynamo <-> Vasari Back and Forth:  Workflow Issue

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#181]
Consider the following workflow...

1.  Dynamo is used to generate Reference Curve geometry...
![image](https://f.cloud.github.com/assets/1890663/689495/c647db02-dab4-11e2-836f-a36a9834d1ea.png)

2.  Designer uses Dynamo Reference Curves to create a surface using Make Form in Vasari... the surface updates when the Dynamo definition changes.
![image](https://f.cloud.github.com/assets/1890663/689512/02f4dc26-dab5-11e2-9eeb-75f6b227c990.png)

3.  Designer can Reference the Vasari Surface BACK into Dynamo using Select Face...  However, when the curves change, the Vasari Surface will change, but the Select Face node will NOT refresh the surface.  
![image](https://f.cloud.github.com/assets/1890663/689538/b5f43736-dab5-11e2-8acf-c2e2d1d75f15.png)

My question:  Why not?  :)

**Comment by riteshchandawar** [comment]
Workflow mentioned in this issue worked with Revit.
Vasari is already discontinued.

Closing this issue.

Thanks,
Ritesh
