### ISSUE TITLE
Taking the given number of indexs from a list

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#1810]
I have a double branched list similar to the image attached. I want to get the information at each index and create a separate curve through these given points. However if there are several index’s I don’t want to have to write out the same piece of script numerous times and change the number input. Is there a way to run an array that understands to select every grouped index separately and apply that to one instance of the script, which as an output produces a list of curves?

Or is this something I need to use the python script node for?

![capture](https://cloud.githubusercontent.com/assets/6421438/3387259/3d668316-fc7c-11e3-8a14-8ea1a912b0ea.JPG)

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
