### ISSUE TITLE
units and parameters

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1840]
formula: x/y=z 
(values come from a list)
instance parameters
x is of type area
y is of type length
z is of type length
using the unit conversion nodes like "length from double" results in 
error: 
Die beste Übereinstimmung für die überladene Revit.Elements.Element.SetParameterValue(Autodesk.Revit.DB.Parameter, double)-Methode enthält einige ungültige Argumente.
Element.SetParameterByName operation failed. 

using the same code without assigning units works.
(dynamo assumes decimal inches and you have to calculate yourself)

**Comment by ikeough** [comment]
Units have been obsoleted.

Closing as out of date. If this is still an error in more recent builds, please re-open.
