### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1882]
language related special characters still do not work for paramers.
unfortunately build in parameters use special characters.like area in german version is fläche

**Comment by andydandy74** [comment]
Looks like the same issue for Japanese Revit version:
http://dynamobim.com/forums/topic/getting-double-byte-name-parameter-value/

**Comment by ke-yu** [comment]
Fixed in https://github.com/DynamoDS/Dynamo/pull/3712 and https://github.com/DynamoDS/Dynamo/pull/3666
