### ISSUE TITLE
Wish: Deprecation graphic for custom nodes

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1923]
I just came across this nice graphic on the forums:
![deprecated](https://cloud.githubusercontent.com/assets/3014437/3538556/9459dd56-0831-11e4-8b96-bb50177eea3d.PNG)
Could we have this for custom nodes, too? More specifically: for those custom nodes that are part of a deprecated package?

**Comment by Racel** [comment]
Closing as their is another related issues in #1171 that seems to have more discussion. Additionally, we will probably not be able to address this until we roll-out the new package manager backend.
