### ISSUE TITLE
Unique Items not working with points

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#1931]
In the image below, Items 1 and 2 are the same, so the unique list should provide a list with 3 items.  The node isn't able to produce output.
![mode_lab_294 jul 10 20 39](https://cloud.githubusercontent.com/assets/6820526/3547284/de38c646-0893-11e4-8995-947dea3e8310.jpg)

**Comment by ikeough** [comment]
Internal issue has been closed.
