### ISSUE TITLE
codeblock comma

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1944]
daily build 07-12
input in codeblock: 43.0985915492
output : 430985915492
input 43.0
output: 430
input: 43
output: 43.000

so the comma vanishes.
maybe problem with localized german version?????

**Comment by ikeough** [comment]
@riteshchandawar Was this ever fixed?

**Comment by ke-yu** [comment]
MAGN-3913 has been fixed. We could close it now.
