### ISSUE TITLE
Wish / Migration:  Vector Angle Method for DesignScript

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#1945]
Whenever possible, I'm trying to migrate my geometry nodes to be based on the DesignScript library so they are not as dependent on the Revit API.

I was in the process of migrating over several vector nodes that I made for 0.6.3  The node uses Revit's  XYZ __AngleTo__ method which allows me to compute the angle in radians between two vectors.  There does not seem to be an equivalent way to calculate angles in DesignScript

So is there a recommended way to calculate the angle between vectors (or similar) using DesignScript?  Can this get added?

**Comment by ikeough** [comment]
@archinate Closing this, because I'm pretty sure you've figured this out by now ;)
