### ISSUE TITLE
Migration Issue:  Revit Geometry, ToDSType not an attribute?

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#1946]
I have several scripts that are returning boundary curve information (among other geometries) from Revit.  However, I seem unable to wrap these geometries so they preview inside of Dynamo (When I try to use **ToDSType()** Python tells me it is not an attribute of these elements).

For example, I have one script that is returning a list of **Autodesk.Revit.DB.Lines** 
![image](https://cloud.githubusercontent.com/assets/1890663/3566656/ac2deab6-0afd-11e4-9798-437a28443bd2.png)

What is the best way to wrap and/or convert these Lines so they are compatible with Dynamo/DesignScript and will Preview?

**Comment by zakharv13** [comment]
Can you tell me how to check and make visible Revit.GeometryConversions.RevitToProtoCurve ??
