### ISSUE TITLE
Can't deprecate package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#1968]
This one's probably for you @pboyer - I can't deprecate the package Increment/Deprecate by 1. Since it works for other packages, I believe it's because of the slash in the package name. Could you please mark this package as deprecated in the package manager backend? Thanks in advance!

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.

**Comment by andydandy74** [comment]
@ikeough - This is not an error per se. This is simply a request to set the above mentioned package as deprecated in the PM database on your end since it cannot be done via the UI (possibly because the package name contains a slash). 
I don't think this something that needs fixing in the package manager code since slashes are no longer allowed in package names.
