### ISSUE TITLE
instability

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#1996]
latest build 20.07 2014 
works - crashes - works
unexpected behavior generating a list of generic models with parameters.
one time it works fine the other it crashes
error:

 bei System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   bei System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   bei System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   bei System.Runtime.Serialization.ObjectManager.DoFixups()
   bei System.Runtime.Serialization.Formatters.Soap.ObjectReader.Deserialize(HeaderHandler handler, ISerParser serParser)
   bei System.Runtime.Serialization.Formatters.Soap.SoapFormatter.Deserialize(Stream serializationStream, HeaderHandler handler)
   bei ProtoCore.CallSite.LoadSerializedDataIntoTraceCache(String serializedTraceData)
   bei ProtoCore.CallSite..ctor(Int32 classScope, String methodName, FunctionTable globalFunctionTable, ExecutionMode execMode, String serializedTraceData)
   bei ProtoCore.Core.GetCallSite(GraphNode graphNode, Int32 classScope, String methodName)
   bei ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   bei ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   bei ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   bei ProtoAssociative.Executive.Execute(Int32 codeblock, Int32 entry, Context callContext, EventSink sink)
   bei ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   bei ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   bei ProtoScript.Runners.LiveRunner.Execute()
   bei ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   bei ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   bei ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   bei Dynamo.DSEngine.EngineController.UpdateGraph(Exception& fatalException)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
