### ISSUE TITLE
thought for iterative workflows- node that dirties graph explicitly

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#2002]
When running a graph that will modify the Revit environment, for instance to take pictures while updating parameters, the graph will only run once unless you force re execution by modifying and rerunning.

In many instances this is not the preferred behavior and the expectation is that the graph will just run again and resave the images, modify revit, ,perform another round of local search etc.

wish is to include a node that when executed, dirties the graph explicitly.

**Comment by jhubers** [comment]
Newbe question: Did somebody already find a way to force re-execution by code in a UI node based on the HelloDynamo example? I can't figure out how to catch the runenabled event...
