### ISSUE TITLE
Element.GetParameterValueByName daily build 20140723T0300

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#2035]
a given list of to elements (rooms)
both rooms have same level (parameter "Level")

Element.GetParameterValueByName returns following results:
for item [0] Name_of_Level (in this case "EG RDOK")
for item[1] Id_of_level (in this case 250756)
where 250756 is the element Id for level "EG RDOK"
![elementgetparamter](https://cloud.githubusercontent.com/assets/6928491/3686231/7606d478-1315-11e4-8b00-3e257775bb03.png)

**Comment by kronz** [comment]
Should be fixed by recent work on disambiguating duplicate parameter names
