### ISSUE TITLE
Sorting select model elements

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#2072]
When using the 'Select Model Elements' it automatically lists these elements by the Revit ID number. It would be good, if there is not already, a method to sort and arrange these elements based on other criteria. For example it would be good if using the 'FamilyInstance.Location' node you can pull out its XYZ of the elements and order based on their position. But at the end still have a list of elements rather than a list of points so you can use element nodes.

![element ordering](https://cloud.githubusercontent.com/assets/6421438/3764968/47caeb7e-18b7-11e4-9d7c-4f0f4838bbd8.JPG)

**Comment by ksobon** [comment]
@MarkThorley @mjkkirschner I think this was resolved with the addition of Sort.ByFunction node. Can we close this?
