### ISSUE TITLE
Eclipse pydev support

### ISSUE THREAD

**Issue by garyedwards** [DynamoDS/Dynamo#2082]
Hi, I am looking to develop some python nodes using the eclipse IDE.  I can do this with Rhino's IronPython as detailed in the following tutorial.:

http://stevebaer.wordpress.com/2010/06/12/configuring-pydev-for-rhino-python/

I was wondering if someone could point me in the direction of the dlls that I would have to use as “Forced Builtin”s to get auto complete working with dynamo python?  Also would they have to be renamed to match the root namespace.

Thanks in advance for any tips,

Gary

**Comment by ikeough** [comment]
@garyedwards If your experiments revealed a way of getting code completion working with pydev, please let us know and we can include a doc on the wiki.
