### ISSUE TITLE
dynamo 0.7 调用的目标发生了异常。

### ISSUE THREAD

**Issue by zhadiqi** [DynamoDS/Dynamo#2084]
在 System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   在 System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   在 System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   在 System.Runtime.Serialization.ObjectManager.DoFixups()
   在 System.Runtime.Serialization.Formatters.Soap.ObjectReader.Deserialize(HeaderHandler handler, ISerParser serParser)
   在 System.Runtime.Serialization.Formatters.Soap.SoapFormatter.Deserialize(Stream serializationStream, HeaderHandler handler)
   在 ProtoCore.CallSite.LoadSerializedDataIntoTraceCache(String serializedTraceData)
   在 ProtoCore.CallSite..ctor(Int32 classScope, String methodName, FunctionTable globalFunctionTable, ExecutionMode execMode, String serializedTraceData)
   在 ProtoCore.Core.GetCallSite(GraphNode graphNode, Int32 classScope, String methodName)
   在 ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   在 ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   在 ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   在 ProtoAssociative.Executive.Execute(Int32 codeblock, Int32 entry, Context callContext, EventSink sink)
   在 ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   在 ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   在 ProtoScript.Runners.LiveRunner.Execute()
   在 ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   在 ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   在 ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   在 Dynamo.DSEngine.EngineController.UpdateGraph(Exception& fatalException)

**Comment by ikeough** [comment]
@Benglin Can we close?
