### ISSUE TITLE
element type node in 0.7

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2086]
See differences:
0.6.3
![fillpattern 0 63](https://cloud.githubusercontent.com/assets/4572196/3790616/3e75b8e6-1b10-11e4-9755-e86ee7f29d08.PNG)
0.7.1 daily
![fillpattern 0 7](https://cloud.githubusercontent.com/assets/4572196/3790617/48748868-1b10-11e4-8f50-44e10b46ebf4.PNG)

can we have same behavior in 0.7 than in 0.6.3?

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/46418884-dea78400-c6e9-11e8-9bca-0aff9101b2d5.png)
