### ISSUE TITLE
WISH: searching and creating nodes with double click on workspace

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#209]
It would be great if nodes can be created in the place of double clicking on workspace, instead of in the middle of canvas, (similar to  grasshopper), therefore there are always some nodes in middle of canvas and new node has to be alwayes moved to position and then wired. As well, it would be great, if searching of the nodes can be done in the mouse tooltip.

**Comment by sharadkjaiswal** [comment]
We have in-canvas search option available on right click. Double-click is reserved for creation of code-block.
