### ISSUE TITLE
WISH: custom color of active nodes

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#210]
It would be great if active nodes (orange) color could be customized, Therefore orange is the color of warning, rather symbol of correct wired node. General override dialogue could be extended to custom color per node/group.

**Comment by Racel** [comment]
@ondejcik - I know this is very old, but just curious as to what you want to use this for. Do you still think it is useful since we have groups?

**Comment by ondejcik** [comment]
Hi,
this wish was from old dynamo before design script. There the standard color for nodes was orange and that was very confusing. However color customization wish is still valid. User could choose color of selected, not selected nodes, node with warning or error. Now the main reason behind this would be purely esthetics and user friendlines.  Some people have preference of very spartan environment, while for other users like it in more colors. As well for presentations of dynamo definitions can be better to have different settings, compared to working preset.

**Comment by Racel** [comment]
Thanks @ondejcik. This is helpful. I appreciate you responding back so quickly.

**Comment by andydandy74** [comment]
@ondejcik - I believe you could customize that now. Have a look at this folder:
C:\Program Files\Dynamo\Dynamo Core\{VERSION}\UI\Themes
