### ISSUE TITLE
wall tool problem

### ISSUE THREAD

**Issue by sjmurphy84** [DynamoDS/Dynamo#2127]
When I feed an arc into the wall tool it creates a longer arc. There is a wall connecting at either end at the first end it joins normally without an extension but at the other the arc continues on.
I have tried rebuilding the arc but it creates the same problem. I would guess it is down to how revit tries to join walls. 

I have tried to join the curves inside dynamo and then generate the walls from this prejoined line but the wall tool would accept the closed polycurve input.

Thanks, Siimon

**Comment by ikeough** [comment]
@riteshchandawar @Randy-Ma Was this ever tracked. What's the status?

**Comment by riteshchandawar** [comment]
@ikeough I don't think I have logged any internal tracking issue for this.

**Comment by kronz** [comment]
I can't reproduce this issue in 1.0
