### ISSUE TITLE
Select Family Type node selection resets with addition of new families / family types to file and/or renaming of families / family types existing in file

### ISSUE THREAD

**Issue by BrianFraumeni** [DynamoDS/Dynamo#2130]
Working with verson 0.6.3:

Select Family Type node selection resets with addition of new families / family types to file and/or renaming of families / family types existing in file.

Is there a work around?

Any known python and/or string based family type selection/specification node or definition available?

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
