### ISSUE TITLE
Warning: Failed to obtain this object for 'DesignScriptEntity.Dispose'.

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#2136]
Hi, I get this warning (def still works) in 0.7.1.17276 with Revit 2015 Update Release 3 that says Warning: Failed to obtain this object for 'DesignScriptEntity.Dispose'. Anyone know how to get rid of this?

![image](https://cloud.githubusercontent.com/assets/5300197/3877423/aa0122c0-2165-11e4-9098-71523e4a5d42.png)

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
