### ISSUE TITLE
Solid.UnionAll changed?

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#2162]
The working of Solid.UnionAll seems to have changed to be similar to Solid.Union

We now seem to have to specify one solid and then a list of solids to combine with that solid. 
Earlier, it just combined a list of solids.

It was better in the earlier form.

Regards,
Vikram Subbaiah

**Comment by ikeough** [comment]
Internal task is marked as closed. @vykrum, please re-open if this is still an issue.
