### ISSUE TITLE
DYNAMO 0.7.1序列不包含任何元素

### ISSUE THREAD

**Issue by zhadiqi** [DynamoDS/Dynamo#2183]
Zach Kron 
运行这个文件Dynamo Stadium ，出现错误？
序列不包含任何元素

   在 System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   在 ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, Core core, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   在 ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, Core core, FunctionGroup funcGroup)
   在 ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, Core core)
   在 ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   在 ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   在 ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   在 ProtoAssociative.Executive.Execute(Int32 codeblock, Int32 entry, Context callContext, EventSink sink)
   在 ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   在 ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   在 ProtoScript.Runners.LiveRunner.Execute()
   在 ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   在 ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   在 ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   在 Dynamo.DSEngine.EngineController.UpdateGraph(Exception& fatalException)

-------------------------------------------------------------------------
http://buildz.blogspot.com/2014/01/dynamo-stadium.html

Opening home workspace D:\Autodesk Revit 2015\朱- revit录制教程\2014年\Dynamo Stadium\20140121_Stadium\Stadium.dyn...
Clearing workflow...
00:00:00.0009824 elapsed for loading xml.
Original file 'Stadium.dyn' gets backed up at 'D:\Autodesk Revit 2015\朱- revit录制教程\2014年\Dynamo Stadium\20140121_Stadium\backup\Stadium.dyn.7.backup'
Original file 'Quads from Rectangular Grid.dyf' gets backed up at 'C:\Users\zhu\AppData\Roaming\Dynamo\0.7\packages\Quads from Rectangular Grid\dyf\backup\Quads from Rectangular Grid.dyf.17.backup'
Loading node definition for "Quads from Rectangular Grid" from: C:\Users\zhu\AppData\Roaming\Dynamo\0.7\packages\Quads from Rectangular Grid\dyf\Quads from Rectangular Grid.dyf
00:00:00.7361732 ellapsed for loading nodes.
00:00:00.0327795 ellapsed for loading connectors.
00:00:00.0044127 ellapsed for loading notes.
00:00:03.7399219 ellapsed for loading workspace.
Update graph failed: 序列不包含任何元素
Evaluation completed in 00:00:00.8860160
Evaluation completed in 00:00:00.0005165

**Comment by ke-yu** [comment]
It has been fixed in https://github.com/DynamoDS/Dynamo/pull/2435. Please reopen it if come across same crash again.
