### ISSUE TITLE
0.7-BoundingBox node

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2243]
I have issues with this in 0.7, as I can't achieve to transform a bounding box. I managed to do this in 0.6.3, but node was quite different, as it was using Tranform. I looked on github and didn't find a test file for this in 0.7. anyone from team to provide an example on how to do this?
here's what I have in 0.7: https://drive.google.com/file/d/0BxqX_gXj6OzEWllPckRBeDFoWGs/edit?usp=sharing

my goal (almost achieved in 0.6.3) is to set a correct BBox to create section views from elements like walls.

**Comment by revitj0hnp** [comment]
Any status on getting a bounding box of rotated elements?

**Comment by hlp** [comment]
Hi @revitj0hnp : rotated bounding boxes are still not supported in our underlying geometry kernel, ASM, so it may be a while...

**Comment by revitj0hnp** [comment]
Thank you. Would there be any suggestions how I can get a cuboid from the overall size of a rotated item? Or maybe RevitBounding box to cuboid?

**Comment by hlp** [comment]
If you get the bounding box for a rotated item, it *should* return a correct bounding box, only it will be axis-aligned. Finding the bounding box that is rotated in space to enclose the minimum volume is a bit more tricky: http://en.wikipedia.org/wiki/Minimum_bounding_box_algorithms, and I don't have any direct experience calculating this.

**Comment by revitj0hnp** [comment]
I see.. Perhaps I need to find a better way to subtract my built in casework from my room calcs..
![2015-02-06_12h04_15](https://cloud.githubusercontent.com/assets/10887072/6085586/5acd3688-adf8-11e4-9699-57eba48ac977.png)

**Comment by hlp** [comment]
I see. Could you elaborate a bit more about your problem, and how you're trying to solve it? (My hunch is that might nob be a bounding box issue)

**Comment by revitj0hnp** [comment]
I was trying to get the maximum extents of my casework and create an
extrusion from them to subtract from room area. I misunderstood the
bounding boxes function. I also tried intersection and perimeter curves.
But depending on the complexity of the casework the results are strange.

**Comment by revitj0hnp** [comment]
I would love to be able to get a cuboid from the outermost pieces of an element's geometry

**Comment by hlp** [comment]
Can you not extract out the Revit geometry, and create a bounding box from geometry?

![bbox](https://cloud.githubusercontent.com/assets/289141/6091196/ec3e3f36-ae52-11e4-8fec-6f9acd68d93a.png)

**Comment by revitj0hnp** [comment]
That was my exact glial initially. But some of the geometry was on an
angled wall and the bounding box remains orthogonal.

**Comment by revitj0hnp** [comment]
Stupid phones- I meant to say goal

**Comment by andydandy74** [comment]
@revitj0hnp - The other day I needed a "rotated" bounding box as well. Here's how I solved it.
The key was to basically project all vertices of the geometry on a horizontal plane and find the convex hull of those points. Be aware that this technique will only work for objects that do not have any protruding geometry, though. 
![boundingboxbyconvexhull](https://cloud.githubusercontent.com/assets/3014437/6097156/6a03ba08-afb2-11e4-8906-a03782de9aa6.png)

**Comment by revitj0hnp** [comment]
@andydandy74 thanks a lot man! I am trying it out now, but I worry because the items I am running this on are casework with handles.

**Comment by revitj0hnp** [comment]
So far so good, but it seems to take the convex hull of the entire selection of objects.

**Comment by revitj0hnp** [comment]
@andydandy74 are you able to create a convex hull for each instance of geometry chosen? Like if I select all of my casework on Level one. Can i have that generate the convex hull per instance of casework?

**Comment by andydandy74** [comment]
@revitj0hnp - Of course. You just have to add a bit of logic to process the list of elements correctly, mainly a few List.Map nodes:
![convexhullforlists](https://cloud.githubusercontent.com/assets/3014437/6121741/ea6f1840-b0e8-11e4-8955-cecf07eb5d20.png)

**Comment by revitj0hnp** [comment]
@andydandy74 Thank you so much for your help and your awesome Clockwork nodes man! I was able to get the results I wanted by changing the very end of what you provided

. I basically made a polygon and "thickened" the surface with a list map node.

Not only did you help me out, but you taught me how a list map node works. Thanks again!

-John

![2015-02-10_09h03_03](https://cloud.githubusercontent.com/assets/10887072/6130658/a36e6764-b103-11e4-91d9-34d4d6c571a5.png)

**Comment by kvwxyz** [comment]
is there still an issue with the BoundingBox.ByGeometryCoordinateSystem node? I am inputting a coordinate system (rotating arbitrarily around the z axis) and geometry, but it still seems to just align with the World axis.
![bounding box](https://cloud.githubusercontent.com/assets/13657593/9082577/fdcc7d00-3b9f-11e5-9498-f47df1ce1529.JPG)

**Comment by aparajit-pratap** [comment]
This is tracked in http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7718

**Comment by dbaldacchino** [comment]
Still broken in 0.9.2. There are actually two nodes with the exact same name but different graphic thumbnail. If this isn't getting fixed any time soon, why not pull them please? It's very frustrating for us to try learn how to use a node on our own and then figure out this has been broken for years. Could have saved us valuable time to work on other approaches instead. Thanks.

![csbbindynamo](https://cloud.githubusercontent.com/assets/4656191/14648299/35f13818-0627-11e6-9990-5148e0ab817e.png)

![csbbinrevit](https://cloud.githubusercontent.com/assets/4656191/14648305/3f4a8522-0627-11e6-96f5-3a545e9fff4a.png)

**Comment by kronz** [comment]
@dbaldacchino sorry for the frustration.  Believe it or not, this is in the pipeline for right after 1.0 release.  Didn't quite make the cut this time.

**Comment by dbaldacchino** [comment]
Awesome, thanks @kronz ! Sorry for sounding harsh, but I think issues such as this would help accelerate learning. Thanks for listening :)

**Comment by kronz** [comment]
@dbaldacchino not at all, it's silly we hav not gotten this right or, as you say, removed it until such time.  I think we've been hopeful for a long time that the fix is right around the corner.

**Comment by ejnaren** [comment]
@aparajit-pratap Just to be curious, is this still an issue with the new 1.2 version?

**Comment by aparajit-pratap** [comment]
@ejnaren unfortunately we have not found a quick and easy way to get bounding boxes to align with arbitrary coordinate systems (this is not supported by the geometry kernel we are using). For the time being therefore we have simply removed the BB nodes using CS (since they were not working anyway) so as to not confuse users. We have however kept this issue open in the hope of returning to it later and implementing those nodes correctly, just can't say when right now.

**Comment by ejnaren** [comment]
@aparajit-pratap  Alright. An idea for an intermediate solution: In grasshopper it is possible to optionally specify a plane that the BB node should use when calculating the bounding box.
Say for instance you need a BB around a window instance would it not be possible then to get the reference plane of the window and feed that into the BB node?

**Comment by rbosborne** [comment]
Any progress on the BoundingBox.ByGeometryCoordinateSystem?  I noticed the Node is no longer available in 1.3.1, but the method still works in DesignScript, and it still seems to not be fixed (regardless of Coordinate system the exact same BB oriented to World XYZ is returned).
![image](https://user-images.githubusercontent.com/12659052/29714963-4d65353c-8973-11e7-9890-7e345a64a024.png)

**Comment by aparajit-pratap** [comment]
@rbosborne we are still not providing any support for `BoundingBox.ByGeometryCoordinateSystem`. The method is not meant to be discoverable at the moment. If it is thanks for highlighting it; we'll turn it off for good and let you know if and when we address this.

**Comment by barney2074** [comment]
to add my 2C

If this could be addressed in a future release, I would find it very useful.

andrew

**Comment by mccrone** [comment]
@ejnaren @aparajit-pratap I recently made a node in the Ampersand package that will return a rectangle that describes the minimum bounding box for a planar polyCurve. It will grab the plane from the vertices of the polycurve, so you don't have to supply them. It returns a Rectangle type, not a proper BoundingBox. It's a limited implementation--it needs a better algorithm to find the convex hull in the case of very complex shapes, and it only works for polycurves made of straight lines. So for example, it will work for Nevada with a jagged line for the  Colorado River, but not for California. I hope it helps you get over a hurdle for now.

![minboundingboxes](https://user-images.githubusercontent.com/6430819/32189554-480ab5b6-bd68-11e7-826e-c21801dbb228.PNG)

**Comment by mccrone** [comment]
@ejnaren @aparajit-pratap @kronz @dbaldacchino OK, so I figured out how to do this for complex shapes too. Just uploaded.
![minbb](https://user-images.githubusercontent.com/6430819/32208417-9e8c7170-bdbf-11e7-911d-7e1f834695ad.PNG)

**Comment by aparajit-pratap** [comment]
@mccrone that's awesome! Will check it out.

**Comment by dbaldacchino** [comment]
Thanks a lot Colin!

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2191).

**Comment by vinhaai** [comment]
i got it.

![image](https://github.com/DynamoDS/Dynamo/assets/137771955/3937e399-811b-4668-a86f-34ae0863303c)
