### ISSUE TITLE
Enhancement: preview of Coordinate System.

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2252]
would be cool to have a better visibility when selecting a coordinate system node, gizmo should be highlighted as the point is.

also, it would be great to have the ability of setting background preview as wireframe, to be able to see some CS gizmo.

**Comment by johnpierson** [comment]
Going ahead and closing this as it is for a very old version of Dynamo. If this kind of problem still persists for you in 2.0.x releases, please feel free to open a new issue with updated information.
