### ISSUE TITLE
Set default values to gbXMLSpaceType values cause internal compile error in ProtoCore

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#2255]
I'm trying to set default values for a node to gbXMLSpaceType.NoSpaceType and gbXMLConditionType.NoConditionType. It builds successfully but once I try to import .dll into Dynamo it gives me this error:

*Build error for library: C:\Users\MSadeghipourroudsari\Documents\GitHub\GBSforDynamo\src\GBSforDynamo\bin\GBSforDynamo.dll*
*Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.*

Do you have any idea why this is happening and how can I get it solved?

Here is an example:
```csharp
public static ElementId SetZoneParameters(ElementId ZoneId = null, gbXMLSpaceType spaceType = gbXMLSpaceType.NoSpaceType, gbXMLConditionType conditionType = gbXMLConditionType.NoConditionType)
        {
        return ElementId;
        }
```

cc: @ikeough @pboyer @tatlin

**Comment by ikeough** [comment]
Defaults are now supported as Design Script expressions. See https://github.com/DynamoDS/DynamoSamples/blob/master/src/SampleLibraryZeroTouch/Examples/BasicExample.cs#L122 for an example.
