### ISSUE TITLE
Element.get.ParameterValueByName

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#2275]
![room](https://cloud.githubusercontent.com/assets/6928491/4103186/2d84bd30-314e-11e4-8c3a-bfa32983e2f8.png)
delivering unexpected results
input: 4 rooms
parameter: "Level"
result:
List
  [0] EG RDOK
  [1] 250756
  [2] G1 RDOK
  [3] G1 RDOK

the result for [1] is the level ID
version daily build 29th 
revit 2015

**Comment by kronz** [comment]
Being pursued in 1234
