### ISSUE TITLE
Wish: Descriptions for custom nodes

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#228]
1. It's a good thing that input and output nodes can be renamed, but it would also be very helpful if a description/comment/tooltip could be added, perhaps by right-clicking on the input/output node (similarly to notes). When hovering over the input/output of built-in nodes, I usually get an explanation of what that port does - I think this would be very important for custom nodes as well because they tend to package more complex functionality and therefore might actually need more explaining than many built-in nodes.
2. A general description for the custom node would be great as well. Not sure how that could be done - maybe not in the custom node itself but rather in the workspace that contains it (right-click to edit).

**Comment by brianringley** [comment]
I know this functionality exists now - what's the syntax?

**Comment by mostaphaRoudsari** [comment]
@brianringley in case you're talking about inputs and outputs check [this RP]( https://github.com/DynamoDS/Dynamo/pull/5676#issue-115838264). Here is an example:

![image](https://cloud.githubusercontent.com/assets/2915573/13474180/d827d3f2-e08a-11e5-800a-f968f91272b9.png)


For the node itself you can edit node properties:
![image](https://cloud.githubusercontent.com/assets/2915573/13474153/bcb5adf6-e08a-11e5-80c4-876a811e6dac.png)
