### ISSUE TITLE
daily: python node edition to execute again?

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2289]
working on a python node, I use transaction. it's about creating parts.
first hit on F5. all is fine. delete the Parts, re run. nothing happens.
edit the python node, run: works fine.
idea?
EDIT: happens with selection by Select Model Elements, not with All Element of category.

**Comment by johnpierson** [comment]
Related to https://github.com/DynamoDS/Dynamo/issues/3273, closing this as that post is being tracked.
