### ISSUE TITLE
dynamo模型，导入到revit视图，模型单位显示不对什么原因？

### ISSUE THREAD

**Issue by zhadiqi** [DynamoDS/Dynamo#2296]
dynamo模型，导入到revit视图，模型单位显示不对什么原因？
http://www.revitbbs.net/forum.php?mod=viewthread&tid=13580&fromuid=252

**Comment by ikeough** [comment]
@Benglin @riteshchandawar Can we close this?

**Comment by ke-yu** [comment]
@riteshchandawar I think we can close this.
