### ISSUE TITLE
Point Intersection Error

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/Dynamo#2300]
http://dynamobim.org/forums/topic/point-intersecion-error/

@riteshchandawar did you log this as an error? 

Its still causing my all kinds of problems..

**Comment by johnpierson** [comment]
Hey @MarkThorley, I wanted to see if this was still an issue for you? (Yes, I realize this is an old one, but I wanted to see if this needed prioritized)

**Comment by MarkThorley** [comment]
Cant say I remember haha! Although if it was never fixed it should definitely be prioritised. Discrepancies like this could result in some major issues. I will try and replicate to see if the issue still exists.
