### ISSUE TITLE
Element Type: view types and view templates

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2313]
![image](https://cloud.githubusercontent.com/assets/4572196/4140017/68f79dde-33a0-11e4-8046-3531e51097e8.png)
in 0.6.3 this node returned both view template and view types if I remember well. We should have both or at least view types. daily build from DynamoInstall0.7.1.20140902T2158

**Comment by ikeough** [comment]
This is, in fact, a duplicate. Closing.
