### ISSUE TITLE
Output name of node with single output stays as var

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#2314]
@pboyer per our discussion today. Here is an example of a single return node and as you can see the output name stays as var. This node returns an ElementId.

![image](https://cloud.githubusercontent.com/assets/2915573/4142085/d6cceba2-33b4-11e4-9d35-bc921d98ef5a.png)

**Comment by ikeough** [comment]
@mostaphaRoudsari @aparajit-pratap Closing this as it sounds like a fix has been provided. Please re-open if I'm mistaken.
