### ISSUE TITLE
Surface.PointAtParameter does not work on daily build (0.7.2.17188)

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#2333]
![2014-09-04_21-12-53](https://cloud.githubusercontent.com/assets/5300197/4155165/bbb54978-3467-11e4-93e6-208664dd8140.jpg)
![surface pointatparameter - renameme](https://cloud.githubusercontent.com/assets/5300197/4155180/e98cf062-3467-11e4-9e2d-8302571624fd.jpg)
when selecting a face in revit

**Comment by aparajit-pratap** [comment]
@kronz can we close this one?
