### ISSUE TITLE
Wish: Improvement to Bake geometry into Revit project

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2345]
Hi team. I don't think that the import instance node is an achievement. Imports in project are not allowed in many offices, including mine.
I can do this workflow:
- generate geometry in Dynamo
- import instance in a generic model (adaptive) family
- explode import instance
- load family in project
- schedule, document, make Parts,etc....
  but to manipulate it with dynamo, it's a different graph. and if I update the geometry, it's a long road to go.

Can we have this straight from Dynamo, with a silent family creation and load into project? User should use either mass template, or adaptive template (in fact Point world). Then this family could be placed in project by dynamo, updated, etc...

This is not that hard with Revit API to achieve this, but I don't have yet the skill to implement this in a robust way. I plan to try though, so I share this here.

thanks for your thoughts about this.
![image](https://cloud.githubusercontent.com/assets/4572196/4175698/7961ea4c-35e1-11e4-9b7d-3ee377605153.png)

**Comment by mariamhosman** [comment]
I believe Springs.FamilyInstance.ByGeometry in Spring Nodes does a similar workflow to what jbenoit44 suggested, maybe worth checking

**Comment by johnpierson** [comment]
`FamilyType.ByGeometry` was added in 1.2.3. 
![image](https://user-images.githubusercontent.com/15744724/46418712-938d7100-c6e9-11e8-9efb-f7b122274270.png)
Image Source: https://twitter.com/ZachKron/status/831877063548293121
