### ISSUE TITLE
Download update?

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#2346]
This is probably a very temporary issue, and not really a problem, but every time I start Dynamo (latest stable), an automatic download starts. When it finishes, I should be able to install this update using the green cloud on top right, but that causes a Revit fatal error.

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
