### ISSUE TITLE
Creating actual geometry from dynamo/ vasari problem

### ISSUE THREAD

**Issue by mmekawy** [DynamoDS/Dynamo#2362]
I was trying to follow the video tutorials from learning section on the dynamo website. When in the second lesson "The anatomy of a definition" i was to trying to imitate the instructor in creating a reference point in the Vasari conceptual mass environment. 
The problem is: whenever i try to use the  "Reference point by point" node attached to the "Point by coordinates" node i get nothing in the vasari view-port, and it even crashes sometimes. The exception listed states this
"Autodesk Revit exceptions. Invalidobjectexception: The referenced point is not valid, possibly because it has been deleted from the database, or its creation was undone"
Dynamo : 0.7.2.10961
Vasari: Beta 3.0

![capture](https://cloud.githubusercontent.com/assets/7359807/4188235/9249b3ba-3770-11e4-9852-fd56e3ced53c.JPG)

**Comment by skhan1124** [comment]
Hi, I am having a similar problem doing this exercise, my vasari or revit totally crashes when ever I click the list button on the "ReferencePoint.ByPoint".

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
