### ISSUE TITLE
<returns> XML documentation for custom nodes

### ISSUE THREAD

**Issue by eertugrul** [DynamoDS/Dynamo#2370]
I couldnot make it work XML documentation for return values <returns></return>

If the output is an single item when hover over the mouse of an output, the tool tip shows the type like 'string', 'int', '[]' etc... if multiple outputs, it shows 'var'

![image](https://cloud.githubusercontent.com/assets/4672688/4206911/0e8794c0-3851-11e4-8854-c95a497c5b6a.png)

I observed that same problem persists in other dynamo nodes as well. below is a snapshot from the code. 
![image](https://cloud.githubusercontent.com/assets/4672688/4206967/d9025ac8-3851-11e4-8e82-940f1ec3ff4d.png)

How to add the tool tip or show the correct type for the returns of a dynamo node ?  Thank you
cc: @pboyer @ikeough @Steell

**Comment by mjkkirschner** [comment]
This issue was resolved by the referenced PR in the linked issue.
