### ISSUE TITLE
Migration issue: BuiltInCategories cannot be unwrapped

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2401]
As the title says, unwrapping BuiltInCategory objects seems to have no effect. This makes the Categories pulldown unusable in Python nodes (e.g. no category ID available, which means no filtered element collectors). 
@pboyer (I think you were working on UnwrapElement) - This screws with about 90% of my Revit-based Dynamo workflows. Is it possible to fix this soonish?

**Comment by wynged** [comment]
Thank you all so much for this thread, especially ikeough  for the script solution.  
When I run the script the line actually need to read: 

`builtIn = System.Enum.ToObject(BuiltInCategory, cat.Id)`

I thought I was going crazy.
