### ISSUE TITLE
Error for Simple Point

### ISSUE THREAD

**Issue by ihnilkim** [DynamoDS/Dynamo#2431]
Can anyone help me understand why there is such error when I am doing this simple thing?

This is first tutorial “Getting Started with Dynamo” I am doing and if this is happening then I wonder how much more error there are later as I go on
![error01](https://cloud.githubusercontent.com/assets/8793938/4288861/562ca082-3daf-11e4-8f8d-4c6ea787d05c.jpg)

**Comment by ikeough** [comment]
@ihnilkim Can you please try with a newer build of Dynamo and let us know if you're still seeing this issue. I'm pretty sure we've got this fixed :)
