### ISSUE TITLE
FamilyInstance.Location

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#2447]
Using daily build, it seems as the FamilyInstance.Location node is not working and is behaving like the StructuralFraming.Location node. I get " Warning: StructuralFraming.get_Location operation failed. 
The location of the structural element is not a valid curve!
The node is used on multiple structural foundations from Revit.

**Comment by LianweiHuang** [comment]
It seems the structural foundation instance in question is actually a family instance in Revit and it is wrapped as structural framing object in Dynamo. This is OK.

But the structural foundation is actually point based (returns LocationPoint in Revit API) while in Dynamo, all structural framing objects/instances are assumed to be curve-based. So exception throws when casting a LocationPoint to LocationCurve.

**Comment by johnpierson** [comment]
Pretty sure this is resolved with the addition of Element.GetLocation. Feel free to reopen on the [DynamoRevit Issues](https://github.com/DynamoDS/DynamoRevit/issues) page.
