### ISSUE TITLE
Dynamo Sandbox now targets ASM 220 instead of 219 if available

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#2448]
I found last night that Dynamo Sandbox now targets ASM 220 (commit that changed this was taking 2015 branch ASM preloading logic 2 days ago) and unfolding code has lots of strange failures running on this version of ASM.  I have verified on 2 machines, but I will reinstall revit 2015 incase of corrupted install or some other cause.

failures in my unit tests (no Dynamo, running on 220) and Dynamo include:
1): polygon.by points has an illegal wire exception… something like this from only a few points.

2) sometimes tests just stop executing but the CPU still is using 50-70% of cycles and doing nothing it seems, Nunit has to be forced to close. If I’m debugging no exception is thrown.

3) After successful tests Nunit agent crashes.

4) rarely I get an error creating bool,  inconsistent  vert vert exception, when intersecting 2 surfaces, poly surfaces have been removed from this code.

5) **unfortunately all of these seem intermittent.**

The most worrying is the execution just stopping and hanging as I can't debug it.  I'm curious if anyone else has repro strange behavior on sandbox after this commit.

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
