### ISSUE TITLE
Need a method to convert Revit geometry elements to Dynamo entities

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2449]
Maybe I have overlooked this, but there doesn't seem to be a method for converting Revit geometry elements to Dynamo entities. Use case:
Let's say I have a Python script that extracts a specific face, edge or line from a given Revit element (which I do). How do I make a Dynamo face or curve from that?

**Comment by joopzuur** [comment]
Hi Peter,

is there an equivalent to construct an edge (Revit curve) as a reference as well?

tnx Joop
