### ISSUE TITLE
Wish: Make ToDSType() more forgiving & versatile

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2460]
1. In many cases, ToDSType() will not be able to convert a Revit element to a Dynamo element (because there is no Dynamo equivalent to that particular Revit element type). When dealing with mixed sets of elements, this becomes a bit of pain, because it requires exception handling in the Python script. It would be much simpler if ToDSType() would return a Dynamo element type where possible and the original element type if there is no corresponding Dynamo element type.
2. In order to keep scripts reusable it would be nice to be able to apply this method to the output once, which is generally a list of items (that would then get processed recursively, just like with the UnwrapElement() method) instead of calling it for each individual element.

**Comment by andydandy74** [comment]
Could somebody **please** alter ToDSType in such a way that it either converts an object to the corresponding Design Script type or - if that fails - just returns the original object without throwing an exception? Seems I am not the only one that is affected by this: http://dynamobim.com/forums/topic/id-string-to-elements

**Comment by Steell** [comment]
For now, you can use this function in your own python scripts:

```python
def maybeToDSType(element):
    try:
        return element.ToDSType()
    except:
        return element
```

**Comment by andydandy74** [comment]
Thanks, but I have a three digit number of Python scripts. Somehow it felt easier just getting rid of it entirely and hoping that the auto-marshaling will take care of it. Yes, you may call me lazy now. ;-)

**Comment by andydandy74** [comment]
```Document``` objects also do not convert. It would really help if they did, e.g. when handling linked documents. In Dynamo, the data type is ```Revit.Application.Document``` while a when accessing the Revit API in a Python node it is ```Autodesk.Revit.DB.Document``` with no way to convert between the two.

**Comment by aparajit-pratap** [comment]
@monikaprabhu could you review @andydandy74 's request above and create a tracking task for it?

**Comment by andydandy74** [comment]
Since this has become quite a long thread I think a quick summary would help:
1. ```ToDSType()``` should return a Dynamo element type where possible and the original element type if there is no corresponding Dynamo element type.
2. ```ToDSType()``` should be able to process elements recursively like ```UnwrapElement()```
3. ```ToDSType()``` should be able to convert Revit ```Category``` and ```Document``` objects. (And so should the auto-marshaling...) Surely there are more object types to consider but I definitely got stuck repeatedly on these two in the past.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2189).
