### ISSUE TITLE
Wish: Dynamo should remember last tab

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2484]
On closing the tab of a custom node while having multiple dyfs open in several tabs, Dynamo will always take me back to the main definition not to the last tab I was working in before. It would be nice if Dynamo could remember the order in which we access the tabs (or the hierarchy of the opened nodes).
Use case:
- Edit a custom node, that has other custom nodes nested in it. 
- Edit one of the nested custom nodes.
- Close it - now I'd like to be taken back to the parent node that I was working on previously. Instead I end up in the DYN tab.

**Comment by Racel** [comment]
This would be nice to have, but I do not think we will have the bandwidth to take this on any time soon. Closing for now, but will consider for the next generation Dynamo UI.
