### ISSUE TITLE
Element.Curves returns wrong curves.

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#2487]
to my experience his node is broken, curves are listed, but they all have a weird offset and are at the wrong place in background preview. they also have incorrect start and end points values.

I've tested this in getting curves from AC.

**Comment by dbaldacchino** [comment]
Hi, what specific elements does this node extract curves from? I tried passing it Walls and Roofs for example, but it always returns an empty list. Is it supposed to work with sketch-based elements only, or also with 2-point placement objects as well? Thanks.
