### ISSUE TITLE
Add ability to get parameter values by GUID and BuiltInParameter name.

### ISSUE THREAD

**Issue by dannypolkinhorn** [DynamoDS/Dynamo#2530]
GetParameterValueByName isn't safe in situations where the parameter names are the same, curtain Grids for example, or for localization differences.  Revit API documentation suggests using the BuiltInParameter name or a shared parameter GUID to ensure that you have selected the exact parameter you expect.
Use case: http://dynamobim.org/forums/topic/curtain-wall-instance-properties/
Api Documentation references:
  Parameters: http://help.autodesk.com/view/RVT/2015/ENU/?guid=GUID-E0F304BC-07B8-461E-8FB2-234106951B0A
  BuiltInParameter: http://help.autodesk.com/view/RVT/2015/ENU/?guid=GUID-C0D9C62F-1BEB-412E-B5B4-E70E2EF4F378

**Comment by ksobon** [comment]
@dannypolkinhorn if you download archi-lab_Grimshaw package you will find three nodes that extend this exact workflow. Here's an example: 

![capture](https://cloud.githubusercontent.com/assets/529781/10382652/12c33150-6df4-11e5-916b-1b81ac91af22.PNG)

Please close this issue if this addresses your question. 

Thank you,

**Comment by dannypolkinhorn** [comment]
Hi Konrad, yes, I think this addresses one of the two parameter options, specifically getting the BuiltInParameter name.  I think the forum post mentioned above would need a shared parameter GUID to resolve the issue.  So, even though GUIDs aren't very user friendly, I would still like to see them added.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2188).
