### ISSUE TITLE
Wish:  Preview Mesh in Revit 2015

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#2541]
Hey all,
I'm taking the new version of Dynamo for a spin with 2015.  I'm liking where the 2015 preview feature is headed.    I haven't tested all geometries here yet, but I am noticing that it does not preview the "Mesh" geometry type.  Is there a way to do this?

-Nate

**Comment by johnpierson** [comment]
This is still a functionality that is missing in Revit 2019 + Dynamo 2.0.1. Adding new labels to prioritize.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2187).
