### ISSUE TITLE
Wish:  Revit 2015 Preview Geometry to "Cut"

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#2542]
It would blow minds if Revit 2015 Dynamo Previews would cut (via section box, in plan, etc...  pretty please???  :)

![image](https://cloud.githubusercontent.com/assets/1890663/4424955/7a296478-45a4-11e4-9aa3-af50462850d4.png)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2186).
