### ISSUE TITLE
Code Block daily build 20140926.12:39

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#2546]
iam using daily build 20140926.12:39
code block:
Point.ByCoordinates(x,y,z) or Point.ByCoordinates(0,0,0)

resulting in 
Warning: Dereferencing a non-pointer.

**Comment by ikeough** [comment]
@epeter- I believe this issue has been resolved by now. Please re-open if the issue persists with a newer build of Dynamo.
