### ISSUE TITLE
Normals for Adaptive Components

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#255]
Placing an AC by XYZs is great if the AC's placement points are not set to inherit their host object's orientation. Currently, when placing an AC (by XYZs) through Dynamo its placement points' Z axes will always be vertical in the family/project environment. 
There should be a node that allows for passing a set of normals along with the set of XYZs so AC placement points can have different orientations.

**Comment by simonlebon01** [comment]
Hello,
I am interested in this node. Does anyone know where to find it?
