### ISSUE TITLE
Possible bug in Curve.ParameterAtPoint

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#2559]
I have observed that Curve.ParameterAtPoint is not working in some specific cases. For example, if you have a polycurve resulting of joining and arc and straight lines, when you have a point in the arc segment ParameterAtPoint is not working.
![01](https://cloud.githubusercontent.com/assets/6596042/4438066/120b7698-47a6-11e4-9dd5-df63c5daf895.jpg)
If the point is in the straight line segment, everything is fine
![02](https://cloud.githubusercontent.com/assets/6596042/4438069/19c549d6-47a6-11e4-93ea-bcbc524ee2a3.jpg)
This possible bug is more or less recent, because until a couple of weeks ago I never had any problem with this. This is with the build “DynamoInstall0.7.2.20140918T1540.exe”
![03](https://cloud.githubusercontent.com/assets/6596042/4438070/1fdb3b1e-47a6-11e4-8396-5b4f5aa1c742.jpg)
You can find the test file here 
https://www.dropbox.com/s/skwq9py6y2a7hzm/test_ParameterAtPoint.dyn?dl=0

**Comment by ikeough** [comment]
@riteshchandawar Was this ever fixed?

**Comment by aparajit-pratap** [comment]
This is fixed. @eproca please let us know if you continue to see bugs. Closing this for now.
