### ISSUE TITLE
Daily Build 0.7.2.37209  Code Block Color.ByARGB

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#2580]
Codeblock feed from another Code Block with 4 integer values like 
0;
10;
255;
55;

error:
Warning: Dereferencing a non-pointer.

**Comment by ikeough** [comment]
@epeter- A screen shot perhaps?

**Comment by ke-yu** [comment]
@epeter- Close this issue as it is not reproducible on 1.1. If you have reproducible steps, please re-open this issue.
