### ISSUE TITLE
Daily Build 0.7.2.37209 Code Block Point.ByCoordinates still bugy

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#2581]
my code:
aX=pts1.X;
aY=pts1.Y;
bX=pts2.X;
bY=pts2.Y;
C=Point.ByCoordinates((aX+bX)/2,(aY+bY)/2,0);

aX,aY,bX,bY = result as expected.
C = null

**Comment by ke-yu** [comment]
@epeter- Close it now. If you have reproducible steps, please re-open the issue.
