### ISSUE TITLE
Dynamo 0.7.2 does not start in Revit 2015 R2 from German Revit templates

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2593]
I have trouble getting Dynamo 0.7.2 (the official release, not a daily build) to start in Revit 2015 R2 (Build: 20140606_1530(x64)) on top of fresh Revit project files created from the default German architectural template. The construction and structural templates seem affected as well. Only the MEP template works.
The Dynamo button in the ribbon just greys out, but nothing happens.
It does work with all of the sample files that ship with Revit and Dynamo respectively, though.

**Comment by sonderbaer** [comment]
Had the same Problem with the BIMhelpertools from VV-Software - Solved by installing Dynamo 7.5
