### ISSUE TITLE
Vector.AngleBetween returns 0 for reversed vectors

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#2612]
Since vectors have direction I expect the result to be 180 and not 0.

![image](https://cloud.githubusercontent.com/assets/2915573/4507441/8bb08a06-4b0c-11e4-8d7a-900691c8c576.png)

**Comment by dbaldacchino** [comment]
I used this node successfully under 0.8.0 back last year or so, but now under 0.9.1 it's not working correctly (maybe it was already broken under 0.9.0, not sure). Here's the problem:

![vector anglebetween](https://cloud.githubusercontent.com/assets/4656191/13508782/11714a4e-e14e-11e5-95be-01cd25e19576.png)

Notice how if a lisst is supplied, the output doesn't make much sense (after experimenting a bit, it seems to always return 0 as the first result). If you supply just a vector value, it computes it just fine. @ikeough is this a known issue? I couldn't find anything in the issues list regarding this, thanks.

**Comment by dbaldacchino** [comment]
Another thing I'm noticing with respect to the results is the precision. The inputs are derived from Revit geometry (a wall and a duct in this case) but they are both snapped and aligned properly to the X and Y axes respectively - there are no "slightly off axis" warnings either. Thanks.

![vector anglebetween2](https://cloud.githubusercontent.com/assets/4656191/13509259/26be0674-e150-11e5-9bc4-be5c0d1bb84a.png)

**Comment by jnealb** [comment]
@dbaldacchino Thank you Dave, you are correct. This is tracked with MAGN-9648.

**Comment by mostaphaRoudsari** [comment]
This is fixed in version 1 based on release notes.
