### ISSUE TITLE
G1 Curve discontinuity when joining curves

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#2643]
I tried to make a PolyCurve.ByJoinedCurves() and was hit with a G1 discontinuity error. I am curious as to why its preventing me from joining curves and what can i do to stop that from happening. Ideas? 
ps. I would post my files here but it seems like only images are supported. :-(

**Comment by hlp** [comment]
Hi all, it looks like I merged in a fix for this 25 days ago. Sorry for not giving you a heads up sooner.

**Comment by aparajit-pratap** [comment]
@ksobon could you verify if this issue has been fixed? Thanks.

**Comment by ksobon** [comment]
I cannot get the G1 discontinuity error so its seems like its fixed. I am having other geometry issues in its stead, so i will just open a new issue when I know more. Thank you,
