### ISSUE TITLE
Possible bug when a var is assigned to a collection index 

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#2649]
When in a points collection of rank 2, you assign a var to the second index, you are getting an error
![02](https://cloud.githubusercontent.com/assets/6596042/4572217/31fac348-4f83-11e4-9bb6-4ee1118912d1.jpg)
Var assigned to the first index seem ok
![03](https://cloud.githubusercontent.com/assets/6596042/4572226/4608bf0c-4f83-11e4-8445-4766ac150322.jpg)

**Comment by ikeough** [comment]
The internal issue is resolved.
