### ISSUE TITLE
Default arguments for custom nodes

### ISSUE THREAD

**Issue by mingzhao240** [DynamoDS/Dynamo#267]
![zud72amhk xsadoe exl8u](https://f.cloud.github.com/assets/4797778/772763/37a09954-e91c-11e2-8531-ee43909929e8.jpg)
This is in the custom node environment, I added more input, but sometimes, I don't want to in the actual battery diagram, each connected to this needs ，I maybe set some default values,

question:if there are like this order to judge whether the input valueses

**Comment by sharadkjaiswal** [comment]
Latest Dynamo already provides a way to annotate default values for the custom node.
