### ISSUE TITLE
Dictionaries

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#2670]
Is there a special way that I am not aware for creating dictionaries in custom Python nodes? This throws an error:

#messing with dictionaries
names = ["Nick", "Alice", "Kitty"]
rating = [1, 2, 3]

dictionary_test = dict(zip(names, rating))

#Assign your output to the OUT variable
OUT = dictionary_test

![untitled-1](https://cloud.githubusercontent.com/assets/529781/4595880/633496bc-509d-11e4-85c7-19dceb9647a0.jpg)

**Comment by ikeough** [comment]
The internal issue has been closed. 

I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
