### ISSUE TITLE
Make Dynamo node give a warning without throwing an exception

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#2671]
Is there anyway to make a zero-touch node show a warning without throwing an exception. I want to give a warning to the user but still return the results. Thanks.

**Comment by ksobon** [comment]
@mostaphaRoudsari I am not sure if that's what you are looking for, but I think that kind of solution is already present in Dynamo Zero Touch. Have a look: 

```C#
/// <summary>
        ///     Select Element by Element Id Integer.
        /// </summary>
        /// <param name="id">Element Id as Integer.</param>
        /// <returns name="Element">Element in model.</returns>
        /// <search>id, element, select</search>
        public static Element GetById(int id)
        {
            RVT.Document doc = DocumentManager.Instance.CurrentDBDocument;
            RVT.ElementId rId = new RVT.ElementId(id);
            try
            {
                Element e = doc.GetElement(rId).ToDSType(true);
                return e;
            }
            catch (Exception) { throw new Exception("Element with given Id could not be found."); }
        }
```

This results in something like this when user provides an element id reference to non existing element:

![untitled-1](https://cloud.githubusercontent.com/assets/529781/14233610/65be4d44-f99b-11e5-9733-6d548350d920.jpg)

Is that what you are looking for?

**Comment by ikeough** [comment]
@mostaphaRoudsari I'm closing, because @ksobon's solution is what we'd expect developers to do. Please let me know if you were looking for something more.

**Comment by ksobon** [comment]
I actually believe that @mostaphaRoudsari wants to have ability to set the node to yellow/warning state based on input from user. Let's consider a situation where user asks you to perform an action by providing an incorrect input, but developer has anticipated that and has a default value ready to substitute for the input. You want to set the node to warning state to let the user know he provided a wrong input, but you also want the node to execute the default value. 

What I have shown above, will not allow for that.

**Comment by riteshchandawar** [comment]
@ksobon @mostaphaRoudsari  This was the PR which was merged https://github.com/DynamoDS/Dynamo/pull/3950 to fix this issue. Can you please try the approach which is mentioned in the above PR. 

- Ritesh

**Comment by mostaphaRoudsari** [comment]
Thanks @ksobon! @riteshchandawar that's exactly what I was looking for. Thanks!
