### ISSUE TITLE
Flipping normals of trimmed surfaces loses trimming curves

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#2677]
@pboyer 
![screen shot 2014-10-12 at 12 15 22 am](https://cloud.githubusercontent.com/assets/508936/4605007/80dd0594-51c6-11e4-8d2b-09e21aee88fb.png)
![screen shot 2014-10-12 at 12 15 12 am](https://cloud.githubusercontent.com/assets/508936/4605008/80ddb11a-51c6-11e4-8621-b843c3d881fb.png)

original issue appears to be that some imported mass faces have incorrect normals(possibly) attempting to flip these faces produces untrimmed surfaces... :(

**Comment by ikeough** [comment]
@mjkkirschner Still an issue?

**Comment by Amoursol** [comment]
This has now been updated inside of Dynamo 2.6.
