### ISSUE TITLE
Combine nodes / list lace nodes pass partially applied functions when called on lists of 1

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#2678]
Combine on a list of 1 item will pass a partially applied function, this exposes a protocore.stackvalue type as of now.

Sometimes it is not known at run that you will get a single value in a list, why does combine behave differently on a list of 2 items than a list of 1?  This seems like a bug.

To clarify, suppose you combine(apply) some function to 2 lists of 1 item each.  Combine will not apply the function.  If the lists both have 2 items, it will succeed.

**Comment by ikeough** [comment]
@mjkkirschner Still an issue?
