### ISSUE TITLE
Wish: Let captured image name default to graph name

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2695]
This is just a minor thing, but I constantly find myself renaming the screen captures shot with Dynamo. I guess "Capture.png" is okay, but I think it would make a lot more sense if the default name would be the same as that of the graph I am taking a screenshot of.

**Comment by Racel** [comment]
I also think this is an easy minor fix that we can squeeze in to our sprints. Assigning to me and UX Love for now. Will try to address soon.

**Comment by johnpierson** [comment]
Tracked internally as [QNTM-5920](https://jira.autodesk.com/browse/QNTM-5920)
