### ISSUE TITLE
mapping getItemAtIndex over to retrieve nested custom lists returns empty list :(

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#2768]
![screen shot 2014-10-17 at 2 23 09 pm](https://cloud.githubusercontent.com/assets/508936/4683861/c62620b4-562a-11e4-8f3f-b36f98fc7bd9.png)

this is problematic

**Comment by ikeough** [comment]
@mjkkirschner Is this still an open issue?

**Comment by mjkkirschner** [comment]
this is fixed, yay!
