### ISSUE TITLE
codeblock make ....geometry.rotate

### ISSUE THREAD

**Issue by minismore** [DynamoDS/Dynamo#2776]
hello, 

simple question. i've been repeating this comand over. can you help me tidy up this into a single codeblock? 
many thanks! 

![question_codescript geo rotate](https://cloud.githubusercontent.com/assets/9298401/4691572/9f4877ae-5723-11e4-911e-4e8ed275f478.PNG)

**Comment by ikeough** [comment]
I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.
