### ISSUE TITLE
Wishlist: shortcut to mark text as comment in CBN

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#2842]
Now that we have this cool autocomplete in CBN, it would be great to have a shortcut to mark and unmark as comment. If I remember correctly they were ctr+k and ctr+u in Autocad DS Studio. 

Maybe these shortcuts exist already and I am just not aware of the correct keys....

**Comment by Racel** [comment]
We will not be working on this for the next release, but we anticipate improvements on CBNs in the next generation of Dynamo. Closing this for now.
