### ISSUE TITLE
Instance parameter numerical input is imperfect

### ISSUE THREAD

**Issue by mingzhao240** [DynamoDS/Dynamo#285]
When I want to enter in “材质”, namely material, want to enter the name of the corresponding, there is no way to correct the input (my material name is "3')
![jupq36tv0hq 0y7gf j092c](https://f.cloud.github.com/assets/4797778/792130/fde966d2-eb6e-11e2-825f-2ff08465d19a.jpg)

**Comment by kronz** [comment]
Obsolete
