### ISSUE TITLE
Sending List into DS function

### ISSUE THREAD

**Issue by luxliber** [DynamoDS/Dynamo#2893]
Hello!

Is there possibility to pass List into DS functions?
For example I have 2-level list ( {{1,2,1},{3,4,1}} ) and I want to make some calculations with inner lists (for example - "Sum").
If I pass list to DS Function then it processes each element of list and sublist (function get only each end-level element).
If I pass list to some node (like Math.Sum) then node gets only sublists

see example pic:
![image](https://cloud.githubusercontent.com/assets/9447605/4826688/b835218e-5f72-11e4-9f59-1d555b07e2dd.png)

**Comment by ikeough** [comment]
The internal issue is closed.
