### ISSUE TITLE
Best practice to visualize analysis results with Dynamo

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#2923]
@ksobon and I are trying to bring the results of the analysis from a 3rd party application into Revit using Dynamo.

The input is a colored mesh. There is a value assigned to each mesh vertices/mesh Face, so we can extract the values in different ways. Having the values and the points what is the best practice to visualize the results using Dynamo?

@holyjewsus I guess you are the one who knows the most about this! I tried to find how you are doing it for Daylighting nodes but I couldn't really find the code. Thanks!

**Comment by mdengusiak** [comment]
Hi is there any work done in this area?
