### ISSUE TITLE
Select divided surface familes. Can't select surface?

### ISSUE THREAD

**Issue by MariaVallentin** [DynamoDS/Dynamo#2926]
I have Revit 2015 and Dynamo 0.7.2 and when I use 'Select divided surface families' I can't pick anything at all? i have created a mass box where 4 of the sides are divided and have a custom rectangle on in the divided parts. The custom rectangle is a componemt with 4 constrains.
Is there a trick to select the 4 divided surfaces?

![sd](https://cloud.githubusercontent.com/assets/9477305/4857694/de9d90b0-60d3-11e4-9f33-8a4a7d56e1b9.PNG)

**Comment by ikeough** [comment]
@MariaVallentin I'm closing this issue as out of date. I apologize for the delay in responding. If you're still experiencing this issue in a newer build, please re-open.

You can also try posting a question on the dynamo [forum](http://dynamobim.org/forums/forum/dyn/)
