### ISSUE TITLE
Second instance of function fails

### ISSUE THREAD

**Issue by testingwaters** [DynamoDS/Dynamo#2930]
Dynamo version: 0.7.2.2921
DynamoInstall0.7.2.20141026T1600.exe

When a function is called for the second time it does not work. This is the case even if the variables used are the exact same as in the instance where it worked

The file is available at https://www.dropbox.com/s/poow8idn9dsx6y9/20141031-1.dyn?dl=0

![20141031-error](https://cloud.githubusercontent.com/assets/5621624/4859717/bd8cf3e2-60ed-11e4-9e5c-bfa14f7fd188.jpg)

Regards,
Vikram Subbaiah

**Comment by jnealb** [comment]
@testingwaters @RodRecker @kronz @sharadkjaiswal @junmendoza @monikaprabhu Closing this, as resolved with RC 7.5.

**Comment by testingwaters** [comment]
Neal,

Just realized that I hadn't replied to your email. Apologies.
I haven't encountered the same problem in the recent past.
Thanks.

Regards,
Vikram Subbaiah

**Comment by jnealb** [comment]
Thanks for your prompt update Vikram,

Best,

Neal
