### ISSUE TITLE
Wish: Better preview control/overview

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2937]
Hi guys, this item is user feedback from the labs and classes held at RTC Europe this week.
Users liked the fact that they could turn individual node previews on/off, but remarked on the difficulties of actually tracking which node currently has which preview setting - especially in large graphs. One suggestion was to add a settingto the view menu that would allow highlighting nodes according to their preview status (on/off).

**Comment by ikeough** [comment]
@riteshchandawar I believe someone is tackling something like this in the recharge.

**Comment by Racel** [comment]
We have addressed this already by having a blue-grey tint over nodes that are hidden from preview. Closing
