### ISSUE TITLE
SAT file that crashes Dynamo

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#2974]
Importing a SAT file with a 3d spline exported  from Inventor 2014 crashes Dynamo (daily builds of 20141031 and 20141104 tested).

The "problematic" SAT file:
https://www.dropbox.com/s/m8fzlsz93l6j5ho/3D_Spline.sat

Note: I have imported a lot of different SAT files in Dynamo. Some of them with really weird solid/surface geometry. Many with several 3d splines. No issues at all until this file

**Comment by aparajit-pratap** [comment]
Not reproducible. Closing for now. Please reopen if there are still issues with details. Thanks!
