### ISSUE TITLE
FamilyInstance.Location

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#3013]
This node still have some issues:
1. If you feed a adaptive one-point family into it, it reports the location of the intersection of the reference planes in the family, not the adaptive point. 
2. If you feed the node a structural foundation, column or component, it still gets a error message: "Warning: StructuralFraming.get_Location operation failed. 
The location of the structural element is not a valid curve!"

For beams it works perfect, returning even the vector.

**Comment by johnpierson** [comment]
Closing this as it has been a while.
Also, it seems both of these issues were most likely resolved with addition of, `AdaptiveComponent.Locations` and `Element.GetLocation`.

If this is still an issue for you, feel free to reopen on the [Revit Issues](https://github.com/DynamoDS/DynamoRevit/issues) page.
