### ISSUE TITLE
Metric multiplier I want to work in feet

### ISSUE THREAD

**Issue by damionc** [DynamoDS/Dynamo#3070]
Dynamo is multiplying all values converting them to meters in my Revit file.  Unlike most people I am working in feet and would like dynamo to produce results without the multiplier as shown in the attached image.  This result is the opposite of everything I am reading about dynamo so what am I missing?

Please explain how I can get rid of this multiplier.

![dynamo multiplying values to metric](https://cloud.githubusercontent.com/assets/9722463/5031520/446a9784-6b25-11e4-8b16-0d64db16b048.JPG)

**Comment by ikeough** [comment]
Units have been deprecated. All units are now interpreted as being in the unit system set in Revit.
