### ISSUE TITLE
Whatever happend to Perform All?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3071]
Perform All was a fantastic node in that it allowed us to put (seemingly) unrelated parts of a graph into sequence. Now it's deprecated. Is there any other node that can perform unrelated tasks in sequence? I was thinking maybe Compose Function, but it seems to be a slightly different animal.

**Comment by DanRumery** [comment]
Can we get this node (or similar) back into dynamo? Some of the File and Excel nodes in particular are side-effecting and hence it's critical to sequence them for ensure well-defined behavior. The Compose node can only compose single-parameter functions and creating a custom node doesn't really alleviate that problem. In Haskell these kinds of operations would be wrapped up in a monad data type. Perhaps  some kind of Monad (or Arrow?) metaphor could be provided in the interface to make it easier to compose these kinds of nodes?

**Comment by andydandy74** [comment]
Can be done now using Clockwork's Passthrough node
