### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by schizo2000** [DynamoDS/Dynamo#3080]
I have quite a lot of problems with rendering as an analysis tool. even the sky model fails. I guess I do it right, but I am not sure.
Is anybody able to help?

![daylighting render](https://cloud.githubusercontent.com/assets/9527960/5042052/31198446-6b94-11e4-9433-7b41bed11b3f.jpg)
![image render](https://cloud.githubusercontent.com/assets/9527960/5042053/311a4f84-6b94-11e4-943b-41eb84b2ea19.jpg)
![sky model](https://cloud.githubusercontent.com/assets/9527960/5042051/3119142a-6b94-11e4-8cd6-ef5a3e34cfd4.jpg)

**Comment by ikeough** [comment]
@jnealb @vasshaug I'm closing this one because its pretty old. Feel free to re-open if this discussion should still be active.
