### ISSUE TITLE
Wish: Search Nodes and Notes in Workspace

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#309]
Workspaces can get pretty large. A way to search a particular node or text node in the workspace and zoom to it would be very useful. A list of found nodes & text would be displayed and the user could cycle through all of them until the part of the map they are looking for is found.

**Comment by smangarole** [comment]
@Racel - This needs your input. Can you please comment/update?
Ping @kronz.

**Comment by Racel** [comment]
@smangarole - This is already in the backlog. We started this task in the new Web UI, and will return to it in the upcoming sprints.

There are probably several issues filed related to this. Please leave one of them open and just reference the other closed tasks, if possible.

**Comment by ramramps** [comment]
Closing this. Tracked in this issue : https://github.com/DynamoDS/Dynamo/issues/7481
