### ISSUE TITLE
Wish: Grid with IDs to improve navigation/graph organization

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#310]
When writing code, one has to be organized in structuring it properly to make it easy to maintain (knowing where to find certain routines is important). Usually this is achieved through commenting but you're typically dealing with a linear list of lines that you scroll through or search for or mark in the IDE so automatic execution pauses to help in debugging.

In a visual script, your "code" is a combination of a) left to right; b) top to bottom. Thinking long term and how I could go back through my notes to maintain my graphs, especially if trying to train someone, I would need a simple way to find what I'm looking for. So imagine the top/bottom and left/right of the grid is numbered and lettered like an Excel spreadsheet: now I can "address" my notes (ex: Used node XXXX at 13H to do YYYY). Small graphs are one thing, but these things can sprawl (kinda like Houston!). A way to get organized and find what you want is very important I think, and also woks in conjunction with #309. This is how we organize and reference details on drawing sets (some actually also include numbers and letters along the sides of their titleblocks for this exact purpose), so the precedent is related and works pretty good.

![grid with ids](https://f.cloud.github.com/assets/4656191/867243/56152f80-f6e1-11e2-8988-2b1e136f17b8.jpg)

**Comment by ikeough** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
