### ISSUE TITLE
Dictionary issue

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3100]
Has something changed regarding the way dictionaries are treated compared to 0.6.3?
I am trying to migrate some Python code to 0.7 which - since there's no interaction whatsoever with the Revit API - in theory should not need any massaging at all. Instead I get this warning:

```
Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
'string' does not contain a definition for 'Key'
```

@holyjewsus - I know you've been working with Python dictionaries as well. Any thoughts?
File is here:
https://github.com/CAAD-RWTH/ClockworkForDynamo/blob/master/issues/3100_Python_dictionaries.dyn

**Comment by ikeough** [comment]
@mjkkirschner still an issue?

**Comment by arif-hanif** [comment]
this is still an issue

**Comment by epeter-** [comment]
still an issue!!!

**Comment by adambear82** [comment]
this is stopping me from using 'attrib' in 'xml.etree.ElementTree' :disappointed:

**Comment by johnpierson** [comment]
I believe this has been addressed in this PR https://github.com/DynamoDS/Dynamo/pull/9296
