### ISSUE TITLE
Wish: Sheet.ExportAsImage

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#3104]
Is this possible? I want to iterate through multiple design options, and visualize them in a number of ways by collecting plans, orthos, perspectives, schedules, etc on sheets.

**Comment by ksobon** [comment]
That's exactly what this does: 

http://archi-lab.net/image-exporter-for-dynamo/

![capture](https://cloud.githubusercontent.com/assets/529781/10327614/4d351070-6c77-11e5-9f41-7b877798989d.PNG)

**Comment by ksobon** [comment]
@ikeough @vasshaug Can we close this issue? Thank you
