### ISSUE TITLE
Conditions in CBNs don't process lists

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3106]
...well, at least not as expected. ;-)
![unbenannt](https://cloud.githubusercontent.com/assets/3014437/5060778/5d902686-6d6c-11e4-9893-30c062fe33ae.PNG)
Expected result:
```
[0] 2.000
[1] Empty List
```
Am I doing anything wrong, does it just not work like this or is it a bug?

**Comment by andydandy74** [comment]
While the originally described issue has been solved, replication seems to have some issues with mixed inputs (list vs. single item), especially when ```List.Empty``` is involved:
![conditionallistprocessing](https://cloud.githubusercontent.com/assets/3014437/11458334/f9bd16e2-96bd-11e5-9c38-f8cdf40905af.png)

**Comment by ke-yu** [comment]
@andydandy74 , for the case
```
cond = {true, false};
vs = {1, 2};
r = cond ? vs : List.Empty;
```
As the third expression (false expression) is a list as well, here it uses shortest lacing,and as `count(List.Empty() == 0`, the whole expression returns an empty list.

The other way is to use longest lacing:
```
r = cond<1L> ? vs<1L> : List.Empty<1L>;
```

But it is a defect that replication guide doesn't work in inline condition. @monikaprabhu , please log a defect.

**Comment by andydandy74** [comment]
@ke-yu - That's a neat trick, I didn't know you could specify Longest Lacing with replication guides as well.
This ought to be in the Dynamo Primer. CC @mccrone

**Comment by ke-yu** [comment]
@andydandy74 just check the code. Seems if there is a parameter which is empty list, the result is already an empty list. @lukechurch  could you please confirm that?
