### ISSUE TITLE
Design Options; name or ID?

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#3108]
Hi, can anyone explain why I get both names and ID's when pulling out Design Options using Element.GetParameterByName? I think it would improve usability greatly if I got one or the other, or preferably both.
![image](https://cloud.githubusercontent.com/assets/5300197/5062557/8c406c62-6dc5-11e4-81ee-c32fc127b85a.png)

**Comment by rbosborne** [comment]
This is a related issue I recently came across...the ID vs name issue with design options is also inconsistent from run to run.  Sometimes you get the ID, other times you will get the name for the exact same index location.
![rooms and design options](https://cloud.githubusercontent.com/assets/12659052/7882065/d663aa20-05d7-11e5-983d-6daa40352286.PNG)
![rooms and design options 08](https://cloud.githubusercontent.com/assets/12659052/7882069/da0bd940-05d7-11e5-84b6-46108fa3ac46.PNG)

**Comment by ksobon** [comment]
You can get Design Option element that any element belongs to by using BuiltInParameter called "DESIGN_OPTION_ID". You can also get the design option set and its subset name as a string using BuiltInParameter called "DESIGN_OPTION_PARAM". These can be obtained via archi-lab package like so: 
![capture](https://cloud.githubusercontent.com/assets/529781/10327881/d94fdefc-6c7a-11e5-8b77-8bf2cad528a9.PNG)

**Comment by ksobon** [comment]
I am showing regular Element.GetParameterValueByName for comparison. It returns the correct values but throws a warning because elements that do not have design option would return a null value. 

@ikeough @vasshaug can we close this issue?

**Comment by Racel** [comment]
The behavior here seems correct. Closing.
