### ISSUE TITLE
Family Instance Location Is Incorrect

### ISSUE THREAD

**Issue by JRohRevit** [DynamoDS/Dynamo#3109]
In version 7.3, the Family Instance Location Node is completely incorrect. It worked in 6.3. See attached image comparisons...You can see with the first image how the points are not even on the surface.

![incorrect7-3dynamopointlocations](https://cloud.githubusercontent.com/assets/9789950/5063273/7ac09c9a-6dad-11e4-9bf9-a776fcbaee91.png)

![correct6-3dynamopointlocations](https://cloud.githubusercontent.com/assets/9789950/5063278/b8b0a504-6dad-11e4-99b0-b25f3ad76f67.png)

**Comment by Racel** [comment]
I know this task was from a while ago, but another customer had a similar issue just recently. @JRohRevit did you ever find a workaround or determine the issue? I am curious if we still need to look at this in the latest stable release of Dynamo (1.3.x)?

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/46418501-21b52780-c6e9-11e8-8a47-46d83df0f8bd.png)
Working as expected in 1.3.3 with `AdaptiveComponent.Locations` node
