### ISSUE TITLE
Focus Publish Package window when publishing a package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3152]
This looks like a regression. When selecting Publish Version the Publish Package window appears _behind_ the Manage Packages window instead of in front of it.
![focusorder](https://cloud.githubusercontent.com/assets/3014437/5083272/4cb2ee10-6ef3-11e4-8b39-cd86c5e1d1ae.PNG)

**Comment by Racel** [comment]
This appears to be fixed. Closing.
