### ISSUE TITLE
Wish: Better dependency warning when removing nodes from a package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3157]
When removing nodes from a package and subsequently publishing that package, Dynamo will warn us if any of the remaining nodes in the package depend on the removed nodes:

> The following workspaces have not been saved: 
> {NAMES OF THE REMOVED NODES}. 
> Please save them and try again.

First of all, the wording of that warning could be clearer.Secondly, it would be great to see a list of affected nodes in order to speed up the process of fixing them. Perhaps something like:

> You seem to have removed the following nodes from this package: 
> {NAMES OF THE REMOVED NODES}. 
> The following nodes in this package rely on them: 
> {NAMES OF THE AFFECTED NODES}. 
> Please resolve these dependency issues before publishing a new version.

**Comment by Racel** [comment]
We do not have the bandwidth to address this in the near term. Closing for now.
