### ISSUE TITLE
Dynamo does not startup when "Mama" is not available

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3161]
today I was travelling by train through the Austrian alps. unfortunately there are gaps in the internet services.
I tried to fire up Dynamo when I had no access to the internet.
Dynamo didn't start up.
Maybe Dynamo should be a little more merciful?

**Comment by ke-yu** [comment]
@epeter- looks this issue can't be reproduced on the new build. I'm closing it.
