### ISSUE TITLE
Improvement: All of categories and All of Types 

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#3176]
They should have a Preview like other nodes.
![image](https://cloud.githubusercontent.com/assets/4572196/5089043/90155d24-6f38-11e4-8602-905fda3f99d5.png)

**Comment by jbenoit44** [comment]
please fix this. this is upsetting me all day long...

**Comment by ksobon** [comment]
This was fixed in 1.3. @kronz can we close this?

**Comment by kronz** [comment]
Fixed!
