### ISSUE TITLE
Mesh public methods?

### ISSUE THREAD

**Issue by anagpuyol** [DynamoDS/Dynamo#3188]
Hi, could we have access the methods on the Mesh.cs? In particular, we would like to use the colors. Thanks!
https://github.com/DynamoDS/Dynamo/blob/3120074548eb3f77ee64b948cc8c137fcd9f8752/src/Legacy/ExperimentalMesh/TopologyMesh.cs#L14

**Comment by ikeough** [comment]
Colors on geometry is now available through `Display.ByGeometryColor`. Please request a new improvement if this does not suffice.
