### ISSUE TITLE
Passing Arguments as Null

### ISSUE THREAD

**Issue by andyopayne** [DynamoDS/Dynamo#3194]
It seems as though passing in an argument with an optional parameter value has a bug in it if you assign it a value of null.  I'm using the Zero Touch methods and if my arguments all have a default values (some of which are null), shouldn't the component act as though it has enough information to compute the require function?  Is this a bug that can be fixed?

**Comment by junmendoza** [comment]
Hi @andyopayne

If you try a function with a default such as Math.Random(), it will give a random value.

Do you have a specific example that does not work? Its good if you could give a simple description of what default argument you provide and what you expect from it. 

Specifically in your ZeroTouch code, what is the signature of the function that fails when calling in Dynamo?

**Comment by andyopayne** [comment]
Hi @junmendoza 
Well, I have a component which has a bunch of inputs (say 7 or 8).  Now, those inputs expect a custom  class object to be passed to it (so not just an int or string)... However, I couldn't define the custom object as part of the parameter when the function is created.  So, as an alternative, I was going to create the arguments as part of the function declaration but assign them as null objects.  Then, inside the function I do a check to see if the input is null and if it is then I create the custom object and assign it to the variable.
So, what I would expect to happen using this method would be that even if my 7 or 8 inputs do not have an explicit connection attached, the function would still compute because the parameter has already been assigned a value (null).  But, right now I have to explicitly create 7 or 8 connections just to get the function to actually compute.  
I hope that's clear (but I was trying to be generic).  If you want a more specific example, I could try to provide some images of the actual implementation.

**Comment by ikeough** [comment]
@andyopayne It's been a while since I checked this issue. Sorry. Now that we have published Firefly, and added the ability to define DS expressions as default arguments, did we get you where you need to be? I'm closing for now because I think we did, but please re-open if I'm mistaken.

**Comment by tatlin** [comment]
@ikeough @andyopayne did go in and expose some more in firefly for Dynamo recently, not sure if he finished that part yet or not but perhaps could look at this again too 

-matt
