### ISSUE TITLE
Dynamo stops updating view when editing custom node

### ISSUE THREAD

**Issue by tothom** [DynamoDS/Dynamo#3207]
Hi!

Got a strange error where the interface stops updating when I enter a custom node. I noticed that it only concerns one certain .dyf-file. I tried restarting Dynamo, Revit and my computer, but the problem still persist. I even tried other builds of Dynamo, but the problem is still the same. It's like the custom node is corrupted or something. I'm now unable to edit the custom node.

![141120-190432](https://cloud.githubusercontent.com/assets/9868784/5130095/14b2d704-70e8-11e4-947f-4873f8e5bf6d.png)

-Thomas

**Comment by ikeough** [comment]
@tothom I'm closing this because the internal task has been resolved and we never checked back here. Please reopen if this is still and issue.
