### ISSUE TITLE
"Ctrl Z" daily builds 0.7.5.2014.11.20T1328

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3218]
pressing "Ctrl" and "Z" key moves active node to infinity.
(I expected the undelete function)

**Comment by jnealb** [comment]
@epeter- @andydandy74 @kronz This is resolved with 7.6 0.7.6.3694 (not posted yet).

**Comment by andydandy74** [comment]
Thanks @jnealb - lots of Europeans will be very happy about this one ... :-)

**Comment by ikeough** [comment]
The internal issue is closed. Please re-open if this issue persists.
