### ISSUE TITLE
Zero Touch Node _ warning level

### ISSUE THREAD

**Issue by eertugrul** [DynamoDS/Dynamo#3224]
Is there any way to set different warning level for zerotouch node, rather than throwing an exception. 

In some cases, we want the node outputs the values successfully returned and warn the user with the black sheep of the input list etc without terminating the whole process. 

is it possible to set the node into orange and throw the warning message but not to sink the whole boat ? :boat: 

cc: @ikeough

**Comment by Racel** [comment]
This was addressed here: https://github.com/DynamoDS/Dynamo/pull/3950
and here: https://github.com/DynamoDS/Dynamo/issues/2671

Closing.
