### ISSUE TITLE
Mapping causes disposal of unused geometry from unused output on multi touch ZT node

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#3226]
It's hard for me to figure out if this is a bug in my code or in how Dynamo implements map, and the interaction with ASM geo/memory.

@ke-yu , seems possibly related to MAGN 4605.

will post this internally when have access.

![screen shot 2014-11-21 at 4 16 00 pm](https://cloud.githubusercontent.com/assets/508936/5152378/104d0ed6-71c0-11e4-9dba-b60df5618b07.png)

will outline structure of image here:
zero touch node with 2 outputs - outputs a 2d list of surfaces, and an object that also contains references to those same surfaces in the first output.

The mapped node with the unused "surfaces" output when I later try to access those same surfaces through through the unfolding object, gives me null references exceptions, the surface wrappers are still in Dynamo and LibG though, but the ASM geo has been disposed.

does Dynamo attempt to dispose geometry output from unused outputs when mapped? (by unused output I mean the output not hooked up to map)

When I do not map the output but let replication automatically map the node, theres no problem downstream, the ASM geometry is still there.

I'll try to create a reproducible case from this with minimal zt node.

**Comment by ikeough** [comment]
@mjkkirschner Still an issue?

**Comment by mjkkirschner** [comment]
think this was a garbage collection bug that was fixed.
