### ISSUE TITLE
Performance closing / opening a dyn file daily builds 0.7.5.3242

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3227]
when closing dyn files or when opening new definitions or when selecting model elements a certain delay is recognizable.

**Comment by ikeough** [comment]
@epeter- Can you tell us if this is still an issue with newer builds?

**Comment by ke-yu** [comment]
Hi @epeter- I'm closing this one as this issue is on very old build. Please test on new build and reopen this issue if it is reproducible.
