### ISSUE TITLE
Confusing File.FromPath node

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#3256]
The new image from file node and the “renovated” excel read node cannot take directly a file path. The file must be extracted first from the path
![01](https://cloud.githubusercontent.com/assets/6596042/5165501/abd8b39c-73e5-11e4-99b8-155bf70fdf3e.jpg)

The not consistency with the Sat and CSV import, that can take the path directly, can be confusing. And honestly, having to take the file from the file path seems a bit redundant and unnecessary.

**Comment by ikeough** [comment]
Internal task is closed.
