### ISSUE TITLE
Wish: Ability to add comment on changes for new package versions

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#326]
When uploading a new package version, it would be useful to be able to publish a comment on fixed issues or added functionality for that version/revision.

**Comment by smangarole** [comment]
@Racel and @kronz - Can you please update this in light of the ongoing package manager development?
Can we close this?

**Comment by Racel** [comment]
@smangarole - This functionality will need to re-evaluated in the new UI/backend. Why don't we close this for now.
