### ISSUE TITLE
UX improvement: Link to package data sets

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3261]
It's great that we can now include documentation in our packages. It is a bit awkward having to browse through the Dynamo package folders to find these files, though. It would be nice to have an additional "Open data sets" option (or something similar) in the Manage Packages dialog _only_ for those packages that actually contain any files in their extra subfolder.

**Comment by andydandy74** [comment]
@johnpierson Feel free to cull this one. I've kinda solved this one for myself:
https://github.com/andydandy74/Monito/wiki/Tools-Overview#package-directories

**Comment by johnpierson** [comment]
I had a feeling you did . 🙂
