### ISSUE TITLE
Wish: Watch2D node

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#3271]
Hey,
would it be possible to have a 2Dwatch Node in Dynamo? I'm thinking of something like graphs or bar charts to evaluate calculations.
Thanks, Fabian

**Comment by redinkinc** [comment]
now an experimental Watch2D in http://github.com/redinkinc/DynamoUtilities.

**Comment by johnpierson** [comment]
Closing this for now as there are a number of packages and extensions that achieve this.
