### ISSUE TITLE
Wish: Hard Refresh or "Recompute All"

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#3273]
Every now and then, I find myself needing to do a "hard" refresh of a definition... meaning to force all nodes to recompute.  Is there a way to do this currently?

The work around always seems to be to re-wire the front of the definition or provide some toggle to make Dynamo "think" it needs to refresh.... but it would be preferable to have a "Recompute All" or "Refresh All" feature.

**Comment by mjkkirschner** [comment]
@scottmitchell - I think you can consider this when you are thinking about the profiler UX.

**Comment by Amoursol** [comment]
This has now been implemented in the **TuneUp** extension, available from Dynamo 2.5 onwards.  All nodes can be marked dirty and recomputed using the **Force Re-execute** button.
