### ISSUE TITLE
Uninstalling Library-based Pacakge Requires Restart of Revit (not just Dynamo)

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#3274]
When uninstalling a Dynamo package that contains a loaded library, Dynamo will give a warning that a the package has been flagged to be uninstalled and a restart of Dynamo is required.  

If you do this within Revit, I have also found that you also need to restart Revit for this process to be successful which is rather inconvenient.

Suggestions...
-- Make it possible to uninstall library-based packages from within Revit (preferred)
-- Make it clear to the user that a restart of Revit is required (will at least clarify the workflow)

**Comment by Racel** [comment]
@kronz - I believe we have improved this workflow in the more recent versions of Dynamo. Closing for now, but feel free to reopen if you disagree.
