### ISSUE TITLE
Feedback on Workflow for Updating Library-based Package

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#3275]
I recently updated a library-based package for Dynamo (Rhynamo).  I found the following which made the process quite tedious for both a developer and a user

From the Developer's side....
- When I update my library with a new version number, the library will no longer load in Dynamo through the package.  I thought I was going crazy because it didn't occur to me that changing the version number on the library would affect if it got loaded
- Following this, in order to get the library to load, I discovered that I also needed to update the pkg.json file by finding the line where it lists the library version and change it to the new version.
![image](https://cloud.githubusercontent.com/assets/1890663/5195727/62353b56-74ef-11e4-8e3f-58dce03cc845.png)

From the Users Side...
This appears to the be the workflow for a user who needs to update a library-based package like Rhynamo...
-  User goes to package manager.
-  User selects the package to update
-  Dynamo downloads package
-  Dynamo says something like "cannot uninstall old package, the old package will be removed but you need to restart Dynamo" (if you are in Revit, you have to restart Revit)
-  After restart, the package is removed... but the new version isn't there
-  User goes to the package manager
-  User selects the package to install
-  Dynamo downloads / installs the package.

A preferred workflow...
-  User goes to package manager
-  User selects package to update
-  Dynamo downloads package. 
-  User is alerted:  "The new version will be available after you restart Dynamo"
-  New package is available after restart.

Or better yet...
-  User goes to package manager
-  User selects package to update
-  Dynamo unloads old libraries and loads new libraries  (no restart needed)

**Comment by ikeough** [comment]
A fix for the internal task is in https://github.com/DynamoDS/Dynamo/pull/3929. Please let us know if you're still seeing this issue in newer builds of Dynamo.
