### ISSUE TITLE
Notes not in selection after copy/paste

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#332]
When copying nodes and notes, the copied nodes are selected after pasting them, the notes aren't. Also, the pasted notes lose alignment to the pasted nodes.
Step by step:
Select and copy:
![bildschirmfoto 2013-08-02 um 12 52 11](https://f.cloud.github.com/assets/3014437/900382/9c8bf58c-fb61-11e2-8f50-2c06c418d568.png)
Paste:
![bildschirmfoto 2013-08-02 um 12 51 20](https://f.cloud.github.com/assets/3014437/900385/b08f7856-fb61-11e2-9f61-c7ebf15c797c.png)
It would be great if:
1. pasted notes would keep their respective alignment to pasted nodes
2. pasted notes would be in the selection, too - that way we could move the entire group of pasted objects (nodes *and* notes) to a new position directly after pasting them
(Using Build 0.5.2.19961)

**Comment by Benglin** [comment]
Oh boy, did not know about this defect until #4133 was created last week. This is now fixed with #4172.

**Comment by andydandy74** [comment]
Great. This was quite the nuisance.
