### ISSUE TITLE
Autodesk.LibG.LibGPINVOKE

### ISSUE THREAD

**Issue by Antfa** [DynamoDS/Dynamo#3338]
Hi I'm using Dynamo 0.7.4.3245 & Revit 2015 UR4 and get the following error.
Point.ByCoordinates operation failed. 
The type initializer for 'Autodesk.LibG.LibGPINVOKE' threw an exception.

![capture](https://cloud.githubusercontent.com/assets/10041482/5257452/adef1294-7a3d-11e4-96f7-9257c28ef166.PNG)

**Comment by benzhang01** [comment]
Hi, I got the same question, my Revit program was saved in“ C:\Program Files\Autodesk\Revit 2014” and the dynamo “C:\Program Files\Dynamo 0.7”, Do you have any idea of the problem? thanks

**Comment by ikeough** [comment]
@benzhang01 Is this still an issue on newer builds of Dynamo for Revit?

**Comment by Jezzzza** [comment]
This just happened to me , script has been working fine all day then suddenly this happened. 

![capture1](https://cloud.githubusercontent.com/assets/12743950/15390281/b577d014-1ded-11e6-9959-89ef125cb323.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12743950/15390282/b66887e8-1ded-11e6-8a5a-5ec366e9c3cb.PNG)

**Comment by Jezzzza** [comment]
and yes revit is installed at "C:\Program Files\Autodesk\Revit 2016"

**Comment by ke-yu** [comment]
Close it now. Please reopen the issue if it is still reproducible on the latest build.

**Comment by kehehee1** [comment]
I also encounter this problem. Anyone can help?

**Comment by sharadkjaiswal** [comment]
@kehehee1 can you please provide more details on the version of Dynamo, Revit installed on your system?

**Comment by kehehee1** [comment]
@sharadkjaiswal Thank you for your reply, I just download the source code recently and complile it.The Dynamo Core version is 2.0.0.3351. Does the Gemoetry Library depends the Revit? If I don't install the Revit, it won't work, is that right?

**Comment by sharadkjaiswal** [comment]
Yes, without Revit installation geometry library in Dynamo won't work.

**Comment by kehehee1** [comment]
@sharadkjaiswal Thanks I get it!!
