### ISSUE TITLE
Views node should show unique list of views

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3345]
Currently some views are listed up to three times.
Also, how about sorting that list alphabetically?
DynamoInstall0.7.5.20141202T1333

**Comment by ksobon** [comment]
This node: 

![image](https://cloud.githubusercontent.com/assets/529781/11068169/1b92adec-879e-11e5-80e3-0093eb9f6ce8.png)

Still not working, and still doing what it used to which is add all of the views to the list every time someone touches it. It doesn't clear the list, it just keeps appending new items to it. 

This is in latest Dynamo 0.9

**Comment by mjkkirschner** [comment]
@ksobon @dimven has provided a PR to fix this I believe, but I forgot to merge it- I will merge it now.

**Comment by ksobon** [comment]
All right thanks!

**Comment by ksobon** [comment]
this has been fixed. Can we close this issue?
