### ISSUE TITLE
what is the equivalent of dir() in design script?

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#3353]

**Comment by ksobon** [comment]
@lukechurch sorry to bother, but is there something available in Design Script to do that? Enumerate all members of an object? I guess what I wanted this for back in the days was that it is relatively hard to "just remember" all of the available methods for a given object and since there is no intelisense for python nodes, i was hoping to use something like a dir() to look them up.

**Comment by ikeough** [comment]
@ksobon We do not have anything equivalent. @ke-yu, please correct me if I'm wrong.
