### ISSUE TITLE
Surface.TrimWithEdgeLoops

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#3354]
I tried utilizing this node with a surface and a closed polycurve, but get "Warning: Surface.TrimWithEdgeLoops operation failed. Not implemented" I tried to look around for known issues in the daily 0.7.5 release but couldn't find any about this topic?

**Comment by ikeough** [comment]
This shows up in newer builds. Can you please take a look and let us know if you're still seeing this issue?
