### ISSUE TITLE
NodeModel library is loaded as ZeroTouch during "Import Library" menu execution

### ISSUE THREAD

**Issue by vmoyseenko** [DynamoDS/Dynamo#3361]
Build: 0.7.5.3373 (master branch)
Used NodeModel library: `SampleLibrayUI.dll`. It is output of project `SampleLibraryUI`.

Using menu "File - Import Library" import NodeModel library. I have used the library specified above. I got next view:
![001](https://cloud.githubusercontent.com/assets/8158551/5295817/8e70a11c-7ba5-11e4-9908-ea3fc29cfa2e.PNG)

`System`, `Microsoft` and `Dynamo` should not be normally visible.

While debugging I have found that any imported by this way library is handled as ZeroTouch library.

**Comment by RodRecker** [comment]
seems related to #3807 which is now closed.
@vmoyseenko Can you check if this works for you now?

**Comment by ramramps** [comment]
@vmoyseenko Can you please check and let us know if this is fixed?

**Comment by johnpierson** [comment]
Closing this issue as we haven't received more information on it in a while. Feel free to reopen and provide more information if this issue persists for you.
