### ISSUE TITLE
Can´t activate 3D preview 

### ISSUE THREAD

**Issue by daaldimo** [DynamoDS/Dynamo#3365]
When i check showing background 3D preview in menu view nothings happend

![dymano problem 1](https://cloud.githubusercontent.com/assets/10080875/5308734/7652c900-7be8-11e4-81f3-0e7e3bbb6dd0.jpg)

![dymano problem 2](https://cloud.githubusercontent.com/assets/10080875/5308736/7b0ca470-7be8-11e4-8e85-131df8fdd65f.jpg)

Its the same when I call to the workspace  "watch 3D"

![dymano problem 3](https://cloud.githubusercontent.com/assets/10080875/5308717/35dc4612-7be8-11e4-8547-c78b5b8b7c81.jpg)

**Comment by ikeough** [comment]
@daaldimo It's been a while :) Can you please try with a newer version of Dynamo. I'm sure you'll have better results.

**Comment by daaldimo** [comment]
yeah man, no problem, thanks :)

2016-05-03 22:25 GMT-05:00 Ian Keough <notifications@github.com>:
