### ISSUE TITLE
List indexing error - Code Block - DesignScript

### ISSUE THREAD

**Issue by maito78** [DynamoDS/Dynamo#3379]
I can not use a variable to access on a more than one dimensional list with DesginScript language.
See the image
![capture](https://cloud.githubusercontent.com/assets/7395751/5317771/34702c14-7c9a-11e4-9cdb-568c7452f946.png)

**Comment by ikeough** [comment]
The syntax is as expected. We don't support lists of indices inside array indexers. @ke-yu can correct me if I'm wrong.
