### ISSUE TITLE
Feature Request: Override Colors in specific view

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#3418]
I could really use a way to override colors in a specified view, not only current. Possible?

**Comment by ksobon** [comment]
You can do that with archi-lab nodes like so: 

![capture](https://cloud.githubusercontent.com/assets/529781/10328537/e141f2d6-6c83-11e5-8fbd-634141fbbd77.PNG)

Result:

![capture1](https://cloud.githubusercontent.com/assets/529781/10328538/e8d6cc24-6c83-11e5-8007-ba119c6edb06.PNG)

Just make sure that list length matches and there is a color and a view for each element. Fill pattern is just a single element input that will be applied to all.

**Comment by ksobon** [comment]
@vasshaug @ikeough Can we close this issue?
