### ISSUE TITLE
Settings not preserved when installing a new Dynamo version

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3421]
I find this *really* annoying - every time I install a new build, I'm presented with the data reporting splash screen and I need to turn off background preview. Those are decisions I already made - they are in DynamoSettings.XML. I really think the installer should be adopting the settings that are aleady present on my machine. And I'm actually pretty sure it used to work like that at some point. perhaps before the installer was rewritten...

**Comment by sharadkjaiswal** [comment]
Hi @andydandy74, do you still see this issue? I think if you uninstall the product yourself and then re-install, it won't remember the new settings. However if you are upgrading using green cloud notification in the product, it should remember your settings and shouldn't prompt you again. @riteshchandawar, @jnealb  Please confirm the behavior.

**Comment by andydandy74** [comment]
Works as expected now. Thanks.
