### ISSUE TITLE
Dynamo UVs no longer translated into Revit UVs on planar surfaces

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3423]
AdaptiveComponent.ByParametersOnFace now seems to pass the Dynamo UVs directly to Revit without converting their range. I have tested this on a planar surface, but this would be a problem with revolves as well since they also do not have a UV range of 0..1 in Revit.
0.7.5 RC
Below you can see a screenshot of a grid of panels placed on UVs in the range of 0..1 - it's the black block in the middle... ;-)
![unbenannt](https://cloud.githubusercontent.com/assets/3014437/5423921/4660ee2e-82d8-11e4-842e-b47a1ee6534d.PNG)

**Comment by andydandy74** [comment]
I was preparing a class on paneling today and ran into this extremely annoying bug again. Any chance this is going to be fixed in the foreseeable future? Anyone who knows a workaround? (And by workaround I don't mean using points instead of using UVs...)
Or maybe it has been fixed? (Couldn't test it in the latest daily because there were no Revit nodes available...)

**Comment by RodRecker** [comment]
@jnealb Can you take a look at this?
@kronz Let's figure out when we need to look at this.

**Comment by kronz** [comment]
OK, I see the issue.  Looks like we lost this bug somewhere along the way.  Double curve surfaces parameterize just fine, but single and planar not so much.  
![2015-04-06_1813](https://cloud.githubusercontent.com/assets/3456818/7013605/edaef626-dc88-11e4-9197-5d8a9d86823c.png)

Looks like the workaround is to use the real world measurements to define the domain of the panels
![2015-04-06_1826](https://cloud.githubusercontent.com/assets/3456818/7013799/9f7a6b46-dc8a-11e4-8791-18c0e4ced59a.png)
tracking with http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6908

**Comment by tatlin** [comment]
Peter had added code to handle this case before 

-matt

**Comment by ikeough** [comment]
@kronz Unclear from the internal issue what the status is here. Please advise.

**Comment by jnealb** [comment]
Can you please check that both AdaptiveComponent.ByParametersOnFace and OnCurveReference now create Revit-hosted components with the next daily build? (the fix is not in the 07/12 build, watch for the next post) - thanks.

**Comment by riteshchandawar** [comment]
@andydandy74 I am just taking a look at old issues, please let us know if this still doesn't work for you.

Thanks,
Ritesh

**Comment by andydandy74** [comment]
@riteshchandawar  - yes, this is still an issue:
![grafik](https://cloud.githubusercontent.com/assets/3014437/22728423/20f01886-edde-11e6-9c1c-70b963e21d81.png)
I used ```ReferencePoint.ByParametersOnFaceReference``` this time, but I would assume that the underlying code gets used in ```AdaptiveComponent.ByParametersOnFace``` as well.
Please keep in mind that this is a regression - @pboyer had this working properly in 0.7.something ...
This affects *all* planar and revolved Revit surfaces.
Dynamo 1.2.1.3083 (Dynamo 1.2.1 stable)

**Comment by smangarole** [comment]
Thanks for the feedback @andydandy74. Will prioritize this one.

**Comment by smangarole** [comment]
@jnealb Please note

**Comment by andydandy74** [comment]
Closed here and reopened in DynamoRevit repo
