### ISSUE TITLE
Finishing a Select Faces selection somewhat counter-intuitive

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3425]
I just used the Select Faces node for the first time and it took me several attempts to actually realize that I need to finish the selection in the option bar in Revit. I absolutely did not expect Dynamo to create any type of GUI inside Revit. If we have to press a button to finish the selection process, I think it would be more appropriate to do that in Dynamo which is after all where we we pressed a button to start the selection process in the first place.

**Comment by andydandy74** [comment]
@jnealb - It would probably help. But I still think the selection process used in Vasari's solar radiation tool would be a lot better. And then you could make the selction node flash in Dynamo... ;-)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2185).
