### ISSUE TITLE
Package manager: Warning for older versions of dependencies

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3433]
Scenario: I want to install a package A that depends on another package B. The version of B I have already installed is higher than the version of B that package A has as its dependency. Dynamo will not give me the choice to keep the newer version of B and still install A.
Expected behaviour: Inform the user that B is already installed and that its version is higher than the version package A needs. Let the user decide between:
- Keep newer version of B
- Install older version of B
- Cancel install of A

**Comment by andydandy74** [comment]
@pboyer - This is a really annoying "feature" of Dynamo. I just installed a package that has an older version of my own package as a dependency, didn't get a warning and effectively managed to overwrite some unpublished (and uncommitted) changes to my own package. Please consider fixing this!

**Comment by jbenoit44** [comment]
This is annoying. if it's not fixed soon, better say dependency is not allowed between packages. Users telling you your package is messing everything on their computer is a real pain in the a**.

**Comment by ksobon** [comment]
I would throw my hat into the fray here as well. Mostly because Julien's package has archi-lab dependency so its messing up my package. :-) I would consider this critical.

**Comment by jonathanroy8676** [comment]
So if I understand correctly, I'm new to Package Dependencies, by installing Package A, package B might be overridden and not work any more in my other script in which package B was used because it might be modified by a newer version of package B? (my post #6475)

**Comment by andydandy74** [comment]
@jonathanroy8676  - No, basically you might end up with an older version of package B than the one you had installed previously.

**Comment by andydandy74** [comment]
In your case, the current version of Bakeyr uses the current version of Clockwork, so no worries.

**Comment by mjkkirschner** [comment]
I think this is now possible,  please reopen if I am incorrect.
https://github.com/DynamoDS/Dynamo/pull/12358
