### ISSUE TITLE
Daily Build 0.7.6.20141215T2126 List.Join missing input (List1)

### ISSUE THREAD

**Issue by mpdiker** [DynamoDS/Dynamo#3434]
Daily Build 0.7.6.20141215T2126 List.Join missing input (List1)
![listjoin](https://cloud.githubusercontent.com/assets/5814209/5468073/216bd0aa-85d2-11e4-9ab2-ab3e60552865.JPG)

**Comment by ikeough** [comment]
@mpdiker Closing as the List.Join node now has a variable number of inputs. I think we got what you want :)
