### ISSUE TITLE
element.geometry unstable

### ISSUE THREAD

**Issue by FMFuk** [DynamoDS/Dynamo#3435]
Hi all,

I place a AC components at the end point of a curve and normal to the curve,
use element.geometry or element.curve to get a list of lines/arcs which are containing
in that AC components, use curve.byjoiningCurve to form a profile shape.
The first time I press "run", curve and the profile are drawn at the right place.
But afterwards if i run again (no matter edit the program content or not), the curve is still
at its right place, BUT the profile goes to somewhere near 0,0 which is very likely 
to be the origin of the AC component family, no longer normal to the curve also, become
flat on XY plane.
Any hints to solve this ? I remember such things do not happen in 0.6 version.

Rgds
FM

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2184).
