### ISSUE TITLE
Wish: List.FilterByBoolMask to accept 0/1 as True/False

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3436]
When I pull data from Yes/No parameters using Element.GetParameterValueByName, Dynamo returns them as 1 or 0. However, List.FilterByBoolMask will only work with True/False. As a workaround, I can take this through a Formula node (x==1), but it would make sense if booleans were automatically converted between Revit and Dynamo.
0.7.5 RC

**Comment by andydandy74** [comment]
Conditional staements in code block nodes aren't as fussy. They deal with 0/1 just like they are dealing with False/True. So it's the ```List.FilterByBoolMask``` node that should be augmented to also accept lists of ones and zeroes as a mask.

**Comment by ksobon** [comment]
+1 I agree. List.FilterByBoolMask should accept 0/1 as True/False

**Comment by johnpierson** [comment]
Definitely still a wishlist item in 2.0.1 
![image](https://user-images.githubusercontent.com/15744724/46486008-15e56600-c7ba-11e8-8a6b-8ff52e1ac01d.png)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2183).
