### ISSUE TITLE
Inconsistency in calling a geometry action (Point.PruneDuplicates)

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3445]
Haven't (consciously) seen this for any other geometry related nodes. Since Point.PruneDuplicates() is categorized as an Action, I would expect it to be called as shown on the left hand side.
![unbenannt](https://cloud.githubusercontent.com/assets/3014437/5494266/daa25442-86f2-11e4-9001-e527adaeeede.PNG)

**Comment by ikeough** [comment]
@andydandy74 The internal issue has been closed. I know we did a round of fixing on some of this. We have not overhauled everything, but have made targeted fixes in core.

**Comment by andydandy74** [comment]
Agreed - I see this as fixed, too, since there is now th epossibility of calling methods with static and instance syntax.
