### ISSUE TITLE
String.Split yielding different results with linebreak separator

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3446]
Using the same input (line break) in a String node and a Code Block shows that the separator strings seem to be interpreted differently:
![splitstring](https://cloud.githubusercontent.com/assets/3014437/5503490/d4ee7d20-8777-11e4-87af-55e993909827.png)

**Comment by ke-yu** [comment]
Fixed in #6791

**Comment by andydandy74** [comment]
@ke-yu - I still see this occuring in 1.2 - please re-open.
