### ISSUE TITLE
Solar Analysis does not work on surfaces that are hosting Divided Surfaces

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#3450]
Just encountered this today, have tested a couple of times, but it seems like surfaces that have Divided Surfaces, and subsequently Curtain Panel Pattern Based Adaptive Components does not work well with displaying analysis results. At least not solar analysis. Can someone else test and verify this?

![image](https://cloud.githubusercontent.com/assets/5300197/5511805/c2a21b26-87d2-11e4-8bc0-7abe976b6336.png)

**Comment by johnpierson** [comment]
Closing this as the issue is stale and the solar analysis nodes in Dynamo are no longer supported.v https://github.com/DynamoDS/Dynamo/wiki/Release-Notes
