### ISSUE TITLE
importInstance selection from Element Types not working

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#3461]
![image](https://cloud.githubusercontent.com/assets/6132497/5539418/1d11a568-8a76-11e4-91ba-4946a23da2f0.png)

**Comment by ksobon** [comment]
@marcellosgamb that was fixed some time ago when wrappers were added for ImportInstances. Can you close this issue? 

![image](https://cloud.githubusercontent.com/assets/529781/22400060/1d6db050-e579-11e6-99ab-56a6d58ac9c8.png)

**Comment by ksobon** [comment]
CC: @kronz can we close this issue? It was fixed.
