### ISSUE TITLE
Build a UI for every one

### ISSUE THREAD

**Issue by 262231123** [DynamoDS/Dynamo#3469]
Hello,I am Scott Xu , a curtain wall engineer from China. I and my workmates like to use dynamo very much. But the problem is that a lot of Chinese Engineers not so good at English. As you know,there are so many architecture projects and AEC in China and all over the world,Maybe a Chinese UI or graphical interfaces will help a lot of people to understand Dynamo. I would like to do this job for Dynamo for free, and I need a little help to know how to change the dynamo UI, if you are interested in this,my E-mail : scott.xyc@foxmail.com

**Comment by ikeough** [comment]
Hey @262231123. Sorry for the delay in this response. Dynamo has been localized into a number of languages. I believe Chinese is one of them. If newer builds of Dynamo Studio or Dynamo for Revit don't do what you want, please let us know. Closing for now!
