### ISSUE TITLE
PolyCurves in Dynamo...more questions.

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#3477]
@hlp @holyjewsus @pboyer @kronz I hope everyone is having wonderful holidays. 

This is just a quick question about behavior that i am experiencing with PolyCurves. Here's an issue: When a NurbsCurve is being queried for Weights it returns a list of weight values all equal to one (1). However, if the same NurbsCurve is being added to PolyCurve, then extracted using Curves() method and converted back ToNurbsCurve() (Curves() returns a list of generic Curve objects so to get back that original NurbsCurve i had to use ToNurbsCurve() method), when queried for Weights it will return a list of weight values equal to zero (0)...somewhere in the process weights all get reset to 0. Is that intentional? 

![capture](https://cloud.githubusercontent.com/assets/529781/5564443/380a74cc-8e8f-11e4-94fd-4db86c0eff84.PNG)

Here's the Python code that does conversion of Curves back to Arcs, Nurbs etc. 

```Python
def tryGetLine(item):
	startPoint = item.StartPoint
	endPoint = item.EndPoint
	distance = startPoint.DistanceTo(endPoint)
	if round(item.Length, 4) == round(distance, 4):
		return Line.ByStartPointEndPoint(startPoint, endPoint)
	else:
		return None
def tryGetArc(item):
	startPoint = item.StartPoint
	endPoint = item.EndPoint
	tangent = item.TangentAtParameter(0)
	dsArc = Arc.ByStartPointEndPointStartTangent(startPoint, endPoint, tangent)
	if round(dsArc.Length, 4) == round(item.Length, 4):
		return dsArc
	else:
		return None

test = []
for i in dsObjects:
	for i in i.Curves():
		if tryGetLine(i) != None:
			test.append(tryGetLine(i))
		elif tryGetArc(i) != None:
			test.append(tryGetArc(i))
		else:
			test.append(i.ToNurbsCurve())
OUT = test

**Comment by ksobon** [comment]
@hlp any news on this issue? I am waiting for this to be resolved before I can finish building Mantis Shrimp. PolyCurves are quite important for me since I can't really move on to Extrusions, PolySurfaces and Trimmed Surfaces without them.

Thanks!

**Comment by hlp** [comment]
Hi @ksobon, you are correct, we re-weight the NurbsCurve when it is passed into the PolyCurve. Your use case has been logged, but I can't comment on when this behavior will be changed.

**Comment by ksobon** [comment]
@ptierney is there any news on this? It's been quite a while (6+ months since your reply) and I am still having issues with NurbsCurves getting their weights re-set to 0 when passed through PolyCurve class. 
Thanks!

**Comment by RodRecker** [comment]
@ksobon Hi Konrad - @aparajit-pratap will follow-up on this one. Sorry for the delay.

**Comment by ksobon** [comment]
@RodRecker and @aparajit-pratap Thanks! Who would be a go to person for all DS Geometry issues? I think I might have some NurbsSurface, NurbsCurve issues that we talked about previously that are still in the backlog.

**Comment by RodRecker** [comment]
Hi Konrad - Please include @aparajit-pratap on those type of questions.

**Comment by ksobon** [comment]
Another geometry related issue that might be nice to have resolved. https://github.com/DynamoDS/Dynamo/issues/4945

**Comment by ptierney** [comment]
@ksobon Hi Konrad, as I mentioned before, this issue isn't a bug per-se, as it's never been part of the PolyCurve interface that we don't re-parameterize the Curves passed in. In other words, a PolyCurve isn't just a list of Curves, it can sometimes modify the Curves passed in, and as the code is written now, we reserve the right to change your passed in Curves. Changing this behavior would require a lot of work re-factoring out all this core assumption (and tracking down the bugs this will inevitably introduce).

Off the top of my head, it sounds like you could try keeping the sub-curves in a list, rather than a PolyCurve.

Or, perhaps Dynamo needs a "group" object: a collection of geometry that is united for data-flow purposes, but doesn't modify any of the input Geometry.

**Comment by aparajit-pratap** [comment]
@ksobon you can include me on all such geometry issues. I'll make sure I track these. I think that Nurbs curve weights should never be set to 0 or `null`. By default they should be unity or if the curve has been reparameterized, the weights should be some other value. Perhaps the `ToNurbsCurve` method needs to be fixed. I'll get back to you on this and the other issue with nurbs surfaces.

**Comment by ksobon** [comment]
@ptierney I hear you. I cant imagine why you would need to do that, but if you say it has benefits then let it be. This was/and still is not my issue here. If you take curves and fold them into a polycurve then i am sure you can provide methods for extracting them. What bothers me is that i can take any curve in dynamo and use tonurbscurve() method on it, and it will return a valid nurbs curve but if i take one that was at any point passed through polycurve i get a pseudo nurbs curve - or one lacking proper weights. If there is a method called ToNurbsCurve then i expect its output to be just that and not some handicap of a nurb or you might just call it something else and dont have an issue here. 
Now, if you think that a curve group class is a better way to go then i am all for it. Keep in mind that if such thing will be introduced i would expect surface trims (just one of many thing that use polycurves) to support both - polycurves and grouped curves - otherwise we might be heading in a wrong direction. 
Idk. Let me know what you think. I dont think that what we have right now is a good solution. I am not sure that you need to refactor the whole thing but geometry, its easy of use and accessibility is quite important if dynamo will ever want to compete in that department with Grasshopper. 
Thanks!

**Comment by aparajit-pratap** [comment]
@ksobon there have been recent changes in Nurbs curves in Dynamo. The current behaviour is such that if the resultant Nurbs curve is non-rational, it will return default weights of unity otherwise it will return non-zero but valid values. You should be able to see this in the daily builds as well as 1.0. Let us know if we can close this issue once you've tested the new behaviour

**Comment by aparajit-pratap** [comment]
@ksobon I'm closing this issue for now until I hear from you otherwise. Please reopen if you still encounter issues. Thanks.
