### ISSUE TITLE
0.75RC2 Surface.Thicken performing slow with higher thickness values

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#3485]
![2014-12-30_133752](https://cloud.githubusercontent.com/assets/7148394/5576012/0316b478-902a-11e4-9f8f-58720e5d1aaf.jpg)

I noticed that once you start entering values over 0.5, the completion time grows exponentially. Is this expected behavior?

**Comment by kronz** [comment]
I can't reproduce this in a similar looking case.  Are you seeing this for all instances
![2015-01-04_2259](https://cloud.githubusercontent.com/assets/3456818/5609106/63504fd6-9465-11e4-9541-b26028e1d479.png)
 using thicken?

**Comment by dimven** [comment]
It seems pretty isolated. I repeated it both with a simple rig and with the original file and the described results only showed in the original file. It might have something to do with the way the surfaces were created?
![test](https://cloud.githubusercontent.com/assets/7148394/5609179/b5b1ec7a-94d4-11e4-8ecf-8bb27ffc10ab.jpg)
![original](https://cloud.githubusercontent.com/assets/7148394/5609180/bac2beba-94d4-11e4-920d-555f95d0fb07.jpg)

**Comment by dimven** [comment]
The problem definitely seems to be related only to surfaces created by lofting two arcs.
![test2](https://cloud.githubusercontent.com/assets/7148394/5612215/3025fd52-950c-11e4-8136-f6fe34f365b2.png)
