### ISSUE TITLE
Output connectors do not align with code

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#3486]
As the code blocks get longer, the alignment of the output connectors in the code block with their corresponding code is lost and a little inconvenient to track intuitively.
![dynamo20141230-3](https://cloud.githubusercontent.com/assets/5621624/5579552/8e6f2f2c-9062-11e4-8b4e-d0900be0bedc.png)

Regards,
Vikram Subbaiah

**Comment by ikeough** [comment]
#4150
