### ISSUE TITLE
AdaptiveComponents.ByPoint

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#3491]
Using 0.7.6.3557, the AdaptiveComponents.ByPoint won't take a list of points. I have also tried to use a  List.Map but no change. 

"Warning: AdaptiveComponent.ByPoints operation failed. 
The input list of points does not have the same number of values required by the adaptive component."

I use a simple one point adaptive family and a very small grid of points.

**Comment by holyjewsus** [comment]
have you tried using a list of a lists of single points.

Like this: [ [point], [point]... ]

**Comment by josols** [comment]
the FamilyInstance.Bypoint works in my case. Haven't tried a list of lists yet.

**Comment by ikeough** [comment]
I'm closing this issue as we do not have enough detail to test it. Please re-open if you're still experiencing this problem and have an example which reproduces the problem.
