### ISSUE TITLE
Door Rescheduling - Sort List by Key List

### ISSUE THREAD

**Issue by lukekv** [DynamoDS/Dynamo#3499]
The overall problem is to take in all the door elements in the project, sort them by level and then re-number the doors sequentially.  I have managed to grab the elements, extract the parameters I need (Unique Revit ID, Level, Mark) and lace them into a list of lists so that each door is its own list.

The problem I'm having is that it will not sort by level.  When I get the parameter level Dynamo spits out the unique Revit ID of the level so in my list of 300-ish doors there are 8 unique levels.  I think maybe I don't understand the "keyList" or "keyProjector" parameter.  I am trying to feed it the function GetItematIndex that points to the index of the level.  

What is a keyProjector?
How do I sort a list of lists based on a particular index of the sublists?
Is this the right method to renumber doors sequentially?

Help would be appreciated.  
![capture3](https://cloud.githubusercontent.com/assets/10402449/5614641/017a8a54-94c1-11e4-86b8-0d72ebb307cb.png)

**Comment by Steell** [comment]
@jnealb ptal

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
