### ISSUE TITLE
Node for Surface/Surface Intersection

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#350]
API to derive a curve from a 2 surface intersections was added to Revit 2014.  We need a node:
Inputs: Surface 1, Surface 2
Output:  Curve

**Comment by formula1210204** [comment]
may I ask the name of this node, or where can i get it?
I need this function for daily use, thanks a lot.

**Comment by andydandy74** [comment]
Use Geometry.Intersect

**Comment by formula1210204** [comment]
thanks for your help
