### ISSUE TITLE
Code block: nested list by naming hierarchy not working

### ISSUE THREAD

**Issue by tzl1117** [DynamoDS/Dynamo#3503]
![image](https://cloud.githubusercontent.com/assets/10407436/5619266/dac7edb4-94e5-11e4-94c8-de62189e7640.png)

The second code block is duplicated from first one. Same definition but different result. If I change the hierarchy index, it doesn't change the structure of the output immediately. I have to copy and paste to make it work.

**Comment by monikaprabhu** [comment]
Which version are you using ? I could not reproduce the first issue where you mentioned the results were different.

**Comment by ikeough** [comment]
I'm closing this issue as we do not have enough detail to test it. Please re-open if you're still experiencing this problem and have an example which reproduces the problem.
