### ISSUE TITLE
GetParameterByValue string error

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#3513]
When I feed the GetParameterByValue-node a string containing special characters (as Æ, Ø, Å) it produce an empty list. If I however use a codeblock with quotes it returns expected list. Any idea why? I'm using 0.7.5 RC2

**Comment by andydandy74** [comment]
I have also observed different behaviour for strings created in CBN's (#3446). Possibly related?

**Comment by monikaprabhu** [comment]
@andydandy74  thanks for reporting the issue - we are tracking this internally as MAGN-5791

**Comment by ikeough** [comment]
Internal issue has been closed.
