### ISSUE TITLE
python errors prevent dynamo saving definitions dailybuild 20141222Txxxx

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3525]
i was working on a python code.
during developing i had errors in my code.....
when the error was in an active transaction, dynamo prevented from saving the dyn file.
i observed that the asterix marking an unsaved definition was gone after Ctrl S, but the definition was not saved.
secondly:
if you use external libraries in your python code you have to rewire the node to execute it.
maybe a "force execution button" for python nodes were helpful

**Comment by ksobon** [comment]
I agree. Custom Python nodes require to be re-wired to re-execute. I am not sure its tied to external libraries being used but something that would force them to re-execute when "Run" button is hit would be nice. 
@pboyer @Steell

**Comment by Amoursol** [comment]
This has been addressed with the 'Run' mode inside of Python Nodes now and the addition of a 'Force Re-Execute' button in the [TuneUp Extension](https://dynamobim.org/tuneup-extension-explore-your-node-and-graph-execution-times/).
