### ISSUE TITLE
How to get the Face object from ElementFaceReference?

### ISSUE THREAD

**Issue by phavelia** [DynamoDS/Dynamo#3535]
So I was trying to query Face properties through the Dynamo node Element.ElementFaceReferences. I am getting the error 'Expected Reference, got ElementFaceReference' in a Python script I am using to query the properties. 

Is there a way to convert this to a reference, or maybe get the Face object from the ElementFaceReference?

Thanks!

P.S.: I am newbie in this, so it's possible I am missing out on some very basic stuff!

**Comment by monikaprabhu** [comment]
@pboyer

**Comment by hlp** [comment]
Hi @phavelia : did we discuss this after Wednesday's class? If so, have you figured out a solution?

**Comment by phavelia** [comment]
Hi @hlp : I actually posted this query before meeting you on Wednesday. I am still trying to figure out the best solution though!

**Comment by andydandy74** [comment]
@phavelia - Have a look at the custom node RevitFace.FromDynamoSurface in package Clockwork - the Python code inside should help you getting what you want.

**Comment by phavelia** [comment]
@andydandy74 - Yeah that worked! Thanks a lot Andy!
