### ISSUE TITLE
Wish - Filtered selections

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#354]
I'm imagining a node that can select all objects of a certain category and then accept some sort of filter. For example something to select all doors of a certain size or created in a certain phase. This would really open the door to building graphs that can be used on any project for QC purposes (can't think of a great example yet, but this Vasari post comes the closest):

http://autodeskvasari.com/forum/topics/conditional-statement-for-door-swing?xg_source=msg_forum_disc

I suppose one could do this with Python in some way, right? I'm looking at something that can be built with nodes instead of going the script route.

**Comment by ksobon** [comment]
@ikeough @dbaldacchino this can be closed. I am pretty sure we have that functionality already.
