### ISSUE TITLE
feature request editor

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3543]
for those of us who are coding a lot in python the allowance of using external editors were extremely helpful.
(editing a python node i.e in notepad++ makes live a lot easier)

**Comment by Steell** [comment]
You can use _Notepad++_ to write a Python script, save it as a file, and read the file into Dynamo by using the the nodes __File Path__, __File.FromPath__, and __File.ReadText__. Then, use a __Python Script From String__ node to execute it.

**Comment by pboyer** [comment]
Thanks @Steell!  @epeter- Please reopen if this doesn't work for you!

**Comment by epeter-** [comment]
thanks a lot guys, i totally missed that one!
will definitely change my future workflow
again thanks
peter


Am 14.01.2015 um 17:10 schrieb Steve Elliott:
>
> You can use /Notepad++/ to write a Python script, save it as a file, 
> and read the file into Dynamo by using the the nodes *File Path*, 
> *File.FromPath*, and *File.ReadText*. Then, use a *Python Script From 
> String* node to execute it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3543#issuecomment-69940521>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com
