### ISSUE TITLE
Element.SetParameterByName gives error on reopening script

### ISSUE THREAD

**Issue by MBijsterbosch** [DynamoDS/Dynamo#3550]
I am working on a script which works fine but when i close the script and reload it I get an error on the Element.SetParameterByName node which worked before. 

I can fix it by connecting a new string to the parametername input, run the script and then reconnect the original string. It seems to occur only when the parametername is "Start Join Cutback" or "End Join Cutback" Any ideas how to fix this, it makes it hard to use the script for other people.

Kind regards,

![working fine before reopening](https://cloud.githubusercontent.com/assets/10550107/5762268/44f5c654-9ce1-11e4-8037-5ae28ba0fb72.JPG)
![error on reload](https://cloud.githubusercontent.com/assets/10550107/5762276/4ca54c8a-9ce1-11e4-9ad6-45162d9c1dde.JPG)

**Comment by monikaprabhu** [comment]
@MBijsterbosch  can you please post your file some where?or send it to me.

**Comment by MBijsterbosch** [comment]
yes of course, the files can be downloaded from http://we.tl/5gMvesC3cp.
the script itself is not very efficient at the moment but that is something ill deal with ounce the error is fixed.

**Comment by monikaprabhu** [comment]
I can reproduce  this on on Revit 2014 and latest daily builds- we are internally tracking this at -MAGN-5878

**Comment by kronz** [comment]
Hi @MBijsterbosch , DOes this issue still reproduce for you?  We cannot recreate it.

**Comment by MBijsterbosch** [comment]
Hi @kronz 

Sorry for the late reply, ive installed the latest version of dynamo 0.8.3.2585 and upgraded the project to revit 2016. Im not sure if the error still exists because i get a new error so i cant test it. The element.SetParameterByName node doesnt recognize the "Start Join Cutback" parameter as parameter any more(see image). I built a python node to verify that it is still possible to write to that parameter and that works.
here is a link to the file and script

http://we.tl/FVeq6ziDx5


![new_error](https://cloud.githubusercontent.com/assets/10550107/9939676/d0b47a28-5d6b-11e5-94bd-5ba37066e611.JPG)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
