### ISSUE TITLE
'List.Phases' Missing Node

### ISSUE THREAD

**Issue by josh-n** [DynamoDS/Dynamo#3561]
There used to be a 'List Phases' node which no longer exists.

Without this it doesn't seem possible to control the phasing of elements through dynamo.

Is anyone able to create a custom node or add this back to the main build?

**Comment by andydandy74** [comment]
In the meantime there's a node called Document.Phases in package Clockwork that should help...

**Comment by monikaprabhu** [comment]
@kronz

**Comment by andydandy74** [comment]
BTW: "List Phases" was a custom node in 0.6.3 - there never was a built-in node for this.

**Comment by monikaprabhu** [comment]
@andydandy74  thanks for clarifying it-

**Comment by josh-n** [comment]
Thanks for your help @andydandy74
