### ISSUE TITLE
Custom Dropdown UI Node, enum items forced to ordered by alphabetically. 

### ISSUE THREAD

**Issue by eertugrul** [DynamoDS/Dynamo#3562]
@ikeough 

I am writing custom dropdown ui nodes and I would like to add a enum items in the same order on my class, and return int values, the sequence starts with 1 instead 0.

![image](https://cloud.githubusercontent.com/assets/4672688/5780682/8471c5aa-9d7a-11e4-8901-15f2c6522f2d.png)

I have just noticed that EnumAs abstract class overrides the int values of custom enum items, since it forced to ordered by name. https://github.com/DynamoDS/Dynamo/blob/297fa123d0c76509404cfce041239152eed6a494/src/Libraries/CoreNodesUI/Enum.cs#L45
also line
https://github.com/DynamoDS/Dynamo/blob/297fa123d0c76509404cfce041239152eed6a494/src/Libraries/CoreNodesUI/Enum.cs#L73

is it possible or is there any way to make changes on EnumAsInt so the items are not ordered by name and store the enum int values of original enum object ?

Thank you

**Comment by monikaprabhu** [comment]
@ikeough ,@keyu

**Comment by Racel** [comment]
@mjkkirschner - Any thoughts on this? If there is not a workaround for this, we do not have the bandwidth to take this on at this time. Please close if this will require implementation on our end.
