### ISSUE TITLE
why are columns created by the "StructuralFraming.ColumnByCurve" node created as sloped columns by default 

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#3563]
why are columns created by the "StructuralFraming.ColumnByCurve" node created as sloped columns by default .

it would make sense to create the columns as vertical by default since 99.9% of all the columns in the AEC industry are vertical?

**Comment by monikaprabhu** [comment]
@kronz

**Comment by kronz** [comment]
@marcellosgamb aren't Structural Columns a 2 pick (curve based) family by default in the Revit user interface as well?

**Comment by josols** [comment]
It's view dependant. In a 3d-view it defaults to 2 pick, in plan views it's not.

**Comment by ikeough** [comment]
I believe this is automatically set by the Revit API.

We use the Revit API's NewFamilyInstances2 method which we supply a list of FamilyInstanceCreationData objects. We get those like this
 `private static FamilyInstanceCreationData GetCreationData(Autodesk.Revit.DB.Curve curve, Autodesk.Revit.DB.Level level, Autodesk.Revit.DB.Structure.StructuralType structuralType, Autodesk.Revit.DB.FamilySymbol symbol)
        {
            return new FamilyInstanceCreationData(curve, symbol, level, structuralType);
        }`

When you define a column by passing in a curve, it automatically creates the column as sloped. If you created the column by passing in a point and a level, it would probably define it as non-sloped.
