### ISSUE TITLE
select model element(s) cannot select daily build 0.7.6.3805 (1st 2015)

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3564]
want to select elments in revit to assign it to Select Model Element / Select Model Elements nodes 
no (Wall)element selectable.
same issue with all selections (face,edge....)
persists in daily build from 20150117

**Comment by monikaprabhu** [comment]
@epeter- This is broken on the latest daily builds and is reported by testing team. We are tracking it at MAGN-5836 thanks for reporting the same

**Comment by epeter-** [comment]
problem persists in daily build 0f 20150120

**Comment by epeter-** [comment]
problem persists in daily build 20150121Txxxx

**Comment by RodRecker** [comment]
The fix has been submitted, it is still running through our automated tests. Watch for the next daily posting and try it there.

**Comment by epeter-** [comment]
tx
