### ISSUE TITLE
some bug with run auto /run in dynamo

### ISSUE THREAD

**Issue by zora-wang** [DynamoDS/Dynamo#3570]
see the attached image. 
1. create one point p=Point.ByCoordinates(1,2,3);
2.run it;--.we can get one point now;
3.create consecutive points( p=Point.ByCoordinates(1..10,2,3))
4 run it--> we can get 10 points now;
5 change step 3 to create a point again with the same name p=Point.ByCoordinates(1,2,3);
6 run it--. it should give us only one point. but there still be 10 points in Dynamo

![bug](https://cloud.githubusercontent.com/assets/10494236/5798049/4e9d6296-9ffe-11e4-9ee0-0ea99e6e538a.PNG)

**Comment by monikaprabhu** [comment]
@zorwang- thanks for reporting the issue - MAGN-5877

**Comment by ikeough** [comment]
@zora-wang I just tried this on our main branch and it seems to be working. Can you try the newest daily build tomorrow and let me know if you still see the issue? Thanks!

**Comment by zora-wang** [comment]
@ikeough  I will re test it next Monday. Thanks :)

**Comment by ikeough** [comment]
@zora-wang Any update here?

**Comment by ke-yu** [comment]
I've fixed this defect, though I can't remember the PR. Verified on the latest build.
