### ISSUE TITLE
Watch 3D 'grows'

### ISSUE THREAD

**Issue by testingwaters** [DynamoDS/Dynamo#3573]
The 'Watch 3D' node grows incrementally taller every time the file is closed and opened.
While this causes no real trouble, it affects the composition/layout of the dynamo definition.

Regards,
Vikram Subbaiah

**Comment by monikaprabhu** [comment]
@testingwaters interesting , is this happening with daily build? can you share your file ?

**Comment by monikaprabhu** [comment]
@testingwaters , I can reproduce this on daily build , thanks for reporting the issue. Tracking at MAGN- 5876.

**Comment by Benglin** [comment]
Hi @testingwaters, the defect has been fixed and pending review. It should get in tomorrow's build, thanks again for reporting!

**Comment by Benglin** [comment]
And so it has landed!
