### ISSUE TITLE
List.Join , and String.Join are borken

### ISSUE THREAD

**Issue by FrenchQuarters** [DynamoDS/Dynamo#3580]
This node is broken in the 0.7.6.3831 version. There "+" and"-" to add or subtract lists/Strings are now missing.

**Comment by monikaprabhu** [comment]
@kronz - can you please comment regarding the behaviour in 0.7.6

**Comment by kronz** [comment]
@monikaprabhu Seems to be an unambiguous bug.

**Comment by holyjewsus** [comment]
this looks like a result of the WPF separation, list.join is a zero touch node, it requires a node view customization if it needs variable inputs.  The node actually works like this... you just need to supply a list of lists using list.create and it will still join them.

**Comment by ke-yu** [comment]
'+' and '-' buttons are available on build 1.1.

![untitled](https://cloud.githubusercontent.com/assets/2600379/16770835/ea4d842e-4880-11e6-9a57-affaff946184.png)
