### ISSUE TITLE
Library filter

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3605]
filter returns non expected result:
user input: "select"
results in:
![select1](https://cloud.githubusercontent.com/assets/6928491/5859607/c65dbaf6-a25b-11e4-97b6-9048c7aa8b18.png)
user input "select " (one whitespace added):
![select2](https://cloud.githubusercontent.com/assets/6928491/5859647/0f816b4c-a25c-11e4-825c-63aec736552b.png)
as you see, only now the option "Select Model Element(s)" is visible.
maybe this behaviour has room for improvement

**Comment by monikaprabhu** [comment]
@epeter- Thanks for reporting this issue- We are internally tracking it at  MAGN-5930.

**Comment by Racel** [comment]
We have made improvements to the Library UI, but still need to make significant changes to our search. We plan on working on this in the near term. Closing this for now as we are tracking in another system.
