### ISSUE TITLE
Wish: Ability to create directories on the fly when writing files

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3613]
Currently, Dynamo seems to expect us to manually create directories we want to save to when using any of the nodes that write to files. It would be nice if any missing subdirectories contained in a given file path could be created on the fly by Dynamo when writing a file.
(Use case: create multiple CSV files in multiple subdirectories - subdirectory names determined by Dynamo script)

**Comment by eproca** [comment]
+1

**Comment by Racel** [comment]
You can make subdirectories using nodes: 
![image](https://user-images.githubusercontent.com/2551261/31630549-e5a4b374-b284-11e7-8c0d-3e62f947dd52.png)

Closing.
