### ISSUE TITLE
Surface error:  IG_SURFACE_NON_G1:  Surface is G1 Discontinous

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#3620]
Every now and then, I get this error when constructing a NURBS surface with NurbsSurface.ByControlPointsWeightsKnots():  "IG_SURFACE_NON_G1:  Surface is G1 Discontinous"

For example, here is a NURBS surface I would like to describe inside of Dynamo...
![image](https://cloud.githubusercontent.com/assets/1890663/5893383/160feab8-a4a7-11e4-92f8-68806b57eb86.png)

The NURBS geometry is originally defined in Rhino.  The surface is DegreeU = 1, DegreeV = 2, NumberOfPointsU = 2, NumberOfPointsV = 5.  

In most cases, NurbsSurface.ByControlPointsWeightsKnots works like a charm.  But there are still surfaces that are give this problem... even basic ones like the example above.

I found others that have had similar problems in Fusion.... http://forums.autodesk.com/t5/sketching-sculpting-modeling-and/quot-surface-g1-is-discontinuous-quot-preventing-ts-to-brep/td-p/5028854

There is also a report of this in AutoCAD:  http://forums.autodesk.com/t5/autocad-2010-2011-2012/how-to-create-a-complex-3d-solid-for-buildings-ceiling/td-p/3946807

**Comment by pboyer** [comment]
@archinate: A degree 1 surface is not G1 continuous.  G1 continuity implies that there is a smooth transition between the tangents of a surface.  For example, a polyline is a curve lacking G1 continuity.  It has sharp discontinuities in its tangents.

Your surface actually has this property as there are only two points in the U direction, but you need to perform what is called "degree elevation: on this surface to make ASM happy.  This will preserve the shape while raising the degree.  As a stop gap, RhinoCommon might be able to supply this out of the box for you.

@hlp It sounds to me like we need to perform a degree elevation by default when constructing a surface with this constructor.

**Comment by archinate** [comment]
hey @pboyer 
I looked into degree 1 as being the cause... but it does seem that the behavior is inconsistent with other surfaces.  

For example, I can get these surfaces to build correctly using the exact same class...  each of these have a Degree 1 in at least one direction... hmmm...

![image](https://cloud.githubusercontent.com/assets/1890663/5894404/e586c892-a4cb-11e4-8cf3-af79ae732a8d.png)

![image](https://cloud.githubusercontent.com/assets/1890663/5894431/ad06838a-a4cc-11e4-9fbf-8289855e999b.png)

![image](https://cloud.githubusercontent.com/assets/1890663/5894449/f3f23ef6-a4cc-11e4-8489-f6257d335dfe.png)

**Comment by pboyer** [comment]
@archinate A degree 1 surface is not G1 continuous*.  It may be that ASM does not do this legality check every time you create a surface with this method.  Either way, degree elevation would fix many of these cases (except when there are repeated knots).  

*Although generally it could be (i.e. in a straight line) but I'm not sure if ASM checks for this.

**Comment by pboyer** [comment]
BTW, here's an open-source degree elevation algorithm I just happened to have written yesterday:  

https://github.com/pboyer/verb/blob/haxe/src/verb/core/Modify.hx  line 84

:)

**Comment by hlp** [comment]
Hi @archinate , ASM doesn't handle degree 1 spline curves and surfaces well. I wish I could give a more exact explanation of when it handles degree1 well and when it doesn't, but all the edge cases aren't documented.

@pboyer I think the idea of degree elevation is interesting, but it violates the contract of the node. If you specify that you want a surface of degree 1, and it returns a surface of degree 3, that's weird.

FYI, going forward, we're looking at incorporating the Autodesk Translation Framework into Dynamo. Insanely smart people have solved the Rhino -> Dynamo / Dynamo -> Rhino problem a while ago, and if there's enough user interest Dynamo's benevolent product owner may increase the priority of this task (paging @kronz )

**Comment by kronz** [comment]
Hi guys.  ATF is a possible place for us to go with Dynamo functionality, but I wouldn't want Nate to have to wait for something speculative when he's got a solution in hand that is so close to working just how he wants it, thanks for exploring the current options.

**Comment by ksobon** [comment]
@archinate I had a similar issue before: https://github.com/DynamoDS/Dynamo/issues/2643
It was logged here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-5037

I hope this helps. Would you mind posting the troublesome surface? I would love to test MS on it. Thanks!

**Comment by aparajit-pratap** [comment]
This may be fixed here: https://git.autodesk.com/Dynamo/LibG/pull/429, (available in dailies and Dynamo 1.3 release)
Closing for now ...

**Comment by teocomi** [comment]
Updated to 1.3 and still getting this issue, @archinate can you confirm as well?

**Comment by aparajit-pratap** [comment]
@teocomi could you attach a sample graph that you're seeing this with?

**Comment by teocomi** [comment]
@aparajit-pratap I've digged down a bit more and the issue seems to be in the Surface.FlipNormalDirection component as the surface is generated successfully, but dynamo fails to flip it:

Dynamo definition: https://www.dropbox.com/s/9297h3sbalhhvib/nurbs-g1-bug2.dyn?dl=0

![image](https://cloud.githubusercontent.com/assets/2679513/24961175/f03ae7a0-1f8f-11e7-92ab-c614cdec809b.png)

**Comment by aparajit-pratap** [comment]
thanks @teocomi will take a look.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
