### ISSUE TITLE
special characters locale

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3623]
python nodes (still?) cannot handle localized characters:
![special](https://cloud.githubusercontent.com/assets/6928491/5896820/40cb4a00-a53c-11e4-9b83-e9e68de7b32a.png)

**Comment by jnealb** [comment]
@epeter- Thanks, we will investigate and update you.

**Comment by alfarok** [comment]
This appears to have been addressed in more recent releases.  Closing, please reopen if you are still having similar issues in newer Dynamo builds.

![image](https://user-images.githubusercontent.com/13341935/32505279-cde6bb4c-c3af-11e7-8166-dd2187863f98.png)
