### ISSUE TITLE
Canvas zoom factor influences screenshot quality

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#364]
It seems that when exporting an image of a larger workspace the node titles and port labels are not included in the image. Could this be changed, please?
![bildschirmfoto 2013-08-12 um 08 08 12](https://f.cloud.github.com/assets/3014437/945560/bb6f514a-0315-11e3-9ae5-9034e8c3607d.png)

**Comment by andydandy74** [comment]
Unfortunately, the zoom factor no longer seems to influence the image quality, which means that with larger graphs the exported screenshots are now completely blurry (which is just another word for "useless").

**Comment by jnealb** [comment]
Is this with 9.1 and 9.0?

**Comment by andydandy74** [comment]
0.9 stable
I'd be happy to provide a sample file.
This is what a screenshot of a large graph looks like:
![superblurry](https://cloud.githubusercontent.com/assets/3014437/12048408/3f4d77b2-aedb-11e5-8040-947bc4bf73f5.PNG)

**Comment by jnealb** [comment]
Sample file would be great, thanks and Happy New Year!

**Comment by andydandy74** [comment]
@jnealb - likewise.
I added you to a private repo (```BIM_Basics_...```) - look in the folder ```Scripts/09x```. You will see several graphs and corrsponding screenshots that show how the image quality deteriorates as the graph size increases.

**Comment by andydandy74** [comment]
This is still present in 1.0 - exporting small graphs works, exporting large graphs fails spectacularly.

**Comment by riteshchandawar** [comment]
Good news @andydandy74, we have fixed the long pending issue of screen capture and the fix is available in daily build.

Here is the Pull Request for the same, if you want to know more about it.  https://github.com/DynamoDS/Dynamo/pull/6786
Do let us know if that doesn't solve your problem.

Thanks a lot to @Benglin for fixing this issue.

Ritesh

**Comment by jnealb** [comment]
Nice going

**Comment by ke-yu** [comment]
Fixed in #6786 by @Benglin
