### ISSUE TITLE
Wish: Dynamo should remember settings between versions

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3651]
Whenever I install a new daily of Dynamo, Dynamo seems to forget:
- My recent files
- That I have already consented to data being collected
- Whether I want to see a background preview or not
(... and probably anything else that would be saved as settings)
I would love it if Dynamo were less forgetful... ;-)

**Comment by jnealb** [comment]
@andydandy74 Thanks for reporting this - until we provide a stabilized Dynamo update mechanism can we suggest that you develop a simple batch file to save off your files, \ProgramData\Dynamo\0.7 etc. Please note that with our localization merge the Samples folders have moved, they are now under \ProgramData\Dynamo\0.7\samples\en-US. The greater issue is being tracked with MAGN-6078.

**Comment by andydandy74** [comment]
I actually posted the same issue in #3421 already, so I'm closing this one...
