### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3652]
1) create a custom node in a project
2) give it a name that already exists in your packagemanager
3) save your custom node to file
4) go back to home workspace (at the moment - versions as of 201501 - dynamo will most propably crash).
5) do not save your workspace during crashing
6) restart dynamo
7) try to open our old project.
8) dynamo crashes as you have a new custom node with an old name and the definitions do not align.
your project file is lost (except you know how to edit xml)

**Comment by ramramps** [comment]
@epeter- I believe this is fixed. Can you please check and confirm?

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
