### ISSUE TITLE
CodeBlock Autocomplete

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3653]
the current version of autocomplete behaves very strange:
1) i have mantis shrimp, rhynamo..... installed on my system.
2) i have learned, that if i want to create a point i must not use Point.ByCoordinates() because of overlapping definitions (rhynamo).
3) the solition is to prepend" Autodesk." meaning "Autodesk.Point.ByCoordinates()".
4) so far so good.
5) whenever i want to create a point in codeblocks Autocomplete suggests "Autodesk.DesignScript.Geometry.NurbsSurface." as input
6) whenever i write "Autodesk." i have to delete "DesignScript.Geometry.NurbsSurface." and then write Point.ByCoordniates()

**Comment by aparajit-pratap** [comment]
@epeter- thanks for reporting. This is being tracked now. I may need more information from you later.

**Comment by riteshchandawar** [comment]
@epeter- I tried at my end and I am getting first option as Autodesk.DesignScript.Geometry.Point.ByCoordinates, so I don't think we have to write from the start like Autodesk..., there is a defect that it is showing for NurbsSurface when you start typing Aut..., auto-completion should complete only Class names and not namespaces. We are tracking that in MAGN-6094

**Comment by aparajit-pratap** [comment]
This has been addressed here: https://github.com/DynamoDS/Dynamo/pull/4060
