### ISSUE TITLE
Beta Builds Feature list

### ISSUE THREAD

**Issue by madeforworship** [DynamoDS/Dynamo#3654]
Hey guys, just curious if you keep a log of fixes/features you are adding when you post pre-release/beta builds of Dynamo.  It could be useful in identifying and testing things.  if you do, I couldn't find it!

Thanks!

**Comment by RodRecker** [comment]
@madeforworship We don't have such a report for the daily builds. We do have that information in the readme for the released and release candidate builds. I agree it would be useful.

**Comment by ikeough** [comment]
@madeforworship Please see the "Releases" section on the [front page of this repo](https://github.com/DynamoDS/Dynamo) for information about what's new and what's updated in recent releases.
