### ISSUE TITLE
Element.Geometry CRASHES 3000+ Generic Model Elements

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3661]
i am trying to work on  a project using a curtain wall containing 3000+ generic model Elements.
I was tying to import the geometry to dynamo 
categories - all elements of a category - element.geometry (respectively element.faces)
whenever 1 push the run button revit crashes!!!! after a few seconds.
splitting the lists into groups helps. found out that it not only a problem of the amount of elements, it is the problem with the geometry itself.
whenever i use a certain group (corner elements) dynamo causes revit to crash. in 20141222Txxx same model is working.
loading the hole model causes revit to crash!
autodesk crash report: CER_107904318
must be a bug in element.geometry respectively in element.faces nodes.

peter

**Comment by RodRecker** [comment]
Hi Peter - sorry about the trouble you're having.  Which version of Revit and which version of Dynamo are you using?

**Comment by epeter-** [comment]
revit 2015
latest daily build
regards peter

Am 01.02.2015 um 15:30 schrieb Rod Recker:
>
> Hi Peter - sorry about the trouble you're having. Which version of 
> Revit and which version of Dynamo are you using?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3661#issuecomment-72366875>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by holyjewsus** [comment]
hey Peter, in your post above, I want to clarify: does the model convert to Dynamo fine when running on revit 2014?

**Comment by epeter-** [comment]
i don't work revit 2014 anymore
sorry

Am 01.02.2015 um 18:55 schrieb Michael Kirschner:
>
> hey Peter, in your post above, I want to clarify: does the model 
> convert to Dynamo fine when running on revit 2014?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3661#issuecomment-72375256>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by holyjewsus** [comment]
@hlp

**Comment by kronz** [comment]
This definitely isn't the return of the same issue we saw in 0.7.4 and before.  I'm able to convert a hell of a lot more geometry in 0.7.6 in Revit 2015 than I could have in 0.7.4.  This sounds like a new problem.
![2015-02-02_0753](https://cloud.githubusercontent.com/assets/3456818/6000797/98dd507a-aab0-11e4-8419-d7d5dffa4ccd.png)

**Comment by kronz** [comment]
This example has 3356 pieces of geometry (not families), but @epeter- you might have a lot more than that with your 3000 families, do you know how many solids you have per family?  In any case, I'm guessing this is not a regression, but I'd like to get a reproducible case. 
![2015-02-02_0800](https://cloud.githubusercontent.com/assets/3456818/6000933/08198be2-aab2-11e4-9a9b-49e8cf5c0bbc.png)

**Comment by epeter-** [comment]
unfortunately i must not post screenshoot that show the project (it is a client project)
![number-elements](https://cloud.githubusercontent.com/assets/6928491/6001244/c33dc174-aae7-11e4-8a0e-e75467e8e336.png)
i distributed the families by filters.
i am able to load about 70% of the elements before revit crashes (it is a revit crash not a dynamo crash!)
![filters](https://cloud.githubusercontent.com/assets/6928491/6001275/2521d1be-aae8-11e4-8869-064399252190.png)

**Comment by hlp** [comment]
Hi @epeter- , I quickly looked through our code base to see if this might be overflowing one of our arrays, or otherwise exceeding Dynamo's storage capacity, but I don't see anything at first glance. We've logged this and will look into it shortly.
