### ISSUE TITLE
New category "ProtoGeometry" appeared

### ISSUE THREAD

**Issue by vmoyseenko** [DynamoDS/Dynamo#3676]
Build: 0.7.6.3985

I have got new category `ProtoGeometry` today
![image](https://cloud.githubusercontent.com/assets/8158551/6025478/73977012-abdb-11e4-9055-af8a37d19a69.png)

Is it correct behavior?

**Comment by sharadkjaiswal** [comment]
Oh this is wrong, thanks for reporting this @vmoyseenko.
@hlp, @zorawang all the resource string has started showing up as nodes in library, we need to make them internal.

**Comment by dimven** [comment]
There's actually two new categories: ProtoGeometry and RevitNodes.

**Comment by sharadkjaiswal** [comment]
@Sancerio has fixed this in #3694 and few related PRs. Please verify this again once his fixes are merged.

**Comment by vmoyseenko** [comment]
Category is disappeared. Fixed.
