### ISSUE TITLE
Element.Geometry CRASHES with nested families

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3679]
replaces the issue with 3000+ elements causing a crash.
found out that it is not the number of elements causing revit to crash but nested families.
i created a showcase file that is available for download under following link:
https://www.dropbox.com/s/gmlixa38olx7nt2/lifting.rvt?dl=0
i will remove the link in 2 hours from now.

**Comment by tatlin** [comment]
@jnealb or @hlp please take a look. cc @RodRecker @kronz

**Comment by hlp** [comment]
Hi @epeter- I've received your file and will look into it in a bit

**Comment by kronz** [comment]
Something odd going on with the specific geometry in the nested family.  
![2015-02-03_1541](https://cloud.githubusercontent.com/assets/3456818/6028966/50038bce-abbb-11e4-958c-9f65591687f9.png)
Guessing that it has to do with the form itself being made into a closed shape, which Revit often does not like
![2015-02-03_1539](https://cloud.githubusercontent.com/assets/3456818/6028985/6c7caefc-abbb-11e4-9e3d-d6846c74e4e6.png)

**Comment by kronz** [comment]
@epeter- I don't see the crash (working in Daily builds).  But I also don't see the looped nested elements coming through from Element.Geometry.  The element itself is an odd one, seems like it's not a well formed solid
![2015-02-03_1552](https://cloud.githubusercontent.com/assets/3456818/6029178/caba3010-abbc-11e4-8afc-97425b5c2487.png)

**Comment by epeter-** [comment]
@kronz i too found out that it is the hook causing all the troubles.
to import the geometry into dynamo you will need Clockwork (Revit/Elements/FamilyInstances/FamInstSubStructure) that will import nested families

**Comment by hlp** [comment]
Hey @epeter- , @tatlin : 

I looked into this. The main problem is that the namespace Autodesk.Revit.DB.RevolvedFace class doesn't provide the sweep parameters for a revolved surface. In other words, we know that those pipe elbows are surfaces of revolution, but have no way of determining that they're only swept 90 degrees. Because of this, we default to a complete revolution, producing circles (as shown in @kronz 's images).

It might not be possible to solve this without something like an import instance.

**Comment by epeter-** [comment]
maybe at least throw an exception to avoid crashing?

**Comment by hlp** [comment]
I actually can't reproduce the crash: I get the same results as Zach, an exception. Are you on the daily build?

**Comment by epeter-** [comment]
i get an exception too, but the exception causes revit to crash.
no, i am still on the last 2014 build, as select model element(s) does 
not work in 2015 dailies

Am 11.02.2015 um 00:08 schrieb Patrick Tierney:
>
> I actually can't reproduce the crash: I get the same results as Zach, 
> an exception. Are you on the daily build?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3679#issuecomment-73804126>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by aparajit-pratap** [comment]
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10222

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2181).
