### ISSUE TITLE
Code block malfunction?

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#3685]
I think the following observation is illogical, but also wanted to know if its intentional. 
When i write a new line into the middle of a codeblock the wires doesn't follow it's orgininal code block line. this goes for both numbers,letters and functions as far as I can tell.

Before:
![image](https://cloud.githubusercontent.com/assets/7080648/6041770/db2011cc-ac7f-11e4-984a-9359e09146bc.png)

After:
![image](https://cloud.githubusercontent.com/assets/7080648/6041777/eea03d4e-ac7f-11e4-81ca-fc42a298f27b.png)
 
Personally I think it would be more logical if the wires followed the values/formulas etc it had originally.

Using daily build 0.7.6.3921

**Comment by andydandy74** [comment]
:+1: I find that very annoying, too.

**Comment by ksobon** [comment]
This sounds like reaching gentlemen. :-1: Sorry for being a party pooper.

**Comment by ikeough** [comment]
I'm closing this request for improvement because, although it's a great idea, it isn't on our road-map to implement. Please feel free to make a contribution to the Dynamo project which adds this feature.
