### ISSUE TITLE
G1 Discontinuity and Nurbs Curves handling while creating floors

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#3689]
A Dynamo user has asked me for help the other day, and here are some of the issues that I was able to pinpoint for him:

Hi Paul,

I had a quick look at your definition. Here's what the problem was. Your curves were joined into a single polycurve which normally is OK. However, for some reason in this instance it caused Dynamo to freak out and report this error:
https://github.com/DynamoDS/Dynamo/issues/2643
Same error reported here by Rhynamo package creator Nate.
https://github.com/DynamoDS/Dynamo/issues/3620

It's clearly a Dynamo issue and has been bugging both of us. My workaround for this type of situation is to explode the polycurves. 

![image](https://cloud.githubusercontent.com/assets/529781/6054160/e6e08d92-acb7-11e4-9193-8da5b5f2a019.png)

That's exactly what I am doing in this very simple Grasshopper definition. I first explode them in Rhino. Reference them in, join them, explode them again and make sure they are on 4 separate branches. I probably could have just referenced them in joined and explode in GH avoiding the extra join step but anyways i digress. 

The idea here is to pass four (4) lists of curves where if all curves from each list were to be joined again you will get that one single floor outline.

![image](https://cloud.githubusercontent.com/assets/529781/6054165/f5019236-acb7-11e4-9d39-82024fc33966.png)

This works quite well! I am sorry this is such a hassle, but Dynamo is a little behind on handling polycurves. There are a lot of issues with them at the moment, and I am still waiting on some solutions from the Dynamo team. 

Just to make sure that you are good to go I went ahead and tried to create the floors....well no luck! Here's my error message:

![image](https://cloud.githubusercontent.com/assets/529781/6054171/02c181b0-acb8-11e4-9dd6-69de7a6f1e91.png)

This is simply a Dynamo being horrible at understanding what Revit wants. This error as much as its not very common it will get thrown when you try to generate a Nurbs Curve in Revit with degree less than 3. 

![image](https://cloud.githubusercontent.com/assets/529781/6054175/0bddd6c2-acb8-11e4-9464-ad07f65c2acf.png)

Since one of the curves in your floor outline is a NurbsCurve of second (2) degree it will not be very welcome by Revit. Here's a screen capture of Revit API exceptions for the NurbsCurves:

![image](https://cloud.githubusercontent.com/assets/529781/6054177/15061c82-acb8-11e4-8fd1-603c70a5bf2a.png)

So, here's a few options for you. Either go back to Rhino, and remodel those curves to up their degree to 3 or more. It's very simple, just rebuild that curve. Second option is to complain to Dynamo team about this. Third option is to handle the floor creation yourself via a custom node, and build in a check for Nurbs Curves that have degree less than 3 and up their degree then or convert them to Revit's closest approximation which is a Hermite Spline. 

It's not a perfect world we live in so I recommend rebuilding the curves in Rhino. Like so:

![image](https://cloud.githubusercontent.com/assets/529781/6054180/1efb4b5e-acb8-11e4-8fc1-cb669aa894c6.png)

And it still fails:

![image](https://cloud.githubusercontent.com/assets/529781/6054183/27e4a760-acb8-11e4-97d1-2909de33a91c.png)

Clearly the Nurbs Curves are not very welcome in Revit. What we can do with that i guess is convert them all to lines and arcs. 

![image](https://cloud.githubusercontent.com/assets/529781/6054187/31932674-acb8-11e4-9f48-1e0369939bba.png)

You can use Rhino command called Convert. 

![image](https://cloud.githubusercontent.com/assets/529781/6054189/3af5ef76-acb8-11e4-99bf-47a31291d9de.png)
![image](https://cloud.githubusercontent.com/assets/529781/6054191/3ef42250-acb8-11e4-943c-2c2559d5d473.png)

Success! 

All in all this was an exercise in how not compatible Dynamo geometry is with Revit geometry.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2180).
