### ISSUE TITLE
Icons for packages?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3721]
Nice job with the icons, everyone!
Now how do we supply custom icons for our packages? :-)

**Comment by pboyer** [comment]
@benglin

**Comment by Benglin** [comment]
Hi @andydandy74, great question! Here is what I would say:

1. Icons are supported for nodes built into Dynamo.
2. Support for zero-touch assemblies is in the work (there is [an internally tracked defect](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6057) preventing that from showing up, but the developer is working on that).
3. Zero-touch assemblies that come through Package Manager are having the same problem as above. Once that is fixed this will work and we will have a documentation on how icon resources can be prepared.
4. Icons are not supported for custom node at this point in time, we have this in our product backlog but no implementation plan for now.

This issue will be updated when anything changes, but I hope the above helps for now.

**Comment by andydandy74** [comment]
Oh, bummer.
It would be nice if there were at least the possibility of having a default icon for an entire package...

**Comment by Benglin** [comment]
Hi @andydandy74, that has been designed by @elayabharath, it is just that the implementation fell outside of the first cut Library UI scope. @riteshchandawar, we can consider increasing the priority for this and support the following for packages that come through Package Manager:

1. A downloaded package contains zero or more `*.dll` assemblies
2. A downloaded package contains one or more classes
3. There should be a way to add `icons.customization.dll` to the package. It contains icon resources for classes/methods inside the package.
4. The Library UI should pick these resources up and display appropriate icons with the same mechanism as other built-in classes/methods.

I have added [an internally tracked task](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6329) for this work. Let's discuss about this across the next sprint. Thanks!

**Comment by kudilovich** [comment]
I second the request to add icon customization. Also could you please clarify what Attributes need to be used in order for the list of Input and Output parameters to get filled in for WPF (UI) nodes.
Thanks.

**Comment by ksobon** [comment]
Can i "third" that? I would love to have icons for custom nodes.

**Comment by mostaphaRoudsari** [comment]
I "fourth" that! :beetle:

**Comment by andydandy74** [comment]
I think this has already been implemented (see #4295). I believe the documentation for DLL-based packages can be found here: https://github.com/DynamoDS/Dynamo/wiki/HowTo:Create-customization-dll
I do *not* know how the process for packages containing custom nodes differs from this documented process. Maybe @aosyatnik or @elayabharath can shed some light on this?

**Comment by aosyatnik** [comment]
Hi, @kudilovich , @ksobon , @mostaphaRoudsari  and @andydandy74 .
Documentation of how you can add icons for custom nodes is here: https://github.com/DynamoDS/Dynamo/wiki/HowTo:-Add-icon-for-custom-node

Sorry for long response. Thanks @andydandy74 for adding me in this conversation, I didn't see it :)

**Comment by andydandy74** [comment]
Thanks @aosyatnik - I must have overlooked that article on the wiki.
In case anyone's interested, I just uploaded a Dynamo graph that will extract the node ID for all DYF files in a given directory. This can be quite useful if you have a large number of nodes in your package...
https://raw.githubusercontent.com/CAAD-RWTH/ClockworkForDynamo/master/workflow_samples/0.7.x/ExtractNodeIDs/ExtractNodeIDs.dyn
