### ISSUE TITLE
0.7.5.3566 and sat import

### ISSUE THREAD

**Issue by safawi** [DynamoDS/Dynamo#3729]
I keep getting this error when trying to import a SAT file: Geometry.ImportFromSAT operation failed. Unable to get the face's range!:API_FAILED-- Operation Unsuccessful.
Does anyone know how to resolve this?

**Comment by jnealb** [comment]
@safawi Hello - I am unable to reproduce this with 0.7.5.3566 and several SAT files. Can you provide us with your file and dyn? Thanks.

**Comment by safawi** [comment]
Hi

I can’t send you the file as I would have you to sign an NDA.

I can see that is looks like sats files with lots of faces gets that warning. Do you know if anyone has been experiencing the same problem?

I’m attaching here the dyn file

Regards
Alessandro

Alessandro Napoli  ARB  RIBA
D +44 (0)20 7943 5801

**Comment by jnealb** [comment]
@safawi @hlp Not that I am aware of - pulling in the expert: Patrick?

**Comment by RodRecker** [comment]
@safawi Sometimes you can reduce the model to a portion that exhibits the problem. Is that possible? It may be difficult to reproduce without some data.

**Comment by safawi** [comment]
This is a portion I’m not able to import……

Regards
Alessandro

Alessandro Napoli  ARB  RIBA
D +44 (0)20 7943 5801

**Comment by safawi** [comment]
Have you got the file?

Regards
Alessandro

**Comment by hlp** [comment]
Hi @safawi I don't see any files attached. Would you mind sending it to my email address: patrick.tierney@autodesk.com

Thanks

**Comment by hlp** [comment]
Hi @safawi I can reproduce this but haven't found the solution. Here's our bug for future reference:
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6302

**Comment by ikeough** [comment]
The internal task has been closed. Please re-open if you're still seeing this issue.
