### ISSUE TITLE
section view by bounding box

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3734]
![section](https://cloud.githubusercontent.com/assets/6928491/6163385/ecd0ceb2-b291-11e4-8dd9-edddad8919b0.png)
i am trying to create a section.
bounding box = the box you see.
coordinatesystem = in the middle of the box
the section is creaed on wrong coordinates.
debugging: creaed a axonometric view from same bbox: perfect result.
found out this only happens when selecting nested families (curtain wall panels) for section

**Comment by jbenoit44** [comment]
old one for me (never succeed though) but worth a look about this topic:
https://github.com/DynamoDS/Dynamo/issues/2243

Andreas had a topic about this recently. rotated BBox. can't find topic....

**Comment by epeter-** [comment]
julian, thanks for responding. found out (at least suppose) that dynamo guys have the same problems converting units as we have (sometimes).

**Comment by Justrhys** [comment]
I have also noticed this and got around it by wiring in an offset based on my original geometry setout. I am now submitting a bug regarding the Section View by Bounding box not returning the sections in the Dynamo UI the watch node just returns a single functioning object

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
