### ISSUE TITLE
Slider GUI missing

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3744]
DynamoInstall0.7.6.20150212T0020
![nosliders](https://cloud.githubusercontent.com/assets/3014437/6184799/ad3ebb30-b366-11e4-86fa-2a4a9e9ed9df.PNG)

**Comment by jnealb** [comment]
@andydandy74 @RodRecker We have seen this and thought it was resolved with MAGN-6203. Can you un-install Dynamo from the Control Panel, delete the Dynamo 0.7 folder from Program Files, re-install Dynamo and try again? Thanks.

**Comment by andydandy74** [comment]
Same result, sorry.

**Comment by jnealb** [comment]
@andydandy74 Thanks - we are working towards a fix.

**Comment by JesusValderrama** [comment]
I have the same problem

**Comment by ikeough** [comment]
@andydandy74 @JesusValderrama Could either of you please send us a log file for a session of Dynamo in which you've seen this behavior. Log files can be found in your <user>\AppData\Roaming\Dynamo\0.7\logs folder. There's will be an exception in that log that should give us an idea why this is occurring.

Also, please try the latest daily build to see whether the issue is resolved.

**Comment by andydandy74** [comment]
Not resolved in the latest daily build. :-(
Here's my log:

Dynamo log started 16.02.2015 17:32:38
16.02.2015 17:32:45 : RequestUpdateVersionInfo
16.02.2015 17:32:45 : Requesting version update info...
16.02.2015 17:32:45 : Dynamo -- Build 0.7.6.4112
16.02.2015 17:32:45 : Dynamo will use the package manager server at : https://www.dynamopackages.com
16.02.2015 17:32:45 : Duplicate migration type registered for SunPathDirection
16.02.2015 17:32:45 : Dynamo is up to date.
16.02.2015 17:32:53 : Welcome to Dynamo!
16.02.2015 17:32:53 : 00:00:03.9363192 elapsed for loading Dynamo main window.
16.02.2015 17:32:53 : RENDER : Rendering Tier: 2
16.02.2015 17:32:53 : RENDER : Pixel Shader 3 Supported: True
16.02.2015 17:32:53 : RENDER : Pixel Shader 4 Supported: False
16.02.2015 17:32:53 : RENDER : Software Effect Rendering Supported: True
16.02.2015 17:32:53 : RENDER : Maximum hardware texture size: 8192;8192
16.02.2015 17:32:56 : Clearing workspace...
16.02.2015 17:33:02 : Failed to apply NodeViewCustomization for IntegerSlider
16.02.2015 17:33:02 : System.IO.IOException:
16.02.2015 17:33:02 : Die Ressource "controls/dynamoslider.xaml" kann nicht gefunden werden.
16.02.2015 17:33:02 :    bei MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   bei System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei Dynamo.Wpf.Controls.DynamoSlider..ctor(NodeModel model, IViewModelView`1 nodeUI)
   bei Dynamo.Wpf.NodeViewCustomizations.IntegerSliderNodeViewCustomization.CustomizeView(IntegerSlider model, NodeView nodeView)
   bei lambda_method(Closure , NodeModel , NodeView )
   bei Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
16.02.2015 17:33:03 : Failed to apply NodeViewCustomization for DoubleSlider
16.02.2015 17:33:03 : System.IO.IOException:
16.02.2015 17:33:03 : Die Ressource "controls/dynamoslider.xaml" kann nicht gefunden werden.
16.02.2015 17:33:03 :    bei MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   bei System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei Dynamo.Wpf.Controls.DynamoSlider..ctor(NodeModel model, IViewModelView`1 nodeUI)
   bei Dynamo.Wpf.NodeViewCustomizations.DoubleSliderNodeViewCustomization.CustomizeView(DoubleSlider model, NodeView nodeView)
   bei lambda_method(Closure , NodeModel , NodeView )
   bei Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
16.02.2015 17:33:09 : Goodbye

**Comment by RodRecker** [comment]
Thank you @andydandy74. So you are running German Windows. @JesusValderrama are you running a non-English version of Windows?

**Comment by JesusValderrama** [comment]
Yes, the spanish one

**Comment by jnealb** [comment]
@andydandy74 @JesusValderrama @RodRecker @ikeough  We can reproduce this, with French Windows. Thanks for your help.

**Comment by ikeough** [comment]
Hey @andydandy74 and @JesusValderrama. I believe we've fixed this with #3771. We are in the midst of a big localization project and the localized assets for cultures other than "en-US" were not yet available in the daily builds. So systems, like yours :), which had cultures set to other locales, could not resolve their resources. The linked fix makes the resource resolver drop back to using the "en-US" resources when no others can be found. I have verified that this fix works on a system with culture set to "de-DEU" (German). It should be available in the next daily build.

**Comment by RodRecker** [comment]
Thanks Ian for fixing it. @andydandy74 @JesusValderrama A daily was just posted but that one was already in progress so it won't contain Ian's fix. Watch for one within the next 12 hours or less.

**Comment by RodRecker** [comment]
Build is posted now - please give the latest daily a try.
http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoInstall0.7.6.20150217T1558.exe

**Comment by andydandy74** [comment]
Thanks, all good now!

**Comment by JesusValderrama** [comment]
Thanks Ian! It works perfectly now.

Jesús Valderrama



C/ Mexico 2, 3ºA (Málaga) 29010

Tel: +34 605 360 440

Email: jesus.valderrama.rguez@gmail.com <jmora@mv-bim.com>




IMPORTANT: The contents of this e-mail message and any attachments are
confidential and are intended solely for addressee. The information may
also be legally privileged. This transmission is sent in trust, for the
sole purpose of delivery to the intended recipient. If you have received
this transmission in error, any use, reproduction or dissemination of this
transmission is strictly prohibited. If you are not the intended recipient,
please immediately notify the sender by reply e-mail or phone and delete this
message and its attachments, if any.

ü Please consider the environment before printing this e-mail

2015-02-18 5:06 GMT+01:00 Andreas Dieckmann <notifications@github.com>:
