### ISSUE TITLE
Mesh Toolkit not compatible with Dynamo meshes?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#3749]
@hlp - this one's most probably for you, right? 
I couldn't find a GitHub repo for the Mesh Toolkit, so I am posting this here - hope that's okay.
I tried to use some of the methods from the Mesh Toolkit on a mesh pulled from a toposurface in Dynamo, but it seems they are incompatible. The same goes for meshes created with the Mesh Toolkit - Dynamo's built-in methods under Geometry.Mesh.Query do not seem to work with them. 
Is this by design or is it a bug that is going to be addressed at some point?
(Dynamo 0.7.5 stable release)

**Comment by hlp** [comment]
This is more of a bug. You're correct in pointing out that at the moment we have two parallel but incompatible Mesh types in Dynamo. You can convert between the two manually, it just requires some Python work. I've attached a graph converting between a Dynamo / Revit topo mesh and a MeshToolkit mesh

```
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
indexGroups = IN[0]

outerList = []

for i in range(len(indexGroups)):
	ig = indexGroups[i]
	innerList = []
	innerList.append(ig.A)
	innerList.append(ig.B)
	innerList.append(ig.C)
	
	outerList.append(innerList)
	
	if ig.Count == 3:
		continue
		
	innerList = []
	innerList.append(ig.A)
	innerList.append(ig.C)
	innerList.append(ig.D)
	
	outerList.append(innerList)

OUT = outerList
```
![mesh_picture](https://cloud.githubusercontent.com/assets/289141/6238420/b8e343ce-b6af-11e4-9783-df2510ec254f.png)

**Comment by andydandy74** [comment]
Thanks @ptierney , I must have missed your reply at the time. Will try your code. Maybe it would make sense to include a conversion node for that purpose in the Mesh Toolkit.

**Comment by ekatzenstein** [comment]
Can we leave this issue open? There still isn't a straightforward way to move from MeshToolkit meshes to Dynamo meshes.

**Comment by RodRecker** [comment]
Logged as MAGN-8326.

**Comment by andydandy74** [comment]
Reopened

**Comment by andydandy74** [comment]
In the meantime - I tested the solution provided above and it doesn't seem to be working for me. Instead I get one new mesh for every triangular face of the original mesh. Maybe I am not passing the arguments to the constructor as expected?
![meshconversion](https://cloud.githubusercontent.com/assets/3014437/9711056/c0731e72-5540-11e5-8ba8-f0a26da71edf.PNG)
Dynamo 0.8.2
MeshToolkit for Dynamo 0.8.2 dailies 1.22.1

**Comment by josols** [comment]
@ptierney thanks for the workaround on this, do you have an example the other way around also,  from meshtoolkit to a dynamo mesh? I can't find a Mesh.faceIndices node in meshtoolkit which does the same as its Dynamo counterpart. Any chance for an implementation of a transformation node anytime soon?

**Comment by rbosborne** [comment]
I second this request - what about conversion from mesh toolkit to Dynamo mesh?  DirectShape nodes seem to require a Dynamo Mesh.

**Comment by aparajit-pratap** [comment]
@rbosborne @josols we have a pending task that we are tracking to enable the interop between these two mesh types. We'll try raising the priority so that we can get to it sooner. Thanks.

**Comment by madeforworship** [comment]
Similar request to the above.  Would like to go from mesk kit mest to dynamo mesh to use with direct shape.

**Comment by alfarok** [comment]
I am closing this issue as there are known multiple OOTB workarounds and packages that can handle this functionality.  We will also keep this in mind next time we have the bandwidth to continue development on the meshToolkit package.
