### ISSUE TITLE
RayBounce.ByOriginDirection

### ISSUE THREAD

**Issue by DanTartagliaNBBJ** [DynamoDS/Dynamo#3750]
Hi,

This node takes a vector (direction). If the vector's length does not allow it to hit an object, should it return 'points'? I would think that it would not even if the direction eventually may hit an object. Am I incorrect?

![image](https://cloud.githubusercontent.com/assets/7255341/6201085/80f88fa2-b464-11e4-917c-ae456b8adc87.png)

**Comment by johnpierson** [comment]
Closing this as it is achievable by other means. 
![image](https://user-images.githubusercontent.com/15744724/46488074-ebe27280-c7be-11e8-8a6d-851885fa6daa.png)
If this is still an issue for you, feel free to open on the [Revit issues ](https://github.com/DynamoDS/DynamoRevit/issues)page again.

**Comment by rabiadhikari** [comment]
@johnpierson Could you please update the Dynamo map you have posted above? It barely reads and if you happen to have a dynamo file itself you would make me happy. Thank you for helping.
