### ISSUE TITLE
Sheet.Views

### ISSUE THREAD

**Issue by bdmackey** [DynamoDS/Dynamo#3763]
When using the sheet.views (build 0.7.5.3566) node if there is a Legend or Graphic Column Schedule on the sheet the result is Null.  Keynote legend and Schedules do not report a Null value however they do not get reported.  Is this a limitation or possibly a bug?

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
