### ISSUE TITLE
when project units set to meters in Revit Dynamo units seems to remain in feet NOT METERS

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#3765]
when project units set to meters in Revit Dynamo units seems to remain in feet NOT METERS

also see this forum post (Which I confirmed)
http://www.revitforum.org/dynamo-bim/23737-units-mismatch.html

**Comment by RodRecker** [comment]
@marcellosgamb Thnks for forwarding this Marcello. So in the other post are you saying this issue is specific to Rooms elements?

**Comment by marcellosgamb** [comment]
No, the in "other post" the import export of sat has the same problem of not importing at the right scale for every element i testing including rooms.... and walls

**Comment by ikeough** [comment]
Dynamo does not currently know anything about the display unit settings in Revit. Dynamo talks to the Revit API which expects decimal feet regardless of what you have your display settings set to. Additionally, the underlying unit assumption in Dynamo is currently SI units. So, as values enter into Revit from Dynamo, they are converted from SI units into decimal feet.

This will be changing soon. In the next major release of Dynamo, the SI unit assumption will go away, and all values coming from Dynamo will be treated simply as scalar values. The conversion applied when data goes into Revit will be based on your Revit project's display unit settings, so 1 unit in Dynamo will equal 1 unit in your Revit project.

**Comment by VenkatPR** [comment]
Hi Ian,
I would like to know that the unit conversion setting changes already been updated or not.
Right now i am using Dynamo 0.9.
when i was trying to find out the Foundation pad Coordinates the dynamo output x,y,z value is different than the Revit coordinates value.
Kindly help me.
Thanks in advance
Venkat

**Comment by ke-yu** [comment]
@riteshchandawar ?
