### ISSUE TITLE
get item at index not wrking on lists of lists

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#3781]
Hi, why is this not working ?
i would like to extract elements in sublist by intdex. indexes in every sublist are different:
![dynamo sort index](https://cloud.githubusercontent.com/assets/4834544/6250184/81405e60-b78c-11e4-9c46-520638c828bc.PNG)

**Comment by holyjewsus** [comment]
I think you need to map the get index node over the list of index lists

**Comment by ondejcik** [comment]
no when i do list.map. it creates extra sublists, based on tree data of index

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
