### ISSUE TITLE
Generic model line based

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#3787]
Hi, is there way to place line based generic model families with dynamo with 2 points, line vector or something similar ? Family instance by poit take only one point

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
