### ISSUE TITLE
Spaces missing from Categories Node

### ISSUE THREAD

**Issue by TVG271069** [DynamoDS/Dynamo#3791]
There is no access to the spaces object from Revit MEP trough the Categories Node

**Comment by dimven** [comment]
I believe it can be accessed with "Element Types" (Space) and the "All Elements of Type" nodes.

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
