### ISSUE TITLE
Watch node not updating

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#3792]
Hello,
I'm working with the current build (DynamoInstall0.7.6.20150219T1630.exe) and my watch node stays empty in all projects. I'm working on a german Windows 64bit. Had the same problem like @andydandy74 in issue #3744 which is fixed now but my watch node still isn't working the way it should.
Anyone else having this issue?
thanks, Fabian

**Comment by jnealb** [comment]
@redinkinc Hi: I am unable to reproduce a non-functional watch node in a similar environment with the same Dynamo build. Can you please provide us with a dyn that reproduces the issue?

**Comment by redinkinc** [comment]
@jnealb: thanks for the quick reply. I added a screenshot of the most simple project I can think of. The Watch node keeps doing nothing, no matter what input i will add.
![watchnode](https://cloud.githubusercontent.com/assets/3741716/6307982/a47131b0-b940-11e4-8adf-5e0b3a37281a.PNG)

**Comment by redinkinc** [comment]
deinstalled the daliybuild and installed 0.7.5 and everything works fine. Seems to be a problem in newer builds only...

**Comment by jnealb** [comment]
@redinkinc Thanks, that is clear! If you have not done so already, can you delete the Dynamo 0.7 folder under Program Files and re-install and try again?

**Comment by redinkinc** [comment]
@jnealb Thanks for the help. Deleting all files in ProgramFiles and ProgramData manually and reinstalling the daliybuild fixes the issue.
