### ISSUE TITLE
codeblock messes with floats

### ISSUE THREAD

**Issue by MBijsterbosch** [DynamoDS/Dynamo#3796]
i encountered an error with the code blocks in one of my scripts.

I've made a code block that transpose a list and splits the values.
The values are strings that are converted to floats decimal floats (example 43.440450.....)

In the top line the string is passed in the codeblock and afterwards converted to float, if i add 1 to it I get 44.440450 which is correct.

in the bottom line the string is converted to float before it is passed in the codeblock, if i add 1 to it I get 43.440451,  the 1 is added to the last decimal instead being added as an integer

Am i missing something that causes this error?
Dynamo build is 0.7.6.20150219T1630

download link for script
http://we.tl/sTPDox8cbi

![overview](https://cloud.githubusercontent.com/assets/10550107/6287599/029ea2dc-b913-11e4-882e-98a49626d260.JPG)
![detail](https://cloud.githubusercontent.com/assets/10550107/6287605/0818cf58-b913-11e4-996c-ff05ab451017.JPG)

Regards, Martin

**Comment by ke-yu** [comment]
hi @MBijsterbosch , can you attach a Watch node to output port of "X" of "transpose list and split output" node to check what's the value of "X"?

**Comment by MBijsterbosch** [comment]
@ke-yu The output from the X nodes seems to be the same in both cases.
![image](https://cloud.githubusercontent.com/assets/10550107/6388604/078523d8-bd9c-11e4-854c-1135dece08ed.png)

**Comment by ke-yu** [comment]
hi @MBijsterbosch , 'XYZ splitter, cleans() and CONVERTS TO FLOAT' node returns a list of **string** instead of floating values. Its python code is:
```
for itemA in outlist:
	for itemB in itemA:
		itemB = float(itemB)

#Assign your output to the OUT variable
OUT = outlist
```
where `itemB` isn't added to `outlist`. Then `+` will perform string concatenation operation.

But `Watch` no does have problem. It should display string in "". @riteshchandawar , we should log a bug.

**Comment by MBijsterbosch** [comment]
@ke-yu I dont know how i missed that.
changed the code of 'XYZ splitter, cleans() and CONVERTS TO FLOAT'  into

for item in templist:
	templistA.append(item.split(" "))
	
for itemA in templistA:
	for itemB in itemA:
		templistB.append(float(itemB))
	outlist.append(templistB[:])
	del templistB[:]

and it works fine.


Thanks!
