### ISSUE TITLE
SunSetting.Current

### ISSUE THREAD

**Issue by aliksumin** [DynamoDS/Dynamo#3797]
Hello. node SunSetting.Current don't automatically update if you change position of the sun, you need disconnect link between this node and next and connect again, then all is working. dynamo 0.7.6.4145

**Comment by ikeough** [comment]
Related to #4441.

**Comment by sharadkjaiswal** [comment]
@aliksumin, which version of Revit are you using?

**Comment by aliksumin** [comment]
Revit 2014
