### ISSUE TITLE
latest daily builds nodes disappear

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3798]
when opening a definition  from .75 versions the nodes are hiding.
only ctrl L bring them back

**Comment by ikeough** [comment]
@epeter- What do you mean by "hiding". Can you send a screen capture or a .dyn?

**Comment by epeter-** [comment]
hiding in terms of gone. even zoom all will not bring the nodes back.
but ctrl L does it (of course restructured)

Am 22.02.2015 um 07:29 schrieb Ian Keough:
>
> @epeter- <https://github.com/epeter-> What do you mean by "hiding". 
> Can you send a screen capture or a .dyn?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3798#issuecomment-75422334>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by andydandy74** [comment]
That sounds like blown-up node coordinates all over again, probably due to Dynamo removing the decimal delimiter in node coordinates on none-US Windows. 
Sounds very much related to #1703

**Comment by jnealb** [comment]
@epeter- @andydandy74 @ikeough @RodRecker @ramramps I suspect this is a symptom of MAGN-6384 rather than a localization issue. We are working on a fix for MAGN-6384 so we will know soon.

**Comment by jnealb** [comment]
@epeter- @andydandy74 We believe this is fixed with builds >= 0.7.6.20150227.

**Comment by ikeough** [comment]
@jnealb Closing :)
