### ISSUE TITLE
icon menue

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3801]
performance too poor!!!!!!!!!!

**Comment by monikaprabhu** [comment]
@epeter- Is this related to a specific functionality in Dynamo ? Can you post more details about the issue you are facing

**Comment by epeter-** [comment]
no it is not a specific issue, just a general perception
regards peter

Am 25.02.2015 um 03:03 schrieb monikaprabhu:
>
> @epeter- <https://github.com/epeter-> Is this related to a specific 
> functionality in Dynamo ? Can you post more details about the issue 
> you are facing
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3801#issuecomment-75891710>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by pboyer** [comment]
Closing this task, but don't worry, we're thinking about it.
