### ISSUE TITLE
how to publish UI nodes

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#3807]
Hello,
I have now published my first version of UI nodes (DynamoUtilities). However, the DLLs have to be copied manually to the Dynamo\nodes folder in order to be displayed in the node browser. Is there a way of publishing UI nodes directly? And how can I publish .dyn files allong with the nodes (right now add files in publish package only allows dll and dyf on my system)
Thanks, Fabian.

**Comment by redinkinc** [comment]
are there any changes yet?

**Comment by RodRecker** [comment]
@pboyer

**Comment by sharadkjaiswal** [comment]
@ke-yu is looking into this issue, being internally tracked by MAGN-5624.

**Comment by redinkinc** [comment]
seems to work in the current build. Thanks a lot, but notifying and closing the issue would be nice.
Fabian

**Comment by RodRecker** [comment]
@redinkinc Thanks for reporting that it works. Sometimes things appear fixed even though we didn't actively work to address it. We haven't closed the defect in our internal tracking system yet which would explain why it wasn't reported back here as fixed.
