### ISSUE TITLE
What time Chinese version and Chinese tutorial?

### ISSUE THREAD

**Issue by Cbise** [DynamoDS/Dynamo#3808]
What time Chinese version and Chinese tutorial? thanks

**Comment by kronz** [comment]
We are actively working on a localization project, and double byte (unicode) handling is available in the daily builds, but there is no active work on Chinese tutorials.  Perhaps you might be interested in creating such a thing?

One thing to keep in mind that much of Dynamo is an expression of "code" and will not be localized.  For instance, Element.Geometry or Point.ByCoordinates are technical terms and will not be localized, but other aspects, like top line menu items (File, Edit, View, Package, Settings) will be.
