### ISSUE TITLE
tell me why , I want to MM display

### ISSUE THREAD

**Issue by Cbise** [DynamoDS/Dynamo#3810]
![image](https://cloud.githubusercontent.com/assets/11164245/6334863/47c77d2c-bbd2-11e4-990f-d231016f8b1e.png)

Tell me why , I want to MM display

ds ver:DynamoInstall0.7.6.20150223T0323
rvt:2015 chinese
system:win7

**Comment by pboyer** [comment]
@ikeough

**Comment by Cbise** [comment]
@ikeough

**Comment by kronz** [comment]
@Cbise 
new major improvments to units are on the way, please take a look on the DynamoBIM.org forum and blog in the next few days.

Thanks
Z
