### ISSUE TITLE
Selecting group instances not working with the last couple of dailies

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#3860]
Seems to be broken with the last few versions of the dailies.
Tested both in R14 and R15.

![groups](https://cloud.githubusercontent.com/assets/7148394/6455808/389b03c4-c194-11e4-858a-1799daead985.jpg)

The last version that seems to work for me is 0.7.6.4102 (the one from 15th of Feb)

On another note, is it possible to use similar naming in the Dynamo builds? (the one in Help>About and the ones in http://dynamobuilds.com/)

**Comment by dimven** [comment]
Now after I downgraded to the older version, I do not have access to all element parameters( used in Get/SetParameterByName). Is anyone else experiencing similar abnormalities?

**Comment by kronz** [comment]
Hi @dimven , it looks like this is working in the daily from 3/2
Can you still reproduce this issue?
![2015-03-07_1849](https://cloud.githubusercontent.com/assets/3456818/6543802/b28ddd96-c4fa-11e4-8bbc-6b94c32825bf.png)

Thanks
Z

**Comment by dimven** [comment]
Thanks, Zach. Seems to be working again in the version from 3/2 (0.7.6.4256)
