### ISSUE TITLE
Rail geometry does not convert correctly in Dynamo

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#3862]
Rail geometry does not convert correctly in Dynamo

![railconversion](https://cloud.githubusercontent.com/assets/6132497/6457889/7873ab9e-c131-11e4-9c94-0a3128e71894.png)

using daily build (March 2 2015)

**Comment by johnpierson** [comment]
Still an issue in Revit 2019 + Dynamo 2.0.1

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2178).
