### ISSUE TITLE
Broken ref-link to ProtoInterface

### ISSUE THREAD

**Issue by ilayshp** [DynamoDS/Dynamo#3864]
Hello
Broken ProtoInterface in DynamoInstall0.7.6.20150302T2106.
I tried to run(soiids sample) - error in first node, ProtoInterface.dll can not load. No calculation.

Thank you.
Ilay

**Comment by sharadkjaiswal** [comment]
Hi Ilay, Sorry to hear that you are facing some trouble executing Dynamo at your end. Do you have Revit installed on your system and if it's installed can you please let me know the location of Revit installation. Dynamo expects Revit installation at "C:\Program Files\Autodesk\", which is a known bug and we are working on a fix for it.

**Comment by ilayshp** [comment]
Hello Sharad
I use - "P:\Program Files\Autodesk\Revit 2015"
But i try to keep "dll" folder from previous builds of dynamo and only renew several dll-s from libg_219 to "dll" directory.
I reinstall to DynamoInstall0.7.6.20150224T0012

**Comment by ilayshp** [comment]
0.8.0.671 - DynamoInstall0.8.0.20150309T0154
again, but it shows where.
how to resolve
1. i copy dll dir to new dynamo(0.8) dir
2. rename it to libg_0. all work and calculate non-revit nodes

i use standalone dynamo, not from revit

**Comment by ikeough** [comment]
Hi @ilayshp. Copying an old dll directory to a new version of Dynamo is definitely not supported. Is there a reason why you need to do this?

**Comment by ilayshp** [comment]
Hello Ian
Dynamo doesn't work me i made default installation
I have revit and dynamo at P-named disk, not C.
I found from dynamo 0.7.2, that if not do it i catch that dynamo can find several assemblies, like ProtoInterface(.dll) or if 0.8.2 - writes that cannot find LibG.ProtoInterface in p:\Program Files\Dynamo\libg_0\ ... i tried restasrt machine(thinking that need to register dlls after...nothing)
So i made experiment with libg_0 and etc. I do not store data at C:, only OS and several packages if authors made it. It works for me. Also seems Sol at dynamo form made such... look at http://dynamobim.com/forums/topic/dynamo-install-broken/

Thanks, Ilay
I'm sorry for my English.

**Comment by sharadkjaiswal** [comment]
With the latest 0.8.0 RC build, you should be able to seamlessly work with the standalone Dynamo, even if Revit was installed at any other location than “C:\Program Files\Autodesk\”. Try it out and let us know your comments.
