### ISSUE TITLE
General Performance, Render Performance / Hidden line / Wireframe

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3865]
I am experiencing performance lags in a model with 1500+ curtain panels, the creation of solids using OOTB nodes are extremely slow. it takes 10+ minutes creating these solids and to combine them for the calculation of volumes.......
active solids (displayed) influence the performence of panning nodes (not geometry)

**Comment by jnealb** [comment]
@epeter- Are you using sliders and Run Automatically in your definitions? If so, we are tracking it as MAGN-6530.

**Comment by epeter-** [comment]
no sliders, no automatisms
regards peter

Am 03.03.2015 um 14:33 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Are you using sliders and Run 
> Automatically in your definitions? If so, we are tracking it as MAGN-6530.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3865#issuecomment-76945392>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by jnealb** [comment]
@epeter- Can we look at your dyns?

**Comment by epeter-** [comment]
private mail yes
regards peter

Am 03.03.2015 um 17:26 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Can we look at your dyns?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3865#issuecomment-76979042>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by jnealb** [comment]
neal.burnham@autodesk.com

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
