### ISSUE TITLE
Warning: Point.ByCoordinates operation failed.

### ISSUE THREAD

**Issue by benzhang01** [DynamoDS/Dynamo#3873]
I got this message “Warning: Point.ByCoordinates operation failed. The type initializer for 'Autodesk.LibG.LibGPINVOKE' threw an exception.” 
I saved my Revit program in this location “ C:\Program Files\Autodesk\Revit 2014” and the dynamo “C:\Program Files\Dynamo 0.7”, Do you have any idea of the problem?

**Comment by sharadkjaiswal** [comment]
Seems like Geometry library is not properly configured. Can you please let me know the Dynamo version number where you face this issue? If this is an older version of Dynamo then can you please try on the latest build from http://dynamobuilds.com/

**Comment by benzhang01** [comment]
Hi Shrad:

Thank you for your reply,  I am using the version 0.7.5, should be the latest one. The following image is the error report and program installing path. Hope it could help you to figure out the problem.

[cid:image001.png@01D05681.E0DF39C0]
[cid:image002.jpg@01D05682.618EA560]

Regard

Ben


发件人: Sharad [mailto:notifications@github.com]
发送时间: 2015年3月4日 13:40
收件人: DynamoDS/Dynamo
抄送: Ben Zhang
主题: Re: [Dynamo] Warning: Point.ByCoordinates operation failed. (#3873)


Seems like Geometry library is not properly configured. Can you please let me know the Dynamo version number where you face this issue? If this is an older version of Dynamo then can you please try on the latest build from http://dynamobuilds.com/

—
Reply to this email directly or view it on GitHub<https://github.com/DynamoDS/Dynamo/issues/3873#issuecomment-77100271>.
____________________________________________________________
Electronic mail messages entering and leaving Arup  business
systems are scanned for acceptability of content and viruses

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.

**Comment by jokopperud** [comment]
I'm having the same issue. Dynamo version 2.0.1.5065

![image](https://user-images.githubusercontent.com/41875873/52210845-711e8680-2888-11e9-81f9-e4328a237817.png)

**Comment by mjkkirschner** [comment]
What version of revit are you using?

**Comment by GuiQr** [comment]
I have the same issue yith Dynamo Core 2.0.1.5055 / Dynamo Revit 2.0.1.5065

**Comment by akuc007** [comment]
I am new user to dynamo, very enthusiastic towards visual programing.

I have been breaking my head to create a single point is sandboox. I am opening a basic file which i got from Dynamo primer…but failed sofar.

Pleas refer the issue at
https://forum.dynamobim.com/t/dynamo-sandbox-without-revit-current-status/37589/9?u=akuc007
https://forum.dynamobim.com/t/dynamo-sandbox-without-revit-current-status/37589/10?u=akuc007
https://forum.dynamobim.com/t/dynamo-sandbox-without-revit-current-status/37589/11?u=akuc007

I could no able to make a single step in my learning. Help me to figure a way… Thank is advance.

**Comment by Amoursol** [comment]
Hello akuc007 - I have answered you on the forum! To cross-post on this:

Dynamo Sandbox will run stand-alone without any Autodesk software if you don’t want to use Geometry. [This blog post](https://dynamobim.org/a-new-way-to-get-dynamo-sandbox/) explains a little more about Sandbox.

If you want to use Geometry in Dynamo Sandbox (Which I believe is what you are asking) you will need to have a recent version of Revit, FormIt or Civil 3D. We typically support the most recent version and two versions backwards.

If you are looking for Geometry inside of Sandbox then please go to your [manage.autodesk.com](https://manage.autodesk.com/home/) tab and install one of these applications.
