### ISSUE TITLE
Select model elements

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3903]
At the moment it is impossible to select multiple elements individually.
Selections by clicks at element were helpful

**Comment by jnealb** [comment]
@epeter- Not able to reproduce this - can you give a specific example?

**Comment by epeter-** [comment]
dynamo offers tw option for selecting model elements 
1) select model element
2) select model elements
@1 obvious
@2 right now the workflow allows to select element by selectionbox. i would like to select multiple elements by "CTRL" select per mouseclick

**Comment by andydandy74** [comment]
:+1: 
And SHIFT for deselecting, please.

**Comment by epeter-** [comment]
tx andreas +1

**Comment by ikeough** [comment]
I know! I want to do this as well. There's one small problem. The Revit API allows you to select in one mode or another. You can be in box selection mode or multiple click selection mode, but not both. At least this is the way it was the last time I looked at the API. We'll have to see if they made improvements for 2016.

**Comment by dimven** [comment]
Guys might I recommend Julien Benoit's node "Tool.GetRevitSelection" from the steam nodes package? It fetches your selection from the Revit UI window. You can use any of the selection methods found in Revit. It's a temporary remedy at least.

**Comment by andydandy74** [comment]
@dimven - Yes, I've indeed been using that one as a workaround - it's really handy.
@ikeough - How about having two nodes: Select Model Elements (Box Selection) and Select Model Elements (Multiple Click Selection). If at some point in the future the Revit API allows for parallel selection modes you can always merge them back into one node.

**Comment by ksobon** [comment]
@andydandy74 I personally prefer "addition by subtraction" rather than "addition by addition". I would say this is something that we start knocking on Revit API's developers doors rather than here. Huh? This is just my opinion. If you all really want the ability to choose between the two modes, maybe its a boolean toggle on the selection node instead of another node. Let's keep the number of nodes to minimum before they get out of hand. :-)

**Comment by andydandy74** [comment]
@ksobon - I'd be perfectly happy with a toogle for the time being. In the long term, though, I think this would be a perfect example for impulses going to the Revit API development team from the Dynamo project - in the Revit UI we can combine the different selection modes and the API should expose that functionality eventually. I also agree with you that redundancies should be avoided (the large number of different Name nodes is a good example - I have a *single* Name node in Clockwork that works for *any* object that has a Name property).

**Comment by johnpierson** [comment]
Referenced on #355
