### ISSUE TITLE
daily build 20150209 forgets  installed packages

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3926]
installed packages are gone!
ok found that we are now 0.8.
copying all packages to 0.8 result in loss of nodes like element.solid.........

**Comment by ilayshp** [comment]
Hello
Look at https://github.com/DynamoDS/Dynamo/issues/3864#issuecomment-77868756

**Comment by dimven** [comment]
It's not just element.Solid. It seems all nodes related to Revit (DynamoRevitDS.dll) fail to load.

**Comment by jnealb** [comment]
@dimven @epeter- Are the Revit nodes "Unresolved" or absent?

**Comment by epeter-** [comment]
solved in latest daily

Am 10.03.2015 um 14:11 schrieb Neal Burnham:
>
> @dimven <https://github.com/dimven> @epeter- 
> <https://github.com/epeter-> Are the Revit nodes "Unresolved" or absent?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3926#issuecomment-78049409>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by dimven** [comment]
The whole Revit tab was missing from the library for me. It was as if I've started Dynamo in standalone mode even tho I started it from the add-ins tab. I'll check the latest daily first thing tomorrow.

**Comment by andydandy74** [comment]
same here, latest daily.

**Comment by mostaphaRoudsari** [comment]
E peter -

**Comment by sharadkjaiswal** [comment]
This issue should have been fixed with latest daily build as well as RC 0.8.0 build. Please try it out and let us know the feedback.
