### ISSUE TITLE
strange results after rerun

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3928]
i create sheets programmatically.
the sheet creation is done in python, same the placement on the sheet.
basically my code runs fine.....but!
i experience, that with the same data after rerun i get different (wrong) results.
i experience, that sometimes i get to sheets created instead of one.
i experience, that sometimes i get to sections created instead of one - with the same data.
might it be that the cache keeps data after running a definition?
first the wrong going with the same data and defintion secondly the correct sheet
![unexpected](https://cloud.githubusercontent.com/assets/6928491/6559990/ede697c4-c686-11e4-9681-97a400bd400e.png)
![expected](https://cloud.githubusercontent.com/assets/6928491/6559991/f0a055ea-c686-11e4-953c-343fa58bc902.png)

**Comment by pboyer** [comment]
Keep in mind that python nodes will not clean up their past results after a new run.  Is that the problem?

**Comment by epeter-** [comment]
exactly, how can i resolve that?

Am 09.03.2015 um 18:08 schrieb Peter Boyer:
>
> Keep in mind that python nodes will not clean up their past results 
> after a new run. Is that the problem?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3928#issuecomment-77897112>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by dimven** [comment]
Hi Peter,
I remember I had a similar problem a while ago and it was solved by wrapping my newly created elements with .ToDSType()

**Comment by epeter-** [comment]
@dimven i just ried the following:
after creation of a view i added it to an outputlist view.ToDSType(True)
the generated views i put on a sheet.
the sheet's output = viewsheet.ToDSType(True)
result is the same
sometimes yes sometimes no

**Comment by dimven** [comment]
Hmm sorry to hear that. I'm out of ideas. Just one thing - when you copy the python node, delete it and paste it again do you get a consistent result or is it still hit or miss?
 I'm asking because I'm trying to figure out if each python node has its own cache container or if the Dynamo process itself is storing the information.

**Comment by epeter-** [comment]
@dimven actually i am now debugging and finding a solution as i have to produce some hundred drawings........

**Comment by epeter-** [comment]
@pboyer is there a possibility to clean up former python results?
btw debugging the calculation results returns correct coordinates (point list)!

**Comment by holyjewsus** [comment]
Hi @epeter- Are you sure that the python node is actually re executing, this may be Dynamo's live runner attempting to not rerun the execution, if you force the python node to execute by disconnecting it, running the graph, and hooking it back up and rerunning the graph, is the output as expected every time (if you do that process every time)

as far as I'm aware the ironpython engine is being restarted each time the node is evaluated, but if it's not  actually evaluated again you might find strange behavior...

**Comment by epeter-** [comment]
@holyjewsus as i am in production and have to deliver my definition to produce my drawings i am some sort of desperate.
thats why i ecxamined each and every option to have it run. 
what i found out:
it is not python it is a dynamo memory allocation bug.
why?
1) when i have only 2 views to distribute on a sheet, everything is fine, reruns possible, 1 sheet produced.
2) when i am to 4 views, every still is fine.
3) from 5 views it starts to misbehave. 
3a) i get two drawings (i know that as i added a random nummer to the sheetname = debugging)
3b) 1 drawing is fine, the duplicate = wrong (shifted coordinates) 
3c) the coordinates calculated in python and forwareded to OUT node are correct
4) i removed the placement of views 7 + 8 to a second node.
4a) first half of the creation works, second works if i have just one of the views selected. maybe it is important: first views are sections, 7 = schedule 8 = axonometric
remarkable is that though sheet is transferred from node to node a sheet between the nodes (only holding the views from 1st sheet) is produced

looks like beeing a major bug in dynamo!!!!!!!!!!!!!!!!!!!!

**Comment by jnealb** [comment]
@epeter- @dimven  Have you tried reverting back to 7.5? Or is that the version that you are running?

**Comment by tatlin** [comment]
@epeter, can we get a copy of your files? @riteshchandawar and @jnealb,
please take a look

**Comment by epeter-** [comment]
pls send me your email adresses
regards peter

Am 11.03.2015 um 15:01 schrieb Matt Jezyk:
> @epeter, can we get a copy of your files? @riteshchandawar and @jnealb,
> please take a look
>
> On Wed, Mar 11, 2015 at 9:31 AM, Neal Burnham <notifications@github.com>
> wrote:
>
> > @epeter- <https://github.com/epeter-> @dimven 
> <https://github.com/dimven>
> > Have you tried reverting back to 7.5? Or is that the version that 
> you are
> > running?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DynamoDS/Dynamo/issues/3928#issuecomment-78262672>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3928#issuecomment-78267837>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by jnealb** [comment]
Neal.burnham@autodesk.com

**Comment by riteshchandawar** [comment]
You can send it to me on ritesh.chandawar@autodesk.com

Also I would like to know about your build number for Dynamo and which Revit you are using?

**Comment by epeter-** [comment]
revit is 2015 ur4

dynamo actually i am back to 20150302T2106

Am 12.03.2015 um 06:56 schrieb riteshchandawar:
>
> You can send it to me on ritesh.chandawar@autodesk.com 
> <mailto:ritesh.chandawar@autodesk.com>
>
> Also I would like to know about your build number for Dynamo and which 
> Revit you are using?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3928#issuecomment-78428032>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by epeter-** [comment]
@jnealb i stepped back to 7.5 same resul

**Comment by jnealb** [comment]
@epeter- Thanks for trying it

**Comment by epeter-** [comment]
@jnealb @riteshchandawar @tatlin @dimven @pboyer @holyjewsus 
finally i got a workaround running.
python = same as before.
step 1 = creation of all views, creating viewfilters, setting scale..........
then export to excel
step 2 = creation of named sheets for views.
step 3 = placing views on sheets ( ok that python was adopted to just fetching elements from lists)
working without problems (so far)

**Comment by holyjewsus** [comment]
hey @epeter- I'm glad you found a workaround, I wont have time to look at this any further util the weekend but after speaking with @pboyer briefly it seems that python has no idea how to cleanup any revit results by itself, and I guess this could cause some kind of strange duplication or errors if you were relying on the results not being duplicated in revit.

Can you explain what you're saving to excel?

**Comment by epeter-** [comment]
@holyjewsus michael, thanks for replying! honestly i don't believe that this is an issue with the python node. i was outputting coordinates as lists and checking them. the points were perfect. 
in my eyes there is a problem with the placement of views on sheets as this node broke in contex.
the workaround did nothing but seperating the tasks and praetaining the placement on sheets i removed the calculations involved completely.
let's see.
