### ISSUE TITLE
Package upload limit 15mb

### ISSUE THREAD

**Issue by kmorin** [DynamoDS/Dynamo#3931]
Currently, the limitation for publishing a package is 15MB. Need to remove/up the limit on this. I am trying to include a third-party python library that is ~30MB (to avoid users having to manually install this library)

**Comment by tatlin** [comment]
@hlp I believe you removed this restriction, no? Cc @pboyer

-matt

**Comment by pboyer** [comment]
This will be in 0.8.0. You can also use the dailies.

**Comment by kmorin** [comment]
Ok awesome. Thanks for the info.
