### ISSUE TITLE
custom nodes are gone ......again

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3948]
issue was fixed with 08.0.20150309T1748
and reappeares with 08.0.20150310T0953

**Comment by ilayshp** [comment]
Same here Peter - l0.8.0.20150310T0953
Not only custom, also from binary as zero-touch lib. Needs to recompile with renew SDK?

**Comment by holyjewsus** [comment]
Hey guys are these both regular custom nodes and downloaded packages?  If you check your %appdata%/roaming/dynamo folder there should be a new .8 folder for packages and custom nodes, do your custom nodes and packages appear in there?

**Comment by epeter-** [comment]
on my side it pertains both custom nodes and builtin nodes

**Comment by epeter-** [comment]
justed tested again. daily build as from 20150310T0953
all nodes here only getmidpoint missing. even after reloading it with packagemangager.
strange!

**Comment by sharadkjaiswal** [comment]
with 0.8, some of the folder structures are changed, we are working on the issue.

**Comment by ikeough** [comment]
@aparajit-pratap Was this ever resolved?

**Comment by aparajit-pratap** [comment]
Resolved.
