### ISSUE TITLE
Element Type: Ceiling doesn't work

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#3952]
"Ceiling" is not a recognized Type as Revit has two "types": Basic Ceilings and Compound Ceilings. So when using the following, nothing is returned.

![element type_ceiling](https://cloud.githubusercontent.com/assets/4656191/6602700/2fcddeda-c7eb-11e4-96a4-804e9e8413f6.png)

If I set to "CeilingAndFloor", it picks floors and both types of ceilings just fine. So this seems like an easily repairable problem to me...can it be fixed please? Thanks!

**Comment by dimven** [comment]
Seems to work for me with the "All Elements of Category" and the "Ceilings" category.

**Comment by dbaldacchino** [comment]
Yep it works with those nodes, but not the ones I posted.

**Comment by ksobon** [comment]
This seems to be working just fine in 1.3

![image](https://user-images.githubusercontent.com/529781/27800639-48fd29aa-5fe8-11e7-8d58-52f13cb1e9f8.png)

@kronz can we close this issue?
