### ISSUE TITLE
Select Model Element/s

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#3954]
I noticed that Select Model Elements (plural) always outputs a list, even when one object is selected. For consistency and to avoid unnecessary checking when creating custom nodes, can we make Select Model Element (singular) also output a list instead?

One more: The output port on Select Model Element (singular) should be renamed to "Element". Thanks.

**Comment by jnealb** [comment]
@dbaldacchino @pboyer I also vote we use names that differ by more than an 's' character.

**Comment by dbaldacchino** [comment]
I take it back...In Select Model Elements (plural), when one object is selected, the output is not a list. I'm just wondering whether it should be for consistency's sake. I'm building a custom node with recursion and it's failing with an array problem (going beyond the maximum because it keeps looping). I believe I have to evaluate what the input is so I can terminate it or it'll loop indefinitely, which is why if these nodes always output lists, then it would make life easier. Or so I think, but then again it could be because of my inexperience :) I'll post an example if I get it working to illustrate.

**Comment by Racel** [comment]
We do not plan on addressing this issue in the near term. It appears that the initial request is satisfied. Closing for now.
