### ISSUE TITLE
Category.Name broken?

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#3955]
Category.Name is not reporting the category of an element, but the Family Type. Shouldn't we be able to wire this node to an element (ex: a wall) and have it return "Walls"? Or am I mistaken and if so, what am I supposed to use to evaluate what object category I'm processing? Thanks.

**Comment by dimven** [comment]
All of the xxx.Name nodes report the name of the element as a string if such exists and are inter-changeable. I'd guess the team keeps them around so that no functionality gets broken. You can get the category name with a python one liner:

![name](https://cloud.githubusercontent.com/assets/7148394/6610703/009f0f54-c89e-11e4-9f0c-50f365a7c390.jpg)

**Comment by dbaldacchino** [comment]
Thanks a lot. It still makes no sense to me why the node is named "Category.Name" and it doesn't return the Category Name though! Thanks for sharing the Python script, I'll use that in the meantime to evaluate what object my custom node might be processing. This is something that should be available as a built-in node.

**Comment by epeter-** [comment]
@dbaldacchino  
actually the latest dailies are very inconsistent, i went back to .76 builds

**Comment by dbaldacchino** [comment]
@epeter- I agree. However my observation is based off the latest official stake release, not a daily build. I'm going back too add yesterday the latest build was missing Revit nodes. I went back one build and it worked, but kept breaking and forcing me to restart Revit, not finding core nodes, giving me different results every time I ran a definition, etc.

**Comment by ksobon** [comment]
@dbaldacchino actually I agree with @dimven here. category.Name is just a bad duplication of Element.Name where there should probably be only a single node that retrieves names of elements. In Dynamo 1.3 you can now get element.GetCategory and then query it for name like so: 

![image](https://cloud.githubusercontent.com/assets/529781/26564545/242566ea-44b0-11e7-8749-9450c72ef670.png)

cc: @kronz can we close this? It was resolved.
