### ISSUE TITLE
Contains / ContainsItem Strange Point Issue

### ISSUE THREAD

**Issue by mpdiker** [DynamoDS/Dynamo#3961]
http://dynamobim.com/forums/topic/point-in-list/

List.ContainsItem and in some situations Builtin.Contains commands are unable to distinguish between Point(0,0,0) and Point(2,2,0)

**Comment by sharadkjaiswal** [comment]
It's really strange, seems some problem related to hashing algorithm. We are working on the fix.

**Comment by ikeough** [comment]
Internal issue has been closed.
