### ISSUE TITLE
WISH - flat list to list of lists mapping per index

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#3988]
Not sure I'm describing this well in the title, however here's what I'm after.

Let's say I have List "A" and List "B". I make List "B" as part of a function and wire it to the f(x) port. I then wire List "A" to the list port. All members of List "B" are mapped to every member of List "A". This produces a new, larger list with multiple nested sublists, depending on the amount of nesting in each list. However what I'm after is as follows:

a) Let's say List "A" is a flat list whose count is "n". List "B" is a list containing "n" nested lists (list of lists). Each sublist can vary in size.
b) I want to create a similar map as described above, however I want to map the first member of List "A" with all the members of the first sublist in List "B", then the second member of List "A" with all the members of the second sublist in List "B", etc.
c) In summary, map f(List "B" Sublist index [n] - all members) to List "A" index [n].

For the life of me (and with no Python knowledge whatsoever), I cannot find a way to do this except through recursion. I could build a custom node that extracts the first index of each list and maps them, then moves on to the next, [n] times. However recursion is too slow and will not be scalable. Thanks.

**Comment by andydandy74** [comment]
Not sure if I understood you correctly, Dave, but may this perhaps be what you're after?
![combine](https://cloud.githubusercontent.com/assets/3014437/6657002/32334872-cb3d-11e4-923b-d04538ef6dcc.PNG)

**Comment by dbaldacchino** [comment]
Hi Andy, not exactly but similar. This came up agian for me recently and Zac helped out here:

http://dynamobim.com/forums/topic/building-lists-of-lists-from-other-lists-of-lists/

Topic: List and Item Matching. So it's doable, just not in one node. Still learning how to use nodes as functions! I'll close this out.
