### ISSUE TITLE
Numeric Slider Nicknames gone

### ISSUE THREAD

**Issue by urosjovanovic** [DynamoDS/Dynamo#4001]
I have a file saved with an older (Workspace Version="0.7.5.3566") version and when I open it in latest build all Nicknames from numeric sliders are gone, it just says "Numeric Slider" or "Double Slider" etc.

The names are correctly saved inside xml file. 

Any quick fixes/thoughts?

**Comment by urosjovanovic** [comment]
Here is a xml test file example:

http://pastebin.com/nMkbuG2h

**Comment by monikaprabhu** [comment]
@urosjovanovic Thanks for reporting the issue. We are tracking this internally at MAGN-6700.
This issue does not happen with files created in 0.7.6 - is it ok to upgrade to later version?

**Comment by urosjovanovic** [comment]
Well only if 0.7.6 can read files from older versions correctly :) Can you recommend some earlier stable branch I can clone for testing?

**Comment by monikaprabhu** [comment]
@urosjovanovic , Here is a workaround that might make you happy - 
1. Open the .dyn file in text editor and find and replace string Dynamo.Nodes.IntegerSlider with "DSCoreNodesUI.Input.IntegerSlider"  
2. If its double Slider Dynamo.Nodes.DoubleSlider with  "DSCoreNodesUI.Input.DoubleSlider"  and save the file. 
This should open file correctly in 0.7.6 and 0.8.0. 
While daily builds are still in testing, its wise to use latest build, as they have more bug fixes and additional functionality  than earlier ones.

**Comment by urosjovanovic** [comment]
Yep, that worked like a charm :) Thank you very much.
