### ISSUE TITLE
transactions

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4014]
use of dynamo often means to build own python nodes.
in these nodes quite often there is a demand for transaction control. especially to rollback transactions is a common requirement.
unfortunately the transactionmanager can't handle rollbacks.
if you try to use your own transactioncontroll you mostly fail because there are still transactions running though you definitely have started none!
quite a pain!

**Comment by johnpierson** [comment]
Transaction examples here. https://forum.dynamobim.com/t/naming-dynamo-transactions-in-revit/21149/6 and here https://forum.dynamobim.com/t/name-a-transaction/23990

**Comment by epeter-** [comment]
@johnpierson cleaning up the house;-)
this topic like the others from 2015 are "hopefully" resolved since ages!

**Comment by johnpierson** [comment]
@epeter- Definitely what I am up to! And I sure hope they are, but I am still investigating them as I go through to get this under control. You would be surprised how may wishlist items from years ago are still on my own wishlist as well. 😁
