### ISSUE TITLE
daily build 0.8.0 not working. 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4015]
Issue with the daily build:
http://dynamobim.com/forums/topic/lunchbox-not-working/#post-13632

Is there documentation for what changed in the latest release? It looks like my Python nodes are fried. 

Thanks!

**Comment by RodRecker** [comment]
Hi Konrad - we're working to get an updated build out today.

**Comment by RodRecker** [comment]
Hi Konrad - the new build is posted. Let us know if this improves things for you.

**Comment by FMFuk** [comment]
All previous dyn files cannot be run in 0.8.706, program exits each time.
Any migration processes are required ?

**Comment by monikaprabhu** [comment]
@ksobon I think its the same issue reported in here- https://github.com/DynamoDS/Dynamo/issues/3991

Please test in the latest build -0.8.0.756(DynamoInstall0.8.0.20150317T1508.exe). Seems to have fixed. If not please send me your file , because 3991 is fixed on this build.

**Comment by FMFuk** [comment]
Thanks, it is fixed using the latest build.
