### ISSUE TITLE
search library gives no result

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4023]
i tried to select the lunchbox room collector
my input "lunchbox" - nope 
my input "room" - nope
and again performance is veeeeeeeeerrrrryyyyyyy slow in searching library.
sometimes you feel like your computer is considering a lot more than you ;-)

**Comment by kronz** [comment]
Many search issues have been addressed, I think this is obsolete.  @epeter- please re-open if this is not the case
