### ISSUE TITLE
red code block unwiring

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4033]
pls don't unwire codblocks that turn red during changing by mistyping.
today i had to rewire miles!!!

**Comment by dimven** [comment]
Not really a solution, but if you do an undo (Ctrl+Z), the wires will reconnect, however you'll need to type in your changes again from scratch.

**Comment by andydandy74** [comment]
I agree, this is really a nuisance, especially when dealing with longer scripts...
And Ctrl+Z unfortunately still does not work reliably on non-US systems (#3218).

**Comment by Racel** [comment]
This is fixed and will be available in the 2.0 Release.  Closing. 
![image](https://user-images.githubusercontent.com/2551261/31631970-6c2b9c56-b289-11e7-9a17-a552fa121fea.png)
