### ISSUE TITLE
python bug!

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4036]
in order to crop / rotate drawings i examined the net and found jeremy's solution for that problem.
at first run everything worked fine!!!!!
copying and rotating the view.
unfortunately the rollback didn't work.
the rotation worked once not twice.
and that is my point. how can it be, that a script run in the same doc file on the same active view results differently???
tx peter

import sys
import clr
sys.exc_clear()
sys.exc_traceback = sys.last_traceback = None
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods

clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.DesignScript.Geometry import *
pyt_path = r'd:\IronPython\Lib'
sys.path.append(pyt_path)
from System import Array
from System.Collections.Generic import *
import math

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
# Assign your output to the OUT variable

debug = []
activeView = doc.ActiveView

duplicated = None

t = Transaction(doc)
t.Start("dup")

duplicated = doc.GetElement(activeView.Duplicate(ViewDuplicateOption.WithDetailing))
debug.append("1 duplicated")

t.Commit()

cropBoxElement=None

tgroup = TransactionGroup(doc)
tgroup.Start("tmp")
t2 = Transaction(doc,"tmp2")
t2.Start()
debug.append("2 duplicated invisible")
duplicated.CropBoxVisible = False

t2.Commit()

collector = FilteredElementCollector(doc,duplicated.Id)
shownElems = collector.ToElementIds()
debug.append("3 collect the invisible")
t2.Start()
duplicated.CropBoxVisible=True
debug.append("4 turn on invisible")
t2.Commit()

collector = FilteredElementCollector(doc,duplicated.Id)
collector.Excluding(shownElems)
cropBoxElement = collector.FirstElement()
debug.append("5 find crop box")
tgroup.RollBack()

t3 = Transaction(doc)
bbox = duplicated.CropBox
debug.append("6 duplicated cropbox activated")
center = 0.5 *(bbox.Max + bbox.Min)
axis = Autodesk.Revit.DB.Line.CreateBound(center,center + XYZ.BasisZ)

t3.Start("rotate")

ElementTransformUtils.RotateElement(doc,cropBoxElement.Id,axis,math.pi/6)
debug.append("7 and rotated")
t3.Commit()
# Assign your output to the OUT variable

OUT = debug

**Comment by dimven** [comment]
Hi Peter, 
I don't have much experience with multiple transactions but from my understanding, you still need to wrap all your revit transactions into the global Dynamo transaction (TransactionManager.Instance.EnsureInTransaction(doc))
Also an a "doc.Regenerate()" after the "tgroup.RollBack()" might be necessary.
Good luck!

**Comment by epeter-** [comment]
dimitar, thanks for replying.
according to transactions.
if you run a python script there seems to ba a global transaction 
started. - even if you unload the transactionmanager.
i found out by creating a script that rotates views. btw a mess in api. 
to rotate a view you have to copy one, find the cropbox, rotate it, 
delete the old one and rename the new one.
each step has to be done after committing the ancestor.
doing that in dynamo - python didn't work and caused revit to crash!
then i found out that you have to globally end a transaction (end 
transaction node) and than build a python node.
now it is doing what i want.
hence i felt like there should be improvement to the transaction 
handling especially transaction grouping and rollbacks.
back to your reply. i always ran in an error like there was an 
transaction already open.
tx and regards
peter

Am 24.03.2015 um 08:14 schrieb Dimitar Venkov:
>
> Hi Peter,
> I don't have much experience with multiple transactions but from my 
> understanding, you still need to wrap all your revit transactions into 
> the global Dynamo transaction 
> (TransactionManager.Instance.EnsureInTransaction(doc))
> Also an a "doc.Regenerate()" after the "tgroup.RollBack()" might be 
> necessary.
> Good luck!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4036#issuecomment-85372331>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2177).
