### ISSUE TITLE
latest daily 20150317xxx

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4037]
clipping planes dont work, model mostly invisible

**Comment by RodRecker** [comment]
Fix coming in the next build.


Rod




On Wed, Mar 18, 2015 at 5:42 PM -0700, "epeter-" <notifications@github.com<mailto:notifications@github.com>> wrote:


clipping planes dont work, model mostly invisible

-

**Comment by kronz** [comment]
Fixed
https://github.com/DynamoDS/Dynamo/pull/4032

**Comment by ekatzenstein** [comment]
I'm having this problem with the current version: DynamoInstall0.8.1.20150421T1658.exe

Posted here: https://github.com/DynamoDS/Dynamo/issues/4306

**Comment by ikeough** [comment]
@ekatzenstein if you're using the daily build, we changed out the visualization component and the far clip plane is being adjusted to accomodate models up to 2km in size. Hold tight, [it's not in quite yet](https://github.com/DynamoDS/Dynamo/pull/4291).
