### ISSUE TITLE
UI node library is not visible when located in package folder 

### ISSUE THREAD

**Issue by manuKrakow** [DynamoDS/Dynamo#4044]
Hi, 
Using DynamoInstall0.8.0.20150319T0206.exe version (0.8.0.772)
I have a component to expose some UI nodes. If this dll is in my  package folder, the dll is not loaded (UI nodes not visible inside the Dynamo library) 
If I copy this dll in ...\Dynamo 0.8\nodes folder all is fine - I could use this as short term solution
DynamoInstall0.8.0.20150317T2200.exe was ok but I can't rollback.  I need the fix for "Lynced LibG DLLs to latest. This fixes MAGN-6662"  to run my tests automation.

Should I do some specific actions to support properly my UI library (add satellite folder and  resources dll?) or this is an issue?

**Comment by ikeough** [comment]
@Benglin It seems as if `NodeModel` types are not being loaded from package contents. Did our work on refactoring the path manager affect this?

**Comment by Benglin** [comment]
Every time I choose to go on leave, somebody's life becomes a tad bit harder. This is one such instance. I might have missed this during the transition to new path management strategy, I apologize for the trouble this have caused you, @manuKrakow. I will look at this when I return to work tomorrow!

**Comment by Benglin** [comment]
An [internal tracked defect](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6744) is created for this issue.

**Comment by Benglin** [comment]
I have [developed a fix](https://github.com/DynamoDS/Dynamo/pull/4074), @manuKrakow could you please have a go with it and let me know how it turns out for you? Thanks!

**Comment by manuKrakow** [comment]
@Benglin, manual testing looks ok, I'm trying to figure out why the some of my unit tests failed.  I'll keep you posted.

**Comment by Benglin** [comment]
Hi @manuKrakow, last night @pboyer had did some serious restructuring and provided [a more thorough fix](https://github.com/DynamoDS/Dynamo/pull/4081) to the problem. If you could have a go with testing that, it'll be awesome. Thanks!

**Comment by kronz** [comment]
Waiting for feedback since May 2015, closing
