### ISSUE TITLE
Dynamo wont start

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#4046]
Installed a bunch of package updates (and a few new ones) and now Dynamo wont start:
![image](https://cloud.githubusercontent.com/assets/5300197/6733958/b0cea6f2-ce55-11e4-9e3d-bc8c143256d2.png)

**Comment by RodRecker** [comment]
@vasshaug Can you check which folder those packages are installed to? Which version of Dynamo are you using?

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.
