### ISSUE TITLE
Wishlist: Dynamo solids to Revit voids

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4061]
Probably the way that the solid geometry created in Dynamo is “imported” in Revit will be greatly enhanced soon. Anyway this can be an easy but practical possibility.

Recently I have been working many times creating solid geometry in Dynamo that will subtract other elements. But this operation is doing in Revit via “Cut”. This way of working is rather  convenient and flexible for many reasons.

Right now, every time that I create the solid geometry in Dynamo I have to:
1.Move the elements to Revit via ImportInstance.ByGeometry 
2.Explode the imported instance in Revit
3.Change the type of solid to “void”

A method that put the solid geometry in Revit directly as Revit solid would avoid having to explode the element every time. And ideally you will have the option that the element will be a “void”, so you don’t have to change the type manually .

**Comment by dimven** [comment]
Correct me if I'm wrong but I thought that functionality already exists with "Form.ByLoftCrossSections"
![capture1](https://cloud.githubusercontent.com/assets/7148394/6779881/4c652c10-d19b-11e4-87e2-6a0d987401d3.JPG)

**Comment by eproca** [comment]
Hi Dimitar,

Reading your answer I am wondering If I explained myself before. In the kind of workflows that I was thinking, the solid geometry used to cut has to be created using Dynamo own geometry tools. And normally, if they will be many elements to cut the same revit entities , they are joined in one single solid in Dynamo before importing in Revit. So later in Revit I can cut with hundreds of entities in one single and fast step.   

This workflow is working really well. The only thing I am wondering is why I have to explode every time in Revit the geometry created in Dynamo in order to be used to cut. If I am creating this solids with Dynamo linked to Revit and when imported in a Revit family and exploded they are recognized perfectly as solids…..why they are not translated as solids in first place instead of an imported instance?

Anyway I didn’t know that you can drive with Dynamo the creation of  Revit Loft Forms. Thanks

**Comment by dimven** [comment]
Seems like the API is pretty limited in that regard as well - the explode command is not exposed. However there might be a possible workaround with "FreeFormElement.Create()" if you can somehow trick the API and translate a Dynamo solid into a Revit solid.( xx.ToRevitType() converts solids into triangular meshes)

**Comment by eproca** [comment]
Thanks  Dimitar. Quite interesting the link. Even if the explode command is not exposed (by the moment) to the API, it seems that maybe it is not needed at all......

**Comment by dimven** [comment]
Hi Eduardo,
I toyed around with the above concept and came up with the following:

![2015-03-24_143721](https://cloud.githubusercontent.com/assets/7148394/6796792/0971884c-d234-11e4-872b-6f25ba0f2b1b.jpg)

Hope it helps.

**Comment by eproca** [comment]
Many thanks Dimitar,

I was posting this as something nice to have in the future. Anyway you can always manually explode the imported instance created.

So  I wasn’t expecting any solution for doing it NOW. I am impressed that you managed to do it. 

It is a pity that you cannot convert directly a Dynamo solid to a Revit solid via APi in the python script. The irony here is that the solids created in Dynamo when hosted in Revit are as “alien” to Revit as they were created with any other software and imported via SAT

I hope that this will change soon.

**Comment by eproca** [comment]
Hi again Dimitar,
Please,  can you copy and paste here the text of the python node?

Many thanks!!

**Comment by eproca** [comment]
Dont mind, the text was that long after all...

After playing a bit, it is really interesting. But in  different scenario. When you import solid geometry  in a family, maybe you will explode it. I mean solid geometry made in another software in general, not made with Dynamo hosted in Revit.

If the solid geometry is a bit complex, sometimes you will have problem with exploding it. Some elements will go away or even the whole thing. But, if via API you extract the geometry and create the freeform, it seems that you are not having any problem at all.

I have to try in more situations. But in a few that the explode were not working, now it is fine.

So maybe this is not just an alternative because currently explode is not exposed to the API. It looks like a better method that explode.

Again many thanks for this solution

**Comment by dimven** [comment]
Glad it helped. Sorry I forgot to post the code as well. Here it is for future reference:

import clr
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
clr.AddReference("RevitAPI")
import Autodesk
clr.AddReference("System")
from System.Collections.Generic import *
dataEnteringNode = IN
el1 = UnwrapElement(IN[0])
TransactionManager.Instance.EnsureInTransaction(doc)
opt1 = Autodesk.Revit.DB.Options()
opt1.ComputeReferences = True
geom1 = el1.get_Geometry(opt1)
enum = geom1.GetEnumerator()
enum.MoveNext()
geom2 = enum.Current.GetInstanceGeometry()
enum2 = geom2.GetEnumerator()
enum2.MoveNext()
x = enum2.Current
OUT = Autodesk.Revit.DB.FreeFormElement.Create(doc,x),el1
TransactionManager.Instance.TransactionTaskDone()

@ikeough 
Could we expect a proper Dynamo node that does something similar?

**Comment by ikeough** [comment]
Hi guys. This is a really cool hack.

The problem for us is that there is no way via the Revit API to import an ASM solid directly into Revit to be used for a FreeForm. We're working with the Revit team on a way to do this. 

We're tracking this internally as [MAGN-6769](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6779).

**Comment by dimven** [comment]
Hi guys,
 I had a look in the API documentation for 2015 the other day and the two new methods for "TessellatedShapeBuilder" and "DirectShape" that were introduced for IFC imports management peaked my interest. Would any of the two methods be useful for the above problem?

**Comment by josols** [comment]
Hi all,
I've also read about the 2016 API, and direct shape. It also mentions a new class called WireframBuilder which can create geometry by curves and points. For a layman like myself that sounds very promising. Or am I just being naive? :)

**Comment by dimven** [comment]
@josols 
As I mentioned above, Revit 2015 already exposes Direct Shape objects and I was able to create some from Dynamo solids with a method similar to the one shown above. I can see solids and surfaces being useful but how exactly can points and lines benefit you exactly? Keep in mind that you can already import any curve with "ModelCurve.ByCurve"

**Comment by josols** [comment]
@dimven 
If you've proceeded to import solids directly to, for instance, a mass in Revit, and also that the solid is able to be handled like any other Revit created solid afterwards, then that is the kind of functionality I was looking for. Is this functionality exposed by Directshape? The reason for mentioning curves/points was only because I thought it may provide a solution for creating a Wireframe of curves/points for Revit to create a solid from so that it is editable in standalone Revit afterwards. Would love to see some examples if you managed to import solids via DirectShape, and according to Ian Keough's response to my question at the Webinar at CASE the other day so would the developers! :)

**Comment by dimven** [comment]
I'm not sure if things have improved in Revit 2016 but from my experience in R15, DirectShape elements are pretty limited and bare-bone. They are not  editable. They cannot be used for references and thus cannot be cut or cut other elements. They do have some benefits over sat imports tho. They can be assigned to a category and thus you can apply parameters and graphical overrides to them.

![2015-05-12_17-41-28](https://cloud.githubusercontent.com/assets/7148394/7584354/7854abf6-f8cf-11e4-94ff-ac875c491347.png)

So for your example, you will have to perform all the solid boolean operations inside Dynamo and then import the end result as an un-editable  DS element. Not sure if that is a good work flow tho.

**Comment by eproca** [comment]
@dimven 
I have used until now quite a bit the workflow of creating  freeform element via the Revit API (always in generic families). To put in Revit geometry created in Dynamo or somewhere else. And the result is quite positive. Not perfect but far better that import and explode:

-Far more robust with complex geometry
-Diferent solids become diferent Revit entities (with import and explode they get unified in one element)
-If it makes sense and the solid is not very complex, direct edit with the grips will get the expected correct result
-they will cut any other solid geometry in the family. Or when inserted in the project (if the family is configured to do that)
-In a wall family (in place) the will work for limits of rooms

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2176).
