### ISSUE TITLE
How Can i Setup  Addons In Dynamo ?

### ISSUE THREAD

**Issue by Omidmr** [DynamoDS/Dynamo#4068]
How Can i Setup and load Addone IN Dynamo Also Svg ?

Thank's so much.

**Comment by kronz** [comment]
HI @Omidmr ,
Can you say a little more about what you are trying to do?  Expose the functionality of a Revit add-in inside of Dynamo?

**Comment by Omidmr** [comment]
hi kronz
i’m a MA Architecture Student

I have a problem about how to create the form Muqarnas by Dynamo
Muqarnas is a three dimentional decoration of Islam architecture.

I think I can create muqarnas with svg .

thanks
