### ISSUE TITLE
Addin organization in UI

### ISSUE THREAD

**Issue by ralvarez76** [DynamoDS/Dynamo#4084]
It would make for a cleaner UI if custom packages where grouped, organized and differentiated from the out of the box categories. Right now everything kind of meshes together which makes it harder to find what you want. It would be cool if maybe the 3rd party packages where under a "3rd Party" or "Downloaded Nodes" grouping, and that maybe their headings where differentiated with a different color or something.

The out of the box nodes should always stay at the beginning of the list.

**Comment by elayabharath** [comment]
Completely agreed, this was in the original library UI design and was dropped. Separating this would allow us to do neat things like searching within addins, linking that with package manager, issue updates for packages etc.

Is this what you are looking for?

![package-in-library](https://cloud.githubusercontent.com/assets/4365353/6817878/dc044ce2-d2e1-11e4-9bcf-e9d16ac6362a.png)

**Comment by williamwong** [comment]
I'll second this suggestion for separating out custom packages. Would make for a much cleaner navigation. Also, those tabs look nice...

**Comment by ralvarez76** [comment]
Yes that's more like what I was thinking. 

Regards,

Rafael Alvarez

**Comment by ikeough** [comment]
I'm closing this issue as the requested functionality is now available in recent builds as customizable library location. Please re-open if the new functionality doesn't meet your needs.

**Comment by ralvarez76** [comment]
Sorry to reopen this, but the customizable library location is about being able to share downloaded and custom nodes.

My original request was about separating the custom node libraries from the core Dynamo nodes in the UI. This is so the core functionality is always found at the top and easier for new users to find, and for us "teachers" to point to consistently. Downloaded and custom nodes would live after a break below the core nodes, and this list would potentially change according to the downloaded node libraries.

**Comment by jnealb** [comment]
@ralvarez76 @Racel @ikeough We are in the process of improving the Library ui and its search and thank you for your valuable feedback.
