### ISSUE TITLE
Unable to edit/open python node 

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#4085]
Hi

I'm using the latest daily build. When I place a Python script node and right click to edit, nothing happens.

**Comment by monikaprabhu** [comment]
@ParametricMonkey , I tried this on latest build -DynamoInstall0.8.1.20150324T2038.exe, I'm able to see the editor - Can you pleas give I a try on this build and let me know- Thanks

**Comment by ParametricMonkey** [comment]
I'm using the 0.8 candidate issue and its working now. thanks
