### ISSUE TITLE
CurtainPanel.Width & CurtainPanel.Height

### ISSUE THREAD

**Issue by fairy420** [DynamoDS/Dynamo#4086]
幕墙划分网格后，CurtainPanel.Width & CurtainPanel.Height提取的参数就反了，只有位于最底部板块的参数是正确的。
![image](https://cloud.githubusercontent.com/assets/11640589/6817164/429a0dfc-d2d8-11e4-8a31-dbd9791958d0.png)

**Comment by monikaprabhu** [comment]
@fairy420 , Thanks for reaching back to us. Which version of Revit/Dynamo  are you using 
Could you please post the files , for us take a look at?

**Comment by ikeough** [comment]
@fairy420 Any files you can provide us to reproduce this issue?

**Comment by smangarole** [comment]
The issue has been waiting for feedback for almost a year. Closing due to this reasons. Please reopen if this issue resurfaces.
