### ISSUE TITLE
Crashes when dynamo file is initiated

### ISSUE THREAD

**Issue by TravisMWilliams** [DynamoDS/Dynamo#4091]

**Comment by RodRecker** [comment]
@TravisMWilliams Sorry about this. Which version of Dynamo are you using?

**Comment by TravisMWilliams** [comment]
HI Rod,

I’m on version 0.8 (which I realize is beta). Thank you for the quick response.

Sincerely,

Travis Williams
Senior Technical Specialist

PHONE    412-932-2044
FAX         412-932-2045
MOBILE   724-713-2417

AE7 abu dhabi   amman   baghdad   bratislava   dubai   dusseldorf   pittsburgh   san francisco
2840 Liberty Ave  |  Suite 403  |  Pittsburgh, PA  15222  |  ae-7.com

Confidentiality Notice: This email message, including any attachments, is for sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by email and delete all copies of the original message.

**Comment by monikaprabhu** [comment]
@TravisMWilliams, can you give us more details?File created from which version are you trying to open. Or please share the file

**Comment by TravisMWilliams** [comment]
Hi Monika,

I am using release 0.8.0.706. I have attached the file for your review.

Sincerely,
Travis Williams

**Comment by monikaprabhu** [comment]
@TravisMWilliams - is there a link to the file or you can email me at monika.prabhu@autodesk.com
Are you seeing the issue while launching in Revit or Standalone?

**Comment by ikeough** [comment]
@monikaprabhu Did you ever receive a file?

**Comment by ke-yu** [comment]
@TravisMWilliams Close it as we can't get enough information to do investigation. Please reopen it if you can reproduce it.
