### ISSUE TITLE
Inconsistency in the units of imported sat files in 0.8

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4102]
The new units behaviour of 0.8 is a huge step in the right direction, IMHO. But there are some little issues pending yet.

From the second half of last year, Dynamo is recognizing the units information embedded in the sat files and making automatically the scale needed, assuming that the internal units of Dynamo are always meter. @ptierney confirm it here:
https://github.com/DynamoDS/Dynamo/issues/2864

This automatic scale doesn't make sense anymore in 0.8. But it is there yet.

**Comment by ptierney** [comment]
Hi @eproca, you are correct, with the units upgrade, SAT files are imported as meters, regardless of the base unit type (and scaled as needed). We're working on a way to expose import controls now. Stay tuned.

**Comment by RodRecker** [comment]
@eproca Yes - this is funny because we were talking about this exact topic during lunch here in Waltham - probably at the same time you were writing this. Thank you for the feedback and as Patrick says, stay tuned.
