### ISSUE TITLE
excel write

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4108]
today i created an exce output.
all listelements are of same length
longest list = 108 elements hence i generated empty elements to fill.
get an error that cannot be written to excel.
same definition with just removing one text field is working as expected

**Comment by monikaprabhu** [comment]
@epeter, can you post your dynamo file here. Im having hard time imagining what it might be like 
I tried to write an array with different sized list into excel and it fails. Please confirm if this is what you are seeing. 
![untitled](https://cloud.githubusercontent.com/assets/5218721/6938204/35ddda46-d894-11e4-829e-a4763f5000df.png)

**Comment by epeter-** [comment]
Exactly THW same issue

**Comment by monikaprabhu** [comment]
This issue is fixed . Please give it a try on latest daily build from 0.8.1.xx
