### ISSUE TITLE
Problem with Code Block

### ISSUE THREAD

**Issue by aamo87** [DynamoDS/Dynamo#4109]
Hi everybody,
I'm new to Dynamo and I have downloaded the Dynamo_language_guide.pdf and I think there is a problem with code block, when I try to make a Point.ByCoordinates. 
It is not listed with constructors.
![codeblock](https://cloud.githubusercontent.com/assets/11161225/6868087/31828976-d491-11e4-86f3-da872fbb47fb.PNG)
![codeblock1](https://cloud.githubusercontent.com/assets/11161225/6868088/31b0f82e-d491-11e4-8d06-236c130ffbda.PNG)

![codeblock2](https://cloud.githubusercontent.com/assets/11161225/6868528/fe366a70-d494-11e4-854d-32360acd157f.PNG)
![codeblock3](https://cloud.githubusercontent.com/assets/11161225/6868637/dc37dab6-d495-11e4-9960-6191686e2c8a.PNG)

**Comment by monikaprabhu** [comment]
@aamo87, do you have any packages installed ? Some of our packages have similar namespace which cerates conflict and this error is thrown- This is a bug and is tracked at MAGN-4633.You might want to look for packages similar to Mantis Shrimp etc.  I suggest that you uninstall them or delete them from the packages folder  C:\Users\..\AppData\Roaming\Dynamo\0.8\packages

**Comment by RodRecker** [comment]
Possible dup of #3208 
Tracking as http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6838

**Comment by ikeough** [comment]
Internal issue has been closed.
