### ISSUE TITLE
Dynamo 0.8.0 Release Candidate Posted

### ISSUE THREAD

**Issue by RodRecker** [DynamoDS/Dynamo#4114]
We have posted a release candidate for 0.8.0 and will be promoting it in the user forums. Please let us know if you see any issues with it. It is available from the builds site in the Daily Builds section:
http://dynamobuilds.com/

or directly at:
http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoReleaseCandidateInstall0.8.0.exe 

Thank you for your help validating this one and the many dailies that have preceded it.

**Comment by aamo87** [comment]
I installed it and I like the new additions. it is easier and nice, so far it's working fine but I think it's slower with codes running

**Comment by andydandy74** [comment]
@RodRecker - this version seems pretty stable. I ran a number of my larger graphs on it and didn't run into any major trouble. A couple of observations:
- Although the README that ships with the 0.8 RC says that the namespace collisions have been taken care of, I am still having some issues with autocomplete (#3208). For people just getting into CBNs this may be confusing behaviour.
- It must have happened somewhere between 0.7.5 and this release candidate, but now there is definitely no more reason to use the screenshot tool any longer (#4118). For me this is more than a little nuisance as it means I now cannot document larger graphs any more. I'm just not prepared to take twenty screenshots of a graph and have Photoshop stitch them together. In production, I need the ability to take screenshots of the entire graph. And I can't move to a version that does not do that for me.
- Found some other smaller issues (#4115, #4116 & #4117) that - after having checked this in 0.7.5, too - seem to have been around for a while.
- 0.7.5 introduced a bug (#3423) that prevents the conversion of Dynamo UV coordinates to Revit UV coordinates - it would be great if this were fixed at some point as it prevents placing panels on *planar* (and probably also revolved) surfaces in a meaningful way.

**Comment by jbenoit44** [comment]
Is running fine here, with some  issues in search engine (see forum). I was able to publish a custom package update, no issue except a small one: the CN was in edit mode when publishing, then just after it was completed (uploaded), all the wires disappear from my screen. closing CN and reopen fixed it, but was weird looking for a short period of time!

**Comment by RodRecker** [comment]
Thank you for the feedback on the 0.8.0 RC. I have just posted a new RC here:
http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoReleaseCandidate2Install0.8.0.exe

The main addition was some autocomplete improvements #4060 that we left out of the release by mistake.
