### ISSUE TITLE
List.Filter & Empty Lists

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4115]
Feeding an empty list into List.Filter will return a null value for both outputs and the following warning:
```The index is outside the given range. 
The index is outside the given range.```
Expected behaviour: return an empty list.
Version: 0.8 RC

**Comment by monikaprabhu** [comment]
@andydandy74 thanks for reporting the issue- Im tracking this at MAGN-6864- Is there any specific workflow you are trying to achieve with these nodes using Empty List.

**Comment by andydandy74** [comment]
This regularly comes up in model checking workflows when we encounter empty element collections in some project files. It's possible to code around this, but it adds otherwise unnecessary nodes to the graph.

**Comment by monikaprabhu** [comment]
@andydandy74 - This bug is fixed, Im closing this
