### ISSUE TITLE
Some Revit query nodes return null when input is an empty list

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4116]
Feeding an empty list into Topography.Points will return a null value and the following warning:
`Internal error, please report: Dereferencing a non-pointer. (3f47aacd)`
Expected behaviour: node returns an empty list
Version: 0.8 RC

**Comment by andydandy74** [comment]
The exact same thing happens when feeding an empty list into Element.Name node.

**Comment by monikaprabhu** [comment]
@andydandy74 Thanks for reporting this issue. Tracking this at MAGN-6873.

**Comment by monikaprabhu** [comment]
@andydandy74 , You can fix it by filtering the Empty List from the input or if you don't mind flattening the list , flatten removes Empty list automatically

**Comment by andydandy74** [comment]
@monikaprabhu - If my input is a single empty list, there is no way of filtering that out - it'll stay an empty list. Scenario / use case is the same as described in #4115, btw.

**Comment by andydandy74** [comment]
I have now seen this behaviour for the following nodes:
- Element.Node
- FamilyInstance.FacingOrientation
- FamilyType.Family
- Topography.Points
I am pretty sure that a number of other nodes are affected by this as well as it seems to be some general behaviour.

**Comment by ikeough** [comment]
@monikaprabhu Is this ready to be closed?

**Comment by andydandy74** [comment]
This is resolved in Dynamo 1.2 stable.
