### ISSUE TITLE
Categories dropdown fails for several categories

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4117]
Setting the Categories dropdown to several categories produces the following warning:
```Warning: Category.ByName operation failed. 
The selected category is not valid in this document.```
I haven't tested this for all categories, but the following categories produce the warning:
- ArcWallRectOpening
- CeilingOpening
- ColumnOpening
- DisplacementElements
- ElectricalCircuitTags
- FabricAreaTags
- FloorOpening
- HostFinTags
- LegendComponents
- RailingSystemTags
- Reveals
- RoofOpening
- RoomSeparationLines
- RvtLinks
- StackedWalls
- StairsTriserTags
- StructuralConnectionHandlerTags
- StructuralFramingOpening
- SWallRectOpening
- Tags

Version: 0.8 RC

**Comment by riteshchandawar** [comment]
Hello @andydandy74 I am getting the same warnings on 0.7.5 if I do it with Run Automatically ON.

On 0.8.0 it is noticeable mainly because it is running in automatic mode by default.

Can you check on 0.7.5 with Run Automatic ON.

I used Category node without connecting to any other node, and I used based revit file as our DynamoSample.rvt.

Thanks,
Ritesh

**Comment by andydandy74** [comment]
@riteshchandawar - Yes, I am aware that this bug is not specific to version 0.8 - it occurs in 0.7.5 as well, regardless of whether Run Automatic is enabled or not and regardless of which Revit project file is used.

**Comment by RodRecker** [comment]
@riteshchandawar Let us know if this is logged. Thank you!

**Comment by riteshchandawar** [comment]
Hello @andydandy74,

I have logged issue for internal tracking MAGN-6909

Will let you know once it is fixed.

Thanks,
Ritesh

**Comment by riteshchandawar** [comment]
@andydandy74 : Can you pick up the latest daily build and check at your side. We have fixed the issue for unnecessary warnings.

Thanks,
Ritesh

**Comment by andydandy74** [comment]
@riteshchandawar - I'll try to check asap, but I still need to get a fresh VM installed for testing the dailies.
