### ISSUE TITLE
Screenshot tool finally completely unusable

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4118]
Just when I thought Dynamo's screenshot tool couldn't get any worse, it actually does. Wow! ;-)
It seems like *now* all we get is the currently visible part of our graph (in the current zoom factor). 
Guys, please - I have a PrintScreen button for *that* functionality... :-1: 
I'll just treat this as an opportunity to summarize what is - in my opinion - wrong with the screenshot tool by describing which kind of functionality I would *expect*:
- ~~Always export the entire graph, regardless of currently visible part of the graph~~
- Constant image quality, regardless of current zoom factor (#364)
- ~~Always export the entire graph, regardless of graph location (#687)~~
- ~~Do not export the grid (#733)~~
- Let the image name be the same as the graph name (#2695)

Version 0.8 RC

**Comment by pboyer** [comment]
@ramramps

**Comment by monikaprabhu** [comment]
@andydandy74 , thanks for reporting issue - I see that it is exporting the  graph in to the image, there seems to be a problem saving the graphics.Tracking it here-"MAGN-6841- The image capture tool does not export geometry correctly". I've added the list of improvements mentioned by you in the issue as well.

**Comment by andydandy74** [comment]
Updated the list above to reflect what has already been fixed.

**Comment by kronz** [comment]
Closing as most of this is done

**Comment by Benglin** [comment]
Finally, finally, finally fixed with #6786

**Comment by ke-yu** [comment]
@Benglin :+1:
