### ISSUE TITLE
AdjacentFaces and AdjacentEdges methods are broken

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4120]
![02](https://cloud.githubusercontent.com/assets/6596042/6884628/d9449fac-d5fc-11e4-9b25-35337709f6c5.jpg)
It seems that these important topology tools are not working in 0.8 (in both last 0.8.1 build and 0.8.0 RC). I have not tested 0.7.5

**Comment by ikeough** [comment]
@ptierney Can you take a look?

**Comment by ptierney** [comment]
AdjacentFaces and Edges is not supported. I don't know why they are exposed.

**Comment by eproca** [comment]
AdjacentFaces and Edges were really killer apps of DesignScript from the very beginning.
Have we (or will we have) any equivalent tools?

**Comment by holyjewsus** [comment]
@eproca if you need basic topology tools now you can checkout the topology namespace in DynamoUnfold, theres no node for grabbing adjacent faces or edges, but it shouldn't be too difficult to build some on top of that code. also see the wiki here:https://github.com/holyjewsus/DynamoUnfold/wiki#topology

**Comment by eproca** [comment]
Many thanks @holyjewsus,  although I think I can deal with this with the default dynamo tools.

I have checked previous 0.7 builds and adjacent faces and edges were always exposed in the library , but never working. These specific topology tools maybe are not the most demanded tools, but they are really useful when you needed.

If you have experience making your custom librarys or DS functions , it is not a big deal to make your own tools for this. But if you have not, or you prefer not to deal with code at all,  it can be really a pain to obtain the equivalent functionality.

@ikeough  and @ptierney , can we expect to have this topology tools (or even support for non manifold solids) in the future?

**Comment by eproca** [comment]
I leave here for reference a DS function that gives the funcionality of adajcent faces.
![03](https://cloud.githubusercontent.com/assets/6596042/6936399/190a52e2-d852-11e4-979a-20c0dffa18d1.jpg)


This is the function 
def EdgeAdjacentFaces (So, Ed)
{
//So - Solid
//Ed - Edge of the solid

FaAll=So.Faces;
AdjFa=CompEdgeToFace(Ed,FaAll);

return=RemoveNulls(AdjFa);
};

It uses this nested function 
def CompEdgeToFace(Ed,Fa)
{
//Ed - Edge of the solid
//Fa - Face of the solid

//Ref point of the edge
EdCu=Ed.CurveGeometry;
RefPt=EdCu.PointAtParameter(0.5);

//Perim curves of the edge and their ref points
Sur=Fa.SurfaceGeometry();
SurPe=Sur.PerimeterCurves();
RefPtAll=SurPe.PointAtParameter(0.5);

//Check if ref points are the same
Chk=RefPt.DistanceTo(RefPtAll);
Chk2=Chk==0?1:null;
Chk3=RemoveNulls(Chk2);

return=List.IsEmpty(Chk3)?null:Fa;
};

I have made it in a rush. If you are going to use it, be aware of:
-It is comparing the (parametric) middle point of the edges. It worked well in the different solids I tried, but It haven't tested extensively. 
-It assumes that it is the same point if the distance between the points is 0. Initially I used a tolerance for this, bit it seems to work better in this way. 
-Right now there is an inconsistency between getting the surface geometry of an edge (action method) and the curve geometry of and edge (query method). This can change soon, so the 
function must be updated accordingly.

**Comment by sharadkjaiswal** [comment]
Adjacency query on topology nodes is available now. Please test it in the upcoming daily build.

**Comment by eproca** [comment]
That is great. Thanks a lot. 

Just a minor quibble related....its always very confusing that extracting the surface geometry of a face is an "action" method, but extracting the curve geometry or point geometry of a edge or vertex are query methods.

I dont mind if they are "action" or "query", but please make them consistent

**Comment by jnealb** [comment]
@eproca An interesting comment for @Racel - thanks.

**Comment by sharadkjaiswal** [comment]
Adjacency query on topology is now available, please check out the latest 0.9.1 daily builds.
