### ISSUE TITLE
Switching between Dynamo versions

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4126]
I really like the fact that there's a version switcher for Dynamo 0.7 and 0.8 - but it shows some - in my opinion - erratic behaviour:
After having switched the version the version switcher is greyed out:
![nomoreswitchingversions](https://cloud.githubusercontent.com/assets/3014437/6893002/80b80518-d6c9-11e4-8cbf-82e52691e537.PNG)
Only after restrating Revit is it possible to use the version switcher again:
![versionswitcherafterrestart](https://cloud.githubusercontent.com/assets/3014437/6893012/970800de-d6c9-11e4-82ea-03f05f690b88.PNG)
The previous version switcher (0.63 vs. 0.7) worked differently: after switching to a different version we had to restart Revit (and were notified of that necessity) which I found a lot more logical in terms of UX.

**Comment by riteshchandawar** [comment]
@andydandy74 : Here we have improved on one step, with old version selector if you want to switch to different version you were restarting revit, but with new Version Selector, it will allow you to select different version **without exiting Revit** . (only first time) But once you select required version and launched Dynamo then you need to restart Revit to change the version. (which is similar to old behavior.)

**Comment by andydandy74** [comment]
Well, I liked the old version switcher better. A *real* improvement would be to be able to freely switch *back and forth* between versions *without* having to restart Revit. If that's not possible, I don't see the benefit in having a greyed out button in my ribbon instead. But it looks like this is how it's going to be now so I'm closing this. Maybe it just takes some getting used to.
