### ISSUE TITLE
WISH - Family Orientation

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4130]
Hi, is there way how to obtain family orientation ? Location point plus angle ? 
thanks, It would be very usefull.

**Comment by andydandy74** [comment]
Haven't tried it myself yet, but there's a package called ```Elements.position_rotation_mirrored``` on the package manager that might help. For retrieving element locations you can try the built-in node FamilyInstance.Location which works for all placeable families or alternatively Element.Location from package Clockwork which should work for soem system families (e.g. walls) and line-based families as well.

**Comment by monikaprabhu** [comment]
@andydandy74 thanks! I see that Elements.Position_rotation_mirrored returns rotation and Family instance.Location returns the coordinates of location.
![untitled](https://cloud.githubusercontent.com/assets/5218721/6915240/f967ee50-d7c4-11e4-8b5d-3f7c046f6dad.png)-So I'm closing this issue
