### ISSUE TITLE
Generic model line based

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4131]
Hi, is there a way to place line based generic model families with dynamo with 2 points, line vector or something similar ? Family instance by poit take only one point, I cant find any other way.

**Comment by monikaprabhu** [comment]
@ondejcik , you can use Adaptive Component.ByPoints.There is a sample file delivered in Dynamo which demonstrates the placement of AdaptiveComponent - Help->Samples->Revit->Place Adaptive Components. Pls let me know if that solved what you were looking for

**Comment by ondejcik** [comment]
Hi, thanks for answer, i am aware of adaptive point families, issue here is i want to place linebased family inside other generic model family and there it is not possible to use adaptive points.

**Comment by smangarole** [comment]
Please open a new issue if there's an actual bug.
