### ISSUE TITLE
Wish - Node Groups

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4132]
Hi,
It would be very helpfull to have a possibility to group node silimar to grashopper. There are many situation where creating node is unpractical, but certain organization would be necessary. thanks, Vladimir

**Comment by lillismith** [comment]
Try out our special build availalbe through this forum post and send your feedback! http://dynamobim.com/forums/topic/groups-special-build-ready-for-feedback/

**Comment by pboyer** [comment]
This feature should be available in master in the near future.  We'd love to see your feedback on the special build.
