### ISSUE TITLE
Internal Error:Non Pointer Issue

### ISSUE THREAD

**Issue by cadtot** [DynamoDS/Dynamo#4134]
Ask me to report this issue on version 0.8.0.856, clip attached
![2015-03-31_12-01-04](https://cloud.githubusercontent.com/assets/8200768/6908967/0847b86e-d79e-11e4-93c8-1727c65229ae.png)

**Comment by RodRecker** [comment]
Logged as http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6873

**Comment by andydandy74** [comment]
duplicate of #4116?

**Comment by ikeough** [comment]
Internal issue has been closed.
