### ISSUE TITLE
File Encoding Issue

### ISSUE THREAD

**Issue by cadtot** [DynamoDS/Dynamo#4148]
I am importing data from a .txt file and having trouble with the file encoding (®).
![2015-03-31_12-07-08](https://cloud.githubusercontent.com/assets/8200768/6938748/4ea53884-d8c2-11e4-8272-ba489ee740f7.png)

Issue happens using 0.8 candidate (0.8.0.856) running on Revit 2015. [20150303_0715(x64)].

It does not seem to read the .txt files as ASCII. in the same way as Notepad++ does.  Copy/clip from Notepad++ works fine but the process becomes very manual.

**Comment by monikaprabhu** [comment]
@cadtot , How is the content organized in your text file- What are the characters that are not imported correctly? Can you post the file please

**Comment by cadtot** [comment]
Example files attached.

Cheers

Kerry


Kerry Thompson

www.kta.co.nz<http://www.kta.co.nz/>

+64 21 443 721

kerry@kta.co.nz<mailto:kerry@kta.co.nz>

**Comment by monikaprabhu** [comment]
@cadtot - I can reproduce the issue - Thanks for reporting it - MAGN - 6891. Read Text does not display ASCII character, Instead a question mark is  displayed. You can directly copy paste text in code block nodes. It supports the characters in your file.
