### ISSUE TITLE
Code - Port - Wire alignment way off

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4150]
Ver: 0.8.0 Release Candidate

In tall code blocks, the node of a variable does not align with the corresponding code. Further the connector and node too do not  match graphically (functionally it is fine)

![20140401-1](https://cloud.githubusercontent.com/assets/5621624/6941850/cce55408-d8a0-11e4-9ae2-7dec7a830114.jpg)

Regards,
Vikram Subbaiah

**Comment by monikaprabhu** [comment]
@testingwaters ,How long is your code. I tried  few options of  long code and could not reproduce - could you please share you code ?

**Comment by testingwaters** [comment]
I've uploaded a file at 
http://a360.co/1MJV6lH

Regards,
Vikram Subbaiah

**Comment by jnealb** [comment]
@ramramps We missed this?

**Comment by ramramps** [comment]
@jnealb - Just checked the file.  I dont think this is something related to port snapping. Have to check on the alignment.

**Comment by ikeough** [comment]
#4168
