### ISSUE TITLE
Dynamo 0.8 and grid/plane/CS representation when working in milimeters

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4155]
Hi,
I love the new possibilities and the easier workflow introduced with v 0.8.

However I like to keep things visual and check from time to time if everything is aligning properly.
With 0.8, when working in millimeters, all of Dynamo's visual tools are tiny and don't seem to be annotative(scale up with your units).

This necessitates the need to zoom in to ridiculous levels before being able to see any visual cues:
![2015-04-02_110335](https://cloud.githubusercontent.com/assets/7148394/6957004/b9aea28a-d928-11e4-8f44-dd1f58b29a93.jpg)

**Comment by jnealb** [comment]
@dimven Can you please send me your dyn file? neal.burnham@autodesk.com

**Comment by dimven** [comment]
I'm not sure if the problem is in my system but the last few daily versions after 0.8 have completely lost the ability to display any geometry larger than a few hundred units.
![2015-04-21_16-46-25](https://cloud.githubusercontent.com/assets/7148394/7248603/841eb5d8-e846-11e4-883f-2355b94a5733.png)

**Comment by ikeough** [comment]
Hey all. Yes, the far clip plane in the new viewer is really small. There is an [outstanding PR](https://github.com/DynamoDS/Dynamo/pull/4291) that fixes this, increasing the far clip plane to 2000000 units (2km in mm). There are just a couple more things to fix in that PR before it comes in. Hold tight.

**Comment by HyunuKim** [comment]
Agreed. It's really annoying. How can I review it without view? There should be some options to control the size of those elements.

**Comment by dimven** [comment]
Planes and coordinates systems are still very hard to see when working in millimeters (or inches). Are there any plans to correct this?

**Comment by dimven** [comment]
I really like the way the new direct manipulation gimbal scales proportionately to your zoom factor. Would it be possible to extend this scaling feature to the coordinate system and plane models?

**Comment by kronz** [comment]
Created internal tracking task
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9556
Not sure if we will get to this one for next release but will try

**Comment by ikeough** [comment]
@kronz Bumping to critical because you mentioned "next release" ;)
