### ISSUE TITLE
Lists actions fail inside DS definitions.

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4165]
Is the below expected behavior?
![capture1](https://cloud.githubusercontent.com/assets/7148394/6977886/8551a9ca-d9f9-11e4-82b8-983b58a18eda.JPG)

**Comment by testingwaters** [comment]
![20140403-1](https://cloud.githubusercontent.com/assets/5621624/6978558/9dd4bf20-d9f2-11e4-8554-886617c67818.jpg)

Regards,
Vikram Subbaiah

**Comment by dimven** [comment]
I see. Thank you, Vikram

**Comment by dimven** [comment]
I thought the above was the root of my problems, but it seems that is not the case.
Common list actions seem to be ignored in both imperative and associative codes.
![2015-04-04_08-59-50](https://cloud.githubusercontent.com/assets/7148394/6990906/41b9d2d4-daab-11e4-8efb-00c4b4309074.png)
Am I doing anything wrong in the above image?
