### ISSUE TITLE
Input port for variable disappears

### ISSUE THREAD

**Issue by testingwaters** [DynamoDS/Dynamo#4167]
Ver: 0.8.0 Release Candidate

Input node for variable disappears on trying to extract deeper data

![20140403-2](https://cloud.githubusercontent.com/assets/5621624/6980436/42fe5fb2-da0f-11e4-9ae6-2fd0b369dae4.jpg)

Regards,
Vikram Subbaiah

**Comment by testingwaters** [comment]
A more stable approach seems to be...
a= BoundingBox.Geometry(AxisIntersect);
b=a.MinPoint;

Combining 'BoundingBox.By Geometry' and 'Min/MaxPoint' in one line seems to generate errors at a later stage, while working properly initially.

Regards,
Vikram Subbaiah

**Comment by kronz** [comment]
tracking internally with http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6897

**Comment by dimven** [comment]
Any progress on this issue? A lot of work flows written mostly in DS created before 0.8 will need to be thoroughly edited otherwise.

**Comment by RodRecker** [comment]
@dimven We haven't been able to focus on this one yet. We will know more in a week after completing scheduling for our next round of work.

**Comment by aparajit-pratap** [comment]
This will be fixed in the next build. Thanks for your patience.

**Comment by aparajit-pratap** [comment]
The fix is in. Please let us know if y'all still face issues.

**Comment by dimven** [comment]
Thanks a lot. Downloading now.

**Comment by dimven** [comment]
The latest daily 2015-05-21T07:44:58.000Z DynamoInstall0.8.1.20150521T0044.exe seems to be working as expected. Thanks a lot!
