### ISSUE TITLE
Long comments in CBNs causing linebreak and port alignment issues

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4168]
While in Dynamo 0.7.5. long comments in CBNs only screwed with the port alignment (#2395)...
![longcomments075](https://cloud.githubusercontent.com/assets/3014437/6984651/43e7ba06-da2b-11e4-96ad-00140e78cc27.PNG)
... Dynamo 0.8.0 RC will also not create automatic lienbreaks for them:
![longcomments080](https://cloud.githubusercontent.com/assets/3014437/6984661/6b480952-da2b-11e4-8ccb-0e4fab0e614f.PNG)

**Comment by dimven** [comment]
![2015-04-04_09-13-17](https://cloud.githubusercontent.com/assets/7148394/6990900/e3365fc0-daaa-11e4-858e-58d6b7edb686.png)

**Comment by monikaprabhu** [comment]
@andydandy74 ,@dimven -  Definitely it would be easy if there were automatic line breaks - What would be your criteria for setting creating  line breaks?

**Comment by andydandy74** [comment]
- Define which characters can constitute a line break (typically " ", "-", "/" & "\" so long URLs and file paths can be split as well
- Define the maximum amount of characters per line (typically about 80)

There must have been some algorithm for this in the CBN editor previously - why not just recycle that one?

**Comment by Racel** [comment]
We will likely not address this in the WPF UI, but will consider this for CBN improvements in the next generation UI. Closing this for now.
