### ISSUE TITLE
Select Divided Surface Families ignoring triangle patterns elements

### ISSUE THREAD

**Issue by BrianFraumeni** [DynamoDS/Dynamo#4192]
Select Divided Surface Families node, when selecting a triangular pattenered surface, ignores every other curtain panel. This results in a checkerboard selection.

Other selection methods which utilize a sorting logic (by Element.BoundingBox > MinPoint > Point.Z, Y, X, ...) has difficulty sorting the Point.Y , depending on the orientation of the triangle vertically. This work around is not sufficient apparently.

![image test_select divided surface families_2](https://cloud.githubusercontent.com/assets/2466772/7035520/41984246-dd3e-11e4-8e9f-812f46b304a0.JPG)

**Comment by monikaprabhu** [comment]
@BrianFraumeni  interesting pattern. Can we have your file to try it out ?

**Comment by ikeough** [comment]
@BrianFraumeni Any files we can have to test this?

**Comment by smangarole** [comment]
The issue has been waiting for feedback for almost a year. Closing due to this reason. Please reopen if this issue resurfaces.
