### ISSUE TITLE
Wish: Keep Dynamo icons in the ribbon in one group

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4194]
Other addins can get in between the version selector and the dynamo icon. Yes, we can change this manually by moving stuff around in the ribbon but this still may be confusing for new users. Why not keep both icons in one group?
![dynamoribbon](https://cloud.githubusercontent.com/assets/3014437/7040238/2c0cf482-ddcd-11e4-80de-c4ae6ee94a6a.PNG)

**Comment by ikeough** [comment]
That's a good point @andydandy74. The version selector and Dynamo are two separate external applications. It might not be possible to combine them into one "panel". At the very least we should change the name of the Dynamo panel from "Visual Programming" to "Dynamo" so it shows up next to the other one.

@sharadkjaiswal, you've been working on the version selector as of late. What are your thoughts?

**Comment by sharadkjaiswal** [comment]
sure, I'll take a look.

**Comment by andydandy74** [comment]
@ikeough - I don't think addins are ordered alphabetically in the ribbon, it's probably the order in which they were installed...

**Comment by monikaprabhu** [comment]
This is tracked at MAGN-7250.

**Comment by sharadkjaiswal** [comment]
@andydandy74 would like to provide your comment on the proposed fix?

**Comment by andydandy74** [comment]
@sharadkjaiswal - This looks like a great improvement. Is this in the dailies?

**Comment by sharadkjaiswal** [comment]
Yes, its available on dailies now.
