### ISSUE TITLE
Dynamo crashes when creating custom nodes

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4202]
I am not sure what the cause is, but its been crashing on me whenever i try to make a custom node. Consistently, on multiple occasions. 

![image](https://cloud.githubusercontent.com/assets/529781/7055027/8e5363ba-de0e-11e4-9c0e-30ff96a9206c.png)

**Comment by kronz** [comment]
Hi Konrad,
What build are you using?
Thanks
Z

**Comment by ksobon** [comment]
I was on a daily from maybe a week ago.

**Comment by monikaprabhu** [comment]
@ksobon , is this still an issue ? I cant see the full stack in your image . Can you copy paste the text ?

**Comment by monikaprabhu** [comment]
@ksobon - Is this fixed? if not please reopen.
