### ISSUE TITLE
only single (1) file at a time can be added to Package via Package Manager

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4204]
It's extremely inefficient to be able to add only one file to a package at a time. I literally had to click "Add File" 6 times to add a few more files to my package. Not to mention that it kept going back to default location so not only did I had to add them separately, but also had to navigate to a folder where my files where 6 times. :-1:

**Comment by pboyer** [comment]
It should be possible to select multiple files from this dialog and it should reset to the last location.  I have create an internal task to fix this regression.

**Comment by ksobon** [comment]
Yeah, I agree it definitely was possible before. Thanks for looking at it.

**Comment by RodRecker** [comment]
Logged internally as http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6975
