### ISSUE TITLE
Periodic refresh + Web Request Node = insta crash ?

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4217]
Periodic refresh is a great idea but it seems to default to 100ms every time it is turned on and not remember the last setting.
Combine that with the Web Request node and it seems that, at least for me, it is crashing every time I turn on Periodic run.

**Comment by dimven** [comment]
The crash seems to be limited to R14. It's not crashing things in R15 so far. However the run periodically doesn't seem to be doing anything?
I am querying the following url: https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new
I specifically chose this website because it does not use any fancy javascript. It will generate an integer every time you refresh. However on canvas, the refresh simply isn't happening. Any ideas?

**Comment by elayabharath** [comment]
Able to reproduce. Tracking internally MAGN-7059

**Comment by dimven** [comment]
This is working well now on R15 with the latest daily and the default periodic run has been bumped to 1000ms which is much more reasonable.
