### ISSUE TITLE
Dynamopackages.com listed as Malware

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4218]
Running a Cisco VPN client, I get the following message when trying to access dynamopackages.com:
![malware](https://cloud.githubusercontent.com/assets/3014437/7082430/50cc8e12-df54-11e4-9397-950d61e5ebd6.PNG)
Some more info on this:
http://www.cisco.com/c/en/us/support/docs/security/web-security-appliance/117851-technote-wsa-00.html
It's not a big deal for me as I can just turn the client off, but maybe this should be addressed anyway as it may also affect other users behind company firewalls that are driven by web reputation filters etc.

**Comment by monikaprabhu** [comment]
@andydandy74 , is there an option to add it to secure sites ?Can you please check it

**Comment by ksobon** [comment]
So I had exact the same issue and my IT folks called your web hosting service to take care of that, but I have no idea what happened beyond that. I agree its annoying and quite not a good business for Dynamo since my Package Manager doesn't work and I have been using a guest WIFI to update my packages.

**Comment by maharr** [comment]
I've had exactly the same issue with fortiguard web filtering software, I've also managed to get the IT guys to add an exception the the firewall

**Comment by monikaprabhu** [comment]
Thanks for reporting the issue - I'm tracking this at MAGN-7163.If we want more information will get back.

**Comment by ikeough** [comment]
@kronz Can you provide an update?

**Comment by kronz** [comment]
There is a larger project underway to modernize the Package manager web interface, one that will be more integrated with the application itself.  We have no plans to fix DynamoPackages.com, rather to replace that particular type of web presense.
