### ISSUE TITLE
Arc.ByCenterStartPointEndPoint error

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4226]
I am not sure what is causing this error, but it seems like I can't get the Arc method to work. This is in the 0.8.0 stable build. 
![untitled-1](https://cloud.githubusercontent.com/assets/529781/7095165/06f14020-df96-11e4-8f6d-4262752eab55.png)
Were there any changes to this method? 

Thank you,

**Comment by monikaprabhu** [comment]
@ksobon ,Without seeing the script its difficult to debug the error.  Looking at your error it looks like some objects passed to arc may be null. Its working at my end on DynamoReleaseCandidate2Install0.8.0.exe 
![untitled](https://cloud.githubusercontent.com/assets/5218721/7104730/ce9b930e-e127-11e4-9853-893e856e03af.png)

**Comment by ksobon** [comment]
I will have another look, and get back to you. It might be that my Dynamo build at work is corrupted since I was having trouble with a lot of things on that machine.

**Comment by monikaprabhu** [comment]
If you can reproduce this - please reopen

**Comment by ksobon** [comment]
It's still not working for me. I have sets of valid points: 
![image](https://cloud.githubusercontent.com/assets/529781/7394079/64f1b9a2-ee5f-11e4-9dda-78f03c731397.png)
yet when I try creating an Arc from them they throw the same error: 
![untitled-1](https://cloud.githubusercontent.com/assets/529781/7394119/a5466b6a-ee5f-11e4-86dc-19a6a9724914.png)
