### ISSUE TITLE
Slider Breaking/Lagging in "Automatic" mode in 0.8.1 

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#4229]
Hello all,
I am using a slider in "Automatic" mode in the latest 0.8 official release.  My geometry will initially update with the slider.  However, after a few iterations the slider will either fail to update any geometry OR there will be a significant delay.

I tried this on something as simple as controlling a point position.

Note the image below.... "Automatic" mode is active, the X coordinate is set to 0, yet my point remains in its previous position.
![image](https://cloud.githubusercontent.com/assets/1890663/7107891/b77cd8ba-e139-11e4-8a1b-aa6fa50ab86c.png)

**Comment by rudderdon** [comment]
Slowest animation ever

**Comment by jnealb** [comment]
@archinate @rudderdon What are your slider Max and Step values? If mine are 10 and 1 or 0.5 etc then with 0.8.0.950 there is no issue as I drag the slider with Run Automatically: the point tracks in real-time. Perhaps we could set up a session to debug this?

**Comment by archinate** [comment]
Hey @jnealb .  I should have been more clear.  I am using the 0.8.1 official release (0.8.1.955).

All of my slider values are default in the above scenario (0-100, Step 0.1)  The slider will begin updating smoothly, but after moving the slider enough, the definition will start to delay and eventually stop working.

**Comment by tatlin** [comment]
I saw the lack of red point updating on some machines today in a workshop in London. 0.8 only, older versions worked fine

-matt

**Comment by jnealb** [comment]
@archinate @rudderdon @tatlin @ikeough I did reproduce the delay with 8.1 0.8.1.1025, also the preview bubble on Point.ByCoordinates is not updating its X coordinate. When the slow down occurs, which is not easily reproduced for me, I find that waiting a bit then clears the condition.

**Comment by ikeough** [comment]
Andy noticed this when he was working on Firefly. It has to do with our task compaction mechanism. Currently, whenever the slider ticks, an execution is fired. These execution "tasks" are then scheduled to run and they are processed in the order they are received. Execution tasks, unlike rendering tasks, do not get compacted by the scheduler. That is, if sliding a slider quickly submits tasks A...B...C, the scheduler doesn't know to only keep task C, the result of which is what you are actually looking for. 

As a test, I enabled task compaction for execution tasks and the performance with a slider is much improved as it compacts most of the tasks. But, there are, I'm sure, a bunch of reasons that we don't want to do this. I have to discuss further with @Benglin to see what the best course of action is.

**Comment by jnealb** [comment]
This is tracked with MAGN-7078

**Comment by ikeough** [comment]
Internal task is closed in https://github.com/DynamoDS/Dynamo/pull/4276. Please re-open if you're still seeing this on newer versions of Dynamo.
