### ISSUE TITLE
0.8 stable: auto run crashes dynamo on opening if errors in graph

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4244]
I have notice this behavior: when run auto is on, the graph executes when when loading the definition, and if something is wrong (new file, no element selected as input,etc...), dynamo is very slow to load definition when not crashing.
is there a way to set the autorun on after the dyn file is open?

**Comment by monikaprabhu** [comment]
@jbenoit44  
1. Open .dyn file and you can change the RunType="Manual". When you open this file next time it will open with default option as manual . 
2. We found a similar crash on custom nodes tracked at-MAGN-7073. A fix is on the way. I want to know if the one you seeing is the same.Are you using Dynamo in Stand alone mode? Also could you please post one of the files so I can be sure the fix we apply takes care the issue you are seeing.

**Comment by jbenoit44** [comment]
no it is used with Revit. runtype manual fixed it. but the problem remains: I use a definition on file A, runtype=auto. I work after on file B, and want to reuse defintion, and if selection or content is not there, as runtype=auto, it will crash.
Maybe user should get a warning when opening a definition set as auto, asking if the setting should be applied on re openning.

**Comment by monikaprabhu** [comment]
@jbenoit44 , are you using selection node within custom node? which selection node are you using ? 

Auto Run behaviour is discussed in this thread - https://github.com/DynamoDS/Dynamo/issues/4121

**Comment by jbenoit44** [comment]
select model element(s).

**Comment by ikeough** [comment]
Internal issue has been closed.
