### ISSUE TITLE
getSpaceAtPoint

### ISSUE THREAD

**Issue by tetsuyahishida** [DynamoDS/Dynamo#4247]
Hello

I'm now trying to rationalize the workflow for MEP engineer, and the first step is to know which space the element is placed.
I focused on 2 means,
GetSpaceAtPoint , and element.space
But Both seem to be not working.
I'd rather say that my coding is wrong, but can someone kindly point out what's wrong?

BestRegards

![image](https://cloud.githubusercontent.com/assets/780947/7154643/26c04576-e393-11e4-919c-26f5311c2642.png)
![image](https://cloud.githubusercontent.com/assets/780947/7154994/0357479e-e396-11e4-9ad3-46adc8b7c242.png)

**Comment by tetsuyahishida** [comment]
Hi I noticed that this was all about unit conversion.
Really difficult to understand...

**Comment by andydandy74** [comment]
@tetsuyahishida - some pointers:
1. UnwrapElement will unwrap an entire list of elements, hence your code could be reduced like so:
```
elements = UnwrapElement(IN[0])
for i in elements:
```
(this will also take care of the issue that you were using the variable ```i``` twice in your nested loops...)
2. There is no need for unit conversion when you use the ```ToXyz()``` method for converting Dynamo points to Revit XYZs:
```xyz = i.Location.ToXyz()```
More info on conversion functions for Python nodes here:
https://github.com/DynamoDS/Dynamo/wiki/Python-0.6.3-to-0.7.x-Migration#geometryobjects
(Actually that whole document should be an interesting read...)

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
