### ISSUE TITLE
0.8 stable: Element.Geometry crashes revit 

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4255]
when a large amount of elements is selected, this nodes makes dynamo+revit crash.
I test this on a project on Parts, around 4000. Works fine in 0.7.6, crashes a few seconds after Run with stable 0.8.
This is not the first time I have issue collecting geometry or solids with dynamo. is this a dynamo failure or a Revit API failure?

**Comment by monikaprabhu** [comment]
@jbenoit44 ,Will be difficult to answer that question without seeing the error. is there an exception thrown in Dynamo. Can you share the file?

**Comment by jbenoit44** [comment]
no exception, just vanishing... will try to redo this with a file I can share. email adress??

**Comment by monikaprabhu** [comment]
monika.prabhu@autodesk.com

**Comment by jbenoit44** [comment]
seems to be project related. did a try with new file and 4000 parts from families. works fine.

**Comment by monikaprabhu** [comment]
Thanks for the update- if its crashing again - Please get back to us
