### ISSUE TITLE
Wishlist: added functionality in groups 

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4257]
It is great to see the groups in the 0.8.1 builds. It helps a lot in large and complex graphics.

It would be interesting to add new nodes to an existing group (for example when moving the node "inside" the group, you get asked if you want to incorporate the node to the group). And in a similar way, to put nodes out of the group (for example when you select a node in a group and right click, you will have this option).

**Comment by jnealb** [comment]
@ramramps @lillismith FYI

**Comment by ramramps** [comment]
This is tracked under MAGN-7085.

**Comment by eproca** [comment]
It is great that the functionality requested is already in the daily builds. Thanks
