### ISSUE TITLE
daily build 20150416T2058

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4261]
graphics invisible.
created geometries (solids) are not displayed.
actually nothing is displayed but grid and coordinatesystem

**Comment by jnealb** [comment]
@epeter-  This may be MAGN-7125, we are investigating. Are you running Win7 or Win8?

**Comment by epeter-** [comment]
win 8.1

Am 17.04.2015 um 14:45 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> This may be MAGN-7125, we are 
> investigating. Are you running Win7 or Win8?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4261#issuecomment-93978707>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by RodRecker** [comment]
@epeter- try doing Windows update. Microsoft released a number of updates to Windows 7 and 8.1 today. Give that a try and let us know if that helps.

**Comment by monikaprabhu** [comment]
@epeter- what is the status on this

**Comment by ke-yu** [comment]
Close as not enough information to further investigation.
