### ISSUE TITLE
ModelCurve.ByCurve crashes Revit and Dynamo in latest stable

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#4266]
the title says it all really. I'm trying to "export" some curves as modelcurves in latest stable and it freezes both Revit and Dynamo. Only a few curves as well (15) 
I've also tries different dynamo curves as input.

**Comment by pboyer** [comment]
@ikeough?

**Comment by ikeough** [comment]
@josols I just tried this on the daily build, and it seems to work. It could be something only in the stable build. Can you send me a .dyn?

![image](https://cloud.githubusercontent.com/assets/1139788/7211988/f4ee160c-e515-11e4-81c3-b4e2711a803b.png)

**Comment by josols** [comment]
![model curve test](https://cloud.githubusercontent.com/assets/7080648/7215565/0bb0e13e-e5df-11e4-9c99-0349a7347e41.png)

**Comment by josols** [comment]
not entirely sure how to send it but changed it to a .png

**Comment by monikaprabhu** [comment]
@josols - Thanks for sending the file- its hanging on latest daily build. You can run it in Manual mode which is working fine. The issue is reported at MAGN-7162.

**Comment by ikeough** [comment]
Internal issue has been closed.
