### ISSUE TITLE
Rotate view control is working in a weird way.

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4275]
In the very last build (DynamoInstall0.8.1.20150418T1253.exe) the rotate view control (of the background 3D preview) seems almost impossible to use.

It looks like that the view keeps rotating a bit after you finish your mouse gesture.

By the way, the new graphics engine in the 3d preview looks truly fantastic compared with the old one

**Comment by dimven** [comment]
I'm having a similar problem as described in here:

https://github.com/DynamoDS/Dynamo/issues/4155

Also it's not limited to the background preview. Watch 3D nodes are affected as well.
