### ISSUE TITLE
Wish: Highlight geometry by line for CBNs

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4285]
It would be nice if selecting a line of code in a CBN would highlight the corresponding elements in geometry preview.

**Comment by dimven** [comment]
+1

**Comment by monikaprabhu** [comment]
@elayabharath  when are we having implementing this ?

**Comment by Racel** [comment]
This will be complicated to implement and require significant investment in the geometry viewer and WPF UI. As mentioned in our blog post about the future of Dynamo, we will not be addressing these type of issues in the near term with the existing UI. Closing for now.
