### ISSUE TITLE
"Non-Pointer" error when creating Point.ByCoordinates 

### ISSUE THREAD

**Issue by cirela20** [DynamoDS/Dynamo#4286]
![dynamo point_error](https://cloud.githubusercontent.com/assets/12034959/7232306/e7b218d2-e748-11e4-9a64-5adc8a899488.png)

Latest stable build release: (0.8.0.95) returns error when trying to produce a Point.ByCoordinates through design script via code block. 

Error reads: Warning, internal error please report. Dereferencing a non-pointer. (3f47aacd).

**Comment by jnealb** [comment]
@cirela20 @kronz This is coming from a collision with the Mantis Point function. If you Run Manual with 8.0 you will see the appropriate message, it is only when running Auto that you get the incorrect 'deref' message. We are tracking the issue as MAGN-7170.

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
