### ISSUE TITLE
ImportInstance sends bad geometry

### ISSUE THREAD

**Issue by duzo** [DynamoDS/Dynamo#4290]
Hi,

I created a Solid geometry using Dynamo 0.8 that gets distorted when sent to Revit using ImportInstance.

I tried to use both
    - a top to bottom loft with 4 guide curves, 
    - a loft using top, middle and bottom cross sections but I get the same result.

If it's exported as a SAT file and imported in Revit, the geometry is fine.

![image](https://cloud.githubusercontent.com/assets/12043623/7245882/333e72c0-e837-11e4-889d-8d2bcaf3f9f7.png)

This is how it shows in Revit
![image](https://cloud.githubusercontent.com/assets/12043623/7245891/4e2035ba-e837-11e4-9759-1252118bbd53.png)

![image](https://cloud.githubusercontent.com/assets/12043623/7245943/3001ed84-e838-11e4-9348-1edc326945af.png)

If I increase the angle even more then it works ?!?
![image](https://cloud.githubusercontent.com/assets/12043623/7245949/48e9d744-e838-11e4-96db-a7e77b5d925e.png)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
