### ISSUE TITLE
Bug: Solid creation methods in design script fail on the last few daily builds

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4305]
![2015-04-22_14-56-20](https://cloud.githubusercontent.com/assets/7148394/7268888/7eccbe6c-e900-11e4-8b05-2788ff97da22.png)

Notice how "Solid" becomes an input.

**Comment by monikaprabhu** [comment]
Do you have Mantis Shrimp or Rhynamo installed ? Possible duplicate of https://github.com/DynamoDS/Dynamo/issues/4109

**Comment by dimven** [comment]
I've got neither Rhynamo, nor Mantis Shrimp installed.

**Comment by monikaprabhu** [comment]
@dimven I'm not able to reproduce this at my end. I tried both inside Revit and Standalone. Can you please give us more details- are you trying on standalone and or Revit? Also please list if you have any other package installed.Any csharp .dlls loaded? What about other geometry methods are they working?
![solid](https://cloud.githubusercontent.com/assets/5218721/7295687/2c487ac8-e9eb-11e4-8919-91f3e55efad4.png)

**Comment by dimven** [comment]
Thank you for looking into this.
It doesn't work for me in both Revit and Standalone modes. I'll add a full list of packages tomorrow but the few that pop into mind are: Ampersand, archi-lab.net, Clockwork, Steam nodes, Lunchbox. I believe the only one that adds any c# libraries from the list of installed packages is the latest version of Lunchbox. I'll also try to do a clean install and see if that clears things up.

**Comment by dimven** [comment]
Hi @monikaprabhu , I did a clean install(uninstalled and deleted all folders) of the latest daily and it seems like everything seems to be  back to normal again. I guess the problem was somewhere on my end?
![2015-04-24_13-38-09](https://cloud.githubusercontent.com/assets/7148394/7313020/c021008e-ea87-11e4-9f3c-c452487c4e0e.png)

**Comment by dimven** [comment]
Hi @monikaprabhu , I did a clean install(uninstalled and deleted all folders) of the latest daily and it seems like everything seems to be  back to normal again. I guess the problem was somewhere on my end?
![2015-04-24_13-38-09](https://cloud.githubusercontent.com/assets/7148394/7313020/c021008e-ea87-11e4-9f3c-c452487c4e0e.png)
