### ISSUE TITLE
Zoom to Fit Disables Preview

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#4306]
Zoom to fit seems to be overzealous.  When I use zoom to fit in Dynamo preview, the geometry disappears, as does the grid.  I think its zooming out too far.

DynamoInstall0.8.1.20150421T1658.exe

**Comment by ekatzenstein** [comment]
Alright, I tested a few other things and it looks like a clipping plane issue.  How can we fix the clipping plane to relate to the zoom extents radius?

**Comment by ikeough** [comment]
@ekatzenstein See my response in https://github.com/DynamoDS/Dynamo/issues/4155.

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
