### ISSUE TITLE
Excel.WriteToFile

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4311]
I am using this node to write room and area object data. I formatted a range in the .xlsx to be a table so I can do some pivot tables elsewhere in the file that update dynamically as data is refreshed by Dynamo. The table expands dynamically, but is not contracting consistently when data is deleted from the Revit model. Some old data is staying behind, which is a problem. I had to manually size the table down, delete the data, then re-run the graph to update the numbers (the table grew to the correct size). Shouldn't tables resize in both directions when data is output from Dynamo? (increase and decrease in size). Thanks.

**Comment by monikaprabhu** [comment]
@dbaldacchino , yes , we are aware of it and its tracked at  MAGN-6750. We will try to fix it soon.
Thanks for reporting it.

**Comment by dbaldacchino** [comment]
Thanks, looking forward to it as I'm working on a workflow that depends on it to make it seamless :)

**Comment by monikaprabhu** [comment]
@dbaldacchino - this is now fixed - a new option "Overwrite" is being introduced. Where in if Overwrite is false By Default, only those cells will be overwritten where there is new input[this will match the previous behavior]. If true it will completely overwrite the Excel sheet. More details on the functionality available here - https://github.com/DynamoDS/Dynamo/pull/4405
