### ISSUE TITLE
Element.Parameters - jumbled reporting

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4351]
This issue exists in 0.7.5 and in 0.8 as well. Basically when you retrieve the parameters of an object category (ex: rooms), the listed items are listed at random. This makes it impossible to pull particular items from the list consistently through List.GetItemAtIndex for example, since the parameters are not reported at the same index consistently. I'm also noticing that some parameters are not reporting any values either (see attached). The reason I was trying to use this approach to retrieve parameter values is because the node Element.GetParameterValueByName is broken and inconsistent in other regards (see #4310). Thanks.

![elementparameters](https://cloud.githubusercontent.com/assets/4656191/7358747/6550e3f4-ecfd-11e4-88be-c16d1d1fdecd.png)

**Comment by ksobon** [comment]
This will be sorted with the https://github.com/DynamoDS/DynamoRevit/pull/1693 PR. Something like this: 
![image](https://cloud.githubusercontent.com/assets/529781/26564443/d1f418a4-44ae-11e7-81be-c13fdf668411.png)
