### ISSUE TITLE
Library does not show all packages

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#4363]
But after opening up one of the dyfs from the package folder, the package amazingly appears in the library. Something is broken...

**Comment by ikeough** [comment]
Can you tell us which package so we can try to replicate internally?

**Comment by LukeyJohnson** [comment]
It affects more than one package, but I demonstrate the issue on Get Revit Selection here:
https://screencast.autodesk.com/main/details/85ff5b5f-2a31-4328-9401-a3ae03e9d2a4

**Comment by ikeough** [comment]
@pboyer Any ideas here?

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
