### ISSUE TITLE
How to access a list in a list in new node?

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#4370]
Hi,
I have another problem in my current version of [utilities](https://github.com/redinkinc/DynamoUtilities). In the dropdown node I can now access list of lists, but only return the index but not the list itself. I'm having similar to this:

                  foreach (var data in listMirror.GetData().GetElements())
                                {
                                    var dataString = index.ToString();
                                    model.Items.Add(new DynamoDropDownItem(dataString, data.GetElements()));
                                }

so I'm using the DynamoDropDownItem to store my string/object pairs. then I return:

                AstFactory.BuildAssignment(
                    GetAstIdentifierForOutputIndex(0),
                    AstFactory.BuildPrimitiveNodeFromObject(Items[Index].Item));

My other methods for single values or flat lists work fine, but I'm still struggling with list of lists.
Hope anyone can give my a clue on how to solve this.
Thanks, Fabian

**Comment by monikaprabhu** [comment]
@keyu- Can you please take a look at this?

**Comment by ke-yu** [comment]
Hi @redinkinc, `AstFactory.BuildPrimitiveNodeFromObject()` is pretty weak...it only works for few primitive types: int, double, string and boolean, otherwise it returns `NullNode()`. If item is an array, you may check its type firstly (e.g., it is `IEnumerable` or not), and use `AstFactory.BuildExprList()` to get an array. 

For example, you would write a helper function to create associative node for nested array:
```
AssociativeNode CreateASTForCollection(IEnumerable items)
{
    List<AssociativeNode> itemAsts = new List<AssociativeNode>();
    foreach (var item in items)
    {
        if (item is IEnumerable)
            itemAsts.Add(CreateASTForCollection(item));
        else 
            // suppose the type of item is in {int, double, boolean, string}
            itemAsts.Add(AstFactory.BuildPrimitiveNodeFromObject(item);
    }
    return AstFactory.BuildExprList(itemAsts);
}

```

and in your code,  

```
AstFactory.BuildAssignment(
                GetAstIdentifierForOutputIndex(0),
                item is IEnumerable 
                   ? CreateASTForCollection(item)
                   : AstFactory.BuildPrimitiveNodeFromObject(Items[Index].Item));
```

Not sure if it solves your problem or not.
