### ISSUE TITLE
check file at filepath isUpdated?

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#4377]
Hi, I have a script where I read in a file. Now if I change something in the file I cannot run dynamo again because I have nothing changed in the script itself. Is there a possibility to have a File.IsUpdated? node in Dynamo?
Thanks, Fabian

**Comment by andydandy74** [comment]
@redinkinc - The File.FromPath node watches changes to an external file.

**Comment by redinkinc** [comment]
@andydandy74 - ok, thanks. I hoped so but faced some issues with that. Will give it a try.
