### ISSUE TITLE
Trying to use Revit.View.SunSettings.Current crashes Dynamo 0.8.1.1106

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#4382]
Tried to use Sunsettings in Dynamo 0.8.1.1106 on German Windows 8.1 64bit and Revit 2016 64bit resulting in following error message:

Invalid call to Revit API! Revit is currently not within an API context.

   bei Autodesk.Revit.UI.UIApplication.add_ViewActivated(EventHandler`1 handler)
   bei DSRevitNodesUI.SunSettings..ctor()
   bei lambda_method(Closure )
   bei Dynamo.Search.SearchElements.NodeModelSearchElement.ConstructNewNodeModel()
   bei Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   bei Dynamo.UI.Controls.StandardPanel.OnMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Regards, Fabian

**Comment by monikaprabhu** [comment]
I can reproduce this on English Windows as well- MAGN-7298 .This is working ok with Revit 2015 can you use that?

**Comment by redinkinc** [comment]
I can use Revit 2015 but then have to recreate my Revit project. Would prefer working in 2016 but having 2015 as a fallback.

**Comment by monikaprabhu** [comment]
@redinkinc - Sorry for inconvenience - will try to get it fixed soon.

**Comment by kronz** [comment]
Fixed
https://github.com/DynamoDS/DynamoRevit/pull/359
