### ISSUE TITLE
various code block issues

### ISSUE THREAD

**Issue by aogata** [DynamoDS/Dynamo#4383]
I have been having a pretty tough time understanding code blocks.
I assumed that the functions would return values of 3 and 5 respectively.
How come I am getting "null" values in the to functions at the top?
How come I get lists on the functions at the bottom?
Also, if you copy the function definition an rename it (Panelize2 from Panelize) it appears to cause problems
Finally, I am not sure I understand if using "return" vs "some other word" affects the function definition

![image](https://cloud.githubusercontent.com/assets/4739811/7435563/24517cdc-f00a-11e4-99b8-77552e2e6778.png)

**Comment by RodRecker** [comment]
@aogata The Panelize function's 2nd line may need "returnSyntax" instead of "return".
Let us know if that doesn't work.

**Comment by aogata** [comment]
Thanks RodRecker... tried it... but no change.
My question regarding the "return syntax" was whether the use of a native term (return) made a difference in assigning a variable (=[Imperative]),

Nevertheless, I thought that the output to the function nodes would be either 3 or 5. Instead I get 2 'null' and 2 lists.

https://cloud.githubusercontent.com/assets/4739811/7435563/24517cdc-f00a-11e4-99b8-77552e2e6778.png

**Comment by RodRecker** [comment]
Which version of Dynamo are you using?

**Comment by aogata** [comment]
0.8.0.950 and revit 2015

**Comment by holyjewsus** [comment]
Hi @aogata you wrote a function taking two inputs, you need to supply both input parameters:

![screen shot 2015-05-01 at 3 19 36 pm](https://cloud.githubusercontent.com/assets/508936/7435846/8d13181a-f015-11e4-98e9-3a8b9234ac45.png)

**Comment by holyjewsus** [comment]
Hi @aogata I'll investigate this more, thanks for submitting the issue, let us know if fulfilling the parameters worked. Something doesn't seem to be right.

**Comment by aogata** [comment]
That was helpful.  
There still is appears to be an issue regarding the input/output formatting. (see integer input vs list input)
![image](https://cloud.githubusercontent.com/assets/4739811/7436152/2486367e-f010-11e4-837f-c9744b80752f.png)

However, it answered my question regarding "return" vs "return syntax".  Seems like now you HAVE to use "return" and variable names are no longer allowed.

**Comment by holyjewsus** [comment]
The issue of passing lists into functions and not replicating over their contents is a question for @lukechurch

**Comment by monikaprabhu** [comment]
@aogata ,
There are language example available in this guide. 
http://dynamobim.org/wp-content/uploads/forum-assets/colin-mccroneautodesk-com/07/10/Dynamo_language_guide_version_1.pdf

Imperative Language is not for replication: To use lists in Imperative Blocks you need to use "for " 
![untitled2](https://cloud.githubusercontent.com/assets/5218721/7440951/e6ff280c-f103-11e4-9619-150f4a648d83.png)


In your example above. There is replication over function.
The function replicates based on the input you have provided. If its a list the function will be called for each input. Try this and see the results:
![untitled](https://cloud.githubusercontent.com/assets/5218721/7440898/23c723b4-f101-11e4-80c7-18441957885a.png)

**Comment by aogata** [comment]
So @monikaprabhu @lukechurch @holyjewsus is that right?
The output of an imperative block with a list input will always be a list with the same qty of indices as the input?

Then, what kind of syntax would you use in a code block if you wanted to use a loop to go through a list and output either a single solution (say... highest number) or a list of a different size (say... same list until the sum of items reaches 20?)

**Comment by holyjewsus** [comment]
hi @aogata, I found out today you can do what you'd like this way by typing the input parameter to your function:

![screen shot 2015-05-04 at 10 07 40 pm](https://cloud.githubusercontent.com/assets/508936/7466033/1f148500-f2aa-11e4-977e-e9541ef7e047.png)

note the :var[] type

**Comment by monikaprabhu** [comment]
@aogata - In the above example I was trying to explain how to iterate throw the list.
As holyjewsus pointed out, if you want to process a list you can pass  a list as argument and return after the processing. here is another example to show how to extract only a part of the list and return it. All the list processing methods should be working ok within Imperative loop and the return value is based what the user wants to return. Its similar to other  programming languages.
 
![impe](https://cloud.githubusercontent.com/assets/5218721/7466688/d7ec3922-f31a-11e4-93d6-21eb2cbf3de6.png)

**Comment by aogata** [comment]
Thank you all... This was most helpful


On Mon, May 4, 2015 at 10:37 PM, monikaprabhu <notifications@github.com>
wrote:

> @aogata <https://github.com/aogata> - In the above example I was trying
> to explain how to iterate throw the list.
> As holyjewsus pointed out, if you want to process a list you can pass a
> list as argument and return after the processing. here is another example
> to show how to extract only a part of the list and return it. All the list
> processing methods should be working ok within Imperative loop and the
> return value is based what the user wants to return. Its similar to other
> programming languages.
>
> [image: impe]
> <https://cloud.githubusercontent.com/assets/5218721/7466688/d7ec3922-f31a-11e4-93d6-21eb2cbf3de6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DynamoDS/Dynamo/issues/4383#issuecomment-98930299>.
>



-- 

Alejandro Ogata, AIA, LEED AP
Adjunct Professor of Architecture
University of Kansas, School of Design
Marvin Hall, 1465 Jayhawk Boulevard
Lawrence, KS 66045
m: 816.694.1747

Sr Project Designer
HNTB Corporation
715 Kirk Drive
Kansas City, MO 64105
o: 816.527.2190
