### ISSUE TITLE
UV Grid distribution algorithm

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#439]
Just noticed that the UV Grid node layout algorithm differs significantly from that of the divided surface functionality - segment length vs. chord length? Would be nice to have options.
![bildschirmfoto 2013-09-07 um 09 58 32](https://f.cloud.github.com/assets/3014437/1100881/b3ba5944-1793-11e3-9a5c-9a50b64259b9.png)
(points in image placed by UV Grid node - U/V numbers identical to those used in divided surface)

**Comment by smangarole** [comment]
@andydandy74 @mjkkirschner @kronz - Looks like there's a workaround for this issue and also a package is available, based on the conversation. Can we close this issue?

**Comment by andydandy74** [comment]
@smangarole This workaround is very, very hacky. Since paneling is a fairly common scenario in Dynamo, I think a good UV distribution algorithm should be available OOTB.

**Comment by smangarole** [comment]
@andydandy74 Thanks. Will get teams attention on this one.

**Comment by andydandy74** [comment]
Closed here and reopened in DynamoRevit repo
