### ISSUE TITLE
Element.GetParameterValueByName - Warning

### ISSUE THREAD

**Issue by ansonman** [DynamoDS/Dynamo#4390]
I creating excel summary with big project data. When run designed standard node on my Dynamo.  the "Element.GetParameterValueByName" showed warning, the warning as below:

Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)

This is bug or not ?

**Comment by monikaprabhu** [comment]
@ansonman - can you post more details? Which version of Dynamo are you using - Also please post the graph. "Element.GetParameterValueByName".Also which version of Revit are you using ?Latest build works ok with Revit 2014,Revit 2015 and Revit 2016.  
![param](https://cloud.githubusercontent.com/assets/5218721/7466382/606b83d6-f314-11e4-8328-2489dfba8559.png)

**Comment by dbaldacchino** [comment]
@monikaprabhu there are related issues #4308 and #4310 (no response/aknowledgement yet).

**Comment by mdengusiak** [comment]
Hi I have the same warning,
Dynamo 0.8.3.2256, Revit 2015  Build 20150704_0715(x64 Update Release 9)

I am trying write into Spaces - parameter - some values

![2015-08-27 23_10_25-dynamo](https://cloud.githubusercontent.com/assets/14005893/9533229/e2dcdd64-4d10-11e5-842f-f14fdae62f27.png)

**Comment by mjkkirschner** [comment]
@mdengusiak it's hard to tell from your graph but the element inputs do not seem to be Revit elements?

**Comment by mdengusiak** [comment]
you are right I took values and not elements IDs... I corrected now this and everything works fine here,

However not sure if this is related but somehow all my text in Revit just disappeard. So my space Tags are blank

![2015-08-28 00_42_45-autodesk revit 2015 - floor plan_ level 13 spaces heat loss - simplifiedtest2_m](https://cloud.githubusercontent.com/assets/14005893/9535189/e676099c-4d1e-11e5-92aa-3531df30dcdf.png)
![2015-08-28 00_43_13-autodesk revit 2015 - sheet_ - - space tag mepbridgesolar rfa](https://cloud.githubusercontent.com/assets/14005893/9535193/eeb2de0a-4d1e-11e5-811a-c1342fc22630.png)

**Comment by natethegrate1** [comment]
What does this error mean? I am also getting the error. Basically taking a toposurface and creating a solid in dynamo in order to calculate total volume of the surface.
![image](https://cloud.githubusercontent.com/assets/11881415/12644970/4b5e44ae-c5cf-11e5-98dc-83e477427100.png)
