### ISSUE TITLE
Design Script method "__Apply" does not work for multiple arguments?

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4392]
![2015-05-04_16-52-40](https://cloud.githubusercontent.com/assets/7148394/7451064/aca25054-f27e-11e4-8ab8-bbc18b9d19fc.png)

"Apply "works just fine with a single argument. However, as the image shows, it fails when used with multiple arguments.
Is it possible for the "Apply" method to accept multiple arguments, just like its Dynamo node equivalent?

**Comment by monikaprabhu** [comment]
@ke-yu - Looks like bug to me - Can you take a look at this ?

**Comment by ke-yu** [comment]
Hi @dimven , yes, `__Apply()` is dumb :-(, it only works with a single argument. To get the final result, you may apply `__Apply()` multiple times. For example:

![untitled](https://cloud.githubusercontent.com/assets/2600379/7465537/5dc9e510-f304-11e4-9c35-8dfbad9bac08.png)

But as you know about `__Apply()`, try `__ApplyList()` :-) 

![untitled](https://cloud.githubusercontent.com/assets/2600379/7465575/0768bc40-f305-11e4-9e4e-62ca84c531c3.png)

**Comment by dimven** [comment]
@ke-yu, Thanks a lot for the info. That works great! :+1:
