### ISSUE TITLE
Problem with Package Manager UI (Scrolling)

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4397]
There's a problem with the UI of the Package Manager, specifically when scrolling after expanding the version list of a particular package. The scroll mouse button doesn't work. Also if you try to scroll using the little scroll control on the right of the window, it jumps to the next package rather than through the list of versions. This actually highlights another problem: version history should be reversed (latest at the top, not the bottom). Currently the only way to get to the bottom of the list is to stretch the window, but once the list gets longer, I'm not sure there will be away once you run out of vertical pixels on your screen. Please see below for an example and try for yourself.

![packagemanagerui](https://cloud.githubusercontent.com/assets/4656191/7459990/859d9f7c-f265-11e4-9975-a3dbb08dfdfb.png)

**Comment by monikaprabhu** [comment]
@dbaldacchino  , yes I see that the scroll bar is jumping to next package and  its quite inconvenient. This is already reported at our end is tracked at MAGN-5576. @pboyer what are the chances of this getting fixed in the recent future?

**Comment by pboyer** [comment]
Although I'm happy to fix this, but this can be fixed by anyone on the
team.  Well need to fit it into our priorities like everything else. :p

**Comment by ikeough** [comment]
@kronz Wondering if this ever got fixed.

**Comment by kronz** [comment]
@dbaldacchino @ikeough Yes, this is fixed now.
