### ISSUE TITLE
Element.GetParameterValueByName not working but Sheet.SheetNumber is working v.80 

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#4412]
Element.GetParameterValueByName not working but Sheet.SheetNumber is working v.80
![image](https://cloud.githubusercontent.com/assets/6132497/7488093/7b59def8-f379-11e4-8e92-3413ee1713ce.png)

**Comment by ThorHow** [comment]
Sheet.Name is working? Oh my - that's a relief! Thanks!
Struggling with the same in [https://github.com/DynamoDS/Dynamo/issues/4310], should have commented here instead of course.

**Comment by cgrammens** [comment]
also getting  this this message when trying to set parameters by name on a filtered list.  it works on a the entire sheet list but not once filtered.

Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)

![image](https://cloud.githubusercontent.com/assets/4682090/7542536/6c3ec9c4-f572-11e4-8015-0a0c9b9e26e9.png)

**Comment by monikaprabhu** [comment]
This is already reported in our system through forums - http://dynamobim.com/forums/topic/sheet-numbers-and-getparametervaluebyname/
We have an open bug to address this specific issue tracked at - MAGN-5870.

**Comment by monikaprabhu** [comment]
@cgrammens , Regarding the error on Element.SetParameterName - Definitely this is a wrong error and bug , but Sheet.SheetNumber is a wrong value to the input Element.SetParameterByName - This node sets the value of a parameter for an element and Sheet Number is a parameter not an element. I think what you are trying to do is have "Sheet" as the element and change the parameter for the same. So replace SheetNumber with Sheet.

**Comment by ikeough** [comment]
Internal issue has been closed. https://github.com/DynamoDS/DynamoRevit/pull/534

**Comment by marcellosgamb** [comment]
Fixed in 1.1v?

Sent from my iPhone

On May 2, 2016, at 9:41 PM, Ian Keough <notifications@github.com<mailto:notifications@github.com>> wrote:


Internal issue has been closed. DynamoDS/DynamoRevit#534<https://github.com/DynamoDS/DynamoRevit/pull/534>

**Comment by marcellosgamb** [comment]
Looks like its working now. I checked with the dailies (5-3-2016)


________________________________
