### ISSUE TITLE
Show geometry in Revit 2016

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4413]
The functionality of showing a preview of the Dynamo geometry in Revit 2015 it is fantastic. In same cases is really critical.

Sadly it seems not available in Revit 2016. Can we expect that this will change soon?.

**Comment by monikaprabhu** [comment]
@eproca - here is the id to track this wish. MAGN-7358

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2175).
