### ISSUE TITLE
Reading numbers from excel

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4415]
Hi,

i have problem with component that reads excel data, it autoaticaly converts numbers to float without chceking if they are intergers, and adds a lot of zeros.

it looks weird when i write values to to revit components that go out on sheets

would it be possible to have component that consideres all data from excel as string ? so the values look exact as in excel? there already is component string to number that could take hand of numbers if needed, 

thanks

![image](https://cloud.githubusercontent.com/assets/4834544/7489658/834041d8-f3d9-11e4-8633-54dcbc8413b4.png)

**Comment by monikaprabhu** [comment]
@aparajit-pratap ,Why are we converting the int into float? how can  we keep the value same as entered in excel

**Comment by aparajit-pratap** [comment]
Let me check this. Thanks for pointing it out.

**Comment by aparajit-pratap** [comment]
@ondejcik all numbers in Excel files are read as floats by Excel by default. It is not worth CPU time to check if a number is meant to be an `int`, then returning it as an `int` and if it is meant to be a `float`, returning it as a `float`. This can make reading Excel files even slower than Excel interop already is. There is however a workaround you can use. If you expect all values in the file to be integers, you can change the number precision in Dynamo. Go to Settings => Number Format. Change its value to '0'.

**Comment by ondejcik** [comment]
ok but is it not possible to read from excel all text and numbers as string ? it would solve my problem, i have both floats and integers in excel and i need to pass the to revit as string anyway.

**Comment by monikaprabhu** [comment]
@ondejcik , Which Revit node are you using to write into sheet?

**Comment by aparajit-pratap** [comment]
@ondejcik yes it is possible to read from excel as strings. That way you will get the data exactly as you see it in the excel file however in Dynamo the `ReadFromFile` node is meant  to read strings as strings and numbers as numbers so that users can use those numbers and perform further computation with them. We will evaluate whether it would be useful to add a new `Read` node to Excel to read all data as strings and get back to you.

Btw, could you tell us which Revit node you are using to write data to it? 

Additionally if you run the graph below, you will see that the `Write` node actually writes the data in the same format as read from the original excel file.
![image](https://cloud.githubusercontent.com/assets/5710686/7580922/7c772fb2-f8af-11e4-97f4-abbade477bbc.png)

**Comment by ondejcik** [comment]
Hi,

my definition looks like this: (in short; i read excel, pick some cells i need and write them to parameterslots in families in revit, (tree data, 200+ parameters) then all data goes directly to sheets and that is why i need them to look same as in excel, all parameters in revit are generated automaticaly and contain string data)

![image](https://cloud.githubusercontent.com/assets/4834544/7582257/11f18174-f88c-11e4-96c7-cee0c7389277.png)

**Comment by aparajit-pratap** [comment]
Under review: https://github.com/DynamoDS/Dynamo/pull/4548

**Comment by aparajit-pratap** [comment]
This is fixed here: https://github.com/DynamoDS/Dynamo/pull/4548

Let us know what you think.

**Comment by ondejcik** [comment]
Hi,

Thanks for implemetation in a first place. However i have still one probem. I got an error when i a reading my excel file with true setting on. I wonder where culd be an error. I would guess it does not like empty fields.


![image](https://cloud.githubusercontent.com/assets/4834544/7815653/0f554f74-03ca-11e5-8c4d-a1028f1f5e29.png)

![image](https://cloud.githubusercontent.com/assets/4834544/7815668/2eb645d0-03ca-11e5-97c7-dc8be44c66ee.png)

![image](https://cloud.githubusercontent.com/assets/4834544/7815684/43e5ded4-03ca-11e5-9326-e9a700f9eb47.png)

it works if the are no empty cells

![image](https://cloud.githubusercontent.com/assets/4834544/7815729/7810e2c6-03ca-11e5-8249-dc09403eba60.png)

![image](https://cloud.githubusercontent.com/assets/4834544/7815738/892415c4-03ca-11e5-9a69-2eb50927de1f.png)

**Comment by aparajit-pratap** [comment]
@ondejcik thanks for pointing this out and sorry for the oversight. This is now fixed in: #4572
