### ISSUE TITLE
Renaming Groups and Position

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#4418]
After renaming a group, if I click on another battery or group in the definition, the entire renamed group is moved to that position.

Daily Build: DynamoInstall0.8.1.20150505T0438.exe

**Comment by monikaprabhu** [comment]
@ekatzenstein - yes I see that - I've filed a bug to track this MAGN-7321.

**Comment by monikaprabhu** [comment]
@ekatzenstein - this issue is fixed - please try the latest build -DynamoInstall0.8.1.20150513T0845
