### ISSUE TITLE
RemoveNulls not visible in library

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4427]
the built in function "RemoveNulls" is not visible in the library and not available as node

It is extremely useful. But right now it is only possible to use in CBN (and if you know that it does exist)

**Comment by monikaprabhu** [comment]
@eproca - While RemoveNulls is not exposed in UI, you can try Package Lunchbox.  It contains "RemoveNulls".

**Comment by eproca** [comment]
Thanks for the answer.

I am using it directly in CBN. For me is fine. I am asking for other users that maybe would like to know that it does exist, even if it is only possible in CBN.

**Comment by monikaprabhu** [comment]
@eproca - That is great epoca. We are working on a node in Lists Management which will take care of this - Aparajit (@aparajit-pratap )is working on this. Just around the corner to make the submission.

**Comment by monikaprabhu** [comment]
A method has been added " List.Clean" -here is the PR for this. Once its merged, the next build that is up on DynamoDaily will have this functionality. https://github.com/DynamoDS/Dynamo/pull/4438

**Comment by eproca** [comment]
List.Clean is great. Thanks
