### ISSUE TITLE
Incorrect Save Location

### ISSUE THREAD

**Issue by ralvarez76** [DynamoDS/Dynamo#4435]
Dynamo is saving the definition (DYN) file to the backup folder under the user profile. It is not saving the DYN file on the location it was opened from.

**Comment by jnealb** [comment]
@ralvarez76 Yes, we are investigating.

**Comment by monikaprabhu** [comment]
@jnealb - Is there a bug to track this ?

**Comment by jnealb** [comment]
@ralvarez76 @monikaprabhu I am unable to repro this with the 0.8.1.1304 build - I did however see it with earlier 8.1 builds. @ralvarez76, are you still experiencing this with the daily builds?

**Comment by ralvarez76** [comment]
It seems to be fixed. I am opening a DYN from a network mapped drive and it saves the file to the location I open it from.

**Comment by jnealb** [comment]
@ralvarez76 @monikaprabhu Closing.

**Comment by ralvarez76** [comment]
Sorry this just happened again. It looks like as soon as I make a change to the graph is starts saving to the backup folder under the Appdata\Roaming folder.

Not only that, but I noticed that when creating a new custom node it created it under a weird name like "new_mane_8tg7gr994485r949545.DYN" and not the name I gave it. This custom node was also saved in the backup folder. I had to do a saveas, and delete the node in the backup folder for it recognize the correct custom node location.

**Comment by jnealb** [comment]
@ralvarez76 Issue #2 is tracked with MAGN-7388. Do you have exact steps to reproduce issue #1? Thanks.

**Comment by ralvarez76** [comment]
Here it is:

1. Start a new definition and save it.
2. Create point at 0,0,0 and at 1,1,1. Create line from one point to the other. Change run state to manual.
3. Create point at 2,2,2. Place Arc.ByThreePoints and try to feed it the previous three points. It will fail.
4. Change third point to 1,2,1 and rerun definition. It will succeed.
5. Any saves after the graph fails will start saving to the "%APPDATA%\Dynamo\backup\" folder.
6. Doing a saveas to the original file location restores the ability to save back to the correct path, until the graph fails again.

Obviously the above graph is not what I was working on, but this gives you an idea of the minimal steps to reproduce the error.

Thanks.

**Comment by jnealb** [comment]
@ralvarez76 Thank you - this is tracked with MAGN-7393

**Comment by dbaldacchino** [comment]
I'm seeing this also in 0.8.1. Is this still an open issue? I can't describe the condition it happens but when I got a lockup and later re-opened Dynamo, the backup did not show up in the backup area but in the recent files area, together with the original file. It's quite confusing actually.
