### ISSUE TITLE
SunSitting.current

### ISSUE THREAD

**Issue by afandianzo** [DynamoDS/Dynamo#4441]
always dynamo crash when use SunSitting.current

**Comment by tatlin** [comment]
This is tracked internally here http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7298 and has a fix waiting to be reviewed and then submitted @rodrecker @ikeough

-matt

**Comment by kronz** [comment]
Fixed
https://github.com/DynamoDS/DynamoRevit/pull/359

**Comment by afandianzo** [comment]
Thank you

Abdulaziz Afandi


Sent from Yahoo Mail on Android
