### ISSUE TITLE
Floor.ByOutlineTypeAndLevel(outlineCurves,floorType,level) - does not appear to function when called in a code block

### ISSUE THREAD

**Issue by buddyd16** [DynamoDS/Dynamo#4457]
The Floor.ByOutlineTypeAndLevel(outlineCurves,floorType,level) node works fine on its own however when attempting to call it in a code block the floors are not created and "null" elements are returned.

I am pretty sure this one is user error on my end but I am not the only one that can't get it to work either.

the forum has an example:
http://dynamobim.com/forums/topic/using-a-code-block-function-to-create-floors/

**Comment by monikaprabhu** [comment]
@buddyd16 - Works for me in latest daily build - Try this, if it still fails please get back to us with more details ![floor](https://cloud.githubusercontent.com/assets/5218721/7612953/79900ee2-f9c0-11e4-8e8f-ddfb453d19be.png)

**Comment by buddyd16** [comment]
Here is what I have now the floor call is in an imperative section which loops over multiple levels, floor types, and groups of closed curves.

![capture](https://cloud.githubusercontent.com/assets/12416202/7613094/9ba6304c-f95c-11e4-9300-442c5b5360cb.png)

**Comment by buddyd16** [comment]
I simplified the variables a bit and here is something odd in the main code block inside the imperative Count(c[0][]) produces a value of 1 but in a standalone code block Count(c[0][]) produce the expected value of 5.


![capture_2](https://cloud.githubusercontent.com/assets/12416202/7621356/34b388b6-f994-11e4-8c1e-565f22d04c11.JPG)

**Comment by buddyd16** [comment]
I am getting closer my list of curves "c" needed to be declared as a three tier list => c:var[][][]
Doing that the floor call produce floors in revit for the initial run of the while loops only. How do I get it to do the other two runs in this case?

![capture_2](https://cloud.githubusercontent.com/assets/12416202/7622070/e874c496-f999-11e4-809c-7d7b947c0fda.JPG)

**Comment by buddyd16** [comment]
I got it I needed to reset indd = 0 prior to second while loop.

Is there somewhere that notes how to declare the variables coming into the code block? me figuring out that c:var[] needed to be c:var[][][] was complete luck by trial and error.
