### ISSUE TITLE
WISH: Make it easy to find missing custom nodes

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4474]
This might already be in the system, but couldn't find it.

If a custom node from a package is used in a definition and that package isn't installed, the node turns red and alerts you (nice). But that's where it stops! We need to know which package it came from so we can download and install it. This data needs to be written "outside" of the node itself so it can be referenced when the package is absent.

**Comment by monikaprabhu** [comment]
@dbaldacchino- Yes I understand the difficulty and agree with the request- I've logged it into MAGN-7396 to explore a solution.

**Comment by ksobon** [comment]
+1

**Comment by andydandy74** [comment]
dupliate of #1171
