### ISSUE TITLE
Wish: Background 3D preview grid customization

### ISSUE THREAD

**Issue by Arek3dim** [DynamoDS/Dynamo#4488]
It would be great to be able to customize the size of the grid and the grid lines in the background 3d preview and the "watch 3d" component.

**Comment by monikaprabhu** [comment]
@Arek3dim - That is a valid request - Here is the tracking number for same - MAGN-7402

**Comment by andydandy74** [comment]
With the new unitless Dynamo it makes a lot of sense. When Revit project units are set to millimeters, for example, the grid becomes tiny...

**Comment by josols** [comment]
not only tiny, but I've experienced some culling/draw distance issues as well. When in mm, the objects aren't always shown completely.

**Comment by Racel** [comment]
This is being improved in Dynamo 2.0. As per our latest blog post on the future of Dynamo, we will not be putting resources in the the geometry viewer as we are working on other solutions. Closing for now.
