### ISSUE TITLE
Wish: Search in workspace

### ISSUE THREAD

**Issue by Arek3dim** [DynamoDS/Dynamo#4490]
Grasshopper has this feature that you can double click inside the workspace and start searching for a node, it's a great powerful tool that speeds up the workflow, can we get something similar to that please? I know we can type anytime but backspacing all the time is just not cutting it, maybe we can fix that in a way? Thank you so much!

**Comment by kronz** [comment]
Thanks, we are working on an in-canvas search. Stay tuned

**Comment by ikeough** [comment]
I'm closing this issue as the requested functionality is now available in recent builds as right click to search in canvas.
