### ISSUE TITLE
Dynamo solids converted to meshes instead of solids 

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#4496]
When using python scripts, Dynamo curves are transformed smoothly to Revit curve geometry objects by using ToRevitType(). So using the Revit API it is quite straightforward to create some Revit elements not supported yet by the current Revit Dynamo nodes. Like for example making detail lines in the active view.

Sadly Dynamo solids are not converted to Revit solid geometry objects by using ToRevitType(). The result is mesh geometry objects instead. Maybe there is here a limitation of the Revit API.

I know that the integration in Revit of "external" solid geometry is an important area of development. Hopefully future versions of Revit will improve this

**Comment by monikaprabhu** [comment]
@eproca I've filed this request in our internal tracking system. MAGN-7443 - would you be interested in sharing how are you planning to use this Solids once converted to Revit. Will be interesting use case to verify the workflow. @pboyer is there are a reason why we convert Dynamo Solids to mesh when using ToRevitType() APi in Python?

**Comment by eproca** [comment]
Sorry for the delay in answering. How to integrate the solid geometry made in Dynamo in Revit is critical for many of us. You can read about some possible workflow related here: https://github.com/DynamoDS/Dynamo/issues/4061

 I am sure that this is being developed and we will have a far better integration of the Dynamo geometry in Revit. 

Right now you can make some tricks (you can read about it in the issue noted before) and at least improve a bit just to put an imported instance and explode. But you make first the imported instance and extract the geometry, create the Revit freeform and delete the imported instance. You put everything in a custom node and you have some sort of Dynamo solid to Revit freeform node. But it is a pity  that you cannot go directly from a Dynamo solid to a freeform or any other similar Revit element and you have to deal with imported instances.

**Comment by monikaprabhu** [comment]
@eproca- thanks for the answer I'll go through the link for 4061.  I wanted to know if  you expect to use any specific Revit tools once converted into revit ?

**Comment by tatlin** [comment]
The correct way to do this in Revit now is using the DirectShape Apis 

-matt

**Comment by eproca** [comment]
@monikaprabhu, you can find at the end of 4061 what I am doing until now with the dynamo solids ported via freeform inside of generic families. Currently it is not possible to do a lot, but at least I can control the graphical appearance and join or cut other elements (inside the generic family or other families when inserted in the project environment). Ideally in the future I can create directly the family, fill  parameter with custom data and propagate instances in the project enviroment, everything from Dynamo without even opening the family editor :).

@tatlin, It would be great if you can point to a sample of porting a Dynamo solid to Revit via the directshape api.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2174).
