### ISSUE TITLE
Selected Geometry Highlights

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4500]
Highlight of selected geometry in background is not visible in cases where they overlap

The attached screen shots should better convey the issue

![20150518-0](https://cloud.githubusercontent.com/assets/5621624/7673911/de963812-fd39-11e4-8c72-0d9bf968a133.jpg)

![20150518-1](https://cloud.githubusercontent.com/assets/5621624/7673858/cf8f6d3a-fd38-11e4-944b-4a026b3d7ce3.jpg)

![20150518-2](https://cloud.githubusercontent.com/assets/5621624/7673889/5ee19f4e-fd39-11e4-9c85-fbd55b2ca6ed.jpg)

Regards,
Vikram Subbaiah

**Comment by jnealb** [comment]
@testingwaters Thank you, we are working on this issue and tracking it as MAGN-6774.

**Comment by dietervermeulen** [comment]
Have a look at the screenshots below. They give a similar effect, but the highlighting is not working even if the objects are not overlapping.
![1](https://cloud.githubusercontent.com/assets/12096185/8902231/abd98eb8-344f-11e5-9b3d-3ed8a8c1d96b.png)

**Comment by ikeough** [comment]
Internal issue has been closed.
