### ISSUE TITLE
Dynamo nodes do not run

### ISSUE THREAD

**Issue by astoupine** [DynamoDS/Dynamo#4527]
I am trying to create a custom node in Dynamo with wpf, and I am running into an issue with the AstFactory.BuildFunctionCall() function, where feeding in a function that accepts a List<List<double>> causes the whole Dynamo graph to just not work. Here is the code in question:

```
        var externalFunction =
            AstFactory.BuildFunctionCall(
                "__ApplyList",
                new List<AssociativeNode>
                {
                    inputAstNodes[4],
                    n
                 });

        var functionCall1 =
             AstFactory.BuildFunctionCall(
                 new Func<OptimoEngine.Container, List<List<double>>, OptimoEngine.Container>(OptimoEngine.NSGA_II.AssignFitnessFuncResults),
                 new List<AssociativeNode>
                { 
                    n, externalFunction
                });
```

I am setting an output with this:

AstFactory.BuildAssignment(
                    GetAstIdentifierForOutputIndex(2), functionCall1)

When I try to import this node into Dynamo, all of the nodes return null, even the nodes that are not attached to the custom node (the process runs for less than a second and then says it is completed). When I remove the line for the output, the Dynamo graph runs normally. Here is a screenshot of Dynamo:

![image](https://cloud.githubusercontent.com/assets/6424117/7736083/2da3a8f8-ff07-11e4-8c3c-fbd10ada1e19.png)

**Comment by monikaprabhu** [comment]
@aparajit-pratap ,@Ben - could you please take a look at this?

**Comment by aparajit-pratap** [comment]
@astoupine sorry for the delay in responding to you. `__ApplyList` is meant to be used in Dynamo internally and not exposed to external developers. May I know exactly what is the use case you are trying to solve using your custom node implementation? It looks as though you're trying to create a higher-order custom node that takes in a function object and a list? Could you give an example? Thanks.

**Comment by ikeough** [comment]
@astoupine Any update here?

**Comment by smangarole** [comment]
The issue has been waiting for feedback for almost a year. Closing due to this reason. Please reopen if this issue resurfaces.
