### ISSUE TITLE
Wish: IndexOf to return a list of indices

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4529]
See attached for an example. I can't figure out a way to achieve this except through Python.
![indexof](https://cloud.githubusercontent.com/assets/4656191/7738417/a9077ecc-ff19-11e4-82ed-4f6a5c8391d3.png)

**Comment by dbaldacchino** [comment]
Related to #4361 so it is in the works already.

**Comment by monikaprabhu** [comment]
How about using FilterByBoolMask to seperate the list  ? I'm filtering out the indices based on the value (-1)of the index here -FilterByBoolMask takes a list and based on the mask , which is a list of booleans splits the list into two parts. 
 ![getkeys](https://cloud.githubusercontent.com/assets/5218721/7740751/e6ffd42e-ffa8-11e4-8606-40ba0c50b620.png)

**Comment by dbaldacchino** [comment]
Ahh thanks, I wasn't familiar with GetKeys. This could possibly get me the end result without Python. I'll give it a shot tomorrow, even though I've already solved it, but it helps me to learn how to apply other nodes to solve other problems in the future :)

Sent from Yahoo Mail on Android

**Comment by ekkonap** [comment]
@dbaldacchino have you tried setting the lacing of 'index of' node to longest?

**Comment by dbaldacchino** [comment]
@ekkonap I tried that but it just outputs -1 as the answer, which is not what I'm after.

**Comment by ke-yu** [comment]
hi @dbaldacchino , I provided two solutions here, hopefully one of them is what you want :-)

![1](https://cloud.githubusercontent.com/assets/2600379/8325610/8ce51c2e-1a8d-11e5-9fdd-560fa2ecba67.png)

![2](https://cloud.githubusercontent.com/assets/2600379/8325614/91e5d452-1a8d-11e5-8b3a-46a1ea0eadbe.png)

**Comment by dbaldacchino** [comment]
Hi @ke-yu, thanks for those solutions (I'm just now getting back to reviewing some old emails!). Dimitar posted a very simple solution in the Dynamobim forum post for my original quest. BTW, the node List.AllIndicesOf does exactly what I want. I wish the functionality of that can be combined into his one. The quantity of nodes that do things just ever so slightly different and have unique names is making this software hard to learn when you're not using it daily.

**Comment by smangarole** [comment]
Closing this issue based on the conversation above.
