### ISSUE TITLE
Document Active view

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4540]
seems broken in 0.8.1.1345. nodes returns this:
![image](https://cloud.githubusercontent.com/assets/4572196/7750924/48cbb4a6-ffd7-11e4-8f26-cb7e2fc5d17b.png)
and using python, it returns this:

![image](https://cloud.githubusercontent.com/assets/4572196/7750943/63d2f944-ffd7-11e4-8c2a-f4725f67e469.png)
impossible to use this in python.

**Comment by kronz** [comment]
Looks like this is fixed now (0.8.1.1661)
![2015-06-17_2259](https://cloud.githubusercontent.com/assets/3456818/8223365/9e98c914-1544-11e5-9b04-fc400f9c499d.png)
