### ISSUE TITLE
View creation in python, batch process needed

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4544]
I have an issue with dynamo vhen i want to create 3D views from a python node. I remember that in 0.6.3 it was a blast. I was able to create hundreds in less than a minute. right now it take ages as it seems that dynamo regenerate Revit each time a view is created.

The node I use is available in Steamnodes package as Element.Create 3D Cropped view.

line used: b=View3D.CreateIsometric(doc, typeid)

**Comment by ke-yu** [comment]
@Randy-Ma , do you have any idea about this issue? is it because of transaction model?

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2173).
