### ISSUE TITLE
Not prompted to Save on closing

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4546]
Not prompted to Save file on closing a file after making changes.
However, the file is saved, BUT, in the backup folder. The original file remains at the last saved state.
The file name in the backup folder is the same as the original file. 
Further adding to the confusion is the presence of two files with the same name in the Recent Files section on the Start Screen.
(One is the file in the original location and the other is the backup file)
![20150522-1](https://cloud.githubusercontent.com/assets/5621624/7762557/36b00f24-0054-11e5-8523-c3c855b29e01.jpg)

Regards,
Vikram Subbaiah

**Comment by sharadkjaiswal** [comment]
@Randy-Ma PTAL

**Comment by mjkkirschner** [comment]
I think this can be closed, backups should not show in the recent files, please reopen if this is still occurring.
