### ISSUE TITLE
Output ports disappear

### ISSUE THREAD

**Issue by testingwaters** [DynamoDS/Dynamo#4550]
Version: DynamoInstall0.8.1.20150521T2046 , DynamoInstall0.8.1.20150522T0052

The output nodes disappear now. 
Seems similar to the older issue where the input nodes disappeared with deep statements.

![20150522-12](https://cloud.githubusercontent.com/assets/5621624/7767554/0c718be2-0091-11e5-8e28-1b99d62ae159.jpg)

The line that caused the trouble is underlined in the image below
![20150522-13](https://cloud.githubusercontent.com/assets/5621624/7767564/2a993b10-0091-11e5-8b61-4e4362c82c55.jpg)

**Comment by aparajit-pratap** [comment]
@testingwaters thanks for highlighting this. We'll look into this and get back to you soon. Is this a regression from earlier or was it that you couldn't get to this stage of writing chained expressions?

**Comment by testingwaters** [comment]
@aparajit-pratap regression? chained expressions?
Sorry, not well versed in technical computer speak :-)

However, this is fresh code, not an old file.
I think such 'chained' statements used to work earlier.

**Comment by monikaprabhu** [comment]
@testingwaters -  From the second image above I cannot see which variable have the input/output ports.      
The code "BaseSol7=Flatten({BaseSol5,BaseSol6}).DifferenceAll(Flatten(Frms))" marked in the image attached above would not have any input ports as all the three variable  
"BaseSol5","BaseSol6" and "Frms" are already defined. Could you please explain why you thought it should have an input port( Or please share the entire code.)

**Comment by testingwaters** [comment]
The first image shows the state of the code block node before adding the underlined (red) statement.
On adding the statement (underlined in second image) all the output ports disappeared.
There were no input ports, in this case.

**Comment by testingwaters** [comment]
The issue was sorted out by splitting the statement into separate lines.
The latest version of the file  (one that works properly) is available at http://a360.co/1Q4kq26

**Comment by aparajit-pratap** [comment]
This has been fixed here: https://github.com/DynamoDS/Dynamo/pull/4616

**Comment by monikaprabhu** [comment]
this is fixed
