### ISSUE TITLE
Localization issue: Button sizes

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4562]
Localized buttons need to resize. Button label text currently appears truncated:
![truncated label text](https://cloud.githubusercontent.com/assets/3014437/7806713/81fa6fbe-0384-11e5-8410-4af42e52b745.PNG)

Environment:
DynamoInstall0.8.1.20150522T1644
Windows 7
German locale

**Comment by ikeough** [comment]
@andydandy74 This is awesome to see. Thanks.

**Comment by RodRecker** [comment]
@monikaprabhu let's log this one Monika.Thanks!

**Comment by monikaprabhu** [comment]
@andydandy74 - this is tracked under - MAGN-7490.Thanks for reporting the issue

**Comment by kronz** [comment]
Fixed:
https://github.com/DynamoDS/Dynamo/pull/4679
