### ISSUE TITLE
Wish: Opt out of localization

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4563]
While I appreciate the effort to provide a localized version of Dynamo, it would be very helpful to be able to *not* use that feature. Please provide an entry in the settings menu that enables the user to switch between the English language version and the localized version. 
(Yes, I know that I could switch my computer's locale to EN but for various reasons I depend on the German locale for other applications I am using).
Environment:
DynamoInstall0.8.1.20150522T1644

**Comment by jbenoit44** [comment]
+1+1+1+1+1+1+1+1

**Comment by Benglin** [comment]
Hi guys, just trying to understand the use case here...

### Dynamo Sandbox
In stand-alone Dynamo, you can launch `DynamoSandbox.exe` with the following flag to force it into `English United States` locale:

    DynamoSandbox.exe /L "en-US"

Creating a shortcut on your desktop with `/L "en-US"` is the most convenient way to do this frequently.

### Dynamo on Revit
Dynamo that launched on top of Revit follows the language settings of Revit, that is, if your Revit is in `fr-Fr` locale, then Dynamo inherits that to launch with `fr-FR` resources loaded. There is currently no way to overwrite this behavior.

Are we talking about the Revit use case here? If so we can think about having a way to deal with it (e.g. like your suggestion of having a configurable settings somewhere).

**Comment by andydandy74** [comment]
@Benglin - Sorry for not being more precise. I was talking about the Sandbox use case as I didn't know if there was a way to launch it in another language. Now I do - thanks for the hint. This should be documented somewhere, though.

**Comment by jbenoit44** [comment]
thanks for details. I will wait for a more stable release on localized version, and maybe provide suggestion for translation, which is not really good at the moment. after using it for a while, I'll share thoughts.

**Comment by jnealb** [comment]
@jbenoit44 @RodRecker Bonjour Julien, je suis d'accord. On peut en discuter? neal.burnham@autodesk.com

**Comment by andydandy74** [comment]
@jbenoit44 - for improving the translation also see #4564
