### ISSUE TITLE
How to provide suggestions for localization

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4564]
I noticed that in the German localization
- some translations are missing 
- some translations could be improved

Question: What's the best way to suggest changes/additions to localizations? I found [this article on the wiki](https://github.com/DynamoDS/Dynamo/wiki/Integrate-localized-resource-files), but it seems that access to localization resource files is only available internally at Autodesk, so I guess a pull request is out of the question, right?

**Comment by Benglin** [comment]
Sorry @andydandy74, the link you found is meant for our internal build process. For your purposes I do not think we would go with pull request method, rather I'd recommend the following: the team internally does have a feedback loop to the localization team, who in turn manages a list of issues with translation. The person who actually does the translation will look at the feedback in that system, and tweak their translation accordingly. However, that system is internal, if you could suggest changes here as *Issues*, then @monikaprabhu will make sure they get into that system as a defect for the localization team to fix.

I hope there is a simpler way to accept your contribution, but does this make sense for you? Thanks for offering anyway!

**Comment by andydandy74** [comment]
Thanks, @Benglin - I'll create an issue.

**Comment by jnealb** [comment]
@andydandy74 @Benglin @monikaprabhu @ikeough @jbenoit44 @RodRecker This is tracked with MAGN-7491.
