### ISSUE TITLE
Localization: open definition issue

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4570]
seems dyn extension got lost in translation....
![image](https://cloud.githubusercontent.com/assets/4572196/7823433/c1bda00e-03fb-11e5-85c5-9c29f3bd187d.png)
![image](https://cloud.githubusercontent.com/assets/4572196/7823445/d1a3fdba-03fb-11e5-8eca-5bd0fd2e42a8.png)
same on save as.

**Comment by monikaprabhu** [comment]
this is already reported and tracked under - MAGN-7474

**Comment by monikaprabhu** [comment]
@jbenoit44 - This is fixed- please use latest Daily build - DynamoInstall0.8.1.20150602T2145.exe
