### ISSUE TITLE
Localization issue: Encoding issues with untranslated resources

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4573]
Untranslated resources display the original (English) text but there seems to be a character encoding issue:
![encodingissue](https://cloud.githubusercontent.com/assets/3014437/7829882/271709c2-0447-11e5-9e4b-302e7ed3774b.PNG)
Also:
![moreencodingfun](https://cloud.githubusercontent.com/assets/3014437/7830032/aa084d9a-0448-11e5-8810-4a1d17dc6ce2.PNG)
(Another example would be the settings menu as it also contains some untranslated items...)
Environment:
DynamoInstall0.8.1.20150522T1644
Windows 7
German locale

**Comment by RodRecker** [comment]
@andydandy74 Here is the explanation from the localization team:

The strange characters you are seeing are what we call “Pseudo-Translation”: it’s basically the English string, in this case:
"Delete Group" 
with extra, extended characters:
"DDélété Gröüpp"
It enables us to test whether a string is globalized / ready for localization, and whether it can take expansion without truncation.

Hence, no need to file a defect for this.

We are currently working on removing all Pseud-Translation from the loc resource files that will be included in customer-facing builds."

**Comment by andydandy74** [comment]
Okay, got it
