### ISSUE TITLE
No localization in latest daily

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4574]
Not sure if you are aware of this, but there is no localization available in the latest daily.
Environment:
DynamoInstall0.8.2.20150526T1702
Windows 7
German locale

**Comment by monikaprabhu** [comment]
@andydandy74  - I think this  is fixed - Try this in latest build - Launch using -  "C:\Program Files\Dynamo 0.8\DynamoSandbox.exe" /L "de-DE"
