### ISSUE TITLE
Crash on opening existing dyn

### ISSUE THREAD

**Issue by bimwood** [DynamoDS/Dynamo#459]
DynamoDailyInstall20130902T0256, reports Build 0.6.0.3426.

Opening an existing .dyn (that worked with 0.3..), crashed:
![dynamo crash 2](https://f.cloud.github.com/assets/5095961/1129096/7ffabddc-1b81-11e3-9032-d8bd06c53cda.PNG)

**Comment by ikeough** [comment]
I'm closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.
