### ISSUE TITLE
Wrong argument types in MigrateToDsFunction call for NewtonRootFind1DWithDeriv

### ISSUE THREAD

**Issue by Dewb** [DynamoDS/Dynamo#4597]
In dynOptimize.cs, I noticed that the migration to NewtonRootFind1DWithDeriv has the wrong function signature: it should be _FunctionObject,_FunctionObject,double,int. Not certain what effect this has on migration of this node type but I figured I'd flag it.

``` c#
    public class NewtonRootFind1DWithDeriv : MigrationNode
    {
        [NodeMigration(from: "0.6.3.0", to: "0.7.0.0")]
        public static NodeMigrationData Migrate_0630_to_0700(NodeMigrationData data)
        {
            return MigrateToDsFunction(data, "", "NewtonRootFind1DWithDeriv",
                "NewtonRootFind1DWithDeriv@_FunctionObject,double,int");
        }
    }
```

**Comment by mjkkirschner** [comment]
I think we can close this as this node has been removed from 2.x.
