### ISSUE TITLE
Some suggested improvements for German localization

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4600]
@monikaprabhu - as per #4564 I am submitting some suggestions on how to improve German localization:

```File``` menu:
- ```Export Model to STL```: **"Modell als STL exportieren..."** (This would be more consistent with the translation used for ```Export Workspace as Image```: ```Arbeitsbereich als Bild exportieren```
- ```Recent Files```: **"Zuletzt benutzte Dateien"** or (better yet) **"Zuletzt verwendete Dateien**" (This is the wording that is commonly used across a wide array of applications. The current wording's literal translation is "last", not "recent".)

```View``` menu:
- ```Connectors```: There is a German word for this that does *not* have latin roots: **"Verbinder"**

```Console``` :
- ```00:00:01.4474435 elapsed for loading Dynamo main window.```: **"00:00:01.4474435 verstrichen zum Laden des Dynamo Hauptfensters"** (a bit of grammar)

**Comment by monikaprabhu** [comment]
@andydandy74 - I'm filing MAGN- 7529 to track this - Will discuss this with development team and find a conclusive way to handle it.
