### ISSUE TITLE
local languages

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4620]
dynamo is automatically using german language although i am running revit in english language.
preferable were a language selection button

**Comment by ayan13yxq** [comment]
yeah, I want to use english version of dynamo on my chinese version of revit. How?

**Comment by ikeough** [comment]
@jnealb Do we have document talking about localization? What languages are available, and what to do if you want to run Dynamo in a different language?

**Comment by ikeough** [comment]
Also...We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).

**Comment by jnealb** [comment]
@ian @pradhu @zack Monika, you have such a document, no? Or do we need to write one?
