### ISSUE TITLE
Improvement: InCanvas search

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4630]
long waited feature. as a first feedback I'd like to have search available without hitting a key. maybe with a mouse gesture like drag left with left click or something like that.

**Comment by redinkinc** [comment]
yes, this feature would be awesome. As a first step it could work that the search field is available even if the library is hidden.

**Comment by kronz** [comment]
Have you tried the right click functionality in daily builds?

**Comment by jbenoit44** [comment]
finally yes! this looks awesome. will test it in the coming days.

**Comment by jbenoit44** [comment]
mouse wheel is not set in search result window but it seems you're on it.
