### ISSUE TITLE
Search engine: major issue

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4631]
As I'm  testing the new feature (InCanvas search), it appears that the current search engine is the worst ever in Dynamo story. just try with Element....all results from custom nodes are missing.
I don't understand how this could happen. there should be no regression in soft dev.
Imagine when people are starting with dynamo, and they get such a horrible result...
this must be the top priority to fix.

**Comment by kronz** [comment]
Hi Julien,
Can you say a little more about what you are seeing. This is what I get (a slightly more recent build of 0.8.1 branch)
![2015-06-04_1033](https://cloud.githubusercontent.com/assets/3456818/7986357/1c481b8a-0aa5-11e5-93c4-a0913729871e.png)

**Comment by jbenoit44** [comment]
I tried with Element, no s, and a lot of custom nodes are missing in result. ElementDOT or ElementsDOT provide different results. Same with capital E ou normal e. I think this should not happen.

**Comment by lillismith** [comment]
Agreed the singular/plural thing is really a problem. Thanks for bringing this up. I'll add this specific case to my list of search problems that we are working on right now.  Also, please keep us posted on how you are finding in-canvas search otherwise.  If you didn't know, we have a short cut for it that is shift+double click. On context menu in latest builds.

**Comment by kronz** [comment]
Tracking internally as MAGN-7286

**Comment by lillismith** [comment]
We are making some changes to the library and search in the latest daily builds.  If you could try it out and let us know what you think, that would be great. I'm not sure they exactly address your "Elements" problem above, but you can let us know if they at least don't make it worse.  Here are the specific changes:
- make search algorithm more forgiving for plurals: https://github.com/DynamoDS/Dynamo/pull/4707 (even though it says don't merge - we did)
- remove "more" button from library browse https://github.com/DynamoDS/Dynamo/pull/4676/files 
- remove truncated search 
- add tool tips to in-canvas search (only on mouse over)
- remove library search alphabetical category return https://github.com/DynamoDS/Dynamo/pull/4665

**Comment by ikeough** [comment]
Internal issue is closed in https://github.com/DynamoDS/Dynamo/pull/4707. Please re-open this issue if you are still experiencing the problem on a newer build of Dynamo.
