### ISSUE TITLE
Wish: opening 2 code in one session

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4645]
Hi it would be very heplful to have a possibility to open 2 dynamo scripts in one sesssion,  same way as custom node and script can be opened on 2 tabs; to be able copy nodes and follow others' scripts 
thanks

**Comment by monikaprabhu** [comment]
@ondejcik - Thanks for the report - A similar request is already tracked in our system in AMGN -MAGN-2312

**Comment by ikeough** [comment]
@sharadkjaiswal This issue was closed internal as a user story, but no resolution was marked here. I believe it is linked to multiple home workspaces which is not completed. Update?

**Comment by johnpierson** [comment]
Closing this as it is related to https://github.com/DynamoDS/Dynamo/issues/6636
