### ISSUE TITLE
Replication Guides Inconsistency

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4657]
Dynamo Ver: 0.8.2.1555
OS: Windows 7

Are the replication guides meant to work only with variables?
Seems counterintuitive.

![dynamo20150608-1](https://cloud.githubusercontent.com/assets/5621624/8034596/b0b5a1a2-0e06-11e5-9f6b-f40bd290862c.jpg)

Regards,
Vikram Subbaiah

**Comment by dimven** [comment]
I get that too sometimes - the code block does not refresh after applying the replication guides. Try copy-pasting the code block. It started happening a lot more often after 0.74

**Comment by monikaprabhu** [comment]
This is a bug. Thanks for reporting this - ive filed MAGN-7677 to track this. it must work even if you are not using variable.

**Comment by ikeough** [comment]
Internal issue has been closed.
