### ISSUE TITLE
3D preview missing in version 0.8.2.1555

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#4658]
Hey,
I'm using Dynamo for Revit in version 0.8.2.1555 and now the 3D-preview in Dynamo is missing. Operationg System is Windows 8.1 (german). 
Thanks, Fabian

**Comment by ikeough** [comment]
Can you tell us what kind of Graphics adapter your system has? Are you running Dynamo using virtualization of any sort (Fusion, Parallels)? Are you running Dynamo over Remote Desktop? What version of Revit?

**Comment by redinkinc** [comment]
Windows 8.1 installation incl. all current upddates on a thinkpad t420/NVIDIA NVS 4200M graphiccard/Revit 2016.

**Comment by ikeough** [comment]
Is it a dedicated graphics card or a switchable setup with intel graphics as well? if it's switchable, can you go to the NVidia control panel and specify that you want to use the "High performance graphics adapter" (not sure this is exactly what it's called, but there's an option to force the use of the NVidia).

**Comment by ikeough** [comment]
Looks like that system has a dual setup with the Intel 3000. Can you try the instructions listed for Nvidia [here](http://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/AutoCAD-crashes-when-opening-or-closing-drawings-on-systems-with-dual-graphic-cards.html)?

**Comment by redinkinc** [comment]
Updating the NVIDIA driver and setting it to always use NVIDIA (instead of let the system chose if the dedicated or onboard graphics should be used) fixed the issue.
Thanks a lot. Fabian

**Comment by jnealb** [comment]
@redinkinc @ikeough Closing, another NVDIA card is validated, thanks.
