### ISSUE TITLE
Screenshot export from 3d view 

### ISSUE THREAD

**Issue by Kaankrby** [DynamoDS/Dynamo#4677]
Adding an export option for 3d workspace from dynamo. 
After new coloring options it will be necessary.

**Comment by monikaprabhu** [comment]
@Kaankrby - You want to export as image?  The option Export Workspace as image is broken - it fails on graphic display - Which is tracked in 6841.

**Comment by alfarok** [comment]
closing this as core 2.0 includes the ability to `Export Workspace As Image` and `Export Background 3D Preview as Image`.  If there is still an issue feel free to comment and reopen.

**Comment by andydandy74** [comment]
@alfarok will the geometry view export be exposed as a node?

**Comment by alfarok** [comment]
@andydandy74 It isn't exposed as a node, but the underlying function can be accessed and called within a zerotouch node I believe.  I do agree that having this as a node would be helpful for tasks such as generating a series of images based on various parameters (helping to automate .gifs etc)

**Comment by andydandy74** [comment]
Great, thanks for the info. Won't need a node if it's a public method. 😀
