### ISSUE TITLE
Python Crashing

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4689]
Hi, i am using dynamo 0.8.2, and i experience instability in python nodes. I use around 30-40  short simple python nodes in a script. When opened, all goes OK, but once i start to create new nodes it usualy crashes on or more python nodes (on both automatic and manual refresh). best way is to close and reoplen dynamo script again, this however is very unefficient. Is there som limit in python nodes that have been testet to work properly? 

also when this happens, other nodes like watch do not update

**Comment by RodRecker** [comment]
Can you post an example to help us debug this?

**Comment by ondejcik** [comment]
i could send you my .dyn file, i dont see i can post files here

**Comment by jnealb** [comment]
@ondejcik @RodRecker  Please send to neal.burnham@autodesk.com.

**Comment by ikeough** [comment]
@jnealb Did you ever receive a case for this?

**Comment by jnealb** [comment]
@ondejcik @ikeough No.

**Comment by ikeough** [comment]
I'm closing this issue as we do not have enough detail to test it. Please re-open if you're still experiencing this problem and have an example which reproduces the problem.
