### ISSUE TITLE
Wish: Ghosting node wires

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#4692]
Is there any chance we could look at implementing a 'ghosting' feature - where you can showcase where a wire input needs to go - without it being connected? 

Given that we're now running automatically as default - this would be fantastic for definitions that have multiple options or for tutorials for people to learn from. 

I simply envisage holding down a key (shift, control, alt) when connecting a wire to a node to 'ghost' it.

**Comment by RodRecker** [comment]
Nice idea!


Rod

**Comment by Amoursol** [comment]
Now no longer needed with Freeze functionality.
