### ISSUE TITLE
Disregard backup folders when uploading a new package version

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4699]
When uploading a new package version all backup folders contained in the local package folder should be excluded from the upload - it just blows up package size unnecesssarily...
(Haven't actually tried this in any of the new builds since I am still keeping my package in 0.7 but I'm assuming this will happen in Dynamo 0.8 as well).

**Comment by pboyer** [comment]
This is tracked internally as MAGN-7676

**Comment by ikeough** [comment]
Internal issue has been closed.
