### ISSUE TITLE
Formula is only considering the two first digits

### ISSUE THREAD

**Issue by JorgenGam-Jorgensen** [DynamoDS/Dynamo#4764]
If you look at items, specially the last ones, you can see that it is only considering.
considering the last two digits

![capture2](https://cloud.githubusercontent.com/assets/12990748/8272957/e7be6970-1858-11e5-99b9-edd81403222e.JPG)

**Comment by JorgenGam-Jorgensen** [comment]
I'd like to add that the Sizes on the left comes from pipe sizes from the Category "PipeInsulations"

**Comment by epeter-** [comment]
this problem is not a formula issue, but the element."getparametervaluebyname" still returns inches when in metric version

**Comment by JorgenGam-Jorgensen** [comment]
OK, I've solved my problem with putting in the box "String.ToNumber" before the formula. Then it worked for me. :) 
Thanks for the answer. :)
