### ISSUE TITLE
Minus symbol inside custom node watch

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#4767]
From a user, is this symbol intended and what does it mean?

With no output connected, the watch window shows a green “minus” symbol;
![image001](https://cloud.githubusercontent.com/assets/508936/8290231/954b95d6-18ef-11e5-960a-a11c6b115626.png)
With an output connected the watch window shows the expected output;

![image002](https://cloud.githubusercontent.com/assets/508936/8290233/97729922-18ef-11e5-8c93-3c58d0b82a94.png)

**Comment by ikeough** [comment]
It's not a minus sign. It's the button that should only show up if you've wired up a revit element. When you click on that button in Dynamo for Revit, it takes you to the element in the view. It's obviously showing up when it's not supposed to.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2172).
