### ISSUE TITLE
Feature Request: Ability to pan in the canvas without a mouse wheel

### ISSUE THREAD

**Issue by seandburke** [DynamoDS/Dynamo#478]
In order to better support a touchpad, or other alternate input device it would be handy to have pan supported by a keyboard+left click and drag. Even more interesting would be the ability to support multi-touch gestures, which a designer could program for different uses beyond the ability to pan.

Either of these approaches would allow using a laptop with single trackpad, or even more interesting: the ability to get our Dynamo on via a remote app on a mobile device, leaving our heavy workstation on the desk while travelling.

**Comment by jluebker** [comment]
when trying the ctrl+alt+arrowkey my display changes orientation rather than panning in dynamo, any ideas how to handle this?
