### ISSUE TITLE
Mesh Toolkit

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#4793]
I think maybe this has been answered before, but I can't find it. Seems like the Mesh Toolkit doesn't show in the library after installing? Using latest daily 0.8.2.1756.

**Comment by aparajit-pratap** [comment]
@josols thanks. We are aware of this issue and are tracking it here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7571

**Comment by monikaprabhu** [comment]
@josols -Try this with Dynamo Version - 0.8.0.950 official release that is available on http://dynamobim.org/ -its loaded there.

**Comment by aparajit-pratap** [comment]
The MeshToolkit packages have been updated on the package manager. There are 2 new versions now, namely, “MeshToolkit for Dynamo 0.8.2 Dailies”, and “MeshToolkit for Dynamo 0.8.1”. The older package named “MeshToolkit” can be used only with Dynamo 0.8.0.

**Comment by aparajit-pratap** [comment]
@josols it would be great if you can verify the new package with the daily build you're using or with Dynamo version 0.8.1 if you have it installed. Thanks.

**Comment by josols** [comment]
sorry for extremely late reply, but i tried downloading and it's working in 0.8.2 dailies. Now do you have a dynamo mesh to mesh toolkit converter? :)

**Comment by andydandy74** [comment]
@josols - see #3749 for a way to convert your mesh...

**Comment by LukeyJohnson** [comment]
I can't see any Mesh Toolkit packages in the package manager today.
![mesh](https://cloud.githubusercontent.com/assets/5659896/10628814/81030e58-7810-11e5-8cc2-a727a6272546.png)

**Comment by aparajit-pratap** [comment]
@josols these are under (re) construction. Apologies for the inconvenience. You'll have to wait for a few hours ...

**Comment by aparajit-pratap** [comment]
MeshToolkit packages have been uploaded back for all Dynamo versions till date.
![image](https://cloud.githubusercontent.com/assets/5710686/10634031/795d5fc6-7821-11e5-9691-1c5ac06292c7.png)
