### ISSUE TITLE
Installed package nodes do not show up in search

### ISSUE THREAD

**Issue by mrahmaniasl** [DynamoDS/Dynamo#4800]
I installed a Energy Analysis Package. When I search for the nodes it does not bring up anything. 

I opened one of the sample Dynamo code that ships with the package. and it includes the nodes, but still does not show up in the search.

![image](https://cloud.githubusercontent.com/assets/5613071/8397687/e0cbff1a-1d99-11e5-87fb-8a0b2e33976e.png)

**Comment by mostaphaRoudsari** [comment]
Try Prepare with capital P and see if it makes any difference

**Comment by BPOpt** [comment]
Thanks,

Yes. It seems it matters. Thanks.
By the way the energy analysis nodes with dropdown still having.

**Comment by monikaprabhu** [comment]
@BPOpt , could you please explain the statement "By the way the energy analysis nodes with dropdown still having" - are there still issues with search here. I'm able to see the nodes correctly when I use the node names correctly with the Uppercase.

**Comment by BPOpt** [comment]
@monikaprabhu The search problem is solved with using upper case. I should not include a separate comment on energy analysis dropdown nodes here. I opened a separate issue for dropdown nodes. 

Thanks.

**Comment by andydandy74** [comment]
I don't think this issue should be closed. Upper / Lower case in search field should not yield different results. Please re-open.

**Comment by monikaprabhu** [comment]
@lillismith - Can you please revisit the design here ? it will be more easy for users if we are linient on text search ignoring the case. Please let me know so I can track it.

**Comment by lillismith** [comment]
Can you try this again on the latest build?  I see desired search results for "Prepare" or "prepare"  on 0.8.2.1782. 
![2015-07-01_0941](https://cloud.githubusercontent.com/assets/2932690/8455830/7eb086e6-1fd5-11e5-8f63-54bb55fb2d91.png)
![2015-07-01_0939](https://cloud.githubusercontent.com/assets/2932690/8455831/805ec5e8-1fd5-11e5-9b25-9d25a06f36c2.png)

**Comment by lillismith** [comment]
oh and if you wanted CreateByMassLevels, it shows up too, just a little farther down the list.

**Comment by BPOpt** [comment]
Hi Lilli,

Thanks for tracking this. I installed the latest version of Dynamo, reinstalled the energy analysis package. It seems that the search is not functioning well. Please see below (It is on the top of Revit 2016):

![image](https://cloud.githubusercontent.com/assets/5613071/8480560/06a8361a-20a4-11e5-99eb-8ad4a25ac911.png)

**Comment by lillismith** [comment]
Hum. I'm puzzled as to why this is happening for you and not for me.  What happens when you search "point" or "watch"?

**Comment by BPOpt** [comment]
Here is what I see when searching for Watch and Point:
![image](https://cloud.githubusercontent.com/assets/5613071/8481511/1caba348-20a9-11e5-895d-848eb9af6304.png)

![image](https://cloud.githubusercontent.com/assets/5613071/8481524/2c40f84e-20a9-11e5-8bf1-85d01e4a2090.png)

**Comment by lillismith** [comment]
Maybe there is a problem with this package?  We don't see this as a general problem. Check out the package documentation here http://core.thorntontomasetti.com/energy-analysis-for-dynamo-open-beta-release/ and file issues here: https://github.com/tt-acm/EnergyAnalysisForDynamo/issues

**Comment by ikeough** [comment]
@lillismith  Is this still an issue?

**Comment by lillismith** [comment]
Don't think we were ever able to reproduce it.
