### ISSUE TITLE
Deprecation: Some possible minor improvements

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#481]
Some suggestions on the handling of deprecation:
1. Installed Packages list: For consistency's sake, the display of deprecated packages should be treated the same way as in Online Package Search (dark grey background)
2. I think this...
![bildschirmfoto 2013-09-18 um 17 22 15](https://f.cloud.github.com/assets/3014437/1166066/3ece2e9e-2076-11e3-9f41-6c77b2f66791.png)
...is very subtle - how about a bit of colour that says "Do not install this package"? ;-)
3. Again, for consistency's sake, shouldn't the search in Online Package Search and the Package Manager Website return the same results? Package Manager Website will not show deprecated packages at all.

**Comment by smangarole** [comment]
@Racel and @kronz - Can you please update this in light of the ongoing package manager development?
Can we close this?

**Comment by Racel** [comment]
We are working on a new backend and UI for package manager. The suggestions in this task are being considered, but I am closing now as we don't have any immediate actions we can take.
