### ISSUE TITLE
Wish: Adding info to deprecated packages during deprecation process

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#482]
I think it would be good to be able to change the info text of the package that one sets as deprecated in order to advise users/subscribers what package or built-in node they should use instead. 
My current workflow is to publish a new version of the freshly deprecated package with an altered info text, but I think this could be something Dynamo lets me do automatically during the process of deprecating a package.

**Comment by smangarole** [comment]
@Racel and @kronz - Can you please update this in light of the ongoing package manager development?
Can we close this?

**Comment by Racel** [comment]
We can do this.
