### ISSUE TITLE
Editing custom nodes creates duplicate entries in node browser

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4820]
After editing a custom node I noticed several duplicate entries of that node in the node browser:
![duplicateentries](https://cloud.githubusercontent.com/assets/3014437/8447827/fa186392-1fbe-11e5-955e-cfa84449d73a.PNG)
Dynamo 0.8.1 RC 2
(Note that these entries are only temporary - they will disappear after starting a new Dynamo session...)

**Comment by sharadkjaiswal** [comment]
Thanks @andydandy74 for reporting this issue, #4802 is in progress to fix this issue.

**Comment by monikaprabhu** [comment]
This is issue is fixed in 0.8.1 release uploaded on DynamoBIM -http://dynamobim.com/download/
