### ISSUE TITLE
Preview list structure transposed?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4822]
It looks like the list structure shown in preview bubbles is transposed:
![previewtransposed](https://cloud.githubusercontent.com/assets/3014437/8447972/51f8a372-1fc1-11e5-93d9-8570b1319de0.PNG)
0.8.1 RC 2

**Comment by monikaprabhu** [comment]
@andydandy74 , I can reproduce this with latest RC on DynamoBIM - which is 0.8.1.1693 - can you please retry on fresh session. is there any other details that might be useful to reproduce this?

**Comment by andydandy74** [comment]
@monikaprabhu - I just tried it again on 0.8.1 RC2 and on my end it's reproducable. if it helps, here's a screenshot of the custom node.
![exteriorangle](https://cloud.githubusercontent.com/assets/3014437/8481473/9041a7a0-20e3-11e5-9bc7-9c3a518b0afe.PNG)
I think I found the cause: If the label is set to ```My_label_name : double``` I get the transposed preview output, when it's set to ```My_label_name : double[]``` the preview output is the same as the actual node output.

**Comment by ke-yu** [comment]
@andydandy74 , exactly. `{30, 60, 90}` replicates for input `Angle : double`.

**Comment by andydandy74** [comment]
@ke-yu - so you're saying this behaviour is to be expected? The actual node output in both cases (```labelname : double``` vs. ```labelname : double[]```) is the same. Shouldn't the output of the preview bubble be the same as well?

**Comment by ke-yu** [comment]
@andydandy74 , preview has some problems actually, it doesn't show key-value pair in the array. @monikaprabhu , shall we log a bug?

* For `angle: double`, as there are two outputs in this custom node, the actual output of this custom node for a single value is an array with two keys. So for example for input `30`, the output looks like `{"360-Angle": 330, "180-Angle":150}`. As the input is an array, `{30, 60, 90}` replicates, the aggregated result of three inputs looks like:
```
{
    {"360-Angle": 330, "180-Angle":150}, 
    {"360-Angle": 300, "180-Angle":120}, 
    {"360-Angle": 270, "180-Angle":60}
}
``` 
Now connecting one of output, say "360-Angle" to watch node, it goes recursively into the array to get the values for key "360-Angle".

* For `angle : double[]`, no replication for inputs, but replicates on `360 - angle` and `180 -angle`, so the outputs of *code block node* are `{330, 300, 270}` and `{150, 120, 60}` respectively. As there are two outputs, the final result looks like:
```
{
    {"360-Angle": {330, 300, 270}},
    {"180-Angle": {150, 120, 60}}
}
```

**Comment by sharadkjaiswal** [comment]
@ke-yu can we organize the preview of multiple output node as list of all the output values, so that whether it replicates or not, output is shown the same way to the users.

**Comment by monikaprabhu** [comment]
I meant to send this before Sharad's request above. 

The result will be different if the input is array or replication.

Below functions explain this with for more clarification - "AngleWithType" is equivalent to input define as "Angle:double" in custom node  and only "Angle" as input is equivalent to "angleNoType"
If you want the result as same and be able to define type then give "Angle:double[]" as Input.Does that satisfy the requirement here? 

![angle](https://cloud.githubusercontent.com/assets/5218721/8493904/2ffce990-2192-11e5-9a6d-8de7e7368328.png)

**Comment by andydandy74** [comment]
@monikaprabhu - No, it does not, because then a single item input will be forced into a nested list output.

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/46421200-e0c01180-c6ee-11e8-9d49-d8f6eae95979.png)
Persists in 2.0.x

**Comment by andydandy74** [comment]
@QilongTang I am sorry, but if this is behaving "as expected", the design ought to be reexamined. I am fairly certain most users would **not** "expect" this behaviour. There is an obvious discrepancy between the actual output of the outports and the contents of the preview bubble.

Setting the input type to ```var[]``` seems a bit overkill to me. I can just add a ```[]..[]``` behind the existing input type in most scenarios. That will a) not force singletons into a single-list-item output and b) retain the type checking for that input.

**Comment by mjkkirschner** [comment]
Thinking on this a bit more - we should compare the results to a zt multiple output node with the same type parameters to compare behavior . I would expect them to behave the same - and I’m not sure that is the case.

**Comment by aparajit-pratap** [comment]
This is as designed and how replication works in Dynamo. For it to give “user expected” results we would need to re-examine the behavior of multi output nodes that output dictionaries. I don’t think this issue should be tagged as a bug outright.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
