### ISSUE TITLE
Mass floor belongs to which Mass?

### ISSUE THREAD

**Issue by ekkonap** [DynamoDS/Dynamo#4828]
I'd like to vote for incorporation of Andreas Dieckmann's latest invention to the core functionality of Dynamo: to obtain the mass that a mass floor intersects from the API instead of performing a geometry intersect operation. See:
http://dynamobim.com/forums/topic/find-mass-floors-mass-id/

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2171).
