### ISSUE TITLE
Bug in 0.8.0

### ISSUE THREAD

**Issue by ekkonap** [DynamoDS/Dynamo#4829]
See also this thread: http://dynamobim.com/forums/topic/find-mass-floors-mass-id/

I am comparing geometry extacted from Mass Floors (Element.Faces) to geometry extracted from the intersection of horizontal planes at created at the elevation of the project Levels and solid geometry obtained from Masses. (Geometry.IntersectAll).

Unexpected result is that at a certain distance from origin, the geometry from the intersection of the panes and solid geometry gets cropped to a cylindrical volume that is centered around the origin, see image.

![capture1](https://cloud.githubusercontent.com/assets/12673938/8455524/999015dc-2005-11e5-8a77-bc949626c2f0.png)

That in turn causes a mismatch when I try to compare the geometry at the edge of this 'ghost' cylinder to the geometry from the Mass Floor faces, not to mention missing stuff outside the cylindrical ‘range’.

Anyone recognize this behaviour? Perhaps fixed in daily build? Solutions to circumvent?

**Comment by andydandy74** [comment]
This could be a clipping issue - if your project units are set to ```mm```, try changing them to ```m``` and see if the problem persists.
