### ISSUE TITLE
Context Menus in Package Manager

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#483]
I would expect the context menu in Installed Packages to only show me those commands that actually make sense (or some commands could be inactive / greyed out):
- Either the Deprecate or the Remove Deprecation option - or neither if I'm not the maintainer.
- Either Publish (if I have created a package, but haven't published it yet) or Publish Version - or neither if I'm not the maintainer.

And Show Types could, in my opinion, be more aptly named, perhaps Show Package Content or Show Nodes?

**Comment by Racel** [comment]
@andydandy74 - we will not be addressing these in the WPF UI, but will consider for next generation UI. Closing for now.
