### ISSUE TITLE
Repeated restarts required when revising functions

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4837]
Ver: 0.8.2.1814 (also in Dynamo Studio)
OS: Win 7

Flattening sub lists by defining functions does not seem to be working as expected. 
Or, am I doing something wrong?

A portion of [this] (http://a360.co/1C0Lpu9) file is shown below.
I would have expected the results from calling the function to be similar to those obtained by using the Map node. Tried a number of variations, but just unable to obtain a similar output using design script.

![20150701-1](https://cloud.githubusercontent.com/assets/5621624/8469682/8b195404-209c-11e5-80b8-666915d58f86.jpg)

**Comment by vykrum** [comment]
A clearer example of the above mentioned problem and the [file] (http://a360.co/1IPOP0e) 
![20150701-2](https://cloud.githubusercontent.com/assets/5621624/8470005/223c3996-20a2-11e5-840e-731a47e74b98.jpg)

**Comment by sharadkjaiswal** [comment]
I think you need to use imperative block to perform List.Map equivalent as follows:

![image](https://cloud.githubusercontent.com/assets/1754137/8470819/da3d88bc-20c3-11e5-85ba-5b13936566c5.png)

**Comment by vykrum** [comment]
@sharadkjaiswal  Not necessary. It should work in Associative mode too by defining a function.
Actually, what I've just realized is that it works ... BUT... only if you save, close and reopen every time you alter the function.

In this [discussion] (http://dynamobim.com/forums/topic/node-to-designscript/) on the dynamo forum I had elaborated on the approach. It works, but seems unreliable. Requires regular reopening of the file for correct results, if functions are being altered or redefined.

Below is a simple example of how I usually use functions to obtain the functionality of the Map node, instead of Imperative blocks and loops.

![20150702-2](https://cloud.githubusercontent.com/assets/5621624/8471138/df4b70dc-20b2-11e5-8e13-dad1130b1d38.jpg)

**Comment by vykrum** [comment]
This [file](http://a360.co/1H29hgj) solves the originally raised problem. The title I've given the issue is probably inaccurate as the issue isn't specific to just Flatten.

The larger issue seems to be the unreliability and incorrect results obtained while working on refining a function definition.

![20150702-3](https://cloud.githubusercontent.com/assets/5621624/8471327/b7384eba-20b4-11e5-9f6b-44558823fb5e.jpg)

**Comment by vykrum** [comment]
@sharadkjaiswal  Could you kindly elaborate on the use of **var[]..[]** in your definition. 
Is that an efficient alternative to the multiple sets of **[]** I have used to indicate the depth of the sub lists to be accessed, in the functions I've defined?

I've learnt mostly by trial and error  :smile:, would appreciate if you could help me understand the syntax.

Thanks.

**Comment by sharadkjaiswal** [comment]
var[]..[] is used for arbitrary rank array, that means array can be of any dimension. So when this type is used, function will not replicate.

**Comment by vykrum** [comment]
@sharadkjaiswal Thanks.
