### ISSUE TITLE
Migration issue: Custom nodes get migrated by name not by unique ID

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4839]
I just ran into this by accident. There are custom nodes called List.ChopByLengths in both the Ampersand and the Clockwork package. When migrating a graph that contains both nodes from 0.7 to 0.8 all instances of those nodes will be set to the node from the Ampersand package. Why do custom nodes have unique IDs when they aren't used in a process as crucial as migrating a workflow to the next Dynamo version?
0.8.1 RC 2

**Comment by andydandy74** [comment]
If you look at [this diff](https://github.com/CAAD-RWTH/ClockworkForDynamo/commit/79372142ee530fe8d5d68e961706226f873d3605), you will notice how the ```ID value``` of the second node has changed (line 17) after migrating from 0.7 to 0.8 ...

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
