### ISSUE TITLE
Wish: Deprecation / New Version Warning or Notification

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#484]
Is there some functionality planned that will let users know they are using deprecated packages or that there is a newer version available of a package they have installed? (Actually I could have sworn there used to be a button in the package manager to download the latest version of a package...)
I think this would be quite useful in the console at startup and also in the installed packages section.
(Currently I would either have to compare the version numbers in Online Package Search and Installed Packages or go to the Package Manager Website and scroll all the way down.)

**Comment by Racel** [comment]
We do not have any plans to work on the WPF UI of package manager. This will be addressed in the next generation UI.
