### ISSUE TITLE
display in workspace

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4842]
daily builds 082...
when working on a model with distant coordinateslike a  line from  (430601.553,433679.124,41.518) to430595.338,433671.845,46.938)
the elements are displyayed in the center of the screen looking like a point.
if you zoom in you may get closer but not close enough. when the graphics is about 2 cm in size it will collaps back to the point
![image](https://cloud.githubusercontent.com/assets/6928491/8474446/587d5e96-20b0-11e5-8ca1-dd9c54d46977.png)
my wish zoom window command

**Comment by alfarok** [comment]
Was not able to reproduce in newer Dynamo release.  You also now have the ability to modify the geometry scaling settings for large models in the Dynamo -> Settings menu.

![image](https://user-images.githubusercontent.com/13341935/32506107-bdd6bc0a-c3b1-11e7-8550-82f0ceea1b09.png)
