### ISSUE TITLE
List.Join not accepting all types of single elements

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4849]
One thing I really like about the List.Join node is the fact that you can also pass single elements to it. I just discovered that this functionality does not work for all data types (see screenshot below). It would be nice if it would.
![listjoin](https://cloud.githubusercontent.com/assets/3014437/8493757/e5306eb0-215e-11e5-88f7-7055be24843a.PNG)
0.8.1 RC2

**Comment by ke-yu** [comment]
Hi @andydandy74  the workaround is connecting `Vector.XAxis` to `List.Create` to create a list.

**Comment by andydandy74** [comment]
Thanks, @ke-yu - I am aware of that, but I just think it would be nice if the List.Join behaviour were consistent for all data types... ;-)

**Comment by ke-yu** [comment]
@andydandy74 sure, will do. @monikaprabhu shall we log a bug?

**Comment by kronz** [comment]
@andydandy74 I'm actually surprised that it works at all with single items, although I'm glad it is forgiving enough to do so.  Are you expecting the same behavior here as List.AddItemToFront. How do you expect them to be different or the same?

**Comment by andydandy74** [comment]
@kronz - I hardly ever use List.AddItemToFront any more because I find the behaviour of List.Join preferable, since it behaves the same way for single items and lists (adding items in a flat structure). I hardly ever need the behaviour of adding a sublist to the front of a list (as provided by List.AddItemToFront).
![joinvsaddtofront](https://cloud.githubusercontent.com/assets/3014437/8563296/7ca4fc7a-253d-11e5-9506-8bbf1901dd73.PNG)

**Comment by kronz** [comment]
@andydandy74 agreed.  @ke-yu @monikaprabhu can you record this as a bug against List.Join that it should take all inputs, as described here? File as a subtask of High Value bugs in Major?

**Comment by monikaprabhu** [comment]
Im filing this at - MAGN-7888. The issue is with accepting geometry types and revit nodes. 
![join](https://cloud.githubusercontent.com/assets/5218721/8671238/06a46ac4-2a56-11e5-8f5a-b72b8288357c.png)

**Comment by andydandy74** [comment]
Looks fixed in 0.8.3.2514 - thanks!
