### ISSUE TITLE
Background model

### ISSUE THREAD

**Issue by afandianzo** [DynamoDS/Dynamo#4851]
HI
I just downloaded 0.8.1 I can't see the model in work space background and even in watch 3D. Also I cant translate my model to Revit

**Comment by jnealb** [comment]
@afandianzo Was your model working with 8.0? What type of graphics card do you have? Thanks, Neal

**Comment by afandianzo** [comment]
Neal,
Yes it was working with 8.0 and still I am using 8.0 because of that. the graphic card is Radeon HD 6770M.
Thanks,Abdulaziz 


     On Monday, July 6, 2015 6:57 PM, Neal Burnham <notifications@github.com> wrote:
   

 @afandianzo Was your model working with 8.0? What type of graphics card do you have? Thanks, Neal—

**Comment by jnealb** [comment]
@afandianzo Thank you - if possible, can you email your model etc to us? That will help us debug; neal.burnham@autodesk.com

**Comment by jnealb** [comment]
@afandianzo Do the Dynamo samples display with 8.1?

**Comment by jnealb** [comment]
@afandianzo This is being tracked with MAGN-7841.

**Comment by ikeough** [comment]
@afandianzo Please follow the steps [here](http://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/Crash-on-systems-with-integrated-Intel-HD-and-discrete-GPUs-Nvidia-AMD.html), to make an exception for DynamoSandbox, or for Revit.exe

**Comment by Curty102** [comment]
I have nearly the same issue.  Everything worked before 8.1, now no background preview, no watch 3D.  I went to the link Ian posted and IT has played with all kinds of settings.  I have an AMD Radeon HD 8690M and have manually set both Revit and Dynamo Sandbox to high performance settings, but no go, just a blank background (grey or black depending on the graphics settings on the laptop).  Existing files and brand new Revit/Dynamo file combos--neither work.  Thanks--  Nick 

![comp_3d](https://cloud.githubusercontent.com/assets/13457861/8851681/ac9ed9a2-3116-11e5-801d-ed04a5533534.png)
![comp_specs](https://cloud.githubusercontent.com/assets/13457861/8851680/ac9e397a-3116-11e5-8812-debfab5dc0a3.png)

**Comment by jnealb** [comment]
@Curty102 We are working on this issue and tracking it with MAGN-7841

**Comment by tcacciuto** [comment]
@jnealb jnealb - there is any update about this graphic issue? I have the same problem

**Comment by jnealb** [comment]
@tcacciuto @Curty102 @afandianzo @ikeough We anticipate providing you with a Helix updated Dynamo build in the next couple of weeks which should help with these graphics rendering issues.

**Comment by afandianzo** [comment]
I am happy to hear that. Thank you.

Sent from Yahoo Mail on Android

**Comment by Curty102** [comment]
+1!

Nick

Sent from my HTC

----- Reply message -----

**Comment by jnealb** [comment]
@Curty102 @afandianzo Can you please try again with the latest daily build (10/1) when our website (Dynamobim.org) is back up?

**Comment by jnealb** [comment]
@Curty102 @afandianzo Update: you can get the build now from http://dynamobuilds.com

**Comment by Curty102** [comment]
Will be next week before I can try.  Office is moving!  Talk then, and thank you!


Nick






Sent from Windows Mail





From: Neal Burnham
Sent: ‎Thursday‎, ‎October‎ ‎1‎, ‎2015 ‎4‎:‎21‎ ‎PM
To: DynamoDS/Dynamo
Cc: Nick Curtis





@Curty102 @afandianzo Update: you can get the build now from http://dynamobuilds.com

**Comment by afandianzo** [comment]
still it is not working.

Sent from Yahoo Mail on Android

**Comment by Curty102** [comment]
Neal,
FYI, the Dynamo Background still is not working.  I'm running Windows 7 Enterprise, Revit 2015, Dynamo 0.9.0.2772.  Per Ian Keough's suggestion to follow this link:...
http://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/Crash-on-systems-with-integrated-Intel-HD-and-discrete-GPUs-Nvidia-AMD.html
...I've had IT update all of my display drivers, and we've set the Graphics Setting for both Revit and Dynamo to High Perforamance.  One other strange thing is that I have a dual monitor setup, both monitors virtually identical, but the background shows up beige on Display 1 and Black on Display 2. ?? 
I can get you any other information you need about my setup, just let me know.
Many thanks,
Nick Curtis

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
