### ISSUE TITLE
Small bug in PreviewGraphAsyncTask.cs

### ISSUE THREAD

**Issue by Muraad** [DynamoDS/Dynamo#4856]
Hey, i just found this

    internal PreviewGraphAsyncTask(IScheduler scheduler, bool verboseLogging1)
        : base(scheduler)
    {
        verboseLogging = verboseLogging;
    }

The ```this``` is probably missing.

Greetings!

**Comment by monikaprabhu** [comment]
@junmendoza - could you please take a look at this?

**Comment by ikeough** [comment]
Fixed in #6578.
