### ISSUE TITLE
Wish: Dependency warning when deprecating a package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#486]
When I deprecate a package that is used in another package, I should get a warning like "The package you are about to deprecate is currently being used by the following packages: .... Are you sure you want to go on?" or similar. 

The dependencies are known to the package manager, so it would be good to inform the user of the consequences of his actions...

**Comment by Racel** [comment]
As mentioned in other comments, there are no plans to work WPF UI of package manager in the near future. Will consider this option for the next generation UI which will be handled in a different repo.
