### ISSUE TITLE
Cleanup Node Layout breaks groups

### ISSUE THREAD

**Issue by seandburke** [DynamoDS/Dynamo#4868]
The Cleanup Node Layout (Ctrl+L) command causes members of a group to bounce around and boundary grows unpredictably. It should respect groups and move the whole group if enabled. Maybe it needs a new name too, if its purpose is to organize multiple element types now. (Text Notes, Groups and Nodes).

**Comment by monikaprabhu** [comment]
@jnealb , @kronz - have you filed a task for this - please post the id here.

**Comment by jnealb** [comment]
@seandburke Have you been able to test the new graph layout?

**Comment by seandburke** [comment]
Seems to function as expected now with the stable 0.8.2.

**Comment by jnealb** [comment]
@seandburke Thank you for the prompt feedback.
