### ISSUE TITLE
CTR+G in 0.8.1 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4869]
Does CTR+G no longer toggles to geometry preview and back to node canvas?

**Comment by jnealb** [comment]
Ctrl-B now

**Comment by ksobon** [comment]
I just tried that and it managed to Crash my session of Dynamo/Revit. Something is not right with the preview.

**Comment by ikeough** [comment]
Feels like the command binding is detached for Ctrl+B.

**Comment by jnealb** [comment]
@ksobon @ikeough With 0.8.1.1823 I am able to use Ctrl-B at will with Dynamo/Revit. Can you give us more details please? The dyn used, graphics adapter, version of Revit, workflow if possible. Thanks.

**Comment by ksobon** [comment]
@jnealb I was on the Dynamo 0.8.1 - latest stable build. I have NVIDIA Quadro K2000 on this machine. Revit 2015 20150303_0715(x64) Update Release 7. Imported large mesh from Grasshopper using Mantis Shrimp and tried to zoom, pan etc in the background preview to get it centered when it crashed. I got to admit that I was immediately annoyed and uninstalled Dynamo going back to 0.8.0 so I can finish working on Mantis Shrimp updates.

**Comment by jnealb** [comment]
@ksobon Can we get access to your large mesh etc?

**Comment by ksobon** [comment]
you can make a Torus in Rhino and then wbCatmullClark it a few times to get polygon count to roughly 400 000. It wasn't anything special, just had a large polygon count.

**Comment by ksobon** [comment]
It works in the latest daily. CTRL+B it is!
