### ISSUE TITLE
background preview 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4872]
Background preview of Mesh geometry is HORRIBLE:

![capture](https://cloud.githubusercontent.com/assets/529781/8552314/53ad56f2-24aa-11e5-9565-4a76860073f9.PNG)

![capture1](https://cloud.githubusercontent.com/assets/529781/8552320/5972872e-24aa-11e5-9302-cd0089c1809f.PNG)

**Comment by ikeough** [comment]
Yeah. Definitely looks like normals are not correct for that geometry. We'll check that out. The jaggies around the edge are a depth buffer precision issue that is fixed in the dailies.

**Comment by ksobon** [comment]
its not just that mesh is a little jagged around the edges. The whole experience of navigating (zooming, panning, rotating) is really JUMPY. Thanks for clarifying the other issues.

**Comment by ikeough** [comment]
I assume that this model is either in mm or has very large imperial units.

**Comment by ksobon** [comment]
most likely very large imperial units. Why does it matter though?

**Comment by jnealb** [comment]
@ksobon @ikeough Yes, we are tracking zoom, pan and rotate issues with MAGN-7186, 7120.

**Comment by dbaldacchino** [comment]
I've had this same experience when working on the out of the box Revit Arch Advanced model, which is in metric (mm).

**Comment by ikeough** [comment]
@dbaldacchino @ksobon We worked on the issue with mesh visualization for meshes with large units a while back and I never checked back. Can you please confirm that large meshes (ex. meshes in mm in Revit) preview correctly in Dynamo?

**Comment by ikeough** [comment]
@dbaldacchino Any update?

**Comment by dbaldacchino** [comment]
Sorry @ikeough ; will get back with an answer ASAP.
