### ISSUE TITLE
Revit API issue or ...: MEP parameters

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4879]
I got a weird problem here, wanting to access to some geometrical parameter of conduit.

only geometrical calculation returns correct result. any idea??

![image](https://cloud.githubusercontent.com/assets/4572196/8569925/bed4ed64-257c-11e5-9c3e-db6453e64952.png)

![image](https://cloud.githubusercontent.com/assets/4572196/8569933/cec38ca8-257c-11e5-89a6-5a724d9edc7c.png)

**Comment by jbenoit44** [comment]
I'm working on latest daily.

**Comment by jnealb** [comment]
@jbenoit44 Can you please send me your dyn and rvt project: neal.burnham@autodesk.com? It is hard to read the contents of the watch nodes here and I can test in French windows. What values are being returned by GetParameterValueByName? On another note, could we ask you to provide us with some feedback regarding the strings in the French localized Dynamo (8.2)? We are grateful for your comments on our FR computerese.

**Comment by jbenoit44** [comment]
done.  feedback will come later, in august. see you!

**Comment by jbenoit44** [comment]
works fine with Convert between Units node, tested in stable 0.8.1
