### ISSUE TITLE
display images...

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4884]
Is this many steps really necessary? 

![capture](https://cloud.githubusercontent.com/assets/529781/8583350/e22ac856-259a-11e5-9081-60ff8e6efdde.PNG)

**Comment by ikeough** [comment]
Yes. We made a choice to separate `File` and `Image` operations into several nodes in order to increase their usability across many different scenarios. I'd be happy to review any PR submitted to "improve" on this.
