### ISSUE TITLE
Publish package in Dynamo sandbox

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4889]
Ver: 0.8.2.1881

Unable to sign in to an Autodesk account and publish to package manager in stand alone mode. 
Is this by design?

![20150709-2](https://cloud.githubusercontent.com/assets/5621624/8593802/a6afa3b4-2658-11e5-974f-4dd3f92cd5a7.jpg)

**Comment by andydandy74** [comment]
I think this is one of the things that separates Dynamo Studio (possible) from Dynamo Sandbox (not possible).

**Comment by pboyer** [comment]
Yes. You cannot sign into Dynamo standalone.

**Comment by RodRecker** [comment]
Andreas is correct - Dynamo Studio will allow this. @vykrum - You can publish your package by starting from Dynamo for Revit. It uses the Autodesk ID associated with Revit to publish the package.
