### ISSUE TITLE
package manager issues when migrating to 0.8.1 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4893]
I have been made aware by users that some nodes from my package went missing after they installed 0.8.1 which is also what I have noticed on my end. 

https://twitter.com/60secondrevit/status/619143759960248320

Thanks! 

@ikeough @pboyer

**Comment by aparajit-pratap** [comment]
I'm taking a look at this issue. It's related to https://github.com/DynamoDS/Dynamo/issues/4894

**Comment by aparajit-pratap** [comment]
This issue has been fixed here: #4901

**Comment by riteshchandawar** [comment]
Hello @ksobon, Did you uninstall 0.8.0 manually before installing 0.8.1?

Thanks,
Ritesh

**Comment by ksobon** [comment]
No I did not. I installed 0.8.1 on top of my 0.8.0 install.

**Comment by ikeough** [comment]
@ksobon Is this still an issue after the fix mentioned above?

**Comment by ksobon** [comment]
I haven't noticed. Feel free to close.
