### ISSUE TITLE
Crash Report - 20150711-Autodesk Dynamo Studio 2016

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4910]
While creating a node from selection, if the Category field is left blank, the below error is displayed and Dynamo shuts down on clicking OK.

![20150711-1](https://cloud.githubusercontent.com/assets/5621624/8632436/172caf4a-27b9-11e5-8247-e6f185d15566.jpg)

**Comment by monikaprabhu** [comment]
We have fixed this in 0.8.1.xx - Dynamo Studio version is 0.8.0.xx
