### ISSUE TITLE
Package Manager and DynamoPackages.com are down

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#4913]
A few of my clients and I are seeing that the Package Manager and DynamoPackages.com are not available.  We cannot access packages.  Is there something going on?

![image](https://cloud.githubusercontent.com/assets/1890663/8634824/6a3257d4-27ce-11e5-98ba-53a862b11fb8.png)

![image](https://cloud.githubusercontent.com/assets/1890663/8634826/84782aa6-27ce-11e5-85e0-b5efefb0c85f.png)

**Comment by lukechurch** [comment]
Thanks for the notification. I can confirm that I've got back from dinner to an inbox that is glowing red with alarms.

**Comment by lukechurch** [comment]
And we're back. Sorry for the inconvenience @archinate, and we apologise to your clients. We'll look into what went wrong.

**Comment by archinate** [comment]
Thanks, @lukechurch !
