### ISSUE TITLE
Background graphics only displays latest node geometry

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4914]
Ver: 0.8.2.1915
OS: Win 7

Below is a screen grab with two code blocks with Imperative code (copied from the Dynamo Language Guide)

On opening the file and running the background graphics displays as expected (as in the image below)
![20150712-1](https://cloud.githubusercontent.com/assets/5621624/8636576/b2a07258-2887-11e5-9db6-83967b43c399.jpg)

On changing a variable name (The first line in Code Block-2 from *a* to *b*) the graphics of Code Block-1 disappears, even though no changes are made to *Preview* in the right click menu (it remains checked)
![20150712-2](https://cloud.githubusercontent.com/assets/5621624/8636586/2a6bc968-2888-11e5-9759-630233da1adf.jpg)

**Comment by vykrum** [comment]
Just noticed that this isn't limited to imperative code blocks.

This is the behavior with any node or code block. Only the graphics of the last node/block inserted is visible.

Can replicate the case even with separate successive *Point.ByCoordinates* node.

**Comment by jnealb** [comment]
Thank you - this is tracked with MAGN-7874.

**Comment by jnealb** [comment]
@vykrum @ikeough Double thank you! - there are two issues here, the second is MAGN-7880. Some sort of prize is in order?

**Comment by jnealb** [comment]
@vykrum @ikeough @pboyer Can you please try again with the latest daily: DynamoInstall0.8.2.20150715T0448. We think both issues are resolved.

**Comment by vykrum** [comment]
@jnealb The background preview seems to be back in order in 0.8.2.1954. Thanks
