### ISSUE TITLE
Graphic display is completely white and not displaying the Structure

### ISSUE THREAD

**Issue by engsabbagh** [DynamoDS/Dynamo#4917]
I am using Revit structure 2015 (Service Pack 8) & Dynamo 0.8.1.1052 and the Graphic display is completely white and showing the structural model generated from the Nodes.
Display Adapters: NVIDIA Quadro FX1800
![err](https://cloud.githubusercontent.com/assets/12892747/8649583/61f1cdaa-2974-11e5-984b-2e96a2847267.png)

**Comment by jnealb** [comment]
@engsabbagh Can you please remove and add DynamoSandbox from the NVIDIA Control Panel's "Manage 3d settings"?

**Comment by engsabbagh** [comment]
Thank you very much jnealb
