### ISSUE TITLE
Watch3D over exposed when opening a file with multiple watch3D nodes.

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#4920]
When opening a file with multiple Watch 3Ds, each preview looks over-exposed, as does the Dynamo preview.  My only workaround currently is to copy and paste a watch3D node or add a new one to the graph.

**Comment by ekatzenstein** [comment]
Version 0.8.2.1873

**Comment by ikeough** [comment]
@ramramps I believe we've seen this before.

**Comment by jnealb** [comment]
@ekatzenstein What graphics adapter are you running on?

**Comment by ekatzenstein** [comment]
NVIDIA Quadro K1100M

**Comment by jnealb** [comment]
@ekatzenstein Does the NVIDIA Control Panel provide a "Manage 3d settings" which allows you to remove and add the Dynamosandbox.exe process? Can you select "High performance NVIDIA Processor" as an option for DynamoSandbox.exe?

**Comment by ekatzenstein** [comment]
@jnealb, that update has solved the issue.  To complicate things, I also installed the stable version of Dynamo, so I'm not sure if that factored in.  thanks.

**Comment by jnealb** [comment]
@ekatzenstein Good news!
