### ISSUE TITLE
Watch3D node does not maintain size 

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#4921]
Funky bug.  When reopening a graph with a watch3D node, the node always seems to get larger.  Really crappy when trying to format a graph.

**Comment by jnealb** [comment]
@ekatzenstein Which version of Dynamo are you using?

**Comment by ekatzenstein** [comment]
Sorry I neglected to add that: Version 0.8.2.1873

**Comment by jnealb** [comment]
@ekatzenstein We are investigating, will update you.

**Comment by monikaprabhu** [comment]
Thanks for reporting this - number to track this - MAGN-7995

**Comment by jnealb** [comment]
@ekatzenstein This is fixed with 8.2, closing.
