### ISSUE TITLE
Level.ProjectElevation

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4929]
Isn't this node supposed to report the level elevation based on the Project Basepoint, or am I misinterpreting its function? It gives the exact same results as Level.Elevation (the description for the latter says "The elevation of the level from ground level": what is "ground" level? The description should state that the measurement is based off the Internal Origin or something like that). Level.ProjectElevation says this is relative to the "Project" origin, which I was assuming is determined by the Project Basepoint since that's one of the options you can set a Level to read from. There's no way to report the level elevation based on Project Internal (fixed) Coordinates. Thanks.

**Comment by Randy-Ma** [comment]
@dbaldacchino 
Thanks a lot for giving us feedback about the two nodes!

Your understanding about Level.Elevation is correct.

Level.Elevation will give the value according to the origin of the view. (I think this is the one that you are looking for) While Level.ProjectElevation will give the value according to the origin of the Project Base Point. Note that there are unit conversions for these two values.

If the elevation of the Project Base Point is changed to a value which is not 0, then Level.ProjectElevation and Level.Elevation will return different result.

**Comment by dbaldacchino** [comment]
Thanks, then I think you have them reversed. Level.Elevation is functioning like Level.ProjectElevation should and vice versa. Here's what I'm talking about in the image below. There's also another problem: the elevation is not updating automatically when this changes in the project. I'm on 0.8.2.1957 (DynamoInstall0.8.2.20150724T0842.exe). Thanks.

![level elevations](https://cloud.githubusercontent.com/assets/4656191/8879885/33355bce-31fa-11e5-9801-8ab6832004ec.png)

**Comment by Randy-Ma** [comment]
### For your first question

I am not saying Level.ProjectElevation and Level.Elevation are not reversed. But I have updated it a bit.

In the case presented, Level.ProjectElevation and Level.Elevation will both return 4 (in feet). But as I can see, it is returning different values in your case. It may be because not the whole graph has been updated yet.

### For your second question

We need to address this. But the underlying logic might be not simple and it may take us time.
@ikeough Ideally when there is a change to an element, we need to mark the corresponding node as dirty and make the graph run again.

**Comment by dbaldacchino** [comment]
Hi @Randy-Ma , I'm sorry but I have to disagree.
The level shown above is located right at Z=0 (global coordinate system; fixed). Level.Elevation should be reading 0 but it is not. Level.ProjectElevation is reading zero, which is incorrect if this is supposed to read from the Project BasePoint, which was lowered by 4'-0" in my example above. So Level.ProjectElevation is behaving like Level.Elevation SHOULD be.

I have not made changes to the Shared Coordinate system in Revit for the above example. That brings up another feedback item: we need a node that reads elevation based on the Survey Point. I hope I'm being clear. You might want to ping @kronz about the above, thanks.

**Comment by Randy-Ma** [comment]
@dbaldacchino 
I guess you are moving the <b>unclipped</b> project base point while I am moving the <b>pinned</b> project base point and then update the level. This is the reason why we are getting different result.

@kronz 
Could you help clarify the expected result of Level.Elevation and Level.ProjectElevation?

**Comment by dbaldacchino** [comment]
Hi @Randy-Ma , when we set a level to report based on the Project Base Point (PBP), it give us the distance relative to the location of the PBP icon. As you can see above in my example, it is 4'-0" below the level. If you move a clipped PBP, you are moving the shared coordinate system by the same magniture but in the opposite direction. The relation of the PBP to the Level does not change, which is why in your test you are seeing 0 being reported for both nodes. There is nothing right now to report the elevation relative to the Survey Point, hence my additional request in my previous post.

**Comment by kronz** [comment]
Hi @dbaldacchino @Randy-Ma ,
Lemme see if I understand the issue.  The existing tools SHOULD allow users to do 2 things: 
A. extract the Level's elevation as it is shown in the UI, as most people see it.  This is the only one people should usually want to get, the one that has a direct corespondance to what is seen in documents.
B. extract the Level's elevation relative to the fixed and invisible coordinate system that underlies the whole operation that is only visible to the API.  This is a long running complaint about how Revit works, that it has never REALLY exposed the document origin at a user level. This should really only be needed by BIM managers or others doing some amount of auditing of files or trying to coordinate with other projects that involve imports.   

From what I see right now, with refresh weirdnesses and naming, it is super confusing.   I suspect that Level.Elevation is showing A (UI Elevation) and Level.ProjectElevation is showing B (API Coordinates).  If we agree that A and B are the 2 things that should be provided in Level queries, let's do this
- correct whatever refresh issue there is
- There should be a "Level.Elevation" node that should show the UI exposed elevation as it is seen in drawings and have the description:  "Elevation of the Level relative to Survey Point or Project Base Point" 
- There should be a "Level.CoordinateSystemElevation"  that returns the distance from the non-user exposed internal origin with the description  "Elevation of the Level relative to the internal API coordinate system"

**Comment by dbaldacchino** [comment]
@kronz @Randy-Ma here are some more comments and clarifications based on Zac's post:

A) In the UI, the user has two options to pick from: Project Base Point (PBP) or Survey Point (SP - the latter is bad terminology as it really means "Shared Coordinate System Origin"...I can elaborate on that if needed). We need a node that either takes this as an input string or simply lets us pick from a built-in drop down list. Alternatively have two separate nodes (I'm not a fan of adding more nodes) that are clearly named with a clear description of what they do.
B) AMEN! Currently the workaround in the UI is to move the Project Base Point to the StartUp location, then in essence the level reads its position relative to the fixed origin ("project internal origin"). However in Dynamo currently Level.ProjectElevation is reading relative to the internal API coordinate system: the name and description are incorrect.

To reiterate, Level.Elevation is reading the elevation relative to the Project Base Point: the name and description are also incorrect. There is currently no way to read relative to the Shared Coordinate System origin (which the UI refers to erroneously as "Survey Point"). We need this to be an available option in your suggestion for A) in addition to the ability to report the elevation relative to PBP.

**Comment by kronz** [comment]
@dbaldacchino PBP and SP are Type parameters for Elevations, so I don't know that we can differentiate at the API level, or if it even makes sense to?  That is, if you are asking what the Elevation at the UI level is for a given collection of levels, it has been set in the Elevations type to be measured one way and NOT another.

**Comment by dbaldacchino** [comment]
Ohhhh I completely understand, my apologies. I forgot for a moment that we are querying an actual level object, which as you pointed out has that set as a type property. I'll go back in my hole now...

**Comment by dbaldacchino** [comment]
I had some more time to think about this...

I think it would be valuable to be able to query a level and retrieve elevations irrespective of what the level says, hence my thoughts about node/s that return relative to Internal, PBP and SP (Shared Coordinate origin). Let's say the team has levels set to read by SP but I need to run a definition that processes elevations based on PBP: If I pick levels, I would want the flexibility of processing data in Dynamo based on requirements independent of the level's type settings. Anyway, just a thought.

**Comment by kronz** [comment]
@Randy-Ma @ikeough Some more information on how "Project Internal" coordinate work versus "Project Base Point" . http://thebuildingcoder.typepad.com/blog/2015/08/internal-vs-base-point-and-link-to-host-coordinates.html#3

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2170).
