### ISSUE TITLE
CS by matrix

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#4934]
Hi, I noticed that creating a Coordinate System by matrix is labeled "deprecated."
Is this being replaced or removed completely?
Please keep this method. It is pretty useful for creating sheared geometry.

**Comment by ikeough** [comment]
@aparajit-pratap Any idea what the plans are here for being able to create a CS from a matrix?

**Comment by aparajit-pratap** [comment]
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10061

**Comment by ikeough** [comment]
@aparajit-pratap Thanks!
