### ISSUE TITLE
Searching "Select" does not display "Select Model Element/s" nodes

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4936]
It's all in the title. You have to at least type "Select M" to get the nodes to display.

**Comment by dimven** [comment]
:+1: 
Surprising  "sel me" brings it up.

**Comment by dbaldacchino** [comment]
Oh lol! Go figure :)

**Comment by monikaprabhu** [comment]
@dbaldacchino - what version are you using- with daily builds it seems to be working ok at my end

**Comment by dbaldacchino** [comment]
I'm using 0.8.2.2005

**Comment by jnealb** [comment]
@dbaldacchino @monikaprabhu @aosyatnik With the latest build, I find that you have to scroll "Selection - Actions" down for the nodes to be listed. Is this true for you? If so, yes, they should be nearer the top of hits, not be "down there".

**Comment by dbaldacchino** [comment]
Hi Neal, I just installed the latest build but the build number is actually older than the one above? I'm now on 0.8.2.1957 (DynamoInstall0.8.2.20150724T0842.exe) and this is what I see. Better, but as you point out if the node has "Select" in the name and you typed that, those hits should be promoted to the top.

![select](https://cloud.githubusercontent.com/assets/4656191/8879485/59679cd8-31f7-11e5-9964-cd123d297ffb.png)

**Comment by jnealb** [comment]
@dbaldacchino Yes, the build # is wrong, but the build is ok. We are re-working the Library Search, and this will be incorporated. Thanks! Keep 'em coming!

**Comment by ikeough** [comment]
The build # is not wrong. The last part of the build number is a number automatically generated by VS which is based on (I believe) the number of seconds since midnight of the day the build was made. It is not sequential.

**Comment by dbaldacchino** [comment]
Hmmm that's interesting. I would have expected it to be based on the date, hour and minutes of the time it was produced. That would give an increasing number so you knew exactly which was the latest. Anyway I'll also post the executable filename when reporting the build number moving forward to avoid confusion.

**Comment by jnealb** [comment]
MAGN-8001 tracks the "Select" not bringing up the "Select Model Element(s)" hits.

**Comment by johnpierson** [comment]
Seems related to https://github.com/DynamoDS/Dynamo/issues/5540
