### ISSUE TITLE
Feature Request: Select All in Code Block

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#4938]
Query all top lists in a list of lists with code block.  Maybe I've missed an existing functionality, but this would be nice to have: 

![alllists](https://cloud.githubusercontent.com/assets/6820526/8727331/184cf702-2bad-11e5-9081-98ec70fbba43.png)

**Comment by holyjewsus** [comment]
you can do this with List.GetAtIndex and replication, the syntax is a bit tricky though, let me get you an example

**Comment by holyjewsus** [comment]
<img width="1048" alt="screen shot 2015-07-16 at 11 30 19 am" src="https://cloud.githubusercontent.com/assets/508936/8727502/128b3b2a-2bae-11e5-9747-ef27f7463f3d.png">


does this work?

**Comment by ekatzenstein** [comment]
Works perfectly.  And it makes sense when I think about it.  Not intuitive though IMO.  It'd also be nice to use the shorthand rather than List.GetItemAtIndex.

**Comment by Amoursol** [comment]
I would also love the short-hand version Ekatzenstein is referring to.

**Comment by Racel** [comment]
You can get this now using List@Level

![image](https://user-images.githubusercontent.com/2551261/31632417-da817af8-b28a-11e7-94fa-5079f1cffd1b.png)

Closing
