### ISSUE TITLE
add nodes to get/set parameters of the active family doc (not loaded type/instance)

### ISSUE THREAD

**Issue by tatlin** [DynamoDS/Dynamo#494]
we need a way to get and set parameter if you are working in a family document.

note this is different than the getters/setters for family types and instances.
it's a pretty easy interfaces to deal with. 
doc.FamilyManager is the access point if active doc is family. iterate list and match name in same way as other param getters do. 

note that after setting you do need to regen the doc i think. 

http://wiki.theprovingground.org/revit-api-py-family

**Comment by luisfribeirinho** [comment]
Hello,

I have created a Phyton script to add type parameters and then another to set their values. The first one is running ok.
 
![image](https://user-images.githubusercontent.com/33350546/32376803-c01a6f50-c09d-11e7-9ccb-edd4e0bda65f.png)
![image](https://user-images.githubusercontent.com/33350546/32376815-cbfa5d80-c09d-11e7-975c-246c49b062ab.png)

 
However, the second not so much.
 
![image](https://user-images.githubusercontent.com/33350546/32376860-ec41257e-c09d-11e7-973e-4cf61c8c035e.png)

![image](https://user-images.githubusercontent.com/33350546/32376824-d724966c-c09d-11e7-9591-54276481f15c.png)

 
I do not understand why there is no current type. I have also noticed that if I change the values manually then the script runs. Any idea why this happens? Thank you

**Comment by johnpierson** [comment]
Going ahead and closing this as it's been a while. There are still no OOTB nodes in D4R to do this. However, we do have nodes available in Clockwork for Dynamo 1.x and Orchid that do this.

If someone feels this is worth reopening, we might want to do so on the [Revit issues](https://github.com/DynamoDS/DynamoRevit/issues) page.
