### ISSUE TITLE
AllTrue / AllFalse return True for empty lists

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#4940]
Shouldn't ```AllTrue``` / ```AllFalse``` return ```false``` when passed an empty list? I think they should only return ```true``` if the list contains at least one item (and if all items in the list satisfy the condition, of course).
![listemptyallfalsetrue](https://cloud.githubusercontent.com/assets/3014437/8743405/cf6433a8-2c6e-11e5-9ac6-31175721f89c.PNG)

**Comment by jnealb** [comment]
@andydandy74 Thanks - this is tracked with MAGN-7932.

**Comment by ke-yu** [comment]
@andydandy74,, @jnealb , that's expected. 

May I say that  "all items are true" (`AllTrue`) is logically equivalent to "there is no item which is false" (`Not (SomeFalse)`). Now consider an empty list. Obviously, as no item in an empty list, `SomeFalse` should return `false`, so `Not (SomeFalse)` returns `true`, then`AllTrue` returns `true`. Similarly for `AllFalse`.

So although at the first glance it is weird that both `AllTrue` and `AllFalse` return `true` for an empty list, but that's expected.

**Comment by andydandy74** [comment]
Thanks for clarifying that, @ke-yu - I guess I'll just have to make a custom ```AllTrue```/```AllFalse``` node that checks against ```List.IsEmpty``` beforehand.
