### ISSUE TITLE
Group Alignement

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/Dynamo#4942]
It would be useful to be able to align Group like we align Nodes

**Comment by jnealb** [comment]
@DanielHurtubise This is tracked with  MAGN-7344 "Make align works for groups"

**Comment by FlintSable** [comment]
I wish there was a Mr.Sprinkle for Dynamo to align all the nodes.

**Comment by Racel** [comment]
Align is still significantly messed up in the latest version of Dynamo. We plan on addressing this in the next generation UI, so I will close this for now as this repo relates to the existing WPF UI.
