### ISSUE TITLE
Nurbs Surfaces - weight property returns null 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4945]
This is related to work that I am doing with Mantis Shrimp hence geometry that I am dealing with is coming from Grasshopper originally. 

I have a RevSurface that I am exporting to Dynamo. I conveniently convert it to NurbsSurface (since at the moment RhinoCommon has not exposed any ON_RevSurface properties) and export to Dynamo. It all works great. I get exactly the same Nurbs Surface in Dynamo. Awesome! 

Here is the trick:

When I try to take this - now DS - surface and export it back to Grasshopper a little funny thing occurs to me. Somehow, somewhere Dynamo figured that this Nurbs Surface was rational (IsRational property returns True) and it now refuses to return Weights(). This is a major letdown here since I quite need those Weights to be able to re-create this exact same Nurbs Surface again in Rhino/Grasshopper. 
Since Dynamo refuses to return Weights of rational Nurbs Surfaces, does it mean that it assumes that they are all equal to 1? This is most definitely not the case here. 

Thank you,

@pboyer @ptierney @kronz @ikeough

**Comment by aparajit-pratap** [comment]
Tracked in http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7970

**Comment by aparajit-pratap** [comment]
This should be fixed in the dailies. Please let us know. Thanks.

**Comment by ksobon** [comment]
Thank you it works great!
