### ISSUE TITLE
Crashing when operating on shared nested families

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4946]
I have a graph that grabs all instances of a family type, some of which are shared and nested within other families, then I use a List.Map node with Elements.Solids node, but Dynamo and Revit lock up and crash. I'm using the rac_advanced_sample_project.rvt file in Revit 2015 for my testing (ungrouped everything just to make sure it wasn't the source of the problem). Below is the simple graph that causes the crash, thanks.

![sharednestedcrash](https://cloud.githubusercontent.com/assets/4656191/8754586/2f5ef944-2c8a-11e5-8466-659adb6e1bd7.png)

**Comment by jnealb** [comment]
@dbaldacchino Thanks Dave - this is tracked with MAGN-7931.

**Comment by andydandy74** [comment]
@dbaldacchino - This should work fine without the ```List.Map``` node - it won't crash, at least not on my end (Revit 2015 R2 Update 7). ```Element.Solids``` will give you a nested list in any case, so there's no need for ```List.Map```.

**Comment by dbaldacchino** [comment]
Thanks @andydandy74 . Still crashing on my end with Revit 2015 R2 Update 8 after removing the List.Map node. I didn't realize that node output as a nested list so thanks for that tip. I tend to depend (almost blindly) on List.Map a lot when doing things on multiple elements. I guess I should test before!

**Comment by ikeough** [comment]
Internal issue has been closed.
