### ISSUE TITLE
Impossible to get weights from NurbsSurface

### ISSUE THREAD

**Issue by KirillLukyanenko** [DynamoDS/Dynamo#4959]
Steps to reproduce:
1. Create NurbsSurface.ByControlPointsWeightsKnots
2. Send to InPort "Weights" values
3. Connect NurbsSurface.ByControlPointsWeightsKnots with node "NurbsSurface.Weights"
4. Receive in result null in "NurbsSurface.Weights"

How can we get weights from NurbsSurface?
![nullweights](https://cloud.githubusercontent.com/assets/13420848/8781290/d2292828-2f16-11e5-8d1b-d41494bf54a8.png)

**Comment by pboyer** [comment]
@aparajit-pratap any ideas?

**Comment by ksobon** [comment]
I also reported this: https://github.com/DynamoDS/Dynamo/issues/4945 
It might be related/same issue.

**Comment by aparajit-pratap** [comment]
@pboyer I'm tracking this here: https://github.com/DynamoDS/Dynamo/issues/4959
Will have to investigate why this fails.

**Comment by ksobon** [comment]
Yes, I definitely second this issue. 
![capture](https://cloud.githubusercontent.com/assets/529781/8808789/b2d6d172-2fb2-11e5-9fcf-eef41b5ba84d.PNG)

**Comment by ksobon** [comment]
Yes, I second this. 
![capture](https://cloud.githubusercontent.com/assets/529781/8808815/d660e9b6-2fb2-11e5-905b-c0c1ccadd020.PNG)

**Comment by aparajit-pratap** [comment]
This should be fixed in the dailies. Please let us know. Thanks.

**Comment by ksobon** [comment]
Works for me!
