### ISSUE TITLE
Section View by Bounding box not returning the sections in the Dynamo UI

### ISSUE THREAD

**Issue by Justrhys** [DynamoDS/Dynamo#4966]
The watch node returns a single functioning object, the sections are created in Dynamo but I can not do anything further with them in Dynamo.

![capture](https://cloud.githubusercontent.com/assets/5448991/8816622/dbdb160e-306c-11e5-8f6d-eb5d3c847ae6.PNG)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
