### ISSUE TITLE
dynamo dailies chrash on reload

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4968]
during the last week dynamo crashes when reloading a definition quite frequently.
it is not depending on the dyn file, as it is working or not.
scenario:
test a definition
reload the revit file
reload the dyn file.
during reload dynamo crashes

**Comment by monikaprabhu** [comment]
@epeter- is this still an issue - ?

**Comment by epeter-** [comment]
i will try the latest daily and will come to you afterwards.
regards
peter
Am 03.08.2015 um 15:45 schrieb monikaprabhu:
>
> @epeter- <https://github.com/epeter-> is this still an issue - ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4968#issuecomment-127239254>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
