### ISSUE TITLE
Ellipse by Plane and radii issue

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4970]
I am not 100% sure about this, but it happened to me on multiple occasions so I decided to report it here: 

When creating an Ellipse using the Ellipse.ByPlaneRadii() method the result is this: 

![capture](https://cloud.githubusercontent.com/assets/529781/8829961/97d954b6-3067-11e5-9883-d9d8400e4a8f.PNG)

Now, I don't even know what this means, because no errors were generated, but also no Ellipse was generated. Can you guys check it out? 

Also, Ellipse.ByOriginVectors() works just fine: 

![capture](https://cloud.githubusercontent.com/assets/529781/8830001/cc2c6c62-3067-11e5-90fa-1838686b3285.PNG)

Thank you,

**Comment by ksobon** [comment]
Hh, i think i was supposed to mention @ptierney and @aparajit-pratap Thanks!

**Comment by ptierney** [comment]
Hi Konrad, can you be more specific about what code you're generating. I tested out Ellipse.ByPlaneRadii and it appears to be working: 
![screen shot 2015-07-22 at 9 56 15 am](https://cloud.githubusercontent.com/assets/289141/8831548/eb0443ae-3057-11e5-93c1-222b8f63d93e.png)

**Comment by dimven** [comment]
Are you performing .Dispose() on any of the geometry related to the creation of the ellipse?( like the plane, the plane origin, plane normal, etc)
I've experienced similar behavior.I think that in my case I was trying to dispose of the generating geometry in the same iteration as the new geometry generation and that might have led to the problem.

**Comment by ksobon** [comment]
Yes, i am disposing of it. It might be it. I havent thought about that. It
used to work fine when i wasnt disposing and now i have this issue. Thanks
for the tip.

On Wednesday, July 22, 2015, Dimitar Venkov <notifications@github.com>
wrote:

> Are you performing .Dispose() on any of the geometry related to the
> creation of the ellipse?( like the plane, the plane origin, plane normal,
> etc)
> I've experienced similar behavior.I think that in my case I was trying to
> dispose of the generating geometry in the same iteration as the new
> geometry generation and that might have led to the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DynamoDS/Dynamo/issues/4970#issuecomment-123947650>.
>


-- 
Konrad K Sobon
