### ISSUE TITLE
Code Block issue

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4972]
When you start typing something in a code block, as soon as you type ".", it automatically selects the first item in the list of commands it finds based on what you type. This shouldn't happen and it should pick the item in the list only when you click Enter. Here's an example when trying to type "pt.x" in a code block similar to what is shown possible in this post: http://dynamobim.com/cbns-for-dummies/.  As soon as you type "pt.", it automatically changes "pt" to "AdaptiveComponent". It should only pick "AdaptiveComponent" if I click the Enter key. Right now you have to play games in order to type in the variable name you want if there's a list of items available. Am I missing something or is this a known issue? Thanks.

**Comment by dbaldacchino** [comment]
On a related note, Point.ByCoordinates is not working. Testing with 0.8.2.2005.

![codeblock_point bycoordinates](https://cloud.githubusercontent.com/assets/4656191/8840444/cc537fd4-30a6-11e5-9bee-6c20938c4aba.png)

**Comment by aparajit-pratap** [comment]
This is an error due to a namespace conflict with `Point` class due to another package loaded in your Dynamo session. It could possibly be due to Rhynamo. This issue has been taken care of. If a user has a conflicting namespace in an installed package, and he types a class name in a code block, he will see all occurrences of that class. For instance if he has Rhynamo loaded, he will see `Autodesk.Point` and `Rhino.Point` when he starts typing “Point” in a code block. And if he opens an existing working file that uses a code block with “Point” in it, it should continue to work in any package environment unless that DYN file predates version 0.8.0.

Similar discussions can be found here:
https://github.com/DynamoDS/Dynamo/issues/3208
https://github.com/DynamoDS/Dynamo/issues/4821

**Comment by aparajit-pratap** [comment]
As for the issue with typing a "." in code block node, it does autocomplete on doing so. This is as designed and is the same behavior that most IDE's exhibit.

**Comment by dimven** [comment]
My temporary workaround for the initial issue is to press the space bar after "pt", followed by a backspace. I've experienced similar behavior with other abbreviations but can't think of other examples at the moment.

**Comment by dbaldacchino** [comment]
I understand it's similar to most IDE's, but in a code block, you're also typing in custom variables. The software should not be making the assumption that I want to pick something from the list. In my example of typing "pt", it is quite bizarre that the software picks "AdaptiveComponent". Having to type in spaces, then delete them etc. to get around this behavior ends up killing the nice fluidity that the code block was designed to achieve.

As for custom packages interfering with namespaces, I'll check what I have installed tomorrow. Is the fix already in a daily build? Thanks.

**Comment by aparajit-pratap** [comment]
I see your concern with autocompletion of code block variables. The reason why you see this "bizarre" behavior is because autocomplete does not support completion of variables yet. We will be be adding this feature after which this issue should be solved.

The namespace conflict work is in the product since version 0.8.0.

**Comment by dbaldacchino** [comment]
Thanks. So if the fix has been applied since 0.8.0, why am I having this problem in 0.8.2.2005? Here's what I have installed. Seems like Point is being redefined by one of the packages, rendering Point.ByCoordinates unusable.
![packages](https://cloud.githubusercontent.com/assets/4656191/8853848/62210e70-3122-11e5-9d8d-b9dd493dd808.png)

**Comment by holyjewsus** [comment]
Hi @dbaldacchino I believe point will be still be redefined, but when using autocomplete both possible namespaces will be shown so you can pick the fully qualified name of the method you want.

**Comment by dbaldacchino** [comment]
Hi @holyjewsus , that's not happening for me. If I didn't read through the previous threads posted above, I wouldn't have known how to fix it and I guarantee you my users wouldn't have a clue! Here's what I see as I start typing:

![point](https://cloud.githubusercontent.com/assets/4656191/8854617/5a061178-3126-11e5-8417-bab604db6e63.png)

**Comment by holyjewsus** [comment]
hi @dbaldacchino thanks for clarifying.

**Comment by aparajit-pratap** [comment]
@dbaldacchino I see that even though there is a namespace conflict with "Point", you are not seeing all namespaces having "Point" in autocomplete? This should definitely not be the case. Autocomplete should display all possible collisions. If that's the case, this is a bug. The only way I can think of reproducing this is by installing all the packages that you have shown above and trying it out locally. Will do so and get back to you. Anyway, do you have any idea which package the other "Point" could be coming from?

**Comment by dbaldacchino** [comment]
Hi, yes I'm not seeing the other namespaces. I really don't know which package it's coming from without uninstalling one by one. I'll post back if I find out tomorrow. Thanks.

Sent from Yahoo Mail on Android

**Comment by dbaldacchino** [comment]
The culprit is Mantis Shrimp by @ksobon.

**Comment by ksobon** [comment]
Yes, I am using RhinoCommon in MantisShrimp and it has a Point class. However, I thought this was already addressed: 
![capture](https://cloud.githubusercontent.com/assets/529781/8913667/646cfd58-3468-11e5-877d-caa4a53b951d.PNG)
It must be a regression in 0.8.2

**Comment by aparajit-pratap** [comment]
Tracked in http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7170
