### ISSUE TITLE
Feature Request: highlight similar text in code block nodes, run Find/Replace ?

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4976]
Most custom text editors support the above mentioned functionality.
We can always just copy/paste the text back and forward to perform this but it would be nice if the functionality is supported natively.
It would tremendously improve code generation and maintenance in long code blocks.
![2015-07-23_11-33-27](https://cloud.githubusercontent.com/assets/7148394/8842742/9408dcca-3130-11e5-9e19-55c83af31bf4.png)
![2015-07-23_11-34-35](https://cloud.githubusercontent.com/assets/7148394/8842744/9b3f9326-3130-11e5-9a09-5a87180e4814.png)

**Comment by dimven** [comment]
Bonus points if this is also applied to the Python Script Editor.

**Comment by andydandy74** [comment]
:+1:
