### ISSUE TITLE
SortIndexByValue

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4984]
There is a node that says it sorts in ascending or descending order, yet it doesn't have a boolean port to do this. However there is a second node that does exactly this, but the description says it sorts in ascending order only. The first node needs to be removed and the second one needs to have the description updated. Thanks.

![sortindexbyvalue1](https://cloud.githubusercontent.com/assets/4656191/8860832/f56aa46a-314b-11e5-95fb-94c10f436b4a.png)

![sortindexbyvalue2](https://cloud.githubusercontent.com/assets/4656191/8860834/f9bbf05a-314b-11e5-8a50-6123ac6f6ff0.png)

**Comment by jnealb** [comment]
@mccrone What do you think?

**Comment by mccrone** [comment]
I agree with @dbaldacchino.  Thanks for pointing this out!  MAGN-7991

**Comment by mccrone** [comment]
@dbaldacchino This was fixed with #4977

**Comment by dbaldacchino** [comment]
Thanks!
