### ISSUE TITLE
Select Face remains at previously selected face

### ISSUE THREAD

**Issue by moethu** [DynamoDS/Dynamo#4991]
Hi there, don't know if this has been reported yet, but occasionally the Select Face node doesn't load new faces - it remains at the previously selected face (see Element Id in Picture). The preview gets updated, but the internal pointer remains on the same Element Id.

![2015-07-24_11h47_34](https://cloud.githubusercontent.com/assets/8201465/8873046/a5556708-31fa-11e5-926f-29c99871da54.png)

**Comment by monikaprabhu** [comment]
@Randy-Ma - can you please take and  look at this. @moethu - can you please give us more information what situation you are seeing the issue- is this with Revit 2015 or 2016 ? Project environment or Conceptual mass etc.

**Comment by moethu** [comment]
I'm experiencing it after something went wrong in my definition. Once one of the Nodes threw an error, the select Face Node needs to be replaced if you want to change the selection. I'm using 2016 (SP1), Project Environment.

**Comment by kronz** [comment]
@moethu Afraid I'm not able to reproduce this (looking with Dynamo 0.9.1 and Revit 2016)  Can you say which version of revit you are using and what nodes are erroring?

**Comment by moethu** [comment]
@kronz, was 0.8.2, haven't experienced this in 0.9 yet.
