### ISSUE TITLE
FamilyInstance.SetRotation

### ISSUE THREAD

**Issue by Siulum** [DynamoDS/Dynamo#4992]
Hey Guys,
I hope the image upload works and you can help me. 
I created some columns out of a sliced list and used the method FamilyInstance.ByPointAndLevel. Since the columns are wrong oriented I used the method FamilyInstance.SetRotation. When I run the method the 1st column of the row (or rather the 1st item in the list) is loosing the position to its equivalent node???!!! 
In the screenshots you can see the behavior before and after I combined the SetRotation node with the rest of my code.

Kind Regards and Thanks.

![bug01_familyinst setrot_01](https://cloud.githubusercontent.com/assets/13483733/8874347/50fa6792-3210-11e5-9824-c2bb383fed8c.PNG)
![bug01_familyinst setrot_02](https://cloud.githubusercontent.com/assets/13483733/8874354/55788768-3210-11e5-8bd2-327e0d91532b.PNG)
![bug01_familyinst setrot_03](https://cloud.githubusercontent.com/assets/13483733/8874357/594e7104-3210-11e5-9704-1ba80e9c8ca2.PNG)

**Comment by Siulum** [comment]
Hey guys,

is there anyone out who could tell me if it is a Bug or the wrong use of the node??
Thanks in advance.

Michael

**Comment by RodRecker** [comment]
@riteshchandawar @Randy-Ma Can one of you take a look?
@Siulum We'll let you know what we find here.

**Comment by Randy-Ma** [comment]
I created some graphs to try to reproduce the issue. It is found that if a List.Slice node is involved, the issue is reproducible but if there is no List.Slice node, it works well. Need a bit more time to check why List.Slice will have impact here.

**Comment by Siulum** [comment]
Ok, thanks a lot guys. Hopefully there is a workaround..
I am starting to love Dynamo. Let's make it better via GitHub.

**Comment by Randy-Ma** [comment]
@Siulum 
I can not find a workaround for this one. :( It needs to be fixed. 
MAGN-8056 will track the issue.

**Comment by Randy-Ma** [comment]
@Siulum 
This has now been fixed. Thanks a lot for your feedback!

**Comment by Siulum** [comment]
@Randy-Ma 
I received an email by you that the bug has now been fixed. I just installed the latest Dynamo-Version 0.8.2. When I run my skript the behavior still seems to occur as you can see in my screenshot.

Kind Regards,
Michael

![bug01_03](https://cloud.githubusercontent.com/assets/13483733/9624769/2de75f80-5150-11e5-8eb0-6ebe312bc148.PNG)
![bug01_04](https://cloud.githubusercontent.com/assets/13483733/9624770/2dea4e66-5150-11e5-9df6-fa402b572ee4.PNG)

**Comment by Randy-Ma** [comment]
@Siulum 
Thanks for your feedback! Last time when the issue is fixed, I have added a message here but I think it is better to add the message when it is tested and so I have removed the message later.

The fix is not included in 0.8.2.
