### ISSUE TITLE
Reference issue trying to implement IGraphicItem for DynamoSAP

### ISSUE THREAD

**Issue by anagpuyol** [DynamoDS/Dynamo#4993]
Hi, I am using Dynamo 8.1 and I tried coloring some meshes using the IGraphicItem interface to visualize the analysis results of a structure using DynamoSAP. 

When setting the reference of the ProtoInterface library in Visual Studio, I get an error specifying that "The type or namespace name 'TessellationParameters' could not be found". If I load this library from a daily build of the Dynamo project, it finds the TesellationParameters and DynamoSAP can be built but then Dynamo cannot resolve the mismatch between the ProtoInterface references... 

@ikeough, @tatlin @mccrone  Do you have any suggestions on how to solve this? Thanks a lot!

**Comment by holyjewsus** [comment]
hi @anagpuyol tessellation parameters are in .82

**Comment by anagpuyol** [comment]
@holyjewsus ok, thanks

**Comment by ikeough** [comment]
@anagpuyol FYI, that API is much less likely to change now that we've added the `TessellationParameters` object as an input. The number of parameters to the method had surpassed our internal guideline for maximum number of method parameters (3), so we added the parameters object to allow for future expansion. You should not have this problem with this API again.

**Comment by anagpuyol** [comment]
great, thanks @ikeough I'm excited to test it out!
