### ISSUE TITLE
Wish: Get model paths from Revit Server

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#5005]
I would like a node that returns the list of files and paths for all models on a host Revit Server.

**Comment by dbaldacchino** [comment]
In relation to this...I recently found I can query a Revit Server using VME (HTTPCaller transformer) so I thought it would be possible to do something similar via the Web Request node. However to use the REST API, you need to supply a method (GET, etc.). Is it possible to do this using the Web Request node?

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2169).
