### ISSUE TITLE
Background Preview in Remote Session not working

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#5006]
As of 0.8.1, the background preview does not display when Dynamo is run on another machine through a Remote Desktop session. I'm also seeing that the new feature "Show Geometry in Revit 2015" is very spotty and doesn't always show. You have to cycle visibility back and forth for it to start displaying, but it can stop working and require this "dance" to get it to work again. I was working in a metric file, so we're dealing with large extents (not sure if this is related to the issue).

**Comment by ikeough** [comment]
3d preview is not supported on Remote Desktop currently. This is due to the lack of software rendering fallback support in .net 4.0. We will be updating the 3d preview component soon to .net 4.5 which should allow software fallback support. Please stay tuned.

**Comment by dbaldacchino** [comment]
Thanks Ian.

**Comment by rsingaby** [comment]
Ian, Has this issue been addressed/ resolved in the latest stable release 0.82?

**Comment by ikeough** [comment]
This has not been resolved in 0.8.2. We are targeting 0.8.3 as the fix release.

**Comment by RodRecker** [comment]
@ikeough which issue is being used to track this? MAGN-8245?

**Comment by ikeough** [comment]
@dbaldacchino @rsingaby We've recently updated Dynamo to support background preview over remote desktop. Can you please try one of the recent daily builds and let us know if this is now working for you?

**Comment by dbaldacchino** [comment]
Hi @ikeough, I tested with 0.9.0.2744 and the background preview is now working in a remote session. Thanks!

**Comment by jnealb** [comment]
@dbaldacchino @ikeough Thanks for your patience!

**Comment by ikeough** [comment]
@dbaldacchino Awesome to hear. Thanks for the confirmation.
