### ISSUE TITLE
Dynamo 0.8.1 installation problem

### ISSUE THREAD

**Issue by mgeranpayeh** [DynamoDS/Dynamo#5032]
I am having problems with the upgrade of the latest Dynamo 0.8.1.  I originally had the previous version 0.7.6, which worked fine but i asked it to check for updates and it installed the latest.  After the installation, it worked the first time (although some features such as the watch 3D did not work) but after that, the next time i open revit to work there was an error and Dynamo does not work.  I have uninstalled and re-installed it several times and the same issues re-occurs. Can you look into the errors pasted below and let me know how i may be able to fix it?

The Error I get is:

Error registering effect: HRESULT: [0x80070057], Module:[General],ApiCode: [E_INVALIDARG/invalid Arguments], Message: The parameter is incorrect. 

And

Error registering effect: The given key was not present in the dictionary.

Thank you,

**Comment by jnealb** [comment]
@mgeranpayeh Can you run DxDiag and save the output to a file and send it to me? Thanks, neal.burnham@autodesk.com

**Comment by jnealb** [comment]
@mgeranpayeh Dynamo 8.2 does not support graphics with remote desktop access to a VM.  We are working to resolve this limitation. If it is practical, you can use 8.0 in the meantime.

**Comment by mgeranpayeh** [comment]
Thank you, I installed 8.0 as you recommended and that one works fine. 

Thank you,
