### ISSUE TITLE
Output port and Parenthesis 

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5034]
Ver 0.8.2.2113
OS Win7

On adding additional/redundant parenthesis the output port in an Imperative code block disappears.

![20150802-1](https://cloud.githubusercontent.com/assets/5621624/9024566/e1477bd4-38f3-11e5-8d54-b5bca8e48017.jpg)

**Comment by monikaprabhu** [comment]
@vykrum - thanks for reporting this issue - MAGN-8046 will track this issue. as a workaround you can use method Transpose - 
c=[Imperative]
{
a={1,2,3,4};
b=(Transpose(a))[1];
return=b;
};

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
