### ISSUE TITLE
Displaying Custom Zero-Touch Node Data in a Watch Window

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/Dynamo#5045]
Is there an attribute that can be added to a zero touch node to make it's data display in a Dynamo watch node?

That is, assume I have a zero-touch node written in C# called "MyDynamoNode", which has a method "ByNumber" that takes a number and returns a MyDynamoNode that has the number stored internally. If I look at the return value of MyDynamoNode.ByNumber in a watch window it says "MyDynamoNode". I would like the watch window to display the number that is stored in my node instead of the node type. I am assuming this is possible, as it is done for Dynamo native items such as Point.

Also, if there are any other attributes that are generally useful for zero-touch node programming can you please say what they are? I have seen one that says "don't expose in Dynamo", and I assume that there are other attributes but I have not been able to find any documentation about this. Any helpful tips would be greatly appreciated.

Thanks much.

**Comment by holyjewsus** [comment]
hi @ColinDayOrg I think you just need to override ToString()

**Comment by ColinDayOrg** [comment]
Oh, ok, that's easier than I thought it would be. :) Many thanks for the quick reply.

**Comment by ikeough** [comment]
Closing this. Please reopen if the solution provided does not do what you need.
