### ISSUE TITLE
No background preview in Windows 10

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5054]
Ver: 0.8.2.2155
OS: Win 10

Upgraded to Windows 10 a little while back and now have no background preview for files that worked  well on Windows 7.

Updated the graphics driver, but that hasn't helped.

Feeling handicapped. Would I need to revert to Windows 7 or can I hope for a solution soon?

Thanks.

**Comment by vykrum** [comment]
In Dynamo Studio 2016, the back ground preview works.

Tried with 0.8.1 and 0.8.2. The background grid does not appear in a blank file.

**Comment by pboyer** [comment]
@NealBurnham

**Comment by jnealb** [comment]
@vykrum We are working to solve this, is it practical for you to use Dynamo 8.0 until we have the solution? That might be easier?

**Comment by vykrum** [comment]
@jnealb Good to know you're working on it. Thanks
Will see if I can use 0.8.0 if I really need the background preview, but don't think it will be very practical.
Actually gives me an excuse to get 'practical' in another way and take a break to look at ways to fund my Dynamo addiction :smile:

**Comment by ikeough** [comment]
A temporary solution is mentioned [here](https://github.com/helix-toolkit/helix-toolkit/issues/176). We need to make sure our installer installs DirectX 11 when running on Windows 10.

**Comment by vykrum** [comment]
@ikeough The DirectX Diagnostic version on Windows 10 says the version installed is 11.1

![20150809-1](https://cloud.githubusercontent.com/assets/5621624/9155534/72e14d9c-3ed8-11e5-96c3-cd74eb986bc0.jpg)

Besides, windows doesn't seem to allow installation of a lower version.

**Comment by jnealb** [comment]
@vykrum Can you please try again on Windows 10 with the latest daily builds? We think we may have fixed the issue.

**Comment by vykrum** [comment]
This has been resolved and hasn't been an issue for a while now
