### ISSUE TITLE
Geometry.explode

### ISSUE THREAD

**Issue by sunda022** [DynamoDS/Dynamo#5064]
Imported stairs and then tried to explode the solid.

Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)

![image](https://cloud.githubusercontent.com/assets/8949731/9126534/c932ebc2-3c73-11e5-868f-d0cf6864a53e.png)

**Comment by monikaprabhu** [comment]
Revit 2016 stair explodes stair into surfaces - which Revit version are you using ?

![stair](https://cloud.githubusercontent.com/assets/5218721/9325313/f798c47e-45c3-11e5-898a-6308b3fb1cd7.png)
