### ISSUE TITLE
Opening Pythoscript editors in parallel, one per node.

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#5068]
Hi, I often come across a situation where I am copying and comparing python code across multiple nodes.
Can you please consider enabling multiple python script editor to be open in parallel, one per node?

I currently reply on note pad on the side, which of course does not have syntax highlighting or code hints.

Thanks,
maher

**Comment by andydandy74** [comment]
Python Script nodes should be (and behave) just like CBNs....

**Comment by monikaprabhu** [comment]
@ke-yu - feature request for you take a look? Are there any plans to change this in future?

**Comment by Dewb** [comment]
#8182 enables multiple Python script windows to be open at once.
