### ISSUE TITLE
Sheet.Views not working with Structural Plans

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#5069]
Why is Sheet.Views not reporting structural plan views on sheets?

**Comment by dimven** [comment]
@ikeough 
Would this help?
https://github.com/DynamoDS/DynamoRevit/pull/550

**Comment by ksobon** [comment]
@kronz this was fixed in @dimven PR here: https://github.com/DynamoDS/DynamoRevit/pull/653 can we close this?

**Comment by kronz** [comment]
That's a convoluted thread on that pr, but yes, looks like it was merged a ways back
