### ISSUE TITLE
Online Package Search returns no results!

### ISSUE THREAD

**Issue by macusan** [DynamoDS/Dynamo#5070]
Using Dynamo 0.8.1
OS: Windows 7
Tried to search for a package. Packages > Search for a Package, but it returned a blank screen?

![2015-08-09_16-15-10](https://cloud.githubusercontent.com/assets/13722614/9157435/ef7a52ee-3eb1-11e5-8175-a7960a0db821.png)

Thanks!

**Comment by jnealb** [comment]
@macusan What was your search term?

**Comment by macusan** [comment]
LunchBox, but I can’t get anything to show up, tried searching for Rhynamo, Quads… all return nothing.

Angus MacGregor, RIBA, LEED AP BD+C
OLSON KUNDIG
T +1 206 624 5670 F +1 206 624 3730

**Comment by jnealb** [comment]
@macusan What happens if you browse to "https://www.dynamopackages.com/"?

**Comment by macusan** [comment]
In the Package search? If so, nothing.
When I put that link into a browser address it says “This webpage is not available”. However, when I google dynamo packages and click on the link it shows the page.
http://dynamopackages.com/

Angus MacGregor, RIBA, LEED AP BD+C
OLSON KUNDIG
T +1 206 624 5670 F +1 206 624 3730

**Comment by jnealb** [comment]
@macusan No, directly into the browser. You have some sort of permissions/security issue - which OS and browser are you using?

**Comment by macusan** [comment]
Windows 7 Professional
Both Chrome and IE.

Angus MacGregor, RIBA, LEED AP BD+C
OLSON KUNDIG
T +1 206 624 5670 F +1 206 624 3730

**Comment by jnealb** [comment]
@macusan If you type uac into the search under the Windows Start button, what do you get for the security level?

**Comment by macusan** [comment]
Never notify?

Angus MacGregor, RIBA, LEED AP BD+C
OLSON KUNDIG
T +1 206 624 5670 F +1 206 624 3730

**Comment by jnealb** [comment]
@macusan So your uac security level is not the issue. Do you have a corporate firewall in place? Can you get out the internet directly from your browser: to cnn.com or https://github.com/DynamoDS/Dynamo?

**Comment by jnealb** [comment]
@macusan Are you still having this issue?

**Comment by smangarole** [comment]
Cannot reproduce this issue. @jnealb Please note. Will re-open if it happens again.
Thanks.

**Comment by jnealb** [comment]
@smangarole Agreed; the last several times this was seen was because the Package Manager server had crashed.

**Comment by WEBMA5TER** [comment]
I have same problem, and too in dynamo studio 
![Screenshot_1](https://user-images.githubusercontent.com/36082366/65105412-799c7b00-d99a-11e9-8e8e-1577e6a3e7de.png)

**Comment by sami-ken** [comment]
Hi,

I have the same problem also.
![Capture](https://user-images.githubusercontent.com/55841197/65691271-7a06d700-e068-11e9-9096-2daea9d00bb8.PNG)

**Comment by Amoursol** [comment]
Hello @sami-ken,

Can you please get the latest Revit patch? This should resolve your Package problems.

**Comment by CRarchitect** [comment]
Hi, I am having issues with using the online package search. I have installed the latest Dynamo Install file (2.0.3) all of the latest Revit updates, restarted, and am still seeing "Search returned no results!"

I have checked my internet settings and have checked firewall settings. All looks good there.. 

If I use Sandbox, it works, but it doesn't work running through Revit.

I have managed to manually install Lunchbox and archi-lab, but am anticipating using more packages as I get more into Dynamo, any ideas..?

![Dynamo - Online package search not working - 2020-05-22](https://user-images.githubusercontent.com/61056766/82637199-8f86cd80-9c04-11ea-8a28-733f4d7acee7.jpg)

**Comment by Amoursol** [comment]
@zeusongit - Do you have any thoughts here?

**Comment by zeusongit** [comment]
Looking into it.

**Comment by mjkkirschner** [comment]
@CRarchitect - what version of revit is this, please show the about box.

**Comment by CRarchitect** [comment]
It is Revit 2019.
![Revit_About](https://user-images.githubusercontent.com/61056766/83127726-cb290800-a0da-11ea-8ef3-bdc0b4fd667d.jpg)


I am also experiencing difficulties using the shortcut keys.

When I try use the DEL key, or CRTL+C, CTRL+V in Dynamo it is referencing back to Revit and not Dynamo. e.g. the delete tool is selected in Revit and does not delete anything in Dynamo.

**Comment by QilongTang** [comment]
@CRarchitect That is a known issue for Revit 2019, a bug in Revit that prevents shortcut keys being triggered for all the addins, I believe it is fixed in later Revit 2019 point releases. About the no results part, I think it is related to the TLS (security) updates which is also fixed in the later Revit 2019 point release, please refer to https://blogs.autodesk.com/revit/2019/07/30/information-about-recent-tls-security-updates/. Because we had to apply this security update on our backend so the update of dates client will not be able to check packages. Similar case by another customer here: https://forum.dynamobim.com/t/online-package-download-problem/40429. Hope this helps.

**Comment by pippomu** [comment]
Don't know if people out there solved this issue. In my case i've tried to simulate the issue with success.
In the firewall of Windows10 i've made some rules to block outgoing connections with  specific applications like Revit.exe, Dynamo, or other Autodesk executables. In this way i had same issue described by people.

So, my suggestion is to **avoid, delete (or wathever you can do) any rule you find that mention Autodesk, Revit, Dynamo, etc.**
