### ISSUE TITLE
Failing to create a default icon for a package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5071]
@aosyatnik - I tried to follow your instructions here:
https://github.com/DynamoDS/Dynamo/wiki/Creating-Icons-for-Custom-Nodes
But I fail to generate an icon DLL - Visual Studio tells me the build fails because there's no entry point.
Maybe I need to use a specific template here?
You can see my solution directory here:
https://github.com/CAAD-RWTH/ClockworkForDynamo/tree/master/icons/visual_studio

**Comment by aosyatnik** [comment]
Hi, @andydandy74 , yes you've taken wrong project template. I assume, that you've taken `Console Application`. But you need `ClassLibrary` template. 
![image](https://cloud.githubusercontent.com/assets/8158404/9196067/7db98c08-4030-11e5-99cb-31a3c5f5df8b.png)

To change template, you should open ClockworkIcon properties:
![image](https://cloud.githubusercontent.com/assets/8158404/9196132/e7e284e0-4030-11e5-86a8-7c37c3cb8341.png)


And change Output type to Class Library:
![image](https://cloud.githubusercontent.com/assets/8158404/9196150/19920416-4031-11e5-8571-55ed92413027.png)

**Comment by andydandy74** [comment]
Thanks @aosyatnik - with your instructions I managed to build a DLL file now. However, it was named ```ClockworkIcon.dll```, not ```Package.customization.dll```. I then renamed the file and moved it to the ```bin``` directory of my package but it does ot have the desired effect. Now Dynamo does neither display its own default node icon nor my custom icon. Could this be related to icon size? What is the expected icon size? (I went for 256x256 pixels but perhaps you're expecting something different like 48x48?)

**Comment by andydandy74** [comment]
BTW: I updated the wiki article to include a sentence about choosing the correct template.

**Comment by aosyatnik** [comment]
Hi, @andydandy74 . Let's make it together.
First let's include your resource file in project.
Click "Show all files" button:
![image](https://cloud.githubusercontent.com/assets/8158404/9217855/4e814322-40d5-11e5-96f6-b1f1b9ff6580.png)

Include `PackageImages.resx` in project.
![image](https://cloud.githubusercontent.com/assets/8158404/9217876/93f304ea-40d5-11e5-9b4f-8210c8ba0686.png)

Next you need to uncomment Before build part.
Open `ClockworkIcon.csproj`. Remove lines 41, 42, 55. I.e. these lines:


Then remove at the end of each row symbol `. I.e.
<Target Name="BeforeBuild">` should be <Target Name="BeforeBuild">

Open Visual Studio and build your solution.

**Comment by andydandy74** [comment]
Great, that did it! How could I have missed that? :-) Thanks @aosyatnik !
One last question: What's the correct size for the icons? I seem to be running into antialiasing issues with the 256x256 pixel grid I have chosen.

**Comment by aosyatnik** [comment]
@andydandy74 , large icons for tooltip considered as 96x96. Small icons - 32x32. But you can use any size of icon, Dynamo will turn it in 32, and 96.

**Comment by andydandy74** [comment]
Thanks, I'll try again with the correct icon sizes.
