### ISSUE TITLE
Python Script Editor Location/Size + Run button.

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#5076]
Can you make the Py editor remember its location and size after closing? When writing long code, having resize every time to "Accept changes" slows down testing.

Better yet, can there be a Run button from the editor?

**Comment by ejnaren** [comment]
I would like to support this idea.
I have the exact same issues and both ideas would make a world of difference.

**Comment by Racel** [comment]
Python improvements have been recently merged in the 2.0 master build. We plan on getting daily builds out soon. Closing this issue as it has been addressed in the latest merged PR mentioned above.
