### ISSUE TITLE
Windows 10 warning when installing Dynamo

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5087]
![20150812-1](https://cloud.githubusercontent.com/assets/5621624/9215632/b1c34dbe-40ca-11e5-9124-8c9952308c39.jpg)

**Comment by jnealb** [comment]
@vykrum Interesting - we have installed Windows 10 and loaded Dynamo 8.2, but have yet to get this warning. Thanks for the heads up.

**Comment by vykrum** [comment]
@jnealb  More info on clicking More info ..
![20150813-1](https://cloud.githubusercontent.com/assets/5621624/9241840/33d50286-4196-11e5-8e6d-94961559ac05.jpg)

**Comment by brencass** [comment]
I had a this issue but with windows 8.1

**Comment by sharadkjaiswal** [comment]
I think it's related to digital signature, DynamoInstaller is probably not digitally signed.

**Comment by jnealb** [comment]
Yet I have Smartscreen set for "Get administrator approval before running..." and I do not get the message for Dynamo running as an admin user. Perhaps policies, or user group membership?

**Comment by vykrum** [comment]
I had noticed that this warning appears only when you **first** install a **new** version of dynamo. The warning doesn't appear on reinstalling the same version.
However, can't confirm if that's still the case since I've reverted to Windows 7, while I wait for you guys to sort out the background 3D issues in Windows 10.

**Comment by jnealb** [comment]
Closing for now, follow up with MAGN-8082.
