### ISSUE TITLE
Wish: Show custom node icon in tooltip, too

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5088]
I am super excited that we can now specify custom icons for our own packages, but it would be even greater if those icons were also displayed in the tooltips. CC @aosyatnik 
![unbenannt](https://cloud.githubusercontent.com/assets/3014437/9218793/ed6693a2-40d5-11e5-974f-08cc28c61bdf.png)

**Comment by aosyatnik** [comment]
@andydandy74 , you can show this icon in tooltip as well. Add icon for tooltip and call it - DefaultCustomNode.Large

**Comment by andydandy74** [comment]
Great, thanks!
