### ISSUE TITLE
Custom icons for custom categories?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5094]
Another question for @aosyatnik 
Is it also possible to create custom icons for custom node categories? If so, is there also an option for a default icon for all custom categories within a given package?

**Comment by aosyatnik** [comment]
There is no way to create custom icon for category. You can create either default icon for the whole package, or icon for each node.

**Comment by Racel** [comment]
We do not plan on addressing this in the near term future. Closing for now.
