### ISSUE TITLE
Single input custom nodes with default input value should execute

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5095]
Scenario: I have a custom node with a single input. I edit its input label and include a data type as well as a default value. I leave the input unconnected and execute the graph. The node returns `_SingleFunctionObject`.
Expected behaviour: If there's a default value set, let the node execute with that default value if no other input value is specified. It works like that for built-in nodes as well, doesn't it?
Dynamo 0.8.1

**Comment by monikaprabhu** [comment]
@andydandy74 - which nodes are you using inside custom node - can you share the image of the graph inside custom node. I could not reproduce this on 0.8.1 or 0.8.2 release candidate

**Comment by andydandy74** [comment]
Here's an example:
![singleinputwithdefaultvalue](https://cloud.githubusercontent.com/assets/3014437/9755335/84643104-56d1-11e5-8aad-b1aa8183f144.PNG)
![singlefunctionobject](https://cloud.githubusercontent.com/assets/3014437/9755345/9d7e000c-56d1-11e5-8928-fc838cadf63f.PNG)

**Comment by andydandy74** [comment]
It looks like this behaviour is limited to code block based custom nodes only. I don't see this happening in node based custom nodes.

**Comment by andydandy74** [comment]
Works as expected in 2.0
