### ISSUE TITLE
0.8.2 daily: issue with List created by Code Block in python

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#5097]
I've experimented a weird behavior of CB list: even if output preview is a list, it seems to not being properly recognized as input by custom nodes using python. Will comment later on if I got any details.

**Comment by monikaprabhu** [comment]
@jbenoit44 - eager to know what's the status here.

**Comment by ikeough** [comment]
@jbenoit44 Any update?

**Comment by smangarole** [comment]
We don't have enough information to work on this issue. Closing for now. Will re-open if necessary.
Thanks.
