### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5103]
This is probably not the appropriate place to report this, but the website (dynamobim.org) seems to be experiencing a lengthy downtime.

The error on Chrome is: Error establishing a database connection

I'm sure you'll are already aware, but reporting nevertheless.

**Comment by vykrum** [comment]
Seems to be alright now.

**Comment by RodRecker** [comment]
Thank you for letting us know. We have setup s better monitoring now.
