### ISSUE TITLE
Zero Touch Library with Icons... possible?

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#5121]
Hello all,
I'm not sure if this is a case of it not being possible, or maybe I'm just missing the documentation somewhere...  Is it possible to have icons with Zero Touch libraries?  I have already found the documentation for custom nodes, etc... but nothing that speaks directly to zero touch nodes.

I'm looking to make the LunchBox package "pretty" and most of those nodes come through a Zero Touch library now.

Any help would be appreciated.

Best,
-Nate

**Comment by ksobon** [comment]
Try this: https://github.com/DynamoDS/Dynamo/wiki/Create-An-Icon-for-A-Node

**Comment by archinate** [comment]
Yeah, I found that one.... but that looks to be for icons in the Dynamo core platform.  Nothing about adding an icon to a zero touch node or tips on distributing zero touch packages with icons.

**Comment by ksobon** [comment]
@ikeough @pboyer you guys have any ideas about this one? I am looking to get the same thing going. Thanks!

**Comment by ke-yu** [comment]
You know that ProtoGeometry is a zero-touch library? :-) 

Check out this post: https://github.com/DynamoDS/Dynamo/wiki/HowTo:Create-customization-dll

**Comment by archinate** [comment]
@ke-yu That looks like it'll do the trick.  I'll give it a shot.  

This may warrant some better documentation in the near term since that article didn't come up in any of my wiki searches.  Seems like it'd be helpful to fold that into other articles on Zero Touch nodes.

Cheers,
-Nate

**Comment by andydandy74** [comment]
Agreed - I think the wiki landing page needs an overhaul...

**Comment by archinate** [comment]
@ke-yu I dug a little deeper into the info on that page....  The documentations seems incomplete with some missing steps.  Some of the links to other documentation also seem to be broken or linked to pages that don't exist.

I still wasn't able to get icons to attach to a zero touch lib after trying it out.  I'll dig deeper this weekend and let you know if I have any luck.  Insight from @ikeough or @pboyer would also be awesome.

**Comment by RodRecker** [comment]
@archinate sorry that the docs were not complete here. Please help us update the docs as you find the missing info. @ksobon has done this for us successfully. The wiki should be open for edits with no pull request required.

**Comment by archinate** [comment]
Hey @RodRecker, always happy to help out... but the the answer to the issue I am inquiring about is still not yet answered and I am still looking for guidance outside of an incomplete wiki link. I am happy to help out by improving the documentation... if I knew what to document.

This issue in question seems to be important as it would help folks (like me, @andydandy74, and @ksobon ) to make our packages/plugins better.

**Comment by ksobon** [comment]
@archinate @RodRecker @ke-yu I made some changes to the Wiki Page that was referenced here. I agree with Nate, it was hastily created with links on it not working and a lot of steps omitted. I added bunch of missing stuff and things to look out for using Bumblebee as an example. Nate, hope this helps! https://github.com/DynamoDS/Dynamo/wiki/HowTo:Create-customization-dll

**Comment by holyjewsus** [comment]
@ksobon thanks for doing this!

**Comment by ksobon** [comment]
@holyjewsus no problem, please correct me if I have said something that is not true. I have only been using Visual Studio and C# for 2 weeks now.

**Comment by RodRecker** [comment]
Thank you guys! This is starting a good internal discussion about how best to handle the documentation going forward.

**Comment by andydandy74** [comment]
For anyone else that stumbles across thris thread: Looks like @archinate moved the article that @ksobon linked to above to a new location: https://github.com/DynamoDS/Dynamo/wiki/HowTo:-Add-Icons-to-a-Zero-Touch-Node-Library-DLL
(It's a pity the GitHub wiki doesn't remember URL changes...)

**Comment by andydandy74** [comment]
Here's a thought for the Dynamo team: Maybe all of the documentation on the wiki pertaining to custom and zero touch nodes could eventually be incorporated into the Dynamo Primer in a separate section on making and maintaining packages. That would give these topics better version control and (probably) better exposure, too. Keep the GitHub wiki documentation strictly for topics revolving around contributing to the Dynamo repo.
CC @RodRecker @tatlin @kronz @ikeough

**Comment by jnealb** [comment]
APPENDIX A

1 of ...

**Comment by ksobon** [comment]
@ikeough made an effort to re-do/make the Wiki Page clearer. The new page can be found here: https://github.com/DynamoDS/Dynamo/wiki/Add-Icons-for-a-Zero-Touch-Assembly 

@archinate can we close this issue? It looks like we have resolved it. Thanks!

**Comment by archinate** [comment]
Looks good to me!  cheers!  Thanks, all!
