### ISSUE TITLE
Python Script Editor Window Titles

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#5137]
It would be great to use the user-define name of Python Script Nodes as the titles for the Python Script Editor Windows--this is instead of the current generic title: "Edit Python Script...".

When editing and jumping between many Python Script Nodes, one sometimes forgets which script they're currently editing. A useful hint/title would be great.

Thanks

**Comment by monikaprabhu** [comment]
@melkhaldi - you can rename the node and change the node name - To make it more user friendly may the Edit Python Script can also display the node name ? will that be sufficient ? 

![python](https://cloud.githubusercontent.com/assets/5218721/9459889/4835419a-4b33-11e5-9906-5fea149d4dc1.png) .

**Comment by melkhaldi** [comment]
Hi, thank you for your feedback. I am aware of the node name change
functionality. But I think the python script editor window title should
also reflect the name of the node it represents.

**Comment by melkhaldi** [comment]
to clarify.. these two should read the same:

![image](https://cloud.githubusercontent.com/assets/5727365/9524915/58d1fe3a-4c96-11e5-82fe-f058e3f3edda.png)

**Comment by smangarole** [comment]
@ghost PR is in review for this feature request. #8182

**Comment by Dewb** [comment]
#8182 has been merged.
