### ISSUE TITLE
Icons for packages: some are missing

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#5141]
![image](https://cloud.githubusercontent.com/assets/4572196/9350476/6e7869b8-4651-11e5-95ff-782dc586a737.png)

tried with DefaultCustomNode.Small, and some packages have icon, some not.

**Comment by monikaprabhu** [comment]
@jbenoit44 - are you saying while trying to upload package with icons all are not getting uploaded?

**Comment by jbenoit44** [comment]
No, some packages have no icon displayed. But they are here.
J BENOIT
Le 26 août 2015 08:57, monikaprabhu <notifications@github.com> a écrit :@jbenoit44 - are you saying while trying to upload package with icons all are not getting uploaded?

**Comment by andydandy74** [comment]
@jbenoit44 - have you checked if those nodes are perhaps not located in the package folder but in the ```definiitions``` folder instead?

**Comment by smangarole** [comment]
@jbenoit44 Can you reproduce this is 1.3? Please re-open if it's reproducible.
