### ISSUE TITLE
Enhancement: ability to set default text size when creating groups

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#5144]
always too small font in my opinion.default is 14, I use 30 most of the time.

**Comment by monikaprabhu** [comment]
@jbenoit44 -the request is tracked at   MAGN-8231. @ramramps

**Comment by andydandy74** [comment]
I think this should be a general setting for the ```Settings``` menu: "Default Group Font Size".
I always use 30, too, btw. It's quite annoying to set the font size to my preferred value each and every time I create a group.

**Comment by sharadkjaiswal** [comment]
I think it would be good to have last used value as default.

**Comment by andydandy74** [comment]
That would work as well. As long as it is saved in DynamoSettings.XML I'm happy because that way I can deploy it to other users/computers.

**Comment by andydandy74** [comment]
Also, it would be nice if Dynamo could also remember the last colour used.

**Comment by dimven** [comment]
Further to this, could you kindly draw group text on the top-most layer of the canvas? At the moment the text is getting obstructed by the node wires:

![revit_2016-10-21_14-27-55](https://cloud.githubusercontent.com/assets/7148394/19588787/93524d80-979a-11e6-9153-6afefbe767c8.png)

**Comment by smangarole** [comment]
This issue is fixed in 1.3. Please re-open if reproducible.

**Comment by smangarole** [comment]
@Racel is this feature request in the UX Love backlog? Specifically, provide user with the ability to set their own default group font size.

**Comment by Racel** [comment]
These are being tracked in our UX Love board for the next generation UI and as of right now will not be fixed for 2.0 release. Closing.

**Comment by Racel** [comment]
Please note that the default font size of groups was increased in 1.3
