### ISSUE TITLE
0.8.2 Release Candidate is available for Testing

### ISSUE THREAD

**Issue by RodRecker** [DynamoDS/Dynamo#5162]
The release candidate for 0.8.2 is available for testing. Please take a look and report back any issues you see.
http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoReleaseCandidateInstall0.8.2.exe

**Comment by vykrum** [comment]
Spotted an instance of a wrong description of what the node does in the 0.8.2 Release Candidate

![20150824-1](https://cloud.githubusercontent.com/assets/5621624/9439339/a40a045c-4a83-11e5-825a-ce74084d2a79.jpg)

**Comment by vykrum** [comment]
Another related to adjacent edges and faces

![20150824-2](https://cloud.githubusercontent.com/assets/5621624/9441629/db6e4140-4a94-11e5-86d3-d652382ee1c8.jpg)

**Comment by Legantmar** [comment]
0.8.2 
<img src="https://leto18g.storage.yandex.net/rdisk/01ed0a2cd88d020289718ff1ce4ccbdd68c9fb8cf0097efc8e3d17083350ab0d/inf/Vlp6SRiHSb6P7vNieL-KcOGfnLSRrgvk9UOdn8ln2sQg6Se5whemURyuBIEldBxy4nlfocv4LV99a7UMv5DE9Q==?uid=0&filename=2015-08-09%2021-07-06%20%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=d251fb00cbc8f40fbea164c5e07935db&force_default=no&ycrid=na-511484a8f049b4854b05df8552e7935f-downloader1g" alt="20150824-2" style="max-width:100%;">

0.8.1
<img src="http://i.imgur.com/g1Ak2SR.png" alt="20150824-2" style="max-width:100%;">

**Comment by monikaprabhu** [comment]
@Legantmar - thanks for highlighting the issue - we are tracking it at - MAGN-8222 -Element.GetParameterValueByName

**Comment by Kelcyo** [comment]
This build has not solved the problem reported in post #5054 and #5033.

**Comment by jnealb** [comment]
@Kelcyo We are tracking with MAGN-8082 - Windows 10 testing - and MAGN-7641 - software fallback - and will provide you with updates promptly as progress is made.

**Comment by vykrum** [comment]
Input and Output ports disappeared in code block

![20150826-1](https://cloud.githubusercontent.com/assets/5621624/9484405/41904c40-4bc9-11e5-8955-08c02027110b.jpg)

Also the behavior of Curves seems to be inconsistent. The same Curves when exploded behave much better as Lines.

**Comment by vykrum** [comment]
Am I wrong to expect similar results from both Code Block 1 and Code Block 2 (below)?
From what I understand, the code in the two blocks is identical, but the structure of the results differs.

![20150826-2](https://cloud.githubusercontent.com/assets/5621624/9484582/f6583a5a-4bcb-11e5-9d71-43b096f38995.jpg)

**Comment by riteshchandawar** [comment]
@vykrum Is there any reaosn behind putting <1><2>? Because if you want to check all points from first collection intersecting with Lines or not then you can directly put "a<1>.DoesIntersect(l<2>);", you dont have to specify <1><2>.

But as far as your concern the results are still different. We need to log that defect and get it tracked.

**Comment by vykrum** [comment]
@riteshchandawar  only by using the replication guides that way I got the desired result in a more elaborate code block. Just tried to replicate that code with a simple example here.

**Comment by monikaprabhu** [comment]
@vykrum  - we have a bug -MAGN-8046 which track the output port issue previously reported by YOu - We plan to look at it soon after RC - I think submitting a last min fix for this can destabilize the build - Could you please use it as variable referencing - 

b=l.Explode();
a=Flatten(b).Area;
I can see the output port in this case.

**Comment by vykrum** [comment]
@monikaprabhu  I'm not completely sure, but in the previous instances either the input ports or the output ports used to disappear. In this case, both seem to disappear.
I am avoiding chained statements for now. Thanks.

**Comment by vykrum** [comment]
ver: 0.8.2 RC2

BoundingBox.ByGeometryCoordinateSystem doesn't seem to be working

Doesn't seem to consider the altered coordinate system and gives the same output as BoundingBox.ByGeometry

![20150829-1](https://cloud.githubusercontent.com/assets/5621624/9561716/e9a37d06-4e6e-11e5-887e-304b27f72e88.jpg)

**Comment by mjkkirschner** [comment]
@vykrum thanks - this one is tracked as well.

**Comment by ikeough** [comment]
@vykrum Please open separate issues for the ones embedded here, if they are still issues. @mjkkirschner can you attach some tracking numbers? I'm closing this container issue.
