### ISSUE TITLE
Adding other python packages

### ISSUE THREAD

**Issue by melkhaldi** [DynamoDS/Dynamo#5167]
How can I add other python-language packages (non-dynamo specific)?

**Comment by holyjewsus** [comment]
hi @melkhaldi do you mean how to you import python modules or libraries to use in the python nodes?

**Comment by holyjewsus** [comment]
if so please checkout this question:

http://stackoverflow.com/questions/1200182/how-to-use-a-c-sharp-dll-in-ironpython

**Comment by melkhaldi** [comment]
Thanks!

**Comment by mjkkirschner** [comment]
please reopen if that did not solve the issue
