### ISSUE TITLE
unloading a previously loaded DLL

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5168]
I have been trying to unload a previously imported DLL. I use the Add>ImportLibrary... method to load a dll into Dynamo but now I want to unload it.

**Comment by holyjewsus** [comment]
this is a .net issue and is not really possible as far as I know. 
@pboyer

**Comment by ksobon** [comment]
ouch, I even tried re-installing Dynamo and it still persists which makes me quite sad. :-(

**Comment by holyjewsus** [comment]
@ksobon now I'm confused, are you opening a file that uses this dll?

**Comment by ksobon** [comment]
yes, i understand that. Problem is that I am not using any of the Dlls that are persisting. I did load them in once and they keep coming back.

**Comment by holyjewsus** [comment]
@ksobon ok, on the same page now:
1) are they in your packages folder?
2) have you checked out the new setting that lets you set extra custom paths for loading packages, are there dlls in there?

**Comment by ksobon** [comment]
![image](https://cloud.githubusercontent.com/assets/529781/9414821/4fc51b60-4809-11e5-9a9c-961d41d91443.png)

Actually my bad. You are right. Those are the two Dlls that are part of my package. I have a Dll that builds a UIDropDown node and then it calls a function that lives in those two suckers. One for each package. So, yes they are being used by my packages but should not be visible in the menu like that. I don't think they should.

**Comment by ksobon** [comment]
So that's the suckers from their respective packages: 

![image](https://cloud.githubusercontent.com/assets/529781/9414888/ba9d3bc0-4809-11e5-994d-71ac26172243.png)

![image](https://cloud.githubusercontent.com/assets/529781/9414896/c9f434e8-4809-11e5-9f28-bf69b0748594.png)

**Comment by holyjewsus** [comment]
you can set use the attribute  [IsVisibleInDynamoLibrary(false)] on the methods and classes(i think).

**Comment by ksobon** [comment]
tried this: 

![image](https://cloud.githubusercontent.com/assets/529781/9415322/6dbedda6-480c-11e5-9591-9e761a67609b.png)

Still there when I reopen Dynamo. Other ideas?

**Comment by holyjewsus** [comment]
@ksobon 
1) are you sure you updated the dll in your package when you rebuilt?
2) does that method you put the tag on show up in the library? or just the category?

**Comment by ksobon** [comment]
Yes, I am sure i updated the dll after i rebuilt it. 
It looks like its not the Class or Method that shows up but rather an enum. Am i correct? 
![image](https://cloud.githubusercontent.com/assets/529781/9415577/56c94d78-480e-11e5-8e0a-2a040a5ccdea.png)
![image](https://cloud.githubusercontent.com/assets/529781/9415584/655a789e-480e-11e5-8bfd-6e4b2235a271.png)

**Comment by holyjewsus** [comment]
@ksobon it appears now part of this library is being loaded and part is hidden... 
according to @pboyer the package .json in the package folder specifies which libraries are to be loaded as node libraries, (check this out and make sure only your top level library is specified here)

BUT other libraries that define and expose some public types into the top level library are loaded as well...  so you'll need to hide the items in this other library. I'm unsure on the what items can be set with this item... I believe I have only seen methods and properties. Potentially you could apply this attribute to an entire namespace?

Hope that helps, if not I will need to investigate further

**Comment by ksobon** [comment]
yes, json has them both listed:
![image](https://cloud.githubusercontent.com/assets/529781/9416296/d06eb128-4812-11e5-9148-3896b15c4217.png)
however, if i delete my "archilab" library from here, it doesn't get loaded into Dynamo and then this happens: 
![image](https://cloud.githubusercontent.com/assets/529781/9416384/59e993be-4813-11e5-8424-95dd1b77f106.png)

This is the archilabUI dll that builds my dropdowns and calls archilab to retrieve the elements:

```C#
    #region archi-lab_Grimshaw.Selection.ParameterGroups
    [NodeName("Parameter Groups")]
    [NodeCategory("Archi-lab_Grimshaw.Selection")]
    [NodeDescription("Retrieve all available Parameter Groups.")]
    [IsDesignScriptCompatible]
    public class ParameterGroupUI : RevitDropDownBase
    {
        private const string NO_FAMILY_TYPES = "No Parameter Groups Available.";
        public ParameterGroupUI() : base("Parameter Group") { }
        public override void PopulateItems()
        {
            Items.Clear();

            var pgList = Enum.GetValues(typeof(BuiltInParameterGroup))
                    .Cast<BuiltInParameterGroup>()
                    .ToList();

            if (pgList.Count == 0)
            {
                Items.Add(new DynamoDropDownItem(NO_FAMILY_TYPES, null));
                SelectedIndex = 0;
                return;
            }

            foreach (var pg in pgList)
            {
                Items.Add(new DynamoDropDownItem(pg.ToString(), pg));
            }
            Items = Items.OrderBy(x => x.Name).ToObservableCollection();
        }

        public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
        {
            if (Items.Count == 0 ||
                Items[0].Name == NO_FAMILY_TYPES ||
                SelectedIndex == -1)
            {
                return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), AstFactory.BuildNullNode()) };
            }

            var args = new List<AssociativeNode>
            {
                AstFactory.BuildStringNode(((BuiltInParameterGroup) Items[SelectedIndex].Item).ToString())
            };

            var func = new Func<string, BuiltInParameterGroup>(GetParameterGroup.byName);
            var functionCall = AstFactory.BuildFunctionCall(func, args);

            return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), functionCall) };
        }
    }
    #endregion //archi-lab_Grimshaw.Selection.ParameterGroups
```

**Comment by ksobon** [comment]
@pboyer can you let me know if/when you have any ideas about this? It seems to me that my archilabUI.dll and how I am making a DropDown in there is causing all this fuss. Can you see anything wrong? Thanks!

**Comment by ksobon** [comment]
Thanks to folks at TT for dealing with this. I haven't tried this but I am going to guess it works like a charm. :-) 

https://github.com/tt-acm/DynamoForRebar/blob/master/src/DynamoRebarUI/GenericClasses.cs
