### ISSUE TITLE
Other Add-Ins failure when running Dynamo

### ISSUE THREAD

**Issue by SethWaldman** [DynamoDS/Dynamo#5189]
I have been using Dynamo for a little while now and yesterday was the first time I encountered my issue. For some reason while I was in the process of making my script, I would receive pop-up notices that other add-ins I have installed would stop working.

![script](https://cloud.githubusercontent.com/assets/13981070/9493523/3d644d42-4bce-11e5-9362-a68bbada1421.jpg)

![failure 1](https://cloud.githubusercontent.com/assets/13981070/9493524/3f69a70e-4bce-11e5-8931-7be1b12ba8e8.jpg)

![failure 2](https://cloud.githubusercontent.com/assets/13981070/9493527/413c9de8-4bce-11e5-9a06-4e6c5055cd40.jpg)

And if I close Dynamo afterward and try to re-open it, I get the following error:

![failure 3](https://cloud.githubusercontent.com/assets/13981070/9493585/86f56950-4bce-11e5-906c-36ded84d4b02.jpg)

Any ideas?

**Comment by jnealb** [comment]
@SethWaldman Can you tell us which version of Revit and Dynamo you are seeing this with?

**Comment by SethWaldman** [comment]
I'm in Revit 2014 and Dynamo version 0.8.3.2256

**Comment by jnealb** [comment]
@SethWaldman Thank you. In order to debug, is it possible for you to temporarily remove the other add-ins except for Dynamo and then see if loading Dynamo still gives the error? This can be done by temporarily removing/renaming the addin files under C:\ProgramData\Autodesk\Revit\AddIns\2014. If Dynamo does load, then can you try re-adding your add-ins one at a time to isolate a potential conflict? Which version of Windows are you running?

**Comment by RodRecker** [comment]
@SethWaldman Would you mind checking if this problem exists in the 0.8.2 release candidate #2 ?

http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoReleaseCandidate2Install0.8.2.exe

**Comment by SethWaldman** [comment]
I disabled the other add-ins and I don't get the pop-up anymore which makes sense. However, what is still another issue that I forgot to mention at first, if I run my script even with the other add-ins disabled, when I close my Dynamo file and try to open any Dynamo file after, nothing loads. So I close Dynamo and try to relaunch it and I get the third error message I posted. Ultimately I have to restart Revit.

I am using Windows 7 Enterprise and this has happened on more than one computer for me.

**Comment by RodRecker** [comment]
@SethWaldman one thing to be aware of - 0.8.2 is the last stable release that will include support for Revit 2014. Dynamo 0.8.3 will remove support for Revit 2014 and add support for the next version of Revit along with Revit 2015 and 2016.

**Comment by SethWaldman** [comment]
Good to know. I'm going to try running this process with Revit 2015 in the next few days when I get time. Thanks!

**Comment by jnealb** [comment]
@SethWaldman Is this still an issue?

**Comment by SethWaldman** [comment]
I'm not sure. My office has decided to use version 0.8.2 since it's a stable release and we haven't re-encountered the issue yet.

**Comment by jnealb** [comment]
@SethWaldman Thanks - we will re-open this if it re-occurs.
