### ISSUE TITLE
Document.ActiveView does not work with structural plan views

### ISSUE THREAD

**Issue by RhysProbyn** [DynamoDS/Dynamo#5196]
This is an old issue, seen in this thread: http://dynamobim.com/forums/topic/error-with-doc-activeview-and-structural-plans/ 

Document.ActiveView throws an error when used with a "structural plan" in Revit, however "floor plans" work fine.

Error log:

Warning: Document.get_ActiveView operation failed. 
Unable to cast object of type 'Revit.Elements.UnknownElement' to type 'Revit.Elements.Views.View'.

**Comment by tatlin** [comment]
There is a pull request to fix this I believe

-matt

**Comment by josols** [comment]
https://github.com/DynamoDS/DynamoRevit/pull/550 Looks like Dimitar has solved it as well?
