### ISSUE TITLE
excel icons mix up

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5197]
it looks like the excel icons in Dynamo are mixed up:

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9537765/934a22ee-4d0a-11e5-8af3-dd39983fe0dd.jpg)

**Comment by ksobon** [comment]
also this is missing: 

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9537819/70d1f61e-4d0b-11e5-87e8-a49750275162.jpg)

**Comment by ksobon** [comment]
This seems awfully redundant. We can expect users to be able to find List.Transpose and not have to create an extra node that does the same thing.

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9537922/af725412-4d0c-11e5-812b-ac63d37689c8.jpg)

**Comment by ksobon** [comment]
This particular node should cover both use cases (flat list and nested list inputs) instead of having two nodes: 

![untitled-2](https://cloud.githubusercontent.com/assets/529781/9537955/382fa80e-4d0d-11e5-98fa-6df9090ba336.jpg)

**Comment by ksobon** [comment]
This seems weird. Two different icons for an function that seems to be accepting exactly the same inputs and have the same outputs. What is the difference? 

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9538028/f3fdbc42-4d0d-11e5-8d53-7ae03d782d19.jpg)

**Comment by ksobon** [comment]
both of the newton nodes are missing large icon image and description

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9538071/5c3a66de-4d0e-11e5-93c5-14ca94b33276.jpg)

**Comment by ksobon** [comment]
people should be able to use list.reverse to toggle between ascending and descending. i don't think that needs a separate node like this: 

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9538104/bf1a5e26-4d0e-11e5-8352-4723956ce13f.jpg)

**Comment by ksobon** [comment]
This can probably be done with a single node: 

![untitled-1](https://cloud.githubusercontent.com/assets/529781/9538355/69bbf4dc-4d11-11e5-82cc-5d44011d98cc.jpg)

**Comment by ksobon** [comment]
sorry if i got a little carried away here....:-)

**Comment by xconverge** [comment]
Started looking at this and addressed the first issue on pull request #5426
