### ISSUE TITLE
Delay Node  - needed

### ISSUE THREAD

**Issue by mdengusiak** [DynamoDS/Dynamo#5202]
Dynamo 0.8.3.2256, Revit 2015 Build 20150704_0715(x64 Update Release 9)

Hi I have this issue with Dynamo script running to fast... and need Delay None
I am trying to solve this issue with unnecessary zeros values in space parameters and the only solution is to remove project parameter and add it again then all zeros are cleaned and I can import only values to spaces I am interested in, Problem is that I need to run this in two setps...If I connect as per this dotted line on image below it runs too fast and nothing happend... I guess solution would be some node that waits till revit opetation is done or manual delay node ie. 3 sek in this case first operation could be completed before second is started.
Please let me know if this is clear what I am trying to show

![2015-08-28 13_09_49-greenshot capture form](https://cloud.githubusercontent.com/assets/14005893/9545085/783a2cca-4d86-11e5-8644-2988af470028.png)

**Comment by ecdw92** [comment]
Hi @mdengusiak did you solve this?
