### ISSUE TITLE
Doesn't Zoom to Fit

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5206]
ver: 0.8.3.2392
OS: Win7

Zoom to Zit in background 3D doesn't seem to work when the geometry is far away from the origin.
Zooming out further after using *Zoom to fit* reveals the created geometry

The below example should help replicate the issue
![20150831-1](https://cloud.githubusercontent.com/assets/5621624/9575850/6d85c426-4ff0-11e5-8c49-49d225ee414b.jpg)

**Comment by monikaprabhu** [comment]
@vykrum , yup! we have some issues here with zoom it will be taken care of when we fix the MAGN-8417- THanks a lot for reporting the same.

**Comment by kronz** [comment]
![2016-02-21_2220](https://cloud.githubusercontent.com/assets/3456818/13208685/5d48c36a-d8e9-11e5-88ef-9c3c729ad779.png)
