### ISSUE TITLE
Windows 10 no input in codeblock possible

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#5207]
today i got upgraded to windows 10.
since now i cannot input anything from keyboard.
tested with codeblocks.
input failed.
in menue (screen menu left side) input is fine.
working on german locale.

just found out it sometimes works, the other time not.

**Comment by jnealb** [comment]
@epeter- Are you still seeing this with the latest dailies?

**Comment by epeter-** [comment]
yes. i saw it in the release from 9th again
regards
Am 08.09.2015 um 23:17 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Are you still seeing this with 
> the latest dailies?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/5207#issuecomment-138703752>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
