### ISSUE TITLE
Crashes wen clicking inside the 'string' node

### ISSUE THREAD

**Issue by philipbussey** [DynamoDS/Dynamo#5209]
I'm using 0.8.1.1942 - when I go to edit the string node (really just click within it) - Dynamo will crash.

![image](https://cloud.githubusercontent.com/assets/8347324/9589719/cf28c5de-4ff5-11e5-8a71-492625a85952.png)

**Comment by ke-yu** [comment]
hi @philipbussey , could you click "Details" button and copy paste all contents? That would help us to do identify the problem.

**Comment by ikeough** [comment]
@philipbussey Do you have a case that reproduces that you could provide?

**Comment by ke-yu** [comment]
@philipbussey close it as we don't have enough information to do further investigation. Please reopen the issue if you encounter the same crash again.
