### ISSUE TITLE
AdaptiveComponents.ByPoints broken in last 8.3 build?

### ISSUE THREAD

**Issue by eproca** [DynamoDS/Dynamo#5214]
![01](https://cloud.githubusercontent.com/assets/6596042/9603177/44661a04-50af-11e5-96f3-78da09b4b5bb.jpg)
Until now It worked always fine, as far I can remember. (tested in Revit 2015)

**Comment by mjkkirschner** [comment]
@eproca this is tracked - it likely has to do with the a preview bubble being open somewhere in your graph

**Comment by mjkkirschner** [comment]
@Randy-Ma

**Comment by eproca** [comment]
Working fine now. Thanks
