### ISSUE TITLE
Python script editor and (False?) Indents Error

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#5215]
I am not sure if others run into this. But I often have to reformat all of my code's indents if I added a new line of code that is not to the end of the script. I use PyCharm to reformat the code and make it is all indented correctly (as a double check), but Dynamo still does not accept this. Is this an issue with how the editor parses ASCII characters? What can I be possibly doing wrong?

**Comment by monikaprabhu** [comment]
@melkhaldi What kind of error does it throw ? could you please post a .dyn file with the indented code. I don't think any indentation must be a problem unless there is some syntax error with it. So please post the code and error snippet. @ke-yu could you please look at this ?

**Comment by melkhaldi** [comment]
i'll post code next time it comes up.

**Comment by monikaprabhu** [comment]
@melkhaldi - that will be great! looking forward to it

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.
