### ISSUE TITLE
Wish: Isolate elements in 3D preview

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5217]
It would be great to be able to right-click on a node (or several nodes) and isolate the resulting geometry in the 3D preview (and of course some way to reset the 3D preview, too).

**Comment by dimven** [comment]
+1 
The addition of global preview switches were really nice and has greatly improved the background 3d preview's functionality. But this would go one step further.

**Comment by jefferyharwood** [comment]
**+**:one:

**Comment by monikaprabhu** [comment]
I agree it will be definitely useful if we can filter the display based on selection.  Alternatively  I'm wondering if it would be more useful if we club it with the groups? So we can group the item to be displayed and show only a particular group ? Feel free to send your comments and thoughts. @lillismith

**Comment by andydandy74** [comment]
I'm not sure that's always practical. When dealing with geometry, I may actually group those nodes that actually create the geometry together. Therefore being able to isolate the geometry of a group wouldn't *always* help (but it would be an excellent piece of functionality nonetheless...).

**Comment by RodRecker** [comment]
@lillismith let's add this to the UX Love project.

**Comment by johnpierson** [comment]
Correct me if I am wrong, but I believe this was solved with the addition of `Isolate Selected Geometry`. 
![image](https://user-images.githubusercontent.com/15744724/46489747-73ca7b80-c7c3-11e8-9730-d3c10ea3f363.png)

Also, it appears @andydandy74 fixed it himself in Dynamonito. 🙂 
![image](https://user-images.githubusercontent.com/15744724/46489826-ad9b8200-c7c3-11e8-8bba-8c29152c9baa.png)


Going to close this, for now, feel free to reopen if you feel it is still an issue.

**Comment by andydandy74** [comment]
@johnpierson No need to reopen. I made the view extension because I wanted more options than Ctrl + I but completely forgot to close the issue here.
