### ISSUE TITLE
Element.SetParameterByName - Strange behavior in Version 0.8.2

### ISSUE THREAD

**Issue by Siulum** [DynamoDS/Dynamo#5219]
Hello Guys,

since I am using the latest stable Dynamo Version 0.8.2 the Element.SetParameterByName node behaves weird. In the 1st image you see the 1st index is null although the StructuralFraming.BeamByCurve node has an input! In the warning it says "The parameter is read only", which can't be as you can see in the third image I am using this node more often and it works fine
I replaced the Element.SetParameterByName on the locations where I get a warning and it worked fine for only one time. When I run the script again the same  warning message appears and the 1st index is null???
Please let me know what is going on there! Any hint helps.
Kind Regards,
Michael

![bug02_01](https://cloud.githubusercontent.com/assets/13483733/9630291/92f3e67c-5179-11e5-8cf0-e347262efeb4.PNG)
![bug02_02](https://cloud.githubusercontent.com/assets/13483733/9630293/94e4697a-5179-11e5-94b7-013e76782d2e.PNG)
![bug02_03](https://cloud.githubusercontent.com/assets/13483733/9630294/96e3fe84-5179-11e5-80de-b3883c9a0cd7.PNG)

**Comment by monikaprabhu** [comment]
@Siulum - I tried this workflow couple of times and I've been able to reproduce the readonly error only once. Let me work on this to reproduce it consistently.  I've filed a bug to myself for reproducing this consistently and is tracked at MAGN-8331.

**Comment by Siulum** [comment]
Here is another behavior I can't find a proper workaround. It seems the node Element.SetParameterByName is not working how it should. Please give me some feedback!


![wrong](https://cloud.githubusercontent.com/assets/13483733/9755538/173c3048-56d3-11e5-8ec9-185ee78c3b2f.PNG)
![whyisitwrong](https://cloud.githubusercontent.com/assets/13483733/9755541/1ca45b1e-56d3-11e5-9da8-7687d8dce118.PNG)

In the images above you can see that not all beams are having the defined offset, although the corresponding pointlist is 1D and all elements are included.
So I removed the Element.SetParameterByName node from my script and ran it again. Afterwards I combined the according nodes again and ran the script. In the images below you can see that now the position of the beams is correct! Every beam has the corresponding offset!

![right](https://cloud.githubusercontent.com/assets/13483733/9755542/211d817a-56d3-11e5-8454-39f3cff3a4b3.PNG)
![nowitiscorrect](https://cloud.githubusercontent.com/assets/13483733/9755547/240c0104-56d3-11e5-8a76-0ebf1b57f8b3.PNG)

I really don't understand this behavior anymore!

**Comment by Siulum** [comment]
Anything new regarding the issue? If you need more information let me know.

Regards,
Michael

**Comment by ikeough** [comment]
This is no longer reproduce-able in newer versions.
