### ISSUE TITLE
New events in DynamoService and graph reevaluation bug

### ISSUE THREAD

**Issue by k-u-s** [DynamoDS/Dynamo#5226]
Source branch: RC0.8.1_master
From what I experienced during cleaning work space graph can be evaluated several times when run type is automatic. This could be reproduced following this path:
1) create a work space with some nodes 
2) click  create new from Menu - File->new-> home workspace 

Also it would be usefull to have events OnWorkspaceClearing and OnWorkspaceCleared exposed in DynamoService

**Comment by monikaprabhu** [comment]
@k-u-s - we may need more information regarding the issue - What happens after clicking on new file to clear the workspace ? are you saying that when you create a new file , the Run operation is still ON ? @ikeough, @ke-yu - Could you please analyse this based on the information at hand ?

**Comment by ke-yu** [comment]
@k-u-s , this issue probably already fixed in PR #5158, please verify with 0.8.2.

**Comment by k-u-s** [comment]
Steps:
1) create a work space with some nodes 
3) set build type to automatic
3) click create new from Menu - File->new-> home workspace
4) now if have registered pre or post graph execution event it will be triggered a few times

On branch RC0.8.2_master I couldnt reproduce it.
But i still would like to have clearing events exposed in DynamoService.

**Comment by manuKrakow** [comment]
@ikeough, @ke-yu - second part could be find here https://github.com/DynamoDS/Dynamo/pull/5235
