### ISSUE TITLE
0.82 Code Block Issue 11.Autocompletes to InwOpState11.

### ISSUE THREAD

**Issue by plh139** [DynamoDS/Dynamo#5228]
Not so much a bug as an annoyance with the autocomplete in code blocks.  I'm only typing numbers into the code blocks and my current project has a module dimension of 11.25.  When typing 11. into the code block, the autocomplete adds InwOpState.  Is this a namespace issue with a package I have installed?

![11 point code block](https://cloud.githubusercontent.com/assets/9588649/9666686/8563ea58-5245-11e5-8b21-f9ca1d94d96b.JPG)
![11 point code block2](https://cloud.githubusercontent.com/assets/9588649/9666687/856618fa-5245-11e5-89b6-c33eca7004b8.JPG)

**Comment by monikaprabhu** [comment]
@plh139 - Its an annoying bug we need to fix - I've filed a bug MAGN-8329 - Autocomplete should not complete the value when typing a "." after entering a text or number unless its the next expected character in the string. A weird , not so helpful workaround I found for this is Undo two times and you will get your old string back. And you can continue typing without autocomplete interfering here. @aparajit-pratap - we should fix this when we get the chance  to look at it.

**Comment by aparajit-pratap** [comment]
Please refer to the discussion in https://github.com/DynamoDS/Dynamo/issues/4972.
This behaviour is expected. Even in visual studio if you type in a '.' it will autocomplete the string and insert the '.' after it. It is typical to how autocomplete works in IDE's generally. 
You can get rid of the autocomplete menu by hitting the `Esc` key before you press the "." to prevent it from autocompleting what you have typed upto that point.

**Comment by plh139** [comment]
@aparajit-pratap - yes, I agree that autocomplete with a period is normal behavior.  My original post was to notify you that Code blocks should not autocomplete to a namespace when typing in a number with a decimal place.  When I type the number 11.25, the code block autocompletes to some namespace called InwOpState.  This, I believe, is not normal behavior if I just want to have numbers in a code block.

**Comment by aparajit-pratap** [comment]
@plh139 if this is a namespace, you're right it should not try and autocomplete the namespace. If you could guide us as to how to reproduce this issue, we should be able to take a look at it. Thanks.

**Comment by plh139** [comment]
@aparajit-pratap - It appears to be a namespace with DynaWorks15 package.  When un-installed, the error can't be replicated.

**Comment by andydandy74** [comment]
FYI @Gytaco

**Comment by ikeough** [comment]
I'm closing this per @aparajit-pratap's suggestion that this is as expected. Please re-open if there is new information.
