### ISSUE TITLE
Direct Shape material

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5232]
ver:0.8.3.2447

Direct Shape is a neat development.
Thank you.

While using the Direct Shape node there is a default material applied.
I have a question related to this...
Is it possible to create other such materials in Dynamo, to allow not having to ensure that the material name already exists in the Revit project?

**Comment by mjkkirschner** [comment]
Currently, not really.

This default material is setup by taking a standard material and copying it and modifying the color. Theres no node to do this, but it could be done through the Revit API, but it still depends on some standard material being loaded into the project.

**Comment by vykrum** [comment]
@mjkkirschner Thanks for explaining

In any case this is a huge improvement on *ImportInstance.ByGeometry*
Would I be right in assuming that this node will eventually be further developed to create objects in Revit with editable properties/materials?

**Comment by dimven** [comment]
I think that one of the limitations of DirectShape and TesselatedShape objects was that the material could be applied only during the creation of the object. That means that the only way to change the material afterwards is to re-create the object. Is that still the case?

**Comment by mjkkirschner** [comment]
@dimven yes, as far as I am aware.

 in the case of the DirectShape nodes in Dynamo, if the material input changes, the geometry is recreated with the new material applied, but the elementId of the directShape will not change unless we cannot rebind for some reason.

**Comment by mjkkirschner** [comment]
@vykrum that depends on the evolution of the DirectShape API, depending on the category you can set some properties, for instance I believe the structural framing category enables one to set a material property for the elements etc.

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
