### ISSUE TITLE
Error, but no error

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5237]
ver:0.8.3.2464
OS: Win7

I might have reported something on these lines earlier (related to defined functions) , but it's getting to be a regular bother lately.
A definition (with no defined functions) when rerun after making a change in the associated Revit file, does not execute and shows error warnings

![20150905-1](https://cloud.githubusercontent.com/assets/5621624/9698444/3321e188-53d4-11e5-9877-5fa7085e4411.png)

The same file executes as expected on reopening.

**Comment by monikaprabhu** [comment]
@vykrum - Thanks for reporting this - Can you also check the value passed to this node when its throwing this error ? is RM passed to this function returning a non- null value when its throwing this error ? Are you saying that when you modified the code shown above in the image and rerun it did not execute ?

**Comment by vykrum** [comment]
@monikaprabhu not changes to the code, changes to the associated Revit elements (in the example above, the code is referencing Rooms in Revit)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2168).
