### ISSUE TITLE
Bug, Dynamo 0.82: Revit nodes fail if the first item in the input  list is a null or an empty list.

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#5238]
I would classify this as a major annoyance. I first noticed it happening in 0.81. So far the following nodes are affected:

Element.GetParameterValueByName
Element.SetParameterByName
Element.Name

there might be more.

There is no problem if the null value or empty list is not at head of the list:
![2015-09-06_10-34-49](https://cloud.githubusercontent.com/assets/7148394/9702145/2dbe7120-5483-11e5-866e-f0e647365ead.png)

![2015-09-06_10-35-15](https://cloud.githubusercontent.com/assets/7148394/9702148/38447734-5483-11e5-9023-66d48c834eb3.png)

However, if it is, the whole list fails to process:
![2015-09-06_10-34-59](https://cloud.githubusercontent.com/assets/7148394/9702157/c94bde66-5483-11e5-9280-ee9f1bdbf97f.png)

![2015-09-06_10-35-26](https://cloud.githubusercontent.com/assets/7148394/9702158/d513f9ae-5483-11e5-9f44-e70ea7f7dd93.png)

We can remedy this with a list.map but this is not an optimal approach:
![2015-09-06_10-40-29](https://cloud.githubusercontent.com/assets/7148394/9702176/ea5f9970-5484-11e5-86ba-50a9d3ddcd0a.png)

**Comment by monikaprabhu** [comment]
@dimven - what is the error /warning shown on these nodes ?

**Comment by dimven** [comment]
Hi @monikaprabhu , the error message is:
_Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)_

**Comment by sharadkjaiswal** [comment]
@ke-yu, can it be related to Type inferencing issue?

**Comment by monikaprabhu** [comment]
@dimven - we have an open issue related to this - which is tracked at - MAGN-6873.Im afraid its the same issue as -https://github.com/DynamoDS/Dynamo/issues/4116. I'll leave a messege to development team to see if we can increase the priority of fixing this. Thanks for reporting it.

**Comment by monikaprabhu** [comment]
@dimven - you can use List.Clean to remove the null/EmptyList from the input to Element.SetparameterName. 
![list_clean](https://cloud.githubusercontent.com/assets/5218721/9712483/7e41b6e8-557d-11e5-9cac-c30691985060.png)

**Comment by dimven** [comment]
@monikaprabhu Thanks for the info.
 I'd personally prefer to keep the null value there, so that the structure of the list is preserved.

**Comment by ikeough** [comment]
Internal issue has been closed.

**Comment by ke-yu** [comment]
https://github.com/DynamoDS/Dynamo/pull/7178

**Comment by dimven** [comment]
was #7178 merged in 1.21? This is still an issue active issue:
![revit_2017-03-17_21-16-45](https://cloud.githubusercontent.com/assets/7148394/24044684/4860db80-0b57-11e7-860b-96564089c6bd.png)

**Comment by aparajit-pratap** [comment]
Fixed in #9559
