### ISSUE TITLE
Wish: Ability to create default values for custom node inputs by calling a DS method

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5241]
In some cases it would be great to be able to set a default value for a custom node input by calling a DS method. 
Example: A custom node that creates a piece of geometry has an input to set the origin of the geometry. If I want to write ```origin : Autodesk.Point = Autodesk.Point.Origin()``` to set (0,0,0) as the default origin the input field does not accept parentheses.

**Comment by monikaprabhu** [comment]
@andydandy74 Its a very valid request - and user can do lot of interesting things when geometry can be set as default argument - I'm tracking this at - MAGN-8345.

**Comment by andydandy74** [comment]
This is being addressed in #5676

**Comment by ikeough** [comment]
@andydandy74 You can do this currently with zero touch nodes, so I imagine it's not terribly difficult to get working with custom nodes. @ke-yu would know more.

**Comment by andydandy74** [comment]
@ikeough - l was under the impression that the PR I referenced above is going to enable this for custom nodes.

**Comment by ikeough** [comment]
Lol. That's what I get for responding to issues at 5 in the morning. You are correct, it does.
