### ISSUE TITLE
Placing the same node multiple times from in-canvas search

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5247]
When searching for a node in the browser we can hit the Return key multiple times to place the same node over and over again (I tend do this a lot e.g. with Watch nodes). When using the in-canvas search this, unfortunately, is not possible. Instead when hitting Return for the second time (and each subsequent time), the last search result from the _browser_ (if any) gets placed. 

It would be great if Dynamo could remember which search field (browser / context menu) was last used and place the respective node on each subsequent use of the Return key. An alternative would be for Dynamo to remember the search term used in the in-canvas search so we can achieve the desired result with a combination of right-click and Return (deleting the search term from the in-canvas search field could be done with Esc key - just like in the browser).

Dynamo 0.8.2

**Comment by smangarole** [comment]
@Racel Is this feature request added to the UX Love backlog?

**Comment by Racel** [comment]
Yes, it is. This will not be fixed for 2.0, but will be considered for the next generation UI. Closing this in github, as it is being tracked for the new interface.
