### ISSUE TITLE
Bounding Box and Patch Surfaces

### ISSUE THREAD

**Issue by s-jamison** [DynamoDS/Dynamo#5265]
The Bounding Box node creates a box that is larger than expected when the input contains a non-planar patch surface. Could be because the UV extents are larger than the patch geometry?
![image](https://cloud.githubusercontent.com/assets/13452181/9770083/fa6d2124-56fb-11e5-8c95-7f8aacb9292f.png)

**Comment by monikaprabhu** [comment]
@s-jamison - Thanks for reporting the issue - I'm tracking this under MAGN-8413. While the bounding box for the above shape is not correct. I change a few coordinates -change CBN to  {0,30,30,0};{0,30,0,0};{20,0,0,0}; the bounding box is correct. we need to debug into code to find what is the issue- so please wait until the developer gets into fixing it. 
![boundingbox](https://cloud.githubusercontent.com/assets/5218721/9897842/c16adfb8-5c7f-11e5-816d-5fcb8fd8a204.png)
Are you planning to use it for an actual project.

**Comment by s-jamison** [comment]
Currently using the curve geometry to make the bounding box as a workaround.
