### ISSUE TITLE
Node type labels in browser get cut off

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5267]
When a subcategory contains only a small amount of nodes (e.g. just a single node), the labels  "Actions", "Create" and "Query" get cut off. I see two possible solutions here:
- Remove the labels if there is not sufficient space
- Have the label force a larger spacing between lines in such a case so that the entire label can be shown

![trimmed_labels](https://cloud.githubusercontent.com/assets/3014437/9779634/1ae61b9a-577e-11e5-83f9-8891e40aea31.PNG)
Dynamo 0.8.3.2514

**Comment by jnealb** [comment]
@Racel @andydandy74 Thanks - we agree, and are refining the design.

**Comment by Racel** [comment]
@andydandy74 - we are working on this now. 
@jnealb @ramramps - please review MAGN-8410 for design and acceptance criteria.

**Comment by Racel** [comment]
@andydandy74 - please take a look at the latest daily build. For localization purposes, we got rid of the Node Type label text and replaced it with colored icons (you can hover over them to see what they stand for). The line right next to the colored icon allows us to group nodes by type and is useful for grouping lengthy lists. Let me know if you have any specific feedback about this. Closing this now.

**Comment by andydandy74** [comment]
@Racel  - looks great! Love the color coding!
