### ISSUE TITLE
Using Save As in custom nodes replaces original custom node in graph

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5268]
**Steps to reproduce:**
1. Open a graph that contains custom nodes
2. Open one of the custom nodes
3. Use "Save As" to create a new custom node from the existing custom node

**Effects:**
1. On return to the graph the original custom node has been **replaced** by the new custom node
2. While the original custom node is still present in the project browser, placing an instance of the original node will result in a node that looks like this:
![superred](https://cloud.githubusercontent.com/assets/3014437/9779957/92238824-5782-11e5-8047-b683e78c16ff.PNG)
Error message: ```Fehler:Definition für benutzerdefinierten Block ist nicht geladen``` (Error: Definition for custom node not loaded")
3. After restarting Dynamo the original node is still missing its title:
![sanstitre](https://cloud.githubusercontent.com/assets/3014437/9779986/ea2479ac-5782-11e5-94b9-d14f2782e678.PNG)

**Workaround:**
After having saved the new custom node quit Dynamo without saving the original graph.

Dynamo Sandbox 0.8.3.2514

**Comment by ikeough** [comment]
@andydandy74 Is this still an issue in newer builds?

**Comment by andydandy74** [comment]
@ikeough - No, i think this wasn't even in 0.9 any more. Closing.
