### ISSUE TITLE
Extremely slow search performance in latest dailies

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5270]
Slow search seems to have made a comeback. :-( 
I am experiencing this in Dynamo 0.8.3.2514 on top of Revit 2015 (running on Windows 7). Search performance in Dynamo Sandbox looks good, though.

**Comment by RodRecker** [comment]
@andydandy74 are you still seeing this in the dailies?

**Comment by andydandy74** [comment]
I am now on 0.8.3.2580 (one of yesterday's builds) and it's still as slow as molasses in January. On top of Revit 2016 the performance is great BTW.

**Comment by jnealb** [comment]
@andydandy74 Is there any difference in your licensing of Revit 2015 versus Revit 2016? We have reports of network licenses being correlated with the proverbial molasses (MAGN-8049).

**Comment by andydandy74** [comment]
No difference - both are single seat EDU licenses.

**Comment by jnealb** [comment]
and you are loading the same or different rvt projects in each? btw: I feel like you know the story: https://en.wikipedia.org/wiki/Great_Molasses_Flood, yes?

**Comment by andydandy74** [comment]
Yes, I do most of my testing on the basic architectural sample project that ships with Revit.
The only difference I see between my 2015 installation and my 2016 installation is that 2015 is bursting with addins. But that couldn't possibly affect the browser search performance, could it?
And no - I didn't know about this piece of Boston history. I think I heard it first when watching Gone With The Wind, but until today I didn't know its origin.

**Comment by jnealb** [comment]
Can you please list all the addins?

**Comment by andydandy74** [comment]
- ArchiCAD Conncetion
- BIM 360
- BIM Collab (BCF)
- BIM Object *
- Boost Your BIM File Upgrader *
- COINS Section Box *
- CASE Apps (R.I.P.)
- DigiPara Elevator Architect *
- GSA Detail Filter *
- IFC Exporter
- Lumion *
- Navisworks Exporter
- Site Designer *
- Revit Extensions *
- Revit Lookup
- Roombook-Areabook-Buildingbook
- Schueco Parametric System
But I don't think this has anything to do with it. I just removed all addin manifestos from C:\ProgramData\Autodesk\Revit\Addins\2015 and C:\Users\...........\AppData\Roaming\Autodesk\Revit\Addins\2015 with no effect on search performance. FWIW, I marked the ones that were still present with an asterisk - they seem to be located elsewhere.

**Comment by RodRecker** [comment]
I'm seeing slow search with 0.8.3 and Windows 8.1 and Revit 2015. No add-ins for Revit.

**Comment by jnealb** [comment]
And I do not with Revit 2015 with 0.8.3.2585 and Windows 7 on my Dell i7 laptop. No add-ins for Revit. @RodRecker do you have any packages downloaded? Is this on your Surface? I can however repro with Revit 2016 (network license) on a VM running French Windows 7 with no addins: after I type a key at the library search it is not echoed back for many secs. Will look at Windows 8.1 next.

**Comment by RodRecker** [comment]
@jnealb yes, on my surface. This is what I'm seeing too:
> after I type a key at the library search it is not echoed back for many secs.

**Comment by jnealb** [comment]
@RodRecker What flavor of Revit are you running: Architecture, etc?

**Comment by RodRecker** [comment]
@jnealb yes - architecture.

**Comment by jnealb** [comment]
We are tracking this with MAGN-6892

**Comment by jnealb** [comment]
@andydandy74 Can you please try upgrading to .net4.6? This has resolved the issue in some cases, and there is no down-side to it.

**Comment by andydandy74** [comment]
@jnealb - sorry, but that didn't improve performance at all.

**Comment by jnealb** [comment]
@andydandy74 Thanks; we are working on it.

**Comment by RhysProbyn** [comment]
Hi just reporting that I too am getting this issue in version 0.8.2.2392 in both Revit 2015 and Revit 2016. Search results are painfully slow using the search box. I'm using fresh installs of both versions of Revit.

**Comment by RadiumC** [comment]
Hello! I have same issue here with version 0.9 although it was the same with 0.8.
When i do a fresh start  of Revit and Dynamo the search speed is allright but when i start to  build definitions it becomes very slow. Seems random that sometimes is much slower than other times and must wait like 20-30 seconds to get the search result. Same situation if i just browse the list or use the right mouse click shortcut  
I checked the Task Manager and the Revit.exe process jumps to 40-50 % of CPU during this issue.
I have Mantis Shrimp plugin and using File Path and File From Path nodes i dont know if its related to it
I am using Windows 7 64 bit

**Comment by RodRecker** [comment]
@RadiumC Sorry for this. You may be able to help us get to the bottom of this problem though. Can you give us more detail on what steps you are taking when you "build definitions"?

Also, which version of 0.9 are you using?

**Comment by RadiumC** [comment]
@RodRecker Thanks for the reply! I  was using the pre-release version on my office computer. I think it was 0.9.1.2015.11.06. Now i installed the stable build of 0.9.0 but i think the issues are similar. On my home computer however i have now the 0.8.2 version and i noticed that the left panel search is slow but the right mouse shortcut search is fast. On the office both ways had the same speed. The way i use it is i first open conceptual massing in Revit and then just start testing in Dynamo. I read somewhere that i should install the latest .NET and try if its better. Does it work faster in Windows 10?  What suggestions do you have?

**Comment by RodRecker** [comment]
@jnealb Neal, can you jump in here with some advice?

**Comment by jnealb** [comment]
@RadiumC Do you have other packages than Mantis Shrimp downloaded? Which version of Revit are you using? Before we go further, can you please check to see if the issue occurs with no downloaded packages?

**Comment by RadiumC** [comment]
@jnealb Hi, thanks for the suggestion!  I am using Revit 2016. I also had LunchBox and Rhynamo. I unninstalled them all and when i checked it seemed to be working with no issues. The i installed just Rhynamo and the search speed was still ok.  I will try to see how it performes with other plugins as well. Is it possible that there is an issue with Mantis Shrimp  that is causing the lag during the search?

**Comment by jnealb** [comment]
@RadiumC We have not been able to fully isolate/debug this sporadic "search slowdown" issue yet, so we appreciate your help and please do try to see if Mantis Shrimp is implicated.

**Comment by RodRecker** [comment]
@RadiumC yes, if you can narrow it down then we can try to work with the package developers to understand what's going on.

**Comment by ikeough** [comment]
@jnealb Did we ever get any resolution here?

**Comment by smangarole** [comment]
@jnealb - I think this is a non-issue now that we have a newer dynamo version. Any inputs from your side?

**Comment by smangarole** [comment]
@andydandy74 - I am catching up on the issue list. Search seems to be working fine for me. Are you still experiencing this issue?

**Comment by jnealb** [comment]
@smangarole Yes, there is a recent one for havard@snohetta.com who experienced it with 1.3 in April:

"Hey guys. Starting work this week, I manually deleted all previous version folders in \AppData\Roaming\Dynamo\Dynamo Revit and (1.0, 1.1 & 1.2) and Search greatly improved. The only package that stopped working (I think) was Bumblebee, and I’ve let Konrad know.

So all is good atm. Would be awesome if dev could look into this for future releases"

All other reports of this are now stale relative to the 1.3 release. Closing, since a workaround has been identified and we have never been able to reproduce it in-house. @andydandy74 Do you disagree?

**Comment by andydandy74** [comment]
Agreed. Haven't seen this come up on any fresh installs.
