### ISSUE TITLE
Dynamo forgets view settings ... again.

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5274]
It seems like Dynamo doesn't store my view settings anymore - very annoying. 
This was fixed once - now it's broken again... :-(
0.8.3.2514

**Comment by jnealb** [comment]
@andydandy74 Please help us understand your concern: in my testing I see that both node and background preview settings (pan, zoom etc) are saved to the dyn and reloaded correctly from it. Did your DynamoSettings.xml get over-written during an upgrade process?

**Comment by andydandy74** [comment]
Every time I open Dynamo I have to turn off background preview again. Saving my graph before quitting seems to be of no consequence whatsoever for storing background preview status.

**Comment by jnealb** [comment]
@andydandy74 Thank you for finding this regression from 8.2 - we will fix with MAGN-8388.

**Comment by jnealb** [comment]
@andydandy74 Can you please check this in the latest dailies? We think it is fixed.

**Comment by andydandy74** [comment]
Thanks @jnealb , works perfectly in latest daily.
