### ISSUE TITLE
Non-alphabetical order of subcategories in browser

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5276]
In some cases the subsections in the node browser are not organized alphabetically, or rather they are organized alphabetically into two separate sections (depending on whether a subcategory contains actual nodes or just more subcategories). Is this intentional? I am not sure if i missed this when testing the initial prototype or if this was introduced later on. Anyway, I think the differentiation in text colour is enough to see which subcategories actually contain nodes and I would prefer to see _all_ subcategories listed alphabetically and not divided into two groups. 
![twosubsections](https://cloud.githubusercontent.com/assets/3014437/9806284/0dfc051e-5843-11e5-8d39-7843ad0f6eed.PNG)
CC @Racel 
0.8.3.2514
BTW: I'm pretty sure those two lonely nodes in subcategory `View` would feel much better if reunited with their siblings in subcategory `Views`... ;-)

**Comment by Racel** [comment]
Hi @andydandy74 - This is not intentional, but a bug that someone brought up in the initial round of testing. We are working on trying to fix these issues.  You can see the same differentiation in the 8.2 library UI with the icons, but it is slightly more pronounced with the new tree view. Thanks again and please let us know if you see any other issues with the new UI.

**Comment by Racel** [comment]
@andydandy74 - We have a library recategorization epic that we will be working on where we will address issues like this. Hope to get this fixed soon, but the OOTB nodes in Studio will be cleaned up first.

**Comment by smangarole** [comment]
@Racel Can you please give an update on this issue?

**Comment by Racel** [comment]
OOTB and Revit nodes have been recategorized and alphabetized for 2.0. I believe this is resolved. Closing.
