### ISSUE TITLE
Node Library trouble

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5278]
Ver: 0.8.3.2526
OS: Win 7
Node is not placed on the canvas after clicking on it in the node library (listed after searching).
This has happened a few times in the last few hours. It happens during the course of working on a file  but haven't yet noticed a pattern that would enable replication of the issue. Works properly when the file is opened.
This problem doesn't seem to apply to all nodes and seems to occur only while selecting a node from a 'search' short listed list of nodes 
Other than reopening the file, the present work around is  to use the right click search on canvas.

**Comment by vykrum** [comment]
The problem seems to be related to where I click. If I click somewhere on the text, in the red zone (in the image below) it doesn't work. In the green zone (blank space besides the text), it works.
![20150911-2](https://cloud.githubusercontent.com/assets/5621624/9813114/6d7f900c-58a0-11e5-832f-4bf222e782b0.jpg)

**Comment by RodRecker** [comment]
@vykrum Thank you for taking the time to narrow this down. We will get this logged and fixed.

**Comment by mjkkirschner** [comment]
@vykrum I have just noticed this as well and tracked this. Do you have a high DPI screen like a mac retina screen?

**Comment by vykrum** [comment]
@mjkkirschner No, using an eight year old monitor (so no chance of a high DPI) with a resolution of 1366x768

**Comment by mjkkirschner** [comment]
@vykrum this PR should fix the issue, should go in soon.
https://github.com/DynamoDS/Dynamo/pull/5281

**Comment by mjkkirschner** [comment]
@vykrum please reopen if you continue to see this
