### ISSUE TITLE
Right-click to edit in node browser gone

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5279]
I am pretty sure there used to be a right-click option to open custom nodes directly from the node browser (also an option to edit node properties, I think). When did that disappear?
0.8.3.2514

**Comment by Racel** [comment]
@ramramps @andydandy74 - Could this have happened around the same time as implementing the library tree view?

**Comment by ramramps** [comment]
@Racel I think yes.

**Comment by Racel** [comment]
@andydandy74 - I see this in our latest build...Can you check if this is still an issue?

![image](https://cloud.githubusercontent.com/assets/2551261/22263034/0fa61718-e241-11e6-9b64-0877ac26fdf0.png)

**Comment by Racel** [comment]
@andydandy74 - Disregard what I said. I read it more closely...

**Comment by smangarole** [comment]
@Racel Can you please give an update?

**Comment by johnpierson** [comment]
I might be wrong, but this might not be possible to add back with the new library? Closing for now. cc. @Racel
