### ISSUE TITLE
Polysurface Intersect

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5280]
ver: 0.8.3.2526
OS: Win 7

Solid *Intersect* Plane = Surface
Surface *Intersect* Plane =Line
Polysurface *Intersect* Plane = Surface? (should be lines, right?)

![20150911-1](https://cloud.githubusercontent.com/assets/5621624/9809887/be0b79ee-5889-11e5-9fb6-25aa3b8cea03.jpg)

**Comment by monikaprabhu** [comment]
@vykrum - Thanks vykrum. the result is weird - I'll log a defect for this - MAGN-8408

**Comment by ikeough** [comment]
Internal issue has been closed.
