### ISSUE TITLE
Localization does not work for Revit 2016 Dynamo Addin

### ISSUE THREAD

**Issue by CKellner** [DynamoDS/Dynamo#5283]
I tried out the new Dynamo Version 0.8.2 for Revit 2016. I expected that this version runs with a German GUI but it was in English. Using Revit 2015 the localization works. 

So is there a way to change the language of the dynamo Addin for Revit 2016, like I can do this for Revit?

I used the Dynamo Version 0.8.2.2392 with Revit 2016 SP2 on a Windows 7 OS

**Comment by monikaprabhu** [comment]
@CKellner , I can get localization on Revit architecture 2016 sp1 - will retest with Revit 2016- vanilla and get back to you! meanwhile can you please tell me how are you launching Revit ? are you using English OS or German OS.

**Comment by jnealb** [comment]
@monikaprabhu @CKellner  Just an fyi: with Revit 2016 (build 16.0.493.0 20150807_1515(x64)) and Dynamo 0.8.2.2392 running French Windows 7 there is no issue: the Dynamo gui is French.

**Comment by CKellner** [comment]
@monikaprabhu I use a German OS

**Comment by monikaprabhu** [comment]
@jnealb Thanks Neal for verifying this - @CKellner  - We may need some info from your end to understand this problem.  Did you install from the build on the DynamoBIM.com
Any other detail that can be of help. 

 Do you have the localization related  folders 
1.  C:\Program Files\Dynamo 0.8\ de-DE ( there are similar 12 folders that correspond to the localization )  
2. C:\Program Files\Dynamo 0.8\libg_locale\ and localization related folders in 
3. C:\Program Files\Dynamo 0.8\Revit_2016\ 
all of them  look like the one below in image 

![localize](https://cloud.githubusercontent.com/assets/5218721/9895074/d2dd3628-5c5d-11e5-8d21-b6f2716fce85.png)

**Comment by CKellner** [comment]
@monikaprabhu I installed Dynamo from DynamoBIM.com and the localization related folders exist.

**Comment by CKellner** [comment]
@monikaprabhu FYI: It seems that I used an other addin that occurs this error. When I uninstall the other addin, Dynamo works fine.

**Comment by jnealb** [comment]
@CKellner What is this other addin?

**Comment by CKellner** [comment]
I wrote a test addin via c#. My own addin occurs the error. ; )

**Comment by jnealb** [comment]
but how can you possibly do that to Dynamo?...

**Comment by CKellner** [comment]
I don't know how this works exactly. I change the current culture for a test. Revit loads addins in a more or less random order. I think the Dynamo addin was loaded after my addin and that's it.

**Comment by jnealb** [comment]
Thanks

**Comment by kehehee1** [comment]
Where can I download this localization resources ? I want use the Chinese laguage.
