### ISSUE TITLE
Getparametervaluebyname

### ISSUE THREAD

**Issue by JohanCantryn** [DynamoDS/Dynamo#5285]
Hi,

I use Revit.Selection.Select Model Element to select a Revit object.
When I use Revit.Element.Parameters I can see all the parameters, including the "Category" of the element.
With GetParameterValueByName I can get the value of any parameter except for this "Category" parameter. I get the error: "Could not obtain element from the current document. The ID may not be valid".

**Comment by mjkkirschner** [comment]
I believe category uses the builtin parameter category name, try:
"ELEM_CATEGORY_PARAM"

**Comment by JohanCantryn** [comment]
Hi mjkkirschner,

Tried "ELEM_CATEGORY_PARAM" as an input for GetParameterValueByName I get an empty value as an output.

**Comment by monikaprabhu** [comment]
@JohanCantryn - I'm filing bug -MAGN-8407 - Currently I don't know the reason for this will discuss with Developer and try to get an answer. @Randy-Ma please take a look when you get time

**Comment by JohanCantryn** [comment]
OK. Thanks fot the follow up.

**Comment by andydandy74** [comment]
@JohanCantryn - In the meantime, you should probably be able to get the category by using ```Get Built In Parameter``` from package ```archi-lab.net``` with the parameter name that Mike suggested. It'll probably return the category ID (which you may be able to turn into a category object by using ```Id to Element``` from the same package).

**Comment by JohanCantryn** [comment]
@andydandy74 - I will give this a try. Thanks for your feedback

**Comment by ksobon** [comment]
@JohanCantryn if this solves your issue please close it. 

ps. I think that maybe this is a different issue. For me it would be great if the GetParameterValueByName node was able to use BuiltInParameter name to get the parameter value. I don't think it does that at the moment.

**Comment by ikeough** [comment]
Internal issue has been closed.
