### ISSUE TITLE
PolyCurve.ByThickeningCurve

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5287]
ver: 0.8.3.2535
OS: Win 7

_PolyCurve.ByThickeningCurve_ seems to only create a poly curve on the XY plane, disregarding the specified normal
![20150913-1](https://cloud.githubusercontent.com/assets/5621624/9836897/643b2470-5a49-11e5-9b16-d9f656a7095f.jpg)

**Comment by monikaprabhu** [comment]
@vykrum - Thanks for reporting this - I think it considers only the plane of the curve as the direction.  tracked at MAGN-8406
![curves](https://cloud.githubusercontent.com/assets/5218721/9866867/a0019578-5b9a-11e5-9b3f-ee4717dfada8.png)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Comment by aparajit-pratap** [comment]
This issue has been fixed and will be available in ver 2.9. Refer to [forum ](https://forum.dynamobim.com/t/help-polycurve-bythickeningcurve/5342/10)post for details.
