### ISSUE TITLE
Element.OverrideColorInView continuos crash

### ISSUE THREAD

**Issue by safawi** [DynamoDS/Dynamo#5296]
Hi I'm not able to complete this task because every time dynamo crashes (virtual machine error).
I'm using dynamo 0.8.2 on revit 2016 and trying to override 7850 curtain panels by colour using their area as a parameter. It should be an easy task. What's wrong?

![dynamo error](https://cloud.githubusercontent.com/assets/9339366/9851970/a19955a8-5af3-11e5-8a97-adff436d8c8c.jpg)
![capture](https://cloud.githubusercontent.com/assets/9339366/9851978/a46a573c-5af3-11e5-84d7-201162e6416c.png)

**Comment by aparajit-pratap** [comment]
@Randy-Ma could you take a look at this? Thanks.

**Comment by Randy-Ma** [comment]
From the call stack, it looks like that there might be some race condition and it can not be caused by the OverrideColorInView node

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2167).
