### ISSUE TITLE
Where is the implementation of IFailuresPreprocessor  ?

### ISSUE THREAD

**Issue by onizuka14** [DynamoDS/Dynamo#5301]
Its seems dynamo doesnt implement IFailuresPreprocessor and i think i cant implement it on dynamo. Is this correct? This is needed as paramaters for some commits

**Comment by monikaprabhu** [comment]
@Onizuka14 , it will be great if you could send more details - do you have you codebase somewhere or code snippet ? @ikeough - could you please take a look at this?

**Comment by onizuka14** [comment]
Its basic this:
 newStairsScope = StairsEditScope(document, "New Stairs")
"Lot of paramaters for creating the stairs"
newStairsRun = StairsRun.CreateSketchedRun(document, newStairsId, levelBottom.Elevation, bdryCurves, riserCurves, pathCurves)

newStairsScope.Commit(new StairsFailurePreprocessor()) -- Here instead of new StairsFailurePreprocessor() i should pass an IFailuresPreprocessor, StairsFailurePreprocessor is an implementation of it. In this link is an example of how to implement it http://spiderinnet.typepad.com/blog/2011/02/implement-an-ifailurespreprocessor-of-revit-api-with-c.html  But i dont think its possible for me to implement it on dynamo interface,

**Comment by onizuka14** [comment]
Or a more simple examle of what i need is this implementation:

class StairsFailurePreprocessor : IFailuresPreprocessor
{
    public FailureProcessingResult PreprocessFailures(FailuresAccessor failuresAccessor)
    {
        // Use default failure processing
        return FailureProcessingResult.Continue; 
    }
}
