### ISSUE TITLE
Export as STL as node

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5310]
Hello,
is it possible to have the "save as STL" functionality also as a node? I need the points of a triangulated surface and Delauney always returns an empty list. The STL File contains the right surfaces, but I always need to switch between Dynamo Scripts because the geometry creation and the further use of the edges can't be implemented into one script.
Thanks

**Comment by andydandy74** [comment]
:+1:

**Comment by alfarok** [comment]
@redinkinc We don't have an OOTB node for exporting to STL but the Dynamo team supports the `meshToolkit` package which includes nodes for importing and exporting various mesh files (obj, stl, etc)
