### ISSUE TITLE
Codeblock resultlist not correct when using codeblock def function

### ISSUE THREAD

**Issue by MBijsterbosch** [DynamoDS/Dynamo#5313]
Hi,

I was trying to put functions (def) in codeblocks to call them in other codeblocks, this works fine but the data preview? (tick the box in the lower right of the node) doesnt update unless you restart dynamo, disconnect/reconnect node or change a value no in the function (def test in my codeblock). 

![dynamo_codeblock_preview_bug](https://cloud.githubusercontent.com/assets/10550107/9938268/d9d721f2-5d64-11e5-98af-d844ef909272.JPG)

**Comment by sharadkjaiswal** [comment]
@junmendoza PTAL

**Comment by vykrum** [comment]
This has been the case for a long time now.
Work around: Change the name of the function. (eg. Make it *test1*) and call it again using the new name OR reopen the file.
