### ISSUE TITLE
Dont Show 3d workspace

### ISSUE THREAD

**Issue by fattahimorteza** [DynamoDS/Dynamo#5321]
i download and install dynamo 8.2 but 3d workspace dont show any thing.
also when i use watch 3d node, dont sho any geometry.

**Comment by sharadkjaiswal** [comment]
@fattahimorteza are you using this over remote desktop or on any virtual machine? Currently, Dynamo graphics doesn't support virtualization; we are working on it. 
If it's on your local system, then please share the graphics card details to troubleshoot the issue.

**Comment by fattahimorteza** [comment]
Hi
Thankyou for your answer.
My laptop is hp 8740w with quadro fx 2800 graphic card.

**Comment by sharadkjaiswal** [comment]
So you are facing this issue while running Dynamo on your laptop and not on a remote desktop? If so can you please try to upgrade the driver to the latest version and give it a try.

@jnealb do we have any known issue registered with quadro fx 2800 graphics card?

**Comment by fattahimorteza** [comment]
I use last version of driver for graphic card. 
No, don t register any issue about quadro fx 2800.

**Comment by jnealb** [comment]
@sharadkjaiswal @fattahimorteza We have not tested the FX2800 but we do have a known issue with the FX1800 so most likely we do the with the FX2800 variant/cousin card. The coming Helix update to Dynamo may address the issue.

**Comment by fattahimorteza** [comment]
i cant find any issue.

**Comment by jnealb** [comment]
MAGN-7502 and MAGN-8245

**Comment by fattahimorteza** [comment]
Thank you.

**Comment by lewshion** [comment]
I meet the same problem,and my graphics card is AMD Radeon R5 M200 Series(2GB) and intel HD Graphics 5500

**Comment by lewshion** [comment]
it's normal when i use the 0.8.0 release of dynamo in revit2015

**Comment by lewshion** [comment]
@sharadkjaiswal

**Comment by sharadkjaiswal** [comment]
@lewshion, From 0.8.1 onwards we have started using hardware acceleration for graphics, hence now its dependent on your graphics card. Sometimes updating the display driver to the latest helps. You may consider updating your driver from http://www.dell.com/support/home/us/en/19/Drivers/DriversDetails?driverId=R283418

**Comment by lewshion** [comment]
@sharadkjaiswal Thank you for answering! I will update the driver and wish it helps.

**Comment by jnealb** [comment]
@fattahimorteza @lewshion Can you please try again with the10/1 daily build from http://dynamobuilds.com? We think we may have solved the background preview rendering issue for your graphics cards.

**Comment by fattahimorteza** [comment]
hi jnealb 
thank you very much 
i download and install, it is work very well.

**Comment by jnealb** [comment]
@ikeough YAY! Nvidia FX1800 and 2800 are validated. @lewshion ?

**Comment by fattahimorteza** [comment]
Quadro fx 2800m validated.
thank you.

**Comment by lewshion** [comment]
Sorry,I can even open dynamo with the 10/1daily build. But I have solved my problem by change the graphics cards from AMD to Intel. Will there be any other problems by doing that?



刘鑫
 
From: Neal Burnham
Date: 2015-10-02 05:27
To: DynamoDS/Dynamo
CC: lewshion
Subject: Re: [Dynamo] Dont Show 3d workspace (#5321)
@fattahimorteza @lewshion Can you please try again with the10/1 daily build from http://dynamobuilds.com? We think we may have solved the background preview rendering issue for your graphics cards.

**Comment by jnealb** [comment]
@lewshion No. We suggest you use the current dailies, 10/1 has known graphics issues.
