### ISSUE TITLE
Crash open opening Dynamo 0.8.2

### ISSUE THREAD

**Issue by defosset** [DynamoDS/Dynamo#5343]

**Comment by monikaprabhu** [comment]
@defosset -Are you still seeing this ? can you add the details to this issue- please provide the os details and Standalone/Revit details.  What is the exception on the crash ?

**Comment by defosset** [comment]
I have resolved the issue.  Some graphic cards don't support Dynamo 0.8.2.  I reverted to 0.8.0 for now and everything is working fine.

Thanks,

Chris

**Comment by mjkkirschner** [comment]
you might want to try the latest daily builds as theres a bunch of work that has been done there on graphics compatibility. If you machine has both dedicated and integrated cards you may need to set dynamo to force the high performance card through your graphics control panel.
