### ISSUE TITLE
Package Manager, not publishing new version online

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#5345]
I recently published a new version of Rhynamo on Friday, September 18 [v.2015.9.18] and tried re-publishing a version today on [v. 2015.9.23].  While Dynamo appears to upload the files, these updates are not make their way to the online manager.

As it appears installed (after I chose to "Publish Online")
![image](https://cloud.githubusercontent.com/assets/1890663/10038287/6e1b1256-6189-11e5-8d5c-927a13942a7d.png)

After searching for the package... only my old version is available.
![image](https://cloud.githubusercontent.com/assets/1890663/10038286/5260e932-6189-11e5-9741-a8a5a4322273.png)

I am doing the same routine I always go through when publishing versions...are the wires getting crossed somewhere?

-Nate

**Comment by andydandy74** [comment]
Interesting - it's definitely not the package manager server. It must be something local in Dynamo 0.8.x because I just published a new version using Dynamo 0.7.5 (don't laugh - still not finished with migration tests) and it shows up on the package manger.

**Comment by archinate** [comment]
So trying again this AM... There seemed to be something preventing the upload process even though the form indicated that everything was uploading.  

It turned out I had been signed in from a different Autodesk 360 account (yay, user error!).  

However, Dynamo was not giving me any indication that my version upload was failing.  Shouldn't there be a message of some kind saying "You are not authorized to publish a version of this package.  Please sign in with a different account." ? or something?

![image](https://cloud.githubusercontent.com/assets/1890663/10046129/8fa2f36a-61cc-11e5-9dda-0913ae05cd02.png)

**Comment by ikeough** [comment]
@archinate I ran into this exact same problem last week. We're tracking it. Thanks.

**Comment by pboyer** [comment]
@ikeough Let's talk about this today.

**Comment by pboyer** [comment]
Yes, there definitely should be an error message when package publish fails. Just to clarify, the issue here is primarily that Dynamo is not emitting an error when the package publish process fails?

**Comment by jnealb** [comment]
@archinate @andydandy74 This is tracked with MAGN-8473.

**Comment by ParametricMonkey** [comment]
A while back I submitted a requested for multiple user admins to manage packages. Did this ever get implemented? This would help solve the issueif you are acciedently loggen in with a different account

**Comment by jnealb** [comment]
@ParametricMonkey @andydandy74 @archinate FYI: this is fixed with the latest daily builds (10/6), all Package Manager errors are now reported.
