### ISSUE TITLE
Empty package

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5352]
Ver: 0.8.3
OS: Win 7

I recently published a package on the package manager.
The package was installed, but the node was not available to the obviously frustrated user (http://dynamobim.com/forums/topic/is-there-a-all-elements-of-family-name-node/)

But the culprit was not Dynamo, it was me (at least partly).
Seems like I hadn't included any files in the package. I had used the *Publish this custom Node....* option. I would have expected it to have done the needful, but it didn't.
I think, the reason is that I hadn't saved the custom node before publishing.

Suggestion: Any attempt to publish an empty package should be flagged / disallowed.

**Comment by jnealb** [comment]
Thanks - this is tracked with MAGN-8473

**Comment by ikeough** [comment]
Internal issue has been closed.
