### ISSUE TITLE
Can't install to r2016 in 0.8.3 daily builds

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#5362]
@jnealb @riteshchandawar DynamoInstall0.8.3.20150924T2050
![2015-09-25_1021](https://cloud.githubusercontent.com/assets/3456818/10102994/91037938-636f-11e5-89c5-efa13a46b660.png)

**Comment by jnealb** [comment]
@kronz Thanks Zack - we are aware of a similar failure on Parallels, what OS is this?

**Comment by monikaprabhu** [comment]
@kronz ,@jnealb - I can reproduce this with win7 VM with Revit 2016 installed - I've attached the details to the bug -MAGN-8474.

**Comment by sharadkjaiswal** [comment]
I think Revit 2015 is not installed on this m/c and hence the issue. https://github.com/DynamoDS/Dynamo/pull/5379 fixes this.

**Comment by ikeough** [comment]
This has been resolved recently. Please try a daily installer.
