### ISSUE TITLE
Dynamo 0.82: Solid.Fillet/Chamfer not working on translated solids

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#5395]
There's an identical error for Solid.Chamfer:
![2015-09-30_14-56-55](https://cloud.githubusercontent.com/assets/7148394/10186493/08e7066e-6784-11e5-8537-97f93b0f0e7c.png)

The error message is hinting that the problem is due to missing edges, but the edges are in fact there and in the correct place:
![2015-09-30_15-02-41](https://cloud.githubusercontent.com/assets/7148394/10186506/1f593764-6784-11e5-8b51-9dfa7024a2dd.png)

**Comment by mjkkirschner** [comment]
@dimven what version of dynamo are you working with?

**Comment by dimven** [comment]
Dynamo 0.82 stable release on top of revit 2015

**Comment by kronz** [comment]
Thanks @dimven , easy enough to reproduce. Will get on it.
![2015-10-07_1320](https://cloud.githubusercontent.com/assets/3456818/10345256/59be4152-6cf6-11e5-94a7-f68660d280ac.png)
Here I'm trying it in Dynamo Studio (0.8.2)

**Comment by kronz** [comment]
Filled http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8767

**Comment by ikeough** [comment]
Internal issue has been closed.
