### ISSUE TITLE
Render display issues. 

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#5414]
Dynamo geometry (and XY plane representation) does not show up on the following system:

Dell, Windows 10 x64, NVIDIA NVS3100M.
Dynamo version: 2016, update 0.8.2.2431

![dynamo](https://cloud.githubusercontent.com/assets/5727365/10231059/86c48500-6835-11e5-87b6-17c2dd33e7a5.PNG)

**Comment by jnealb** [comment]
@melkhaldi Can you please try again with the latest dailies? We think this is fixed.

**Comment by melkhaldi** [comment]
Thanks, will try it on that machine and report back.

**Comment by mdoghman** [comment]
But i am using autodesk dynamo and not the one with Revit
when i download the latest daily it says revit required

**Comment by melkhaldi** [comment]
Aaahh install REVIT. You get students license for free.I'll show you
tomorrow inshaAllah

**Comment by melkhaldi** [comment]
Yes . now working in the dynamo-revit.
When is this fix going to be added to the standalone version?

**Comment by jnealb** [comment]
The fix can be found with the daily builds on Dynamobuilds.com. Please let us know if it works for you.

**Comment by melkhaldi** [comment]
The daily builds are only for the Dynamo which requires REVIT to be
installed in the first place, is that correct? They do not affect The
AutoDesk Dynamo Studio.

I am TAing a class where students are working with Dynamo Studio (2016).
They tried to get releases 0.9, but so far it seems that to get the latest
release they should have REVIT installed first. They can't get the update
to work on Dynamo Studio 2016.

am I missing something?

**Comment by jnealb** [comment]
@kronz Can you help with this?

**Comment by jnealb** [comment]
@melkhaldi @kronz Can you please run DxDiag from a command (DOS) session on your machine, save the results to file and send them to us?

**Comment by kronz** [comment]
@melkhaldi There are possibly a couple issues here.  The hardware acceleration tools in current versions of Dynamo Studio and Dynamo for Revit 0.8.2 have a few known issues for certain cards and for certain versions of Windows running in Parallels on Macs. Windows 10 in general is not well supported.  The next update release for Studio will have a lot of fixes.  For a workaround, students either need to use an older version of Studio or install Revit and Dynamo for Revit (as noted, available for free for students). Sorry for the inconvenience.

For the full list: check out this known issues page:
https://github.com/DynamoDS/Dynamo/wiki/Known-Issues
Specifically, I think you are looking at this:
The known configurations with this issue are:
Windows 8.1 or 10 with a NVidia 9600M GT graphics card and updated drivers
Windows 8.1 and a NVidia FX1800 graphics card and updated drivers
Windows 7 with a Radeon Radeon™ HD 6770M graphics card and updated drivers
Parallels and Windows 10 the background preview may not display.

**Comment by melkhaldi** [comment]
@kronz thanks! That is what I had them do. Install REVIT's educational version and install the latest release of Dynamo.  This worked fine.

@jnealb I will run the command on the student's/problem-machine when I see them next week and report back.

**Comment by ikeough** [comment]
Closing this for now. Please re-open if the suggested fixes didn't work.
