### ISSUE TITLE
Wish: Extended functionality for presets

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5428]
@mjkkirschner - Truly amazing work on presets and the CLI!
I think a great UX improvement would be the ability to preview the settinsg stored in a particular preset (without restoring it to the graph) and - even better - the ability to edit your presets without having to delete and recreate them.

**Comment by andydandy74** [comment]
It would also be nice to be able to export presets to a separate preset file for use with the DynamoCLI.
And being able to delete *all* presets from a graph with one click would also be a welcome addition.

**Comment by mjkkirschner** [comment]
@andydandy74 thanks for the kind words, there have been some designs for a states editor that would enable these functionalities.

I'll reference this issue there.

differencing the graph before and after preset application is an interesting UI/UX challenge. Deleting presets and exporting them should be small changes.

**Comment by andydandy74** [comment]
@mjkkirschner - I wasn't suggesting a preview in the graph itself, rather a separate dialogue similar to the family types dialogue in Revit - which would basically be what you dubbed the states editor.

**Comment by andydandy74** [comment]
Presets are dead and gone, unfortunately.
