### ISSUE TITLE
Cannot sign up for Customizer in Dynamo 0.9.0.2747 for Revit 2015, german

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5429]
Hello,
seems like  #3847 comes true with the Customizer. I downloaded the latest daily built and run it as revit add-in, but I can't sign up for the beta. Is this a limitation of the german version? 
BTW: will it be possible to run the english version on german machines in the future?
Thanks, Fabian

**Comment by pboyer** [comment]
@redinkinc Can you specify what exactly is presenting you from signing up?

**Comment by redinkinc** [comment]
@pboyer: There is no entry "sign up for Cusomizer beta" in the file menu. The file menu just looks like in version 0.8.2.

**Comment by jnealb** [comment]
@redinkinc @pboyer This is tracked with MAGN-8758.

**Comment by jnealb** [comment]
@redinkinc @pboyer We may have a temporary workaround for you: update the Revit desktop icon from "/language DEU" to "/language ENG" and re-launch Revit and then the Dynamo Addin: the English locale will provide the functional customizer menu items.

**Comment by redinkinc** [comment]
@jnealb: Thanks, sign up in english version works. Now I ended up in #5473.

**Comment by ikeough** [comment]
Internal issue has been closed.
