### ISSUE TITLE
api-ms-win-core-libraryloader -l1-2-0.dll is missing

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#5453]
I just updated to Revit 2016 (This is the only version of Revit that I have installed) and installed latest daily built of Dynamo (DynamoInstall0.9.0.20151005T0037). When I open DynamoSandbox it gives me the error below.

![image](https://cloud.githubusercontent.com/assets/2915573/10307833/d5244fa0-6bff-11e5-82fe-510c5cbf9d30.png)

After pressing OK for multiple times this is what I get:
![image](https://cloud.githubusercontent.com/assets/2915573/10307933/79e48b72-6c00-11e5-9e6e-35e217cd468a.png)

**Comment by mostaphaRoudsari** [comment]
PS: Dynamo works fine when I open it from inside REVIT

**Comment by Racel** [comment]
Hi @mostaphaRoudsari - Can you tell us which version of Windows you are running? And are you on Parallels?

**Comment by mostaphaRoudsari** [comment]
Hi @Racel. Windows 8 and I'm not sure what do you mean by being on Parallel but I assume the answer is no.

**Comment by mjkkirschner** [comment]
Hi @mostaphaRoudsari is windows 8 running on your local machine or on a VM is what Racel meant.

**Comment by mostaphaRoudsari** [comment]
Hi @mjkkirschner. Thanks. That's what I guessed. It's running local on my laptop.

**Comment by ikeough** [comment]
Thanks @mostaphaRoudsari. We're investigating this internally. Some of our machines are exhibiting this and some are not. We'll have a solution soon.

**Comment by ikeough** [comment]
@mostaphaRoudsari Can you tell us which version of Windows you are using (8 or 8.1). And can you send us the output from dxdiag.exe?

**Comment by mostaphaRoudsari** [comment]
@ikeough  Sure. It's Windows 8.

![image](https://cloud.githubusercontent.com/assets/2915573/10312508/8f17ea52-6c19-11e5-8fc8-e08b1c85a94f.png)

Here is the output from dxdiag: https://www.dropbox.com/s/fe0j7rimsobbuzz/DxDiag_msr.txt?dl=0

Thanks for looking into this.

**Comment by ikeough** [comment]
@mostaphaRoudsari I know this is a big ask, and you can completely shoot me down. But, can you try updating to windows 8.1 and let me know if the problem persists?

**Comment by mostaphaRoudsari** [comment]
@ikeough I was actually thinking to update to Windows 10 but since it can involve extra work to get my system ready after the update I'll do it later once I have enough time to deal with the side effects. I'll report back once I updated my system. For now I'll be using it form inside REVIT.

**Comment by ikeough** [comment]
There's another thing to try that doesn't involve updating windows.

- Install the DirectX End User Runtimes (http://www.microsoft.com/en-us/download/details.aspx?id=8109). Those should have been installed with Dynamo, but there's the possibility that they were not, or that it only installed the components required for windows 7 and windows 8.1.

**Comment by mostaphaRoudsari** [comment]
@ikeough Downloaded and installed. Didn't make a difference. One question for you. Why does it run fine when I execute it from inside Revit? Is the workflow totally different between the two?

**Comment by mostaphaRoudsari** [comment]
Also 1-1-* and 1-0-* are installed
![image](https://cloud.githubusercontent.com/assets/2915573/10315536/e9943ff8-6c28-11e5-8599-2aecebe7fd27.png)

**Comment by ikeough** [comment]
That's a good question. I believe it's picking up DirectX which is installed with Revit. it's hard to say.

**Comment by ikeough** [comment]
@mostaphaRoudsari We just solved this locally. Can you try deleting the `d3d10warp.dll` from your Dynamo install folder, and running again?

**Comment by mostaphaRoudsari** [comment]
@ikeough perfect! works for me. You saved so much time by figuring this out. Thanks.

**Comment by ikeough** [comment]
Thanks for checking.

**Comment by ikeough** [comment]
@mostaphaRoudsari @Racel This should be fixed with https://github.com/DynamoDS/Dynamo/pull/5461
