### ISSUE TITLE
Bake

### ISSUE THREAD

**Issue by vasshaug** [DynamoDS/Dynamo#5454]
Using Dynamo for modeling on large projects I totally need a way to user-select when Dynamo creates or updates Revit Elements. The Revit interaction is so slow that it completely breaks my workflow.

Also, this would solve the problem of deleting elements that I do not want to delete, just because the only way of not interacting with Revit was de-wiring Revit Interaction Nodes.

**Comment by ikeough** [comment]
We have a task in our backlog to do this, but it requires a bit of design. It's a really good idea. It feels like you should have a way, on the node, of specifying that node "Generates Elements". But do we want it per node, or globally for the open workspace?

**Comment by andydandy74** [comment]
@ikeough - Definitely per node. And let's have it for custom nodes, too, pretty please?

**Comment by ikeough** [comment]
I'm closing this issue as the requested functionality is now available in recent builds as frozen nodes.

**Comment by jnealb** [comment]
@ikeough With one caveat: we get the request to provide an equivalency to the GH "bake" command on a regular basis, and our Freeze is not quite the same.

**Comment by ikeough** [comment]
@jnealb As I understand it, this issue was about the ability to shunt parts of the graph to affect performance. 

Agreed that bake is a different issue, but bake also has a different meaning in dynamo with regards to Revit.

**Comment by vasshaug** [comment]
Bake as a way of telling Dynamo what to do to Revit and when, is completely different than Freeze. When needing to populate or manipulate a Revit document, we should push to Revit rather than constantly synchronize, which slows down everything. My workaround today is 1. populate Revit, 2. select in Revit, 3. Ctrl+X, 4. Freeze node, 5. Run graph, 6. Paste to same place. Freeze is merely a simpler way of de-wiring a Revit node - it does not improve the workflow at all, like a Bake would.
