### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wanthony13** [DynamoDS/Dynamo#5455]
Dynamo crashes when I run it.  See screenshots.
![bug1](https://cloud.githubusercontent.com/assets/14987694/10310195/59d0e60e-6c06-11e5-9bbb-6ba43c28ce31.JPG)
![bug2](https://cloud.githubusercontent.com/assets/14987694/10310198/5ddd1c4a-6c06-11e5-98d8-1e195cec2d6d.JPG)

**Comment by monikaprabhu** [comment]
@wanthony13 - Thanks for sending the report- Which version is this ? What operation caused the crash?
Inorder to try this at our end we need more details.

**Comment by ColinDayOrg** [comment]
Is this still an issue? We are not sure what version you were working with. If this is still an issue please let us know.
