### ISSUE TITLE
Cannot open new tabs dynamo 0.8.2

### ISSUE THREAD

**Issue by TYLJ** [DynamoDS/Dynamo#5459]
Hi,
I just join dynamo community and totally new to Dynamo, but i have trouble when opening new tabs when running the program. When i push ctrl+N they always close the current program then opening new tab(so totally there is only one tab that can be opened).

Best Regards,

TYLJ

**Comment by mjkkirschner** [comment]
hi @TYLJ this is currently working as expected, multiple home workspace tabs are in progress here:
https://github.com/DynamoDS/Dynamo/pull/5223
