### ISSUE TITLE
Code Block - Internal Components -  Individual preview visibility control

### ISSUE THREAD

**Issue by Curty102** [DynamoDS/Dynamo#5462]
Revit 2015, Dynamo 0.8.3.2632

When I convert a number of nodes to a code block (or simply author a code block from scratch that has many components within it (ie. Coordinate Systems, lines, points...), the code block shows ALL of its internal components in the geometry preview.  I know a workaround is to turn preview off for the code block entirely, and then attach "preview" code blocks to the outputs for which a preview is desired.  But for lengthy codeblocks, especially those where a majority of the components wish to remain visible but some do not, it would be nice to override the visibility of the components individually, possibly by right clicking (or simply single-left-clicking) the output arrow, or through some internal syntax to flag the item as "not visible".

If you'd like to see a longer description with images, forum discussion is here:
http://dynamobim.com/forums/topic/design-script-selective-onoff-visibility-for-internal-components/

Cheerio!

NC

**Comment by andydandy74** [comment]
seems related to #4285

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
