### ISSUE TITLE
Wish: Color Scheme

### ISSUE THREAD

**Issue by mdengusiak** [DynamoDS/Dynamo#5465]
Adding new ability to place color fill legend and control color 
1. scheme category: Spaces, Rooms, HVAC Zones 
2. Scheme Definition Titel - Colour by value or by range

![2015-10-07 15_07_55-autodesk revit 2015 - floor plan_ g_04 a_rc - 034291_zalm_sim2015_rs_mdengusi r](https://cloud.githubusercontent.com/assets/14005893/10338231/3e38c830-6d05-11e5-908c-5746f70c37d9.png)

![2015-10-07 15_06_47-edit color scheme](https://cloud.githubusercontent.com/assets/14005893/10338216/2430f21e-6d05-11e5-884f-6edc494ebb64.png)

**Comment by ksobon** [comment]
Michal, I think I remember saying that this functionality doesn't exist in the Revit API. You should probably post this request to Revit API blog because Dynamo team, even though they can "walk over" to Revit API guys and ask them to expose that, will not be able to expose new Revit functionality in Revit API by themselves. Of course this is a valid request, but i doubt you will achieve anything by making it here. Just don't be surprised if this just "never happens". :-) Sorry mate.

**Comment by mdengusiak** [comment]
thanks Konrad I will start now searching for right person that can deal with this on Revit API side,

**Comment by tatlin** [comment]
I have forwarded this to my colleagues in the Revit API group

-matt

**Comment by mdengusiak** [comment]
Do we know if there is any update on this? 
I think it is logged under item CF-3558 ...

**Comment by mdengusiak** [comment]
Hi Do we have any update on this?

**Comment by ke-yu** [comment]
@sharadkjaiswal @Randy-Ma

**Comment by ksobon** [comment]
@mdengusiak as far as I am aware this was not exposed in Revit 2017 API...maybe in 2018 version?

**Comment by mdengusiak** [comment]
thanks Konrad...this is very sad news... however I will keep trying...we see how many years take to get access to color scheme...I really hope this can be done faster..I already know there is not any implication on another part of software so it is matter of allowing someone  time to fix it...

**Comment by mdengusiak** [comment]
Hi, is there any chance you can support me and vote for this
https://forums.autodesk.com/t5/revit-ideas/coloring-scheme-and-ability-to-control-rgb-colors/idi-p/6638639#comment-on-this
I am trying to promote and lobby this for over 3 years...we can do all automated stuff but place coloring scheme  is manual... please help me!

**Comment by ksobon** [comment]
...and we are at 2018 version and still no support for Color Schemes. @tatlin @kronz you can't ping anyone from the dev team to get this on their radar? Cheers!

**Comment by kronz** [comment]
Thanks for the discussion, and keeping up the pressure for desired API exposure.  I'll close this for now, as we hear your wishes, but can't do anything about it for the moment.  We can re-open when it's possible

**Comment by mdengusiak** [comment]
..disaster...there is many people here from Autodesk that can make it happen in less than 4 hours. Does it mean that you are going to open this when is possible?
