### ISSUE TITLE
Perimeter curves from surfaces

### ISSUE THREAD

**Issue by al-cox** [DynamoDS/Dynamo#5472]
I have been trying to generate curves by intersecting a solid with a series of planes. This should in theory be a simple way to generate floors via curves, with the planes being floor levels. 

my approach is to create as solid from two poly curves, intersect with planes, and extract the perimeter curves from the resultant surfaces. Works fine on shapes with straight lines. However as soon as even a simple curve is added, the white screen of death comes up. I have tried many ways, poly surfaces, intersecting surfaces rather than solids to get the curves, but nothing seems to work. 

its odd, as the surface generates fine, you can get areas from it, and a linear perimeter length, all of which suggest that the perimeter is definable. 

any ideas?

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
