### ISSUE TITLE
Cannot use customizer on IE11, Firefox

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5473]
Hi,
I published a Customizer and when I try to open it get the following errors:
in IE: signing in using my autodesk ID gets me back to the start page where it wants me to sign in (so I could not open anything).
in Firefox: I can sign in and manage my customizers. But when I try to open a Customizer it says:

```
  warning: connection failed, attempting to reconnect.
```

and after some attempts:

```
  Error: Connection failed. Coudn't connect to Dynamo. Please try again later.
```

As I wanted now to publish a very simple graph (a sphere with a slider for the radius) even publishing failed.
(using Revit 2016 DEU with start option "\language ENG" and Dynamo daily built from oct 7)

**Comment by mjkkirschner** [comment]
@pboyer

**Comment by pboyer** [comment]
@redinkinc Thanks for the feedback! There are a few bugs here:

>As I wanted now to publish a very simple graph (a sphere with a slider for the radius) even publishing failed.
>(using Revit 2016 DEU with start option "\language ENG" and Dynamo daily built from oct 7)

This is fixed, but you'll need to get the latest build. This kind of defect shouldn't happen again, but it has to do with synchronization of the server and client (Dynamo).

>in Firefox: I can sign in and manage my customizers. But when I try to open a Customizer it says:
      
>      warning: connection failed, attempting to reconnect.

>and after some attempts:

>      Error: Connection failed. Coudn't connect to Dynamo. Please try again later.

We're working on this right now! Should have a fix in a few days. For now, can you use chrome?

>in IE: signing in using my autodesk ID gets me back to the start page where it wants me to sign in (so I could not open anything).

Which version of IE are you using?  

I just made a small fix and it should look something like this:

![image](https://cloud.githubusercontent.com/assets/916345/10370169/be0e3e18-6dab-11e5-8be2-9c8d752022be.png)

**Comment by redinkinc** [comment]
@pboyer: 
1. Publishing works again. Thanks!
2. Just installed chrome. Just works fine. Thanks!
3. IE is version 11. Just tried it again, problem stays the same.

**Comment by pboyer** [comment]
>in IE: signing in using my autodesk ID gets me back to the start page where it wants me to sign in (so I could not open anything).

Which page are you trying to access?

**Comment by redinkinc** [comment]
No, I tried to access the project page. When I try to access the manager the page stays totally blank.

**Comment by pboyer** [comment]
Ah, I see this is IE11 - which does support WebGL. We'll keep working on
IE11 support.

**Comment by pboyer** [comment]
With your permission, I'm going to change the name of this issue to more accurately reflect the issue.
