### ISSUE TITLE
windows 10 64 bit dynamo quits on screensaver

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#5476]
dYnamo workspace quits after relogin.

**Comment by jnealb** [comment]
@epeter- Do you mean re-launching Dynamo or logoff/login into Windows? What do you mean by "screensaver"?

**Comment by epeter-** [comment]
loging on and off
Am 08.10.2015 um 17:00 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Do you mean re-launching Dynamo 
> or logoff/login into Windows? What do you mean by "screensaver"?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/5476#issuecomment-146572051>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by jnealb** [comment]
@epeter- Thanks, is the exact symptom that your background preview is blank? What graphics card are you using?

**Comment by epeter-** [comment]
no it is not blank.
dynamo asks me to save my worspace, i confirm and dynamo quits.
before quitting i was working in a python window.
the python window stays open when dynamo quits.

Am 08.10.2015 um 17:30 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Thanks, is the exact symptom 
> that your background preview is blank? What graphics card are you using?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/5476#issuecomment-146579893>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by epeter-** [comment]
in the latest daily builds the problem persists.
when the screensaver starts, dynamo quits and has to be restarted.
kindly enough the save file dialog pops up.

**Comment by kronz** [comment]
@epeter- can you try this in 0.9.0 (or even better, 0.9.1 daily builds if you can).  We have done some major changes to graphics and this should be fixed.

**Comment by epeter-** [comment]
@kronz i am already on 01.xx and haven't experienced the problem in a while.
so i will close the issue.

**Comment by kronz** [comment]
Thanks @epeter-
