### ISSUE TITLE
Dynamo 0.8.2: Wall in plane view cant be seen in revit 2015

### ISSUE THREAD

**Issue by lewshion** [DynamoDS/Dynamo#5481]
The Wall built by dynamo can be seen in 3D view,but it cant be seen in any plane view.And I have already checked the visibility of wall in revit.
![qq 20151009171209](https://cloud.githubusercontent.com/assets/14797905/10390116/1dd284a0-6ea9-11e5-8b74-7d44e7c20461.png)
![qq 20151009171504](https://cloud.githubusercontent.com/assets/14797905/10390172/835a1eaa-6ea9-11e5-998f-1eb1aaa15c37.png)

**Comment by tatlin** [comment]
that looks like a section view in revit, not a plan view.

it also looks like a structural view type, check the properties of the view
and change it to architectural and see if the walls show up.

**Comment by lewshion** [comment]
@tatlin Thank you very much! Now the walls show up by changing them to structural walls.
