### ISSUE TITLE
Right Click Search not showing Nodes

### ISSUE THREAD

**Issue by mpdiker** [DynamoDS/Dynamo#5484]
![rightclicksearch](https://cloud.githubusercontent.com/assets/5814209/10397553/f8c4a26c-6eb0-11e5-8a11-4c60dba8e5ee.jpg)

Right Click Search not showing Nodes

DynamoInstall0.9.0.20151008T2051.exe
Windows 10 Pro
Bootcamp @ MacBook Pro mid 2014

**Comment by jnealb** [comment]
@mpdiker Yes, thank you, this is tracked with MAGN-8794.

**Comment by ikeough** [comment]
We're closing this issue because the internal issue tracking it has been closed. Please try again with a more recent build of Dynamo, and re-open this if the issue persists.
