### ISSUE TITLE
Dynamo 0.8.2: Floor cant be create when the z coordinates of the lines are not the same

### ISSUE THREAD

**Issue by lewshion** [DynamoDS/Dynamo#5486]
I want to create a floor instance in rvt2015 by dynamo with the node"Floor.ByOutlineTypeAndLevel"，and the outline is assembled by four straight lines.But when the  z coordinates of the lines are not the same,there is a error said"Input normal vector is not perpendicular with the face constructed from input curves."Can I create a floor with slope by dynamo in rvt2015.

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move how-to questions and conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
