### ISSUE TITLE
Package Manager dependencies

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5487]
Someone probably already mentioned this but i will just drop this off here to make sure that someone is looking after this: 

![image](https://cloud.githubusercontent.com/assets/529781/10413839/aa83c0e2-6f87-11e5-9ca8-82b7966f9cc0.png)

Trying to install a package BVN that is apparently dependent on an older version of archi-lab will uninstall latest archi-lab. Why? 

@pboyer  thanks...

**Comment by andydandy74** [comment]
see #3433 
Currently one of the most annoying Dynamo "features"...

**Comment by jbenoit44** [comment]
+1

**Comment by ksobon** [comment]
Now i would also like to mention that Package Manager has been behaving in all sorts of weird manners. For example. I added a few custom nodes from my home machine last night. Uploaded to PM. I download latest version at work this morning and some of the nodes are not there. 

![image](https://cloud.githubusercontent.com/assets/529781/10432613/4be6eda8-70da-11e5-9dcd-d6a39d54150b.png)

Slightly inconvenient. Does that mean i can only upload to the same package from one machine? I am sure I was logged in from the same 360 account. Upload went through successfully. No errors.

**Comment by mjkkirschner** [comment]
@ksobon are you on the latest daily builds, we just fixed a bug with unsaved files not being uploaded as well.

**Comment by ksobon** [comment]
Come again, please. If my definition was not saved, then it wouldn't upload to Package Manager? Or is it that my custom nodes weren't saved. 

In both cases I think that my file was saved when I was uploading and my nodes had to be saved on hard drive because that's currently the only way to add them to the pacakge ("add files feature"). 

Either way, I will try again. Also, I am not on latest daily because I am getting ready for ACADIA and need something stable so I am on "8.2 stable".

**Comment by LukeyJohnson** [comment]
I am also on 8.2 stable and my published new versions are not appearing on package manager in product or on website.

**Comment by ksobon** [comment]
Luke, make sure you are logged into 360 with the same user name as you used
when you first created the package.

On Friday, October 23, 2015, LukeyJohnson <notifications@github.com> wrote:

> I am also on 8.2 stable and my published new versions are not appearing on
> package manager in product or on website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DynamoDS/Dynamo/issues/5487#issuecomment-150557848>.
>


-- 
Konrad K Sobon

**Comment by LukeyJohnson** [comment]
I have current issues with uploading packages, getting the warning "Failed to submit"...

I would like to be able to 'disconnect' the whole dependency thing in the package manager at upload time. Just publish my package files and forget about the dependencies, people can be notified in the UI "You need to install package X, Y, Z..." 

It seems the dependency management, including the uninstall/reinstall process, causes more headaches than it solves - headaches that stop package upload, and / or problems on the end user side. Is it just me?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
