### ISSUE TITLE
In Canvas Search not working

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5501]
Ver: 0.9.1.2850
OS: Win 7

Search results not displayed

![20151013-1](https://cloud.githubusercontent.com/assets/5621624/10445107/0c63d120-718c-11e5-862c-3babb8da36e1.jpg)

**Comment by jnealb** [comment]
@vykrum This is tracked with MAGN-8794, thanks!

**Comment by redinkinc** [comment]
same issue on Windows 10

**Comment by ikeough** [comment]
Internal issue has been closed.
