### ISSUE TITLE
Adding Color Range to graph crashes geometry preview

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5508]
In version 0.9.1, when I add a Color Range to the graph, the geometry isn't updated anymore. when I save and restart the project, the geometry isn't drawn at all, but I can still see the Coordinate system. Seems like ColorRange crashes the geometry preview.

**Comment by ikeough** [comment]
@redinkinc Thanks. We're tracking this as [MAGN-8848](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8848).

**Comment by ikeough** [comment]
@redinkinc Can you confirm that a recent daily build resolves this issue?

**Comment by redinkinc** [comment]
Hi @ikeough: Yes, the daily build from today (26.10.2015) resolves this issue. Thanks
