### ISSUE TITLE
Wish: All Elements of Category of active design option

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#5524]
Hi,
i am working on a big project and i would like to filter/collect only objects that are in current/active model and primary design options. the objects from secondary desing options (for example, objects for  schedules) are often interfearining with main bim model objects.

i think i would be handy to have a node that collects "all elements of category of active model" (model + primary options) 

thanks,
vladimir

**Comment by ksobon** [comment]
This was added to archi-lab package a while ago. 

![image](https://cloud.githubusercontent.com/assets/529781/26564102/a0b23eb4-44aa-11e7-8b37-3806d2acd2de.png)

cc: @kronz can we put this on some sort of internal tracking list to make sure that we add this to the DynamoRevit core at some point?

**Comment by kronz** [comment]
Sure, it's a good wish list item.  It's do-able with the out of the box functionality in the meantime (if a little cumbersome)
![2017-05-30_1516](https://cloud.githubusercontent.com/assets/3456818/26600705/085e053e-454b-11e7-8c47-368f9d9f1f57.png)

**Comment by ksobon** [comment]
@kronz can you post tracking number for this wishlist item? I believe you guys use Jetbrains to track issues and feature requests.

**Comment by kronz** [comment]
@ksobon We're trying now to not duplicate issues in our internal process until we know (short term) that we are going to work on it.  This is a reasonable addition (makes sense in the larger landscape of functionality and is consistent with it), but not a priority to get on right away (other ways to accomplish the work, resources currently on other priorities)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2166).
