### ISSUE TITLE
Pyhton node depreciated

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#5541]
Hi,
with new dynamo, my python nodes are depreciated and it is relatively complicated to replace them:
i have at least one python in each script, and i think many other have too, it would be nice if node can be updated automaticaly or to have  a paralel instalation as it was with dynamo 0.7 and 0.8.
or at least to be able to extract python code from the node

thanks.

Ps:I really like path management in 0.9 for packages, but i need to make sure older definitions works before implementing 0.9 it in the office

![pyhton](https://cloud.githubusercontent.com/assets/4834544/10542771/d6bb4ea4-741a-11e5-988e-42a73cb614f7.PNG)

**Comment by ikeough** [comment]
@ondejcik Looks like the migration for python nodes doesn't work for 0.9.0 for some reason. We'll look into it.

**Comment by ikeough** [comment]
Tracked internally with [MAGN-8885](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8885?query=8774)

**Comment by kronz** [comment]
@ondejcik , is this a node that was last used in 0.6?  or have you been using it in 0.7?

**Comment by ondejcik** [comment]
@kronz , no, node was created in: DynamoInstall0.8.3.20150814T1649

**Comment by kronz** [comment]
@ondejcik hmm, very strange.  I think there is something unique about your file, as I can open all the files I'm looking at that were created in 0.8 era in 0.9.  If it was created in 0.8.3, this means it was made from a pre-release build, so there's probably some amount of inherent instability that comes from working directly from the development stream. Can you open other python nodes?

**Comment by ondejcik** [comment]
@kronz , it looks it is only those that was made in 0.8.3 are not working, i chcecked some older script that that was mostlikely were done before 0.8.3 and there it works ok.

**Comment by kronz** [comment]
@ondejcik The good news is that, in almost all cases, you will find that you can open dyn and dyf files made in newer versions back in older versions.  There are exceptions of course, nodes that didn't exist in older versions will be inoperable, and the pre-release versions are, buy definition, not 100% tested or validated.  So, in your case, yes, you might try opening your 0.8.3 nodes in 0.8.2 and resaving.  So, for mission critical/office needed work, we do recommend that you stay with the latest stable or previously stable builds.  These are the ones that have gone through a more rigorous testing and stabilization period.  

Of course, we are thrilled that people are using and giving feedback on pre-release builds. Your and other's contribution to the community is what allows us to rapidly update and improve the software.  But pre-release is a construction zone, and it is good to keep backup work when you are using these builds.

Thanks
Zach

**Comment by mjkkirschner** [comment]
I wonder if there is a migration from .8 -> .9, but not from .83 -> .9

**Comment by RodRecker** [comment]
0.8.3 was never released and renamed to 0.9.0. Not sure if we implemented migrations for that.

**Comment by ondejcik** [comment]
@kronz , I know that it is possible to open for example 0,8,3 in stable 0,8,2, but even if i resave it from there, it ll still remebers version that it was originaly created  and next time i open it i get a warning again. I would like to get rid of that, especially if i want to pass it to someone else.

**Comment by kronz** [comment]
We are going to go ahead and implement a migration from 0.8.3.
However, the idea that saving in 0.8.2 isn't getting written to the file doesn't sound right either.  Are you saving a .dyn file that has a .dyf in it, or the .dyf itself?

**Comment by ondejcik** [comment]
Yes, dyn file contains also custom nodes, ill try to open and resave those separately and see it it ll help

**Comment by ikeough** [comment]
https://github.com/DynamoDS/Dynamo/pull/5585

**Comment by ondejcik** [comment]
Hi, so i manage to covert my 0.8.3 to 0.8.3. all custom nodes has to be opened and resaved. Dynamo crashed a lot trhought the process, but i can live with that for now., i ll try to see if i have alway the same error.

**Comment by ikeough** [comment]
@ondejcik If you have an example of a workflow that crashed Dynamo please send it to us. Also, just to be clear, did you mean to say "my 0.8.3 to 0.9.0"?
