### ISSUE TITLE
No Browse Button on File Path Object

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/Dynamo#5542]
If I place a File Path node from the input section into a Dynamo graph (0.8.2) I do not see a "Browse" button. I am assuming that I am just getting the wrong node, but I am getting the same node from the Input|FilePath section as from the standard File Path section.

If anyone could point me towards the proper node to use for browsing the file system for a file path it would be greatly appreciated.

Thanks.

**Comment by mjkkirschner** [comment]
@ColinDayOrg did you ever get this sorted out?

**Comment by ColinDayOrg** [comment]
No, but I worked around it by simply returning a string from a Code node. Although... I just tried it before sending this response and it was functioning (properly) as expected, so I guess... yes, I did get it sorted out?


Thanks,

+ Colin


________________________________

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
