### ISSUE TITLE
Wish: Visually identify optional inputs

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5550]
It would be helpful if node input ports that have a default value assigned to them had a different color/grayscale. That way one could immediately see that it is not necessary to connect anything to them.

**Comment by redinkinc** [comment]
+1

**Comment by ksobon** [comment]
+1

**Comment by Racel** [comment]
@andydandy74 - Assigning different color to input nodes might be difficult as we are already starting to use input port colors to signify different things. Maybe we can do some other affordance, like an asterisk or italicized text. In any case, adding to UX Love backlog.

**Comment by radumg** [comment]
@Racel, perhaps instead of input port colors, text colour could be used : 
- black/bold = required (prominent)
- grey = optional (subtle)

**Comment by smangarole** [comment]
@Racel Can we get an update on this feature request?

**Comment by Racel** [comment]
I also think that this will be a nice feature to have. Since this is a minor UI change, I believe we should consider for 2.0. This has been filed in our UX Love board and will be discussed as to whether or not it makes it in to the release.

**Comment by johnpierson** [comment]
Tracked internally as [QNTM-5923](https://jira.autodesk.com/browse/QNTM-5923)

**Comment by Amoursol** [comment]
@andydandy74 - This work is once again in-play.

**Comment by mmisol** [comment]
Fixed by #10361
