### ISSUE TITLE
Map node in Builtin library

### ISSUE THREAD

**Issue by JohanCantryn** [DynamoDS/Dynamo#5551]
I came across 2 nodes, MAP and MAPTO,  in the builtin library but I can’t guess what they do and why you should use them. (I'm not talking about the List.Map node). The only help I could find is from the node itself: “Maps a value into an input range”. Can somebody provide an example an some explanation about these nodes. Thanks in advance.

**Comment by mjkkirschner** [comment]
These nodes scale a range of numbers into another range... for example

1..10 can be ramped to 0..1

**Comment by mjkkirschner** [comment]
also checkout remap

**Comment by JohanCantryn** [comment]
Tnaks for your feedback. But I still do not understand the how these nodes are working compared to the remap node. In the following example I c
![map](https://cloud.githubusercontent.com/assets/13676901/10572516/7354375a-7649-11e5-9ff6-9cb7b61338bc.PNG)

**Comment by mjkkirschner** [comment]
@JohanCantryn the code for this node is here:
https://github.com/DynamoDS/Dynamo/blob/b4c034b01a541d308ac53738e15dc4aff64e3119/src/Engine/ProtoCore/Lang/BuiltInFunctionEndPoint.cs#L951

I was incorrect before on this builtin node specifically, what it does is to map some input between min and max, so lets say input = 1, min = 0, and max = 4. into the normalized range between them. so we will get .25 as the output.

**Comment by JohanCantryn** [comment]
@mjkkirschner thanks a lot, now I understand it.
