### ISSUE TITLE
Ability to Hide Nodes in a Published Package

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#5552]
In some cases, code creation results in some nodes that are not really useful by themselves but need to be nested or used in some other node.

It would be good to be able to set a 'hidden' property in the dyf xml, so that this node would not show in the Library or In Canvas search, but Dynamo would still know that it was there and would use it in calculation.

Is this addition to Package Manager / dyf structure possible?

**Comment by andydandy74** [comment]
:+1:

**Comment by sharadkjaiswal** [comment]
You can use IsVisibleInDynamoLibrary="false" attribute for your custom node workspace as done in #5058

**Comment by andydandy74** [comment]
@sharadkjaiswal Great - this works perfectly!

**Comment by sharadkjaiswal** [comment]
@andydandy74 Great to hear that it works, closing this issue now.
