### ISSUE TITLE
starting a node from a c# code

### ISSUE THREAD

**Issue by FloEisbaer** [DynamoDS/Dynamo#5569]
Hi,
we are trying to call one or more Dynamonodes from a c# code. We need that for an optimizer we want to write so that we cann run parts of the project in Dynamo again and again automatically to find the best solution. We need something that restarts the node like the function.apply node but can't find anything like that in the codestructure. 
Does anybody know how to solve it?
Thank you and greetings
Flo

**Comment by mjkkirschner** [comment]
perhaps loop.while will help you:
https://github.com/DynamoDS/Dynamo/blob/09d59dd92254da43e776d0b18180126257a0697a/src/Engine/ProtoCore/ExtendedLibraries/FunctionObject.ds#L598

if you want to write a higher order node - one that accepts a function, like __apply() then look at the implementation of list.map and loop while.

**Comment by FloEisbaer** [comment]
Thank you for your reply.
Do you know if its possible to define a functionObject in c# and to call apply on it and which dll i would need for that?
At the moment we are reading in the function as a string for our optimizer. Then we transform that string to a function and call it with "function.evaluate()" inside the algorithm. It would be perfect if we could do that on a random collection of Dynamo-nodes. So reading in a functionObject and calling it wherever we need to inside the code.

**Comment by mjkkirschner** [comment]
@FloEisbaer I don't think it is currently possible with c#. This is a question for @lukechurch though.

What you can do now is to implement a UI node in c# and build an output AST that builds a _singleFunctionObject from some input list.

for exmaple:

https://github.com/DynamoDS/Dynamo/blob/f92d2971505cc605f16964a8ffeb78faaa2335ab/src/Libraries/CoreNodeModels/CreateList.cs

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
