### ISSUE TITLE
Dynamo 0.8.3 and upwards Revit compatibility

### ISSUE THREAD

**Issue by mtsalheen** [DynamoDS/Dynamo#5570]
When I try to install Dynamo starting from version 0.8.3 and upwards I receive this message "Dynamo requires an installation of Revit 2015 or Revit 2016 or Revit 2017 in order to proceed!"
We are using Revit 2014 and will likely remain using it for the next couple of years, Any Advice?

Thanks in advance.

**Comment by RodRecker** [comment]
@mtsalheen Dynamo 0.8.2 is the last version that supports Revit 2014.

**Comment by mtsalheen** [comment]
Oops, it looks like I'm stuck here ... is that because of 2014 functionality limitations?

**Comment by RodRecker** [comment]
To some extent yes. The more releases of Revit we support, the more time we spend integrating new features to match the API differences in each release. That means less time for new feature work.

**Comment by RodRecker** [comment]
@mtsalheen tell us more about how you're stuck and maybe we can figure out how to help.

**Comment by mtsalheen** [comment]
@RodRecker appreciate that, so far no particular issue except some instability when I rerun a script it takes very long time more than the first run and some times returns error for nods that were fine while I didn't change anything related to it.
I kind of hoped that the new builds could eliminate that.
What I meant by stuck that I'll not receive any updates or fixes as long as I'm working in this project cause we have a contractual requirement to use Revit 2014.
