### ISSUE TITLE
Dynamo Library

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5571]
A few questions depending on the Dynamo library:
- is it possible to have a switch to have the library look like in version 0.8? I loved the groups. Now it is horrible to browse, especially on smaller screens. Perhaps it will also be enough to have tabs for create/action/query again.
- is it possible to restore the library in the state (visible or hidden) as it was when closing dynamo on restart?
  Thanks, redinkinc

**Comment by Racel** [comment]
We do not plan on reverting back to the 0.8 version of the library. We are working on a reorganization of the library for 2.0. We currently do not have plans to cache the state o the library and do not have that in our roadmap for the near term future.

Closing this for now.
