### ISSUE TITLE
0.9.0 Release Candidate available for review

### ISSUE THREAD

**Issue by sharadkjaiswal** [DynamoDS/Dynamo#5581]
We’re getting ready to post the next approved stable build. We’ll be letting it “bake” for a week or so, looking for any late regressions or bugs in the new functionality. Please try it out, and let us know if you see anything gone wrong.

http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoReleaseCandidateInstall0.9.0.exe

You can see the list of major new functionality in the What’s New on first run of the new install, or just take a look at the ReadMe on Github

Because this is a jump from 0.8 to 0.9, you will be able to have any 0.8 era Dynamo installed side by side with 0.9, so no worries about having to move back and forth with your old builds. The jump from 0.8 to 0.9 should be much smoother than any update before, as the underlying structural changes are much more subtle this time.

Thanks!

The Dynamo team

**Comment by jnealb** [comment]
Please note that if your graphics adapter has a "control panel" which registers Dynamo for "High Performance graphics etc" you may need to update it manually for 0.9 for optimal performance.

**Comment by andydandy74** [comment]
This is a minor nuisance, but not really mission critical:
#5613 (under certain conditions custom nodes may be wrongfully displayed as ```Create``` type nodes)
