### ISSUE TITLE
Library Graphics

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5590]
ver: 0.9.1.2917
OS: Win 7

Some of the graphics in the library tree go beyond the left edge of the frame

![20151022-1](https://cloud.githubusercontent.com/assets/5621624/10655927/15fad316-7897-11e5-8775-446fe8e1f4d2.jpg)

**Comment by ksobon** [comment]
same here:
![image](https://cloud.githubusercontent.com/assets/529781/10760338/81e4c2c2-7c92-11e5-845f-779e45dfbd85.png)

**Comment by ksobon** [comment]
what's causing it is an onClick event attached to the "+" graphic. The whole tree jumps over to the left when you click on the little plus/thunder icon. Weird.

**Comment by smangarole** [comment]
@vykrum Please re-open if this issue is reproducible in Dynamo 1.3. Thanks.
