### ISSUE TITLE
Package Manager not showing new versions

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#5599]
I have uploaded Bakery package many times since the latest date shown on the Package Manager website, but the last months worth of uploads / new versions do not seem to be showing. There were no errors reported during the upload. Why is this happening?

**Comment by ksobon** [comment]
are you logged into exact same autodesk 360 account as you used when you first published your package? this will cause exact behavior that you are describing.

**Comment by LukeyJohnson** [comment]
Yes as far as I know I always use the same account, luke.johnson . I'm wondering if its because I use a lot of dependencies? Like Lunchbox appears twice, plus Bakery sometimes shows up as a dependency. I'm thinking of making it non-dependent on other packages to see if that will fix the issue.
![dependency list](https://cloud.githubusercontent.com/assets/5659896/10714826/97559e72-7b4f-11e5-85bb-0a8a69812b58.png)

**Comment by LukeyJohnson** [comment]
I installed 0.9 RC to see if it would allow upload. It failed with message "try again later". Is there a more useful log hiding somewhere that could tell me what is causing this problem?
![failed 9rc](https://cloud.githubusercontent.com/assets/5659896/10729703/2acdebd2-7c3b-11e5-9d19-6560de149d85.png)

**Comment by jnealb** [comment]
@pboyer Can you please give this a curbside?

**Comment by LukeyJohnson** [comment]
I am able to deprecate and remove deprecation without issue, so I don't think it is a permissions issue. It is extremely frustrating that I have almost two months worth of work and custom nodes that I cannot share with the community in the package manager at this time. Is there some back-end hack to just delete everything in the Bakery repository and let me re-upload it? I see the greg package zip in the temp directory, but I can't find any useful logs that would indicate a problem with the upload.

**Comment by jnealb** [comment]
@LukeyJohnson We understand your feelings and are investigating.

**Comment by LukeyJohnson** [comment]
Ok, I think I solved it by deleting the backups in the dyf\backups folder. This reduced my greg package zip from 15mb to 1mb. I also removed a lot of dependencies but I don't think that was the root cause.

**Comment by andydandy74** [comment]
Wow - 14 MB of backups. A couple of months ago I asked to have the backup folder ignored when uploading: #4699

**Comment by mjkkirschner** [comment]
issue was solved with this PR I believe:
https://github.com/DynamoDS/Dynamo/pull/5877
