### ISSUE TITLE
ProtoCore.DSASM.StackValue in preview output

### ISSUE THREAD

**Issue by KirillLukyanenko** [DynamoDS/Dynamo#5601]
It reproduced in version 0.8.2 and RC 0.9.0

Steps to reproduce:
1. Create node (for example Color.ByARGB)
2. Open Custom node with Color.ByARGB
3. Return to main document and open preview of node

![stackvalue](https://cloud.githubusercontent.com/assets/13420848/10715653/b45cec92-7b26-11e5-99b8-a8ac54af1732.png)

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem.
