### ISSUE TITLE
Quick Access Toolbar Issue with Dynamo 0.8.2 and Revit 2016 R2

### ISSUE THREAD

**Issue by PeterAvsec** [DynamoDS/Dynamo#5604]
Dear Sirs,

I have a ZBook 17 G2 with Intel HD 4600 and Nvidia Quadro K3100M on Windows 10 , 24 Gb memory and Revit 2016 R2 with dynamo 0.8.2.

Drivers are up to date. As soon as the startup of Revit 2016 R2 is finished de quick access toolbar disappears.

When I attach a screen to de displayport of my ZBook and I pull Revit 2016 R2 to the screen everything is OK.

I found out that the problem is due to Dynamo 0.8.2. because I installed dynamo 0.8.1. and have no issues.

I have installed the RC of Dynamo 0.9 and have the same issue.

Thanks in advance for any answer.

Best regards.

Peter

**Comment by RolandoV** [comment]
Hello, 

I experienced the same problem as PeterAvsec had. I Install Dinamo 0.8.2 for Revit Structure 2016 and my quick access toolbar disappear. I uninstall it and repair my Revit and the quick access toolbar came back. 

Thanks in advance for your help 

All the best, 

Rolando

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2164).

**Comment by PeterAvsec** [comment]
Bonjour, c'est peter.
L'adresse peter.avsec@cartocad.fr est protégée des courriers indésirables par SpamWars.
Pour que vos messages me soient transmis, veuillez répondre à ce message (bouton "Répondre") en tapant n'importe où dans le texte de la réponse le code ci-dessous :
J  E  R      E     D      
(tapez les cinq lettres sans les espaces blancs)
Vous n'aurez à effectuer cette opération qu'une seule fois, et vous serez averti de l'acheminement de votre message.
Cordialement,
peter

SpamWars est un antispam multi-plateforme (Windows, MacOS, Unix/Linux)

Hello, this is peter.
The address peter.avsec@cartocad.fr is protected against spam by SpamWars.
In order to send messages to me, please reply to this message ("Reply" button) type the following code anywhere in your message :
J    E   R  E  D  
(type the five letters without spaces)
This needs to be done only once, and you will receive e-mail notification once your message is sent.
Best regards,
peter

SpamWars is a multi-plateform antispam product (Windows, MacOS, Unix/Linux)
