### ISSUE TITLE
Surface.FlipNormalDirection Translates the surface up

### ISSUE THREAD

**Issue by jluebker** [DynamoDS/Dynamo#5609]
I was working with the flip surface normal node and discovered that it is translating the surface vertically when it flips the surface coming from a translate node (aka it igonores the stranslation

Translated Surface
![flipnormal-after](https://cloud.githubusercontent.com/assets/4041748/10746880/3df7fc0e-7c0c-11e5-8f7f-5bf14386c8a7.PNG)

Flipped Translated surface (moves up)
![flipnormal-before](https://cloud.githubusercontent.com/assets/4041748/10746879/3df48df8-7c0c-11e5-9d34-1858ee8b34ab.PNG)

original surface before translation
![flipnormal-original](https://cloud.githubusercontent.com/assets/4041748/10746950/edce9b1a-7c0c-11e5-99d1-9cfcb4eca337.PNG)

**Comment by jluebker** [comment]
on further exploration the surface.flipnormaldirection does not actually flip the surface, it just flips the normal (i.e. reverses the normal vectors) ... as demonstrated by the fact that the perimeter curve does not change direction (which it should if the surface was truly flipped)...

this is a problem... it would be better to have a flip surface than a flip surface normals (we can essentially do the same thing by throwing a reverse vector on the normal of the surface...

when you flip the surface it flips more than just the normals which is important if you are using a surface to drive the dynamo graph...
![flipsrfbug1](https://cloud.githubusercontent.com/assets/4041748/10799591/dc02baba-7d6a-11e5-94c4-b473ca22e56c.PNG)
![flipsrfbug2](https://cloud.githubusercontent.com/assets/4041748/10799590/dbf914b0-7d6a-11e5-956d-6708b0590494.PNG)

**Comment by aparajit-pratap** [comment]
Tracked here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10437

**Comment by jluebker** [comment]
who do we sign into that? its not using the autodesk credentials... is this the new system at the dynamo team is using to track issues?

**Comment by aparajit-pratap** [comment]
This is our internal tracking system just for our own reference. Will update you when this issue is fixed.

**Comment by Amoursol** [comment]
The Flip Normal node has now been amended in Dynamo 2.6.
