### ISSUE TITLE
0.82 definition extends are zoomed out and can't be restored

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#5615]
sometimes the definition is zoomed out. if you try to zoom all (both screen menu and pop up menu) it does not restore.
examining the dyn file shows that x and y coordinates are extremely big values.

**Comment by ikeough** [comment]
Is this for the 2D graph view of for 3D view?

**Comment by epeter-** [comment]
it is for the definition graph

Am 27.10.2015 um 18:22 schrieb Ian Keough:
>
> Is this for the 2D graph view of for 3D view?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/5615#issuecomment-151576237>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by ikeough** [comment]
This definitely sounds like a localization bug that we have not seen in a while. We've been doing some work with copy and paste that may have affected this. We will log it internally. Thanks!

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
