### ISSUE TITLE
current dynamo version

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5616]
@mjkkirschner  is there a way to find out what is the current running version of Dynamo? 

Hopefully it's something that I can access from Python node. :-) 

Thanks!

**Comment by mjkkirschner** [comment]
I'm not sure there is a way through python currently, but you could always do what is done by the extensions and view extensions frameworks 

https://github.com/DynamoDS/Dynamo/blob/bf3e1b64b55ee0b37f838317910e5f4031e1c6d8/src/DynamoCore/Models/DynamoModel.cs#L579

this is not guaranteed to always reflect the way we set the version though... If you are writing a UI node, you can get a reference to the DynamoModel, and look at this property:
https://github.com/DynamoDS/Dynamo/blob/bf3e1b64b55ee0b37f838317910e5f4031e1c6d8/src/DynamoCore/Models/DynamoModel.cs#L187

**Comment by ksobon** [comment]
I will close this but this doesn't help me with Python. Just one more quick question...would it be possible to add that kind of a utility method to Dynamo code and expose it for use with Python? I am asking because of all of the changes in new version, each one that comes out has a different physical location on a drive and it becomes a pain to try and manage multiple versions at the same time. I mean i could potentially have Dynamo in 0.6, 0.7, 0.8 and 0.9 folders at this point. You know what i mean? Thanks!

**Comment by mostaphaRoudsari** [comment]
:+1:

**Comment by dimven** [comment]
I thought that once running, Dynamo would be loaded as a module in the main Revit process and once we have the module, we can extract the version from that. Unfortunately, that doesn't seem to be the case. 
Not sure if this is of any help, but the above principle works great for the DynamoSandbox:
![2015-10-31_21-57-57](https://cloud.githubusercontent.com/assets/7148394/10864041/5abcf642-801b-11e5-8994-4b84ecc567b7.png)

**Comment by mostaphaRoudsari** [comment]
@dimven I didn't know that you can do this. This is by itself is pretty useful. I agree that having access to document itself and the node from inside Python is a great step to make them much more useful for bigger developments

**Comment by mjkkirschner** [comment]
@ksobon theres no reason you can't run those linked lines of code from inside python

**Comment by mostaphaRoudsari** [comment]
@ksobon I ended up using sys.path. Looks to be the easiest for now w/o extra lines and it should always work.

```python
def getPackagePath(packageName):
	import sys
	sys.path.append('C:\Program Files (x86)\IronPython 2.7\Lib')
	import os
	dynamoPath = sys.path[1].split('\\')[2].replace(' ', '\\')
	appdata = os.getenv('APPDATA')
	return '%s\%s\packages\%s\extra'%(appdata, dynamoPath, packageName)

OUT = getPackagePath('Manthis Shrimp')
```

**Comment by ksobon** [comment]
oh wow! I had no idea that you can do that with <code>sys.path</code>. That is extremely useful. Thanks for sharing!

**Comment by dimven** [comment]
Actually, if you're loading any of the default assemblies, couldn't you use its path ? MS definitely loads ProtoGeometry for example:

![2015-12-04_01-06-49](https://cloud.githubusercontent.com/assets/7148394/11567753/7f28d308-9a23-11e5-90a7-5a1c948a3de7.png)

**Comment by ksobon** [comment]
I don't always load ProtoGeometry. Some of my nodes are utility nodes that might for example just read rhino layers and that doesn't require ProtoGeometry. This is a good idea, but @mostaphaRoudsari approach is much more robust. :-)

**Comment by mjkkirschner** [comment]
@ksobon - I think you may want to be careful using the sys path of a python engine running inside another application, just be aware that it will point to different locations i.e., Dynamo on Revit will point somewhere different than Sandbox etc.

**Comment by mostaphaRoudsari** [comment]
@mjkkirschner thanks. I just checked inside Revit and as you mentioned it only has the current folder. Good to know.
