### ISSUE TITLE
Mulitline text parameter appears as single line

### ISSUE THREAD

**Issue by nmeek** [DynamoDS/Dynamo#5635]
Using Element.SetParameterByName for a multi-line text parameter results in a single line of text.
![dynamo multiline text](https://cloud.githubusercontent.com/assets/15450035/10884306/f3ed55e2-813c-11e5-9fa0-b610da0d8776.PNG)
![multiline text result](https://cloud.githubusercontent.com/assets/15450035/10884308/fbfa3944-813c-11e5-8293-3966dd32736d.PNG)

**Comment by smangarole** [comment]
@nmeek This issue is Revit specific. If this is still an issue can you please file this in the Revit Repo - https://github.com/DynamoDS/DynamoRevit ?
If you have a workaround, can you please share?

**Comment by andydandy74** [comment]
@nmeek - Both of these work:
![grafik](https://user-images.githubusercontent.com/3014437/29783672-a0361d52-8c21-11e7-8b0f-35a1d2f985e6.png)
