### ISSUE TITLE
2.	Element.Solids returns NULL 

### ISSUE THREAD

**Issue by nmeek** [DynamoDS/Dynamo#5636]
1.  Element.Solids returns NULL when a wall’s profile has been modified such that it extends beyond the original wall boundary

**Comment by dimven** [comment]
I've experienced this too. However for me, going beyond the extents is not the problem, but the fact that the profile has splines.
This works:
![2015-11-03_11-25-01](https://cloud.githubusercontent.com/assets/7148394/10900697/ebca2c6e-821d-11e5-82d1-f45ac0a0e7eb.png)
![2015-11-03_11-25-31](https://cloud.githubusercontent.com/assets/7148394/10900698/ed1a459a-821d-11e5-9307-f7de5114891b.png)

This fails:
![2015-11-03_11-27-24](https://cloud.githubusercontent.com/assets/7148394/10900701/f4e558d2-821d-11e5-956e-359fcbeedd23.png)
![2015-11-03_11-27-37](https://cloud.githubusercontent.com/assets/7148394/10900705/f70c1830-821d-11e5-8855-a54e92bc72f8.png)
![2015-11-03_11-27-42](https://cloud.githubusercontent.com/assets/7148394/10900708/f97cc22c-821d-11e5-80aa-b5a41972c0f4.png)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2163).
