### ISSUE TITLE
Categories node not usable as type for RemoveIfNot node

### ISSUE THREAD

**Issue by nmeek** [DynamoDS/Dynamo#5637]
the “Categories” node produces the plural form of the type (ie. “Walls”), but the “RemoveIfNot” node accepts the singular “Wall” as the type

**Comment by ikeough** [comment]
Can you explain a bit more of your desired workflow?

**Comment by ksobon** [comment]
I think user is confusing how `RemoveIfNot` works and what the `type` input should be. We asked for additional input to explain his question better over two years ago. It's time to close this issue. cc: @kronz

**Comment by pomerlok** [comment]
Але долбоебы на вопрос то ответите?
