### ISSUE TITLE
OverrideColorInView resets all other graphical overrides

### ISSUE THREAD

**Issue by nmeek** [DynamoDS/Dynamo#5640]
OverrideColorInView  resets all graphical overrides, other than surface color, to default values. In my oppinoin, this node should change only the surface color. Sometimes other overrides may have been used in the view for other reasons, and the user may not want to reset those.
Before:
![overridecolorinview_before](https://cloud.githubusercontent.com/assets/15450035/10886027/d19575fc-8145-11e5-923c-d18a67d17918.PNG)
After:
![overridecolorinview_after](https://cloud.githubusercontent.com/assets/15450035/10886036/d6a01e76-8145-11e5-83c1-0b7e5517afc4.PNG)

Consider adding nodes such as "OverrideProjectionColor", "OverrideSurfaceTransparency", "OverrideHalftone"....

**Comment by andydandy74** [comment]
see issue #4769

**Comment by nmeek** [comment]
public Element OverrideSurfaceColorInView(Color color) 
         { 
             TransactionManager.Instance.EnsureInTransaction(DocumentManager.Instance.CurrentDBDocument); 

             var view = DocumentManager.Instance.CurrentUIDocument.ActiveView; 
             var ogs = view.GetElementOverrides(InternalElementId);
 
             var patternCollector = new FilteredElementCollector(DocumentManager.Instance.CurrentDBDocument); 
             patternCollector.OfClass(typeof(FillPatternElement)); 
             FillPatternElement solidFill = patternCollector.ToElements().Cast<FillPatternElement>().First(x => x.GetFillPattern().IsSolidFill); 

             var overrideColor = new Autodesk.Revit.DB.Color(color.Red, color.Green, color.Blue); 
             ogs.SetProjectionFillColor(overrideColor); 
             ogs.SetProjectionFillPatternId(solidFill.Id); 
             view.SetElementOverrides(InternalElementId, ogs); 

             TransactionManager.Instance.TransactionTaskDone(); 
             return this; 
         }

         public void ResetViewOverrides() 
         { 
             TransactionManager.Instance.EnsureInTransaction(DocumentManager.Instance.CurrentDBDocument); 

             var view = DocumentManager.Instance.CurrentUIDocument.ActiveView; 

             var ogs = new OverrideGraphicSettings();
 
             view.SetElementOverrides(InternalElementId, ogs); 

             TransactionManager.Instance.TransactionTaskDone(); 
         }
