### ISSUE TITLE
Flatten in Custom Components

### ISSUE THREAD

**Issue by moethu** [DynamoDS/Dynamo#5656]
Hi there, experiencing a weird behavior of the Flatten Node within a Custom Component. See Image:
![2015-11-05_10h38_00](https://cloud.githubusercontent.com/assets/8201465/10966133/797c1e82-83a9-11e5-8343-639034bd9450.png)

**Comment by moethu** [comment]
Dynamo Version 0.9.1.2992

**Comment by ke-yu** [comment]
@moethu `Flatten` node is updated recently. Could you please retest?

**Comment by johnpierson** [comment]
Seems to be functioning appropriately in Dynamo 2.0.1. 
![image](https://user-images.githubusercontent.com/15744724/48852811-6402f880-ed6b-11e8-922b-4b7b3cb9e779.png)
