### ISSUE TITLE
wish: modify "preview", "preview upstream" and "show labels" for a selection of nodes

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5660]
Hi,
would it be possible to change the preview, preview upstream and show labels state of multiple nodes at once? right now i have to rightclick on all of the nodes individually to change their state.
Thanks, redinkinc.

**Comment by dimven** [comment]
This should already be implemented in versions past 0.81. Just select all the nodes and right click anywhere on canvas:
![2015-11-06_09-50-55](https://cloud.githubusercontent.com/assets/7148394/10987180/db02f992-846b-11e5-82b9-360c53729ad7.png)

**Comment by redinkinc** [comment]
:+1: works fine, thank you
