### ISSUE TITLE
wish: "enter" should "accept" while renaming a node. 

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5661]
Hi,
I often rename my nodes to easily identify them in large projects. Would it be possilble to change the behaviour on pressing the "enter" key to accept the changes instead of starting a new line? If a new line is necessary in my opinion it should be "alt + enter", like in many other applications (eg Excel).
Thanks, redinkinc.

**Comment by smangarole** [comment]
This issue is fixed in Dynamo Core 1.3.
