### ISSUE TITLE
wish: List.Tostring also showing number of elements

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5662]
Hi,
I often work with large nested lists and need to know and need to know the number of contained elements. In nestet lists counting is often difficult and to call list.count of the nested lists also. Therefore I suggest to display the length of the list in the ToString output like this.
![capture](https://cloud.githubusercontent.com/assets/3741716/10975099/7fcb2864-83e5-11e5-9529-ae8782e69bf1.png)
Another possibility would be a option to fold and unfold all lists.
Thanks, redinkinc

**Comment by dimven** [comment]
:+1: 
This is a great idea. That way we won't have to scroll all the way down to a sub-list's last index to quickly check the count visually. With lots of nested sub-lists, we could just start minimizing and very quickly gain an idea for the total count of each.

**Comment by jnealb** [comment]
@Racel @lillismith fyi

**Comment by Racel** [comment]
@redinkinc @dimven - Thanks for your comments. We are actually working on improving the preview bubble and watch nodes so that you can get info like this. More soon...

**Comment by smangarole** [comment]
We have added this issue in our backlog. Please note that you will find the total count in Dynamo Core 1.3.
Thanks.
