### ISSUE TITLE
If-Statement with lists of different size

### ISSUE THREAD

**Issue by Siulum** [DynamoDS/Dynamo#5665]
Hi there,

I just realized that the If-Statement Node cannot deal with lists that are not equal in size! When I have a longer list in the false statement then the size of this list becomes as long as the list in the true statement. 
In my opinion a Bug. Or is it that the inquiry only can take lists of same size?? If there is a workaround please let me know.
![statementfalse](https://cloud.githubusercontent.com/assets/13483733/10991785/76d1d7b4-8460-11e5-99a8-e40b4887ddc3.PNG)
![statementtrue](https://cloud.githubusercontent.com/assets/13483733/10991787/7acde8a8-8460-11e5-9bd4-9c95c60b5e0c.PNG)

Thanks in advance. 

Michael

**Comment by dimven** [comment]
Hi,
Have a look at the following forum discussion:
http://dynamobim.com/forums/topic/if-node/#post-30782

**Comment by Siulum** [comment]
Thanks Dimitar, 

I check it out. Super fast reply..AWESOME DUDE

**Comment by kronz** [comment]
Thanks for the response @dimven
