### ISSUE TITLE
Dynamo 0.8.2 doesn’t working with Revit 2016 R2

### ISSUE THREAD

**Issue by lucky117** [DynamoDS/Dynamo#5666]
Hello guys, I´m new user in Dynamo. I wanted to try some basics with points but I find a problem with the data sharing between Revit and Dynamo. I see the point in Revit but if I move with him in Dynamo nothing happened in Revit. I don’t know why? I use Revit 2016 R2, do you think this could be the Problem? Thanks a lot for you answer. 
Lukas

**Comment by kronz** [comment]
Can you try the file in Dynamo in Help>Samples>Basic> Basic02?
This has an example of how to create and move a Reference Point.

**Comment by lucky117** [comment]
Thanks for your quick respond. I have tried the sample Basic02, but nothing happened in Revit, please see the link below, I have made a short video, where I show the issue.

https://www.youtube.com/watch?v=Jd0ocSVSNok&feature=youtu.be

**Comment by kronz** [comment]
I think the issue is a units conversion confusion.  The Sample has the point moving around 2-5 units.  I'm going to guess that your project is in mm?  So, I can see that the reference points are created, but movement is probably not going to be apparent that far out when moving the slide is going to change from 2-5 mm.

**Comment by lucky117** [comment]
That’s it, very kind thank you for your help. Now I’m able to start with DYNAMO :)

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move conversations to the forum, and reserve the issues site for bugs and improvement requests. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/).
