### ISSUE TITLE
migration to 0.9

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5668]
All of my UI nodes are gone from my package when I move to 0.9. Anything special i need to do, to make them appear again?

**Comment by ikeough** [comment]
@ksobon Recent namespace changes to Dynamo will require small edits to your code and a recompile. Please see the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

<b>BEWARE:</b>As we approach Dynamo 1.0 many namespaces will be changing, and you will need to re-compile and re-release to stay up to date. We anticipate that after 1.0 namespace changes will be MUCH less frequent and we will be aligning with [semver](http://semver.org/).

**Comment by kronz** [comment]
Hi @ksobon we sent out a notification in the middle of October, you were on the list.  Did you get that?

Thanks
Z

**Comment by ksobon** [comment]
@ikeough  @kronz oh, that's what this is. OK, I will take care of this on my side. Thanks!
