### ISSUE TITLE
Warning: Point.ByCoordinates operation failed

### ISSUE THREAD

**Issue by BIMRigSoft** [DynamoDS/Dynamo#5674]
Looks like Libg.libginvoke causes an issue with Revit 2016R2. No problem with revit 2015.
Already tried solutions found on the forum.
Any other idea?

**Comment by mjkkirschner** [comment]
try uninstalling all versions of dynamo and reinstalling the latest.

are you using Dynamo daily builds or a stable release version?

Is the R2 release of 2016 recent? / Did you install it recently? Did it work for R1?

**Comment by BIMRig** [comment]
Already tried to uninstall all dynamo versions and reinstall. Revit 2016 reinstalled, after registry clean up.
First time issue came with 0.8.2 version, after revit R2 upgrade.
Worked fine before the upgrade.
I tried the 0.9.1 . Same issues with 2016 R2, no issue with 2015.
Install of Revit with default path.

**Comment by kronz** [comment]
@BIMRig can you check in C:\Program Files\Autodesk\Revit Architecture 2016 and confirm you have a file called ASMKERN221A.dll
Is there an ASMKERN file that is something close but not quite that name?

**Comment by BIMRig** [comment]
Hi Zach, this file is in my revit folder, yes. It is a one box version.
Any thought?

**Comment by monikaprabhu** [comment]
@BIMRig - Is this problem happening while launching dynamo through Revit or you have it  on Dynamo Standalone? Also please specify the operating system details you are using. @Randy-Ma , could you please take a look at this issue.

**Comment by BIMRig** [comment]
Problem solved (the hard way). I installed a fresh version of revit on another computer and copied all the files to the laptop.
It's working fine now. One of revit's file must have been broken.
