### ISSUE TITLE
lofting closed curves crashes dynamo

### ISSUE THREAD

**Issue by pkrez** [DynamoDS/Dynamo#5683]
as the topic says.
![capture](https://cloud.githubusercontent.com/assets/15015569/11063795/479ac030-87b9-11e5-9d93-54db7518b6e4.png)

**Comment by monikaprabhu** [comment]
@pkrez it seems to work fine on latest daily build - Can you please try again.

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem.
