### ISSUE TITLE
changes to 0.9 break GetFamilyParameter Revit UI node

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5684]
@mjkkirschner @ikeough 

Recent changes to namespaces in 0.9 seem to have broken the Revit UI node by the name of Get Family Parameter. 

![image](https://cloud.githubusercontent.com/assets/529781/11067895/cd7ad126-879c-11e5-85f2-abf23816cfe7.png)

No error is thrown, it just doesn't populate the node. 

Since I have one in my package that was based exactly on this node, mine doesn't work as well. I tried Debugging but it enters into an infinite loop of going through the <code>OnPropertyChanged()</code> when the item gets initialized - dropped on canvas. There are no errors as far as I can tell, so I am sorry if this is not enough information, but I don't have much to go on here. 
The only significant change associated with this node was the rename of the <code> Dynamo.DSEngine</code> to <code>Dynamo.Engine</code> but I don't see anything missing there. 
Can someone investigate this a little more? 

Thanks!

**Comment by ikeough** [comment]
@ksobon It wasn't the namespaces after all. This node was using a string reference to a non-existent property to determine whether to update the items in the drop down. See the linked PR for more details.

**Comment by kronz** [comment]
Tracking internally as:
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9058

**Comment by ksobon** [comment]
This fixed it. Thank you,

![image](https://cloud.githubusercontent.com/assets/529781/11079367/d29500f4-87d9-11e5-9d97-aae82693e5e7.png)
