### ISSUE TITLE
Dynamo 0.9 freezes on accessing csv data

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5685]
Hi, I recently installed version 0.9.0 on Windows 10. When I access a .csv file like below, Dynamo freezes. I can then still drag and rename the nodes, but avering else (even closing Dynamo) is no longer possible. It doesn't crash, so I do not have a report on this.
![accesslist](https://cloud.githubusercontent.com/assets/3741716/11068660/aec61aac-87d2-11e5-927e-e693abef262f.PNG)

**Comment by redinkinc** [comment]
I now noticed this can be reproduced with any script using ScopeIf. If sometimes works but can also freeze Dynamo.

**Comment by dimven** [comment]
@redinkinc ScopeIf should only  be used inside custom nodes for recursion. I think that the last time it worked for me was back in version 0.74-0.75 ...
Can you try substituting the ScopeIf with one of the alternatives provided here:
http://dynamobim.com/forums/topic/if-node/

**Comment by ke-yu** [comment]
hi @redinkinc , `ScopeIf` is a really tricky node, for example one of its limitations is a node can't be shared (e.g., `List.GetItemAtIndex` node and `Header` in your graph) as one of upstream nodes of its true/false branch :-(. Just as @dimven , using it in custom node.

**Comment by redinkinc** [comment]
ok, thanks for the reply. I'm right now using a MatLab script for getting my csv processing done. So I will close this issue...
