### ISSUE TITLE
only one package can have icons (Package.customization.dll)

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5688]
@ikeough @mjkkirschner @pboyer 

It appears to me that currently only one package can have icons defined using Package.customization.dll
Adding icons to ZeroTouch libraries works fine. That usually creates a customization file that has unique name based on namespace name ex: <code>bbUI.customization.dll</code>. Unless there are two packages with the same name, I don't think there will ever be a conflict with that method. 
However, the same name seems to throw off all of the customization files with the same name "Package". Only one of them will get loaded. For example my bumblebee package has both namespace and package customization files but since i already loaded icons via "package" customization file for Mantis shrimp, my bb icons don't get displayed. If I however, uninstall mantis shrimp, both icon sets get loaded nicely for bumblebee. Also, since my package name starts with "A" my icons load in, but @andydandy74 package doesn't load since his name starts with "C". 

All in all, it appears that only ONE (1) Package.customization.dll file can be loaded at the time. Can we make sure customization files work for more than one package? 

Thanks!

**Comment by ikeough** [comment]
@kronz is working on this with another user. I believe it's [MAGN-9057](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9057).

**Comment by andydandy74** [comment]
Looks like this is being addressed in #5761
