### ISSUE TITLE
Error: Third party updater 'Sun and Shadow Settings Updater' has experienced a problem and its action to be canceled.

### ISSUE THREAD

**Issue by tauyoung** [DynamoDS/Dynamo#5702]
![render error](https://cloud.githubusercontent.com/assets/1397095/11112303/a40d09c4-894c-11e5-8d12-ad30afc07549.jpg)
Steps to reproduce:
1. Start Revit with Dynamo installed
2. New a project.
3. Go to default 3D view
4. Click View->Render->Choose a sun location->Choose Sunlight from Top Right->Select "Level 3"->click OK
If you run Dynamo once, above steps can work correctly with no error message.
Reported from ITF - https://beta.autodesk.com/project/feedback/view.html?cap=F32D2578538B4B1A802B54F32B07D134&uf=7013CD474CA3472582AEEA104D4CA349&new=1&ifps=-898&t=0&fti=2&vfid=%7bD486C397-9C89-47A3-962B-112C54361876%7d&bnufnc=%7b59A7E929-6234-401C-85F8-BAFE064D598C%7d&bnufpc=%7bB840F58C-5892-4676-84B2-60DC648A5920%7d

**Comment by sm6srw** [comment]
This was fixed in 0.9.2 for Revit 2015, 2016 and 2017.
