### ISSUE TITLE
Costum Nodes not loading in Dynamo 0.9.0

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#5704]
Hi, I have a folder with my costum nodes that are not in the Dynamo folder. In previous builds they have been loaded automatically when I opened a Dynamo Project where I used one of these. Now I get the Error: Custom node definition is not loaded! every time I open a project. I have also added the folder a node path, but it still doesn't work.

**Comment by jbf1212** [comment]
I'm also having this problem.
