### ISSUE TITLE
define default value 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5707]
@ikeough @mjkkirschner 

I am sorry if this is programming question and not really Dynamo question, but I am wondering if there is a way to define one of the inputs with a default value that is a class instance rather than int or bool. 

![image](https://cloud.githubusercontent.com/assets/529781/11129938/39884506-8950-11e5-8dd1-852ce63efb4b.png)

I want to leave this input out and set the value to null if not plugged in but I can't get Dynamo to work. 

```C#
public static BarData Data(List<string> Names, List<double> Values, Domain dDomain = null)
        {
        }
```

Any idea how I can make this work? I looked under the hood for some of the nodes in Dynamo, but all I could find were int or bool based default value declarations. 

Thanks in advance!

**Comment by ikeough** [comment]
@ksobon On zero touch nodes, you can't use the standard c# default parameter mechanism for references types (i.e. objects). You can however use a special attribute that we provide which allow you specify a piece of Design Script that will be the default. I'm adding an example to the Dynamo Samples repo presently.

**Comment by ksobon** [comment]
mhmmmm, I am trying not to force users to provide input for this value but if they do it's a custom class input. Sounds like that will not work. I will just force them to provide input. :-( 
Can we log this as a functionality request then? It would make sense to be able to do this and not get <code>_SingleFunctionObject</code> but rather just let the node execute with the default defined?

**Comment by ksobon** [comment]
at the same time being able to use that node as an input for a list,Map function is a pretty powerful functionality so I am by no means asking for that to go away. If its not possible to have both then I will just live with it. Thanks!

**Comment by ikeough** [comment]
@ksobon I think we've got you covered. 

See here:
![image](https://cloud.githubusercontent.com/assets/1139788/11130854/37921aba-893c-11e5-98b1-5c62e4ebe027.png)
```c#
public static BasicExample Create([DefaultArgumentAttribute("Point.ByCoordinates(5,5,5);")]Point point)
{
  return new BasicExample(point.X, point.Y, point.Z);
}
```

On the "Point" port, you can right click and check "Use Default", which will use the default value. Otherwise, the node will not use that default, and it can be used in List.Map.

**Comment by ikeough** [comment]
I've put the example in Dynamo Samples:

https://github.com/DynamoDS/DynamoSamples/blob/master/src/SampleLibraryZeroTouch/Examples/BasicExample.cs#L122

**Comment by ksobon** [comment]
so I tried this: 

```C#
/// <summary>
        /// New data class
        /// </summary>
        /// <param name="Names">Name property for each value.</param>
        /// <param name="Values">Value</param>
        /// <param name="Domain">Optional domain for data set.</param>
        /// <returns name="Data">BarData</returns>
        public static BarData Data(List<string> Names, List<double> Values, [DefaultArgumentAttribute("Domain(0,0);")]Domain dDomain)
        {
            List<BarDataPoint> dataPoints = Names.Zip(Values, (x, y) => new BarDataPoint { name = x, value = y }).ToList();
            BarData barData = new BarData();
            barData.Data = dataPoints;
            barData.Domain = dDomain;
            return barData;
        }
```

Then in Dynamo i check "use default value" and i get this error:

![untitled-1](https://cloud.githubusercontent.com/assets/529781/11131302/0af403a8-8958-11e5-9c80-5fd8e322bad0.png)

Does <code> Domain()</code> has to be in the same namespace?

**Comment by mjkkirschner** [comment]
Try supplying the fully qualified name for the constructor

**Comment by ksobon** [comment]
tried this: 

```C#
public static BarData Data(List<string> Names, List<double> Values, [DefaultArgumentAttribute("D3jsLib.d3BarCharts.Domain(0,0);")]Domain dDomain)
```

same issues: 

![untitled-2](https://cloud.githubusercontent.com/assets/529781/11131392/99065f9c-8958-11e5-87b5-dd8ce5a814ea.png)

Here's my Domain class:

```C#
public class Domain
    {
        double _a;
        public double A
        {
            get { return this._a; }
            set { this._a = value; }
        }
        double _b;
        public double B
        {
            get { return this._b; }
            set { this._b = value; }
        }
        public Domain(double x, double y)
        {
            this._a = x;
            this._b = y;
        }
        public Domain()
        {

        }
    }
```
and its namespace: <code>namespace D3jsLib.d3BarCharts</code>

**Comment by ksobon** [comment]
ok got it to work. thanks!

**Comment by ksobon** [comment]
I am getting a null error further downstream so i need to do some more investigation. let me play with it for a little bit and i will get back to you.

**Comment by ksobon** [comment]
So here's what happens. Somehow this generates a null object. I was able to catch it downstream but that's probably not ideal. It works for now, but I am not sure I am ready to close this issue.

**Comment by ksobon** [comment]
I got it figured out. Cheers!

**Comment by minhchau1510** [comment]
Hi ksobon,

So what was the problem and answer in the end then? Thanks!
