### ISSUE TITLE
Model not updated after variable is modified in complex definition

### ISSUE THREAD

**Issue by pilcru** [DynamoDS/Dynamo#5718]
When I change one of the inputs in the attached Dynamo definition, the model is not updated as it should. Dynamo will say "working" for a while and return the same result as before.

You can try it for the "mesh size" variable here, for Dynamo to register the changes you will have to save the file and reopen it.

File here: https://www.dropbox.com/s/5a7d7ih4rgjjzwg/CompassMethod_working_DynamoGen.dyn?dl=0

I am using version 9.1.3162

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
