### ISSUE TITLE
The "open with" Dynamo is not working

### ISSUE THREAD

**Issue by pilcru** [DynamoDS/Dynamo#5719]
In windows 7, using Dynamo 9.1.3162, when I double-click on a .dyn to open it with Dynamo, Dynamo opens but does not open the file. Instead, I get the home page and have to open the file myself from Dynamo.

Is that a mis-configuration on my side or a Dynamo bug?

**Comment by monikaprabhu** [comment]
@pilcru - Thanks for reporting the issue. I can reproduce it on the Dynamo open source build. (It seems to be working on Dynamo Studio) Tracking the issue in MAGN-9128.

**Comment by smangarole** [comment]
@Randy-Ma - Can you please comment on how difficult is the fix? We are trying to figure out if we should be working on this issue.

**Comment by smangarole** [comment]
This issue is not affecting any major workflows. It's low on the priority list. Closing this issue.
Thanks.
