### ISSUE TITLE
Curve.Extrude crashes dynamo

### ISSUE THREAD

**Issue by johncyyoung** [DynamoDS/Dynamo#5728]
Using dynamo 0.9.0.3067 with Revit 2016
Going through the primer to get familiar.
In section on Data going through example'
![2015-11-19_14-36-15](https://cloud.githubusercontent.com/assets/2712127/11261728/59f42b54-8ecb-11e5-9a50-0a10b4c8e66b.jpg)

**Comment by ikeough** [comment]
Are there any details in the window that pops up during the crash? If so, can you send them to us?

**Comment by kronz** [comment]
@johncyyoung  If there is anymore information, please re-open.  Thanks!

**Comment by johncyyoung** [comment]
Sorry for not replying earlier, .91 has fixed problem.
John

Sent from Outlook<http://aka.ms/Ox5hz3>




On Sun, Nov 22, 2015 at 7:03 PM -0800, "Zach Kron" <notifications@github.com<mailto:notifications@github.com>> wrote:


@johncyyoung<https://protect-eu.mimecast.com/s/ZlrHBzX57tZ> If there is anymore information, please re-open. Thanks!

-

**Comment by ikeough** [comment]
@johncyyoung Thanks for the update!
