### ISSUE TITLE
Mantis Shrimp causing a slow search? 

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5745]
This was brought to my attention. https://github.com/ksobon/MantisShrimp/issues/17
@pboyer can you shed some light on possible causes? I am not sure that there is anything that I can do to make MS better.

**Comment by ikeough** [comment]
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem.
