### ISSUE TITLE
Transpose not work

### ISSUE THREAD

**Issue by lzeaf** [DynamoDS/Dynamo#5751]
structure  was change
but item not  change

**Comment by monikaprabhu** [comment]
@lzeaf - thanks for catching this - I'm tracking it under -MAGN-9192

**Comment by monikaprabhu** [comment]
@lzeaf - could you please post your testcase for reference.

**Comment by lzeaf** [comment]
i thinhk i need a data structure ike grasshopper    same like {A;B;C} i ==> {A;B;i}C

**Comment by kronz** [comment]
Transpose seems to be working fine in daily builds
