### ISSUE TITLE
Background 3D Preview does not refresh

### ISSUE THREAD

**Issue by mikeyforrest** [DynamoDS/Dynamo#5756]
When using a boolean toggle and python script to control output ( to show or hide geometry), the geometry is not refreshed and removed on a 'null' output?

If the 'false' statement is connected to new geometry it works, seems the 3D Preview does not refresh unless it has to draw new geometry.

**Comment by monikaprabhu** [comment]
We already have an issue logged at - MAGN-9172

**Comment by dbaldacchino** [comment]
Here's a video example of when the background preview fails to refresh when the list that generates polysurfaces becomes empty. Hope it's of some use.

http://autode.sk/1XeNnND

**Comment by jnealb** [comment]
@dbaldacchino Thank you for that

**Comment by ikeough** [comment]
Internal issue has been closed.
