### ISSUE TITLE
Re-creatable crash when removing nodes when connecting wires

### ISSUE THREAD

**Issue by archie456** [DynamoDS/Dynamo#5768]
1. Create two number noded
2. Create a Point.ByCoordinates node
3. Click on the > button in one of the number nodes, you start to connect the wire - don't connect it to anything.
4. Right click the title of the node the wire connection is coming from - and select remove to remove the note
5. The Node is removed, but the wide connection still exists - connect it to any of the X, Y or Z of the Points.ByCoordinates node - this causes a crash.

**Comment by monikaprabhu** [comment]
@archie456 - This is duplicated by issue https://github.com/DynamoDS/Dynamo/issues/5768. Internally tracked at MAGN-9127.

**Comment by ikeough** [comment]
Internal issue has been closed.
