### ISSUE TITLE
Topology nodes

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5775]
Ver: 0.9.1.3302
OS: Win 7

Shouldn't all faces, edges and vertices be listed?

![20151130-2](https://cloud.githubusercontent.com/assets/5621624/11466555/c50d4b92-9767-11e5-950d-bbadecd82efa.png)

**Comment by dimven** [comment]
This is actually the result of a much deeper problem with Dynamo (and possibly the ASM). A rectangle is actually a polycurve and when you loft two polycurves you should expect to get a polysurface, but as you've found out - you don't get that.

![2015-12-02_18-44-12](https://cloud.githubusercontent.com/assets/7148394/11528918/9b61039c-9924-11e5-980c-fe7d53f9a314.png)

The first problem is the issue of element casting in nodes (the type of the output). The "Surface.ByLoft" node always casts the result as a surface, even when it's not. There are many other offenders that do this. For example the "Curve.Offset" node always re-casts the result as a curve(even if the input was a nurbs, rectangle, arc, what have you) and the "Polycurve.Curves" node always casts the resulting segments as curves even when they're actually lines, arcs, nurbs, etc. So if you don't know that you're actually getting a polysurface, this could lead to a lot of confusion. 

The second problem is that right now polysurfaces are handled very poorly by Dynamo. If you try to perform any action on them (get the iso lines, create UV points, or as you have found out extract primitives), the action is applied only on the first surface in the array. The expected result would be to at least perform the action on all the surfaces or ideally, treat the PS as a single entity and perform the action globally( possibly very technically challenging).

**Comment by sharadkjaiswal** [comment]
@vykrum, this has been fixed in latest daily build, please take a look.
