### ISSUE TITLE
List Indentation

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5795]
Ver: 0.9.1.3351
OS: Win 7

No sub list indentation.

![20151203-1](https://cloud.githubusercontent.com/assets/5621624/11563834/091dc690-99fc-11e5-97fe-a306686c0f97.png)

**Comment by monikaprabhu** [comment]
@jnealb , @ramramps - please take a look at this issue. @vykrum - Thanks for bringing this up.

**Comment by ramramps** [comment]
@monikaprabhu - Yes. this is fixed as part of preview bubble.http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8941

**Comment by kronz** [comment]
![2016-01-01_2320](https://cloud.githubusercontent.com/assets/3456818/12073201/560dec48-b0de-11e5-8e8b-040469ded1d7.png)
