### ISSUE TITLE
Text notes UI in Dynamo

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#5798]
I have noticed some weird Text Note UI behavior: 

It can be made really small: 

![image](https://cloud.githubusercontent.com/assets/529781/11569385/8e12ad6c-99bf-11e5-829e-fe6ca2554045.png)

Adding a Minimum Size property to that window might make sense. 

It can be collapsed so that controls/buttons disappear:

![image](https://cloud.githubusercontent.com/assets/529781/11569423/c8c11034-99bf-11e5-92c8-d57acf711ca7.png)

Again, a min size constraint would fix that. 

It cannot be expanded however: 

![image](https://cloud.githubusercontent.com/assets/529781/11569436/e5cc38f2-99bf-11e5-8d87-b705d30b1a47.png)

There seems to be a Max Size applied to it. It only allows for 2 lines of text to be visible at a time making adding longer notes quite hard. 

It can be maximized to look like this: 

![image](https://cloud.githubusercontent.com/assets/529781/11569474/195e863e-99c0-11e5-9269-66c384802e27.png)

That's weird, maybe we disable the min and max boxes. 
Also, its visible in the task-bar as independent app: 

![untitled-6](https://cloud.githubusercontent.com/assets/529781/11569508/48a64256-99c0-11e5-94f4-14411df53605.png)

That of course can be disabled as well. 

All in all, that text note editor might need some love. I bet others will have some comments about enabling font style, color, size etc. 

Thanks!

**Comment by Amoursol** [comment]
Text Notes have been improved in https://github.com/DynamoDS/Dynamo/pull/9600 so that there is a minimum for **SetValue** to stop UI compression and text notes can now also be resized in any direction.
