### ISSUE TITLE
Feature Request: expose the "MaxWatchNodeWidth" and "MaxWatchNodeHeight" settings to the end user

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#5805]
I constantly find myself wishing that the watch node could be expanded further, especially when dealing with long multi-dimensional arrays. Can (and should) these be exposed as user modifiable settings? 

Alternatively, it might be a good idea to make the watch node expandable like the Watch3D node.

**Comment by josols** [comment]
+1

**Comment by ksobon** [comment]
+1

**Comment by eibre** [comment]
+1

And also add the ability to copy the content from the watch node to clipboard with ctrl+c

**Comment by smangarole** [comment]
Thanks guys for your input. We added these requests to our backlog.
