### ISSUE TITLE
DynamoSamples-0.9.0

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/Dynamo#5821]
Having some trouble updating my dlls to version 0.9.0 I wanted to have a look at the samples. They are now separate. But I can't get them to work. In the pkg.json file it says "engine_version":"0.8.2". Shouldn't that be "0.9.0". 

In the readme.md file it says:"The `dynamo_package` folder at the root of the repository will now have the built libraries. The `Dynamo Samples` folder in that directory can be copied directly to your Dynamo packages directory:`C:\Users\<you>\AppData\Roaming\Dynamo\0.8\packages`.
- Run Dynamo. You should find SampleLibraryUI and SampleLibraryZeroTouch categories in your library." Shouldn't that be "...\0.9..."

**Comment by alfarok** [comment]
Dynamo Samples are up to date with the current Dynamo version (1.3), I am closing this issue
