### ISSUE TITLE
My program (dynamo9.0) often collapse, and version 0.82, there is no problem

### ISSUE THREAD

**Issue by lcwewei** [DynamoDS/Dynamo#5826]
The input argument "materialId" of function `anonymous-namespace'::TessellatedFace_constructor or one item in the collection is null at line 89 of file d:\ship\2016_px64\source\foundation\geomutilapi\gensrc\APITessellatedShapeBuilderProxy.cpp.
Parameter name: materialId

   在 ?A0x3826548e.TessellatedFaceProxy_constructor(IList`1 outerLoopVertices, ElementId materialId)
   在 Autodesk.Revit.DB.TessellatedFace..ctor(IList`1 outerLoopVertices, ElementId materialId)
   在 Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Surface srf, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   在 Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   在 Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   在 System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   在 Dynamo.Models.NodeModel.UpdateValueCore(UpdateValueParams updateValueParams)
   在 Dynamo.Models.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   在 Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   在 Dynamo.ViewModels.NodeViewModel.ToggleIsVisible(Object parameter)
   在 System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
for now, try disabling the revit background preview, I'm assuming you are not running the in english?
