### ISSUE TITLE
Code Block Input port issue

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5862]
Ver: 0.9.1.3503
OS: Win 7

![20151219-1](https://cloud.githubusercontent.com/assets/5621624/11910981/75ca16b2-a62d-11e5-9a27-95a06516e2ab.png)

**Comment by kronz** [comment]
![2016-01-01_2306](https://cloud.githubusercontent.com/assets/3456818/12073177/552dcd9a-b0dc-11e5-87f2-ffa3419920ae.png)
