### ISSUE TITLE
Crash when extruding in 0.9.0 or upper

### ISSUE THREAD

**Issue by Kosmos3D** [DynamoDS/Dynamo#5864]
here the details. I have italian version of Revit 2016 x64.

The input argument "materialId" of function `anonymous-namespace'::TessellatedFace_constructor or one item in the collection is null at line 89 of file d:\ship\2016_px64\source\foundation\geomutilapi\gensrc\APITessellatedShapeBuilderProxy.cpp.
Parameter name: materialId

   in ?A0x3826548e.TessellatedFaceProxy_constructor(IList`1 outerLoopVertices, ElementId materialId)
   in Autodesk.Revit.DB.TessellatedFace..ctor(IList`1 outerLoopVertices, ElementId materialId)
   in Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Solid solid, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   in Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   in Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in Dynamo.Models.HomeWorkspaceModel.Run()
   in Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   in System.Windows.Controls.Button.OnClick()
   in System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   in System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   in System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   in System.Windows.Input.InputManager.ProcessStagingArea()
   in System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   in System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   in System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

and here the screen:

![2015-12-19_193803](https://cloud.githubusercontent.com/assets/16364492/11914759/3f3e28bc-a688-11e5-839b-09b31cc7c75b.jpg)

**Comment by mjkkirschner** [comment]
@jnealb is this tracked? It's the default material naming issue in localized Revit.

@Kosmos3D - turn off the revit background preview as a workaround - I think that will avoid the crash.

**Comment by Kosmos3D** [comment]
Perfect. Stopping revit preview worked succesfully. I tought materialId localization issue...
Thank you so much :-)
