### ISSUE TITLE
No Undo for creating a custom node from selection

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5881]
It would be great to be able to undo the creation of a custom node - not the deletion of the created dyf file, but restoring the graph to its previous state.
Dynamo 0.9 stable

**Comment by kronz** [comment]
@andydandy74 not sure what you mean.  I can do this right now:  
- make some nodes
- select and create custom node
- undo (tab for custom node remains, home workspace now has original nodes)

**Comment by monikaprabhu** [comment]
@andydandy74 - as Zach mentioned , we cannot see a case where undo is not available after creation of custom nodes using selection. I've tested on both 0.9.0/0.9.1 with Revit and standalone. If you can still see the issue please reopen with the steps/details.
