### ISSUE TITLE
Small Wishes/Issues Collection

### ISSUE THREAD

**Issue by Arek3dim** [DynamoDS/Dynamo#5886]
I apologize beforehand if some of these are already there. I checked as hard as I could.
I also want to let you know that I'm really not trying to be very demanding, simply reporting what I think would make Dynamo more amazing.

Wishes:
Split Surface for Topography
Ability to create multiple links instantly
Delete Input function (selected model gets replaced by the Dynamo output)
Select EdgeS(being able to select multiple edges from Revit)
Add to group/Remove from group function

Issues: Again, apologies if some of these are known, didn't find them in the list.
When I have some components selected, holding shift will add to the selection, but not when you drag and shift. Dragging deselects previous selections (even with Shift held).
Turning off the preview for multiple components can be a tedious task, once one has selected multiple components, turning off the preview will affect only one of them.

Thanks lots guys! Keep your head up with the outstanding work, and please let me know if my requests are valid. Best regards.

**Comment by kronz** [comment]
Hi @Arek3dim 
Thanks for the suggestions.  Couple things:

Split Surface for Topography:  
- Do you mean cutting a surface at a repeated increment?  
Ability to create multiple links instantly:  
- say a little more of what you mean?
Delete Input function (selected model gets replaced by the Dynamo output):  
- You mean for example that you pick a Family in Revit and replace it with a  specified family?
Add to group/Remove from group function:  
- you can currently add a node to a group (select the group and the new node, right click on the new node, "Add to group".)

Turning off the preview for multiple components can be a tedious task, once one has selected multiple components, turning off the preview will affect only one of them.  
- Multiple element preview on/off works, you need to select multiple items and right click in the empty canvas, not on a specific node

**Comment by Arek3dim** [comment]
Hello @kronz,
Thanks for the reply. Here we go:

Split Surface for Topography:
* I mean having a node that "splits" the topography into seperate/multiple elements, like the Revit topography function "split surface" in massing & site, having it in Dynamo will help create better topo-related scripts. moreover, having "merge surfaces" (again, same function as Revit) would be great too, but so far we can do that by taking points from all topos, pruning duplicates and create a new one. Cutting the surface at a repeated increment could come as a Dynamo bonus, since we could only split a topo into two parts in Revit, splitting at repeated increment or into multiple parts with different lines or planes would be awesome as well.

Ability to create multiple links instantly:
* We can only create links in Revit repeating the same process over and over again, having a function that creates links from multiple paths or every file in a folder would be awesome and save us a lot of time. This is more useful when creating .SAT links than establishing .RVT links, but still, I think it adds to efficiency in my view.

Delete input function:
* I mean, for example, I had a script that you "select model element" in the beginning, it happened to be a topo, and then at the end of the script, I created a new topo. It was an "attach to face" algorithm. Now I have two topo's in Revit, the new one and the old one. Would be sufficient to have the possibility of getting old one deleted and replaced by the new one Dynamo. Not necessarily a family. Not necessarily a topo of course.
 
Thanks for the tips on groups and multiple node preview on/off and every-great-thing else.

Oh, and happy new year btw! :)
Arek

**Comment by andydandy74** [comment]
@Arek3dim - For deleting Revit elements you could use ```Tool.Eraser``` from package ```SteamNodes``` by @jbenoit44 or ```Doc.DeleteElements``` from package ```SpringNodes``` by @dimven .

**Comment by Arek3dim** [comment]
Thanks for letting me know @andydandy74, even though this wasn't the place for it :)

**Comment by Arek3dim** [comment]
@andydandy74 Thanks for the info. Doc.DeleteElements did the job better for me, since it seems to delete the element after the data has passed to other node, which could act as a "delete input and replace by the result" function. Tool.Eraser deletes the element and the rest of the script doesn't run anymore. I'm working with the example mentioned above: The input topo gets deleted and replaced with the resulting topo.
Thanks again!

**Comment by Arek3dim** [comment]
To summarize, I guess that leaves us only with these to wish for:
Split Surface for Topography node
Ability to create multiple links instantly
Select EdgeS node (I personally think this is the most important)
Holding shift and dragging to add to node selection

I can seriously never thank you enough. cheers!
