### ISSUE TITLE
How to get reference to  UIDocument/Document

### ISSUE THREAD

**Issue by Playm** [DynamoDS/Dynamo#5897]
I want to implement my own FilteredElementCollector in my ZeroTouchPackage. And for that I need a reference to the active document so that I can use Revit API. What should I do ?

**Comment by HasanAyan** [comment]
This question was asked by me (another account). I think I found my answer. In RevitServices.dll, ```RevitServices.Persistence.DocumentManager``` class has the properties I want (```CurrentUIDocument``` etc) but I did not test the usability. If I am right, this issue can be closed.

**Comment by ksobon** [comment]
That will work. I agree. You can close it.
