### ISSUE TITLE
3D Watch and Background Preview in 0.9.* are broken in Windows 10

### ISSUE THREAD

**Issue by epsilonite** [DynamoDS/Dynamo#5905]
3D Watch and Background Preview are broken;
Revit Background Preview still works;

error in Watch 3D window: 
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at HelixToolkit.Wpf.SharpDX.RenderContext.set_Camera (Camera value)
>   at HelixToolkit.Wpf.SharpDX.Viewport3DX.HelixToolkit.Wpf.SharpDX.IRenderer.Render (RenderContext context)
>   at HelixToolkit.Wpf.SharpDX.DPFCanvas.Render()
>   at HelixToolkit.Wpf.SharpDX.DPFCanvas.UpdateAndRender()

**Comment by jnealb** [comment]
@epsilonite What version of Dynamo are you running?

**Comment by epsilonite** [comment]
0.9.1.3567

**Comment by epsilonite** [comment]
was running stable release of 0.9.0 before upgrading to the latest build

**Comment by othiele** [comment]
I'm experiencing the same issue with the standalone Dynamo Studio 0.9.0.3072.
[DxDiag.txt](https://github.com/DynamoDS/Dynamo/files/117686/DxDiag.txt)

**Comment by othiele** [comment]
Found a solution for my problem: Had SLI deactivated. I'm running two Nvidia GeForce GTX 560 Ti. Enabling SLI solved my problem.

**Comment by jnealb** [comment]
@othiele @epsilonite Please check out the Dynamo Forum or the Read Me on Github, we think we understand why some Win10 configurations (those with graphics cards that work with Win7 or 8) have this issue. Here is a clarifying thread:

https://github.com/helix-toolkit/helix-toolkit/issues/257#issuecomment-194145932

We are working towards a solution.

**Comment by ralvarez76** [comment]
This was an issue on my Windows 10 machine running two GEFORCE cards. I had set these up without SLI because it causes performance degradation on some 3d applications. I found that if I installed the SLI bridge and enabled it, the 3d preview works in Dynamo.

**Comment by jnealb** [comment]
Thanks for the update

**Comment by Crashnorun** [comment]
Hi All.
I'm running into the same issue. Dynamo (standalone) doesn't have a graphic preview in the background nor in the 3d watch panel. But when I run dynamo through revit 2016, it works fine. I'm running dynamo 0.9.2.4472 (latest version to date).
I'm running a dell xps, win 10
[DxDiag.txt](https://github.com/DynamoDS/Dynamo/files/198238/DxDiag.txt)

**Comment by Crashnorun** [comment]
Fixed the issue. See Andrew Heumann's comment about the NVIDIA control panel.
