### ISSUE TITLE
Bug-reporting UX

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5909]
It would be nice if 
a) the `Submit Bug To GitHub` button were to **copy the reported error to the clipboard** and
b) **open this URL**: https://github.com/DynamoDS/Dynamo/issues/new
![capture](https://cloud.githubusercontent.com/assets/3014437/12112020/0389f322-b39a-11e5-8b23-c6edd10f47d8.PNG)
(I know I can manually copy the error msg but I keep forgetting and hitting that button before doing so...)
Dynamo 0.9 stable

**Comment by Racel** [comment]
@mjkkirschner - I am going to add this to the UX Love backlog, but would like your opinion on how difficult/easy this would be to implement. Need to understand so we can prioritize appropriately.

**Comment by ramramps** [comment]
@Racel I  think this is not too complex. Should be straight forward.

**Comment by Racel** [comment]
Thanks @ramramps - Will probably try and prioritize this higher in the UX Love backlog as I think it might be easy to fix with high reward.

**Comment by Racel** [comment]
@andydandy74 - After discussing with the team, we feel like we will not be able to do this in the near term due to other priorities (web UI and other more pressing bugs/UX fixes). We will revisit again in the future.

**Comment by radumg** [comment]
Had a different idea to fix this : pre-fill a new (empty) issue on the Github repo with the crash text, no copy-pasting required.

See an example implementation in #9150 @andydandy74 @Racel
