### ISSUE TITLE
No migration for GroupByKey (0.9.0 > 0.9.1)

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5912]
A ```GroupByKey``` node placed in 0.9.0 is not correctly resolved to ```List.GroupByKey``` in 0.9.1 - instead it shows up as deprecated.
Dynamo 0.9.1.3686

**Comment by jnealb** [comment]
@andydandy74 Thanks - tracked with MAGN-9296.

**Comment by jnealb** [comment]
@andydandy74 We think this is fixed with dailies >= 1/8/2016
