### ISSUE TITLE
Number From Feet and Inches changes displayed input

### ISSUE THREAD

**Issue by sixtysecondrevit** [DynamoDS/Dynamo#5914]
Number from feet and inches modifies the user input to a different value. Revit recognizes the correct value but it is confusing. Discussed here http://dynamobim.org/forums/topic/number-from-feet-and-inches-problem/#post-35720
![numberbug](https://cloud.githubusercontent.com/assets/15744724/12155985/7efda2ce-b485-11e5-991f-44cba4358642.gif)

**Comment by kronz** [comment]
@sixtysecondrevit , what is your expectation for the behavior?  It looks correct to me
![2016-01-13_1627](https://cloud.githubusercontent.com/assets/3456818/12344760/da0caec8-bb0e-11e5-80b3-12d7d5a94a76.png)

**Comment by sixtysecondrevit** [comment]
The problem occurs when a user types in a number at 3/32 or smaller. The
node changes the display to show a different value. The output is right but
the display changing throws people off. I hope that makes sense.

**Comment by ke-yu** [comment]
Fixed in PR #6905
