### ISSUE TITLE
DynamoInstall0.9.1.20160106T2144 Can't pull out a connector???

### ISSUE THREAD

**Issue by jonathanroy8676** [DynamoDS/Dynamo#5919]
Ever since I installed the latest version I can't pull out connectors from the ports. It just starts opening a cross selection window???  

DynamoInstall0.9.1.20160106T2144

![dynamoinstall0 9 1 20160106t2144_connectorpull](https://cloud.githubusercontent.com/assets/16231080/12178917/238b23a4-b542-11e5-9a64-7d737d08114f.png)

**Comment by jonathanroy8676** [comment]
Revit 2016.
Uninstalled 9.1.2 and reinstalled 9.0 
The multiple versions (0.7.5, 0.8.2 and 0.9.0 are back since they disappeared with the 0.9.1.2
.Connector pull works on first try...

![image](https://cloud.githubusercontent.com/assets/16231080/12179163/42c69586-b543-11e5-978c-c7e286219b50.png)

**Comment by jnealb** [comment]
@jonathanroy8676 Thanks - this is tracked with MAGN-9306 and will be fixed soon.

**Comment by jnealb** [comment]
@jonathanroy8676 This is fixed and will be available in the dailies >= 1/8/2016

**Comment by jonathanroy8676** [comment]
Was I supposed to close the issue after I was notified it had been fixed? This is my first post on github that I'm not familiar with protocole.
Thanks
