### ISSUE TITLE
Suggestion for Tutorial 8.4 Dynamo for Revit/Creating

### ISSUE THREAD

**Issue by angelthrone** [DynamoDS/Dynamo#5927]
Hi and first of all, thank you a LOT for that awesome and wonderfully organized tutorial for us newbies to learn Dynamo!
Now to the question, on one of the last nodes qhen creating the truss for the Revit fassade, we need to transpose the list in order to get from 3x10 to 10x3. My question is, if we swap the node connectors a few nodes earlier when we do the Gemoetry.Intersect and plug in List.Create to "entity" and Curve.PlaneAtParameter to "geometry" instead, wouldn't the transpose not be necessary anymore?
I have done so at it seemed to work. Was I lucky to find a shortcut or instead did I have a sheer luck that it somehow worked this time when it's actually an aberration? 

Benjamin
a recently started dynamo user from Spain

![capture_creating_01](https://cloud.githubusercontent.com/assets/16611314/12200539/af752e9a-b61f-11e5-9d40-686e5c8f501d.png)
![capture_creating_02](https://cloud.githubusercontent.com/assets/16611314/12200540/af845cda-b61f-11e5-9add-fe43e3e067d1.png)
![capture_creating_03](https://cloud.githubusercontent.com/assets/16611314/12200541/af89c300-b61f-11e5-90ab-9e80d40cd563.png)

**Comment by ikeough** [comment]
We really appreciate this conversation, but we're trying to move conversations to the forum. Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/)
