### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Mark-Drotar** [DynamoDS/Dynamo#5930]
Dynamo 0.9.0
Windows 7
See attached for files

I'm working on a tutorial and I've created many connections (that could be part of the issue but it works until I change a connection). Either way, I create what I want to and then I get curious how other nodes would change the structure because the current connection looks complicated and I think I could simplify it to get the same result. I remove two nodes and two previous connections to insert one node and try to run it. Dynamo thinks for a few second and then acts as if it completed the run except it didn't. 

The run looks successful based on the button but nothing changes from then on. I can go into the geometry view and rotate and pan. I can go back into the node view and add nodes and alter connections. I can even save. However, nothing will change no matter what connections I alter. Trying to close the program does nothing and I eventually have to end task.

I understand I may not be able to do what I was trying to do but I thought it would give me an error box above the nodes like it normally does instead of freezing without really freezing.

[Dynamo Error.zip](https://github.com/DynamoDS/Dynamo/files/83298/Dynamo.Error.zip)

**Comment by jnealb** [comment]
Thank you @Mark-Drotar - we are seeing your issue and investigating.

**Comment by ikeough** [comment]
Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/)
