### ISSUE TITLE
Accidentally removed default packages from Dynamo whilst trying to install new packages 

### ISSUE THREAD

**Issue by jeanluc01** [DynamoDS/Dynamo#5934]
Hey Guys and Girls,

I am a Dynamo n00b and decided it would be a smart idea installing all of these packages without realizing that I needed the core revit features which comes as a default package in Dynamo. Is there an easy way to get it back or a package on the server I can download for it?

Kind regards,

Jean-Luc

**Comment by andydandy74** [comment]
Maybe you were using the DynamoSandbox.exe? The Revit nodes will only be available when using Dynamo as a Revit plugin.

**Comment by jeanluc01** [comment]
Hey Andy, yep I have just figured out what the issue was. Like how you said the Revit feature will only be available from within Revit. Thank you for the quick response though I appreciate it :).
