### ISSUE TITLE
Request - Node Browsing, Organization, Visual?

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#594]
A workshop comment that I thought was super relevant....  "The interface doesn't really allow for us to explore different nodes.  How do new users know what to search for?  How can we browse?"

The comment came in contrast Grasshopper's icon-based menus are super useful for browsing and seeing what's there at a glance without having to expand trees, etc.

Something to think about...

-Nate

**Comment by Racel** [comment]
We have plans to work on search in the near future, and improve UX/UI of using the correct nodes. But, as there are not specific guidelines in this issue, closing for now.
