### ISSUE TITLE
Python Dll Error - Errno 2

### ISSUE THREAD

**Issue by brencass** [DynamoDS/Dynamo#5944]
I am importing 5 dll’s into a python node but one is causing a Errno 2 issue(see below image), this error effects dynamo 0.8.2/0.9.0 and 2015 and 2016 versions of the dll. I have a sneaky feeling it is the dll that is a issue but thought i would post to the dynamo team in case it is a dynamo issue. 

The dll is from civil 3d vanilla install and I followed instructions from the civil 3d autodesk developer network for the correct dll's.

![dll-error](https://cloud.githubusercontent.com/assets/14090637/12260110/bb0fefd4-b911-11e5-8cd9-3c9f339806e2.png)

**Comment by ikeough** [comment]
Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/)
