### ISSUE TITLE
Node Attributes not work for ZeroTouch nodes

### ISSUE THREAD

**Issue by luxliber** [DynamoDS/Dynamo#5947]
Hi all!

I am creating ZeroTouch library and i know that Dynamo assign last Node Category part (Create, Action or Query) automatically (for properties it`s "Query", for constructors and static methods returns class instance it`s "Create") and for other methods it`s "Action".

I also know that we can assign category for UI nodes manually with [NodeCategory] attribute.

But this attribute (like other node attributes) don`t work with ZeroTouch class elements.

I would like to assign category manually for some nodes.
For example,  Move ViewName method to Query category because i have not ability for making property:
    
    namespace Prorubim.Common
    {
       public class View
       {
            [NodeCategory ("Prorubim.View.ViewName.Query")]
            public static string ViewName(Revit.Elements.Views.View view)
            {
                var uv = view.InternalElement as Autodesk.Revit.DB.View;
                return uv == null ? null : uv.ViewName;
            }
        }
    }

**Comment by mjkkirschner** [comment]
@luxliber have you seen the customization xml files, https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodes/DSCoreNodes_DynamoCustomization.xml

I'm not sure it would handle the case you are interested in but worth looking at.

**Comment by luxliber** [comment]
@mjkkirschner Yes, I use customisation xml files too.But its solve some different goal.

Xml files allow to assign root category path for ZeroTouch class and don`t provide ability for setting subcategory for class methods and properties.

I`ve created pull request about this issue.  See #5956

**Comment by ikeough** [comment]
PR merged!
