### ISSUE TITLE
A question about the license and rights

### ISSUE THREAD

**Issue by HasanAyan** [DynamoDS/Dynamo#5953]
I could not find any info on licensing of Dynamo. Can sell add-ins I created using Dynamo or some part of it (i.e. ProtoGeometry library)?

**Comment by kronz** [comment]
Hi @HasanAyan 
You can find all the licensing information here:
https://github.com/DynamoDS/Dynamo/blob/master/LICENSE.txt
Also in the Readme.
Dynamo itself is under Apache 2.0, which allows for most kinds of derivative work uses, including commercial.  Read more about Apache 2.0 here:
http://www.apache.org/licenses/LICENSE-2.0

Thanks!
