### ISSUE TITLE
WISH: Conditionally close down part of script

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#5962]
Hi,
i have a script where back runs only at certain conditions otherwise it recieves no data. i would like to close down that nodes with booelan input to prevent them from turning orange. i want to pass this further to other colleagues and be sure no warnings will appear.

if (true)
{
lot of nodes and functions
}

thanks

![skarmklipp](https://cloud.githubusercontent.com/assets/4834544/12354549/11f08df4-bb97-11e5-8f91-0b577d11638f.PNG)

**Comment by ikeough** [comment]
I'm closing this issue as the requested functionality is now available in recent builds as frozen nodes.
