### ISSUE TITLE
Same nodes 2 times available

### ISSUE THREAD

**Issue by Thomas84** [DynamoDS/Dynamo#5965]
vers. 1.0.0.105

the icons are different but anything else is same? 

Geometry[] means more than one? so the node name should be ByGeometriesCoordinateSystem ?

![17 01](https://cloud.githubusercontent.com/assets/5624034/12379040/b97f1aac-bd51-11e5-9508-a620671c0a1e.png)

**Comment by dimven** [comment]
One of those selects single objects, while the other selects lists. I suggest the ones with list inputs are renamed to *.ByGeometires.
![dynamosandbox_2016-01-19_12-02-00](https://cloud.githubusercontent.com/assets/7148394/12409370/56c0c2d6-bea4-11e5-88d6-6ced5d78e208.png)

**Comment by smangarole** [comment]
@Thomas84 This does not seem to be an issue in Dynamo 1.3. Can you please confirm? If it's still an issue, please re-open.
