### ISSUE TITLE
a polycurve question

### ISSUE THREAD

**Issue by lzeaf** [DynamoDS/Dynamo#5972]
when I join lines to polycurve,it can't offset on plane xy, it go to Z vector.
when I offset polycurve,it trans to a curve ， I can't break it to lines or linelikecurves.

Aaaaaaaaaaaaaaaa！

**Comment by kronz** [comment]
@lzeaf Can you say a little more about what you are doing?  Your situation does not reproduce for me, see attached:
![2016-01-20_0636](https://cloud.githubusercontent.com/assets/3456818/12447849/42191e2c-bf40-11e5-97a6-9911ee6b5db2.png)

**Comment by lzeaf** [comment]
when I offset 1 line ，it can‘t offset to xy-plane， it to z vector

**Comment by lzeaf** [comment]
my line was selected from  revit

**Comment by kronz** [comment]
this is offsetting a single line?  Sounds like the plane it's associated with is not xy

**Comment by lzeaf** [comment]
so if len(myline) == 1,I draw a arc join with my line then offset---break---get my line。。。
