### ISSUE TITLE
Random List of lists

### ISSUE THREAD

**Issue by nreifenstein** [DynamoDS/Dynamo#5977]
I want to create a series of lists, each of which has a random selection of elements. In other words, N lists of M elements each. The attached graph seems like it should work, mapping the list.shuffle function over a list of lists. However, it appears to be randomizing each sublist exactly the same way. Not useful. Shouldn't mapping the shuffle function create a different sublist each time?
![random_lists](https://cloud.githubusercontent.com/assets/4603600/12425776/3f5aad96-be8b-11e5-8bfa-329f5fe5255e.png)

**Comment by ikeough** [comment]
Please post this question to the [Dynamo forums](http://dynamobim.org/forums/forum/dyn/)
