### ISSUE TITLE
Dynamo behavior on loading corrupted .dyn file is poor

### ISSUE THREAD

**Issue by oderby** [DynamoDS/Dynamo#5980]
When attempting to load a "corrupted" .dyn file (see attached) in Dynamo 0.9.0 from the home/start screen, it appears to silently fail and sit there doing nothing. When I open a blank document (or any other valid document) and look back through the console, I see the following error:

```
Error opening file: Object reference not set to an instance of an object.
System.NullReferenceException:
Object reference not set to an instance of an object.
   at Dynamo.Models.AnnotationModel.set_SelectedModels(IEnumerable`1 value)
   at Dynamo.Models.AnnotationModel.DeserializeCore(XmlElement element, SaveContext context)
   at Dynamo.Core.NodeGraph.LoadAnnotationFromXml(XmlNode annotation, IEnumerable`1 nodes, IEnumerable`1 notes)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Core.NodeGraph.LoadGraphFromXml(XmlDocument xmlDoc, NodeFactory nodeFactory)
   at Dynamo.Models.DynamoModel.OpenHomeWorkspace(XmlDocument xmlDoc, WorkspaceInfo workspaceInfo, WorkspaceModel& workspace)
   at Dynamo.Models.DynamoModel.OpenFile(WorkspaceInfo workspaceInfo, XmlDocument xmlDoc, WorkspaceModel& workspace)
   at Dynamo.Models.DynamoModel.OpenFileFromPath(String xmlPath, Boolean forceManualExecutionMode)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.DynamoViewModel.Open(Object parameters)
```

The problem seems to be when a Dynamo.Models.ConnectorModel element references a non-existent model. Now, I manually created this corrupted file, to illustrate the case, but we have a much more complicated graph which exhibits the exact same behavior, and has 4 missing nodes in a similar annotation (group) element, and was somehow generated through normal use.

I would expect dynamo to throw a warning about invalid/missing elements in a group and continue loading the file.

Other information: Windows 7.1, Dynamo 0.9.0

``` xml
<Workspace Version="0.9.0.3067" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSCoreNodesUI.CreateList guid="76bb5d0e-2e2a-47ab-bd33-a55d5faae548" type="DSCoreNodesUI.CreateList" nickname="List.Create" x="6902.61967886708" y="1620.34731362718" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2" />
    <Dynamo.Nodes.DoubleInput guid="c37a45c5-14e4-4b90-8c7e-ad37cf60c99b" type="Dynamo.Nodes.DoubleInput" nickname="Number" x="6560.21967886708" y="1617.54731362718" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Double value="0" />
    </Dynamo.Nodes.DoubleInput>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="c37a45c5-14e4-4b90-8c7e-ad37cf60c99b" start_index="0" end="76bb5d0e-2e2a-47ab-bd33-a55d5faae548" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c37a45c5-14e4-4b90-8c7e-ad37cf60c99b" start_index="0" end="76bb5d0e-2e2a-47ab-bd33-a55d5faae548" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="69b3a48c-3bf5-4c6c-8b81-91718bd1a8c4" annotationText="&lt;Click here to edit the group title&gt;" left="6550.21967886708" top="1587.54731362718" width="489.600000000001" height="237" fontSize="14" InitialTop="1617.54731362718" InitialHeight="237" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="76bb5d0e-2e2a-47ab-bd33-a55d5faae548" />
      <Models ModelGuid="c37a45c5-14e4-4b90-8c7e-ad37cf60c99b" />
      <Models ModelGuid="401948c9-3644-42ea-b18e-9d89b339443f" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>
```

**Comment by kronz** [comment]
Taking a quick poke at this file, it opens if the group is removed (which fits with what was said above, I think).  That is, delete this section between <Notes /> and <Presets /> and the file is happy.  FYI @ramramps :

  <Annotations>
    <Dynamo.Models.AnnotationModel guid="69b3a48c-3bf5-4c6c-8b81-91718bd1a8c4" annotationText="&lt;Click here to edit the group title&gt;" left="6550.21967886708" top="1587.54731362718" width="489.600000000001" height="237" fontSize="14" InitialTop="1617.54731362718" InitialHeight="237" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="76bb5d0e-2e2a-47ab-bd33-a55d5faae548" />
      <Models ModelGuid="c37a45c5-14e4-4b90-8c7e-ad37cf60c99b" />
      <Models ModelGuid="401948c9-3644-42ea-b18e-9d89b339443f" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>

**Comment by oderby** [comment]
Yep, that was my workaround. Alternatively, you can just remove the `<Models ModelGuid="401948c9-3644-42ea-b18e-9d89b339443f" />` entry from the annotation and everything should be happy then too (and you keep your group).

But the point is Dynamo should be able to make that determination itself and warn the user, and not fail on loading the entire file as a result.

**Comment by johnpierson** [comment]
Working as expected on Dynamo 1.3.3 and up
