### ISSUE TITLE
DateTime.Now does not re-execute

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5994]
I would expect ```DateTime.Now``` to always re-execute whenever a graph is re-run.
Time does move on, doesn't it?
(Of course, it shouldn't *trigger* a re-run in automatic mode...)

**Comment by kronz** [comment]
Filed as http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9547

**Comment by ikeough** [comment]
Internal issue has been closed.
