### ISSUE TITLE
Dynamo 0.91 UI suggestions

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#6006]
First of all, I really like the direction in which 0.91 is going. A ton of things have been changed and added to greatly improve usability. 
However some of the UI changes seem to have been implemented only partially. I was waiting to see if the stable build would develop things further and now with the RC out, I have a few small suggestions:

![revit_2016-01-24_10-43-08](https://cloud.githubusercontent.com/assets/7148394/12534318/0d69826a-c28e-11e5-92ca-6eaa1dc15c3a.png)
- The watch node:
  - Why does it need a node preview toggle? Are there any plans to remove it in the following releases?
  -  It would be a good idea to make the element Ids pop out and look more like buttons, so that people know they can be selected to zoom to the element inside the Revit UI.
  - You might need to change the colour of the text inside the watch node to make it more contrasting to the background.
  - Making the watch node expandable seems to be a popular request.
- Generic Nodes:
  - With the preview toggle moved outside of the node, we're left with quite a lot of empty space at the base of the node.
  - Are there any plans to make the lacing switch a floating toggle? (Similar to the preview toggle).
  - If not, I suggest moving it to the centre of the node to make it a predominant part of the node, mainly because node lacing can have a dramatic effect on the outcome of the whole graph.
  - Alternatively you could move the lacing switch to the title of the node. (or somewhere else?)

Right now the new toggle can get obstructed by other nodes. If the same is implemented for lacing, you should definitely make it so that the toggle is always visible and does not become obstructed by other nodes. Otherwise graph comprehension might suffer:

![revit_2016-01-24_11-43-33](https://cloud.githubusercontent.com/assets/7148394/12534353/3635231e-c290-11e5-871d-af7fc370da07.png)

Here's a quick sketch for the lacing suggestion:

![revit_2016-01-24_11-48-22](https://cloud.githubusercontent.com/assets/7148394/12534371/b7823f6e-c291-11e5-962d-dabc767ec0b0.png)

@RodRecker  @Racel

**Comment by Racel** [comment]
@dimven - Thanks for the great suggestions! We are still working on making all the changes to the updated preview bubble interactions and will likely be making tweaks/additions over the next few releases.

Thanks for reminding us of the watch node preview bubble issue. I went ahead and filed that in our backlog and our team will try to work on it ASAP. We also will be working on making the preview bubble expandable in future releases and making changes to how users view and select content inside the watch node/preview bubbles (which may address some of the concerns you mentioned above). More soon.

Regarding the lacing icon and remaining empty space, we are playing around with some new designs for this including a lacing toggle. But, I really like your last sketch as it ensures that lacing is discoverable. Please keep the comments coming as we are looking to improve the preview bubble/watch node functionality/interactions as they are the key to understanding what your graph is doing.  We really appreciate your feedback/thoughts and hope to hear more soon.

**Comment by andydandy74** [comment]
I think I'd rather see a row of icons above the node title instead of in the node body itself, because I'm afraid that placing an icon inside the node will not work in all cases (think UI nodes).
Possible candidates besides Lacing:
- Freeze node (active/inactive)
- Show geometry preview (active/inactive)
- Preview Upstream (active/inactive)
- Show labels (active/inactive)

I absolutely agre with @dimven that Lacing should be more visible. And so should these other node properties. Context menus are quite expensive in terms of the number of clicks you have to do during the day.

Regarding the IDs: I'd rather not see them become three-dimensional. Two things that would really make me happy, though: find another colour (this has got to be one of the ugliest greens available in RGB, it makes me think of mint chocolate) and then go find a second colour for the hover effect (and drop the current resize effect).

**Comment by ksobon** [comment]
@dimven so we are at Dynamo 2.0 and none of these were implemented. Can we agree that it won't happen? Hahaha. Let me know if you STILL think these are important updates, and should still be considered. If not, can we close this issue? 

@Racel it's all right to tell people straight up that some things will not happen. I am all for being upfront and open about the direction of the software that its heading in. You are the "head of UI", so feel free to reject these suggestions and close this issue. We won't get offended. I promise. 

Cheers!

**Comment by Racel** [comment]
@ksobon @dimven - As you may know, we are currently working on the next generation UI/UX of Dynamo and some of the features mentioned above have/are being considered. It is unlikely that what we are working on will be released for production in 2.0, but just know that the thoughts/ideas in here will likely show up in the newer UI. 

I see that @dimven has already closed this issue for now and that is fine with me as we are aware and considering these suggestions already.
