### ISSUE TITLE
Wish: Always show expandable slider UI on top

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6030]
Currently, nodes seem to stack on top of each other in the order they were placed on canvas - which is fine, I suppose. In the case of sliders this can be a bit annoying, though. I would like the expandable UI of the slider node to always be on top of every other node on canvas.
Current behaviour (nodes stacking in order of placement):
![1](https://cloud.githubusercontent.com/assets/3014437/12641074/d38cddd0-c5ad-11e5-8f74-415620997c24.PNG)
If you move the second slider above the first, you get this:
![2](https://cloud.githubusercontent.com/assets/3014437/12641096/f13f5920-c5ad-11e5-918c-7f59c6e8a476.PNG)
Dynamo 0.9 stable

**Comment by Racel** [comment]
@andydandy74 - You can choose the view order of nodes permanently by clicking on whichever one you want to bring to the top. I believe this was added after 1.0. Let me know if I did not understand correctly. If this fix is ok, please close this issue.

I did, however, find a bug related to this request. When you hover over a node for 500ms, that node should be brought to the top of the view order temporarily. This is not working properly with number sliders. So, I will file a task for that.

**Comment by andydandy74** [comment]
Great, @Racel . This is indeed resolved.
