### ISSUE TITLE
0.8.2.2392 Autosave Frequency

### ISSUE THREAD

**Issue by BrianFraumeni** [DynamoDS/Dynamo#6059]
Having an issue where save times are close to a minute (after graph has been executed), and Dynamo v 0.8.2.2392 running as a R14 add-in is autosaving every minute and /or on some other unknown queue or interval. I am essentially unable to work. Does anyone have any experience with this issue or insight on this? Is there a way to control autosave frequency? Is there a way to disable autosave.

Thanks

**Comment by RodRecker** [comment]
@BrianFraumeni Hi Brian - any chance you can upgrade to a newer version of Dynamo?

**Comment by BrianFraumeni** [comment]
@RodRecker Thanks for replying - need to deliver in Revit 2014...

**Comment by BrianFraumeni** [comment]
a fix, make the following change in file:

%AppData%/Dynamo/<version number>/DynamoSettings.xml
(<version number> 0.7, 0.8, 0.9 , based on which build you want to modify)

Original code in xml:
<BackupInterval>60000</BackupInterval>

60000 = 60000ms (1 minute). 
Increase the number to decrease backup frequency i.e. …>30000<… for a 5 minute interval

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
