### ISSUE TITLE
Wish for node browser: Constrain search to single category or package

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6066]
EDIT: Since the original request has already been realized in current daily builds, the topic of this wish list item has changed. See @mostaphaRoudsari 's comment below.
~~Sometimes we just want to find stuff within one category or one package when searching in the node browser. The category/package filter has been a great usability improvement, but it would be even nicer if we could right-click on any one of the listed categories/packages in the filter in order to isolate that single category/package and hide/disable all other categories/packages. 
(When you have lots of packages installed it may take a lot of time disabling stuff in the filter.)~~
![unbenannt](https://cloud.githubusercontent.com/assets/3014437/12776220/88ae1472-ca54-11e5-9cf5-256448516811.PNG)

CC @Racel

**Comment by Racel** [comment]
Hi @andydandy74 - Thanks for your comment. Check out the daily builds. We have a way to do this now :) It will be released in the next stable release.

![image](https://cloud.githubusercontent.com/assets/2551261/12776506/738f3958-ca91-11e5-9ae2-2cb6f5d415ed.png)

**Comment by Racel** [comment]
Also, we have the ability to switch between compact and detailed view of the results so you can get rid of the description. 

![image](https://cloud.githubusercontent.com/assets/2551261/12776546/bc482d58-ca91-11e5-8013-02f3a97e7d00.png)

**Comment by andydandy74** [comment]
NICE! I really like the new look of the filter list.

**Comment by mostaphaRoudsari** [comment]
This is very nice but as a person who doesn't like to click - and I assume there are other users like me- is it possible to have a convention like ***libraryName::NodeName***

For instance if I'm looking for a node in Clockwork I can type ***Clockwork::*** and it will only show the nodes under Clockwork.

**Comment by RodRecker** [comment]
I like this @mostaphaRoudsari

**Comment by Racel** [comment]
@mostaphaRoudsari - great idea! I have this in our backlog of things to do.

**Comment by mostaphaRoudsari** [comment]
Thanks!

**Comment by andydandy74** [comment]
@mostaphaRoudsari - Great idea. I have renamed the issue accordingly and reopened it.

**Comment by kronz** [comment]
@mostaphaRoudsari @andydandy74 I think we already have this behavior, no?
![2016-02-10_2157_001](https://cloud.githubusercontent.com/assets/3456818/12968534/53903624-d041-11e5-8fed-21d5dde6fd05.png)
![2016-02-10_2157](https://cloud.githubusercontent.com/assets/3456818/12968535/5392450e-d041-11e5-91f1-14a1423e467f.png)

**Comment by andydandy74** [comment]
@kronz - Right you are. Never tried that. So easy.

**Comment by mostaphaRoudsari** [comment]
Hi @kronz! Is not exactly the same but I agree that it does the job. Here is an example Display will return nodes included the one under Display. As you can see there are nodes from Geometry and Core.

![image](https://cloud.githubusercontent.com/assets/2915573/13030963/abcbe618-d289-11e5-9eae-a22ed02fd7a6.png)
