### ISSUE TITLE
Strange concatenation behaviour when adding a variable to itself

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6067]
Since I have trouble explaining this in writing, I'll let the images speak (mostly) for themselves.
This is my initial graph, running in automatic mode:
![1](https://cloud.githubusercontent.com/assets/3014437/12788077/75286b5c-ca98-11e5-82f6-a3ca67249eba.PNG)
When manipulating a string in the code block, Dynamo rewards me with an extra line:
![2](https://cloud.githubusercontent.com/assets/3014437/12788098/8d4ad21a-ca98-11e5-882e-c1f2d3caf37a.PNG)
Expected result: Only line 1 and 3...
Dynamo 0.9 stable release

**Comment by RodRecker** [comment]
@andydandy74 If you exit Dynamo after the first graph, then restart and make the second graph, does it work as expected?

Also, any chance you can try this in the latest daily builds?

**Comment by andydandy74** [comment]
@RodRecker - only if I rebuild the graph from scratch.
I currently cannot use the daily builds as I am busy building a lot of new stuff for 0.9 - so there would be backward compatibility issues. But I was going to try to have a VM set up for testing our code in the daily builds anyway, so I could probably give some more feedback by the end of next week.

**Comment by andydandy74** [comment]
@RodRecker - just tested this in 1.0.0.910: same weird behaviour.

**Comment by sharadkjaiswal** [comment]
@ke-yu, does this issue ring a bell? I think I have seen something similar before.

**Comment by andydandy74** [comment]
Not relevant anymore, since variables are now immutable in 2.0
