### ISSUE TITLE
Zoom extents disregards notes

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6068]
Zoom extents only seems to work for no**d**es - no**t**es are ignored.
Expected behaviour: Zoom extents should show the graph in its entirety - including annotation elements.
Dynamo 0.9 stable release

**Comment by ramramps** [comment]
I agee. @jnealb - what do you think?

**Comment by kronz** [comment]
@andydandy74 @ramramps I agree

**Comment by ke-yu** [comment]
Fixed in #6798
