### ISSUE TITLE
After getting DocumentSet in Python, Dynamo will not open again

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#6083]
Using a simple definition, we can get a list of currently opened documents in the Revit application:
![definition and python](https://cloud.githubusercontent.com/assets/5659896/12842379/56da4764-cc42-11e5-9133-dad6213011e8.png)
However, after running this script successfully, and then closing Dynamo, then Dynamo will not open again and reports this error:
![error](https://cloud.githubusercontent.com/assets/5659896/12842380/579154d6-cc42-11e5-8de8-cee1a709ebef.png)
I have tested on 0.8.2 and 0.9 and the same error occurs on both.

**Comment by jnealb** [comment]
@mjkkirschner Curbside?

**Comment by mjkkirschner** [comment]
potentially on shutdown we dispose of the documents in some way that invalidates them. Have you tried closing/reopening documents in Revit before reopening Dynamo?

**Comment by LukeyJohnson** [comment]
Ok if I close Dynamo, close documents, open a new document, then Dynamo will work again.

**Comment by mjkkirschner** [comment]
We must be disposing this managed instance, @jnealb I think we should track this as a bug specifically for Revit document objects.

**Comment by jnealb** [comment]
Ok

**Comment by LukeyJohnson** [comment]
This is still there on latest 1.0.0 daily:
<img width="303" alt="daily" src="https://cloud.githubusercontent.com/assets/5659896/13478444/ff5eb6ac-e120-11e5-8d7d-2da806d329fe.png">

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
