### ISSUE TITLE
Import SAT file with "Show Edges" locks up Dynamo background thread

### ISSUE THREAD

**Issue by oderby** [DynamoDS/Dynamo#6094]
Steps to reproduce:
1. Launch Dynamo Sandbox (or in Revit, doesn't matter)
2. Set Settings > Show Edges to true
3. Create a new Dynamo script and try to import the surface from [Surface.zip](https://github.com/DynamoDS/Dynamo/files/121773/Surface.zip) (inside the .zip)
Observe that, while you can continue interacting with the Dynamo UI, the geometry never shows up, the DynamoSandbox thread is spinning (when viewed in Windows Task Manager), and if you try to close Dynamo, it hangs until you force close the program (using task manager).

Now, if you skip step #2 above (that is, set Show Edges to false), everything works as expected (the geometry is displayed immediately).

This is occurring for me on Dynamo v0.9.0.3067

Also, this appears to be the same behavior as reported in #2974, although in that case, it seems to crash regardless of Show Edges setting, so perhaps a different issue?

**Comment by kronz** [comment]
Hi @oderby ,
Happily, I am not reproducing this in the 0.9.1 release candidate (in Dyn Studio). 
![2016-02-10_2145](https://cloud.githubusercontent.com/assets/3456818/12968426/cc017480-d03f-11e5-96a5-09dbdc074d93.png)
