### ISSUE TITLE
Wish: Do not break up words in group titles

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6097]
This, in my opinion, should not happen:
![unbenannt](https://cloud.githubusercontent.com/assets/3014437/12914542/1ddf8baa-cf25-11e5-9106-a11c03facf34.PNG)
Expected behaviour: Only create line breaks in group titles at typical delimiter characters like whitespace, dash etc.
Dynamo 0.9 stable release
CC @Racel

**Comment by LukeyJohnson** [comment]
Agree!

**Comment by Racel** [comment]
Good point, @andydandy74. This also bugs me. Adding it to our backlog.

**Comment by ikeough** [comment]
@Racel Was this ever fixed?

**Comment by kronz** [comment]
Still happens in 1.0

**Comment by Racel** [comment]
Here are 2 YTs related to this issue:
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10042
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7417

**Comment by Racel** [comment]
@andydandy74 - Hope to work on this in the next few sprints.

**Comment by Racel** [comment]
Addressed here: https://jira.autodesk.com/browse/DYN-61

https://github.com/DynamoDS/Dynamo/pull/7535

This is under review and should be in the next release. I will close this once it is merged and tested.

**Comment by andydandy74** [comment]
This has been fixed. Thanks, guys.
