### ISSUE TITLE
0.91RC Replication guides misbehaving?

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#6101]
So far replication guides have somewhat  worked like this:
![2016-02-10_14-55-12](https://cloud.githubusercontent.com/assets/7148394/12940808/ad4a5508-d007-11e5-93e4-302b4bbfb40d.png)
Sort of behaving like a List.Map node

However in 0.91RC the result is the following:
![2016-02-10_14-55-04](https://cloud.githubusercontent.com/assets/7148394/12940814/bd17b73c-d007-11e5-9e2e-8814c1815c81.png)

@ke-yu is this expected behavior?

**Comment by ke-yu** [comment]
hi @dimven , haven't checked the replication guide code yet, but notice the implementation `List.Chop()` was modified. 

It is very hard to figure out the expected result for even not so complicated replication guides like <1><2>. I'm trying to formalize it and even simplify it, so replication guide behavior might be changed soon.

**Comment by dimven** [comment]
Thanks for the info.
@vykrum suggested using "List.Sublists" as a workaround.

![2016-02-11_14-31-19](https://cloud.githubusercontent.com/assets/7148394/12970620/01512a9a-d0cc-11e5-9afe-f38dff014926.png)
