### ISSUE TITLE
Category.ByName issue

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6108]
ver: 1.0.0.384
OS: Win 10
Tried this as it didn't work with a string, still didn't.

![20160210-2](https://cloud.githubusercontent.com/assets/5621624/12952500/ab3b4b66-d03c-11e5-9f3f-8e439c8eff38.png)

**Comment by dimven** [comment]
This node has always worked kinda weirdly. It expects the built-in Revit category name:
![2016-02-11_14-46-30](https://cloud.githubusercontent.com/assets/7148394/12970794/2b9ba9a4-d0ce-11e5-879d-1a6a4d2abf52.png)

I'm not sure what's the best way to fix this. Should "Category.Name" provide the built-in name or should the "Category.ByName" automatically perform the above operations?

**Comment by jnealb** [comment]
@vykrum @dimven @sm6srw This was tracked with MAGN-7419 and has been fixed with 1.0. Can you please try the latest daily build?
