### ISSUE TITLE
Disable the auto-show of node output preview

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#6126]
Hi,
This is wrt the new feature in 0.9 which auto-shows the output preview of nodes when mouse enter them.

Can there be a check-menu item in the settings to enable or disable this feature? I prefer to have it the way it used to be prior to 0.9-- where I click a button to show content. This is due to two reasons in current implementation:
1-Hinders Visibility: Auto-show also means auto-hide other parts in the graph. This makes things harder to work with because they continuously get hidden as mouse travel over the graph. 
2-Performance. Sometimes, Dynamo gets very occupied with trying to "animate" the expansion of output preview lists. The software sometimes hangs, or just becomes too slow and usable. For example, if the mouse happened to have hovered over 3 nodes, it could take up to 30 seconds until the animation is done and dynamo becomes usable again. Other times, I just have to restart Dynamo. This can happen on files with under 10 nodes. I haven't identified the procedure that can reproduce this yet, but it happened a few times already upon using 0.9 in the first week. 

I am running dynamo on a fairly advanced machine with all drivers are up to date. So I don't think it is a hardware issue at all.

I realize 0.9 is in development still, but it would be great if users are given a choice of defining what becomes a default (automatic) behavior and what does not. Please consider a check-menu item in settings! :)

**Comment by Racel** [comment]
There is a menu option under Settings, "Show Preview Bubbles", where you can disable all previews.
