### ISSUE TITLE
numpy in dynamo

### ISSUE THREAD

**Issue by tetsuyahishida** [DynamoDS/Dynamo#6128]
Hi all.

I was trying to use numpy in Dynamo, but 

import numPy as np

resulted in error such as
"ImportError: No module named numpy"

Are there any means to use numpy in Dynamo?

by the way, I just needed the functionality of "transpose" for 3 dimensional list. There must be many other means to achieve this.

**Comment by pboyer** [comment]
Numpy is not a pure python package. Instead it calls into c subroutines.
Therefore, I'm not sure it will be callable. Now that dynamo uses
ironpython, not the cpython installed on your machine.

**Comment by tetsuyahishida** [comment]
>pboyer
Thank you for replying. I was working on using Enthought Canopy (64-bit)but still not figuring out how to use it in Dynamo.
I hope there were packages that utilizes functionality given in numpy.

**Comment by mostaphaRoudsari** [comment]
@tetsuyahishida do you addreference to numpy?

This post might help:

**Comment by mjkkirschner** [comment]
@tetsuyahishida if you need Numpy, you could start a regular python process and have it run your code and pipe the result back into Dynamo. I have never implemented this but should be possible.

**Comment by ikeough** [comment]
Closing issue as out of date. @tetsuyahishida, please re-open if this is still an issue.
