### ISSUE TITLE
still low performance and incorrect results ver 1.0

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#6132]
i tried to filter "all elements of type" the result was 20+ valid nodes.
actually there is just one valid result namely "all elements of type"
![image](https://cloud.githubusercontent.com/assets/6928491/13110707/ebb985b4-d581-11e5-9515-06f090aa70ad.png)

**Comment by jnealb** [comment]
@Racel fyi

**Comment by smangarole** [comment]
@epeter- The search performance issue has been solved with 1.3 Dynamo. 

We are aware of the search issue that you have identified and are working towards a solution. 
@Racel

**Comment by smangarole** [comment]
@epeter- Please re-open the issue if you think it's still happening in Dynamo 1.3. Thanks.
