### ISSUE TITLE
Lines not visible in background

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6135]
Ver: 1.0.0.464
OS: Win 10
Lines are white in color and are not visible. They however, turn blue on selecting and are visible against a dark background (of some other geometry)
![20160217-5](https://cloud.githubusercontent.com/assets/5621624/13118550/afe56816-d5ca-11e5-831c-61918b78edc8.png)

**Comment by jnealb** [comment]
@vykrum Thank you - this is tracked with MAGN-9499.

**Comment by jnealb** [comment]
@vykrum This has been fixed.
