### ISSUE TITLE
Graph getters and setters from py

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#6145]
Is there a way in python script to programmatically:
1-add, remove, and reposition graph nodes?
2-get and set nodes parameter values? for example sliders, or input ports of nodes, etc.

**Comment by dimven** [comment]
A Dyn definition is just an XML file. Each node's location, a slider's value, everything is all saved there.

If you have the patience to read and modify the XML code through python, it's doable, yes. Here's some suggestions on XML parser modules for python:
http://stackoverflow.com/questions/1591579/how-to-update-modify-a-xml-file-in-python

**Comment by melkhaldi** [comment]
Yep. I tried modifying the XML already, but for things to actually update,
I'll need to reopen the dyn file again. My use case is that I need to drive
nodes values in real time, without having to reopen the dyn. Is there a way
to do that?

**Comment by melkhaldi** [comment]
For example: I load a CSV file--> read a design vector( associated list of values), and then look for the nodes in the graph whose GUIDs match the design vector vaue list, and set them accordingly. I can do that via XML, but I'll need to open and close the file every time...

**Comment by dimven** [comment]
Well it might be possible. The graph layout cleaner code can shift nodes around during execution. Maybe you can tap into something from its code:

https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Workspaces/WorkspaceModel.cs

**Comment by melkhaldi** [comment]
Ah, source code! What about setting values during execution?

**Comment by smangarole** [comment]
@Racel @kronz Can you please comment on this enhancement request?

**Comment by Racel** [comment]
@mjkkirschner - Any thoughts on this?

**Comment by mjkkirschner** [comment]
yes, if we do this it should be a library that we add like DynMeta project or something like this that can be used to expose core Dynamo and DynamoWorkspace model methods.

Thats one approach, another is to add more functionality into the DynamoServices project.

I prefer the first - this could be a totally separable package. I'm not sure if it would enable editing of the current graph or only automating of another dynamoModel.
