### ISSUE TITLE
Background preview not updating when deleting the node

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#6152]
Dynamo 0.9.1.4062, Windows 7, Revit 2015

Created a circle, deleted the node but circle remained in the background even after several reruns. It disappeared only when closing and reopening Dynamo.

**Comment by monikaprabhu** [comment]
@paoloemilioserra - I've seen some issues related to geometry not cleaning up while using CodeBlockNodes to create geometry.If delete those CBN after making some changes to the script Dynamo is not removing the geometry from view.This is tracked in MAGN-9434. I would like to know if the issue you are seeing is related to CBN or the Geometry nodes is we can track it seperately.

**Comment by paoloemilioserra** [comment]
I didn't use code block nodes but circle.ByPointAndRadius
Regards


Paolo Serra
BIM Technical Consultant
Autodesk Consulting AEC - EMEA
MOBILE   +39 344 138 6032


-------- Messaggio originale --------
Da: monikaprabhu <notifications@github.com>
Data: 02/22/2016 04:38 AM (GMT+01:00)
A: DynamoDS/Dynamo <Dynamo@noreply.github.com>
Cc: Paolo Serra <paolo.serra@autodesk.com>
Oggetto: Re: [Dynamo] Background preview not updating when deleting the node (#6152)


@paoloemilioserra<https://github.com/paoloemilioserra> - I've seen some issues related to geometry not cleaning up while using CodeBlockNodes to create geometry.If delete those CBN after making some changes to the script Dynamo is not removing the geometry from view.This is tracked in MAGN-9434. I would like to know if the issue you are seeing is related to CBN or the Geometry nodes is we can track it seperately.

-

**Comment by monikaprabhu** [comment]
@paoloemilioserra - we have fixed the issue in PR - https://github.com/DynamoDS/Dynamo/pull/6157. 
Which is merged into daily build - Sorry its disturbing you. If you are still able to see this in 1.0 please let me know!

**Comment by ikeough** [comment]
@monikaprabhu I'm closing this issue because it's fixed :) @paoloemilioserra Please re-open if you're still having issues.
