### ISSUE TITLE
Wish: Better documentation abilities

### ISSUE THREAD

**Issue by Arwilliams83** [DynamoDS/Dynamo#6159]
I have been investigating ways to use Dynamo in our MEP group.  One thing that has struck me is that there seems to be no easy way to document what you have done, basically just codeblocks with commented out text.  The coloured groups are great but I think it would be great if you had a comment block that could be attached to a node or group that had a description of the intended behavior.  Basically so other members of your team, or any one who downloads your files can see the reasoning.

Additionally, the python nodes seem like they would benefit from being able to rename the input and output ports visible in the UI for ease of use.  Also renaming the python node while retaining a clear indication it is a python node.

**Comment by mostaphaRoudsari** [comment]
@Arwilliams83 do you know about ctrl+W? It let's you add a note to the document.

I agree with you that you should be able to change the input/output names for the Python node.

**Comment by Arwilliams83** [comment]
I must admit I didn't know, it helps greatly, thank you.

**Comment by ikeough** [comment]
@mostaphaRoudsari Is there already a feature request for the python port renaming? If not, please create one.

@Arwilliams83 I'm closing this as it seems that the Notes feature helped. Please re-open if you're looking for more in the way of notes.
