### ISSUE TITLE
Dynamo Crash on New Version 0.9.1.4062

### ISSUE THREAD

**Issue by amorris3817** [DynamoDS/Dynamo#6166]
0.9.1.4062

Windows 7, 

Dynamo is crashing over and over
Object reference not set to an instance of an object.
Here is the error report.

Object reference not set to an instance of an object.

   at Dynamo.Controls.DynamoView.DynamoViewModelRequestViewOperation(ViewOperationEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

This just started happening since I updated to this version today. I cannot work at all not.... crashes over and over. Please help.

**Comment by jnealb** [comment]
@amorris3817 Can you please provide more detail about your workflows? Does it reproduce or is it random?

**Comment by amorris3817** [comment]
It seems to be related to windows. If another application window like outlook opens over Revit and Dynamo, when the outlook window is closed the Dynamo interface greys out and you can't do anything but close and re-open.

Abe Morris
BIM Manager* Smith Seckman Reid, Inc.

On Feb 29, 2016, at 3:04 PM, Neal Burnham <notifications@github.com<mailto:notifications@github.com>> wrote:


@amorris3817<https://github.com/amorris3817> Can you please provide more detail about your workflows? Does it reproduce or is it random?

-

**Comment by smangarole** [comment]
@amorris3817 This issue is fixed in Dynamo 1.3. Please re-open if you are able to reproduce this issue.
Thanks.
