### ISSUE TITLE
Cannot use Revit API "TopographyEditScope" in Dynamo Python Script

### ISSUE THREAD

**Issue by rbosborne** [DynamoDS/Dynamo#6189]
## Dynamo version

0.9.0
## Operating system

 Windows 7
## What did you do?

I am trying to add points to a topo (not create new, but add points to an existing) in Revit using PythonScript In Dynamo.  This requires the use of TopographyEditScope.  It seems that TopographyEdit Scope does not play nice with Dynamo.  See this post on the user forum:
http://dynamobim.org/forums/topic/topo-add-points-api-guru-help-needed/
## What did you expect to see?

I expected to be able to enter the TopographyEditScope, Add points, and see new points added to the topo
## What did you see instead?

Error on PythonScript (see pics on Dynamo Forum)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2159).
