### ISSUE TITLE
Select.Face: Dereferencing a non-pointer (3f47aacd)

### ISSUE THREAD

**Issue by Palroe** [DynamoDS/Dynamo#6190]
## Dynamo version

0.9.0.3067
## Operating system

Windows 7 Enterprise
## What did you do?

Applied a Select.Face node to my reinforcement design script and selected my desired face. Connected it to a Surface.Offset node.
## What did you expect to see?

I would expect the node to accept my selected face, as the node usually does.
## What did you see instead?

I got a warning and a not-funtioning yellow node, see pic. 
![error](https://cloud.githubusercontent.com/assets/17548786/13398128/3b567760-defd-11e5-81ee-77210b16080e.png)

**Comment by monikaprabhu** [comment]
@Palroe - I tried with Dynamo 0.9.0 and 0.9.1 and 1.0 could not reproduce the issue either with revit 2015 and 2016. Can you please share details on which Revit element are you selecting also the Revit version?

**Comment by Palroe** [comment]
Okey, thanks for the help so far.

The Revit element I'm selecting is a .dwg imported geometry from AutoCad.
It is imported as a generic model. The Revit version I am using:
Revit 2016
Build: 16.0.1092.0
20151209_0715(x64)
Update1 for R2

Pål
