### ISSUE TITLE
Dynamo Lag With Wacom Tablet

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#6192]
## 0.9.0

0.9.1
## What did you do?

navigating on workspace with Wacom Intuos tablet input (instead of mouse)
## What did you expect to see?

It should be fluent as with mouse
## What did you see instead?

Very laggy, slow response
(it works in revit and other software)

**Comment by alfarok** [comment]
Dynamo does not officially support Wacom interaction.  I would try upgrading to a newer version of Dynamo or try tweaking Wacom settings for better response as a workaround.  Closing this issue
