### ISSUE TITLE
Flux plug-in with large files

### ISSUE THREAD

**Issue by claudioarchi** [DynamoDS/Dynamo#6198]
## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
0.9.1.4062
## Operating system

(e.g. Windows 7, Windows 8.1, etc)
## What did you do?

Using Flux nodes importing large files from their web site
https://flux.io/
## What did you expect to see?

Get the geometry  in Dynamo
## What did you see instead?

Nothing just crashed

**Comment by ikeough** [comment]
@claudioarchi I'd like to get the flux guy's input on this.

**Comment by oderby** [comment]
@ikeough yep, we're on it. We'll post updates here once we understand what's happening.

@claudioarchi you should receive an email from us shortly.

**Comment by ikeough** [comment]
@oderby Thanks!

**Comment by smangarole** [comment]
@claudioarchi Any updates on this one?
