### ISSUE TITLE
Slider whose value, min, and max are defined by ports

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#6209]
How can I make a custom slider whose current, min, and max values can be defined by input ports as well as by user interactions.

When disconnected, its values are defined by the user. When a port is connected, its value gets overriden as the graph updates. That said, the user can still set the value while connected. Basically the min, max, sbd current values can get updated by two sources of input (user and graph), of course one at a time.

Where do I start exploring the process of building this?

**Comment by mjkkirschner** [comment]
You should look at these samples first thing:
https://github.com/DynamoDS/DynamoSamples/tree/master/src/SampleLibraryUI

This might be a tricky node to write - you'll probably need to use `Engine.GetMirror()` to access live values in the graph, so error checking will be key, also look here:
https://github.com/DynamoDS/Dynamo/wiki/How-To-Create-Your-Own-Nodes

and look at the bit about the color range node, I would suggest writing this node on 1.xx

**Comment by monikaprabhu** [comment]
@kronz ,@racel - This looks like an interesting request - Can we add this in our backlog to enhance the slider to take inputs ?

**Comment by andydandy74** [comment]
Actually, this has been requested before: #963 
(And I wholeheartedly second that request...)
CC @dbaldacchino

**Comment by dbaldacchino** [comment]
Thanks @andydandy74 :)

**Comment by ikeough** [comment]
@kronz This is similar to what I was working on at Smart Geometry this year. Let's talk.

**Comment by ikeough** [comment]
And because @andydandy74 linked the original, I'm closing this one.
