### ISSUE TITLE
try-catch blocks in DesignScript

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#6218]
## Dynamo version

0.91 stable (0.9.1.4062)

## Operating system

Windows 7

## What did you do? 
@ke-yu 

Is it possible to create try-catch imperative blocks inside DesignScript? The "try" and "catch" keywords are reserved so this makes me think that it should be possible. Am I using the syntax incorrectly or is this a feature that did not pass over from DesignScript Studio?

![2016-03-07_15-33-44](https://cloud.githubusercontent.com/assets/7148394/13563166/587ce658-e47a-11e5-8550-01dd743bdb88.png)

P.S. 
It would be great if error messages inside DS functions/blocks could be more specific.

**Comment by ke-yu** [comment]
@dimven wow wow! `try` and `catch` was supported long time back as an experimental feature, but when associative language was supported, we didn't come up a design to make it work with associative language (associative update/replication and so on), so we dropped it. I don't have a plan to support it in the near term :-(

**Comment by dimven** [comment]
Ok thanks for letting me know. In most cases we can come up with an alternative approach and circumvent the use of a try-catch block. So this is definitely not a priority feature just something nice to have around.
