### ISSUE TITLE
freeze with list.flatten

### ISSUE THREAD

**Issue by dago2015** [DynamoDS/Dynamo#6222]
## Dynamo version

0.9.1

## Operating system

Windows 7

## What did you do? 

![dynamo freeze](https://cloud.githubusercontent.com/assets/16885846/13585032/3c0ae1c0-e46e-11e5-82a1-e209cff2434b.PNG)

trying to pull out numbers from a list

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by jnealb** [comment]
@dago2015 If possible, can you please send us your complete dyn? neal.burnham@autodesk.com

**Comment by dago2015** [comment]
I just sent the file over. Thanks,

**Comment by jnealb** [comment]
@dago2015 Can you please try the latest daily build from 03/11? We think this is fixed.

**Comment by dago2015** [comment]
Dear Neal,

I have been working with the newest release for two days and so far I have
not had the program crash on me. Thanks. Also, I have notice that the node
align command has stopped working.

I would like to request that there be a way that I can copy or export a
group of nodes from one Dynamo workspace to another, or maybe import a
workspace to another workspace.

Thanks,

Dago

**Comment by ikeough** [comment]
@dago2015 Glad to hear your crash is fixed. If you'd like to open a separate improvement request, please do so and add the Improvement tag.
