### ISSUE TITLE
Keep custom xaml control on top of Dynamo

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/Dynamo#6231]
## What did you do? 

Trying to keep a xaml window with CSV display on top of Dynamo. I thought maybe the Python script editor window code would give a clue. But in fact that one also disappears behind the Dynamo window when you come from another application. Also would be nice to keep MessageBox.Show() on top of Dynamo.

**Comment by jhubers** [comment]
The answer to this question might be interesting for future amateur developers like me. The trick is that you make the `DynamoView` the owner of the xaml window control. You can do this in the `NodeViewCustomization` class of your custom UI node like in the Dynamo Samples. E.g. imagine that you make a custom UI node called `YourNode`. And with that node you create an instance of a xaml window called `myXamlWindow`. Then give 'YourNode' a property: `public static DynamoView dv;` Then in the `CustomizeView` method put next code:
```
public void CustomizeView(YourNode model, NodeView nodeView)
{
    var YourNodeControl = new YourNodecontrol();
    NodeView nv = nodeView; 
    YourNode.dv = FindUpVisualTree<DynamoView>(nv);
    nodeView.inputGrid.Children.Add(YourNodeControl);
    YourNodeControl.DataContext = model; 
}
private static T FindUpVisualTree<T>(DependencyObject initial) where T : DependencyObject
{
    DependencyObject current = initial;
    while (current != null && current.GetType() != typeof(T))
    {
        current = VisualTreeHelper.GetParent(current);
    }
    return current as T;
}
```
And in your myXamlWindow.cs file:
```
public partial class myXamlWindow: Window
  {
      public myXamlWindow()
      {
          InitializeComponent();
          Owner = YourNode.dv;
      }
  }
```

**Comment by ke-yu** [comment]
@jhubers thanks! We should include it in the sample. @riteshchandawar , what do you think?

**Comment by mjkkirschner** [comment]
@ke-yu @ramramps theres also the question of the WPF utility method that @jhubers used - should things like this be in the API?

**Comment by jhubers** [comment]
@ke-yu, @mjkkirschner, @riteshchandawar, @ramramps Maybe good to realise: The problem of leaving controls behind when closing Dynamo, is then also automatically solved.

**Comment by ikeough** [comment]
@jhubers This is very good to know. Thanks! @riteshchandawar, I'm closing this issue, but feel free to open a back-log item for including notes about this in the Dynamo Samples code.
