### ISSUE TITLE
Can not see the workplane

### ISSUE THREAD

**Issue by himanshuruhilla** [DynamoDS/Dynamo#6251]
## Dynamo version

0.9.1.0

## Operating system

Windows 7

![image](https://cloud.githubusercontent.com/assets/17799532/13723601/e7b7c7ac-e88f-11e5-8062-21c341994593.png)

**Comment by ikeough** [comment]
Please see the first issue in the [FAQ](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ). If none of those solutions help, please re-open.
