### ISSUE TITLE
List.Chop doesn't accept 0 as chop length

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#6257]
## Dynamo version

0.9.1
## Operating system

Win7
## What did you do?

Used a List.Chop node
## What did you expect to see?

For example: List {1,2,3,4,5,6,7} matched with lengths {2,0,3,0,2} would result in {{1,2},empty list,{3,4,5},empty list, {6,7}}
## What did you see instead?

List {1,2,3,4,5,6,7} matched with lengths {2,0,3,0,2} results in {{1,2},{3},{4,5,6},{7}}

![image](https://cloud.githubusercontent.com/assets/7080648/13746628/8295eed8-e9f4-11e5-9e2a-799390832402.png)

**Comment by josols** [comment]
the List.ChopByLengths is from the Clockwork package

**Comment by andydandy74** [comment]
@josols  - I just ran into this one myself. I deprecated List.ChopByLengths in Clockwork when List.Chop but will re-add it to the package until this issue is resolved.

**Comment by andydandy74** [comment]
Looks like this is getting fixed here: https://github.com/DynamoDS/Dynamo/pull/9145
