### ISSUE TITLE
Wish: Update Wiki "API Changes" to 1.0.0

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/Dynamo#6262]
Hi there,
are there any changes in the API from 0.9.1 to 1.0.0? Would it be possible to update the Wiki "API Changes accordingly? I'm thinking about updating my libraries (still in 0.9.0) and just like to know, if I will have to change it again soon.
Thanks, Fabian

**Comment by ikeough** [comment]
Hey @redinkinc. There are now several 1.0 sections in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) documentation corresponding to the parts of the application that have changes. Please review the doc, and re-open this issue if you're still not seeing what you need.
