### ISSUE TITLE
Custom Node Properties dialog box has white text on white background in Category dropdown

### ISSUE THREAD

**Issue by LukeyJohnson** [DynamoDS/Dynamo#6277]
## Dynamo version

0.9.1
## Operating system

Windows 10
## What did you do?

Create Node from Selection... Custom Node Properties dialog box
## What did you expect to see?

Category list (select group dropdown) to be be white text on black background
## What did you see instead?

Category drop down list was white text on white background, almost impossible to interpret
![cnp](https://cloud.githubusercontent.com/assets/5659896/13864350/ad97573a-ecf0-11e5-9b7d-91a2ce479414.png)

**Comment by smangarole** [comment]
@LukeyJohnson This issue is fixed in Dynamo 1.3 (studio 1.3 too). Please re-open if you are able to reproduce.
Thanks.
