### ISSUE TITLE
Wish: Ability to disable Package Manager

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6289]
## Dynamo version

0.9.0
## Operating system

Windows 7
## What did you do?

For rolling out Dynamo in our office we are using a curated list of packages that we want our users to use. What we do **not** want is for them to install other packages that have not been vetted by us. Therefore, it would be great to be able to disable the package manager in DynamoSettings.xml for certain user groups.
## What did you expect to see?

A setting to disable the package manager in DynamoSettings.xml
## What did you see instead?

Disabling the package manager currently does not seem possible

**Comment by ikeough** [comment]
@andydandy74 I believe you can instruct Dynamo not to load the package manager at startup by removing the `<dynamo install>\extensions\PackageManagerExtension_ExtensionDefinition.xml` file. This would have to be part of your deployment protocol.

**Comment by andydandy74** [comment]
@ikeough - while this would have been nice, unfortunately it doesn't work. I tried this in 0.9.0 stable and the latest daily (1.0.0.910). DynamoSandbox (0.9.0) won't start at all, neither will the Revit addin. The screenshot below shows the error message I get when I try to launch the Revit addin.
![disablepkgmanager](https://cloud.githubusercontent.com/assets/3014437/14737698/bf6fbbe8-087d-11e6-94bb-d7dd9fbda4de.PNG)

**Comment by ikeough** [comment]
Ah. I see why this would be. We converted the package manager to an extension, but kept the package manager UI bits as part of the core application. Not very smart. The package manager UI should be a _view extension_ so you could disable both the extensions and disable the PM. Thanks for trying.

**Comment by mjkkirschner** [comment]
This is actually possible by setting the address of the package manager to some nonexistent url...
in the dynamoPackages.config file.

**Comment by mjkkirschner** [comment]
closing for now if this solution works.
