### ISSUE TITLE
Wish - Ability to Define and Decompose Meshes

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#629]
Would love the ability to create meshes and have them preview.

Create Mesh
- Inputs:  Vertices list (XYZ), Face list (index)
- Outputs:  Mesh

Decompose Mesh
- Inputs:  Mesh
- Outputs:  Vertices list (XYZ), Face list (index)

**Comment by mjkkirschner** [comment]
@archinate I believe this functionality can be achieved with MeshToolkit nodes now. Please reopen if not what you were looking for.
