### ISSUE TITLE
Watch Node Freezes Dynamo: Forces Quit and Unsaved work Lost! 

### ISSUE THREAD

**Issue by thall26** [DynamoDS/Dynamo#6292]
## Dynamo version

0.9.1.4062

## Operating system

Windows 7

## What did you do? 

Scrolling down the watch node. While scrolling, Dynamo **freezes **up and forces me to kill Revit and Dynamo losing all work unsaved to that point. This happens both in the Watch 2D node AND the dynamic watch node that automatically opens up below the node when hovering. 

## What did you expect to see?

My list management. 

## What did you see instead?

Dynamo freezing. Force quit immediately following.

**Comment by jnealb** [comment]
@thall26 Thanks - we think this is fixed 9.2 which will be released soon.

**Comment by thall26** [comment]
@jnealb Wonderful! Thanks Neal!
