### ISSUE TITLE
Crash from Element.GetParameterValueByName

### ISSUE THREAD

**Issue by DavePlumb** [DynamoDS/Dynamo#6311]
## Dynamo version

0.9.1
## Operating system

Windows 7-64 SP1
## What did you do?

My graph selects all Doors in a project, then gets the nearby Rooms
Next it compares the Door Number to both Room Numbers and sets a flag if the Door matches one of the Rooms or false if it matches neither.
## What did you expect to see?

This has worked on small projects, but on a large project with
I got an error:
**Internal error: please report: 
Dereferencing a non-pointer (3f47aacd)**
(Image attached)
This was in an Element.GetParameterValueByName node

I've attached the graph and an image of the error, but the Revit project is 400 Meg, 
If you want to test the graph, you'll also want to remove the "Filter Superdoors" node.
That node uses a parameter that is unique to our doors. 
"Normal" doors will work fine bypassing that node.
![dynamoerror](https://cloud.githubusercontent.com/assets/18071127/14045134/71095028-f265-11e5-87ef-7b2149ce1ff3.PNG)

[DoorNumberQA.dyn.txt](https://github.com/DynamoDS/Dynamo/files/189557/DoorNumberQA.dyn.txt)

**Comment by DavePlumb** [comment]
Forgot to mention:
By "large project", I meant there are about 1600 Doors.
Is there perhaps a limit on List length?

**Comment by ke-yu** [comment]
No limit on list length. I'll do some test with your graph.

**Comment by DavePlumb** [comment]
I've been narrowing it down this morning, and I think I understand what's going on.
The error message is generated when the Element.GetParameterValueByName node is passed a nul value for the "element" input. 
So that makes sense.
Now I have to figure a way around that condition in my graph.

**Comment by ikeough** [comment]
@DavePlumb You shouldn't have to "get around" this. We should safely handle nulls input to that node.

**Comment by jnealb** [comment]
@ikeough @DavePlumb @ke-yu This, and another "user not friendly" issue are tracked: please see MAGN-9976, 9915.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2157).
