### ISSUE TITLE
Dynamo auto-assigning 

### ISSUE THREAD

**Issue by brianringley** [DynamoDS/Dynamo#6312]
## Dynamo version

0.9.2.4472

## Operating system

Windows 7 Enterprise Service Pack 1

## What did you do? 

Opened a Project and associated Dynamo graph.

The graph had empty Family Type drop-down lists connected to an authoring node (FamilyInstance.ByPointAndLevel).

When I then opened a Revit Family (with the intention to load it into the the Revit project linked to the Dynamo graph), all of my empty Family Type nodes selected the first available family in the list, thus writing arbitrary family types into the project which caused Revit to crash.

I'm not sure why opening a Revit file would trigger a change in a Dynamo graph, especially when the two are not linked in any way.

## What did you expect to see?

If a Family Type Node is empty, it should remain empty, and not arbitrarily select a family from my project.

## What did you see instead?

Dynamo making arbitrary changes to my graph (the drop-down selection in the Family Types node) which is extremely dangerous, particularly when I'm running in Automatic mode.

![dynissue092](https://cloud.githubusercontent.com/assets/6502496/14049779/cd393368-f28d-11e5-8eab-acddfe77a1ff.jpg)

**Comment by riteshchandawar** [comment]
Hello @brianringley, So as per my understanding you are saying when you opened a Revit Family file, Dynamo Graph picked up the first family from the list, OR when you load the Family into Project then Dynamo picked up the first family?

- Ritesh

**Comment by brianringley** [comment]
Hi @riteshchandawar. It was upon opening a Revit Family file. Thank you.

**Comment by riteshchandawar** [comment]
That's strange, Is it possible for you to share the Revit and DYN files with me. (ritesh.chandawar@autodesk.com)

- Ritesh

**Comment by rk-lakshmanan** [comment]
Hello @brianringley
Whenever a new Revit file opens, Dynamo will populate the combo box and reset all of the drop-down selection to the first drop-down item in the list. I have made a fix by removing the portion of the code that causes the reset. 
The PR link for your reference: https://github.com/DynamoDS/DynamoRevit/pull/928
Thank you.

**Comment by ikeough** [comment]
@rk-lakshmanan I'm closing this issue because it's fixed (according to the PR :) ). @brianringley Please re-open if this is still causing issues.

**Comment by brianringley** [comment]
SO FAR SO GOOD
