### ISSUE TITLE
Sub-optimal z-ordering of nodes and previews

### ISSUE THREAD

**Issue by lukechurch** [DynamoDS/Dynamo#6313]
## Dynamo version

0.9.2.4472

## Operating system

Windows 7 via Parallels

This z-ordering where the node is on top of the preview, but everything else is below, doesn't feel right.

![image](https://cloud.githubusercontent.com/assets/2978182/14050791/1d05f8d6-f2b6-11e5-8cd7-bcc8a34d3afd.png)

Repro is to run, select the lower node and then hover over the upper node

**Comment by jnealb** [comment]
@lukechurch @Racel Thanks Luke - are you wedded to 9.2? If not, you will find 1.0 improved in this regard (just an fyi: the 1.0 installers are in transition at the moment, but do work, except with Revit 2017 and the Samples in Standalone).

**Comment by ramramps** [comment]
Oh. this was not cherry picked to 0.9.2?

**Comment by jnealb** [comment]
No

**Comment by lukechurch** [comment]
Hey @jnealb @Racel, nah no big deal. I just needed some screenshots for some writing I was doing and ran into this. Sounds like you've already got it well under control :)
