### ISSUE TITLE
Warning: Method '__func_3bb214f859b84ce8969be42d4d05414e()' not found

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#6315]
## Dynamo version

0.9.1.3872
## Operating system

Windows 8
## What did you do?

Tried to re-run the definition
## What did you expect to see?

I expected the definition to work fine but...
## What did you see instead?

A number of custom nodes started to show the same error as:

```
Warning: Method '__func_3bb214f859b84ce8969be42d4d05414e()' not found
```

**Comment by ke-yu** [comment]
@mostaphaRoudsari , do you have step to reproduce or any sample .dyf file?

**Comment by mostaphaRoudsari** [comment]
Haven't see this recently.
