### ISSUE TITLE
PointAnalysisDisplay.ByViewPointsAndValues gives inputs match error

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#6316]
## Dynamo version
0.9.1.3872

## Operating system
Windows 8

## What did you do? 

![image](https://cloud.githubusercontent.com/assets/2915573/14061857/129bca9a-f362-11e5-855d-055796f765ba.png)

I tested different views but it still gives me the same error. It might be my lack of knowledge in setting up the node but also might be a bug.

## What did you see instead?
Warning: One or more of the input types are not matching. Couldn't find a version of ByViewPointsAndValues that takes arguments of type (Revit.Elements.Views.FloorPlanView,__array,__array,string,string,string)

**Comment by mjkkirschner** [comment]
UnitType I think is an actual type, not a string.

**Comment by mostaphaRoudsari** [comment]
Of course! Thanks @mjkkirschner.
![image](https://cloud.githubusercontent.com/assets/2915573/14062049/0877cd42-f368-11e5-90ea-544df86b786d.png)
