### ISSUE TITLE
Issue with Export Workspace as Image

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6349]
## Dynamo version

1.0.0.670

## Operating system

Windows 10

## What did you do? 

Export Workspace as Image (by clicking the icon at the top right)

## What did you expect to see?

![20160331-2b](https://cloud.githubusercontent.com/assets/5621624/14174816/9c7e8eea-f764-11e5-96ce-153401600226.png)

## What did you see instead?

![20160331-2](https://cloud.githubusercontent.com/assets/5621624/14174824/a2a2979e-f764-11e5-9857-a599693563d6.png)

**Comment by ikeough** [comment]
@vykrum I fidddled about making several image captures and couldn't reproduce. I opened the console and captured. I resized the view and captured, and I toggled the library closed and captured. Nothing seemed to reproduce this.

**Comment by vykrum** [comment]
@ikeough The problem was with the build mentioned above. Haven't faced this issue in the more recent builds (or earlier builds).
