### ISSUE TITLE
Help tag: On/Off - DynamoDailyInstall20131027T1403

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#636]
It would be great to switch on/off this new feature cause now it's overlapping when you want to connect 2 nodes depending on the zoom factor.
or maybe mouse over the node + shift to activate this popup.....

also I would advocate for a shortcut to activate/hide all previews.

great job guys!

**Comment by ke-yu** [comment]
There is an option in help | Hide preview bubble.
