### ISSUE TITLE
define custom input name for zero touch node

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#6360]
## Dynamo version

9.2
## Operating system

windows 10

This is more of a feature request, than a bug. Tell me if this is possible, but it would be nice if the input names define in the XML markup for zero touch nodes would allow to define a custom name for inputs instead of only allowing to use name of the input variable. I usually tend to name my variables with abbreviations of actual words but that's not a perfect name to display to user. Example: 

``` C#
/// <summary>
        ///     Select Element by Element Id Integer.
        /// </summary>
        /// <param name="id">Element Id as Integer.</param>
        /// <returns name="Element">Element in model.</returns>
        /// <search>id, element, select</search>
        public static Element GetById(int id)
```

Can the param name="id" take another variable for displayName="ElementId"? 

Cheers! 

cc: @mjkkirschner @ikeough @pboyer

**Comment by ikeough** [comment]
@ksobon There are a number of ways we could do this. I hesitate to overload the `param name=` functionality in the xml, as this format for comments is document in MSDN. We could add an attribute to a method like:
```c#
[ParamToInputConversion("someBar","inputBar")]
public void Foo(bar someBar){...}
```
In this scenario, you'd call your parameter "someBar" in code, and it would show up as "inputBar" on the Node.

**Comment by ksobon** [comment]
yeah that would do the trick too

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
