### ISSUE TITLE
Red Node

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6380]
## Dynamo version

1.0.0.943

## Operating system

Windows 10

## What did you do? 

Placed a node on the blank canvas in a new file

## What did you expect to see?

![20160406-2a](https://cloud.githubusercontent.com/assets/5621624/14305269/39774d0a-fbd8-11e5-9dbf-abf9a62a94d3.png)

## What did you see instead?

![20160406-2](https://cloud.githubusercontent.com/assets/5621624/14305271/3f6593f2-fbd8-11e5-89e4-312703421042.png)

**Comment by ke-yu** [comment]
@rk-lakshmanan @Benglin FYI
