### ISSUE TITLE
Element.Geometry inconsistency

### ISSUE THREAD

**Issue by rbosborne** [DynamoDS/Dynamo#6394]
Using 0.9.2.  I have lately noticed many elements that are not working with Element.Geometry.  Attached is a file containing 3 elements.  Only one of the 3 (the rectangular beam) will work with element.geometry in Dynamo.  If the rectangular beam is connected and joined to the elliptical column, it will not work with element.geometry.

I have looked at all 3 elements using RevitLookup.  For the Rectangular beam, the geometry only shows "Solid".  For the Ellipse Column it shows "GeometryInstance" and "Solid". For the cable loop it only shows "GeometryInstance".

I am wondering 
1. Why won't all 3 elements work with Element.Geometry (can the node perhaps be fixed to work for all 3?)
2. if there is some issue on the way the families are built to make it work with Element.Geometry - should that be documented so that people know best practices to make their elements work with Dynamo?
3. Is there an issue with nested (non-shared) families working with Element.Geometry?  (A Generic Model nested into an empty Structural Framing family perhaps??)

[Element Geometry fails.zip](https://github.com/DynamoDS/Dynamo/files/209231/Element.Geometry.fails.zip)

**Comment by kronz** [comment]
thanks @rbosborne , looks like this has been the behavior at least since 0.8.2, 

@aparajit-pratap It looks like Dynamo doesn't like to deal with 2 different situations.  One is elliptical extrusions and I think the other issue is conical elements, or maybe a sweep to a point?

**Comment by rbosborne** [comment]
A bit more testing on my end.  I agree that it appears that the ellipse and the swept conical blend are the problem pieces in this case.  I deleted the swept conical blend out of the family and reloaded it.  See image for result - Element.Geometry did successfully generate something - just not the correct thing.
![elementgeometry](https://cloud.githubusercontent.com/assets/12659052/14381645/cfc35aa0-fd55-11e5-8b24-a417ceef7141.PNG)

**Comment by mjkkirschner** [comment]
KroNz did you try this on 1.x after We made changes to the cone face converter ?

**Comment by dimven** [comment]
@rbosborne 

It looks like you are using revolved edges. There was an earlier issue with REs described here:
https://github.com/DynamoDS/Dynamo/issues/3679

I don't believe that was ever resolved.

**Comment by ikeough** [comment]
@dimven Thanks for the tips and the issue link. @rbosborne I'm closing this issue as the one that @dimven linked covers it. @mjkkirschner can you please confirm this is the same issue?
