### ISSUE TITLE
Surface analysis data node missing

### ISSUE THREAD

**Issue by Lexiko** [DynamoDS/Dynamo#6425]
## Dynamo version

0.9.2

## Operating system

Win 7

## What did you do? 
Trying to use "FaceAnalysisDisplay.ByViewAndFaceAnalysisData" but can't find a node to create data for input
## What did you expect to see?

Surface data node where surface, associated uv's and associated values are combined

## What did you see instead?

nothing

**Comment by ikeough** [comment]
@Lexiko Sorry for the confusion. In newer releases of Dynamo, the `FaceAnalysisDisplay.ByViewAndFaceAnalysisData` node has been replaced by the `FaceAnalysisDisplay.ByViewFacePointsAndValues` node as seen here:
![image](https://cloud.githubusercontent.com/assets/1139788/14717199/101f8ce6-07a5-11e6-85cd-89aa83d1068f.png)
The `FaceAnalysisData` node is no longer required. You can simply pass in a surface, a list of UV locations on that surface, and some values.

Please us know if you're still having issues.
