### ISSUE TITLE
ToXyz does not convert vectors to Revit's display unit

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6426]
## Dynamo version

1.0.0.910

## Operating system

Windows 7

## What did you do? 

Use the ```ToXyz()``` method in Python that is supplied by Dynamo via ```Revit.GeometryConversion```.

## What did you expect to see?

Same results for vectors and points

## What did you see instead?

Different results for vectors and points - vectors do not get converted to Revit's display unit.

![toxyzconversionfail](https://cloud.githubusercontent.com/assets/3014437/14526698/65e39d26-0245-11e6-8b17-d2147bace9bc.PNG)

**Comment by mjkkirschner** [comment]
for some reason 
```
 public static Autodesk.Revit.DB.XYZ ToXyz(this Autodesk.DesignScript.Geometry.Point pt, bool convertUnits = true)
        {
            if (convertUnits) pt = pt.InHostUnits();
            return new XYZ(pt.X, pt.Y, pt.Z);
        }

        public static Autodesk.Revit.DB.XYZ ToXyz(this Vector vec, bool convertUnits = false)
        {
            if (convertUnits) vec = vec.Scale(UnitConverter.DynamoToHostFactor(UnitType.UT_Length));
            return new XYZ(vec.X, vec.Y, vec.Z);
        }
```

vector is set to false for convert units, I think this is not a mistake, not sure though, but you can also call toXYZ with true set so that it converts units.

**Comment by ksobon** [comment]
could it be because you guys made an assumption that vectors would be unitized between 0-1 and hence would not require unit conversion?

**Comment by ikeough** [comment]
@ksobon is correct about our assumption.

**Comment by ksobon** [comment]
@ikeough I am glad I guessed this right. Just so its clear the answer here is: call this method using a CodeBlock and set the boolean to True instead of relying on a node which is by default set to false. Is that right?

**Comment by ikeough** [comment]
@ksobon As far as I understand the issue, your method seems correct.
