### ISSUE TITLE
Error in API Changes Documentation

### ISSUE THREAD

**Issue by ikeough** [DynamoDS/Dynamo#6427]
The API Changes documentation states that the `DropDownBase.PopulateItems` method has been changed to `DropDownBase.PopulateItemsCore`. This is not true. The original method still exists (and should exist). The new method has been added but is not part of the public API.

@rk-lakshmanan

**Comment by Benglin** [comment]
Good point, @ikeough. The documentation now says the following, what do you think of it?

- Changes made to `CoreNodeModels.DynamoDropDownItem`
   - `CoreNodeModels.DynamoDropDowBase.PopulateItems` is no longer a `virtual` method, custom population logic should now be implemented in `CoreNodeModels.DynamoDropDownBase.PopulateItemsCore` method instead.

**Comment by ikeough** [comment]
@Benglin Great! Thanks for the fix.
