### ISSUE TITLE
Geometry missing/broken in the preview after transform

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#6428]
## Dynamo version

Dynamo Studio 0.9.2.4461
## Operating system

Windows 7
## What did you do?

I created a graph to transform a PolySurface on a Curved surface using Geometry.Transform

[PatternDesign2.zip](https://github.com/DynamoDS/Dynamo/files/219157/PatternDesign2.zip)
## What did you expect to see?

The CoordinateSystems are all there but the resulting geometry is only half and even broken
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/14221455/14528823/c425b638-0251-11e6-8d63-eceb5ae10b3a.png)

**Comment by paoloemilioserra** [comment]
![image](https://cloud.githubusercontent.com/assets/14221455/14528926/53ed23a0-0252-11e6-95b7-0adf7a0e9b59.png)

**Comment by paoloemilioserra** [comment]
On Dynamo Add-in in Revit seems to work fine though

**Comment by mjkkirschner** [comment]
@paoloemilioserra interesting :)

so I can reproduce this locally but I see even less geometry. We're definitely hitting some kind of tri or memory limitation. If you lower the rendering settings to LOW I see all surfaces fine.

it's interesting that use on Revit corrects it, I have yet to verify that locally.

@ikeough @marimano any thoughts?

**Comment by kronz** [comment]
Interesting, I can see all the geometry, using a MacBook Pro (with 2880x1800 resolution).  It's a little slow, but there.  This is an excellent little stress test, cc @jnealb

**Comment by paoloemilioserra** [comment]
eventually it worked also in Dynamo Studio but I had to relaunch a few times to get rid of "ghost" geometry from previews run
![image](https://cloud.githubusercontent.com/assets/14221455/14542573/e2a5b6c4-028f-11e6-851d-d9ce29532c48.png)

**Comment by kronz** [comment]
That is so cool!  So, I wonder if this is also affected by a couple of changes we did in 1.0.  @paoloemilioserra can you tell us about the graphics specs for your system?

**Comment by paoloemilioserra** [comment]
Dell Precision M6800, resolution 1980x1080

![image](https://cloud.githubusercontent.com/assets/14221455/14543179/2b58c48a-0293-11e6-95da-567b7a9c8de0.png)

**Comment by mjkkirschner** [comment]
This actually crashes my vm if I do not lower the resolution of the tessellation - I guess it's possible were running out of gpu memory

**Comment by jnealb** [comment]
Indeed @kronz! However, it runs fine with Studio 1.0.0.1032 with my Nvidia K2100M set for High Performance (renders in < 10 secs). @paoloemilioserra, is it possible for you to try with Studio 1.0?

**Comment by paoloemilioserra** [comment]
I need to try a VM for that

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
