### ISSUE TITLE
Installation and access problems

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6434]
## Dynamo version

1.0.1.1050
## Operating system

Windows 10
## What did you do?

Searched for Dynamo on the windows search bar
## What did you expect to see?

Dynamo 1.0 listed in the search results
## What did you see instead?

Nothing
Dynamo isn't listed under All Apps in the Windows Start Menu

The sequence of events......
Initially was able to run Dynamo standalone, but not from Revit

So, uninstalled Dynamo 1.0 and reinstalled

Now it runs from Revit, but no standalone (sort of)

PS: Standalone Dynamo without background 3D (but with a 2D grid) can be accessed from

C:\Program Files\Dynamo\Dynamo Revit\1.0\DynamoSandbox.exe

**Comment by kronz** [comment]
FYI @sharadkjaiswal

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2156).
