### ISSUE TITLE
Installation of Bakery package asing to uninstall Clockwork and Lunchbox???

### ISSUE THREAD

**Issue by jonathanroy8676** [DynamoDS/Dynamo#6475]
## Dynamo version

0.9.2.4472

## Operating system

Windows 7 Pro  SP1

## What did you do? 
Install Bakery package
Packages > Search for a package > Bakery > Install

## What did you expect to see?

downloaded and installed with a new package in my library named Bakery

## What did you see instead?
![image](https://cloud.githubusercontent.com/assets/16231080/14684527/5b406094-06fe-11e6-968f-851f960873c7.png)

**Comment by kronz** [comment]
@jonathanroy8676 I think that Luke's package re-distributes pieces of Clockwork and Lunchbox, and so needs to replace them.  You will need to contact him to discuss his strategy for distributing pieces of existing packages.

**Comment by jonathanroy8676** [comment]
@kronz Just found this information on the [Dynamo Nodes - Bakery](https://dynamonodes.com/2016/01/22/what-is-bakery/).
"If you don’t want to deal with other packages wanting to uninstall and reinstall when installing Bakery, just download it from the Package Manager website as a ZIP, then unzip to this directory:

%APPDATA%\Dynamo\0.8\packages\Bakery"

Sorry, just found the Dynamonodes website.

**Comment by kronz** [comment]
No worries, its confusing

**Comment by andydandy74** [comment]
@kronz - This is actually exactly the kind of thing I described in #3433. It is indeed very confusing and I hope it gets improved in the next version of the package manager.

**Comment by jonathanroy8676** [comment]
I downloaded the latest package 2016.4.15 and unzipped it in 0.9 and 0.8 (just in case) folders and it still doesn't show up when I open my Revit 2016/Dynamo0.9. I researched his name and Bakery with succes. Other than tweeting Luke I don't know I should get in touch with him or other authors. i just tried his github for Bakery, I'm afraid I'm screwing things up... lol

**Comment by kronz** [comment]
@jonathanroy8676 I think the way to go is this:  You can go ahead and install Bakery, then just download and install Clockwork and and Lunchbox again.  A hassle, but will just work without having to mess with folder structures

**Comment by jonathanroy8676** [comment]
@kronz After understanding that I had to close Revit, and not just Dynamo, to uninstall the packages that were taged "Pending Uninstall". I installed the Bakery package which in turn reinstalled Clockwork, Blackbox and Lunchbox... :) I'm not sure what happen but things appear back to "normal". I do have to agree with @andydandy74 about this process not being very user friendly.

Thanks for the help and that's what I love about this community!
![bakerypackage_troubleshoting2](https://cloud.githubusercontent.com/assets/16231080/14689582/ed91cdfe-0715-11e6-984f-1c3bb43be199.png)

**Comment by LukeyJohnson** [comment]
I know that Bakery isn't ideal because of its dependencies. If you get into real trouble, you can just "Cut" all of the content out of your Packages folder, install Bakery (which will install Clockwork etc), then bring back any other packages you had already installed.

I also find that deleting DynamoSettings.xml sometimes helps, it gets recreated on next run.
