### ISSUE TITLE
Warning on installation

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6487]
## Dynamo version

1.0.1.1112

## Operating system

Windows 10

## What did you do? 

Install 

## What did you expect to see?

The usual installation windows

## What did you see instead?

![20160421-5](https://cloud.githubusercontent.com/assets/5621624/14709700/b4e26b46-07ef-11e6-8fd4-8720cbbd4f56.png)

**Comment by ikeough** [comment]
This is because the daily installer is not signed (I think). @sharadkjaiswal can give a little more background here.

**Comment by jnealb** [comment]
@ikeough @sharadkjaiswal In my experience a "First time in" thing that goes away, but not clear what the rules are for that yet.
