### ISSUE TITLE
SetParameterByName fails on Families (adaptive components) structured in a list of rank 3

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6493]
## Dynamo version

0.9.2
## Operating system

Win 10
## What did you do?

I have an Adaptive Component cladding system organised in a 3D list/rank 3 (List of list of lists). I iterate through the list to update each components instance parameters within an imperative DesignScript block but it fails to update the parameters.
## What did you expect to see?

The instance parameters update with the information I was giving it (import from Excel). Instead, I had to extract the sublist of panels first (so 2D list/rank 2) and return it back into a 3D array once I had iterated through the list to get around the bug. 
## What did you see instead?

No change to the instance parameters. 
(Fill in here)

**Comment by ikeough** [comment]
@ke-yu Sounds like an imperative block issue.

**Comment by ThomasMahon** [comment]
Just some further information to clarify the above; I did achieve SetParameterByName within DesignScript imperative block, but only by extracting the sublist to a new list, operating on that list inside a secondary for loop, then returning back into a primary list to retain my required data structure (i.e. 3D list)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2155).
