### ISSUE TITLE
Dot product returning erronous scalars?

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6494]
## Dynamo version

0.9.2

## Operating system

Win 10

## What did you do? 

Get the dot product of two vectors. Evaluating against world Z Vector. 

## What did you expect to see?
Dot product returned as a scalar between -1 to +1. 

## What did you see instead?

Due to the way I've created the vector for evaluation (flowing a PointByParameter on a circle with its centre point as its start point. The vector has been normalised) if I set the parameter on curve to 1 (effectively a 360 degree rotation) it returns -2.44929359829471e-16. I would also expect to see a scalar of 0!

Similarly for a parameter of 0.5 (effectively a -90 degree rotation) it returns a scalar of 1.22464679914735e-16. I would expect to see a scalar of 0! 

If I set the point by parameter to 0 (so +90 degree rotation) I get the result I expect = 0. Similarly for collinear vectors it correctly outputs +1 and opposing correctly outputs -1.

![dot product at 0deg full 360 deg rotation](https://cloud.githubusercontent.com/assets/18601851/14725447/e2337738-0813-11e6-9af8-737360f0033e.png)
![dot product at 0deg](https://cloud.githubusercontent.com/assets/18601851/14725448/e2353f96-0813-11e6-975b-fc89e299efdb.png)
![dot product at 90deg](https://cloud.githubusercontent.com/assets/18601851/14725449/e23613a8-0813-11e6-8ca7-3bb39ff99243.png)
![dot product at 180deg](https://cloud.githubusercontent.com/assets/18601851/14725451/e23b2be0-0813-11e6-8ca1-f44dfe6a22f6.png)
![dot product at minus 90deg](https://cloud.githubusercontent.com/assets/18601851/14725450/e23a3262-0813-11e6-8c0d-6f20fd588139.png)

**Comment by kronz** [comment]
@aparajit-pratap is there a youtrack task on this as well?

**Comment by aparajit-pratap** [comment]
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10001

**Comment by aparajit-pratap** [comment]
Should be fixed in the next build. Thanks @rk-lakshmanan .
