### ISSUE TITLE
Update Dynamo NuGet packages to Copy Local = False

### ISSUE THREAD

**Issue by ikeough** [DynamoDS/Dynamo#6496]
When the Dynamo NuGet packages are used by third party developers, they should not copy their assemblies locally. The NuGet packages should be updated to include the proper install script so that this doesn't happen. Like we've done [here](https://github.com/ikeough/GRegClientNET/blob/frac-272/src/GregClient/NuGet/tools/Install.ps1)

**Comment by johnpierson** [comment]
This is still an issue. Adding to the backlog as this would be great to have, especially since we are exposing view extensions to more people. Tracked as [QNTM-5937](https://jira.autodesk.com/browse/QNTM-5937)

**Comment by QilongTang** [comment]
3rd party devs should just remember to not do this
