### ISSUE TITLE
Variable Input Node Implementation

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#6500]
@mjkkirschner @ikeough 

Hey guys, I was playing around with the Variable Input Nodes and it crashes me out. I am not doing anything with it yet, other than just trying to implement the VariableInputNode. 

Here's the code: 

```C#
        [NodeName("RowContainer")]
        [NodeDescription("Some Description")]
        [NodeCategory("Mandrill.Nodes.Containers")]
        [IsDesignScriptCompatible]
        public class RowContainer : VariableInputNode
        {
            public RowContainer()
            {
                InPortData.Add(new PortData("item0", Resources.CreateListPortDataIndex0ToolTip));
                OutPortData.Add(new PortData("list", Resources.CreateListPortDataResultToolTip));

                RegisterAllPorts();

                ArgumentLacing = LacingStrategy.Disabled;
            }

            protected override string GetInputName(int index)
            {
                return "item" + index;
            }

            protected override string GetInputTooltip(int index)
            {
                return string.Format(Resources.ListCreateInPortToolTip, index);
            }

            protected override void RemoveInput()
            {
                if (InPortData.Count > 1)
                    base.RemoveInput();
            }

            public override bool IsConvertible
            {
                get { return true; }
            }

            public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
            {
                if (IsPartiallyApplied)
                {
                    var connectedInput = Enumerable.Range(0, InPortData.Count)
                                                   .Where(HasConnectedInput)
                                                   .Select(x => new IntNode(x) as AssociativeNode)
                                                   .ToList();

                    var paramNumNode = new IntNode(InPortData.Count);
                    var positionNode = AstFactory.BuildExprList(connectedInput);
                    var arguments = AstFactory.BuildExprList(inputAstNodes);
                    var functionNode = new IdentifierListNode
                    {
                        LeftNode = new IdentifierNode("DSCore.List"),
                        RightNode = new IdentifierNode("__Create")
                    };
                    var inputParams = new List<AssociativeNode>
                    {
                        functionNode,
                        paramNumNode,
                        positionNode,
                        arguments,
                        AstFactory.BuildBooleanNode(false)
                    };

                    return new[]
                    {
                        AstFactory.BuildAssignment(
                            GetAstIdentifierForOutputIndex(0),
                            AstFactory.BuildFunctionCall("Function", inputParams))
                    };
                }

                return new[]
                {
                AstFactory.BuildAssignment(
                    GetAstIdentifierForOutputIndex(0),
                    AstFactory.BuildExprList(inputAstNodes))
            };
            }
        }
```

and here's the customization class:

```C#
public class RowContainerNodeViewCustomization : VariableInputNodeViewCustomization, INodeViewCustomization<Mandrill.Nodes.Containers.Container.RowContainer>
    {
        public void CustomizeView(Mandrill.Nodes.Containers.Container.RowContainer model, Dynamo.Controls.NodeView nodeView)
        {
            base.CustomizeView(model, nodeView);
        }
    }
```

It crashes with the following message when I place the node on canvas. It looks like the node itself gets created all right but then the Workspace Model freaks out. I am not sure what I am doing wrong. Ideas? 

Thanks! 

The '+' character, hexadecimal value 0x2B, cannot be included in a name.

   at System.Xml.XmlDocument.CheckName(String name)
   at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
   at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
   at System.Xml.XmlDocument.CreateElement(String name)
   at Dynamo.Graph.ModelBase.CreateElement(XmlDocument xmlDocument, SaveContext context)
   at Dynamo.Core.UndoRedoRecorder.RecordActionInternal(XmlElement group, ModelBase model, UserAction action)
   at Dynamo.Graph.Workspaces.WorkspaceModel.RecordCreatedModel(ModelBase model)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.SearchViewModel.OnSearchElementClicked(NodeModel nodeModel, Point position)
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at Dynamo.UI.Controls.ClassInformationView.ExecuteSearchElement(ListBoxItem listBoxItem)
   at Dynamo.UI.Controls.ClassInformationView.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by mjkkirschner** [comment]
I knew this looked familiar:
https://github.com/DynamoDS/Dynamo/issues/5120

is this all your code, I want to debug this and see whats going on.

its the same stack trace, looks like somehow there is a "+" in the xml when the node's creation gets recorded for undo. May not be anything you are doing wrong, will need to look further.

**Comment by ksobon** [comment]
yes! but it looks like I didn't exactly solve the issue. Agrrr. I must have gotten lucky last time, but this happening again kind of makes me want to investigate deeper this time around. 

Yes, I am literally trying to create a node that has variable inputs and will combine them into a list. Of course once I have all of the inputs as a list I wrap them up into a <code>new RowContainer(inputList)</code> but that was going to be my next step. For now I am literally copying the List.Create node implementation with a different name.

**Comment by ksobon** [comment]
so it looks like i got this to work. I think that I made a mistake of sticking this whole thing into another class and that was causing some issues. anyways, i am no longer getting an error about the "+". Great!

Now, next step would be to be able to take all of the inputs, combine them into a List<object> and then instantiate a class object called RowContainer(List<object>) and return that as output. 

@mjkkirschner any examples that I can look at? i am going to guess that i need to implement some variation of the AstFactory function call but I am not sure which one/how. My container class looks like this: 

```C#

    public class RowContainer
    {
        public List<object> Contents;

        public RowContainer(List<object> contents)
        {
            this.Contents = contents;
        }

        public RowContainer AssignColMdValue()
        {
            // define md-x value
            string mdValue = "";
            if (12 % this.Contents.Count != 0)
            {
                // process divs with remainder
                double value = 12 / this.Contents.Count;
                mdValue = Math.Floor(value).ToString();
                // ignore the remainder at the moment
            }
            else
            {
                //process evenly spaced divs
                mdValue = (12 / this.Contents.Count).ToString();
            }

            foreach (object o in this.Contents)
            {
                try
                {
                    var bc = o as d3BarChart;
                    var tn = o as TextNote;
                    var lc = o as D3jsLib.d3LineCharts.d3LineChart;
                    var ac = o as D3jsLib.d3AreaCharts.d3AreaChart;
                    var sp = o as D3jsLib.d3ScatterPlots.d3ScatterPlot;

                    if (bc != null) { bc.ColMdValue = mdValue; }
                    else if (tn != null) { tn.ColMdValue = mdValue; }
                    else if (lc != null) { lc.ColMdValue = mdValue; }
                    else if (ac != null) { ac.ColMdValue = mdValue; }
                    else if (sp != null) { sp.ColMdValue = mdValue; }
                }
                catch (Exception) { }
            }
            return this;
        }
    }
```

Calling a function like this throws an error saying that it could not find a RowContainer() method

```C#
 [NodeName("RowContainer")]
    [NodeDescription("Some Description")]
    [NodeCategory("Mandrill.Nodes.Containers")]
    [IsDesignScriptCompatible]
    public class RowContainerUI : VariableInputNode
    {
        public RowContainerUI()
        {
            InPortData.Add(new PortData("Chart 0", "Input for charts."));
            OutPortData.Add(new PortData("RowContainer", "Row Container object."));

            RegisterAllPorts();

            ArgumentLacing = LacingStrategy.Disabled;
        }

        protected override string GetInputName(int index)
        {
            return "Chart " + (index + 1);
        }

        protected override string GetInputTooltip(int index)
        {
            return "Tooltip " + (index + 1);
        }

        protected override void RemoveInput()
        {
            if (InPortData.Count > 1)
                base.RemoveInput();
        }

        public override bool IsConvertible
        {
            get { return true; }
        }

        protected override int GetInputIndex()
        {
            return InPortData.Count - 1;
        }

        public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
        {
            if (IsPartiallyApplied)
            {
                var connectedInput = Enumerable.Range(0, InPortData.Count)
                                               .Where(HasConnectedInput)
                                               .Select(x => new IntNode(x) as AssociativeNode)
                                               .ToList();

                var paramNumNode = new IntNode(InPortData.Count);
                var positionNode = AstFactory.BuildExprList(connectedInput);
                var arguments = AstFactory.BuildExprList(inputAstNodes);
                var functionNode = new IdentifierListNode
                {
                    LeftNode = new IdentifierNode("DSCore.List"),
                    RightNode = new IdentifierNode("__Create")
                };
                var inputParams = new List<AssociativeNode>
                    {
                        functionNode,
                        paramNumNode,
                        positionNode,
                        arguments,
                        AstFactory.BuildBooleanNode(false)
                    };

                return new[]
                {
                        AstFactory.BuildAssignment(
                            GetAstIdentifierForOutputIndex(0),
                            AstFactory.BuildFunctionCall("_SingleFunctionObject", inputParams))
                    };
            }

            var func = new Func<List<object>, mandrillTypes.RowContainer>(mandrillTypes.RowContainer.byList);
            var funcCall = AstFactory.BuildFunctionCall(func, inputAstNodes);

            return new[] { AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(0), funcCall) };
}
}
```
ideas?

**Comment by mjkkirschner** [comment]
@ksobon so the next trick is that the function you call needs to be defined in a separate .dll (project usually) from the place where you define the `BuildOutputAST` method that calls it. So add your RowContainer type to a different project, I think you'll still need to import the other .dll though so that the VM knows about your type.

**Comment by mjkkirschner** [comment]
if you look at this sample https://github.com/DynamoDS/DynamoSamples/blob/a99f7f9b4340d883a11714d5a8bc5a6530a3bbf6/src/SampleLibraryUI/Examples/CustomNodeModel.cs#L185

which I am sure you have seen already, note that the method called here in BuilOutputAST is defined in another project (the zero touch sample project)

**Comment by ksobon** [comment]
Solved here: https://github.com/DynamoDS/Dynamo/issues/7033
