### ISSUE TITLE
dynamo crashes as soon as i hit run...

### ISSUE THREAD

**Issue by jankahre** [DynamoDS/Dynamo#6503]
## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by jankahre** [comment]
#
[Floor.zip](https://github.com/DynamoDS/Dynamo/files/231392/Floor.zip)

**Comment by kronz** [comment]
@jankahre this does not reproduce just with the file you have supplied.  Can you add teh Revit file or template you are running against?

**Comment by kronz** [comment]
Can't reproduce
