### ISSUE TITLE
Sandbox missing - Bug or feature?

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#6504]
## Dynamo version

1.0.0.910

## Operating system

Windows 7

## What did you do? 

Look for DynamoSandbox.exe

## What did you expect to see?

DynamoSandbox.exe

## What did you see instead?

Nada

**Comment by dimven** [comment]
Already asked about this one. Zach confirmed that it's coming back. It seems that now it's in transit between DynamoCore and DynamoRevit. One of the dailies had the executable inside the DynamoRevit folder, try checking in there.

**Comment by kronz** [comment]
@andydandy74 @dimven Yes, sandbox.exe is still there, in the Dynamo Revit folder.
