### ISSUE TITLE
Excel Data Import / Export Failure

### ISSUE THREAD

**Issue by TomasTar** [DynamoDS/Dynamo#6505]
## Dynamo version

0.7.1.9124; 0.7.3.3034; 0.9.4472.
## Operating system

Windows 7 Enterprise, System type: 64-bit.
## What did you do?

I have tested export import sample files: _ImportExportData to Excel_ and
_ImportExportExcel to Dynamo_ both files failed on my and colleague's destop on other colleague's destop works fine same as on few laptops, all PCs have same specifications same windows edition, Revit version, and Excel version. 
Only_ ImportExportCSV to Stuff_ file works fine on all PCs. 
## What did you expect to see?

Results.
## What did you see instead?

On_ Excel.ReadFromFile_ Node warning message: Excel.ReadFromFile operation failed same message on _Excel.WriteToFile_ node.
No data exported or imported to Dynamo / Excel,
![export failure](https://cloud.githubusercontent.com/assets/18613917/14740681/b104c552-0888-11e6-8044-61e96497dee2.png)
![data import failure](https://cloud.githubusercontent.com/assets/18613917/14740685/b41e61bc-0888-11e6-9dbb-0da8d557c589.png)

**Comment by jnealb** [comment]
@TomasTar Is Excel installed on these machines?

**Comment by TomasTar** [comment]
Hi Jnealb, Excel version 2007 on all machines. I had 2007, recently replaced by 2010. I have tested on both Excel versions on my machine.

**Comment by ThomasMahon** [comment]
Hi Tomas / Jneal

This is a registry issue with Microsoft Office 2007. If you install a newer version and then roll back to an older one (in this case 2010 back to 2007), the registry key for 2010 remains which is incompatible with 2007. That, at least, was the issue I had. To resolve you need to delete the registry key for 2010 or newer if you want to continue using 2007.

**Comment by TomasTar** [comment]
Hi Thomas / Neal

I have deleted Microsoft Office registry key for 2007, but still have the same issue. I didn’t roll back to an older version and I have Microsoft Office 2010 version only, so I’m in slightly different situation. Why did you roll back to 2007 version, if is anything to do with the Dynamo?

**Comment by jnealb** [comment]
@TomasTar @ThomasMahon We have validated the Excel nodes with Office 2010, certainly we may not be providing the appropriate message for unsupported versions of Excel. Is it possible for you to clean out all remnants of 2007, install 2010 fresh and try again?

**Comment by TomasTar** [comment]
Hi Neal /Thomas
IT technician done what you wrote: He cleaned out all remnants of 2007, and repaired 2010, then I had tested, as still the same issue he uninstalled Microsoft office 2010 32 bit and installed Microsoft office 2010 64 bit, still makes no difference. Do you have any other suggestions?

**Comment by jnealb** [comment]
@TomasTar Can you provide a view of the application console (under View) when this occurs? We may have more detail there.

**Comment by TomasTar** [comment]
Hi Neal,
Please see Import / Export views below.
![import export excel to dynamo](https://cloud.githubusercontent.com/assets/18613917/15038341/ee1a9efa-129a-11e6-8723-c37feafd9620.JPG)
![import export data to excel](https://cloud.githubusercontent.com/assets/18613917/15038347/f4dc85a0-129a-11e6-81c5-32d7fde4582b.JPG)

**Comment by jnealb** [comment]
@TomasTar @ikeough @ThomasMahon Thank you, we are tracking this with MAGN-10079.

**Comment by brencass** [comment]
I thought i will bring some information on this, as i am currently having this issue as well. 

Current System setup:
OS:Windows 8.1 - fully up to date
Dynamo versions: 0.8.2, 0.9.2 and 1.0
Excel Version: Office 2010 64bit professional -  full install and all updates installed
Note: it did work previously prior to a reformat of the system i did 6 months ago.

It seems as if it is not able to instigate the opening of the excel file, reason i say this is because the excel program does not open at all when it does on another machine that has the same install and setup.

Note: i am going to try a overwrite of the files from the pc that works onto the one that doesnt, to see if its a corrupt dll or something.

**Comment by SEANFRUIN** [comment]
SAME ISSUE HAS ANYONE FIGURED OUT A SOLUTION PLEASE!!!!!

**Comment by jnealb** [comment]
@SEANFRUIN Are you running Dynamo 1.2?

**Comment by brencass** [comment]
I had installed 1.2 then did this registry fix(below) and it worked for me, but I had not tried it with just 1.2 installed and no registry change.

"Excel nodes can be rendered non-functional by bad registry data. To correct this: Go to Start--> Run --> regedit. Browse to HKEY_CLASSES_ROOT-->TypeLib-->{00020813-0000-0000-C000-000000000046}. Delete the 1.8 key."

From: https://github.com/DynamoDS/Dynamo/wiki/Known-Issues

**Comment by SEANFRUIN** [comment]
Hi @jnealb I am have the issue on both 1.2 and 0.9. I have seen stuff about a bad key when updating windows apps. Still no solution.

**Comment by jnealb** [comment]
@SEANFRUIN Which version of MSFT Office are you running?

**Comment by SEANFRUIN** [comment]
@jnealb 2016

**Comment by jnealb** [comment]
@SEANFRUIN This is wip, tracked by MAGN-10831. Thanks for the report.

**Comment by dnegi123** [comment]
Sams issue using dynamo 1.2.1 and Office 2013 !!

**Comment by tripler123** [comment]
I have the same problem

**Comment by MiroSK** [comment]
Hi. Does that deleting of registry help? I have same problem at ver. Win10. Dynamo 1.3 Office 2016 Revit 2018.2 It was working and now it is not.

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Comment by yunmemory** [comment]
> Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

I met the same issue for Dynamo 2.0 and 2.01 version.

the error happened after I upgraded the MS Project to 2016.

I've tried re-install the dynamo, delete the 1.8 key. But none of them works. Could anyone provide any advice? Thanks.

**Comment by mjkkirschner** [comment]
@yunmemory can you try the x32 or x64 bit version of excel (what do you have installed currently?)

**Comment by yunmemory** [comment]
> @yunmemory can you try the x32 or x64 bit version of excel (what do you have installed currently?)

I have excel 2016 x32 version.

Do you think I should try excel x64 version?

**Comment by IrinaGalitskaya** [comment]
> > @yunmemory can you try the x32 or x64 bit version of excel (what do you have installed currently?)
> 
> I have excel 2016 x32 version.
> 
> Do you think I should try excel x64 version?

Hello, I was facing the same problem yesterday and it was solved by updating Microsoft OS to 64Bit so it is the same version as Microsoft OS. Thanks!

**Comment by QilongTang** [comment]
@IrinaGalitskaya  Thank you for the information!

**Comment by IrinaGalitskaya** [comment]
Hi all, 

Like I was writing, after Microsoft Office OS upgrading to 64Bit it started to work, but the next day I was facing the same problem with the script. I've solved the problem by modifying the Microsoft 365 (see attachment below) and it started to work again. Hope this can help somebody to solve the problem.
![Capture](https://user-images.githubusercontent.com/87368136/125813169-74f60e20-8540-4e90-9f05-f2075eaf2dbc.PNG)
