### ISSUE TITLE
PointAtParameter on selected Revit Mass Face ignores Brep extents 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6508]
## Dynamo version

0.9.2
## Operating system

Win10
## What did you do?

Created an array of points using cross product lacing on a selected face from a Revit mass. The mass is orthogonally extruded. However, when the edge is lifted such that the face is sheared, there there is a bug as described below and shown in the attached images.
## What did you expect to see?

That the points are generated within the parameter space of the brep. 
## What did you see instead?

The points are generated within an invisible 'bounding box' of the extents of the selected face/surface

<img width="927" alt="orthogonal extrusion" src="https://cloud.githubusercontent.com/assets/18601851/14763464/5c585ac6-098e-11e6-9f0c-581212b44ffe.PNG">
<img width="970" alt="sheared extrusion" src="https://cloud.githubusercontent.com/assets/18601851/14763465/5c5cdd30-098e-11e6-9020-ac30de4267d6.PNG">
## The plot thickens

If the mass is edited at a corner point - if a corner is pulled in such a way that the selected face becomes double-curved, then the points map within its UV parameter space as expected.
<img width="945" alt="double curved extrusion" src="https://cloud.githubusercontent.com/assets/18601851/14763507/3caa7dd4-098f-11e6-8382-0fc150e8e30f.PNG">

**Comment by mjkkirschner** [comment]
I believe these are the same issue: https://github.com/DynamoDS/Dynamo/issues/2210

**Comment by ThomasMahon** [comment]
Thanks, seems like the same issue. Will just have to rebuild for now.

**Comment by aparajit-pratap** [comment]
... and #5475

**Comment by aparajit-pratap** [comment]
Tracked here: MAGN-9350, 9967

**Comment by avidit** [comment]
duplicate https://github.com/DynamoDS/Dynamo/issues/2210 https://github.com/DynamoDS/Dynamo/issues/5475
