### ISSUE TITLE
Improvement: Show Labels includes node name and shows in Revit project

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6511]
## Dynamo version

0.9.2
## Operating system

Win 10
## Improvement Suggestion

I would like to see Show Labels display the node name AND both node name and index markers in Revit too. Another issue is creating or placing Revit elements. If I place a load of adaptive components, they only show in the Revit project which means I cant view the labels. Ideally, I would want to see their Labels. I am supporting a number of my clients implementing and training Dynamo and the biggest complaint from the users is the lack of labelling of elements between the applications. 

Also, it would be very useful to control the symbol size or more specifically, to be able to control the size of the XYZ handles and labels, etc.

**Comment by smangarole** [comment]
@Racel and @kronz Please note the enhancement requests.
