### ISSUE TITLE
Problem generating sheets

### ISSUE THREAD

**Issue by IFChaos** [DynamoDS/Dynamo#6515]
## Dynamo version

9.2
## Operating system

Windows 7
## What did you do?

I'm generating sheets by level and then placing views in these sheets.
## What did you expect to see?

Each time i change the level the name of the sheet changes and new sheets should be created.
## What did you see instead?

It destroys my previous sheets. No matter if you restart Revit, the computer, or whatever you try, Dynamo always destroy your previous sheets (if you created them with dynamo) and replace them. I noticed that when the sheets have no views inside this problem vanishes.

**Comment by kronz** [comment]
@IFChaos can you upload as simple an example as you have?
Thanks
Zach

**Comment by IFChaos** [comment]
Yes, here is an example.

![horror case](https://cloud.githubusercontent.com/assets/12625508/14853354/78c72994-0c8b-11e6-81b3-b2983fd9527d.jpg)

**Comment by kronz** [comment]
@Randy-Ma Is there modification API for Sheets?  Or do they need to be destroyed and recreated?  Seems like there is no element binding going on here.

**Comment by sixtysecondrevit** [comment]
Thanks for your feedback. As this is a Revit related issue, please re-open and link to the original issue here: https://github.com/DynamoDS/DynamoRevit/issues
