### ISSUE TITLE
bug report, Excel.ReadFromFile node

### ISSUE THREAD

**Issue by Finearcltd** [DynamoDS/Dynamo#6517]
## Operating system

Windows 7 Pro
## What did you do? 

tried to use the Excel.ReadFromFile node as part of the Dynamo video tutorials. The node that appears
in the tutorial does not exist in Dyanmo any more. The new one seem to fail to do it's jog.

## What did you expect to see?
the node working as in the tutorial, reading the data from the Excel strings.

## What did you see instead?

Warning: One or more of the input types are not matching. Couldn't find a version of ReadFromFile that takes arguments of type (string,string,string)

![screen shot 04-25-16 at 04 38 pm](https://cloud.githubusercontent.com/assets/18655795/14785543/ff8f9684-0b03-11e6-91ce-0d3d51b9d48b.PNG)

**Comment by dimven** [comment]
This is not really a bug per se. You need the "File.FromPath" node between the file string and the read node.

**Comment by ThomasMahon** [comment]
Just to add to Dimitar's comments, Finearcltd you also need to be mindful of datatypes: readAsStrings input takes a bool not a string. Use the bool node.

**Comment by Finearcltd** [comment]
Thank you guys! that helped. do you happen to know which node replaces the ExcelToPoint one?
