### ISSUE TITLE
Dynamo Crashed

### ISSUE THREAD

**Issue by vasudha-dixit** [DynamoDS/Dynamo#6519]
## Dynamo version
0.9.2
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 7
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Tried to delete a node
(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?
Crash
(Fill in here)

**Comment by ikeough** [comment]
Can you provide exact steps to reproduce?

**Comment by vasudha-dixit** [comment]
Hi there,

I was trying to build a cube in Dynamo and deleted the Range node which was connected to list nodes for input when Dynamo crashed. Hope this helps.

Regards,
Vasudha

**Comment by jnealb** [comment]
@vasudha-dixit @ikeough We believe this is fixed with the 1.0 release, which is coming very soon. If you can use the daily builds in the meantime, please let us know if the error recurs.

**Comment by vasudha-dixit** [comment]
Sounds good. Thanks!
