### ISSUE TITLE
Document.ActiveView doesn't update

### ISSUE THREAD

**Issue by moethu** [DynamoDS/Dynamo#6525]
## Dynamo version

0.9.2.4472
## Operating system

Windows 7
## What did you do?

Document.ActiveView keeps the active view from when it has been placed. Changing the active view and placing another Node will contain the new active view (see Image). Don't know if this has been fixed in future versions and if this behavior is expected?
![2016-04-26_10h11_05](https://cloud.githubusercontent.com/assets/8201465/14813008/993e27da-0b97-11e6-9f33-4c3c97fca9a5.png)

**Comment by ksobon** [comment]
@moethu based on how that node is coded (ZT), it's expected behavior. An argument could be made that this should be a `NodeModel` node with a `DocumentUpdated` event subscription, that would force it to re-execute. I am not sure which way the team wants to go on this one. 

@ikeough @jnealb @kronz @mjkkirschner thoughts?

**Comment by moethu** [comment]
But then Document.ActiveView is very misleading since its a buffered view from an ActiveView at the time the node has been placed into the canvas.

**Comment by ksobon** [comment]
Agreed. So let's get @kronz and @mjkkirschner to agree that this should be moved to a `NodeModel` with proper events, and we will also need a Migration strategy for that. Can we assign this to someone and create a task?

**Comment by mjkkirschner** [comment]
@ksobon I agree the current behavior if as reported here is not as you would expect.

I think the `nodeModel` approach is one way, - we might also be able to use element binding to the view to kick off another execution, but it doesn't make as much sense as other constructor nodes, and I guess the nodeModel version will be more straight forward.

Does this happen with Dynamo 1.3 or 2.0?

**Comment by sixtysecondrevit** [comment]
Thanks for your feedback. As this is a Revit related issue, please re-open and link to the original issue here: https://github.com/DynamoDS/DynamoRevit/issues

**Comment by ksobon** [comment]
@sixtysecondrevit I am not sure it's a good idea to close these issues and ask people to re-open them after 2.5 years of inactivity. If anything can you guys close them open again in DynamoRevit repo? Otherwise it's virtually a lock that people won't open them again.

**Comment by sixtysecondrevit** [comment]
> If anything can you guys close them then open again in DynamoRevit repo?

This was something we discussed, but if we were to open the issue, the original owner is lost. The hope is that the original poster would re-evaluate if this was still an issue for them.

**Comment by ksobon** [comment]
@sixtysecondrevit ok so you are telling me that losing the owner of the issue, is more important than losing the issue itself? That sounds suspect. This is a valid request that @moethu made, and whether he wants to follow through with this long term, it should be retained. 

Now, there might be some issues that are a little bit more vague like a bug that you all can't recreate and it really is up to the user to provide extra info, or check if its there after subsequent releases. In these cases i would probably just close them and leave it up to the user. However, in this particular case it's something that is easily reproducible and would be a valuable addition to the DynamoRevit package. I would keep it around even if @moethu doesn't have time to follow through with it. 

Of course i might be wrong on that. 

Ps. CC-int the original poster on the issue would also send them a notification when you re-create it. They can choose then to mute any further notifications or follow the issue. 

Ps2. Obviously  after 2.5 years of inactivity, I also doubt anyone is following these anymore.

**Comment by moethu** [comment]
well, yes I see it's in the wrong repo, but I agree with @ksobon - asking people to reopen the issue might result in lost issues. anyway I'll create it in DRevit

**Comment by moethu** [comment]
but I certainly won't try to reproduce it again :)

**Comment by sixtysecondrevit** [comment]
Thanks for the comments @ksobon and @moethu. The feedback is very appreciated. Essentially , we are working to clear up some of these issues that fell through the cracks, so you will see some movement on these items. That being said, we are looking at auto migrating the Revit specific ones.
