### ISSUE TITLE
Core If function error

### ISSUE THREAD

**Issue by Hundread** [DynamoDS/Dynamo#6536]
## What did you do? 
used the core If function to put a list of items into false, a blank list into true and a List.IsEmpty into test.

## What did you expect to see?

When the condition (is list empty) returns false, the result from If should be the input from false.

## What did you see instead?

empty list

Image attached shows the issue. Same is happening on 0.8.2 Dynamo so presumably this is a problem in IronPython (I'm running 2.7.5.0)?

![dyn](https://cloud.githubusercontent.com/assets/5745589/14847121/ea64c0ca-0c5e-11e6-8b96-1def4c412c29.JPG)

**Comment by ThomasMahon** [comment]
Use the scopeIf node and it should work. If you want to return a singleton with one condition and a list with the other, the scopeIF is the only way. The If node on the other hand always replicates and returns a list regardless (try using null as the true input and you'll see it happen).

**Comment by ke-yu** [comment]
If node is confusing. We should change it to the other name. @Racel ?

**Comment by Hundread** [comment]
Sadly no change using Scopeif. I've managed to resolve the issue but only by uninstalling all versions of Dynamo and Iron Python, cleaning out the route directory and reinstalling.
