### ISSUE TITLE
Bug report - Revit regen

### ISSUE THREAD

**Issue by Finearcltd** [DynamoDS/Dynamo#6549]
## Dynamo version

9.2.4472
## Operating system

Windows 7 pro
## What did you do?

delete nodes containing image sampling
## What did you expect to see?

retrun of previous condition in Revit
## What did you see instead?

No change at all! only the Dynamo screen updated. To get the Revit screen to update I need to relaod the new node status in Dynamo and hit Run anew.

**Comment by ikeough** [comment]
@Finearcltd Can you provide more information such as a file to reproduce the issue or a screen shot?
