### ISSUE TITLE
Geometry error

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#6553]
## Dynamo version

1.0.0
## Operating system

W7
## What did you do?

Create a solid by loft of set of cross sections
## What did you expect to see?

A well formed solid
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/14221455/14925151/4022e7ba-0e46-11e6-8fb5-501e6450761d.png)

**Comment by ikeough** [comment]
@paoloemilioserra How are the cross sections formed that you are lofting together?

**Comment by paoloemilioserra** [comment]
I'm reading the points of the subassemlies in Civil3D (the "sketchy-ish" representation is because the model is far away from the origin). for each subassembly I create a surface from perimeter points, retrieve the perimeter curves, join them in a Polycurve and loft them all toghether, not in pairs, what you see here is also the result of multiple lofts. In previous versions I had funky geometries from the same dataset but in a different location

![image](https://cloud.githubusercontent.com/assets/14221455/14947869/f9597b96-1039-11e6-9841-abedac24a936.png)

**Comment by johnpierson** [comment]
@paoloemilioserra , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
