### ISSUE TITLE
Dynamo Mesh into surface

### ISSUE THREAD

**Issue by Finearcltd** [DynamoDS/Dynamo#6559]
Anybody knows how to turn Dynamo Mesh into Surface?

**Comment by ikeough** [comment]
@Finearcltd You can try posting this question on the Dynamo [forums](http://dynamobim.org/forums/forum/dyn/). Please post as accurate a description of what you are trying to do and your desired outcome. I'm closing this issue here as it does not relate directly to Dynamo development.
