### ISSUE TITLE
Improvement: Inconsistent input names for List methods

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6560]
## Dynamo version

1.0.1
## Operating system

Win 10
## Improvement Suggestion

There is a minor improvement I would like to suggest for the naming of the inputs for some of the List methods. You will see in the image that the `List.Create`node and `List.Join` node expects 'List0', 'List1', etc. As list indexing always starts from 0, this nomenclature goes without saying. However, for the other nodes I've included in the graph, they name the inputs with 'List1', 'List2', etc. While this isn't really an issue, its worth mentioning as a new user I was introducing to Dynamo and data structures found this quite odd (having been told all list, regardless of rank, start from index 0), and I have to concur. Any chance the naming of such inputs can be made consistent across the board?

![capture](https://cloud.githubusercontent.com/assets/18601851/14941805/dd57ec00-0fa0-11e6-9b8c-ab0ed5ef3f2d.png)

**Comment by johnpierson** [comment]
Adding this to the backlog, [QNTM-5936](https://jira.autodesk.com/browse/QNTM-5936)

**Comment by mjkkirschner** [comment]
should be addressed for core nodes (not geometry)
