### ISSUE TITLE
Improvement: Separable Dynamo Graph view and Geometry view 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6561]
## Dynamo version

1.0.1
## Operating system

Win 10
## Improvement Suggestion

It would be very useful to be able to open two Dynamo views, 1. showing the graph, 2. showing the geometry view. Seeing both simultaneously would speed up workflow and be more intuitive, particularly to designers!

Also, is it possible to enable the geometry view to 'grey out' like what happens to the graph view when switching to the geometry view? It would make working in the graph more legible without needing to push the geometry out of view of the background.

**Comment by ikeough** [comment]
@kronz @Racel To consider given our conversations about multiple workspaces.

**Comment by smangarole** [comment]
@ThomasMahon Dynamo Team is working on an improved UI, which we will make available to our users. Your specific request(s) are addressed in this UI, as well as other workflows.
@Racel and @kronz please note.
