### ISSUE TITLE
Unit Types node not working

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#6562]
## Dynamo version

1.0.0 stable, Revit 2016
## Operating system

Win 7 Entreprise
## What did you do?

Placed a Unit Types node and hit run
## What did you expect to see?

A node being not red and return a Unit Type.
## What did you see instead?

The Unit Types node does not work. It reports:

 _"Warning: Whilst preparing to run, this node encountered a problem. Please talk to the creators of the node, and give them this message:

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index"_

(I'm using the input to a PointAnalysisDisplay.ByViewPointsAndValues and it doesn't seem to mind. It takes a null value and let the resulting analysis view be unitless.)

**Comment by ksobon** [comment]
@josols is this still an issue in 1.3? It looks good on my machine: 
![image](https://user-images.githubusercontent.com/529781/27255929-a56feeee-5376-11e7-9de2-b9571bf3725f.png)

**Comment by josols** [comment]
Haven't looked into this in a while, but no, it doesn't seem to be a problem any more. I'll close.
