### ISSUE TITLE
Pass null as default argument for Zero Touch nodes

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#6564]
I am not sure this is possible but I would like to be able to pass a null value as a default argument for Zero Touch node input. The reason I want to do that, is because I want to give users ability not to specify certain inputs and still receive output from the node that is not a _SingleFunction node. Ideas? 

Tried this, doesn't work: 

```C#

public static RVT.OverrideGraphicSettings OverrideGraphicsSetting(
            [DefaultArgument(null)] Color projectionLineColor,
            [DefaultArgument(null)] int projectionLineWeight,
            [DefaultArgument(null)] Element projectionLinePattern,
            [DefaultArgument(null)] Color projectionFillColor,
            [DefaultArgument(null)] Element projectionFillPattern,
            [DefaultArgument(null)] int transparency,
            [DefaultArgument(null)] Color cutLineColor,
            [DefaultArgument(null)] int cutLineWeight,
            [DefaultArgument(null)] Element cutLinePattern,
            [DefaultArgument(null)] Color cutFillColor,
            [DefaultArgument(null)] Element cutFillPattern
            )
```

cc: @ikeough @mjkkirschner

**Comment by ksobon** [comment]
ahh this did the trick: 

```C#
public static RVT.OverrideGraphicSettings OverrideGraphicsSetting(
            [DefaultArgument("archilab.View.GetNull()")] Color projectionLineColor,
            [DefaultArgument("archilab.View.GetNull()")] int? projectionLineWeight,
            [DefaultArgument("archilab.View.GetNull()")] Element projectionLinePattern,
            [DefaultArgument("archilab.View.GetNull()")] Color projectionFillColor,
            [DefaultArgument("archilab.View.GetNull()")] Element projectionFillPattern,
            [DefaultArgument("archilab.View.GetNull()")] int? transparency,
            [DefaultArgument("archilab.View.GetNull()")] Color cutLineColor,
            [DefaultArgument("archilab.View.GetNull()")] int? cutLineWeight,
            [DefaultArgument("archilab.View.GetNull()")] Element cutLinePattern,
            [DefaultArgument("archilab.View.GetNull()")] Color cutFillColor,
            [DefaultArgument("archilab.View.GetNull()")] Element cutFillPattern
            )
```
I just set up a small utility method like that: 

```C#
 [IsVisibleInDynamoLibrary(false)]
        public static object GetNull()
        {
            return null;
        }
```
Also, making sure that int input types are actually declared with "int?" to make sure that they are nullable. Now I can do this: 

![image](https://cloud.githubusercontent.com/assets/529781/14945571/0d429cb2-0fe2-11e6-8b7f-3fcc4c52746e.png)

Idk, maybe its a little hacky and there is a better way. Just let me know. Cheers!

**Comment by pflaumingo** [comment]
@ksobon is this the method you've found most useful still? It's not a bad solution, but thought I'd check if there is something a little more direct. I've got a similar scenario with objects that have a couple required parameters and several optional inputs. Dynamo doesn't seem to accept null as a default value for strings, support nullable data types or set default object references to null.

**Comment by ksobon** [comment]
Yeah thats the only way that i found to make it take a null as a default value, null a string, int etc input. Sorry mate.

**Comment by sanzoghenzo** [comment]
It's still the case, I'm running into this myself.
I assumed that `null` default value worked just like the other default argument values (without using the `DefaultArgument` decorator as the Zero Touch Development wiki page states).
Is it a bug or an intended behavior?
Using dynamo 2.3.0.5885.

**Comment by michaldengusiak** [comment]
Hi, we just tried this method and does not work
Using dynamo 2.3.0.5885

@ksobon 
do we need any other reference apart from: 
`Autodesk.DesignScript.Runtime`

Is there any rule for `defaultArgumentExpression` input for DefaultArgument?
Do we need to provide the full name with namespace?

Can we re-open this ticket seems more people got this issue?

**Comment by ksobon** [comment]
@michaldengusiak have a look at this: https://github.com/ksobon/archilab/blob/dynamo-2.0.0/archilab/Revit/Selection/Selection.cs it's been working for me for a while.

**Comment by timrutter** [comment]
is there any reason why you're not just using [DefaultArgument("null")] ?  as opposed to [DefaultArgument(null)].  DefaultArgument expects a string and in your original code you're passing a null string rather than the string "null". The above solution seems a bit odd to me.
