### ISSUE TITLE
Custom node not working but works if 'expanded'

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#6574]
## Dynamo version

0.9.2
## Operating system

Windows 7
## What did you do?

Using a custom node from the BVN package
## What did you expect to see?

Doors should update based on room name
## What did you see instead?

Doesn't work. Custom node works if copyed and pasted into a new file (not a custom node). However when packaged up into a custom node it fails.

[Door.RenumberByRoom.zip](https://github.com/DynamoDS/Dynamo/files/248097/Door.RenumberByRoom.zip)

**Comment by sharadkjaiswal** [comment]
@ke-yu any idea, what must be going on?

**Comment by CharlP6** [comment]
I have the same problem. I created a custom node from a working script, and when I use it in a subsequent script, it only updates if I break and remake connections between nodes. Attached is an image of my working script, the custom node, and the custom node used in a script:

![script compilation](https://user-images.githubusercontent.com/18455926/32827394-bbc627f4-c9f4-11e7-810d-85fb8d8b7c7c.png)
