### ISSUE TITLE
Disabling "Revit Background Preview" disables Dynamo's background preview for the next session.

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#6584]
(not sure if I should classify this issue under Revit or under Core)

## Dynamo version

1.0.0.1180 (also happens in 0.91/0.92)

## Operating system

Windows 7

## What did you do? 

Turned off the Revit background preview. Everything worked as expected. However once Dynamo was restarted, the Dynamo background preview was also turned off.

## What did you expect to see?

Dynamo's BGP should have remained ON.

## What did you see instead?

Dynamo's BGP was turned OFF. Not a show-stopping bug but it gets really annoying after a few times...

**Comment by ksobon** [comment]
Yup, I noticed that too.

**Comment by jnealb** [comment]
@dimven @ksobon @kronz This is tracked as MAGN-9757.

**Comment by ke-yu** [comment]
Seems has been fixed in https://github.com/DynamoDS/Dynamo/pull/6649.
