### ISSUE TITLE
Geometry.Split breaks up polysurfaces into constituent surfaces making the results unusable

### ISSUE THREAD

**Issue by mccrone** [DynamoDS/Dynamo#6586]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0
## Operating system

Windows 7
## What did you do?

![splitproblem](https://cloud.githubusercontent.com/assets/6430819/15086673/5da337f8-13b0-11e6-930f-74fea14273fa.png)

1 polysurface contains 3 surfaces.
A single line is used to split the single polysurface, and the Geometry.Split command returns 6 surfaces.
## What did you expect to see?

2 polysurfaces, each containing 3 surfaces.
## What did you see instead?

6 individual surfaces.

The problem is that the current behavior of the Geometry.Split node makes it nearly unusable with polysurfaces.  There is no algorithmic workaround to stitch the polysurfaces back together once the information has been lost about which constituent surfaces belonged with which other constituent surfaces.

**Comment by mccrone** [comment]
Attached is the dyn as a .txt.

[SplitSurface.txt](https://github.com/DynamoDS/Dynamo/files/253079/SplitSurface.txt)

**Comment by ke-yu** [comment]
cc @aparajit-pratap @Randy-Ma

**Comment by kronz** [comment]
We've had some discussion about this a long time ago.  The summary from Patrick was that "The geometry library offers no guarantee that geometry objects on both sides of a split are kept together, the array can return any number of items, and it is assumed the user will sort though them to find the correct pieces to stick together.  This would add a substantial amount of complexity to the geometry library (ie lots of future bugs), and would be a serious undertaking."  
Essentially, this is not something that we get from the geometry engine and would need to build from scratch.  Not to say that we shouldn't do it, but just that it's expensive
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-4328

**Comment by mccrone** [comment]
I can definitely understand that that will be difficult since the geometry library doesn't give this for free.

My reason: I ran into the need for this feature while working on a paneling problem.  The surface can only accurately be modeled as a polysurface, which makes it impossible to use simpler tools (like Paneling Tools for Rhino) that work with surface parameters.  Rhino, and therefore Grasshopper, have the ability to divide polysurfaces and also keep their pieces attached in a meaningful way.  Until the feature is available in Dynamo, Rhino/Grasshopper will remain the better tool for problems involving polysurfaces and polycurves (#6581), and likely the better tool for paneling in general.  But I'd rather do this directly in Revit via Dynamo.

**Comment by dimven** [comment]
Hi @mccrone 
Is it possible to change the split order? First you do the vertical single split and then you do horizontal multi split for each resulting surface.

Alternatively, if you could do a 2d analysis of the resulting faces and the splitting tool, you should be able to stitch them back together:

![2016-05-10_14-31-42](https://cloud.githubusercontent.com/assets/7148394/15137378/0bedea16-16bc-11e6-829d-45ada00fd33f.png)

**Comment by mccrone** [comment]
@kronz apparently not _so very_ expensive :P

Now available in Ampersand.  PolySurface.Split.

![image](https://cloud.githubusercontent.com/assets/6430819/15164895/dde7b290-16df-11e6-951c-188508d256f5.png)

Answer is to explode the polysurface into individual surfaces, perform a split operation on every single one, throw it all together in a soup of surfaces, and use graph search algorithm to sort them into appropriate buckets.  Two special sauces: the rules about whether two surfaces belong together (must touch via a point or a curve but not if the point intersects the tool or if the curve intersects the tool at more than one point) and a depth-first search algorithm.

@dimven I couldn't do a 2D analysis because the polysurface I am trying to divide has a lot of special conditions.  Also, geez, you know DesignScript quite well.

Put it in Dynamo!

**Comment by kronz** [comment]
@aparajit-pratap what do you think?  Seem like a transferable and robust approach?

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
