### ISSUE TITLE
Improvement: Excel.ReadFromFile and Excel.WriteToFile inconsistent file input datatypes

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6590]
## Dynamo version

1.0.0

## Operating system

Win 10

## Improvement Suggestion
I notice that the Excel.ReadFromFile and Excel.WriteToFile use different datatypes as the file path input.

The Excel.WriteToFile uses a string input whereas the Excel.ReadFromFile doesn't and requires an additional File.FromPath node? I think the path input datatype should be consistent.

*Also, very minor, but simply for consistency, the file inputs for both nodes should be named: filePath

![excel nodes](https://cloud.githubusercontent.com/assets/18601851/15091648/840d33ac-1447-11e6-8597-067fb9f29a6e.jpg)

**Comment by andydandy74** [comment]
No, this is by design. The File.FromPath node tracks will dirty once the monitored file has changed (which makes sense when reading but not when writing a file).

**Comment by ThomasMahon** [comment]
@andydandy74 That does make sense - thanks for pointing it out.
