### ISSUE TITLE
Unwarranted warning

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6593]
## Dynamo version

1.0.1.1250
## Operating system

Windows 10
## What did you do?

Opened a fresh Dynamo session of an error free definition.
## What did you expect to see?

All nodes having the same color, with no indication of any errors.
## What did you see instead?

A yellow code block with a warning informing that a method hasn't been found even though the method/function is available in another code block.

Does not cause any real trouble as the file works fine if the warning is ignored and the definition is Run.

![20160509-1](https://cloud.githubusercontent.com/assets/5621624/15102426/52e76e4c-15bd-11e6-9af5-d297b9b37346.png)

**Comment by smangarole** [comment]
We have seen this happen sporadically but we do not have concrete steps to reproduce. We are working on making changes in the language, which means that the behavior may change. Closing this one for now.
