### ISSUE TITLE
Hints in custom node not showing in 1.0.0

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#6598]
## Dynamo version

1.0.1

## Operating system

Windows 7

## What did you do? 

Updating BVN Dynamo package to version 1.0.0

## What did you expect to see?

Custom nodes should be copied across unchanged 

## What did you see instead?

The custom nodes in 1.0.0 have lost all the comments and hints from the inputs

**Comment by riteshchandawar** [comment]
@ke-yu Can you please take a look at this.

Thanks,
Ritesh

**Comment by ParametricMonkey** [comment]
@ke-yu can you please take a look at this. its been quite a while since submitted

**Comment by ParametricMonkey** [comment]
resloved. updated to new Dynamo WIP
