### ISSUE TITLE
Improvement: Create new note placement a nuisance

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6601]
## Dynamo version

1.0.0

## Operating system

Win 10

## Improvement suggestion
Admittedly this is minor, but an annoyance nonetheless: whenever a new note is added to the graph, it centres...which (well for me anyway) almost always means its 'buried' underneath a node giving the impression no new note has been added to the graph. I then have to shift nodes around to find it! 

Any chance it can be added to the graph ABOVE all nodes so it can easily been seen?

**Comment by andydandy74** [comment]
Agreed. I'd like to see the ```New Note``` command as a right-click option on canvas which should place the node where I clicked.

**Comment by ke-yu** [comment]
Fixed in #6777
