### ISSUE TITLE
Impovement: Edit Node Name dialog behaviour improvements

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6604]
## Dynamo version
1.0.0

## Operating system

Win 10

## Improvement Suggestion
When renaming nodes, I find it odd that pressing the Enter key creates a new line...and more text can be added to the node name? I would expect the Enter key to simply accept my input and exit out of the Edit Node Name dialog. Any chance this behaviour can be changed?

Renamed node:
![rename node](https://cloud.githubusercontent.com/assets/18601851/15161915/14385f4e-16f8-11e6-99b6-efaf5384413f.JPG)

More lines of text added after pressing the Enter key:
![new lines](https://cloud.githubusercontent.com/assets/18601851/15161921/2dd9c9ba-16f8-11e6-9f99-8da50024aeaa.JPG)

**Comment by andydandy74** [comment]
Strange behavior indeed, especially since Node titles on canvas are constrained to a single line in any case. ;-)

**Comment by riteshchandawar** [comment]
@rk-lakshmanan Can you take a look at this and fix this behavior.

**Comment by rk-lakshmanan** [comment]
@riteshchandawar  Created PR for the issue:https://github.com/DynamoDS/Dynamo/pull/6618

**Comment by aparajit-pratap** [comment]
@ThomasMahon this should be fixed in the next daily. Please let us know otherwise.
