### ISSUE TITLE
Static methods fail in Imperative DesignScript code

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6620]
## Dynamo version

1.0.0
## Operating system

Win 10
## What did you do?

Used a static method Curve.PointAtParameter() to put a point on a list of curves in an imperative DesignScript def. I used a for loop to iterate a collection of closed curves.
## What did you expect to see?

A point at the specified parameter on each of the curves iterated by the loop
## What did you see instead?

nulls.

Using the same static method in a code block works as expected. Using the same method non-static works in imperative code. I suspect this behaviour is 'by design', but I would expect to use either paradigm without limits. If that is the case, this behaviour is also not good for new users looking to develop coding skills as IMHO its too abstract and perhaps should be improved/simplified/more flexible/more concise etc, etc, etc - it is supposed to be a scripting language after all.

![static methods fail in designscript](https://cloud.githubusercontent.com/assets/18601851/15229747/5a4ad776-188a-11e6-930a-38f906fdcbf5.JPG)

**Comment by ke-yu** [comment]
Imperative language block is broken. :(

**Comment by ke-yu** [comment]
@ThomasMahon  Fixed in #7245.
