### ISSUE TITLE
Improvement: String.Format method needed!

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6621]
## Dynamo version

1.0.0

## Operating system

Win 10

## Improvement Suggestion
I was looking for a String.Format (same as c# method) node and discovered there isn't one!

Any chance one can be added to the library, or DesignScript at the very least?

**Comment by kronz** [comment]
@ThomasMahon please try "String from Object".  If this doesn't do what you need, please re-open and describle the desired behavior
