### ISSUE TITLE
Improvement: Inaccurate Menu Sub Grouping

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6638]
## Dynamo version

1.0.1.1364
## Operating system

Windows 10
## What did you do?

Tried to visually interpret the action of a node according to it's grouping (_Create, Action_ or _Query_)
## What did you expect to see?

Nodes that extract and provide information to be grouped under _Query_
## What did you see instead?

In many cases nodes are grouped under Create, even though they don't create anything.
One such case...
![20160517-2](https://cloud.githubusercontent.com/assets/5621624/15315062/195c536e-1c33-11e6-9461-15e142840005.png)
None of the above nodes create anything.

**Comment by andydandy74** [comment]
Also see #5613

**Comment by johnpierson** [comment]
Seems to be resolved int 2.0.1
