### ISSUE TITLE
Improvement: Node 'Show Label' settings UI improvements

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6640]
## Dynamo version

1.0.0
## Operating system

Win 10
## Improvement Suggestion

The Show Labels setting is pretty useful to visualise data structure - I'm finding with new users its invaluable. However, there are also some improvements that would aid usability:
1. On even average sized graphs it becomes difficult to decipher which node the displaying labels are emanating from. This is a big problem when all you want to do is switch them off! An icon or some other marker on the nodes to indicate that the labels of the node are active would be a big aid. 
2. A setting in the Edit menu (or right-click quick menu) which can globally set any active Show Label setting to off
3. Colour - designers are, by nature, visual so colour coding nodes when their state changes is very helpful. If the icon/marker suggestion is too discreet, nodes which change colour would be very helpful 

Take this graph - not very big or complex, yet its very easy to lose track of the nodes that have their labels switched on:
![show labels](https://cloud.githubusercontent.com/assets/18601851/15323344/7c3a3c02-1c39-11e6-9f47-0ad71753b670.JPG)

**Comment by smangarole** [comment]
@ThomasMahon We won't be working on WPF (UI) improvements for now. 

Please go through this blog post for more information on what's happening with the Dynamo Project: http://dynamobim.org/whatre-they-building-in-there/
