### ISSUE TITLE
Node rendering draws text at all scales on paste

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/Dynamo#6642]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0.0
## Operating system

Windows 7
## What did you do?

Select some components and paste
## What did you expect to see?

typically, node rendering hides node text labels below a certain zoom threshold, and then displays them when you zoom in. 
## What did you see instead?

When pasting a component, text is displayed at all zoom thresholds, meaning that at one moment some components display text while others do not. 
![image](https://cloud.githubusercontent.com/assets/2157902/15335493/9852d19a-1c40-11e6-85ad-1fe1ac322dd0.png)

**Comment by smangarole** [comment]
@AndrewHeumann This is a minor flaw, which may be useful in some cases. We will won't be fixing this issue. 
Thanks,
Sid
