### ISSUE TITLE
Improvement: Shift- and Ctrl- window select to add/remove nodes from selection

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/Dynamo#6643]
Currently (as of 1.0.1.1157), Dynamo supports adding one node at a time to the current selection while shift is held down. However, it is impossible to modify your selection otherwise - you cannot use ctrl (or shift or alt or anything) to _remove_ an item from the selection, and you definitely cannot add multiple items to a selection by holding down shift and performing multiple window selects. This seems like a UI no-brainer.

**Comment by ke-yu** [comment]
Fixed in #6643. Pressing shift, you could either adding a node to the selection by clicking a node, or do window selection.

**Comment by ke-yu** [comment]
FYI @Racel

**Comment by Racel** [comment]
Nice work, @ke-yu. We might considering re-opening this, because we did no address the "removing" of an item yet. Users should be able to remove an single item by clicking or use a window to remove multiple items. I suggest that we use "Shift" for add/removal toggle. Let me know if this makes sense or if you have any other thoughts.

**Comment by AndrewHeumann** [comment]
Can I suggest that we not use shift for removal? it is more common to use Shift to add and Ctrl to remove from selection - and using the same key for both is confusing, and "toggle" behavior makes it hard to grow a selection that's complex (If I go over the same components twice, it will deselect the ones I already selected).

**Comment by gregmarr** [comment]
I think more common is Shift for add and Ctrl for toggle.

**Comment by Racel** [comment]
Thanks, @AndrewHeumann and @gregmarr. 

@ke-yu - Let's use Shift for add and Ctrl for toggle when we implement "remove from selection"

**Comment by ke-yu** [comment]
@Racel , @samuelcwl 's PR supports Shift to remove a selected node from selection as well. 

Can we use one key, either Shift or Ctrl for both add/removal? Otherwise we have to switch between keys.

**Comment by Racel** [comment]
@ke-yu - As @AndrewHeumann mentions, with one key, it is often difficult to expand/contract selections with a "toggle" mechanism. 

How about we do this:
- Shift for add/remove toggle (this will likely be the most discoverable, so I think it would be good to make this the toggle)
- Shift+Ctrl for add only
- Ctrl for removal only

I looked through a bunch of other programs (graphics editing, 3d modeling, etc.) for examples, selection methods vary. So, I think this may be an ok compromise.
