### ISSUE TITLE
Arc.ByStartPointEndPointStartTangent fails using a normalised vector

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6644]
## Dynamo version

1.0.0

## Operating system

Win 10

## What did you do? 

Created an arc using the Arc.ByStartPointEndPointStartTangent. The tangent start vector was derived from an adjoining arc with the intention to create a tangency.

## What did you expect to see?
The new arc tangent to the arc from which the start vector was derived.

## What did you see instead?
The node failed and displayed the following warning:

> Could not create the plane! The desired axes of this plane are parallel. 

However, it seems this error is caused by a tolerance issue. As the vector is normalised (i.e. length of 1), I found if the same vector is rebuilt but increased in length, then the node works as expected. Oddly, if the vector length is less than 8.3 then the node fails. I'm working in mm and the radius of the arcs in question are 7500mm.

 **Arc.ByStartPointEndPointStartTangent Node fails using a normalised vector:**
![arc bystartpointendpointstarttangent fails with normalised vector](https://cloud.githubusercontent.com/assets/18601851/15342869/73db9ee6-1c90-11e6-9957-fe35d60ee1c2.jpg)

 **Arc.ByStartPointEndPointStartTangent Node works if the same vector is rebuilt:**
![arc bystartpointendpointstarttangent works when vector is rebuilt](https://cloud.githubusercontent.com/assets/18601851/15342953/007d27a2-1c91-11e6-9e85-ee245aaea242.jpg)

**Comment by kronz** [comment]
FYI @aparajit-pratap

**Comment by aparajit-pratap** [comment]
Tracked here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10114

**Comment by aparajit-pratap** [comment]
This should be fixed in the next daily. Thanks @rk-lakshmanan!
