### ISSUE TITLE
Package manager not showing recently updated packages

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#6650]
## Dynamo version

1.0.0.1180
## Operating system

Win 7
## What did you do?

Opened package manager and sorted by most recently updated
## What did you expect to see?

To see packages sorted by most recently updated.
## What did you see instead?

Packages do not appear sorted by most recently updated.

Example is sorted view as pr 19. May. Searching for Bakery and Spring nodes clearly shows that they've been updated after eg Juggernaut as shown in the picture below. Any logical reason to why this is so?
![testimg](https://cloud.githubusercontent.com/assets/7080648/15408743/06da54e4-1e12-11e6-9a03-abed5db6872c.png)
![testimg2](https://cloud.githubusercontent.com/assets/7080648/15408744/06e863d6-1e12-11e6-9db3-0071d39e8576.png)
![testimg3](https://cloud.githubusercontent.com/assets/7080648/15408745/06ed16a6-1e12-11e6-86ac-63a88dcc25c2.png)

**Comment by ParametricMonkey** [comment]
@ikeough @kronz This is still happening. When searching for lunchbox which has just been updated it is not at the top of the list. 
![packagemanager1](https://cloud.githubusercontent.com/assets/10913639/16548273/cc04c140-41cc-11e6-8519-00777653f8b3.JPG)
![packagemanager2](https://cloud.githubusercontent.com/assets/10913639/16548274/ce57add6-41cc-11e6-988a-32dcc1dbb986.JPG)

**Comment by smangarole** [comment]
@josols This issue is fixed in Dynamo 1.3. Closing this issue.
