### ISSUE TITLE
Hide referenced dll

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/Dynamo#6654]
## What did you do?

Developing own UI nodes(see #4776). Needed a static class for BuildOutputAst with Func. Made it in a separate namespace (don't remember if this is necessary). I put `[IsVisibleInDynamoLibrary(false)]` just above the static class declaration. Needed to reference this dll in the dll of the UI node of course and also needed to include it in the Dynamo Package.
## What did you expect to see?

Expect that this static class is not visible in Dynamo menu.
## What did you see instead?

The static class appears in the Dynamo menu.

**Comment by ksobon** [comment]
@jhubers i have had this issue before as well. for some reason it is not enough to just mark the class as <code>[IsVisibleInDynamoLibrary(false)]</code> but also I had to actually publish my package (locally), and then when you go to Manage Packages menu you can right click on the DLL and uncheck "IsNodeLibrary". Only then, would my classes not get loaded into the library.

**Comment by jhubers** [comment]
@ksobon thanks for the tip. Appears to work only from Revit/Dynamo and indeed by right clicking the file in the publish dialogue.

**Comment by ksobon** [comment]
Oh yeah, there is that thing too "works only from Revit/Dynamo", I can't publish packages from Sandbox for some reason too. :-1:

**Comment by johnpierson** [comment]
This issue was reported for version 1.x. Can you confirm for us if this is still an issue for you in Dynamo 2.0.x?

**Comment by jhubers** [comment]
Hi John,

Unfortunately our faculty decided not to continue with Revit/Dynamo in the courses I was teaching. Also my research in this domain had to be stopped. So it is not an issue for me anymore.

Best regards,

Dr. Ir. J.C. (Hans) Hubers
Associate professor

TU Delft / Faculty of Architecture
Julianalaan 134 / 2628 BL, Delft
01.West.120
PO Box 5043 / 2600 GA, Delft
The Netherlands

**Comment by johnpierson** [comment]
Thanks for the update @jhubers! That is a bummer to hear, maybe they will come back around one day.

I am going to go ahead and close this for now.
