### ISSUE TITLE
GroupByKey Not Found

### ISSUE THREAD

**Issue by jordanbillingsley** [DynamoDS/Dynamo#6674]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.0.1.1462
## Operating system

Windows 10
## What did you do?

Using a custom node (Lunchbox List.Count Occurences)
## What did you expect to see?

List
## What did you see instead?

Null values. Opened the custom node and found error -> Warning: Method 'GroupByKey' not found

**Comment by dimven** [comment]
This is probably because the node hasn't been updated after version 0.9. The old "GroupByKey" node was renamed to "GroupByFunction" and a new method was added that was called "List.GroupByKey".

If the custom node uses a CBN( code block node) script, then it can not be migrated automatically.
cc @kronz

**Comment by aparajit-pratap** [comment]
@dimven unfortunately at present we don't have a mechanism to automatically migrate method names used in CBN's. We can only do this for nodes at the moment.

**Comment by kronz** [comment]
@aparajit-pratap seems like we ought to be able to detect these names though . . . currently I know of a few users who are doing search and replace on dyn files in text editors.  Did we look at any kind of detection on upgrade?

**Comment by aparajit-pratap** [comment]
@kronz created a story to track this and currently assigned to you for prioritization: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10164
