### ISSUE TITLE
Improvement: Pin and scroll bar overlap in Preview bubble

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6676]
## Dynamo version

1.0.1.1462

## Operating system

Windows 10

## What did you do? 

Tried to use the vertical scroll bar

## What did you expect to see?

To be able to drag the scroll bar down

## What did you see instead?

Unable to do so as the pin appears above the scroll bar on moving the cursor to the top right.

![20160530-1](https://cloud.githubusercontent.com/assets/5621624/15639415/dc3f4278-2648-11e6-9a0f-7f2460eb072c.png)

**Comment by kronz** [comment]
FYI @Racel

**Comment by Racel** [comment]
On it. [http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10171](Filed under MAGN-10171)

**Comment by ke-yu** [comment]
@vykrum, this has been fixed in #6799.
