### ISSUE TITLE
Improvement: right-click 'Quick' Search should show location of node in the Library

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6677]
## Dynamo version

1.0.0

## Operating system

Win 10

## Improvement Suggestion
It would be very useful when using the right-click search menu to show either information of where the required node is located in the Library or for new functionality to be added which will automatically expand and highlight the required node in the library. (To clarify what is meant by 'the required node' it is whichever node listed in the search results the user has placed their cursor over).

This request has also been made by a number of new users who I'm teaching Dynamo.

One example is the Flatten node. There are two flavours and both are located in different categories in the Library. One is located in CORE > List > Flatten the other is in BUILTIN > Flatten. While the search results for the search term 'flatten' will list both nodes, there is nothing to tell the user where either node is located in the Library. This example highlights how the search tool could be improved as its current usage effectively divorces the user from the typical interactions of Library to graph.

This is especially problematic for those who want to grasp a better understanding of the Library. The search tool, while very useful, hinders any such endeavour. 

![capture](https://cloud.githubusercontent.com/assets/18601851/15650414/4bedcfbe-2670-11e6-95e8-3e4d032d3787.JPG)

**Comment by kronz** [comment]
Hi @ThomasMahon 
One of the design decsions that we made in creating the in-canvas search was to emphasize simplicity and compactness.  This is a bit of a counterpoint to the way that search works within the library browser, which has filters, compact and detailed views, as well as linked tex to do just what you are saying, allowing users to follow specific nodes back into the browser to find similar functionality.  Another way to look at this is that the in-canvas search is more "advanced" and aimed to speed and delivery for those who know what they are looking for, and the browser search is more introductory or exploratory.

**Comment by ThomasMahon** [comment]
@kronz seems reasonable. Thanks
