### ISSUE TITLE
Polygon.RegularPolygon has the wrong description

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6678]
## Dynamo version

1.0.0

## Operating system

Win 10
## What did you do? 

Used the Polygon.RegularPolygon node

## What did you expect to see?

A description explaining that a circle is used to construct the polygon along with the count of verticies

## What did you see instead?

The same description as the Polygon.ByPoints method

![wrong description for polygon regularpolygon](https://cloud.githubusercontent.com/assets/18601851/15654714/6d230f96-268e-11e6-8f8d-6ee21aee5326.JPG)

**Comment by kronz** [comment]
@ThomasMahon nice catch, thanks.  
@riteshchandawar can you assing to change this to read:  "Construct an inscribed Polygon Curve within a circle"

**Comment by riteshchandawar** [comment]
@rk-lakshmanan please take a look and submit the fix.

Thanks,
Ritesh

**Comment by riteshchandawar** [comment]
@ThomasMahon Fix is available in daily build.

Thanks for reporting.

- Ritesh
