### ISSUE TITLE
search in library still!!!

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#6681]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

since 0.9 to dailies
## Operating system

10
## What did you do?

search packages
## What did you expect to see?

that only correctly filtered elements are displayed.
categori definitely is not category
same for python definitely not is revit

same issue with all elements of type. you find everything but the correct command in the list
## What did you see instead?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/6928491/15704752/50db7814-27ec-11e6-90df-68e76b9759dd.png)

![image](https://cloud.githubusercontent.com/assets/6928491/15704873/d746a3ba-27ec-11e6-9d15-92d6cb630a4c.png)

**Comment by QilongTang** [comment]
@kronz This could be another highlight showing it might be worth enabling pining nodes before investigating on improving search to cover all the edge cases.

**Comment by kronz** [comment]
@epeter- , not sure what is wrong in your search.  We have a "fuzzy search" algorithm that allows for "near matches" to account for typos and plurals (search for "points" still finds "point", "cordinate" finds "coordinate"), and your Python search has found a node (Revit ID)  that has been Categorized as Python

**Comment by epeter-** [comment]
zach, the fuzziness seems to be way to fuzzy.

with alll respect to fuzzy algorithms i expect that incorrect results 
are sorted out.

for me that is especially important when searching the library for 
categories, types..

there you have significant letters like "i" or "y" to find the two 
relevant results in the query.

meaning when i search for categor*y *i am definitely for *all elements 
of category*, replacing the *"y*" in my search with an "*i*" should 
deliver *categories* as a top search result.

as you now, this will not happen in the current implementation of the 
search algorithm.

(and has never been).

best peter


Am 02.06.2016 um 04:11 schrieb Zach Kron:
>
> @epeter- <https://github.com/epeter-> , not sure what is wrong in your 
> search. We have a "fuzzy search" algorithm that allows for "near 
> matches" to account for typos and plurals (search for "points" still 
> finds "point", "cordinate" finds "coordinate"), and your Python search 
> has found a node (Revit ID) that has been Categorized as Python
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/6681#issuecomment-223177637>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGm4a0qRsVSXZ4fegUBGluA1LYcX38BGks5qHjvpgaJpZM4IrWwQ>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by josols** [comment]
I agree with @epeter- . Fuzzy or not it's not very logical.

**Comment by smangarole** [comment]
Currently we are working on 2.x and search is not part of the scope. We will work on Search in the next generation of Dynamo.  

Please go through this blog post for more information: http://dynamobim.org/whatre-they-building-in-there/

Thanks.
