### ISSUE TITLE
Stop Dynamo IronPython to warp objects in IronPython.Runtime.Types.PythonType

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/Dynamo#6683]
## Dynamo version

1.0.0.1180
## Operating system

Windows 8
## What did you do?

I created a new type that inherits from `datetime` type.
## What did you expect to see?

I expect to be able to use `__lt__` or `__gt__` methods with no issues. For instance 2015-01-01 is smaller than 2015-12-31. I tested the code in Python and IronPython (but not in Dynamo) and it works fine.
## What did you see instead?

Dynamo returns wrong outputs. 2015-01-01 < 2015-12-31 returns False.

![image](https://cloud.githubusercontent.com/assets/2915573/15717782/8615200c-27f6-11e6-951b-49540a2869bb.png)

There are other issues which I assume is happening for the same reason. For instance `isinstance` won't work correctly. I have added my own workarounds around for both cases but this is a major issue and can break workflows that are expected to work correctly in [Iron]Python. What is the reason to wrap the objects in a new type and can it be removed?

tags: python, bug

**Comment by mjkkirschner** [comment]
@mostaphaRoudsari I'm having a hard time understanding your issue. This is the base object of all Python types in iron python.

Can you provide the code in your other python script?

**Comment by mostaphaRoudsari** [comment]
Hi @mjkkirschner! Thank you for the quick reply. Here is code sample. Download this [zipped file which I had to rename to .txt!](https://github.com/DynamoDS/Dynamo/files/293967/dynamotest.txt) and try to run the code below.

```python
import sys
p = r"C:\Users\Administrator\Desktop\dynamotest"
sys.path.append(p)

from analysisperiod import AnalysisPeriod

ap = AnalysisPeriod()
print len(ap.HOYs)
```

It should print out 8760.
![image](https://cloud.githubusercontent.com/assets/2915573/15718980/e6a44eb6-27fb-11e6-8198-8d8bb16069d5.png)

Now the same code in Dynamo will return 1.
![image](https://cloud.githubusercontent.com/assets/2915573/15719008/04576f1a-27fc-11e6-9068-a4c2136180df.png)


It happens because of what I posted above. You can check the code in line 120 in analysisperiod.py. It finishes the while loop right after the first step as ```curr <= endTime``` will return False when you run it from inside dynamo, which is the issue that I posted originally.

```python
        while curr <= endTime:
            if self.__isPossibleHour(curr.hour):
                time = LBDateTime(curr.month, curr.day, curr.hour, curr.minute)
                self.__timestampsData.append(time.MOY)
            curr += self.minuteIntervals
```

**Comment by ke-yu** [comment]
Hi @mostaphaRoudsari , sorry for the late reply. Looks the second case doesn't marshal data through Dynamo, the evaluation is done only in IronPython, right?

For the first case, looks something goes wrong when marshalling IronPython.Runtime.Types.PythonType back to your type which inherits from `datetime`. Does it help if import analysisperiod into python node that does comparison?

**Comment by mostaphaRoudsari** [comment]
I figured a workaround for this. I will re-open the issue if it was a problem.
