### ISSUE TITLE
Watch 3D not working

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6685]
## Dynamo version

1.0.1.1523

## Operating system

Windows 10

## What did you do? 

Connected a wire to the Watch 3D node

## What did you expect to see?

The same graphics as in the background 3D

## What did you see instead?

Nothing

![20160602-1](https://cloud.githubusercontent.com/assets/5621624/15745891/c510d700-28f1-11e6-9532-53bfcaefa01f.png)

**Comment by monikaprabhu** [comment]
@vykrum - thanks for reporting this .We have the same issue logged  at MAGN-10161 by the team.

**Comment by ke-yu** [comment]
Fixed in #6776
