### ISSUE TITLE
Improvement: Show node label name

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6691]
## Dynamo version

1.0.0
## Operating system

Win 10
## Improvement Suggestion

It would be extremely helpful if the nodes can show their method names separate to the name of the node itself. On large graphs, its borderline insane not to rename nodes to something more meaningful (loosely related to #6510), and therein lies the problem. Once the node is renamed, its pretty frustrating to have to hover the mouse cursor over the node to see the information pop-up to discover what it is. What would be really useful and improve productivity, is if the node could display not only a name but also a secondary heading which only shows its method. To further extend this functionality, it could also be a global control in the View menu > _Show node labels_. If users want to retain the current appearance and not show the method name this setting simply hides the heading for all nodes.

Here's another example which illustrates the problem, a recent post on the Dynamo forum, where I'd renamed a node for graph legibility and no one can work out what they are (the two nodes in question were actually the `Point.ByCylindricalCoordinates` and `List.DropItems` for the four ptCorner nodes, positioned right on the image below):
![forum problem pres](https://cloud.githubusercontent.com/assets/18601851/15807618/a0572bec-2b5a-11e6-902b-a90fbaf351e9.JPG)

What I would like to see: 

![menu example](https://cloud.githubusercontent.com/assets/18601851/15807592/1b8153fc-2b5a-11e6-9829-09a075153962.jpg)

![upgrade to node name title](https://cloud.githubusercontent.com/assets/18601851/15807602/470175c0-2b5a-11e6-8cc6-4c81a0277bf3.jpg)

**Comment by ke-yu** [comment]
@Racel do you have any thoughts?

**Comment by Curty102** [comment]
+1

**Comment by Racel** [comment]
@ke-yu - We have some designs around this, but am not sure when this will make it in. We will probably do some more iterations/testing before this makes it into master...

**Comment by smangarole** [comment]
We are working on the next generation UI for Dynamo. This issue is listed in our backlog and will be prioritized. 

Please go through this blog post for more information on what's happening with the Dynamo Project: http://dynamobim.org/whatre-they-building-in-there/

Thanks.
