### ISSUE TITLE
Curve.ToNurbsCurve fails. Warning message: To BSplineCurve not implemented

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6692]
## Dynamo version

1.0.1.1421
## Operating system

Win 10
## What did you do?

I created a curve using a number of nurbs curves and lines which are joined to form one continuous path using the PolyCurve.ByJoinedCurves method. I then attempted to convert the joined curve back to a new continuous nurbs curve
## What did you expect to see?

A new nurbs curve built from the joined PolyCurve
## What did you see instead?

Method fails with the following warning message

> Warning: Curve.ToNurbsCurve operation failed. To BSplineCurve Not Implemented

![screen shot showing problem](https://cloud.githubusercontent.com/assets/18601851/15808134/99f24784-2b67-11e6-89c4-79e86038a2ea.jpg)

EDIT: See also this related thread #6694 as there may be another bug using the Solid.ByLoft node. Dynamo seems to be having some serious trouble with this geometry (quite surprising considering it's not very complex...)

**Comment by ThomasMahon** [comment]
More problems. I'm not going to open a new thread as this may be related to the input curve as described above rather than another problem with the node, but if I extrude the joined PolyCurve to surfaces and attempt to extract the boundary curves using Surface.PerimeterCurves then I get the following error message:

> Unable to approx. Surface: API_FAILED -- operation failed

![error with surface extract boundaries](https://cloud.githubusercontent.com/assets/18601851/15808224/289fbd8e-2b6a-11e6-80cc-303f53d63bd6.JPG)

**Comment by mariamhosman** [comment]
**Dynamo version**
2.0.0.4654

**Operating system**
Win 10

**What did you do?**
The same workflow discussed above

**What did you expect to see?**
A new nurbs curve built from the joined PolyCurve

**What did you see instead?**
failure to implement
![failure to implement](https://user-images.githubusercontent.com/5843355/40114896-7791cdee-5906-11e8-9bca-aa1897eca219.PNG)

**Comment by jnealb** [comment]
@ThomasMahon Thanks for the report; this is tracked with Jira task QNTM-4303 which is in the 2.1 backlog. @aparajit-pratap @smangarole @Racel fyi.
