### ISSUE TITLE
Improvement Request_Have SaveAs dialog when downloading Packages

### ISSUE THREAD

**Issue by Omeba720** [DynamoDS/Dynamo#6702]
Hi,

I was wondering whether there could be an option where we could choose which location to save the packages if more than one package path exists? Since we have a network location as the primary package location and C drive as secondary when downloading a package, some users may want packages but we don't want the network package location getting cluttered and prefer this to go to their local. I know that this may result in broken scripts if not everybody has the package it originated from installed, but that's easy to remedy.

cheers,
Dan

**Comment by ke-yu** [comment]
@riteshchandawar any thought?

**Comment by sharadkjaiswal** [comment]
we do have option to install the package at a specific location. Refer: #5186

**Comment by riteshchandawar** [comment]
@Omeba720 : You can use @sharadkjaiswal's solution (by choosing smallarrow button)  or you can also set the default path for package download from Setting>Manage Node and Package Path. Once you set the path you can use normal install button to install the package, it will get saved to your network path.

I hope this will solve your problem.

Thanks,
Ritesh
