### ISSUE TITLE
Surface.Thicken issue

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6704]
## Dynamo version

1.0.1.1586

## Operating system

Windows 10

## What did you do? 

Used the *Surface.Thicken* node without *both_sides* boolean option

## What did you expect to see?

The surface to be thickened on both sides, by default, as indicated in the node description
Expected similar result as when using the other *Surface.Thicken* node with *both_sides* set to *true*

## What did you see instead?

![20160608-1](https://cloud.githubusercontent.com/assets/5621624/15883565/df89c6ea-2d66-11e6-9d18-705b3700d2ba.png)

**Comment by aparajit-pratap** [comment]
@vykrum we're having difficulty reproducing the issue. Could you share the Dynamo graph you used so that we can investigate this.

**Comment by vykrum** [comment]
https://dl.dropboxusercontent.com/u/40183413/SurfaceEdgeExtend1.dyn

**Comment by YanmengLi** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8663553/15917918/c16c60d2-2e33-11e6-9c8b-a3df5aac7b5f.png)

Hi @vykrum I try to run your file on build 1.0.1.1586 in Windows 10 and could not reproduce this issue. Surface.Thicken seems to work properly.

**Comment by vykrum** [comment]
@YanmengLi In your image above you have actually reproduced the issue.
Observe that on the left thickness is distributed on both sides of the surface while on the right the thickness is on one side.
The problem is that both should actually be identical

**Comment by YanmengLi** [comment]
![surface_thicken2](https://cloud.githubusercontent.com/assets/8663553/15926545/2a9d2a7e-2e6f-11e6-9aa5-10f55a057a45.png)
It will be identical when you set the boolean value to false, not true. When you set it to false, it will thicken the surface on one side, works exactly as the another node.

**Comment by vykrum** [comment]
@YanmengLi The problem is with the other node, the node with the true/false option behaves correctly

The node without that option does not behave as indicated in the node description. (It should work like the other node set to *true*)

There IS a problem.

**Comment by vykrum** [comment]
Either the description or behavior of this node needs to change

![20160609-5](https://cloud.githubusercontent.com/assets/5621624/15927143/63924fa6-2e5d-11e6-9b3c-9ef57d741440.png)

**Comment by YanmengLi** [comment]
Yes you are right. We will investigate this. Thanks for pointing this out. @vykrum

**Comment by aparajit-pratap** [comment]
Fixed: https://git.autodesk.com/Dynamo/LibG/pull/348
