### ISSUE TITLE
Comments (Ctrl-W) no multiline input available

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#6707]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.0.1.1586
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
win 10-64
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
try to input multiline content
(Fill in here)

## What did you expect to see?
line1
line2
line3
.....
(Fill in here)

## What did you see instead?
line1line2line3....
(Fill in here)
<cr><lf> is ignored. when one enters return key the input window closes. so only single line inputs are available.
"german locale"

**Comment by ke-yu** [comment]
hi @epeter-, is the problem in code block node? What does the code look like? Multline comments? /**/ or // ?

**Comment by epeter-** [comment]
no it is the comments (Ctrl +W) option

Am 17.06.2016 um 05:25 schrieb Yu Ke:
>
> hi @epeter- <https://github.com/epeter->, is the problem in code block 
> node? What does the code look like? Multline comments? /**/ or // ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/6707#issuecomment-226671755>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGm4a8WdFAn3qrxtviF4pyJa0M5msCpRks5qMhOxgaJpZM4Iw-SJ>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by ke-yu** [comment]
Oh Ctrl-W is for creating notes.

**Comment by epeter-** [comment]
exactly. but shouldnt notes be formatable too?

Am 17.06.2016 um 08:50 schrieb Yu Ke:
>
> Oh Ctrl-W is for creating notes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/6707#issuecomment-226694055>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGm4a03eQszO1juK43NU0K2f1iQ4_Q4Hks5qMkOxgaJpZM4Iw-SJ>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by ke-yu** [comment]
It should be. Will fix it once we get some bandwidth.

**Comment by epeter-** [comment]
ok ;-)

Am 17.06.2016 um 08:54 schrieb Yu Ke:
>
> It should be. Will fix it once we get some bandwidth.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/6707#issuecomment-226694615>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGm4a_BZTeS6m_KAlRkY97dEXXJ1bczwks5qMkSjgaJpZM4Iw-SJ>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Benglin** [comment]
It appears to be working with the RC build of *Dynamo Studio*, I have yet to check on *Dynamo for Revit* (waiting for a class to start)... hopefully it works there too :-)

![multi-line-notes](https://cloud.githubusercontent.com/assets/5086849/16218931/b5701ed8-37b4-11e6-900e-1a6d25a82a9a.png)

**Comment by ke-yu** [comment]
@monikaprabhu @riteshchandawar some difference between Dynamo Studio and Dynamo Sandbox?!

**Comment by riteshchandawar** [comment]
@ke-yu @epeter- : This is the latest regression caused while fixing the behavior for Node Name change. Now while changing the Node name user can simply click enter to accept the changes, but for Notes we should allow entering the second line.

**Comment by ke-yu** [comment]
This https://github.com/DynamoDS/Dynamo/pull/6762 is to fix the issue.

**Comment by rk-lakshmanan** [comment]
@epeter-  I have created a PR to fix the issue mentioned above: https://github.com/DynamoDS/Dynamo/pull/6762

**Comment by ke-yu** [comment]
Fixed in #6762.
