### ISSUE TITLE
Wish: Improve dialog text for installation of packages that have dependencies

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#671]
The following occurs when you try to install a package that has dependencies and you already have one of the required packages installed. It's not a real bug as the installation process _does_ work, but it could be potentially confusing for new users.
1. So far everything's normal....
![bildschirmfoto 2013-11-01 um 15 35 39](https://f.cloud.github.com/assets/3014437/1454159/281dd3f6-4304-11e3-93b4-91f1d8be57d8.png)
2. Now Dynamo claims that the package is already installed - which isn't true. 
Expected behaviour: A message like "The required package XXXX is already installed." or similar....
![bildschirmfoto 2013-11-01 um 15 35 54](https://f.cloud.github.com/assets/3014437/1454160/2c18cf6a-4304-11e3-8cc1-34a08b8b5354.png)
3. Everything back to normal again...
![bildschirmfoto 2013-11-01 um 15 36 14](https://f.cloud.github.com/assets/3014437/1454162/30b10678-4304-11e3-8318-7f22fb4838fc.png)

**Comment by Racel** [comment]
This is something that we will improve in the future, but not right now.
