### ISSUE TITLE
Improvement: Search options dropdown refinement

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6712]
## Dynamo version

1.0.1.1586

## Operating system

Windows 10

## What did you do? 

Searched for the node *All Elements of Type*

## What did you expect to see?

In the search box I type *All Element* and the node appears in the drop down list. 
When I get more specific and type *All Element***s**, I'd have expected the drop down list to have further filtered fewer and more relevant options.

## What did you see instead?
 Instead, the relevant node is moved out of sight further down the list.

![20160609-3a](https://cloud.githubusercontent.com/assets/5621624/15918296/fb3fbe50-2e22-11e6-836f-983b89f64203.png)

![20160609-3b](https://cloud.githubusercontent.com/assets/5621624/15918301/00495348-2e23-11e6-8726-4646267e514c.png)

**Comment by josols** [comment]
In the same category as this: #6681

**Comment by jnealb** [comment]
Yes, we are working on this.

**Comment by ke-yu** [comment]
Tracked in #6681.
