### ISSUE TITLE
Error when using Node to Code on a custom ZT Node

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#6719]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

Daily 6-9-2016
## Operating system

w 10 
## What did you do?

Error when using Node to Code on a custom ZT Node
## What did you expect to see?

Node to Code Make no error
## What did you see instead?

Error when using Node to Code on a custom ZT Node

![image](https://cloud.githubusercontent.com/assets/6132497/15938196/fbb8be14-2e26-11e6-8635-d40a2d661b18.png)

**Comment by ke-yu** [comment]
hi @marcellosgamb, what's the original function looks like? Is it a multi output node?
