### ISSUE TITLE
Output Ports not displaying correct name from ZT custom nodes 

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#6720]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

daily 6-9-2016

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Operating system

w 10
## What did you do?

Output Ports not displaying correct name from ZT custom nodes 
## What did you expect to see?

Output Ports not displaying correct name from ZT custom nodes 
## What did you see instead?

Output Ports not displaying correct name from ZT custom nodes 

![image](https://cloud.githubusercontent.com/assets/6132497/15938381/b6d60c7e-2e27-11e6-99a4-fd85b21014a6.png)

**Comment by mjkkirschner** [comment]
two things:

1) don't use a mutlireturn attribute if you are not returning multiple outputs. (_there was a bug here, I don't know if it has been fixed_), but it's just a bit of strange practice anyhow.

2) you can use <return> attribute to name the output. like this:
https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#documentation-tooltips-and-search
