### ISSUE TITLE
Unable to deactivate labels

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6723]
## Dynamo version

1.0.1.1610
## Operating system

Windows 10
## What did you do?

Selected a line in the preview bubble and saw labels in the background display.
Then clicked outside in an empty area.
## What did you expect to see?

Expected the action to unselect the line in the preview bubble and turn off label display
## What did you see instead?

Unable to unselect

![20160611-3](https://cloud.githubusercontent.com/assets/5621624/15985134/5e2e6996-3001-11e6-9923-6383b4c1406e.png)

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
