### ISSUE TITLE
Ghost Function

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6727]
## Dynamo version

1.0.1.1610
## Operating system

Windows 10
## What did you do?

typed _a_ in code block
## What did you expect to see?

an input port to appear
## What did you see instead?

![20160613-1](https://cloud.githubusercontent.com/assets/5621624/16006980/84cf23c8-318d-11e6-8b69-06180d2f703a.png)

**Comment by vykrum** [comment]
Observed that the above issue is actually not about _**a**_
I happened to have defined a function **_a_** (and deleted it too) in **another file** and that function seems to affect all subsequent files opened in the same Dynamo session.

The problem is resolved on closing Dynamo and reopening. Just reopening a file in the same Dynamo session doesn't solve the problem.

As this pertains to a function doesn't seem to die, I'll change the title to _Ghost Function_ :-)

**Comment by ThomasMahon** [comment]
I've experienced the same thing although I couldn't pin it down...memory leak? I notice that if you write definitions and copy paste them into another code block Dynamo becomes unstable and the problem you describe arises.

**Comment by ke-yu** [comment]
Bug :-(

**Comment by aparajit-pratap** [comment]
Fixed in https://github.com/DynamoDS/Dynamo/pull/10113

**Comment by aparajit-pratap** [comment]
Reopening issue as the earlier fix has to be revisited - causing regressions in other areas.

**Comment by mjkkirschner** [comment]
should be fixed.
