### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by incentive734** [DynamoDS/Dynamo#6739]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by aparajit-pratap** [comment]
@incentive734 this is an empty bug report??

**Comment by ke-yu** [comment]
Hi @incentive734 , it would be very helpful if you could provide more details about the crash, for example the crash call stack, the step to reproduce, etc. Please reopen it if you have more details.
