### ISSUE TITLE
Can't get coordinate system from Rectangle

### ISSUE THREAD

**Issue by KirilLukyanenko** [DynamoDS/Dynamo#6745]
## Dynamo version

1.0.0.1663

## Operating system

Windows 10

## What did you do? 

Create Rectangle.ByWidthLength and get CoordinateSystem from it

## What did you expect to see?

CoordinateSystem before creating rectangle and after should be equals

## What did you see instead?

Coordinate systems are different
![coordinatesystem](https://cloud.githubusercontent.com/assets/19977109/16120667/00964100-33e9-11e6-958e-578613bd4bc4.png)

**Comment by ke-yu** [comment]
hi @KirilLukyanenko, `Equals` node compares if two objects are the same object or not (equality), but doesn't check for equivalence. 

Use `CoordinateSystem.IsEqualTo` node for equivalence testing. 

![untitled](https://cloud.githubusercontent.com/assets/2600379/16139782/8640695e-347d-11e6-95b0-e3f605c61ed2.png)

**Comment by KirilLukyanenko** [comment]
The same result
I have another AXis and YAxis after creating rectangle
![coordinatesystem](https://cloud.githubusercontent.com/assets/19977109/16145944/1e589a8a-3484-11e6-9c1e-0ff2b1a5d209.png)

**Comment by ke-yu** [comment]
@riteshchandawar @aparajit-pratap is it an issue in `Geometry.ContextCoordinateSystem`?

**Comment by mjkkirschner** [comment]
I think this could be a bug in with curves, if you create a cuboid in a similar manner with the CS input, the context coordinate system seems to be returned correctly.

**Comment by riteshchandawar** [comment]
@ke-yu @mjkkirschner @KirilLukyanenko : Issues logged for internal tracking. http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10263

We will inform you once the fix available in daily build.

- Ritesh

**Comment by ke-yu** [comment]
Sorry, `Equals` node should do real equality test. I think it is an issue in `CoordinateSystem`.

**Comment by aparajit-pratap** [comment]
This should be fixed in the next daily.

**Comment by KirilLukyanenko** [comment]
@aparajit-pratap:  I don't see fix in 2016-07-22T03:51:40.000Z        83017667       DynamoInstall1.1.0.20160721T2051.exe
Could you specify build version where this fix is available?

**Comment by aparajit-pratap** [comment]
I think the fix missed the build. You'll have to wait another day or two. We're currently focusing on our release 1.1 builds and not the dailies but you should have it very soon.
