### ISSUE TITLE
Improvement: Inconsistent names for Plane.XZ vs CoordinateSystem.ZXPlane

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6746]
## Dynamo version

1.0.1.1421

Win 10

(e.g. Windows 7, Windows 8.1, etc)
## Improvement Suggestion

This is minor but an annoyance nonetheless: the CoordinateSystem.ZXPlane method is named inconsistently compared to Plane.XZ not to mention general standards for axes notation (X axis should always take precedent). Is this an oversight?

![cs zx](https://cloud.githubusercontent.com/assets/18601851/16133077/f052b5b0-340d-11e6-93db-643f3790af9f.JPG)
![nodes](https://cloud.githubusercontent.com/assets/18601851/16133076/f05258c2-340d-11e6-8aa6-cd3ecff66144.JPG)
![plane xz](https://cloud.githubusercontent.com/assets/18601851/16133075/f05038b2-340d-11e6-93ff-8d9471fdaa3b.JPG)

**Comment by gregmarr** [comment]
This is the proper mathematical name for the coordinate system. Z cross X gives Y.  X cross Z gives -Y, and a left handed coordinate system.

**Comment by ThomasMahon** [comment]
XZ is widely used within mathematics, and more specifically in many CAD applications (minus a few like Catia). Regardless of which method is used, I would expect it to be consistent, and I do have a bias I suppose, due to other application I frequently use that do adopt XZ notation.

**Comment by gregmarr** [comment]
I assume it's more important for a coordinate system to have the proper name than a plane, since it only matters for a plane if you care which direction is up.  I don't know what the impact would be of either of these changes.  I'm just a part-time user of Dynamo.
