### ISSUE TITLE
Revit 2017- Dynamo1.0__node_"select model element" does not select.__thanks. 

### ISSUE THREAD

**Issue by JEballar** [DynamoDS/Dynamo#6764]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by monikaprabhu** [comment]
@JEballar - can you please provide build number and which element are you using. I could not reproduce this with latest daily build on DynamoBIM.
![select](https://cloud.githubusercontent.com/assets/5218721/16257170/3d1e5ae6-3889-11e6-8f0a-ad7a94b73e10.png)

**Comment by JEballar** [comment]
Dear Dynamo Support, Aloha! Thank you for the quick reply.  Apparently it is now corrected, I went back & redo the "Select Model Element ( & Elements)" .  At that time the Dynamo built is/was __1.0.1.1593. Sorry for the delayed response.   Thanks for taking the time.  Mahalo nui loa. Kind regards, Jess 
=======================
---------- Original Message ----------
Return-Path: <noreply@github.com>
Received: from mx02.vgs.untd.com (mx02.vgs.untd.com [10.181.44.32])
 by maildeliver08.vgs.untd.com with SMTP id AABMYWPT4A6WFYAS
 for <jesacramento@juno.com> (sender <noreply@github.com>);
 Tue, 21 Jun 2016 23:54:50 -0700 (PDT)
Authentication-Results: mx02.vgs.untd.com; DKIM=PASS
Received-SPF: Pass
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2-ext8.iad.github.net [192.30.252.199])
 by mx02.vgs.untd.com with SMTP id AABMYWPT4AX3DK9S
 for <jesacramento@juno.com> (sender <noreply@github.com>);
 Tue, 21 Jun 2016 23:54:50 -0700 (PDT)
Date: Tue, 21 Jun 2016 23:54:50 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
 s=pf2014; t=1466578490;
 bh=804bMCico6WjCmnKUwVcAqk4syY1/vWYVMIyHe7bixw=;
 h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
 List-Archive:List-Post:List-Unsubscribe:From;
 b=1Co+8mtvdOj8Qpj9KFtxZxwUBrrclQCsYE6+2NMKi6S53rnUbPnioIk4j47FrTlG+
 X395vEPJwDgcwzlH03meRS+5EvwfvOZuQdZlo3QpOwmtDzUJnpalo65AvjnIuKKgol
 LE6yIT2xTnGNLyUUvTC8OTrqVpl4a2jIhb7LwEOY=
