### ISSUE TITLE
Error while opening a DYN file

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#6804]
## Dynamo version

1.0

## Operating system

Win7

## What did you do? 

open file

## What did you expect to see?

file opened

## What did you see instead?

error

It might be FLUX related. 
[Master_CanopyWalk_02.zip](https://github.com/DynamoDS/Dynamo/files/337675/Master_CanopyWalk_02.zip)

**Comment by oderby** [comment]
Hmm, it opens fine for me. 
![image](https://cloud.githubusercontent.com/assets/1351158/16427184/0b83c6fa-3d21-11e6-8186-5131475c99ce.png)
Does opening in manual mode make a difference? 
Do you have the full text of the error and/or the full Dynamo console logs from the error?

**Comment by ksobon** [comment]
well I am on the same Dynamo version, Revit 2016 on Windows 7....idk. It crashes out for no obvious reason.

**Comment by oderby** [comment]
Hmm, I'm using Revit 2015, though I fail to see how that'd explain the different behaviors. Hopefully someone from the dynamo team can provide some help digging in further. 

Although it's hard to tell, if the file won't even open, it seems like an issue with Dynamo. If, after further investigation, you think it's a Flux plugin issue, please file the issue on https://community.flux.io/ and we'd be happy to help.

**Comment by ksobon** [comment]
@oderby I have no clue if its Flux related, but Mark had the same error and also had Flux components in his def so I was guessing that if it happened twice, it could be related. I will let Dynamo team, dig through this. Thanks for looking.

**Comment by jnealb** [comment]
@ksobon I need the FamilyInstance.SetType custom node as well please. Are there any package dependencies?

**Comment by ksobon** [comment]
@jnealb well...now that we are at this topic. It looks like that was already requested by @andydandy74 a while back. https://github.com/DynamoDS/Dynamo/issues/1171

Anyways, the answer is that I don't remember from top of my head. I made that definition a few months back and the issue is that I can't open it, so I don't think I will be able to help here much. I usually steer away from custom packages other than Clockwork and Archi-lab. I would try that.

**Comment by jnealb** [comment]
@ksobon We can not reproduce with Flux and the dyn you provided: the file opens in 1.0, with unresolved nodes. See also  https://github.com/DynamoDS/Dynamo/issues/6552.

**Comment by ksobon** [comment]
yes, indeed that was the issue as described in #6552 installing new Flux solved it. I didn't even realize that I didn't have new flux. My bad.
