### ISSUE TITLE
BuildOutputAST update

### ISSUE THREAD

**Issue by JeremyGraham** [DynamoDS/Dynamo#6814]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.0

## Operating system

Windows 7

## What did you do? 

Created custom UI node that generates list on ui based on input. User can then edit this list.

## What did you expect to see?

Output to update as user edits UI

## What did you see instead?

output is not updating, cannot seem to update the BuildOutput AST function. So, the UI is firing events but I don't know how to link the BuildOutput AST to these events.

**Comment by ke-yu** [comment]
@JeremyGraham  so seems `BuildOutputAST` not called?

**Comment by JeremyGraham** [comment]
I have the BuildOutputAst method override in my custom node model as shown attached.

I am trying to get this to update every time the "test" list is updated which is a public list. As new strings are added to the list, the output is not updated. Strings are added by the user pressing a trigger on the node UI.

![capture22](https://cloud.githubusercontent.com/assets/19681852/16481830/c40da76c-3edf-11e6-8d64-44e613abd3

**Comment by JeremyGraham** [comment]
![capture22](https://cloud.githubusercontent.com/assets/19681852/16481902/16ba4da8-3ee0-11e6-9447-096839cce887.PNG)

**Comment by ke-yu** [comment]
@JeremyGraham when a string is added, you may try to call `MarkNodeAsModified()` so that Dynamo will know this node is modified and need to re-generate ASTs.

**Comment by JeremyGraham** [comment]
That doesn't seem to work. 

To be more specific, I have checkboxes on the UI, when a user clicks one, a checked event occurs which adds a string to the "test" list. I have mucked around with OnNodeModified which shows the event is working, even though it adds null to the output, but of course this clears the UI which isn't ideal...If I can provide anything else which may help, please let me know.

**Comment by ke-yu** [comment]
If `OnNodeModified()` is triggered, I'd expect `BuildOutputAst()` will be called. No?

**Comment by JeremyGraham** [comment]
Yes, OnNodeModified works to trigger BuildOutputAst but it also wipes the UI clean. I'm guessing that's because the input list is reset also?

**Comment by ke-yu** [comment]
@JeremyGraham what is `test` in `BuildOutputAst`? If `test` is a list of *string*, then probably you have to do this:
```
var stringNodes = test.select(s => AstFactory.BuildStringNode(s));
var stringExpr = AstFactory.BuildExprList(stringNodes);
...
```
I guess the problem here is `AstFactory.BuildExprList()`. If you pass a list of string to it, internally it treats each string as a *variable* from other node, instead of a string. So here we have to build a list of `StringNode` firstly and pass it to `AstFactory.BulidExprList()`.

**Comment by JeremyGraham** [comment]
@ke-yu test is a public list which I am using to append strings to as a checkbox is ticked on the UI. It is as coded as shown below.

![ctwp](https://cloud.githubusercontent.com/assets/19681852/16487711/175342f0-3eff-11e6-8ce3-d9764e3c438b.JPG)

I tried your suggesting with the list of strings but am having the odd error:

"cannot convert from 'System.Collections.Generic.List<ProtoCore.AST.Associative.StringNode>' to 'System.Collections.Generic.List<ProtoCore.AST.Associative.StringNode>' "

this is occurring on the variable stringNodes when I try to use it in stringExpr as you have above..

**Comment by JeremyGraham** [comment]
Sorry i got the error wrong, it is-

![capture222](https://cloud.githubusercontent.com/assets/19681852/16489483/5f50e19e-3f08-11e6-8cbe-9fba23198dc9.JPG)

**Comment by ke-yu** [comment]
@JeremyGraham 
```
var stringNodes = test.Select(s => AstFactory.BuildStringNode(s)).Cast<AssociativeNode>.ToList();
var stringExpr = AstFactory.BuildExprList(stringNodes);
...
```

**Comment by JeremyGraham** [comment]
@ke-yu first off, thanks a heap for your help mate, I really appreciate it as I've been struggling with this for a week now.

Unfortunately, when I try to cast , the "cast<AssociativeNode>" produces the new error:

![casterror](https://cloud.githubusercontent.com/assets/19681852/16491046/db596d28-3f0e-11e6-8483-614af1e34ca6.JPG)

**Comment by ke-yu** [comment]
@JeremyGraham I'm so sorry, I didn't have an editor to verify the syntax when I typed it, a `()` is missing after `Cast<AssociativeNode>` 

Try
```
test.Select(s=> AstFactory.BuildStringNode(s)).Cast<AssociativeNode>().ToList();
```

**Comment by JeremyGraham** [comment]
No worries at all mate! Thanks that has done the trick to sort the string list! 

However, unfortunately I still have the problem of the BuildOutpuAST not updating.

To give you an example, shown below, it works if I use OnNodeMofied() once a checkbox is checked... however, This resets the node UI so the checked box is no longer checked. The example below shows how I have ticked the checkboxes for 1,2 and 3 which updates the output, but the checkboxes are no longer checked as OnNodeModified resets the input... so, is there any other way of updating the output without running OnNodeModified?

![capture111](https://cloud.githubusercontent.com/assets/19681852/16508756/dc9f5198-3f68-11e6-90d4-1fec318ce3cf.JPG)

**Comment by ke-yu** [comment]
Does 1,2,3,4 in Custom Node Model come from `{1, 2, 3, 4}` in Code block? I dont think OnNodeModified will reset the input/UI, but to update the output, the only is to call `MarkNodeAsModified()/OnNodeModified()`

**Comment by JeremyGraham** [comment]
Yes that is correct.
The Grid on the UI is updated using the input, i.e. a ObservableCollection is created and displayed based on the input data. In this collection, each checkbox has a checked event which calls OnNodeModified which seems to wipe the UI of any changes. MarkNodeAsModified has no effect on the node.

**Comment by ke-yu** [comment]
Oh I see. So seems like `OnNodeModified` triggers graph execution, but as its upstream node, which is code block node, has been executed and will not be executed in this run, this node won't get new data, so it wipes out the old one. Does it need to cached data?

I'm still not quite sure how you get data from code block node, is it from upstream node's `NodeModel.CachedValue`?

**Comment by JeremyGraham** [comment]
It doesn't really require the code block to be rerun. Once the node is run initially, it stores the data from the code block in a collection. The user can then check/uncheck checkboxes to update this collection which is ideally then output. Cached data as in , is the input data stored? Apologies if misunderstood.

In the CustomNodeModelNodeViewCustomization class, i'm using the follow code to get the data from the input and update the UI:

![capture111111](https://cloud.githubusercontent.com/assets/19681852/16510713/1a226d0e-3f7b-11e6-82e4-9f55819306f4.JPG)

this then invokes:

![capture112222221](https://cloud.githubusercontent.com/assets/19681852/16510730/3b7918f4-3f7b-11e6-9359-e677f25ef5f6.JPG)

which uses the RunTimeMirror to get the data from the input....

**Comment by ke-yu** [comment]
wow, really impressive to see Scheduler and Mirror are used! :-)

@Benglin

**Comment by JeremyGraham** [comment]
@key hah, i'm learning as I go mate so I hope it's a good thing ;)

**Comment by JeremyGraham** [comment]
Hey @ke-yu , so should I not be using the Scheduler and Mirror for this? Is this why the BuildOutputAST is not updating? If there is no other solution than just OnModified(), I can close this issue as unresolved?

**Comment by ke-yu** [comment]
@JeremyGraham sorry for the late reply! If querying data through scheduler, as task is async, it is not guaranteed that you'll get the latest data. Sorry again that I don't fully understand the problem. If possible, could you upload some sample code so that I can do some debugging?

**Comment by JeremyGraham** [comment]
@ke-yu no worries mate, I'm sure you are very busy as it is! 

I would be happy to, do you mind if I send a link to the complete code to your email?

**Comment by ke-yu** [comment]
@JeremyGraham , please :-)

**Comment by JeremyGraham** [comment]
@ke-yu Thanks mate, sent to your gmail.

Cheers!

**Comment by ke-yu** [comment]
@JeremyGraham , I quickly went through your code. Seems the input was wiped out because `CustomNodeModelNodeViewCustomization` tries to reset input when selection changed:

```
public void CustomizeView(CustomNodeModel model, NodeView nodeView)
{
    ...
    CheckListBox.SelectionChanged += delegate
    {
        updateInputList();
    };
    ....
}
```

Instead of re-generating inputs, when selection changed, `CustomNodeModel` should generate new **outputs**. So could you please try

    CheckListBox.SelectionChanged += delegate
    {
        customNode.OnNodeModified(true);
    };

I haven't run the code, so not quite sure if it works or not. Do please let me know the result. :-)

**Comment by JeremyGraham** [comment]
Hey @ke-yu ,

Thanks for looking at my code.

Unfortunately, this doesn't seem to be the issue... I tried what you suggested and I tried taking out the event all together, still the same problem as shown below.

![animation](https://cloud.githubusercontent.com/assets/19681852/16719074/e78948d2-4758-11e6-9a12-2e9bf3b94e22.gif)

Do you think I should try a different approach? maybe the Scheduler isn't the best way?

**Comment by ke-yu** [comment]
@JeremyGraham , forgot to mention, also remove `OnUpdateInputList()` from `CustomNodeModel.OnPropertyChanged()`. Property `CachedValue` is changed when the node *is executed*, that is, after `BuildOutuptAST()` is called and new output is generated. So calling `OnUpdateInputList()` will reset inputs.

**Comment by JeremyGraham** [comment]
@ke-yu you legend, you've done it! 

Thanks a milllion mate, this has been driving me crazy for far too long now!!! You have been extremely helpful!

**Comment by ke-yu** [comment]
@JeremyGraham  my pleasure. :-)

**Comment by ksobon** [comment]
@ke-yu  I think I have the same issue here: https://github.com/DynamoDS/Dynamo/issues/7254 do you mind having a look?
