### ISSUE TITLE
Issue with points

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6824]
## Dynamo version
1.0.1.1757

## Operating system
 Windows 10

## What did you do? 
Similar lists obtained in different ways give different results

## What did you expect to see?

Points to behave the same irrespective of the method of creation

## What did you see instead?
![20160630-1](https://cloud.githubusercontent.com/assets/5621624/16486356/cff87ac8-3ee1-11e6-873c-460ca5176019.png)

**Comment by dimven** [comment]
This might have to do with the fact that even tho you're using integers, the point automatically casts those to doubles and thus makes them susceptible to FP inaccuracies.

![2016-07-01_10-04-37](https://cloud.githubusercontent.com/assets/7148394/16509796/12bb6d20-3f73-11e6-9b5e-720aaff78be1.png)

**Comment by vykrum** [comment]
@dimven I think the problem lies elsewhere.
![20160701-1](https://cloud.githubusercontent.com/assets/5621624/16512707/02c5c92a-3f7c-11e6-8640-4ea3a712729a.PNG)

Wondering whether the recent spurt in Point related issues on the forum is related to this.

**Comment by dimven** [comment]
Are you getting the same result with "Geometry.IsAlmostEqualTo" ? It adds a small margin of error that eliminates the issue of floating point variance:
![2016-07-01_13-45-28](https://cloud.githubusercontent.com/assets/7148394/16512810/e6db13f8-3f91-11e6-8546-97d337b196ae.png)

**Comment by vykrum** [comment]
Works fine with _Geometry.AlmostEqual To_ and _Equals_ (ObjectA,ObjectB)

**Comment by ke-yu** [comment]
If element is an object, `Contains` do reference comparison, that is, if two items are the same object, similar to "==" node.

**Comment by vykrum** [comment]
@ke-yu Ok, but isn't this something that needs to be rectified?

![20160701-1](https://cloud.githubusercontent.com/assets/5621624/16521721/624a41ac-3fb6-11e6-9861-56cba716f820.png)

**Comment by vykrum** [comment]
[This query](https://forum.dynamobim.com/t/point-x-gives-different-result-ver-1/4797/2) on the forum might be related

**Comment by ke-yu** [comment]
@vykrum so `Contains` behavior is incorrect. It shouldn't do reference equality testing (`==`).

`==` tests for reference equality; `Equals` node, if inputs are from zero touch library, it will further call `Equals` on the corresponding C# class. In this case, it will finally call `Point.Equals()` and return `true`.

**Comment by ke-yu** [comment]
@monikaprabhu FYI

**Comment by ke-yu** [comment]
#6860 is to fix `Contains` behavior.

**Comment by ke-yu** [comment]
We keep the reference equality testing behavior for `==` node for the time being. `Contains` now has same behavior as `Equals` node.
