### ISSUE TITLE
Cropped Workspace Image

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6834]
## Dynamo version

1.0.1.1823
## Operating system

 Windows 10
## What did you do?

Took a screenshot using _Export Workspace As Image_
## What did you expect to see?

![20160701-1a](https://cloud.githubusercontent.com/assets/5621624/16521883/a6a96778-3fb7-11e6-9ad9-9dc7633a3380.png)
## What did you see instead?

Note that cropped preview bubbles on the left
![20160701-1](https://cloud.githubusercontent.com/assets/5621624/16521904/c5830a5a-3fb7-11e6-89c1-cdd56958f8cb.png)

**Comment by ke-yu** [comment]
@Benglin need to include preview bubble...

**Comment by Benglin** [comment]
Hi @vykrum, thanks so much for reporting this issue, I have [proposed a fix](https://github.com/DynamoDS/Dynamo/pull/6893).

**Comment by smangarole** [comment]
@vykrum The original issue is fixed and will be available in the next release with the exception of truncating the warning message, which we don't plan on fixing. Users can tell which nodes are in a warning/error states based on the color of the nodes. 

Closing this issue. Thanks.
