### ISSUE TITLE
Surface.Thicken does not work with negative thickness

### ISSUE THREAD

**Issue by eibre** [DynamoDS/Dynamo#6841]
## Dynamo version

1.1.1.1841

## Operating system

Windows 10

## What did you do? 

Used Surface.Thicken with negative value of thickness

## What did you expect to see?

The surface to be thickened in the opposite direction of its normal.

## What did you see instead?

The surface was thickened in the direction of its normal.

![image](https://cloud.githubusercontent.com/assets/5968613/16546236/25b43d08-4144-11e6-9a8d-7126c6f3b968.png)

**Comment by vykrum** [comment]
You should use the other Surface.Thicken node. This one extrudes on both sides of the normal, by default.
![20160704-2](https://cloud.githubusercontent.com/assets/5621624/16553730/e894c9ca-41e7-11e6-9721-54aeeac84b9f.png)

**Comment by eibre** [comment]
Thank you Vikram! This is changed behavior since 1.0.0, but I see now that it was supposed to work as you describes:
![image](https://cloud.githubusercontent.com/assets/5968613/16554017/793ed43c-41cc-11e6-9168-5a367b6bb307.png)
