### ISSUE TITLE
Unit Types not working

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#6844]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.0.1.1576

## Operating system

Windows 7

## What did you do? 

Dropped the Unit Types on the canvas

## What did you expect to see?

Work as expected

## What did you see instead?

An error message as shown below

![unit type](https://cloud.githubusercontent.com/assets/10913639/16551159/0c18655e-41f8-11e6-81a0-3dcc38a5ad83.jpg)

**Comment by josols** [comment]
Same as here: #6562  
Revit error?

**Comment by ke-yu** [comment]
@rk-lakshmanan any idea?

**Comment by rk-lakshmanan** [comment]
@josols  @ke-yu  I have created a PR to the issue mentioned above https://github.com/DynamoDS/Dynamo/issues/6844.
