### ISSUE TITLE
Dynamo Null Handling - Custom Nodes comparable to GH's Sift and Recombine Workflow

### ISSUE THREAD

**Issue by Curty102** [DynamoDS/Dynamo#6846]
## Dynamo version

1.0.0.276
## Operating system

Windows 7 Enterprise
## What did you do?

I have attempted to create a workflow similar to GH's Sift and Recombine.  I've created a pair of custom nodes call List.Pull and List.Put that extract items from a list using an input mask.  List.Pull inserts nulls to maintain original indexing.  I am running into problems since many Dynamo nodes don't seem to like nulls -- they won't run if any portion of an input list contains a null.
## What did you expect to see?

An output list with: executed nodes on indices that DID NOT contain null items, and nulls for items with input indices that DID have nulls.
## What did you see instead?

If input list contained any nulls at all, most nodes (in attached case Geometry.Scale) are not executing any portion of the list.
[List_Replace_Non_Sequential_Items.zip](https://github.com/DynamoDS/Dynamo/files/346560/List_Replace_Non_Sequential_Items.zip)

**Comment by dimven** [comment]
This sounds very similar what I had highlighted earlier:
https://github.com/DynamoDS/Dynamo/issues/5238

Usually a node would fail to execute only if the first item in the list is null or an empty sub-list

**Comment by Curty102** [comment]
Thanks for the reply Dimitar,  I'm pretty new to the GitHub realm.  You do really great (and much) work and have taught me a lot.  I'm attempting to reply via email here.  So how does this work if this issue is similar to the yours?  Does it get added to your thread or does it get it's own (or is this determined by a moderator)?  I tried scouring the forums for this issue, but I guess  I wasn't sure how to "scour" the GitHub repository yet before I submitted.  Again, thanks-- you do great work.
Nick

Date: Mon, 4 Jul 2016 20:00:28 -0700

**Comment by dimven** [comment]
Thanks. Let's keep things as it is. The other issue is already closed. I only mentioned it here so that the work done on that issue can be reviewed and extended or reused, if possible.

**Comment by Curty102** [comment]
@ke-yu or Ian K. or others, I see this as a very high priority for Dynamo.  Being able to split lists by filter or condition, and maintain item indexes weather via using nulls or some other method, and then putting the items back together in order, is crucial for building sophisticated graphs.  Is the best way to help this along to make a starter list of key nodes that don't handle nulls well?

**Comment by andydandy74** [comment]
You should submit any such cases as new issues here or on the DynamoRevit GitHub site. A lot of the Revit-related cases are fixed since Dynamo 1.2 (see #4116).
