### ISSUE TITLE
Contains listed twice

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6849]
## Dynamo version
1.1.1.1841

## Operating system
Windows 10

## What did you do? 
Searched for _Contains_ on the canvas

## What did you expect to see?
One node that matches

## What did you see instead?
Two nodes with the same name and almost identical descriptions

![con1](https://cloud.githubusercontent.com/assets/5621624/16622842/3639315c-43b9-11e6-956d-8deb51f0b6e9.png)
![con2](https://cloud.githubusercontent.com/assets/5621624/16622857/3ffbe89c-43b9-11e6-8bca-5ff7fa9c83de.png)

**Comment by ke-yu** [comment]
Fixed in #6861. 

@riteshchandawar @monikaprabhu  FYI
