### ISSUE TITLE
BoundingBox.ToPolySurface returns surfaces with 50% of surfaces facing inwards

### ISSUE THREAD

**Issue by secretlyagoblin** [DynamoDS/Dynamo#6857]
## Dynamo version

1.0.0.1180
## Operating system

Windows 10
## What did you do?

BoundingBox.ByCorners > BoundingBox.ToPolySurface > PolySurfaces.Surfaces > Surface.NormalAtParameter (0.5, 0.5)
## What did you expect to see?

All normals pointing outward
## What did you see instead?

3 Surfaces facing outward, 3 surfaces facing inwards

<img width="591" alt="screen shot 2016-07-11 at 11 27 03 am" src="https://cloud.githubusercontent.com/assets/13952064/16716812/4f54c1a6-475b-11e6-8797-ae1f7e3793e4.png">
![screen shot 2016-07-11 at 11 26 51 am](https://cloud.githubusercontent.com/assets/13952064/16716813/4f550a26-475b-11e6-90fb-20b2b1fd4c61.png)

**Comment by johnpierson** [comment]
@secretlyagoblin , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
