### ISSUE TITLE
Cant find Curve.DivideEqually command!

### ISSUE THREAD

**Issue by marqmau** [DynamoDS/Dynamo#6896]
When I was doing an exercise I need  the command "Curve.DivideEqually, but  I wrote it to search it but never appears that command, I have the Dynamo for revit 1.0.
Please, tell me what I need to do.

**Comment by aparajit-pratap** [comment]
@marqmau `Curve.DivideEqually` has been deprecated. Use `Curve.PointsAtEqualSegmentLength` to create points at equal lengths along the curve and then use those points to split the curve using `Curve.SplitByPoints` to get functionality equivalent to the older `DivideEqually` node. See https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Node-Changes for all the node name changes in recent releases.
