### ISSUE TITLE
Running EnergyPlus from a ZeroTouch node throughs an error

### ISSUE THREAD

**Issue by j12kemp** [DynamoDS/Dynamo#6898]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.0
## Operating system

Windows 7, Windows 10
## What did you do?

Running EnergyPlus from a zero touch library. See code below:

`        public static bool TestRunEplus()
        {
            bool success = false;
            string dllPth = @"C:\Users\jkemp_000\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\Prototype\extra\Eplus";
            SetDllDirectory(dllPth);
            EnergyPlusManaged("C:\EplusTest");
            success = true;
            return success;
        }

```
    [DllImport("energyplusapi.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
    private static extern void EnergyPlusManaged(string filePath);

    [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
    private static extern bool SetDllDirectory(string lpPathName);
```

`
## What did you expect to see?

The code above runs fine from a console application
## What did you see instead?

Once the EneryPlus simulation completes an error occurs. See attached.
![error](https://cloud.githubusercontent.com/assets/9081501/16898567/7c4df31c-4bde-11e6-88e9-ca822c5aca3c.jpg)

**Comment by redinkinc** [comment]
Hey @j12kemp. I had a lot of problems with this, too. I finally managed doing it like this: [DynamoPlus](https://github.com/redinkinc/DynamoPlus). I didn't use it for a long time, that's why it's not updated for Dynamo verison 1.0. But perhaps you can use some parts of it...

**Comment by ke-yu** [comment]
@redinkinc @j12kemp looks the exception is from native code?

**Comment by j12kemp** [comment]
From the exception thrown it looks like it comes from Revit once the simulation is complete. I am running Eplus via the energyplusapi.dll rather than the exe. Looking at @redinkinc source code he is running the exe and using process start variables that I am not doing. Will see if I can do this with running the dll from managed code.
