### ISSUE TITLE
Unable to install latest build

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6917]
## Dynamo version

 DynamoInstall1.1.0.20160720T1648.exe

## Operating system

Windows 10

## What did you do? 

Tried to install newest build

## What did you expect to see?

The installation windows

## What did you see instead?
Error saying a newer version is already installed

![20160721-1](https://cloud.githubusercontent.com/assets/5621624/17020721/cc73c2ba-4f60-11e6-805e-a18707b2489f.png)

**Comment by sharadkjaiswal** [comment]
It seems that you have installed Dynamo 1.1.1 you might need to uninstall both Dynamo core and Dynamo Revit manually

**Comment by ke-yu** [comment]
@vykrum could you please try what @sharadkjaiswal suggest and see if you're able to install it?

**Comment by vykrum** [comment]
@sharadkjaiswal @ke-yu Yes managed to Install after uninstalling current installation
