### ISSUE TITLE
Dynamo crashed when unlinking element.geometry

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/Dynamo#6926]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.0.0.1180
## Operating system

Windows 10 x64
## What did you do?

Unconnecting All Elements from Category from Element.Geometry
## What did you expect to see?

Not to crash :)
## What did you see instead?

It crashed

**Comment by ke-yu** [comment]
Hi @DanielHurtubise it would be quite helpful if you would provide more information about the context of crash -- can the crash be reproduced? What are steps?

**Comment by aparajit-pratap** [comment]
@DanielHurtubise could you attach the call stack for this crash?
