### ISSUE TITLE
Start 1.1 with package very slow

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/Dynamo#6952]
## Dynamo version
1.1.0.2065
## Operating system
Windows 8.1
## What did you do? 
Start Dynamo with package in Roaming folder
## What did you expect to see?
With Dynamo 1.0 starting was fast. Starting Dynamo Sandbox 1.1 without my package takes 5.05 seconds.
## What did you see instead?
Starting Dynamo Sandbox 1.1, even after several times, until the start screen takes 20.51 seconds. Starting a *.dyn file with 5 custom UI nodes takes 5.46 seconds.

**Comment by mjkkirschner** [comment]
@jhubers is there any difference with internet disconnected?

**Comment by sharadkjaiswal** [comment]
@jhubers is it for the first launch of Dynamo Sandbox 1.1 after the install or every launch of Dynamo takes similar amount of time? Upon first launch of Dynamo 1.1 it is migrating some of your application specific data to newer version so it may take some time, but if it's happening consistently then it's definitely an issue.

**Comment by jhubers** [comment]
@mjkkirschner there is no difference with or without internet connection.

**Comment by jhubers** [comment]
@sharadkjaiswal this morning after a night rest it took 38 seconds the first time. Second time took 21 seconds. Yesterday it took about 20 seconds every time.

**Comment by ke-yu** [comment]
@jhubers how many packages installed? 

@sharadkjaiswal would be it related to analytics?

**Comment by jhubers** [comment]
@ke-yu Hi, I only installed my own pCOLAD package. You can find the code at https://github.com/jhubers/pCOLAD-for-Dynamo/tree/0.97. I am on holiday and won't be able to work on this before august 30.

**Comment by jhubers** [comment]
Figured it out. There were many unnecessary dlls in the package, because I forgot again to set the new references to Copy Local = false :( Now it is OK.
