### ISSUE TITLE
Element.Geometry operation failed

### ISSUE THREAD

**Issue by dgoff96** [DynamoDS/Dynamo#6954]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0.2065
## Operating system

Windows 7
## What did you do?

Attempted to use the Element.Geometry node on a slab and was met with error:
"Warning: Element.Geometry operation failed. value cannot be null. parameter name: source"

I was directed to post this hear by Michael Kirschner and reference my dynamo forum post:
https://forum.dynamobim.com/t/element-geometry-operation-failed/5241/5
## What did you expect to see?

Expected to be able to extract solid from floor slabs
## What did you see instead?

"Warning: Element.Geometry operation failed. value cannot be null. parameter name: source"

**Comment by mjkkirschner** [comment]
@jnealb another failing geo conversion.

**Comment by jnealb** [comment]
@mjkkirschner @dgoff96 We are tracking with MAGN-10473.

**Comment by kronz** [comment]
Looks like Element.Geometry is failing if you have an interior opening on a slab with an elliptical sketch.

**Comment by natethegrate1** [comment]
Did this ever get resolved? I am running 1.2 and getting the same error.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2153).
