### ISSUE TITLE
DYNAMO OVERWRITES DYF FILES TO EARLIER, UNSAVED STATES UPON CRASHING

### ISSUE THREAD

**Issue by brianringley** [DynamoDS/Dynamo#6961]
## What did you do?

Dynamo crashed (upon placing SunSettings.Current node, though I don't suspect the particulars of the crash matter)
## What did you expect to see?

My *.dyf files unchanged.
## What did you see instead?

All *.dyf files have reverted to prior, unsaved states. Most of my most recently saved states are lost. The prior, unsaved states appear to be almost random per node - basically all *.dyf files now represent a moment where I was in the process of editing them, but none of these moments correspond with an actual save action. This is honestly one of the weirdest Dynamo bugs yet. It's worth mentioning that this behavior has also occurred with @AndrewHeumann

**Comment by ke-yu** [comment]
@Randy-Ma does Dynamo auto backup include .dyf file?

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.
