### ISSUE TITLE
Point.Projection partial failure. No exception warnings or nulls

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6963]
## Dynamo version

1.1.0
## Operating system

Win 10
## What did you do?

Ambition was to import an object representing a road in DWG format (into Revit) and recreate using a floor then edit its points to create the required undulation. Workflow:
1. Import the DWG solid object
2. Extract faces (surfaces)
3. Extract boundary curves from surfaces, then extract Start/End points
4. Prune duplicates
5. Project points to XYPlane = PARTIAL FAILURE
## What did you expect to see?

All the points projected to the plane
## What did you see instead?

Majority of points projected. Some failed for reasons unknown. There are no warnings and no nulls:
![image](https://cloud.githubusercontent.com/assets/18601851/17271197/8b4481ee-566d-11e6-876e-8826d8251277.png)

I tried changing the lacing (kind of pointless as plane is a single object) scaling the plane, and also the vector since Dynamo has had issues with normalised vectors in the past (#6644). I also tried creating Line.ByStartPointDirectionLength (all lines successfully create), then use Geometry.Intersect as a workaround. Still fails the same points. I also isolated one of the problem points and tried projecting it, but...fails. Bug, or am I missing something? (Before the question of working limits is raised, its not an issue, the object is approx 100m long and in the centre of the Revit project)

**Comment by ThomasMahon** [comment]
So, looks like planes in Dynamo have a limit! WTF! Planes are infinite! Why are planes implemented with limits?

**Comment by ThomasMahon** [comment]
If I use Curve.Pull onto plane (using the boundary curves), it works. Why is this so inconsistent?

![image](https://cloud.githubusercontent.com/assets/18601851/17276971/7ed97f82-572f-11e6-9b50-c7fe370d9b3b.png)

**Comment by ke-yu** [comment]
@aparajit-pratap @Randy-Ma

**Comment by kronz** [comment]
@aparajit-pratap is this a large units error?

**Comment by aparajit-pratap** [comment]
I'm suspecting this is because planes are being treated as limited surfaces and the projections being evaluated on the surfaces. Ideally a plane should be treated as an infinite object and the projection evaluated using its analytic equation.

**Comment by monikaprabhu** [comment]
@ThomasMahon - Could you please share the data set with us so we can test a fix we made for ASM scaling issue, https://github.com/DynamoDS/Dynamo/pull/6991.Alternatively you can test it in 1.2.3 builds and let us know. Feel free to email me the files at monika.prabhu@autodesk.com

**Comment by ThomasMahon** [comment]
@monikaprabhu this appears to be fixed in 1.2.1.

![image](https://cloud.githubusercontent.com/assets/18601851/22970731/2191853a-f36b-11e6-882b-d745771898ff.png)

**Comment by monikaprabhu** [comment]
@ThomasMahon - Great to know its fixed at your end. Thanks for reporting the issue.
