### ISSUE TITLE
FamilyInstance.ByPointAndLevel inconsistent Z value

### ISSUE THREAD

**Issue by eibre** [DynamoDS/Dynamo#6975]
## Dynamo version

1.1.0.2094
## Operating system

Windows 10
## What did you do?

The end goal was to replace a slab with a isolated footing. Refer to this thread in the dynamo forum: https://forum.dynamobim.com/t/swapping-structural-foundation-slabs-with-iso-footings/5292/4
### Step 1: Feed the centriod directly

Looks like the new instance is placed relative to the level it was assigned
![image](https://cloud.githubusercontent.com/assets/5968613/17343524/7a5aff1e-58fe-11e6-8026-f38d6ac05ece.png)
### Step 2: Try to move the centroid to the level elevation

I try to move the point by the levels elevation and gets the same result as in step 1.
![image](https://cloud.githubusercontent.com/assets/5968613/17343549/8c6cc494-58fe-11e6-8386-87c9f69589dd.png)
### Step 3: Go back to step 1.

when I reconnect Solid.Centroid to point, I get the expected result.
![image](https://cloud.githubusercontent.com/assets/5968613/17343561/963ba4fe-58fe-11e6-9469-95ef53fe0ebd.png)
## What did you expect to see?

![image](https://cloud.githubusercontent.com/assets/5968613/17343561/963ba4fe-58fe-11e6-9469-95ef53fe0ebd.png)
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/5968613/17343524/7a5aff1e-58fe-11e6-8026-f38d6ac05ece.png)

**Comment by eibre** [comment]
Here is the file (rename to .dyn)
[replace-foundation.dyn.txt](https://github.com/DynamoDS/Dynamo/files/398048/replace-foundation.dyn.txt)

**Comment by ke-yu** [comment]
@riteshchandawar

**Comment by eibre** [comment]
This might be related: https://forum.dynamobim.com/t/create-instance-by-point-error/5516/4

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2152).
