### ISSUE TITLE
Math.Round returns double but description says it should be integer.

### ISSUE THREAD

**Issue by eibre** [DynamoDS/Dynamo#6980]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.1.0.2094

## Operating system

Win10

## What did you do? 

Used Math.Round to round a number. Expected a integer after reading the description of the node.
![image](https://cloud.githubusercontent.com/assets/5968613/17359720/2a6f4a90-5968-11e6-855b-441f30508404.png)

## What did you expect to see?

Int32

## What did you see instead?

Double

**Comment by ke-yu** [comment]
@Racel @eibre Do you think this description make sense?
"Round a number to the closes integral value".

And for output:
"Integral value closes to the number."

**Comment by Racel** [comment]
@ke-yu - I think the descriptions you have made make more sense, but I'm wondering if these descriptions would still confuse users.

Maybe we should add the following line to the description. "Note that this method returns a Double instead of an integral type." I'm using this as a guide: https://msdn.microsoft.com/en-us/library/wyk4d9cy(v=vs.110).aspx

**Comment by eibre** [comment]
@ke-yu @Racel Why not return an integer? (You probably have a good reason) The port on the node states "Int", and it is a bit confusing that it shows a double with no decimal zeroes.
![image](https://cloud.githubusercontent.com/assets/5968613/17372381/ee4afbea-59a3-11e6-9b40-259e3ea6ee70.png)

I was actually looking for a way to convert a double to a int, this is the only way I can think of when Math.Round fails:
![image](https://cloud.githubusercontent.com/assets/5968613/17372325/acde2b0a-59a3-11e6-839a-2120429b90ac.png)

**Comment by ke-yu** [comment]
@eibre simple reason is `double` value has wider range than an integer. 

We could write a function to convert an input to integer:

![toint](https://cloud.githubusercontent.com/assets/2600379/17386342/7845c528-5a1c-11e6-8373-179b90e0b653.png)

**Comment by ke-yu** [comment]
Fixed in PR #6987. :-)

**Comment by vykrum** [comment]
@eibre  

> I was actually looking for a way to convert a double to a int
![issue-20160823-2](https://cloud.githubusercontent.com/assets/5621624/17895576/2c950072-696b-11e6-9f95-69cf509cbfc6.png)

**Comment by eibre** [comment]
@vykrum @ke-yu I don't understand why Math.Floor or .Ceiling should give different results than .Round?

This works very well though:
![image](https://cloud.githubusercontent.com/assets/5968613/17895781/7428a5b4-694e-11e6-98b8-6cdbe2be4874.png)

**Comment by vykrum** [comment]
@eibre 

> I don't understand why Math.Floor or .Ceiling should give different results than .Round?

I think it's because _Math.Round_ has an overload where you can specify number of decimal places. That can't be an integer :-)

**Comment by eibre** [comment]
@vykrum Looks like they are two separate functions to me:
https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodes/Math.cs
```
        /// <summary>
        /// Rounds a number to the closest integral value.
        /// Note that this method returns a double-precision floating-point number instead of an integral type.
        /// </summary>
        /// <param name="number">Number to round.</param>
        /// <returns name="number">Integral value closes to the number.</returns>
        public static double Round(double number)
        {
            return CSMath.Round(number);
        }

        /// <summary>
        /// Rounds a number to a specified number of fractional digits. 
        /// </summary>
        /// <param name="number">Number to be rounded.</param>
        /// <param name="digits">Number of fractional digits in the return value.</param>
        /// <returns name="number">The number nearest to value that contains a number of fractional digits equal to digits.</returns>
        public static double Round(double number, int digits)
        {
            return CSMath.Round(number, digits);
        }
```

**Comment by eibre** [comment]
@vykrum The reason given by Ke-Yu above, is wider range in double. In this example Math.Round works but .Ceil and .Floor returns 0. (maybe they should have given a warning?)
![image](https://cloud.githubusercontent.com/assets/5968613/17908837/57212124-6982-11e6-80ce-9d0babd9ac35.png)

**Comment by ke-yu** [comment]
@eibre `Math.Ceiling` and `Math.Floor` returns an integer, in this case the number is too large. Yes I think they should throw some warnings.
