### ISSUE TITLE
Export Workspace as Image needs background white and higher resolution

### ISSUE THREAD

**Issue by schmiedman** [DynamoDS/Dynamo#6986]
## 1.0.0.1180

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 7 Prof

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Used 'Export Workspace as Image'

## What did you expect to see?

White background - higher resolution

## What did you see instead?

Drab olive background and image to low res to see node information.
Perhaps resolution and background color could be settable.

**Comment by ke-yu** [comment]
hi @schmiedman Export workspace to image has been enhanced in PR https://github.com/DynamoDS/Dynamo/pull/6786, could you please try 1.1 (we just released it)?

**Comment by schmiedman** [comment]
Hey @ke-yu - I just tried it in 1.1 and it looks great. Much better resolution on the node titles etc... Also, I think my background color problem had to do with what I was opening it in and not the export. I noticed it has a transparent background, which is nice... Thanks!
