### ISSUE TITLE
Excel Nodes Fail

### ISSUE THREAD

**Issue by sixtysecondrevit** [DynamoDS/Dynamo#6992]
## Dynamo version

Dynamo 1.1.0

## Operating system

Windows 7 and Excel 2010

## What did you do? 

Created a simple excel file with letters in column 1, then placed excel read nodes in Dynamo.
![2016-08-04 12_03_48-dynamo](https://cloud.githubusercontent.com/assets/15744724/17413440/71c30108-5a3e-11e6-8a11-36a7fa43bc12.png)

## What did you expect to see?

Dynamo read the excel file

## What did you see instead?

Excel.ReadFromFile operation failed. 
![image](https://cloud.githubusercontent.com/assets/15744724/17413502/ad7eb5ac-5a3e-11e6-9781-d5fd7372745a.png)

##Excel file here.
[Book1.xlsx](https://github.com/DynamoDS/Dynamo/files/402337/Book1.xlsx)

**Comment by ThomasMahon** [comment]
Have you installed new versions of Office recently then rolled back to an older version?

**Comment by NCrane** [comment]
I had the same problem. It seems to me that the problem is having spaces in the file name. The path the File.FromPath node passes through to the Excel node isn't the correct path.
![capture](https://cloud.githubusercontent.com/assets/17646845/17804986/3094b4e8-65f5-11e6-8af4-cb34c3721902.JPG)

**Comment by mjkkirschner** [comment]
I think these are different issues - the path above has no spaces. (I have seen the spaces issue with File.FomPath though) will check if it is filed.

**Comment by sixtysecondrevit** [comment]
This was resolved by removing a bad key in the registry. https://github.com/DynamoDS/Dynamo/wiki/Known-Issues

**Comment by cphubb** [comment]
I looked at the above link and the key in question is not there, but my Excel Nodes are not only failing but crashing Dynamo.
