### ISSUE TITLE
Dynamo crash

### ISSUE THREAD

**Issue by haninh2612** [DynamoDS/Dynamo#7030]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0
## Operating system

Windows 7
## What did you do?

Install software
## What did you expect to see?

Crash dynamo
![image](https://cloud.githubusercontent.com/assets/10362156/17616483/3b1d96c4-609f-11e6-8a30-7f990e2b0e83.png)
## What did you see instead?

(Fill in here)

**Comment by sharadkjaiswal** [comment]
Sorry to see that Dynamo has crashed. Can you please copy and paste the content of the dialog by pressing Copy button on the crash dialog?

**Comment by haninh2612** [comment]
Following is the bug statement: 

Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)

   at CSharpAnalytics.WinFormAutoMeasurement.SetupRequesterAsync()
   at CSharpAnalytics.BaseAutoMeasurement.<StartRequesterAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


Thank you :).

**Comment by sharadkjaiswal** [comment]
Can you please check if you have	System.Net.Http.dll	 at C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\

**Comment by haninh2612** [comment]
I checked that folder and it missing the System.Net.Http.dll file. I copied
that file to that folder, the Dynamo did not show the bug windows but still
it did not run :(.

Best Regards,

*Truong Huu Ha **Ninh*
*Team leader of BIM Department*

*h <nthh@mth.dk>aninh2612@gmail.com <aninh2612@gmail.com>**+84 972362712*






*BIM FM A/S21st Floor180-192 Nguyen Cong Tru street,Ward Nguyen Thai
Binh, District 1,Ho Chi Minh City, Vietnam.*

**Comment by sharadkjaiswal** [comment]
Can you please check if .NET framework 4.5 is installed on your system or not. You may download the .NET framework installer from https://www.microsoft.com/en-sg/download/details.aspx?id=30653

**Comment by sharadkjaiswal** [comment]
@haninh2612 Do you still see this issue? Can you please try with the [latest daily build](http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoInstall1.1.1.20160816T1250.exe) and verify this issue is fixed?

**Comment by smangarole** [comment]
@haninh2612 Can you please verify if you are still seeing this issue? We fixed this issue and should be available in Dynamo 1.3.0.

Closing this issue. Please re-open if it resurfaces.
Thanks.

**Comment by haninh2612** [comment]
Hi,

I would like to confirm that problem was fixed :).
Thank you for all of your supports.

Best Regards,

*Ninh *Truong Huu Ha



*BIM LeaderFounder of www.revitandbim.com
<http://www.revitandbim.com>Mobile: +84 972362712Linkedin:
www.linkedin.com/in/ninhtruong <http://www.linkedin.com/in/ninhtruong>*
