### ISSUE TITLE
Weird behaviour when escaping a backslash at the end of a string in code blocks

### ISSUE THREAD

**Issue by regnstr** [DynamoDS/Dynamo#7044]
## Dynamo version

1.1.0

## Operating system

Windows 10

## Description

Escaping a backslash at the end of a string literal in a code block seems to be bugged. I noticed this while trying to construct a file path using code blocks.

![string literal](https://cloud.githubusercontent.com/assets/11628576/17691407/85491c8a-6394-11e6-979e-db5fac36bdfb.png)

In the first and second code blocks, the string `Hello\` is returned, which is odd for the first block but expected for the second.

In the third code block, the backslash escapes the quotation mark and the code block produces an error. This is expected.

In the fourth, the backslash should be escaped and the output should be the same as the second code block, but I'm getting an error (it just says "Error: error").

**Comment by ke-yu** [comment]
Fixed in #7068
