### ISSUE TITLE
Improvement: Faster node output preview

### ISSUE THREAD

**Issue by regnstr** [DynamoDS/Dynamo#7045]
Hello!

I would love it if the node output preview appeared faster when hovering the mouse over a node (or remove the delay completely), I think it feels sluggish.

Pinning the preview feels better in 1.1.0, good job!

//Isak

**Comment by dimven** [comment]
It would be even better if we had the option to turn off all animations in Dynamo and have things like node preview, drop-down menus, etc. show instantly.

**Comment by ikeough** [comment]
@Racel

**Comment by ke-yu** [comment]
This should have been fixed in #7052.

**Comment by Racel** [comment]
Thanks for the feedback @regnstr - We have fixed the sluggishness of the output preview. Check out the latest daily build. Let us know if you are still experiencing issues. For now, I am closing this.

**Comment by smangarole** [comment]
@regnstr Please check Dynamo 1.3.0. Please open a new issue if you are still experiencing the sluggishness. Thanks.
