### ISSUE TITLE
When an error occurs in custom node, getting error message

### ISSUE THREAD

**Issue by cjm771** [DynamoDS/Dynamo#7046]
Is there a way to get an output / log From a custom node? It is hard to debug when things aren't working in a custom node. It does not display the yellow message. I was hoping there would be some kind of function like Dynamo.getWarningsLog() or Dynamo.getErrorsLog() that I can shoot to an output parameter. thanks.

**Comment by mjkkirschner** [comment]
@cjm771 what kind of custom node do you mean? one defined in the UI (a subgraph)? or a zero touch or node model node that's implemented in .net?

**Comment by cjm771** [comment]
Hi Michael,

This is done with your (subgraph). If there was a way to query the errors or warnings after the process ran ,it would be great feedback, as currently there is no feedback. 

For example on the setparameterbyname which is used inside the node, one of the parameters was readonly and gave an error when trying to set.. but because it was inside a custom node , for the user, they could not see what was happening and had no way of resolving their issue.

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
