### ISSUE TITLE
Preview Bubble in 1.1.1 takes forever to expand

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7057]
## Dynamo version
1.1.1

## Operating system
Windows 10

## What did you do? 
Attemped to further expand and view the list in preview bubble of a code block by moving the cursor over the unexpanded preview _List(45000)_ 

## What did you expect to see?
Instant expansion of bubble as in 1.1.0

## What did you see instead?
Doesn't expand. Takes forever for large lists.

**Comment by sharadkjaiswal** [comment]
#7052 should fix this issue. Thanks for reporting.

**Comment by ksobon** [comment]
also duplicate of this: https://github.com/DynamoDS/Dynamo/issues/7045

**Comment by Racel** [comment]
Closing this as it was addressed in #7052
