### ISSUE TITLE
Unable to distinguish Double from Integer

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7071]
## Dynamo version

1.1.1.2346
## Operating system

Windows 10
## What did you do?

Tried to obtain indices of a value, as represented in _Math.Round_ preview bubble
## What did you expect to see?

The indices
## What did you see instead?

Empty Lists (as the number is a double and not an integer)
If it is expected behavior, it would help if the preview bubble reflects that. 
If **1** is a double it should be represented as **1.0**

![issue-20160823-1](https://cloud.githubusercontent.com/assets/5621624/17881920/ac145d10-6926-11e6-8d17-47c33f452e9e.png)

**Comment by eibre** [comment]
Seems related to this https://github.com/DynamoDS/Dynamo/issues/6980

I agree that 1.0 would be more clear than 1.

**Comment by vykrum** [comment]
A suggestion, not sure if it's possible
![issue-20160823-3](https://cloud.githubusercontent.com/assets/5621624/17895809/ebbf6dca-696b-11e6-9121-d8ce15c03999.png)

**Comment by johnpierson** [comment]
This appears to be fixed in 2.0.2
![image](https://user-images.githubusercontent.com/15744724/50008365-2ca1f900-ff71-11e8-865a-3fd3d06d7901.png)
