### ISSUE TITLE
Longest by default

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7080]
## Dynamo version
1.1.1.2352

## Operating system
Windows 10

## What did you do? 
Inserted  _Sequence_ and _Range_ nodes on the canvas.

## What did you expect to see?
As with other nodes, expected Lacing set to _Shortest_ by default
May not really affect the way the nodes function, but is inconsistent.

## What did you see instead?
Is this intentional?
![longest](https://cloud.githubusercontent.com/assets/5621624/17977547/ccc8e8f6-6b0f-11e6-86dc-eaf9e0b08b9b.png)

**Comment by ke-yu** [comment]
@Racel @riteshchandawar @monikaprabhu  I don't remember that we intentionally set these nodes' lacing to Longest.

**Comment by riteshchandawar** [comment]
@ke-yu Neither I remember. Can you please change it to Shortest?

Thanks,
Ritesh

**Comment by samuelcwl** [comment]
PR made for this fix: https://github.com/DynamoDS/Dynamo/pull/7146
