### ISSUE TITLE
Custom UI node question

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7099]
Is there a way to override how custom UI nodes store their information (serialize) so that when I close my model and re-open it, I can return my node to its last saved state? 

Can someone point me to an example? 

Cheers!

**Comment by mjkkirschner** [comment]
@ksobon totally, check out how the python node saves its number of ports

**Comment by ksobon** [comment]
Is that what you mean? https://github.com/DynamoDS/Dynamo/blob/24d5303986ee8ac18186c17abccbd2a80db5a66e/src/Libraries/PythonNodeModels/PythonNode.cs

**Comment by ksobon** [comment]
I found it here. Works great! Thanks for the tip. https://github.com/DynamoDS/Dynamo/blob/24d5303986ee8ac18186c17abccbd2a80db5a66e/src/Libraries/PythonNodeModels/PythonNode.cs
