### ISSUE TITLE
Dividing/Splitting Surfaces Causing Crash

### ISSUE THREAD

**Issue by briandeyoung** [DynamoDS/Dynamo#7100]
## Dynamo version

1.1.0
## Operating system

Windows 7 Enterprise
## What did you do?

Need to divide or split a surface in two directions
## What did you expect to see?

A grid of smaller surfaces - in order to eventually place adaptive components.
## What did you see instead?

It runs once, then if any changes are made or parameters altered it crashes Revit. Does not seem to crash Dynamo, but Dynamo is brought down by Revit.

[Dynamo Files.zip](https://github.com/DynamoDS/Dynamo/files/447757/Dynamo.Files.zip)

**Comment by aparajit-pratap** [comment]
I can reproduce the crash using this updated file:
[Dividing Surface - Alternate Method.zip](https://github.com/DynamoDS/Dynamo/files/468905/Dividing.Surface.-.Alternate.Method.zip)
 but cannot reproduce consistently

**Comment by aparajit-pratap** [comment]
@jnealb?

**Comment by jnealb** [comment]
@aparajit-pratap Will take a look
