### ISSUE TITLE
Flatten and List.Map break list structure when input list starts with sublist containing only empty lists

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#7116]
## Dynamo version

1.1 stable

## Operating system

Windows 7

## What did you do? 
Tried to flatten sublists like so:
![mapflatten](https://cloud.githubusercontent.com/assets/3014437/18248247/5ad999dc-7377-11e6-8011-73b308f950e3.PNG)

## What did you expect to see?

[0] Empty List
[1] Empty List
[2] List
____[0] 1
____[1] 2

## What did you see instead?
[0] List
____[0] 1
____[1] 2

It looks like the cause for this is the fact that the first sublist only contains ```Empty List```s, as altering the list structure like so will preserve the original list structure:
![mapflatten2](https://cloud.githubusercontent.com/assets/3014437/18248539/1bbb04aa-7379-11e6-9a58-762370ae72ae.PNG)

I have the feeling that I have submitted this issue before but couldn't find it. Sorry if this is indeed a duplicate.

**Comment by ke-yu** [comment]
Looks the problem is `Count()` (`List.Map()` internally uses `Count()` to put the result to the corresponding position) -- `Count({List.Empty, List.Empty})` return 0 instead of 2.
