### ISSUE TITLE
Dynamo doesn't work after Installation of Visual Studio Express 2015!!

### ISSUE THREAD

**Issue by calmwish** [DynamoDS/Dynamo#7119]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.1.0

## Operating system

Windows 8.1

## What did you do? 

I've installed Visual Studio Express 2015

## What did you expect to see?

outputs in Dynamo

## What did you see instead?

All Outputs returns "Null" and I see no result, even I tried to load basic files, but also don't work.
It happens, after I've installed VSE2015 :(

**Comment by sharadkjaiswal** [comment]
@calmwish, are you using Dynamo for Revit or Dynamo Studio? Did you launch Dynamo on Revit? Can you please try launching DynamoSandbox.exe from `C:\Program Files\Dynamo\Dynamo Revit\1.1\` folder?

**Comment by calmwish** [comment]
Well, I use Dynamo on Revit. Anyway I found a solution.
When I copy my definitions to new empty dynamo scratch, then it works.
I don't know what happens, but I can work further...
