### ISSUE TITLE
I can't type inside Code-Block nodes.

### ISSUE THREAD

**Issue by rndl** [DynamoDS/Dynamo#7132]
## Dynamo version
Dynamo 1.1

## Operating system
Windows 7

## What did you do? 

I created a new 'Code-Block' node by doubleclicking

## What did you expect to see?

When trying to type inside the node nothing happens. The same happens when trying to type in existing Code-Block nodes in loaded *,dyn files. 

## What did you see instead?

The nodes remain empty, cold and lifeless. I can only change their names, but not the content.
![mypain](https://cloud.githubusercontent.com/assets/22093472/18379009/81600982-7670-11e6-8964-e613973f5088.jpg)

**Comment by sharadkjaiswal** [comment]
@rndl not sure if it's related to #7130

**Comment by jnealb** [comment]
@sharadkjaiswal @rndl This issue has been seen by me with D4R 1.2.0.2573, but after un-install/install the issue has cleared up. We are investigating.

**Comment by jnealb** [comment]
This is tracked with MAGN-10678

**Comment by kronz** [comment]
Update, this appears to be the result of a conflicting AvalonEdit library.  Current theory is if some function in Revit invokes some particular text editing interface, the subsequent runs of Dynamo will have this appearance in Code blocks.  Still investigating fix

**Comment by QilongTang** [comment]
Please check similar discussion in issue https://github.com/DynamoDS/Dynamo/issues/7130. This has been fix in 1.2.
