### ISSUE TITLE
New node beyond visible canvas

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7139]
## Dynamo version

1.2.0.2513
## Operating system

Windows 10
## What did you do?

![issue-20160910](https://cloud.githubusercontent.com/assets/5621624/18407741/639403f0-7737-11e6-8bde-20616c548a26.gif)
## What did you expect to see?

The node selected from the right click search to be added within the visible extent of the canvas
## What did you see instead?

It is added, but beyond the visible extents of the canvas. Need to zoom out.

**Comment by Racel** [comment]
Thanks @vykrum - This is a known issue. It was filed here: https://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10568

**Comment by Racel** [comment]
Should be fixed here and available in next release: https://github.com/DynamoDS/Dynamo/pull/7259
