### ISSUE TITLE
Dynamo point at different files

### ISSUE THREAD

**Issue by tayday01** [DynamoDS/Dynamo#7140]
Dynamo needs an OTB way to be able to point it at different documents. Instead of closing and reopening dynamo every time to run a script you should be able to chose the file it is pointing at, that is open in that current revit session. I see it working much like the way revit's "switch windows" tool works.  THANKS!

![599e956797195307894309fd49c2727aae34f971_1_690x265](https://cloud.githubusercontent.com/assets/19196457/18414419/eca3c13c-777b-11e6-8498-6db39ee06b72.jpg)

**Comment by smangarole** [comment]
@tayday01 We visited this sometime back. Right now we will not be tackling this issue for the upcoming release. Closing this ticket for now. 

Thanks.

**Comment by Hauk-Lykke** [comment]
I agree with @tayday01, this is very much functionality I miss from Dynamo, almost every time I use it.

**Comment by Hauk-Lykke** [comment]
It's been 5 years, is it time to start revisiting the idea?
