### ISSUE TITLE
Node label color

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7149]
## Dynamo version

1.2.0.2573
## Operating system

Windows 10
## What did you do?

Checked _Use Levels_ and _Keep List Structure_ in a node
The input node label changed color on checking _Keep List Structure_
Unchecked _Use Levels_
The _Keep List Structure_  is now greyed out and unavailable
## What did you expect to see?

The input label to revert to it's original state
## What did you see instead?

The color remains
![20160914-4](https://cloud.githubusercontent.com/assets/5621624/18515308/8733b1ba-7ab2-11e6-94c0-b1300aa5d6bd.png)

**Comment by jnealb** [comment]
fyi @Racel

**Comment by Racel** [comment]
Thanks, @vykrum - Filed it as a bug in our backlog: https://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10677

**Comment by Racel** [comment]
Addressed here and fixed: https://github.com/DynamoDS/Dynamo/pull/7202
