### ISSUE TITLE
Dynamo open multiple files window function?

### ISSUE THREAD

**Issue by zhadiqi** [DynamoDS/Dynamo#715]
Hello：

```
   Now，Dynamo can be developed to support multiple dyn. format files window operation?   Currently supports a file operation, not a good idea.
```

**Comment by chriswmackey** [comment]
The ability to open multiple tabs of dyn files would be incredibly helpful.  I find myself having to close and then rerun dyn files every time I switch between two of them.  This rerunning is fine for quick scripts but the lack of tab-switching is currently limiting how computationally intensive I am willing to build dynamo scripts right now.

**Comment by ke-yu** [comment]
Supporting multiple workspaces definitely is in our radar :-)

**Comment by zhadiqi** [comment]
notifications@github.com

**Comment by zhadiqi** [comment]
We waited four years, don't fail us now.

**Comment by Racel** [comment]
We had several internal projects around multiple workspaces that have not been pushed to master. We understand that our customers want to be able to easily work with multiple workspaces simultaneously without having to rerun the graph. We are looking at other options other than tabs to resolve this problem. Closing for now, but please note that this is being actively considered in the next generation of Dynamo.

**Comment by ArchitectTaeyoon** [comment]
Couldn't you look at... how Grasshopper does it..?

**Comment by RitaAguiar** [comment]
Is this possible yet? It would be very advantageous.

**Comment by shanedo2** [comment]
Is this still not possible @Racel? We'd love this functionality.

**Comment by colinmccroskey** [comment]
Any update on this? Would be really helpful to copy/paste nodes between scripts...

**Comment by cobyiv** [comment]
Bump, really need this!

**Comment by onurgoztepe** [comment]
Still waiting. how dynamo cannot reach this functionality as grasshopper does so many years ago
