### ISSUE TITLE
Dynamo do not watch 3D and background

### ISSUE THREAD

**Issue by MichaelKonovalov** [DynamoDS/Dynamo#7171]
## Dynamo version
1.2.0.2514

## Operating system

Windows 7

## What did you do? 

I just started to learn and follow the examples. (The Dynamo Primer)

## What did you expect to see?
background and geometry (visibility is enabled)

## What did you see instead?
hothing :(
![capture](https://cloud.githubusercontent.com/assets/22279949/18618358/a7687674-7dfe-11e6-9485-62ee9f6a075f.png)

**Comment by mjkkirschner** [comment]
please see first question in faq:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by MichaelKonovalov** [comment]
Thanks a lot
