### ISSUE TITLE
DetailCurve.ByCurve won't work in drafting view

### ISSUE THREAD

**Issue by sixtysecondrevit** [DynamoDS/Dynamo#7172]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 1.2.0 Release Candidate

## Operating system

Windows 7

## What did you do? 

Fed the DetailCurve.ByCurve node a list of curves and a selected drafting view.

## What did you expect to see?

Detail lines in my drafting view.

## What did you see instead?

"View does not support annotation" error.

**Comment by kronz** [comment]
Fixed, with https://github.com/DynamoDS/DynamoRevit/commit/5ed4ddb1d84033c52ae3454ecb0c11eb237c41c7
