### ISSUE TITLE
Dynamo Crash 

### ISSUE THREAD

**Issue by YSR01** [DynamoDS/Dynamo#7173]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0
## Operating system

Windows 7
## What did you do?

Launch application from Revit 
## What did you expect to see?

Start Menu, Recent files etc 
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/18330475/18629696/4295eb8a-7e5f-11e6-9a37-b036aa2d562c.png)

**Comment by jnealb** [comment]
@YSR01 We think this is fixed with the newer daily builds, is it possible for you to check?

**Comment by jnealb** [comment]
Thank you

**Comment by sharadkjaiswal** [comment]
@YSR01 can you please share your `%appdata%\Analytics\CSharpAnalytics-MeasurementSession` file. I think this file has got corrupt. Please share the file before deleting it.

**Comment by YSR01** [comment]
Hi, I did delete it and it worked fine. Thank you very much.

**Comment by jnealb** [comment]
@sharadkjaiswal @mjkkirschner Is this a case of MAGN-5263 that we missed?
