### ISSUE TITLE
DynamoCore doesn't uninstall cleanly

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#7179]
## Dynamo version

1.1 stable
## Operating system

Win 7
## What did you do?

Uninstall Dynamo, first DynamoCore, then DynamoRevit
## What did you expect to see?

Both apps removed from list of apps in Windows Control Panel
## What did you see instead?

DynamoCore was still there. Needed to choose the uninstall option again for Windows to recognize that "something went wrong during uninstall - the product has already been uninstalled" and then remove the app from the list of installed apps.

BTW: It would be nice if uninstalling DynamoCore gave me an option of also uninstalling any other installed Dynamo modules.

@sharadkjaiswal

**Comment by andydandy74** [comment]
Also, installing a newer version of Dynamo levaes me with multiple installations of Dynamo Core.
Not good at all.
![twodynamocores](https://cloud.githubusercontent.com/assets/3014437/21175417/7e4ae0c4-c1e2-11e6-899f-3724a17af456.PNG)
CC @kronz

**Comment by sharadkjaiswal** [comment]
@andydandy74 not sure what went wrong on your system. Can you please try this utility to clean up the registry https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed.

**Comment by andydandy74** [comment]
@sharadkjaiswal  - Another thing that just came up: 
Under Windows 10 we're unable to uninstall Dynamo Core 1.2.1:
![cantuninstallcorewin10](https://cloud.githubusercontent.com/assets/3014437/21177888/62c23aa4-c1ed-11e6-8d79-d235e277a038.png)
Can you advise how to proceed on that one? Manual delete of folder contents + the MS tool?

**Comment by sharadkjaiswal** [comment]
You can use add remove program from control panel to uninstall Dynamo core.

**Comment by dbaldacchino** [comment]
Been running into this problem as well. The uninstall doesn't complete (being done programmatically via VBScript and WMIC), at least not in all cases.

I am really, totally, against what Autodesk is doing with Revit updates where they are now including Dynamo. It's causing us a lot more trouble than it's worth. So for example when we installed 2017.1 and then I needed Dynamo 1.2.1, I have to remove 1.2.0 and then install 1.2.1. I understand why you're doing this (I assume to increase the number of installs), but from a practical standpoint, it's starting to get annoying.

**Comment by andydandy74** [comment]
Strongly agree with @dbaldacchino - deploying 2017 1.1 without Dynamo 1.2 was no fun at all (to use a friendly euphemism). Bundling up Revit with Dynamo is a nice idea, but **PLEASE** give us better deployment options.

**Comment by andydandy74** [comment]
Haven't seen this come up again. Closing.
