### ISSUE TITLE
Dynamo Script does not work when Dynamo Preview is on

### ISSUE THREAD

**Issue by cjm771** [DynamoDS/Dynamo#7187]
![weird_dynamo_error](https://cloud.githubusercontent.com/assets/4239492/18721152/03de66fc-7fe4-11e6-832f-97b5679557aa.PNG)
## Dynamo version

v1.1 + v1.0
## Operating system

Windows 7
## What did you do?

Run the script
## What did you expect to see?

The script work as per usual
## What did you see instead?

An error screen in the background preview. 
## How did i resolve this?

I turned off the preview, and ran again. the script ran.

**Comment by sharadkjaiswal** [comment]
@cjm771, thanks for reporting this issue. It looks like some issue with rendering of some specific geometry. Can you please share your graph for investigation?

**Comment by johnpierson** [comment]
This issue was reported for version 1.x. Can you confirm for us if this is still an issue for you in Dynamo 2.0.x? If this is still an issue, feel free to reopen with more information.

**Comment by cjm771** [comment]
I haven’t encountered this issue in Dynamo 2.0. I think its all good now thanks for the follow up!
