### ISSUE TITLE
Running DynamoSandbox.exe with command line options

### ISSUE THREAD

**Issue by choiie** [DynamoDS/Dynamo#7200]
## Dynamo version

1.1.0
## Operating system

Win 7
## What did you do?

Try to debug a Dynamo package by running dynamosandbox.exe from VisualStudio, with a .dyn file as command line option.
## What did you expect to see?

The .dyn file opening along within Dynamo Sandbox. (Similar to Revit.exe running a .rvt file if supplied as command line option.)
## What did you see instead?

Nothing happened. Apparently there's no real command line options for DynamoSandbox, as far as I could tell.

**Comment by andydandy74** [comment]
As you've already discovered DynamoSandbox.exe doesn't support command line options. The executable you'll want to use is DynamoCLI.exe - documentation can be found here: https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Command-Line-Interface
