### ISSUE TITLE
Tag.ByElement won't take a sheet as a view

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#7206]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.2.0
## Operating system

Windows 7
## What did you do?

Used Tag.ByElement per example files. Only difference was view input was sheet. We place our revision clouds on the sheet rather than in the viewport, which is where this workflow came up.
## What did you expect to see?

Revision tag generated.
## What did you see instead?

Yellow error, it seems sheets are not supported.
![image](https://cloud.githubusercontent.com/assets/20781221/18879691/839d71dc-8492-11e6-806c-46f5b06f26e0.png)

**Comment by jhubers** [comment]
Hi @johnpdps. Could you tell me which example has the Tag.ByElement. I can't get it to work. Not sure what kind of string e.g. horizontalAligment is expecting. I tried with a room and a floor. Only get the error that if failed :(

**Comment by sixtysecondrevit** [comment]
@jhubers , are you asking a question that is simply related to the tag nodes and not this issue itself?

**Comment by jhubers** [comment]
@sixtysecondrevit. Yes. Looking for an example. Don't understand what inputs are needed to make it work.

**Comment by sixtysecondrevit** [comment]
This should help
https://lh3.googleusercontent.com/-c2Fc1LGYK5Q/V9gsmzFVB8I/AAAAAAAABe4/YxKc__CvdRo/Tag.ByElement_thumb%25255B1%25255D.png?imgmax=800

**Comment by jhubers** [comment]
@sixtysecondrevit Thanks. Indeed it helps. Works for a wall. Not for a Room.

**Comment by ksobon** [comment]
This PR https://github.com/DynamoDS/DynamoRevit/pull/1672 should fix this issue. cc: @kronz can we close this here. There is a duplicate in DynamoRevit repo.
