### ISSUE TITLE
Variable Input Node port definition

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7207]
I was trying to upgrade how I do my port definition from the old model using the `OutPortData.Add()` to a new suggested model using the attributes on the class and it makes only my "in ports" get created. 

```
    [NodeName("Create Report")]
    [NodeDescription("Some Description")]
    [NodeCategory("Archi-lab_Mandrill.Report.Window")]
    [IsDesignScriptCompatible]
    [InPortTypes("RowContainer")]
    [InPortNames("RowContainer0")]
    [InPortDescriptions("RowContainer0")]
    [OutPortTypes("Report")]
    [OutPortNames("Report")]
    [OutPortDescriptions("Report0")]
    public class MandrillReportNode : VariableInputNode
    {
        /// <summary>
        ///     Report Node
        /// </summary>
        public MandrillReportNode()
        {
           // OutPortData.Add(new PortData("Report", "OutToolTip0"));
            RegisterAllPorts();
            ArgumentLacing = LacingStrategy.Disabled;
        }
```

This code would only create the in ports. Un-commenting the deprecated method would bring them back. Ideas? 

![image](https://cloud.githubusercontent.com/assets/529781/18883863/011efbc4-84b3-11e6-8eb4-5be725859f7a.png)

**Comment by ke-yu** [comment]
i'm sorry @ksobon , they are not deprecated :-(, I'll remove Depracated attribute

**Comment by ksobon** [comment]
no need to apologize. Thanks!

**Comment by ramramps** [comment]
@ksobon Let us know if this is fixed.

**Comment by johnpierson** [comment]
> @ksobon Let us know if this is fixed.

How did  this work out @ksobon ?

**Comment by ksobon** [comment]
@johnpierson this was an issue to be resolved on your side. @ke-yu did you guys fix this?

**Comment by johnpierson** [comment]
Let me do some checking with the team @ksobon
