### ISSUE TITLE
Improper rounding

### ISSUE THREAD

**Issue by mccrone** [DynamoDS/Dynamo#7212]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.0.2514 (1.2.0 RC)

## Operating system

Windows 7

## What did you do? 

Simple Math with 4 sig figs

## What did you expect to see?

An accurate answer

## What did you see instead?

Evidence of an internal rounding error

![rounding](https://cloud.githubusercontent.com/assets/6430819/18932777/efaf37c6-859f-11e6-8a54-2c8f770455bc.PNG)

attn: @jnealb @kronz

**Comment by jnealb** [comment]
Thanks @mccrone, we will investigate.

**Comment by tatlin** [comment]
Is this not just single prediction floating point behavior?

-matt

**Comment by gregmarr** [comment]
10.1 as double precision is   `10.0999999999999996447286321199`
10.05 as double precision is `10.0500000000000007105427357601`
10.1 - 10.05 is thus `0.0499999999999989341858963598`
Assuming that this number was displayed with 15 digits of precision, which is the number needed to uniquely identify every double precision floating point number when converted to a string, it would be `0.0499999999999989`, which is what is displayed in the graph.

**Comment by jnealb** [comment]
This is tracked with MAGN-10772.
