### ISSUE TITLE
Slow Performance for Nodes with Many Inputs

### ISSUE THREAD

**Issue by pflaumingo** [DynamoDS/Dynamo#7213]
Hi,

I've created a Domain Model for eQUEST, a building energy simulation tool, and I've wrapped this in a C# library to expose in Dynamo. Attached is an image of the graph I'm running that is taking about 5 minutes to resolve. I know from the image the nodes can't be read, but ultimately each of the sections results in a list of objects that gets passed into the very large node to the right. This large node is the main domain model and all the inputs take a list of objects and where no input is supplied the default value is null. When I simulate without this large nodes and connections the runtime drops down to 1-2 seconds. When I create a unit test in Visual Studio and increase the number of objects being passed in to 100 times what is being simulated in the graph shown, the runtime is also just a couple of seconds.

Is there something related to Dynamo where runtime increases significantly with the number of inputs to a node? 

![image](https://cloud.githubusercontent.com/assets/15233892/18933643/9b9fce6c-858a-11e6-9ebd-ab60a30b23d4.png)

Sorry for posting here, but I typically find the forum somewhat unresponsive to programming questions.

**Comment by pflaumingo** [comment]
An additional observation is that as I increase the number of inputs (connections) to the large node to the right, the time it takes to resolve the graph seems to grow somewhat exponentially:
- 16 inputs = 2 seconds
- 18 inputs = 22 seconds
- 20 inputs = 2 minutes 1 second
- 22 inputs = 2 minutes 5 seconds
- 23 inputs = 4 minutes 2 seconds

Any advice as to why this may be?

**Comment by mjkkirschner** [comment]
what do you mean by resolve the graph? Open the file?

**Comment by pflaumingo** [comment]
Sorry, I just mean for it to run to completion.

**Comment by mjkkirschner** [comment]
hmm, have you enabled lacing on this node or list at level on this node? I'm guessing some kind of replication is occurring.... with some many inputs lists the total number of iterations if replication over some of them occur will be a lot of executions - maybe try adding a static counter to your class and see how many times the function is actually invoked.

**Comment by pflaumingo** [comment]
Is lacing controlled via an attribute? What do you mean list at level? All Dynamo behaviors are default at the moment so lacing is possible, but at the moment only one object is being produced.

As for the static counter, which function are you referring to? The node is a static constructor. Are you talking about a counter to count how many times the constructor is called?

**Comment by ke-yu** [comment]
@pflaumingo I don't think many inputs will slow down the execution. I created a simple custom node with 20 inputs, and the execution is done within one second.

Like @mjkkirschner said, I suspect it is because of replication -- the custom node is called multiple times. Could you send me the file if possible?

**Comment by pflaumingo** [comment]
Sent to @ke-yu's email account.

**Comment by pflaumingo** [comment]
@mjkkirschner I put a static counter on the class and incremented it on the static constructor and it's increasing by 1 each time the constructor is called, but I'm guessing the constructor isn't actually getting called multiple times due to replication?

**Comment by pflaumingo** [comment]
Talking with @ke-yu further, it seems that this is a performance issue for nodes with many inputs due to replication. The suggestion for the moment is to reduce the number of inputs into a single node by splitting it into multiple nodes.
