### ISSUE TITLE
Room.Name also reporting number

### ISSUE THREAD

**Issue by JohanCantryn** [DynamoDS/Dynamo#7219]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2

## Operating system

Win 10

## What did you do? 

Get info out of a room object by using Room.Name node

## What did you expect to see?

Only the name of the room

## What did you see instead?

I get a string with the name and the number

**Comment by ksobon** [comment]
@ikeough @kronz its easy to fix just use the Built In Parameter for this rather than Element.Name property since it was overwritten for Room objects. 

```
var name = rm.get_Parameter(Autodesk.Revit.DB.BuiltInParameter.ROOM_NAME).AsString();
```

**Comment by ksobon** [comment]
Ps. Not doing this and keeping the implementation as is, pretty much duplicates the `Element.Name` node functionality.

**Comment by aparajit-pratap** [comment]
@ksobon https://github.com/DynamoDS/DynamoRevit/pull/1353

**Comment by ParametricMonkey** [comment]
@aparajit-pratap @ksobon @kronz 
![2017-09-26 14_07_58-dynamo](https://user-images.githubusercontent.com/10913639/30842282-9c0105a8-a2c4-11e7-990a-2bd05b58c969.png)
This is still an issue in 1.3
