### ISSUE TITLE
Python Script - Node will not re-evaluate

### ISSUE THREAD

**Issue by rhamati** [DynamoDS/Dynamo#7232]
## Dynamo version

1.2.0.2621
## Operating system

Windows 7
## What did you do?

I have a python script stored on the computer and in dynamo I am providing the path and running the function from the script.

The path (for the script) is provided in a node entry (IN[1]). When removing this entry an re-hiting run, the output is unchanged. This is unfortunate since i want to write the script using an editor, and from time to time to reevaluate in dynamo.
![image](https://cloud.githubusercontent.com/assets/11173543/19019489/ae1c6716-8892-11e6-9fef-31007e079600.png)
## What did you expect to see?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/11173543/19019493/bd24692a-8892-11e6-9f7f-052589d3ea00.png)
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/11173543/19019489/ae1c6716-8892-11e6-9fef-31007e079600.png)

**Comment by ThomasMahon** [comment]
If you add a boolean input to 'run' your code and encapsulate your code in an if statement, you can force the node to update. You'll need to set the bool to false, click run, then switch it back to true so it changes states.

**Comment by rhamati** [comment]
Hi,

Thanks for your feedback. I've been trying this until dynamo 1.2, where it seems it doesn't work anymore. The work around it is to actually change something inside the python script node. I tried passing a number from outside, and always change the number, this didn't affect, the python node wouldn't re-evaluate the script loaded via "sys.path.append."

**Comment by dimven** [comment]
Not sure why it's not updating, however the python script from string node might be a better option for your workflow. Check out the below example:

![2016-10-02_21-23-14](https://cloud.githubusercontent.com/assets/7148394/19020856/b32b5c54-88e6-11e6-8eef-cdafa6e2a120.gif)

**Comment by rhamati** [comment]
Thanks! That will do the trick

**Comment by rhamati** [comment]
I am not sure now how to mark this issue as solved

**Comment by mostaphaRoudsari** [comment]
@rhamati you can just close the issue.

**Comment by Aeiddius** [comment]
Still had this same issue at 2023 version of revit and its just so frustrating
