### ISSUE TITLE
Using ! (not) in imperative CodeBlock fails

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7237]
## Dynamo version

1.2.0
## Operating system

Win 10
## What did you do?

Wrote simple imperative function which inverts a true/false input within an if statement
## What did you expect to see?

The return statements of the if function to respond to the true/false input
## What did you see instead?

Fails to respond:

![not in imperative fails to respond](https://cloud.githubusercontent.com/assets/18601851/19043650/f53fc902-8988-11e6-8db9-a43b9ec1a16d.gif)

**Comment by ke-yu** [comment]
It is not ! doesn't work in imperative language block. It is because associate update breaks in imperative language block, that is, it doesn't re-execute the language block once x is updated.

**Comment by ramramps** [comment]
Closing this, as this is fixed in the referenced PR.
