### ISSUE TITLE
IndexGroup.ByIndices with three indexes has wrong description

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7238]
## Dynamo version

1.2.0

## Operating system

Win 10

## What did you do? 

IndexGroup.ByIndices with three indexes

## What did you expect to see?

Description stating three indices

## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/18601851/19043729/4e6bee98-8989-11e6-9c5e-e8aa6391cfd7.png)

**Comment by vykrum** [comment]
Had reported this earlier here...
https://github.com/DynamoDS/Dynamo/issues/7075

**Comment by ThomasMahon** [comment]
@vykrum thanks I'll close this one and ref from yours

**Comment by Alashhar** [comment]
The issue still exist... it generates four points.... :(
