### ISSUE TITLE
dynamo 1.2 daily crashes opening old definition 

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#7242]
latest daily built
crashes on opening
message:
![image](https://cloud.githubusercontent.com/assets/6928491/19081115/755ca3aa-8a59-11e6-9649-1338cbc89e72.png)
(eternal loop)
message: something like outdated definition.
looping
is a definition from 1.0 with a custom node that is older

**Comment by andydandy74** [comment]
Try to upgrade that package from the package manager.
If the latest version is below. 0.8 open the file manually in dynamo 0.9 and save it.

**Comment by albertotono** [comment]
![problem 1](https://cloud.githubusercontent.com/assets/11828200/19116842/2b583c1a-8b17-11e6-9b45-2c0d43759c18.png)
And for Turn Into List?

**Comment by andydandy74** [comment]
@albertotono - Uninstall the package and install package Clockwork instead.

**Comment by albertotono** [comment]
thanks a lot. it works well

**Comment by alfarok** [comment]
this appears to have been solved, closing
