### ISSUE TITLE
Custom node library categorisation using Actions prefix is limited

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7244]
## Dynamo version

1.2.0

## Operating system

Win 10

## What did you do? 

Created a custom node and added it to a custom library category. I assigned an `Actions` suffix

## What did you expect to see?
For it to appear next to an `Action ` icon with the red lightning symbol in the library

## What did you see instead?

It defaults to a `Create` categorisation. I presume the `Create `> `Action `> `Query `library structure is set up as a dependency meaning at least one `Create `node is needed before any `Action `nodes can be added. 

![image](https://cloud.githubusercontent.com/assets/18601851/19095198/6cbee5ea-8a8c-11e6-94fc-d1d472979923.png)
![image](https://cloud.githubusercontent.com/assets/18601851/19095309/eefdcf12-8a8c-11e6-9c32-5cf571b8c31d.png)

For example, if a `Create `node is added, then the `Action `categorisation works as expected:
![image](https://cloud.githubusercontent.com/assets/18601851/19095338/13d48cd6-8a8d-11e6-87b8-7c89d88f7823.png)

I find this slightly limiting.

**Comment by andydandy74** [comment]
Limited is a nice way of putting it. It's a one year old bug. There, I said it.
Seems related to #5613

**Comment by ThomasMahon** [comment]
@andydandy74 as always, thanks for the insight. No lightning bolts for me. I'll close this and ref from yours.

**Comment by ThomasMahon** [comment]
Closed as documented in #5613
