### ISSUE TITLE
Python Script not loading

### ISSUE THREAD

**Issue by bendoty** [DynamoDS/Dynamo#7261]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.2.0.2690
## Operating system

Windows 10
## What did you do?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/22302066/19279842/e87a7720-8f97-11e6-84e5-d9fe482e7193.png)
## What did you expect to see?

(Fill in here)
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/22302066/19279877/11cb1a30-8f98-11e6-99cb-6d45ea1f072f.png)

**Comment by alfarok** [comment]
Closing, no steps provided to reproduce.  If you are still experiencing similar behavior please feel free to reopen.
