### ISSUE TITLE
DynamoPrimer example (pg2.4) causes Revit to freeze

### ISSUE THREAD

**Issue by justinpelliott** [DynamoDS/Dynamo#7268]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.2.0.2690
## Operating system

W10
## What did you do?

I built the sample script from the Dynamo Primer pg 2.4
Adjust a Number Slider
## What did you expect to see?

The Circle radius to change, based on the Geometry.DistanceTo node
## What did you see instead?

It worked, then it froze.

[Circle Attractor.zip](https://github.com/DynamoDS/Dynamo/files/527373/Circle.Attractor.zip)

**Comment by johnpierson** [comment]
Closing this as the provided file is working as expected in 2.0.1. If this is still an issue for you, feel free to reopen or create an update issue.
