### ISSUE TITLE
Problem with graphic visualization

### ISSUE THREAD

**Issue by andrews1981** [DynamoDS/Dynamo#7285]
The my problem is visualization graphic in dymo, I have create point but I don't visualize the point.
I believe to have problem with graphic card or other problem.
Can someone help me? not even visualize the grid in dymo.

**Comment by jnealb** [comment]
@andrews1981 Can you please run the DxDiag utility (click on the Windows button and type it in+enter key) and save its output to a file and send that to us? Thanks.

**Comment by riteshchandawar** [comment]
@andrews1981 You can also refer to this document as well.  https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ
