### ISSUE TITLE
[UI] Wish: Drag and re-connect multiple wires.

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#7288]
It's quite common that I end up with a node that sprouts a whole branch of wires, connecting it to three or more other nodes. Occasionally I want to change the node or the list structure and I end up having to re-connect those three or more wires manually. In the below example I decided I want to flatten the list first and ended up having to re-connect 5 nodes spread all over the graph.

![revit_2016-10-21_14-07-03](https://cloud.githubusercontent.com/assets/7148394/19589199/75f008e2-979d-11e6-9553-7c48578ed4db.png)

It would be great if instead of doing that, I could have right-clicked (or CTRL-clicked) on the "in" output, select all five of those wires and re-connected them to the Flatten node's output in one fluid action. That would save me a whole lot of clicks, pans, zooms, etc and be a boon for overall productivity.

**Comment by ThomasMahon** [comment]
Agree - has parallels with my improvement request in #6510 - basically enabling find/replace functionality or search functions that can manage this exact workflow problem.

**Comment by Curty102** [comment]
Agree with all above.  Additional functionality:  
1. Control+click can equally be used to DISconnect all wires at once in addition to relocating all wires at once.
2. To SELECTIVELY remove or reconnect only select wires in a group to another node in one motion, right click be used to call a checkbox menu.  This would be awesome!

**Comment by riteshchandawar** [comment]
@dimven @ThomasMahon, take a look at this PR.https://github.com/DynamoDS/Dynamo/pull/7534

**Comment by ThomasMahon** [comment]
@riteshchandawar nice! What about the reverse, say I want to connect one node to multiple other inputs (either of the same node or numerous) further down stream? Essentially what I am asking for is the ability to plug one wire multiple times.

**Comment by ksobon** [comment]
@kronz this looks like it was addressed and merged already. Can we close?
