### ISSUE TITLE
Crash after re-opening a saved file

### ISSUE THREAD

**Issue by fukanfengjing** [DynamoDS/Dynamo#7295]
## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

Version 1.2
## Operating system

win10
## What did you do?

open a saved file
## What did you expect to see?

the programming diagram (in manual model). I am editing the relay model for a railway project that is comparatively complex.

is my model too complex to handled? Now I only want to open the diagram and then I can delete some part of the model. But I cannot do anything. Every time  I tried to open the save file, a crash window show the following information.
## What did you see instead?

将对象引用设置到对象的实例。

   在 Dynamo.Controls.Watch3DView.CompositionTargetRenderingHandler(Object sender, EventArgs e) 位置 E:\Dynamo-master\src\DynamoCoreWpf\Views\Preview\Watch3DView.xaml.cs:行号 233
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 DynamoSandbox.DynamoCoreSetup.RunApplication(Application app) 位置 E:\Dynamo-master\src\DynamoSandbox\DynamoCoreSetup.cs:行号 54

**Comment by riteshchandawar** [comment]
@frankfralick Will it be possible for you to send the file for further investigation at our end, as this is a file specific issue so we really can't debug to the problem unless we have the file.

- Ritesh

**Comment by QilongTang** [comment]
This will be fixed in Dynamo 2.0. Closing
