### ISSUE TITLE
Revit.Elements.Coordinates nodes not updating when moved in Revit project

### ISSUE THREAD

**Issue by JohanCantryn** [DynamoDS/Dynamo#7297]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.2
## Operating system

Win 10
## What did you do?

Added Coordinates.Basepoint, Coordinates.Surveypoint, Coordinates.ProjectRotation nodes.
They report the actual situation.
Then I move survey point and/or project base point in my Revit project.
## What did you expect to see?

Node output ports updating and reporting the new values
## What did you see instead?

Nodes are still reporting the old values

**Comment by mjkkirschner** [comment]
are you running in Automatic mode?

**Comment by JohanCantryn** [comment]
@mjkkirschner

Yes I do.

**Comment by ksobon** [comment]
All of these nodes are built as ZT nodes, so none of them will update itself without you forcing the update somehow. I know you think that moving a project base point in Revit is enough to update the node, but unfortunately it's not. If that was the case your Dynamo graph would be running constant updates on most of the nodes, and eventually just die a death by lack of memory. In this particular case you might have to just delete that node and place it again. That will force it to recalculate. 

@mjkkirschner do we want to consider building these as `NodeModel` nodes? How would we handle migration? This could also be handled with periodic updates.

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2151).
