### ISSUE TITLE
DesignScript shorthand range with string yields strange results when mixing case

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7298]
## Dynamo version

1.2
## Operating system

Win 10

## What did you do? 

Created a range using DesignScript with strings and mixed case `"a".."H";`

## What did you expect to see?

a, b, c etc to h (or H?)

## What did you see instead?

Inverted sequence from Z with a at the start:

![image](https://cloud.githubusercontent.com/assets/18601851/19702472/c17c9228-9af7-11e6-857b-71068dd8beb8.png)

**Comment by gregmarr** [comment]
Looks like ASCII order.  The upper case letters are before the lower case letters.
