### ISSUE TITLE
Dynamo not rendering grid or visual objects

### ISSUE THREAD

**Issue by lukeroot** [DynamoDS/Dynamo#7304]
## Dynamo version

Core and Revit 1.2.0.2690
## Operating system

Windows 7. (because 10 sucks)
## What did you do?

So I opened Dynamo and erm... No grid like normal and no ability to draw to the screen. Not a clue why? 
I updated my graphics cards drivers and nothing. Reinstalled Dynamo still nothing. Not sure why I wouldn't be getting a display I've literally just opened it up from a fresh install and same old, no display. Help pleasee.

Okay so I did do some work before noticing this but [here](http://imgur.com/a/PHh4u) is what my screen looks like ? No grid and nothing drawn

Highly appreciate any ideas, throw them my way.

Cheers guys keep up the good work
Luke

**Comment by alex1173** [comment]
The same happened to me just a minute ago. I was working in dynamo 1.2.0.2690  and suddenly the geometry stopped being displayed. Everthing in dynamo is set to null. There is no connetion between revit en dynamo anymore.

**Comment by mjkkirschner** [comment]
these don't exactly sound like the same issue, @lukeroot has proper graph execution but the background preview is not displayed.

Can both of you try setting version 1.2 of Dynamo to high performance mode in your graphics control panel, nvida or amd.  Are either of you on laptops with integrated and discreet gfx cards?

The other time I have seen this happen is when the background preview crashes when displaying very large meshes and after that Dynamo usually crashes as well.

**Comment by mukhesh-studio4** [comment]
I am facing the same issue with a new Dell laptop which has switchable AMD graphics.

There is no background preview and I have tried re-installing drivers, installing directx runtime libraries but in vain. 

I get the following message in the console for dynamo.
##START###
Dynamo log started 2016-11-19 14:27:00Z
Requesting version update info...
Dynamo -- Build 1.2.0.2690
Duplicate migration type registered for SunPathDirection
Dynamo will use the package manager server at : https://www.dynamopackages.com
DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
Backup files timer is started with an interval of 60000 milliseconds
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384,16384
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384,16384
SYSTEM:Environment Path:C:\Program Files\Autodesk\Revit 2016\en-US;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Common Files\Autodesk Shared\;C:\Program Files\Autodesk\Revit 2016;C:\Program Files\Dynamo\Dynamo Core\1.2\
DynamoManipulationExtension (id: 58B0496A-E3F8-43D9-86D2-94823D1D0F98) view extension is added
NotificationsExtension (id: ef6cd025-514f-44cd-b6b1-69d9f5cce004) view extension is added
Welcome to Dynamo!
00:00:00.5128772 elapsed for loading Dynamo main window.
Dynamo is up to date.
###END###


Does anyone have a solution for this ?

**Comment by jnealb** [comment]
Solution for @mukhesh-studio4 can be found at https://github.com/DynamoDS/Dynamo/issues/5818.
