### ISSUE TITLE
ImportFromCSV nodes don't work

### ISSUE THREAD

**Issue by mccrone** [DynamoDS/Dynamo#7306]
## Dynamo version

1.2.0
## Operating system

Windows 7
## What did you do?

Read a CSV File
## What did you expect to see?

Data form the CSV file
## What did you see instead?

null items in the expected structure.   Note that the CSV.ReadFromFile node works correctly.  the two flavors of ImportFromCSV seem to be both redundant and not working.

![csvexample](https://cloud.githubusercontent.com/assets/6430819/19782166/a6a00e44-9c5a-11e6-93a5-28a1a3c83756.png)

**Comment by ThomasMahon** [comment]
@mccrone Its working onWin 10 Dynamo v1.2

![image](https://cloud.githubusercontent.com/assets/18601851/19786750/71991a64-9c97-11e6-9018-ce2bb72f00cc.png)

**Comment by ke-yu** [comment]
@mccrone needs `File.FromPath` to convert to a file.

**Comment by mccrone** [comment]
@ke-yu I don't think that's the problem:

- The inputs for the two nodes that don't work call for a **file path** not a **file**.
- The example from @ThomasMahon does not use a **File.FromPath** node.

**Comment by gregmarr** [comment]
@mccrone Is it because the output of ImportFromCSV is a 2D array of doubles, and you're trying to read a CSV containing strings, which can't be converted to doubles?

**Comment by mjkkirschner** [comment]
@mccrone @ke-yu those nodes have double arrays as their outputs... your excel file is full of strings... I think the error is clear right?

**Comment by mjkkirschner** [comment]
damn @gregmarr beat me!

**Comment by mccrone** [comment]
Wow.  Nice Job.  The error isn't as clear as you'd think though.  Given that these nodes are less functional than **CSV.ReadFromFile**, the larger question remains: why are they even there?

**Comment by ke-yu** [comment]
@mccrone these are legacy builtin functions from DesignScript. We'll remove them soon.  FYI @kronz @Racel
