### ISSUE TITLE
Sheet.View node does not populate when Legend is pressent on sheet 

### ISSUE THREAD

**Issue by snilling** [DynamoDS/Dynamo#7307]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.2.0.2831
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Operating system

Windows 10
(e.g. Windows 7, Windows 8.1, etc)
## What did you do?

use the Sheet.Views node. 
The sheets in question have Legend view on them.
(Fill in here)
## What did you expect to see?

list of views on each sheet
(Fill in here)
## What did you see instead?

the list is populating with Null vallues for the sheets with legend on them
and I get the error Message: 
_"Warning: Sheet.get_Views operation failed. 
Unable to cast Object of type 
'Revit.Elements.UnknownElement' to type
'Revit.Elements.Views.View'."_

**Comment by dimven** [comment]
1) Please re-post this issue in the [Dynamo4Revit repository](https://github.com/DynamoDS/DynamoRevit/issues)

2) You could try using the "Springs.Sheet.Views+" node from spring nodes in the mean time

![revit_2016-10-31_15-08-22](https://cloud.githubusercontent.com/assets/7148394/19846640/0ca1d05a-9f7c-11e6-844e-8ffb2f5a0ceb.png)

**Comment by ksobon** [comment]
This will be fixed in the next release if/when this PR gets merged: 

https://github.com/DynamoDS/DynamoRevit/pull/1711

**Comment by ksobon** [comment]
@kronz can we close this? looks like it was fixed, merged
