### ISSUE TITLE
Dynamo Crashes when trying to copy paste groups

### ISSUE THREAD

**Issue by BrettCTaylor** [DynamoDS/Dynamo#7314]
## Dynamo version

Core:1.2.0.2931
Revit: 1.2.0.2690

## Operating system

Windows 10

## What did you do? 

selected a group within one dynamo script, copied the group. Created a new dynamo script, select paste. Dynamo crashed.

When I select the individual nodes within the group, select copy, create a new dynamo script and then select paste, the nodes copied over as expected

## What did you expect to see?

The group would copy over to a new file like copying over the nodes

## What did you see instead?

dynamo crashed

**Comment by jnealb** [comment]
@BrettCTaylor Does this reproduce for you? Thanks for letting us know.

**Comment by BrettCTaylor** [comment]
Hi @jnealb I'm not sure exactly what you mean by "reproduce" but it happens in different dynamo scripts, with different Revit models and after rebooting my computer. Below is the error message that comes up with the crash


> Sequence contains no elements
> 
>    at System.Linq.Enumerable.Min(IEnumerable`1 source)
>    at Dynamo.Models.DynamoModel.Paste(Point2D targetPoint, Boolean useOffset)
>    at Dynamo.ViewModels.WorkspaceViewModel.Paste(Object param)
>    at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
>    at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@BrettCTaylor I mean steps that you reproduce each time to get the crash

**Comment by BrettCTaylor** [comment]
Easy.

1) within opened dynamo script, select a group
![image](https://cloud.githubusercontent.com/assets/18408513/19949154/dd697884-a19b-11e6-9dec-b868f786a242.png)

2) click on the Edit menu and then select copy (or just use the keyboard shortcut CTRL C

3) Click on the new file icon on the toolbar, or keyboard shortcut CTRL N

4) Within new file, click on the menu Edit\Paste or just use keyboard shortcut CTRL V

But now when I refollow my above steps it is now not crashing. (even though it crashed everytime I did it yesterday on different files). So apologies it looks as though it has fixed itself. I will reply back if I can reproduce it again.

**Comment by ramramps** [comment]
@BrettCTaylor Please re-open if you see this error .
