### ISSUE TITLE
Excel node cannot function

### ISSUE THREAD

**Issue by anniec15** [DynamoDS/Dynamo#7316]
## Dynamo version
Dynamo 1.2
## Operating system
Window 10

## What did you do? 
I cannot run the excel node in dynamo after updated the Skype.

## What did you see instead?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/21327666/19924856/b0c41e9c-a128-11e6-81de-9630034f62d6.png)

## What I have tried?
I have followed the instruction in below link:
https://github.com/DynamoDS/Dynamo/wiki/Known-Issues

There was only the content in blue box. So I duplicated one for 1.8 (red box) and then delete it afterwards. But the bugs cannot be fixed.
![image](https://cloud.githubusercontent.com/assets/21327666/19924925/eebf00cc-a128-11e6-94d6-3f11c372e81b.png)

**Comment by dago2015** [comment]
Is there a solution for this? I'm running into the same problem.

**Comment by jnealb** [comment]
@dago2015 What version of MS Office are you using? Can you open Excel (eg is Office activated?)?

**Comment by dago2015** [comment]
Hi,

I am using Excel 2007. I was able to get the node to work for Dynamo 1.0
but it stopped working with 1.2.1.

I found that the Bumblebee package node does work but I get the following
message when using the OOTB node.

[image: Inline image 1]

**Comment by anniec15** [comment]
My excel is version 2016. But the dynamo still fails by using bumblebee package node.

**Comment by riteshchandawar** [comment]
@anniec15 

Have you tried the OOTB nodes of Excel? Is that working for you?

Thanks,
Ritesh

**Comment by anniec15** [comment]
Both cannot function

![image](https://cloud.githubusercontent.com/assets/21327666/20821373/f1200ca6-b87c-11e6-8ab7-1726a153c416.png)

**Comment by kronz** [comment]
@dago2015 We recommend using Excel 2013 or higher. Excel 2010 works in most cases, but 2007 does not.

**Comment by dago2015** [comment]
Sadly, my office does not plan update our Excel licenses. Would it be
possible for a future build to add this functionality back? @Kron

**Comment by kronz** [comment]
@dago2015 I'm afraid we can't support so many versions . . . going back 6 years in support is stretching us already, 10+ years of version support is out of range.

@anniec15 can you try uninstalling Bumblebee and see if the out of the box nodes work after a restart?  Trying to see if there is a conflict with Bumblebee
fyi @ksobon

**Comment by ksobon** [comment]
Well version 2016.12.1 had a small bug. Please update to 2016.12.2 and report back.

**Comment by ksobon** [comment]
And yes, you cannot wire all of the nodes together like that. The best you can do is probably have one read and one write node at the same time but that still requires that the FileStream is set up in a specific way which i dont think either ootb not bumblebee supports.

**Comment by anniec15** [comment]
Thanks @ksobon and @dago2015 , I have tried the updated version, the Read and Write Excel node are successful. However, the original WriteToFile and ReadFromFile from Office package still not function. But it's ok, just leave the question here as I can access the Excel now.
