### ISSUE TITLE
Rotate to Normal - List 0:0 and List 0:1 has similar angles, but does not respond properly

### ISSUE THREAD

**Issue by IDStudios** [DynamoDS/Dynamo#7320]
## Dynamo version

1.2.0

## Operating system

Windows 10

## What did you do? 

I am trying to rotate satellite geometries around their axis, so their edges are normal to the grid point (central geometry). The list numbers and sequences checked and correct.

I placed a vector on Z-axis on the center of each satellite and a vector to the normal (that is going from the center of grid point (central geometry) to center of satellite point. 

## What did you expect to see?

This would allow me to find the angle between the vector on Z-axis and the vector to the Normal. I could use the list of angle's for rotation of the geometry. So, all the geometries on the same row, should have similar rotation.

NOTE: This was working on the previous version of Dynamo (0.9.2 or 2016), however when I updated to newer version it does not respond.  

## What did you see instead?

The list 0:0 is not the same as the List 0:1 - which I could not find any reason why it would be. Since the List 0:0 respond properly rotation to the normal, rest of the lists do not... (as shown in the List 0:1

I believe this is a bug, since it was responding before but not anymore..

I look forward to our comments. Please check the images below.

![dynamo1](https://cloud.githubusercontent.com/assets/23246676/19984449/ac6ad868-a20e-11e6-9f98-3a4eac9c232a.JPG)
![dyanmo2](https://cloud.githubusercontent.com/assets/23246676/19984448/ac6ad2c8-a20e-11e6-832f-ab414fb7ea9d.JPG)

**Comment by dimven** [comment]
Hi,

Try using the new "Vector.AngleAboutAxis", using the Zaxis as a rotation axis.

**Comment by IDStudios** [comment]
Thank you Dimitar.

It seems to be working with the new node, although the numbers are still different, visually it is working.

All the best

Hasan Yumer
BIM Manager & Designer

www.IDStudios.Co
+356 9994 6267
