### ISSUE TITLE
Grid visible in screenshots

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#733]
In recent builds the grid is visible in screenshots. It would be nice if this could either be disabled again completely or if we at least could toggle it on and off for the screenshots.
Build 0.6.2.10960
![bildschirmfoto 2013-11-12 um 23 02 41](https://f.cloud.github.com/assets/3014437/1526572/3e28a730-4be6-11e3-9f28-92ff9d55edc4.png)

**Comment by Benglin** [comment]
Finally, finally, finally fixed with #6786
