### ISSUE TITLE
DateTime Now() fails to update

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7350]
## Dynamo version

1.2

## Operating system

Win 10

## What did you do? 

Use the `DateTime.Now()` node

## What did you expect to see?

The current date/time to update in sync with the computer clock - no different to how C# and even Excel implement  `Now()`

## What did you see instead?

It fails to update whether on automatic or manual mode. It is effectively a snapshot in time which seems to be unusual behaviour for a `Now()` function:

![recording 7](https://cloud.githubusercontent.com/assets/18601851/20276892/3f35143a-aa96-11e6-9748-96ff0e3b9b43.gif)

**Comment by mjkkirschner** [comment]
I'm not sure this is a bug. This node is marked periodic and and if the run mode is changed to periodic will re-execute the graph.

What happens if you hit the run button *after* you change the input to the new Date.Now() node?

**Comment by ThomasMahon** [comment]
@mjkkirschner the problem with Periodic execution though is that it executes indefinitely. I need it to refresh every second to change the state of a bool, but I am only interested in the state once I decide and the only way to do this is on Manual execution. Needless to say on large, complex graphs, Period execution with such a short refresh cycle simply isn't viable.

**Comment by riteshchandawar** [comment]
I am closing this issue because the original intent of this node to work with Periodic Update and it is updating correctly. 

@ThomasMahon you can log a Wish request with more details.

Thanks,
Ritesh

**Comment by catdotgif** [comment]
In my testing, it's not updating on a manual run either-- I have to close Dynamo and open it again to get a new timestamp.   Which is fine if that's the intent, but I need a way to timestamp the run.
