### ISSUE TITLE
Custom Node input type breaking output

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#7368]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.0.2690

## Operating system

Windows 10

## What did you do? 

Creating a simple custom node as depicted below:

![image](https://cloud.githubusercontent.com/assets/12857357/20482592/4f4ae1f2-afe5-11e6-93c1-b8ec3c605bf1.png)

This correctly functions how I believe it should: Simply putting a point onto surfaces, querying their z-values and filtering based off that (Top planar surfaces matching a List.MaximumItem variable from Point.Z).

The canvas output is correct as shown below:

![image](https://cloud.githubusercontent.com/assets/12857357/20482500/e2cc38d2-afe4-11e6-9f96-925e7386c423.png)

However, as soon as I try to define the 'type' in the input the graph behaves weirdly. No longer does the filter work correctly. 

![image](https://cloud.githubusercontent.com/assets/12857357/20482535/0710471a-afe5-11e6-8fbc-dfe278ce7e4f.png)

It suddenly pulls through every single surface, chops the list up into sub-lists of one each and filters nothing.

![image](https://cloud.githubusercontent.com/assets/12857357/20482552/25a23634-afe5-11e6-8999-62d4fd44115c.png)

## What did you expect to see?

As above. 

## What did you see instead?

As above.

**Comment by mjkkirschner** [comment]
I think this is as designed, an input of surface can't take s list of surfaces - make the input type like this surf : surface []
