### ISSUE TITLE
Package Dependecies not loaded

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/Dynamo#7369]
## Dynamo version

1.2.0

## Operating system

Windows 7

## What did you do? 

I wrote a custom package that depends MeshToolkit and added `  "dependencies": [{"name":"MeshToolkit","version":"1.2.0"}]` to the pkg.json file.
My package never showed into Dynamo, this because the MeshToolkit dlls were loaded **after** my package dll.

As a workaround I renamed my package folder to start with a name alphabetically after the MeshToolkit folder, so that it would be loaded after it, my package finally showed into Dynamo.

**Comment by mjkkirschner** [comment]
@teocomi thanks for reporting this - it's a known issue of the package manager / library importer - I'll try to find the tracking number.

**Comment by teocomi** [comment]
Thanks, sorry for duplicating the issue, I didn't see it.

**Comment by mjkkirschner** [comment]
@teocomi no worries, it's tracked internally, so you wouldn't have seen it. - lets keep this open.

**Comment by mjkkirschner** [comment]
@kronz this is a super annoying issue, I filed it a long time ago and we never picked it up.
https://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9677  (not sure if this moved over yet)

I think we should fix it, though it may not be super straight forward.

**Comment by kronz** [comment]
@mjkkirschner who's appropriate to take a look at this?

**Comment by mjkkirschner** [comment]
@kronz  Anyone on the team can look at this, familiarity with package manager or VM will be good.

**Comment by mjkkirschner** [comment]
this should be fixed in 2.3 and >
