### ISSUE TITLE
No File Save prompt triggers on new files when opening another file from File > Open Recent Files resulting in loss of data

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7380]
## Dynamo version

1.2.1

## Operating system

Win 10

## What did you do? 

Created a new home workspace. After developing a new script, clicked on File > Open Recent Files and opened a recent file without saving the new script. 

## What did you expect to see?

For a File Save prompt to trigger

## What did you see instead?

Just opens the recent file selected without giving any prompt resulting in a loss of work

**Comment by mjkkirschner** [comment]
@QilongTang does this ring a bell?

**Comment by jnealb** [comment]
Perhaps related: MAGN-7761?

**Comment by jnealb** [comment]
This is tracked with DYN-236.

**Comment by riteshchandawar** [comment]
@ThomasMahon This one is fixed and will be available in Daily build soon.
