### ISSUE TITLE
Point.ByCoordinates (and other geometry) missing LibG.ProtoInterface.dll

### ISSUE THREAD

**Issue by ThomasGale** [DynamoDS/Dynamo#7408]
## Dynamo version
Building master (Dynamo Core 2.0.0.3427)

## Operating system
Windows 8.1

## What did you do? 
Wanted to build Dynamo from source (to debug my custom node - it had some unmanaged code which was being problematic). That is now appearing to work fine (although weirdly only on master, not RC1.2.1 branch)!

However, in all my versions built from source, I'm struggling some of the core 'geometry' nodes to work such as 'point'. (which I currently require in my user workflow).

## What did you expect to see?
A standard 'Point.ByCoorinates' node construction.

## What did you see instead?
![image](https://cloud.githubusercontent.com/assets/11990706/21030765/210b3a92-bd98-11e6-932b-2792106d6bbf.png)

It appeared to be missing the LibG.ProtoInterface.dll library.

I poked around and discovered that 3 (I assume) versioned folders containing this library were actually in bin!
![image](https://cloud.githubusercontent.com/assets/11990706/21031000/2b116b1e-bd99-11e6-86b9-5068cdcf8ddc.png)

(With the assumption that I needed some post build copy or equivalent) I tried the nieve approach of copying the contents up out of the folder manually (so as to be picked up at runtime)

However, I then got a different error, in the form of an exception
![image](https://cloud.githubusercontent.com/assets/11990706/21031076/92e5710e-bd99-11e6-9812-a06012832bf8.png)

As a side note, I have a huge number of warnings in my Dynamo.All solution.
![image](https://cloud.githubusercontent.com/assets/11990706/21031502/baa9e344-bd9b-11e6-9a39-b5283e144f7b.png)
Is this normal? 

My apologies if this is the wrong place to submit this issue. 
I am a complete beginner to the Dynamo code base, so I also apologise if I've missed something glaringly obvious!

Many thanks in advance for any help :)

**Comment by mjkkirschner** [comment]
hi @ThomasGale cool that you got the repo building. LibG(geometry library) requires ASM to be installed on the machine you are using. So the Pinvoke failure is because the ASM dlls are not present or cannot be found on your machine. Try installing an Autodesk product like Revit or Dynamo Studio, then Dynamo will find the ASM dlls when it starts up.

**Comment by ThomasGale** [comment]
Hi @mjkkirschner, thanks for the pointer. 

This is strange, I have a fair number of Autodesk products installed on my PC, including CR Dynamo Studio 2017 (1.1.0.2093). I don't have the missing libraries when I run it.
![image](https://cloud.githubusercontent.com/assets/11990706/21048357/c782255c-be06-11e6-8108-6a63748132f5.png)

What I don't understand, is that I don't see the same LibG libraries in the install directory for CR Dynamo Studio 2017 (1.1.0.2093)
![image](https://cloud.githubusercontent.com/assets/11990706/21048445/4e795b8e-be07-11e6-9e1e-6217e58bacaa.png)

Is my installed 1.1.0.2093 version looking somewhere else? Using something different?

With regard to my 2.0.0.3434 build, as a further comment, when I run the "SurfaceAnalysisDataBySurfacePointsAndResults_ValidArgs" test, it appears to be looking in a 'libg_0' folder for the libraries, this does not exist (only the libg_220, 221, 222 as mentioned before).
![image](https://cloud.githubusercontent.com/assets/11990706/21048753/ce16379e-be08-11e6-85bc-f23f267d3dc2.png)
Am I missing something in my compilation?

My PC locale is en_GB for reference (if at all relevant)

Thanks.

**Comment by sharadkjaiswal** [comment]
Actually, DynamoSandbox.exe looks only for Revit installation, so you need to have Revit installed on your system. I think we should make it work for Dynamo Studio ASM installation as well.

**Comment by ThomasGale** [comment]
Ah great! 
Yes, after installing Revit, the issue appears to have been resolved in my 2.0.0.3434 build.

Maybe it would be useful to mention the dependency on a Revit installation in the building documentation (unless I managed to miss it!)
Many thanks for the help.

**Comment by vryy** [comment]
@mjkkirschner Sorry to maybe ask a stupid question here. What is full name of ASM package that's required for Pinvoke? Can we install it separately to let DynamoSandbox running? I have the same problem as @ThomasGale , but I do not want to let my users to install full Revit to only get DynamoSandbox running.

**Comment by SahirJ** [comment]
I have revit 17 installed, but still getting libg.protointerface.dll missing.
Please help

**Comment by QilongTang** [comment]
@SahirJ Most likely you can fix it by using the workaround @vnozdrenkova suggested above, I would first check if you have libG_222 in Dynamo folder locally as a starting point.
