### ISSUE TITLE
List.FirstItem behavibng strange in DS

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#7411]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.0

## Operating system

Win 7

## What did you do? 

Wanted a list filter

## What did you expect to see?

The codeblock returning an item not a list

## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/7080648/21045908/7e55e264-be02-11e6-9f2d-e8fdb431efcc.png)

**Comment by andydandy74** [comment]
This is a replication issue in conditional statements. See #6491

**Comment by josols** [comment]
ok, thanks. Then I'm closing this one.
