### ISSUE TITLE
Improvement Request: String.AllIndicesOf

### ISSUE THREAD

**Issue by mccrone** [DynamoDS/Dynamo#7415]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1

## Operating system

Windows 7

## Request

There is currently no out-of-the-box method to find all of the characters of a particular type in a string.  With direct analogy to finding items in a list, there should be a node to find all of the indices of a character.  A related request is to rename the node "String.IndexOf" to "String.FirstIndexOf" for a parallel structure with the Core/List library.

![allindices](https://cloud.githubusercontent.com/assets/6430819/21120370/e8fcdc8c-c094-11e6-9a0e-871153163790.PNG)

**Comment by mccrone** [comment]
cc: @DanielHurtubise

**Comment by jnealb** [comment]
Thanks @mccrone - we will TAL.

**Comment by dimven** [comment]
Is this really something that the team has to allocate resources to? Why not turn the string into a list and then use the existing node?

![revit_2016-12-14_09-22-20](https://cloud.githubusercontent.com/assets/7148394/21166245/2f4d03c4-c1df-11e6-872c-990d61c9640f.png)

**Comment by andydandy74** [comment]
Actually there's a node for that in clockwork. Can't remember the name though.

**Comment by andydandy74** [comment]
Just looked it up. It's called List.FromString...

**Comment by mccrone** [comment]
Thanks @dimven and @andydandy74.  This certainly satisfies my needs for now.

To the point about Dynamo team priorities, I don't presume to make that call.  But I do tend to report obviously missing functionality, for which I believe this is an example.  The name "String.IndexOf" is misleading and "String.AllIndicesOf" should exist if "List.AllIndiciesOf" exists.  It's a great trick to split the string into a list, but that's pretty inefficient for a large number of strings.  It is also a "trick," and the whole point of visual programming is to make things more accessible to more people, so the fewer tricks required the better.

**Comment by gregmarr** [comment]
> The name "String.IndexOf" is misleading

@mccrone FYI, String.IndexOf matches the C# standard library, and is similar to the C standard library (index), and the C++ standard library and MFC (string::find, CString::Find).

I agree that `String.AllIndicesOf` would be helpful.

**Comment by mccrone** [comment]
Yup, I knew that, @gregmarr. But it doesn't mean that MSFT's decision is the best Dynamo can do.  Analogously, the Revit nodes use different terms sometimes than in the Revit API (ex: "familySymbol").

**Comment by gregmarr** [comment]
@mccrone Yeah, it's just a bit of history about where it probably came from.

**Comment by jnealb** [comment]
@kronz @Racel @aparajit-pratap Your thoughts? Mine: vote FOR String.AllIndicesOf, and also FOR math.sin (all math.*) truncated to "sin" etc (will never be a collision) and a review of "&&" and "And" etc. Using the C or J (sourcing from the variants thereof) methods as exact models for a scripting language is not the right design for a scripting language.

**Comment by aparajit-pratap** [comment]
https://github.com/DynamoDS/Dynamo/pull/7432

**Comment by aparajit-pratap** [comment]
`String.AllIndicesOf` is in. Please create new Github issues for any additional requests or improvements for easier tracking. Closing this. @mccrone @jnealb
