### ISSUE TITLE
Node to Code unnecessarily wraps expressions

### ISSUE THREAD

**Issue by lukechurch** [DynamoDS/Dynamo#7423]
# Dynamo version

1.2.1.3083

## What did you do? 

N2C on 
![image](https://cloud.githubusercontent.com/assets/2978182/21188226/8f294ef0-c212-11e6-9566-396a880fbd95.png)

Results in

```
t1 = (0..10);
t2 = 1;
point1 = Point.ByCoordinates(t1, t1, t2);
```

## What did you expect to see?

```
t1 = 0..10;
pt1 = Point.ByCoordinates(t1, t1, 1);
```

There are 2 issues here:

- The 0..10 shouldn't be wrapped in () as it is the only expression in the assignment.
- The constant 1 is very short and is only used in a single location so should be constant propagated

Both of these would improve legibility.

**Comment by jnealb** [comment]
@lukechurch @Racel Please keep 'em coming!

**Comment by Racel** [comment]
@lukechurch - I agree that 0..10 shouldn't be wrapped, but t2 is an input from a number slider. I think it may have been done that way to accomodate for changes in the slider.
