### ISSUE TITLE
Dynamo Crash 

### ISSUE THREAD

**Issue by YSR01** [DynamoDS/Dynamo#7424]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.2.1.3083

## Operating system

Windows 7

## What did you do? 

Combining Lists together 

## What did you expect to see?

Result of 'flatten' node 

## What did you see instead?

![dynamo error1](https://cloud.githubusercontent.com/assets/18330475/21188767/5994524c-c214-11e6-9196-2adddd02519a.PNG)

**Comment by ikeough** [comment]
Can you post the .dyn file that caused this error?

**Comment by mjkkirschner** [comment]
this looks like you need to upgrade your version of the `Turn Into List` package - it's very old.

**Comment by andydandy74** [comment]
Actually, you'll need to uninstall the turn into list package and any clockwork package you may have installed and install a current version of clockwork.

**Comment by YSR01** [comment]
Hi, @andydandy74 thank you. All is working now.

**Comment by mjkkirschner** [comment]
@andydandy74  thanks.
