### ISSUE TITLE
Code Block string issues with "\"

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#7425]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 1.2.1

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(Windows 7 & Windows 10)

## What did you do? 

The Code Block has issues with strings ending in '\\' (and so does GitHub). For example I can create a path string as follows:

`"B:\\Temp\\";`

But if I then try to add another string in the same code block, it throws "Error: ';' is expected". Because of this I'm finding it difficult to house path strings within the same code block and sometimes I have to resort to silly solutions like this (because if I place the text of the second code block in the initial one, it fails. And I'm having to replace "/" in the end to make it work, which seems silly):

![codeblockissues](https://cloud.githubusercontent.com/assets/4656191/21204246/19f48794-c21c-11e6-93be-0b6d5e71d071.png)

This also doesn't seem right, unless I am missing something in terms of expected syntax:

![2016-12-14_16-08-50](https://cloud.githubusercontent.com/assets/4656191/21204086/3c6b039e-c21b-11e6-856b-2cd269455ca7.png)

## What did you expect to see?

I expect concatenation to work regardless of string contents.

## What did you see instead?

See above.

**Comment by dbaldacchino** [comment]
Seems related to #7248 (sorry, just found it). Also for example at times when there are '\\' in the mix, it throws an error when you try concatenating a variable, a typed string in quotes, and another variable.

**Comment by andydandy74** [comment]
May be related to #2396 as well

**Comment by dbaldacchino** [comment]
Thanks @andydandy74 , didn't realize this has been going on for quite a while (tells you I haven't Dynamo'd much lately!).

**Comment by dbaldacchino** [comment]
Here's another example which makes no sense.

![cbnfail](https://cloud.githubusercontent.com/assets/4656191/21231161/de00803a-c2ac-11e6-8128-061beef3184d.png)

**Comment by aparajit-pratap** [comment]
This is fixed. Please reopen if you come across other edge case scenarios.
