### ISSUE TITLE
Plane.Offset strange behavior

### ISSUE THREAD

**Issue by garciadelcastillo** [DynamoDS/Dynamo#7428]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.0

## Operating system

W 8.1

## What did you do? 

Used Plane.Offset to translate a plane along its Normal vector

## What did you expect to see?

The offset plane with the same X and Y vectors

## What did you see instead?

Dynamo had changed the orientation of these vectors. 

DESCRIPTION:

In a Dynamo definition, we have created a Plane from its Origin and a Normal vector. This plane has then been rotated 180 degrees around its normal for better alignment with a robotic arm. But upon using Plane.Offset to create an offset copy of the rotated plane, the component outputs a Plane with the offset Origin, but its orientation is not maintained and it is reset to the axes before rotation. 

FILES:

Two files attached: the one with the problem (red highlights), and another with a workaround to get the desired outcome. 

NOTE: 

This is part of the P+W project at the BUiLD space. 

[PlaneOffset.zip](https://github.com/DynamoDS/Dynamo/files/655058/PlaneOffset.zip)

**Comment by jnealb** [comment]
@aparajit-pratap fyi @garciadelcastillo Is it possible for you to try this with the latest daily build of 2.0?

**Comment by garciadelcastillo** [comment]
How do I get it?

**Comment by jnealb** [comment]
D4R is available at Dynamobim.org

**Comment by garciadelcastillo** [comment]
You mean DynamoInstall1.2.0.20161019T0636.exe, right?

**Comment by jnealb** [comment]
no, sorry goto http://dynamobuilds.com

**Comment by garciadelcastillo** [comment]
Yeah, but which is the build you would like to try with?

**Comment by jnealb** [comment]
Please try DynamoInstall1.2.1.20161123T2054.exe, sorry for the confusion, I did not know that we are not posting 2.0

**Comment by jnealb** [comment]
@garciadelcastillo Do you currently have access to the internal shares?

**Comment by garciadelcastillo** [comment]
Nope... :(

**Comment by mjkkirschner** [comment]
@garciadelcastillo can you get on VPN?

**Comment by aparajit-pratap** [comment]
@jnealb yes, I'm able to reproduce this. Needs to be logged as a bug.

**Comment by aparajit-pratap** [comment]
@jnealb this is fixed. Please test in the next build. Closing
