### ISSUE TITLE
Directory.Contents

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#7457]
## Dynamo version

1.2.1.3083

## Operating system

Windows 7

## What did you do? 

Used Directory.Contents to list files and folders.

## What did you expect to see?

Expected to see both files and subdirectories.

## What did you see instead?

The "directories" output port is empty even when there are subfolders.

**Comment by alfarok** [comment]
This appears to be resolved in the latest builds.  Please feel free to reopen if you are still experiencing similar behavior.

![image](https://user-images.githubusercontent.com/13341935/32508989-1228fab8-c3ba-11e7-8384-5be2d95faa32.png)

Node now returns a list containing
[0] files
[1] directories
