### ISSUE TITLE
ZeroTouch node development: Declare the Node Name using an attribute tag 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7460]
## Dynamo version

1.2.1

## Operating system

Win 10

## What did you do? 

Attempted to create an attribute tag in a ZeroTouch node written in C#, like this example on the Dynamo ZeroTouch github:
![image](https://cloud.githubusercontent.com/assets/18601851/21532744/0e53a732-cd4b-11e6-9b0b-78a9a51e5fe3.png)

## What did you expect to see?

The node name in the attribute tag display as the node name in Dynamo

## What did you see instead?

Visual Studio throws an exception (or have these attribute tags been superseded by the XML tag markup)?

**Comment by mjkkirschner** [comment]
attributes like this are to be used with Nodes which inherit from `nodemodel` or other `node model` derived types - the idea is that zero touch functions should know as little as possible about Dynamo and have no dependencies on dynamo attributes and the like, of course thats not always the case... but for ZT nodes the name is taken from the method name.

**Comment by ThomasMahon** [comment]
Hi @mjkkirschner useful to know. Once again, thanks for the insights.
