### ISSUE TITLE
ZeroTouch Node library automatically implements the Class Name as a node in the library when a single public class method is created

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7461]
## Dynamo version

1.2.1

## Operating system

Win 10

## What did you do? 

Created a new ZeroTouch class called Curves with a single method. 

## What did you expect to see?

The new method available in the library within Dynamo

## What did you see instead?

The class is added to the library as well. I've found a workaround by declaring a new method and hiding it from the Dynamo library then only my desired method is displayed, but understandably, this feels like a bad workaround. It appears to be related to this problem (more so as the workaround causes the Action node to classify as a Create node): #5613

![image](https://cloud.githubusercontent.com/assets/18601851/21532816/013a4168-cd4c-11e6-9458-7c1728801587.png)

**Comment by mjkkirschner** [comment]
when you create a class in c# with no constructor a constructor with no parameters is automatically added by the .net runtime so this object cab be created.

trying adding a private constructor for your curve type. Or try adding a public constructor and hiding it.

**Comment by mjkkirschner** [comment]
to clarify- it's hard to tell if this is a bug or not since it would be difficult for us to tell if you added this constructor or .net did.

**Comment by ThomasMahon** [comment]
@mjkkirschner no constructor was the issue! Thanks for the advice, all now working as expected.
