### ISSUE TITLE
wrong input in Code Block

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/Dynamo#7465]
## Dynamo version
1.2.1.3083
## Operating system
Windows 8.1
## What did you do? 
put a variable to {} in [Imperative] statement in Code Block
## What did you expect to see?
not as input
## What did you see instead?
it shows up as input

**Comment by mjkkirschner** [comment]
@ke-yu PTAL

**Comment by aparajit-pratap** [comment]
@jhubers did you mean like this:
```
[Imperative]
{ a; }
```
: this will throw a warning

**Comment by jhubers** [comment]
I found out that to avoid showing a variable as input, you have to declare and set the value in both the associative part and again in the imperative part. But what is the logic of it? Example:
![image](https://user-images.githubusercontent.com/1529297/27323536-2c2fef38-55a2-11e7-993a-3a5830fff27f.png)

**Comment by ke-yu** [comment]
@jhubers we should fix this.

**Comment by ramramps** [comment]
@jhubers I believe this is fixed in 1.3 release. Please let us know if this is fixed.

**Comment by jhubers** [comment]
Well, you can check yourself of course, but it is not fixed in 1.3.2.2480

**Comment by ramramps** [comment]
@aparajit-pratap FYI. Do you have any updates here?

**Comment by aparajit-pratap** [comment]
@ramramps I'm currently working on making semantic changes to the use of imperative language blocks for 2.0. Will update this issue with the new expected behavior.
