### ISSUE TITLE
Unexpected output from IF node

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#7467]
I'm not entirely sure this is a bug, but it just doesn't seem logical to me
.
## Dynamo version

1.2.1.3083

## Operating system

Windows 7

## What did you do? 

Used an IF node as follows:

![if_with_lists](https://cloud.githubusercontent.com/assets/4656191/21557629/e1e71aee-cdf4-11e6-9e27-5c43abb3fe03.png)

## What did you expect to see?

See image above...I expected the result on the right. Shouldn't this node just pass through the result?

## What did you see instead?

I see a list of the same dimension as the False output (in this case I only have one item that evaluates to True).

**Comment by ThomasMahon** [comment]
This, as far as I'm aware, is as-designed behaviour. You can use ScopeIf as an alternative to achieve the behaviour you expect, or follow @andydandy74 suggestion on this thread #6491

![image](https://cloud.githubusercontent.com/assets/18601851/21567975/779916c4-cea8-11e6-94b0-6959647cdc75.png)

**Comment by dbaldacchino** [comment]
Thanks Thomas, I did find the documentation on DynamoDictionary re: the If node and it does appear to be as designed. Also found several posts (including ones by @andydandy74 ) regarding the use of functions in CBN or Python. This node might need to have lacing incorporated to make it a bit clearer, so definitely not a bug, perhaps UI Improvement/Naming. ScopeIf does the job, it's just not as discoverable/intuitive as the If node! Also needs more documentation as it can be quite powerful yet limiting at the same time (as I'm finding out).
