### ISSUE TITLE
The workspace can not excute more than one time?

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7478]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0

## Operating system
(e.g. Windows 7, Windows 8.1, etc)
Windows 7

## What did you do? 
I executed a designed workspace. Without changing any parameter, I executed the second time. The Dynamo just did nothing in the second time.  Then after tried many times, I found that if I want to execute more than one time the workspace, I must change some parameter.

## What did you expect to see?
I wonder is there anyway execute the workspace many times without changing any parameter?

**Comment by jnealb** [comment]
At this time only with the Periodic functionality.

**Comment by kronz** [comment]
@kehehee1 why do you want the workspace to execute when there are no changes?

**Comment by kehehee1** [comment]
@kronz Actually I use the Dynamo to interactive with other applications. So changes may happen in the other application, not in the Dynamo.

**Comment by mjkkirschner** [comment]
@kronz a use case for this is any host application that cannot or does not send element updates to Dynamo. The representation in Dynamo v. the Host will quickly get out of sync and executing the graph fresh is the only way to reason about what state the program and host are in.

**Comment by kronz** [comment]
Ah, I understand.  Yes, there are tools to make sure that Dynamo watches the external resources for changes.  For instance, Excel nodes use a File.FromPath to monitor the state of the Excel file on disk.  Some nodes can optionally use a file monitor, like File.ReadText, which can either take a File Path nodes (which simply delivers a string and does not update if the file is changed on disk unless the .dyn file is reloaded) or can use a File.FromPath to update the dyn file whenever the file on disk is changed.  
![2017-01-08_2254](https://cloud.githubusercontent.com/assets/3456818/21756926/6f37b220-d5f5-11e6-8e8f-b3026172d0ed.png)

There are also a couple other nodes that use Periodic update settings, like Web Request or DateTime.Now, which will udate with a specified polling time
![2017-01-08_2257](https://cloud.githubusercontent.com/assets/3456818/21756958/d2c477e2-d5f5-11e6-9156-1a002a5eb3b1.png)

For other nodes that are supplied on the package manager used to monitor other applications, it is up to the developer as to wether they will take advantage of this capability
Thanks
Zach

**Comment by kronz** [comment]
@mjkkirschner Sorry, I think we were responding at the same time.  So you are saying that in the situation where there are applications that do not allow for monitoring, we would need to supply a force-reexecute, right?  Similar to the workaround that Python users create with a boolean toggle?

**Comment by mjkkirschner** [comment]
Exactly, this could be done per node (from a context menu) or for the entire graph. It might also be possible for this method to drop element binding data though thats another discussion I guess. 😉

**Comment by kronz** [comment]
@kehehee1 if you want to see an example of this way to force re-execution on a Python based node, check out the Lunchbox package, and look at a node like "LunchBox Area Element Collector", which has a toggle to force a re-execution.
