### ISSUE TITLE
Difficult to find a node in the view

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7481]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0

## Operating system
Windows 7

## What did you expect to see?
Sometimes it's very difficult to find a node in the view. Expect to have find function for the node in the view.

**Comment by andydandy74** [comment]
Duplicate of #309

**Comment by alfarok** [comment]
thanks @andydandy74 - closing as duplicate
