### ISSUE TITLE
Force stop execution

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7484]
## Dynamo version
2.0

## Operating system
Windows 7

## What did you do? 
I click the menu "run mutation test", this menu is in the Debug menu. Then the graph run repeatedly and I can't stop it. The workspace can't close.

## What did you expect to see?
I know items in the Debug menu are not for the end user. But sometimes I  really need to stop the execution because it costs too much time or the program falls into an endless loop. So I expect I can force stop execution when I need.

**Comment by johnpierson** [comment]
Similar to https://github.com/DynamoDS/Dynamo/issues/6749
