### ISSUE TITLE
Error: Class redefinition

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/Dynamo#7485]
## Dynamo version
1.2.1.3083
## Operating system
Windows 8.1
## What did you do? 
Code Block: 
class MyFloor
{
  public Name ="";
  public Area =0;
}
## What did you expect to see?
Expected to be able to use this class not only the first run.
## What did you see instead?
In subsequent runs I get the error in the title.

**Comment by mjkkirschner** [comment]
@ke-yu PTAL - I'm not sure that `class` should be exposed in user code any longer?

**Comment by ke-yu** [comment]
@jhubers it is not expected to use class definition in code block node, neither in any .ds file. Class is generated virtually when we import a zero touch library, but it is for internal use and we may remove it in the future.

**Comment by jhubers** [comment]
@ke-yu So better remove it from the Design Script documentation then? Now I made a simple C# class dll and that works ok.

**Comment by aparajit-pratap** [comment]
This is fixed here: https://github.com/DynamoDS/Dynamo/pull/7541
