### ISSUE TITLE
excel.readfromfile not working

### ISSUE THREAD

**Issue by bujoldsj** [DynamoDS/Dynamo#7488]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.2.0.2690

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 7
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
trying to read from excel file.  Initially with script for space planning.  With this not working, wrote a script that just has FilePath, File.FromPath, Excel.ReadFromFile (string with Sheet1).  File is being found, checked with Watch.

(Fill in here)

## What did you expect to see?
List results
(Fill in here)

## What did you see instead?

Warning: Excel.ReadFromFile operation failed. 

![image](https://cloud.githubusercontent.com/assets/10131839/21786480/a9ecf2ba-d689-11e6-8bc2-7024ca292f88.png)

(Fill in here)

**Comment by jnealb** [comment]
Which version of MS Office are you using?

**Comment by bujoldsj** [comment]
MS Excel 2016 MSO (16.07571.7063) 32 bit

**Comment by jnealb** [comment]
Can you launch Excel?

**Comment by mjkkirschner** [comment]
what is the actual error?

**Comment by jnealb** [comment]
"Warning: Excel.ReadFromFile operation failed."

**Comment by bujoldsj** [comment]
Can launch excel from windows.  Have never tried to launch from dynamo, if this is possible.

**Comment by jnealb** [comment]
I meant from Windows, no not possibe from Dynamo builtin nodes.

**Comment by jnealb** [comment]
Did you upgrade from a prior version of MS Office?

**Comment by bujoldsj** [comment]
The problem was with Excel.  Got a hotfix and did repair on install.  Excel.readfromfile is now working.

**Comment by jnealb** [comment]
Thank you.

**Comment by MiroSK** [comment]
@bujoldsj Hi. Which hot fix did you use?

**Comment by bujoldsj** [comment]
I don't recall which fix.  My version of Excel is 1712 (build 8827.2148)

**Comment by MiroSK** [comment]
Thx bujoldsj. I have 1708 (8431.2153). So I will try update it.

**Comment by MiroSK** [comment]
So I did update at Excel version 1712 and it does help. It is working !!! Thx for help.
