### ISSUE TITLE
Wish: Re-sizable watch node (and copy to clip board)

### ISSUE THREAD

**Issue by eibre** [DynamoDS/Dynamo#7538]
The ability to re-size the watch node is s long time and repeating wish on the forums.
Reason: Get a better overview and make it easier to see relations when checking large list data for consistency

A really nice bonus would be an easy way to copy the contents to clip board.

Related issue: https://github.com/DynamoDS/Dynamo/issues/6006

See this forum post: https://forum.dynamobim.com/t/n00b-question-how-to-resize-watch-node/1423/7

And this forum post: https://forum.dynamobim.com/t/feature-request-re-sizable-watch-nodes-and-notes/5144/5

@Racel

**Comment by Racel** [comment]
Thanks @eibre - Taking a look at this...More soon.

**Comment by andydandy74** [comment]
The copy-to-clipboard part seems related to #1989 Although that was mainly targeted at preview bubbles)

**Comment by Racel** [comment]
@riteshchandawar - Added two tasks to WPF minimal improvements: 
Resize Watch node: https://jira.autodesk.com/browse/DYN-429
Resize Preview bubble: https://jira.autodesk.com/browse/DYN-430

**Comment by ramramps** [comment]
We are working on this in the next generation of dynamo. Closing this here

**Comment by theoryshaw** [comment]
was this ever implemented?

**Comment by mmisol** [comment]
Hi @theoryshaw . Judging from the Jira tasks this was never finished. Copying @Amoursol to bring them to their attention.

**Comment by Amoursol** [comment]
Hello @theoryshaw - This didn't make it into Dynamo in the end, but there is an alternative workaround available today in the **Springs** package called `/W WatchDialog`

![image](https://user-images.githubusercontent.com/12857357/89795315-3be69a80-daf6-11ea-8b97-416bfbb769df.png)
