### ISSUE TITLE
Notification from other application showing up in Dynamo

### ISSUE THREAD

**Issue by Tacopover** [DynamoDS/Dynamo#7547]
## Dynamo version

Dynamo Core:  1.2.0.2831
Dynamo Revit: 1.2.0.2690

## Operating system

Windows 7

## What did you do? 

I was trying to import a FBX file into Unity, but that failed, so I got an error message in Unity saying the FBX file was corrupted. At the same time I was working in Dynamo and then suddenly a new notification pops up. I open the notification and it shows me the error message from Unity in Dynamo.
Dynamo was opened through Revit but I don't if that is relevant.

![image](https://cloud.githubusercontent.com/assets/25353466/22307618/05e03aa2-e344-11e6-9449-1be7ba069a5f.png)

**Comment by johnpierson** [comment]
@Tacopover , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Yes, Going ahead and closing this. Thanks for your replies!
