### ISSUE TITLE
adaptivecomponent.bypoints

### ISSUE THREAD

**Issue by mimarsuleyman** [DynamoDS/Dynamo#7556]
I did everything until the last family type thing. When i choose family type adaptivecomponent.bypoints gives error. What can i do?﻿

**Comment by ThomasMahon** [comment]
Try posting on the Dynamo forum and you need to describe your problem in detail if you expect to get an answer. https://forum.dynamobim.com/

**Comment by ksobon** [comment]
@kronz Can we close this? It's clearly a forum question.
