### ISSUE TITLE
Loft list of curves

### ISSUE THREAD

**Issue by KenyonGraham** [DynamoDS/Dynamo#7570]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.1.0.2093
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 7 pro
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Simple dynamo definition

- generated a list of curves simple straight lines

- translated the (curves) geometry

- created a list two entries

- attempted to use surface loft....lofting between the series of lines

## What did you expect to see?

I expected to see  7 surfaces generated between the curves.

(Fill in here)
[Surface_Bridge_Rev_A - Copy.txt](https://github.com/DynamoDS/Dynamo/files/748249/Surface_Bridge_Rev_A.-.Copy.txt)

## What did you see instead?
Screenshot attached

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/15694328/22556534/5bdde916-e9cc-11e6-818a-41544940a650.png)

[Surface_Bridge_Rev_A - Copy.txt](https://github.com/DynamoDS/Dynamo/files/748254/Surface_Bridge_Rev_A.-.Copy.txt)

Dynamo file renamed to .txt

**Comment by johnpierson** [comment]
@KenyonGraham , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
