### ISSUE TITLE
String.ToNumber ignores decimal separator

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#7574]
## Dynamo version

1.2.1.3083 (1.2.1 stable)

## Operating system

Win 7 Pro, German locale

## What did you do? 

Converted a number to a string and back to a number

## What did you expect to see?

The same number as the original input value

## What did you see instead?

![grafik](https://cloud.githubusercontent.com/assets/3014437/22603616/69298022-ea48-11e6-8368-970c7f101988.png)
My hunch is that ```String.ToNumber``` doesn't respect the German locale the way that ```String from Object``` does

**Comment by andydandy74** [comment]
@johnpierson Yes.
![grafik](https://user-images.githubusercontent.com/3014437/50012769-ce503700-ffbf-11e8-9f29-40965e7c0dff.png)

**Comment by iAliJ** [comment]
This seems to be fixed as of 2.2

![image](https://user-images.githubusercontent.com/47180374/129468384-f263907a-9940-497f-a446-1503fa277f40.png)

**Comment by QilongTang** [comment]
@iAliJ Keen eyes, indeed this has been fixed and still good in latest master. Closing
