### ISSUE TITLE
DateTime.Now preview bubble snapshot clipped 

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7581]
## Dynamo version

Dynamo Core 1.2.2.91 (Unable to copy this info from _About_)

## Operating system

Windows 10

## What did you do? 

Took a snapshot of the canvas with _DateTime.Now_ with the preview bubble expanded

## What did you expect to see?

![20170206-4c](https://cloud.githubusercontent.com/assets/5621624/22652194/8f852cde-ecab-11e6-9946-a7217d171a70.png)

## What did you see instead?

![20170206-4b](https://cloud.githubusercontent.com/assets/5621624/22651949/97b0448a-ecaa-11e6-934a-21fe69246969.png)

**Comment by ramramps** [comment]
@vykrum This should be fixed in 1.3 release of studio. Please re-open if this is an issue in the latest release
