### ISSUE TITLE
Spelling Error in FilterByBoolMask

### ISSUE THREAD

**Issue by Nefarion** [DynamoDS/Dynamo#7592]
## Dynamo version 
1.2.1

## Operating system
Win7 x64

## Description
The `FilterByBoolMask` has a spelling error in the description, 

"Filters a sequence by **lookng** up ...."

Nothing major, just so you have it in the backlog!

**Comment by QilongTang** [comment]
Fixed by @andydandy74 on master(2.0). I cherrypicked to RC1.2.3 so it should be available in the coming 1.3 Release. Thank you guys for helping!
