### ISSUE TITLE
DynamoDS _ preview issues with 3D and graph toggling_ whitespace_very lots of white space

### ISSUE THREAD

**Issue by KenyonGraham** [DynamoDS/Dynamo#7596]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.1.0.2093 Dynamo Studio..............running 30 day evaluation

## Operating system

Windows 7 Professional

## What did you do? 

Attempted to preview in 3d the geometry generated.

Pls note that the purpose of the geometry is to generate an orthogonal grillage skewed grillage.

## What did you expect to see?

Spilt screen showing both the definition and 3d preview

## What did you see instead?

Merged screen showing fully 3D preview and the definition/graph preview. The right hand side of the screen was occuppied by white space a veritable white out only for 50% of the screen. Screnshot provided.

![image](https://cloud.githubusercontent.com/assets/15694328/22864569/c8c36846-f1b8-11e6-9254-fd203803713a.png)

Please note dynamo file attached  extension required:

[Surface_Bridge_Rev_C - Copy.txt](https://github.com/DynamoDS/Dynamo/files/769496/Surface_Bridge_Rev_C.-.Copy.txt)

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
