### ISSUE TITLE
Wish: Python node template

### ISSUE THREAD

**Issue by eibre** [DynamoDS/Dynamo#7604]
I think I've never used the default template in the python node:
![image](https://cloud.githubusercontent.com/assets/5968613/22944405/e3e19ae2-f2f0-11e6-9db5-f17b26028584.png)

Most of the time I work with Revit API and that require quite a few references, so I have have a textfile somewhere that I need to open and copy/paste from. (I do this almost every time I use Dynamo!) It would be nice to be able to add the path to the text file in settings. Maybe rename and extend the node paths dialog somehow:
![image](https://cloud.githubusercontent.com/assets/5968613/22944798/2a476150-f2f2-11e6-974e-6326ef5eb022.png)

Maybe add the .dyn template wish at the same time: https://github.com/DynamoDS/Dynamo/issues/6143

**Comment by eibre** [comment]
This is the template I use, if it's of any interest:
```
import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#Preparing input from dynamo to revit
element = UnwrapElement(IN[0])

#Do some action in a Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

TransactionManager.Instance.TransactionTaskDone()

OUT = 0
```

**Comment by wynged** [comment]
Seconded.  Even if there was a fixed location of this starting file that we
could alter, that would be cool.

**Comment by ThomasMahon** [comment]
Thirded - I have the exact same txt as @eibre set up which is copy/pasted whenever I start usnig Python in Dynamo, so clearly this would be a good move!

![image](https://cloud.githubusercontent.com/assets/18601851/23063163/f71a8828-f500-11e6-8797-b2e77ed09cbf.png)

**Comment by ksobon** [comment]
I agree with these sentiments. It would be nice to be able to specify a template for Python node. Although, I usually use a similar template but I have that set up in pyCharm and it allows me to create them quite quickly and efficiently. It's still a workaround rather than a solution so I vote for Python templates in Dynamo.
