### ISSUE TITLE
How to control the precision of number node?

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7606]
## Dynamo version
2.0

## Operating system

Windows 7

## What did you do? 

I pull a number node into the workspace. I want to use a number like π. But the number node only support  3 digits after the decimal point. How can I control the precision?

**Comment by dimven** [comment]
That's just the UI implementation of the node. The precision of your number is not really limited by the visual representation.

![dynamosandbox_2017-02-19_16-20-05](https://cloud.githubusercontent.com/assets/7148394/23100561/6d9bbd36-f6bf-11e6-9aa8-e60a2786caec.png)
