### ISSUE TITLE
Point basic

### ISSUE THREAD

**Issue by threedimages** [DynamoDS/Dynamo#7607]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using?1.2.1 

## Operating system

Windows 7

## What did you do? 

Point at Dynamo not connect with the Revit
![report](https://cloud.githubusercontent.com/assets/25786073/22962159/c0500a86-f37d-11e6-93a6-fde22ce453cb.PNG)

## What did you expect to see?
how to fix this

## What did you see instead?

can't link with the Revit, some part

**Comment by mjkkirschner** [comment]
what are your units in revit?

**Comment by threedimages** [comment]
Metric - mm

**Comment by mjkkirschner** [comment]
try using a larger number - moving 8 mm is probably just not visible in revit.

**Comment by threedimages** [comment]
thanks, for your help...

**Comment by andydandy74** [comment]
Can this be closed? Seems like expected behaviour to me.

**Comment by threedimages** [comment]
yes sure
