### ISSUE TITLE
How to batch execute dyn files more efficiently using DynamoCLI.exe?

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7616]
## Dynamo version
2.0

## Operating system
Windows 7

## What did you do? 
I want to run dyn files out of Dynamo. I find that DynamoCLI can do this. But it takes about 3s before the dyn execution using DynamoCLI.exe. How can I imporve this?

**Comment by kehehee1** [comment]
I know how to do this now. I write a client imitating the DynamoCLI.exe myself. Construct CommandLineRunner onetime and run it repeately. It takes a little much time only when it runs the first time.

**Comment by mjkkirschner** [comment]
glad you figured this out - the issue is when we load the core libraries and convert them into design script classes and methods.
