### ISSUE TITLE
Dynamo Crashing Unexpectedly

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#7631]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Operating system

Windows 10

## What did you do? 

Simply tried to Flatten a complex list structure using List@Level. Refer to attached image.

![dynamo_github_error](https://cloud.githubusercontent.com/assets/12857357/23211324/74606630-f8f9-11e6-846f-0f906d80cff7.JPG)

## What did you expect to see?

The Flatten node working correctly. 

## What did you see instead?

An error message requesting a submission to GitHub.

![dynamo_github_error2](https://cloud.githubusercontent.com/assets/12857357/23211369/bd75cfd6-f8f9-11e6-82bb-dba92f797d18.JPG)

**Comment by ramramps** [comment]
@Amoursol This is fixed in 1.3 Dynamo studio. Please try the latest build and re-open if this is still an issue.
