### ISSUE TITLE
Element.Geometry fails at floors with circular openings

### ISSUE THREAD

**Issue by taurerm** [DynamoDS/Dynamo#7632]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Operating system

Windows 10

## What did you do? 

Getting geometry of a floor with a circular opening (Element.Geometry node)

## What did you expect to see?

Element geometry

## What did you see instead?

null
[FloorOpening.zip](https://github.com/DynamoDS/Dynamo/files/794334/FloorOpening.zip)

**Comment by dimven** [comment]
Hi @taurerm 

Are you sure the openings are circular and not elliptical? There is a known issue that is already being tracked here: https://github.com/DynamoDS/Dynamo/issues/6542

**Comment by taurerm** [comment]
Hi @dimven - I investigated the opening family and indeed - although it appears to be round - it is based on an ellipse. So this is like #6542

**Comment by kronz** [comment]
closing as duplicate
