### ISSUE TITLE
Code Block doesn't create input port

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#7658]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Operating system

W7

## What did you do? 

Flatten(a)[n];

## What did you expect to see?

A Code Block with 2 input ports, "a" and "n"

## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/14221455/23500885/f2bb75fe-ff31-11e6-87f7-e1641b9dd106.png)

**Comment by andydandy74** [comment]
I've seen this happen with other nodes as well. As far as I can tell this issue seems to be isolated to elements from the ```BuiltIn``` category.

**Comment by ThomasMahon** [comment]
Also, you need to declare the class then the method. Really this should probably throw an exception. Also, it seems that `Flatten` in DesignScript only accepts the long version:

![image](https://cloud.githubusercontent.com/assets/18601851/23579310/8b643064-00e2-11e7-99c3-4e1049eaa806.png)

**Comment by andydandy74** [comment]
@ThomasMahon - This is not ```List.Flatten```, just ```Flatten``` - it's a different node/command. The commands from the ```BuiltIn``` category are called directly, not by their class.

**Comment by ramramps** [comment]
@paoloemilioserra This is fixed in the next release.
<img width="323" alt="screen shot 2017-10-27 at 12 29 37 pm" src="https://user-images.githubusercontent.com/8495197/32114831-931a87a0-bb12-11e7-976c-70d59b19fd10.png">

**Comment by ramramps** [comment]
Closing this, as this is fixed in the next release.
