### ISSUE TITLE
Improvement: Node to deal with Parts

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#767]
Would like to have nodes like:

create Parts
select Parts (or maybe with select elements)
divide Parts by intersection(=curves? could be tricky though I guess)

later: merge Parts....

thanks for watching ;-)

**Comment by johnpierson** [comment]
Closing as this is an older topic and is achievable with custom packages available. If this is still a wishlist item for Dynamo for Revit, please open on the D4R Issues page. https://github.com/DynamoDS/DynamoRevit/issues
