### ISSUE TITLE
  Why Openning dynamo  so slow from Revit 2015,  and abnormal quit

### ISSUE THREAD

**Issue by poborsky** [DynamoDS/Dynamo#7672]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
  1.2.0
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
   Win7 64-bit
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by ikeough** [comment]
We're going to need more info to help diagnose this. I also recommend opening this issue in the Dynamo for Revit repo, as suggested by the notes above.
