### ISSUE TITLE
Build #1.2.3.20170301T0037 crashed Dynamo Studio

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/Dynamo#7677]
## Dynamo version

1.2.1 now

## Operating system

Windows 10 x64

## What did you do? 

Updated to the latest Daily build

## What did you expect to see?

Dynamo Studio to start

## What did you see instead?

Dynamo Studio crashed on startup

**Comment by ramramps** [comment]
@DanielHurtubise Did you try the latest build version? 
Please re-open if this is an issue with the latest release.
