### ISSUE TITLE
"Warning: No item exists at specified index address" when using List.SortByKey

### ISSUE THREAD

**Issue by ejnaren** [DynamoDS/Dynamo#7702]
## Dynamo version

1.2.1.3083

## Operating system

Windows 7

## What did you do? 

When trying to get the first sublist of List.SortByKey i get an error saying: "Warning: No item exists at specified index address".

The exact same method works fine on an identical list of lists I create manually.

## What did you expect to see?

I expect to get the first sublist of the "global list"

## What did you see instead?

No sublist for me...

Screenshot:

![dynamobim bug 10-03-2017](https://cloud.githubusercontent.com/assets/737773/23792470/5ace5296-0587-11e7-96d0-3510c91d50ef.JPG)

**Comment by ejnaren** [comment]
By the way, I just tested with List.GroupByKey also. Same issue.
I dont get it. Am I missing something here..?

**Comment by ThomasMahon** [comment]
@ejnaren its not a bug but expected behaviour. With methods like `SortByKey` you cant index the list using integers, you have to access the sublist via their key. Best thing to do, is place the node equivalent on the graph and look at its output ports. Typically this will be the name of the key you need:

![image](https://cloud.githubusercontent.com/assets/18601851/23826352/c1070632-0692-11e7-9d23-2f0b3751f5c0.png)

**Comment by ejnaren** [comment]
Ah. I see.
That is very clever.
I thought it was a bit too weird to find a bug like that. Just could not
figure it out :)

Maybe there should be some easy way to deduct that from the user interface?
Maybe a tip in the description if the node documentation or in the error
message?
If indeed that is a default way to handle many such situations it should be
clear.
Or maybe I have not been diving deep enough in the training material.

Anyway many thanks for the help!
You are a star!

**Comment by mjkkirschner** [comment]
@kronz @Racel - this is actually a tracked old task about getting better UI around dictionaries with named keys...

**Comment by mjkkirschner** [comment]
I think is now addressed since these nodes return dictionaries and previews show their keys.
