### ISSUE TITLE
Error when building Dynamo core on Linux 

### ISSUE THREAD

**Issue by bigdoods** [DynamoDS/Dynamo#7711]
Hi @pboyer 

I have just tried to build Dynamo with the latest version of mono and I get the following error:

https://gist.github.com/bigdoods/dfb52dc3939e7fb0b448ddfc7cd7e6e7

I am using ubuntu 16.04, XBuild Engine Version 12.0 and Mono, Version 4.2.1.0. I could try install the versions of mono that you have used? Any other suggestions/ fix?

Thanks in advance.

**Comment by pboyer** [comment]
We have used 3.2.8 internally. @mjkkirschner might be able to give you some pointers.

**Comment by mjkkirschner** [comment]
It looks like you need to run nuget restore first on the solution (also using mono and the nuget.exe)

**Comment by ramramps** [comment]
@bigdoods Any updates here? Did you try using mono?

**Comment by bigdoods** [comment]
No. Didn't attempt @mjkkirschner suggestion and didn't install mono version 3.2.8 to try either.

**Comment by ramramps** [comment]
thanks @bigdoods . Please try using that suggestion and let us know if that works.

**Comment by bigdoods** [comment]
If there is a need for it in the future, I might do, but I don't personally have a need for it immediately. I would be very interested to hear about another person's success ;-)

**Comment by ramramps** [comment]
Sure @bigdoods. You can look at the github space for any updates.
I am closing this for now.
