### ISSUE TITLE
Package author seems to be name bound instead of account id

### ISSUE THREAD

**Issue by moethu** [DynamoDS/Dynamo#7719]
## Dynamo version
1.2

## Operating system
Windows 7

## What did you do? 
I recently changed my Autodesk Username but afterwards I was no longer able to update the packages I released under the old name. I had to change my username back in order to be the official author again. Is the author bound by name? Would it be possible to bind it by ID if such exists?

**Comment by mjkkirschner** [comment]
this should now be fixed.

**Comment by moethu** [comment]
thanks @mjkkirschner
