### ISSUE TITLE
Number Sequence returning invalid Numbers

### ISSUE THREAD

**Issue by mengelmn** [DynamoDS/Dynamo#7725]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(1.2.1.3083)

## Operating system

(Windows 10)

## What did you do? 

(Create a def for the calculation of the Fibonacci Sequence to a Given length)

## What did you expect to see?

(A Fibonacci Sequence of Numbers)

## What did you see instead?

(When a Sequence of Numbers is requested of a length greater than 47 Items, the Calculation returns "Negative" and inaccurate values)

![image](https://cloud.githubusercontent.com/assets/20505196/24156859/bf29b14e-0e25-11e7-82da-fa1533e8d5be.png)

When Complete the same def utilzing Swift on IOS the numbers return accuratly
![image](https://cloud.githubusercontent.com/assets/20505196/24156973/20eea22c-0e26-11e7-8313-7db3aac918b3.png)

**Comment by mjkkirschner** [comment]
@aparajit-pratap @ke-yu is this expected?

**Comment by gregmarr** [comment]
I would say yes, the next number in the sequence is greater than the largest possible positive 32 bit number, and so it wraps around to a negative value.  Getting a larger number would require using a 64 bit integer.

**Comment by ke-yu** [comment]
I remember internally we use int64, not int32.

**Comment by gregmarr** [comment]
Seems like there needs to be an int32 in the pipeline somewhere.
