### ISSUE TITLE
The DesignScript code is not available always in code block

### ISSUE THREAD

**Issue by Qiongjing** [DynamoDS/Dynamo#7762]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 1.2.0

## Operating system

Windows 7

## What did you do? 

I entered the code in the code block when I open the dynamo in the revit, but it showed "null" in the list.However, when I only open the dynamo to enter the same code, everything was ok.

## What did you expect to see?

the data displayed normally in the list

## What did you see instead?

the list showed "null"

**Comment by aparajit-pratap** [comment]
@Qiongjing could you share the graph you used to reproduce this.

**Comment by johnpierson** [comment]
Closing as this issue has not seen a lot of action. If this issue still persists, please feel free to reopen.
