### ISSUE TITLE
Dynamo crashes

### ISSUE THREAD

**Issue by ilyamoto** [DynamoDS/Dynamo#7767]
[bug_report.txt](https://github.com/DynamoDS/Dynamo/files/908557/bug_report.txt)
## Dynamo version
1.2.1.3083

## Operating system
Windows 10

## What did you do? 

Dynamo keeps crashing for no obvious reason (see attached report and dynamo file)
![autodesk dynamo studio 2017-04-10 00 28 49](https://cloud.githubusercontent.com/assets/27149619/24841112/b989f730-1d84-11e7-949b-52cd2c326b7a.png)

[While Definition.zip](https://github.com/DynamoDS/Dynamo/files/908566/While.Definition.zip)
[bug_report.txt](https://github.com/DynamoDS/Dynamo/files/908567/bug_report.txt)

**Comment by alfarok** [comment]
I am unable to reproduce the issue using the latest dynamo build.   Please feel free to reopen if you are still experiencing similar behavior.

![image](https://user-images.githubusercontent.com/13341935/32509371-1a6393f4-c3bb-11e7-9943-0c7de1925322.png)
