### ISSUE TITLE
Backslash causing issues in code block string

### ISSUE THREAD

**Issue by BrettCTaylor** [DynamoDS/Dynamo#7781]
## Dynamo version

1.3.0

## Operating system

Windows 10

## What did you do? 
In the latest 1.3.0 release I am now getting an error with strings contained within Code Blocks where the string ends with a backslash (ie for a folder path).  I had this same error with an earlier release but it was fixed, it is now reappearing (Code Block Error #7248 ) 

![image](https://cloud.githubusercontent.com/assets/18408513/24993629/8bfcc2c8-206a-11e7-9525-48b057f04282.png)

**Comment by gregmarr** [comment]
Looks like #7248 was fixing "\\\\", which is different than your case.  The \ character is a quote character, and is used for, among other things, including a " in a string.  You should do "test\\\\";

**Comment by BrettCTaylor** [comment]
Hi Greg,

No #7248 was a "\" error which is the same error I am now getting in Dynamo 1.3.0. 

This was fixed in previous versions but is now reappearing in 1.3.0.
