### ISSUE TITLE
PolyCurve Change number of segments when changing the Geometry Working Range

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#7782]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.
![image](https://cloud.githubusercontent.com/assets/14221455/25013260/400e918a-2073-11e7-9f0e-d40613f55b04.png)

## Operating system
W7
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Created PolyCurve by Points and Changed the Geometry Working Range to Extra large to get rid of a warning

## What did you expect to see?

![image](https://cloud.githubusercontent.com/assets/14221455/25013309/6b66fe76-2073-11e7-8603-5cca9ca7b1f5.png)

## What did you see instead?
Many segments of the PolyCurve are missing in the Extra Large range.
![image](https://cloud.githubusercontent.com/assets/14221455/25013327/767bf050-2073-11e7-8c4a-62c7d4c109f2.png)

**Comment by aparajit-pratap** [comment]
https://jira.autodesk.com/browse/DYN-804

**Comment by Kranzy** [comment]
Is there a fix for this? or a work around?

**Comment by aparajit-pratap** [comment]
We have found a simple example for this use-case to work as expected in the Medium and Large scale settings. There is no guarantee that all geometry-scale settings will work for any geometry, just that any one setting should work in most cases.
![image](https://user-images.githubusercontent.com/5710686/80044047-522e0380-84d1-11ea-82f3-6e061b95fa53.png)

**Comment by aparajit-pratap** [comment]
See attached file for the simplified case:
[Polycurve.ByPoints - Copy.zip](https://github.com/DynamoDS/Dynamo/files/4519454/Polycurve.ByPoints.-.Copy.zip)
