### ISSUE TITLE
Solid.ByRevolve description

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7785]
## Dynamo version

1.3.0.875

## Operating system

Windows 10

## What did you do? 

Checked out the description of _Solid.ByRevolve_

## What did you expect to see?

Something in the description that indicates the resulting geometry would be a solid

## What did you see instead?

![solidrevolve](https://cloud.githubusercontent.com/assets/5621624/25063484/ef000058-2202-11e7-8f2a-f99364f0c6f0.png)

**Comment by aparajit-pratap** [comment]
@vykrum thanks for catching it.

**Comment by Amoursol** [comment]
This typo has now has been resolved.
