### ISSUE TITLE
Planning and Programming

### ISSUE THREAD

**Issue by JD12345678901** [DynamoDS/Dynamo#7828]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo Core 1.3.0.875
Dynamo Revit 1.3.0.875
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Microsoft Windows 7 Proffessional
![capture](https://cloud.githubusercontent.com/assets/28068285/25456036/61c44e4a-2a97-11e7-8f01-c6a24d0b8405.png)

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?
![color](https://cloud.githubusercontent.com/assets/28068285/25456016/5047d736-2a97-11e7-8cb9-c0a37d83d07d.JPG)

(Fill in here)

## What did you see instead?
![output](https://cloud.githubusercontent.com/assets/28068285/25488445/a26c02e0-2b2c-11e7-980d-f6ad50f8fae7.JPG)

(Fill in here)

**Comment by JD12345678901** [comment]
I am having an issue with the various colors showing up as well as the correct lengths and widths, any ideas?

**Comment by JD12345678901** [comment]
Warning: Material.ByName operation failed. 
A Material with the given name does not exist in the current Document.

I have created all the materials in revit and im still getting warning messages...

**Comment by ksobon** [comment]
This kind of questions is better suited for Dynamo Forum. https://forum.dynamobim.com/

**Comment by ikeough** [comment]
I agree with @ksobon, that this could probably be resolved in the Forum. Also, I'd ask that this issue please be moved to the Dynamo for Revit repository, as per the instructions above.

Having said all of that, in order to reproduce, we'd need a .dyn file and a Revit model if some context is required. If you'd like to supply those, please re-open this in the Dynamo for Revit repo.
