### ISSUE TITLE
Revit preview Vision not updated

### ISSUE THREAD

**Issue by LuiggiAlfaro** [DynamoDS/Dynamo#7836]
![bugdynamo](https://cloud.githubusercontent.com/assets/28229216/25566864/140c8834-2da8-11e7-953e-3fc0f2526803.gif)
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(1.3)

## Operating system

(Windows10)

## What did you do? 

(I'm trying too view my changes in revit while i'm making changes in dynamo, but it doesn't show it. It only show me an static point. This is the workflow of the second learning video)

## What did you expect to see?

(Changes while i'm changing the number of the slider)

## What did you see instead?

(No change)

**Comment by mjkkirschner** [comment]
I think this is a units issue, try larger numbers.

**Comment by ikeough** [comment]
As per the above instructions, please re-open this issue in the Dynamo fore Revit repo if the problem persists.
