### ISSUE TITLE
update nuget package for DSCoreNodes.dll

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7843]
DynamoCoreNodes package needs an update to 1.3. That DLL is not in any other package. 

Cheers! 

![image](https://cloud.githubusercontent.com/assets/529781/25620250/c684b440-2f1b-11e7-87c2-c4bf77a92213.png)

**Comment by aparajit-pratap** [comment]
https://www.nuget.org/packages/DynamoVisualProgramming.DynamoCoreNodes/2.0.0-beta4066
