### ISSUE TITLE
Code Block with string value not upgrading properly to 1.3.0

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#7863]
## Dynamo version

1.3.0.875

## Operating system

Windows 7

## What did you do? 

I opened a definition that worked fine in 1.2.1 and noticed errors in the code blocks.

## What did you expect to see?

The code block string should not have resulted in this error (see below). Also there were code blocks that contained strings of text and were frozen and worked fine in 1.2.1 but result in the same red node and error in 1.3.0.

## What did you see instead?

Code block disconnected (no longer has an output port) and reports "Error: EOF expected". In the meantime I'll have to change these nodes with a String node instead. (The string was a lengthy Regular Expression: "[a-zA-Z]{1,5}?[\d]{1,4}?[^ '\t\n\r\f\v\w]+[\w]{1,5}?[^ '\t\n\r\f\v\w]*[\w]{0,4}[^ '\t\n\r\f\v\w]*[\w]{0,4}|[a-zA-Z]{1,5}[^ '\t\n\r\f\v\w]*[\d]{1,5}[a-zA-Z]*";)

![codeblockstring](https://cloud.githubusercontent.com/assets/4656191/25975174/6bb8e2f8-3672-11e7-8e9d-26c486f00320.png)

**Comment by dbaldacchino** [comment]
Here's another before (1.2.1)

![codeblock-1 2 1](https://cloud.githubusercontent.com/assets/4656191/25975559/93ec010e-3674-11e7-8108-3f4d03055897.png)

 and after (1.3.0):

![codeblock-1 3 0](https://cloud.githubusercontent.com/assets/4656191/25975561/9aed9df0-3674-11e7-816f-049c08f11ac0.png)

**Comment by dbaldacchino** [comment]
Looks like it's due to the \ characters. What has changed with respect to this?

**Comment by ksobon** [comment]
cc: @kronz @samuelcwl @ke-yu Looks like a regression guys. Can we get this fixed?

**Comment by aparajit-pratap** [comment]
This is expected behaviour and is not a bug. There are only certain characters that can be escaped as shown here for C# (and DesignScript tries to be close to C#): https://blogs.msdn.microsoft.com/csharpfaq/2004/03/12/what-character-escape-sequences-are-available/
Namely the following characters can be escaped:
```
\' – single quote, needed for character literals
\" – double quote, needed for string literals
\\ – backslash
\0 – Unicode character 0
\a – Alert (character 7)
\b – Backspace (character 8)
\f – Form feed (character 12)
\n – New line (character 10)
\r – Carriage return (character 13)
\t – Horizontal tab (character 9)
\v – Vertical quote (character 11)
\uxxxx – Unicode escape sequence for character with hex value xxxx
```
You can see them hardcoded in our grammer here:
https://github.com/DynamoDS/Dynamo/blob/0622384b0bbffd5a2de617b8d4a8ad3aaeb72396/src/Engine/ProtoCore/Parser/atg/Start.atg#L665

In the script that you're using above, you're trying to escape characters like `w` that are not "escapable" and you'll therefore see the syntax error unless you use `\\w`.

**Comment by dbaldacchino** [comment]
Thanks for the explanation. Unforunately this complicates matters for non-codees unnecessarily IMO. If one is using certain syntax for a regular expression, it becomes unnecessarily complicated to know what characters need to be escaped with an additional \ and which don't because they don't work consistently across the board. This makes the tool very frustrating to deal with.

**Comment by aparajit-pratap** [comment]
@dbaldacchino that is why we have the `String` node in addition to code block nodes. Strictly speaking code block strings allow for certain characters to be escaped so as to codify the strings that they wish to create including things like whitespaces, etc. DesignScript doesn't have anything for string literals in its syntax, which is what you're looking for but that is exactly what the `String` node is for. See the difference in the graph below. The code block string generates a string preview with tabs and newlines in it but the string node output preserves the input string:
![image](https://user-images.githubusercontent.com/5710686/50713540-4ebd0180-106d-11e9-849c-e872636ce186.png)

**Comment by dbaldacchino** [comment]
Understood, I appreciate your explanation. String node from now on when this use case arises :) Have a great weekend!
