### ISSUE TITLE
Low graph and 3d preview performance

### ISSUE THREAD

**Issue by TFoteinop** [DynamoDS/Dynamo#7867]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.875

## Operating system

Windows 10 x64

## What did you do? 

Any action

## What did you expect to see?
A fast and fluid UI

## What did you see instead?
UI is so slow that is almost unusable. I am having this issue since version 1.1. Never been fixed.
In contrary the same version of Dynamo DS is fast and fluid.

**Comment by johnpierson** [comment]
@TFoteinop , are you still receiving this error on Dynamo 2.0.1?
