### ISSUE TITLE
Changing Geometry Working Range scales new Coordinate Systems incorrectly

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7871]
## Dynamo version

1.3
## Operating system

Win 10

## What did you do? 

Set the Geometry Working Range to Large.

Created a `Point.ByCartesianCoordinates` (X=500 ,Y=500) and a `CoordinateSystem.ByOrigin` (XYZ, X=2000). Connected the new CoordinateSystem to the cs input of the point. 

## What did you expect to see?

The point translate using the new cs as its origin. 

## What did you see instead?

The cs position in the geometry view is 'rescaled' by 1000, whereas the point is not, resulting in an incorrect translation of the point if the new coordinate system is input. 

In the attached video you can clearly see the problem. The point is a long distance away from the coordinate system with X=500 ,Y=500, despite the fact the CoordinateSystem X = 2000 (i.e. the Point shouldn't be beyond the CoordinateSystem  along X). Notice the output of coordinates from both nodes. In addition, if the CoordinateSystem is used as the cs to the Point, it appears to translate the point from itself (as expected) but since its positioned incorrectly in the geometry view, the result must be wrong:

[Recording #84.zip](https://github.com/DynamoDS/Dynamo/files/1002418/Recording.84.zip)

![untitled-1](https://cloud.githubusercontent.com/assets/18601851/26078486/a2510532-39b7-11e7-8286-cc2a2e551a57.jpg)

![image](https://cloud.githubusercontent.com/assets/18601851/26078214/abd6ac3e-39b6-11e7-88eb-9d5e9be8206b.png)

**Comment by aparajit-pratap** [comment]
Tracking: https://jira.autodesk.com/browse/DYN-825

**Comment by aparajit-pratap** [comment]
Fix will be available in 2.3. FYI: @QilongTang

**Comment by QilongTang** [comment]
Thanks, @aparajit-pratap Verified using Verified using daily build: DynamoCoreRuntime_2.3.0.4775_20190423T1256
