### ISSUE TITLE
Python Custom Nodes are adding additional (and unnecessary) ranks to output lists

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#7873]
## Dynamo version

1.3

## Operating system

Win 10

## What did you do? 

Output a 1D list from a python script in a custom node

## What did you expect to see?

A 1D list of elements

## What did you see instead?

A 2D list. It seems that when a python script is wrapped in a CN, the CN adds an additional rank to the output list. If the same python script is copied and pasted into a DYN, the output behaves as expected. This isn't an isolated problem, but the second time I've experienced this problem (first time I observed this behaviour I thought it was something to do with outputting a jagged array...turns out I was wrong!).

The only way to circumvent this problem is to defy all logic and index the output list from Python in the body of the code.

**Python script in DYN** (output 1D list, as expected):
![image](https://cloud.githubusercontent.com/assets/18601851/26100391/a5595b94-3a25-11e7-858f-367dcf59e50f.png)

...the same python script in a CN outputs this:
![image](https://cloud.githubusercontent.com/assets/18601851/26100304/614310da-3a25-11e7-9e6e-b0399b5906a1.png)

**Workaround:- Index the output list within the Custom Node:** 
I would expect this to return the first item
![image](https://cloud.githubusercontent.com/assets/18601851/26100081/bf52d008-3a24-11e7-8755-7488f991d35f.png)

...instead, it defies all logic and returns a list! The behaviour - or the output list structure I should say - is now as expected:
![image](https://cloud.githubusercontent.com/assets/18601851/26100063/b4ec095e-3a24-11e7-9ead-d8014756ff97.png)

...copy that python script to a DYN...and the first item is returned, as expected, but obviously exhibiting different behaviour from the CN:
![image](https://cloud.githubusercontent.com/assets/18601851/26100188/1891d4b6-3a25-11e7-9bde-99e9e7f94d01.png)

**Comment by andydandy74** [comment]
@ThomasMahon - I think this may have something to do with how you declare the custom node's inputs. Dynamo needs to know that the first input expects a list of elements.

**Comment by ThomasMahon** [comment]
@andydandy74 Good point, I just tested it and that does appear to fix it. Cheers
