### ISSUE TITLE
Multiplication of large numbers doesn't work as expected

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#7875]
Please see here: https://forum.dynamobim.com/t/dynamo-calculation/11825

Basically if number is too big the Integer32 can't hold it, and it returns a weird result instead of a meaningful exception: 

MSDN reference: https://msdn.microsoft.com/en-us/library/system.int32.aspx

cc: @kronz

**Comment by kronz** [comment]
@keyu @aparajit what kind of options do we have for handling this better?

**Comment by jnealb** [comment]
@kronz We have filed tasks under MAGN-6647 on YouTrack to address this.

**Comment by kronz** [comment]
Thanks.  In the end it looks like it is an issue resolved by having a meaningful error

**Comment by Amoursol** [comment]
This should now be resolved in Dynamo 2.5.
