### ISSUE TITLE
Geometry Range settings affect visualization of coordinate system on curve

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#7882]
## Dynamo version

![image](https://cloud.githubusercontent.com/assets/14221455/26260370/315d1f50-3ccd-11e7-89f5-c12cc168ec2a.png)

## Operating system

W7

## What did you do? 

Curve.CoordinateSystemAtParameter and Curve.StartPoint in two different Geometry Ranges

## What did you expect to see?

![image](https://cloud.githubusercontent.com/assets/14221455/26260319/0f333a40-3ccd-11e7-8f72-c6162b2ac430.png)

## What did you see instead?
![image](https://cloud.githubusercontent.com/assets/14221455/26260262/d8d20292-3ccc-11e7-90fd-42f30901f412.png)

**Comment by mjkkirschner** [comment]
fyi @aparajit-pratap

**Comment by mjkkirschner** [comment]
related to https://github.com/DynamoDS/Dynamo/issues/7871 ?

**Comment by paoloemilioserra** [comment]
Possibly

**Comment by aparajit-pratap** [comment]
Tracking: https://jira.autodesk.com/browse/DYN-825

**Comment by aparajit-pratap** [comment]
Fix will be available in 2.3, FYI: @QilongTang
