### ISSUE TITLE
[Wishlist] Opening Excel in a background process

### ISSUE THREAD

**Issue by kronz** [DynamoDS/Dynamo#7921]
It would be very useful for teamwork that we have the ability to open Excel in the background when running operation with Read from Excel.
Most users are not closing it after the operation unfortunately.
Originally filed in DynamoDS/Revit by @DanielHurtubise
https://github.com/DynamoDS/DynamoRevit/issues/1639

**Comment by joshmoorePW** [comment]
Hi I'm curious if there is any work being done on this.  Another use case is automation of dynamo runs with services like Imaginit Clarity.  Having the ability to tell Excel to open read only, or when it creates an excel file to save and close it can circumvent lot's of problems.  I hope that helps the use case.

**Comment by XTDHub** [comment]
Option to close Excel while writing to it..
