### ISSUE TITLE
Wrong Perimeter Curves From Surface

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#7928]
## Dynamo version

![image](https://cloud.githubusercontent.com/assets/14221455/26790036/94325120-4a12-11e7-8b70-a11a00f88378.png)

## Operating system

W7

## What did you do? 

![image](https://cloud.githubusercontent.com/assets/14221455/26790492/31e35990-4a14-11e7-94dc-c2f788486642.png)

## What did you expect to see?

perimeter curves of the whole surface

## What did you see instead?

Curves not matching the perimeter of the only surface returned.

**Comment by paoloemilioserra** [comment]
There is a single surface in the output but if I use it to create a polysurface it returns that the number of surfaces is 2.

**Comment by johnpierson** [comment]
@paoloemilioserra , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
