### ISSUE TITLE
Wish: Filters for Package Manager

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#793]
Since Peter has just closed #519, I thought some new wishes were in order... ;-)

It would be great to be able to filter the package manager list for cases like:
- "Installed / Not installed": Only show me packages I haven't installed yet
- "Update available": Only show me packages that need updating
- "Mine": Only show me packages that I have authored
- "Deprecated": Include deprecated packages

Of course it would help if we were able to combine those filters (Example: "Show me my deprecated packages that aren't installed on this machine").

**Comment by Racel** [comment]
Yes, this is a great idea! But, as mentioned before. We will address this in the next generation and not the WPF UI.
