### ISSUE TITLE
Not able to view preview

### ISSUE THREAD

**Issue by sxr157930** [DynamoDS/Dynamo#7933]
## What did you see instead?: Nothing

I've tried repair, reinstall, and uninstall and reinstall of Dynamo.

![image](https://user-images.githubusercontent.com/29215187/26837531-7d94175c-4a92-11e7-86f7-910a82635b93.png)

Please let me know how to fix this issue as this is beginning to become a huge road-blocker for me.

Thanks,
Sandheep

**Comment by jnealb** [comment]
@sxr157930 Are you running Studio or Dynamo for Revit?

**Comment by sxr157930** [comment]
The fact is, it didn't work on both. The attached screenshot is from Studio. On Revit, the background grid itself was not available, although selected in VIEW.
I was initially able to view on Studio (but not on Revit), then I had to install Factory Design Suite for a different purpose, and that was the last time Studio worked fine. So, I uninstalled the factory design suite completely, along with Revit and Dynamo Studio, reinstalled Studio, and still facing the issue.

**Comment by jnealb** [comment]
@sxr157930 Do you have any vestigial versions of Dynamo installed? Can you check for any folders under Program Files and also in the Control Panel?

**Comment by sxr157930** [comment]
@jnealb I'm not sure if it is vestigial, but there are files in Program Files>Autodesk>Dynamo Studio 2017 and Program Files>Dynamo>Dynamo Core/Dynamo Revit. On the control panel it is the same three available, Studio 17, Dynamo Core 1.3.0.875 aand Dynamo Revit 1.3.0.875

**Comment by sxr157930** [comment]
@jnealb Is there anyway to completely cleanup without any remnants and then try installing again?

**Comment by jnealb** [comment]
@sxr157930 Just wipe out the Dynamo folders and uninstall from the Control Panel if anything remains.

**Comment by mjkkirschner** [comment]
this looks like the problem that we saw together @jnealb where the background preview is actually working but geometry is not visible (but the grid is). The user had some issue with a mismatched core and DynamoRevit installing a different dynamoCore.

**Comment by sxr157930** [comment]
@jnealb I tried your suggestion of wiping out the folders and uninstalling from control panel. Then restarted, tried reinstalling, but somehow the system is made to believe that Studio is already installed, not sure if I need to go and remove some info from any log file.

**Comment by jnealb** [comment]
@sxr157930 Can you try using https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed to remove Dynamo? Then try re-installing.

**Comment by sxr157930** [comment]
@jnealb That worked great! Finally my day is starting to turn around for good. Thanks a lot for your help and guidance, much appreciated! All your suggestions were spot on. :) 👍 💯

**Comment by jnealb** [comment]
Why our installers/upgrade processes led you to the bad state is a riddle wrapped in an enigma, but at least we can get you back in the saddle :+1:

**Comment by sxr157930** [comment]
:) may be you could put your suggestions together as a template if someone else comes with a similar issue  and add it to wiki
