### ISSUE TITLE
Element.GetParameterValueByName does not work

### ISSUE THREAD

**Issue by AnasAnas11** [DynamoDS/Dynamo#7940]
I use dynamo 1.3 on windows 7
I'm trying to get the height of my windows by Element.GetParameterValueByName
But I get a list WITHOUT VALUES.
I tried many parameter names (normally the three of them are correct)
I have the same problem with walls.

Do you know where is the problem?
Their is another function that I can  use instead?

![supp3](https://user-images.githubusercontent.com/29274955/26922599-dfdfc31c-4c3f-11e7-9274-db0f75c7d4e2.PNG)
![suppp1](https://user-images.githubusercontent.com/29274955/26922598-dfde1698-4c3f-11e7-9eb1-4294fcd59323.PNG)
![suppp2](https://user-images.githubusercontent.com/29274955/26922600-dfe10c04-4c3f-11e7-934e-e44100429999.PNG)

**Comment by ksobon** [comment]
Isn't Height a type parameter? In which case you have to grab the Type first then the Height: 

![image](https://user-images.githubusercontent.com/529781/27034649-76c4bca6-4f4c-11e7-8fb6-236c20f64d83.png)

Also, this is Dynamo github page. Please post all DynamoRevit related issues here: https://github.com/DynamoDS/DynamoRevit 

cc: @kronz can we close this?
