### ISSUE TITLE
Dynamo script worked yesterday, but not today?? (Saying to report)

### ISSUE THREAD

**Issue by KimberleyR** [DynamoDS/Dynamo#7967]
Version of Dynamo; 1.3.0.0

Operating System; Windows 10.

Device using; Surface Pro 4, 256GB, 8GB Ram.

I have been creating a code checking, having dynamo check the parameter of elements within Revit. The code seemed to work fine yesterday on another PC and when I went to work on it today it sent up the same error/ bug script that it in the screen shot attached so I rebuilt it, for it to just re throw the same script. 

I expected to see it di what it done yesterday, which is it identify which building elements in the revit model are outside of the building standard by coding them red. 

The error script/ nothing. Telling me to report it to this page and close the script and restart it and try again....

**Comment by mjkkirschner** [comment]
@KimberleyR we'll need the stack trace from the crash dialog at a minimum to help. Please reopen if you are still having the issue.
