### ISSUE TITLE
Nodes as members of multiple groups

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#7972]
## Dynamo version

1.3 stable

## Operating system

Windows 7

## What did you do? 

Added a node to a group using box selection from right to left, accidentally selecting **two** groups
![before](https://user-images.githubusercontent.com/3014437/27174209-8fa98c76-51bb-11e7-8de7-8a7da7f3e118.PNG)

## What did you expect to see?
Apart from the fact that this happended by accident, any of the following:
* The "Add to group" command greyed out
* The "Add to group" command expanding to two options ("Group 1" & "Group 2")
* An error message like "You cannot add an item to more than one group"

## What did you see instead?
![after](https://user-images.githubusercontent.com/3014437/27174319-fcbd9df2-51bb-11e7-8ba9-27e0310bab97.PNG)
My observations are these:
* When in doubt, Dynamo will add items to the oldest group in the selection
* Items in other selected groups will be added to that group as well (probably only when using left-to-right selection boxes since that will also select all items contained in a selected group).

Here's a diff of the graph before and after the grouping operation:
![dyndiff](https://user-images.githubusercontent.com/3014437/27174521-c22a5a4e-51bc-11e7-81b6-949e40a88201.PNG)

While the ability to nest groups has been requested as a new feature (#6603), I believe this to be a bug, since in this case the individual elements are added to a second group (instead of the nested group's Guid).

CC @Racel

**Comment by jnealb** [comment]
@ramramps fyi

**Comment by ramramps** [comment]
This is tracked here :  https://jira.autodesk.com/browse/QNTM-2372
