### ISSUE TITLE
Create Project Parameter Node Does not Create Project Parameter

### ISSUE THREAD

**Issue by crwinchester** [DynamoDS/Dynamo#7982]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 1.2

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 7

(e.g. Windows 7, Windows 8.1, etc)

## Create Project Parameter

This node does not create a real project parameter. Instead it creates a floating shared parameter that is not actually published to the shared parameter file. Somehow it's both types of parameters simultaneously.

## What did you expect to see?

Expectation is that the node would create what it says that it would create: A Project Parameter. The current state prevents it from being able to be read across projects that contain similarly instantiated Project Parameters via the node. It does not appear to be working correctly and somehow maintains a dual state in the Project.

## What did you see instead?

Parameter that results appears as a Shared Parameter, but is not actually a Shared Parameter since it is not published to the loaded Shared Parameter file.

**Comment by ksobon** [comment]
Revit API doesn't allow for creating Project Parameters. https://forums.autodesk.com/t5/revit-api-forum/create-project-parameter-not-shared-parameter/td-p/5150182 I am not sure why this node is pretending to be doing that. 

@kronz can you answer that? cc: @moethu

**Comment by moethu** [comment]
@ksobon yes the Revit API does not allow that but I don't understand the problem with this workflow - at least we have never experienced any issue with this using this "workaround" and I used it everywhere, in Grevit and various tools. I agree on renaming it but the workaround worked for me so far.

**Comment by ksobon** [comment]
@moethu i don't have anything against the workaround, but it seems to be causing issue:

>  The current state prevents it from being able to be read across projects that contain similarly instantiated Project Parameters via the node. <

We are making users believe something that is not true, and then they are disappointed by the shortcomings that stem from this really being a workaround not a solution.

**Comment by kronz** [comment]
Interesting . . . we shouldn't be systematizing creation of elements masquerading as other elements.  I agree that it is probably a useful functionality to have, but the introduction of this kind of inconsistency is a problem, as we are seeing in this bug. Now that it is there in the application and in use, it makes it a little bit tricky to remove. 
So, the actual behavior is to create an unpublished shared parameter?  Let's talk about what kind of solution we could do here:
a. Remove the node
b. Change the description of the existing node to say what it actually does
c. Change the name of the functionality to Parameter.CreateUnpublishedSharedParameter and add a migration
d. others ideas?

**Comment by andydandy74** [comment]
d) Remove the node and add a migration to Parameter.CreateSharedParameter which seems to do exactly what is expected. 

And speaking about Parameter.CreateSharedParameter:
* Cherry on top would be to have an additional boolean input to make params invisible (like in the archi-lab implementation of this functionality. 
* And if I had another wish, it would be this: Another optional input (string) for a shared params file path so users gain the ability to *not* write Dynamo-generated shared params to their standard SP file. (When the node is done it would reset the SharedParametersFilename value to its previous value. Wouldn't that be something?)

Sorry for hijacking the thread... ;-)

**Comment by ksobon** [comment]
@andydandy74 if you post this as a new Issue, then I can have a look at making these changes. 

@kronz Yeah, I think we should remove this one. It really gives users a bad idea about something that is not possible.

**Comment by andydandy74** [comment]
@ksobon Done.
https://github.com/DynamoDS/DynamoRevit/issues/1718

**Comment by johnpierson** [comment]
Closed as this is tracked on the issue Andreas mentioned.
