### ISSUE TITLE
No Geometry Showing.

### ISSUE THREAD

**Issue by nitromechanic16** [DynamoDS/Dynamo#7984]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Studio 1.3.0.875

## Operating system
Windows 10

## What did you do? 

Open up a dynamo sample file and older files.

## What did you expect to see?

I expected to see geometry in 3d workspace. 

## What did you see instead?

The 3d workspace is not populated with any geometry. 

![2017-06-19_0033](https://user-images.githubusercontent.com/25863104/27274141-06025d26-5487-11e7-8fdc-2db6cfcc4ab6.png)

**Comment by jnealb** [comment]
@nitromechanic16 This may be a known issue: do you also have Revit installed on the same machine? Did you upgrade to Studio 1.3?

**Comment by nitromechanic16** [comment]
I upgraded studio to 1.3, but for some reason Revit will not upgrade. I have tried uninstalling and then reinstalling with 1.3 and it still installs the older version.

**Comment by nitromechanic16** [comment]
@jnealb update: I have revit 2017 installed. I have removed the earlier dyanmo version and installed 1.3 for revit and dynamo studio and still no luck.

**Comment by nitromechanic16** [comment]
@jnealb I have uninstalled revit and in in-installed/ reinstalled dynamo to no avail.

**Comment by jnealb** [comment]
@nitromechanic16 I am on vacation now, pulling in @smangarole to follow up..

**Comment by TravisMWilliams** [comment]
Same problem here. Trying out the trial to see if it is something we want to purchase. No background preview is a deal breaker for me.

**Comment by nitromechanic16** [comment]
So, it appears you must update the Dynamo via the app manager to install the 2017.4 update. This seems to fix the issue. However, attempts to download the 2017.5 update seem to create an error in the app manager. The important this is that I can see geometry now!
