### ISSUE TITLE
unable to unfreeze node

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/Dynamo#7993]
during some workshops at AU london, a bug affected a number of users. The "unfreeze" option was greyed out - to solve, users had to freeze something upstream and then unfreeze it again - then unfreeze was made available again. Possibly related to [7965](https://github.com/DynamoDS/Dynamo/issues/7965). occurred in both dynamo studio and dynamo for revit version 1.3 up to date as of today.

**Comment by AndrewHeumann** [comment]
no circular dependencies in this case - just a normal graph from Dieter Vermeulen's workshop.

**Comment by jnealb** [comment]
@AndrewHeumann Is it possible for you to provide us with this graph?

**Comment by ramramps** [comment]
@AndrewHeumann can you please attach the graph or provide some screen shot?

**Comment by AndrewHeumann** [comment]
No

**Comment by ramramps** [comment]
We have tried this in other graphs and cannot reproduce. 
Closing this for now, but feel free re-open when you see it again. Please attach the graph or error screen shot.
