### ISSUE TITLE
Node for Curves not working with Edges

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#800]
Evaluate Curve or edge works with both, but it seems to be the only node that works with edges, aka autodesk.revit.DB.edge.

XYZ array on curve reports this:
One of your inputs was not of the correct type. See the console for more details.
   à Dynamo.Models.NodeModel.__eval_internal_recursive(FSharpList`1 args, Dictionary`2 outPuts, Int32 level)
   à Dynamo.Models.NodeModel.<>c__DisplayClass44.<evaluateNode>b__41()

How can I get an XYZ array on edge for instance? I tried a few things with no luck.

thanks.

![edges](https://f.cloud.github.com/assets/4572196/1590947/1e68bae8-5299-11e3-870a-73adac67cd16.PNG)

**Comment by ikeough** [comment]
XYZArrayOnCurve no longer exists. Closing :)
