### ISSUE TITLE
L error

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8023]
## Dynamo version
1.3.0.875

## Operating system
Windows 7

## What did you do? 
Typed 'L' in a code block

## What did you expect to see?
L to be recognized as a variable

## What did you see instead?
![l](https://user-images.githubusercontent.com/5621624/27823341-673b09a8-60c6-11e7-9859-f0d796c72556.png)

**Comment by andydandy74** [comment]
@vykrum - I think ```L``` is a reserved word since it can be used in replication guides for setting Longest lacing:
![lisreserved](https://user-images.githubusercontent.com/3014437/27829475-16fc1396-60c2-11e7-8d00-5e2e32631618.PNG)

**Comment by vykrum** [comment]
@andydandy74 Thanks. Makes sense.
