### ISSUE TITLE
Parameter.StorageType not working as expected

### ISSUE THREAD

**Issue by taurerm** [DynamoDS/Dynamo#8030]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.875

## Operating system

Windows 10

## What did you do? 

Trying to query parameters

## What did you expect to see?

Parameter.StorageType, UnitType... etc working

## What did you see instead?

Only Parameter.Name and Parameter.Id work
![capture](https://user-images.githubusercontent.com/3396098/27986541-728a6b5e-6400-11e7-8028-f04309a01c53.png)

**Comment by ksobon** [comment]
@mjkkirschner this is an interesting one. The `Parameter` wrapper that we have doesn't catch this case. Basically they cover `Autodesk.Revit.DB.Parameter` class, while this is a wrapper class for user created parameters stored in the project. Also, `ParameterElement` inherits from an `Element` thus our internal wrapper just used the `UnknownElement` wrapper on it. That makes the `Parameter.Name` and `Parameter.Id` not fail since it doesn't rely on `Definition` and only on the element object. Now, all other properties that OP is demonstrating require that we retrieve the Definition, but this particular object doesn't have it stored in a property `Definition` but instead it uses a method called `GetDefinition` to retrieve it. Yet, another Revit intricacy. What do we do about this? 

cc: @kronz

**Comment by ksobon** [comment]
@taurerm what are you trying to accomplish? I am afraid that Parameter and ParameterElement are not the same thing in Revit. There is no functionality supporting ParameterElement yet. Maybe I can think of some workaround if you tell me what your end goal is.

**Comment by taurerm** [comment]
The way I'll try to resolve is to iterate through all categories, get the info there and then pull out individual items per parameter ID...

Sent from my iPhone

On 9 Jul 2017, at 01:26, Konrad K Sobon <notifications@github.com> wrote:

@taurerm what are you trying to accomplish? I am afraid that Parameter and ParameterElement are not the same thing in Revit. There is no functionality supporting ParameterElement yet. Maybe I can think of some workaround if you tell me what your end goal is.

**Comment by ksobon** [comment]
I don't follow. Please provide a detailed workflow description.

**Comment by taurerm** [comment]
I'll send my graph tomorrow- basically I want to write out all shared parameter bindings to Excel, edit them there, and recreate them in an empty project.
So far I got it all sorted using InternalDefinition in Python except Instance/Type... for that I need to go the extra way of iterating through all Types, get all parameter bindings and ID > unique items > sort by ID to get the lists in sync 

Sent from my iPhone

On 9 Jul 2017, at 17:44, Konrad K Sobon <notifications@github.com> wrote:

I don't follow. Please provide a detailed workflow description.

**Comment by taurerm** [comment]
Sample here - this post illustrates the issue 
https://www.linkedin.com/feed/update/urn:li:activity:6289496777401995264
Sent from my iPhone

On 9 Jul 2017, at 17:44, Konrad K Sobon <notifications@github.com> wrote:

I don't follow. Please provide a detailed workflow description.

**Comment by taurerm** [comment]
And this is the Dynamo - finally on the Hotel WiFi...
WriteSharedParametersToExcel.dyn - this one works, but I can't determine if
it is a Type or Instance

My experimental one is: SharedParametersWIP.dyn - see how everything goes
haywire after applying Element.Parameters to All Elements of Parameter Type
[image: Inline image 1]
The output is - well, quite a surprise...

Cheers
Martin

Martin Taurer
taurerm@gmail.com
+31 6 34489 403

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2150).
