### ISSUE TITLE
Doc.ParameterBindings

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#8038]
dynamo 4 revit 2017

## Dynamo version

1.3

## Operating system

Win10
## What did you do? 
following python code:
.....
`doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application
instlist = []
typelist = []
instlist.append("I N S T A N Z P A R A M E T E R")
typelist.append("T Y P E P A R A M E T E R")
bindings = doc.ParameterBindings
n = bindings.Size
if 0 < n:
	it = bindings.ForwardIterator()
	while (it.MoveNext()):
		d = it.Key
		b = it.Current
		m = it.Current.GetType()
		if m == Autodesk.Revit.DB.InstanceBinding:
			instlist.append("Parameter: %s" % d.Name)
		else:
			typelist.append("Parameter: %s" % d.Name)

OUT=instlist,typelist`

## What did you expect to see?
2 lists 
1) with name of parameters
2) with parameter types

## What did you see instead?

dynamo error. "The managed object is not valid"

for d.Name  line 38
!!!!!!!!!!!!!!!!!!!
same code is working in 0.91

**Comment by johnpierson** [comment]
@epeter- , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
