### ISSUE TITLE
Set Custom Package Folder during install?

### ISSUE THREAD

**Issue by CBTIT** [DynamoDS/Dynamo#8045]
Hi I was looking to see if there was a way to set the CustomPackageFolder during the install process. I am an admin that is trying to deploy Dynamo and if this could be set either through the install that would make deployment a lot easier. 

I already know that this can be changed in the dynamosetting.xml file but that is located in a user profile and does not get created until Dynamo is launched the first time by the user. This is fine for a couple of users but not for 200+. 

If this should not have been submitted here please let me know where it should be submitted.

**Comment by QilongTang** [comment]
@sharadkjaiswal Do you think it's possible?

**Comment by radumg** [comment]
Second this ! Could this be done with a simple argument passed to the `msi` file ?
Something like `-custompackagefolder "\\server\folder\"` ?
I added Dynamo's MSI to the Revit deployment, so we can either add arguments to it there or in things like PDQ.

FYI @CBTIT , we push out the dynamo packages to user machines at logon via a script, 450+ users globally to get around this limitation as I didn't want to overwrite their `DynamoSettings.XML` file. Vastly more inefficient, but gets the job done.
Also, see [this issue ](https://github.com/DynamoDS/Dynamo/issues/7274) for some background info.

**Comment by johnpierson** [comment]
This is similar to the issue radu referenced here, https://github.com/DynamoDS/Dynamo/issues/7274. Closing this as it is being tracked there.
