### ISSUE TITLE
Crash when trying to put a string into a code block

### ISSUE THREAD

**Issue by taurerm** [DynamoDS/Dynamo#8053]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1.1736
## Operating system

Windows 10

## What did you do? 

Created a code block, tried to input "#"

## What did you expect to see?

A code block with "# "

## What did you see instead?

Dynamo has crashed

**Comment by smangarole** [comment]
@taurerm - Can you please provide more details about the crash? Steps to reproduce?

**Comment by taurerm** [comment]
I cashed while opening a code block and wanted to have "#" as a string
deliminator

**Comment by ramramps** [comment]
@taurerm Let us know if this is still an issue. Also provide some screen shot or attach the graph here. 
With latest core, we don't see this issue.

**Comment by taurerm** [comment]
Issue resolved...

Martin Taurer
taurerm@gmail.com
+31 6 34489 403

**Comment by ramramps** [comment]
thanks @taurerm

**Comment by taurerm** [comment]
It turned out that another plugin caused the issue - pyRevit
http://eirannejad.github.io/pyRevit/ - it is hard to trace the root of the
cause - at my desktop installation they coexist nicely, on my laptop they
crash...

Happy to help to get to the root of this - I assume it is a Python
incompatability...

Cheers
Martin

Martin Taurer
taurerm@gmail.com
+31 6 34489 403
