### ISSUE TITLE
How to convert Dynamo list to a N-dimensional array in C#

### ISSUE THREAD

**Issue by xuhaozheng** [DynamoDS/Dynamo#8058]
## Dynamo version

1.3.0

Hi, I'm trying to discretize points on surface by UV into a 2D array in C# for some algorithm, simple code like  this:
![image](https://user-images.githubusercontent.com/28526120/28554628-1c0f57aa-712d-11e7-9a3e-70be39181ae5.png)
As can be seen in Dynamo:
![image](https://user-images.githubusercontent.com/28526120/28554658-4820d6e8-712d-11e7-9caa-15cfbb4ee71e.png)
The result is a list of lists, and I can access certain item with index PS[n][m] in Dynamo, so how can I access item with similar item in **C#** like **points[n][m]**?
Or, since I'm not very familar with C#, which type can be used to achieve the same object instead of IEnumerable? What is the stucture of Dynamo list?

**Comment by mjkkirschner** [comment]
Seems you just want to use something like toList() or ElementAt() on your Ienumerable, I think the Dynamo list implement the .net IList interface.

**Comment by mjkkirschner** [comment]
please re-open or ask in the forum if you still need help.
