### ISSUE TITLE
Dynamo Crash

### ISSUE THREAD

**Issue by pierramo** [DynamoDS/Dynamo#8064]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by smangarole** [comment]
@pierramo Can you please provide more details about this crash?

**Comment by ramramps** [comment]
Closing this  for now.
@pierramo Please feel free to re-open if this issue still persists.
