### ISSUE TITLE
DynamoCLI.Exe - Error - Unhandled Exception

### ISSUE THREAD

**Issue by milotindragos** [DynamoDS/Dynamo#8077]
## Dynamo version
Dynamo Core 1.3.1.1736
## Operating system
Windows 10
## What did you do? 
Use DynamoCLI.Exe to run tasks in the background.
"C:\Program Files\Dynamo\Dynamo Core\1.3\DynamoCLI.exe" -o "Z:\Desktop\CMD-Test\CMD-Test2.dyn" /s "all"
When running the graph with Revit open and via Dynamo everything works perfectly. 
## What did you expect to see?
Write data to excel file
## What did you see instead?
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Autodesk.LibG.LibGPINVOKE.end_asm_library()
   at Autodesk.LibG.LibG.end_asm_library()
   at Autodesk.LibG.ExtensionApplication.ShutDown()
   at ProtoFFI.ExtensionAppLoader.Terminate()

What am I doing wrong?

![capture](https://user-images.githubusercontent.com/30367360/28859591-1eb62a14-7750-11e7-9ee9-3775fe970625.JPG)
![cmd-test2](https://user-images.githubusercontent.com/30367360/28859590-1eb3f41a-7750-11e7-96cb-8cf15cb7b7ac.png)
[CMD-Test2.zip](https://github.com/DynamoDS/Dynamo/files/1192793/CMD-Test2.zip)

**Comment by mjkkirschner** [comment]
@milotindragos - I'm not sure the CLI loads excel nodes, you might need to add it here and recompile:
https://github.com/DynamoDS/Dynamo/blob/7e27f7fa4c99feaec8307787044fcd0ac243af12/src/DynamoApplications/PathResolvers.cs#L28

This error is unrelated and shows on some machines when Dynamo shuts down.

**Comment by mjkkirschner** [comment]
please reopen if you are still having trouble.
