### ISSUE TITLE
Namespace lookup not working in imperative blocks

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#8084]
## Dynamo version

1.3 / 1.31

## Operating system

Windows 10

## What did you do? 

Tried to resolve this issue:
https://github.com/dimven/SpringNodes/issues/29

## What did you expect to see?

```
def NullAllInd(l1:var[],val){
return = [Imperative]
{
i;
z = {};
for(i in GetKeys(l1) )
{
	if(l1[i] == val)
	{
		0;
		z = DSCore.List.AddItemToEnd(i,z);
	}
}
return = z;
}};
```
`NullAllInd({null,1,2,null,3,null,1,2}, 1)`

should return `{1, 6}`

## What did you see instead?

null

This is a pretty big issue, because whenever you install some of the most popular packages out there, something in imperative code becomes unusable. (i.e. Lunchbox disables Solid, Rhynamo disables Point, archi-lab.net disables List, etc...)

If I remove archi-lab, the code behaves as expected:

![dynamosandbox_2017-08-04_21-03-18](https://user-images.githubusercontent.com/7148394/28969956-3bf27848-7959-11e7-8a6f-4274b7947191.png)

@aparajit-pratap

**Comment by ThomasMahon** [comment]
See also #7697. @dimven agree, its a major issue. For the uninitiated (most of whom are likely to be using Archi-lab given its popularity), it must be a nightmare trying to track down the cause and really needs urgent attention.

**Comment by mjkkirschner** [comment]
@dimven are you saying that when even when you use the full namespace of a list function the function is not found?

**Comment by dimven** [comment]
Ah, I forgot to check if this has been reported already. Since this is a known issue, i'll close the current one and follow up in #7697.

@mjkkirschner , yes that seems to be the case.
