### ISSUE TITLE
workspace is blank,and it is not shows anyting.

### ISSUE THREAD

**Issue by freedom0525** [DynamoDS/Dynamo#8092]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(DynamoInstall0.9.1-DynamoInstall1.3.1)

## Operating system

(Windows 10)

## What did you do? 

(workspace is blank,and it is not shows anyting,and no grid.)
![-12](https://user-images.githubusercontent.com/30766877/29032725-1cd5e422-7bc5-11e7-9682-bce57c9927c3.jpg)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by jnealb** [comment]
@freedom0525 Can you please provide us with some more detail: did you upgrade from 0.9.1 to 1.3.1? If so, how was it done?

**Comment by freedom0525** [comment]
I have tried to install different Dynamo version to solve this problem,but it is no use!!!

**Comment by jnealb** [comment]
Is this Dynamo Studio or Dynamo for Revit?

**Comment by freedom0525** [comment]
dynamo for revit

**Comment by jnealb** [comment]
which version of Revit?

**Comment by freedom0525** [comment]
revit 2017

**Comment by freedom0525** [comment]
I install ladybug,butterfly and Honeybee, affter that it is not show the grid and graph。

**Comment by jnealb** [comment]
so if the Revit Addins are not installed does Dynamo function properly?

**Comment by freedom0525** [comment]
![-122](https://user-images.githubusercontent.com/30766877/29033537-f3ba122c-7bc7-11e7-8c73-f71452af915c.jpg)

**Comment by jnealb** [comment]
Which Addin collides?

**Comment by mjkkirschner** [comment]
@mostaphaRoudsari FYI any thoughts?

**Comment by freedom0525** [comment]
maybe addin collides,but I have tried to uninstall different Addin。it can not solve !

**Comment by freedom0525** [comment]
I also tried to clean the registrys and uninstall other version.it still can not solve it.
![-2](https://user-images.githubusercontent.com/30766877/29034110-c3fcfb1a-7bc9-11e7-9674-264c966974cf.jpg)

**Comment by mostaphaRoudsari** [comment]
@mjkkirschner none of ladybug tools plugins interact with the Dynamo itself.
@freedom0525 is this happen when you insert any specific node?

**Comment by freedom0525** [comment]
I have uninstalled all plugins 。it can not solve !

**Comment by mjkkirschner** [comment]
@freedom0525 have you looked at any of the faqs about graphics not showing - https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by ramramps** [comment]
@freedom0525 Did you try the suggestion made above?
