### ISSUE TITLE
[Feature Request] Docking Dynamo Player

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8099]
Can we please add the functionality to 'dock' Dynamo Player in Revit? Same way we dock the Properties menu, or Project Browser. 

It could be tabular (Same way the Flux addon is). Would make an awesome upgrade on use now that the Player has inputs.

**Comment by jnealb** [comment]
1++

**Comment by johnpierson** [comment]
@Amoursol , Do you think you could open a Revit idea for all this really great Dynamo player ideas you have? If you already have, feel free to share the link here. 

Similar to: https://github.com/DynamoDS/DynamoRevit/issues/1808
