### ISSUE TITLE
[Feature Request] Element Id's selectable in Player Output

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8100]
The same way the Watch node allows you to select the '**Green Element Ids**' in Dynamo, could we implement this into the renamed _Watch Output_ in Player? 

Would be pretty epic to select directly from that environment and would facilitate many efficiency gains in things such as Warnings resolution. 

In the image below, the **Element Id** outputs are blue - and non-selectable. In the Dynamo environment, they will hone in on that element in Revit.

![player_element_ids](https://user-images.githubusercontent.com/12857357/29162359-191219d0-7db1-11e7-84c3-147f453ca6b8.jpg)

**Comment by mjkkirschner** [comment]
@bogdanzavu FYI

**Comment by johnpierson** [comment]
@Amoursol , Do you think you could open a Revit idea for all this really great Dynamo player ideas you have? If you already have, feel free to share the link here. 

Similar to: https://github.com/DynamoDS/DynamoRevit/issues/1808

**Comment by SajithWetta** [comment]
Is this idea already implemented? I saw some posts regarding its availability in several versions of Revit.

**Comment by SajithWetta** [comment]
@BogdanZavu @kronz I would like to know the possibility of implementing this idea.
