### ISSUE TITLE
[Feature Request] Notes output for Player

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8101]
Could we have the ability to add in a **static notes** output to Player? You can fudge this by putting in a faux string, or a faux watch node, but it's still not quite ideal. 

This would allow for users to input micro-help files into their players scripts that would help out hugely with legibility. 

![player_notes](https://user-images.githubusercontent.com/12857357/29162551-b2fe5f9a-7db1-11e7-9bb2-c0a3048a2044.jpg)

**Comment by ikeough** [comment]
Like my comment on #8102, can you please re-post this to the Dynamo for Revit repo?

**Comment by Amoursol** [comment]
Done! [https://github.com/DynamoDS/DynamoRevit/issues/1808](url)

**Comment by BogdanZavu** [comment]
@Amoursol My first taught is to use the frozen flag to display inputs in read-only state. I know there is a request to deal with the frozen nodes as well. This could be a cheap way to satisfy both requests. We'll have to discuss this internally however...

**Comment by johnpierson** [comment]
Closing this as it was moved to the Revit repo. It also seems that this needs to go through the "Revit Ideas" route.
