### ISSUE TITLE
[Bug] Dynamo Player won't recognise capitalised .DYN files

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8102]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1

## Operating system

Windows 10

## What did you do? 

I tried to load in a directory of Scripts to access via Dynamo Player. The one I was looking for exists within said directory, but didn't appear in Player.

## What did you expect to see?

The script in question.

## What did you see instead?

It appears that having a file named x.DYN won't be recognised, but x.dyn will. I'm not sure how the file type is named - but I had both lower and upper case natively from the generation of scripts.

If I manually renamed the .DYN to .dyn - and refresh player, it appears. It disappears if I do it in reverse. 

Not recognised:
![not recognised](https://user-images.githubusercontent.com/12857357/29168869-c75c38b0-7dc8-11e7-8917-18a4e62bca01.JPG)

Recognised:
![recognised](https://user-images.githubusercontent.com/12857357/29168827-997b0016-7dc8-11e7-8ed4-8963ae6b2313.JPG)

**Comment by ikeough** [comment]
@Amoursol Thanks for this report. This is a problem for the Dynamo Player team. Can I ask you to repost this in the Dynamo for Revit repo?

**Comment by Amoursol** [comment]
Done :) [https://github.com/DynamoDS/DynamoRevit/issues/1807](url)

**Comment by ramramps** [comment]
Because this is tracked under Dynamo For Revit repo, closing this issue in Dynamo.
