### ISSUE TITLE
Unhandled exception dynamo engine

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#8105]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo core 1.3.1.1736 // Dynamo Studio 1.2.0.2871

## Operating system

Windows 10

## What did you do? 

I was using Optimo package linked with Robot Structural Analysis and started the iteration process

## What did you expect to see?

To complete the iteration process

## What did you see instead?

(Fill in here)
![immagine](https://user-images.githubusercontent.com/25440316/29219672-fbd13ef6-7eb8-11e7-83bd-4ac2149b534a.png)

**Comment by jnealb** [comment]
@cleobeca Can you please provide us with your steps and which dyn/dyf files you used?

**Comment by cleobeca** [comment]
Here the file i used:
[Files.zip](https://github.com/DynamoDS/Dynamo/files/1218373/Files.zip)

**Comment by jnealb** [comment]
@cleobeca I can not repro the crash with your files; I get a warning "null value can not be cast to double" with the NSGA_II.AssignFitnessFuncResults node. Why is your Studio version 1.2? It should be 1.3.

**Comment by cleobeca** [comment]
You need Robot Structural Analysis to make the things work, i forgot this custom node too:
[V Bracing.zip](https://github.com/DynamoDS/Dynamo/files/1218753/V.Bracing.zip)

About the version of dynamo Autodesk App fails to install the update, don't know why, but i have the same crash using the Dynamo for Revit 1.3.1

**Comment by jnealb** [comment]
Not sure why we have this delta: I still get the warning and the Function.Apply node lists 7 "null" list elements as its output, which may hint at incorrect input/setup?

**Comment by cleobeca** [comment]
Have you downloaded the package that allowed the link between robot structural analysis and dynamo? If you search for _"Structural Analysis for Dynamo"_ in the online package you should easily find it. It seems that you miss something to begin the analysis in Robot and i think is the package that the reason of the null value. Before Manul Run in Dynamo you have to lunch Robot. Unfortunately it's not that easy to explain

**Comment by jnealb** [comment]
I do not have Robot

**Comment by cleobeca** [comment]
I'll try i new installation and see what happen. Thank anyway

**Comment by johnpierson** [comment]
Closing this as the user account does not exist anymore.
