### ISSUE TITLE
[Bug] Dynamo 2.0 does not render missing ZT nodes

### ISSUE THREAD

**Issue by radumg** [DynamoDS/Dynamo#8124]
## Dynamo version

2.0 - built from source just now.

## Operating system

Windows 10

## What did you do? 

1. Loaded a ZT library
2. Placed a few nodes on canvas, connected them, etc.
3. Saved DYN file and closed Dynamo
4. Re-opened Dynamo and file
5. None of the ZT nodes (or connections) are rendered on the canvas

![workspace-zt-not-loaded](https://user-images.githubusercontent.com/11439624/29591751-4c8ee888-8798-11e7-97bb-de64a1e256de.png)

6. Add ZT library again using + button next to `Add-ons`
7. Nothing happens, so I close the DYN file and re-open.
8. All ZT nodes and connections are now rendered as expected.

![workspace-zt-loaded-file-reopened](https://user-images.githubusercontent.com/11439624/29591757-5589b8f0-8798-11e7-8fa8-8df700d7eb93.png)

Note : between the 2 Dynamo sessions, the `.DLL` file for the ZT library has not changed or moved, there's no reason why it shouldn't see it in the first place. Dynamo `1.3+` installed on same system does not exhibit this issue. 

## What did you expect to see?

All ZT nodes correctly rendered on the canvas.

## What did you see instead?

No nodes from the ZT library were present on the canvas.

**Comment by mjkkirschner** [comment]
@radumg thanks for this report:
@Racel @ramramps @ColinDayOrg @smangarole 

There are two issues here and should be two tasks:

1) dummy nodes (unresolvedNodes) are not created for nodes with missing types
2) ZeroTouch libraries saved in the file are not automatically imported like they were for xml deserialization.

**Comment by mjkkirschner** [comment]
I've marked major because it essentially destroys graphs.

**Comment by mjkkirschner** [comment]
filed as :
https://jira.autodesk.com/browse/QNTM-1635
and
https://jira.autodesk.com/browse/QNTM-1636

**Comment by radumg** [comment]
Thanks @mjkkirschner for the lightning-fast reaction. Let me know if you need me to test anything further.

**Comment by mjkkirschner** [comment]
I believe this has been fixed with:
https://github.com/DynamoDS/Dynamo/pull/8173
