### ISSUE TITLE
[bug] Dynamo 2.0 files not recognised as future version by Dynamo 1.3

### ISSUE THREAD

**Issue by radumg** [DynamoDS/Dynamo#8130]
## Dynamo version

2.0

## Operating system

Windows 10

## What did you do? 

Open a DYN file authored in Dynamo `2.0` in Dynamo `1.3`.

## What did you expect to see?
![future dyn](https://user-images.githubusercontent.com/11439624/29696599-db5faee4-8941-11e7-9486-2c114d9158e5.PNG)

![future version](https://user-images.githubusercontent.com/11439624/29696534-809418f6-8941-11e7-9159-b35aa00d7b85.PNG)

An error message warning me the file was authored in a future version of Dynamo.

## What did you see instead?

An error message telling me the file is corrupted.
![dynamo 2 0 in previous versions](https://user-images.githubusercontent.com/11439624/29696459-0762e372-8941-11e7-8184-8698776c1f16.PNG)

I suspect this is because the logic that is establishing the version (future or not) is still reliant on deserialising the XML first.

**Comment by jnealb** [comment]
@radumg Nice, this will get filed in JIRA.

**Comment by jnealb** [comment]
Update the priority of QNTM-1681 to Critical.

**Comment by radumg** [comment]
hi @jnealb , if this has been closed, I assume it has been resolved on the ADSK side somehow ?

**Comment by jnealb** [comment]
@radumg As mentioned above, it is filed in our backlog which is why I closed it.
