### ISSUE TITLE
Improvement Request: Node Ports to be Consistent Height

### ISSUE THREAD

**Issue by OliverEGreen** [DynamoDS/Dynamo#8138]
Hi guys! Just a quick UI improvement request :)

## Dynamo version

All versions

## Operating system

All OSs

## What did you expect to see?

Node & Code Block headers of consistent height, so that when aligned to top, all wires are straight.

## What did you see instead?

![nodeheaders](https://user-images.githubusercontent.com/29973601/29817956-f122f5f6-8cb1-11e7-86df-b497da9449ca.JPG)

Wires are wonky; I use keyboard shortcuts to keep my definitions looking legible and any 'wonky' lines are seen as an area which requires improvement. This has greatly increased the legibility of my definitions, however Code Blocks are still a thorn in my side. Is there any capacity to slightly increase the header height of all Code Blocks to make them consistent with all other nodes? 

Thanks in advance!

**Comment by gregmarr** [comment]
The headers, and even the nodes themselves, are all actually the same size here, it's the port heights that are different.  The ports on the code block nodes are shorter than the ports on the List.Create and Watch nodes, even when the ports have the same content.

**Comment by OliverEGreen** [comment]
On second glance, it seems you're right. Ideally we'd have consistent port height. Maybe the line spacing could be increased within the code block?

**Comment by Racel** [comment]
This will not be addressed in the WPF UI. But, we will try and address this in the next generation of Dynamo. Closing.
