### ISSUE TITLE
Crash after adding custom node in itself

### ISSUE THREAD

**Issue by ysvirshch** [DynamoDS/Dynamo#8144]
## Dynamo version

Dynamo.Core 1.2.1.3083. I used Dynamo Sandbox.

## Operating system

Windows 10 x64

## What did you do? 

1. Create custom node Node1.
2. In the opened custom node workspace select Node1 and add it to the canvas.
3. Add any other node to the canvas

## What did you expect to see?

Node was added to the canvas.

## What did you see instead?

Dynamo crashed. Please see the gif below.

![dynamo_crash](https://user-images.githubusercontent.com/22908074/29975432-f9ea3610-8f3e-11e7-9a1e-11d2b9a97d3f.gif)

**Comment by jnealb** [comment]
@ysvirshch Can you please see if this still happens with the latest stable version: 1.3?

**Comment by ysvirshch** [comment]
Hi @jnealb, thanks for the response.
Yes this crash is reproduced on the version 1.3.0.875. But in this case I get other exception. Please see attached image 

![image](https://user-images.githubusercontent.com/22908074/30020761-b4f697a2-916d-11e7-9c3b-e3f5fba7af4c.png)

**Comment by jnealb** [comment]
@ysvirshch Thank you. This is tracked in our system as QNTM-1777. FYI: @smangarole

**Comment by ikeough** [comment]
Looks like it's having a problem with a custom node that has no inputs and outputs being embedded in itself. The error is an exception when trying to address the output ports on the custom node, most likely when we recompile the function definition for the VM.

**Comment by jnealb** [comment]
@ysvirshch This is being addressed in the upcoming Dynamo release.

**Comment by QilongTang** [comment]
@ysvirshch This will be fixed in next release:
![recursivecustomnode](https://user-images.githubusercontent.com/3942418/31346629-b69d3422-ace7-11e7-91b3-c92e156f9717.gif)
