### ISSUE TITLE
SplitByParameter ambiguity

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8148]
## Dynamo version

1.3.1

## Operating system

Windows 7

## What did you do? 

tried to distinguish between the two SplitByParameter options

## What did you expect to see?

Two different descriptions of what the nodes do.
Would be better if one of them was SplitByParameter**s**

## What did you see instead?
Identical description for nodes that behave quite differently
![csbp-1](https://user-images.githubusercontent.com/5621624/30011827-88002048-9158-11e7-965a-7594ab6b3271.jpg)
![csbp-2](https://user-images.githubusercontent.com/5621624/30011829-892fa6d2-9158-11e7-912c-0b1294c01fa7.jpg)

**Comment by ikeough** [comment]
The documentation for the second function just seems to be wrong. It should save "Split a Curve into multiple segments at the provided parameters."

**Comment by jnealb** [comment]
@vykrum This is tracked with QNTM-2256: thank you.

**Comment by QilongTang** [comment]
This is fixed in latest Dynamo 2.9.0.
