### ISSUE TITLE
Dynamo Crash when using Rhynamo Node CreateRhinoGeometry.DS_BrepToRhino

### ISSUE THREAD

**Issue by pierramo** [DynamoDS/Dynamo#8172]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1.1736

## Operating system

Windows 7 Professional

## What did you do? 

Trying to create Rhino Brep from DSpolysurface causes dynamo/Revit to crash. I am currently attempting to convert 342 fairly simple geometries. When I operate on 50-60 geometries, it seems to work fine.

## What did you expect to see?

(Fill in here)

## What did you see instead?

Crash - see thread on Dynamo forum for more info on the issue and files for review [https://forum.dynamobim.com/t/rhynamo-crashes/14634?u=pierre_roberson]

**Comment by pierramo** [comment]
Ok, Thank you.

**Comment by ikeough** [comment]
Closing this, pending a response from the package maintainer. If it is found to be a problem with Dynamo, please re-open.
