### ISSUE TITLE
DYNAMO HAS CRASHED...ERROR I'VE NEVER SEEN...

### ISSUE THREAD

**Issue by ktseniedaoducnguyen** [DynamoDS/Dynamo#8180]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

DYNAMO 1.3.1

## Operating system

Windows 10

## What did you do? 

WHEN I OPEN DYNAMO, THERE HAS A NOTICE LIKE THIS
![dynamo error](https://user-images.githubusercontent.com/31981881/30470200-f365b686-9a1d-11e7-908e-6a5e7332e717.jpg)

## What did you expect to see?

PLEASE HELP ME TO FIX THIS ERROR

## What did you see instead?

(Fill in here)

**Comment by mjkkirschner** [comment]
we'll need to be able to see the first lines of that text box.

**Comment by QilongTang** [comment]
@ktseniedaoducnguyen Would you show us the top of callstack so we can work on the exception fix if you ever hit this again?

**Comment by smangarole** [comment]
@ktseniedaoducnguyen We have a new version of Dynamo 1.3.2. Please confirm if you can reproduce this issue with the latest version. If reproducible, please re-open with steps to reproduce and appropriate screenshots.
