### ISSUE TITLE
Dynamo cannot create Background Preview

### ISSUE THREAD

**Issue by Nainoor** [DynamoDS/Dynamo#8185]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1.1736

## Operating system

Windows 10

## What did you do? 

Created a line from two points.

## What did you expect to see?

A line in the background preview.

## What did you see instead?

Nothing

**Comment by mjkkirschner** [comment]
@Nainoor can you provide a screenshot, there are few failure modes and a screenshot will help us to provide the right solution.

**Comment by mcfetridgem** [comment]
I've been having the same issue. Screen shot attached of what I'm experiencing:
![capture](https://user-images.githubusercontent.com/19632288/30768449-ac4cc322-a05b-11e7-91d0-50b140eb50c5.PNG)

**Comment by mcfetridgem** [comment]
I'm running the exact same build version on Windows 10 also

**Comment by mjkkirschner** [comment]
@kronz @jnealb

**Comment by jnealb** [comment]
@Nainoor @mcfetridgem This may be a case of DYN-887 – “Dynamo install/upgrade process leads to disabled gfx rendering” - we recommend uninstalling all builds of Dynamo (using MSFT fixit to thoroughly clean the machine) and re-installing 1.3.

**Comment by kronz** [comment]
Real fix is to provide the full installer from the download site, a process which is underway.  Seems that there is an issue with the upgrade process that affects a non-trivial number of people!

**Comment by jnealb** [comment]
yes; we have a Forum post for the issue.

**Comment by mcfetridgem** [comment]
I installed the Dynamo Studio Installer on a fresh version of Windows 10 and encountered this issue. After installing the "update" on the Autodesk Desktop App the graphics issue was fixed. So it's working as expected for me now :)
