### ISSUE TITLE
Geometry.DoesIntersect still has bugs despite correct geometry working range

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#8203]
These issues have been closed but they are still a problem:

https://github.com/DynamoDS/Dynamo/issues/5681
https://github.com/DynamoDS/Dynamo/issues/5233

Refer attached file.

## Dynamo version

1.3 with Revit 2017.2

## Operating system

Windows 7

## What did you do? 

Using the geometry.DoesIntersect node returns unpredictable results even if working range is set correctly (Large).

## What did you expect to see?

Room boundary and intersecting spline to return that an intersection is present. It works on adjacent room boundaries.

## What did you see instead?

Node returns no intersection.

![dynamo error](https://user-images.githubusercontent.com/10913639/30789437-ec442202-a1e8-11e7-996a-5afeb4b3e73a.png)

**Comment by ParametricMonkey** [comment]
https://www.dropbox.com/sh/zpk4tlt5jjofp8l/AADq1ww-ieoCr-HFAytK5uNCa?dl=0

**Comment by mjkkirschner** [comment]
this should be fixed in upcoming product years - it's not something the Dynamo team can fix directly.

Will close this issue when we know the specifics of the fixed versions. @aparajit-pratap

**Comment by aparajit-pratap** [comment]
This might be fixed in ASM version226, alpha 13. We don't have enough data anymore to test this specific bug, however. Closing, unless we can get a graph to test this workflow with the latest ASM fixes.
