### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lukvbl** [DynamoDS/Dynamo#8229]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.3.1.1736
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
win 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

pres run

## What did you expect to see?

lines been cut on second line

## What did you see instead?

nothing error

**Comment by mjkkirschner** [comment]
@lukvbl this report does not contain enough information for us to help you. Please clarify and or attach sample files that reproduce your issue.

**Comment by mjkkirschner** [comment]
please reopen with more information.
