### ISSUE TITLE
Geometry not visible in Dynamo Studio 2017 1.3.1.1736

### ISSUE THREAD

**Issue by EENagel** [DynamoDS/Dynamo#8235]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Studio 2017 1.3.1.1736

## Operating system
 
Virtual Machine, Windows 7

## What did you do? 

I had Dynamo Studio 2017 installed on my virtual machine.

## What did you expect to see?

Geometry in the background / 3D plane after placing a geometry node in the graph.

## What did you see instead?

Nothing.  Geometry is not dispalying in the background / 3D plane.

**Comment by jnealb** [comment]
@EENagel Do you see the 3D grid or is it in 2D mode (looks like a 2D ruler)?

**Comment by EENagel** [comment]
Yes, I see the 3D grid.

**Comment by jnealb** [comment]
@EENagel The fix is to un-install all Dynamo versions (look for 1.1) using the Control Panel, remove all Dyn folders and re-install Studio 1.3. You may also have to use the Microsoft Fixit utility if this does not work.

**Comment by jnealb** [comment]
@EENagel Any progress?

**Comment by EENagel** [comment]
Nothing positive to report.  We tried uninstalling / re-installing Dynamo Studio with no luck.  Version of Studio: 1.3.1.1739

**Comment by jnealb** [comment]
@EENagel Would it be possible to remote into your machine to debug this?

**Comment by EENagel** [comment]
It might be possible.  My IT department would like to know if you work for Autodesk and/or the Dynamo development team.  Please note that I have CC’d my IT contact.

**Comment by jnealb** [comment]
Yes I do, QA Engineer on Dynamo.

**Comment by EENagel** [comment]
Neal,

We would like you to remote in and have a look at the issue we are facing with Dynamo Studio.  Casey, my IT contact, would like for you to remote into his virtual machine as he is having the exact same issue that I am having.  How do we go about doing that and is there a specific time that works for you?

Eric Nagel

**Comment by DanielHurtubise** [comment]
Morning Eric,
if it makes you (and IT) feel better i've done it to solve problems. It works like a charm but most importantly... Neal will sove your issue ;)

**Comment by jnealb** [comment]
@EENagel No pressure! Is Monday at 3:00pm EST possible? Do you use TeamViewer, or another tool for meetings?

**Comment by EENagel** [comment]
Monday works, so does TeamViewer.  Can we take the communication off the forum and email directly so that I can include my IT staff?

**Comment by jnealb** [comment]
Yes: neal.burnham@autodesk.com

**Comment by jnealb** [comment]
Another case of 1.x install/upgrade leading to the "no gfx" scenario. Uninstall all Dyn (1.2.2+1.3) followed by a Studio install cleared it.
