### ISSUE TITLE
Crash when manipulating list

### ISSUE THREAD

**Issue by ghost** [DynamoDS/Dynamo#8241]
## Dynamo version

1.3.1.1736

## Operating system

Windows 10

## What did you do? 

Connected the node "GetItemAtIndex" to a list generated with python

## What did you expect to see?

A list

## What did you see instead?

ERROR
![error](https://user-images.githubusercontent.com/11173543/31335070-9d6bf756-acf9-11e7-91ab-1c95055f65d0.PNG)

**Comment by jnealb** [comment]
@rhamati Is it possible for you to share your Dynamo graph and Python script with us?

**Comment by rhamati** [comment]
[zip.zip](https://github.com/DynamoDS/Dynamo/files/1371554/zip.zip)

**Comment by rhamati** [comment]
The dynamo script has a file path node, this needs to refer the xml file
