### ISSUE TITLE
Crash after open a Code Block

### ISSUE THREAD

**Issue by MTJ001** [DynamoDS/Dynamo#8267]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1.1736

## Operating system

Windows 7

## What did you do? 

Open a Code block

## What did you expect to see?

(Fill in here)

## What did you see instead?

![capture](https://user-images.githubusercontent.com/32869340/31667700-1e1a77c0-b348-11e7-8fdf-3bfe9fc6ddef.PNG)

**Comment by mjkkirschner** [comment]
Please try removing other addins from revit and packages from dynamo - it's likely some package or addin is referencing a different version of avalonedit dll. You can try searching for that dll.

What version of revit are you on?

**Comment by MTJ001** [comment]
Well, to be honest with you that issue has arisen when some packages were installed, so it was my first thought. I am running last version 1.3.1.1736.
Thank for the quick response.

**Comment by dimven** [comment]
Xceed is used in the UI++ package by @gytaco

**Comment by WhoaHorsey** [comment]
Okay, So I have the same exact problem... Same operating system, Same dynamo version, etc.  I deleted all my packages, tested both versions of dynamo (0.9.1.4062 and 1.3.1.1736).  I essentially can edit code blocks already in place (from tutorials and examples) but I cannot add a new one without instantly crashing dynamo and getting the same error MTJ001 originally received.

**Comment by WhoaHorsey** [comment]
Update... For me it was a revit add-in that was causing the conflict, not packages in dynamo.  If I figure out which one, I will add that to this discussion.

**Comment by MTJ001** [comment]
My issue came out after upgrade my Dynamo version and install Spring Nodes Package if this can help. Still dealing with this problem, I wonder if could be Dynamo updating.
