### ISSUE TITLE
Rhythm Package not working or cannot be found.

### ISSUE THREAD

**Issue by b-ardrey23** [DynamoDS/Dynamo#8268]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.0

## Operating system

Window 7

## What did you do? 

Try to install Rhythm Package into dynamo

## What did you expect to see?

Rhythm to appear

## What did you see instead?

Nothing Rhythm did not appear  dynamo nor did any of the nodes. Dynamo would have an update ready and crash

**Comment by mjkkirschner** [comment]
what other packages do you have installed?
what does the crash exception state?
Have you contacted the author of Rhythm?

**Comment by b-ardrey23** [comment]
for the other packages I have installed they are lunchbox, clockwork and spring nodes. After I try to install Rhythm is see a green cloud that says update ready. When I click on it states that I need to restart/close. Then is try to close but windows states that it did not close properly and check for solutions on online. As for contacting the author I have not yet.

**Comment by mjkkirschner** [comment]
There should be no update associated with Rhythm using the Dynamo update, so I see no reason to click that, seems like a possible incorrect notification there.

Can you attempt to uninstall the other packages temporarily and install Rhythm?

**Comment by mjkkirschner** [comment]
also please check the dynamo console for any messages about the rhythm library.

**Comment by sixtysecondrevit** [comment]
@b-ardrey23 did you get this resolved? Did you install from the package manager?

**Comment by b-ardrey23** [comment]
Yes is can be close I was able get this resolved thank you.
