### ISSUE TITLE
run radiance analysis

### ISSUE THREAD

**Issue by ghafourpour** [DynamoDS/Dynamo#8277]
![radiance](https://user-images.githubusercontent.com/32937673/31783908-bb332d52-b50c-11e7-8885-a9a24c5b26ff.jpg)

**Comment by SpencerMAQ** [comment]
You might want to post on the ladybug forum instead: http://discourse.ladybug.tools/

**Comment by mjkkirschner** [comment]
closing this as it deals with a specific package.
