### ISSUE TITLE
Cannot see the Nodes when opening Daynamo, and an error notifcation appears!

### ISSUE THREAD

**Issue by BassemAssad** [DynamoDS/Dynamo#8291]
## Dynamo version
Dynamo 1.3

## Operating system
Windows 10

## What did you do? 
When opening Dynamo, cannot see the nodes, and does not work

## What did you see instead?
Only wires, and nodes disappearing

![dynamo error](https://user-images.githubusercontent.com/33142383/32086640-67aa67d8-bb22-11e7-88b2-424adb99ea78.jpg)

**Comment by ramramps** [comment]
@BassemAssad Can you attach the graph here?

**Comment by BassemAssad** [comment]
https://user-images.githubusercontent.com/33142383/32086640-67aa67d8-bb22-11e7-88b2-424adb99ea78.jpg

**Comment by mjkkirschner** [comment]
the actual .dyn file if possible.

**Comment by johnpierson** [comment]
Closing this as we need more information. Please reopen and update if this is still an issue for you. Specifically, please upload the applicable DYN files
