### ISSUE TITLE
Library disappears when using Remote Desktop on 2.0

### ISSUE THREAD

**Issue by Dewb** [DynamoDS/Dynamo#8293]
## Dynamo version

Sandbox, Core 2.0.0.2821
(local build from master branch, commit d7162b261aa85026d99608dae54201d0bba68d53)

## Operating system

Windows 10

## What did you do? 

- Run Dynamo, open a workspace
- Connect to Win10 machine using Remote Desktop (from MacBook Pro running OSX)
- Click in library a couple of times
- Library disappears, region of screen goes black
- Go back to Win10 machine, unlock screen, library is visible again
- Click into library a couple of times, library goes black again

## What did you expect to see?

The library tree

## What did you see instead?

Not the library tree

**Comment by Dewb** [comment]
I deleted the `packages` folder before building the latest master, forcing a nuget package restore, in case that was the issue.

**Comment by mjkkirschner** [comment]
@Dewb this appears to be fixed in cef 57... too bad we can't use that. 😢

**Comment by mjkkirschner** [comment]
https://github.com/cefsharp/CefSharp/issues/1861

**Comment by kronz** [comment]
@mjkkirschner with the recent change in CEF, is this now fixed?  https://github.com/DynamoDS/Dynamo/commit/735e32eb15bfcd6175bf57004fafc0b8ae721c46

**Comment by mjkkirschner** [comment]
untested- but potentially!

**Comment by jnealb** [comment]
@kronz @mjkkirschner Tested with D4R 2.0.0.4016: works fine with Win10 running Revit 2018.3
