### ISSUE TITLE
"Ghosting" in Library search

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8296]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Latest 2.0.0.2995/2996
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Win 7

## What did you do? 

Search for nodes in library

## What did you expect to see?

former searches going away after deleting search text

## What did you see instead?

ghosting. as in former search results still showing up in library.
![image](https://user-images.githubusercontent.com/7080648/32217052-12750f7c-be27-11e7-9cc5-ae915e0c8f9f.png)

Goes away if I open something up that "overwrites" that part of the screen.

**Comment by QilongTang** [comment]
FYI: @Racel @kronz

**Comment by Racel** [comment]
@QilongTang - Can you please file this in jira?

@josols - Thanks for testing out the latest daily build! What version of Revit are you using? And what version of windows?

**Comment by QilongTang** [comment]
Tracked internally as [QNTM-2532](https://jira.autodesk.com/browse/QNTM-2532)

**Comment by josols** [comment]
This was in Revit 2018.1. When I resize the panel the ghosting disappears.

**Comment by smangarole** [comment]
@josols - I was not able to reproduce this issue. Can you provide me with reliable steps to reproduce?

**Comment by smangarole** [comment]
@josols - I was not able to reproduce this issue. If you encounter this behavior again, please reopen with reliable steps to reproduce. Thanks.
