### ISSUE TITLE
Deleting Python node while Python editor is open

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8297]
## Dynamo version

2.0.0.2995/2996

## Operating system

WIn7

## What did you do? 

Double clicked Python editor, editor opens, new behaviour lets you "roam" freely in dynamo canvas while python editor is open AND even lets me delete the Python node itself. Trying then to Save Changes in editor crashes dynamo with "UpdateModelValue: Model not found"

## What did you expect to see?

some warning that this can't be done while editor is opened

## What did you see instead?

no warning.

**Comment by QilongTang** [comment]
FYI: @Dewb @Racel

**Comment by Racel** [comment]
@Dewb - can you take a look at this?
@QilongTang - Can you please file a task in jira for this?

**Comment by QilongTang** [comment]
Tracked internally as [QNTM-2533](https://jira.autodesk.com/browse/QNTM-2533)

**Comment by mjkkirschner** [comment]
I believe this has been fixed.

**Comment by Dewb** [comment]
Fixed in #8295.
