### ISSUE TITLE
Returning BaseType throws Exception

### ISSUE THREAD

**Issue by moethu** [DynamoDS/Dynamo#8298]
Hi Guys, this is an issue / wish for returning objects converted to their base type if somehow possible. Maybe there is another way to do this, but I wasn't able to find it. Please see below.

## What did you do? 
Created a Node in C# and returned an object converted to its base type. I have an object of type LoadPattern which inherits an abstract class "Element". Now instead of Type LoadPattern, I want to return Type "Element". Which is the LoadPatterns BaseType.

## What did you expect to see?
No Exception

## What did you see instead?
An Exception saying "Asked to convert non-convertible types" which is not true. The returned element Type LoadPattern does inherit Type Element which is therefore convertible.

## Dynamo version
1.3

## Operating system
Windows 7

![image](https://user-images.githubusercontent.com/8201465/32235162-0385d9d2-be5f-11e7-9352-836bb3d080be.png)

**Comment by mjkkirschner** [comment]
Can you share your source here?

**Comment by moethu** [comment]
Hi @mjkkirschner , sadly not.. would have to create a similar structure or I'm just setting up a quick screenshare session

**Comment by mjkkirschner** [comment]
@aparajit-pratap does this have to do with element being abstract?

**Comment by moethu** [comment]
@aparajit-pratap my object is of a class which inherits an abstract class. For some, not all, classes inheriting the same abstract I get this issue. Didn't find any common property causing it. But it seems odd because I'm using the same core implementation in many other applications.

**Comment by moethu** [comment]
@aparajit-pratap this images describes it a bit better. The abstract classes loading element and datum element do not contain any implementation, they are strictly for organizational purposes.
![image](https://user-images.githubusercontent.com/8201465/35221194-91c04024-ff79-11e7-9d33-dcb2d0582ef6.png)

**Comment by mjkkirschner** [comment]
@moethu are you able to test this in 2.0?
Also is there any difference between your loadPattern class and Grid for example?

**Comment by moethu** [comment]
@mjkkirschner thanks, will test 2.0 first

**Comment by moethu** [comment]
@mjkkirschner same in 2.0, yes there is a difference between classes (grid and loadpattern) but they are marginal. And all classes are derived from "element". Any idea?
![image](https://user-images.githubusercontent.com/8201465/36382422-21e0675e-1589-11e8-8ad8-b9e2bc9a2659.png)

**Comment by mjkkirschner** [comment]
@moethu unfortunately no. I think to be helpful I will need a sample project which reproduces this so I can eliminate some unknowns. Could you provide that? Does not need to be your actual source, just a demo project.

**Comment by aparajit-pratap** [comment]
@moethu we have recently fixed a regression related to class inheritance and polymorphism in DesignScript in Dynamo 2.0. It would be great if you could use the latest daily build and see if you can reproduce this issue and let us know. Thank you.

**Comment by moethu** [comment]
Thanks, I will test this. so far I used a workaround returning only type object for all my nodes as output and input and then casting it - but this adds a lot of redundant code.

**Comment by moethu** [comment]
John, thanks for looking into this. Since I’m using a very very ugly workaround I do not experience the issue at the moment. And sadly I don’t have any Windows Installation running. Maybe someone else can check if this is still an issue? If not I’ll try to get a VM

Enviado desde mi iPhone

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
