### ISSUE TITLE
Performing a new search in library structured view

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8302]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0.2995/2996

## Operating system

Win7

## What did you do? 

Search for something in the library, switched to Structured View, and tried searching for something else

## What did you expect to see?

The search to update.

## What did you see instead?

Nothing happens, even when pressing enter.
In image example, I first searched for line, then switched to Structured view and then searched for polysurface:
![image](https://user-images.githubusercontent.com/7080648/32264329-8258b516-bede-11e7-8d92-502d4d5014b7.png)

**Comment by ramramps** [comment]
Tracked here : https://jira.autodesk.com/browse/QNTM-2568

**Comment by Racel** [comment]
We are getting rid of this experimental view. https://jira.autodesk.com/browse/QNTM-2464

**Comment by mjkkirschner** [comment]
removed this view.
