### ISSUE TITLE
Preview Upstream

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8315]
## Dynamo version
2.0.0

## Operating system
Windows

## What did you do? 
Wanted to limit visibility of graphics in Watch 3D node

## What did you expect to see?
_Preview Upstream_ in the node right click menu

## What did you see instead?
No such option anymore

**Comment by QilongTang** [comment]
@vykrum Please check out our release note for daily builds here at http://dynamobim.org/resuming-pre-release-builds/, `Preview Upstream` is deprecated

**Comment by vykrum** [comment]
@QilongTang So Dynamo lost the ability to do something like this? ....
![previewupstream](https://user-images.githubusercontent.com/5621624/32411197-6248c908-c1fb-11e7-8f5f-fa837c038ad9.png)

**Comment by mjkkirschner** [comment]
@QilongTang @Racel I think we need another discussion around this - it looks like the current implementation turning regular preview on and off also effects all downstream watch3d nodes, making them useless for isolating geometry.

I think we need to investigate if we can turn preview off for a specific node - for instance, a point.byCoorinates() node, but then when attaching a watch3d, the points should still show up in that watch3d node. This does not currently happen and is not what we discussed when we talked about removal of previewUpstream. Either it's a change in behavior or we had a misunderstanding of the previous behavior.

**Comment by mjkkirschner** [comment]
Also, codeblocks have odd behavior in my opinion when using watch 3d nodes - the entire codeblock output value is displayed, but I would assume just the port actually plugged into the watch3d node would be displayed - even when using an intermediate node.

**Comment by mjkkirschner** [comment]
tracked:
https://jira.autodesk.com/browse/QNTM-2631
most likely will not bring preview upstream back but modify watch3d behavior to make it unnecessary.

**Comment by vykrum** [comment]
@mjkkirschner _Preview Upstream_, in any case was relevant only while using _Watch 3D_, so makes sense modifying _Watch 3D_ instead of having _Preview Upstream_ on every node.

While _Watch 3D_ probbly isn't used much anymore, since we now have Background Preview, it is still needed to capture graphics with _Export Workspace As Image_
