### ISSUE TITLE
List in CodeBlock

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8316]
## Dynamo version
2.0.0

## Operating system
Windows 10

## What did you do? 
Typed _List_ in a Code Block

## What did you expect to see?
Dynamo to assume, by default, _DSCore.List_ (where else, if not Dynamo?)

## What did you see instead?
The images below should hopefully outline the trouble in doing something that should be extremely simple. Also, if this is how it is to be, besides making code seem overly complicated, will be a serious pain when old Design Script definitions need to be upgraded.
![list-1](https://user-images.githubusercontent.com/5621624/32405327-3c1a7adc-c189-11e7-969a-842933e16fe7.png)
![list-2](https://user-images.githubusercontent.com/5621624/32405328-3e5075fe-c189-11e7-99b7-96813f59f5a0.png)
![list-3](https://user-images.githubusercontent.com/5621624/32405330-40814fce-c189-11e7-943c-794337661dce.png)
![list-4](https://user-images.githubusercontent.com/5621624/32405331-42a986d6-c189-11e7-9b4b-9bd46576fed3.png)
![list-5](https://user-images.githubusercontent.com/5621624/32405332-448b7130-c189-11e7-98b9-3937e33bff55.png)

**Comment by mjkkirschner** [comment]
@vykrum do you have other packages installed which replace List?
@QilongTang @aparajit-pratap it seems the element resolver is not doing its job here.

**Comment by mjkkirschner** [comment]
https://jira.autodesk.com/browse/QNTM-2633

**Comment by QilongTang** [comment]
@mjkkirschner Thanks for logging it. ElementResolver is actually serialized and deserialized

**Comment by aparajit-pratap** [comment]
@mjkkirschner thanks, I think there's already an existing issue I'm aware of that's related: https://jira.autodesk.com/browse/QNTM-2117

**Comment by mjkkirschner** [comment]
@vykrum @andydandy74 @josols do you only see this behavior with lists methods?

**Comment by vykrum** [comment]
@mjkkirschner Packages installed....
![list-6](https://user-images.githubusercontent.com/5621624/32474939-56134366-c395-11e7-89bc-86900fea9b27.jpg)
Steel Select and Testing Waters have Design Script custom nodes
None caused any trouble earlier.

**Comment by mjkkirschner** [comment]
@vykrum this should now be fixed.

**Comment by mjkkirschner** [comment]
please reopen if this still occurs.
