### ISSUE TITLE
[Dynamo 2.0] Open in Manual Execution Mode is ignored

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#8318]
## Dynamo version

2.0.0.2976

## Operating system

Windows 7

## What did you do? 
use the open command with "Manual Execution Mode" checked

## What did you expect to see?

The graph opened in manual mode

## What did you see instead?

The graph opened in automatic mode and shortly after that froze :)

**Comment by mjkkirschner** [comment]
Was this through the ui or through code ? And can you upload the file?

**Comment by dimven** [comment]
Through the UI. You can try that with any file. For example:

[8318.txt](https://github.com/DynamoDS/Dynamo/files/1446154/8318.txt)

(rename to *.dyn)

**Comment by mjkkirschner** [comment]
https://jira.autodesk.com/browse/QNTM-2632

**Comment by smangarole** [comment]
Fixed in `DynamoRevit2.0.0.20171115T1013.exe` found on dynamobuilds.com
