### ISSUE TITLE
Conditional Statements Not Handling True Values

### ISSUE THREAD

**Issue by nboyts** [DynamoDS/Dynamo#8320]
## Dynamo version

1.3.1 
(Haven't been able to check other versions yet.)

## Operating system

Windows 10 Enterprise

## What did you do? 

Convert strings (or other objects) to booleans with conditional statements.
(And vice versa when converting booleans to other objects.)

See forum discussion here: https://forum.dynamobim.com/t/converting-text-to-boolean/16271/7

## What did you expect to see?

When checking a true value (boolean) against a false conditional statement the output would be _false_.

## What did you see instead?

When checking a true value against any conditional statement, the object always returned _true_, even when the statement was false.

(The conditional statement would still return _Empty List_, _null_, and _false_ when checking against those respective objects.)

**Comment by mjkkirschner** [comment]
@aparajit-pratap FYI, this seems like a bug.

**Comment by mjkkirschner** [comment]
@nboyts is your report here specific to `replaceByCondition` node?

**Comment by mjkkirschner** [comment]
@nboyts any chance you have had time to check 2.0?

**Comment by aparajit-pratap** [comment]
@nboyts there are certain type conversion rules that are built in to the language in Dynamo. When strings are converted into boolean values, the following rules apply:

An empty string is equivalent to a Boolean ‘false’
A non-empty string is equivalent to a Boolean ‘true’

![image](https://user-images.githubusercontent.com/5710686/35024710-10b3bfe2-fb0f-11e7-9405-a7ac6e6e0fec.png)

I hope this answers your questions. I'm closing this issue for now.
