### ISSUE TITLE
Parameter value when point not on curve

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8337]
## Dynamo version
1.3.2 and 2.0.0

## Operating system
Windows 10

## What did you do? 
![parameteratpoint](https://user-images.githubusercontent.com/5621624/32699711-1a77b112-c7e0-11e7-8e79-b9f8decbcd57.png)

## What did you expect to see?
Empty list or null or error

## What did you see instead?
A value that doesn't make sense

**Comment by jnealb** [comment]
@vykrum Thank you; this is tracked with QNTM-2793.

**Comment by kronz** [comment]
Pretty sure this would require all such operations to do a boolean "doesIntersect" on the curves, no?  That would be hella slow.
