### ISSUE TITLE
Improvement: Copy Packages to local location if source location is on a network

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8348]
## Dynamo version

1.3.1

## Operating system

Win 10

## Improvement Suggestion

Deploying Dynamo company-wide with a centralised location on the network for packages creates well known admin problems (namely, the dll's become read-only which prevents upgrades or deletion). 

I'm finding that in large organisations, its impractical to ask all users to close down Dynamo and Revit so changes can be made to the package folder, which leaves administrators high-and-dry if someone has forgot to close down the applications before leaving the office or if package upgrades need to be performed during working hours.

I would therefore like to make a suggestion to improve this which would involve Dynamo automatically copying package files to a local location every time its launched if the packages are derived from a network location. Maybe this can be a simple property admins can set in the users Dynamo XML preferences file, so it is manually set rather than having to change the behaviour of the application wholesale and potentially introducing a new set of problems.

**Comment by DanielHurtubise** [comment]
We have a script that does that. 
I'd rather have the Dynamo team focus on Dynamo issues/improvements then dealing with network deployment honestly.
Basically we compare network content with local content and update as required on startup. Never had any problem with that process. (It's the same for Revit's AddIns btw)

**Comment by DanBoghean** [comment]
Daniel,

Any chance you could give me some insight on how that script is created? I would love to set that up for my firm, but I'm not sure I can figure it out quite yet.

Thanks!

**Comment by DanielHurtubise** [comment]
Here's a quick one to copy locally adddins. You can derive one for Dynamo with it :)

del C:\ProgramData\Autodesk\Revit\Addins\2018\filter.*
    xcopy /Y "\\Server\Folder\*.*" "C:\ProgramData\Autodesk\Revit\Addins\2018"

**Comment by DanBoghean** [comment]
Thanks, Daniel.

I'm wondering how you run this script at startup? Do you bundle it as part of the Revit shortcut?

**Comment by DanielHurtubise** [comment]
Just part of the login script. Totally Windows driven, nothing Autodesk related :)

**Comment by jnealb** [comment]
:+1:
