### ISSUE TITLE
No background preview anymore

### ISSUE THREAD

**Issue by T-Lueks** [DynamoDS/Dynamo#8379]
Dynamo version:    1.3.2.2480
Operating system:    Windows 8.1

Dear people of Dynamo, I am experiencing a issue with my background preview. I have made a script that produces a curve. As shown in the picture below, this works fine. The problem is  I can't see anything anymore in the background preview. It used to work just fine before. I tried zooming in and out, but there is nothing there. Watch 3D doesn't show anything either. I have the latest available version of Dynamo, I have updated my graphics card, and yes, I do have background preview turned on in the view settings. The preview within Revit works, but i don't like using that one. 

Can anyone help me?

With kind regards,

T. Lueks

![2017-12-05_0942](https://user-images.githubusercontent.com/28598380/33597766-b5342146-d9a0-11e7-9b44-c086661d2fd5.png)

**Comment by jnealb** [comment]
This is likely an installer issue on our side: can you please try un-installing all Dynamo components from the Control Panel and then re-install 1.3?

**Comment by abhishakee** [comment]
Reinstalled but still same problem.

**Comment by jnealb** [comment]
@T-Lueks Please see the email I sent you and let me know if you are still experiencing the issue.

**Comment by xinyuanlele** [comment]
I have the same problem

**Comment by T-Lueks** [comment]
I Fixed it by upgrading my GPU
