### ISSUE TITLE
ZeroTouch: 'ProtoCore.Exceptions.CompilerInternalException' on custom enum as input with default value

### ISSUE THREAD

**Issue by alvpickmans** [DynamoDS/Dynamo#8383]
## Dynamo version

Dynamo Core 1.3.0.875

## Operating system

Windows 10

## What did you do? 

I am improving a package I developed by creating a custom enum list of options to use as input for the constructor nodes instead of relying on integers. It works fine except if the method has the option argument with a default value.

"Working" sample code:
```
namespace Test
{
    public enum TestOptions
    {
        None,
        Option1,
        Option2
    }
    public class TestClass
    {
        public string testText { get; set; }
        internal  TestClass (string txt, TestOptions option )
        {
            testText = txt;
        }

        public static TestClass ByTextAndOption(string txt, TestOptions option)
        {
            return new TestClass(txt, option);
        }
    }
}
```

Failing sample code:
```
namespace Test
{
    public enum TestOptions
    {
        None,
        Option1,
        Option2
    }
    public class TestClass
    {
        public string testText { get; set; }
        internal  TestClass (string txt, TestOptions option )
        {
            testText = txt;
        }

        public static TestClass ByTextAndOption(string txt, TestOptions option = TestOptions.None) //here is where it has a default value
        {
            return new TestClass(txt, option);
        }
    }
}
```

## What did you expect to see?

Constructor node with option input with default value to be overriden if option is connected.
![image](https://user-images.githubusercontent.com/12413808/33692130-b80477ec-dae3-11e7-8fee-0b41055c0514.png)

## What did you see instead?

Dynamo is not even able to load the dll library, console message:
"_Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown_"

**Comment by mjkkirschner** [comment]
This is a known issue - you could try using a default argument attribute instead if you wish to create the type.

https://github.com/DynamoDS/Dynamo/blob/7e27f7fa4c99feaec8307787044fcd0ac243af12/src/Libraries/GeometryColor/GeometryColor.cs#L106

**Comment by alvpickmans** [comment]
Great, worked perfectly! Closing the issue.
