### ISSUE TITLE
Dynamo 2.0.0.3421 file crash

### ISSUE THREAD

**Issue by afandianzo** [DynamoDS/Dynamo#8395]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0.0.3421
## Operating system
Windows 10
## What did you do? 
I preview on (NurbsCurve.ByPoints) node while I was doing simple waves with (sin, cos, tan......)
## What did you expect to see?
a curve
## What did you see instead?
the file crashed

**Comment by mjkkirschner** [comment]
@afandianzo we'll need the stacktrace or file to be able to help here.

**Comment by mjkkirschner** [comment]
@afandianzo have you seen this crash again?

**Comment by afandianzo** [comment]
No I did not because I am using different version since I had the problem

**Comment by jnealb** [comment]
Closing, @afandianzo please re-open if this re-occurs for you.
