### ISSUE TITLE
Dynamo graph doesn’t execute unless zoomed in/out

### ISSUE THREAD

**Issue by jovillarroelb** [DynamoDS/Dynamo#8402]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2 - Revit 2017.2

## Operating system

Windows 10 Pro

## What did you do? 

Updated to the latest stable version of Dynamo.

## What did you expect to see?

To work as usual, smoothly.

## What did you see instead?

The global behavior of the program decreased quite noticeable. When I work in Manual, for the program to run the script or more exactly to DO something I have to scroll the mouse wheel. If not, it stills at “Run Started”.

![f41e8e08a6bcf0eacdf2398015d0c665e6b7223b_1_512x500](https://user-images.githubusercontent.com/20558436/34009668-e94d5158-e0f0-11e7-9de4-7dd253b2b1a6.gif)

**Comment by mjkkirschner** [comment]
are you running with a HDPI screen with scaling enabled?

**Comment by jovillarroelb** [comment]
Hi @mjkkirschner, sorry my ignorance but can you explain me please what do you mean with "HDPI screen with scaling enabled"?

**Comment by jovillarroelb** [comment]
An update of the issue. The same Dynamo is working just fine in Revit 2016 and Revit 2018. ¿Any Ideas?

Cheers

**Comment by jovillarroelb** [comment]
Hi @mjkkirschner. In response to "HDPI screen with scaling enabled",  I'm running with two monitors and the scaling to 100%. Is this what you mean? Thanks
