### ISSUE TITLE
Improvement suggestion: 2D lists with empty sublists triggers "Dereferencing a non-pointer" exception

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8411]
## Dynamo version

1.3.2

## Operating system

Win 10

## Improvement Suggestion

I found that any 'property' node will throw an exception if a 2D list is input where the sublists contain both objects and sublists that are empty. The solution is to remove the empty sublists or flatten the list, but its not immediately obvious to users and could easily be bypassed with a better implementation in Dynamos VM. 

For example, BimorphNodes Element.IntersectsElement, or Element.IntersectsSolid output lists of this strucutre to enable the user to understand if there are any clashes. If no clashes are found, empty sublists are returned to indicate 'no clashes'. If clashes are found, the sublists are populated with the clashing elements. Maintaining the data structure is very important to enable the user to ascertain where the clashes are located, so avoiding this problem via the node itself is not an option. If the output is connected to, say, Element.Solids node, the exception is thrown. If the list is flattened or the empty sublists removed, no exception is thrown and the expected behaviour is observed (nulls where the sublists are empty). 

Can this behaviour be improved as it inhibits usability and creates an unnecessary abstraction to users (this issues is not specific to BimorphNodes for the record)?

I should add, creating methods which return the desired members (say, solids) is one solution, however this then screws up the library structure and 'shifts' the problem.

**Comment by aparajit-pratap** [comment]
@ThomasMahon is this exception thrown with a particular node or most nodes in general? Could you share a simple graph to demonstrate the workflow? Thanks!

**Comment by ThomasMahon** [comment]
@aparajit-pratap its any property node from any library. 

Here are some examples, example graph attached at the end. It seems to be null that causes the exception. I read on MSDN that if exceptions are expected with properties, make them methods instead, but that is clearly impractical:

**Autodesk.DesignScript.Geometry**
![image](https://user-images.githubusercontent.com/18601851/34529566-6385ea94-f0a4-11e7-9854-6e886c4758ee.png)

![image](https://user-images.githubusercontent.com/18601851/34529587-75089da2-f0a4-11e7-99c9-fcd15bd8ee8f.png)

[Example Dereferencing a non-pointer.zip](https://github.com/DynamoDS/Dynamo/files/1601031/Example.Dereferencing.a.non-pointer.zip)

**Revit.Elements**
![image](https://user-images.githubusercontent.com/18601851/34529733-dde8c0b8-f0a4-11e7-88b7-3ea02b344c98.png)

**BimorphNodes**
![image](https://user-images.githubusercontent.com/18601851/34529940-7522ab10-f0a5-11e7-8599-6e40ce76d936.png)

**Comment by ThomasMahon** [comment]
@aparajit-pratap also, look what happens if the first input contains an object, oddly, it works as expected:

![image](https://user-images.githubusercontent.com/18601851/34530176-359723f8-f0a6-11e7-93f3-b239ac86a4c6.png)

![image](https://user-images.githubusercontent.com/18601851/34530201-47a50ff6-f0a6-11e7-9b3d-2266ed0794d8.png)

![image](https://user-images.githubusercontent.com/18601851/34530225-5f7bfe1e-f0a6-11e7-96bf-144fd533ca43.png)

**Comment by andydandy74** [comment]
Looks similar to #5238

**Comment by aparajit-pratap** [comment]
Thanks @ThomasMahon. This issue was partly addressed for methods [here](https://github.com/DynamoDS/Dynamo/pull/7178) but unfortunately still persists for properties. We'll make a note of it but cannot promise a fix for 2.0.

**Comment by aparajit-pratap** [comment]
FYI @jnealb: https://jira.autodesk.com/browse/QNTM-3075

**Comment by ThomasMahon** [comment]
@aparajit-pratap thanks for the update. Any chance in the meantime you could update the exception message to provide the user with more instructions on how to resolve?

**Comment by reddyashish** [comment]
This is being fixed in 2.2 release.

**Comment by QilongTang** [comment]
@reddyashish Can you point to the PR and close this?

**Comment by aparajit-pratap** [comment]
Fixed in https://github.com/DynamoDS/Dynamo/pull/9578
