### ISSUE TITLE
Periodic runs cannot be called via designscript. 

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#8422]
## Dynamo version
Dynamo Core 1.3.2.2480
Dynamo Studio 1.3.0.946

## Operating system
WIndows 10 Enterprise

## What did you do? 
Trying to recreate an animation using a periodic run method utilizing only design script, so I added `DSCore.DateTime.Now;` to my code block, but this didn't allow for use of periodic runtimes. Adding the DateTime.Now node allowed for periodic runs, but the function called in my designscript node didn't update on subsequent runs.  

## What did you expect to see?
The same results as what was seen with a normal periodic run method - DateTime.Now would update the current time with each run allowing for sequential runs

## What did you see instead?
The version called via design script never updated, even after periodic updates were enabled, though the output of the node did.

**Comment by jnealb** [comment]
@JacobSmall Can you please check this with the daily 2.0 builds?

**Comment by mjkkirschner** [comment]
I don’t think this is a bug - periodic run mode is a node property not a function property- if you ran this ds code in some other ds interpreter it would be strange to me if this function started executing your program periodically.

The improvement here could be to enable periodic on codeblocks that contain functions which were imported as nodes with periodic ... might be possible.

**Comment by kronz** [comment]
Ya, I'm going to agree with @mjkkirschner that this isn't a bug . . . periodic update is really a special nodal functionality, like pickers etc . . . we could certainly do better around messaging and understanding how Periodic works and what nodes do and don't use it, but I don't see extending this to DS.
