### ISSUE TITLE
Nothing Showing on Background 3D after programming

### ISSUE THREAD

**Issue by aliahm08** [DynamoDS/Dynamo#8423]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.875

## Operating system

Windows 10 Enterprise

## What did you do? 

created a point.byCoordinates with three connected sliders to create a point at 0,0,0

## What did you expect to see?

a point at 0,0,0 in the view port

## What did you see instead?

nothing drawn/modelled in the view port.

**Comment by jnealb** [comment]
@aliahm08 Can you please try running the geometry samples under Help? Is there any geometry displayed?

**Comment by kronz** [comment]
I suspect this is the old Dual graphics card issue.  Please take a look at the Known Issues page, 2nd item here: https://github.com/DynamoDS/Dynamo/wiki/Known-Issues
If this doesn't solve the issue, please re-open
thanks
Z
