### ISSUE TITLE
Error in even move any node 

### ISSUE THREAD

**Issue by amirabehery** [DynamoDS/Dynamo#8430]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2

## Operating system
Windows 10

## What did you do? 

open script i don't finalize it yet

## What did you expect to see?
i was working on & suddenly it crashes , Sure no error.

## What did you see instead?

Unhandled error
![error](https://user-images.githubusercontent.com/34469908/34554383-7d80b318-f124-11e7-8aa3-7817d431bde9.PNG)

**Comment by aparajit-pratap** [comment]
@amirabehery could you specify in detail the steps you followed before you saw this crash. Are you able to reproduce it consistently?

**Comment by amirabehery** [comment]
thanks a lot I have solve the problem, Many thanks

**Comment by amirabehery** [comment]
about the steps nothing I do more than moving or deleting a node
the error solved after I erase all nodes that gives me warning or freeze & restart the file.
that's all

**Comment by aparajit-pratap** [comment]
@amirabehery I'm glad you were able to resolve the issue however, in an ideal case the crash should not occur in the first place. Since it will be hard to debug the issue without proper reproducible steps, I'm closing this for now. Thanks.
