### ISSUE TITLE
Error Opening Corrupted File

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8453]
## Dynamo version
DynamoRevit2.0.0.20180110T1645.exe

## Operating system
Windows 10

## What did you do? 
Attempted opening a file that was last worked on and saved in an earlier build.

Managed to open the same file on uninstalling this build and installing the previous build (Dynamo Core 2.0.0.3484 / DynamoRevit2.0.0.20171221T1208.exe )

## What did you expect to see?
The contents of the file

## What did you see instead?
![erroropeningcorruptedfile](https://user-images.githubusercontent.com/5621624/34811120-4ac714b6-f6c5-11e7-952e-4b2eb0347823.png)

**Comment by mjkkirschner** [comment]
Can you upload this file ?

**Comment by vykrum** [comment]
@mjkkirschner  Here is one file. But I had the same issue on trying to open a few other earlier versions of the file too
[Pattern.zip](https://github.com/DynamoDS/Dynamo/files/1622462/Pattern.zip)

**Comment by mjkkirschner** [comment]
@jnealb do you think you'll have a chance to look at this?

**Comment by jnealb** [comment]
@mjkkirschner Sure, @QilongTang and I are on a big sweep: let's get them all!

**Comment by mjkkirschner** [comment]
could be that this is some intermediate json format that does not the meet the spec or it could be a bug.

**Comment by jnealb** [comment]
@mjkkirschner @vykrum The file opens with an older build of 2.0:

![image](https://user-images.githubusercontent.com/9357222/34844132-70f460e4-f6de-11e7-9b8c-cec7e99fda46.png)

**Comment by vykrum** [comment]
@jnealb Two observations...
1. Files created on previous 2.0 builds do not open on this build(DynamoRevit2.0.0.20180110T1645), but do open when on reinstalling a previous build
2. However, files saved around Nov 16 (build could be older than the date mentioned, not sure) do open with this build (DynamoRevit2.0.0.20180110T1645)

**Comment by jnealb** [comment]
@vykrum @mjkkirschner @QilongTang @smangarole This is tracked with QNTM-3127.

**Comment by Aban6** [comment]
Hi,
I am using Revit 19 and Dynamo 2.0.1. When I try to reopen a Dynamo file, my Revit crashes. I have attached my Revit and Dynamo files here. Any help would be appreciated.

[Project1.zip](https://github.com/DynamoDS/Dynamo/files/2582135/Project1.zip)

Thanks

**Comment by QilongTang** [comment]
@Aban6 Your zip does not contain the custom nodes you were referring in the main dyn. As a result, I was able to open rvt and dyn without crash, would you update the zip file with all the content and we will try again.

**Comment by Aban6** [comment]
@QilongTang Thank you very much for your reply. It seems like something has gone wrong after installing some packages. I uninstalled them and it was fixed.
