### ISSUE TITLE
navigation menu abnormalities in 2.0

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#8464]
@mjkkirschner @kronz this is the issue I have mentioned on our call last week. When loaded a recent built from Revit2018 branch, this is what my library looks like: 

![image](https://user-images.githubusercontent.com/529781/34909007-bf02b760-f867-11e7-9323-7096598941e9.png)

All that Misc stuff is really just misplaced DynamoRevit stuff. We might be looking at an issue with the customization file. Can you look into it? 

## Dynamo version

2.0.0.3507

## Operating system

Win10

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by mjkkirschner** [comment]
@ksobon this one we have tracked and will deal with very soon.

**Comment by alfarok** [comment]
https://github.com/DynamoDS/librarie.js/pull/115
