### ISSUE TITLE
library generation and refresh

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#8467]
This might be my screen, computer only but the library appears glitchy.

![image](https://user-images.githubusercontent.com/529781/34909179-06cb18a6-f86a-11e7-9505-a98683c2b4ab.png)

This happens on multiple open/close of different sub-sections. Basically open a section like Revit, and keep it open, then open one above it like Math. It will cause the behavior. Sliding your mouse over it will cause the refresh and redraw of WPF and it all goes to normal, but that's not ideal. 

Also the actual act of generating the UI with all the icons and stuff is SLOW. It's not like super slow, but it's slow enough that you notice the glitch when all icons are being loaded. Perhaps some sort of compression would be needed for these images? Perhaps different size of the image should be loaded, and not always the same 128px one? Perhaps the full sub-category unfolding action on a single slick of top most category is a bad idea, as it's making "shallow" libraries like List or Math unfold ALL of their nodes and generate all of the icons. It's a bit too much for this thing to re-draw. 

@mjkkirschner @Racel @kronz 

## Dynamo version

2.0.0.3507

## Operating system

Win10

**Comment by mjkkirschner** [comment]
if this is running in debug mode, there might some really slow logging going on 0- but 100% agreed icon loading with cef from disk at the time of needing to display the icon is a bad idea. we should preload the icons. @Racel  @ramramps

**Comment by ksobon** [comment]
@mjkkirschner not in debug mode. Slow loading times are noticeable in regular Revit>Dynamo operation.

**Comment by ramramps** [comment]
@jnealb @smangarole can you check this as the first pass and log the defect? 
Also, @ksobon is the slow loading happening for the first time or everytime during refresh ? (ex: you search for the node, clearing the search etc).

**Comment by ksobon** [comment]
every time in refresh. it takes a while for the menus to get regenerated.

**Comment by jnealb** [comment]
@ksobon @mjkkirschner @kronz @smangarole  I am unable to reproduce this in preliminary testing with D4R 2.0.0.3766 on an i7 Dell laptop with an Nvidia card. Will continue to try.

**Comment by ksobon** [comment]
maybe because you actually have a graphics card. I don't. My laptop has a shitty integrated card. Either way, it should be able to handle menu in redraw in Dynamo.

**Comment by Racel** [comment]
@mjkkirschner Did we file a task to do the preload? Is this the correct approach and will it fix the issue?

**Comment by ramramps** [comment]
@ksobon is this still an issue with stable 2.0 release? We did some improvements to librarie after the version mentioned in the issue.

**Comment by ksobon** [comment]
@ramramps I think it has gotten better. I haven't noticed it lagging in 2.1. Thanks!
