### ISSUE TITLE
Custom nodes in mixed packages losing category assignment

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8477]
## Dynamo version

2.0.0.3483

## Operating system

Windows 10

## What did you do? 

Right-clicked on a custom node to edit its properties

## What did you expect to see?

* The custom node's category as specified in the *.dyf file
* Dynamo not changing the node's category without my knowledge/consent.

## What did you see instead?

Category was set to "Custom Nodes".

## Steps to reproduce

* Install package DynamoAutomation
* Place a custom node from the package on the canvas
* Right-click on placed node and choose "Edit Custom Node Properties"
* Notice how the category is set to "Custom Nodes"
* Exit dialog and notice how node was re-categorized in library

Note that this doesn't happen with any of the Clockwork nodes that I tried, so my theory is that this issue is limited to mixed packages (i.e. packages that include both ZT and custom nodes).

Before:
![grafik](https://user-images.githubusercontent.com/3014437/35144932-5290f558-fd06-11e7-953e-a248cb24aa68.png)
Edit dialog:
![grafik](https://user-images.githubusercontent.com/3014437/35145061-b39e1588-fd06-11e7-8312-22bd52dbbd8c.png)
After:
![grafik](https://user-images.githubusercontent.com/3014437/35145160-232f310c-fd07-11e7-8f2b-c5380e066778.png)

**Comment by mjkkirschner** [comment]
@alfarok @Racel this definitely seems like a confirmation of bugs in atleast part of the testing task around library addons.

**Comment by Racel** [comment]
Good catch @andydandy74! @QilongTang - have we filed this yet? I will file this as part of the testing task...

**Comment by jnealb** [comment]
@andydandy74 Not able to reproduce this with D4R 2.0.0.3934, the correct Category is shown 
![image](https://user-images.githubusercontent.com/9357222/35577847-77c48bfc-05b0-11e8-9c96-f1c5bc84460c.png)

**Comment by mjkkirschner** [comment]
@jnealb are you looking at packages that have both zt and custom nodes?

**Comment by jnealb** [comment]
@mjkkirschner Yes, the one that Andreas mentions: DynamoAutomation (1.3.4)

**Comment by jnealb** [comment]
Update: found a scenario where the Category gets erroneously reset to "Custom Nodes". Investigating.

**Comment by QilongTang** [comment]
PR: https://github.com/DynamoDS/Dynamo/pull/8592
