### ISSUE TITLE
Problems linking excel file.....

### ISSUE THREAD

**Issue by johaslak** [DynamoDS/Dynamo#8480]
Trying to import from Excel. Get the message: "Warning: Excel.ReadFromFile operation failed" when I try to link an Excel file. I use the same procedure as the sample shows, but it seems that the Excel.ReadFromFile node does not find the excel file in the file path. Using Dynamo Studio...

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by jnealb** [comment]
@johaslak Can you launch Excel on this machine? Is Microsoft Office licensed?

**Comment by johaslak** [comment]
Hi! Yes, I use Excel all the time. I have only problems with Dynamo. But, could it have something to do with my machine? Maybe some setups?
And one more thing; when I work in Revit, and use geometry to visualize the element i Dynamo. Like a wall. I appears VERY large on the screan. I seems that the workplane is infinately small. Shouldn’t it fit the workplane? It may be told that I work on a student Version of Revit…

John-Erik Aslaksen

Sendt fra E-post for Windows 10

Fra: Neal Burnham
Sendt: mandag 22. januar 2018 kl. 16.30
Til: DynamoDS/Dynamo
Kopi: johaslak; Mention
Emne: Re: [DynamoDS/Dynamo] Problems linking excel file..... (#8480)

@johaslak Can you launch Excel on this machine? Is Microsoft Office licensed?

**Comment by jnealb** [comment]
@johaslak Can you share your dyn graph with us?

**Comment by johnpierson** [comment]
Closing this for now. If this is still an issue for you, please provide a sample DYN, RVT and XLSX file.
