### ISSUE TITLE
[Bug] Dynamo Crashes when (mistakenly) trying to directly call DesignScript.Dictionary.Count

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8496]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0 Daily Build

## Operating system

Windows 10

## What did you do? 

So my auto-complete made this faux pas, but it still shouldn't cause a crash!

Please refer to attached image.

![dict_issue_01](https://user-images.githubusercontent.com/12857357/35457643-86a2ef24-02d1-11e8-9efb-a6bdc474b4f9.JPG)

## What did you expect to see?

Something not crashing Dynamo even if it was a typo.

## What did you see instead?

Dynamo crashing.

Additionally:

As a side note, there is a similar one when (Guessing) what to type into the SetValueAtKeys DesignScript equivalent as below:

![dict_issue_02](https://user-images.githubusercontent.com/12857357/35457681-a9485c8a-02d1-11e8-8518-323399c66f56.png)

Even if you correctly use the syntax of a direct call:

![dict_issue_03](https://user-images.githubusercontent.com/12857357/35457700-b9723cd4-02d1-11e8-81a8-57b74079a4e0.png)

**Comment by mjkkirschner** [comment]
@pboyer @aparajit-pratap

**Comment by aparajit-pratap** [comment]
This bug is being tracked here: https://jira.autodesk.com/browse/QNTM-3279

**Comment by mjkkirschner** [comment]
@aparajit-pratap should this be fixed in latest builds?

**Comment by jnealb** [comment]
@mjkkirschner @aparajit-pratap @Amoursol This is fixed in the latest daily builds.
