### ISSUE TITLE
[Feature Request] Can Dictionaries in DS work with List@Level and Replication?

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8498]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.0 Daily Build

## Operating system

Windows 10

## What did you do? 

In the following case, I simply wanted to make a 1 : 1 paring.

![dict_issue_06](https://user-images.githubusercontent.com/12857357/35457842-3186de32-02d2-11e8-85ec-15913991f478.png)

## What did you expect to see?

I expected it to allow me to do so.

## What did you see instead?

The image above.

**Comment by ramramps** [comment]
@Racel @aparajit-pratap

**Comment by mjkkirschner** [comment]
I think there was just a big discussion about this... @pboyer

**Comment by aparajit-pratap** [comment]
@Amoursol thanks for testing the new Dictionary feature and for your observations. We are currently not going to support arbitrary expressions for Dictionary keys and are also soon going to remove support for identifiers. That means Dictionaries will only support string constants as keys for now. 

This is to make the Dictionary initialization syntax simpler and more understandable in its usage. We may reconsider expanding the syntax to support arbitrary expressions in the future but we would like to start off simple as users can alternatively call into the equivalent zero touch method `Dictionary.ByKeysValues(keys : string[], values : object[])` from code blocks with which they can still use replication guides and list-at-level syntax, etc. if needed.

**Comment by kronz** [comment]
@Amoursol You can do what you are after like this
![2018-01-29_1419](https://user-images.githubusercontent.com/3456818/35529650-a6309bf4-04ff-11e8-8486-8e2da82145b4.png)
