### ISSUE TITLE
Internal Error, Please Report: Dereferencing a non-pointer. Element.GetParameterValueByName

### ISSUE THREAD

**Issue by donkalantjr** [DynamoDS/Dynamo#8504]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core: 1.3.2.2480
Dynamo Revit: 1.3.2.2480

## Operating system

Windows 7 Professional

Room.RenumberByModelCurve element

List is null
Internal Error, Please Report: Dereferencing a non-pointer

**Comment by donkalantjr** [comment]
![capture](https://user-images.githubusercontent.com/35933058/35531896-02112922-04fe-11e8-93c8-e3a66217cd43.png)

**Comment by donkalantjr** [comment]
![capture](https://user-images.githubusercontent.com/35933058/35531928-1ddb264e-04fe-11e8-8d01-eaa56cf22c98.png)

**Comment by mjkkirschner** [comment]
@donkalantjr in this case it looks like the custom node you are using is not returning any elements so all downstream methods are failing because null is passed to them. I think you'll need to ask the author of this node.

**Comment by donkalantjr** [comment]
All, it was an error with loading the clockwork package. The custom node "Room.GetNumberByModelCurve" was unable to load the clockwork package. I uninstalled and reinstalled and it works now. I just gotta make sure all of the correct packages are installed correctly.

**Comment by jnealb** [comment]
@donkalantjr Thank you for the debugging and update.
