### ISSUE TITLE
Can't create a code block - causes immediate crash!

### ISSUE THREAD

**Issue by basamyousif** [DynamoDS/Dynamo#8506]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 1.3 (latest as of Jan 2018)

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Win 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Can't create a code block - causes an immediate crash!

## What did you expect to see?

A code block :) 

## What did you see instead?

A crash and Dynamo shutting down

**Comment by jnealb** [comment]
@basamyousif Is this Dynamo for Revit?

**Comment by johnpierson** [comment]
@basamyousif, is this still an issue for you? If so can you provide additional information for us?

**Comment by johnpierson** [comment]
Going ahead and closing this as we need more information. If this is still an issue for you please feel free to reopen and supply more information/sample files.
