### ISSUE TITLE
Asked to convert non-convertable types

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8508]
## Dynamo version
2.0.0.3865

## Operating system
Windows 7

## What did you do? 
Updating 1.3.1 code to work with 2.0.0

## What did you expect to see?
An error free code block once when all expected geometry is generated

## What did you see instead?
![error20180130](https://user-images.githubusercontent.com/5621624/35544281-8a037e3e-058f-11e8-957a-0d5da39a7562.png)

Able to identify the line where the warning originates, but unable to find any issue (no nulls and output is as expected).

**Comment by mjkkirschner** [comment]
@aparajit-pratap thoughts?
@vykrum can you share the code?

**Comment by aparajit-pratap** [comment]
@vykrum so it sounds like you're pointing at a regression from 1.3? Could you describe a little more about what exactly were you trying to do or share the code in your code block? Were you calling a zero touch method from a package or simply using the geometry methods?

**Comment by vykrum** [comment]
This error, I realized,was on account of a rogue point in a list if Polygons. Was trying to get the center.
However, this error wasn't thrown on running the same definition in 1.3
