### ISSUE TITLE
Input port accepts multiple wires

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8510]
## Dynamo version
2.0.0.3865

## Operating system
Windows 7

## What did you do? 
Connected a new wire to an input port that was already wired

## What did you expect to see?
The new wire replaces the old wire

## What did you see instead?
The input port accepted multiple connections

![20180130-3](https://user-images.githubusercontent.com/5621624/35556853-729185a4-05c9-11e8-9140-474522df2d87.png)
On reopening the file only one wire retained.
However, Dynamo crashes on undoing actions before closing.

**Comment by mjkkirschner** [comment]
@vykrum I can't reproduce this yet. Can you try using the latest daily build? Did you need to do anything specific or this happens for every code block on your build?

I am on 2.0.0.3944 for reference.

**Comment by vykrum** [comment]
@mjkkirschner I actually wasn't even able to reproduce this on the same build on reopening the file. 
But seemed odd enough to merit reporting :-)

**Comment by Racel** [comment]
@jnealb - can you take a look to see if we can get reproducible steps? Without them, we may need to close temporarily.

**Comment by jnealb** [comment]
@Racel Sure.

**Comment by jnealb** [comment]
Can not reproduce with 2.0 daily build, @vykrum please re-open if you are able to.
