### ISSUE TITLE
Dynamo Studio No Geometry

### ISSUE THREAD

**Issue by mengelmn** [DynamoDS/Dynamo#8535]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.2480 

## Operating system

Windows 10

## What did you do? 

Open and Run Dynamo Studio

## What did you expect to see?

Geometry

## What did you see instead?

Background Grid

**Comment by ramramps** [comment]
@mengelmn can you please attach the file you are trying to run?
@jnealb fyi.

**Comment by mengelmn** [comment]
I believe the above bug is related to the previous reported and solved issue  https://github.com/DynamoDS/Dynamo/issues/7964

I have tried this solution as well, remove all dynamo installs and reinstall both Dynamo Revit and Dynamo Studio (from desktop app and download)  Have attempted in both orders of Studio then Revit and Revit then Studio.

Dynamo Sandbox runs fine and shows the background geometry, after and prior to each install.

**Comment by mjkkirschner** [comment]
@jnealb is there an installer download for this issue?

**Comment by jnealb** [comment]
@mengelmn Is it possible for us to remote into your machine?

**Comment by mengelmn** [comment]
@jnealb - as a final option, is there something specific

**Comment by jnealb** [comment]
@mengelmn given that you have tried the un-install all and re-install of Dynamo it seems like we may need to debug your machine

**Comment by mengelmn** [comment]
@jnealb send me a direct message and we can set something up.

**Comment by jnealb** [comment]
@mengelmn Please email me at neal.burnham@autodesk.com

**Comment by jnealb** [comment]
This is tracked with JIRA task DYN-887.

**Comment by mengelmn** [comment]
@jnealb @mjkkirschner   
For reference the current solution to the descibed graphic issue can be resolved by doing a full clean install of Dynamo Studio from the trial link https://www.autodesk.com/products/dynamo-studio/free-trial

**Comment by jnealb** [comment]
@mengelmn Thank you.

**Comment by kronz** [comment]
You can also run the update from the Autodesk Desktop App
![2018-02-13_1405](https://user-images.githubusercontent.com/3456818/36168387-ecb2ca66-10c6-11e8-8a68-e9513d0d3688.png)
