### ISSUE TITLE
Search nodes function freezes every keystroke

### ISSUE THREAD

**Issue by SZEBROW** [DynamoDS/Dynamo#8536]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo Core: 1.3.2.2480
Dynamo Revit: 1.3.2.2480
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 7 Professional
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Attempted to search nodes.  Dynamo freezes almost every keystroke.  Deleted most packages but still problem persists.  I have to wait 30+ seconds for a single keystroke to register.

## What did you expect to see?
Fast query of search results

## What did you see instead?
Painfully slow query of search results

**Comment by jnealb** [comment]
@SZEBROW Can you please try un-installing all versions of Dynamo (including any earlier folders etc) and re-installing Dynamo? We think this may clear the slow search.

**Comment by SZEBROW** [comment]
Thanks for the advice.  I wiped my HD clean of Dynamo, AND removed all packages.  Re-installed.  Same problem.  However, I think I have found the culprit.  The lag only occurs when I am working in a large model (local model that syncs to central).  When I open a small project, no lag....  Any suggestions?  Thanks.

**Comment by jnealb** [comment]
@kronz Any thoughts?

**Comment by kronz** [comment]
@jnealb Sounds similar to https://forum.dynamobim.com/t/lag-latency-dynamo-search-extremely-slow/18506/12

**Comment by jnealb** [comment]
@kronz Thanks.

**Comment by mjkkirschner** [comment]
@kronz is this something you can reproduce?

**Comment by SZEBROW** [comment]
Update to the issue.  I have acquired a new machine with a clean version of Revit 2017 and clean version Dynamo with no packages downloaded yet.  However, I am still having the same problems using the search function.

**Comment by kronz** [comment]
@mjkkirschner no, It doesn't happen on my machines.  @SZEBROW can you try using search with and without any network connections (completely disabling wifi and unplugging any network cables)?
