### ISSUE TITLE
Lacing Inconsistency

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8538]
## Dynamo version
2.0.0.3865

## Operating system
Windows 7

## What did you do? 
Changed Lacing from _Auto_ to _Shortest_

## What did you expect to see?
Similar behavior as _Auto_

## What did you see instead?
Works like _Longest_
![error-20180206-1](https://user-images.githubusercontent.com/5621624/35839733-0a53061c-0b18-11e8-975d-b43e65c47f21.png)

**Comment by mjkkirschner** [comment]
@Racel this seems correct to me, since there is only one input on this node - lacing between shortest and longest would be the same would it not?

**Comment by vykrum** [comment]
@mjkkirschner If this behavior is correct, then it has been wrong in all earlier versions :-)
Another example ...
In 1.3.2
![pointproject-13](https://user-images.githubusercontent.com/5621624/36438387-ceefe5ee-168f-11e8-89de-6355252d4e84.png)
In 2.0
![pointproject-20](https://user-images.githubusercontent.com/5621624/36438460-0096ffb0-1690-11e8-940c-553d36325607.png)

**Comment by mjkkirschner** [comment]
@vykrum @Racel can verify but I am pretty sure that previous behavior was actaully AUTO and now shortest is really shortest.

**Comment by vykrum** [comment]
@mjkkirschner Does that mean AUTO is something other than Shortest, Longest and Cross Product?

**Comment by vykrum** [comment]
Related issue, i think.
In the below screen shot, the last line of Flatten 1 and Flatten 2 should have the identical list structures, but they don't.
![error-20180221-1](https://user-images.githubusercontent.com/5621624/36464844-13990ef6-16f8-11e8-83d3-2fa65a7fd0e0.png)

**Comment by mjkkirschner** [comment]
@vykrum yes - AUTO is not any of the other lacing types.

**Comment by Racel** [comment]
@vykrum - @mjkkirschner is correct. But, we did check out your last screenshot. It looks like there may be some bug or weird behavior happening. 

Can you try and save your dyn and reopen it again in the latest daily build? We are concerned by the use of 'mstrPrint01' in the "Flatten 2" node. 'mstrPrint01' should not be callable in "Flatten 2". Can you recall how you created "Flatten2"? Did you copy and paste from the first code block?

If possible, please send us your dyn.

**Comment by vykrum** [comment]
@Racel I most likely did copy and paste from the first code block.
While I didn't retain a copy of the file, recreating the same on the latest build seemed to work fine.

**Comment by aparajit-pratap** [comment]
@vykrum I'm closing this for now. Let us know if you have any other questions.
