### ISSUE TITLE
Crashed  when i try to save my Dynamo file to document.

### ISSUE THREAD

**Issue by 123wangbiao** [DynamoDS/Dynamo#8539]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo1.3.2
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
 Windows 8.1
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
I pressed  "the button of  save" in the list of  document when i try to save my Dynamo work
(Fill in here)

## What did you expect to see?
Save my Dynamo work successfully
(Fill in here)

## What did you see instead?
My software has broke down(deadly error)
(Fill in here)

**Comment by jnealb** [comment]
@123wangbiao Can you please give us more detail: was this with Dynamo for Revit, your Dyn graph etc?

**Comment by johnpierson** [comment]
Going ahead and closing this as we need more information to investigate. If this is still an issue for you, please feel free to reopen and supply additional information or files.
