### ISSUE TITLE
Dynoma Player does not show up after launching it in Revit

### ISSUE THREAD

**Issue by ThomasBSmits** [DynamoDS/Dynamo#8548]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

1.2 & 1.3.1

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

Window 7

## What did you do? 

Trying to start Dynamo Player with Revit 2017.2 (C4R) project, but the dialog does not show up

## What did you expect to see?

Dynamo Player

## What did you see instead?

Nothing

**Comment by jnealb** [comment]
@kronz Ping

**Comment by kronz** [comment]
From development:
earlier versions of Dynamo were producing a crash in the headless mode when you tried to open a file and Dynamo created a backup for it (because the file was upgraded I guess) in a folder where the user didn't have write access.

That's 1 theory
The second is that somehow the dlls got messed up in the sense that a newwer version of our dll ended up somehow in the folder for an earlier version. For example the user copied because he wanted to have inputs in 2017
The third is that DynamoPlayer is off the screen somehow. The user put it in the right corber or something and then changed resolution and Player remembers last position
For the last one there should be a Player process active

**Comment by ThomasBSmits** [comment]
To eliminate the first two theories, I’ve fully unstalled Dynamo and Re-installed 1.3.

When I startup dynamo Player, there is a process in the background, but I can’t find the player anywhere:
[cid:image002.jpg@01D3AA5E.5B16E070]

Van: Zach Kron [mailto:notifications@github.com]
Verzonden: vrijdag 9 februari 2018 23:05
Aan: DynamoDS/Dynamo <Dynamo@noreply.github.com>
CC: Smits, Thomas <tsmits2@heijmans.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DynamoDS/Dynamo] Dynoma Player does not show up after launching it in Revit (#8548)


From development:
earlier versions of Dynamo were producing a crash in the headless mode when you tried to open a file and Dynamo created a backup for it (because the file was upgraded I guess) in a folder where the user didn't have write access.

That's 1 theory
The second is that somehow the dlls got messed up in the sense that a newwer version of our dll ended up somehow in the folder for an earlier version. For example the user copied because he wanted to have inputs in 2017
The third is that DynamoPlayer is off the screen somehow. The user put it in the right corber or something and then changed resolution and Player remembers last position
For the last one there should be a Player process active

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDynamoDS%2FDynamo%2Fissues%2F8548%23issuecomment-364582663&data=02%7C01%7Ctsmits2%40heijmans.nl%7C8389ab6c29f64023784408d57009301a%7C3d23df7613bc420b8520d9c146eed97b%7C0%7C0%7C636538107127429132&sdata=5IiNUzguXxYir9VKf6jJ9JZtyzUkznLKZZCJccYaBWI%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXHxY-O7fP9EDWAObqO1r-iRekfYvx_Dks5tTMEUgaJpZM4R_noN&data=02%7C01%7Ctsmits2%40heijmans.nl%7C8389ab6c29f64023784408d57009301a%7C3d23df7613bc420b8520d9c146eed97b%7C0%7C0%7C636538107127429132&sdata=AqJ5QCoXZAwen4y3BuvvzArPNtAWYumMT3bgYZC0hK4%3D&reserved=0>.


---
The information contained in this e-mail communication is solely intended for the person/legal person to whom it is/has been sent, and as it may contain information of a personal or confidential nature, it may not be made public by virtue of law, regulations or agreement. If someone other than the intended recipient should receive or come into possession of this e-mail communication, he/she will not be entitled to read, disseminate, disclose or duplicate it. If you are not the intended recipient, you are requested to inform Heijmans N.V. of this by telephone (phone number: +31 (0)73 543 51 11) immediately, and to destroy the original e-mail communication. Heijmans N.V. shall not be liable for the correct and complete transmission of the contents of a transmitted e-mail, or for any delay in its receipt.
This e-mail message does not create any contractual obligations for Heijmans N.V. Chamber of commerce 16004309.

**Comment by jnealb** [comment]
@ThomasBSmits Is this still happening for you?

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2148).
