### ISSUE TITLE
[Suggestion] Harmonize Get and Set Parameter node name

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8560]
## Dynamo version
2.0.0.4047
2.0.0.4074

## Operating system
Windows 10

## What did you do? 
Searched for _SetParameterValueByName_ and expected _**Element.SetParameterByName**_ to appear in the list of available node options

## What did you expect to see?
Suggestion: For consistency, either include or remove _**Value**_ in both the _Get_ and _Set_ node names

## What did you see instead? 
![parameternodes](https://user-images.githubusercontent.com/5621624/36133702-f8ac9bb0-10a5-11e8-8130-043eb72bc984.png)

**Comment by johnpierson** [comment]
Closing this as it is Revit related. If this is still a wishlist item for you please open on the correct repo. https://github.com/DynamoDS/DynamoRevit/issues
