### ISSUE TITLE
IronPython Distribution Method and Standard Library

### ISSUE THREAD

**Issue by AndersDeleuran** [DynamoDS/Dynamo#8561]
Hi All,

I started a thread on the Discourse forum regarding some concerns I have about the  Dynamo IronPython distribution method:

https://forum.dynamobim.com/t/distribute-revit-dynamo-with-the-iron-python-standard-library

Basically boiling down to:

1) The potential breakage of IronPython within other applications, due to the Dynamo system-wide install method of IronPython 2.7.

2) Why the path to the IronPython Standard Library _should_ be hard-coded within the available scripting environments (the Dynamo Python node specifically).

Best,

Anders (entirely new user that do not mean to pop in and make a fuss)

**Comment by AndersDeleuran** [comment]
A real-world example of Point 1 can be seen here:

https://github.com/ladybug-tools/ladybug-dynamo/issues/34

**Comment by AndersDeleuran** [comment]
Another example here:

https://discourse.mcneel.com/t/rhino-6-wip-grasshopper-python-does-not-load-os-module/37877/15?u=andersdeleuran

**Comment by steenblikrs** [comment]
Please fix this Autodesk!!

**Comment by mjkkirschner** [comment]
hi @steenblikrs 
regarding 1. we have some instructions here that might be useful for getting up and running - https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ#ironpython

In the longer term, we have added a task around these issues into our backlog for future versions of dynamo.

**Comment by mariamingallonMM** [comment]
Hello, 

Has this been resolved now? I seem to be running into similar issues when trying to use pandas from within the Python Script editor in Dynamo. While there are ways around it (manipulate csv using pandas outside Revit/Dynamo), it would be great to use pandas, numpy and many others from the Python Script editor directly. Please share any developments on this front. 

Thanks
Maria

**Comment by mjkkirschner** [comment]
I think this has been addressed in 2.1 release.
