### ISSUE TITLE
No 3D background 

### ISSUE THREAD

**Issue by debrajka** [DynamoDS/Dynamo#8563]
## Dynamo version

Studio 1.3.0.946

## Operating system

(10)

## What did you do? 

(regular work on project)

## What did you expect to see?

3d background

## What did you see instead?

blank background
![capture](https://user-images.githubusercontent.com/36441630/36145770-5f5c666a-10d8-11e8-8747-5420493c97ec.PNG)

**Comment by jnealb** [comment]
@debrajka Can you please un-install all of your Dynamo components and re-install, from the Control Panel (if you have any older folders like 1.2 or 1.1 please remove them)? If that does not fix it, please consult https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ for further suggestions on debugging this.

**Comment by jnealb** [comment]
@debrajka Is this still happening for you?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
