### ISSUE TITLE
Geometry unexpected behavior

### ISSUE THREAD

**Issue by ricardo7cordas** [DynamoDS/Dynamo#8579]
## Operating system

Windows 10 Pro
Version 1709
OS Build 16299.248

## What did you do? 

I'm trying to create a closed curve from several ways and all returned an unexpected results.

Note: **i'm using Extra Large geometry working range**

## What did you expect to see?

A closed curve by four points

## What did you see instead?

see images below.

![image](https://user-images.githubusercontent.com/14896455/36352923-62130908-149e-11e8-9a01-2679c9193f49.png)

![image](https://user-images.githubusercontent.com/14896455/36352928-6778c0fe-149e-11e8-9c6c-11539e4e97b0.png)

![image](https://user-images.githubusercontent.com/14896455/36352933-6e0a6aee-149e-11e8-9b4f-94c283287a7d.png)

![image](https://user-images.githubusercontent.com/14896455/36352934-738b4aec-149e-11e8-8430-afddff86d8bf.png)

![image](https://user-images.githubusercontent.com/14896455/36352967-e96b0eaa-149e-11e8-9fd5-169a14517c42.png)

**Comment by ricardo7cordas** [comment]
Another way fails


![2018-02-18_11-49-28](https://user-images.githubusercontent.com/14896455/36353282-417901a2-14a3-11e8-9574-3f070753f0f8.png)
![2018-02-18_11-49-21](https://user-images.githubusercontent.com/14896455/36353283-41904e8e-14a3-11e8-964d-22973d6fc63f.png)
![2018-02-18_11-49-05](https://user-images.githubusercontent.com/14896455/36353284-41edf41c-14a3-11e8-83b7-7f38021dad1f.png)
![2018-02-18_11-48-42](https://user-images.githubusercontent.com/14896455/36353285-42046e0e-14a3-11e8-8c5d-f6829f8e0ee7.png)

**Comment by ricardo7cordas** [comment]
The same code works fine with medium geometry working range

![image](https://user-images.githubusercontent.com/14896455/36355146-e8648094-14bd-11e8-9490-5df579ea20f0.png)

**Comment by mjkkirschner** [comment]
@aparajit-pratap this seems as designed to me. Please correct me if I am wrong and reopen if so.
