### ISSUE TITLE
attempting to load dynamo 1.3 package that references VariableInputNodeModel in 2.x crashes

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#8580]
this crashes on startup when the package is loaded.

**Comment by mjkkirschner** [comment]
this is particularly bad because we migrate 1.3 packages to 2.x package folder... maybe we should not do this.

**Comment by jnealb** [comment]
@mjkkirschner File it?

**Comment by mjkkirschner** [comment]
@jnealb please file it - we found it at the workshop - I think it might hit many users as we auto migrate 1.3 packages currently.

**Comment by mjkkirschner** [comment]
@QilongTang is this assigned to someone in this sprint?

**Comment by ramramps** [comment]
@jnealb @mjkkirschner Here is the task : https://jira.autodesk.com/browse/QNTM-3485
This is in F sprint. Yet to groom this one. So, no idea whether this is required for the release cut.

**Comment by mjkkirschner** [comment]
@kronz wanted this fixed and it only makes sense to fix for the release, so yes lets do it. @kronz please confirm.

**Comment by kronz** [comment]
@mjkkirschner @ramramps yes, please fix for the release.

**Comment by QilongTang** [comment]
@mjkkirschner On this, can you give an example of the package?

**Comment by mjkkirschner** [comment]
I would try loading archilab, or to replicate what was found at the workshop, make a node which inherits from VariableInputNodeModel.

**Comment by QilongTang** [comment]
https://github.com/DynamoDS/Dynamo/pull/8631
