### ISSUE TITLE
Nothing to background

### ISSUE THREAD

**Issue by mojtabajeem** [DynamoDS/Dynamo#8581]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Dynamo Studio 1.3)

## Operating system

(Windows10)

## What did you do? 

(Simple nodes to build and show the geometry)

## What did you expect to see?

(show the geometry)

## What did you see instead?

(NOTHING!)
.
.
.

![screenshot 205](https://user-images.githubusercontent.com/36623394/36372904-bee6a3aa-157b-11e8-822b-214e72bad960.png)

**Comment by jnealb** [comment]
@mojtabajeem Can you please un-install all of your Dynamo components and re-install, from the Control Panel (if you have any older folders like 1.2 or 1.1 please remove them)? If that does not fix it, please consult https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ for further suggestions on debugging this.

**Comment by mojtabajeem** [comment]
@jnealb   Thanks, I uninstall and install the product and deleted all files on "appdata folder" Twice! But it didn't work yet ... I decided to use your link.

**Comment by mjkkirschner** [comment]
@jnealb doesn't this require some installer fix or removal of studio? It looks like the grid is present but no other geometry.

**Comment by mjkkirschner** [comment]
@kronz do you recall this issue - studio and revit installer interaction weirdness?

**Comment by kronz** [comment]
@mojtabajeem can you try running the full installer from here:
https://www.autodesk.com/products/dynamo-studio/free-trial

**Comment by jnealb** [comment]
@mojtabajeem Is this still happening for you?

**Comment by mojtabajeem** [comment]
@jnealb @kronz   On my laptop, it doesn't fixed yet ... but on my PC it does install and work correctly ... several month ago, I install it on my laptop and it going correctly showing the geometry but One Day(!) it didn't show the geometry on my laptop until now ... I uninstall & install the product and remove that dynamo folder package Twice ... but the answer is No on my laptop.

**Comment by jnealb** [comment]
@mojtabajeem You may find some useful debugging help for this issue here: : https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by mojtabajeem** [comment]
@kronz  thanks Zach ... I downloaded online trial version of dynamo and it's gone work!
