### ISSUE TITLE
Dynamo v2.0 breaks [DefaultArgument("{}")] Attribute in ZT Nodes

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8604]
## Dynamo version

2.0

## Operating system

Win 10

## What did you do? 

Used a ZT node in Dynamo 2.0 which has a default argument using the DefaultArgument attribute.

## What did you expect to see?

An empty list as the default input

## What did you see instead?

![image](https://user-images.githubusercontent.com/18601851/36800581-c2729438-1ca7-11e8-941b-31a9e6c7ac13.png)

I assume this is caused by the seperation of lists and dictionaries in DesignScript v2.0 where curly brackets now define dictionaries and square brackets define lists.  If that is the case, what workarounds are there so users upgrading to Dynamo v2.0 and using Packages built on Dynamo builds before V2.0 don't experience this exception?

**Comment by ramramps** [comment]
@Racel @aparajit-pratap

**Comment by mjkkirschner** [comment]
a question for @pboyer.

**Comment by aparajit-pratap** [comment]
It looks like we need a migration strategy for `DefaultArgumentAttribute`s on ZT nodes. I do not think we have many such nodes but we cannot be sure of the number of packages that will be impacted. @kronz @Racel

**Comment by jnealb** [comment]
@aparajit-pratap Is there a JIRA task for this?

**Comment by ThomasMahon** [comment]
Would an overload added to the attribute method work? For example, create a secondary input with an enum defining versions, so the dev can specify the target version and this can simply be interpreted by Dynamo's VM at runtime? If the inputs don't include any version input, then it assumed to be built on versions of Dynamo prior to 2.0?

![image](https://user-images.githubusercontent.com/18601851/36907966-e21b9aa6-1e31-11e8-84b9-118988892ba6.png)

**Comment by Racel** [comment]
@ThomasMahon We currently do not intend to provide an automated migration for this for the Dynamo 2.0 release as we are low on bandwidth. We suggest that you update your package to be compatible with Dynamo 2.0 and instruct your users to download the new package.

We may revisit this in a later release. Closing for now.

**Comment by ThomasMahon** [comment]
@Racel booo! I might just use null instead and handle that within in my code. Its too much effort to manage different versions, especially given that custom packages are not monitized to cover development and maintenance costs...so I have to stick to one platform.
