### ISSUE TITLE
Package Manager broken: Screws up folder structure and deletes data from JSON file

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8606]
## Dynamo version

Dynamo 1.2

## Operating system

Win 10

## What did you do? 

Publish update to Dynamo Package via the Package Manager

## What did you expect to see?
An updated package adhering to the folder structure

## What did you see instead?

The folder structure is changed (the 'extra' folders dll's get copied to the bin folder (so they appear in both folders) and the XML description file gets put in extras even though it should be in the root directory, i.e. bin). 

The other annoying problem it has is wiping the node libraries property from the JSON file, so if the package is then downloaded after updating, nothing appears in the library, so I have to re-publish the package to fix it. This needs to be fixed as its been an ongoing issue now for months.

**Comment by mjkkirschner** [comment]
Hi @ThomasMahon, if you publish an update locally do you see the same behavior?

**Comment by ThomasMahon** [comment]
Hi @mjkkirschner yep, I get the same behavior publishing locally. Could it be caused by the dll's in my extra's folder being compiled with other versions of the Revit API and Package Manager thinking they are the primary package dll's and automatically moves the to the bin folder?

**Comment by mjkkirschner** [comment]
@ThomasMahon can you post a zip of your package including the json header file?

**Comment by ThomasMahon** [comment]
@mjkkirschner sure, as attached:

[BimorphNodes.zip](https://github.com/DynamoDS/Dynamo/files/1785935/BimorphNodes.zip)

**Comment by mjkkirschner** [comment]
@ThomasMahon so one thing to consider regarding the `node_libraries property`.

This array contains the fullName of the assembly including specific version - if you have updated your package to include a new version of this assembly (via incrementing the assembly version in visual studio) then the package is likely finding that the previously noted assembly is no longer present.

if you manually mark the new assembly as a nodeLibrary using the very hard to find right click on .dll context menu in the package manager client UI does that fix that particular issue?

**Comment by ThomasMahon** [comment]
Hi @mjkkirschner you are spot-on, that was the cause of the wiping of the parameter. If I right-click I can specify the up-versioned package dll and it publishes correctly. 

The issue of mixing the dll's from the extra folder still persists however.

**Comment by zagor-dmtr** [comment]
> @ThomasMahon so one thing to consider regarding the `node_libraries` property.
> 
> This array contains the fullName of the assembly including specific version - if you have updated your package to include a new version of this assembly (via incrementing the assembly version in visual studio) then the package is likely finding that the previously noted assembly is no longer present and removing it from the list. - As that version indeed might no longer be present.
> 
> if you manually mark the new assembly as a nodeLibrary using the very hard to find right click on .dll context menu in the package manager client UI does that fix that particular issue?

I published a new version, but it did not work for anyone, not even me. I spent a lot of time researching until I could solve this problem on my own. I came here to create a report on this problem and found this solution. It turns out that this problem was discussed more than a year ago! But finding this solution is impossible until you solve the problem yourself!

**Comment by ThomasMahon** [comment]
Yep its a pain in the arse. One recommendation that I now use: add your pkg.JSON to your Visual Studio project and when you up-version your assembly, ensure you update your JSON accordindly. I also increment the package version while I'm at it, so when I publish a new version via the package manager I have nothing to input (into its nasty dialog), simply upload and thats it.

**Comment by zagor-dmtr** [comment]
This is a great idea! Thank you! I will do the same.

**Comment by avidit** [comment]
Dynamo 3.0 now has option to retain folder structure while publishing package.
https://github.com/DynamoDS/Dynamo/pull/14880
