### ISSUE TITLE
cannot download and install MeshToolKit in Revit 2018

### ISSUE THREAD

**Issue by xiuchengyang** [DynamoDS/Dynamo#8608]
## Dynamo version

Revit 2018, Dynamo 1.2.2.373

## Operating system

Window 10

## What did you do? 

I cannot download and install MeshToolkit. I tried on different versions, 1.31., 1.2.0. 
<img width="349" alt="default" src="https://user-images.githubusercontent.com/29282366/36895302-bc372c10-1e0e-11e8-9cb4-0c1ce041d532.PNG">

Thanks very much for your advice about the possible problem.

**Comment by jnealb** [comment]
@xiuchengyang We are unable to reproduce this with Revit 2018.3 and Dynamo 1.3. Can you please take a look at the console and provide us with the full error message?

**Comment by mjkkirschner** [comment]
is this still a problem? Please reopen if it is with more information.
