### ISSUE TITLE
Create Sheet By Name Number Title Block And View not Functioning.

### ISSUE THREAD

**Issue by crwinchester** [DynamoDS/Dynamo#8610]
## Dynamo version

1.3.1

## Operating system

W10

## What did you do? 

Input Lists to Sheet.ByNameNumberTitleblcolAndView. All list lengths are the same but the node continually throws a warning and fails to function correctly. Additionally, I tried single item list inputs.

## What did you expect to see?

This node should have created all the sheets as input. Data are aligned and appear to be correct. 

## What did you see instead?

Warning: One or more of the input types are not matching. Couldn't find a version of ByNameNumberTitleBlockAndView that takes arguments of type (__array,__array,__array,__array)
![node problem](https://user-images.githubusercontent.com/29491492/36919324-ccd0e84a-1e54-11e8-9579-893938ee912a.PNG)

Warning: One or more of the input types are not matching. Couldn't find a version of ByNameNumberTitleBlockAndView that takes arguments of type (string,string,Revit.Elements.FamilyInstance,Revit.Elements.Views.FloorPlanView)
![node problem_02](https://user-images.githubusercontent.com/29491492/36919625-dcb5bca8-1e55-11e8-946e-fd165f58712b.PNG)

**Comment by mjkkirschner** [comment]
it appears you are passing family instances, but you need to pass family types.

**Comment by mjkkirschner** [comment]
please reopen if are still encountering this issue after using family types.
