### ISSUE TITLE
Dynamo 2.0 Library Panel missing

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8627]
## Dynamo version

2.0.0.4297

## Operating system

Win 10

## What did you do? 

Opened Dynamo 2.0

## What did you expect to see?

Operational application

## What did you see instead?

Library is missing with conflicts reported in the console. This issue is not fixed by re-installing and has also happened on another of my laptops. The solution so far has been to completely uninstall all Dynamo versions, remove any registry keys, then install afresh:

![image](https://user-images.githubusercontent.com/18601851/37155134-fdd45358-22d9-11e8-9e0d-e322415a38c7.png)

**Comment by mjkkirschner** [comment]
This appears to be revit 2018.2 - you can fix by removing pnid modeler for now from revit install location / addins

**Comment by ThomasMahon** [comment]
Thanks @mjkkirschner that appears to have fixed it
