### ISSUE TITLE
Can't hide library any more

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8632]
## Dynamo version

2.0.0.4297 (Sandbox)

## Operating system

Windows 10

## What did you do? 

Wanted to hide the library

## What did you expect to see?

A button or similar device

## What did you see instead?

Nothing

Dynamo 1.3.x:
![grafik](https://user-images.githubusercontent.com/3014437/37172786-15603d06-2312-11e8-9a0e-3acfda548fe8.png)
Dynamo 2:
![grafik](https://user-images.githubusercontent.com/3014437/37172767-0b27eeec-2312-11e8-867a-169c5bdbc4fe.png)
Am I missing something obvious here? I am fairly certain there was a control at the right hand side of the library in earlier 2.0 builds...

**Comment by alfarok** [comment]
Hey @andydandy74, the collapse arrow from 1.3 doesn't exist on the [new library](https://github.com/DynamoDS/librarie.js).  In 2.0 you can drag the library to collapse which will populate a button to expand it back out (or you can also drag it back).

![library_tab](https://user-images.githubusercontent.com/13341935/37174765-89cb8f74-22e5-11e8-97d6-c04b17f3b8d7.gif)

You can check out the related PRs [here](https://github.com/DynamoDS/Dynamo/pull/8521)

**Comment by andydandy74** [comment]
Oh well. I think the first version of the PR was better:
![grafik](https://user-images.githubusercontent.com/3014437/37176112-a7b02794-231b-11e8-8228-dba38def43e8.png)
Clicking to collapse seems simpler and faster than dragging.
On the bright side, Dynamo now remembers I collapsed the library so I only need to do it once and never worry about it again. :-)
