### ISSUE TITLE
2.0 CBN migration issue - unwanted input created

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8634]
## Dynamo version

2.0.0.4297

## Operating system

Windows 10

## What did you do? 

Review a 1.3 code block in 2.0

## What did you expect to see?

The code block having the same number of inputs as in 1.3

## What did you see instead?

![grafik](https://user-images.githubusercontent.com/3014437/37173627-67cf14b6-2314-11e8-8381-878672f891fd.png)

**Comment by ramramps** [comment]
@aparajit-pratap any thoughts?

**Comment by jnealb** [comment]
@ramramps Also: ping @ColinDayOrg. @mjkkirschner

**Comment by jnealb** [comment]
Thanks @andydandy74 - this is tracked with QNTM-3646.

**Comment by jnealb** [comment]
@andydandy74 The fix can be found in the latest daily builds.
