### ISSUE TITLE
Automatic renaming of custom nodes when editing multiple unsaved custom nodes

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8635]
## Dynamo version

2.0.0.4297

## Operating system

Windows 10

## What did you do? 

Created several custom nodes at once, then proceeded to save them

## What did you expect to see?

Custom node workspaces with the names I had orginally entered

## What did you see instead?

Custom node workspaces changing their names once Dynamo creates a backup file

## Steps to reproduce
Create two code blocks:
![step1](https://user-images.githubusercontent.com/3014437/37177931-399d12e8-2321-11e8-83c4-8768d70681fe.PNG)
Turn each one into a custom node:
![step2](https://user-images.githubusercontent.com/3014437/37177972-614f23da-2321-11e8-912d-aa424f5226a2.PNG)
Switch to the workspace of the first custom node:
![step3](https://user-images.githubusercontent.com/3014437/37178032-906a522a-2321-11e8-8847-3bc73033aa1b.PNG)
Wait a couple of seconds until Dynamo saves a backup file and notice how the node name changes:
![grafik](https://user-images.githubusercontent.com/3014437/37178105-c4910abc-2321-11e8-8ff5-80df6770a395.png)
When you switch back to the main workspace, this is what you end up with:
![grafik](https://user-images.githubusercontent.com/3014437/37178144-e5c4a036-2321-11e8-8b38-c42c15f673da.png)

So there are actually two undesirable things happening here:
1. Nodes changing names
2. Nodes being grouped under nodes in the library (see last image)

**Comment by QilongTang** [comment]
Addressed by https://github.com/DynamoDS/Dynamo/pull/8623 from @mjkkirschner

**Comment by QilongTang** [comment]
@jnealb @smangarole Would you close this when the internal Jira task also closed?

**Comment by andydandy74** [comment]
@QilongTang  - What about item 2:
![grafik](https://user-images.githubusercontent.com/3014437/37178464-e2db524c-2322-11e8-845d-72e49eeff7a6.png)

**Comment by mjkkirschner** [comment]
Number two is happening because of the rename to `.dyf` the . is used to create a new sub category.

**Comment by mjkkirschner** [comment]
please try the latest daily... probably tomorrow to see if this is fixed.

**Comment by mjkkirschner** [comment]
also @andydandy74 we really appreciate these issue posts. Thanks for checking out the latest builds.

**Comment by andydandy74** [comment]
@mjkkirschner - I can reproduce number two independently of this issue. 
![grafik](https://user-images.githubusercontent.com/3014437/37178977-696a1a7c-2324-11e8-9a54-360cfc929b75.png)

Obviously, it would be bad package design. But I think there should be a safeguard against it. Sample attached below. Try placing node ABC from the library... ;-)

[U.zip](https://github.com/DynamoDS/Dynamo/files/1794962/U.zip)

**Comment by mjkkirschner** [comment]
@andydandy74 but this issue (2) is not different from the other issue you are discussing with @alfarok is it?

**Comment by andydandy74** [comment]
It is, in that it creates a situation that was previously not possible: a category (ABC in this example) and a node occupying the same space in the library browser. Don't you think in this example there should be a placeable node (ABC) and a category (ABC) that contains the second node (ABC.DEF)?
Here's how the same thing would look in 1.3:
![grafik](https://user-images.githubusercontent.com/3014437/37180639-15c6b5b4-232a-11e8-9924-1e46aa15d5a8.png)

**Comment by mjkkirschner** [comment]
ah okay so you are saying that you have a category which is also a custom node - can you actually add this custom node?

@alfarok @ramramps ....

**Comment by alfarok** [comment]
You should be able to add a custom node that has the same name as a category.  Or are they created simultaneously?  Not sure if I fully understand the issue

![cn](https://user-images.githubusercontent.com/13341935/37184888-949ef690-230b-11e8-9264-f632bde07810.gif)

**Comment by andydandy74** [comment]
Please just open the ZIP file attached above (https://github.com/DynamoDS/Dynamo/files/1794962/U.zip) and put those two nodes in your library. 
You will see that one of them behaves like a category which I thnk it shouldn't.

**Comment by alfarok** [comment]
Thanks @andydandy74, digging into it now

**Comment by alfarok** [comment]
Tracking the custome node Category/Name collision with [QNTM-3653](https://jira.autodesk.com/browse/QNTM-3653)

**Comment by jnealb** [comment]
@andydandy74  The Custom Node renaming issues are fixed in the daily builds.

**Comment by alfarok** [comment]
@jnealb The 2nd issue discussed here filed under QNTM-3653 is not yet resolved.  Do you still want to close this issue?

**Comment by jnealb** [comment]
@alfarok Done per @kronz directive (yes this is counter to what I told you earlier).
