### ISSUE TITLE
Middle mouse scrolling on node preview box freeze, and finally crash Dynamo.

### ISSUE THREAD

**Issue by lxmfly123** [DynamoDS/Dynamo#8638]
## Dynamo version

1.3.2

## Operating system

Windows 7 x64

## What did you do? 

1. Make a node to output all parameters of an element.
2. Click the preview button.
3. Scroll the middle wheel of mouse while the pointer is in the preview box.

## What did you expect to see?

The list scrolls or nothing.

## What did you see instead?

Dynamo freezes, even revit does.

**Comment by ramramps** [comment]
@lxmfly123 Can you attach the graph here? Is it happening on all the previews of a node?

**Comment by lxmfly123** [comment]
Yes. After I scrolled the wheel, both dynamo and revit froze.

![screen shot 2018-03-10 at 9 33 31 am](https://user-images.githubusercontent.com/2769678/37236779-2f53a51a-2446-11e8-9710-178ffd9acc98.png)

**Comment by mjkkirschner** [comment]
replied in #6570.

**Comment by lxmfly123** [comment]
Thx, it works. @mjkkirschner
