### ISSUE TITLE
Missing library localization

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8639]
## Dynamo version

2.0.0.4297

## Operating system

Windows 7

## What did you do? 

Had a look at the library in a non-English version

## What did you expect to see?

Localized labels

## What did you see instead?

English language labels

![grafik](https://user-images.githubusercontent.com/3014437/37216649-9a966e74-23bb-11e8-9fb2-f72fad464d7a.png)

**Comment by jnealb** [comment]
@andydandy74 Thanks - this is tracked with QNTM-3675.
