### ISSUE TITLE
BooleanDifference returning null

### ISSUE THREAD

**Issue by Dorkside** [DynamoDS/Dynamo#8641]
## Dynamo version
1.3.2

## Operating system
Win 10

## What did you do? 
Created a node for exporting excavated rooms.

## What did you expect to see?
Meshes that had parts removed from BooleanDifference of another mesh

## What did you see instead?
BooleanDifference outputs null

I also tried replacing just the BooleanDifference node with a BooleanUnion and it runs smoothly, returning the expected output. I'm guessing that coming from the same library the inputs should be the same.

**Comment by johnpierson** [comment]
@Dorkside,  , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
