### ISSUE TITLE
Index out of range for an Enum/Dropdown node (Schedule Filter Type)

### ISSUE THREAD

**Issue by Password2501** [DynamoDS/Dynamo#8668]
## Dynamo version

1.3.2

## Operating system

Windows 10 Revit 2018.2

## What did you do? 
Here the Topic in dthe forums:
[LINK](https://forum.dynamobim.com/t/index-out-of-range-for-an-enum-dropdown-node-schedule-filter-type/19426)

The node Schedule filter Type just stopped working the Node object just did not respond.
But when I took the exact same Node again into the Code this one worked.
All I did was run and saved the code several times

## What did you expect to see?

The schedule Filter Node working normally

## What did you see instead?

[(Picture)](https://discourse-cdn-sjc1.com/business/uploads/dynamobim/original/3X/8/2/8267a84ce51a4ce2d786c5bfa5b1a052e82848ec.png)

**Comment by ksobon** [comment]
@Password2501 Were you able to reproduce this issue ever again? It's one of these things that no one else can re-create. 

@johnpierson I vote to close this down as un-reproducible. Leave it to the user to provide a **sample file** otherwise it's impossible to investigate.
