### ISSUE TITLE
[Feature Request] VariableOutputNode

### ISSUE THREAD

**Issue by Vlok2018** [DynamoDS/Dynamo#8672]
Hi All,

I need to write Dynamo nodes with variable outputs but I think this is not possible currently and only a VariableInputNode exists, correct?

Can you please add a VariableOutputNode to get rid of this limitation?

Thank you very much!

**Comment by saintentropy** [comment]
Hey @Vlok2018.  Thanks for your request.  We can create nodes in Dynamo that have multiple outputs although you are correct that there are not too many of them in the library.  Try searching for 'deconstruct' and you will find some examples.  If you are writing a zero touch you can use the mechanism displayed in this [example](https://github.com/DynamoDS/DynamoSamples/blob/master/src/SampleLibraryZeroTouch/Examples/BasicExample.cs#L135) in the DynamoSamples repo.  Would this work for your request?

**Comment by Vlok2018** [comment]
Unfortunately not as I am working with custom nodes and not zero touch nodes. So i would need something similar to the VariableInputNode just for Outputs.

**Comment by johnpierson** [comment]
@Vlok2018 can you mock up what you would envision the functionality of this being?
