### ISSUE TITLE
Creating sheets by name number titleblock and view doesnt work properly

### ISSUE THREAD

**Issue by Bramdj** [DynamoDS/Dynamo#8680]
## Dynamo version
1.3.2

When i create a sheet with dynamo it works perfectly. When i use the same dynamo script to create another sheet it removes the other sheet. See the pictures below.
![image](https://user-images.githubusercontent.com/26225756/37833275-2ef687a8-2eab-11e8-8f35-3590390c3165.png)
![image](https://user-images.githubusercontent.com/26225756/37833277-30cd5aac-2eab-11e8-93c6-b58a61a6b002.png)
![image](https://user-images.githubusercontent.com/26225756/37833281-3317e7be-2eab-11e8-963f-05e75712f2de.png)
![image](https://user-images.githubusercontent.com/26225756/37833289-35590aee-2eab-11e8-959b-481eac2ab659.png)

**Comment by andydandy74** [comment]
This seems like expected behaviour. Have a look at the topic of element binding:
https://forum.dynamobim.com/search?q=element%20binding
