### ISSUE TITLE
Exception after creating a node from ProtoGeometry.dll without Revit installed

### ISSUE THREAD

**Issue by vnozdrenkova** [DynamoDS/Dynamo#8724]
## Dynamo version
I am using Dynamo Studio 2017

## Operating system
Windows 10

## What did you do? 
I have created a windows form application from where I run Dynamo studio (I use Dynamo Core)
Try creating Point.ByCoordinates. Exception. When I install Revit - everything is OK.
As far as I know the Dynamo Studio is a complete stand alone application. Why the Revit is needed.

## What did you expect to see?

The node should work without Revit

## What did you see instead?

It doesn't works without Revit. Very similar to https://github.com/DynamoDS/Dynamo/issues/7408

**Comment by vnozdrenkova** [comment]
I tried it with installed Dynamo Studio but without any success. It started
to work after Revit installation

2018-04-18 17:08 GMT+03:00 Michael Kirschner <notifications@github.com>:

**Comment by andybak** [comment]
Why is this closed? Doesn't it make Dynamo Sandbox virtually useless? Even if that's not the case then the failure mode is extremely unfriendly and should be handled more gracefully. Nodes that are  not functioning in Sandbox should surely be hidden in the UI?

**Comment by tnzk** [comment]
Same problem here. Why do the nodes with such a elementary functionality like Point.ByCoordinates need to have dependency on an external library?
