### ISSUE TITLE
Code Block display error after opening a file.

### ISSUE THREAD

**Issue by MarcinTata** [DynamoDS/Dynamo#8747]
**## Dynamo version**

Dynamo Core 1.3.0.875  Dynamo Studio 1.3.0.946

**## Operating system**

Windows 10

**## What did you do?** 

I opened a file.

**## What did you expect to see?**

Code written in code block

**## What did you see instead?**

Just a few letters. Could not expand a code block to see all content.

![dynamo cb error dispaly](https://user-images.githubusercontent.com/38285902/38616801-862aaaec-3d95-11e8-8344-93b130308db1.PNG)

**Comment by mjkkirschner** [comment]
can you reproduce this or was it a one time occurrence?

**Comment by mjkkirschner** [comment]
please reopen if you can reproduce.
