### ISSUE TITLE
delete key doesn t work in dynamo  (revit 2019  Dynamo 1.3.3.4111)

### ISSUE THREAD

**Issue by fnstegeman** [DynamoDS/Dynamo#8751]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version    1.3.3.4111

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system       WINDOWS 7

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)  TRY TO DELETE A CODE BLOCK   AND TRY TO DELETE STRINGS IN A CODE BLOCK

## What did you expect to see?

(Fill in here)   DELETE SOME THING

## What did you see instead?

(Fill in here)

**Comment by QilongTang** [comment]
@fnstegeman This is expected and will be fixed in the coming Revit 2019.0.1 in May, please refer to http://dynamobim.org/dynamo-1-3-3-in-revit-2019-0/. Closing
