### ISSUE TITLE
Multitiered dictionaries convert keys and values to lists

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8760]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0

## Operating system

Win 7

## What did you do? 

Created a multitiered dictionary and tried to get out keys/values.

## What did you expect to see?

I'm on thin ice on the lingo here, but I expected singeltons as were inputted?

## What did you see instead?

the dictionary components converted to lists.
![image](https://user-images.githubusercontent.com/7080648/38870038-e5f096b0-424c-11e8-80aa-0c3aaae80514.png)

**Comment by josols** [comment]
I agree there is not a big problem. Maybe it’s my mental model of how the nodes should work that needs refining.. in my head the value return of the first Dictionary.Components should be equal to the output from the first Dictionary.ByKeysValues. ie a Dictionary and not a multileveled list containing a Dictionary?

**Comment by mjkkirschner** [comment]
I don't think this is a bug - the component nodes return lists even if the dictionary only has a single key.

loosely modeled I would guess after the .net std library Keys and Values methods. Going to close for now, if this causes problems in some other workflow please reopen.
