### ISSUE TITLE
Dynamo 2.0.0 cannot use keyboard to Delete, Copy/Paste

### ISSUE THREAD

**Issue by linkay** [DynamoDS/Dynamo#8761]
Hi, I just updated Dynamo 2.0.0 for Revit 2019 and found out that it cannot use Keyboard for functions, such as Delete, Ctr+C / Ctr+V.

**Comment by andydandy74** [comment]
See #8751

**Comment by QilongTang** [comment]
Unfortunately, this is a conflict with Revit host. This is expected and will be fixed in the coming Revit 2019.0.1 in May, please refer to http://dynamobim.org/dynamo-1-3-3-in-revit-2019-0/. Closing

**Comment by ErwinMeulman** [comment]
Revit 2019.0.1 in May? Men it real suck I can't copy/paste :(
