### ISSUE TITLE
Cannot Uninstall Dynamo Core 2.0.0

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8762]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0.4654

## Operating system

Windows 10

## What did you do? 

Had the latest daily build installed for Dynamo prior to 2.0.0.0 Stable release. Was looking to uninstall it before installing.

I have Dynamo Studio installed that could also be querying the Core build. Might be linked. 

## What did you expect to see?

I expected to be able to uninstall Dynamo Core 2.0 daily. Could uninstall Dynamo Revit 2.0 like normal.

## What did you see instead?

![image](https://user-images.githubusercontent.com/12857357/38880333-54d7284a-425d-11e8-821b-752e09a123ba.png)

![image](https://user-images.githubusercontent.com/12857357/38880342-5c9b7a0e-425d-11e8-8686-4b0811ab7e53.png)

Dynamo Core 2.0.0 uninstall (and Modify) are both greyed out.

**Comment by jnealb** [comment]
@Amoursol Thanks - this is tracked with QNTM-4028.

**Comment by mjkkirschner** [comment]
@Amoursol have you been given a workaround for this?

**Comment by QilongTang** [comment]
@jnealb  I think the workaround can be deleting the component and use Microsoft Fixit for registry, or are you aware of an existing workaround?

**Comment by Amoursol** [comment]
@mjkkirschner No fix yet - but it's just a note to say it's happening to you guys really. I ended up overriding the install with a fresh 2.0 version and all seems to be working at present.

**Comment by jnealb** [comment]
@QilongTang @Amoursol @mjkkirschner The Microsoft Fixit cleared up the issue on our QA machine. We are not aware of any other workaround at this time.
