### ISSUE TITLE
Web Request does not re-fetch on a manual run

### ISSUE THREAD

**Issue by architectcodes** [DynamoDS/Dynamo#8767]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.0.0.4654
Dynamo Revit 2.0.0.4655

## Operating system

Windows 10

## What did you do? 

I added a Web Request, the value of which varies over time (such as https://www.random.org/integers/?num=1&min=0&max=100&col=1&base=10&format=plain&rnd=new). I need to be able to re-trigger the request manually (because periodic update makes the UI of Revit extremely janky).

Therefore I switched the run mode dropdown in the bottom left corner to Manual.

## What did you expect to see?

I expect Dynamo to re-fetch the request every time I click the Run button.

## What did you see instead?

Dynamo makes a request the first time I click the Run button, but does not re-fetch on subsequent runs.

**Comment by architectcodes** [comment]
The same applies to more basic nodes like `DateTime.Now`:

![2384872653](https://user-images.githubusercontent.com/4624660/38977622-2c4f796e-43b5-11e8-8ea3-c32c32d2d2eb.gif)

**Comment by smangarole** [comment]
@architectcodes Thanks for logging this issue. I will take a look and file this issue internally.

**Comment by mjkkirschner** [comment]
@smangarole @architectcodes this is expected behavior - discussed here: 
https://github.com/DynamoDS/Dynamo/issues/6759

I would categorize this as a long standing user request. The issue is that if this node re-executed always then in automatic mode it would not stop executing .. ie all periodic nodes would execute over and over in automatic mode.

I think the suggestion from @ikeough in that linked issue is a good one, some attribute that changes behavior of periodic nodes in manual mode.

**Comment by mjkkirschner** [comment]
also here: https://github.com/DynamoDS/Dynamo/issues/7350
https://github.com/DynamoDS/Dynamo/issues/5994

**Comment by architectcodes** [comment]
Thanks for letting me know about #6759 – I did find it when searching through open issues, but had the impression forced re-execution isn’t a new feature I need. I thought the current behaviour is a bug.

Happy to close this issue as a duplicate of #6759. I’ll stay tuned for updates in there! 📻
