### ISSUE TITLE
Dynamo 2.0 cannot work

### ISSUE THREAD

**Issue by honenc** [DynamoDS/Dynamo#8768]
![image](https://user-images.githubusercontent.com/38492817/38923679-c0798f18-432d-11e8-8a63-d62f6dfb9363.png)

If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by Racel** [comment]
@honenc - What version of Revit are you running? It looks like you might have a conflict with PnIDModeler.dll that comes shipped with Revit 2018.2.  

Dynamo 2.0 has a conflict with Revit 2018.2’s implementation of PnID Modeler resulting in a blank library browser pane. This issue is not present in 2018.1 or 2018.3, or Revit 2019, just 2018.2. If you want to use 2.0 with Revit 2018.2, you will need to remove the the manifest file C:\Program Files\Autodesk\Revit 2018\AddIns\PnIDModeler\PnIDModeler.addin

For more known issues, please take a look at our [release notes](https://github.com/DynamoDS/Dynamo/wiki/Release-Notes)

If this is your issue, please let us know so that we can close this issue.

**Comment by honenc** [comment]
Is it right ?
thanks!



2018-04-18 22:57 GMT+08:00 Racel <notifications@github.com>:

**Comment by MichelBelien** [comment]
I have the same issue with Revit 2018.3
![missing library 2018 3](https://user-images.githubusercontent.com/38561659/39052744-50ed7c3c-44ad-11e8-9ac6-b266cb6f1627.png)

**Comment by jnealb** [comment]
@MichelBelien If you close Dynamo and re-launch it in the same Revit session does the blank library still happen?

**Comment by MichelBelien** [comment]
Yes then I still have a blank Library.

**Comment by jnealb** [comment]
@MichelBelien Thanks. Can you show us what packages you have loaded by pulling down the Manage Packages window?

**Comment by MichelBelien** [comment]
None packages installed for 2.0
![image](https://user-images.githubusercontent.com/38561659/39053935-9a154a0e-44b0-11e8-9468-af7dbad7abf9.png)

**Comment by jnealb** [comment]
@MichelBelien Thanks. Two more requests: 1. Can you open the console (it is under View) to check for any errors 2. The Notification window shows 5 issues, can you also send us that window's contents?

**Comment by MichelBelien** [comment]
Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly CefSharp.Wpf, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138, Dynamo detected that the dependency CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms
Dynamo is up to date.
Clearing workspace...

**Comment by MichelBelien** [comment]
![image](https://user-images.githubusercontent.com/38561659/39054701-9f26eaaa-44b2-11e8-82fd-c62a2976ee52.png)

**Comment by jnealb** [comment]
@MichelBelien Thanks. What other Revit Addins do you have loaded?

**Comment by ramramps** [comment]
Do you have NBS plugin?

**Comment by MichelBelien** [comment]
a lot,
![image](https://user-images.githubusercontent.com/38561659/39054935-30000462-44b3-11e8-993a-ca7f1c7472ef.png)

**Comment by mjkkirschner** [comment]
the message above contains some hints about what is conflicting.
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

**Comment by MichelBelien** [comment]
yes NBS plugin is installed

**Comment by ramramps** [comment]
Thanks @MichelBelien.. NBS plugin has its cefsharp loaded...we will get back to you with possible workaround.

**Comment by Racel** [comment]
@ramramps Just following up on this. Any updates?

**Comment by ramramps** [comment]
@smangarole @jnealb did we get any luck in loading this plugin in our dev environment?

**Comment by MichelBelien** [comment]
When I did a de-install off the NBS plugin the Dynamo library appears.
So the issue sits in the NBS plugin

**Comment by Racel** [comment]
@MichelBelien @ramramps I know that uninstalling the plugin is not ideal, we are working towards resolving the CEFsharp issues with library. But, since we know that Dynamo will be fixed if you removed the plugin, can we close this issue?

**Comment by MichelBelien** [comment]
Yes you can close the issue

**Comment by natgmac** [comment]
If we don't have the NBS plugin to uninstall to fix this problem, how can we find out which plugin is causing the issue?

**Comment by jnealb** [comment]
@natgmac There are several that could be causing it; it is best to "divide and conquer" eg remove them to identify which one it is.

**Comment by rahimrajpari** [comment]
Same issue. Removed all the addins from the directory but no luck.
