### ISSUE TITLE
Dynamo 2.0.0 Library Search

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#8769]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0 stable

## Operating system

Win 7

## What did you do? 

search for library items

## What did you expect to see?

A search result

## What did you see instead?

It seems like the fuzzy algos of library searching has gotten even more fuzzy, also compared to this, #6681. 
![searchdyn](https://user-images.githubusercontent.com/7080648/38927854-4b4eb59a-4307-11e8-9823-b86bd87169bf.gif)

the search in canvas still works the old way, though still prone for improvement. (ie. category, all elements of category etc.)
![searchcanvas](https://user-images.githubusercontent.com/7080648/38928453-2d45b2cc-4309-11e8-87d7-d523dd459cdd.gif)

**Comment by Racel** [comment]
@josols As mentioned on twitter, the latest daily build contains a fix for this. http://dynamobuilds.com/

Please take a look and let us know if your issue is resolved.

**Comment by Racel** [comment]
@josols Just following up on this. Have you been able to test the 2.0.1 daily build? Can we close this issue?

**Comment by josols** [comment]
Sorry for the late reply. The search now works similar to the incanvas search (as far as I can tell)  I'll close.
