### ISSUE TITLE
squre millimeter volume incorrect

### ISSUE THREAD

**Issue by SJM84** [DynamoDS/Dynamo#8773]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by smangarole** [comment]
@SJM84 We need more information on this bug. Please provide OS versions, Revit versions if any, Dynamo and DynamoRevit versions

**Comment by SJM84** [comment]
REVIT VERSION 2018

DYNAMO VERSION 1.2.2.373

OS WINDOWS 10

Simon Murphy
BSc Architecture
Architectural Assistant
sjm@gotch.co.uk

[cid:image001.png@01D3D7F4.A14C7190]
www.gssarchitecture.com

DDI: 01423 637152   T: 01423 815121
