### ISSUE TITLE
XAML error while debugging sandbox

### ISSUE THREAD

**Issue by BartDeMaesschalck** [DynamoDS/Dynamo#8774]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

master-branch

## Operating system

Windows 10

## What did you do? 

I downloaded the latest master branch in a zip and compiled it using visual studio 2017 (version 15.6.6)
Build went ok without errors. 
Selected DynamoSandbox as startup project.
On running coming to InitializeComponent(); in DynamoView.xaml.cs execution stops reporting:
"Exception thrown: 'System.Threading.ThreadAbortException' in DynamoCore.dll
The component 'Dynamo.Controls.DynamoView' does not have a resource identified by the URI '/DynamoCoreWpf;component/views/core/dynamoview.xaml'."

## What did you expect to see?

Running Sandbox

## What did you see instead?

Error listed above

**Comment by smangarole** [comment]
@mjkkirschner @alfarok Any idea?

**Comment by QilongTang** [comment]
I have seen this couple times from my experience, it usually happens for the first a few times you start sandbox. I think if Sandbox crashes before it got launched, it always end up with this exception, you may want to try rebuilding a couple times and debug again couple times. Then this exception should go away. Not a good answer but worth to try.

**Comment by BartDeMaesschalck** [comment]
Found out that after deleting  AppData\Roaming\Dynamo\Dynamo Core\2.0
everything worked.

Thanks for the help

**Comment by ricardyn** [comment]
It happened to me right in 2025. @BartDeMaesschalck, thanks for the response. It solved the problem.
