### ISSUE TITLE
3D Viewport has no content at all

### ISSUE THREAD

**Issue by aliasguru** [DynamoDS/Dynamo#8787]
## Dynamo version
2.0.0.4354

## Operating system
Windows 10

## What did you do? 
I'm using the Integration of Dynamo in Autodesk Alias. No matter how I proceed, the 3D Viewport behind the node tree remains entirely blank. Not even the grid is drawn. I have already installed the Direct3D patch from https://knowledge.autodesk.com/support/alias-products/downloads/caas/downloads/content/alias-sample-files.html, but it made no difference. I also tried the Frame View button, no luck. The geometry IS created, as I can send it back to Alias using the 'Bake to Alias' node.

## What did you expect to see?
Geometry in the Viewport

## What did you see instead?
White, nothing else

Node View:
![dynamo1](https://user-images.githubusercontent.com/24734924/39184133-996bf67e-47c2-11e8-9a87-11c31b149405.JPG)

3D View:
![dynamo2](https://user-images.githubusercontent.com/24734924/39184159-b004f250-47c2-11e8-96a9-ea31433ac9b8.JPG)

**Comment by ramramps** [comment]
@ptierney Is this sandbox or revit? Did you check this page?
https://github.com/DynamoDS/Dynamo/wiki/Known-Issues

**Comment by ramramps** [comment]
thanks @aliasguru .
@jnealb any thoughts here?

**Comment by jnealb** [comment]
@aliasguru @ramramps Yes, we have another report of Dynamo not supporting multi graphics card configurations, please see QNTM-2325.

**Comment by mjkkirschner** [comment]
@aliasguru have you read this section on switchable graphics:https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ?

it's less likely with a desktop and xeon cpus but they may still have integrated gpus...

I would try that first, then try what @jnealb suggests and try disabling the other cards temporarily.

**Comment by aliasguru** [comment]
OK, I'm one step further. When I disable my three TitanX cards, Dynamo runs just fine. I'll investigate further tomorrow if I can assign specific cards to Dynamo via the Control Panel.

**Comment by aliasguru** [comment]
Of all the solutions I've tried, only deactivating ALL secondary GPUs works. As soon as I reactivate any of the three Titans, the Viewport is gone.

- reinstalling the driver was useless
- installing a different driver gave me other hell, so cannot confirm if that would make a difference
- Setting options in the Performance Tab for DynamoAlias made no difference
- In the BIOS, my onboard GPU is deactivated already. Also, there are no settings for it in the OS anywhere

Running out of options at the moment.

**Comment by jnealb** [comment]
@aliasguru @mjkkirschner @ramramps  The QNTM-2325 task is in our backlog for 2.1. If we find a workaround in the meantime we will notify you.
