### ISSUE TITLE
System Icomparer shows up in the library

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#8790]
I am not sure how this one found its way into the library: 

![image](https://user-images.githubusercontent.com/529781/39222625-a7e41d78-480b-11e8-8014-525e9c507726.png)

**Comment by mjkkirschner** [comment]
* do you embed interop types into your dlls?
* do you reference this type at all?
* do you have any methods that accept or return an IComparer?

**Comment by mjkkirschner** [comment]
rather, I think it was meant to hide the base class, but the regression might be very specific (why we missed it)

can you share your in development package.json file here and an image of your bin folder?

**Comment by mjkkirschner** [comment]
another thought - are you distributing dynamo core or dynamoServices with your package? That will also cause this behavior.

**Comment by ksobon** [comment]
So I was able to get it to hide itself when I changed the class to `internal` - obviously. I did try the `[SupressImportIntoVM]` attribute and that didn't work. I also tried putting `[IsVisibleInDynamoLibrary(false)]` attribute on both the class and the method inside of it since that was public as well, but that didn't work either. 

Again, luckily I could actually make this one internal, so problem solved but it's something worth checking out. 

```
/// <summary>
    /// Comparer class that reverses the order of sorting.
    /// </summary>
    internal class ReverseComparer : IComparer
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        /// <returns></returns>
        public int Compare(object x, object y)
        {
            return new CaseInsensitiveComparer().Compare(y, x);
        }
    }
```

![image](https://user-images.githubusercontent.com/529781/39223350-954070be-480f-11e8-9c97-d46b4fb2bf51.png)

I don't distribute any of the mentioned libraries. I do reference them in for some of the UI work. 

![image](https://user-images.githubusercontent.com/529781/39223469-469dd482-4810-11e8-997b-6925004a7c1c.png)

[pkg.zip](https://github.com/DynamoDS/Dynamo/files/1945292/pkg.zip)

**Comment by mjkkirschner** [comment]
@ksobon can you verify that you package (that you are testing) is built against the dynamo 2.x nugets and not the 1.3 ones?

**Comment by ksobon** [comment]
Yup. 

![image](https://user-images.githubusercontent.com/529781/39223558-c8051058-4810-11e8-829c-51fa9574e227.png)

**Comment by mjkkirschner** [comment]
tracked with:
https://jira.autodesk.com/browse/QNTM-4094

**Comment by aparajit-pratap** [comment]
@mjkkirschner I think it would be worth investigating the `IsVisibleInDynamoLibrary` and `SuppressImport` attributes to see if they're not broken. I think I saw a similar issue with these recently.

**Comment by aparajit-pratap** [comment]
This is fixed in https://github.com/DynamoDS/Dynamo/pull/9242. Closing. Let us know if you still see issues.
