### ISSUE TITLE
Dynamo Forum Login: There was an error authorizing your account

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8792]
Not sure where to post this but I cant log in to the Dynamo forum, and see this error. I've attempted to clear my brower history and logins, but nothing seems to work. The only thing I have done recently is reset my ssl settings. 

![image](https://user-images.githubusercontent.com/18601851/39251382-0780a5b4-489b-11e8-8e4c-a8f9b79b25d9.png)

**Comment by QilongTang** [comment]
I could not log in either.. FYI: @Racel @mjkkirschner @ramramps

**Comment by jnealb** [comment]
I was in as recently as Monday, fyi.

**Comment by QilongTang** [comment]
@ThomasMahon I could do it now without doing anything on my end. It could be specific identity service  went down for a few hours.. Let us know if you still could not log in

**Comment by ThomasMahon** [comment]
@QilongTang  @jnealb same, this appears to be working now. Thanks for looking into it
