### ISSUE TITLE
DesignScript behaving oddly

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8794]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Studio version 1.3.0.881 | Dynamo Core version 1.3.2.2480

## Operating system

Windows 10

## What did you do? 

Building a custom definition in designscript that is behaving oddly with nodal interactions behind it.

## What did you expect to see?

The **GetKeys** node behaving correctly. Also, weirdly, Math.Abs / Math.Round etc don't work (Probably due to the data being broken).

## What did you see instead?

The points list from the **Watch** node is being ran through a definition to simply get their X and Y points and pair them (Intention is to wrap in a bigger portion hence not using nodes). This apparently results in the correct information - but the **GetKeys** node (And others tested) return either incorrect data or **Nulls**.

![image](https://user-images.githubusercontent.com/12857357/39296112-fd178730-4937-11e8-8a3d-c12fabd77a4a.png)

**Comment by aparajit-pratap** [comment]
@Amoursol there have been issues with the way we represented lists and dictionaries with essentially the same data structure in the past. However, in 2.0 a majority of these issues should be addressed with the introduction of a separate `Dictionary` type. Now, lists are simply lists and therefore many of the old methods that worked with lists earlier, do not apply to lists any more , `GetKeys` being one of them. Some of these nodes have therefore been [deprecated ](https://github.com/DynamoDS/Dynamo/pull/8615)in 2.0 and will therefore not be fixed. We highly recommend you switch to 2.0 but if you have to continue to use 1.3, please avoid using these methods. I'm sorry I don't have a better answer.
