### ISSUE TITLE
Preview Upstream

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8795]
## Dynamo version
2.0.04654 (stable)

## Operating system
Windows 10

## What did you do? 
Selected node/s and right click on canvas 

## What did you expect to see?
Menu with no traces of _Preview Upstream_
Note:  Though it's been depreciated, while it existed, I did find it useful to control graphics visibility on _View3D_ as I'd earlier outlined [here](https://github.com/DynamoDS/Dynamo/issues/8315)

## What did you see instead?
_Preview Upstream_ stubbornly lingers 😃 
![previewupstream](https://user-images.githubusercontent.com/5621624/39307392-4fccc6f0-4980-11e8-8e69-c4e9002bd1bc.png)

**Comment by ramramps** [comment]
thanks @vykrum. This is tracked under https://jira.autodesk.com/browse/QNTM-4110

**Comment by johnpierson** [comment]
Confirmed that this persists in 2.0.1. For the 2.0.0 release, it was removed from the context menu when right clicking on nodes, but missed on the right click on canvas with nodes selected.
