### ISSUE TITLE
[Bug][DesignScript] Namespace issues causing Input Port Generation

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8796]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1) Dynamo Studio 1.3.0.881 & Dynamo Core 1.3.3.4111
2) Dynamo Revit 2.0.0.4655 & Dynamo Core 2.0.0.4665

## Operating system

Windows 10

## What did you do? 

I have namespace conflicts with some of my custom packages, so I'm trying to hardcode in the default Dynamo namespaces. This is causing input ports to be generated in lieu or correctly calling the right function.

## What did you expect to see?

I expected the hard-coded namespace to correctly call the relevant library - in this case Geometry.

## What did you see instead?

Input ports being auto-generated as the Code Block is not recognising the namespace.

Dynamo Revit v2.0
![image](https://user-images.githubusercontent.com/12857357/39311314-7f1d0634-4964-11e8-999a-78547f463670.png)

Dynamo Studio v1.3
![image](https://user-images.githubusercontent.com/12857357/39313570-3bdf3bc0-496a-11e8-9307-d050fb4c6d59.png)

**Comment by mjkkirschner** [comment]
@aparajit-pratap FYI

**Comment by jnealb** [comment]
@mjkkirschner @aparajit-pratap @Racel @Amoursol Is this already filed in JIRA?

**Comment by mjkkirschner** [comment]
don't think so.

**Comment by dimven** [comment]
Previously reported in #7697 and #8084

**Comment by mjkkirschner** [comment]
please put this in the release notes or design script updates doc/ with a workaround if it proves to work... @Amoursol can you try the suggested work around?

**Comment by Amoursol** [comment]
I've tested the workaround and it functions correctly @mjkkirschner! Thanks for that :)

![image](https://user-images.githubusercontent.com/12857357/39397142-475366be-4af2-11e8-9413-85c0376ae460.png)

**Comment by Racel** [comment]
Thanks @Amoursol and @mjkkirschner Added to the release notes and language changes docs as known issues.

**Comment by mjkkirschner** [comment]
@Racel @aparajit-pratap @smangarole @jnealb - There are a bunch of bugs like this that users run into all the time - finding them and communicating the workarounds to users is tough when they are closed - why are they closed when they are still issues? Can we add a new label like tracked or something more explicit and stopping closing issues that are not fixed?

**Comment by andydandy74** [comment]
That would be much appreciated!

**Comment by aparajit-pratap** [comment]
@mjkkirschner I would like to see them open myself but I think the general protocol followed by QA so far has been to close them after filing them internally. I leave it up to the team to decide which is better.

**Comment by jnealb** [comment]
@Racel @mjkkirschner @aparajit-pratap @smangarole @Dewb @andydandy74 Yes that protocol was adhered to leading up to the 2.0 release. Nothing wrong with revisiting it now. 

Also, please see JIRA task QNTM-4354 for a follow-up to these issues.

**Comment by mjkkirschner** [comment]
so I'm going to open this then. 😄

**Comment by mjkkirschner** [comment]
@Racel @johnpierson - should we add a tracked label for these issues which we want to mark as tracked in jira?

**Comment by Racel** [comment]
@johnpierson Thanks for adding the Tracked label!

**Comment by mjkkirschner** [comment]
I think this should be fixed now - yay!
