### ISSUE TITLE
[Nodes] Curve not offsetting properly

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8799]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Tested in both versions.

1) Dynamo Studio 1.3.0.881 & Dynamo Core 1.3.3.4111
2) Dynamo Revit 2.0.0.4655 & Dynamo Core 2.0.0.4665

## Operating system

Windows 10

## What did you do? 

Simply attempted to offset a curve on the XY plane.

## What did you expect to see?

Curve offsetting in both the postive and negative directions as per the list input.

## What did you see instead?

Curve appears to not offset correctly. It is planar and an equality comparison considers the curves to be different - however both graphically and via the XYZ location numbers the curves are located in the same place. 

![image](https://user-images.githubusercontent.com/12857357/39367909-0a0ee7be-4a30-11e8-9262-10a22767e8de.png)

If I rebuild the curve using the start and endpoints prior to offsetting, it works as expected. Tested in both 1.3 and 2.0 versions - same results.

![image](https://user-images.githubusercontent.com/12857357/39367950-2714777a-4a30-11e8-8137-e2dd14243018.png)

Wondering if I've somehow corrupted my install as a lot of nodes are failing of late... 😢

**Comment by mjkkirschner** [comment]
How are you creating these lines?

**Comment by Amoursol** [comment]
@mjkkirschner They are PerimeterCurves() pulled from a surface. Said surface is generated randomly from a points distribution grid. 

Simplified version as follows:

![image](https://user-images.githubusercontent.com/12857357/39472028-83db74fc-4d3e-11e8-81dc-ff5044c7178f.png)

Using one of @dimven 's epic nodes (Python pulled out due to package issues):

![image](https://user-images.githubusercontent.com/12857357/39472039-9b630af4-4d3e-11e8-9df1-cf5b673c9f15.png)

**Comment by aparajit-pratap** [comment]
@Amoursol just one comment here - the `Geometry.IsAlmostEqualTo` is the preferred way of doing equality checks for geometry as it takes into account a tolerance.

**Comment by Amoursol** [comment]
> @Amoursol just one comment here - the Geometry.IsAlmostEqualTo is the preferred way of doing equality checks for geometry as it takes into account a tolerance.

Ah brilliant, I'll use that node from now on :) Many thanks @aparajit-pratap

**Comment by smangarole** [comment]
@Amoursol Can you please provide the DYN files you used?

**Comment by Amoursol** [comment]
It appears to be an issue at my end on my work laptop - as it appears to work correctly at home on 2.0 and 1.3.1

I did have an issue with my installs so there could be some form of legacy thing breaking stuff. I'll have to run a registry purge and reinstall I think. 

![image](https://user-images.githubusercontent.com/12857357/39490426-bdeb34b0-4d80-11e8-92a0-ff2c1fd8db33.png)

[curveOffsetIssue.zip](https://github.com/DynamoDS/Dynamo/files/1964995/curveOffsetIssue.zip)

**Comment by smangarole** [comment]
@Amoursol Registry purge is recommended if you are installing/uninstalling. Thanks for the information. Will checkout the files.

**Comment by Racel** [comment]
@Amoursol Closing this task now since your issue seems to be resolved.
