### ISSUE TITLE
Issue with the Override element color node/def

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#880]
Hi guys, here's what happens in the console with Revit 2013, trying to play with the sample def provided:

All Tests Passed. Core library loaded OK.
Welcome to Dynamo!
00:00:01.6778563 elapsed for loading Dynamo main window.
Opening home workspace C:\Autodesk\Dynamo\Core\samples\22 Color\OverrideGraphicsInView_Walls.dyn...
Clearing workflow...
00:00:00.0008871 elapsed for loading xml.

Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf59" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5a" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5b" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5c" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5d" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5e" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5f" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf60" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf61" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf62" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf63" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf64" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf65" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf66" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf67" not found in Document.

00:00:00.2697098 ellapsed for loading nodes.
00:00:00.0186649 ellapsed for loading connectors.
00:00:00.0029692 ellapsed for loading notes.
Applying model migration from 0.5.3.x to 0.6.0.x
00:00:01.1513572 ellapsed for loading workspace.
System.TypeLoadException:
Could not load type 'Autodesk.Revit.DB.OverrideGraphicSettings' from assembly 'RevitAPI, Version=2013.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Dynamo.Nodes.OverrideColorInView.Evaluate(FSharpList`1 args)
   at Dynamo.Revit.RevitTransactionNodeWithOneOutput.Evaluate(FSharpList`1 args, Dictionary`2 outPuts)
   at Dynamo.Models.NodeModel.__eval_internal_recursive(FSharpList`1 args, Dictionary`2 outPuts, Int32 level)
   at Dynamo.Revit.RevitTransactionNode.__eval_internal(FSharpList`1 args, Dictionary`2 outPuts)
   at Dynamo.Models.NodeModel.<>c__DisplayClass44.<evaluateNode>b__41()
Could not load type 'Autodesk.Revit.DB.OverrideGraphicSettings' from assembly 'RevitAPI, Version=2013.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Dynamo.Nodes.OverrideColorInView.Evaluate(FSharpList`1 args)
   at Dynamo.Revit.RevitTransactionNodeWithOneOutput.Evaluate(FSharpList`1 args, Dictionary`2 outPuts)
   at Dynamo.Models.NodeModel.__eval_internal_recursive(FSharpList`1 args, Dictionary`2 outPuts, Int32 level)
   at Dynamo.Revit.RevitTransactionNode.__eval_internal(FSharpList`1 args, Dictionary`2 outPuts)
   at Dynamo.Models.NodeModel.<>c__DisplayClass44.<evaluateNode>b__41()
Evaluation completed in 00:00:00.4524185

and I also have an issue with the node in Revit 2014:

All Tests Passed. Core library loaded OK.
Welcome to Dynamo!
00:00:01.1010201 elapsed for loading Dynamo main window.
Opening home workspace C:\Autodesk\Dynamo\Core\samples\22 Color\OverrideGraphicsInView_Walls.dyn...
Clearing workflow...
00:00:00.0004468 elapsed for loading xml.

Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf59" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5a" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5b" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5c" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5d" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5e" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf5f" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf60" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf61" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf62" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf63" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf64" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf65" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf66" not found in Document.
Element with UID "5091baf4-c802-459a-8a18-a30b661c48ef-0002cf67" not found in Document.

00:00:00.2218889 ellapsed for loading nodes.
00:00:00.0170719 ellapsed for loading connectors.
00:00:00.0030528 ellapsed for loading notes.
Applying model migration from 0.5.3.x to 0.6.0.x
00:00:00.9845570 ellapsed for loading workspace.
System.InvalidOperationException:
La séquence ne contient aucun élément correspondant.
   à System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   à Dynamo.Nodes.OverrideColorInView.Evaluate(FSharpList`1 args)
   à Dynamo.Revit.RevitTransactionNodeWithOneOutput.Evaluate(FSharpList`1 args, Dictionary`2 outPuts)
   à Dynamo.Models.NodeModel.__eval_internal_recursive(FSharpList`1 args, Dictionary`2 outPuts, Int32 level)
   à Dynamo.Revit.RevitTransactionNode.__eval_internal(FSharpList`1 args, Dictionary`2 outPuts)
   à Dynamo.Models.NodeModel.<>c__DisplayClass44.<evaluateNode>b__41()
La séquence ne contient aucun élément correspondant.
   à System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   à Dynamo.Nodes.OverrideColorInView.Evaluate(FSharpList`1 args)
   à Dynamo.Revit.RevitTransactionNodeWithOneOutput.Evaluate(FSharpList`1 args, Dictionary`2 outPuts)
   à Dynamo.Models.NodeModel.__eval_internal_recursive(FSharpList`1 args, Dictionary`2 outPuts, Int32 level)
   à Dynamo.Revit.RevitTransactionNode.__eval_internal(FSharpList`1 args, Dictionary`2 outPuts)
   à Dynamo.Models.NodeModel.<>c__DisplayClass44.<evaluateNode>b__41()
Evaluation completed in 00:00:00.3433672
Active view is now travail 3D

Hope it helps.

**Comment by kronz** [comment]
duplicate issue with http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-940
We have to squash this one . . . wicked old

**Comment by jnealb** [comment]
@jbenoit44 @LevL We think this is fixed with 0.7.6.3850 which can be downloaded from Dynamobuilds.

**Comment by jbenoit44** [comment]
I will check this asap. If so, I think I will have a celebrating dance :)!

Julien BENOIT

**Comment by jbenoit44** [comment]
Having a dance right now!!  \m/  \m/

**Comment by RodRecker** [comment]
Send a video!

**Comment by jnealb** [comment]
@jbenoit44 @RodRecker La Bretonne, Farandole, Ritournelle, Bourrée ou la Gigue, venue d'Angleterre au 17eme siècle?

**Comment by jbenoit44** [comment]
![tumblr_static_tumblr_mjatuzs0lg1rb4km6o1_500](https://cloud.githubusercontent.com/assets/4572196/5876764/32e1cdde-a31a-11e4-8356-ac7d15d78979.gif)

**Comment by RodRecker** [comment]
nice!
