### ISSUE TITLE
Custom node input descriptions are not saved

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8802]
## Dynamo version
Dynamo 2.0 stable

## Operating system
Windows 10

## What did you do? 

- Created a custom node
- Included a comment in the input node of the custom node
- Saved the custom node

## What did you expect to see?

The comment to be saved in the custom node file

## What did you see instead?

While in session, the comment is visible in the input port tooltip. After restarting Dynamo, it is not. Examining the *.dyf file reveals that the comment never got saved.
Furthermore, nodes that were migrated to JSON format with the migration view extension originally include the comments but will lose them once they are edited and saved in 2.0

FYI @mjkkirschner

**Comment by jnealb** [comment]
@andydandy74 Thanks. This is tracked with QNTM-4176.
