### ISSUE TITLE
Node coordinates in custom nodes are set to 0,0 when editing node properties

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8803]
## Dynamo version
2.0 stable

## Operating system
Windows 10

## What did you do? 
Changed a custom node's description

## What did you expect to see?
Just a changed node description

## What did you see instead?
![grafik](https://user-images.githubusercontent.com/3014437/39411954-07237174-4c14-11e8-9b81-31b5b456a6f2.png)
All node coordinates within the custom node were reset to X=0 and Y=0.
![grafik](https://user-images.githubusercontent.com/3014437/39411948-fba3094a-4c13-11e8-8741-46cb8d6f438e.png)

## Steps to reproduce
Using the Dynamo UI, change the description or category of any of the nodes available here:
https://github.com/andydandy74/ClockworkForDynamo/tree/master/nodes/2.x

FYI @mjkkirschner

**Comment by andydandy74** [comment]
Maybe a localizaton issue again? Try German locale.
Here's what I did:
![changenodeproperties](https://user-images.githubusercontent.com/3014437/39446702-a1d837da-4cbf-11e8-8bb2-48983620007e.gif)
And here's what the node looks like in the next Dynamo session:
![coordinateslost](https://user-images.githubusercontent.com/3014437/39446723-b0f7c938-4cbf-11e8-82d6-25fa84f38145.gif)

**Comment by andydandy74** [comment]
Yes, when creating the GIFs I realized I had neglected to mention that in my original description... ;-)

**Comment by andydandy74** [comment]
Also, looking at the diff screenshot posted above again, I'm noticing that the ```IsSetAsInput``` property value of the Python Script node is being changed as well. Not sure which effect that would have and if that's to be expected.

**Comment by QilongTang** [comment]
@andydandy74 Thank you for reporting and I found this is causing a series of larger issues, we are using the **save** function on **CustomNodeWorkspaceModel** when editing custom node info which only saves model properties. This means all view info will be lost after this action as long as `IsSetAsInput` and `IsSetAsOutput`.   FYI: @mjkkirschner @Racel @ramramps @smangarole @jnealb I think this is worth to fix in 2.0.1

**Comment by ramramps** [comment]
good find @QilongTang.. lets get this in 2.0.1

**Comment by jnealb** [comment]
This is tracked with QNTM-4180; again, thanks @andydandy74 !

**Comment by mjkkirschner** [comment]
@QilongTang oh man, good catch, needs a test. @jnealb Is this in this sprint?

**Comment by andydandy74** [comment]
@QilongTang @ramramps @jnealb @mjkkirschner 
Did this fix not make it into the 2.0.1 release? Because I'm still seeing this in 2.0.1 stable (2.0.1.5055) when editing custom node properties in sandbox:
![grafik](https://user-images.githubusercontent.com/3014437/40596117-141e0fa2-6239-11e8-8fe0-243152c4bd6d.png)
![grafik](https://user-images.githubusercontent.com/3014437/40596136-365e0b9e-6239-11e8-86d8-400f6add8d59.png)
Also, not sure why ```Name``` and ```ShowGeometry``` properties need to be rewritten.

**Comment by QilongTang** [comment]
@andydandy74 I think the fix is there but do you mind sharing the steps again this time?

**Comment by mjkkirschner** [comment]
Since the view is being rewritten it looks like the fix is applied, but a case was missed - will need exact steps I think.

**Comment by andydandy74** [comment]
So what I'm doing (in Sandbox - haven't tried DynamoRevit) is the following:
1. New workspace
2. Place custom node from library
3. Right-click on node to edit properties
4. Edit properties and exit dialog with OK
5. Close Sandbox

Diffing the node file gives the result above.

If I double-click on the placed node to open it in a new tab (and close that tab again) between steps 2 & 3, the node coordinates are **not** reset. So the issue only occurs if the custom node is not opened prior to editing the properties.

**Comment by mjkkirschner** [comment]
@smangarole I feel like we also tested this but maybe we missed it - we may have started down this path but not finished, seems like it could be when the node is lazy loaded and so there is no loaded customNodeWorkspace, but placing it should load that workspace....

**Comment by Racel** [comment]
@mjkkirschner @QilongTang can you make a jira task for this and place it in the backlog for 2.1?

**Comment by jnealb** [comment]
https://jira.autodesk.com/browse/QNTM-4368

**Comment by jnealb** [comment]
@andydandy74 Thank you!
