### ISSUE TITLE
[DesignScript][Crash] Mask Generation failing

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8808]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 1.3.3.4111

## Operating system

Windows 10

## What did you do? 

Simply trying to run a code line generating a Mask - but inadvertently hit 'run' before finalising the line.

## What did you expect to see?

The line execute without causing a crash and to simply tell me I hadn't finished with the line correctly (As in - calling Surface.Area on a Surface)

## What did you see instead?

This executes correctly:
![image](https://user-images.githubusercontent.com/12857357/39427996-c4ed198a-4c7d-11e8-9d5b-38f58334df9d.png)

When I uncomment the final line, and hit run, it crashes:
![image](https://user-images.githubusercontent.com/12857357/39428022-d8b1ab7a-4c7d-11e8-8a29-e1f5c92560bc.png)

Code [Will run on any flat planar surface - to execute correctly call on actual surface in final line]:
`// Values
offsetAmt = 5000;
// Stuff
crv = srf.PerimeterCurves();
cLen = crv.Length;
mask = cLen == DSCore.List.MaximumItem(cLen);
longCrv = Flatten(DSCore.List.FilterByBoolMask(crv,mask)["in"]);
rebuildCrv = Line.ByStartPointEndPoint(longCrv.StartPoint,longCrv.EndPoint);
doubleOffset = {-offsetAmt,offsetAmt};
offsetCrv = Flatten(rebuildCrv<1>.Offset(doubleOffset<2>));
centrePnt = srf.PointAtParameter(0.5,0.5)[0];
crvDist = Autodesk.Geometry.DistanceTo(offsetCrv,centrePnt);
crvMask = DSCore.List.MinimumItem(crvDist) == crvDist;
insideCrv = Flatten(DSCore.List.FilterByBoolMask(offsetCrv,crvMask)["in"])[0];
extendCrv = insideCrv.ExtendStart(insideCrv.Length/2)
.ExtendEnd(insideCrv.Length/2);
extrudeVals = {-50,50};
extrudeCrv = PolySurface.ByJoinedSurfaces(extendCrv<1>.Extrude(extrudeVals<2>));
smallSrf = Flatten(Autodesk.Geometry.Split(srf,extrudeCrv));
//srfMask = Autodesk.Surface.Area == DSCore.List.MinimumItem(Autodesk.Surface.Area);`

**Comment by mjkkirschner** [comment]
This appears to be attempting to call MinimumItem on a function, I would guess this is not a syntax error, but should be a runtime error and not a crash. @aparajit-pratap ?

**Comment by aparajit-pratap** [comment]
@Amoursol yes, `Surface.Area` is a function object as it needs to be passed a surface object in order to invoke it, like: `Surface.Area(surface);`. Otherwise you can also invoke it using `surface.Area;`, where `surface` is the input surface created upstream. In any case this should not crash. Could you let us know if you are able to reproduce this crash on 2.0? There have been related fixes that have gone into 2.0 and it would be good if we could with your help verify them. Thanks.

**Comment by Amoursol** [comment]
Hello @aparajit-pratap, the fix indeed works in 2.0 - many thanks!

Result as follows:

![image](https://user-images.githubusercontent.com/12857357/39471756-d18f6aa2-4d3c-11e8-9f6b-bf498a6fff07.png)
