### ISSUE TITLE
assign icons to methods with different input

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#8813]
@alfarok 

I have tried to follow the below wiki, but I cant figure why I cant assign my icons when methods are named the same with different inputs.
https://github.com/DynamoDS/Dynamo/wiki/Add-Icons-for-a-Zero-Touch-Assembly-or-NodeModel-assembly

I have two methods named the same, but taking different inputs:
public static object LoadFamily(IList family)
public static object LoadFamily(IList document, IList family)

I have tried to name the icon:
Orchid.Core.File.LoadFamily.family.Small
Orchid.Core.File.LoadFamily.document-family.Small

Orchid.Core.File.LoadFamily.var.Small
Orchid.Core.File.LoadFamily.var-var.Small

Orchid.Core.File.LoadFamily1.Small
Orchid.Core.File.LoadFamily2.Small

no matter how I do it, no icons is shown...

**Comment by alfarok** [comment]
Hey @erfajo, you might also want to check out [this wiki](https://github.com/DynamoDS/Dynamo/wiki/Adding-or-Updating-Built-In-Library-Icons#overloaded-methods).  If you have an overloaded method you need to append the parameter types to the name, each separated by a dash.  When dealing with arrays and collections you must also append an integer that specifies the rank.  For example...
```
Surface.ByLoft
crossSections: Curve[]
guideCurve: Curve
```

I believe it should be something similar to...
```
Autodesk.DesignScript.Geometry.Surface.ByLoft.Curve1-Curve.Small.png
```

If you run into additional issues please post the method signatures so I can take a look at how your IList's are defined.

**Comment by erfajo** [comment]
I did see that part of the wiki, and I have tried to figure how IList is evaluated as an Array, but haven't found the way to do it. I have tested with these names, without success.
Orchid.Core.File.LoadFamily.family2.Small
Orchid.Core.File.LoadFamily.document1-family1.Small

Orchid.Core.File.LoadFamily.var2.Small
Orchid.Core.File.LoadFamily.var1-var1.Small

The method as such is actually my own implementing of a PythonEngine, and it works quite good... so the method below is the entire code (with call to my PythonEngine)

        /// <summary>
        /// Load family by file name, same core process as FamilyDocument.LoadFamily
        /// </summary>
        /// <param name="family">Path to the family file(s)</param>
        /// <returns name="Family">Family</returns>
        [NodeCategory("Actions")]
        public static object LoadFamily(IList family)
        {
            // Python file and input
            string script = PythonEngine.ReadEmbeddedResourceFile("Orchid.Lib.File_LoadFamily.py");
            string method = "_auto_";
            object[] parameters = { family };
            return PythonEngine.InvokeMethodWithParameters(script, method, parameters);
        }

The other method has just an extra input, but the code inside the method is the same.

![image](https://user-images.githubusercontent.com/2844374/39490344-e19a5d98-4d88-11e8-8f93-702fc54d0f00.png)
![image](https://user-images.githubusercontent.com/2844374/39490360-ec442418-4d88-11e8-8873-f43f56ed9d16.png)

**Comment by alfarok** [comment]
@erfajo Can you give this a try...
```
Orchid.Core.File.LoadFamily.varN.Small.png
Orchid.Core.File.LoadFamily.varN-varN.Small.png
```

**Comment by alfarok** [comment]
Awesome, it appears the IList becomes an Array of arbitrary rank which is where varN comes from.  Thanks for bringing this up, I will update the wiki to reflect this type of scenario.
