### ISSUE TITLE
Code Blocks crashes dynamo v.1.3 and v.2.0 after installing v.2.0

### ISSUE THREAD

**Issue by thp44** [DynamoDS/Dynamo#8847]
Using a newly created code block crashes Dynamo every time! 

## Dynamo version

Both 1.3 and 2.0 after installing Dynamo 2.0

## Operating system

Windows 10

**Comment by ramramps** [comment]
@thp44 Can you give more details here? did you get any stack trace?  What is the revit version here?

**Comment by thp44** [comment]
@ramramps 

I have uninstalled all packages. I double click on the canvas to get a code block and get a weird looking code block. When I'm deselection the code block dynamo crash. 

Print screen:
https://i.imgur.com/CRSsdNh.png

**Comment by ramramps** [comment]
https://forum.dynamobim.com/search?q=avalonedit

**Comment by mjkkirschner** [comment]
@thp44 checking in to see if /how you resolved this?

**Comment by thp44** [comment]
Hi @mjkkirschner 
Just had a minor holiday..
I just uninstalled pyrevit. it solved the problem :-)

**Comment by Racel** [comment]
Closing this since it seems to be resolved.
