### ISSUE TITLE
Wish: Configurable paths for definitions and package folders

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#885]
Seeing that I just broke my Parallels image (and my last backup is a few weeks old because there's nothing to backup on that image - oh wait - except maybe for my Dynamo folder) I'd like to make a request:
It would be great to be able to configure a path for the definitions and the packages folders outside of the Dynamo folder - basically like how we can specify where our family library is located in Revit.
(Yes, I am aware that I could install Dynamo to an other directory than the default directory - but I'd like to be able to separate "core" from "content".)

**Comment by jbenoit44** [comment]
count me in, I have to deploy for 10 users. I need a way to point a specific folder on our server.

**Comment by pboyer** [comment]
See this @kronz!  It will happen soon friends!

**Comment by LukeyJohnson** [comment]
Definitely needed if we are to make Dynamo 'deployable'. I think the ideal feature would be:
Open DYN file
Dynamo detects missing packages and offers to install them from web
This way, you could use a big master Dyn or something as a deployment tool

**Comment by andydandy74** [comment]
This was introduced in 0.8.2 - thanks!
