### ISSUE TITLE
Polycurve: included points

### ISSUE THREAD

**Issue by GinoKoolman** [DynamoDS/Dynamo#8852]
## Dynamo version

1.3.2

## Operating system

Windows 7 Enterprise

## What did you do? 

I created a polycurve from a list of points, when checking the startpoint of the polycurve it doesn't match the first point from my list nor is it in the range of the polycurve

## What did you expect to see?

the first point in my list as startpoint of the polycurve

Is this a bug, any workarounds? 

![image](https://user-images.githubusercontent.com/39132473/39828359-f1e75fe2-53ba-11e8-826d-a596f10ec04e.png)

**Comment by dimven** [comment]
Have you tried changing the geometry working range of Dynamo (you'll find it under Settings)? Those coordinates are quite big (from a unitless point of view) and might be interfering with the inner workings of the geometry kernel.

**Comment by GinoKoolman** [comment]
Thanks Dimitar, i switched from XL to L and it works fine so far.
