### ISSUE TITLE
Excel.ReadFromFile failing

### ISSUE THREAD

**Issue by KuriPitomi** [DynamoDS/Dynamo#8857]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.3.4111

## Operating system

Windows 10 Pro

## What did you do? 

Trying to create sheets in Revit from an Excel File. Opened up the "ImportExport_Excel to Dynamo.dyn" sample script and noticed the errors.

## What did you expect to see?

Being new to Dynamo, I am not sure what the sample script results should be. So, I looked into the first warning, "Warning: Excel.ReadFromFile operation failed," and there appears to be others experiencing similar problems.

A suggestion was to disable hardware acceleration in Excel. Even after disabling, the problem persists.

## What did you see instead?

Please refer to the preceding answer.

**Comment by jnealb** [comment]
@KuriPitomi Are you able to launch Excel on the machine (eg is Office registered etc)? Which version of Office do you have installed? What OS are you running?

**Comment by KuriPitomi** [comment]
Yes, I can launch Excel. I am running Excel 2016; Office 365 Business.
The OS is Windows 10 Pro

**Comment by jnealb** [comment]
Is Office then the 64bit edition?

**Comment by KuriPitomi** [comment]
Yes, 64bit.

**Comment by jnealb** [comment]
@KuriPitomi Thanks; this limitation is tracked internally with QNTM-3434 and is included in our backlog for the 2.1 release of Dynamo. A workaround is of course to revert to the 32bit edition of Office.
