### ISSUE TITLE
Sheet.ByNameNumberTitleBlockAndView fails on empty View

### ISSUE THREAD

**Issue by DavePlumb** [DynamoDS/Dynamo#8858]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2

## Operating system

Windows 7 SP1

## What did you do? 

Use Sheet.ByNameNumberTitleBlockAndView node to create a Sheet and place a View on it.

## What did you expect to see?

View placed on Sheet

## What did you see instead?

The node works properly provided there is something visible in the View being placed.
However, if the View is completely empty, the node simply fails to place the View on the Sheet.
This is expected Revit behavior, so there's really nothing "wrong" with the node.
It's just that I'd expect the node to throw an error or a warning saying that it failed to place an empty View

**Comment by johnpierson** [comment]
Interestingly enough, this is kind of a neat OOTB way of creating an empty sheet. 😁 
![image](https://user-images.githubusercontent.com/15744724/46163058-563b6600-c247-11e8-8e31-2fb73ce8d36e.png)
