### ISSUE TITLE
Wish: List members alphabetically in Dynamo API reference

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8881]
## Dynamo version

N/A

## Operating system

N/A

## What did you do? 

Visited https://dynamods.github.io/DynamoAPI/

## What did you expect to see?

Class members listed alphabetically

## What did you see instead?

Class members *not* listed alphabetically
FYI @Racel As per our email correspondence I am filing this as an issue
![grafik](https://user-images.githubusercontent.com/3014437/40327782-708bb37e-5d44-11e8-8535-6b71b03ceb9a.png)

**Comment by mjkkirschner** [comment]
not really a response to this bug, but:
https://www.fuget.org/packages/DynamoVisualProgramming.Core

**Comment by andydandy74** [comment]
Sweet! It even has diffing capability!
