### ISSUE TITLE
Cannot run unit tests when inheriting from Dynamo TestServices classes

### ISSUE THREAD

**Issue by radumg** [DynamoDS/Dynamo#8882]
## Dynamo version
2.0
## Operating system
Win 10

## What did you do? 

Followed instructions from here : 
https://github.com/DynamoDS/Dynamo/wiki/Writing-Unit-Test-Libraries-for-Dynamo

wrote 2 tiny unit tests :

```csharp
[TestFixture]
    public class TestClass : GeometricTestBase
    {
        [Test]
        public void PassingTest()
        {
            // TODO: Add your test code here
            Assert.Pass("Your first passing test");
        }

        [Test]
        public void DynamoRefTest()
        {
            var g = Cuboid.ByLengths();
            Assert.IsNotNull(g);
            Assert.AreEqual(1, g.Length);
            Assert.AreEqual(1, g.Width);
            Assert.AreEqual(1, g.Height);
        }
    }
```

## What did you expect to see?

NUnit test explorer picks up tests and runs them.

### With Inheritance
When the `TestClass` inherits from `GeometricTestBase`, unit tests are discovered but cannot run any more. This includes the `PassingTest` which simply does `Assert.Pass()`

![image](https://user-images.githubusercontent.com/11439624/40378572-dad54004-5deb-11e8-99b6-ae090711549b.png)

Console reads this when running the tests :
```
[21/05/2018 22:23:21 Informational] ------ Run test started ------
[21/05/2018 22:23:22 Informational] NUnit Adapter 3.10.0.21: Test execution started
[21/05/2018 22:23:22 Informational] Running all tests in C:\Users\radug\Desktop\TestLib\bin\Debug\TestLib.dll
[21/05/2018 22:23:22 Informational] NUnit couldn't find any tests in C:\Users\radug\Desktop\TestLib\bin\Debug\TestLib.dll
[21/05/2018 22:23:23 Informational] NUnit Adapter 3.10.0.21: Test execution complete
[21/05/2018 22:23:23 Warning] No test is available in C:\Users\radug\Desktop\TestLib\bin\Debug\TestLib.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[21/05/2018 22:23:23 Informational] ========== Run test finished: 0 run (0:00:01.1898018) ==========
```

### Without inheritance
When the inheritance is removed, NUnit discoveres the tests and the `PassingTest` passes, but the `DynamoRefTest` no longer passes as `LibG.Interface` assembly fails to load.

![image](https://user-images.githubusercontent.com/11439624/40378600-f203d5a6-5deb-11e8-80ac-5a58328e7073.png)

Note that the `TestServices.dll.config` is correctly configured and the all required LibG files are present in bin folder (both `LibG.Interface` and the `libg_223` folder).

### Further notes
whilst digging around, i also found these irregularities :

- Dynamo `TestServices` makes use of NUnit 2.6.2 whilst the NuGet package requires >= 2.6.3
![image](https://user-images.githubusercontent.com/11439624/40330943-90c0931a-5d46-11e8-8fcf-cfa1dcf7ffdc.png)

- there seems to be a bug filed on NUnit 3 repo with similar issue, but i'm guessing this wasn't a problem before since presumably it was tested when wiki was written ?
https://github.com/nunit/nunit/issues/2316

- i've also tried with NUnit NuGet version 2.6.3 and get same result.

Any ideas ?

cc @mjkkirschner (thanks for helping with previous unit tests!)

**Comment by mjkkirschner** [comment]
@radumg first step, use nunit adapter version 2.x not 3.x as an extension in visual studio.
then do as you did before and make sure to reference 2.x only in your tests, not 3.

**Comment by mjkkirschner** [comment]
also please see:
https://github.com/DynamoDS/DynamoSamples/issues/24 I think you might encounter that next. I think @alfarok had plans to fix it soon.

**Comment by radumg** [comment]
prize for world's fastest reply goes to... @mjkkirschner ! 👏 🎉 
Will try it out and report back.

**Comment by radumg** [comment]
Ok, switched to NUnit VS Adapter 2.1.1.0 & NuGet 2.6.3 and 
- `TestServices.dll.config` is picked up correctly
- tests now run

However, i'm now getting a `NotImplemented` exception :
![image](https://user-images.githubusercontent.com/11439624/40332252-5e98cac4-5d4b-11e8-8a04-9032a4734cd8.png)

**Comment by mjkkirschner** [comment]
okay, so now to figure out why the host factory cannot find the correct geometry methods - do you actually have ASM on this machine as well, with version 223 - ie revit 2018?

What does your test config file look like?

**Comment by jnealb** [comment]
Good thing there is a record of this conversation :)

**Comment by alfarok** [comment]
Thanks @radumg for the additional details and updating the Wiki!  @mjkkirschner @jnealb We are already tracking the issue in the Dynamo Samples link above with [QNTM-4186](https://jira.autodesk.com/browse/QNTM-4186).  Looks like an easy fix and has already been groomed for next sprint.

**Comment by radumg** [comment]
`TestServices.dll.config` looks like this : 
![image](https://user-images.githubusercontent.com/11439624/40352110-f539fcbe-5da5-11e8-80db-1001eff93367.png)

The folder it's pointing to is the build output of Dynamo 2.0 branch and has all the required LibG files in theory :
![image](https://user-images.githubusercontent.com/11439624/40352244-4002d45a-5da6-11e8-8885-10adfce8ef40.png)

If the config file is removed or path changed, i get a `FileNotFound` exception for `LibG.Interface.dll`, leading me to believe it's finding this file but not the `libg_223` folder for some reason ?

**Comment by mjkkirschner** [comment]
@radumg any luck?

**Comment by radumg** [comment]
Yay, it worked !
Thanks so much everyone for the help.
![image](https://user-images.githubusercontent.com/11439624/40441345-a82281f8-5eb8-11e8-9522-230038493811.png)

I've tried switching between x86 and x64 and it indeed fails on x86 but works on x64.
