### ISSUE TITLE
Typo in the tooltip of Arc - ByFillet ("twp" instead of "two")

### ISSUE THREAD

**Issue by guenthm** [DynamoDS/Dynamo#8884]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0.4354

## Operating system

Windows 7

## What did you do? 

Checked tool tipp of "Arc - ByFillet" function.

## What did you expect to see?

The word "two" to be spelled correctly

## What did you see instead?

"two" spelled "twp".
![arc-byfillet-speeling-error](https://user-images.githubusercontent.com/28102684/40407409-9ef3c712-5e64-11e8-998b-393ebfd2acdf.png)

**Comment by QilongTang** [comment]
@aparajit-pratap For this kind of type, we need to fix in ASM/LibG code base I suppose?

**Comment by gregmarr** [comment]
That's correct, it's in LibG.

**Comment by QilongTang** [comment]
@gregmarr @aparajit-pratap Thanks for the info. Fixed in https://git.autodesk.com/Dynamo/LibG/pull/583
https://git.autodesk.com/Dynamo/LibG/pull/585 https://git.autodesk.com/Dynamo/LibG/pull/586

**Comment by aparajit-pratap** [comment]
Thanks @QilongTang your fixes should be in the next master build. I'm closing this issue. @guenthm thanks for reporting this.
