### ISSUE TITLE
Dynamo 2.0 Dictionary watch window beneath ZT nodes doesn't display

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8885]
## Dynamo version

![image](https://user-images.githubusercontent.com/18601851/40433901-154c8e22-5ea5-11e8-874c-fdd7d0026c4c.png)

## Operating system
Win 10

## What did you do? 

Dictionary watch window doesn't display beneath a node.

![recording 12](https://user-images.githubusercontent.com/18601851/40433936-299e13fa-5ea5-11e8-8586-ad9cce436d02.gif)

Seems to only be affecting either ZT nodes, or generic dictionaries:
![image](https://user-images.githubusercontent.com/18601851/40434162-ac29ad34-5ea5-11e8-8ec6-e1a6ecd8bd09.png)

**Comment by mjkkirschner** [comment]
@aparajit-pratap was this fixed?
https://github.com/DynamoDS/Dynamo/pull/8734

**Comment by mjkkirschner** [comment]
@ThomasMahon is it possible to test on the latest daily build?

**Comment by mjkkirschner** [comment]
also @ThomasMahon just curious if you see this with your own nodes only or other ZT nodes as well? I feel like Déjà vu.

**Comment by ThomasMahon** [comment]
@mjkkirschner no nested dictionaries, 2D list of curves, and 1D list of strings. Maybe its caused by using generic types in the dictionary declaration due to the mixed return types, given that the OOTB node shown above is working?

![image](https://user-images.githubusercontent.com/18601851/40435468-9abd6d9e-5ea8-11e8-94bc-ac5d936644e1.png)

**Comment by mjkkirschner** [comment]
@ThomasMahon tough to say without the source for the nodes - but can you try removing the generics so type your dictionary <string,object> and then also or in another experiment remove the `[]` from the key names.

**Comment by aparajit-pratap** [comment]
@ThomasMahon I don't see there's a problem with `[]` in the port names either as long as they are written in the `MultiReturnAttribute` as well.

**Comment by aparajit-pratap** [comment]
Hmm, I tried it with a generic type too: 
![image](https://user-images.githubusercontent.com/5710686/40444398-4dce7d9a-5e97-11e8-8a99-b4a896cb937e.png)
![image](https://user-images.githubusercontent.com/5710686/40444410-58e7ea68-5e97-11e8-871d-927e5f3527c4.png)

**Comment by ThomasMahon** [comment]
@aparajit-pratap So the only difference I can see is no type declaration when I instantiate the list of inputs for the MultiReturn attribute:

![image](https://user-images.githubusercontent.com/18601851/40445428-f21953e4-5ec3-11e8-8837-7fccd62c190b.png)

I went ahead and tested the node using `new string[]` instead and it still fails. 

Here's the code:

```
        /// <summary>
        ///  Dictionary
        /// </summary>
        /// <param name="elements">elements</param>
        /// <returns name="Element">Element</returns>
        [MultiReturn(new[] {"Element[]", "Element1[][]"})]
        public static Dictionary<string, List<DynamoElement>> Dictionary2(List<DynamoElement> elements)
        {
            return new Dictionary<string, List<DynamoElement>>
            {
                {"Element[]", elements },
                {"Element1[][]", elements }
            };
        }
```

**Comment by ThomasMahon** [comment]
...maybe its my XML tags?

**Comment by ThomasMahon** [comment]
Yeah, its the XML tags:
![image](https://user-images.githubusercontent.com/18601851/40446799-5e1b93fa-5ec8-11e8-98b7-78f1d985e2ec.png)

So in v2.0 the `MultiReturn` attribute list, the Dictionary keys AND the XML tags all have to match otherwise this problem occurs. Is this documented anywhere?

**Comment by aparajit-pratap** [comment]
@ThomasMahon could you also share how you rewrote your xml tags in order to get it to work?

@mjkkirschner this looks like a bug to me. It seems that the xml tags conflict with the multi-return attribute in terms of port naming and since the node preview for multi-return nodes depends on port names, the preview is messed up as well. I think it should be ok to expect the multi-return attribute to match with the keys but it's a bit too much to expect the xml tags to match with everything else too. I think we should therefore make an exception for multi-return nodes and ignore the presence of xml tags in determining their port names. Thoughts?

**Comment by ThomasMahon** [comment]
@aparajit-pratap sure:

```
        /// <summary>
        ///  Dictionary
        /// </summary>
        /// <param name="elements">elements</param>
        /// <returns name="Element[]">Element[]</returns>
        // <returns name="Element1[][]">Element[][]</returns>
        [MultiReturn(new[] { "Element[]", "Element1[][]" })]
        public static Dictionary<string, List<DynamoElement>> Dictionary2(List<DynamoElement> elements)
        {
            return new Dictionary<string, List<DynamoElement>>
            {
                {"Element[]", elements },
                {"Element1[][]", elements }
            };
        }
```

I'll reopen this for the time being. If this change isn't a bug, its quite a punitive one.

**Comment by aparajit-pratap** [comment]
@jnealb could you log this as a bug? The basic issue is that the xml tags conflict with the multi-return attributes for port naming. I think we should ignore the presence of xml tags in determining port names for multi-return nodes as those are already determined by the attributes.

**Comment by jnealb** [comment]
@aparajit-pratap This is filed as QNTM-4403, please update with details if necessary.
