### ISSUE TITLE
Editing custom node properties while inside custom node workspace doesn't dirty workspace

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8894]
## Dynamo version

2.0.1.5055

## Operating system

Windows 10

## What did you do? 

Edit custom node properties while inside custom node workspace

## What did you expect to see?

The workspace to be dirtied (i.e. the asterisk appearing next to the file name in the tab & user being asked to save changes on exit).

## What did you see instead?

Nothing. Closing the custom node workspace will not prompt me to save changes (if I haven't made any changes in canvas).
I'm fairly certain this is a regression but at least in 1.3.1 the behaviour is identical.

**Comment by smangarole** [comment]
@andydandy74 Thanks for pointing it out. We have already logged this internally.
