### ISSUE TITLE
CreateSharedParameter -> character error

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#8897]
the node CreateSharedParameter doesn't read special characters like colon
![image](https://user-images.githubusercontent.com/2844374/40650380-6dec8176-6333-11e8-806f-1b48d178beb2.png)

If I remove colon from "10:   CCS Common Instance" then it works!

## Dynamo version
1.3.3 and 2.0.0

**Comment by dimven** [comment]
![image](https://user-images.githubusercontent.com/7148394/40693773-d5f57a6c-63eb-11e8-96c2-0629f89ece5f.png)

;)

**Comment by erfajo** [comment]
That is not entirely trough :-)

You can do whatever you want with shared Parameters, and inside Revit is it not a problem at all. I have maintained my SP file adding a number with a colon for the last decade or so. That gives a much better overview when you have extremely many shared parameters as I have.
I am maintaining the Danish Educational Content which is widely spread throughout Denmark in both educational institutions as well as in the industry were my content is the base.

Just test the sample file I have attached… no problem at all :-)
[Shared Parameters.txt](https://github.com/DynamoDS/Dynamo/files/2052618/Shared.Parameters.txt)

In my nodes in the **Orchid** package where I have the comparative node for FamilyDocument, I have implemented it so it takes whatever is written in the SP file, and I am using the same API as the Dynamo Team. But if it isn’t being solved I will just add my own CreateSharedParameter node.

**Comment by dimven** [comment]
Ah, I see shat you mean now - the colon's in the parameter group's name and not the parameter's name. Not sure why that would be problematic tho.

**Comment by smangarole** [comment]
@erfajo I am on 2.0.1 and I don't see the colon being a problem. It would be helpful if you can send me your graph and the packages you installed.

**Comment by erfajo** [comment]
Since nothing has happened until now, have I solved the problem by my self and coded four new nodes to use for Parameters. You may close the topic!
![addparameter 4 nodes](https://user-images.githubusercontent.com/2844374/43169839-df7d7868-8fa2-11e8-9d66-394b5eaaafd4.png)
