### ISSUE TITLE
IsConnected on PortModel should be public

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/Dynamo#8902]
I think the IsConnected property should be public:

https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Nodes/PortModel.cs#L290

At least according to this document:

http://developer.dynamobim.org/03-Development-Options/upgrade-nodes-for-dynamo-20.html

Current workaround `InPorts[0].Connectors.Any()`

## Dynamo version

2.0.1.5055

**Comment by mjkkirschner** [comment]
yep, seems this should be public.

**Comment by QilongTang** [comment]
@mjkkirschner If this is only matters to developers, I think we can commit to the 2.0.1 branch and re upload the nugets or we can fix our documentation and include the fix in 2.1

**Comment by mjkkirschner** [comment]
I think in most cases additions of new apis should be 2.1 - in which case we should add to master only.
```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

but it's all fuzzy anyway ;)

**Comment by QilongTang** [comment]
@mjkkirschner OK, let's do it in 2.1

**Comment by mjkkirschner** [comment]
@QilongTang - you fixed this yes?

**Comment by QilongTang** [comment]
@mjkkirschner Yes, mentioned in our API changes doc here https://github.com/DynamoDS/Dynamo/wiki/API-Changes#dynamocore
