### ISSUE TITLE
API: Dictionary.ByKeysValues operation failed

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/Dynamo#8912]
I'm getting an unexpected error in 2.0.1, using the Dynamo API on a custom node. The same code was working fine in 1.3. 
The error is:

> Warning: Dictionary.ByKeysValues operation failed. 
> Value cannot be null.
> Parameter name: first
> Dictionary.ByKeysValues operation failed. 

The error is thrown when dynamically adding OutPorts to a node. I've create a simplified version of my node, you can use it to replicate the issue.
To replicate it, use the code below to create a custom node, I've tweaked the `+` sign that's used to add InPorts to actually add OutPorts, but the same error happens when the action is fired by a button on the node UI or by external events. Adding a few ports behaves just fine, but after a while the error shows up without apparent reason.

```
using Dynamo.Graph.Connectors;
using Dynamo.Graph.Nodes;
using Newtonsoft.Json;
using ProtoCore.AST.AssociativeAST;
using System.Collections.Generic;

namespace Test
{
  [NodeName("Test")]
  [NodeDescription("Tetst.")]
  [NodeCategory("Test")]
  [NodeSearchTags("Test")]
  [IsDesignScriptCompatible]
  public class Test : VariableInputNode
  {

    [JsonConstructor]
    private Test(IEnumerable<PortModel> inPorts, IEnumerable<PortModel> outPorts) : base(inPorts, outPorts)
    {
      ArgumentLacing = LacingStrategy.Disabled;
    }

    public Test()
    {
      InPorts.Add(new PortModel(PortType.Input, this, new PortData("In", "")));
      RegisterAllPorts();

      ArgumentLacing = LacingStrategy.Disabled;
    }

    public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
    {
      var associativeNodes = new List<AssociativeNode>();
      for (var i = 0; i< OutPorts.Count; i++)
      {
        associativeNodes.Add(AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(i), AstFactory.BuildStringNode(i.ToString())));
      }
      return associativeNodes;
    }

    protected override void AddInput()
    {
      OutPorts.Add(new PortModel(PortType.Output, this, new PortData("out" + (OutPorts.Count + 1), "")));
      RegisterAllPorts();
      OnNodeModified(true);
    }

    protected override string GetInputName(int index)
    {
      return "item" + index;
    }

    protected override string GetInputTooltip(int index)
    {
      return "Layer " + InPorts[index].Name;
    }

    public override bool IsConvertible
    {
      get { return true; }
    }

    protected override void OnConnectorAdded(ConnectorModel obj)
    {
      base.OnConnectorAdded(obj);
    }
  }
}

```

![image](https://user-images.githubusercontent.com/2679513/40944055-a46eb4ce-6853-11e8-85ab-17dc5b77bc06.png)

**Comment by jnealb** [comment]
@aparajit-pratap Any thoughts?

**Comment by aparajit-pratap** [comment]
@teocomi I think the node is executing each time you add an output port in `AddInput` at the `OnNodeModified(true);` statement call. Try omitting this statement as `OnNodeModified` triggers a node execution/update immediately. If you look at the base class implementation of `AddInput`, you'll see that there is no call to `OnNodeModified`.

**Comment by teocomi** [comment]
Thanks @aparajit-pratap , no error shows up if I remove `OnNodeModified(true);` but I would actually like to execute the node immediately and return some values... Is that not possible at all?
In Dynamo 1.3 this behaved just fine.

**Comment by teocomi** [comment]
Hi @aparajit-pratap I've dug a bit more into this and can replicate the issue also *without expiring the node right after registering new ports*.

To reproduce the issue you can use the code below, the `+` button adds a new port, the `-` button expires the node. After the 3rd port is added, and then expired, the warning shows up.

Dynamo is throwing an exception at https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/DesignScriptBuiltin/Dictionary.cs#L31

And the method `ByKeysValues` is called two times when the node fails, the first time keys and values are fine, the second time the `key` is null.

```
using Dynamo.Graph.Nodes;
using Newtonsoft.Json;
using ProtoCore.AST.AssociativeAST;
using System.Collections.Generic;

namespace Test
{
  [NodeName("Test")]
  [NodeDescription("Tetst.")]
  [NodeCategory("Test")]
  [NodeSearchTags("Test")]
  [IsDesignScriptCompatible]
  public class Test : VariableInputNode
  {

    [JsonConstructor]
    private Test(IEnumerable<PortModel> inPorts, IEnumerable<PortModel> outPorts) : base(inPorts, outPorts)
    {
      ArgumentLacing = LacingStrategy.Disabled;
    }

    public Test()
    {
      InPorts.Add(new PortModel(PortType.Input, this, new PortData("In", "")));
      RegisterAllPorts();
    }

    protected override void AddInput()
    {
      DispatchOnUIThread(() =>
      {
        OutPorts.Add(new PortModel(PortType.Output, this, new PortData("out" + (OutPorts.Count + 1), "")));
        RegisterAllPorts();
      });
    }

    protected override void RemoveInput()
    {
      OnNodeModified(true);
    }

    public override IEnumerable<AssociativeNode> BuildOutputAst(List<AssociativeNode> inputAstNodes)
    {

      var associativeNodes = new List<AssociativeNode>();
      for (var i = 0; i < OutPorts.Count; i++)
      {
        associativeNodes.Add(AstFactory.BuildAssignment(GetAstIdentifierForOutputIndex(i), AstFactory.BuildStringNode("aaaaaaa")));
      }
      return associativeNodes;
    }

    protected override string GetInputName(int index)
    {
      return "item" + index;
    }

    protected override string GetInputTooltip(int index)
    {
      return "item" + index;
    }
  }
}
```

**Comment by mjkkirschner** [comment]
@teocomi do you have the full stack trace?
I think this might just be coming from the preview output for the node.

**Comment by teocomi** [comment]
@mjkkirschner I only get this:
```
Value cannot be null. Parameter name: first
   at System.Linq.Enumerable.Zip[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)
   at DesignScript.Builtin.Dictionary.ByKeysValues(IList`1 keys, IList`1 values) in C:\code\Dynamo\src\Libraries\DesignScriptBuiltin\Dictionary.cs:line 31
```
The `key` in the dictionary is null, the `values` instead are there.

**Comment by aparajit-pratap** [comment]
@teocomi I ran your code and could reproduce the issue. What I think is happening is that each time a new output port is added to your node, new assignments are generated to the same output variable for the node:
```
// Click + 
...

// Click +
var_out0 = "0";
var_out1 = "1";
var_result = Dictionary.ByKeysValues(["out1", "out2"], [var_out0, var_out1]);

// Click +
var_out0 = "0";
var_out1 = "1";
var_out2 = "2";
var_result = Dictionary.ByKeysValues(["out1", "out2", "out3"], [var_out0, var_out1, var_out2]);

AND
var_result = Dictionary.ByKeysValues(null, [var_out0, var_out1]); // is executed again
```
What I cannot figure out why the last statement is executed again.

**Comment by mjkkirschner** [comment]
@aparajit-pratap if the extra execution is due to associative update would it have occurred in 1.3?
I guess @teocomi could also try placing the entire AST inside an imperative AST node.


Is it possible the final call is due to this use of dictionary for preview bubbles?
https://github.com/DynamoDS/Dynamo/blob/c4a3305559c04f04e6757a5db8a55bc98eae6c15/src/DynamoCore/Graph/Nodes/NodeModel.cs#L1302

**Comment by teocomi** [comment]
@aparajit-pratap I'm now generating new AST identifiers, but I'm not sure how to map them to the OutPorts? 
I've tried following code in the `CodeBlockNode`  but that's using `BinaryExpressionNode` and could not get `GetAstIdentifierForOutputIndexInternal()` to work on a `StringNode`...

@mjkkirschner wouldn't know where to start, any sample would be much appreciated 💯 

Thanks both!

**Comment by mjkkirschner** [comment]
small update.

@aparajit-pratap @teocomi I think I have tracked this down the preview bubble generation. All nodeModels have another AST which represents the code to build a dictionary or list which represents the previewBubble value.

When I replace the call to generate the dictionary output preview bubble value, with a simple string or don't return a preview bubble value, I cannot reproduce the issue.

@aparajit-pratap looks like some kind of bug in the this bit of code.
https://github.com/DynamoDS/Dynamo/blob/c4a3305559c04f04e6757a5db8a55bc98eae6c15/src/DynamoCore/Graph/Nodes/NodeModel.cs#L1302

I guess it could also be related to associative update triggering the preview bubble to update in a strange state - As this is not really a workaround I will keep looking for some other temporary fix that can be used by @teocomi for now.

**Comment by teocomi** [comment]
Thanks @mjkkirschner !!

**Comment by teocomi** [comment]
@aparajit-pratap @mjkkirschner is there any update on this? 
Maybe a workaround to disable the preview bubble?

**Comment by mjkkirschner** [comment]
@teocomi - apologies, lost track of this issue, have you found a workaround or seen this any longer in newer versions of Dynamo?

**Comment by teocomi** [comment]
@mjkkirschner - couldn't find any workarounds, issue still happening with 2.1.0

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
