### ISSUE TITLE
Unsaved work crash recovery does not save Home workspace if crash happens while editing custom node

### ISSUE THREAD

**Issue by Dewb** [DynamoDS/Dynamo#8913]
## Dynamo version

2.1.0.4395 (local build from Github head)

## Operating system

Windows 10

## What did you do? 

1. Run Dynamo Sandbox
2. New Workspace
3. Create a code block node with the contents `msg = "Important info I want to save";`
4. Create another code block node with the contents `str + " and other stuff";`
5. Connect the output of the first CBN to the input of the second CBN
6. Select the second CBN and go to Edit > Create Custom Node...
7. Enter any values for name/description/category and hit OK
8. Click the tab for the new custom node workspace.
9. Edit the CBN node in the custom node to reproduce the crash from #8911 by adding the second line `a = 1...10;`
10. See crash dialog saying "You will get a chance to save your work." Hit Continue.
11. See Confirmation dialog saying "You have unsaved changes to the Home workspace. Would you like to save your changes?" Hit Yes.
12. Get Save As dialog with Home.dyn prefilled as the file name. Change filename to "crashed home.dyn"
13. Dynamo exits.
14. Reopen Sandbox and open "crashed home.dyn"
15. Contents of "crashed home.dyn" are the contents of the custom node, not the home workspace.

## What did you expect to see?

At minimum, I expect to see my unsaved Home workspace, since that is what Dynamo told me it was saving. Even better would be separate prompts to save both the Home and the Custom Node workspaces.

## What did you see instead?

Only the custom node workspace was saved, and it was mis-described as the Home workspace.

**Comment by jnealb** [comment]
@Dewb Thank you for the detailed report: this is tracked with QNTM-4423 and is in the 2.1 backlog.

**Comment by QilongTang** [comment]
PR for fixing this: https://github.com/DynamoDS/Dynamo/pull/10119
