### ISSUE TITLE
Dropdown / NodeModel producing multiple outports

### ISSUE THREAD

**Issue by kraftwerk15** [DynamoDS/Dynamo#8919]
## Dynamo version

Dynamo Core - 2.0.0.4654
Dynamo Revit - 2.0.0.4655

## Operating system

Windows 10

## What did you do? 

Saved the file with dropdowns in the file. 

## What did you expect to see?

Only one outPort per dropdown.

## What did you see instead?

After opening the file, there are additional outPorts to the node.

Image:
![image](https://user-images.githubusercontent.com/30668448/41112144-c574e0b6-6a43-11e8-977b-4a1fdc78fdd4.png)

My node from my library is in the upper left corner. WorksetKind and WorksetVisibility are from Konrad's archi-lab package. Did this to confirm it was his package or mine, but it is both. Confirmed also this was not just in the session. I closed down the Dynamo and Revit applications. Problem still exists. After running, the node will return null.

Also wanted to note that the previous test was in a graph that was promoted to 2.0. Below shows that it is not related to that upgrade. This is a new graph in 2.0 showing the same issue.

![image](https://user-images.githubusercontent.com/30668448/41115196-690de224-6a4c-11e8-96fd-b7ada0c22c18.png)

**Comment by mjkkirschner** [comment]
Either the packages have not been updated - or a package is installed which contains json.net or some other dependency that is causing json.net deserialization failure.

**Comment by smangarole** [comment]
Closing this issue for now. Please re-open if further input is needed.

**Comment by kraftwerk15** [comment]
Sorry guys, just getting back to this from working. I continue to get this error with others packages as well. You will notice I **removed** my package from the managed packages location and removed archi-lab. This is Rhythm package producing the same error.

![image](https://user-images.githubusercontent.com/30668448/41128966-9e88562c-6a75-11e8-9351-1e77b3530308.png)

**Comment by mjkkirschner** [comment]
Rhythm is also not updated for 2.0- try removing all packages but your own. Also do you distribute Json.net with your package dlls? Hint : don’t 😉

**Comment by kraftwerk15** [comment]
You're right. My process, please tell me what I'm doing wrong, was taking the Dropdown example here: https://github.com/DynamoDS/DynamoSamples/blob/master/src/SampleLibraryUI/Examples/DropDown.cs#L23

Adding newtonsoft.json via nuget. Then flagged this to Copy Local to false. Build Project that copies to the location.

The image below shows the example cs from above with the [JsonConstructor] per the example. Image also shows all usings and references, in case that is an issue.

![image](https://user-images.githubusercontent.com/30668448/41161280-f1cd8302-6af7-11e8-8623-a4a9c23b7b9b.png)

**Comment by mjkkirschner** [comment]
@kraftwerk15 one thought - try referencing newtonsoft json.net version 8.03.
 you're also referencing a bunch of dynamo core dlls - are these version 2.0 dlls? Do you have them set to copy local false?

**Comment by mjkkirschner** [comment]
can you share an image of your package bin folder as well? 
And please confirm you are attempting to only load your own package with all others removed to remove variables.

**Comment by kraftwerk15** [comment]
@mjkkirschner 
Dynamo 2.0 package location:

![image](https://user-images.githubusercontent.com/30668448/41162921-e9c90a50-6afc-11e8-836b-cb3a7ec7e2aa.png)

Specific Package Bin folder:
![image](https://user-images.githubusercontent.com/30668448/41162948-fa7b54a2-6afc-11e8-9246-4a530369997c.png)

I'm waiting on a run to complete in Dynamo, then I can back out all other packages and try again. I did roll back nestonsoft to 8.0.3 and all Dynamo dlls are using /2/ folder and all Revit APIs are looking at 2018.

I did just notice that my two other dlls were using newtonsoft 8.0.3, while the Lightning2UI was using the 11.0.0. I'll test to see if it was that issue, again, once this run in Dynamo completes.

**Comment by kraftwerk15** [comment]
@mjkkirschner It looks like rolling back to Newtonsoft.Json 8.0.3 fixed the problem. The below image shows two nodes from my package at the top that are behaving correctly. Below shows archi-lab and Rhythm that are broken.

Can we add on the Wiki (https://github.com/DynamoDS/Dynamo/wiki/Update-Packages-from-1.3-to-2.0) that only 8.0.3 can be used to avoid confusion for others?

![image](https://user-images.githubusercontent.com/30668448/41165416-3596eda2-6b03-11e8-84d7-bcc505927a54.png)

**Comment by mjkkirschner** [comment]
@alfarok did we ever update the dynamo core nugets to pull version 8.03 of newtonsoft.json.net?

**Comment by kraftwerk15** [comment]
I did search on issues to see if there was an issue similar to mine and could not find anything. Looked through archi-lab's and he already commented on a similar issue here.

https://github.com/DynamoDS/DynamoRevit/issues/2039

Cross-reference to archi-lab package:
https://github.com/ksobon/archilab/issues/14

**Comment by QilongTang** [comment]
@mjkkirschner I did updated to include newtonsoft.json to be a dependency of DynamoCore nuget package
