### ISSUE TITLE
Migration to 2.0 - Inconsistent input rank for some ex-Builtin nodes

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#8939]
## Dynamo version
1.3.3 - > 2.0.1

## Operating system
N/A

## What did you do? 
Observed how nodes are migrated between versions.

## What did you expect to see?
Consistent input ranks between versions or an alternative solution (list@level on affected input ports, etc)

## What did you see instead?
Inconsistent input ranks, highlighted the changes with the blue notes below:

![dynamosandbox_2018-06-21_21-04-56](https://user-images.githubusercontent.com/7148394/41721235-f0f66566-7597-11e8-8493-fb1375892406.png)

This will negatively affect new and inexperienced users, there's already been a few topics about the inconsistency:

Note that the List.IndexOf's functionality now completely overlaps with the "List.FirstIndexOf" node and one of them is redundant.

https://forum.dynamobim.com/t/dynamo-2-0-list-items/21313/14

https://forum.dynamobim.com/t/list-map-old-1-3-3-vs-new-2-0-1/22962/9

**Comment by dimven** [comment]
Another post relevant to the above:
https://forum.dynamobim.com/t/copying-rebar-from-one-element-to-another-reload/23009

**Comment by aparajit-pratap** [comment]
@dimven your observations are correct. This rationalization of the nodes was done in a deliberate manner so as to reduce the number of redundant nodes we had in the Dynamo library and to reduce user ambiguity between which nodes to use. 

In general we have adopted a consistent approach of removing the overloads that had lower argument rank(s) in favor of the overload with the higher input rank(s). For example, `Equals(var, var) => List.Equals(var[]..[], var[]..[])`. The reason why these were found to be redundant is that what one can do with the lower ranked overload can also be achieved by the higher ranked overload with a combination of replication guides OR list@level. See this [post](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-2.0-Language-Changes-Explained#2-overloaded-functions-with-parameters-that-only-differ-by-rank-are-illegal) for a more detailed explanation.

In addition we did some recategorization of the nodes and brought all built-in nodes that were related to lists under the `List` category.

**Comment by dimven** [comment]
I understand what you've done and why you needed to proceed in such manner. Some of the listed nodes did not always have multiple input overloads/versions. I'd just wanted to point out that the new alternatives don't necessarily process their inputs in the same manner. Thus migrating these nodes to a newer version of Dynamo leads to unpredictable and hard to spot side effects.

If there are similar cases in the future, consider posting a detailed migration guide or making sure that the migrated version acts identically through the necessary lacing/list@level settings...
