### ISSUE TITLE
3D view 

### ISSUE THREAD

**Issue by EricM007** [DynamoDS/Dynamo#8940]
## Dynamo version

Dynamo core 2.0.0.4354

## Operating system

Windows 10 - 64 bits

## What did you do? 

Activate the 3d background view

## What did you expect to see?

3d background view

## What did you see instead?

No access to the 3D background menu ( frozen menu )
![image](https://user-images.githubusercontent.com/40466120/41723431-526ef42a-756b-11e8-98bb-449a7e39e1ad.jpg)

**Comment by smangarole** [comment]
@EricM007 I cannot reproduce this on Win 10 and 2.0.0.4654. Can you please see if you can re-install? The stable builds are available on dynamobuilds.com

**Comment by mjkkirschner** [comment]
@EricM007 please read this:

https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by EricM007** [comment]
Thank you for your feedback.
@smangarole, I will try to re-install the soft with stable builds. I will post to give you the result.
@mjkkirschner, done and applied.
