### ISSUE TITLE
ZeroTouchNode crashes when dragging a connected number slider

### ISSUE THREAD

**Issue by aliasguru** [DynamoDS/Dynamo#8942]
## Dynamo version

Dynamo for **Alias**

## Operating system

Windows 10

## What did you do? 

I'm developing Zero Touch Nodes for certain geometry operations. One of the Nodes takes input geometry, extracts a plane from that, and rotates the input around said plane. The code is:

        public static D.Geometry[] SourcePatternPlacement(D.Surface[] Pattern, double RotationAngle = 0.0, double TranslateX = 0.0, double TranslateY = 0.0)
        {
            if (Pattern.Length < 5)
            {
                throw new ArgumentException("Must have at least five Elements in Pattern", "Pattern");
            }

            D.Point pOrigin = Pattern[0].PointAtParameter();
            D.Point pU = Pattern[2].PointAtParameter();
            D.Point pV = Pattern[4].PointAtParameter();

            D.Plane basePlane = D.Plane.ByThreePoints(pOrigin, pU, pV);

            int _len = Pattern.Length;
            D.Geometry[] res = new D.Geometry[_len];

            for (int i = 0; i < _len; i++)
            {
                res[i] = Pattern[i].Rotate(basePlane, RotationAngle).Translate(basePlane.XAxis, TranslateX).Translate(basePlane.YAxis, TranslateY);
            }

            //GC
            pOrigin.Dispose();
            pU.Dispose();
            pV.Dispose();
            basePlane.Dispose();

            return res;
        }

When adding that node to my scene, it works at first run. However, if I connect a number slider to the Rotation input socket, and drag for a while, Dynamo crashes. Typing in the values most of the time works fine. I have no chance / idea on how to use the Debugger of VS with Dynamo for Alias, or on how to install Dynamo Sandbox (I don't have Revit), if you could support me there you're more than welcome.

## What did you expect to see?

no crashes on dragging the slider

## What did you see instead?

KABOOM

**Comment by smangarole** [comment]
@mjkkirschner @ramramps Any ideas?

**Comment by mjkkirschner** [comment]
There are a bunch of intermediate surfaces in the for loops which are not disposed.

What is the stack trace.

**Comment by mjkkirschner** [comment]
Debugging is simple, start visual studio after dynamo and alias start, and Debug -> attachToProcess -> find Dynamo process.

**Comment by aparajit-pratap** [comment]
@aliasguru can you try this:
```
for (int i = 0; i < _len; i++)
        {
            temp1 = Pattern[i].Rotate(basePlane, RotationAngle);
            temp2 = temp1.Translate(basePlane.XAxis, TranslateX);
            res[i] = temp2.Translate(basePlane.YAxis, TranslateY);
            temp1.Dispose();
             temp2.Dispose();
        }
```

**Comment by aliasguru** [comment]
@aparajit-pratap I tried your suggestion and it worked! So far no more freezes when pulling the slider. So, for my understanding: It is mandatory to catch intermediate geometry and `dispose()` it as well? Because, I was of the opinion that if I don't assign a variable, Garbage Collection would take care of the items in any case.

@mjkkirschner Thanks for the Debugging tip, this works well. Huge improvement in terms of developing!

Thanks everyone who contributed, guess this ticket can be closed.
