### ISSUE TITLE
I can not download dyno 0.7.1 . Please sent it to me if you have

### ISSUE THREAD

**Issue by hauvovan** [DynamoDS/Dynamo#8947]
I can not download dyno 0.7.1 . Please sent it to me if you have it.

I create new account but I can download it. I don't know why I cant get link

if you had download it please sent me. My email haucpe@gmail.com

Please help me
thank you very much

**Comment by mjkkirschner** [comment]
please contact the author of dyno:
http://prorubim.com/en/tools/dyno/

or post on the dynamo forum
https://forum.dynamobim.com.

**Comment by mjkkirschner** [comment]
if by chance you actually meant "dynamo .71" please try from here:
http://dynamobuilds.com

**Comment by hauvovan** [comment]
thank you very much. but I need dyno 0.7.1 plugin . however I cant download it
