### ISSUE TITLE
Dynamo 2.0 error when open custom node ?

### ISSUE THREAD

**Issue by hauvovan** [DynamoDS/Dynamo#8949]
I just install dynamo 2.0 and i create new custom node. i save in D:// success. Later, i close and open this custom node and appear error, revit 2018 auto closed when i open a custom node.

I try make a very single custom node. However, when open a any custom node, revit auto shutdow.
i try uninstall dynamo and reinstall 3 times but this error not yet . 
Please help resolve this problem.

thank you

**Comment by smangarole** [comment]
@hauvovan can you try saving the custom nodes in a new folder by itself. If the folder location has other custom nodes and 1.3 files, it's highly likely that you will see a crash when you open it up in 2.0.

Also, please provide me the exact steps to reproduce so I can help you further.

**Comment by johnpierson** [comment]
Closing this as we need more information. Please reopen and update if this is still an issue for you.
