### ISSUE TITLE
Dynamo Sandbox doesn't read Custom Nodes

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#8951]

**Comment by ramramps** [comment]
Is there any notifications? I mean, can you check if there is one by clicking the green "!" on the top?

**Comment by erfajo** [comment]
There is no notifications.

**Comment by mjkkirschner** [comment]
Hi @erfajo how is your package structured? Can you share an image of the package root directory? Are the custom nodes in a .dyf folder?

Do you have this issue with DynamoRevit?

Your package has both ZT and custom nodes?

**Comment by erfajo** [comment]
It is working perfect with DynamoRevit, and after open/close one random custom node does also the DynamoSandbox work without any problems.

The package has both ZT and CN nodes... some nodes do I need to keep as CN nodes until the .net version for FEM-design and Sigma Estimates have implemented .net fully.

![image](https://user-images.githubusercontent.com/2844374/41865653-04b28c7e-78ae-11e8-88d6-0c58f4536379.png)

**Comment by mjkkirschner** [comment]
It might be worth mentioning that dynamoRevit and dynamoSandbox have different package paths. A first guess is that sandbox is pointed to your dll, but does not actually have your package installed.

Can you check the manage package paths / and manage packages menu items in sandbox so see if 1. you have installed your package in sandbox

2. you don't have an extra package path added that points to your zero touch dll only - it might be getting loaded twice and causing weirdness.

**Comment by erfajo** [comment]
Well, the dll is the only thing it loads, it is the custom nodes it doesnt load!?
the paths is as it should be... and the same as it is in DynamoRevit, so no difference.
There is one path to the folder for all packages...

The strange thing is, that my internal sandbox version works perfectly and this has the exact same structure. All four project is a part of the same solution in Visual Studio, and is being compiled at the same time. The sandbox version has also a combination of CN and ZT nodes... but it works as it should do.

**Comment by erfajo** [comment]
I have figured why my "sandbox" version works for custom nodes... They are all placed in the "definition" folder and not in the package folder. So the problem it still the same. If DynamoSandbox reads any dll file it doesnt read dyf files...

**Comment by mjkkirschner** [comment]
@erfajo I would like to try reproducing your issue in sandbox. Can you please give me the most direct steps possible to install your package that should reproduce the issue on sandbox?

**Comment by erfajo** [comment]
go here --> https://github.com/erfajo/OrchidForDynamo
I have also an executable file that takes care of the installation process for you if that is easiere.

**Comment by erfajo** [comment]
Just to include a screendump from DynamoRevit and DynamoSandbox side-by-side. The custom nodes should be the same in that "subfolder"
![image](https://user-images.githubusercontent.com/2844374/42057869-f2b805c6-7b1e-11e8-80f8-76de0c0b1e7b.png)

**Comment by mjkkirschner** [comment]
Hi @erfajo I can reproduce this and I think I know whats going on - I fear you will not like the reason 😄 .

It appears your package has a dependency on the revit API. When Dynamo attempts to load your dlls it cannot as it fails to find the required dependencies, this throws an exception, at this point the first dll is loaded, the revit one fails to load, but the custom nodes never load as a result of the exception.

I found this in the dynamo console:

```
Exception when attempting to load package Orchid from C:\Users\kirschm\AppData\Roaming\Dynamo\Dynamo Core\2.1\packages\Orchid_200
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

When I find the full exception it states:
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'RevitAPI, Version=18.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'
```

Which makes sense.

I think there are two solutions:
1. Dynamo still throws an exception, but not until after loading the rest of the package.
2. You break your package into two parts, a sandbox version which only contains the core dlls, and a revit one which depends on both of your dlls.

**Comment by erfajo** [comment]
Sorry for being late... I had other matters to attend to :-)

You are right, I don't like this. Shouldn't It be an option to load the same package and then let the Sandbox version dismiss the assemblies there are dependent on the Revit assembly?

It has been working previously so it must be a bug in the newer versions...

**Comment by erfajo** [comment]
@mjkkirschner 
I think I have an idea there can solve the issue. The problem is as you say Michael the assemblies you feed the dynamosandbox with. Since I (and many others) has split their packages into nodes that uses Revit API and not, could you then add this information into the pkg.json file? 

Meaning dynamo trough Revit reads "node_libraries" and dynamosandbox read "node_libraries_sandbox" e.g.

```
{
  "... all the other informations ...",
  "node_libraries": [
    "OrchidCore, Version=130.3.0.6793, Culture=neutral, PublicKeyToken=null",
    "OrchidRevit, Version=130.3.0.6793, Culture=neutral, PublicKeyToken=null"
  ],
  "node_libraries_sandbox": [
    "OrchidCore, Version=130.3.0.6793, Culture=neutral, PublicKeyToken=null"
  ]
}

```
