### ISSUE TITLE
[DefaultArgument("false")] is not read in RevitSandbox 2.0.1+

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#8958]
## Dynamo version
DynamoSandbox 2.1.0+

## Operating system
windows 10

## What did you do? 
used the same node from my package (**Orchid**) in DynamoRevit and DynamoSandbox.

## What did you expect to see?
I expected that [DefaultArgument("false")] would be read!

## What did you see instead?
In dynamoSandbox is [DefaultArgument("false")] not being read!

DynamoSandbox
![image](https://user-images.githubusercontent.com/2844374/42048533-d2cb7d12-7b03-11e8-889d-0b46778b3d67.png)

DynamoRevit
![image](https://user-images.githubusercontent.com/2844374/42048537-d60f287a-7b03-11e8-80d2-435fe5539c17.png)

It works as expected in the Dynamo 1.3.0+ versions

**Comment by mjkkirschner** [comment]
@erfajo this seems very unlikely. DynamoCore contains the functions to load attributes- these functions are the same between dynamoSandbox and DynamoRevit.

This indicates to me that a few things could be going on:
1) You are loading different versions of your dlls into dynamo revit vs dynamo sandbox. Please check both your dynamo revit and dynamo sandbox package folders and make sure you have the same dlls there.

2) when you import a dll directly into dynamo 2.0 it adds a path to that dll to the manage package path settings window and will load it automatically on next startup - this could cause issues if you're trying to load it from a package as well, please check the manage package path settings menu in both environments (sandbox and revit) to check there is not an unexpected path pointing to your dll.

**Comment by erfajo** [comment]
hi @mjkkirschner 
I have tested that I am not doing any rookie failures... and I do only write because I think it is something to be fixed…

Below is my JSON pkg file. As you can see, I load first the DLL file which works both in DynamoRevit and DynamoSandbox, and the latter works only in DynamoRevit. You need to load them as this and you need to have names in an alphabetic order since dynamo cant handle it. This is an error well described, we don’t need to discuss this here in this thread.
…AND no, it doesn’t play any role if the Custom nodes are included in the JSON file or not, that is also tested.

My path is exactly the same in DynamoRevit and DynamoSandbox

```
{
   "license":"GPL-3.0 (This package is covered by the 'License.rtf' in the 'extra' folder)",
   "file_hash":null,
   "name":"Orchid",
   "version":"200.2.02",
   "description":"Orchid is a collection of practical nodes. The package is designed to support logic, technical, and mathematical solutions. In particular, many solutions are implemented as recursive functions, which means that solutions can solve nD-list challenges. In addition, the package also contains solutions that can be used working with Revit families. Furthermore, solutions for external applications included in the BIM wheel are supported, which not necessarily are Autodesk products. These solutions include e.g. solutions for estimation and load bearing challenges.\n\n---\nHistory of Orchid:\nPlease see 'License.rtf' in the 'extra' folder or on the github repository.\n\nVersioning:\nThe major number follows the Dynamo version, e.g. 200.x.x is usable in Dynamo +2.0.0.x versions. The Minor number is internal minor builds. The build number is an internal build number.\n\nSoftware environment: Built for Dynamo +2.0.0 and Revit +2017.\n\n---\nMore information: Contact @erfajo at https://forum.dynamobim.com, https://forum.dynamobim.com/u/erfajo",
   "group":"Orchid",
   "keywords":["orchid","erfajo","logic","technical","mathematical","recursive","element","list","family","type","instance"],
   "dependencies":[],
   "contents":"Install or Update Orchid - How to install or update the Orchid package?",
   "engine_version":"2.0.0.4655",
   "engine":"dynamo",
   "engine_metadata":"",
   "site_url":"",
   "repository_url":"https://github.com/erfajo/OrchidForDynamo",
   "contains_binaries":true,"node_libraries":[
      "OrchidCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
      "OrchidRevit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null"
   ]
}
```

**Comment by mjkkirschner** [comment]
@erfajo thanks for the explanation, definitely want to get to the bottom of it, but have to start with gathering the system's setup state to debug efficiently :).
I will try to replicate. Another thought - do you have any other packages installed in sandbox that you do not have in your dynamoRevit packge folder?

For example, Lunchbox bundles version 1.3 of dynamoSerivces.dll with their package - this will break packages that load version 2.0 of that dll as it forces 1.3 to be loaded... this could cause your issue as the `DefaultArgumentAttribute` is in that dll.

If you have the time, I would ask that you try removing all other packages/dlls but your own in the sandbox context while I find some time to repro.

**Comment by erfajo** [comment]
Thanks @mjkkirschner, that was the exact problem, it is Lunchbox that gives the error... removing that package and everything works as expected...
