### ISSUE TITLE
ViewExtension - Opening file from path issue

### ISSUE THREAD

**Issue by alvpickmans** [DynamoDS/Dynamo#8959]
## Dynamo version

2.0.1.5055

## Operating system

Windows 10

## What did you do? 

Implementing a ViewExtensions that among other things, should open a dyn file from a selected path.

## What did you expect to see?

A dyn file opened correctly

## What did you see instead?

![openfileissue](https://user-images.githubusercontent.com/12413808/42080526-e55ce8e0-7b7a-11e8-8baa-e05a83900a70.gif)

1. If Dynamo has just started and opening from extension, CodeBlock's text area is not loaded. It doesn't gets fixed until a previously saved file is opened via Dynamo interface. It also piles all nodes on the same location.
```
Error al aplicar NodeViewCustomization para CodeBlockNodeModel
System.NullReferenceException:
Referencia a objeto no establecida como instancia de un objeto.
   en Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   en Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   en Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   en Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   en lambda_method(Closure , NodeModel , NodeView )
   en Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)

```
2. If file already opened and opening another from extension, nodes keep getting placed on the same spot if file hasn't been opened before on this session.

## Aditional comments

I have tried with [both methods in link](https://github.com/alvpickmans/GitHubForDynamo/blob/master/GitHubForDynamoWPF/ViewModels/MainViewModel.cs#L225), as a new `RecordableCommand` or using `DynamoModel.OpenFileFromPath()`  with similar results . Is there another way I am missing?

I had to "manually" hide the StartPage as this wasn't handled by any of the methods above.

I also looked into using [DynamoOpenFileDialog()](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/Views/Core/DynamoOpenFileDialog.cs#L14) but for some reason is not marked as public while [DynamoFolderBrowserDialog()](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/Views/Core/DynamoOpenFileDialog.cs#L108) is.

Note: The `Open File` button is just for testing purposes.

**Comment by mjkkirschner** [comment]
@alvpickmans I think two things are occurring here:

1. I think there is a race condition that results in the node view failing to load in some cases - this occurs more frequently when opening the file in automatic mode.
2. If you open the file using the dynamo model then only the model properties will be loaded - the node positions are view properties and will not be loaded. so:


try this:
https://github.com/DynamoDS/DynamoWorkspaceUpgradeExtension/blob/master/src/migrationWindow.xaml.cs#L50

this uses a view model command to open the file.

here is the actual method this ends up calling:
https://github.com/DynamoDS/Dynamo/blob/c0e141245c9465626d84cada143d77f702c088d7/src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs#L1226

You can try sending it the `ForceManualMode` flag and see if that helps the view not loading as a workaround.

**Comment by alvpickmans** [comment]
@mjkkirschner thanks, silly that I missed that!
I also notice that the `CurrentWorkSpaceChanged` event is not raised when the workspace is closed. Is that the desired behaviour?

I´ll close this for now.
