### ISSUE TITLE
Keep List Structure

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8962]
## Dynamo version
Dynamo Core 2.1.0.5357

## Operating system
Windows 10

## What did you do? 
Checked _Keep List Structure_

## What did you expect to see?
List Input node to change color and the output to inherit the list structure of this input

## What did you see instead?
![keepliststructure](https://user-images.githubusercontent.com/5621624/42135337-46d0179e-7d67-11e8-85e0-49adbe208866.png)

**Comment by jnealb** [comment]
@aparajit-pratap @Racel Any thoughts?

**Comment by Racel** [comment]
@jnealb I can reproduce this. This is definitely a bug that I am seeing in 2.0. Can we please file? And can we discuss how we can catch this next time during testing? 

FYO @smangarole

**Comment by jnealb** [comment]
@vykrum Thank you - this is filed as QNTM-4759 and is in the 2.1 backlog.
