### ISSUE TITLE
Wish: More options for creating ref planes

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#897]
The current Reference Plane node seems to be limited to creating ref planes based on lines that need to be located on a horizontal plane (probably the ground plane or Z = 0). It would be great to have some other options, such as creating them from current workplane or a combination of origin and normal.

**Comment by ksobon** [comment]
What about something like this?

![image](https://user-images.githubusercontent.com/529781/27163744-985d684c-5157-11e7-9f3f-c82a93461342.png)

**Comment by andydandy74** [comment]
Is it christmas yet? :-)

**Comment by ColinDayOrg** [comment]
This issue has been moved to the DynamoRevit repo (#2200).
