### ISSUE TITLE
Code Block Input port issue

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#8971]
## Dynamo version
Dynamo Core 2.1.0.5357

## Operating system
Windows 10

## What did you do? 
Changed value in code block from -1 to -0.1

## What did you expect to see?
Nothing significant

## What did you see instead?
Input node for variable disappears
![inputportissue](https://user-images.githubusercontent.com/5621624/42226162-df5b437c-7efb-11e8-990b-feab3de2209e.png)

**Comment by smangarole** [comment]
@vykrum Thanks for logging this issue. I verified that the behavior is same in 1.3.2. Logging this internally.

**Comment by smangarole** [comment]
@aparajit-pratap Can you please add your inputs here?

**Comment by aparajit-pratap** [comment]
@smangarole this obviously is a bug. @vykrum thanks for pointing it out.

**Comment by jnealb** [comment]
@vykrum Thank for the report: this is filed as QNTM-4761 and is in the 2.1 backlog. @aparajit-pratap @smangarole fyi.
