### ISSUE TITLE
Some menu items in Help menu not working

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8975]
## Dynamo version

2.0.1 stable

## Operating system

Windows 10

## What did you do? 

Clicked on ```Help > Getting Started``` and ```Help > Samples```

## What did you expect to see?

Something happening

## What did you see instead?

Nothing happening
Not a regression, same behaviour in 1.3.2 as well.

**Comment by smangarole** [comment]
Tracked internally: https://jira.autodesk.com/browse/QNTM-4684
