### ISSUE TITLE
Unconnected custom nodes with multiple output ports throwing warnings 

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8976]
## Dynamo version

2.0.1 stable

## Operating system

Windows 10

## What did you do? 

Placed a custom node with multiple output ports on canvas

## What did you expect to see?

No warnings

## What did you see instead?

Warnings. Every input port will generate a ```List indices must be numeric``` warning.
This is a regression. Nodes like these don't throw warnings in 1.3.x
![grafik](https://user-images.githubusercontent.com/3014437/42258037-fb2f4c84-7f59-11e8-94e7-d89c5544b9d3.png)

**Comment by smangarole** [comment]
Hi @andydandy74 Verified that this is a regression. Thanks for logging this issue.
Note that the warning goes away when "a" is assigned a value.
![image](https://user-images.githubusercontent.com/992006/42323506-66d8c288-802e-11e8-834c-656f57c8fa9d.png)

**Comment by smangarole** [comment]
This is actually weird:
1. If you remove the CBN and custom node connection (shown in the screenshot above), the warning re-appears. Note that I do see the values in the custom node preview bubble
2. In 1.3.x the custom node output is a list and in 2.0.x, it's a dictionary

**Comment by smangarole** [comment]
@Racel @mjkkirschner Tracked internally: https://jira.autodesk.com/browse/QNTM-4683

**Comment by mjkkirschner** [comment]
@smangarole I think @aparajit-pratap just fixed this here:
https://github.com/DynamoDS/Dynamo/pull/8928

@aparajit-pratap is this the same issue?

**Comment by aparajit-pratap** [comment]
Yes @mjkkirschner this should have been fixed in #8928. @smangarole could you test if this still reproduces in master (2.1.0)? Thanks.

**Comment by smangarole** [comment]
Fixed in the latest daily build. Closing @jnealb @mjkkirschner @aparajit-pratap @andydandy74
