### ISSUE TITLE
Imperative block does not evaluate

### ISSUE THREAD

**Issue by sunfield** [DynamoDS/Dynamo#8977]
## Dynamo version

Dynamo 2.0.1

## Operating system

Windows 10

## What did you do? 

I created a CBN containing an imperative block with nested while-loops to get the desired associations between two lists that I had trouble working out through lacing.

## What did you expect to see?
Initially I got the expected result: A list of the surfaces I was looking for, like this
![problem2](https://user-images.githubusercontent.com/8625521/42278468-76ac2956-7f8a-11e8-8e36-fcabf62615ec.png)

## What did you see instead?
The next time (and every following time) I would open Dynamo, it would return an empty list. Not one external change affects this outcome - _only_ by changing the CBN in any way whatsoever, such as adding or removing a space, will get it to properly evaluate and return the list when the graph is ran.
I've tried all I can think of such as defining it as a function and calling that, explicitly assigning the inputs to variables outside the imperative block, as well as potential solutions I could find online like namespace definition outside the imperative (though I'm not using the full namespace to begin with and don't currently have any packages installed).
![problem4](https://user-images.githubusercontent.com/8625521/42278485-7ecc750a-7f8a-11e8-941e-290fb31404aa.png)

I've also tried adding additional functionality to the CBN to evaluate in hopes it would get it going but while the additional part works as expected, the desired part does not. Not even manually running the graph a second time helps since nothing updated. It _has_ to be a local change for it to evaluate correctly.

It feels a lot like needing to smack a car engine with a hammer to get it to start; fine if you're just tinkering but not what you'd want to pick your date up with...

**Comment by smangarole** [comment]
@sunfield Thanks for logging this issue. Can you send us the DYN file?

**Comment by smangarole** [comment]
@aparajit-pratap @mjkkirschner Any inputs? I agree that it's not ideal to make changes every time you want a correct evaluation.

**Comment by smangarole** [comment]
Tracked internally: https://jira.autodesk.com/browse/QNTM-4682

**Comment by sunfield** [comment]
@smangarole Thank you for your response. It's not the original file due to confidentiality restrictions, but it contains the relevant CBN and associated parts, and reproduces the issue for me identically to the description above.
All that should be required for easy reproduction is a basic room centred around 0,0 in Revit (I'm using Revit 2017 but I have no reason to believe it should matter). Otherwise adjust the coordinates in the DYN file as needed.

[Imperative Bug.zip](https://github.com/DynamoDS/Dynamo/files/2166636/Imperative.Bug.zip)

**Comment by sunfield** [comment]
@smangarole 
**I have found the cause and working solution:**
The problem is with List.Count(). It does not work correctly within an Imperative block so all the conditions in while- or for-statements need to be determined _before_ entering the imperative block. Since the sizes of the lists and sublists in my case need to be dynamic, I can't just count them inside the codeblock using List.Count() beforehand since I don't know in advance how many lists I need to count. Neither can run it in a loop since that necessitates an imperative block, let alone a loop within a loop as it involves multidimensional lists.

The only way that I have found - without resorting to learning Python - is using the List.Map node (any reason this can't be called from a CBN?) together with List.Count to produce an array of counted sublists, and then adding those as extra inputs to my method.

![solution](https://user-images.githubusercontent.com/8625521/42566977-e400d408-84f7-11e8-908f-bbb5aa683c50.png)

That being said, I'm not convinced this is functioning as intended, especially since there is no way for the user to know that using List.Count() within an imperative will not behave as expected, so I will leave it to you to decide whether or not to close this issue or to take a more fundamental look at the imperative block handling.

**Comment by aparajit-pratap** [comment]
@sunfield thanks for pointing out the issue. Yes, this is reproducible with a simple case like:
![image](https://user-images.githubusercontent.com/5710686/42669614-5ef1be7a-8624-11e8-8efc-28da0cf495fb.png)
Updating the input list does not cause the code block to update. We will look into this.

**Comment by mjkkirschner** [comment]
@Racel @aparajit-pratap where can we document or release note this?

**Comment by smangarole** [comment]
@aparajit-pratap @mjkkirschner I have updated the bug with the files provided. Closing this issue. Tracked internally: https://jira.autodesk.com/browse/QNTM-4682
