### ISSUE TITLE
[Missing Element] Categories node missing 'Structural Framing - Structural Opening Cut' category in dropdown

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#8991]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 1.3.3

## Operating system

Windows 10

## What did you do? 

Was looking to pull all Openings from the model.

## What did you expect to see?

The ability to choose 'Structural Framing - Structural Opening Cut' category in the drop down.

## What did you see instead?

As per the attached image, I can use a **Select Model Element** node in conjunction with a **Element.GetCategory** node to successfully create a category, but cannot seem to find it in the drop down menu (Unless it's been otherwise named and is not inherently obvious to me).

![dynamogithub_missing_category](https://user-images.githubusercontent.com/12857357/42646149-ea49a7ee-85f7-11e8-85ba-20224615bb0a.png)

**Comment by andydandy74** [comment]
Seems like this issue should be raised on the DynamoRevit repo, I think.
Possibly related to https://github.com/DynamoDS/DynamoRevit/issues/982

**Comment by smangarole** [comment]
Closing this issue. Opened in D4R
