### ISSUE TITLE
Importing OBJ

### ISSUE THREAD

**Issue by ads-banana** [DynamoDS/Dynamo#9002]
## Dynamo version
Core 1.3.0.875 Studio 1.3.0.946

## Operating system
Windows 10

## What did you do?
importing obj-model

## What did you expect to see?
vertex numeracy the same as in original OBJ (made in Max)

## What did you see instead?
Half of Vertices ID "scrambled". 

Importing slightly distorted plane with 4x4 quads (25 vertices).

Re-importing obj back to Max - shows that ID did not change, so, issue inside Dynamo.

**Comment by mjkkirschner** [comment]
Hi @ads-banana can you provide the files here?

**Comment by johnpierson** [comment]
Closing this as this issue has gone without information for a while. @ads-banana if this is still an issue for you, please feel free to reopen and provide sample files along with it.
