### ISSUE TITLE
typo "sqare" should be "square"

### ISSUE THREAD

**Issue by rtrwalker** [DynamoDS/Dynamo#9008]
https://github.com/DynamoDS/Dynamo/blob/ced307f2b6792a10d4171b60bc0d484a4c29ad7f/doc/distrib/Samples/en-US/Basics/Basics_Basic01.dyn#L262

**Comment by johnpierson** [comment]
This is being tracked internally as [QNTM-5744](https://jira.autodesk.com/browse/QNTM-5744)

**Comment by johnpierson** [comment]
https://github.com/DynamoDS/Dynamo/pull/9326

**Comment by QilongTang** [comment]
This is fixed in coming release of Dynamo 2.1, closing
