### ISSUE TITLE
List.MaximumItem breaks on mixed input

### ISSUE THREAD

**Issue by sunfield** [DynamoDS/Dynamo#9009]
## Dynamo version

2.0.1.5055

## Operating system

Windows 10

## What did you do? 

Took a list of numbers from a file (so as strings), sorted and converted to number, then tried to find the largest one using `List.MaximumItem`.

## What did you expect to see?

The largest value in the list returned.

## What did you see instead?

null, with a warning.

Boiled it down to this:
![tonumber](https://user-images.githubusercontent.com/8625521/43076951-45468eaa-8e86-11e8-93de-f36bc3e26f90.png)

Tests reveal that if some numbers have a decimal separator and others don't, then the output from `String.ToNumber` is not uniform, which causes problems when using `List.MaximumItem`, which apparently cannot handle a list that includes e.g. Int and Double.
There is actually test code for this which I imagine should have picked this up: 
https://github.com/DynamoDS/Dynamo/blob/dec6240ded0c4369617775336b9af60c2aba4103/test/Libraries/CoreNodesTests/ListTests.cs#L364

What's interesting, looking at the source, is that the `Max()` method, which `List.MaximumItem` uses, seems to cast its inputs to doubles. My C# is rusty but I'm feel like this should be working?
https://github.com/DynamoDS/Dynamo/blob/852ae53e293e16a76f0ef80f603d2c8112cccb59/src/Libraries/CoreNodes/List.cs#L397
https://github.com/DynamoDS/Dynamo/blob/852ae53e293e16a76f0ef80f603d2c8112cccb59/src/Libraries/CoreNodes/Math.cs#L398

Looking into the `DoubleConverter` reveals that this was added to fix exactly this problem here https://github.com/DynamoDS/Dynamo/pull/2041, which maybe it did, but perhaps got unfixed with an update..? I'm in over my head at this point, though.

**Comment by jnealb** [comment]
@sunfield Thank you for this report. We have filed it as QNTM-4876 and it is in the 2.1 backlog.

**Comment by aparajit-pratap** [comment]
@sunfield thanks for highlighting the issue and fix :)
https://github.com/DynamoDS/Dynamo/pull/9012
