### ISSUE TITLE
Feature Request: Allow dll.config files in bin folders of packages

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#9013]
## Dynamo version

2.0.1

## Operating system

Win 10

## What did you do? 

Tried to publish a package containing a view extension locally. The extension dll makes use of a dll.config file for storing application settings. That file needs to be in the same location as the dll.

## What did you expect to see?

The dll.config file to remain in the ```bin``` folder with the dll.

## What did you see instead?

The dll.config file being moved to the ```extra``` folder during the publishing process. This will result in the view extension not being able to read its own settings file.

FYI @Racel @kronz @mjkkirschner

**Comment by mjkkirschner** [comment]
seems like something that should work - but you can do as the dynamo install detective does and load the config manually if you know the path:
https://github.com/DynamoDS/Dynamo/blob/master/src/Tools/DynamoInstallDetective/ProductLookUp.cs#L326

**Comment by andydandy74** [comment]
Thought I'd tried something like that, but I must have had a typo in the alternative path then. Will try again.

**Comment by andydandy74** [comment]
Got it to work. I was using ```OpenExeConfiguration``` instead of ```OpenMappedExeConfiguration```.
Thanks Mike.
