### ISSUE TITLE
Installation error on Linux

### ISSUE THREAD

**Issue by TejaswiRJadhav** [DynamoDS/Dynamo#9031]
hello
   I'm trying to install dynamo on Linux. I have installed mono (version mono-5.12.0.301) and now trying to install dynamo src from github. I'm getting following error after executing command
xbuild /p:Configuration=Release src/Dynamo.Mono.sln_

Errors:

/lus/dal/appuser/testing/benchmark/dynamo/intel/Dynamo-master/src/Dynamo.Mono.sln (default targets) ->
(Build target) ->

        /lus/dal/appuser/testing/benchmark/dynamo/intel/Dynamo-master/src/Dynamo.Mono.sln: error : Could not find the project file '/lus/dal/appuser/testing/benchmark/dynamo/intel/Dynamo-master/src/ShapewaysClient/ShapewaysClient.csproj'

/lus/dal/appuser/testing/benchmark/dynamo/intel/Dynamo-master/src/Dynamo.Mono.sln (default targets) ->
(Build target) ->
/lus/dal/appuser/testing/benchmark/dynamo/intel/Dynamo-master/src/DynamoUtilities/DynamoUtilities.csproj (default targets) ->
/lus/dal/appuser/testing/benchmark/dynamo/intel/build-mono/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        PathHelper.cs(5,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

         38 Warning(s)
         2 Error(s)
Is there anyone have idea how to resolve this?

**Comment by mjkkirschner** [comment]
Hi @TejaswiRJadhav 
1. The mono.sln has not been updated since we removed the shapeways.csproj. You can remove this dependencey manually from the sln until we update it again.

2. Dynamo uses nuget for some dependencies - to run nuget on linux with mono see something like:
 https://stackoverflow.com/questions/38118548/how-to-install-nuget-from-command-line-on-linux

**Comment by mjkkirschner** [comment]
@alfarok did you remove shapeways 😉 ?

**Comment by alfarok** [comment]
@mjkkirschner I didn't remove it from Dynamo
