### ISSUE TITLE
Wall.ByFace Broken

### ISSUE THREAD

**Issue by crwinchester** [DynamoDS/Dynamo#9037]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 1.3.1

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Wall.ByFace Node is non-functional.

## What did you expect to see?

Wall should be created from the input data.

## What did you see instead?

Warnings are thrown and null values are listed instead. Node not functioning.

![wallbyfaceglitch_03](https://user-images.githubusercontent.com/29491492/43745742-412b9fda-9995-11e8-9542-44b1749fbc2d.png)

**Comment by kronz** [comment]
Thanks for the feedback @crwinchester , could you file this in the Revit issues section, 
https://github.com/DynamoDS/DynamoRevit/issues 
and can you say which versions of Revit and Dynamo you are using? Thanks!
Also, can you verify that you can create wall by faces through the regular manual methods in Revit, some surface are not available in either the UI or in the API
![2018-08-12_0025](https://user-images.githubusercontent.com/3456818/43998572-67475a3a-9dc6-11e8-961a-bf95b6da4597.png)

**Comment by crwinchester** [comment]
Hi there @kronz, I filed this here because it appeared to relate more to Dynamo than to Revit, since there are no issues creating the walls via the wall by face tools there. The version of Revit that I was using was 2018.1.3. No mass faces were able to be used to generate walls in Dynamo - the warning keeps incorrectly saying that I need to use mass faces no matter the mass and no matter the face. I thought it would be because of mesh geometry contained in the mass, but I tested with simple box form and still the same result. That said, I cannot say that this issue is necessarily. The issue persists as far as I can see unless later versions of Dynamo have resolved it?

**Comment by kronz** [comment]
Yes, definitely related to Dynamo, but it's the Revit specific functionality.  That is, issues that stem from the functions specifically tailored to Revit interactions should be filed here:
https://github.com/DynamoDS/DynamoRevit/issues
I moved this issue to here: https://github.com/DynamoDS/DynamoRevit/issues/2117
