### ISSUE TITLE
Geometry.IntersectAll() with Plane has undesired results when used with Surface.PerimeterCurves()

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#9039]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.1

## Operating system

Windows 10

## What did you do? 

Using Python, I'm looking at generating Planes from a Solid's Centroid X and Y with variable Z values. Those planes would then be intersected with the Solid to form Surfaces (Floors). 

## What did you expect to see?

My expectation would be simply flat Surfaces that could be used to call **Surface.PerimeterCurves()** from correctly. 

## What did you see instead?

Random lines running off into the middle of nowhere (appears to be an arbitrary location).

![dynamobugperimetercurves](https://user-images.githubusercontent.com/12857357/43832152-5d78be88-9afe-11e8-9e85-3a47b6438ae0.gif)

**Comment by Amoursol** [comment]
Workaround:

Creating a **Rectangle** instead of Planes appears to work. Assumption, however, was that planes should work.

**Comment by kronz** [comment]
@Amoursol Just to confirm . . . this ONLY happens with Python?  Not with regular node operations?
![2018-08-12_0000](https://user-images.githubusercontent.com/3456818/43998394-e1195a74-9dc2-11e8-966d-54a39decfdb4.png)

**Comment by Amoursol** [comment]
In all my tests with regular node operations - it appears to be fine. I'll have another look later in the week to confirm if the geometry coming out of my Python Node will correctly execute using **Geometry.Intersect**. It feels like an edge case as I've ran into this issue at times in the past (But simply playing).

**Comment by Amoursol** [comment]
As an addendum, the Rectangle 'workaround' is also failing coming out of the Python node. It simply worked as an origin test so I'll have to investigate more.

**Comment by johnpierson** [comment]
@Amoursol , feel free to reopen if this comes up again.
