### ISSUE TITLE
Application hangs when typing a perdiod (.) after particular lines of code (autocomplete issue?)

### ISSUE THREAD

**Issue by DanRumery** [DynamoDS/Dynamo#9059]
## Dynamo version

1.3.3

## Operating system

Windows 7

## What did you do? 

Typed the following python code in a python node:

```
import clr
from System import AppDomain
APP_DOMAIN_DATA_PROPERTY_NAME___PROPERTY_NAME = ""
str
```
If I then go to type a period (.) after the 'str' above, the application freezes (both in sandbox and in Revit).

## What did you expect to see?

Either an autocompletion window or nothing (but no application freeze!)

## What did you see instead?

Application hangs (have to kill it).

**Comment by jnealb** [comment]
@DanRumery Thank you: we can reproduce it and have filed it for our 2.1 backlog.
