### ISSUE TITLE
[BUG] Python 2.0 Instance Method

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#9067]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core: 2.0.1.5055
Dynamo Revit: 2.0.1.5065

## Operating system

Windows 10

## What did you do? 

Attempting to call DesignScript static methods inside of a Python block. In particular, **Curve.Length()**

## What did you expect to see?

I expected the static method **Curve.Length(crv)** to correctly return the Length property.

## What did you see instead?

It returns an error as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/12857357/44596146-135b1e00-a7c3-11e8-999d-0edc103f4840.png)

However, the **instance** method still works:

![image](https://user-images.githubusercontent.com/12857357/44596146-135b1e00-a7c3-11e8-999d-0edc103f4840.png)

```
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

polyCrv = IN[0]
offset = IN[1]

offsets = [-offset, offset]
lengths, newCurves, output = [], [], []

for off in offsets:
	newCurves.append(Curve.Offset(polyCrv, off))

for nc in newCurves:
	lengths.append(Curve.Length(nc))

for nc,len in zip(newCurves, lengths):
	if len == min(lengths):
		output.append(nc)

OUT = lengths, newCurves, output
```

**Comment by Amoursol** [comment]
FYI @aparajit-pratap @mjkkirschner @Racel Found a bug I think :)

**Comment by dimven** [comment]
most likely you will have to get the underlying getter and apply it to the instance like so:
`Curve.Length.__get__(crv)`

**Comment by aparajit-pratap** [comment]
@Amoursol  the fact that you're able to call the static version of `Curve.Offset(curve, offset)` is surprising since even that method is a .NET instance method. As @mjkkirschner points out this should not be transferrable to Python but only exist in DesignScript code. In the case of `Curve.Length`, as @dimven says, since it's a property it may work if you use the static getter method: `Curve.get_Length(curve)`. I need to find out what's going on here. Thanks for pointing it out.

**Comment by Amoursol** [comment]
Thank you for the submission of this Issue above - We very much do appreciate your time taken to look to improve Dynamo and help it grow and evolve into the future.

In order to better serve the active Dynamo user base and the evolving nature of Dynamo, the Dynamo team has made the decision to **close any issue that hasn't had activity since 1st January 2019**. This doesn't mean that these issues will not be addressed, but just that they are not being actively worked on as they do not align with our current [Dynamo Public Roadmap](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Public-Roadmap).

If this issue is still relevant to you and your workflows, please do re-submit in a new Github Issue and link to this closed issue for historical context.

Many thanks,
The Dynamo Team
