### ISSUE TITLE
rebar instance select crash

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#908]
I know I am not supposed to be in there with Dynamo 
but when I open a rebar shape in "edit mode" and open dynamo and add the select family instance node
then select the node then the model line in the rebar family it crashes everytime
it does not seem to crash with other families (tested a structural column family)

![error](https://f.cloud.github.com/assets/6132497/1707172/a6bf0e6a-60f9-11e3-91df-162aa17457b9.png)

**Comment by kronz** [comment]
seriously old bug, assuming obsolete
