### ISSUE TITLE
谁有中文教程或者说明文档呀？

### ISSUE THREAD

**Issue by wyw7733** [DynamoDS/Dynamo#9083]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by QilongTang** [comment]
@wyw7733 Do you find this useful? http://primer.dynamobim.org/zh-tw/ or are you requesting more materials than primer along?

**Comment by johnpierson** [comment]
I would also recommend opening primer related issues here, https://github.com/DynamoDS/DynamoPrimer/issues, if this is still a concern for you.
