### ISSUE TITLE
Dynamo fails at loopWhile (with Optimo package)

### ISSUE THREAD

**Issue by MarcinTata** [DynamoDS/Dynamo#9091]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.3.4651

## Operating system

Windows 10

## What did you do? 

Run script with Optimo package 

## What did you expect to see?

Result of the Optimo package, which comes from a loopWhile

## What did you see instead?

"null" and error in popout:

(PL: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.)

ENG: The object reference has not been set to the occurance of the object
   w ProtoCore.DSASM.Heap.RecursiveMark(StackValue root)
   w ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   w ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   w ProtoScript.Runners.LiveRunner.ApplyUpdate()
   w ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   w ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   w ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   w Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   w Dynamo.Scheduler.AsyncTask.Execute()

**Comment by sixtysecondrevit** [comment]
Closing as #9095 has more information for this same report.
