### ISSUE TITLE
3d grid and 3d results not visible in dynamy

### ISSUE THREAD

**Issue by g69031** [DynamoDS/Dynamo#9094]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

windows 10
## What did you do? 

doing the 1st tutorial

## What did you expect to see?

3d grid in the 3d interface and the point placed in the 3d window which I created seeing the tutorial

## What did you see instead?
 I saw nothing , even in watch 3d node

**Comment by johnpierson** [comment]
@g69031, are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Going to go ahead and close this for now as we need sample files / more information to continue. If this is still an issue for you, please feel free to reopen and attach the files needed for us to test.
