### ISSUE TITLE
Dynamo. Export elements by category to FBX

### ISSUE THREAD

**Issue by jbalado** [DynamoDS/Dynamo#9096]
Does anyone know why this doesn't work?

I'm trying to generate the views of each category of items to be able to export them later.

Some Views are generated but they don't correspond with the categories.

![1](https://user-images.githubusercontent.com/43201161/45412351-b4c4e980-b676-11e8-924f-e25aa53ad77a.JPG)

![2](https://user-images.githubusercontent.com/43201161/45412369-b8f10700-b676-11e8-8a43-483b3db574d6.JPG)

**Comment by sixtysecondrevit** [comment]
This seems better suited as a post on the forum rather than here. A search on the forum shows quite a few results of individuals trying to achieve similar results, https://forum.dynamobim.com/search?q=fbx.
