### ISSUE TITLE
Dynamo failure start up

### ISSUE THREAD

**Issue by Arsany123** [DynamoDS/Dynamo#9104]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
 1.3.3 /2.0.0
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

Windows 10
## What did you do? 
opening dynamo and start a new script
(Fill in here)
![capturesdfdsfdsf](https://user-images.githubusercontent.com/43368301/45671597-dcb0c300-bb36-11e8-9556-a1eee042c0bb.JPG)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by johnpierson** [comment]
@Arsany123 , are you still receiving this error on Dynamo 2.0.1?

**Comment by johnpierson** [comment]
Closing this as we need more information. Please reopen and update if this is still an issue for you.
