### ISSUE TITLE
Duplicate groups and notes in custom nodes

### ISSUE THREAD

**Issue by EllouzeMustapha** [DynamoDS/Dynamo#9114]
https://forum.dynamobim.com/t/duplicate-groups-and-notes/26255

## Dynamo version

2.0.1

## Operating system

Windows 10 Pro

## What did you do? 

Created groups (CTRL + G) and notes (CTRL + W) inside a custom node. 
Saving the node. 
Closing the corresponding tab (.dyf). 
Re-opening the custom node by double-clicking on one instance on the graph (.dyn).

## What did you expect to see?

The same nodes, groups and notes than I had when I closed the tab.

## What did you see instead?

All the nodes where fine but the groups and the notes were duplicated. Additionally Duplicate notes could not be moved (but could be deleted). Nota : Duplicate notes are hard to see as they are right on top of the original ones.
![2018-09-24 09_57_54-dynamo](https://user-images.githubusercontent.com/43533821/45941915-99e06680-bfe0-11e8-8272-ce202dce6da9.png)
![2018-09-24 09_59_01-dynamo](https://user-images.githubusercontent.com/43533821/45941916-99e06680-bfe0-11e8-8d5a-bb9af4be44d0.png)

**Comment by johnpierson** [comment]
Tracked internally as QNTM-5544

**Comment by johnpierson** [comment]
Closing as a fix for this has been merged as PR #9205.
