### ISSUE TITLE
Node to code: Backslashes in strings do not get escaped

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#9117]
## Dynamo version
2.0.1 stable

## Operating system
Windows 10

## What did you do? 
Ran node to code on a string node that contained a string that ended with a backslash

## What did you expect to see?
An error-free code block

## What did you see instead?
Code block turned red, since backslash was not escaped upon conversion, producing a ```Invalid Associative_FunctionalStatement``` error.
![grafik](https://user-images.githubusercontent.com/3014437/45992896-5ba08100-c08c-11e8-973b-9802932f7805.png)

**Comment by andydandy74** [comment]
I just realized that any backslash anywhere in a string node will trigger the same error (with the exception of standard escape sequences like ```\a```, ```\b```, ```\f```, ```\n```,  ```\r```, ```\t```, ```\v```and ```\0``` - which don't trigger the error but will be converted to line breaks, tabs etc.).

**Comment by johnpierson** [comment]
Tracked internally as [QNTM-5742](https://jira.autodesk.com/browse/QNTM-5742).

**Comment by andydandy74** [comment]
FWIW, I solved this for myself with a view extension by modifying the ```StringInput``` values before caling ```NodeToCodeCommand```:
https://github.com/andydandy74/Monito/blob/master/src/_Unfancify/UnfancifyViewModel.cs#L210

**Comment by johnpierson** [comment]
Related: https://forum.dynamobim.com/t/dynamo-quotation-marks/35145/3

**Comment by Amoursol** [comment]
Now tracked internally at: [DYN-1261](https://jira.autodesk.com/browse/DYN-1261 )
