### ISSUE TITLE
My Dynamo can‘t save files

### ISSUE THREAD

**Issue by songguoer22** [DynamoDS/Dynamo#9126]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by johnpierson** [comment]
Hi there @songguoer22, we are going to need some information on this. The submission above is pureley the placeholder text.

**Comment by songguoer22** [comment]
Dynamo version：2.1 ；Operating system：Win10；Revit 2017

I want to use Dynamo to model

**Comment by johnpierson** [comment]
I see you opened this on the Revit issues page as well. https://github.com/DynamoDS/Dynamo/issues/9126
Going to close this one as that has more info.
