### ISSUE TITLE
Crashes when creating list using two other lists resulting from an If statement

### ISSUE THREAD

**Issue by jagostinhoCT** [DynamoDS/Dynamo#9143]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.3

## Operating system

Windows 7

## What did you do? 

Created two lists in same code block using if statements as below

DOS=DesOpSetIsNull=DSCore.Object.IsNull(DesOpSet<1L>)?"Main Model":DesOpSet.GetParameterByValueName("Name");

DO=DesOpSetIsNull=DSCore.Object.IsNull(DesOpSet<1L>)?"Main Model":DesOpName.GetParameterByValueName("Name");

## What did you expect to see?

the lists.

## What did you see instead?

crash error

**Comment by johnpierson** [comment]
@jagostinhoCT Going to need some more information on this. Also, are you developing a ZeroTouch node that is interacting with Revit? If so, this issue would need to be created in the correct repo at this [location](https://github.com/DynamoDS/DynamoRevit/issues).

**Comment by jagostinhoCT** [comment]
@johnpierson I am a basic Dynamo user taking my first steps in DS.
I do not know what a ZeroTouch node is.

I got the error when I created a single node to contain these lines below.

DOS=DesOpSetIsNull=DSCore.Object.IsNull(DesOpSet<1L>)?"Main Model":DesOpSet.GetParameterByValueName("Name");

DO=DesOpSetIsNull=DSCore.Object.IsNull(DesOpSet<1L>)?"Main Model":DesOpName.GetParameterByValueName("Name");

Does this make sense, or help?

**Comment by johnpierson** [comment]
Are you creating the code block from scratch or is this via Node2Code? Screenshots and sample files would also help.

**Comment by jagostinhoCT** [comment]
@johnpierson was trying to replace the two CBs on the right by it.
Graph also attached.
The goal was to extract DO info from the models into Excel.
[Design Analisys_v2.06.dyn.zip](https://github.com/DynamoDS/Dynamo/files/2442992/Design.Analisys_v2.06.dyn.zip)



![image](https://user-images.githubusercontent.com/43812310/46426804-85664180-c737-11e8-938d-e4872dd62bf7.png)

**Comment by johnpierson** [comment]
@jagostinhoCT, I see. I would go ahead and try to post this as a [Dynamo Forum](https://forum.dynamobim.com/) post. Since it is dealing with custom nodes, there is a good chance someone else has run into this before. If that does not work out, please repost on the Dynamo Revit page [here](https://github.com/DynamoDS/DynamoRevit/issues).
