### ISSUE TITLE
Library Quit Functioning

### ISSUE THREAD

**Issue by Drafter1967** [DynamoDS/Dynamo#9151]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.01
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
I have had the Library stop functioning multiple times. I have had to stop Dynamo and Revit and restart both for it to start again.  I could not do a search for nodes nor pick any items from the list.
(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by johnpierson** [comment]
@Drafter1967 Can you drop some screenshots on here to let us see what happens? Does the library load and you simply cannot select?

**Comment by Drafter1967** [comment]
Here is a screen show with explanation that you have asked for.




Kevin Billings
[o]817.377.2969
www.huckabee-inc.com
Committed to the success of all students and the profound impact it has on all of us

**Comment by johnpierson** [comment]
@Drafter1967 looks like the image didn't come through on the "reply with email" option.

**Comment by Drafter1967** [comment]
I have hit reply and have attached the PDF file

Kevin Billings
[o]817.377.2969
www.huckabee-inc.com
Committed to the success of all students and the profound impact it has on all of us

**Comment by johnpierson** [comment]
PDF or image, the attachment did not come through. Sorry about that man. Going to need you to include that for us to have more info on the issue.

That being said, here is another issue that had a similar problem (from what it sounds like)
https://github.com/DynamoDS/Dynamo/issues/8768

**Comment by Drafter1967** [comment]
I have attached the image to this email twice.  Your Github pop hub keeps coming up and wanting me to use it.  There is no option to attach an image through that program.  Please use an email address that will allow me to send you an image.  We send images all the time and do not have this problem.


Kevin Billings
[o]817.377.2969
www.huckabee-inc.com
Committed to the success of all students and the profound impact it has on all of us

**Comment by johnpierson** [comment]
> We send images all the time and do not have this problem.
I believe that for typical email interaction. But it appears your GitHub account was just created so that information seems a little irrelevant.

Please email the attachment to sixtysecondrevit@gmail.com and I will attach here for you. (FYI: I am using Firefox on Windows and uploading works fine from browser(

**Comment by johnpierson** [comment]
Information about issue:
![image](https://user-images.githubusercontent.com/15744724/46675031-d09aad00-cb9a-11e8-9523-670912286f9e.png)

**Comment by Drafter1967** [comment]
Yes, it is ivanti Antivirus


Kevin Billings
[o]817.377.2969
www.huckabee-inc.com
Committed to the success of all students and the profound impact it has on all of us

**Comment by mjkkirschner** [comment]
Would you mind disabling temporarily to see if the problem is solved?

**Comment by Drafter1967** [comment]
I will have to see if IT will do that.  Myself, the end user, is not allowed to do that.


Kevin Billings
[o]817.377.2969
www.huckabee-inc.com
Committed to the success of all students and the profound impact it has on all of us

**Comment by johnpierson** [comment]
@Drafter1967 , did the anti-virus option work?

**Comment by Drafter1967** [comment]
I’m sorry.  What are you referring to?


Kevin Billings
[o]817.377.2969
www.huckabee-inc.com
Committed to the success of all students and the profound impact it has on all of us
