### ISSUE TITLE
Using ReadyParams.CurrentWorkspaceChanged Event messes up connectors and CodeBlocks

### ISSUE THREAD

**Issue by MostafaElAyoubi** [DynamoDS/Dynamo#9171]
## Dynamo version

2.0.1

## Operating system

Widows 10

## What did you do? 

Used the ReadyParams.CurrentWorkspaceChanged Event to scan the nodes in the workspace at the opening of the .dyn and make sure all default values are activated. 
Here's the code: 

```
`            p.CurrentWorkspaceChanged += (str)=>
            {            
                foreach (NodeModel node in p.CurrentWorkspaceModel.Nodes)
                {
                    if (node.Category.StartsWith("Data-Shapes"))
                    {
                        foreach (PortModel port in node.InPorts)
                        {
                            if (port.ToolTip.Contains("Default value") && port.UsingDefaultValue == false)
                            {
                                var viewModel = new ActivateDefaultValues(p, false);
                                var Uwindow = new UpdateNotification
                                {
                                    // Set the data context for the main grid in the window.
                                    MainGrid = { DataContext = viewModel },

                                    // Set the owner of the window to the Dynamo window.
                                    Owner = p.DynamoWindow
                                };

                                Uwindow.Left = Uwindow.Owner.Left + 400;
                                Uwindow.Top = Uwindow.Owner.Top + 200;
                                Uwindow.Show();

                                Uwindow.ActivateBut.Click += (s, a) =>
                                {
                                    foreach (NodeModel nd in p.CurrentWorkspaceModel.Nodes)
                                    {
                                        foreach (PortModel pt in nd.InPorts)
                                        {
                                            if (pt.ToolTip.Contains("Default value") && pt.UsingDefaultValue == false)
                                            {
                                                pt.UsingDefaultValue = true;
                                            }
                                        }
                                        nd.RegisterAllPorts();
                                    }
                                    Uwindow.Close();
                                };
                                break;
                            }
                        }
                    }
                }`
```

## What did you expect to see?

Everything works, except for the fact that there is a glitch with the connectors and codeblocks. Selecting all elements and moving them makes the connectors reappear ar their normal place but it takes saving/reopening the .dyn to have the codeblocks appear normally. 

## What did you see instead?

Here is the glitch in image: 

![currentworkspacechanged](https://user-images.githubusercontent.com/20224923/46853506-9a5d6780-cdfe-11e8-8266-5001296116f2.gif)

**Comment by MostafaElAyoubi** [comment]
Ok I just fixed the connectors part of the problem by using the IDynamoModel.WorkspaceOpening Event : 

            var ViMo = p.DynamoWindow.DataContext as DynamoViewModel;
            IDynamoModel m = ViMo.Model;
            m.WorkspaceOpening += (str) =>
etc. 

But the codeblocks still won't load normally.

**Comment by mjkkirschner** [comment]
Hi @MostafaElAyoubi I really want to get to the bottom of this one, but don't have time to investigate myself right now - perhaps you can do some shrinking of the problem space.

What happens if you don't create any WPF controls during your iteration and instead just iterate the nodes and ports (IE don't show anything or create your viewModels)

What happens if you just iterate nodes, but not ports?

**Comment by mjkkirschner** [comment]
Last question - have you tried invoking your iteration on the dispatcher?

**Comment by MostafaElAyoubi** [comment]
Hi @mjkkirschner , thanks for your reply!
The issue persists if I don't open Wpf on create a viewModel. 
I'm not sure I understand the last question 😨

**Comment by mjkkirschner** [comment]
The wpf dispatcher let’s you invoke work on the ui thread. The broken code blocks look like a threading issue to me so it might be somewhere to start.

**Comment by mjkkirschner** [comment]
dispatch your wpf interactions like this:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher.invoke?redirectedfrom=MSDN&view=netframework-4.7.2#System_Windows_Threading_Dispatcher_Invoke_System_Delegate_System_Object___

you may prefer beginInvoke()

**Comment by MostafaElAyoubi** [comment]
Thanks I'm looking into this. Will let you know how it goes.

**Comment by MostafaElAyoubi** [comment]
Got it working!
I actually used the DynamoWindow dispatcher and BeginInvoke. I invoked the iteration like that and all works well now. Thanks a lot! 
 This dispatcher thing gives me ideas 🤔  .. 

![dispatcher](https://user-images.githubusercontent.com/20224923/47008269-49b97780-d13a-11e8-9e73-24957b9e1c37.gif)

**Comment by mjkkirschner** [comment]
👍
