### ISSUE TITLE
Dynamo 2017 doesn't open, Dynamo 2016 works but no 3D preview

### ISSUE THREAD

**Issue by RielBessai** [DynamoDS/Dynamo#9188]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 0.9.2.4461

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Op Windows 10 Home 64 Bit

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Try to use Dynamo

## What did you expect to see?

3d Preview

## What did you see instead?

No 3d Preview. Tried switching between AMD Radeon 8700M and intel HD Graphics 4000 and restarting but still nothing. Also, i installed the 2016 because 2017 wouldn't open at all. Its as if the files didn't download properly. It says 30/800 mb downloaded and then jumps to "install completed", seems suspiciously quick for the install/download time. Similarily quick for the 2016 version but i can open the program at least.

**Comment by johnpierson** [comment]
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Comment by jli113** [comment]
Background 3d preview is gray in Dynamo from Revit 2020.
Have the same problem opening DynamoSandbox 2.4.0.6186.
I only have an RX5700XT GPU card using Win 10 18362, tried many methods, no use.
