### ISSUE TITLE
Running .dyn's in sequence fails to execute all dyn's

### ISSUE THREAD

**Issue by DanimoSite** [DynamoDS/Dynamo#9195]
Hi,

I am getting some weird behaviour when running sequences of .dyn files. I have built a ViewExtension which allows the user to batch run .dyn files, but on first run not all files seem to execute. On second run however (and thereafter), all files execute. Any help with this would be much appreciated, I have attached a video as an example of the behaviour I am seeing...

[https://youtu.be/HTlgOfiwzL4](url)

In my code I am looping through a list of filepaths, opening each file in Dynamo, Running and then closing. I have stepped through the code several times and some files just don't seem to run. Is there something specific I should be doing here? I have checked the Dynamo repo and couldn't see anything that would suggest otherwise.

Cheers,
Dan

## Dynamo version

Dynamo 1.3.2

## Operating system

Windows 10 pro 64 bit

## What did you do? 

Tried to run multiple .dyn files consecutively via ViewExtension

## What did you expect to see?

All .dyn files executed when called via ViewExtension

## What did you see instead?

Only a 3-5 (varies) out of 15 .dyn files executed on first run. Second run executes all of them.

**Comment by johnpierson** [comment]
Hi there @DanimoSite! Sounds like an interesting workflow. To get you the right kind of assistance/info, we are going to need to see some of the code that is doing this. Are you able to provide that here?

**Comment by DanimoSite** [comment]
Hi @johnpierson!

Yup sure can, you can find the whole solution here...

[https://www.dropbox.com/s/jjwkfq0q3sz7upx/DanimoViewExtensionSolution.zip?dl=0](url)

You want the "Script Manager" folder. The code is in the ScriptManagerViewModel and to make it easy to find what you probably need, the OnRunSequence() method is what is making the calls to DynamoVM (line 690) and this calls another method from within ExecuteDynamoFile() (line 322).

The code is a little messy around these methods as I was trying several things with events etc before posting having to post here. 😄 

Thanks in advance for any help with this! 

cheers,
Dan

**Comment by johnpierson** [comment]
This is being tracked internally as [QNTM-5728](https://jira.autodesk.com/browse/QNTM-5728).
@DanimoSite we should have an update for you before too long.

**Comment by johnpierson** [comment]
another quick question for you @DanimoSite, Have you tried subscribing to the event `DynViewModel.Model.RunCompleted ` to trigger the next graph after the previous has completed?

**Comment by DanimoSite** [comment]
Hi @johnpierson 

Yup, it was one of the first things I tried, but the event was never fired even though the scripts executed. Other events fire just fine, like opening, clearing and closing, but not the RunCompleted event which was weird.

**Comment by mjkkirschner** [comment]
@DanimoSite please try evaluationCompleted - I think runCompleted might be an event that is obsolete/should have been removed.

https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCLI/CommandLineRunner.cs#L49

**Comment by DanimoSite** [comment]
Thanks @mjkkirschner, I shall try this later.

Is the EvaluationCompleted event only called when the graph is run?

**Comment by DanimoSite** [comment]
Hi @johnpierson @mjkkirschner 

I tried the EvaluationComplete event and now logging from here. But the results are same as before and what get's returned by the event args is odd. Here is my code...

        private void OnRunSequence()
        {
            if (CanRunSequence())
            {
                if(DynViewModel != null)
                {
                    SequenceRunReport = new List<string>();
                    List<DynamoFilePath> dynFilePaths = SelectedSequence.DynamoFilePath;                                                    

                    foreach (DynamoFilePath dfp in dynFilePaths)              
                    {                        
                        string fp = dfp.FPath;

                        if (File.Exists(fp))
                        {
                            ExecuteDynamoFile(fp);                            
                        }
                        else
                        {
                            SequenceRunReport.Add("Not Found : " + fp);
                        }
                        WriteLog(ScriptManagerFilePath, SequenceRunReport);
                    }
                }
                else
                {
                    System.Windows.MessageBox.Show("Dynamo View Model Not Found");
                }
            }
        }  

        public void ExecuteDynamoFile(string fp)
        {
            DynViewModel.Model.OpenFileFromPath(fp, true);
            DynViewModel.Model.EvaluationCompleted += Model_EvaluationCompleted;
            DynViewModel.Model.ForceRun();
            DynViewModel.CloseHomeWorkspaceCommand.Execute(null);
            DynViewModel.Model.EvaluationCompleted -= Model_EvaluationCompleted;
        }

        private void Model_EvaluationCompleted(object sender, Dynamo.Models.EvaluationCompletedEventArgs e)
        {
            var wsm = sender as WorkspaceModel;
            if (e.EvaluationTookPlace)
            {
                if (e.EvaluationSucceeded)
                {
                    SequenceRunReport.Add("Success:" + wsm.FileName);
                }
                else
                {
                    SequenceRunReport.Add("Failed: " + e.Error.Message);
                }
            }
            else
            {
                SequenceRunReport.Add("Failed: " + wsm.FileName + " Failed to Execute");
            }
        }

and here is what I am logging on first run...

Failed: D:\TestDynFiles\MyScriptManagerTest1.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest2.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest3.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest4.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest5.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest6.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest7.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest8.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest9.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest10.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest11.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest12.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest14.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest13.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest15.dyn Failed to Execute

But 4 dynamo scripts out of 15 actually wrote a text file, therefore succeeded.

On second run however I get this...

Success:D:\TestDynFiles\MyScriptManagerTest1.dyn
Failed: D:\TestDynFiles\MyScriptManagerTest1.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest2.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest3.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest4.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest5.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest6.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest7.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest8.dyn Failed to Execute
Success:
Success:D:\TestDynFiles\MyScriptManagerTest9.dyn
Failed: D:\TestDynFiles\MyScriptManagerTest9.dyn Failed to Execute
Failed: D:\TestDynFiles\MyScriptManagerTest10.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest11.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest12.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest14.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest13.dyn Failed to Execute
Success:
Failed: D:\TestDynFiles\MyScriptManagerTest15.dyn Failed to Execute
Success:

But all scripts wrote their text files.

I'm a little lost on what I am doing wrong here... 😕

**Comment by Amoursol** [comment]
Hello @DanimoSite - Is this still an issue or have you found a resolution?
