### ISSUE TITLE
Errors building Dynamo from source

### ISSUE THREAD

**Issue by bimwood** [DynamoDS/Dynamo#9259]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo/master

## Operating system

Windows 7

## What did you do? 

Followed the instructions at http://developer.dynamobim.org/02-Build-Dynamo-From-Source/2-0-build-dynamo-from-source.html

## What did you expect to see?

Successful build, "...it should read similar to '==== Build: 69 succeeded, 0 failed, ...' " etc.

## What did you see instead?

Failed build. Output from Build attached, ending with similar to: '==== Build: 11 succeeded, 60 failed, ...' etc.

You can see that it's not resolving the references correctly, even though it seems to have restored the nuget packages. I've had a google, and tried 'Update-Package -reinstall', but that doesn't seem to have made any difference. Tried using 'Manage Packages' to uninstall / reinstall individual packages, with inconsistent results. Restarted VS of course. 

Any ideas?

[DynamoBuild.txt](https://github.com/DynamoDS/Dynamo/files/2608420/DynamoBuild.txt)

**Comment by Amoursol** [comment]
@bimwood, not a fix per see, but can you please keep trying to **Clean** and **Build** until it builds? It can take up to 20x or so - but we all got there in the end at the London Extensions Workshop.

**Comment by QilongTang** [comment]
@bimwood The first error caught my eyes:
```
error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
```

When you use solution explorer to check `DynamoUtilities` project, do you find NewtonSoft.Json is correctly referenced like this?
![image](https://user-images.githubusercontent.com/3942418/49027897-2a692d80-f16f-11e8-98b7-2b56e3d9b128.png)

If it is pointing to a null path, it usually means it is not referenced correctly. In such case, you need to
1. check your Dynamo/src/packages to see if the package `Newtonsoft,Json.8.0.3` folder is there or not
2. If it is there, restart your VS Studio in case this package is restored after solutions loaded so path sometimes not resolved correctly and do Clean then Build.
3. You can also try the tip above to start again.

I think the reference issue happens from time to time, as long as the package is restored correctly. Restarting VS usually fixes it for me. Let us know

**Comment by bimwood** [comment]
Thanks all! I'll have another go and report back.

**Comment by mjkkirschner** [comment]
@bimwood did you get this building?

**Comment by bimwood** [comment]
Sorry, no not yet. I think I need to start again from a clean fork.
