### ISSUE TITLE
Package Manager Search returns empty list behind a proxy

### ISSUE THREAD

**Issue by nhoway** [DynamoDS/Dynamo#9284]
Hello,

I am behind an enterprise proxy and I think requests made by Dynamo Package Manager are blocked by this one.

Can you please tell me how could I configure the proxy properly for the Package Manager ?

I tried to reach https://www.dynamopackages.com from my default browser (Firefox 60.1.0esr) and I can download any package from it without any issue.

Thanks for your help !

## Dynamo version
1.3.3.4111

## Operating system
Windows 10 Enterprise

## What did you do? 
I want to install a new Package from the Package Manager : Packages > Search for a Package...

## What did you expect to see?
The list of available packages

## What did you see instead?
An empty list.

**Comment by mjkkirschner** [comment]
I would try using dynamo 1.3.4 - which will use newer TLS protocols. The proxy may block older TLS connections.

**Comment by mjkkirschner** [comment]
@nhoway I know this is a very old issue, were you able to resolve it by using Dynamo 1.3.4 or newer? - Was this happening in DynamoRevit or sandbox?

**Comment by nhoway** [comment]
Hi @mjkkirschner, I've tried with Dynamo 1.3.4 and it didn't solve this issue. I used DynamoRevit only and didn't try through the sandbox. Unfortunately, I cannot reproduce it because I asked for an exception at our IT department and it has been approved.
