### ISSUE TITLE
Dictionaries - Multiple Values per Key

### ISSUE THREAD

**Issue by Curty102** [DynamoDS/Dynamo#9318]
## What did you do? 

Filtered items from a list by a condition.

## What did you expect to see?

Wish there was an integral option to convert a list to a dictionary to enable retention of keys even after filtering. Rhino's Grasshopper achieves this through the use of nulls as placeholders for unfiltered values, but given Dynamo's recent embrace of dictionaries, perhaps a set of tools could emerge allowing for keys with multiple values (similar to tuples or temporary class instances).

## What did you see instead?

Currently, for more localized filter operations, I use List.Filter.ByBooleanMask paired with Springs List.MergeByBooleanMask to reintegrate the altered subset.  But when generating many different subsets and/or referencing many mask functions, I sometimes resort to grouping values with keys via List.Transpose.  It just seems like Dictionaries, especially if allowing multiple values per key, could clean up the workflow.

**Comment by mjkkirschner** [comment]
Why not store a list or dictionary as the value?

some images of the workflow you're after might help explain if that idea would help or not.

**Comment by Curty102** [comment]
Michael, you may be right, am trying to exhaust my idealism before I reply.. 😉

**Comment by aparajit-pratap** [comment]
Closing this unless there are further issues to be discussed.

**Comment by Curty102** [comment]
Ok.  I have since seen the light of dictionaries for non-ordered collections, lists for those that are ordered, and nested combinations of both.  Great job team Dynamo on inclusion of Dictionaries.
