### ISSUE TITLE
Hard Crash when running graphs

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#9329]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2 Stable

## Operating system

Win 10

## What did you do? 

Occasionally, Dynamo hard crash and exits without notification and bring Revit along with it on graphs that worked fine before saving, closing and opening them again. I have had multiple other collegues also reporting the very same. I can't fathom what is going wrong although I suspect custom nodes playing a part. Attached is the file I was playing around with when Dynamo crashed. (change the extension to dyn) 

Please tell me if there is anything I can do to help.

[Wall.ByProfile – Kopi.txt](https://github.com/DynamoDS/Dynamo/files/2695133/Wall.ByProfile.Kopi.txt)

## What did you expect to see?

Dynamo not hardcrashing without warning

## What did you see instead?

Hardcrash

**Comment by mjkkirschner** [comment]
Hi @josols - worked fine in what version of dynamo? 2.0.1?
Also what version of revit were you/ are you using?

**Comment by josols** [comment]
Hi, will do. BTW, the Revit file used was the advanced architectural example file with som minor adjustments.(Copied terrain upwards 10m, drew tree model lines beneath the terrain

**Comment by dimven** [comment]
Actually yes. I've experienced the same behaviour recently with the `Mesh.ToPolySurface` node. To be honest I haven't used it in a while but I suspect that at some point, while the team was updating the LibG libraries during the last 2 years, they stopped being thread safe - i.e. they didn't like it when multiple threads are calling the Surface.ByPoints method?

**Comment by mjkkirschner** [comment]
It's possible this is true - is this a recent change that you have noticed in behavior though?
I recall this node uses parallel code?

**Comment by mjkkirschner** [comment]
@dimven does this node adhear to this advice?
https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#dispose--using-statement

even though the warning is in the context of c# zeroTouch - the same concerns apply from python.

**Comment by mjkkirschner** [comment]
hmm, I know this is a very late response....
And I have not delved into the node's code - but even a polysurface in LibG should be an immutable new surface - the input surfaces should be disposed if they are not referenced someone else.

I'm curious if this behavior has improved in the 2.5 builds.

**Comment by mjkkirschner** [comment]
@josols @dimven - please reopen if there is no improvement after 2.5 (should be able to be tested in 2.5 sandbox builds)
if springs is using multi threading then special care should be followed as outlined here:

https://forum.dynamobim.com/t/dynamo-geometry-stability-improvements-request-for-feedback/39297
