### ISSUE TITLE
"Maintain List Structure" not implementing until file is closed and reopened 

### ISSUE THREAD

**Issue by Curty102** [DynamoDS/Dynamo#9342]
## Dynamo version

2.X. All stable versions so far.

## Operating system

Windows 10

## What did you do? 

When applying List @ Level to a (any) node input, and selecting "Maintain List Structure", the option is not immediately applied, but does get implemented if the file is saved, closed, and reopened.

## What did you expect to see?

Immediate implementation of "Maintain List Structure (@@ syntax).

## What did you see instead?

Only worked after save, close, reopen.

**Comment by mjkkirschner** [comment]
@Curty102 please see:
https://github.com/DynamoDS/Dynamo/issues/8962

**Comment by Curty102** [comment]
Apologies, I couldn't find a search function on GitHub.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
