### ISSUE TITLE
Regression: String indexing broken in Dynamo 2.0.x

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#9383]
## Dynamo version

2.0.2

## Operating system

Windows 10

## What did you do? 

tried to get the substring from a string object

## What did you expect to see?

the substring

## What did you see instead?

the entire string again

It seems the string is automatically promoted to a list whenever you tryto use list indexing notation?

![image](https://user-images.githubusercontent.com/7148394/50831374-502f4800-1353-11e9-9d46-791d1f4c2167.png)

This worked perfectly fine in previous versions. I can remember using string indexing as far back as 0.8:

![image](https://user-images.githubusercontent.com/7148394/50831399-60472780-1353-11e9-9eeb-18a82ff2536b.png)

**Comment by mjkkirschner** [comment]
@aparajit-pratap will your current task address this?

**Comment by johnpierson** [comment]
I wanted to reference the dynamo forum post here as well, https://forum.dynamobim.com/t/more-feet2fraction-issues/22408/11

**Comment by aparajit-pratap** [comment]
Yes, there's a current task for this filed internally: https://jira.autodesk.com/browse/DYN-995. It was a regression after the introduction of Dictionaries.

**Comment by aparajit-pratap** [comment]
https://jira.autodesk.com/browse/DYN-995
