### ISSUE TITLE
Dynamo.Models.DynamoModel.IsHeadless is always false

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/Dynamo#9384]
`Dynamo.Models.DynamoModel.IsHeadless` is always `false` even when running Dynamo from the Dynamo Player, while in this case it should be `true`.

Is there any other way to check if Dynamo is running headless or not?

**Comment by mjkkirschner** [comment]
DynamoRevitModel has a UIStarted flag I think.

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/DynamoRevit/blob/d129a6ce22a69c8c64a96c7da5211816b36e1c27/src/DynamoRevit/DynamoRevit.cs#L192

**Comment by teocomi** [comment]
Thanks Mike!
