### ISSUE TITLE
View scale, please...

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#941]
Looks like there is no way of specifying a scale for the view-related nodes (currently Axonometric, Section, Drafting). 
When combining one of these nodes with the VIew Sheet node, the need to have the correct scale, otherwise aving Dynamo do the packing doesn't make sense...

**Comment by ksobon** [comment]
@andydandy74 this was resolved with the latest PR https://github.com/DynamoDS/DynamoRevit/pull/1377/commits/899132d15c7f4905432282d0f1f1d434cc7fcb94

**Comment by ikeough** [comment]
Closing this as I assume @ksobon is correct. @andydandy74 please re-open if we haven't solved it.
