### ISSUE TITLE
Dynamo crash while "Python Script" opening 

### ISSUE THREAD

**Issue by MarcinTata** [DynamoDS/Dynamo#9418]
Hello.
It happened to me first time. 
"Python from Script" is working and executes provided script. 
Background: lately I installed VisualStudio2017 with Python package.

## Dynamo version

2.0.2.6826

## Operating system

W10

## What did you do? 

I tried to open node "Python Script".

## What did you see instead?

Error message.

> Setting identificator of connectionId caused exception.
> 
>    w System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
>    w System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
>    w System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
>    w System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
>    w PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel, PythonNode nodeModel, NodeView nodeView, WindowRect& windowRect)
>    w PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
>    w PythonNodeModelsWpf.PythonNodeViewCustomization.view_MouseDown(Object sender, MouseButtonEventArgs e)
>    w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    w System.Windows.Input.InputManager.ProcessStagingArea()
>    w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    w System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    w System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    w System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    w System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    w MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    w System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    w System.Windows.Application.RunDispatcher(Object ignore)
>    w System.Windows.Application.RunInternal(Window window)
>    w DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)
>

**Comment by mjkkirschner** [comment]
what python package have you installed in visual studio?

**Comment by MarcinTata** [comment]
Actually, I'm not sure if it was a 'package' or a set of templates. 
Anyway I chose it at the same step of installation were I chose version of Visual Strudio (2017).
![obraz](https://user-images.githubusercontent.com/38285902/51127597-2039e600-1826-11e9-8c89-120e2b6764ad.png)

**Comment by MarcinTata** [comment]
Reinstallation of Dynamo does not help.

**Comment by mjkkirschner** [comment]
it's unclear to me if this has anything to do with your use of the python tools for vs.

* where are you using Dynamo, in revit?
* when you start dynamo do you see any green notifications in the dynamo menu? -Any about Avalon.Edit dll?
* what addins do you have installed for revit -? 
* Do you have the same issues when you run DynamoSandbox?

The exception itself is unfortunately not too useful, it just points to some xaml loader code from .net.  But this code is called when the python editor UI is called - which we use AvalonEdit for. I would start there looking for conflicts, like something else loading another version.

**Comment by MarcinTata** [comment]
Hello,

- I use DynamoSandbox and Dynamo in Revit. Dynamo crashes while opening 'python script' node only outside Revit.
- No green dot, no notifications.
- I did't install any Revit Extensios/addins. 
- Problem appears only in DynamoSandbox.

My packages:
- archi-lab.net
- BIM4Struc.Productivity
- BIM4Struc.Rebar
- BumbleBee
- Data-Shapes
- Dynamo Text
- DynaShape
- Simplex
- the-Saurus
- WombatDynamo

**Comment by mjkkirschner** [comment]
interesting - where are you running Sandbox from on disk?
Have you built sandbox yourself or this is one that installed with DynamoRevit?
Can you debug it to see the loaded modules?

**Comment by mjkkirschner** [comment]
also a first easy debugging step is to remove all the packages from your package folder and just place them outside of the package folder to see if the issue reproduces with all packages removed.

also - what versions of .net do you have installed?

**Comment by MarcinTata** [comment]
I run DynamoSandbox shortcut from desktop. DynamoSandbox is in C:\Program Files\Dynamo\Dynamo Core\2.
Removing all packages from package folder WORKS.

Then I found a package that seems to mess with Dynamo: its Simplex. The package enables Dynamo to work with a few other programmes.

These are .NET versions:
![net](https://user-images.githubusercontent.com/38285902/53357180-93f30680-392d-11e9-8825-0e7d53b86e57.PNG)

Soooo:  Simplex package is the problem.

**Comment by mjkkirschner** [comment]
is this package opensource somewhere?

**Comment by marcellosgamb** [comment]
I will work with mjkkirschner to resolve.
The simplex package may have extra references that are not needed
or may need to be split up
Yes it talks with 4 databases Revit, SAP, ETABS, TEKLA

**Comment by mjkkirschner** [comment]
@marcellosgamb - please reopen this issue if you were not able to resolve the problem with the python node editor.
