### ISSUE TITLE
Surface.PointAtParameter 

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#9424]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2.6826

## Operating system

Win 10

## What did you do? 

Intersect a cuboid with a surface, and attempted a Surface.PointAtParameter node after that. 

## What did you expect to see?

Points at the middle of the resulting surfaces (green in the screenshot below).

## What did you see instead?

Points at other locations (red in the screenshot below).

![image](https://user-images.githubusercontent.com/29869395/51137777-65055300-180d-11e9-9948-869d19232dd6.png)

This issue reproduces with various unexpected results from cuboid intersections, and persists into Dynamo for Revit versions as well (initially brought to my attention via this forum post - https://forum.dynamobim.com/t/finding-center-points-of-surfaces-with-surface-pointatparameter-question/30665?u=jacobsmall)

Remove the .txt to get a graph that readily reproduces the issue. Additional setups may be required to find other error states (as indicated by the results of the Dynamo for Revit graph in the forum post above)
[exampleFilePointOnSurface.dyn.txt](https://github.com/DynamoDS/Dynamo/files/2756881/exampleFilePointOnSurface.dyn.txt)

**Comment by mjkkirschner** [comment]
@JacobSmall what happens if you reverse the inputs to the intersection node - maybe the parameterization of the intersecting surfaces is that of the original rectangle.

**Comment by mjkkirschner** [comment]
@JacobSmall did you ever get to try reversing the inputs?

**Comment by JacobSmall** [comment]
@mjkkirschner - reversing the inputs does create the correct results, but the bug persists as it creates inconsistent results when used in the order I illustrated.

**Comment by mjkkirschner** [comment]
@aparajit-pratap what do you think? I'm not sure this is really a "bug" it's just that we don't document that the order of the intersection parameters will effect the resulting parameterization?

**Comment by JacobSmall** [comment]
@mjkkirschner, is the indication that the resulting surface from intersecting geometries is that the UV parameters are maintained as relative to their original geometry, not the resulting geometry? That is to say that since the original rectangle had a point at the origin for UV 0.5,0.5, all resulting intersections which produce a new surface are acting on the original surface, instead of the trimmed one?

**Comment by aparajit-pratap** [comment]
@JacobSmall yes, unfortunately the parameterization of a trimmed surface follows the parameterization of the original surface from which it was trimmed. This is a known "issue" that several users (Revit) have complained in the past. We would need to give this problem some thought from a geometry perspective before we get back to you.

**Comment by aparajit-pratap** [comment]
So I asked Tom Finnigan about this problem and this is what he had to say: 
"Keeping the original parameterization is very convenient for mapping points on the original, untrimmed surface to the trimmed surface, or back.  On the other hand, it is super handy that almost all surfaces in Dynamo are parameterized  [0..1,0..1].

However, what people would probably really want (the entire visible surface of every trimmed surface is [0..1,0..1]) isn't really possible in general - for it to work, the visible part of the trimmed surface needs to be rectangular, and all of its edges need to be straight lines in UV space, parallel to the original U and V.

I have seen tools that do a 'trim shrink', which shrink the UV space of the trimmed surface as closely as possible to the visible region, which would probably help in this case.  Maybe a separate node that does this would make sense?

The advantage of having it a separate node is that sometimes you want the parameterization to map to the original, and sometimes you want it to shrink the parameterization to the visible part of the surface.  It's relatively straightforward to go from original mapping to shrunk mapping, but very difficult to go the other way, unless you store extra information on every trimmed surface (essentially, the original untrimmed surface)"

From my experience listening to Dynamo users it looks like a lot of them want the latter, i.e. have the parameterization shrunk map to the visible part of the trimmed surface and from Tom's comments it sounds like there may be a way to do that using ASM: http://asmdoc.autodesk.com/sdk_release/dc/d65/class_a_s_m_1_1surface__xs.html#ac57ab4d727df8d69a4cc723b3f188a3f. I would vote for this to be an "improvement" feature in our geometry library.
