### ISSUE TITLE
Excel data export Failure

### ISSUE THREAD

**Issue by yunmemory** [DynamoDS/Dynamo#9425]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.2.6833

## Operating system

Windows 10

## What did you do? 

The dynamo node "Data.ExportExcel" didn't work after I upgraded the MS Project to 2016.

I've tried re-install the dynamo & delete the 1.8 key. However, none of them works. 

Could anyone provide any advice? Thanks.

## What did you expect to see?

solutions

## What did you see instead?

alternative solutions.

![dynamo bug](https://user-images.githubusercontent.com/18615900/51141898-6a1bcf80-1818-11e9-985f-6a233ce5794f.png)

**Comment by johnpierson** [comment]
@yunmemory Can you confirm if any of this applies to you? https://github.com/DynamoDS/Dynamo/issues/8857
