### ISSUE TITLE
Transaction Problem with Custom Variable Input Node

### ISSUE THREAD

**Issue by mrahmaniasl** [DynamoDS/Dynamo#944]
Hi,

I am trying to create a custom variable input node. The node that I am creating needs to make some changes on the model geometry in Revit but  I am having problem with transactions with Revit (As I see this type of node does not inherit Revit Transaction. Can you please guide me how to interact with Revit through this node?

I tried the following:
using (Autodesk.Revit.DB.Transaction tx = new autodesk.Revit.DB.Transaction(doc))
                    {
                        tx.Start("Dynamo" + i.ToString());
                        //Do Something
                        tx.Commit();
                    }

But I keep receiving error.
Thanks
Mohammad

**Comment by ikeough** [comment]
Closing as out of date. If this is still an error in more recent builds, please re-open.
