### ISSUE TITLE
How to get a wall reference 'point'

### ISSUE THREAD

**Issue by MarkAckerley** [DynamoDS/Dynamo#9450]
## Dynamo version
2.0.2

## Operating system
Windows 10

## What did you do? 
Tried to dimension at a junction of 2 walls which were not perpendicular

## What did you expect to see?
To get a reference Point at the junction (the faces were not perpendicular to the dimension so they could not be used)

## What did you see instead?
Only to get references as a face (or to lookup the face 'tag')

![image](https://user-images.githubusercontent.com/41670424/51533724-9bf5ed00-1e3b-11e9-8fe4-b1b81ae376b7.png)

In Revit I can dimension from a point like this...
![image](https://user-images.githubusercontent.com/41670424/51534054-9351e680-1e3c-11e9-8895-1bd7ce5e0791.png)

There is some related discussion here...
https://github.com/DynamoDS/Dynamo/issues/1704#issuecomment-45152511

**Comment by johnpierson** [comment]
Closing as this is a revit quesiton. Please open here. https://github.com/DynamoDS/DynamoRevit/issues
