### ISSUE TITLE
LibG error with Revit 2019.2?

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#9455]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2

## Operating system

Win10

## What did you do? 

Select model element, chose direct shape, tried to extract geometry via Element.Geometry

## What did you expect to see?

The geometry in Dynamo

## What did you see instead?

Nothing..
![image](https://user-images.githubusercontent.com/7080648/51661751-134d8d00-1fb2-11e9-97c3-36561645734c.png)

**Comment by mjkkirschner** [comment]
Hi @josols can you attach the .rvt file or simple one that reproduces this?

**Comment by johnpierson** [comment]
Related: https://forum.dynamobim.com/t/element-getlocation-not-working-since-revit-update-2019-2/31548/2

**Comment by mjkkirschner** [comment]
2.02 or 1.3.4 should be used when running on top of 2019.2 can you confirm that both dynamo revit and core are these versions?

**Comment by josols** [comment]
as famously put by George Bernhard Shaw: "The single biggest problem with communication is the illusion that it has taken place." 
User that reported have indeed used 2.0.1. I'll close and let my self out..
