### ISSUE TITLE
Dynamo graphics display doesn't work without an internet connection

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#9467]
## Dynamo version

1.3.3

## Operating system

Win 10

## What did you do? 

Opened dynamo for Revit and run a script which outputs protogeometry

## What did you expect to see?

The proto geometry (polygons and points to be precise)

## What did you see instead?

Nothing. Before asking the obvious, Background Preview is on.

Turns out, it disappears without an internet connection. Is this normal? 

From what I understand Dynamo uses an opensource graphics engine? Does this need to be online to register its use as part of some licencing? 

@kronz I'm jumping to a wild conclusion here as I don't really know if the above assumption is right; if it is then I jump to yet another assumption - could this be the offending party which is responsible for collecting users browser history which you reported, given the requirement for an internet connection for it to work?

**Comment by kronz** [comment]
What version of Revit are you using? Does it work in some versions of Revit and not others?

**Comment by mjkkirschner** [comment]
@ThomasMahon this sounds very odd - no it should not require any internet connection. Are we talking about tessellation / display or actual geometry creation failing?

**Comment by ThomasMahon** [comment]
Hi @mjkkirschner and @kronz 
Ok this is a weird one. First off, the issue was observed in Dynamo 1.3.3 and 2.0.1 and Revit 2017, 18 and 19. It only affects the tessellation in the Dynamo preview window; any Proto-Elements or Revit elements are created successfully and they even display in the transient view in Revit. 

Whenever I've experienced this problem its always at 40,000 ft in the air - yep, I code while flying, did you expect anything less! Which is why:
1. Flight mode on my laptop is on
2. Its the only place you'll find me where I wont be online (unless I fly Qatar)

However, my theory is debunked now I'm back on solid ground; oddly if I turn flight mode on, the tessellation is working? It only happens when I'm on a plane? When it first happened I tried uninstalling, and reinstalling Dynamo but it had no effect. 

I'm not quite sure what the best remedy is here as I cant reliably reproduce the issue.

**Comment by kronz** [comment]
Hmm, I can't recall our ever putting a barometer into any of our instrumentation. Not that this wouldn't be interesting ("Dynamo session length tends to decrease at altitudes above 5000m"). This sounds remarkably hard (and expensive) to debug. 
The only other thing I wonder about is your power mode, are you running on battery power on the plane and are your "when on battery" settings curtailing your graphics? 
When you failed to reproduce this on the ground, what else might have been different?

**Comment by ThomasMahon** [comment]
😂 I literally fell of my chair reading that! 

And with that Zach, you are indeed spot on - i always work on power saver mode in-flight, but nowhere else...and when I do that on stable earth (where I currently am) it causes the graphics problem. So its the power saving mode, not the internet connection. 

Thanks for the input and identifying the problem, its appreciated.
