### ISSUE TITLE
[Feature Request] Dynamo 2.0 Please expand Dictionary keys to all hashable c# objects and not just strings

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#9475]
## Dynamo version

2.0.2

## Operating system

N/A

## What did you do? 

N/A

## What did you expect to see?

Having all kinds of hashable objects as keys, or at the very least at least int & float numbers as keys, would make dictionaries immensely more useful. Not sure how complicated that will be from the VM's point of view but I hope it's as simple as changing the current <string, object> type to an <object, object> one.

## What did you see instead?

Currently (and back in prior versions when only arrayLists were used) the VM can only handle string values:

![image](https://user-images.githubusercontent.com/7148394/52322588-64ae4100-29e2-11e9-83d3-882f97936bde.png)

That's also why in my original implementation of `Dictionary.ByKeysValues` in spring nodes I chose to do the value lookup inside the script to avoid returning a dictionary object or some kind of a wrapped dictionary object

**Comment by aparajit-pratap** [comment]
@dimven similar requests have been brought up in the past and have been closed for certain design decisions we have made. For the sake of not repeating ourselves, please take a look at these discussions: https://github.com/DynamoDS/Dynamo/issues/8497#issuecomment-361332513, https://github.com/DynamoDS/Dynamo/issues/8759#issuecomment-382467614.

**Comment by dimven** [comment]
Thanks. These are valid concerns, I can see how this will complicate things in the DS VM. Because each node's result is a new object in memory to keep things immutable, that means you always have to compare by value and can't compare by reference like in other languages.
