### ISSUE TITLE
asynchronous or stop/start new events

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/Dynamo#9480]

**Comment by johnpierson** [comment]
@erfajo Are you simply trying to trigger a view change? 

This seems related to:

https://forum.dynamobim.com/t/changing-active-view-is-tempoerarily-disabled/9267/6?

**Comment by erfajo** [comment]
No that part is the easy part. I also used the asynchron `RequestViewChange` way to get a "current" view like Thomas apparently did. But that is not neither a solution or an answer to the problem, alltrough it seems similar on the bare surface.
I do always go to @jeremytammik whenever I need some further informations on an issue, he is a most reliable source. He also was in this case.
https://thebuildingcoder.typepad.com/blog/2017/02/setting-active-view-during-idling.html

The problem comes from this issue on Dynamobim forum... where my preliminary solution can be found
https://forum.dynamobim.com/t/how-to-set-the-active-view/31797/9

my preliminary code is as so...

```
        public static void SetOpenView(Revit.Elements.Element view, bool close)
        {
            // Close all transactions
            TransactionManager.Instance.ForceCloseTransaction();

            // current UI document
            uidoc = DocumentManager.Instance.CurrentUIDocument;

            Autodesk.Revit.DB.View newView = view.InternalElement as Autodesk.Revit.DB.View;
            uidoc.RequestViewChange(newView);

            //       From here comes problems!, I cant trigger en event,
            //       if that is not doable, then I cant trigger ActiveView

            // event handler start
            uiapp.Idling += new EventHandler<IdlingEventArgs>(idleUpdate);

            // set current view
            uiapp.ActiveUIDocument.ActiveView = newView;

            //       The below part can be executed, if the view is open in advance
            //       but if it is a new view, then I need to set the view not to be closed
            //       since you cant start/stop event, the new view is first open when 
            //       dynamo comes idle again... this is the problem

            if (close)
            {
                // current UI application
                uiapp = DocumentManager.Instance.CurrentUIApplication;

                var openViews = uiapp.ActiveUIDocument.GetOpenUIViews();
                foreach (var openView in openViews)
                {
                    if (openView.ViewId != newView.Id)
                        openView.Close();
                }
            }
        }
```

**Comment by aparajit-pratap** [comment]
@erfajo it sounds like what you're trying to find is a way to schedule a task (such as setting the active view) when Revit is idling on it's idle thread. If that's the case you may want to look at this method: https://github.com/DynamoDS/DynamoRevit/blob/4cc183fb6eb7db13e29cf2d04192df499961a8b9/src/DynamoRevit/DynamoRevit.cs#L61 `IdlePromise.ExecuteOnIdleAsync`. You can see that it is called in some places, for example a Draw routine where we wish to draw Revit graphics when control returns to Revit after a graph execution in Dynamo. Feel free to ignore if this is not what you're looking for.

**Comment by erfajo** [comment]
Thanks @aparajit-pratap, 
Since I am looking for a “needle”, this suggestion is as valid as any good suggestion.

**Comment by ThomasMahon** [comment]
@erfajo this might help:
![image](https://user-images.githubusercontent.com/18601851/52661193-681d5d00-2ef9-11e9-96a1-4b7d0a81da9f.png)

https://forum.dynamobim.com/t/how-to-set-the-active-view/31797/2
