### ISSUE TITLE
Minor Bug: `Auto` missing from the lacing menu when multiple nodes are selected

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#9483]
## Dynamo version

2.0.2

## Operating system

Win 10

## What did you do? 

Selected some nodes, right-clicked on the canvas and went to the lacing menu.

## What did you expect to see?

The default 'Auto' option in addition to the already existing `Shortest`, `Longest` and `Cross` options

## What did you see instead?

The auto option is missing

![image](https://user-images.githubusercontent.com/7148394/52529885-a36f2e80-2d35-11e9-928d-bcf27526b79c.png)

**Comment by QilongTang** [comment]
@dimven Would you be so kind to help us confirm that is it a regression from 1.3.x or not?

**Comment by dimven** [comment]
I don't think we can classify it as a regression, since 1.3 didn't have an official "Auto" lacing mode even tho that was the default under the hood. It was only added in 2.0. Looks to me like a simple fix, just add the matching MenuItem to the right-click menu:

https://github.com/DynamoDS/Dynamo/blob/d7eb46eec0c5f0192fab56af6abbbb9ec6191748/src/DynamoCoreWpf/Views/Core/WorkspaceView.xaml#L351

**Comment by alfarok** [comment]
solved with #9572
