### ISSUE TITLE
crashBug - I am not sure what is triggering this one - Causes multiple crashes, messages

### ISSUE THREAD

**Issue by EmCru** [DynamoDS/Dynamo#9499]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## [Dynamo version](url)

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

opened up this node (that I have used before effectively), copied the contents and dropped into my home screen.

## What did you expect to see?

I expected to be able to plug a list of elements into my node/workflow

## What did you see instead?

6 crash messages
[crash_GetElementLocationAsString.txt](https://github.com/DynamoDS/Dynamo/files/2876661/crash_GetElementLocationAsString.txt)

![image](https://user-images.githubusercontent.com/24195138/52964417-15a7ca80-3357-11e9-8e6b-62ccca7a35d8.png)

**Comment by EmCru** [comment]
![image](https://user-images.githubusercontent.com/24195138/53187159-5bfb6480-35b7-11e9-8a55-ea219a138e14.png)

I found that I was calling up "Get Keys" in a code block and believe that is what crashed my system

**Comment by mjkkirschner** [comment]
Hi @EmCru - if this is still occurring please attach the required files to reproduce and re-open this task.
