### ISSUE TITLE
Bug: Background preview adversely affected by geometry scaling settings

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#9501]
## Dynamo version

2.0.2 / 1.3.4

## Operating system

Win 10

## What did you do? 

Tried to create coordinate systems along a nurbs curve

## What did you expect to see?

the coordinate systems at the correct location along the curve

## What did you see instead?

the coordinate systems all bunched up near the origin

Same thing happens with the `Curve.HorizontalFrameAtParameter` node:

![image](https://user-images.githubusercontent.com/7148394/52994988-491c4f00-3454-11e9-9439-ffb9f45548cd.png)

**Comment by dimven** [comment]
Edit: Hmm, there seems to be something more funny happening. Even if I attempt to build the coordinate systems manually and set them at the supposedly correct origin, the CS preview in the background preview still appears wrong?

**Comment by ThomasMahon** [comment]
I believe this is correct - they're in the affine space which is unitless, like Revit (well, it uses vector space which does have a units system applied). You'll see the same phenomenon with vectors.

**Comment by mjkkirschner** [comment]
Do you see this with all curves, or only those extracted from revit locations curves?

**Comment by dimven** [comment]
This is happening to all curves and I managed no narrow down the cause - switching the `Geometry Scaling` to anything else than the default `Medium` setting interferes with the background preview:

![wkjbkykro5](https://user-images.githubusercontent.com/7148394/53055392-757eac80-34e2-11e9-8b75-cf724711b4b2.gif)

Just tested this on 1.3.4 and I'm seeing the same behavior, not sure about previous versions. While this is possibly not a regression, it's still an annoying bug.

**Comment by mjkkirschner** [comment]
@dimven thanks for investigating - @smangarole @aparajit-pratap @saintentropy  - this should be in libG yes?

**Comment by aparajit-pratap** [comment]
> This is happening to all curves and I managed no narrow down the cause - switching the `Geometry Scaling` to anything else than the default `Medium` setting interferes with the background preview:
> 
> ![wkjbkykro5](https://user-images.githubusercontent.com/7148394/53055392-757eac80-34e2-11e9-8b75-cf724711b4b2.gif)
> 
> Just tested this on 1.3.4 and I'm seeing the same behavior, not sure about previous versions. While this is possibly not a regression, it's still an annoying bug.
> 
> What's more concerning is that the preview of the nurbs curve is all over the place too.

This fix will be available in 2.3. The curve is changing because each time you change the geometry scale setting, the graph is made to re-execute and due to the `Math.Random`, a new curve is generated each time.
