### ISSUE TITLE
Mouse pointer size 4K screen

### ISSUE THREAD

**Issue by danielgijsbers** [DynamoDS/Dynamo#9514]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by johnpierson** [comment]
Hey @danielgijsbers , we need the information filled out in the report as well. I get that you are seeing issues on a 4k screen, but other information is great for our tracking purposes. Feel free to reopen and supply all the pertinent info and screenshots.

**Comment by danielgijsbers** [comment]
Hi John,

something went wrong with posting, i'll add the info now
