### ISSUE TITLE
Mandrill Pie Chart Error

### ISSUE THREAD

**Issue by dsmith76** [DynamoDS/Dynamo#9522]
## Dynamo version 
2.0.2

## Operating system
Windows 10

## What did you do? 
Running archilab Mandrill package. Report Window seems to cause crash.

## What did you expect to see?

Pie chart.

## What did you see instead?

Script completed. When clicking on Launch window to view crash occurs.

![image](https://user-images.githubusercontent.com/48027778/53433659-cd298600-39c2-11e9-8f6f-f56f71a54221.png)

**Comment by erfajo** [comment]
You need to ask the author of archilab Mandrill for this issue first. If the error is due to some coding in the package, then cant the dynamo team as such be responsible for this...
