### ISSUE TITLE
Number node missing bottom "balloon"

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#956]
So now almost all nodes have a nice expandable balloon on the bottom to report the values coming out of the node (I'm sure it has a name but it's not coming to me at the moment...my apologies but I'm jumping back in to playing around!). Is there a reason the number node doesn't have it? Since we can add variables to a number sequence such as 0..x..10 (input port x can be connected to a number slider for example), having the balloon list would be helpful, instead of having to attach to a watch node.

**Comment by johnpierson** [comment]
Closing as range functionality was moved to code blocks a while back which allows the preview bubble.
![image](https://user-images.githubusercontent.com/15744724/46478657-af0c8080-c7aa-11e8-9755-38a76a578ec4.png)
