### ISSUE TITLE
Node Package, Dependencies?

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#957]
I currently have a package that includes several nodes requiring that few external libraries (dlls).  Is there a way for me to distribute these libraries with the package and ensure that they end up in the right folders of the end user?

I see that there is a dependency field when creating a package but I do not see a way to specify them.

![image](https://f.cloud.github.com/assets/1890663/1816501/06820f4c-6f40-11e3-995e-99845ddab148.png)

**Comment by Racel** [comment]
This is supported now. Closing as fixed.
