### ISSUE TITLE
Custom nodes don't work/busted + horrendous developer experience

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#9576]
## Dynamo version

1.3.4

## Operating system
 Win 10

## What did you do? 

Created a custom node.

## What did you expect to see?

A working custom node.

## What did you see instead?

Null/failed execution with no exception. [begins slow clapping].

I believe this issue is caused by a limitation in CN's which for reasons unknown, cannot support a mix of singleton and list inputs? Whenever I create these things (which gladly is hardly ever), it always feels like a lottery with no certainty that strong-typed inputs with any rank declaration will yield the desired result hence why the developer experience is so bad.

I always strong-type the inputs and declare the rank for inputs requiring lists but no matter what i try (var[], var[]..[], convert to list internally etc), the node fails to execute and returns null. This limitation has blighted Dynamo for years - when will it be fixed?

**Comment by mjkkirschner** [comment]
Hi @ThomasMahon - do you think this is an issue with custom nodes, DS in codeblocks nested inside the custom node- or both?
Can you upload a minimal custom node which reproduces the issue?

**Comment by QilongTang** [comment]
@ThomasMahon Any example? Really would like to look into this for you
