### ISSUE TITLE
Minor UI Bug - Text can be typed whilst the package manager syncs with the server.

### ISSUE THREAD

**Issue by RyaPorter** [DynamoDS/Dynamo#9577]
## Dynamo version
Latest master branch (2.3)

## Operating system
Windows 10

## What did you do? 
Opened the package manager and started typing into the search box.

![PackageSearchSyncingProblem](https://user-images.githubusercontent.com/46380195/54431847-6248b080-471f-11e9-895b-f5b017578f66.png)

After sync the text remains behind the "Search..." string and has to be deleted to actually search.
![PackageSearchSyncingProblem_AfterSync](https://user-images.githubusercontent.com/46380195/54431852-6674ce00-471f-11e9-9ffe-dc966b25f3a6.png)

## What did you expect to see?
The text box should be collapsed until the sync has completed so a search query can't be typed until the package manager is ready.

## What did you see instead?
Can type search query whilst package manager is syncing with the server.

**Comment by johnpierson** [comment]
Yes! This bugs the heck out of me too!!!! Adding some labels to this.
