### ISSUE TITLE
Default Argument does not work on some machines

### ISSUE THREAD

**Issue by LongNguyenP** [DynamoDS/Dynamo#9579]
The default argument for ZeroTouch nodes (declared using the default argument attribute) does not work on some machines, while still working correctly on the others.

Apparently, this has been the case since Dynamo 1.3. But nobody has seemed to report it.

**Comment by mjkkirschner** [comment]
very likely this is caused by the packages installed on the machines. If a package bundles some other version of our DynamoServices assembly which includes the attribute havoc will occur. Remove packages which are bundling dynamo core dlls.

**Comment by mjkkirschner** [comment]
@LongNguyenP - also, try using the fully qualified name in the default argument snippet - whats an example of a non working argument?

**Comment by mjkkirschner** [comment]
@LongNguyenP please reopen if you are still encountering and can provide more info.

**Comment by LongNguyenP** [comment]
@mjkkirschner I always use fully qualified names for the default values. Also I never bundled standard Dynamo dlls together with my package distribution. But maybe these are bundled in other packages that the users previously downloaded?

**Comment by LongNguyenP** [comment]
Actually, I just checked again. I did not use fully qualified names all the time. I will try doing this and see. 
I will need to find a machine where this problem actually occurs. Never had this on my own computers
