### ISSUE TITLE
Element.Id_Crashing when I use node to code

### ISSUE THREAD

**Issue by EmCru** [DynamoDS/Dynamo#9595]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
windows 10
(e.g. Windows 7, Windows 8.1, etc)
[
![Revit__001_190325 11 02](https://user-images.githubusercontent.com/24195138/54942977-86f61280-4eed-11e9-8321-4404dce39e5a.png)
](url)
## What did you do? 

script crashes when I click node to code on the the element.Id

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by mjkkirschner** [comment]
Hi @EmCru what version of Dynamo are you using?

**Comment by EmCru** [comment]
[
![image](https://user-images.githubusercontent.com/24195138/54943186-04ba1e00-4eee-11e9-81f7-74f185e647e0.png)
](url)

I can call it directly and that is perfect, but I was teaching someone how to use node to code...lol.

**Comment by EmCru** [comment]
![image](https://user-images.githubusercontent.com/24195138/54943324-42b74200-4eee-11e9-98db-9cf56226cd01.png)

**Comment by johnpierson** [comment]
@EmCru can you provide a screenshot of your manage packages window as well?

**Comment by mjkkirschner** [comment]
I think this should be fixed in 2.1.

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/Dynamo/pull/9330/files
