### ISSUE TITLE
ImportCSV not working in 2.0.2

### ISSUE THREAD

**Issue by Abstractmachina** [DynamoDS/Dynamo#9626]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2.6833

## Operating system

Win7

## What did you do? 

Importing a CSV file written from GH C# component.

## What did you expect to see?

list of point coordinates.

## What did you see instead?

null. 
I have also Dynamo 1.3.4.6666 installed and it works flawlessly there.

**Comment by Abstractmachina** [comment]
Oops, this should have gone on the Dynamo for Revit Issues page. So sorry!

**Comment by mjkkirschner** [comment]
without the graph in question cannot make a good guess as to the issue. Please reopen if you have not solved it with more info.
