### ISSUE TITLE
Quick question: SupressImportIntoVM() attribute 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#9628]
Quick question re the SupressImportIntoVM() attribute

Does this simply prevent any member with the attribute from being 'seen' by the VM so users cant call it in DesignScript or does it do something more? Are there any drawbacks of using it? 

The reason for using it has come about from an interface in ZT nodes which is being implemented in a number of classes. As the properties have to be marked public, I don't want them to appear as nodes in the library nor do I want them hidden from the library; suppressing them seems like the right way to go. I don't think its an issue regardless since the classes are private, but I'm not the type who develops shoddy code!

@mjkkirschner

**Comment by mjkkirschner** [comment]
Hey @ThomasMahon - This attribute actually blocks the member from being imported into the VM and a new class or member from being generated. It's different from hiding it from the library where it's still callable via DS. You can use it when importing into the VM causes some issue (a bug, or other unexpected consequence)

Downside is that you can't do this if for example you require users to pass one of these types as an input to another node.

If the members are private already they are already suppressed.

**Comment by mjkkirschner** [comment]
for example:
https://github.com/DynamoDS/Dynamo/blob/0dbc0cc413cfa662f76879e3c496ef470b84b5ae/src/Engine/ProtoCore/FFI/CLRDLLModule.cs#L399

if this function returns true (it checks the attribute) then the member is just skipped.

**Comment by ThomasMahon** [comment]
Thanks @mjkkirschner this is really useful.

**Comment by johnpierson** [comment]
Seems this was resolved, so I am closing for now. Feel free to reopen if need be! 😁
