### ISSUE TITLE
Dynamo CLI IGraphicItem runtime error 

### ISSUE THREAD

**Issue by milotindragos** [DynamoDS/Dynamo#9630]
## Dynamo version

**Edition**: Dynamo Core Runtime CLI
**Version**: 2.1.0.7500

## Operating system

**Edition**: Windows 10 Home
**Version**: 1809
**OS Build**: 17763.379

## What did you do? 

Run a simple Dynamo script using the command:
```
cd /d LOCATION && start DynamoCLI.exe -o "LOCATION\Simple-Create-Cube-Export-to-SAT.dyn"
```

## What did you expect to see?

Export a 1 meter cube to a SAT file. 

## What did you see instead?

I got an `error` but the `.dyn` file still **executes correctly**. 
```
Error: Can't import Autodesk.DesignScript.Interfaces.IGraphicItem, IGraphicItem is already imported as Autodesk.DesignScript.Interfaces.IGraphicItem, namespace support needed. loaded file
```

**Comment by mjkkirschner** [comment]
The error means that something in your graph or a package you are loading - something external to a plain Dynamo session is trying to import the graphicItem interface. It's probably happening when you use Dynamo as well (check the console)

check your packages for those which might include `DynamoServices.dll`

**Comment by milotindragos** [comment]
> The error means that something in your graph or a package you are loading - something external to a plain Dynamo session is trying to import the graphicItem interface. It's probably happening when you use Dynamo as well (check the console)
> 
> check your packages for those which might include `DynamoServices.dll`

That is a bit strange as **no other Dynamo sessions are running**, Revit is not running .etc, nothing else but the command line terminal is running on the computer.

The graph that I am running is the *simplest* I could think of to create some geometry and export that out **to validate that the CLI command ran successfully**. 

![DynamoCLIerror](https://user-images.githubusercontent.com/30367360/55677677-f7d0fd80-58e3-11e9-8590-dcf341e8fa71.png)

**Comment by mjkkirschner** [comment]
When the CLI runs it will run dynamo like normal, this means that packages,custom nodes, zt.dlls are imported etc.

1. Check the dynamo console during a normal session - do you see the same exception?
2. Remove all packages from your package folders / package paths -  run the CLI again - do you see the error?

**Comment by mjkkirschner** [comment]
closing - please reopen if still occurring with more information requested.
