### ISSUE TITLE
Dynamo Sandbox cannot open dyn files

### ISSUE THREAD

**Issue by alfonsomonedero** [DynamoDS/Dynamo#9633]
## Dynamo version
Dynamo sandbox 2.0.2.6826
Windows 10

## What did you do? 

Open an existing graph, just a couple of nodes.
Dynamo crashes and is not able to open any saved DYN file
It doesn't give a report specifying why it crashes

![image](https://user-images.githubusercontent.com/43339587/55715076-dbb88380-59eb-11e9-8ba5-3ff914953e5c.png)

**Comment by mjkkirschner** [comment]
@alfonsomonedero - please try 2.0.3.

**Comment by johnpierson** [comment]
If this persists in 2.0.3 for you, please feel free to reopen and update accordingly.
