### ISSUE TITLE
Dynamo Developer Guidance: NodeModel

### ISSUE THREAD

**Issue by OliverEGreen** [DynamoDS/Dynamo#9638]
## Dynamo version
Dynamo v2.1

## Operating system
Windows

## What did you do? 
This was raised at the London Dynamo Hackathon; I found some outdated API calls in the NodeModel guidance page here:
https://developer.dynamobim.org/03-Development-Options/3-5-nodemodel-derived-nodes.html

The outdated API call is: 
`if (!HasConnectedInput(0) || !HasConnectedInput(1))`

The HasConnectedInput() method seems to have been deprecated in v2.1. I forget the new method name but I was asked by @lukechurch to raise this.

**Comment by mjkkirschner** [comment]
should be updated to `InPorts[index].IsConnected` I think.

**Comment by QilongTang** [comment]
@OliverEGreen @lukechurch  Please refer to https://github.com/DynamoDS/Dynamo/wiki/API-Changes#202

**Comment by mjkkirschner** [comment]
fixed in above post.
