### ISSUE TITLE
Wish: Warning when other windows/dialogs are open

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#965]
Running a definition will only work when I have no other dialogs open in Revit/Vasari. If I do, the Run button will turn grey, but the definition will only get evaluated once I close the other dialog.
It would be helpful if Dynamo could warn me (console or alert) why the defintion is not evaluated. On a system with multiple monitors this is probably a non-issue, but on a notebook it's a different story.

**Comment by Racel** [comment]
@andydandy74 @mjkkirschner @QilongTang - Would putting something in the notification window work? And, is this a non-issue with Revit 2017.1 and higher?

**Comment by andydandy74** [comment]
@Racel - Since this issue also extends to active commands in Revit (e.g. Trying to run Dynamo after having started the Wall command in Revit), I doubt that the behaviour in 2017 or 2017.1 will be any different.

**Comment by andydandy74** [comment]
@johnpierson Glad that you're re-tagging this old issue. Should I perhaps reopen it on the DyanmoRevit repo?

**Comment by johnpierson** [comment]
Hi @andydandy74! Yes, that would be great as it is a Revit-Centric item. 🙂 Thanks!
