### ISSUE TITLE
Can't work out how to install Dynamo 2.1.0

### ISSUE THREAD

**Issue by DuncanLithgow** [DynamoDS/Dynamo#9657]
## Dynamo version
2.1.0

## Operating system
Windows 10

## What did you do? 
Downloaded DynamoCoreRuntime2.1.0.zip, unpacked the archive.
Trying to install, none of the .exe files appear to install anything to my system.

I tried copying the folders contents to C:\Program Files\Dynamo in a few different places and that didn't make any difference.

## What did you expect to see?
A setup.exe file or similar
Dynamo opening to the latest version from inside Revit.

## What did you see instead?
No obvious way to install anything. I guess the place to explain what I should be doing is here: https://primer.dynamobim.org/02_Hello-Dynamo/2-1_launching_dynamo.html

I expect I'm doing something obviously wrong, but then again new users like me need lots of help in the beginning.

**Comment by mjkkirschner** [comment]
Please see 

https://dynamobim.org/a-new-way-to-get-dynamo-sandbox/

This is not intended as an installer on top of Revit.

**Comment by DuncanLithgow** [comment]
Here [ https://primer.dynamobim.org/02_Hello-Dynamo/2-1_launching_dynamo.html ] the installer is shown with options to install the core and Revit components. But I can't find an installer, and not surprisingly Revit is not seeing that I've downloaded a newer version.

**Comment by QilongTang** [comment]
@DuncanLithgow Please refer to the following graph in our official release announcement https://dynamobim.org/dynamo-core-2-1-release/.


_As Dynamo is now a feature of Revit, you will not be able to remove, uninstall or downgrade your Dynamo version but will also no longer have to support multiple versions of Dynamo with each install of Revit nor update Dynamo versions in Revit._

_This also means that the Dynamo team will no longer deliver installers for Dynamo Revit and Revit will instead start shipping newer versions of Dynamo on a regular basis. This means you will get an updated Dynamo version when Revit releases a new version meaning more stability and performance with less overhead requirements_

**Comment by DuncanLithgow** [comment]
Maybe that should be mentioned at https://dynamobim.org/download/ where many newbies and people used to the previous process would look for the installer (for Revit plugin). 

https://primer.dynamobim.org/02_Hello-Dynamo/2-1_launching_dynamo.html links to that page as the place to get an installer for Revit. Should I just write to the maintainers of the documentation? 

Is this something for @johnpierson ?

**Comment by johnpierson** [comment]
@DuncanLithgow , open an issue on the primer repo here, https://github.com/DynamoDS/DynamoPrimer/issues and reference this one. Additionally, this blog post, https://dynamobim.org/dynamo-core-2-1-release/, has more information regarding Revit 2020 compatibility. Considering 2020 just came out and the primer is written for installations previous to this, the instructions are still completely valid for all releases before 2020.
