### ISSUE TITLE
Dynamo 2.02 freezing, nodes not visible, unable to place any nodes, basically not working

### ISSUE THREAD

**Issue by pbiggers18** [DynamoDS/Dynamo#9669]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by Amoursol** [comment]
Hello @pbiggers18 - Does this problem still exist for you in the 2.0.3 build?

**Comment by mjkkirschner** [comment]
closing - please reopen if this is still an issue with latest DynamoRevit.

**Comment by XTDHub** [comment]
This is happening to me at the moment and I'm on 2.3
