### ISSUE TITLE
Switching to Remote Session Crashing Dynamo on Browsing Getting Started

### ISSUE THREAD

**Issue by QilongTang** [DynamoDS/Dynamo#9681]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.1.0.7500

## Operating system

Windows 10

## What did you do? 

Launched `Getting Started` and switched to use remote desktop into current session which changed screen resolution

## What did you expect to see?

I can still browse `getting started`

## What did you see instead?

![image](https://user-images.githubusercontent.com/3942418/56685862-dff9c780-66a0-11e9-91d7-4549c4d10c24.png)

**Comment by mjkkirschner** [comment]
@QilongTang did you address this with a PR?

**Comment by QilongTang** [comment]
@mjkkirschner https://github.com/DynamoDS/Dynamo/pull/9848 .. I can't believe I forgot that this was reported by myself in April
