### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in LibG.Managed.dll Additional information: Attempted to read or write protected memory.  / Sandbox not starting?

### ISSUE THREAD

**Issue by grittmw** [DynamoDS/Dynamo#9696]
## What did you do? 
In Visual Studio 2017 I created a custom node by following
http://teocomi.com/dynamo-unchained-1-learn-how-to-develop-zero-touch-nodes-in-csharp/
I used the Nuget packages 
![image](https://user-images.githubusercontent.com/50228739/57133686-df011e00-6da3-11e9-9f74-2e5abdd17273.png)
![image](https://user-images.githubusercontent.com/50228739/57133788-37382000-6da4-11e9-9650-2eb22cfcb10e.png)

This worked yesterday. Now I am reproducing it, but it doesn't work. In between I tried to make node with pull down wpf item. Here al the problems started. 

## What did you see instead?

An unhandled exception of type 'System.AccessViolationException' occurred in LibG.Managed.dll Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by grittmw** [comment]
Maybe it has something to do with DynamoSandbox? It now doesn't start at all.

**Comment by QilongTang** [comment]
@aparajit-pratap @mjkkirschner Seeing this exception again, is this one also related to https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#dispose--using-statement?

**Comment by aparajit-pratap** [comment]
@grittmw could you share your zero touch node implementation.

**Comment by mjkkirschner** [comment]
Please reopen if this is still occurring after using the dispose pattern.
