### ISSUE TITLE
Dynao doesn't visualize any nodes

### ISSUE THREAD

**Issue by lifeiskkang** [DynamoDS/Dynamo#9699]
[If](url) this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
both Dynamo 2017 and new version in Revit 2020

## Operating system
window 10

## What did you do? 
1. I made 3 points. it didn't show any points and the basic coordinates with blue in background
2. i just opened 'basics_basic01.dyn' from samples in Dynamo. Also, it didn't visualize anything.

## What did you expect to see?

visualization of some shape or points.

## What did you see instead?

i couldn't see anything. 
only comment : run completed
![안됨다이](https://user-images.githubusercontent.com/50241695/57195618-119e4880-6f55-11e9-9c30-ebe1ec2d5299.PNG)
![안됨다이나모](https://user-images.githubusercontent.com/50241695/57195628-1c58dd80-6f55-11e9-918a-fa3ec948af44.PNG)

**Comment by QilongTang** [comment]
@jnealb @smangarole @mjkkirschner Have you seen this before? This looks like missing DirectX or some Graphic Card issue?

**Comment by lifeiskkang** [comment]
![그래픽카드](https://user-images.githubusercontent.com/50241695/57545576-0b480c00-735b-11e9-93ef-7faa59b992be.PNG)
I can use only Revit

**Comment by mjkkirschner** [comment]
I think this is a conflict between studio and revit - @kronz may remember this issue... I cannot recall the solution - I think Studio had to be uninstalled and a newer core installed.

**Comment by kronz** [comment]
Before trying to uninstall Studio, have they tried this (first item) https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

**Comment by mjkkirschner** [comment]
@lifeiskkang please reopen if you have not been able to resolve.
