### ISSUE TITLE
List.Transpose: ArrayList output

### ISSUE THREAD

**Issue by torkuen** [DynamoDS/Dynamo#9714]
List.Transpose outputs an ArrayList that can´t be used directly.

## Dynamo Version
2.0.2.6833

## Operating system

Windows 7

## What did you do? 

Transposing a list of points and use the output.

## What did you expect to see?

Normal behaviour of the points list

## What did you see instead?

List was not accepted as it was an ArrayList
![List_Tranpose_ArrayListOutput](https://user-images.githubusercontent.com/7558042/57775770-11a10400-771e-11e9-8e32-b2d43d578b67.png)

**Comment by mjkkirschner** [comment]
We're not able to reproduce this.
do you have some packages installed?

**Comment by mjkkirschner** [comment]
without more info cannot reproduce. Please reopen with more info.
