### ISSUE TITLE
List.Transpose: List structure inconsistency

### ISSUE THREAD

**Issue by torkuen** [DynamoDS/Dynamo#9715]
## Dynamo version
2.0.2.6833

## Operating system

Windows 7

## What did you do? 

Transpose two list of same structure

## What did you expect to see?

same result

## What did you see instead?

different list structures
[ListStructure_Inconsistency.pdf](https://github.com/DynamoDS/Dynamo/files/3182834/ListStructure_Inconsistency.pdf)

**Comment by mjkkirschner** [comment]
we cannot reproduce this, can you share the files?
