### ISSUE TITLE
Dynamo Double Compare Inconsistency

### ISSUE THREAD

**Issue by RyaPorter** [DynamoDS/Dynamo#9733]
## Dynamo version
2.3.0.5074 (master branch)

## Operating system
Windows 10

## What did you do? 
Compared to doubles (4.701312264353, 4.70131302602723)

## What did you expect to see?
The comparison 4.701312264353 < 4.70131302602723 to evaluate as True.

## What did you see instead?
It evaluated as false:
![Dynamo_CompareError](https://user-images.githubusercontent.com/46380195/58257398-c2d01b80-7d68-11e9-96a9-f5fed28411da.png)

I'm pretty sure I'm not missing something obviously stupid. But Python confirms that something fundamental is wrong with, I'm guessing, DesignScript. (Again if I'm not missing something obviously stupid).

**Comment by RyaPorter** [comment]
It seems very inconsistent. Returning different results depending on the amount of decimal points and significant figures:

![Dynamo_CompareError_the_plot_thickens](https://user-images.githubusercontent.com/46380195/58264987-bfdc2780-7d76-11e9-9736-d1412f3b256d.png)

![Dynamo_CompareError_SigFigSmall](https://user-images.githubusercontent.com/46380195/58264995-c10d5480-7d76-11e9-870b-3c2c82d104ae.png)

![Dynamo_CompareError_the_plot_thickens_again](https://user-images.githubusercontent.com/46380195/58265218-282b0900-7d77-11e9-90c6-4a185ea0a75e.png)

**Comment by mjkkirschner** [comment]
this is partially resolved. Equality still remains tolerant, discussing solutions at this point.

**Comment by mjkkirschner** [comment]
This should now be resolved I think as a new tolerant equals node has been added where tolerance is specified.
