### ISSUE TITLE
Sequence and Sliders Disappear

### ISSUE THREAD

**Issue by estanima** [DynamoDS/Dynamo#9740]
When I save and reopen a dynamo file that had sequence and number sliders they disappear and have to recreated.

**Comment by mjkkirschner** [comment]
@estanima need more info to help you -
* what version of dynamo are you using?
* what application are you using Dynamo in?
* do you see errors in the console?
* do you have other addins or plugins installed in the host application (old pyRevit for example?)
* do you see any green notifications in Dynamo's menu bar?

**Comment by mjkkirschner** [comment]
I believe this has been fixed on the civil side.
