### ISSUE TITLE
Auto-generate package document

### ISSUE THREAD

**Issue by lukechurch** [DynamoDS/Dynamo#975]
We need to be able to support extensible, auto-generated documentation of core library. We need to support a mechanism where users can contribute to this documentation and have it automatically folded into the various documentation locations, inline and in generated documents.

This mechanism also needs to work for nodes in the package manager and custom nodes.

An excellent starting example is this: https://www.dropbox.com/s/vhrs722sa6s208a/Node-Book_for_Dynamo.xlsx from Thomas Vogt

**Comment by Racel** [comment]
Hi @lukechurch - we now have the dynamo dictionary: dictionary.dynamobim.com

Closing :)
