### ISSUE TITLE
Corridor.GetSolids not working

### ISSUE THREAD

**Issue by wcheungSpatial** [DynamoDS/Dynamo#9774]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.1.1.7865
Dynamo Civil3D 2.1.1.896

## Operating system
Window 10

## What did you do? 
The program is coming from samples/Case03/SplitCorridorSolid in DynamoCivil3D
The node Corridor.GetSolid do not get any output.

## What did you expect to see?
It should create solid object from corridor in Civil3D 2020

## What did you see instead?

![Civil3D Dynamo Error](https://user-images.githubusercontent.com/51431517/59006263-8cf46200-8853-11e9-87a8-09260557fb69.PNG)

**Comment by mjkkirschner** [comment]
Can you provide the drawing you are running that sample on?

**Comment by NigelPMPeters** [comment]
the GetSolids node ios a query node for locating any already created solids in the Civil3D Drawing. It is not designed to create the solids.
