### ISSUE TITLE
Entire Node Library Missing

### ISSUE THREAD

**Issue by Icomanman** [DynamoDS/Dynamo#9789]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

DynamoCoreRuntime2.1.0 (Dynamo Core 2.1.0.7500) downloaded as .zip file

## Operating system

Windows 10

## What did you do? 

Downloaded the zip file, extracted the contents then run the "DynamoSandBox.exe"

## What did you expect to see?

The library on the left panel

## What did you see instead?

None
![DynLib](https://user-images.githubusercontent.com/26214100/59264008-bd604580-8c31-11e9-8b79-49d71993bcd4.png)

**Comment by mjkkirschner** [comment]
please follow this wiki and re-open back if it still occurs:
https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds

**Comment by Icomanman** [comment]
Thank you for the response above. I have read it and it's very helpful. 
However, I would like to clarify this "Optional Components." Does that mean, I can no longer use the Geometry Library without Revit? Because I have used Dynamo in the past and I never had this issue, that I was able to install and run it without any other Autodesk product (If I remember correctly, this was version 0.7.x). Hence I tried downloading the version 0.7.5 to check if it would run ok. Nevertheless, I get the same problem.

So, again, can I no longer use the Geometry Library (or any other Libraries) ? If so, can you help me find a version of Dynamo that's not Autodesk product-dependent?
![OptionalComp](https://user-images.githubusercontent.com/26214100/59546608-27256b80-8f20-11e9-9004-1a25eb4d391b.png)
without Revit?
