### ISSUE TITLE
Maximize Window Crashing

### ISSUE THREAD

**Issue by Icomanman** [DynamoDS/Dynamo#9790]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.1.0.7500

## Operating system

Windows 10

## What did you do? 

Clicked the maximize button

## What did you expect to see?

Maximized window

## What did you see instead?

Crashing

**Comment by mjkkirschner** [comment]
@Icomanman do you get a particular stack trace you can share?

**Comment by mjkkirschner** [comment]
closing this as no actionable info - if you see this again please share the stack trace. Thanks.
