### ISSUE TITLE
dynamo stuck running

### ISSUE THREAD

**Issue by Sirdanly** [DynamoDS/Dynamo#9792]
using dynamo 1.2.2.373 on revit 2018.3.2. it used to work but now just stuck on running but not doing anything

**Comment by johnpierson** [comment]
If I recall correctly, Dynamo 1.2.2 was not compatible with Revit. Have you tried updating to a newer version? The most recent stable version of Dynamo for Revit 2048 is Dynamo 1.3.4. This is documented in the primer [here](https://primer.dynamobim.org/08_Dynamo-for-Revit/8-1_The-Revit-Connection.html)

**Comment by mjkkirschner** [comment]
please reopen with more info if this is not resolved.
