### ISSUE TITLE
What is the contains_binaries parameter in the Package JSON file used for?

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#9794]
Dear Dynamo team

As above, what does the contains_binaries key do in the package JSON file? 

The reason for asking is becuase installs of BimorphNodes via the package manager shows this warning and I'm thinking this warning may be triggered by this parameter? Is that the case as its a nonsense warning...there are no Python binaries in the package (there were in older versions, which may explain why this parameter set to true still persists until today):
![image](https://user-images.githubusercontent.com/18601851/59507412-e3d8e780-8ea2-11e9-998f-93c4da3438f1.png)

This warning sometimes is enough to stop users from installing a package as they assume its a compatibility issue (or they dont read or understand it and and naturally cancel the install - which isn't good.

If I change this parameter to false, the package still loads, so I'm guessing I can update it via the package manager and there will be no adverse affects and no redundant warnings?

**Comment by mjkkirschner** [comment]
@ThomasMahon - this property is true if your package contains binaries (.dlls/compiled code, binary files) - `OR` python nodes. - IE anything not designscript or customNodes (excluding python nodes in those custom nodes)

**Comment by mjkkirschner** [comment]
@ThomasMahon closing this - if you want to discuss further please reopen.
