### ISSUE TITLE
Dynamo no preview

### ISSUE THREAD

**Issue by petrasvestartas** [DynamoDS/Dynamo#9811]
I am new Dynamo user, who just installed Revit 2019 and opened the Dynamo Sandbox from program files. I believe I do not need to download dynamo as it is part of Revit?

After openning the Dynamo for the first time, I tried to draw a simple circle, but nothing appears on my screen. What is wrong?

I do not see the grid as in typical tutorials.

![a613b5647a930d081feea6171d41ddcf56cf3b7a](https://user-images.githubusercontent.com/18013985/59968902-94518600-954a-11e9-8dd2-f05f587c4752.png)

## Dynamo version

Just install Revit 2019

## Operating system

(eWindows 10)

## What did you do? 

Just tried to open Dynamo

## What did you expect to see?

Preview

## What did you see instead?

Nothing

**Comment by mjkkirschner** [comment]
try this:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ

when you use sandbox try forcing high performance GPU mode using your GPU control panel - force it specifically for the DynamoSandbox exe you are using.

But if you want to use Dynamo in Revit - don't use sandbox - use Dynamo under the manage tab in the Revit UI.

Sandbox is a standalone development environment.

**Comment by mjkkirschner** [comment]
seems like this was figured out on the forum - please reopen if not.
