### ISSUE TITLE
Can't see 'Watch Image' and 'Watch 3D' nodes in Dynamo Player as an Output. 

### ISSUE THREAD

**Issue by ashwanidv100** [DynamoDS/Dynamo#9856]
## Dynamo version

Dynamo Core 2.0.0.4654
Dynamo Revit 2.0.0.4655

## Operating system

Windows 10

## What did you do? 

Check Mark the node property 'Is Output' and reload it in Dynamo Player to see.

## What did you expect to see?

Wanted to see the Output Result from 'Watch Image' and 'Watch 3D' in Dynamo Player

## What did you see instead?

Nothing get as an result

**Comment by johnpierson** [comment]
I have been told that it is probably better to share ideas like this one at the Revit  Ideas page here, https://forums.autodesk.com/t5/revit-ideas/idb-p/302

**Comment by ashwanidv100** [comment]
Ahh, I didn't know this falls in Revit wish list, I thought it was falling under Dynamo development. No Issues than Thanks @johnpierson
