### ISSUE TITLE
'Is Input' option is not available for 'File Path' Node (Dynamo Version 2.0.0.4654)

### ISSUE THREAD

**Issue by ashwanidv100** [DynamoDS/Dynamo#9857]
If not recommend to upgrade dynamo but in this given Dynamo version 
'Is Input' option is not available for 'File Path' Node

## Dynamo version

Dynamo Core 2.0.0.4654
Dynamo Revit 2.0.0.4655

## Operating system

Windows 10

## What did you do? 

Look into the 'File Path' properties

## What did you expect to see?

Like to see 'Is Input' option in 'File Path' Node

## What did you see instead?

'Is Input' option in 'File Path' Node not available

**Comment by Amoursol** [comment]
@saintentropy can we throw this one to you and the Refinery team please. 

Side note, as previously mentioned, can we migrate all Refinery issues to a more appropriate place?

**Comment by ashwanidv100** [comment]
Hi @Amoursol , Is there any update on this. I think this Issue is resolved in new updates. It would be good to close it off then.

**Comment by QilongTang** [comment]
@ashwanidv100 Hi, thank you for reminding us! This has indeed been fixed as part of Dynamo 2.0.1 ( please refer to https://github.com/DynamoDS/Dynamo/pull/8846 by @saintentropy ). You should be able to utilize this functionality from the versions above. If you are still using Revit 2017 to Revit 2019, you can use the Dynamo installer 2.0.1 or 2.0.2 at https://dynamobuilds.com/. If you are using Revit 2020, Dynamo should be ready for you there. Let us know if you have questions! Closing this.
