### ISSUE TITLE
I can not view the library column

### ISSUE THREAD

**Issue by arquiman** [DynamoDS/Dynamo#9893]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 2.0 Sandbox

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 7

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

I can not see the library column. I've just installed dynamo on my pc.

## What did you expect to see?

How to activate it. 

![image](https://user-images.githubusercontent.com/53914593/62726458-8df26d00-ba17-11e9-9ed7-7720cb471ac4.png)

**Comment by mjkkirschner** [comment]
please read through this document:
https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds

**Comment by Amoursol** [comment]
Hello @arquiman - Were you able to fix the problem with Mike's solution?

**Comment by arquiman** [comment]
Yes!! Finally it could be a problem related with Windows updates, so
updating and restarting the computer was enough!
