### ISSUE TITLE
search returned no results in package search

### ISSUE THREAD

**Issue by MichielSchiks** [DynamoDS/Dynamo#9896]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.3.8810

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

want to download a package

## What did you expect to see?

packages

## What did you see instead?

no results.

**Comment by MichielSchiks** [comment]
Hello all, please help! I want to set up a script but can't get packages. If I download them from the website and insert in the right root folder, they show up in 'manage packages' but not in the library and so I can not use them. Search the internet but didn't find a solution. Any suggestion how this is possible. I am working in a private laptop.
Many thanks!

**Comment by mjkkirschner** [comment]
Hello 

This may have to do with TLS security updates - please make sure you are using up to date revit with latest patches - what revit version and build are you using ?

When you download packages from the site use 7zip to unzip them or try unblocking the zip before unzipping.

**Comment by MichielSchiks** [comment]
This is the version I use:         19.0.1.1
Nu updates available when I open the Autodesk Desktop App.

**Comment by mjkkirschner** [comment]
https://knowledge.autodesk.com/support/revit-products/downloads/caas/downloads/content/autodesk-transport-layer-security-updates-require-security-fix-for-revit-2019.html

see this page, you need to update to 2019.0.2 or 2019.2

**Comment by MichielSchiks** [comment]
Thank you very much!!! It works.. Brilljant ;)
