### ISSUE TITLE
Wishlist: comments / issues with custom packages.

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/Dynamo#993]
a possible improvement to the package manager website would be the ability to add comments on the package directly to let the author know of issues or to ask questions.

also, maybe a link to the package website page directly from each package? Is the only way to find it through the manage package menu?

**Comment by Racel** [comment]
@mjkkirschner - The team does not have bandwidth to address this in the near future. Trying to assess how useful this is. Can we close this?
