### ISSUE TITLE
Search for a package not working

### ISSUE THREAD

**Issue by SheilaBombin** [DynamoDS/Dynamo#9933]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.4

## Operating system

Windows 10 Enterprise

## What did you do? 

Search for a package

## What did you expect to see?

A list of the avaible packages

## What did you see instead?

Blank

**Comment by QilongTang** [comment]
@SheilaBombin Please refer to https://knowledge.autodesk.com/support/revit-products/downloads/caas/downloads/content/autodesk-transport-layer-security-updates-require-revit-security-fix.html you may need to update the Revit security update

**Comment by mjkkirschner** [comment]
closing, pleas reopen if AKN updates did not fix this.
