### ISSUE TITLE
Crash - Unhandled

### ISSUE THREAD

**Issue by JackalRockan** [DynamoDS/Dynamo#9938]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo core : 2.0.2.6826
Dynamo Revit : 2.0.2.6833

## Operating system

Windows 10

## What did you do? 

Running a script usually working (and for the 10th time today), got this crash. I rebooted the pc, dynamo, revit, even copied the whole script into another dynamo file, still the same issue

## What did you expect to see?

Just filling a small excel with 5 row and 3 collumn

## What did you see instead?

This crash. 

![image](https://user-images.githubusercontent.com/54539078/63692443-f57b2b80-c811-11e9-8834-4ea7ac3a3d7e.png)

L'index se trouve en dehors des limites du tableau.

   à ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   à ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   à ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   à ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   à ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   à ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   à ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   à ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   à ProtoScript.Runners.LiveRunner.ApplyUpdate()
   à ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   à ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   à ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   à Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   à Dynamo.Scheduler.AsyncTask.Execute()

[Métré Villa.zip](https://github.com/DynamoDS/Dynamo/files/3541202/Metre.Villa.zip)

**Comment by mjkkirschner** [comment]
tracked with https://jira.autodesk.com/browse/DYN-2285

**Comment by smangarole** [comment]
@JackalRockan Can you please provide more information. What Revit version were you using?

**Comment by smangarole** [comment]
![image](https://user-images.githubusercontent.com/992006/75045890-11464e00-5492-11ea-8ada-df4ec56f939d.png)
I tried a simple Excel graph in Dynamo (2.1.0) that comes with Revit 2020. I cannot reproduce the crash. Please update Dynamo if you are experiencing any issues with the older version. Thanks
