### ISSUE TITLE
Dynamo4AS Straight Beam Section orientation issue

### ISSUE THREAD

**Issue by andmailg** [DynamoDS/Dynamo#9977]
## Dynamo version
Dynamo Core 2.1.0.7500
Dynamo AS 2.1.0.1333

## Operating system
Windows 10x64 (1809)

## What did you do? 
Create a Straight Beam using **StraightBeam.ByStartPointEndPoint** Node

## What did you expect to see?
A new beam with a section oriented along the Z Axis

## What did you see instead?
A new beam with a section oriented along the X Axis

Recalculating the script (change beam length for example) creates a beam with the correct vOrientation.
Try a simple script ([test_beam3.zip](https://github.com/DynamoDS/Dynamo/files/3609634/test_beam3.zip)):

- run the script
- check section orientation (incorrect)
- change the beam length
- run the script again
- section orientation changed (correct)

[Here](https://forum.dynamobim.com/t/straight-beam-section-orientation-issue/40535) is my post on forum

**Comment by Amoursol** [comment]
Hello @andmailg - I've passed on a link to your issue to the Advance Steel team who implemented Dynamo to look at 🙌

**Comment by vpavel04** [comment]
This is a bug. I fixed it in the master branch

**Comment by QilongTang** [comment]
@vpavel04 Would you indicate what version of Dynamo 4 AS the users can found the fix and close this issue?

**Comment by vpavel04** [comment]
The fix is for Dynamo 4 AS 2021
@QilongTang I can't close the issue because i do not have rights. Could you please close it?

**Comment by QilongTang** [comment]
@vpavel04 Thank you for the verification! Closing
